### ISSUE TITLE
webextensions.api.i18n.getUILanguage - doesn't work on safari 14

### ISSUE THREAD

**Issue by sxsx1xsxs** [mdn/browser-compat-data#10018]
#### What information was incorrect, unhelpful, or incomplete?
does not work on safari 14. Always return en-US even when set other language for safari in language & region setting of Mac.

I am on safari 14.0.3
#### Did you test this? If so, how?

<details>
<summary>MDN page report details</summary>

* Query: `webextensions.api.i18n.getUILanguage`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/i18n/getUILanguage
* Report started: 2021-04-21T20:59:29.718Z

</details>

**Comment by xeenon** [comment]
Are you seeing this still? Does Safari UI actually reflect the UI languages or are the strings still en-US?

**Comment by queengooborg** [comment]
I'm going to close this issue because there has been no response and there is not enough actionable information.
