### ISSUE TITLE
http.headers.Origin - incorrect BCD for Firefox for Android

### ISSUE THREAD

**Issue by TheRealShakesbear** [mdn/browser-compat-data#10016]
Firefox for Android, versions 58+

#### What information was incorrect, unhelpful, or incomplete?
The documentation incorrectly states that Firefox on Android users must explicitly opt in to enable sending origin header for cross origin requests.

#### What did you expect to see?
The origin header is now sent by default. Please see https://bugzilla.mozilla.org/show_bug.cgi?id=1424076

#### Did you test this? If so, how?
Tested on Firefox on Android 88.1.1 (Build# 2015804891). Origin header is sent by default for cross-origin requests in no-cors mode. It is also sent with both simple and preflighted CORS requests.

<details>
<summary>MDN page report details</summary>

* Query: `http.headers.Origin`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin
* Report started: 2021-04-21T18:27:17.927Z

</details>

**Comment by ptoomey3** [comment]
Just bumping this as someone that found the docs for this on https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin and thought it would be strange for desktop/mobile Firefox to be so far apart on this after this long. Good to hear that isn't the case.

**Comment by queengooborg** [comment]
It seems like #5495 had already taken care of this, I don't know what updates BCD would need.  I'm going to go ahead and close this PR, but please feel free to reopen if you think changes still need to be made.
