### ISSUE TITLE
javascript.operators.logical_or_assignment - Opera and other Chromium-based browsers reported as No Support

### ISSUE THREAD

**Issue by vazitron** [mdn/browser-compat-data#10036]
#### What information was incorrect, unhelpful, or incomplete?

Opera (and Samsung Internet as well) are listed as "No Support".
I believe that Opera and Samsung Internet should be listed as "Full Support", since they're chromium-based.

#### What did you expect to see?

I would expect every recent Chromium-based browser to be marked as "Full Support", **if it's indeed true.**

#### Did you test this? If so, how?
No. Unfortunately, Opera failed to install on my machine :/

Thanks in advance

<details>
<summary>MDN page report details</summary>

* Query: `javascript.operators.logical_or_assignment`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_OR_assignment
* Report started: 2021-04-22T19:39:15.803Z

</details>

**Comment by jculver050** [comment]
Close

**Comment by jculver050** [comment]
Close

**Comment by queengooborg** [comment]
Looks like this has been fixed in #11782!
