### ISSUE TITLE
html.elements.menu - Possible missing support information for Edge

### ISSUE THREAD

**Issue by schalkneethling** [mdn/browser-compat-data#10075]
#### What information was incorrect, unhelpful, or incomplete?

Looking at https://caniuse.com/mdn-html_elements_menu it would seem that `menu` is supported in Edge as well? Interestingly the panel states the the information is provided by BCD but the table on MDN Web Docs, does not show the same level of support:

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/menu#browser_compatibility

#### What did you expect to see?

That the `menu` element is supported in Edge as well

#### Did you test this? If so, how?

This only provides additional semantic meaning over a plain `ul` element so, visually it even renders correctly in Chrome for example.

<details>
<summary>MDN page report details</summary>

* Query: `html.elements.menu`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/menu
* Report started: 2021-04-25T10:00:43.753Z

</details>

**Comment by vinyldarkscratch** [comment]
It looks like the linked CanIUse feature is actually coming from our own data, so it seems like there might be some sort of rendering issue.  We'll have to look into that more with CanIUse and see what's going on there.

**Comment by queengooborg** [comment]
It appears this has been since fixed!
