### ISSUE TITLE
html.elements.fieldset - Issue rendering <section> inside <fieldset> in Safari

### ISSUE THREAD

**Issue by aprishchepov** [mdn/browser-compat-data#10097]
Browser name
Safari
Browser version
14.0.3
Operating System
Mac OS 10.15.6

Rendering <section> tag inside <fieldset> has a bug in Safari:
![Untitled](https://user-images.githubusercontent.com/629050/116141980-5de57480-a6a7-11eb-94ef-59a0058afae6.png)

I don't see any restrictions for such case and it works in all other browsers we tested in.

<details>
<summary>MDN page report details</summary>

* Query: `html.elements.fieldset`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/fieldset
* Report started: 2021-04-26T19:46:59.220Z

</details>

**Comment by queengooborg** [comment]
Sorry for how long it took to respond to this!

I gave a quick try at placing a section element within a fieldset, but I haven't experienced any issues in Chrome or Safari.  Either this was a bug in that particular Safari version that's now fixed, or there's a development issue.  Would you like to share the code for testing, assuming this is still an issue?

**Comment by queengooborg** [comment]
I'm going to close this because there hasn't been any response and there isn't enough actionable information to be able to proceed.  Feel free to reopen with the requested information if this is still an issue.
