### ISSUE TITLE
api.Worker - Safari 14.0.3 (macOS) seems fine with ESM Web Worker

### ISSUE THREAD

**Issue by akauppi** [mdn/browser-compat-data#10119]
#### What information was incorrect, unhelpful, or incomplete?

"Support for ECMAScript modules" for Safari is "no".

It looks to me like Safari 14.0.3 does support them. Unfortunately don't know since when.

#### Did you test this? If so, how?

Have a project with web worker. Default build is ESM and I was expecting it to fail on Safari. At least the worked was loaded and reported receiving messages.

<details>
<summary>MDN page report details</summary>

* Query: `api.Worker`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Worker
* Report started: 2021-04-27T14:22:25.819Z

</details>

**Comment by queengooborg** [comment]
Looks like the data updates were taken care of in #10749, then #10898!
