### ISSUE TITLE
javascript.operators.optional_chaining - don't work in NodeJS 14.16.1

### ISSUE THREAD

**Issue by FilippeMafra** [mdn/browser-compat-data#10118]
Optional Chaining don't work in NodeJS 14.16.1.
Error message: "SyntaxError: Unexpected token '.'"
I tested in "Ubuntu 18.04.3 (LTS) x64", with node 14.16.1 (nvm installation).

<details>
<summary>MDN page report details</summary>

* Query: `javascript.operators.optional_chaining`
* MDN URL: https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Operators/Optional_chaining
* Report started: 2021-04-27T14:10:39.884Z

</details>

**Comment by jculver050** [comment]
clos

**Comment by jculver050** [comment]
Close

**Comment by jculver050** [comment]
Close
