### ISSUE TITLE
Normalize spec URLs from DOM spec

### ISSUE THREAD

**Issue by sideshowbarker** [mdn/browser-compat-data#10136]
Similar to https://github.com/mdn/browser-compat-data/issues/10090, while creating patches for spec URLs, it became clear that the URLs scraped from MDN which cited the DOM spec had inconsistencies. So I spent some time “normalizing” those, and will submit a series of patches for them.

I’m opening this issue to give a summary of the details, to avoid repeating those in the commit messages for each patch.

1. Some URLs cited a spec section not written for developers but instead written for browser implementors; for example, https://dom.spec.whatwg.org/#dom-element-slot — which has a corresponding section at https://dom.spec.whatwg.org/#ref-for-dom-element-slot① that’s written specifically for developers. So the pattern for those changes is that `ref-for-` got prefixed to the URL, and a ① got appended.

4. Some URLs cited a target within a WebIDL block in cases where citing a section heading would provide a better reader experience; e.g., https://dom.spec.whatwg.org/#abstractrange ➡ https://dom.spec.whatwg.org/#interface-abstractrange.

5. Some URLs were changed in ways not falling into the above categories but instead are just  “miscellaneous cleanup”.

As with https://github.com/mdn/browser-compat-data/issues/10090, the lessons learned from this will be incorporated into the additions to the guidelines planned in https://github.com/mdn/browser-compat-data/issues/10106.

**Comment by queengooborg** [comment]
Hey @sideshowbarker, do you know if this is still an issue, or has it pretty much been all resolved at this point?

**Comment by sideshowbarker** [comment]
> Hey @sideshowbarker, do you know if this is still an issue, or has it pretty much been all resolved at this point?

All resolved
