### ISSUE TITLE
css.properties.gap.flex_context - Safari 14.1 (MacOs) and Safari 14.5 (IoS) now have support 

### ISSUE THREAD

**Issue by MattyBalaam** [mdn/browser-compat-data#10153]
Safari 14.1 (MacOs) and Safari 14.5 (iOS) now have support for gap in flex layout.

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.gap.flex_context`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/gap
* Report started: 2021-04-28T14:13:07.588Z

</details>

**Comment by json-derulo** [comment]
Will be fixed with #10129

**Comment by vinyldarkscratch** [comment]
This has now been resolved by #10129!  The MDN documentation should update soon to reflect this data.
