### ISSUE TITLE
html.elements.textarea - The wrap attribute status doesn't reflect wrapping behavior

### ISSUE THREAD

**Issue by andreubotella** [mdn/browser-compat-data#10164]
#### What information was incorrect, unhelpful, or incomplete?
The MDN compat data lists `<textarea>`'s `wrap` attribute as being supported in all browsers, but the mdn-bcd-collector seems to test it by the presence of the `wrap` field on an `HTMLTextAreaElement` object, rather than by whether the textarea's value wraps when submitted.

#### What did you expect to see?
Firefox doesn't implement the wrapping behavior, so it shouldn't be listed as supporting the `wrap` attribute.

#### Did you test this? If so, how?
I run [this WPT test](https://wpt.fyi/results/html/semantics/forms/the-textarea-element/wrap-enumerated-ascii-case-insensitive.html?label=experimental&label=master&aligned) on desktop Firefox Nightly (version 90) and desktop Firefox version 88. Note that although the test is for the case-sensitivity of the `wrap` attribute, Firefox fails even the basic all-lowercase test.

Also note that WebKit browsers (tested on GNOME Web, since I don't have access to Safari) fail the tests but they do implement the wrapping behavior (perhaps differently to what's spec'd?); changing the test to have `cols="6"` makes it work.

#### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?
WPT test (wpt.live): https://wpt.fyi/results/html/semantics/forms/the-textarea-element/wrap-enumerated-ascii-case-insensitive.html?label=experimental&label=master&aligned
WPT test (WPT github): https://github.com/web-platform-tests/wpt/blob/master/html/semantics/forms/the-textarea-element/wrap-enumerated-ascii-case-insensitive.html
Textarea wrapping transformation in the HTML spec: https://html.spec.whatwg.org/multipage/form-elements.html#textarea-wrapping-transformation

**Comment by sideshowbarker** [comment]
heads—up @vinyldarkscratch @foolip (about the mdn-bcd-collector piece of this)

**Comment by foolip** [comment]
OK, so this is a case of supporting the IDL attribute reflecting the content attribute, but the behavior for the content attribute not being implemented.

This data was added in https://github.com/mdn/browser-compat-data/pull/7601 by manually copying the data, mdn-bcd-collector doesn't itself make the assumption that content attributes and IDL attributes match. But I as a reviewer did.

Notes will be needed for both entries.
