### ISSUE TITLE
css.properties.scroll-margin - Safari compatibilty has improved

### ISSUE THREAD

**Issue by dns2utf8** [mdn/browser-compat-data#10160]
#### What information was incorrect, unhelpful, or incomplete?
Apple fixed the name of the CSS property in 2020.

#### What did you expect to see?

From version 14 on it is correct.

#### Did you test this? If so, how?

https://bugs.webkit.org/show_bug.cgi?id=189265

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.scroll-margin`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-margin
* Report started: 2021-04-28T19:15:11.079Z

</details>

**Comment by dns2utf8** [comment]
I forgot, a friend of mine tested it on Safari and it worked.

**Comment by vinyldarkscratch** [comment]
This has now been resolved by #10129! The MDN documentation should update soon to reflect this data.
