### ISSUE TITLE
Issue with "HTMLAnchorElement.toString()": Wrong behavior in IE11

### ISSUE THREAD

**Issue by LiuYuHui** [mdn/browser-compat-data#10165]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLAnchorElement/toString

#### What information was incorrect, unhelpful, or incomplete?
In browser compatibility table of MDN, the `toString` function don't supported by IE11, but in my test, the `toString` function works in IE11.
#### What did you expect to see?
Here is the browser compatibe table of MDN
![image](https://user-images.githubusercontent.com/13926137/117268966-6d747280-ae8a-11eb-9cd1-2f38a5bc8c91.png)
Here is the test in browserlab of mouselog.
![image](https://user-images.githubusercontent.com/13926137/117268666-1ff80580-ae8a-11eb-954e-d679b9703c6f.png)
Here is the result in IE11
![image](https://user-images.githubusercontent.com/13926137/117623256-1e8a4e00-b1a6-11eb-9765-e07ab75675d2.png)

#### Did you test this? If so, how?
```js
let test = document.createElement("a");
test.href="/en-US/docs/HTMLAnchorElement";
test.toString();
```

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/htmlanchorelement/tostring`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLAnchorElement/toString
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmlanchorelement/tostring/index.html
* Last commit: https://github.com/mdn/content/commit/31cd850cae3803c72203218dd89003f29b4b9612
* Document last modified: 2021-02-11T17:10:24.000Z

</details>

**Comment by queengooborg** [comment]
Thanks for reporting the issue!  I had corrected this data in #13516 with basically the same test, thanks for confirming!
