### ISSUE TITLE
html.elements.input.input-date - Safari 14.1 now supports input type date

### ISSUE THREAD

**Issue by yousifalraheem** [mdn/browser-compat-data#10174]
#### What information was incorrect, unhelpful, or incomplete?

As of Safari v14, the Input type date is supported. The table shows that it is not.
<img width="1037" alt="Screenshot 2021-04-30 at 8 24 35 AM" src="https://user-images.githubusercontent.com/10633734/116656757-82826a80-a98d-11eb-8171-ca6ba36ea879.png">

Here is what it looks like in Safari
<img width="1023" alt="Screenshot 2021-04-30 at 8 30 06 AM" src="https://user-images.githubusercontent.com/10633734/116657214-59aea500-a98e-11eb-9ff8-8131a664a957.png">

#### What did you expect to see?
Showing that Safari supports input type date

#### Did you test this? If so, how?
Yes, with Safari version 14.1 on a MacBook Pro

#### Related issues
Same goes for
- [datetime-local](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local)
- [time](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time) No, picker, but native support and masking

<details>
<summary>MDN page report details</summary>

* Query: `html.elements.input.input-date`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date
* Report started: 2021-04-30T06:21:35.289Z

</details>

**Comment by json-derulo** [comment]
This has already been added with #10129. A new package was released, the updates should soon arrive on the MDN Docs pages.

**Comment by vinyldarkscratch** [comment]
Can confirm that #10129 fixes this!
