### ISSUE TITLE
css.properties.translate - mark as available on safari 14.1

### ISSUE THREAD

**Issue by Ayc0** [mdn/browser-compat-data#10172]
#### What information was incorrect, unhelpful, or incomplete?

This is now available on safari 14.1

#### What did you expect to see?

A little green card saying "14.1" like the one displayed for firefox

<img width="1092" alt="image" src="https://user-images.githubusercontent.com/22725671/116602370-ea07ce00-a92b-11eb-9935-cd038b573d4f.png">

#### Did you test this? If so, how?

The provided example is working on my safari:

https://user-images.githubusercontent.com/22725671/116602637-466aed80-a92c-11eb-9454-4843d948d7ab.mov

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.translate`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/translate
* Report started: 2021-04-29T18:40:01.032Z

</details>

**Comment by json-derulo** [comment]
This has already been added with #10129. A new package was released, the updates should soon arrive on the MDN Docs pages.
