### ISSUE TITLE
Fixing up doc vs BCD deprecation

### ISSUE THREAD

**Issue by hamishwillee** [mdn/browser-compat-data#10224]
I've been through MDN and BCD attempting to match up deprecation info on web apis (theory being that ideally they should ideally match completely, but certainly not differ. MDN now matches BCD, where BCD has an entry.

- The first section below are cases where BCD has a different entry/inconsistency. I presume we will want to fix these. 
- The second section is cases where there is no BCD entry. Wondering whether you think this is worth documenting in BCD to make everything sync up.

FYI @ddbeck 

### Marked as deprecated in MDN but not on BCD

`Document.domain` - in discussion #10348
`SVGStylable` - under investigation on MDN https://github.com/mdn/content/pull/4782
`SVGTransformable` - #10354

#10356 - fixes
`Window: vrdisplayblur event` - marked as not deprecated (`onvrdisplayblur` marked as deprecated).
`Window: vrdisplayconnect event`  - marked as not deprecated (`onvrdisplayconnect ` marked as deprecated).
`Window: vrdisplayactivate event` -  marked as not deprecated (`onvrdisplayactivate` marked as deprecated).
`Window: vrdisplaydeactivate event`-  marked as not deprecated (`on` version marked as deprecated).
`Window: vrdisplaydisconnect event` -  marked as not deprecated (`on` version marked as deprecated).
`Window: vrdisplayfocus event` - marked as not deprecated (`on` version marked as deprecated).
`Window: vrdisplaypointerrestricted` event - marked as not deprecated (`on` version marked as deprecated).
`Window: vrdisplaypointerunrestricted` event - marked as not deprecated (`on` version marked as deprecated).
`Window: vrdisplaypresentchange event` - marked as not deprecated (`on` version marked as deprecated).
`Window: appinstalled event` - Not documented. `onappinstalled` does exist and is marked as deprecated

`WorkerGlobalScope.close()` - Not documented. `onclose` does exist and is marked as deprecated - see #10416

### Deprecated subfeatures where BCD has no record

UIEvent.cancelBubble 
- there is Event.cancelBubble and this has note that says is only supported in UIEvent on Firefox
- This is non-spec and I think perhaps should be deleted everywhere. - https://github.com/mdn/content/issues/4859

Still to look at:
- [CanvasRenderingContext2D.addHitRegion()](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/addHitRegion) - Entry for CanvasRenderingContext2D  only
- [CanvasRenderingContext2D.clearHitRegions()](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/clearHitRegions) - Entry for CanvasRenderingContext2D only
- [CanvasRenderingContext2D.removeHitRegion()](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/removeHitRegion) - Entry for CanvasRenderingContext2D only
- [Document.rootElement](https://developer.mozilla.org/en-US/docs/Web/API/Document/rootElement)  - entry for Document only
- [DOMLocator](https://developer.mozilla.org/en-US/docs/Web/API/DOMLocator) - no entry
- [DOMObject](https://developer.mozilla.org/en-US/docs/Web/API/DOMObject) - no entry
- [DOMUserData](https://developer.mozilla.org/en-US/docs/Web/API/DOMUserData) - no entry
- [ElementTraversal](https://developer.mozilla.org/en-US/docs/Web/API/ElementTraversal) - no entry
- [File.fileName](https://developer.mozilla.org/en-US/docs/Web/API/File.fileName) - entry for File but not for FileName. There is "File.name"
- [File.getAsBinary()](https://developer.mozilla.org/en-US/docs/Web/API/File.getAsBinary) entry for File only
- [File.getAsText()](https://developer.mozilla.org/en-US/docs/Web/API/File.getAsText) entry for File only
- [KeyboardEvent.initKeyboardEvent()](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent.initKeyboardEvent) - entry for KeyboardEvent only
- [KeyboardEvent.initKeyEvent()](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent.initKeyEvent) - entry for KeyboardEvent only
- [LocalFileSystemSync.requestFileSystemSync()](https://developer.mozilla.org/en-US/docs/Web/API/LocalFileSystemSync/requestFileSystemSync) - no entry
- [MutationEvent](https://developer.mozilla.org/en-US/docs/Web/API/MutationEvent) - no entry
- [Navigator.msSaveBlob](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/msSaveBlob) - no entry
- [Navigator.msSaveOrOpenBlob](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/msSaveOrOpenBlob) - no entry
- [RTCNetworkType](https://developer.mozilla.org/en-US/docs/Web/API/RTCNetworkType) - no entry
- [Selection.selectionLanguageChange()](https://developer.mozilla.org/en-US/docs/Web/API/Selection.selectionLanguageChange) - entry for Selection only.
- [SpeechRecognitionError](https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognitionError) - no entry (though there is SpeechRecognitionErrorEvent)
- [SVGEvent](https://developer.mozilla.org/en-US/docs/Web/API/SVGEvent) - no entry
- [TypeInfo](https://developer.mozilla.org/en-US/docs/Web/API/TypeInfo)- no entry
- [Window.applicationCache](https://developer.mozilla.org/en-US/docs/Web/API/Window.applicationCache)  - note, the MDN docs for SharedWorkerGlobalScope.applicationCache  links here so may be OK?
- [Window.back()](https://developer.mozilla.org/en-US/docs/Web/API/Window.back) - entry for Window only
- [Window.defaultStatus](https://developer.mozilla.org/en-US/docs/Web/API/Window.defaultStatus) - entry for Window only
- [Window.directories](https://developer.mozilla.org/en-US/docs/Web/API/Window.directories) - entry for Window only
- [Window.forward()](https://developer.mozilla.org/en-US/docs/Web/API/Window.forward) - entry for Window only
- [Window.ondragdrop](https://developer.mozilla.org/en-US/docs/Web/API/Window.ondragdrop) - entry for Window only
- [Window.onmozbeforepaint](https://developer.mozilla.org/en-US/docs/Web/API/Window.onmozbeforepaint) - entry for Window only
- [XPathException](https://developer.mozilla.org/en-US/docs/Web/API/XPathException) - no entry
- [getCandidateWindowClientRect](https://developer.mozilla.org/en-US/docs/Web/API/getCandidateWindowClientRect) - no entry

**Comment by ddbeck** [comment]
Thanks for opening this, @hamishwillee. It's partly related to https://github.com/mdn/browser-compat-data/issues/7709.

You're right that, for the APIs marked as deprecated in MDN but not on BCD, we ought to fix those. 👍 I'd welcome PRs to correct them. I'd prefer the PRs be grouped by topic. The ones where closely related features are already deprecated seem really straight forward to me (e.g., if one of `<event>_event`, `on<event>`, and, if applicable, the API for the event isn't like the others, then let's make them consistent with each other).

For the deprecated features without data in BCD, I suspect that many of them are not implemented at all. I don't think we should labor too hard over these. My recommendation for that would be to put the features into groups:

1. At least one of Chrome, Firefox, or Safari supports the feature (i.e., the interface is exposed or a property is in the prototype—we don't need to find out of it actually works). @ me if you want pointers on how to do this.
2. The feature is in a contemporary specification. The MDN pages themselves ought to lead in the direction of a relevant spec.
3. Everything else.

Group 1 we should fix, groups 2 and 3 we should do a cursory check to find out if the features were ever supported (and, if in the last two years, add 'em). For groups 2 and 3, we shouldn't spend more than a couple of minutes searching the Chromium, Gecko, and WebKit mirror repos before moving on.

**Comment by hamishwillee** [comment]
Thanks @ddbeck . Kind of what I suspected. I'll start on these then.

**Comment by OnkarRuikar** [comment]
We've started updating BCD info in `mdn/content` in [this PR series](https://github.com/mdn/content/pull/19185).

***
Regarding deprecated features in the doc but not deprecated in BCD, I've [updated remaining such 23 cases](https://github.com/mdn/browser-compat-data/pulls?q=is%3Apr+author%3Aonkarruikar+sort%3Aupdated-desc+is%3Aclosed+deprecated) in BCD.
If you still find any case then let me know.

All the cases mentioned in the opening post of this issue either
- got updated in BCD
- the documents got deleted
- there are no entries for the deprecated features in BCD

I think we can close this issue.

**Comment by hamishwillee** [comment]
@OnkarRuikar - I agree. Also, thanks for tidying this up. Would be good if we could automate keeping them in sync at some point.

**Comment by OnkarRuikar** [comment]
> Would be good if we could automate keeping them in sync at some point.

After we complete the PR series, I'll sync BCD as part of the [Daily markdownlint](https://github.com/mdn/content/pull/19211/files) PRs.
