### ISSUE TITLE
api.SpeechSynthesisUtterance.boundary_event - SpeechSynthesisUtterance.onboundary  does not work in Chrome

### ISSUE THREAD

**Issue by danfleser** [mdn/browser-compat-data#10303]
#### What information was incorrect, unhelpful, or incomplete?
Chrome Version 90.0.4430.93 (Official Build) (64-bit)
#### What did you expect to see?
I expect to see logs into browser console.
#### Did you test this? If so, how?
I run this code into the console, and should log each work, but it does not log anything. In FIrefox and Edge works.

```
var synth = window.speechSynthesis;
var voices = synth.getVoices();
var utterThis = new SpeechSynthesisUtterance("no code is printed to the console");
utterThis.voice = voices[19];
utterThis.onboundary = function(event) {
  console.log(event.name + ' boundary reached after ' + event.elapsedTime + ' milliseconds.');
}
synth.speak(utterThis);
```

<details>
<summary>MDN page report details</summary>

* Query: `api.SpeechSynthesisUtterance.boundary_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesisUtterance/boundary_event
* Report started: 2021-05-05T22:04:06.741Z

</details>

**Comment by vinyldarkscratch** [comment]
Is this on Chrome Desktop or Chrome Android?  If it's Chrome Android, then this is a known bug, which we've got linked in our tables.

**Comment by danfleser** [comment]
It is Chrome Desktop.

**Comment by vinyldarkscratch** [comment]
I was reading the linked bug for the Chrome Android data, and I noticed someone was able to [reproduce the same issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1122143#c8) you're describing (Google voice on Chrome Desktop).  We'll copy the note over.
