### ISSUE TITLE
api.MediaSource.isTypeSupported - <PUT TITLE HERE>

### ISSUE THREAD

**Issue by sq3612336** [mdn/browser-compat-data#10305]
#### What information was incorrect, unhelpful, or incomplete?
we i inside the iqiyi video     https://www.iqiyi.com/v_1nkb54zlkpc.html?vfrm=pcw_home&vfrmblk=D&vfrmrst=712211_focus_A_image3
it show following err:
当前浏览器不支持播放，建议使用以下浏览器
下列软件均已通过安全验证，您可放心安装

from the code , i found t.isTypeSupported('video/mp4;codecs="avc1.42E01E"') return false

#### What did you expect to see?
what deb should i install to support this MIME:video/mp4;codecs="avc1.42E01E  && 'audio/mp4;codecs="mp4a.40.2"'
or  how to debug the issue "is my ubuntu system support those MIME"

#### Did you test this? If so, how?
inside this website with chrome : https://www.iqiyi.com/v_1nkb54zlkpc.html?vfrm=pcw_home&vfrmblk=D&vfrmrst=712211_focus_A_image3

<details>
<summary>MDN page report details</summary>

* Query: `api.MediaSource.isTypeSupported`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MediaSource/isTypeSupported
* Report started: 2021-05-06T02:27:13.726Z

</details>

**Comment by sq3612336** [comment]
my chrome version is 90.0.4395.0

**Comment by vinyldarkscratch** [comment]
This repository isn't a help forum, but rather for historic data of what browsers support what web features.  I'd recommend a dedicated help forum like Ask Ubuntu (StackExchange) for your issue.

Closing due to irrelevance.
