### ISSUE TITLE
api.Response - both status and statusText work in Chrome and Firefox on Android

### ISSUE THREAD

**Issue by varqox** [mdn/browser-compat-data#10345]
#### What information was incorrect, unhelpful, or incomplete?

Docs say Response.status and Response.statusText are unsupported in Chrome and Firefox on Android, but I tested it today and they appear to work the same as on desktop

#### Did you test this? If so, how?
I tested `fetch(url).then(r => alert(r.ok + '; ' + r.status + '; ' + r.statusText))` and it showed the same message on Android and desktop.

<details>
<summary>MDN page report details</summary>

* Query: `api.Response`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Response
* Report started: 2021-05-06T16:49:45.446Z

</details>

**Comment by queengooborg** [comment]
Looks like this was fixed in #12579!
