### ISSUE TITLE
SpeechRecognition API is not available in SafariViewController and web apps added to Home Screen

### ISSUE THREAD

**Issue by mishushakov** [mdn/browser-compat-data#10376]
According to this bug, https://bugs.webkit.org/show_bug.cgi?id=225298#c3

> SpeechRecognition API is not available in SafariViewController and web apps added to Home Screen for now
> There are some implementation details we need to figure out before we can enable it.

please update the page to reflect that

thanks

**Comment by vinyldarkscratch** [comment]
Closing due to off-GitHub discussion confirming that we won't be tracking differences in Safari iOS/iPadOS vs. developer libraries.
