### ISSUE TITLE
css.selectors.after - Incorrect browser support

### ISSUE THREAD

**Issue by MarcusOtter** [mdn/browser-compat-data#10408]
#### What information was incorrect, unhelpful, or incomplete?
https://developer.mozilla.org/en-US/docs/Web/CSS/::after
The browser support shows that the `::after`-selector is not supported in Internet Explorer nor Safari.

![image](https://user-images.githubusercontent.com/35617441/117554614-1a044f00-b059-11eb-8e63-79a2abddebd1.png)

#### What did you expect to see?
CanIUse.com says it's been supported in every browser pretty much always:
https://caniuse.com/css-gencontent
![image](https://user-images.githubusercontent.com/35617441/117554639-43bd7600-b059-11eb-8d55-7ec4eac48b9c.png)

I believe the mistake is that it's using support data for whether or not _animations_ are supported on the pseudo element, which is a different thing. This about matches the data from CanIUse.com as well:
https://caniuse.com/mdn-css_selectors_after_animation_and_transition_support
![image](https://user-images.githubusercontent.com/35617441/117554672-6fd8f700-b059-11eb-95be-cb29afe088ac.png)

#### Did you test this? If so, how?
I did not test this to verify, but seeing the `::after` selector used extensively in different articles and answers all over the internet, I question the browser compatibility table shown since I don't think I've ever seen anyone mention that it wasn't supported on IE nor Safari.

<details>
<summary>MDN page report details</summary>

* Query: `css.selectors.after`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/::after
* Report started: 2021-05-08T21:51:22.985Z

</details>

**Comment by vinyldarkscratch** [comment]
Your screenshot is showing that the tables are indicating there is support.  There's two rows: one for the selector itself, and the other for the animation and transition support (which is indeed not supported).

**Comment by MarcusOtter** [comment]
🤦 I need coffee, sorry

**Comment by vinyldarkscratch** [comment]
Haha, you're fine, no worries!  Happens to the best of us.  😝
