### ISSUE TITLE
api.Transferable - Chrome 17+

### ISSUE THREAD

**Issue by styfle** [mdn/browser-compat-data#10432]
#### What information was incorrect, unhelpful, or incomplete?

I think it is incomplete.

#### What did you expect to see?

I expect to see Transferable added at Chrome 17 like in this article https://developers.google.com/web/updates/2011/12/Transferable-Objects-Lightning-Fast

#### Did you test this? If so, how?

No

<details>
<summary>MDN page report details</summary>

* Query: `api.Transferable`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Transferable
* Report started: 2021-05-10T21:57:22.708Z

</details>

**Comment by nutza978** [comment]
@nutza978

**Comment by nutza978** [comment]
> #### What information was incorrect, unhelpful, or incomplete?
> I think it is incomplete.
> 
> #### What did you expect to see?
> I expect to see Transferable added at Chrome 17 like in this article https://developers.google.com/web/updates/2011/12/Transferable-Objects-Lightning-Fast
> 
> #### Did you test this? If so, how?
> No
> 
> MDN page report details

running

**Comment by queengooborg** [comment]
We've removed this interface in #12376, as it was an abstract interface turned into a WebIDL keyword.
