### ISSUE TITLE
Expose mixin data as-is

### ISSUE THREAD

**Issue by saschanaz** [mdn/browser-compat-data#10447]
https://github.com/saschanaz/types-web/pull/10 wants to utilize mixin data but those are currently merged to base interfaces and thus needs to be unmerged first. Can those data be exposed so that the unmerge step can be skipped?

**Comment by ddbeck** [comment]
I don't follow, @saschanaz. Can you give an example of the sort of data you're hoping to see?

**Comment by saschanaz** [comment]
For example I want the members of `ParentNode` are supported at least at one interface. Currently I have to scan every interface that includes `ParentNode` and extract each compat data from the members of the interfaces (thus "unmerge"). But this step shouldn't be needed since the data already exists as `_mixin/ParentNode__*.json`.

**Comment by Elchi3** [comment]
BCD doesn't mark mixins as such necessarily, see "1. For smaller mixins" in https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines.md#mixins. That said, BCD doesn't really know about mixins per se. The api/_mixins folder is just meant to be an authoring convenience for large mixins.

**Comment by saschanaz** [comment]
Yeah... I found it when working on this further. I'll probably just write a wrapper library for this, unless BCD has a better plan. Thanks!
