### ISSUE TITLE
css.selectors.is - Support not updated to newer browser versions which DO have support for this

### ISSUE THREAD

**Issue by jjspace** [mdn/browser-compat-data#10461]
#### What information was incorrect, unhelpful, or incomplete?

This support data doesn't seem to have been updated for a couple months. For example it shows that this selector is not supported in Edge. This is true for the specified version 79 but looking at [caniuse's support](https://caniuse.com/css-matches-pseudo) it shows that starting in Edge version 88 it _was_ fully supported.

<details>
<summary>MDN page report details</summary>

* Query: `css.selectors.is`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/:is
* Report started: 2021-05-12T19:30:04.352Z

</details>

**Comment by queengooborg** [comment]
This had been fixed in #10163!
