### ISSUE TITLE
api.HTMLElement.pointerdown_event - Missing Safari and iOS Safari support

### ISSUE THREAD

**Issue by francescostella** [mdn/browser-compat-data#10486]
#### What information was incorrect, unhelpful, or incomplete?
The support for Pointer Events is marked as not supported for Safari and iOS Safari.

#### What did you expect to see?
Pointer Events should be listed in the Browser Compatibility chart as supported for both **Safari(14.1)** and **iOS Safari(14.5)**

#### Did you test this? If so, how?
Source: https://caniuse.com/pointer

<details>
<summary>MDN page report details</summary>

* Query: `api.HTMLElement.pointerdown_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/pointerdown_event
* Report started: 2021-05-14T08:28:02.328Z

</details>

**Comment by ddbeck** [comment]
Thanks for reporting this, @francescostella. This is also covered by https://github.com/mdn/browser-compat-data/issues/8709. A fix is in https://github.com/mdn/browser-compat-data/pull/9596, which is awaiting review. Since this issue is a duplicate, I'm going to close this one. Thanks again!
