### ISSUE TITLE
api.ImageCapture - IOS CHROME

### ISSUE THREAD

**Issue by aaronpaultolentino** [mdn/browser-compat-data#10481]
Is there a support for IOS Chrome? There's no information whether it is supported or not, unlike firefox which it's explicitly show that it's not supported yet.

<details>
<summary>MDN page report details</summary>

* Query: `api.ImageCapture`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/ImageCapture
* Report started: 2021-05-14T03:01:14.029Z
* OS: IOS14.4
* Browser: Chrome87.0

</details>

**Comment by vinyldarkscratch** [comment]
All browsers on iOS are actually just Safari due to OS restrictions, so there is no difference in compatibility between Safari and Chrome on iOS or iPadOS.  The compatibility tables state that there is no Safari support altogether for this API.
