### ISSUE TITLE
css.properties.offset-anchor - not working in Chrome

### ISSUE THREAD

**Issue by malteschmitz** [mdn/browser-compat-data#10495]
#### What information was incorrect, unhelpful, or incomplete?

The Browser compatibility table says `offset-anchor` works in Chrome since version 79, but in Chrome 90.0.4430.212 on macOS it is not working.

#### Did you test this? If so, how?

The example on https://developer.mozilla.org/en-US/docs/Web/CSS/offset-anchor is not working in Chrome 90.0.4430.212. It works fine in browsers supporting `offset-anchor` such as Firefox.

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.offset-anchor`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/offset-anchor
* Report started: 2021-05-15T20:06:31.738Z

</details>

**Comment by queengooborg** [comment]
Looks like this was fixed in #15281!
