### ISSUE TITLE
css.properties.position - fixed element will be absolute on Firefox when root element set filter property

### ISSUE THREAD

**Issue by Germxu** [mdn/browser-compat-data#10510]
#### What information was incorrect, unhelpful, or incomplete?
Latest version Firefox: 
When I set filter properties on the root element html，not body or other sub nodes , there will be some different between Firefox and Chrome: Chrome still works on fixed but Firefox will be absolute

And the bug alse seen on Bugzilla https://bugzilla.mozilla.org/show_bug.cgi?id=1423746

#### What did you expect to see?
Fixed element works as fixed, like Chrome or Safari

#### Did you test this? If so, how?

Look on https://codepen.io/germxu/pen/eYvdOrj

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.position`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/position
* Report started: 2021-05-17T15:21:04.879Z

</details>

**Comment by queengooborg** [comment]
Looks like the bug has been resolved as fixed now!
