### ISSUE TITLE
api.WindowOrWorkerGlobalScope.caches - window.caches is available on Safari

### ISSUE THREAD

**Issue by smeng9** [mdn/browser-compat-data#10513]
A datapoint on Safari 13.1.2 on macOS High Sierra 10.13.6 shows window.caches is available when accessing HTTPS websites.

#### What information was incorrect, unhelpful, or incomplete?
Browser compatibility for WindowOrWorkerGlobalScope/caches under Safari is incorrect

#### What did you expect to see?
The information should be corrected. The support can probably be dated back to Safari 11.1

#### Did you test this? If so, how?
Tested when opening the console and typed window.caches

<details>
<summary>MDN page report details</summary>

* Query: `api.WindowOrWorkerGlobalScope.caches`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/caches
* Report started: 2021-05-17T22:14:21.648Z

</details>

**Comment by queengooborg** [comment]
Looks like we have fixed this before moving to the new `_globals` format!
