### ISSUE TITLE
api.HTMLElement.click - Not working in Safari iOS

### ISSUE THREAD

**Issue by DmPrkp** [mdn/browser-compat-data#10518]
#### What information was incorrect, unhelpful, or incomplete?

.click() does not work in Safari 

#### What did you expect to see?

i'll expect to see 
https://caniuse.com/?search=click

#### Did you test this? If so, how?

I test it; 
following code does not work in Iphone

` 
> const link = document.createElement('a');
> > link.setAttribute('href', url);
> > link.setAttribute('target', '_blank');
> > link.click();
> > link.remove();
`

<details>
<summary>MDN page report details</summary>

* Query: `api.HTMLElement.click`
* MDN URL: https://developer.mozilla.org/ru/docs/Web/API/HTMLElement/click
* Report started: 2021-05-18T12:49:24.655Z

</details>

**Comment by vinyldarkscratch** [comment]
Your test code is working fine for me, so there must be something else going on there.  Closing since the click function is supported in Safari iOS.
