### ISSUE TITLE
Remove some Android WebView versions with matching engine versions?

### ISSUE THREAD

**Issue by vinyldarkscratch** [mdn/browser-compat-data#10524]
As I've found in #10523, both Android WebView 1.1 and 1.6 have the same WebKit versions as 1.0 and 1.5 respectively.  I've run the traverse script and have found that there is nothing set to either of these two WebView versions as it is.  I think we can safely remove both of these from BCD.

**Comment by vinyldarkscratch** [comment]
While we're at it, there's a few more that we should probably remove:

- 2.3 - same engine version as 2.2, though seems to be in use
- 4.1 - same engine version as 4.0, though seems to also be in use
- 4.2 - same as 4.0, and not used anywhere

**Comment by Elchi3** [comment]
I agree to do this! :) I remember I requested vendor feedback when I originally added webview data but there wasn't much info available so we went with what seemed best at the time. (https://github.com/mdn/browser-compat-data/pull/2690)

**Comment by vinyldarkscratch** [comment]
Thanks for merging all the PRs, @Elchi3!  This issue can now be closed!
