### ISSUE TITLE
api.Blob.type - type jpeg is till not work in safari iphone?

### ISSUE THREAD

**Issue by ilhamdoanggg** [mdn/browser-compat-data#10557]
#### What information was incorrect, unhelpful, or incomplete?
```new File([blob], "imageName.jpeg", { type: "image/jpeg", lastModified: Date.now() });```
#### Did you test this? If so, how?

<details>
<summary>MDN page report details</summary>

* Query: `api.Blob.type`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Blob/type
* Report started: 2021-05-21T02:45:51.750Z

</details>

**Comment by vinyldarkscratch** [comment]
We need more information regarding what exactly is happening.  Are there any console logs when executing your code?

**Comment by ilhamdoanggg** [comment]
is this still unsupported for safari on ios ?
![image](https://user-images.githubusercontent.com/9218660/119140693-aad22600-ba6e-11eb-9ac3-f54ed5ba11b2.png)

**Comment by vinyldarkscratch** [comment]
As our documentation states, getting a blob's type via `blob.type` is unsupported (although your code snippet does not seem to use it anyways).  That doesn't mean that types such as JPEG are unsupported.

**Comment by vinyldarkscratch** [comment]
Closing since there's been no actionable information on this issue for a few months.  Feel free to reply to this issue if you're still having problems, and I'll attempt to resolve them or reopen this issue!
