### ISSUE TITLE
Set-cookie Max-Age is not supported in IE11

### ISSUE THREAD

**Issue by martindzejky** [mdn/browser-compat-data#10569]
Hi! 👋 

`Max-Age` in the HTTP header `Set-Cookie` is not supported in IE11. I've unfortunately learned this the hard way. My backend server is responding with an HTTP header `set-cookie: name=value; Max-Age=20; Secure; SameSite=None` so I expected the cookie to expire in 20 seconds. But when I then reload the webpage after let's say 30 seconds, I can see in IE's devtools that the cookie is sent in the next HTTP request.

Note that I don't have much experience with IE (I'm working on a Macbook, testing this on [LambdaTest](https://www.lambdatest.com/)), and it looks like in IE's devtools there's no way to see the expiration date of the cookie. So I can't say for sure that IE does not support `Max-Age`, but based on the fact that it includes the cookie in the next HTTP request when the cookie should have been expired tells me that it probably does not.

#### What information was incorrect, unhelpful, or incomplete?

https://caniuse.com/mdn-http_headers_set-cookie_max-age

Based on my own testing, it looks like IE11 does not support `Max-Age`.

#### What did you expect to see?

IE11 support should be red, and I assume that also IE8-10.

#### Did you test this? If so, how?

Already described in the top of the issue description.

#### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

Not really

**Comment by martindzejky** [comment]
This is probably related to #1642

**Comment by queengooborg** [comment]
I'm closing this issue since the IE data was frozen a few releases back.
