### ISSUE TITLE
css.at-rules.font-face.font-variation-settings - font-variation-settings not supportet for @font-face by Google Chrome

### ISSUE THREAD

**Issue by davidseegert** [mdn/browser-compat-data#10572]
#### What information was incorrect, unhelpful, or incomplete?
font-variation-settings are listed as a supportet @font-face descriptor for Google Chrome since version 62. However, while font-variation-settings are supportet by regular css selectors, they are not supported inside of @font-face in chome (tested with version  90.0.4430.212).

#### What did you expect to see?
No (not supportet entry in table)

#### Did you test this? If so, how?
 Compared css in firefox and chrome 
````
@font-face {
    font-family: 'Bodoni';
    src: url('./BodoniModa[opsz,wght].ttf') format('truetype');
    font-style: normal;
    font-variation-settings: "wght" 900;
}
````

<details>
<summary>MDN page report details</summary>

* Query: `css.at-rules.font-face.font-variation-settings`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-variation-settings
* Report started: 2021-05-21T21:39:25.612Z

</details>

**Comment by queengooborg** [comment]
This was fixed by #15332!
