### ISSUE TITLE
api.Element.requestPointerLock - Pointer lock fails on Android

### ISSUE THREAD

**Issue by ClickSapiens** [mdn/browser-compat-data#10618]
OS: Android 10 QKQ1.191215
Browser: Chrome, Edge, Firefox

Use case: 
A low cost Bluetooth gyroscopic device is used to control motion and aiming in a game or application, providing continuous data that extend beyond the screen, that can only be handled/adapted/corrected with a pointer lock function, otherwise the normal screen-limiting mouse function also causes misalignment on the motion data every time it reaches the edges of the screen/window.

The issue:
1. Pointer lock fails in all browsers.
2. Firefox doesn't even raise an error while it fires the pointerlockchange event.
3. Chrome and other browsers raise the following error event that I captured with a complex stringifying function:

<
 "eventName"" "[object Event]"
 "bubbles": false
 "cancelBubble": false
 "composed": false
 "defaultPrevented": false
 "eventPhase": 2
 "fromElement": null
 "isTrusted": true
 "path": null
 "relatedTarget": null
 "returnValue": true
 "sourceCapabilities": null
 "timeStamp"; 32079.6000000000028
 "toElement": null
 "type": "pointerlockerror"
 "view": null
>

This error is raised even if I just touch the screen, which means that the browser treats the touch event the same as the click from a pointing device.

Official online MDN demo:
https://mdn.github.io/dom-examples/pointer-lock/

Other demos:
http://media.tojicode.com/q3bsp/
http://www.smartjava.org/examples/pointerlock/

<details>
<summary>MDN page report details</summary>

* Query: `api.Element.requestPointerLock`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Pointer_Lock_API
* Report started: 2021-05-24T13:03:46.722Z

</details>

**Comment by queengooborg** [comment]
> the browser treats the touch event the same as the click from a pointing device.

This is normal behavior for all browsers; touches on the screen count as pointer events, including clicks.  Since a phone isn't able to lock the pointer of a touch input (it would have to physically force your finger in place for that), any pointer lock events would fail accordingly.
