### ISSUE TITLE
Mirroring script: account for Safari and Chrome for Android WebView mirroring

### ISSUE THREAD

**Issue by queengooborg** [mdn/browser-compat-data#10612]
I've recently discovered that setting WebView to `1` when Chrome is `1` (or for that matter, Chrome Android is `18`) is not a valid rule-of-thumb, due to the difference in engine versions (see #10588).  Since the first WebView Android used a WebKit version closer to the same one as the first Safari iOS, it's safer to mirror the data from Safari around those times -- particularly, if support is present in Safari 3 or older, it's safe to say it's present in WebView 1.

As a part of this. we should update the mirroring script to account for both Safari _and_ Chrome for WebView.

**Comment by foolip** [comment]
This will probably result in some APIs being added in WebView 1 and then removed again in 4.4, and maybe added back again later. When that's really what happened it's OK to put it in the data, but when making the data complex like that it would be great to not just trust the mirroring script but also base it on testing.

**Comment by queengooborg** [comment]
I'm going to close this as irrelevant because it's related to super old browser versions that we can just test if we wanted to.
