### ISSUE TITLE
html.elements.iframe - <Safari on iOS浏览器无法安装APP>

### ISSUE THREAD

**Issue by Anima-No** [mdn/browser-compat-data#10626]
比如我们在A页面iframe的src指向B页面。在B页面内有一个方法是执行的
{ window.location.href =  `itms-services://?action=download-manifest&amp;url=${this.iosDowLoadUrl}` }
其大概的意思是，B页面执行安装一个ios应用软件。此时在A页面没办法安装，也没有任何提示。在换到别的浏览器可以正常弹框提示用户是否安装此APP。麻烦问一下有没有什么方法可以解决，在不改变B页面的内容情况下！

**Comment by vinyldarkscratch** [comment]
This repository is not a help forum.  Please use a dedicated platform like StackOverflow.

该存储库不是帮助论坛。 请使用专用平台，例如StackOverflow。
