### ISSUE TITLE
api.FontFaceSet.check - Does not seem to be supported by iOS 

### ISSUE THREAD

**Issue by FrankConijn** [mdn/browser-compat-data#10624]
iOS 14.5.1, iPad Pro 2020. Checked in Safari and Edge for iOS. 

The Vivaldi font is not installed on iPads, see [https://developer.apple.com/fonts/system-fonts/](url). Still, this Javascript does not throw an alert: 

`if (document.fonts.check('20px Vivaldi') == false) {
        alert('No Vivaldi on this device.');
}`

On my Android phone, it does. 

<details>
<summary>MDN page report details</summary>

* Query: `api.FontFaceSet.check`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/FontFaceSet/check
* Report started: 2021-05-24T20:08:12.752Z

</details>

**Comment by queengooborg** [comment]
Safari is actually behaving per spec, while Chrome is not.  See #8966 or the compatibility note for Chrome for more details.
