### ISSUE TITLE
http status 500 error

### ISSUE THREAD

**Issue by chintanrlodaya111** [mdn/browser-compat-data#10627]
#### Did you test this? If so, how?

<details>
<summary>MDN page report details</summary>

* Query: `http.status.500`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500
* Report started: 2021-05-25T12:25:49.571Z

</details>

**Comment by ddbeck** [comment]
I'm closing this issue because it appears to be empty. The issue template is incomplete and no actionable information has been provided.

If this has been closed in error, edit the body, and post a follow-up comment.
