### ISSUE TITLE
api.BaseAudioContext.decodeAudioData - supported in Safari 14.1

### ISSUE THREAD

**Issue by AshleyScirra** [mdn/browser-compat-data#10630]
#### What information was incorrect, unhelpful, or incomplete?

The promise-based syntax of decodeAudioData is listed as not supported in Safari. However it is now supported as of Safari 14.1 with its standards-compliant Web Audio API support.

#### What did you expect to see?

Supported in Safari 14.1+

#### Did you test this? If so, how?

Yes, in browser console in Safari 14.1 on macOS

<details>
<summary>MDN page report details</summary>

* Query: `api.BaseAudioContext.decodeAudioData`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/BaseAudioContext/decodeAudioData
* Report started: 2021-05-25T13:51:38.048Z

</details>

**Comment by vinyldarkscratch** [comment]
It appears this was resolved in #11553!
