### ISSUE TITLE
css.selectors.is - edge 90 is :is() and Support for forgiving selector list working.

### ISSUE THREAD

**Issue by juner** [mdn/browser-compat-data#10644]
`Edge 90` is [`:is()`](https://developer.mozilla.org/docs/Web/CSS/:is) and [`Support for forgiving selector list`](https://developer.mozilla.org/docs/Web/CSS/:is#forgiving_selector_parsing) working.

#### What information was incorrect, unhelpful, or incomplete?

`Edge 90` is [`:is()`](https://developer.mozilla.org/docs/Web/CSS/:is) and [`Support for forgiving selector list`](https://developer.mozilla.org/docs/Web/CSS/:is#forgiving_selector_parsing) support.

#### What did you expect to see?

I think the supported version should be `Edge 88`. 

Same as [`:where()`](https://developer.mozilla.org/docs/Web/CSS/:where).

#### Did you test this? If so, how?

```javascript
document.querySelectorAll(":is(:not-support-selector)"); // <- OK(success)
document.querySelectorAll(":is(:not-support-selector,div)"); // <- OK(success)
document.querySelectorAll(":not-support-selector"); // <- OK(ERROR)
```

<details>
<summary>MDN page report details</summary>

* Query: `css.selectors.is`
* MDN URL: https://developer.mozilla.org/ja/docs/Web/CSS/:is
* Report started: 2021-05-27T01:04:15.236Z

</details>

**Comment by queengooborg** [comment]
This has been fixed in #11475!
