### ISSUE TITLE
javascript.operators.await - Edge supports top-level module await

### ISSUE THREAD

**Issue by amn** [mdn/browser-compat-data#10640]
#### What information was incorrect, unhelpful, or incomplete?

I believe the information on support of top-level `await` by Microsoft Edge is outdated.

#### What did you expect to see?

I have tested Microsoft Edge 90.0.818.66 (publicly available) and it supports top-level `await` just fine.

#### Did you test this? If so, how?

Yes, I have:

```html
<!DOCTYPE html>
<html>
	<body>
		<script type="module">
			console.debug(await new Promise(resolve => {
				resolve("I am your Huckleberry.");
			}));
		</script>
	</body>
</html>
```

<details>
<summary>MDN page report details</summary>

* Query: `javascript.operators.await`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await
* Report started: 2021-05-26T13:49:23.249Z

</details>

**Comment by queengooborg** [comment]
This was fixed in #10632!
