### ISSUE TITLE
api.IntersectionObserverEntry.isIntersecting - Not supported in Chrome

### ISSUE THREAD

**Issue by jason-grimm** [mdn/browser-compat-data#10654]
At least Chrome55 doesn't have this property

**Comment by ddbeck** [comment]
Hi @jason-grimm and thanks for reporting this. Could you help us out by completing the questions in [the new issue template](https://github.com/mdn/browser-compat-data/issues/new/choose) or filling in the template generated by the "Report problems with this compatibility data on GitHub" link on the [`isIntersecting` page](https://developer.mozilla.org/en-US/docs/Web/API/IntersectionObserverEntry/isIntersecting#browser_compatibility)? We need additional details to triage compat data issues and one of those templates should help.

Alternatively, you can copy and paste the template into this issue, complete it, and request to reopen this one.

Thanks for your understanding!
