### ISSUE TITLE
Issue with "webNavigation.onCreatedNavigationTarget": regression for target="_blank" links

### ISSUE THREAD

**Issue by jonathanmayer** [mdn/browser-compat-data#10675]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webNavigation/onCreatedNavigationTarget

#### What information was incorrect, unhelpful, or incomplete?

The documentation for `webNavigation.onCreatedNavigationTarget` does not reflect that, since Firefox 65, there has been a regression where the event does not fire when clicking on an anchor element with a `target="_blank"` attribute.

Relevant discussion:
* https://bugzilla.mozilla.org/show_bug.cgi?id=1344376
* https://bugzilla.mozilla.org/show_bug.cgi?id=1503681
* https://bugzilla.mozilla.org/show_bug.cgi?id=1543647
* https://gitlab.com/eyeo/adblockplus/adblockpluschrome/-/issues/237

#### Specific section or headline?

Since this firing condition is essential to the event, it seems appropriate to flag the regression in the explanation of when the event fires. At minimum, the regression should appear in the browser compatibility table.

#### What did you expect to see?

A description of the regression.

#### Did you test this? If so, how?

In a Firefox test extension, I confirmed that `webNavigation.onCreatedNavigationTarget` did not fire when I clicked on an anchor element with a `target="_blank"` attribute.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/api/webnavigation/oncreatednavigationtarget`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webNavigation/onCreatedNavigationTarget
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/api/webnavigation/oncreatednavigationtarget/index.html
* Last commit: https://github.com/mdn/content/commit/c7d9128559ed9526914c9be5bb461445fde5866a
* Document last modified: 2021-02-19T20:09:33.000Z

</details>

**Comment by rebloor** [comment]
I re-ran the test described in [Bug 1344376](https://bugzilla.mozilla.org/show_bug.cgi?id=1344376) onCreatedNavigationTarget not called when clicking a target="_blank" link. I confirmed that the webpage was still as specified:
![image](https://github.com/mdn/browser-compat-data/assets/7352080/e854332e-a04a-4d03-b45e-83eabd7408f4)
I then followed the various links:
<img width="914" alt="image" src="https://github.com/mdn/browser-compat-data/assets/7352080/62cdde88-0755-4f6b-9378-01d177a8c4d5">
The event fired, as expected.
