### ISSUE TITLE
javascript.builtins.Array.at - <PUT TITLE HERE>

### ISSUE THREAD

**Issue by pxladin** [mdn/browser-compat-data#10688]
#### Did you test this? If so, how?

<details>
<summary>MDN page report details</summary>

* Query: `javascript.builtins.Array.at`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/at
* Report started: 2021-05-31T17:20:02.065Z

</details>

**Comment by xNocken** [comment]
Thats a keneders best practice
