### ISSUE TITLE
Remove iOS releases with matching engine versions?

### ISSUE THREAD

**Issue by foolip** [mdn/browser-compat-data#10723]
In https://github.com/mdn/browser-compat-data/issues/10524, some cleanup of WebView Android versions was made after @vinyldarkscratch discovered that some of the WebView versions had the same WebKit engine version.

There's a similar situation for iOS (but not macOS) with these releases having the same `engine_version`:
- [x] iOS 3 and 3.1 both have WebKit 528.18 (https://github.com/mdn/browser-compat-data/pull/11173)
- [x] iOS 4.2 and 4.3 both have WebKit 533.17 (https://github.com/mdn/browser-compat-data/pull/11174)
- [x] iOS 5 and 5.1 both have WebKit 534.46 (https://github.com/mdn/browser-compat-data/pull/11175)
- [x] iOS 6 and 6.1 both have WebKit 536.26 (https://github.com/mdn/browser-compat-data/pull/11156)

Assuming these versions are correct, should we remove the second of each pair, and change the existing versions to the first of the pair?

@apple-web-evangelist @gsnedders @jensimmons, are either of you able to verify that these versions are in fact correct, and if they are, what do you think should be done?

**Comment by binhle7777** [comment]
Why ???

Vào Th 4, 2 thg 6, 2021 lúc 7:36 CH Philip Jägenstedt <
***@***.***> đã viết:

**Comment by ux-8** [comment]
@ทศธนโพธิ์ทอง

**Comment by ux-8** [comment]
!!

**Comment by ux-8** [comment]
> ใน[#10524 การ](https://github.com/mdn/browser-compat-data/issues/10524)ล้างเวอร์ชัน WebView Android บางเวอร์ชันเกิดขึ้นหลังจาก@vinyldarkscratchค้นพบว่าเวอร์ชัน WebView บางเวอร์ชันมีเวอร์ชันเอ็นจิน WebKit เหมือนกัน
> 
> มีสถานการณ์ที่คล้ายคลึงกันสำหรับ iOS (แต่ไม่ใช่ macOS) โดยมีรุ่นเหล่านี้เหมือน`engine_version`กัน:
> 
> * iOS 3 และ 3.1 ทั้งคู่มี WebKit 528.18
> * iOS 4.2 และ 4.3 ทั้งคู่มี WebKit 533.17
> * iOS 5 และ 5.1 ทั้งคู่มี WebKit 534.46
> * iOS 6 และ 6.1 ทั้งคู่มี WebKit 536.26
> 
> สมมติว่าเวอร์ชันเหล่านี้ถูกต้อง เราควรลบคู่ที่สองของแต่ละคู่ออก และเปลี่ยนเวอร์ชันที่มีอยู่เป็นรุ่นแรกของคู่หรือไม่
> 
> @apple-web-evangelist @gsnedders @jensimmonsคุณคนใดคนหนึ่งสามารถยืนยันได้ว่าเวอร์ชันเหล่านี้ถูกต้องหรือไม่ และหากเป็นเช่นนั้น คุณคิดว่าควรทำอย่างไร

ใครลบก็ไปลบที่ไอ้คนนั้นให้หมดอย่างให้เหลือแม้แต่อักษรซักตัวเดียว

**Comment by foolip** [comment]
https://github.com/mdn/browser-compat-data/pull/11174 got rid of 4.3, I've turned the description into a checklist. @vinyldarkscratch FYI.

**Comment by foolip** [comment]
There's no separate issue for Safari, and I think there's just a single case, so here's checklist of one:
- [ ] Safari 3.2 (WebKit 525.26) can be merged into 3.1 (WebKit 525.13)

**Comment by queengooborg** [comment]
Closing because all of our iOS versions have been taken care of, and all Safari Desktop ones too!
