### ISSUE TITLE
Add UC and "UC (China)" browsers

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#1072]
We'd like to add the UC browsers to this repo. Apparently there is an international version and a Chinese version.

To add a new browser to the data these three steps need to be taken:

1. Agree on a [browser identifier](https://github.com/mdn/browser-compat-data/blob/master/schemas/compat-data-schema.md#browser-identifiers)
I guess this could be "`uc_android`" and "`uc_chinese_android`". 
Browser identifiers try to have the form of "browsername_platform". This identifier is used everywhere in the data then. See the [CSS background property](https://github.com/mdn/browser-compat-data/blob/master/css/properties/background.json) for an example data set and the other browser identifiers.

2. Add browser release infos to the [browsers](https://github.com/mdn/browser-compat-data/blob/master/browsers) folders. File names should be the same as the agreed identifiers:
  `browsers/uc_android.json`
  `browsers/uc_chinese_android.json`
  See the [Samsung Internet data](https://github.com/mdn/browser-compat-data/blob/master/browsers/samsunginternet_android.json) for an example.

3. The browser identifiers also need to be added to the docs and the schema files, so that our validation scripts work accordingly
 https://github.com/mdn/browser-compat-data/blob/master/schemas/compat-data-schema.md#browser-identifiers
  https://github.com/mdn/browser-compat-data/blob/master/schemas/browsers.schema.json#L6
  https://github.com/mdn/browser-compat-data/blob/master/schemas/compat-data.schema.json#L74

**Comment by foolip** [comment]
The suggested identifiers make sense to me, http://wap.uc.cn/verlist/chinese_999/ucbrowser/145 also uses "chinese" as opposed to "china".

The lunar new year is here so I don't expect feedback here until sometime next week at the earliest, but I'll prepare a PR for review nonetheless.

**Comment by foolip** [comment]
I've submitted https://github.com/mdn/browser-compat-data/pull/1077 with each ID as a separate commit just in case the Chinese edition isn't wanted/needed. See the commit messages there.

**Comment by jensimmons** [comment]
Why did we decide to not support the UC Browser?

**Comment by ddbeck** [comment]
@jensimmons Sorry for the confusion on this one too. UC was _added_ with d00712c, which closed this issue. See https://github.com/mdn/browser-compat-data/tree/master/browsers to see which browsers are included in BCD (though actual data coverage varies significantly between browsers)
