### ISSUE TITLE
BCD loader crashes when mixin feature included in both files

### ISSUE THREAD

**Issue by queengooborg** [mdn/browser-compat-data#10734]
When working on #10724, I ran into an issue where the `extend()` function in `index.js` crashes, throwing an error that `"Both target and source must be plain objects"`.  After doing some research, I was able to determine two causes for this error.  The first is due to invisible files created by the system (which I've addressed in #10733).  The second is a little more troublesome, which is why I'm opening this issue.

The reason behind this boils down to two separate files containing the exact same feature.  While demixing `LinkStyle`, I hadn't noticed that the feature it exposes on `HTMLStyleElement`was also documented in the dedicated API's JSON, so when creating the new mixin file, both `api/HTMLStyleElement.json` and `api/_mixins/LinkStyle__HTMLStyleElement.json` expose `api.HTMLStyleElement.sheet`.  The `load()` function loads the data from the first file, and then when it gets to the second file, notices that we already have a `sheet` member inside of `api.HTMLStyleElement`, so it [performs a recursive `extend()`](https://github.com/mdn/browser-compat-data/blob/71a3bca95a9cf385d2d73365c1cc26f8e93d0f5c/index.js#L48) through the feature.  That is, until it gets to the `mdn_url` member, which it attempts to perform a recursive `extend()` upon, but since it throws an error if either variable isn't a plain object (and `mdn_url`'s value is a string), the whole function crashes.

Now of course, we wouldn't want to have duplicate data anyways, and should probably have some sort of linter or otherwise to prevent it.  However, an error message such as the one we're getting is just plain unhelpful in figuring out what exactly is going on.

**Comment by foolip** [comment]
Throwing errors when anything other than an object appears in two places was a deliberate change, see the discussion in https://github.com/mdn/browser-compat-data/pull/9821#discussion_r612582315.

However, the error it throws isn't very obvious I guess.
