### ISSUE TITLE
Add qq browser

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#1073]
We'd like to add the qq browser to this repo.

To add a new browser to the data these three steps need to be taken:

1. Agree on a [browser identifier](https://github.com/mdn/browser-compat-data/blob/master/schemas/compat-data-schema.md#browser-identifiers)
I guess this could be "`qq_android`".
Browser identifiers try to have the form of "browsername_platform". This identifier is used everywhere in the data then. See the [CSS background property](https://github.com/mdn/browser-compat-data/blob/master/css/properties/background.json) for an example data set and the other browser identifiers.

2. Add browser release infos to the [browsers](https://github.com/mdn/browser-compat-data/blob/master/browsers) folders. File names should be the same as the agreed identifiers:
  `browsers/qq_android.json`
  See the [Samsung Internet data](https://github.com/mdn/browser-compat-data/blob/master/browsers/samsunginternet_android.json) for an example.

3. The browser identifiers also need to be added to the docs and the schema files, so that our validation scripts work accordingly
 https://github.com/mdn/browser-compat-data/blob/master/schemas/compat-data-schema.md#browser-identifiers
  https://github.com/mdn/browser-compat-data/blob/master/schemas/browsers.schema.json#L6
  https://github.com/mdn/browser-compat-data/blob/master/schemas/compat-data.schema.json#L74

**Comment by jensimmons** [comment]
Why did we decide not to support the QQ browser?

**Comment by ddbeck** [comment]
@jensimmons Sorry for the confusion. QQ was _added_ in #1078, which closed this issue. See https://github.com/mdn/browser-compat-data/tree/master/browsers to see which browsers are included in BCD.
