### ISSUE TITLE
allow vr not working on IOS - Any update here?

### ISSUE THREAD

**Issue by jhetuts** [mdn/browser-compat-data#10760]
#### What information was incorrect, unhelpful, or incomplete?
Hi, this was reported previously as shown in this discussion https://github.com/immersive-web/webxr/issues/25. I've happen to stumble this when supporting third party app which uses iframe but serving it in our own domain inside of iframe. As per the latest release. I added this attribute on iframe tag `<iframe allow="xr-spatial-tracking"></iframe>` and perfectly working on Android devices but not on IOS.
#### What did you expect to see?
Support for IOS mobile platform.

<details>
<summary>MDN page report details</summary>

* Query: `http.headers.Feature-Policy.vr`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy/vr
* Report started: 2021-06-04T09:16:44.814Z

</details>

**Comment by vinyldarkscratch** [comment]
Can we get some more clarification on the issue?  Is it that you are wanting to use WebVR/WebXR on iOS, but you're finding that it's not supported?  If that's the case, then our data indicates that it is unsupported in iOS.  If you mean that you've tried this feature and found it _is_ supported, we'd be happy to correct our data.

**Comment by jhetuts** [comment]
Hi @vinyldarkscratch. I mean it's still not working on IOS Safari browser.

I'm running a VR app inside an iframe and hosted in the same domain.
I don't see this permission to Allow access to "Motion and Orientation" prompt when I tried to view it on IOS Safari browser. 

I'm following up if this `allowvr="yes"`  on iframe works on IOS now.

**Comment by vinyldarkscratch** [comment]
I see, thanks for the clarification.  This feature is marked as unsupported on Safari iOS in our data, so your results are as expected.

**Comment by jhetuts** [comment]
You have an idea if MDN is still working on it or what's the status?

**Comment by vinyldarkscratch** [comment]
I think there might be some confusion here: MDN Web Docs is a team of documentation writers, NOT the developers of Safari or other browsers (although there's quite a bit of crossover).  If you're looking to track implementation status for something in Safari, I'd take a look at the dedicated website for [WebKit](https://webkit.org/) itself.

**Comment by jhetuts** [comment]
Oh got it. Thanks for the info @vinyldarkscratch !
