### ISSUE TITLE
Issue with "Element.getBoundingClientRect()": (Difference in IE)

### ISSUE THREAD

**Issue by PAPIONbit** [mdn/browser-compat-data#10768]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect

#### What information was incorrect, unhelpful, or incomplete?
X & Y as return values, are not supported in any version of IE (Internet Explorer). it is better to be mentioned.

#### Did you test this? If so, how?
![image](https://user-images.githubusercontent.com/47592258/119352102-7fda1300-bcb6-11eb-8c4c-bb6dc69557cc.png)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/element/getboundingclientrect`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/element/getboundingclientrect/index.html
* Last commit: https://github.com/mdn/content/commit/56d9a678477f0e79232caa8169114519bf02a44a
* Document last modified: 2021-02-19T19:41:18.000Z

</details>

**Comment by queengooborg** [comment]
I'm closing this issue as we are no longer maintaining the Internet Explorer; see the [applicable discussion](https://github.com/orgs/mdn/discussions/202) for more details.
