### ISSUE TITLE
html.global_attributes.spellcheck - <Chrome 9.0+ not working on Windows system>

### ISSUE THREAD

**Issue by Jennette-wq** [mdn/browser-compat-data#10818]
#### What information was incorrect, unhelpful, or incomplete?
spellcheck is not working on Chrome 9.0+ on windows system
#### What did you expect to see?
Should show red line under spelling errors input fields
#### Did you test this? If so, how?

<details>
<summary>MDN page report details</summary>

* Query: `html.global_attributes.spellcheck`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/spellcheck
* Report started: 2021-06-07T08:55:22.502Z

</details>

**Comment by ddbeck** [comment]
Hi @Jennette-wq. Thanks for reporting this.

(Just to be clear, the question here about "What did you expect to see?" was meant in the sense of the "What did you expect to see in the compatibility table?" If you're looking for help with web development, it won't be possible for us to provide support, unfortunately.)

Do you have a test case or citation for this problem? For example, a demonstration in Codepen of this feature failing to work would be ideal, but a link to a Chromium bug or other source verifying the problem would be a big step toward updating the table. Thank you again!

**Comment by queengooborg** [comment]
I'm going to go ahead and close this issue since there has been no response, and I have not been able to replicate the issue on my end.  If this is still an issue, please feel free to reply to this thread and I'll happily reopen the issue!
