### ISSUE TITLE
api.MediaMetadata - <error  'MediaMetadata' is not defined  no-undef>

### ISSUE THREAD

**Issue by nidhi-canopas** [mdn/browser-compat-data#10819]
#### What information was incorrect, unhelpful, or incomplete?
`error  'MediaMetadata' is not defined  no-undef`
Using `MediaMetadata` with `vue-electron-builder`
#### What did you expect to see?
Should run without throwing any error
#### Did you test this? If so, how?
Tested compatibility with following code : 
`if ('mediaSession' in navigator) { console.log("supported"); } else { console.log('MediaMetadata is not supported') }`

Actual code trying to apply with : 

```
if ("mediaSession" in navigator){
  let track = myTrackObj;
  navigator.mediaSession.metadata = new MediaMetadata({
    title: track.name,
    artist: track.artist.name,
    album: track.album.name,
    artwork: track.image_url
  });
}
```

<details>
<summary>MDN page report details</summary>

* Query: `api.MediaMetadata`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MediaMetadata
* Report started: 2021-06-07T07:10:16.901Z

</details>

**Comment by vinyldarkscratch** [comment]
That sounds like something to do with `vue-electron-builder`.  I don't know enough about how it works to really say what browser engine and version it's using.  Perhaps check to see what `navigator.userAgent` reports?

Unfortunately, we can't really provide coding assistance on this repository, so I'm closing this issue.

**Comment by vinyldarkscratch** [comment]
I did a quick search for you, and have found the following.  It pertains to React instead of Vue, but since both use Babel and Electron, I believe this solution should solve your issue: https://stackoverflow.com/a/62264777
