### ISSUE TITLE
This is part of #5438.

### ISSUE THREAD

**Issue by 4LY451N** [mdn/browser-compat-data#10832]
This is part of #5438.

It removes the style attributes in canvas api pages.

It was either styling emphasing text ("red" actually written in red), or floating images that I put back in the flow of the text (adapting it when needed, like changing "the image to the right" to something working with the image in the flow)

__Originally posted by @teoli2003 in https://github.com/mdn/content/pull/5725__

**Comment by teoli2003** [comment]
Hi @4LY451N !

I'm unsure why you opened this here: I don't think it needs any BCD update.

If it is a mistake/test, not a big deal, just close it. Else I'm really puzzled and… curious!

**Comment by vinyldarkscratch** [comment]
Closing since the same user has created other issues that are just template issues or reposts.
