### ISSUE TITLE
css.properties.inset - Inset property supported in latest Edge browser

### ISSUE THREAD

**Issue by D41126522** [mdn/browser-compat-data#10835]
#### What information was incorrect, unhelpful, or incomplete?
The chart shows the Edge browser isn't supported under version 79. Support is available in newer versions.

#### What did you expect to see?
I'm not sure when Edge started supporting `inset`, but it's in there now. I would assume support would be similar to Chrome.

#### Did you test this? If so, how?
 Tested in Edge Version 91.0.864.41. I can confirm that Edge currently supports the `inset` property.

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.inset`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/inset
* Report started: 2021-06-07T12:36:59.672Z

</details>

**Comment by queengooborg** [comment]
This has been fixed in #10795!
