### ISSUE TITLE
javascript.builtins.SharedArrayBuffer - <PUT TITLE HERE>

### ISSUE THREAD

**Issue by yuriyvyatkin** [mdn/browser-compat-data#10855]
#### What information was incorrect, unhelpful, or incomplete?
There is no the anchor link to the description of atomic operations.

#### What did you expect to see?
Anchor tag with attribute href="https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Atomics#атомарные_операции" to the word "атомарные".

#### Did you test this? If so, how?
I checked the link.

<details>
<summary>MDN page report details</summary>

* Query: `javascript.builtins.SharedArrayBuffer`
* MDN URL: https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer
* Report started: 2021-06-08T05:39:04.154Z

</details>

**Comment by vinyldarkscratch** [comment]
This is an issue for https://github.com/mdn/content rather than this repository.  Can you open an issue there?

**Comment by yuriyvyatkin** [comment]
Yes, sure. Thank you for the link. I opened a new issue #5789.
