### ISSUE TITLE
html.elements.input.input-month - Supported in Firefox Android

### ISSUE THREAD

**Issue by flo13270** [mdn/browser-compat-data#10861]
Firefox for Android version 89.1.1 (on Android 10)
#### What information was incorrect, unhelpful, or incomplete?
"Firefox for Android : No support"
#### What did you expect to see?
"Firefox for Android : Yes"
#### Did you test this? If so, how?
![Yes](https://media.discordapp.net/attachments/778184824355029014/851745194348249088/Screenshot_2021-06-08-10-43-59-513_org.mozilla.firefox.jpg?width=269&height=583)

<details>
<summary>MDN page report details</summary>

* Query: `html.elements.input.input-month`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/HTML/Element/Input/month
* Report started: 2021-06-08T08:23:46.530Z

</details>

**Comment by queengooborg** [comment]
This has been fixed in #13531!
