### ISSUE TITLE
api.MediaDevices.getUserMedia - <PUT TITLE HERE>

### ISSUE THREAD

**Issue by wjh19980109** [mdn/browser-compat-data#10903]
#### Did you test this? If so, how?

<details>
<summary>MDN page report details</summary>

* Query: `api.MediaDevices.getUserMedia`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/API/MediaDevices/getUserMedia
* Report started: 2021-06-10T03:38:05.473Z

</details>

**Comment by 138166234** [comment]
mohamadsalmanpor

1381662341mohamadsalmanpor

در تاریخ پنجشنبه ۱۰ ژوئن ۲۰۲۱،‏ ۱۰:۱۴ wjh19980109 ***@***.***>
نوشت:
