### ISSUE TITLE
<!-- build_hash: e5f0f2d4378b0cbc0f756a750cf41439 date: 2021-06-10 09:38:08.592380 -->

### ISSUE THREAD

**Issue by 4LY451N** [mdn/browser-compat-data#10929]
## Preview URLs

- <https://pr5849.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/KeyboardEvent/keyCode>
- <https://pr5849.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/KeyboardEvent/getModifierState>

## Flaws

URL: [`/en-US/docs/Web/API/KeyboardEvent/keyCode`](https://pr5849.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/KeyboardEvent/keyCode)
Title: `KeyboardEvent.keyCode`
[on GitHub](https://github.com/mdn/content/blob/5849/merge/files/en-us/web/api/keyboardevent/keycode/index.html)
Flaw count: 2

- **macros**:
  - `/en-us/docs/web/api/keyevent (url: /en-US/docs/Web/API/KeyEvent) does not exist`
- **broken_links**:
  - `Can't resolve /en-US/docs/Gecko_Keypress_Event`

---

URL: [`/en-US/docs/Web/API/KeyboardEvent/getModifierState`](https://pr5849.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/KeyboardEvent/getModifierState)
Title: `KeyboardEvent.getModifierState()`
[on GitHub](https://github.com/mdn/content/blob/5849/merge/files/en-us/web/api/keyboardevent/getmodifierstate/index.html)
Flaw count: 1

- **macros**:
  - `/en-us/docs/web/api/keyevent (url: /en-US/docs/Web/API/KeyEvent) does not exist`

## External URLs

URL: [`/en-US/docs/Web/API/KeyboardEvent/keyCode`](https://pr5849.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/KeyboardEvent/keyCode)
Title: `KeyboardEvent.keyCode`
[on GitHub](https://github.com/mdn/content/blob/5849/merge/files/en-us/web/api/keyboardevent/keycode/index.html)

No *new* external URLs

---
URL: [`/en-US/docs/Web/API/KeyboardEvent/getModifierState`](https://pr5849.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/KeyboardEvent/getModifierState)
Title: `KeyboardEvent.getModifierState()`
[on GitHub](https://github.com/mdn/content/blob/5849/merge/files/en-us/web/api/keyboardevent/getmodifierstate/index.html)

No *new* external URLs

__Originally posted by @github-actions in https://github.com/mdn/content/pull/5849#issuecomment-858472241__

**Comment by teoli2003** [comment]
This is not a real issue. (spam-like). It is a copy of a message from mdn/content.

You can close it. (I can't myself)
