### ISSUE TITLE
api.MediaTrackSettings.channelCount - Chrome supports channelCount?

### ISSUE THREAD

**Issue by Mogrenn** [mdn/browser-compat-data#10937]
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36"

Data says no Chrome support, but I used the command navigator.mediaDevices.getSupportedConstraints() and there it was as true

<details>
<summary>MDN page report details</summary>

* Query: `api.MediaTrackSettings.channelCount`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackSettings/channelCount
* Report started: 2021-06-10T16:44:42.154Z

</details>

**Comment by queengooborg** [comment]
We're working on removing all dictionaries from BCD, so I'm going to close this issue.  Thank you anyways!
