### ISSUE TITLE
Fixes #5728.

### ISSUE THREAD

**Issue by 4LY451N** [mdn/browser-compat-data#10930]
Fixes #5728.

Like in #5825, I replaced the background color by icons and adapted the footnotes.

__Originally posted by @teoli2003 in https://github.com/mdn/content/pull/5849__

**Comment by teoli2003** [comment]
This is not relevant. @4LY451N has created several of these bogus issues over the last few days. Likely some wrong manipulations,

Please close it (I can't myself)
