### ISSUE TITLE
css.properties.overflow-x - Support info for the clip value is outdated for Chromium-based browsers

### ISSUE THREAD

**Issue by stof** [mdn/browser-compat-data#10962]
#### What information was incorrect, unhelpful, or incomplete?

MDN reports the `clip` as supported only in Firefox

#### What did you expect to see?

According to [Caniuse](https://caniuse.com/css-overflow), Chrome 90+ supports the `clip` value too

#### Did you test this? If so, how?

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.overflow-x`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-x
* Report started: 2021-06-11T14:26:44.803Z

</details>

**Comment by stof** [comment]
Note that this also affects the [`overflow-y`](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-y) data. However, the [`overflow`](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow#browser_compatibility) data is updated

**Comment by queengooborg** [comment]
Looks like this was resolved in #10281!
