### ISSUE TITLE
Lint for "experimental features" supported by three engines

### ISSUE THREAD

**Issue by gsnedders** [mdn/browser-compat-data#10961]
We can debate whether or not this should be two or three, but certainly when Blink, Gecko, and WebKit all support something it definitely seems a stretch to call something still experimental at that stage.

**Comment by bkardell** [comment]
I agree, it would be great to see when things flip to 2 and to 3 - feels like that would be useful even for simpler prioritizing of work.

**Comment by queengooborg** [comment]
This has been resolved by #15889!
