### ISSUE TITLE
Add DOM-Style-Level-2 to the exception list of authorized spec

### ISSUE THREAD

**Issue by teoli2003** [mdn/browser-compat-data#10971]
Hi!

According to the error message I get in #10970, we have an exception list of extra authorized specs in addition of those [w3c/browser-specs](https://github.com/w3c/browser-specs). I think we should add an extra spec there.

**Context**

1. On MDN, we are now sourcing spec info from here, with the `{{Specifications}}` macro.
2. A few interfaces/methods/properties were part of an old DOM Spec, were _implemented_ by 2 engines (Gecko and WebKit) at least and are *still implemented* by one (WebKit).
3. With the new sourcing, the spec info is disappearing from the table.

I tried to add the spec links to these few i/f, propertiies and methods (~12 of them) in #10970, but the linter rightfully reject them.

**Why I don't believe it should be in the list of _w3c/specs_**

This is a very old spec, deprecated stuff is almost completely removed, and I don't want to see new links to it appearing all over the place.

**Why I believe we should add an exception**

Because of point 2. (still implemented, still in use), I believe it is still useful (if our prose is not complete, reading the old but latest spec about it can help understand), not to create new code with it, but for example when migrating old code.

_Note: I'm not advocating to add old specs all over the place, but only for these entries._

**A few links**
- Example of original state on MDN: https://developer.mozilla.org/en-US/docs/Web/API/CSSValue#specifications

- Example of future state on MDN: https://pr5917.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/CSSValue#specifications
- Example of spec link to add: https://www.w3.org/TR/DOM-Level-2-Style/css.html#CSS-CSSValue

- The blocked PR: #10970

**Comment by teoli2003** [comment]
cc/ @elchi3, @foolip, @sideshowbarker

**Comment by foolip** [comment]
That seems OK to me. My main question is if we should still set `standards_track` to false? I would say we should, since this is no longer on a standards track.

**Comment by teoli2003** [comment]
Yes, I think that standards_track should stay to false. It is not on a standard track.

**Comment by sideshowbarker** [comment]
While I won’t object to this if others support it, I personally don’t believe we should add links to obsolete specs. I don’t actually think it’s helpful at all to developers for us to connecting them with obsolete specs. But then I also don’t think we should have spec URLs for features we’ve marked as Deprecated either — even if the spec URLs are for targets in non-obsolete specs.

The principle that I see at work here is that if a feature is deprecated, not making it easier for developers to figure out how to use it is a feature, not a bug. And if a spec is obsolete, not making it easier for developers to find that spec and read it is a feature, not a bug. So I think it’s appropriate that if a developer does want to find spec information for a deprecated feature, or to read an obsolete spec, it should require them to do some extra work on their own.

Some of the reasons for that include that many older obsolete specs are just really bad. For example, if a developer does manage to find the obsolete DOM specs, they are likely gonna have a lot of confusion when trying to read them, given how poorly written they are — and how poorly they map to how things are actually implemented.

All that said, however, as far as BCD goes at least, downstream consumers can choose to completely ignore features marked deprecated — and also to ignore features marked non-standard. In fact, for https://w3c.github.io/mdn-spec-links/ that’s what I actually do — I just have it ignore all deprecated and non-standard features.

So anyway, as I said at the beginning of this comment, while I don’t support adding DOM-Style-Level-2, I also won’t object.

**Comment by teoli2003** [comment]
I am not as sure as I was yesterday about this being a good idea (or not). I would like to revisit this once the discussion about mdn/yari#4012 (improving the message) has progressed. It may be good enough for this case too.

**Comment by Elchi3** [comment]
I think these features have lived out their life. I know it doesn't formally meet irrelevance criteria but I wish it did. (Firefox removed, Safari seems to be just late with removal?).

Adding spec urls to BCD doesn't really bring much for the MDN rendering. There is no meta data to display (like the spec title) as this spec isn't in browser-specs, so you'll get "Unknown spec". 

I'm objecting and proposing to delete outdated pages and compat data. If we don't want to delete yet, the outdated spec information (with some custom text that DOM 2 is outdated) can be added manually to the MDN page and doesn't need to use the BCD mechanism.

**Comment by teoli2003** [comment]
Let's keep mdn/browser-compat-data free of outdated spec! It makes sense.

So I will:
- close this issue and the associated PR, that is leaving mdn/browser-compat-data as is
- revisit the related mdn pages to not use `{{Specifications}}` in a PR.

I will not delete the pages and associated bcd for now, as I would like to focus in doing the `{{Specifications}}` and not been dragged on somewhat unrelated and not urgent decisions.

**Comment by teoli2003** [comment]
Looks we have a consensus.
