### ISSUE TITLE
javascript.builtins.String.trim 

### ISSUE THREAD

**Issue by vijetaashita** [mdn/browser-compat-data#10987]
#### Did you test this? If so, how?

<details>
<summary>MDN page report details</summary>

* Query: `javascript.builtins.String.trim`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/trim
* Report started: 2021-06-13T01:54:19.268Z

</details>

**Comment by vinyldarkscratch** [comment]
Closing since the PR template has not been filled out and there's no actionable information.
