### ISSUE TITLE
api.DataTransfer.getData - Safari iOS support

### ISSUE THREAD

**Issue by zuku1985** [mdn/browser-compat-data#10997]
#### What information was incorrect, unhelpful, or incomplete?
Safari on iOS
#### What did you expect to see?
It works since Safari 11
#### Did you test this? If so, how?
I tested it on 11,12,13 and 14 via BrowserStack and 14 on physical test device

<details>
<summary>MDN page report details</summary>

* Query: `api.DataTransfer.getData`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/getData
* Report started: 2021-06-13T22:23:54.572Z

</details>

**Comment by queengooborg** [comment]
This has been resolved by #13556!
