### ISSUE TITLE
Issue with "URL()": Special schemes don't correctly parse username/password

### ISSUE THREAD

**Issue by mranosa** [mdn/browser-compat-data#11015]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/URL/URL

#### What information was incorrect, unhelpful, or incomplete?
Dont know of this is the right place to post the issue, but anyhow.

Put the code below and run on a tsx file, log returns an empty string. Should return `1`. Works correctly on `ts` and `js`.

```
const newUrl = new URL('sftp://1:2@3.com');
console.log(newUrl.username)
```

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/url/url`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/URL/URL
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/url/url/index.html
* Last commit: https://github.com/mdn/content/commit/0582826af567669d6b3255a9c9c6aaf393914daa
* Document last modified: 2021-03-01T11:54:40.000Z

</details>

**Comment by queengooborg** [comment]
This has been fixed by #22079!
