### ISSUE TITLE
api.DataTransfer.setData - <Data transfer>

### ISSUE THREAD

**Issue by dayknchung** [mdn/browser-compat-data#11016]
#### What information was incorrect, unhelpful, or incomplete?
The index of .setData

#### What did you expect to see?
All distinct number the indicate the browser.

#### Did you test this? If so, how?
Not yet.

<details>
<summary>MDN page report details</summary>

* Query: `api.DataTransfer.setData`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/setData
* Report started: 2021-06-14T10:11:50.130Z

</details>

**Comment by vinyldarkscratch** [comment]
Apologies, I don't understand the question.  I'm not seeing anything about an "index" described on the MDN page.  Can you clarify?

**Comment by vinyldarkscratch** [comment]
Closing since there has been no actionable information on this issue.  If you'd like to add the requested information, feel free to reply to this thread!
