### ISSUE TITLE
use href= - safari 11 only supports xlink:href

### ISSUE THREAD

**Issue by aredridel** [mdn/browser-compat-data#11022]
#### What information was incorrect, unhelpful, or incomplete?

svg `<use href="#id">` does not work in at least mobile safari 11.2. `<use xlink:href="#id">` does.

#### What did you expect to see?

A note about the use of svg 2 href= vs svg 1 xlink:href

#### Did you test this? If so, how?

Experimentation in iOS 11.2 simulator

#### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://bugs.webkit.org/show_bug.cgi?id=153854 is the relevant bug, but I am unable to locate which specific versions it was released as a part of.

**Comment by queengooborg** [comment]
Support was added for the `href` attribute in Safari 12.1 / iOS 12.2 as is indicated by the data.
