### ISSUE TITLE
html.elements.meta.name.theme-color - <Safari adds support>

### ISSUE THREAD

**Issue by iMonZ** [mdn/browser-compat-data#11023]
Safari has added this feature in the latest Safari 15 beta on macOS and iOS

<details>
<summary>MDN page report details</summary>

* Query: `html.elements.meta.name.theme-color`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name/theme-color
* Report started: 2021-06-14T15:36:50.951Z

</details>

**Comment by vinyldarkscratch** [comment]
Duplicate of #10885.
