### ISSUE TITLE
SVG `use` with `xlink:href` attribute - Chrome & Firefox support seems wrong

### ISSUE THREAD

**Issue by ndorfin** [mdn/browser-compat-data#11034]
When browsing for SVG's `<use>` `href` and `xlink:href` attributes, I came across an odd metric when comaring the two.

According to the [relevant page](https://caniuse.com/?search=svg%20use%20href), it states SVG2's `href` attribute has 90% global support, while SVG1's `xlink:href` attribute only has 45% global support.

I think it's because the older Chrome & Firefox versions aren't listed as supporting `xlink:href` in the data.

#### What information was incorrect, unhelpful, or incomplete?

Older Chrome & Firefox versions _do_ support `xlink:href`. They're missing from this chart.

<img width="699" alt="" src="https://user-images.githubusercontent.com/107569/122004425-80bf1a00-ce08-11eb-8dda-28a676025b9e.png">

#### What did you expect to see?

I expected to see more support for `xlink:href` than `href` since it's the older, more commonly supported attribute. `xlink:href` support should be in the high 90s.

#### Did you test this? If so, how?

I didn't, sorry.

#### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/href
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href

**Comment by queengooborg** [comment]
This is because we don't have the exact version numbers for this particular feature; we just know that it's supported in Chrome at some point, which is why the CanIUse rendering looks a little odd.  We plan on adding a version number soon!

I will be closing this issue, but we will still be tackling this as a part of our key goals for BCD.
