### ISSUE TITLE
css.at-rules.page - <@page rule size option not working properly on mobile chrome browser android>

### ISSUE THREAD

**Issue by GokulYadav98** [mdn/browser-compat-data#11035]
#### What information was incorrect, unhelpful, or incomplete?

@page {
   size: 10in 8in;
}
In Mobile chrome browser, print paper size is not changing to mentioned size. It's default size is in LETTER format. In web browser it works fine.

#### What did you expect to see?

In Mobile browser, during print method - i want the paper size to be customized in the mentioned height for save As Pdf using @page css.

#### Did you test this? If so, how?

I have tested using @page rule css. It's not reflecting the change in mobile chrome android.

<details>
<summary>MDN page report details</summary>

* Query: `css.at-rules.page`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/@page
* Report started: 2021-06-15T07:21:19.946Z

</details>

**Comment by queengooborg** [comment]
I'm unable to confirm this issue with the latest Chrome Android, so I'm going to close this issue.
