### ISSUE TITLE
api.ResizeObserverEntry.contentRect - Safari now supports contentRect

### ISSUE THREAD

**Issue by coatesap** [mdn/browser-compat-data#11075]
#### What information was incorrect, unhelpful, or incomplete?
ResizeObserverEntry.contentRect now seems to be supported by desktop Safari. Tested in v14.1.1.

#### What did you expect to see?
Currently the compatibility table suggests no support for `contentRect` in desktop Safari, so I didn't expect observing it to provide changes to `contentRect.width`, however, it seems to currently work as per other desktop browsers.

#### Did you test this? If so, how?
Created some test code and opened it in desktop Safari:
https://jsfiddle.net/coatesap/480awck1/2/

<details>
<summary>MDN page report details</summary>

* Query: `api.ResizeObserverEntry.contentRect`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserverEntry/contentRect
* Report started: 2021-06-17T07:31:22.592Z

</details>

**Comment by queengooborg** [comment]
This has been resolved by #13836!
