### ISSUE TITLE
Document HTMLCanvasElement.toDataURL supported formats

### ISSUE THREAD

**Issue by gsnedders** [mdn/browser-compat-data#11070]
https://bugs.webkit.org/show_bug.cgi?id=226950 shows some degree of developers asking for further support; the MDN article for this API also says (in text) "Chrome also supports the image/webp type", which suggests there's value in giving compat data here.

**Comment by queengooborg** [comment]
Looks like the WebP feature was added in #13897!  We probably also want to add JPEG as a subfeature, unless its data matches with `toDataURL`.
