### ISSUE TITLE
Initial support of RTCPeerConnection and RTCConfiguration in Firefox is contradictory

### ISSUE THREAD

**Issue by foolip** [mdn/browser-compat-data#11136]
Filing this after merging https://github.com/mdn/browser-compat-data/pull/11119 too fast.

There are a few problems here:
- The data doesn't match https://caniuse.com/rtcpeerconnection
- `mozRTCPeerConnection` isn't represented
- Manual testing shows that `new RTCPeerConnection()` in Firefox 22 actually doesn't work, but `new mozRTCPeerConnection()` does
- It makes no sense to claim that `RTCConfiguration` is supported before `RTCPeerConnection`

**Comment by queengooborg** [comment]
RTCConfiguration has been removed, so this is no longer relevant.
