### ISSUE TITLE
css.properties.appearance - Version when dropped missing

### ISSUE THREAD

**Issue by zomp** [mdn/browser-compat-data#11137]
#### What information was incorrect, unhelpful, or incomplete?
The support seems to be dropped.

#### What did you expect to see?
When (at best even why) the support was dropped.

#### Did you test this? If so, how?
I tried to open the demo from https://developer.mozilla.org/en-US/docs/Web/CSS/appearance on Firefox 89 and Chromium 91 and `appearance` had no effect there (all texts were the same). On Kubuntu 21.10.

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.appearance`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/appearance
* Report started: 2021-06-17T22:02:03.452Z

</details>

**Comment by queengooborg** [comment]
This property is still supported in all current browsers, so I'm not sure how you had determined the property wasn't supported.  I'm going to close this issue accordingly -- if it's still an issue, please feel free to open a new issue with test code that we can use to confirm lack of support!
