### ISSUE TITLE
css.properties.aspect-ratio - full support in Safari 15

### ISSUE THREAD

**Issue by johnspurlock** [mdn/browser-compat-data#11135]
#### What information was incorrect, unhelpful, or incomplete?
css.properties.aspect-ratio json data for Safari

this info flows into caniuse, which is where I noticed it.

#### What did you expect to see?
Supported as of version 15.

#### Did you test this? If so, how?
Yes, works using Safari 15 on the first betas of iOS 15 and macOS 15.

#### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?
https://developer.apple.com/documentation/safari-release-notes/safari-15-beta-release-notes#CSS
https://developer.apple.com/videos/play/wwdc2021/10029

**Comment by Schweinepriester** [comment]
I believe this issue can be closed, because it has been updated already? 0:-)
- https://developer.mozilla.org/en-US/docs/Web/CSS/aspect-ratio#browser_compatibility
- https://caniuse.com/mdn-css_properties_aspect-ratio

**Comment by johnspurlock** [comment]
Yes, appears to have been fixed by 3ff9c6080b8f26b7bc044355e2f91df81293021a
