### ISSUE TITLE
api.Navigator.vibrate - Opera on Desktop has it

### ISSUE THREAD

**Issue by Krisseck** [mdn/browser-compat-data#11143]
#### What information was incorrect, unhelpful, or incomplete?
Browser compatibility table claims that Opera on Desktop does not have support for `navigator.vibrate()`, although it does

#### What did you expect to see?
Opera on Desktop has support for `navigator.vibrate()`

#### Did you test this? If so, how?
Tested on two desktop computers, Linux and Win10

`Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36 OPR/77.0.4054.64`

`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36 OPR/76.0.4017.177`

Both of these browsers have `navigator.vibrate()`

<details>
<summary>MDN page report details</summary>

* Query: `api.Navigator.vibrate`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/vibrate
* Report started: 2021-06-18T06:21:10.970Z

</details>

**Comment by queengooborg** [comment]
This had been fixed by #14287!
