### ISSUE TITLE
Meaningless "Promise-based version." notes for RTCPeerConnection

### ISSUE THREAD

**Issue by foolip** [mdn/browser-compat-data#11158]
For example:
https://github.com/mdn/browser-compat-data/blob/2d29a84f220d74b6d957ec4767ffb55b88ee0b5f/api/RTCPeerConnection.json#L105-L114

This is a note for the `new RTCPeerConnection()` constructor, and makes no sense. This seems to be have copied and spread around at some point, and only partially clean up.

**Comment by lucalves** [comment]
Would the solution be to remove the note?

**Comment by foolip** [comment]
Yep, most of those notes can go. A few methods originally didn't return a promise and for those they can stay. Then all browsers should have the note, most likely.

**Comment by AnilSeervi** [comment]
I'm confused. Do we need to remove all the `notes: "Promise-based version."` lines from the file?

**Comment by foolip** [comment]
@AnilSeervi not quite, but all of the cases where Opera has these notes but Chrome doesn't are wrong and should be removed.
