### ISSUE TITLE
api.MediaRecorder - Length of video time means duration of video is not there 

### ISSUE THREAD

**Issue by Neel7317** [mdn/browser-compat-data#11177]
#### Did you test this? If so, how?

<details>
<summary>MDN page report details</summary>

* Query: `api.MediaRecorder`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MediaStream_Recording_API
* Report started: 2021-06-21T11:57:55.618Z

</details>

**Comment by vinyldarkscratch** [comment]
Can you provide more details by filling out the issue template?

**Comment by vinyldarkscratch** [comment]
Closing since there is no actionable information for this issue.  Feel free to reply to this thread if you have more info and we'll happily take another look into this issue!
