### ISSUE TITLE
javascript.builtins.Array.slice - <filename 	/activeview/js/current/rx_lidar.js>

### ISSUE THREAD

**Issue by Nortyboy1983** [mdn/browser-compat-data#11170]
Firefox 89.01 for Windows 10 pro 20H2
#### What information was incorrect, unhelpful, or incomplete?
GEThttps://pagead2.googlesyndication.com/pagead/js/r20210616/r20110914/abg_lite_fy201

 GEThttps://pagead2.googlesyndication.com/pagead/js/r20210616/r20110914/client/window_fo

#### What did you expect to see?

Googlemaps
#### Did you test this? If so, how?

no, dont know how
![2021-06-20 (3)](https://user-images.githubusercontent.com/48383297/122687995-dedd6a00-d219-11eb-9554-2524027b77be.png)

<details>
<summary>MDN page report details</summary>

* Query: `javascript.builtins.Array.slice`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/slice
* Report started: 2021-06-20T20:36:16.738Z

</details>

**Comment by vinyldarkscratch** [comment]
Closing as this has nothing to do with the reported feature, or even BCD.
