### ISSUE TITLE
XMLHttpRequest isn't supposed to be supported in service workers

### ISSUE THREAD

**Issue by foolip** [mdn/browser-compat-data#11183]
We have a lot of "Not supported in service workers" notes here:

https://github.com/mdn/browser-compat-data/blob/f3e3413a9232737e0b3576390eb11117222f7b4a/api/XMLHttpRequest.json#L2071-L2118

Per https://xhr.spec.whatwg.org/#interface-xmlhttprequest (`[Exposed=(Window,DedicatedWorker,SharedWorker)]`) this isn't supposed to be supported in service workers, so these notes aren't really appropriate for BCD. https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest already has this note:
> This feature is available in Web Workers, except for Service Workers

That seems like the right place to document this, and we should remove the notes from BCD.

**Comment by Blakelist7** [comment]
Hey, @foolip 
If I am getting this right, we have to remove https://github.com/mdn/browser-compat-data/blob/f3e3413a9232737e0b3576390eb11117222f7b4a/api/XMLHttpRequest.json#L2071-L2118 
right?

**Comment by foolip** [comment]
@Blakelist7 we shouldn't remove that whole part of the file, but the notes there talking about service worker support, and any others in the file.

**Comment by Blakelist7** [comment]
Could you assign it to me?

**Comment by foolip** [comment]
@Blakelist7 done!
