### ISSUE TITLE
Sec-CH-UA User Client Hints - Time to document?

### ISSUE THREAD

**Issue by hamishwillee** [mdn/browser-compat-data#11190]
*User Agent Client Hints*  went into [Chrome 89](https://www.chromestatus.com/feature/5995832180473856). 
- The [spec](https://wicg.github.io/ua-client-hints/) is a W3C Draft Community Group Report - which presumably counts as "on a standard track".
- Mozilla's [position](https://mozilla.github.io/standards-positions/) is "not harmful"
- There is no signal from Safari according to [that Chrome 89 info](https://www.chromestatus.com/feature/5995832180473856)

The MDN convention on [When to document new technologies](https://developer.mozilla.org/en-US/docs/MDN/Guidelines/Conventions_definitions#when_to_document_new_technologies) doesn't give me clear direction on whether we document this on MDN and in BCD. I feel it probably is time, but perhaps I'm overly influenced by chromium's effective market share.

Is it time? 

FYI @Elchi3 @ddbeck

**Comment by ddbeck** [comment]
Ordinarily, I'd say that if a browser is shipping a feature, then it should be represented in BCD. That feels like an obvious threshold, so I'm concerned that I'm missing some key detail that would suggest otherwise in this case.

**Comment by hamishwillee** [comment]
You're not missing any key detail. The question arises because [When to document new technologies ](https://developer.mozilla.org/en-US/docs/MDN/Guidelines/Conventions_definitions#when_to_document_new_technologies) for MDN includes the level of interest from other browser vendors as part of the calculation.

If BCD has slightly different standard of "is in a browser" that's all I need to know. Will look at this on Friday.
