### ISSUE TITLE
CSS types – basic-shape's ellipse() missing

### ISSUE THREAD

**Issue by teoli2003** [mdn/browser-compat-data#11208]
#### What information was incorrect, unhelpful, or incomplete?
`ellipse()` is missing (we have the others like `circle()` or `polygon()` and the live sample on MDN Web docs shows that some browsers support it at least.

#### Did you test this? If so, how?
(Live sample)

#### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?
https://developer.mozilla.org/en-US/docs/Web/CSS/basic-shape/ellipse()

**Comment by Blakelist7** [comment]
Hey, @teoli2003 if I am not wrong, you wish to add an image like <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/basic-shape/circle()#examples">circle</a> to <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/basic-shape/ellipse()#basic_ellipse_example">Ellipse</a>. Also if this is what this issue says, I don't think we have an image for <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/basic-shape/polygon()#basic_polygon_example">Polygon</a> as well.

**Comment by teoli2003** [comment]
HI @Blakelist7, no that's about adding compatibility data for ellipse in https://github.com/mdn/browser-compat-data/blob/main/css/types/basic-shape.json.

It shouldn't be too difficult to dig this info out, but I hadn't time for it that day. For example, https://bugzilla.mozilla.org/show_bug.cgi?id=1326406 clearly hint at Fx 54, the same as `circle()`. But we still need chromium info, then test with old browser to validate.

**Comment by Blakelist7** [comment]
ohk, now I get it, we have to add a table that shows which browser's support `ellipse()`
right?

Could you assign this to me?
Thanks :)

**Comment by teoli2003** [comment]
Hi @blakelist7. I can't assign it to it (I don't have the rights to do it). Feel free to submit the PR for it, though.

What has to be done is to _edit the **json** file_ I linked too, not to touch the content page: browser compat tables are filled from data in these json files.
