### ISSUE TITLE
IE supports Array.prototype.includes

### ISSUE THREAD

**Issue by kingeke** [mdn/browser-compat-data#11211]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes

Can this be updated as IE supports Array.prototype.includes, thank you

**Comment by zloirock** [comment]
Nope.

**Comment by kingeke** [comment]
ok, why not?, I just tested it on IE and it worked

**Comment by zloirock** [comment]
It's not supported in IE. Seems you tested it on a page with a polyfill.

**Comment by kingeke** [comment]
You're absolutely right, my apologies.
