### ISSUE TITLE
Update compat data for "Array.prototype.at()"

### ISSUE THREAD

**Issue by segandiaye** [mdn/browser-compat-data#11215]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/at

#### What information was incorrect, unhelpful, or incomplete?

JavaScript Demo: Array.at() not working well

That reurn an error ```js Error: array1.at is not a function ```

#### Specific section or headline?

JavaScript Demo: Array.at()

Example: 

```js
const array1 = [5, 12, 8, 130, 44];

let index = 2;

console.log(`Using an index of ${index} the item returned is ${array1.at(index)}`);
```

#### What did you expect to see?

Should output ```js Using an index of 2 the item returned is 8 ```

#### Did you test this? If so, how?

Yes I tested it locally and on https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/at

Thank you in advance and I'm happy with your work.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/array/at`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/at
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/array/at/index.html
* Last commit: https://github.com/mdn/content/commit/3c394e62835ef7b443fb5208343ecba892bbf6d5
* Document last modified: 2021-05-26T11:36:38.000Z

</details>

**Comment by queengooborg** [comment]
The `at()` method is now available in almost all browsers, and we've added data for all browsers so far.  I think it's safe for us to close this issue now!
