### ISSUE TITLE
block/inline shorthands in Edge needs updating

### ISSUE THREAD

**Issue by o-t-w** [mdn/browser-compat-data#11233]
Edge classes padding-block, padding-inline, margin-block, margin-inline, border-block, border-inline as 
"Can be enabled by setting enable-experimental-web-platform-features to enabled". This is now out of date. I tested on Edge 91 and these features are all supported. I'm not that sure which version of Edge added support.

**Comment by queengooborg** [comment]
Looks like this has been resolved in #10751 and #12202!
