### ISSUE TITLE
api.Element.mouseenter_event - onmouseenter not working with Brave browser

### ISSUE THREAD

**Issue by RealNerdEthan** [mdn/browser-compat-data#11231]
#### What information was incorrect, unhelpful, or incomplete?
onmouseenter isn't working in the Brave browser. 
Browser: Version 1.25.73 Chromium: 91.0.4472.106 (Official Build) (64-bit)
OS: Windows 10 Pro 21H1

#### What did you expect to see?
When moving my mouse over a button, I expected to see a console.log message.

#### Did you test this? If so, how?
Yes I tested my code by loading the page in Internet Explorer. When hovering over the button I get the console.log message I was expecting.

[onmouseenter code.txt](https://github.com/mdn/browser-compat-data/files/6709202/onmouseenter.code.txt)

<details>
<summary>MDN page report details</summary>

* Query: `api.Element.mouseenter_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/mouseenter_event
* Report started: 2021-06-24T12:20:54.774Z

</details>

**Comment by vinyldarkscratch** [comment]
I gave your test code a try on the latest Chrome without problems.  I don't think that Brave would disable support for such a basic feature, but even if it does, we aren't tracking Brave as a separate browser in BCD as it's a fork of Chrome (and has very little market share, sitting at just [0.05%](https://kinsta.com/browser-market-share/)).

**Comment by RealNerdEthan** [comment]
That's fine. It's up to you what's done about the issue, just bringing it to attention as a known issue.
