### ISSUE TITLE
http.headers.Access-Control-Expose-Headers - Wildcard supported in Safari

### ISSUE THREAD

**Issue by claudepache** [mdn/browser-compat-data#11232]
#### What information was incorrect, unhelpful, or incomplete?

Browser compatibility / [Access-Control-Expose-Headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers) / Wildcard (*)  
Supported in Safari and Safari on iOS: No

#### What did you expect to see?
Supported in Safari and Safari on iOS: yes

Probably: supported since version 13, see Additional informations below.
Probably: Same issue with [Access-Control-Allow-Methods](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Methods) and [Access-Control-Allow-Headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Headers) 

#### Did you test this? If so, how?

Tested: `Access-Control-Expose-Headers: *`: checked as working in both Safari 14.1.1 and Safari Mobile 14.1.1 by issuing a cors `fetch(_, { credentials: 'omit' })` towards a server that issued `Access-Control-Expose-Headers: *` and no `Access-Control-Expose-Headers: X-Foo`.

Not tested: `Access-Control-Allow-Methods: *` and `Access-Control-Allow-Headers: *`

#### Additional informations

Webkit bugs, both marked as resolved between 2019-06-09 and 2019-06-15 (few months before Safari 13 release):
* `Access-Control-Expose-Headers: *`: https://bugs.webkit.org/show_bug.cgi?id=169194
* `Access-Control-Allow-Methods: *` and `Access-Control-Allow-Headers: *`: https://bugs.webkit.org/show_bug.cgi?id=165508

<details>
<summary>MDN page report details</summary>

* Query: `http.headers.Access-Control-Expose-Headers`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers
* Report started: 2021-06-24T13:23:27.625Z

</details>

**Comment by claudepache** [comment]
@Elchi3 Besides `Access-Control-Expose-Headers: *`, there are also `Access-Control-Allow-Methods: *` and `Access-Control-Allow-Headers: *` that should probably be corrected (see top comment).

**Comment by Elchi3** [comment]
Thanks @claudepache. Reopening.
