### ISSUE TITLE
svg.attributes.xlink.xlink_title - <>

### ISSUE THREAD

**Issue by ArdianIbishi** [mdn/browser-compat-data#11242]
#### Did you test this? If so, how?

<details>
<summary>MDN page report details</summary>

* Query: `svg.attributes.xlink.xlink_title`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:title
* Report started: 2021-06-25T14:06:32.835Z

</details>

**Comment by vinyldarkscratch** [comment]
I'm closing this because the issue template has not been filled out and there is no actionable information.
