### ISSUE TITLE
css.at-rules.supports - Safari now supports @supports selector()

### ISSUE THREAD

**Issue by fritz-c** [mdn/browser-compat-data#11253]
#### What information was incorrect, unhelpful, or incomplete?

Safari was marked as not supporting the `selector()` syntax for `@supports`.

#### What did you expect to see?

Safari should be marked as supporting the `selector()` syntax for `@supports`, at least as of version 14.1.1. The bug tracker link referenced in the existing table shows that it was merged into WebKit in March 2021, and I can confirm it working as expected in Safari 14.1.1.

#### Did you test this? If so, how?

Yes. I used one of the test files provided in the bug tracker:
`at-supports-041.html` from
https://bugs.webkit.org/attachment.cgi?id=407424&action=prettypatch

<details>
<summary>MDN page report details</summary>

* Query: `css.at-rules.supports`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/@supports
* Report started: 2021-06-26T00:38:33.455Z

</details>

**Comment by queengooborg** [comment]
This has been resolved by #11302!
