### ISSUE TITLE
Remove Safari releases with matching/similar engine versions?

### ISSUE THREAD

**Issue by queengooborg** [mdn/browser-compat-data#11258]
This issue is the desktop-based counterpart of https://github.com/mdn/browser-compat-data/issues/10723.  In the other issue, we are talking about the removal of Safari iOS releases with matching WebKit versions, and were most likely added simply because there was a Safari version with a matching number, and at the time (during the wiki tables era), nobody knew whether or not the iOS versions were a significant change.

The same also seems to apply with some Safari desktop versions, for one reason or another.  These versions include:

- [x] Safari 3.2 -> 3.1 (https://github.com/mdn/browser-compat-data/pull/11266)
- [x] Safari 6.1 -> 7 (6.1 is a backport of 7, see #9423)

CC @foolip

**Comment by foolip** [comment]
9 and 9.1 are interested, I never suspected those before. Showing the differences between them would be great.

**Comment by vinyldarkscratch** [comment]
I'm attempting to get a copy of Safari 9.0 right now, but my goodness is it proving to be challenging...  Safari 9.0 is supposed to be bundled with El Capitan, but I'm only able to find El Capitan releases with 9.1 bundled, and only Safari 10.1 is available in the App Store.

Reading Apple's documentation, there are some clear differences between 9 and 9.1, such as support for the `picture` element, many more added CSS properties, and more, but not as much difference as 10 vs 10.1 and similar.

**Comment by vinyldarkscratch** [comment]
After further review and discussion, @foolip and I decided to keep Safari 9.1 as a separate browser version.  Philip's comment in our chat regarding the matter was:

> ￼I would say keep it since it was deemed significant enough to create https://developer.apple.com/library/archive/releasenotes/General/WhatsNewInSafari/Articles/Safari_9_1.html and also it was 6 months after 9.0 and 6 months before 10.

**Comment by foolip** [comment]
https://github.com/mdn/browser-compat-data/pull/11266 is merged now, what remains is 6.1 with a lot of discussion in https://github.com/mdn/browser-compat-data/issues/9423 even though it was filed about 6.2.

**Comment by queengooborg** [comment]
We have now removed Safari 6.1 from the data, so this is now complete!  Whoo!
