### ISSUE TITLE
api.SVGAltGlyphElement - Not supported by Firefox and Chrome

### ISSUE THREAD

**Issue by saschanaz** [mdn/browser-compat-data#11265]
#### What information was incorrect, unhelpful, or incomplete?

SVGAltGlyphElement does not exist but BCD argues it does

#### What did you expect to see?

Some proper `removed_version` values

#### Did you test this? If so, how?

DevTools console

<details>
<summary>MDN page report details</summary>

* Query: `api.SVGAltGlyphElement`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/SVGAltGlyphElement
* Report started: 2021-06-26T21:13:13.136Z

</details>

**Comment by queengooborg** [comment]
This has been fixed by #17422!
