### ISSUE TITLE
Issue with "<display-legacy>": (short summary here please)

### ISSUE THREAD

**Issue by DarknessChaser** [mdn/browser-compat-data#11274]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/display-legacy

#### What information was incorrect, unhelpful, or incomplete?
According to caniuse, inline-flex only started partial support in IE10. The information now seems to be sstarted partial support in IE8

#### Specific section or headline?
Support of inline-flex `https://developer.mozilla.org/en-US/docs/Web/CSS/display-legacy#support_of_inline-flex`

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/display-legacy`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/display-legacy
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/display-legacy/index.html
* Last commit: https://github.com/mdn/content/commit/4df8fc624cb319731c0e0ad052348b2b0f62e59e
* Document last modified: 2021-06-11T11:56:01.000Z

</details>

**Comment by queengooborg** [comment]
Sorry it's taken so long to respond.  Could you clarify what data you were expecting to see in the BCD tables?

**Comment by DarknessChaser** [comment]
> Sorry it's taken so long to respond. Could you clarify what data you were expecting to see in the BCD tables?

![image](https://user-images.githubusercontent.com/22089140/152910467-87eedbed-68a6-4186-81b3-4e16beacd34d.png)
now 👆
I hope 👇
![image](https://user-images.githubusercontent.com/22089140/152910652-60e2ee7b-946a-4e20-a5ad-3fa3aa08a945.png)

**Comment by queengooborg** [comment]
So since this issue was opened, we've actually frozen IE data entirely and will be removing it from BCD in the near future.
