### ISSUE TITLE
css.properties.scroll-margin-inline-start - Not supported on Safari 14.1.1

### ISSUE THREAD

**Issue by raycherr** [mdn/browser-compat-data#11273]
#### What information was incorrect, unhelpful, or incomplete?
Unsupported property name warning 
Safari 14.1.1
Mac OS 11.4

#### What did you expect to see?
To be supported as indicated in the browser compatibility table [here](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-margin-inline-start#:~:text=Initial%20definition-,Browser%20compatibility,-Report%20problems%20with)

#### Did you test this? If so, how?
![image](https://user-images.githubusercontent.com/11989003/123573197-1478e900-d800-11eb-9acf-0078a78e6173.png)

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.scroll-margin-inline-start`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-margin-inline-start
* Report started: 2021-06-28T02:44:08.408Z

</details>

**Comment by queengooborg** [comment]
This has been fixed by #19589!
