### ISSUE TITLE
`ipRecording` might be more accurate?

### ISSUE THREAD

**Issue by murtinibima22** [mdn/browser-compat-data#11270]
`ipRecording` might be more accurate?

_Originally posted by @nicolasburtey in https://github.com/GaloyMoney/galoy/pull/270#discussion_r659340030_

**Comment by nicolasburtey** [comment]
how is a commet in this [commit](GaloyMoney/galoy#270 (comment)) ends up as an issue on this unrelated repo?

**Comment by vinyldarkscratch** [comment]
It happens way more often than one might think, unfortunately -- whether it's someone who just doesn't understand how GitHub works or intentionally trying to disrupt a project's productivity, spam issues, comments, and PRs are created all the time.  Sorry that you received a notification for this!
