### ISSUE TITLE
SubtleCrypto.deriveBits() with PBKDF2 and output length > 2048 bits

### ISSUE THREAD

**Issue by Gu7z** [mdn/browser-compat-data#11283]
By @juanelas in this [issue](https://github.com/mdn/content/issues/1671)

**Summary**
*What is the problem?*
SubtleCrypto.deriveBits() with PBKDF2:

- Length argument must be a multiple of 8. This is congruent with the RFC but should be documented
- Length argument does not accept an input > 256 bytes. This constraint is not defined in the original PBKDF2 and should be considered to be removed.

**Steps To Reproduce (STR)**
*How can we reproduce the problem?*
Just run the following html in firefox:

```html
<html>
<head><title>pbkdf2 - Firefox</title></head>
<body>
  <script>
    (async () => {
      const password = new ArrayBuffer() // empty password
      const passwordKey = await crypto.subtle.importKey('raw', password, 'PBKDF2', false, ['deriveBits'])
      const params = { // pbkdf2 params
        name: 'PBKDF2',
        hash: 'SHA-256',
        salt: new ArrayBuffer(),  // empty salt
        iterations: 1
      }
      crypto.subtle.deriveBits(params, passwordKey, 8 * 64).then(
        derivedKey => console.log(derivedKey), // no error since Lenght is a multiple of 8 and Length <= 256 bytes
        err => console.log("ERROR: can't derive more than 256 bytes (2048 bits)",err)
      )
      crypto.subtle.deriveBits(params, passwordKey, 8 * 384).then(
        derivedKey => console.log(derivedKey),
        err => console.log("ERROR: can't derive more than 256 bytes (2048 bits)",err) // error since Lenght > 256 bytes
      )
    })()
  </script>
</body>
</html>
```

**Actual behavior**
crypto.subtle.deriveBits(params, passwordKey, 8 * 384) produces error since 384 > 256

**Expected behavior**
To just derive 384 bytes (3072 bits)

**Additional context**
Sometimes you need an arbitrary output length for the PBKDF2 function, such as when using it to compute scrypt that you need to output p * 128 * r (with r usually 8 and p between 1 and 16).

**Comment by ddbeck** [comment]
This might be related to https://github.com/mdn/browser-compat-data/issues/8752, though I'm not well acquainted enough with this API to say that it's a duplicate.

**Comment by sideshowbarker** [comment]
> This might be related to #8752, though I'm not well acquainted enough with this API to say that it's a duplicate.

I think @twiss might be able to give some insight.

See also https://github.com/mdn/content/issues/1671 (from which this BCD issue arose)

**Comment by twiss** [comment]
Hello :wave: I think this is a separate issue / incompatibility, since this one is an issue in Firefox, whereas #8752 appears to be an issue in Safari. It's also a different function, and https://bugzilla.mozilla.org/show_bug.cgi?id=1469482#c2 (which corresponds to this issue) links to some code which seems fairly specific to this function and algorithm.

**Comment by Gu7z** [comment]
Any updates?

**Comment by twiss** [comment]
@Gu7z Are you asking for an update on the bug in Firefox, or about documenting the bug on MDN? For the former, the bugzilla issue I linked is a better place to ask; for the latter, I don't think there is any, but I assume this repo would be happy to accept a PR, if you want to make one? (I assume the same is true for the Firefox issue ^.^)

**Comment by Gu7z** [comment]
@twiss Where can I open an issue to report this bug for firefox? On Bugzilla? :eyes:

**Comment by twiss** [comment]
It's already reported, that's the issue I linked: https://bugzilla.mozilla.org/show_bug.cgi?id=1469482
