### ISSUE TITLE
`api.Notification` - Notes for Chrome are incorrectly structured and dubious

### ISSUE THREAD

**Issue by ddbeck** [mdn/browser-compat-data#11288]
#### What information was incorrect, unhelpful, or incomplete?

The notes field for the Chrome entry for `api.Notifications` contains a very long note that seems to be more like four notes in one:

https://github.com/mdn/browser-compat-data/blob/31e399e619b4180a42174d794c825d43af821238/api/Notification.json#L11

(It's unclear what all the notes mean, exactly (e.g., it references `navigator.webkitNotifications`, which I'm not certain is a real thing), so I didn't want to simply split them.)

#### What did you expect to see?

At very least, an array of notes.

#### Did you test this? If so, how?

No. The veracity of the notes needs to investigating.

#### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

Probably related to some of the problems with `api.Notification.Notification` raised in https://github.com/mdn/browser-compat-data/issues/7923.

**Comment by foolip** [comment]
These notes were rewritten in https://github.com/mdn/browser-compat-data/pull/12032 + https://github.com/mdn/browser-compat-data/pull/15822.
