### ISSUE TITLE
api.KeyboardEvent.getModifierState.*_parameter are misnamed (after value, not name)

### ISSUE THREAD

**Issue by foolip** [mdn/browser-compat-data#11295]
Example:
https://github.com/mdn/browser-compat-data/blob/f01af3d359ad9681b3687273f4050bdc4f3629b1/api/KeyboardEvent.json#L393-L440

This represents the support of `event.getModifierState("Accel")` but is named like the [Parameters and parameter object features](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines.md#parameters-and-parameter-object-features) guideline would suggest for a parameter named `accel`. The parameter name in [the spec](https://w3c.github.io/uievents/#dom-keyboardevent-getmodifierstate) is `keyArg`, there's just that one argument with name different possible values.

Aside: The `Arg` suffix to argument names is unusual in web specs and I don't think we should copy it into MDN/BCD.

@ddbeck is there a guideline for how to name support for `method(value)` for many different supported `value`?

**Comment by ddbeck** [comment]
> @ddbeck is there a guideline for how to name support for `method(value)` for many different supported `value`?

No, we haven't covered this case. The closest thing I can think of this would be in CSS, where properties have supported values, but there's no equivalent to the parameter name. Maybe we could build on the existing parameter guideline though, something like: name features for specific argument values in the form `valuename_value` (if the parent feature is `paramname_parameter`) or `paramname_parameter_valuename_value` (if the parent feature is the method itself). Admittedly, that's a big ugly, but has the benefit of being unimaginative.

> Aside: The `Arg` suffix to argument names is unusual in web specs and I don't think we should copy it into MDN/BCD.

The spec editors would think it's a nuisance if I opened a PR changing that, right? 😆

**Comment by foolip** [comment]
> The spec editors would think it's a nuisance if I opened a PR changing that, right? 😆

I've sent lots of spec PRs in the name of consistency, so I don't think they'd consider a nuisance, no :)

**Comment by foolip** [comment]
`key_parameter_ Accel` seems OK here. I'm not sure what the `valuename` component would be here, the type of the argument is `DOMString`, but that's not especially interesting to include, I doubt it would be ever be needed for disambiguation. (It would be something like both the number 0 and the string "0" being different supported values worth distinguishing, which feels far fetched.)

**Comment by ddbeck** [comment]
Hmm, you're right that was pretty undercooked. What about this sort of approach? Should capture the farfetched cases but be sort of straight forward in the usual cases?

- For fixed parameter values (e.g., specific string, number, etc.):
  - If the parent feature is a parameter feature, then a value should be represented as a subfeature named for the value itself. For example, for a feature `api.KeyboardEvent.getModifierState.keyArg_parameter`, you could have subfeatures for `Accel`, `Alt`, etc.
  - If the parent feature is a method feature, then the value should be represented as a subfeature named for the parameter feature that would exist, a `_value_` infix, and the value itself. For example, for a feature `api.KeyboardEvent.getModifierState.keyArg_parameter_value_Accel`.
- For parameter types (e.g., DOMString, etc.):
  - If the parent feature is a parameter feature, then the type should be represented as a subfeature named for the type, with. For example, for a feature `api.KeyboardEvent.getModifierState.keyArg_parameter`, you could have a subfeature `DOMString`.
  - If the parent feature is a method feature, then the type should be represented as a subfeature named for the parameter, a `_type_` infix, type itself. For example, for a feature `api.KeyboardEvent.getModifierState.keyArg_parameter_type_DOMString`.

I could write up some guidelines for the descriptions too.

**Comment by foolip** [comment]
That sounds pretty comprehensive! It seems to leave open the choice of whether to have a feature for the parameter itself or just a bunch of features for it's possible values, but that flexibility seems OK to me, we can always make it stricter later if the resulting variety of style is too much.

**Comment by ddbeck** [comment]
OK, great. I'll open a PR to amend the data guidelines for parameters (you also had some ideas about the ordinal stuff, so I'm inclined to drop that too).

And yes, I considered that it might be overly flexible, but I thought it might be obnoxious to require parameter features to be parents of value features. If a parameter is widely supported (such that it never got its own subfeature), then it seems a bit annoying to introduce one to capture one additional point. Though I maybe I can include some verbiage to favor the parameter features when there's more than one or something…
