### ISSUE TITLE
Thank you "issue"!

### ISSUE THREAD

**Issue by epistemex** [mdn/browser-compat-data#1130]
Thank you guys for this. it's no doubt a tremendous amount of work you have put into it! Looking pretty good.

This has already come (hopefully) useful in form a swag tool for those interested: [mdncomp](https://github.com/epistemex/mdncomp) to see the data directly in the console.

**Comment by Elchi3** [comment]
Wow, very nice project! Thanks for sharing it with us!

**Comment by teoli2003** [comment]
Yes, thank you for mdncomp. @jwhitlock made a PR to list it there: https://github.com/mdn/browser-compat-data#projects-using-the-data

Such tools is exactly what we had in mind when we started this project: "Free the Data"

**Comment by jwhitlock** [comment]
I feel properly thanked.
