### ISSUE TITLE
Drop NodeJS v10 (and maybe even more?)

### ISSUE THREAD

**Issue by queengooborg** [mdn/browser-compat-data#11311]
Since NodeJS v10 is no longer in LTS, I'd say that it's time for us to drop support for it.  However, since BCD consumers are no longer bound to any NodeJS versions thanks to our bundled releases, I'm thinking that we could raise the minimum version even higher, dropping v12 as well.  This NodeJS requirement only affects the BCD contributors, and already we're not running tests for anything lower than NodeJS v14 in GitHub Actions.  Additionally, by raising the NodeJS requirement higher, we'll be able to upgrade our linter/test dependencies easier.

The big questions to ask are:
- What NodeJS versions are contributors using now?
- Are they willing to upgrade to the latest Active LTS or current NodeJS versions?

What do you think. @ddbeck?

**Comment by ddbeck** [comment]
As of https://github.com/mdn/browser-compat-data/pull/10511, we have a practical requirement that the tests pass for Node's Active LTS release ([right now, that's v14; in October that will need to be bumped to v16](https://nodejs.org/en/about/releases/)); we don't specify a Node version apart from that.

So I'm not sure what you're actually asking to change here. What changes would satisfy this issue that's not already settled by the testing branch protection rule?

**Comment by vinyldarkscratch** [comment]
We have a NodeJS version specified in the package.json for our contributors, which is currently set to v10.  That's what I'm aiming to bump the requirement for.

**Comment by vinyldarkscratch** [comment]
I've just submitted a PR to demonstrate what I'm talking about, if you'd like to take a look!
