### ISSUE TITLE
api.HTMLEmbedElement - Safari does not support getSVGDocument()

### ISSUE THREAD

**Issue by Abdull** [mdn/browser-compat-data#11358]
At least in Safari 14, `getSVGDocument()` does not work.

Calling `someSvgEmbedElement.getSVGDocument()` results in Safari throwing `NotSupportedError: The operation is not supported.`.

 Also see https://stackoverflow.com/q/31534637/923560 .

<details>
<summary>MDN page report details</summary>

* Query: `api.HTMLEmbedElement`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLEmbedElement
* Report started: 2021-07-01T16:47:49.090Z

</details>

**Comment by vinyldarkscratch** [comment]
This seems quite contradictory to its reported support all the way back in Safari 3.  Can you provide an example of where this method throws said error?

**Comment by Abdull** [comment]
https://codepen.io/abdull-the-typescripter/pen/YzVXmZx?editors=1111

Couldn't make this Codepen fully comprehensive as I would need to find a codepen.io-hostname-hosted SVG file.

But nevertheless, in Safari it throws that `NotSupportedError: The operation is not supported.`.

**Comment by vinyldarkscratch** [comment]
Okay, so running the Codepen, I get the same error that you are.  That is, until I reload the page with the SVG already cached.  As such, I think it has something to do with Safari stating the method isn't supported if it doesn't recognize an SVG document, including if it isn't loaded.

Thus, I'd say that one would need to ensure the document is loaded before performing actions using the functions.  I think this is something that should be documented in the MDN article whenever it gets written.
