### ISSUE TITLE
css.properties.padding-block/margin-block/margin-inline - Supported in Edge

### ISSUE THREAD

**Issue by saschanaz** [mdn/browser-compat-data#11383]
#### What information was incorrect, unhelpful, or incomplete?

They are supported in Edge

#10751 only fixed padding-inline and the remainings are still to be fixed.

#### What did you expect to see?

Proper version numbers

#### Did you test this? If so, how?

The MDN examples work

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.padding-block`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/padding-block
* Report started: 2021-07-04T15:34:27.990Z

</details>

**Comment by saschanaz** [comment]
It could also be worth to check opera for Android support.

**Comment by foolip** [comment]
I can confirm with these test on Edge 91:
https://mdn-bcd-collector.appspot.com/tests/css/properties/padding-block
https://mdn-bcd-collector.appspot.com/tests/css/properties/margin-block
https://mdn-bcd-collector.appspot.com/tests/css/properties/margin-inline

I haven't tested Opera for Android, but think we can safely mirror all Chromium-based browsers here.

**Comment by foolip** [comment]
@vinyldarkscratch can you fix this? Probably mdn-bcd-collector can just fill in the right versions.
