### ISSUE TITLE
Issue with `circle()`: not supported in Firefox 54

### ISSUE THREAD

**Issue by Blakelist7** [mdn/browser-compat-data#11381]
#### What information was incorrect, unhelpful, or incomplete?
Firefox 54 does not support `circle()`.
#### What did you expect to see?
As I can check, Firefox supports `circle()` from Firefox 62.
#### Did you test this? If so, how?
Yes
#### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/basic-shape/circle()
https://developer.mozilla.org/en-US/docs/Web/CSS/basic-shape/circle()#basic_circle

**Comment by Blakelist7** [comment]
@vinyldarkscratch should I create different issues for `polygon()` and `inset()` or merge them in the same issue?

**Comment by teoli2003** [comment]
Pay attention that circle() may start working on clip-path: and on shape-outside: at different-moment.

The example use only one of the two I think. As it is a CSS function of a type, we need to know the earliest of the two.

Bugzilla (https://bugzilla.mozilla.org/show_bug.cgi?id=1247229 ) hints at Fx 54 (that's a hint though).

**Comment by Blakelist7** [comment]
I think <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/basic-shape/circle()#basic_circle">This</a> example uses `shape-outside` as mentioned in the example.

**Comment by teoli2003** [comment]
Yes, `circle()` on `shape-outside` works on Fx 62 onward (as mentioned [here](https://developer.mozilla.org/en-US/docs/Web/CSS/shape-outside)) while on `clip-path` since 54.

So the page looks correct. Thanks a lot for the investigation!

**Comment by Blakelist7** [comment]
Also, we need to update the https://github.com/mdn/browser-compat-data/blob/main/css/types/basic-shape.json FF version back to 54.
So should I directly submit a PR for that ?

**Comment by teoli2003** [comment]
Oh yes! You are right! Just submit a PR that say "Fixes #<this issue number>" in the desc and when it gets merged, it will automatically close this issue.
