### ISSUE TITLE
css.properties.break-after - Compatibility matrix may show incorrect level of support for Firefox

### ISSUE THREAD

**Issue by leifurhauks** [mdn/browser-compat-data#11407]
I'm using Firefox 89 on Ubuntu 20.04.

#### What information was incorrect, unhelpful, or incomplete?
In pages documenting certain CSS fragmentation properties (break-after, break-inside...), the compatibility matrix at the bottom indicates that the values `page` and `avoid-page` are implemented for print media beginning with Firefox 65. However, `break-after: avoid-page` and `break-inside: avoid-page` appear not to have any effect when printing a page, and if I check the elements to which they apply in the inspector, using the "Toggle print media" button, the inspector indicates that these properties are invalid.

#### What did you expect to see?
If these features are not implemented, I would expect this to be indicated in the compatibility matrix. On the other hand, if they are implemented, I would expect Firefox to handle them correctly (should I file a Firefox bug instead?)

Or, if the behavior is consistent with the spec, perhaps there is missing information regarding situations where these properties do not apply. I've tested this with some very simple layouts, such as the fiddle linked below.

#### Did you test this? If so, how?
As described above, these properties don't appear to affect print layout in Firefox, at least in my environment. The inspector also flags them as invalid, including in this fiddle: https://jsfiddle.net/v2gb9eha/

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.break-after`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/break-after
* Report started: 2021-07-06T18:51:08.288Z

</details>

**Comment by bodograumann** [comment]
I can confirm that. Similarly `break-after: avoid` and `break-before: avoid` work neither in firefox nor chromium. They should probably get a dedicated row in the compatibility table.
Not even `page-break-*` is completely implemented, so it is no suprise that the newer features have even less support.

Cff.:
- https://bugs.chromium.org/p/chromium/issues/detail?id=223068
- https://bugzilla.mozilla.org/show_bug.cgi?id=775617
- https://caniuse.com/css-page-break

**Comment by queengooborg** [comment]
This has been fixed by #16628!
