### ISSUE TITLE
webextensions.api.runtime.onInstalled - Not working on Safari

### ISSUE THREAD

**Issue by juancarlosjr97** [mdn/browser-compat-data#11418]
#### Environment

* macOS Big Sur: 11.4 (20F71)
* Safari: Version 14.1.1 (16611.2.7.1.4)
* Safari Technology Preview: Release 126 (Safari 14.2, WebKit 16612.1.17.10.5)
* Plugin: Swift 5 and React.js
 
#### What information was incorrect, unhelpful, or incomplete?

The `onInstalled` script is running using Chrome Version 91.0.4472.114 (Official Build) (arm64) as background script but it is not running on Safari.

#### What did you expect to see?

A plugin that is using the `webextensions.api.runtime.onInstalled` to open a site it is not getting triggered. 

#### Did you test this? If so, how?

Xcode build the plugin but it did not work 

<details>
<summary>MDN page report details</summary>

* Query: `webextensions.api.runtime.onInstalled`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/onInstalled
* Report started: 2021-06-23T15:37:16.023Z

</details>

**Comment by xeenon** [comment]
I'm not sure what `webextensions.api` is, but Safari does support the `chrome.runtime.onInstalled` and `browser.runtime.onInstalled` events.

**Comment by queengooborg** [comment]
I'm going to close this issue because there hasn't been a response and there is no actionable information to make changes to BCD.
