### ISSUE TITLE
svg.attributes.events - Completely blank

### ISSUE THREAD

**Issue by hieyou1** [mdn/browser-compat-data#11421]
![image](https://user-images.githubusercontent.com/31020711/124840647-13a72c00-df51-11eb-9bf8-2453aa843e04.png)

#### Did you test this? If so, how? Not tested.

<details>
<summary>MDN page report details</summary>

* Query: `svg.attributes.events`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/Events
* Report started: 2021-07-07T23:24:09.209Z

</details>

**Comment by vinyldarkscratch** [comment]
This happens to be an issue with the content, rather than BCD itself.  It looks like the content article is simply pointing to the wrong BCD entry, luckily it's a quick an easy fix!

**Comment by vinyldarkscratch** [comment]
I've opened up https://github.com/mdn/content/pull/6663 to take care of this!  Closing this issue now.
