### ISSUE TITLE
api.MediaSource - appendbuffer API throwing InvalidStateError frequently.

### ISSUE THREAD

**Issue by dhaval-sutaria** [mdn/browser-compat-data#11435]
#### What information was incorrect, unhelpful, or incomplete?
 - While using appendBuffer API on source buffer it is throwing error [  **InvalidStateError** error ] frequently.
 - This is is observed with latest chrome version only [ 91.0.4472.124 ], when running same code on chrome version [ 86.0.4240.75] we are not getting error.
 -  we are appending fragmented mp4 data in source buffer and observed this behavior with latest chrome.
 
#### What did you expect to see?
- It should work properly.

#### Did you test this? If so, how?

<details>
<summary>MDN page report details</summary>

* Query: `api.MediaSource`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MediaSource
* Report started: 2021-07-08T11:26:03.307Z

</details>

**Comment by Earthman100** [comment]
so error is no error Live runtime

**Comment by dhaval-sutaria** [comment]
So what could be the reason for this error. Video is getting stuck whenever we receive this error.

**Comment by Earthman100** [comment]
size of vid. for buffer source stream the parcel would be connecting to live raw invalid entry could be process entry to component add a breakpoint to the inital byte grab buffer size then transport authenticate a code for transport if data is raw like media player app play button would be fragment entry set a negociation for code to authenticate to proper uri security methods; (with proper label as destination not excluding permissions for fragment as known source for consent usage of analytics policy code runtime functions) platform 2 platform exchanges as play button to code functions if it is data apt.api container is mp4 fragments through java or interpreter language.

**Comment by Earthman100** [comment]
this pages analytics show on script when seen code function for components on loading assests for dynamic on runtime that there is a delay  if seen then goes to loading element or assest as () from its runtime assest function for code2code page from codepage code or code from user using Platform device specs or app on platform device specs ad of course app it is dynamicly loading to or from could be an error from above as that it timesout based off authentication or uri source being ment for code to code interpreter rather than connection to codepage code where that platform would be confused with codepage and codepage code interpreter codepage functions rather than code and code interpreter delay would prevent codepage from codepage revisions while in use 
    whenSeen('delayed-loading', () => import('./github/delayed-loading-element'))

**Comment by Earthman100** [comment]
could be old server data api preventing loading old data

**Comment by Earthman100** [comment]
numbers are fun mind boggling is that current societys current google app up to date or ? its a good one

**Comment by Earthman100** [comment]
prolly data ref to old history of last app used thorugh data api insances for updates to current transport destination

**Comment by Earthman100** [comment]
old to new in seconds

**Comment by dhaval-sutaria** [comment]
is there any way to get ref. frame and ref. video for "ISO BMFF Byte Stream Format", we are passing mp4 in this format.

**Comment by vinyldarkscratch** [comment]
Hey @dhaval-sutaria, could you include an example snippet of the code you're using, as well as more details on the error you're getting?  (There should be a message included with the `InvalidStateError`, as the error is generic and not too informative.)

**Comment by dhaval-sutaria** [comment]
![image](https://user-images.githubusercontent.com/87128436/126936119-dc2d04bb-2b66-48d9-b53c-ce8925abeab7.png)
Here I attached error we are getting. Thanks

**Comment by queengooborg** [comment]
Sorry for the long delay in responding.

Based upon what I'm seeing from the errors, it looks like your error has to do with your graphics drivers (D3D11 = DirectX 3D 11).  I've given this a try on my end and haven't found any issues, so it looks to be localized.  I'd probably recommend reinstalling your GPU drivers and see if that does the trick, assuming you're still running into any issues.
