### ISSUE TITLE
Add missing spec URLs for MIDIOutput, MIDIPort, SVGPointList, RTCPeerConnection»getTransceivers, SameSite param of Set-Cookie

### ISSUE THREAD

**Issue by sideshowbarker** [mdn/browser-compat-data#11443]
The BCD data for the features listed below currently lacks `spec_url` values which it should have.

Whoever works on this would just need to check the corresponding specs to get the appropriate URLs to cite, and then open a PR with a patch. I think finding the spec URLs and putting together a patch would take maybe 30 minutes of work in total.

BCD file			|	Feature		 |	MDN article
--------------------------------|------------------------|----------------------------------------------------------------
api/MIDIOutput.json		|	send		 |	https://developer.mozilla.org/docs/Web/API/MIDIOutput/send
api/MIDIPort.json		|	close		 |	https://developer.mozilla.org/docs/Web/API/MIDIPort/close
api/MIDIPort.json		|	connection	 |	https://developer.mozilla.org/docs/Web/API/MIDIPort/connection
api/MIDIPort.json		|	id		 |	https://developer.mozilla.org/docs/Web/API/MIDIPort/id
api/MIDIPort.json		|	manufacturer	 |	https://developer.mozilla.org/docs/Web/API/MIDIPort/manufacturer
api/MIDIPort.json		|	name		 |	https://developer.mozilla.org/docs/Web/API/MIDIPort/name
api/MIDIPort.json		|	onstatechange	 |	https://developer.mozilla.org/docs/Web/API/MIDIPort/onstatechange
api/MIDIPort.json		|	open		 |	https://developer.mozilla.org/docs/Web/API/MIDIPort/open
api/MIDIPort.json		|	state		 |	https://developer.mozilla.org/docs/Web/API/MIDIPort/state
api/MIDIPort.json		|	type		 |	https://developer.mozilla.org/docs/Web/API/MIDIPort/type
api/MIDIPort.json		|	version		 |	https://developer.mozilla.org/docs/Web/API/MIDIPort/version
api/MIDIPort.json		|	MIDIPort	 |	https://developer.mozilla.org/docs/Web/API/MIDIPort
api/RTCPeerConnection.json	|	getTransceivers	 |	https://developer.mozilla.org/docs/Web/API/RTCPeerConnection/getTransceivers
api/SVGPointList.json		|	appendItem	 |	https://developer.mozilla.org/docs/Web/API/SVGPointList/appendItem
api/SVGPointList.json		|	clear		 |	https://developer.mozilla.org/docs/Web/API/SVGPointList/clear
api/SVGPointList.json		|	getItem		 |	https://developer.mozilla.org/docs/Web/API/SVGPointList/getItem
api/SVGPointList.json		|	initialize	 |	https://developer.mozilla.org/docs/Web/API/SVGPointList/initialize
api/SVGPointList.json		|	insertItemBefore |	https://developer.mozilla.org/docs/Web/API/SVGPointList/insertItemBefore
api/SVGPointList.json		|	length		 |	https://developer.mozilla.org/docs/Web/API/SVGPointList/length
api/SVGPointList.json		|	numberOfItems	 |	https://developer.mozilla.org/docs/Web/API/SVGPointList/numberOfItems
api/SVGPointList.json		|	removeItem	 |	https://developer.mozilla.org/docs/Web/API/SVGPointList/removeItem
api/SVGPointList.json		|	replaceItem	 |	https://developer.mozilla.org/docs/Web/API/SVGPointList/replaceItem
api/SVGPointList.json		|	SVGPointList	 |	https://developer.mozilla.org/docs/Web/API/SVGPointList
http/headers/set-cookie.json	|	SameSite	 |	https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

**Comment by teoli2003** [comment]
I opened PR #11444 to fix the regular cases.

There is still the http header subfeature that is defined in experimental, time-limited spec. I think that's the first case we meet this case, so I want to handle it individually.

**Comment by teoli2003** [comment]
Opened w3c/browser-specs#345 for the http case.

**Comment by hanzl035** [comment]
The requested spec_urls  in https://github.com/mdn/browser-compat-data/issues/11443#issue-940372442 have already been added to the main branch.

BCD file | Feature | spec_url
-- | -- | --
api/MIDIOutput.json | send | https://webaudio.github.io/web-midi-api/#dom-midioutput-send
api/MIDIPort.json | close | https://webaudio.github.io/web-midi-api/#dom-midiport-close
api/MIDIPort.json | connection | https://webaudio.github.io/web-midi-api/#dom-midiport-connection
api/MIDIPort.json | id | https://webaudio.github.io/web-midi-api/#dom-midiport-id
api/MIDIPort.json | manufacturer | https://webaudio.github.io/web-midi-api/#dom-midiport-manufacturer
api/MIDIPort.json | name | https://webaudio.github.io/web-midi-api/#dom-midiport-name
api/MIDIPort.json | onstatechange | https://webaudio.github.io/web-midi-api/#dom-midiport-onstatechange
api/MIDIPort.json | open | https://webaudio.github.io/web-midi-api/#dom-midiport-open
api/MIDIPort.json | state | https://webaudio.github.io/web-midi-api/#dom-midiport-state
api/MIDIPort.json | type | https://webaudio.github.io/web-midi-api/#dom-midiport-type
api/MIDIPort.json | version | https://webaudio.github.io/web-midi-api/#dom-midiport-version
api/MIDIPort.json | MIDIPort | https://webaudio.github.io/web-midi-api/#MIDIPort
api/RTCPeerConnection.json | getTransceivers | https://w3c.github.io/webrtc-pc/#dom-peerconnection-gettranseceivers
api/SVGPointList.json | appendItem | https://svgwg.org/svg2-draft/types.html#__svg__SVGNameList__appendItem
api/SVGPointList.json | clear | https://svgwg.org/svg2-draft/types.html#__svg__SVGNameList__clear
api/SVGPointList.json | getItem | https://svgwg.org/svg2-draft/types.html#__svg__SVGNameList__getItem
api/SVGPointList.json | initialize | https://svgwg.org/svg2-draft/types.html#__svg__SVGNameList__initialize
api/SVGPointList.json | insertItemBefore | https://svgwg.org/svg2-draft/types.html#__svg__SVGNameList__insertItemBefore
api/SVGPointList.json | length | https://svgwg.org/svg2-draft/types.html#__svg__SVGNameList__length
api/SVGPointList.json | numberOfItems | https://svgwg.org/svg2-draft/types.html#__svg__SVGNameList__numberOfItems
api/SVGPointList.json | removeItem | https://svgwg.org/svg2-draft/types.html#__svg__SVGNameList__removeItem
api/SVGPointList.json | replaceItem | https://svgwg.org/svg2-draft/types.html#__svg__SVGNameList__replaceItem
api/SVGPointList.json | SVGPointList | https://svgwg.org/svg2-draft/shapes.html#InterfaceSVGPointList
http/headers/set-cookie.json | SameSite | https://httpwg.org/http-extensions/draft-ietf-httpbis-rfc6265bis.html#name-the-samesite-attribute

**Comment by sideshowbarker** [comment]
@hanzl035 — thanks much; closing per https://github.com/mdn/browser-compat-data/issues/11443#issuecomment-1245819818
