### ISSUE TITLE
svg.elements.feDistantLight.azimuth - Browser compatibility table is incomplete

### ISSUE THREAD

**Issue by BarryCap** [mdn/browser-compat-data#11479]
#### What information was incorrect, unhelpful, or incomplete?
The [browser compatibility table](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/azimuth#browser_compatibility) for the `azimuth` attribute was incomplete, showing unknown compatibility for all browsers.
#### What did you expect to see?
Browser compatibility for **Chrome 5**; **Edge 12**; **Firefox 3**; **Internet Explorer 10**; **Opera 12.1**; **Safari 6**; **WebView Android 91**; **Chrome Android 91**; **Firefox for Android 89**; **Opera Android 12.1**; **Safari on iOS 6.1**; **Samsung Internet 4**—as it is shown in the [Can I use table](https://caniuse.com/mdn-api_svgfedistantlightelement_azimuth). However, the note on Can I use says that the data is based on [MDN browser-compat-data](https://github.com/mdn/browser-compat-data).
#### Did you test this? If so, how?
I tested this attribute on **Chrome <span title="91.0.4472.124">91</span>**, **Edge <span title="91.0.864.67">91</span>**, **Firefox <span title="89.0">89</span>** and **Internet Explorer <span title="11">11</span>**. It seems to work properly in all the three first browsers, having an issue with [the iFrame](https://yari-demos.prod.mdn.mozit.cloud/en-US/docs/Web/SVG/Attribute/azimuth/_sample_.topExample.html) in **Internet Explorer**.

<details>
<summary>MDN page report details</summary>

* Query: `svg.elements.feDistantLight.azimuth`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/azimuth
* Report started: 2021-07-12T07:19:04.409Z

</details>

**Comment by queengooborg** [comment]
Thanks for reporting the issue!  We're still working to fill all of the data with proper compatibility data (see #3555), however SVG isn't as much of a priority at the moment (based on page view count).  We do plan to fill this data out though, don't worry!

I'm going to close this issue as we're already tracking this in #3555, but if you'd like to populate the data, we'd happily welcome a PR that copies the data from `api.SVGFEDistantLightElement.azimuth`, which is what CanIUse is getting the data from!
