### ISSUE TITLE
Mirroring Script, replacing false with added and removed in the same version

### ISSUE THREAD

**Issue by AdaRoseCannon** [mdn/browser-compat-data#11485]
api/progressEvent  -> initProgressEvent

"version_added": false,

becomes

"version_added": true,
"version_removed": "1.0"

Bug came up in: https://github.com/mdn/browser-compat-data/pull/11448

https://github.com/mdn/browser-compat-data/pull/11448/files/315ae9f546bac5ad1be66406ba31538daa92283d#diff-1cf2b37014729971fc79acf90ecff976397a1316d9bc404cc8795b04dc6fc841R145

**Comment by queengooborg** [comment]
Since overhauling the migration script to become a build-time step, this is no longer an issue!
