### ISSUE TITLE
How do I handle new timeZoneName options?

### ISSUE THREAD

**Issue by hamishwillee** [mdn/browser-compat-data#11501]
FF91 adds support for 4 new `timeZoneName` options in [Intl.DateTimeFormat()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat#browser_compatibility) - longOffset, shortOffset, longGeneric, shortGeneric.. But is here: https://bugzilla.mozilla.org/show_bug.cgi?id=1710429. These are just in FF91 and V8 at time of writing - it isn't clear what version of V8 (to me).

The problem is that there is already an option here:
![image](https://user-images.githubusercontent.com/5368500/125429177-70eda2b3-eafa-4644-bfe4-d9ce8daffaf2.png)

I assume that in future new things will support all of these new ones at once. So my proposal is to add a new subfeature "IANA offset/generic time zone names in timeZone option"

Does that make sense @ddbeck ?

**Comment by Elchi3** [comment]
Docs on this are here: https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines.md#parameters-and-parameter-object-features

Also, @foolip made a lot of this more consistent in https://github.com/mdn/browser-compat-data/pull/11502
Philip, can you advice Hamish how the structure should be like here?

**Comment by foolip** [comment]
I came across this very entry while preparing https://github.com/mdn/browser-compat-data/pull/11502 but left it alone to not end up with a huge PR.

There are features with these "IANA time zone names" descriptions in both `Date.json` and in `DateTimeFormat.json`.

First I would rename the "locales" and "options" subfeatures in those files to "locales_parameter" and "options_parameter", with proper descriptions.

Then, these `timeZone` entries can probably be "options_timeZone_parameter_iana" with "options.timeZone" in the decription.

Finally, name the new thing "options_timeZoneName_parameter".

I would suggest taking a closer look at these existing entries too. Maybe they actually match when the the `options.timeZone` parameter itself was supported and can be simplified. A lot of things are wrong and can be simplified if one looks closer :)

**Comment by ddbeck** [comment]
More background on @foolip's suggestions above: https://github.com/mdn/browser-compat-data/issues/11295#issuecomment-872163723.

**Comment by hamishwillee** [comment]
Thanks very much. So I have started the work for this in #11544. This essentially just restructures DateTimeFormat (only) as I "think" you suggested - ie constructor parameters are now subfeatures, and the options are subfeatures of those. 

Let's discuss the addition of `options_timeZoneName_parameter` in that item!

**Comment by queengooborg** [comment]
It's looking like all the work for this issue has been performed and merged already, so I'm going to go ahead and close this as resolved!  Please feel free to reopen if there's still work that still needs to be done.
