### ISSUE TITLE
Issue with "KeyboardEvent.metaKey": Windows key is no longer metaKey since FF 48

### ISSUE THREAD

**Issue by KibiH** [mdn/browser-compat-data#11537]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/metaKey

#### What information was incorrect, unhelpful, or incomplete?
Under broswer compatibility, Firefox gets a "yes". However, Firefox never returns MetaKey

#### Specific section or headline?
"Browser compatibility"

#### What did you expect to see?
"Firefox: No"

#### Did you test this? If so, how?
On my firesfox browser I try to pick up meta key presses (using the Windows key in combination with alt) and it never shows that metaKey is pressed, instead showing that alt is pressed with a code="OSLeft", key="OS"

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/keyboardevent/metakey`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/metaKey
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/keyboardevent/metakey/index.html
* Last commit: https://github.com/mdn/content/commit/496619dff5c263692bc1ecddbf80541d51b784dc
* Document last modified: 2021-06-14T00:31:40.000Z

</details>

**Comment by vinyldarkscratch** [comment]
Firefox definitely has support for `metaKey`.  As stated on the documentation, the Windows key is no longer considered the `metaKey` since Firefox 48, so the behavior you're experiencing is normal.

**Comment by dontcallmedom** [comment]
Would it be worth documenting in the BCD section itself (and thus in the data) the fact that the Windows key is no longer considered the `metaKey` since FF48?

**Comment by vinyldarkscratch** [comment]
That's a good point, actually!  It's a pretty big change that may affect site compatibility.  Reopening!
