### ISSUE TITLE
Make Bluetooth API OS support notes consistent across files

### ISSUE THREAD

**Issue by foolip** [mdn/browser-compat-data#11532]
https://github.com/mdn/browser-compat-data/pull/10197 updated `api/BluetoothRemoteGATTService.json` to simplify how BCD represents that `BluetoothRemoteGATTService` is only supported on some platforms by default, and needs a flag on some still.

Meanwhile, most of the existing Web Bluetooth API data still uses the previous style. These files need updating to match the style now used in `api/BluetoothRemoteGATTService.json`:
- [ ] `api/Bluetooth.json`
- [ ] `api/BluetoothCharacteristicProperties.json`
- [ ] `api/BluetoothRemoteGATTCharacteristic.json`
- [ ] `api/BluetoothRemoteGATTDescriptor.json`
- [ ] `api/BluetoothRemoteGATTServer.json`

These files don't have any such notes, but probably should, the existing data is likely wrong:
- [ ] `api/BluetoothDevice.json`
- [ ] `api/BluetoothUUID.json`
- [ ] `api/Navigator.json` (the api.Navigator.bluetooth entry)

cc @vinyldarkscratch

**Comment by Lukepearshotmail** [comment]
api/BluetoothRemoteGATTService.json
