### ISSUE TITLE
api.WindowOrWorkerGlobalScope.fetch - Is it really still experimental?

### ISSUE THREAD

**Issue by zaygraveyard** [mdn/browser-compat-data#11540]
#### What information was incorrect, unhelpful, or incomplete?
`fetch` is marked as experimental

#### What did you expect to see?
`fetch` is stable

#### Did you test this? If so, how?
No (don't know how to test it)

<details>
<summary>MDN page report details</summary>

* Query: `api.WindowOrWorkerGlobalScope.fetch`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API
* Report started: 2021-07-15T14:29:03.428Z

</details>

**Comment by ddbeck** [comment]
Thanks for reporting this, @zaygraveyard! Fixed now.
