### ISSUE TITLE
Issue with "Feature-Policy: display-capture": Firefox Support not Reported

### ISSUE THREAD

**Issue by eladalon1983** [mdn/browser-compat-data#11554]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy/display-capture

#### What information was incorrect, unhelpful, or incomplete?
Firefox support is incorrectly reported.

#### Specific section or headline?
Browser compatibility

#### What did you expect to see?
Supported since version X.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/headers/feature-policy/display-capture`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy/display-capture
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/feature-policy/display-capture/index.html
* Last commit: https://github.com/mdn/content/commit/03fa603f10d9f59aadbae7f2ae7c53149bcfe3ba
* Document last modified: 2021-06-08T00:56:33.000Z

</details>

**Comment by vinyldarkscratch** [comment]
Can you give more details as to why you think the current data is incorrect?  Did you test this, and if so, how?  Or if not, are there any articles, bugs and/or commits that back your statement?  Currently, our data states that Firefox support is present behind a flag.

**Comment by eladalon1983** [comment]
I don't think your data is up to date. I set up a [demo](https://plastic-brief-carnation.glitch.me/) for you - enjoy. :-)

**Comment by eladalon1983** [comment]
(Make sure to refresh the page in between clicks, btw, or you'll get throttled.)

**Comment by eladalon1983** [comment]
(Btw, I am working to implement `display-capture` in Chrome, so hopefully we can soon take away the `experimental technology` tag.)

**Comment by eladalon1983** [comment]
And I see it's also already implemented on Safari...
