### ISSUE TITLE
[Schema] The special case of prefixes and features removal

### ISSUE THREAD

**Issue by teoli2003** [mdn/browser-compat-data#116]
With the current schemas, a feature is supported or not. If it is supported 'prefixed', we say it is not supported and add the prefix support as a note.

Similarly if a feature was supported in the past, it is marked as 'non-supported', with a note indicated it was in the past.

This works well for the use case to display inside MDN, but obviously limits the ability to answer questions like 'What features were supported in Firefox 37' as features removed after Fx 37 will just be marked as 'not-supported'.

Is this a limitation we are ready to take? Or should we add a way to describe these now?

**Comment by jwhitlock** [comment]
This will make our data less useful than caniuse, which has [detailed per-version notes](https://github.com/Fyrd/caniuse/blob/master/CONTRIBUTING.md):

* **stats** — The collection of support data for a given set of browsers/versions. Only the support value strings can be modified; additional versions *cannot be added*. Values are space-separated characters with these meanings, and must answer the question "*Can I use* the feature by default?":
	* `y` - (**Y**)es, supported by default
	* `a` - (**A**)lmost supported (aka Partial support)
	* `n` - (**N**)o support, or disabled by default
	* `p` - No support, but has (**P**)olyfill
	* `u` - Support (**u**)nknown
	* `x` - Requires prefi(**x**) to work
	* `d` - (**D**)isabled by default (need to enable flag or something)
	* `#n` - Where n is a number, starting with 1, corresponds to the **notes_by_num** note.  For example: `"42":"y #1"` means version 42 is supported by default and see note 1.

**Comment by Elchi3** [comment]
To illustrate further what caniuse does:
```
    "firefox":{
      "2":"n",
      "3":"n",
      "3.5":"n",
      "3.6":"n",
      "4":"n",
      "5":"n",
      "6":"n",
      "7":"n",
      "8":"n",
      "9":"n",
      "10":"n",
      "11":"n",
      "12":"n",
      "13":"n",
      "14":"n",
      "15":"n",
      "16":"n",
      "17":"n",
      "18":"n",
      "19":"n",
      "20":"n",
      "21":"n",
      "22":"n",
      "23":"n",
      "24":"n",
      "25":"n d #1 #2",
      "26":"n d #1 #2",
      "27":"n d #1 #2",
      "28":"n d #1 #2",
      "29":"n d #1 #2",
      "30":"n d #1 #2",
      "31":"n d #1 #2",
      "32":"n d #1 #2",
      "33":"n d #1 #2",
      "34":"n d #1 #2",
      "35":"n d #1 #2",
      "36":"n d #1 #2",
      "37":"n d #1 #2",
      "38":"n d #1 #2",
      "39":"n d #1 #2",
      "40":"n d #1 #2",
      "41":"n d #1 #2",
      "42":"n d #1 #2",
      "43":"n d #1 #2",
      "44":"n d #1 #2",
      "45":"n d #2",
      "46":"n d #2",
      "47":"n d #2",
      "48":"n d #2",
      "49":"n d #2",
      "50":"n d #2",
      "51":"y",
      "52":"y",
      "53":"y"
},
"notes_by_num":{
    "1":"Can be enabled in Firefox by setting the about:config preference webgl.enable-prototype-webgl2 to true",
    "2":"WebGL2 context is accessed from \"experimental-webgl2\" rather than \"webgl2\"",
    "3":"Can be enabled in Chrome by passing the \"--enable-unsafe-es3-apis\" flag when starting the browser through the command line",
    "4":"Can be enabled via the \"Experimental Features\" developer menu"
},
```
I guess this requires a new entry for each browser version. 

What we have done so far (only one `support` property, but adding multiple here for illustration):
```
"Firefox": {
        "support": "23.0", // support by default in this version
        "support": false, // no support by default
        "support": true, // means we know it is supported but we don't know the version
        "support": null, // means "Support (u)nknown"
        "notes": ["Implemented as X-Content-Security-Policy header in Firefox 4."]
}
```
What we could do (again, duplicate properties only for illustration):
```
"Firefox": {
        "support": "23.0", // support by default in this version
        "support": false, // no support by default
        "support": true, // means we know it is supported by default but we don't know the version
        "support": null, // means "Support (u)nknown"
        "polyfill": false,
        "polyfill": true,
        "prefix": false,
        "prefix": "X-",
        "preference": false,
        "preference": "dom.csp.enabled", // indicates which pref is needed
        "notes": ["Implemented as X-Content-Security-Policy header in Firefox 4.", 
                  "To enabled CSP in Firefox, go to about:config yada yada.",
                  "Removed in Firefox 666 because of security issues."]
}
```
I don't think we need "(A)lmost supported (aka Partial support)" as our data is much more granular, and thus we will add sub features which then make it clear what is supported and what not ("partial" on caniuse is fuzzy anyway).

**Comment by wbamberg** [comment]
> What we could do (again, duplicate properties only for illustration):

How would this capture scenarios like "supported, behind a preference, from version 20 onwards"? And is the suggestion that the choices are mutually exclusive, and if so, shouldn't you be allowed to have "prefix" and "preference"?

It seems as if treating all the values (support, prefix, polyfill, preference) at the same level is wrong, because (presumably) "support" is not compatible with "prefix" or "preference" ("support" means supported unprefixed, without needing to tweak a pref), but "prefix" and "preference" are compatible with each other.

If feel like we have three states:

* no support (with a possible side-order of polyfill) 
* experimental support (with a side-order of one or more of "prefixed" and "preffed-off")
* supported

All these states can have notes. Should polyfill have a URL to the polyfill?

So perhaps:

```
"Firefox": {
        "support": ["23.0" | false | true | null]
        "experimental_support": [ "preffed-off" : pref-value and/or "prefixed": prefix-value ]
        "no-support: [ "polyfill": polyfill-url]
}
```
Does that sound right? This would get us closer to the richness of the caniuse data, but there's still the question of what to do about historical data, where, say, feature XYX was:
* unsupported until version 12, without a polyfill
* unsupported from 13-17, with a polyfill
* supported with a prefix from 18-20
* supported unprefixed from 21-45
* removed in 46

If we do want to have this, then I don't see any way of doing it other than listing versions, or version ranges, anyway:

```
"Firefox": {
    13: "no-support: [ "polyfill": polyfill-url] [notes]
    18: "experimental_support": [ "prefixed": prefix-value ] [notes]
    21: "support": [notes]
    46: "no-support": [notes]
}
```

**Comment by SebastianZ** [comment]
Will's statement about the historical data is important, though the presented schema seems a bit incorrect and the one used by caniuse.com is too verbose/redundant.

One important question: Do we want to put the data as it exists on MDN into the schema or do we want to extend/split it in version 1 of the schema already?

Regarding this, some notes regarding the suggestions above:
1. As far as I know, we don't have an extra info regarding the polyfill within the compat data but outside of it.
2. As far as I know, prefixed support *until* a specific version is currently only expressed in the notes.
3. As far as I know, preferences information is currently only expressed in the notes.

If we reflect the data currently available on MDN, the schema might look like this:

```
{
  <feature>: {
    "nonStandard": true | false,
    "deprecated": true | false,
    "experimental": true | false,
    ...
    "support": {
      <browser>: [
        {
          [ "version": <number>, ]
          [ "support": true | false, ]
          [ "prefix": <string>, ]
          [ "notes": <string> ]
        }
        ...
      ]
      ...
    }
  }
  ...
}
```

Where either `support` or `prefix` is defined and the other one is skipped. If the version number is unknown, it is skipped. So, e.g. for the `padding-box` value of the CSS `box-sizing` property the structure for Firefox may look like this:

```json
{
  "<code>padding-box</code>": {
    "nonStandard": true,
    "deprecated": true,
    "support": {
      "firefox": [
        {
          "version": 1,
          "prefix": "-moz",
          "notes": "in Firefox prior to 23 <code>box-sizing</code> is not respected when the height is calculated from {{domxref("window.getComputedStyle()")}}."
        },
        {
          "version": 29,
          "support": true
        },
        {
          "version": 50,
          "support": false
        }
      ]
    }
  }
}
```

This structure does already allow to answer questions like 'What features were supported in Firefox 37' indirectly by interpreting it. Regarding the example above, you could conclude from the data above that the feature was supported in Firefox 37.

Sebastian

**Comment by teoli2003** [comment]
So it looks, we don't want to loose information AND we want to be less verbose than caniuse schema.

What about:
{
  "padding-box": {
    "nonStandard": true,
    "deprecated": true,
    "support": {
      "firefox": [
        {
          "prefix": "-moz",
          "version": 1,
          "endversion":22,
          "notes": "<code>box-sizing</code> is not respected when the height is calculated from {{domxref("window.getComputedStyle()")}}."
        },
       {
          "prefix": "-moz",
          "version": 23,
          "endversion":50,
        },
       {
          "version": 29,
          "endversion":50
        }
      ]
    }
  }
}

The key difference is the addition of an optional "endversion" We have 1 entry per support. If there is no entry, for a given version, it means no support. 

We loose the 'unknown' state here, but we could mark it like this:
       {
          "version":1,
          "endversion":13,
          "status": "unknown"
       }
Or in other words, "status" can have either the value "true" or "unknown" (default: "true")

I think this would allow to save everything, but I wonder how easy to maintain it will be...

**Comment by Elchi3** [comment]
I think after a few months of discussions we've come to an agreement here and the new schema reflects that. Please open new issues if you have new feedback on how the new schema treats prefixes and feature removals.

**Comment by styfle** [comment]
It seems like there is duplicate effort going on here...

Why not have MDN read directly from [caniuse](https://github.com/Fyrd/caniuse) or maybe convince @Fyrd to read caniuse from MDN data?
