### ISSUE TITLE
http.headers.csp - Browser compatibility table content is not visible

### ISSUE THREAD

**Issue by nadir-promo** [mdn/browser-compat-data#11625]
#### What information was incorrect, unhelpful, or incomplete?
Feature names in browser compatibility table are not visible due to length of feature names.
![image](https://user-images.githubusercontent.com/45351787/126293406-2d83c951-379e-4cd3-9706-4af624f08008.png)

#### What did you expect to see?
I expect the names to wrap to next line or the feature name column to extend to the right.

#### Did you test this? If so, how?
Tested it by opening the [CSP Headers page](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP#browser_compatibility) in Chrome Version 91.0.4472.164 (Official Build) (64-bit)

<details>
<summary>MDN page report details</summary>

* Query: `http.headers.csp`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP
* Report started: 2021-07-20T08:46:20.382Z

</details>

**Comment by teoli2003** [comment]
I think this problem will be fixed by this PR once it lands: mdn/yari#4241

**Comment by vinyldarkscratch** [comment]
Closing this issue since it pertains to Yari and the BCD rendering, rather than the content itself.  The issue can be tracked here: https://github.com/mdn/yari/issues/4230
