### ISSUE TITLE
Safari data for AudioWorklet is incomplete

### ISSUE THREAD

**Issue by foolip** [mdn/browser-compat-data#11648]
`AudioWorklet` and `AudioWorkletNode` are marked as shipping in Safari 14.1, but `AudioWorkletGlobalScope` and `AudioWorkletProcessor` are marked as not supported in Safari.

This probably stems from mdn-bcd-collector not doing any testing inside worklets yet, and  `AudioWorkletGlobalScope` and `AudioWorkletProcessor` are `[Exposed=AudioWorklet]`.

cc @jdatapple

**Comment by lucalves** [comment]
Hello @foolip, I created PR #11743 to solve this. 

However, I was unsure if I should also add `safari_ios` compatibility: `"14.5"`.

If it is necessary to add, please inform me that I can do this.

**Comment by foolip** [comment]
Thanks @lucalves! I've commented on the PR.
