### ISSUE TITLE
api.Accelerometer - <PUT TITLE HERE>

### ISSUE THREAD

**Issue by StarTraX** [mdn/browser-compat-data#11713]
#### What information was incorrect, unhelpful, or incomplete?
The Browser Compatibility table omitted a report for Accelerometer running in Chrome on iPhone.

#### What did you expect to see?
A column in the phone section listing"Chrome on iOS"

#### Did you test this? If so, how?
Yes, it's not there

<details>
<summary>MDN page report details</summary>

* Query: `api.Accelerometer`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Accelerometer
* Report started: 2021-07-23T22:22:16.706Z

</details>

**Comment by vinyldarkscratch** [comment]
We aren't tracking Chrome on iOS/iPadOS separately from Safari iOS/iPadOS.  This is because on iPhones and iPads, the underlying browser engine is still a version of Safari tied to the operating system itself.
