### ISSUE TITLE
api.FileReader - available in Web Workers in Safari 14

### ISSUE THREAD

**Issue by knightjdr** [mdn/browser-compat-data#11784]
#### What information was incorrect, unhelpful, or incomplete?

The FileReader api is listed as not available in Web Workers for Safari

#### What did you expect to see?

It should be available as per manual testing.

#### Did you test this? If so, how?

Tested in Safari version 14.1.2 on OSX Catalina 10.15.7

<details>
<summary>MDN page report details</summary>

* Query: `api.FileReader`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/FileReader
* Report started: 2021-07-26T14:06:26.636Z

</details>

**Comment by queengooborg** [comment]
This has been resolved in #11762!
