### ISSUE TITLE
javascript.builtins.Intl.DateTimeFormat - <Georgian language doesn't work in Opera and Chrome >

### ISSUE THREAD

**Issue by TheSlimReaper925** [mdn/browser-compat-data#11786]
Opera GX, Opera and Google chrome

#### What information was incorrect, unhelpful, or incomplete?
When I set up locale to ka-GE, mozilla and Microsoft Edge returns date with Georgian language, but when I
open it in Opera GX or in Chrome, it doesn't return Georgian values, it returns English values
#### Did you test this? If so, how?

<details>
<summary>MDN page report details</summary>

* Query: `javascript.builtins.Intl.DateTimeFormat`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat
* Report started: 2021-07-26T15:26:35.488Z

</details>

**Comment by Josh-Cena** [comment]
Unfortunately we can't exhaustively document all locales that each browser version supports, because the spec doesn't mandate it and browsers constantly improve their database. You are responsible for testing the actual locale support.
