### ISSUE TITLE
http.headers.Set-Cookie.SameSite - missing documentation of iOS-12.x SameSite XHR/fetch bug on custom TLD or newer gTLDs

### ISSUE THREAD

**Issue by binki** [mdn/browser-compat-data#11780]
#### What information was incorrect, unhelpful, or incomplete?

For Mobile Safari iOS-12.x including latest (iOS-12.5.3), there is an undocumented bug.

If a website which has a TLD not recognized by iOS, the cookies are only sent for top-level requests. The cookies will not be sent for any XHR/fetch. iOS-12.5.3 does not recognize anything newer than `.inc` in [the list of gTLD delgations](https://newgtlds.icann.org/en/program-status/delegated-strings) or any custom private domains such as `.not-a-tld` which might be valid within a corporate network.

See the [webkit bug #228261](https://bugs.webkit.org/show_bug.cgi?id=228261).

#### What did you expect to see?

I expected to see documentation about this.

#### Did you test this? If so, how?

By following the procedure from [webkit bug #228261](https://bugs.webkit.org/show_bug.cgi?id=228261) which I am copying here:

1. Produce a webserver issuing a header such as `Set-Cookie: c=1; Path=/; SameSite=Lax` such as with the following command: `node -e "require('http').createServer((req, res) => {console.log(req.headers); res.writeHead(200, {'Set-Cookie': 'c=1; Path=/; HttpOnly; SameSite=Lax', 'Cache-Control': 'no-cache', 'Content-Type': 'text/html; charset=utf-8'}).end('<html>');}).listen(3000)"`
2. Configure your network and iPod running iOS-12.5.3 (latest for iPod6) such that the host blah.not-a-tld resolves to your server. For example, add an entry the server’s `/etc/hosts` and run `dnsmasq` on the server and then set custom DNS servers pointing to your server in your iPod’s network settings.
3. On the iPod, navigate to http://blah.not-a-tld:3000/.
4. Using Web Inspector from Safari Technology Preview on a Mac OS X machine, run `fetch('http://blah.not-a-tld:3000/', { credentials: 'include', })` twice.

Expected results:

The second time the `fetch()` is run, the request should send the cookie. This will be visible to the server and via Web Inspector.

Actual results:

The second time the fetch is run, the cookie is not sent.

If `SameSite` is removed entirely from the Set-Cookie header, the cookie is sent.

If top-level navigation is performed (e.g., reload the page or renavigate to it in Mobile Safari), the cookie is sent.

The problem is not reproducible in iOS-14.6.

<details>
<summary>MDN page report details</summary>

* Query: `http.headers.Set-Cookie.SameSite`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite
* Report started: 2021-07-24T01:02:50.386Z

</details>

**Comment by queengooborg** [comment]
Looks like this was fixed in #5878!
