### ISSUE TITLE
http.headers.csp.Content-Security-Policy - navigate-to works in Chrome 92

### ISSUE THREAD

**Issue by MaartenW** [mdn/browser-compat-data#11797]
Google Chrome
Google Chrome is up-to-date
Versie 92.0.4515.107 (Officiële build) (x86_64)

#### What information was incorrect, unhelpful, or incomplete?
CSP "navigate-to" is said not to work in Chrome.

#### What did you expect to see?

CSP "navigate-to" is compatible in chrome, at least from v92

#### Did you test this? If so, how?
Yes, see the following screenshot:

![Schermafbeelding 2021-07-27 om 13 17 45](https://user-images.githubusercontent.com/1092133/127145380-85dbd593-c13b-4897-8f20-db071275d1ef.png)

<details>
<summary>MDN page report details</summary>

* Query: `http.headers.csp.Content-Security-Policy`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy
* Report started: 2021-07-27T11:16:39.094Z

</details>

**Comment by queengooborg** [comment]
We've removed this feature from BCD in #17902.  It has been removed from the specification, and is probably not supported in Chrome any longer.
