### ISSUE TITLE
Issue with "Intl.DateTimeFormat() constructor": (short summary here please)

### ISSUE THREAD

**Issue by tiuvi** [mdn/browser-compat-data#11803]
page => https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat#using_timezonename

Uncaught RangeError: Value longGeneric out of range for Intl.DateTimeFormat options property timeZoneName
    at new DateTimeFormat (<anonymous>)

![image](https://user-images.githubusercontent.com/69035383/127180552-d2cf3b14-fbb5-4925-9417-7d5d99f58f24.png)

![image](https://user-images.githubusercontent.com/69035383/127180690-544875b7-e41a-4b93-923f-d80e0b9f464c.png)

'ShortOffset', 'longOffset', 'shortGeneric', 'longGeneric' are implemented?

**Comment by Francisco-AM** [comment]
@sideshowbarker  Yes, I'm sorry, I didn't see the browser compatibility.

**Comment by sideshowbarker** [comment]
> @sideshowbarker Yes, I'm sorry, I didn't see the browser compatibility.

No worries — we’ve got the issue in the right place now, so thanks for having raised it

**Comment by queengooborg** [comment]
This was fixed by #21470!
