### ISSUE TITLE
api.Element.animate - options.pseudoElement works in Chromium without flag

### ISSUE THREAD

**Issue by rururux** [mdn/browser-compat-data#11811]
#### What information was incorrect, unhelpful, or incomplete?
The "options.pseudoElement" Chrome/Edge support status on this page says:

> From version 81: this feature is behind theExperimental Web Platform Features preferences. To change preferences in Chrome, visit chrome:flags.

But when I tried it, it worked as well without enabling this flag.
#### Did you test this? If so, how?
test page: https://codepen.io/danwilson/pen/oNjwyOV

Windows: Chromium Edge v92, Vivaldi 3.7.2218.52 (Chromium version is maybe 89.0.4389.116)
Android: Google Chrome v92

Information that may be relevant: https://bugs.chromium.org/p/chromium/issues/detail?id=981894

<details>
<summary>MDN page report details</summary>

* Query: `api.Element.animate`
* MDN URL: https://developer.mozilla.org/ja/docs/Web/API/Element/animate
* Report started: 2021-07-29T08:47:17.966Z

</details>

**Comment by rururux** [comment]
close by https://github.com/mdn/browser-compat-data/pull/14425

**Comment by ninevra** [comment]
I think this issue should be reopened. The data is still incorrect, and the linked pull request does not appear to relate.

**Comment by rururux** [comment]
oh, OK, I'll reopen the issue.

**Comment by rururux** [comment]
thank you @ninevra, @Elchi3! 😄
