### ISSUE TITLE
api.Window.print - <not work on android>

### ISSUE THREAD

**Issue by Ali1ty** [mdn/browser-compat-data#11825]
#### Did you test this? If so, how?

<details>
<summary>MDN page report details</summary>

* Query: `api.Window.print`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/print
* Report started: 2021-07-31T07:11:55.564Z
print function not work in android os
</details>

**Comment by vinyldarkscratch** [comment]
I'm closing this issue as the PR template is blank and there is no actionable information.  If you'd like us to reopen this issue, please fill out the template and reply to this thread (or open a new issue, either works) and I'll happily reopen it!
