### ISSUE TITLE
api.WebGL2RenderingContext.uniform1fv etc. - no data

### ISSUE THREAD

**Issue by saschanaz** [mdn/browser-compat-data#11852]
#### What information was incorrect, unhelpful, or incomplete?

```js
  WebGL2RenderingContextOverloads: [
    // These are implemented in WebGLRenderingContext and WebGL2RenderingContext separately
    // but BCD only have them in WebGLRenderingContext
    "bufferData",
    "compressedTexImage2D",
    "compressedTexSubImage2D",
    "readPixels",
    "texImage2D",
    "texSubImage2D",
    "uniform1fv",
    "uniform1iv",
    "uniform2fv",
    "uniform2iv",
    "uniform3fv",
    "uniform3iv",
    "uniform4fv",
    "uniform4iv",
  ],
```

#### What did you expect to see?

Those exist in WebGLRenderingContext, but since `WebGLRenderingContext.prototype.uniform1iv !== WebGL2RenderingContext.prototype.uniform1iv`, they should also be in WebGL2RenderingContext separately.

#### Did you test this? If so, how?

The above JS expression

#### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://developer.mozilla.org/en-US/docs/Web/API/WebGL2RenderingContext

**Comment by queengooborg** [comment]
This has been fixed in #17201!
