### ISSUE TITLE
css.selectors.dir - Supported in Chrome

### ISSUE THREAD

**Issue by alimansourey** [mdn/browser-compat-data#11868]
Chrome Version 92.0.4515.107 (Official Build) (64-bit)

#### What information was incorrect, unhelpful, or incomplete?
MDN chart shows this feature as not supported in Chrome browser, while in fact it is .
#### What did you expect to see?
CSS pseudo-class (:dir(rtl | ltr ) is supported in this Chrome version.
#### Did you test this? If so, how?
yes I tested it and it works : 
```
<!-- HTML code -->
<p dir="rtl"> Arabic text :  نص عربي هنا ... </p>
/* CSS Rules */
p:dir(rtl)::after {
content : 'This is Arabic text' ;
}
```

<details>
<summary>MDN page report details</summary>

* Query: `css.selectors.dir`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/:dir
* Report started: 2021-08-01T21:32:38.924Z

</details>

**Comment by Lukepearshotmail** [comment]
On 1 Aug 2021 22:50, alimansourey ***@***.***> wrote:



Chrome Version 92.0.4515.107 (Official Build) (64-bit)

What information was incorrect, unhelpful, or incomplete?

What did you expect to see?

CSS pseudo-class (:dir(rtl | ltr ) is supported in this Chrome version.

Did you test this? If so, how?

yes I tested it and it works :



 Arabic text :  نص عربي هنا ... 

/* CSS Rules */

p:dir(rtl)::after {

content : 'This is Arabic text' ;

}





MDN page report details

Query: css.selectors.dirMDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/:dirReport started: 2021-08-01T21:32:38.924Z

**Comment by tannerdolby** [comment]
> MDN chart shows this feature as not supported in Chrome browser, while in fact it is .

In fact, if you head over to [caniuse.com](https://caniuse.com/?search=%3Adir) you will see that `:dir` is not supported in Chrome. It can be experimentally enabled but it does not have support outside of this "experimental usage".

<img width="1276" alt="Screen Shot 2021-08-01 at 10 14 26 PM" src="https://user-images.githubusercontent.com/48612525/127807496-0ead65d5-a33f-4c9b-b435-cc77697e657e.png">

@vinyldarkscratch I reckon this can be closed.

**Comment by vinyldarkscratch** [comment]
Thanks for looking into this more @tannerdolby!  I looked at the test available on the MDN page on the latest Chrome, and can confirm that there is no support without flags.
