### ISSUE TITLE
Add browser release date to rendered compatibility tables

### ISSUE THREAD

**Issue by Barbieroalex** [mdn/browser-compat-data#11871]
#### What did you expect to see?

Browser release date (can be on hover)
A section where it is suggested or not to use said technology
How many users may be affected if we use said technology

<details>
The graph is pretty good, but it would be great to know what the experts' recommendation is for using the different technologies.

it could be something like:
You can use this technology with confidence 97% of the world's users have a compatible browser 

</details>

**Comment by vinyldarkscratch** [comment]
Can you open an issue at https://github.com/mdn/yari instead?  This repo is explicitly for the data rather than the rendering of it.
