### ISSUE TITLE
api.Navigator.setAppBadge - Wrong Samsung Internet compatibility

### ISSUE THREAD

**Issue by renenienaber** [mdn/browser-compat-data#11879]
Since Samsung Internet is based on Chromium, which doesn't supports the API on Android, this should not work. There is NO evidence in that it will work there. Same for Navigator.clearAppBadge

<details>
<summary>MDN page report details</summary>

* Query: `api.Navigator.setAppBadge`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/setAppBadge
* Report started: 2021-08-02T09:48:49.656Z

</details>

**Comment by queengooborg** [comment]
Looks like the Chrome Android data was updated in #9988, but Samsung Internet and Opera Android were left untouched.  Fix coming right up!
