### ISSUE TITLE
html.global_attributes.dir - IE11 on Win10 supports it

### ISSUE THREAD

**Issue by tacsipacsi** [mdn/browser-compat-data#11893]
#### What information was incorrect, unhelpful, or incomplete?
According to the compatibility table, Internet Explorer doesn’t support the `dir` global attribute. However, with a quick test, it seems to support it on Win10 21H1, at least on `<p>` elements.

#### What did you expect to see?
Accurate compatibility info, of course. :) I didn’t find any documentation about this online, so the only thing I know is that it works in IE11 on Windows 10, version 21H1 (IE version 11.0.19041.1).

#### Did you test this? If so, how?
With a simple HTML file:
```html
<!DOCTYPE html>
<html>
	<head>
		<title>Dir test</title>
	</head>
	<body>
		<p dir="ltr">ltr</p>
		<p dir="rtl">rtl</p>
	</body>
</html>
```

<details>
<summary>MDN page report details</summary>

* Query: `html.global_attributes.dir`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/dir
* Report started: 2021-08-03T11:15:52.733Z

</details>

**Comment by queengooborg** [comment]
I'm closing this issue as we are no longer maintaining the Internet Explorer; see the [applicable discussion](https://github.com/orgs/mdn/discussions/202) for more details.
