### ISSUE TITLE
css.properties.font-synthesis - macOS Safari 14.1, 15 don't appear to support

### ISSUE THREAD

**Issue by thunderdw** [mdn/browser-compat-data#11907]
Browsers: Tested in Safari v14.1.2 and Safari 15 Technology Preview Release 128
Operating System: MacOS Big Sur v11.5 Beta
Processor: Apple Silicon 

#### What information was incorrect, unhelpful, or incomplete?
The compatibility information lists Safari as supporting `font-synthesis` in all versions 9 and up, but in my testing Safari 14.1 and 15 don't support `font-synthesis`

#### What did you expect to see?
When using Safari, the synthesized fonts examples in both the CSS Demos and the Examples section on the MDN `font-synthesis` page should alter the font styling (italic, bolding) for text with the CJK font. None of the examples change the styling of CJK text regardless of `font-synthesis` attribute value set on its element

#### Did you test this? If so, how?
Yes. I opened the MDN URL below in Safari 14.1.2 and the 15 Technology Preview Release 128 and verified that the `font-synthesis` did not change the styling of text with the CJK font on elements it was applied to. I also opened the page in Firefox 90.0.2 (64-bit), and verified that the styling of text with the CJK font did change based on its `font-synthesis` value.

I also used Browser Stack (linked to from [caniuse.com](https://caniuse.com/?search=font-synthesis)) to test more versions of Safari. Results:
Respected `font-synthesis` value: 9.1, 10.1
Mixed result: 11.1 - the font-synthesis property was reflected in the Examples section but not in the CSS Demos section
Did not respect `font-synthesis` value:  <=8 (expected behavior); 12.1, 13.1, 14.1 (unexpected behavior)

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.font-synthesis`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/font-synthesis
* Report started: 2021-08-04T10:11:28.999Z

</details>

**Comment by queengooborg** [comment]
I'm not able to confirm this when looking at the CSS Demo on Safari 14.1 or higher (13.1 is no longer supported by MDN).  The results are the same as on Chrome and Firefox.
