### ISSUE TITLE
api.BarcodeDetector - Version 92.0.902.62 (Official build) (x86_64)

### ISSUE THREAD

**Issue by nerding-it** [mdn/browser-compat-data#11914]
#### What information was incorrect, unhelpful, or incomplete?
This API is available in Version 92.0.902.62 (Official build) (x86_64) when I tested in debugger console

#### What did you expect to see?
I expect the API compatible with Edge version 92

#### Did you test this? If so, how?
I tested in developer tools

<details>
<summary>MDN page report details</summary>

* Query: `api.BarcodeDetector`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Barcode_Detection_API
* Report started: 2021-08-05T06:20:27.155Z

</details>

**Comment by queengooborg** [comment]
Our data already indicates as such since #6250, and then #10650 which indicated macOS support only, so I'm not sure what needs updating.  Is it that this API is supported in Windows and/or Linux?  What OS are you testing with?

**Comment by queengooborg** [comment]
Closing because there has been no response and not enough actionable information has been provided.  If this is still an issue, please feel free to reopen and reply with the requested information.
