### ISSUE TITLE
api.ReadableStream - Stability level

### ISSUE THREAD

**Issue by dodomorandi** [mdn/browser-compat-data#11915]
#### What information was incorrect, unhelpful, or incomplete?
All `ReadableStream` APIs are shown as _experimental_, but at the same time the [Stream spec](https://streams.spec.whatwg.org) is a living standard.

#### What did you expect to see?
I expect the `ReadableStream` APIs to be a stable API or, if there is a reason why these are still experimental even if the spec is standard, a sort of _stability note_ would be helpful to understand the actual situation.

#### Did you test this? If so, how?
I just opened the spec to see if it was still in draft or a living standard.

<details>
<summary>MDN page report details</summary>

* Query: `api.ReadableStream`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream
* Report started: 2021-08-05T10:04:40.799Z

</details>

**Comment by ddbeck** [comment]
Thanks for reporting this, @dodomorandi!
