### ISSUE TITLE
svg.elements.feComposite - problem with compatibility data

### ISSUE THREAD

**Issue by StipJey** [mdn/browser-compat-data#11929]
Hi, I use two browsers:
- Google Chrome 92.0.4515.131
- Safari 14.1.2 (15611.3.10.1.5, 15611)
on MacOS Catalina 10.15.7

#### What information was incorrect, unhelpful, or incomplete?

The designer drew a picture using effects for example: feComposite. But it looks terrible in the browser. He tells me that all properties are supported by all browsers. But this is not the case. See how the examples from the article look like. Does this look like correct support?
![image](https://user-images.githubusercontent.com/8746529/128530543-c62baa33-1f8a-40a9-95cc-833304b0303f.png)

#### What did you expect to see?

![image](https://user-images.githubusercontent.com/8746529/128529841-b695d870-1c8c-4ad5-b3ac-fbb5a641843a.png)

#### Did you test this? If so, how?
All examples from https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feComposite
Just open this in your browser

I see that:
Chrome:
![image](https://user-images.githubusercontent.com/8746529/128530034-617eb04e-a672-435b-a80a-61f3fa27d652.png)

Safari:
![image](https://user-images.githubusercontent.com/8746529/128530143-da0b50db-0a60-4b02-a302-4bf423e2da11.png)

<details>
<summary>MDN page report details</summary>

* Query: `svg.elements.feComposite`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feComposite
* Report started: 2021-08-06T14:45:52.687Z

</details>

**Comment by queengooborg** [comment]
I'm unable to replicate the issue you're running into, and the result div's output matches each of the examples at the top.  If I had to guess, it might have either been a caching issue or something with MDN's static files that's now resolved.
