### ISSUE TITLE
css.properties.image-rendering - iOS does not work

### ISSUE THREAD

**Issue by Coder2195Text** [mdn/browser-compat-data#11921]
Device details:
![08ACD4CB-476E-41CF-99E1-C303F1C80EF6](https://user-images.githubusercontent.com/63069499/128375062-5119ac20-bd5b-459b-87cf-ac48764c071b.png)

Pixelation works on my friends Firefox but not my safari and he double check my code there is nothing wrong

I have applied the pixelation onto a <image\> element

![1ECCC015-3E49-45EE-BD60-47CA409D3943](https://user-images.githubusercontent.com/63069499/128375320-ee9e67d3-4ab8-4c33-b0e6-1b0b91ac1b06.png)

**Comment by queengooborg** [comment]
Using the demo on the MDN page, I'm unable to confirm a lack of support for the `pixelated` mode.  Without test code to reference, we will unfortunately not be able to follow up on this.
