### ISSUE TITLE
html.elements.input.input-search - <Type Search does not work on safari Mobile>

### ISSUE THREAD

**Issue by razor11** [mdn/browser-compat-data#11932]
Safari  mobile , Ios 14.7.1

#### Did you test this? If so, how?

<details>
<summary>MDN page report details</summary>

* Query: `html.elements.input.input-search`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/search
* Report started: 2021-08-06T22:20:15.915Z

</details>

**Comment by vinyldarkscratch** [comment]
Can you provide more details on why you think this input type doesn't work on iOS and iPadOS by filling out the pull request template?
