### ISSUE TITLE
api.HTMLMediaElement.canplaythrough_event - OBS Studio browser source does not handles this event

### ISSUE THREAD

**Issue by Poketchu** [mdn/browser-compat-data#11949]
Tested this trigger on the OBS Studio browser source (OBS Studio version 27.0.1). According to the OBS wiki, this browser source handles CEF so I assumed this was based on Chromium which is supposed to handle the event.

Unfortunately since console seems to be unreachable on this browser, I can't provide much details for now. I'll try a console redirection through local port in a near attempt though.

**Comment by vinyldarkscratch** [comment]
I'm sure the OBS Studio team would love to hear about this issue.  Can you open this issue here?  https://github.com/obsproject/obs-studio

Note that BCD is not tracking OBS' integrated browser.
