### ISSUE TITLE
javascript.builtins.Array.at - <Compatibility with Node.js is true>

### ISSUE THREAD

**Issue by thibaud-vct** [mdn/browser-compat-data#11940]
#### What information was incorrect, unhelpful, or incomplete?
Compatibility with Node.js

#### What did you expect to see?
Compatibility with Node.js : Yes

#### Did you test this? If so, how?
https://nodejs.org/en/blog/release/v16.6.0/

<details>
<summary>MDN page report details</summary>

* Query: `javascript.builtins.Array.at`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/at
* Report started: 2021-08-08T15:34:18.123Z

</details>

**Comment by queengooborg** [comment]
This has been fixed in #11819!
