### ISSUE TITLE
css.properties.overflow - Missing Safari 13.1+/iOS 13.4+ support for multiple values of overflow

### ISSUE THREAD

**Issue by HM100** [mdn/browser-compat-data#11953]
#### What information was incorrect, unhelpful, or incomplete?
Multiple values of overflow property is unsupported in Safari
#### What did you expect to see?
Multiple values of overflow property is supported in Safari 13.1 and iOS 13.4 and as such should be displayed the same in MDN as well
#### Did you test this? If so, how?
No but info is taken from https://caniuse.com/css-overflow

See also https://bugs.webkit.org/show_bug.cgi?id=198230 for the bug about the ``clip`` property of Overflow

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.overflow`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/overflow
* Report started: 2021-08-09T19:04:14.566Z

</details>

**Comment by queengooborg** [comment]
This has been fixed by #20036!
