### ISSUE TITLE
css.properties.inset -Inset function not working on Firefox

### ISSUE THREAD

**Issue by iamumarjaved** [mdn/browser-compat-data#11985]
Firefox 90.0.1 
I was trying to do box shading inside of container in HTML using "box Shading" and "Inset". But it looks like the "inset" tag wont work on firefox. its working well on Edge and Chrome.
i have tested this multiple times but same response( Inset function is not working) but "Box Shading" function works Fine.
Thank you.

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.inset`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/inset
* Report started: 2021-08-12T08:02:50.713Z

</details>

**Comment by queengooborg** [comment]
I an't confirm a lack of support in Firefox; the CSS property works as expected.  Without test code to reference, we won't be able to follow up on this.
