### ISSUE TITLE
html.elements.textarea - Safari maxlength counts newlines incorrectly

### ISSUE THREAD

**Issue by liamcmitchell-sc** [mdn/browser-compat-data#11988]
#### What information was incorrect, unhelpful, or incomplete?

Safari is listed as fully supporting maxlength attribute but it's implementation is wrong and/or should have implementation note.
When calculating maxlength (and preventing over-length input), new lines are counted as 2 characters instead of 1.
Webkit bug: https://bugs.webkit.org/show_bug.cgi?id=154342

#### What did you expect to see?

Note like:

> When calculating maxlength (and preventing over-length input), new lines are counted as 2 characters instead of 1.

#### Did you test this? If so, how?

Still an issue in Safari 14.0.3 and 14.2 Technology Preview. View min/max example (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea#min_and_max_length) and try to enter 20 (max) new lines, only 10 can be entered.

<details>
<summary>MDN page report details</summary>

* Query: `html.elements.textarea`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea
* Report started: 2021-08-12T15:52:28.388Z

</details>

**Comment by mxdvl** [comment]
I think this has been solved by https://github.com/WebKit/WebKit/commit/2252898e2468994720be25176170e00bc7b26ca3, and I could see it working in Safari Technology Preview.

**Comment by quocvuong2000** [comment]
Still not work correctly in safari 16.0.
