### ISSUE TITLE
api.Navigator.share - Opera browser compatibility

### ISSUE THREAD

**Issue by hugochmt** [mdn/browser-compat-data#11989]
Browser : Opera
Version : 77.0.4054.277
OS: Windows 10

#### What information was incorrect, unhelpful, or incomplete?
The section about Opera in Browser compatibility table seems outdated.

#### What did you expect to see?
The Opera support must be OK in the table.

#### Did you test this? If so, how?
I'm currently using Opera browser in version 77.0.4054.277 and the `navigator.share` feature is working on my device.

<details>
<summary>MDN page report details</summary>

* Query: `api.Navigator.share`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/API/Navigator/share
* Report started: 2021-08-12T16:59:53.891Z

</details>

**Comment by lucalves** [comment]
I've opened #12223 to solve this. Let's wait review :)
