### ISSUE TITLE
api.InputEvent.InputEvent - Safari 14.1.2 does not support initData in InputEvent constructor correctly 

### ISSUE THREAD

**Issue by ZhangYiJiang** [mdn/browser-compat-data#11994]
Browser: Safari 14.1.2  
OS: macOS Catalina 10.15.7

#### What information was incorrect, unhelpful, or incomplete?

`InputEvent()` constructor's compatibility chart suggests Safari is fully compliant, but it does not correctly support `initData`. This makes it difficult to use `InputEvent` constructor since the properties defined in `initData` are immutable (readonly) on the actual event object, which means the constructor cannot be used. 

#### What did you expect to see?

A note warning about Safari not supporting `initData` correctly

#### Did you test this? If so, how?

Webkit bug tracker: https://bugs.webkit.org/show_bug.cgi?id=170416

In Safari's console - 

```
> e = new InputEvent('beforeinput', { inputType: 'insertText' }) 
< InputEvent {isTrusted: false, inputType: "", data: null, dataTransfer: null, getTargetRanges: function, …}
> e.inputType
< ""
```

Compared to in Firefox 

``` 
> e = new InputEvent('beforeinput', { inputType: 'insertText' })
< beforeinput { target: null, isTrusted: false, isComposing: false, inputType: "insertText", detail: 0, layerX: 0, layerY: 0, which: 0, rangeOffset: 0, SCROLL_PAGE_UP: -32768, … }
> e.inputType
< "insertText"
``` 

<details>
<summary>MDN page report details</summary>

* Query: `api.InputEvent.InputEvent`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/InputEvent/InputEvent
* Report started: 2021-08-13T16:21:29.960Z

</details>

**Comment by gsnedders** [comment]
#7287 is relevant here; WebKit has:

```
dictionary InputEventInit : UIEventInit {
    DOMString? data = null;
};
```

As such the rest of the dictionary is unsupported.
