### ISSUE TITLE
api.MediaRecorder.MediaRecorder - Safari compatibility version is incorrect

### ISSUE THREAD

**Issue by topherhunt** [mdn/browser-compat-data#11998]
#### What information was incorrect, unhelpful, or incomplete?

https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder/MediaRecorder#browser_compatibility compatibility table says that Safari supports the `MediaRecorder()` constructor as of version 14. But when I test on Safari v14.0 (build 15610.1.28.1.9) on MacOS 10.15.7, in the JS console I see this error: `ReferenceError: Can't find variable: MediaRecorder`. Based on data from https://caniuse.com/?search=MediaRecorder, I believe Safari may support MediaRecorder as of 14.1+, but I haven't confirmed this.

#### What did you expect to see?

I'd suggest to update the compatibility table to either remove Safari support, or specify the earliest version that does actually support it (possibly 14.1, but again I haven't tested that).

#### Did you test this? If so, how?

<details>
<summary>MDN page report details</summary>

* Query: `api.MediaRecorder.MediaRecorder`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder/MediaRecorder
* Report started: 2021-08-14T19:15:04.088Z

</details>

**Comment by gsnedders** [comment]
It existed behind an experimental feature flag for a while, and I believe shipped in 14.1. https://github.com/WebKit/WebKit/commit/c6d610e0fa5abe274d7e38ed0bc73e96c63d352e (macOS) and https://github.com/WebKit/WebKit/commit/0f3f28a0aa422d102de843f3fb98ecbedb56b491 (iOS) seem to be flipping the defaults, though I think on macOS it might be restricted to 10.15 and above (while 14.1 shipped on 10.14 too). @youennf?
