### ISSUE TITLE
CI jsonlint fail

### ISSUE THREAD

**Issue by glukki** [mdn/browser-compat-data#12]
AFAICS there's `jsonlint ... --environment json-schema-draft-04` call in [.travis.yml](https://github.com/mdn/browser-compat-data/blob/master/.travis.yml#L5).
It makes `jsonlint` [call](https://github.com/zaach/jsonlint/blob/master/lib/cli.js#L85) `JSV.createEnvironment(options.env)`.
But `JSV` [has](https://github.com/garycourt/JSV/blob/master/lib/jsv.js#L1495) [only 3 environments](https://github.com/garycourt/JSV/blob/master/lib/environments.js) [register themselves](https://github.com/garycourt/JSV/blob/master/lib/json-schema-draft-01.js#L946).
`JSV` provides a method [registerEnvironment()](https://github.com/garycourt/JSV/blob/master/lib/jsv.js#L1287) to register custom environments, but `jsonlint` doesn't proxy it.

I see 3 options here:
* use `JSV` directly;
* make `JSV` support `json-schema-draft-04` from the box;
* or switch to one of `JSV` current environments.

What would you choose?

**Comment by Elchi3** [comment]
Thanks for looking into this. I'm not familiar with json schema validation, but apparently jsonlint doesn't support json-schema-draft-04. I found https://github.com/epoberezkin/ajv which does support it. If you rebase against master, the CI should pass now.

**Comment by Elchi3** [comment]
Closing this as there is no CI failure anymore. If anyone knows even better tooling, let me know :)
