### ISSUE TITLE
api.HTMLMediaElement.volume - Not working on iOS

### ISSUE THREAD

**Issue by pagedesigner** [mdn/browser-compat-data#12001]
#### What information was incorrect, unhelpful, or incomplete?
When Volume is changed it is now working, either its 0 or 1 (100%)

#### What did you expect to see?
Actual volume must be changed with the change of amount in HTMLMediaElement.volume

#### Did you test this? If so, how?
tested on latest version of iOS Safari and Chrome Browsers

<details>
<summary>MDN page report details</summary>

* Query: `api.HTMLMediaElement.volume`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/volume
* Report started: 2021-08-15T08:36:14.623Z

</details>

**Comment by queengooborg** [comment]
This was fixed by #16311!
