### ISSUE TITLE
api.Navigator.share - filesArray doesn't have support on IOS

### ISSUE THREAD

**Issue by jessewarddev** [mdn/browser-compat-data#12064]
#### What information was incorrect, unhelpful, or incomplete?
Sharing files doesn't seem to be supported on IOS.  I've tried with filesArray and it returns an error.

#### What did you expect to see?
I expected to be able to share an image on IOS with filesArray

#### Did you test this? If so, how?
Yes, on my own device and at this demo link: https://w3c.github.io/web-share/demos/share-files.html 

<details>
<summary>MDN page report details</summary>

* Query: `api.Navigator.share`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share
* Report started: 2021-08-19T16:57:39.338Z

</details>

**Comment by queengooborg** [comment]
File sharing support was added to Safari in iOS 15!  Since this issue was opened, we added subfeatures for the different data types in #12194.
