### ISSUE TITLE
api.WebSocket.send - IE support might be incorrect

### ISSUE THREAD

**Issue by Vilx2** [mdn/browser-compat-data#12071]
`api.WebSocket.send` page says that the `.send()` method is completely unsupported by any version of IE, however `api.WebSocket` page states that it's supported since IE10. caniuse.com data is also similarly confusing - IE10 is supposed to have full support of WebSockets, however a bit lower WebSocket.send() is marked as unsupported.

A quick test on IE11 shows that there `.send()` is supported at least at a basic level, however I have not performed a more detailed test to see where it might differ from the spec.

<details>
<summary>MDN page report details</summary>

* Query: `api.WebSocket.send`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/send
* Report started: 2021-08-20T08:09:54.385Z

</details>

**Comment by queengooborg** [comment]
Looks like this was fixed in #12667!
