### ISSUE TITLE
List all sandbox attribute values

### ISSUE THREAD

**Issue by acechorizo** [mdn/browser-compat-data#1208]
This is more of a question than an issue perhaps - 

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#Browser_compatibility

In the browser compatibility table, there are some sandbox attributes listed, but there are a whole lot more that are not, such as allow-scripts, allow-same-origin, allow-forms, etc. Am I supposed to read this table as any attribute not specifically called out should be included in the "sandbox" row?

**Comment by teoli2003** [comment]
The answer is "yes". I believe in such cases, we should list all of them individually, though the table would start to be a bit long.

A negative side of implying the values, is that new values, not yet listed, will be implied as supported.

**Comment by vinyldarkscratch** [comment]
I stumbled upon a little something that may help cover this, whether intentionally or not.  I noticed a `matches.keywords` attribute was added to compatibility statements in #3631.  Maybe we can use that to our advantage here?

Here's an example in use: https://github.com/mdn/browser-compat-data/blob/master/css/properties/transform.json#L161
