### ISSUE TITLE
CSS color-mix & color-contrast - Available on iOS 15 Safari as experimental

### ISSUE THREAD

**Issue by formspiel** [mdn/browser-compat-data#12099]
Both CSS properties are available as experimental features in Safari iOS (beta 6). See screenshot
![image](https://user-images.githubusercontent.com/1277141/130336003-a044e43e-763e-4006-93a4-bfeb13b7e86f.png)

**Comment by ddbeck** [comment]
Fixed by #12361. Thanks for the report!
