### ISSUE TITLE
css.properties.margin-inline - Outdated Compatibility Information for Microsoft Edge

### ISSUE THREAD

**Issue by agoodson582** [mdn/browser-compat-data#12096]
#### What information was incorrect, unhelpful, or incomplete?
In the browser compatibility section for the CSS `margin-inline` property, it says the following for Microsoft Edge: 
> From version 79: this feature is behind the `enable-experimental-web-platform-features` preferences (needs to be set to enabled).
#### What did you expect to see?
I believe the compatibility information chart should show that Edge now fully supports the `margin-inline` property without needing the user to enable the `enable-experimental-web-platform-features` flag, at least for the desktop version of the browser.
#### Did you test this? If so, how?
I tested this by making sure the `enable-experimental-web-platform-features` flag was disabled in my Edge browser and then viewing a webpage that had `margin-inline` implemented. It appears to work in Edge version 92.0.902.78 (It might also work in a few previous versions of Edge).

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.margin-inline`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/margin-inline
* Report started: 2021-08-21T16:58:55.342Z

</details>

**Comment by queengooborg** [comment]
Looks like this was resolved in #12202!
