### ISSUE TITLE
api.Headers.get - Seems to be supported on Firefox for Android v91

### ISSUE THREAD

**Issue by o-alquimista** [mdn/browser-compat-data#12102]
#### What information was incorrect, unhelpful, or incomplete?
Support for "Firefox for Android"
#### What did you expect to see?
"Full support"
#### Did you test this? If so, how?
Yes, I've tested it over remote debugging (USB).

See the discussion I started on the respective browser's repository: https://github.com/mozilla-mobile/fenix/discussions/20958

I still don't know in which version support was added.

<details>
<summary>MDN page report details</summary>

* Query: `api.Headers.get`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Headers/get
* Report started: 2021-08-21T22:47:03.941Z

</details>

**Comment by ddbeck** [comment]
Hi @o-alquimista and thanks for reporting this. This has been fixed by https://github.com/mdn/browser-compat-data/pull/12166. The updates should show on MDN in the next few days. Thanks again!
