### ISSUE TITLE
Switch from npm to yarn?

### ISSUE THREAD

**Issue by queengooborg** [mdn/browser-compat-data#12137]
With the the introduction of NodeJS v15/v16 and the subsequent NPM v7, I think that we should consider switching to Yarn for the package manager.

# Reasoning

When working on BCD, I often find myself having to switch to NodeJS v14 (with the help of `nvm`) before I start working.  Any time that I create a new terminal window, I have to remember to re-perform the switch to an earlier NodeJS version, though sometimes I forget to do so and end up creating an updated v2 lockfile, causing some dependency conflicts.  Yarn's versioning is independent from NodeJS', so using v14 vs. v16 isn't a problem.

# Pros/Cons

Pros that I can think of:
- Contributors can use either NodeJS v14 or v16
- Most other MDN repositories use Yarn, so we'd retain some consistency with them
- Switching over should be easy

Cons that I can think of (edited):
- May be harder for new contributors to get accustomed to (pointed out by @ddbeck below)
- Yarn doesn't have its own `audit fix`, oddly enough (but this is not something that affects us as much since we have very few dependencies and Dependabot fixes these already)

# Conclusion

What does the rest of the BCD team think about switching to Yarn?

**Comment by ddbeck** [comment]
I'm neutral but leaning negative on this idea. Here's where I'm coming from:

- I haven't really liked Yarn over on mdn/content, but that's pretty much the extent of my experience with it. I find it to have weird error messages and CLI design, though I don't know how much of that is project-specific.
- I think one of the MDN devs proposed this for BCD at one point (under a proposal to switch all mdn/ repos to Yarn). At the time, I raised concerns that adding an additional tool made it harder for new contributors to jump in. I'm still concerned about this and I'm not sure how to find out how comfortable would-be contributors are to use this tool.

That said, I do want to ameliorate your problems with developing BCD. Seems silly to impose a lot of burdens on a core contributor. If there are other bits of friction, let's look at them too (or maybe open issues to handle them). If Yarn is the solution, then we can pursue that, but if there are narrower solutions to specific problems, I want to know about those options.

Specifically:

- I don't have your Node versioning problem, though I do have various Node versions installed. I use `nodenv` (and a `.node-version` file that's not checked in) to automatically switch between node versions—there's some shell integration that makes this happen. Does `nvm` offer anything like that?
- When you "end up creating an updated `package-lock.json`", what does this mean, specifically? Is this `npm` upgrading to `"lockfileVersion": 2` or something else?

**Comment by vinyldarkscratch** [comment]
Thanks for your feedback, @ddbeck!  You've brought up some great points!

> I find [Yarn] to have weird error messages and CLI design, though I don't know how much of that is project-specific [to `mdn/content`].

I'd have to say those Yarn troubles are a lot more project-specific.  For the most part, my experience with Yarn in other projects I work on has been straightforward; `yarn add [-D]` to install a dependency, `yarn remove` to remove it, and `yarn [script]` to run a script defined in `package.json` (AKA, no need for the `run` keyword).  `mdn/content`'s CLI has been a different interaction than pretty much any other NodeJS project I've worked on, and I think this is mostly in part to `mdn/yari` featuring a single script for the CLI commands for all of the content.

> I raised concerns that adding an additional tool made it harder for new contributors to jump in. I'm still concerned about this and I'm not sure how to find out how comfortable would-be contributors are to use this tool.

Your point regarding new contributors is a very good one.  New contributors who aren't as familiar with the NodeJS ecosystem (and even some who are more familiar with it) may not be familiar with Yarn, much less how to install it.  Depending on Yarn does also impose an extra setup step for contributors if they haven't set it up already.  However, I feel that new contributors are probably more likely to edit files directly on GitHub.com to start, and more experienced contributors would clone the repository locally.  Perhaps, we could include a "getting started" section in the contributing guide that explains how to set up everything for a local clone?

> I use `nodenv` (and a `.node-version` file that's not checked in) to automatically switch between node versions—there's some shell integration that makes this happen. Does `nvm` offer anything like that?

It looks like `nvm` _does_ have an `.nvmrc` file one can define to switch between NodeJS versions depending on the project.  Additionally, it appears that, while `nvm` doesn't have built-in auto-switching, it does provide a script one can implement into `zsh` (my shell of choice) or `fish`.  This would easily solve my issue -- thanks for the advice there!  (Maybe it also makes sense to commit `.node-version` and `.nvmrc` files for other contributors too?)

> When you "end up creating an updated `package-lock.json`", what does this mean, specifically? Is this `npm` upgrading to `"lockfileVersion": 2` or something else?

Yes, I do mean that `npm` upgrades the `package-lock.json` to a v2 lockfile.  Apologies for not clarifying there!

**Comment by ddbeck** [comment]
> no need for the `run` keyword

Ha, I almost mentioned that I _hate_ this. Not that it matters for the purposes of this discussion, but it's kinda hard to tell when you've goofed up a yarn command or a project script under this "feature."

> Perhaps, we could include a "getting started" section in the contributing guide that explains how to set up everything for a local clone?

I mean, yes, we can do this. But we can't let docs be a band-aid over complexity. If it's not too onerous to go without, we shouldn't opt in to things that require more explanation.

> Maybe it also makes sense to commit `.node-version` and `.nvmrc` files for other contributors too?

I'm glad the `.nvmrc ` thing helps! (I'm also a fish enthusiast.) I don't know whether it's conventional to check those in. I'll need to investigate more. I also use a `nodenv` plugin for version shorthands (e.g., `14` instead of the fully-qualified versionn umber) in `.node-version`, so I'd probably end up overriding the default config anyway, which makes me think that the answer is "no" for `.node-version`, at least.

> Yes, I do mean that `npm` upgrades the `package-lock.json` to a v2 lockfile.

I think we can fix this one directly. If I understand the docs, then v2 lockfiles are backwards compatible with npm <7.0.0—if we upgraded the lockfile, it'd probably fix this particular hassle. I'll try testing this.

**Comment by hamishwillee** [comment]
My 2 bits. I prefer to have consistent toolchain - because I use the commands every day. As a user I find yarn a little more predictable than npm - and we could certainly make it so among our tools.

I very rarely need to think about contributing to the toolchain. If I did, then the package manager choice would be the least of my problems.

**Comment by queengooborg** [comment]
We're switching to NPM for all MDN projects, so I'm going to close this.  Additionally, Yarn v2+ has an awful design, so I would no longer recommend it as a package manager.

**Comment by hamishwillee** [comment]
Cool. As long as we have a consistent approach I don't care.
