### ISSUE TITLE
AudioContext.outputLatency

### ISSUE THREAD

**Issue by epistemex** [mdn/browser-compat-data#1215]
There seem to be an error with the documentation for AudioContext's `outputLatency`. Currently it's reported that it has support in Chrome but when checking there is no such property available in current versions (incl. canary v.66). There seem to be little progress on the implementation based on [this issue](https://bugs.chromium.org/p/chromium/issues/detail?id=785409&q=outputLatency&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified).

At least as far as desktop version go - and this would then also be the case for Opera [Blink] and possibly Safari, but I cannot check the latter.

 AudioContext.outputLatency (On Standard Track)
 https://developer.mozilla.org/docs/Web/API/AudioContext/outputLatency

```
 DESKTOP:
 Chrome    | Edge      | Firefox   | IE        | Opera     | Safari
 ----------+-----------+-----------+-----------+-----------+-----------
     Y     |     ?     |     -     |     -     |     Y     |     -

 MOBILE:
 Webview/A | Chrome/A  | Edge/mob  | Firefox/A | Opera/A   | Safari/iOS
 ----------+-----------+-----------+-----------+-----------+-----------
     Y     |     Y     |     ?     |     -     |     Y     |     ?

```

**Comment by Elchi3** [comment]
Fixed with https://github.com/mdn/browser-compat-data/pull/1231
