### ISSUE TITLE
Incorrect Deno value for api.CloseEvent.initCloseEvent ?

### ISSUE THREAD

**Issue by teoli2003** [mdn/browser-compat-data#12175]
MDN advertizes Deno's support `initCloseEvent`. As it is the only target to support it, It looks suspicious to me, and this may be an oversight of bulk-adding the other `api.CloseEvent.*` support values.

<img width="956" alt="Screenshot 2021-08-25 at 09 24 52" src="https://user-images.githubusercontent.com/1466293/130745376-99d411e5-6474-4106-92ec-7bd8595b904e.png">

cc/ @lucacasonato who surely can confirm/infirm this value.

The two mdn pages with this info are [`CloseEvent`](https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent) and [`CloseEvent.initCloseEvent`](https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent/initCloseEvent)
The bcd git page with this info: https://github.com/mdn/browser-compat-data/blob/main/api/CloseEvent.json

**Comment by lucacasonato** [comment]
Already fixed a few days ago in https://github.com/mdn/browser-compat-data/commit/c5e9582dbd23f3f06d22797ac8236535e7c0ab13

**Comment by teoli2003** [comment]
Perfect!
