### ISSUE TITLE
api.EventTarget.addEventListener - Supported in IE11

### ISSUE THREAD

**Issue by hasakilol** [mdn/browser-compat-data#12184]
#### What information was incorrect, unhelpful, or incomplete?

It says addEventListener is not working in IE 11.

#### What did you expect to see?

In fact, addEventListener works in IE 11.

#### Did you test this? If so, how?
Yes. I just typed window.addEventListener on the IE 11 console. It returns a function, not undefined.

<details>
<summary>MDN page report details</summary>

* Query: `api.EventTarget.addEventListener`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener
* Report started: 2021-08-26T02:48:03.041Z

</details>

**Comment by hasakilol** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener
![hehe](https://user-images.githubusercontent.com/46310359/137424249-dc01a768-cee2-4cec-9e62-f33e8814b503.png)
What does this mean?

**Comment by queengooborg** [comment]
That is referring to IE's previous, non-standard name for the function, `attachEvent`.  The way the compat table is rendered doesn't make that fact too clear any longer, sadly -- I'll mention it to the folks who work on that part of MDN!
