### ISSUE TITLE
javascript.builtins.Function.call - "this" doesn't default to global object

### ISSUE THREAD

**Issue by tiborh** [mdn/browser-compat-data#12190]
#### What information was incorrect, unhelpful, or incomplete?

```
var sData = 'Wisen';

function display() {
  console.log('sData value is %s ', this.sData);
}

display.call();  // sData value is Wisen

```
#### What did you expect to see?

> sData value is Wisen

#### Did you test this? If so, how?

in node.js (script)

this worked:
`display.call({sData: sData});`

<details>
<summary>MDN page report details</summary>

* Query: `javascript.builtins.Function.call`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/call
* Report started: 2021-08-26T15:04:54.264Z

</details>

**Comment by Only1adhd228** [comment]
![Uploading pp_my_qrcode_1630284587167.jpg…]()

**Comment by Only1adhd228** [comment]
19cb665ee89a419063adfa89baa9f568194417f2

**Comment by queengooborg** [comment]
Alright, I see what's going on here.  It looks like in NodeJS, `this` doesn't default to the global object when running `function.call()`, which is different from standard browser behavior.  I'll add a note to our tables now!
