### ISSUE TITLE
api.Performance.now - caniuse says vendor prefix not needed for recent Chrome/Chromium versions

### ISSUE THREAD

**Issue by o-alquimista** [mdn/browser-compat-data#12237]
Currently, [MDN compat table](https://developer.mozilla.org/en-US/docs/Web/API/Performance/now#browser_compatibility) says we need a 'webkit' vendor prefix to use this feature. [caniuse](https://caniuse.com/?search=performance.now) says vendor prefix not needed for recent Chrome/Chromium versions. We must check if this information is current. 

<details>
<summary>MDN page report details</summary>

* Query: `api.Performance.now`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Performance/now
* Report started: 2021-09-01T12:47:19.597Z

</details>

**Comment by queengooborg** [comment]
This has been fixed back in #3571!
