### ISSUE TITLE
api.Response.clone - MDN says mobile browsers are not supported but they are

### ISSUE THREAD

**Issue by sachin-sharma1** [mdn/browser-compat-data#12234]
#### What information was incorrect, unhelpful, or incomplete?
https://developer.mozilla.org/en-US/docs/Web/API/Response/clone

#### What did you expect to see?
I was expecting it not to work on android 's firefox browser version 91.3.1 and chromium browser version 92

#### Did you test this? If so, how?
I tested on above listed browsers and it was working.

<details>
<summary>MDN page report details</summary>

* Query: `api.Response.clone`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Response/clone
* Report started: 2021-08-31T14:02:06.509Z

</details>

**Comment by queengooborg** [comment]
Looks like this has been fixed in #12579!
