### ISSUE TITLE
javascript.builtins.Date.toISOString - <toISOString Safari Compatibility issue>

### ISSUE THREAD

**Issue by qiyundai** [mdn/browser-compat-data#12233]
#### What information was incorrect, unhelpful, or incomplete?
Safari has compatibility issue with Date.prototype.toISOString(). This issue is consistent on both desktop and mobile version.
#### Did you test this? If so, how?
I built an app translating a Date object to ISO String. Safari logs RangeError: Invalid Date.

<details>
<summary>MDN page report details</summary>

* Query: `javascript.builtins.Date.toISOString`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString
* Report started: 2021-08-31T21:56:31.861Z

</details>

**Comment by vinyldarkscratch** [comment]
Can you provide example code so we can further review this?  Additionally, is the same code working in Chrome and Firefox with no issues?

**Comment by queengooborg** [comment]
I'm closing this issue because there has been no actionable information.  If this is still an issue, please feel free to reply to this thread with the requested information and I'll happily reopen this!

**Comment by qiyundai** [comment]
Hi! Sorry I got sidetracked and fell off the thread. I'm going to backtrack and find the code I was working on when I encountered the issue. I'll be in touch should I find anything.
