### ISSUE TITLE
webextensions.manifest.author - Not supported in Opera

### ISSUE THREAD

**Issue by carlosjeurissen** [mdn/browser-compat-data#12247]
#### What information was incorrect, unhelpful, or incomplete?
`browser-compat-data` claims the `author` property is supported in Opera. it is not.

#### What did you expect to see?
That `author` is not supported. Opera can only work with `developer.name`.

#### Did you test this? If so, how?

Yes. Tested in the opera browser by loading an extension with `author`

<details>
<summary>MDN page report details</summary>

* Query: `webextensions.manifest.author`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/author
* Report started: 2021-09-03T10:24:59.174Z

</details>

**Comment by rebloor** [comment]
Tested in Opera 104.0.4944.54 and extension with "author" key loaded successfully. Also tested in Chrome (119.0.6045.123), given both based on chromium, also loaded the unpacked extension without issue.
