### ISSUE TITLE
Individual Transform Properties - Missing Chrome support (behind flag)

### ISSUE THREAD

**Issue by lukewarlow** [mdn/browser-compat-data#12273]
#### What information was incorrect, unhelpful, or incomplete?
Currently Chrome is marked as having no support for the three individual transform properties.

#### What did you expect to see?
Chrome has support for these properties gated behind the `enable-experimental-web-platform-features` flag.

#### Did you test this? If so, how?
Using the demos on the MDN page I have validated this is true as of at least Chrome 93. I know this is true of older versions too I'm just not sure how far back support was added.

#### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://developer.mozilla.org/en-US/docs/Web/CSS/scale
https://developer.mozilla.org/en-US/docs/Web/CSS/translate
https://developer.mozilla.org/en-US/docs/Web/CSS/rotate

**Comment by queengooborg** [comment]
We're actually working to remove flag data from BCD entirely, as it isn't useful for end users and flags are only intended for testers trying out new features.  Additionally, browser vendors (like Google) have been requesting for us to limit our flag data to begin with.  So unfortunately, I'll be closing this as a "wontfix".
