### ISSUE TITLE
Reorganize GlobalEventHandlers and WindowEventHandlers mixin data

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#12290]
BCD doesn't expose mixin compat data anymore (see https://github.com/mdn/browser-compat-data/issues/8929)

Two event related mixins still exist and they need to be dealt with. https://github.com/mdn/browser-compat-data/issues/7545 is a related issue on how to represent support for events. However, this issue is specifically about what to do with 

- `GlobalEventHandlers` and
- `WindowEventHandlers`

**Comment by hamishwillee** [comment]
@Elchi3 Would be great when you do `GlobalEventHandlers` to note exactly where the handlers were implemented so we can mirror it in MDN. At the moment it isn't very clear to me where these appear - the docs mention Window and Document and Element, and I presume are therefore inherited by SVGElement etc - but that is a guess.

**Comment by Elchi3** [comment]
@queengooborg opened two PRs for this:

https://github.com/mdn/browser-compat-data/pull/15477
https://github.com/mdn/browser-compat-data/pull/15480

@foolip I would very much appreciate you taking a look if this approach makes sense to you.

**Comment by foolip** [comment]
Maybe starting with the events in https://html.spec.whatwg.org/multipage/media.html#mediaevents would be a good start, that's a big chunk of the events, and almost all of them should be given the same treatment. The exception is events like "abort" and "error" which can also be fired at other interfaces with completely different meanings. We can look at that in review.

**Comment by queengooborg** [comment]
Both mixins have now been demixed and removed from BCD!  WindowEventHandlers was solved fairly early on, and GlobalEventHandlers was solved as a part of https://github.com/mdn/browser-compat-data/issues/14578#issuecomment-1193910587!
