### ISSUE TITLE
Too many features claimed to be shipped in Firefox for Android 44

### ISSUE THREAD

**Issue by foolip** [mdn/browser-compat-data#12312]
`npm run traverse firefox_android api 44` lists lots of features, more than seems plausible. `comm -13 <(npm run traverse firefox api 44 | sort) <(npm run traverse firefox_android api 44 | sort)` lists those which are marked shipped in Firefox for Android 44 but not in Firefox 44:

api.HMDVRDevice
api.HMDVRDevice
api.HMDVRDevice.getEyeParameters
api.HMDVRDevice.getEyeParameters
api.HMDVRDevice.setFieldOfView
api.HMDVRDevice.setFieldOfView
api.Headers
api.Headers.get
api.PositionSensorVRDevice
api.PositionSensorVRDevice.getImmediateState
api.PositionSensorVRDevice.getState
api.PositionSensorVRDevice.resetSensor
api.RTCPeerConnection.addIceCandidate
api.RTCPeerConnection.addStream
api.RTCPeerConnection.addTrack
api.RTCPeerConnection.addstream_event
api.RTCPeerConnection.canTrickleIceCandidates
api.RTCPeerConnection.createAnswer
api.RTCPeerConnection.createDTMFSender
api.RTCPeerConnection.createDataChannel
api.RTCPeerConnection.createOffer
api.RTCPeerConnection.currentLocalDescription
api.RTCPeerConnection.datachannel_event
api.RTCPeerConnection.generateCertificate
api.RTCPeerConnection.getConfiguration
api.RTCPeerConnection.getLocalStreams
api.RTCPeerConnection.getRemoteStreams
api.RTCPeerConnection.getStreamById
api.RTCPeerConnection.iceGatheringState
api.RTCPeerConnection.icecandidate_event
api.RTCPeerConnection.iceconnectionstatechange_event
api.RTCPeerConnection.icegatheringstatechange_event
api.RTCPeerConnection.localDescription
api.RTCPeerConnection.negotiationneeded_event
api.RTCPeerConnection.onaddstream
api.RTCPeerConnection.ondatachannel
api.RTCPeerConnection.onicecandidate
api.RTCPeerConnection.oniceconnectionstatechange
api.RTCPeerConnection.onicegatheringstatechange
api.RTCPeerConnection.onnegotiationneeded
api.RTCPeerConnection.onremovestream
api.RTCPeerConnection.onsignalingstatechange
api.RTCPeerConnection.ontrack
api.RTCPeerConnection.pendingLocalDescription
api.RTCPeerConnection.pendingRemoteDescription
api.RTCPeerConnection.remoteDescription
api.RTCPeerConnection.removeStream
api.RTCPeerConnection.removeTrack
api.RTCPeerConnection.removestream_event
api.RTCPeerConnection.setLocalDescription
api.RTCPeerConnection.setRemoteDescription
api.RTCPeerConnection.signalingState
api.RTCPeerConnection.signalingstatechange_event
api.RTCPeerConnection.track_event
api.RTCTrackEvent
api.RTCTrackEvent.receiver
api.RTCTrackEvent.streams
api.RTCTrackEvent.track
api.RTCTrackEventInit
api.RTCTrackEventInit.receiver
api.RTCTrackEventInit.streams
api.RTCTrackEventInit.track
api.Window.orientationchange_event

I noticed this because of the WebRTC data, which I don't believe is right.

https://blog.mozilla.org/en/products/firefox/webrtc-now-available-across-mobile-and-desktop-with-new-firefox-for-android-compatibility/ + https://hacks.mozilla.org/2013/09/firefox-24-for-android-gets-webrtc-support-by-default/ from September 2013 show that this was shipped in Firefox for Android 24.

**Comment by foolip** [comment]
@queengooborg can you take a look at fixing the Firefox for Android data for WebRTC?

**Comment by foolip** [comment]
`npm run traverse -- -b firefox_android -f 44 api` now lists these remaining cases:

api.Element.matches (as webkitMatchesSelector)
api.Headers
api.Headers.Headers
api.Headers.append
api.Headers.delete
api.Headers.get
api.Headers.has
api.Headers.set
api.RTCIceCandidate
api.RTCIceCandidate.RTCIceCandidate
api.RTCPeerConnection
api.RTCPeerConnection.RTCPeerConnection
api.RTCSessionDescription
api.RTCSessionDescription.RTCSessionDescription
api.Window.orientation
api.Window.orientationchange_event

**Comment by queengooborg** [comment]
This list has shrunken even further, so I think that what remains is probably accurate -- as such, I'm going to close this issue.
