### ISSUE TITLE
Add onsecuritypolicyviolation  to Window and Document?

### ISSUE THREAD

**Issue by hamishwillee** [mdn/browser-compat-data#12334]
I added `onsecuritypolicyviolation` to the global handlers in #12289. 

However I "think" that  `onsecuritypolicyviolation` is also needed in BCD on `Window` and `Document` too. Can you please confirm? Reasoning below.

The `Window` and `Document` handlers were in the spec before being added to the global handlers.
- Testing shows that `onsecuritypolicyviolation` is present on Chrome in `Window` and `Document` (but not in elements). i.e. it implements these
- Notes indicate it is present `Document` in Safari but not `Window`
- For completeness, FF92 did not implement these.

If these do need a BCD entry, what versions could be used?  Just set to true, false appropriately? We can kind of guess at these from [SecurityPolicyViolationEvent](https://developer.mozilla.org/en-US/docs/Web/API/SecurityPolicyViolationEvent) but it would be a guess - because we know this guess does not work for Firefox.

**Comment by Elchi3** [comment]
This issue seems to be an instance of https://github.com/mdn/browser-compat-data/issues/12290. I don't have an answer yet, linking this for inspiration/context.

**Comment by hamishwillee** [comment]
@Elchi3 Well, there is no way I can reflect the right versions that `onsecuritypolicyviolation` are available on `Window` and `Document` using `GlobalEventHandlers`. So from correctness of the data it certainly makes sense to split them out. 

However I will leave this alone until a decision is made.
