### ISSUE TITLE
api.Navigator.userAgentData - <Compatibility vs Enabled>

### ISSUE THREAD

**Issue by 4E71-NOP** [mdn/browser-compat-data#12355]
#### What information was incorrect, unhelpful, or incomplete?
Compatibility is stated for Chrome 90 as for some other browsers. But it is not enabled (apparently) and nothing in this webpage tells the reader that it may not be enabled or functional. Only that it's *experimental*. 

#### What did you expect to see?
A note to tell readers that this may not be enabled yet. And it seems so (unless I'm missing something). 

#### Did you test this? If so, how?
I used the JavaScript from the webpage (and several other sources). It just returns 'undefined'. 
Tested on Chrome 93.0.4577.63/Win10 and Chromium 90.0.4430.212/Linux

<details>
<summary>MDN page report details</summary>

* Query: `api.Navigator.userAgentData`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/userAgentData
* Report started: 2021-09-12T14:40:05.282Z

</details>

**Comment by queengooborg** [comment]
This property is fully supported and enabled by default since Chrome 90, as I have just confirmed in BrowserStack.  I'm unable to confirm a lack of support.
