### ISSUE TITLE
api.MediaDevices.enumerateDevices - Misleading Footnote re: Firefox Compatibility 

### ISSUE THREAD

**Issue by michaelmcchen** [mdn/browser-compat-data#12365]
#### What information was incorrect, unhelpful, or incomplete?
The footnotes under Firefox compatibility are misleading. The following is how they're currently written: 

> From version 63: this feature is behind the media.setsinkid.enabled preferences (needs to be set to true). To change preferences in Firefox, visit about:config.

> Prior to Firefox 63, enumerateDevices() only returned input devices. Starting with Firefox 63, output devices are also included if the media.setsinkid.enabled preference is enabled.

The first sentence seems to imply that the entire feature is wrapped behind the `media.setsinkid.enabled` preference. In my own testing (on Firefox 92.0), I found that regardless of input devices are returned regardless of `media.setsinkid.enabled` is enabled or not. If that value is enabled, we also see output devices (consistent with the second sentence).

#### What did you expect to see?
The first sentence is misleading and can be removed. 

"Prior to Firefox 63, enumerateDevices() only returned input devices. Starting with Firefox 63, output devices are also included if the media.setsinkid.enabled preference is enabled. To change preferences in Firefox, visit about:config."

#### Did you test this? If so, how?
Tested on Firefox 92.0 by running the following Javascript: 

```
          navigator.mediaDevices.enumerateDevices().then( devices => 
            devices.forEach( device => {
                console.log("general device", device);
            })
          ).catch((error) => {
            console.log("error", error);
          });
```

<details>
<summary>MDN page report details</summary>

* Query: `api.MediaDevices.enumerateDevices`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/enumerateDevices
* Report started: 2021-09-12T20:47:07.236Z

</details>

**Comment by queengooborg** [comment]
The notes were updated and rewritten in #20307!
