### ISSUE TITLE
Issue with "outline": missing information regarding border-radius

### ISSUE THREAD

**Issue by AlonBru** [mdn/browser-compat-data#12369]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/outline

#### What information was incorrect, unhelpful, or incomplete?
from my experience, it 

seems that while on firefox the outline does conform to border-radius,  but on chrome and safari it does mot

#### What did you expect to see?
perhaps could be added under browser compatibility

#### Did you test this? If so, how?
tested on chrome, firefox and safari
- firefox:
- added styles:
````css
outline: 2px red solid;
border-radius: 50%;
padding: 30px;
````
![Screen Shot 2021-09-11 at 2 04 42](https://user-images.githubusercontent.com/66993391/132926336-07b83bc9-f3d1-419f-9030-efb43146aeed.png)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/outline`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/outline
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/outline/index.md
* Last commit: https://github.com/mdn/content/commit/26f50bdaeb1228f458d21dbdf7dc110387b20daa
* Document last modified: 2021-08-12T23:59:09.000Z

</details>

**Comment by AlonBru** [comment]
What i meant is that it should be noted in the article that the outline doesnt follow border-radius

**Comment by rachelandrew** [comment]
It does in the spec however, and is being updated in browsers, so the place to note it is in compat data, if we add compat notes in the text they very quickly get out of date and hang around.

**Comment by AlonBru** [comment]
In the spec it notes that it works in FF, but it does not note anywhere it doesnt elsewhere.
But if you think theres no point...

**Comment by queengooborg** [comment]
Looks like this has been resolved in #12820!
