### ISSUE TITLE
api.Document.referrer - Safari v 14.1.2

### ISSUE THREAD

**Issue by ajaymodi** [mdn/browser-compat-data#12374]
#### What information was incorrect, unhelpful, or incomplete?
document.referrer is always empty 

#### What did you expect to see?
document.referrer to set to the URI of the page that linked to this page

#### Did you test this? If so, how?
Opened safari, navigate page B from page A from the same domain and tested document.referrer in console. It was empty.

<details>
<summary>MDN page report details</summary>

* Query: `api.Document.referrer`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document/referrer
* Report started: 2021-09-13T10:12:53.189Z

</details>

**Comment by queengooborg** [comment]
I'm unable to replicate the issue on my end; if I navigate to MDN web docs and click on one of the Hacks Blog links, then check `document.referrer`, I'm getting the expected value of `https://developer.mozilla.org`.
