### ISSUE TITLE
css.selectors.focus-visible - Not working safari browser

### ISSUE THREAD

**Issue by anowarbhai** [mdn/browser-compat-data#12380]
#### Did you test this? If so, how?

<details>
<summary>MDN page report details</summary>

* Query: `css.selectors.focus-visible`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible
* Report started: 2021-09-13T19:00:01.293Z

</details>

**Comment by queengooborg** [comment]
Closing since there's no actionable information, and our BCD already states that this feature is not compatible in Safari.
