### ISSUE TITLE
api.Navigator.share - not available on iOS 14

### ISSUE THREAD

**Issue by EvanDElia** [mdn/browser-compat-data#12396]
Using iPhone XS with iOS 14.8 installed and using Safari v14, window.navigator.share is undefined

<details>
<summary>MDN page report details</summary>

* Query: `api.Navigator.share`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share
* Report started: 2021-09-14T22:39:48.905Z

</details>

**Comment by queengooborg** [comment]
I've confirmed that the feature is supported on iOS.  You may be trying to access it from a non-HTTPS website; the feature requires HTTPS.
