### ISSUE TITLE
javascript.classes.private_class_fields - not compatible in chrome

### ISSUE THREAD

**Issue by Wikitelmex** [mdn/browser-compat-data#12432]
#### Did you test this? If so, how?
I used into an private array, and in only in edge is working

<details>
<summary>MDN page report details</summary>

* Query: `javascript.classes.private_class_fields`
* MDN URL: https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Classes/Private_class_fields
* Report started: 2021-09-16T14:18:06.202Z

</details>

**Comment by queengooborg** [comment]
Can you provide additional details as to what's going on, such as code examples, console errors, etc.?
