### ISSUE TITLE
Create MDN macro for building overview page tables

### ISSUE THREAD

**Issue by ExE-Boss** [mdn/browser-compat-data#1243]
This macro would work by supplying it references to the APIs that belong to that overview page, eg.:
```
{{CompatOverview("api.Body","api.FetchEvent","api.Headers","api.Request","api.Response")}}
```
Which would render as:
<table>
	<thead>
		<tr>
			<th rowspan="2"></th>
			<th colspan="6">Desktop</th>
			<th colspan="7">Mobile</th>
		</tr>
		<tr>
			
			<th>Chrome</th>
			<th>Edge</th>
			<th>Firefox</th>
			<th>IE</th>
			<th>Opera</th>
			<th>Safari</th>
			
			<th>Android Webview</th>
			<th>Chrome for Android</th>
			<th>Edge Mobile</th>
			<th>Firefox for Android</th>
			<th>Opera for Android</th>
			<th>iOS Safari</th>
			<th>Samsung Internet</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<th><a href="https://developer.mozilla.org/docs/Web/API/Body"><code>Body</code></a></th>
			
			<td>42</td>
			<td>Yes</td>
			<td>39</td>
			<td>No</td>
			<td>29</td>
			<td>No</td>
			
			<td>42</td>
			<td>42</td>
			<td>?</td>
			<td>44</td>
			<td>Yes</td>
			<td>No</td>
			<td>?</td>
		</tr>
		<tr>
			<th><a href="https://developer.mozilla.org/docs/Web/API/FetchEvent"><code>FetchEvent</code></a></th>
			
			<td>40</td>
			<td>Yes</td>
			<td>44</td>
			<td>No</td>
			<td>27</td>
			<td>No</td>
			
			<td>40</td>
			<td>40</td>
			<td>?</td>
			<td>44</td>
			<td>27</td>
			<td>No</td>
			<td>?</td>
		</tr>
		<tr>
			<th><a href="https://developer.mozilla.org/docs/Web/API/Headers"><code>Headers</code></a></th>
			
			<td>42</td>
			<td>Yes</td>
			<td>39</td>
			<td>No</td>
			<td>29</td>
			<td>10.1</td>
			
			<td>42</td>
			<td>42</td>
			<td>?</td>
			<td>44</td>
			<td>29</td>
			<td>No</td>
			<td>?</td>
		</tr>
		<tr>
			<th><a href="https://developer.mozilla.org/docs/Web/API/Request"><code>Request</code></a></th>
			
			<td>42</td>
			<td>Yes</td>
			<td>39</td>
			<td>No</td>
			<td>28</td>
			<td>No</td>
			
			<td>42</td>
			<td>42</td>
			<td>Yes</td>
			<td>Yes</td>
			<td>28</td>
			<td>No</td>
			<td>?</td>
		</tr>
		<tr>
			<th><a href="https://developer.mozilla.org/docs/Web/API/Response"><code>Response</code></a></th>
			
			<td>42</td>
			<td>Yes</td>
			<td>39</td>
			<td>No</td>
			<td>29</td>
			<td>10.1</td>
			
			<td>42</td>
			<td>42</td>
			<td>Yes</td>
			<td>Yes</td>
			<td>29</td>
			<td>10.1</td>
			<td>?</td>
		</tr>
	</tbody>
</table>

## See also:
- #1163

**Comment by teoli2003** [comment]
Overview tables are one of the reasons we wanted to have BCD in a machine-readable format.

The question here are:
- How do we indicate features inside an API that are not suppoorted. E.g. Interface1 is supported with property1 and property2. Interface1.property3 is not. How do we indicate this? (If we want)
- How do we deal with notes, prefixes, and alternative names?

**Comment by teoli2003** [comment]
Note that such macro should likely be discussed in more details (especially its implementation) in the kumascript repo :-)

Btw, I'm really excited to be see such macro being a thing we can do now!

**Comment by ExE-Boss** [comment]
>  How do we indicate features inside an API that are not suppoorted. E.g. Interface1 is supported with property1 and property2. Interface1.property3 is not. How do we indicate this?

We could probably use the formatting used when [`partial_implementation`](https://github.com/mdn/browser-compat-data/blob/master/schemas/compat-data-schema.md#partial_implementation) is `true` and only have it be green from the version that fully supports the feature.

**Comment by wbamberg** [comment]
In terms of the presentation of the tables, this should be just like the "aggregate tables" that we have in the WebExtension docs, e.g. https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs#Browser_compatibility. There are UI issue with these tables, for sure, but the solutions should be the same I think.

It would be interesting if the macro could make use of the `groups` in mdn/data, then for example you could do:

```
{{CompatOverview("css", "CSS Grid Layout")}}
```

...or something, and have it look up the contents from https://github.com/mdn/data/blob/master/css/properties.json.

**Comment by Elchi3** [comment]
Thanks for your issue! This got worked on here https://github.com/mdn/kumascript/pull/650

I'll close this here for now, this repo is just about the data, hopefully https://github.com/mdn/browser-compat-toolkit will deal with all displaying soon. For now issues like this are discussed / worked on in https://github.com/mdn/kumascript still.
