### ISSUE TITLE
Web Extensions - Safari iOS

### ISSUE THREAD

**Issue by lukewarlow** [mdn/browser-compat-data#12440]
#### What information was incorrect, unhelpful, or incomplete?

Currently the only mobile browser allowed to have web extensions listings is firefox android.

#### What did you expect to see?

Safari iOS as of version 15 will have support for web extensions. So this should be allowed and have data added for.

#### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://developer.apple.com/documentation/safari-release-notes/safari-15-beta-release-notes#:~:text=Added%20support%20for%20Safari%20Web%20Extensions%20in%20iOS%20and%20iPadOS.

**Comment by M7sn1982** [comment]
`false`

**Comment by M7sn1982** [comment]
~~@M7sn1982 ~~

**Comment by queengooborg** [comment]
This has been resolved by numerous PRs, starting with #13279!
