### ISSUE TITLE
api.RTCRtpTransceiver.setCodecPreferences - Supported by Chrome

### ISSUE THREAD

**Issue by saschanaz** [mdn/browser-compat-data#12469]
#### What information was incorrect, unhelpful, or incomplete?

It says Chrome has no support

#### What did you expect to see?

Chrome support version

#### Did you test this? If so, how?

`RTCRtpTransceiver.prototype.setCodecPreferences` on console

<details>
<summary>MDN page report details</summary>

* Query: `api.RTCRtpTransceiver.setCodecPreferences`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/RTCRtpTransceiver/setCodecPreferences
* Report started: 2021-09-17T11:30:55.902Z

</details>

**Comment by queengooborg** [comment]
This was fixed in #14318!
