### ISSUE TITLE
Support compatibility table for manifest keys (and subkeys!)

### ISSUE THREAD

**Issue by Rob--W** [mdn/browser-compat-data#125]
There is no way to see when a specific manifest key is supported:
E.g. look at https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/commands

I want to add some version-specific compatibility notes. E.g. base support in Firefox 48, support for `_execute_browser_action` in Firefox 52, note that Firefox requires `suggested_key` to be set whereas Chrome allows it to be `null`.

Currently the work-around is to [write it in the text itself](https://bugzilla.mozilla.org/show_bug.cgi?id=1246034#c47), but that makes it more difficult to quickly find whether an API is well-supported or not.

**Comment by wbamberg** [comment]
I really want to do this, but there's currently a project to revise the JSON schema used for compat data. I'd prefer to wait until the new schema is agreed before adding manifest.json data.

**Comment by Elchi3** [comment]
This is now done \o/

**Comment by wbamberg** [comment]
-> https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json#Browser_compatibility
