### ISSUE TITLE
javascript.builtins.WeakRef - Latest opera supports WeakRef

### ISSUE THREAD

**Issue by DimaIT** [mdn/browser-compat-data#12523]
#### What information was incorrect, unhelpful, or incomplete?

`WeakRef` marked as unsupported in Opera browser

#### What did you expect to see?

`WeakRef` to be marked as supported in Opera browser
- since version 70 on desktop (underlying chromium 84 supports `WeakRef`)
- I believe it's also supported on android, but can't check

#### Did you test this? If so, how?

Checked Opera 79 on MacOs, `WeakRef` present

<details>
<summary>MDN page report details</summary>

* Query: `javascript.builtins.WeakRef`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakRef
* Report started: 2021-09-21T13:32:54.952Z

</details>

**Comment by Danimilad** [comment]
اصلاح 404

**Comment by dy** [comment]
Yes, confusing from the MDN docs.

**Comment by Elchi3** [comment]
This is fixed https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakRef#browser_compatibility
