### ISSUE TITLE
api.KeyboardEvent.repeat - IE11/Edge don't have full support

### ISSUE THREAD

**Issue by TheWyo** [mdn/browser-compat-data#12529]
#### What information was incorrect, unhelpful, or incomplete?
Compatibility table for IE & Edge (pre-Chromium version)

#### What did you expect to see?
IE & Edge should be listed as partial support. They support the repeat property, but the value of it is always false.

#### Did you test this? If so, how?
Add the following to the console and hold a key.
```js
document.addEventListener("keydown", function(e) {console.log(e.key, e.repeat)})
```

Change appears to have come from #10206, the test used to determine support only checks the existence of the property, not that its behaviour is correct. I don't have old Edge anymore to double check but I'm fairly sure I remember it doing the same as IE does in always returning false.

<details>
<summary>MDN page report details</summary>

* Query: `api.KeyboardEvent.repeat`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/repeat
* Report started: 2021-09-21T16:26:08.187Z

</details>

**Comment by queengooborg** [comment]
I'm closing this issue since the IE data was frozen a few releases back.
