### ISSUE TITLE
Is there a way to indicate "not applicable" for versions

### ISSUE THREAD

**Issue by hamishwillee** [mdn/browser-compat-data#12533]
Discussion came up [here](https://github.com/mdn/content/issues/9139) asking why HTTP `Digest` and `Want-Digest` headers are marked as "supported" when the browser does nothing with them. This is answered in  #4600:

> I have just used true here, since all browsers have to do to support it is include any request headers they are asked to include, and expose any response headers the server sends them.

I understand why this is done, but it is [misleading](https://github.com/mdn/content/issues/9139#issuecomment-924549071). 
What are our options?

I was thinking that it would be quite convenient to be able indicate that the whole support story is "Not applicable" - so you could keep the spec links, and possibly even have sub features, but not have to fill in the support section. Possibly with a note as to why it isn't applicable.

@ddbeck Thoughts?

**Comment by reschke** [comment]
What makes things even worse is this:

  https://caniuse.com/mdn-http_headers_digest

It suggests that some browsers do things others do not, which evidently is not true.

**Comment by queengooborg** [comment]
If there's a feature that doesn't really have compatibility data, such as dictionaries, typedefs, or in this case an HTTP header that browsers do nothing with, then the general consensus has been that it doesn't belong here in BCD.  Thus, I'd say we should probably remove this entry?

I opened up an issue on Yari discussing possible fallbacks for the spec URL when a feature isn't in BCD, see https://github.com/mdn/yari/issues/4704.

**Comment by hamishwillee** [comment]
@queengooborg I chatted to @ddbeck about this on Thursday. While it is correct that there is no browser compatibility "story" it might be worth looking at other alternatives:
- Knowing that something has no compatibility story can be useful - so we don't revisit this every time someone else comes to do compatibility documentation.
- Having spec data here is useful. Further you can't necessarily easily just replace in yari, particularly when BCD breaks down to a lower level than MDN docs.

Daniel is going to have a chat with other team members offline to work though options (presumably including you).

**Comment by LPardue** [comment]
Hey, I'm an editor on the Digest header draft. I agree with all of Julian's points here and the issue on the content repo. 

Digest and Want-Digest are request and response header and trailer fields I can think of dozens of permutations of how Digest could be used by client or server. The draft includes a handful https://httpwg.org/http-extensions/draft-ietf-httpbis-digest-headers.html#appendix-B

The browsers are using Digest headers for anything, so they can't support anything. Passing through headers isnt support, it is simply not blocking or dropping them.

One example of support would be for a browser to verify a response's Digest before loading it. No browsers actually do that. (Subresource Integrity, although similar, is entirely different). Another example is a browser automatically adding a Digest header to requests with a payload. No browsers do that either.

Not using a header is not equivalent to "not applicable" in my opinion. Someone somewhere inna browser team has decided not to implement Digest. That's their prerogative.

Browsers passing through headers can perhaps be a reflection on https://developer.mozilla.org/en-US/docs/Glossary/Forbidden_header_name

**Comment by hamishwillee** [comment]
@queengooborg The comment from ^^@LPardue above more or less agrees with your point - we do nothing with the header so it  isn't in BCD.

Personally that just changes my suggestion from being able to specify "na" at the top level to `false` at the top level (rather than having to build out a full tree). It is useful to explicitly say false rather than to say nothing.

**Comment by hamishwillee** [comment]
FYI @ddbeck Says that **for now** these should be marked as `null` in preference to `true`, `false` or a specific version. It isn't strictly correct but it is more correct than saying that they are supported or they are not supported. This will doubtless be revisited in future.

**Comment by queengooborg** [comment]
We had just removed most of the HTTP status codes in #23529 for the very reason that support isn't applicable for browsers, and the browsers won't do anything different for them (aside from the ones that we kept).  So, I'm going to close this and say "no, BCD will not have an N/A support declaration", and any features that wouldn't have browser support applicable wouldn't belong in BCD.
