### ISSUE TITLE
css.properties.font-variant-alternates - is not deprecated

### ISSUE THREAD

**Issue by fantasai** [mdn/browser-compat-data#12546]
#### What information was incorrect, unhelpful, or incomplete?

MDN claims that font-variant-alternates is deprecated, but it is still in the most recent specs from the CSSWG, so this seems incorrect.

#### What did you expect to see?

No deprecation notice.

#### Did you test this? If so, how?

Looking up the spec: https://www.w3.org/TR/css-fonts-4/#font-variant-alternates-prop

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.font-variant-alternates`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-alternates
* Report started: 2021-09-22T21:43:53.071Z

</details>

**Comment by queengooborg** [comment]
This was resolved by #14892!
