### ISSUE TITLE
Feature Policy - Firefox data is all flagged

### ISSUE THREAD

**Issue by lukewarlow** [mdn/browser-compat-data#12545]
#### What information was incorrect, unhelpful, or incomplete?

Firefox support for "Feature-Policy" header all states that it's only supported behind a flag.

#### What did you expect to see?

Some if not all have been partially supported since Firefox ~~[73](https://bugzilla.mozilla.org/show_bug.cgi?id=1600883)~~ [74](https://bugzilla.mozilla.org/show_bug.cgi?id=1617219). Only working inside the allow attribute.

#### Did you test this? If so, how?

I've validated that for the "display-capture" feature policy it definitely works as of at least version 74.

#### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy

**Comment by lukewarlow** [comment]
Follow up issue after noticing more than just display capture was wrong when doing https://github.com/mdn/browser-compat-data/pull/11700

**Comment by lukewarlow** [comment]
This data was originally added as a full support in 74. But was later reverted in https://github.com/mdn/browser-compat-data/pull/9280. It should have been changed to only partial implementations with a note (like has been done for Safari).

**Comment by lukewarlow** [comment]
Behind the `dom.security.featurePolicy.experimental.enabled` flag, the following policies are supported. Not sure on exact version they were added yet.

`autoplay`
`document-domain`
`encrypted-media`
`midi`
`payment`
`xr-spatial-tracking`

**Comment by queengooborg** [comment]
It appears that the data has been fixed at least since the rename to `Permissions-Policy`, so I'm going to close this issue.  If I'm missing anything, please let me know.
