### ISSUE TITLE
webextensions.manifest.theme - Wrong and unchangeable colors in color.firefox.com

### ISSUE THREAD

**Issue by tempuserr** [mdn/browser-compat-data#12554]
Unchangeable black background on context menus:

![image](https://user-images.githubusercontent.com/12864611/134531564-fe6e92a3-b6b1-40c4-b960-c60155cc6c9e.png)

Before setting few colors on color.firefox.com context menu background was system default (white or light gray).

What is wrong??

#### What did you expect to see?
System default background color.

#### Did you test this? If so, how?

<details>
<summary>MDN page report details</summary>

* Query: `webextensions.manifest.theme`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/theme
* Report started: 2021-09-23T14:51:02.525Z

</details>

**Comment by tempuserr** [comment]
User on reddit "reverse engineered" why there is black background on context menus:
reddit.com/r/firefox/comments/nt7e5y/firefox_color_how_to_change_color_of_context_menu/

Obviously linking it to "Background Tab Text Color" is not thought out.

**Comment by queengooborg** [comment]
Closing because this issue is irrelevant to the BCD project.  I'm assuming this is something you'd like Firefox to fix, if so please open a bug at https://bugzil.la.
