### ISSUE TITLE
Checking All Features for Chrome - Incorrect Data

### ISSUE THREAD

**Issue by gumulaola** [mdn/browser-compat-data#12596]
#### What information was incorrect, unhelpful, or incomplete?
I tested the features for **Chrome** on **PC** completely, and got the following result:
![data](https://user-images.githubusercontent.com/71512917/134844392-c1f52e16-01ba-4d17-bced-d0bca26f9185.png)
#### Did you test this? If so, how?
I tested them in real browsers controlled by a NPM package called "[selenium-webdriver](https://www.npmjs.com/package/selenium-webdriver)".
Our test is from Chrome **15** to the **latest** version.

**Comment by queengooborg** [comment]
Hey @gumulaola, thanks for looking into these!  We'd happily welcome PRs to correct the data if you're willing to write them.  😄

**Comment by queengooborg** [comment]
It looks like all the features mentioned have been updated via results from the mdn-bcd-collector, or removed as irrelevant!
