### ISSUE TITLE
Uncaught DOMException: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.     at HTMLAnchorElement.<anonymous> (file:///C:/Users/Mahima/Desktop/Task2%20SolutionAbhishekSachan/script.js:43:29) (anonymous) @ script.js:43

### ISSUE THREAD

**Issue by ABHISHEK64** [mdn/browser-compat-data#12597]
I used this function in my code
but it shows the error: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.     at HTMLAnchorElement.<anonymous> 
I don't know how to fixed:
here my code:
//where error occur
downloadBtn.addEventListener('click',function(){
    downloadBtn.href=canvas.toDataURL('image/jpeg', 1.0)
    downloadBtn.download='true';
})

**Comment by queengooborg** [comment]
Closing because this is not a development help forum.  Please use a dedicated service like StackOverflow to get development help.
