### ISSUE TITLE
css.properties.transform-style - Problem in Chrome 94

### ISSUE THREAD

**Issue by CleberLopess** [mdn/browser-compat-data#12604]
Parece que não funciona na nova versão do Chrome (v.94)

Ele não esta realizando o efeito corretamente de rodate 3d

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.transform-style`
* MDN URL: https://developer.mozilla.org/pt-BR/docs/Web/CSS/transform-style
* Report started: 2021-09-27T18:09:45.348Z

</details>

**Comment by queengooborg** [comment]
This sounds like it's probably a development issue, not a browser issue.  The MDN page's examples are working just fine on my Chrome installation.

Esto parece que probablemente sea un problema de desarrollo, no un problema del navegador. Los ejemplos de la página MDN están funcionando bien en mi instalación de Chrome.

**Comment by CleberLopess** [comment]
beleza, voce me deu uma ideia de rodar do codePain, vou fazer o teste


OK, you gave me an idea to run codePain, I'll do the test

**Comment by CleberLopess** [comment]
Eu uso também o navegador brave, baseado em chominum, nele esta a versão ainda 93, e esta funcionando, e essa atualização do crome, veio nesta madrugada 26 -> 27, por isso associei ao problema


I also use the brave browser, based on chominum, it's still version 93, and it's working, and this crome update came this morning 26 -> 27, so I associated it with the problem

**Comment by HugoFortunato** [comment]
Just like Cleber explained. This happens specifically with the transform-style property: preserve-3d.

**Comment by HugoFortunato** [comment]
Just like Cleber explained. This happens specifically with the transform-style property: preserve-3d.

**Comment by HugoFortunato** [comment]
Hi!

The problem has been solved, however, I'm still not sure if it was just a development problem. What I can say is that the application worked until version 93 of Chrome.

The problem was solved with a CSS combinations game, studying the backface-visibility functionality well.

As the case was initially resolved here in development, I believe this issue can be closed.

**Comment by lukewarlow** [comment]
https://chromestatus.com/feature/5640541339385856 - could be relevant
