### ISSUE TITLE
Console - Substitution Strings appears 3 times with the same data

### ISSUE THREAD

**Issue by grian32** [mdn/browser-compat-data#12607]
#### What information was incorrect, unhelpful, or incomplete?
Substitution strings part of Console API Appearing 3 times instead of one
#### What did you expect to see?
It appearing once.
#### Did you test this? If so, how?
N/A
#### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?
https://developer.mozilla.org/en-US/docs/Web/API/Console_API#browser_compatibility

**Comment by hamishwillee** [comment]
@queengooborg Thanks for the clarification. If combining does not work, then I think this would have to be moved to the yari repo - because MDN authors don't have specific control over the rendering.

**Comment by queengooborg** [comment]
> @queengooborg Thanks for the clarification. If combining does not work, then I think this would have to be moved to the yari repo - because MDN authors don't have specific control over the rendering.

I thought the `Compat` macro had a depth parameter?  Is that not the case?

**Comment by hamishwillee** [comment]
@queengooborg [It appears to](https://github.com/mdn/yari/blob/main/kumascript/macros/Compat.ejs). This was news to me - hence my previous post to move it back - Sorry!

So we can try this if you want. For now I will assume you are merging the data. If you change your mind though let me know,..

**Comment by queengooborg** [comment]
I think that we should go forward with merging these subfeatures together, since their compatibility data is so similar I don't think it makes sense to keep them separate!
