### ISSUE TITLE
Add ranges for Chrome and Firefox

### ISSUE THREAD

**Issue by queengooborg** [mdn/browser-compat-data#12626]
During my weekly discussion with @foolip, we were talking about adding ranges for Chrome for the earliest versions available in BrowserStack and SauceLabs.  I think it would make sense to do the same for Firefox as well.

This issue is to propose that we add Chrome ≤15, Chrome ≤26, and Firefox ≤4 as allowed ranges.

**Comment by foolip** [comment]
Why do we need both Chrome ≤15 and Chrome ≤26?

**Comment by queengooborg** [comment]
Chrome 15 is the lowest that BrowserStack will go, whereas Chrome 26 is for ￼SauceLabs.  We could just stick with Chrome 26 though?

**Comment by foolip** [comment]
I would go with just Chrome ≤15, since we can get the data. I think BrowserStack is slightly more popular than Sauce, and we probably could get an account for BCD if other contributors need it.

**Comment by queengooborg** [comment]
We do have a BCD team for BrowserStack, so alright, let's go for just Chrome ≤15!

**Comment by foolip** [comment]
@queengooborg do you want to send a PR for this?

**Comment by saschanaz** [comment]
Should this be closed too per https://github.com/mdn/browser-compat-data/pull/12661#issuecomment-951636721 ?
