### ISSUE TITLE
`height: fit-content` Firefox - Marked as not supported

### ISSUE THREAD

**Issue by lukewarlow** [mdn/browser-compat-data#12643]
#### What information was incorrect, unhelpful, or incomplete?
The fit-content value for height is marked as not supported in Firefox and Firefox Android.

#### What did you expect to see?
I would expect it to have a similar support as width: fit-content. At least partially supported via a prefix. I'm not sure on the version this was added else I'd make a PR for it.

#### Did you test this? If so, how?
The red column is only the height of its content (and it has fit-content) where as the blue column is larger (it doesn't have fit-content). 
https://jsfiddle.net/bawy06Lx/3/

#### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://developer.mozilla.org/en-US/docs/Web/CSS/height#browser_compatibility

**Comment by robinmetral** [comment]
Related: https://github.com/mdn/browser-compat-data/issues/13428

**Comment by ADTC** [comment]
Can we get clarity on this?

**Comment by ADTC** [comment]
Can we get clarity on this? Even this site is confusing: https://caniuse.com/mdn-css_properties_height_fit-content

**Comment by queengooborg** [comment]
Fixed in #19522!
