### ISSUE TITLE
css.properties.text-align - match-parent requires prefix on Chrome.

### ISSUE THREAD

**Issue by rosshjb** [mdn/browser-compat-data#12648]
#### What information was incorrect, unhelpful, or incomplete?
`text-align: match-parent` needs vendor prefix `-webkit-` on recent Chrome.

#### What did you expect to see?
`match-parent` value requires a vendor prefix for Chrome. So, it should be marked as `-x-`.

#### Did you test this? If so, how?
I tested this feature on Chrome 94.0.4606.61 running on macOS 11.6.

https://codepen.io/rosshjb/pen/NWgoQBM

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.text-align`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/text-align
* Report started: 2021-09-29T23:11:20.457Z

</details>

**Comment by queengooborg** [comment]
This has been fixed in #20170!
