### ISSUE TITLE
`input-security` - Missing data

### ISSUE THREAD

**Issue by lukewarlow** [mdn/browser-compat-data#12664]
#### What information was incorrect, unhelpful, or incomplete?
There's no MDN browser compat entry for the [`input-security`](https://drafts.csswg.org/css-ui-4/#input-security) property.

#### What did you expect to see?
An entry for it. ~~It's now supported in Safari TP 133~~ it would seem that's not actually true, an entry for it would still be good though as it's coming soon.

#### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?
https://webkit.org/blog/11975/release-notes-for-safari-technology-preview-133/#:~:text=Added%20support%20for%20input-security

Issue for the content entry: https://github.com/mdn/content/issues/9422

MR for the syntax data: https://github.com/mdn/data/pull/512

**Comment by lucalves** [comment]
I would like to work on it. However, you would need to know what to include in the `input-security` page entry.

**Comment by stefanjudis** [comment]
Headsup. :) I just played around with `input-security` and doesn't look like it is supported.

<img width="746" alt="image" src="https://user-images.githubusercontent.com/962099/135588835-c358195f-8df8-4d1e-a0cb-fd6c49502507.png">

<img width="347" alt="image" src="https://user-images.githubusercontent.com/962099/135588874-92a88258-6086-4653-9ca0-98eabfc2059f.png">

**Comment by lukewarlow** [comment]
> Headsup. :) I just played around with `input-security` and doesn't look like it is supported.
> 
> <img alt="image" width="746" src="https://user-images.githubusercontent.com/962099/135588835-c358195f-8df8-4d1e-a0cb-fd6c49502507.png">
> 
> <img alt="image" width="347" src="https://user-images.githubusercontent.com/962099/135588874-92a88258-6086-4653-9ca0-98eabfc2059f.png">

Strange, I've tested too and you're right. The change set doesn't look like it's behind a flag (and one doesn't exist) so I assume it's just wrong and will come in the next release.

**Comment by lukewarlow** [comment]
> I would like to work on it. However, you would need to know what to include in the `input-security` page entry.

To start with a very basic page that gives a rough description of the property, would be useful. Once supported in more browsers then an interactive example might be useful. 

I've made an issue in the mdn/content repo to add a page for it.

**Comment by lukewarlow** [comment]
Looks like Safari has put this behind a flag for now https://github.com/WebKit/WebKit/commit/bed3cc8a73bd94b0061e87ba313baa5506a136ac

And sounds like the CSSWG might drop the property from the spec entirely. https://github.com/w3c/csswg-drafts/issues/6788

Given the above two points, and the lack of movement on the blocking discussion (should this be separate or a replacement for the existing `-webkit-text-security` property) for the associated PR, I'm gonna go ahead and close this issue.
