### ISSUE TITLE
api.Document.fullscreen - iOS Support

### ISSUE THREAD

**Issue by manngo** [mdn/browser-compat-data#12683]
#### What information was incorrect, unhelpful, or incomplete?

Support table indicates that this is supported on iPad, but not iPhone (14.7)

#### What did you expect to see?

As of iOS 15, this feature is not supported at all.

This is reflected on CanIUse: https://caniuse.com/fullscreen

#### Did you test this? If so, how?

Certainly not working on iPad OS 15.

<details>
<summary>MDN page report details</summary>

* Query: `api.Document.fullscreen`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API
* Report started: 2021-10-02T22:58:02.769Z

</details>

**Comment by queengooborg** [comment]
The data on CanIUse indicates that it is still supported in the latest Safari on iPadOS.  As such, I'm going to go ahead and close this issue.
