### ISSUE TITLE
javascript.statements.import - <PUT TITLE HERE>

### ISSUE THREAD

**Issue by lukmangrd** [mdn/browser-compat-data#12688]
#### Did you test this? If so, how?

<details>
<summary>MDN page report details</summary>

* Query: `javascript.statements.import`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules
* Report started: 2021-10-03T17:38:38.689Z

</details>

**Comment by evilpie** [comment]
@lukmangrd Can you please comment what the issue you found with the article?

**Comment by queengooborg** [comment]
I'm re-closing this issue because the issue template is empty and there has been no actionable information.  I am also locking the thread because it was reopened by the author, who appears to be a user bot based upon their profile.
