### ISSUE TITLE
Remove IE/Edge-only features early

### ISSUE THREAD

**Issue by queengooborg** [mdn/browser-compat-data#12725]
During my weekly meeting with @foolip, we were talking about ways to reach 100% real values for the API folder. We came across a couple of categories of features that still have true/null values, but don't seem worthwhile to hunt down the version numbers since they'll be removed already or should be removed.

One of these categories is features that were only present up to Edge 18 and removed in Edge 79 due to the switch to Chromium.  There are many features that were only in IE and/or pre-Chrome Edge, and a portion of these features that have non-real data.  Although these features aren't ready to be considered as irrelevant and ready for removal, it doesn't make too much sense to try and find real values for these features that are going to be removed in a few months anyways.

I'm proposing that we expedite the removal of these EdgeHTML- and Trident-only features to reach 100% real values for the API folder by the end of the year.

**Comment by qwsubah** [comment]
> خلال اجتماعي الأسبوعي مع foolip ، كنا نتحدث عن طرق للوصول إلى 100٪ من القيم الحقيقية لمجلد API. لقد صادفنا فئتين من الميزات التي لا تزال تحتوي على قيم صحيحة / فارغة ، ولكن لا يبدو أنه من المفيد البحث عن أرقام الإصدارات حيث ستتم إزالتها بالفعل أو يجب إزالتها.
> 
> إحدى هذه الفئات هي الميزات التي كانت موجودة فقط حتى Edge 18 وتمت إزالتها في Edge 79 بسبب التبديل إلى Chromium. هناك العديد من الميزات التي كانت موجودة فقط في IE و / أو ما قبل Chrome Edge ، وجزء من هذه الميزات يحتوي على بيانات غير حقيقية. على الرغم من أن هذه الميزات ليست جاهزة لاعتبارها غير ملائمة وجاهزة للإزالة ، فليس من المنطقي محاولة العثور على قيم حقيقية لهذه الميزات التي ستتم إزالتها في غضون بضعة أشهر على أي حال.
> 
> أقترح أن نقوم بالإسراع بإزالة ميزات EdgeHTML و Trident-only للوصول إلى قيم حقيقية 100٪ لمجلد API بحلول نهاية العام.

**Comment by queengooborg** [comment]
Our real values reasoning no longer applies since we've reached 100% real values, mostly by just putting in random version numbers for the data that's too hard to obtain.  I still think this would be great to do though.  :D

**Comment by foolip** [comment]
It's only a few weeks until Edge 79 turns two years old and lots of features can be removed per guidelines.

**Comment by queengooborg** [comment]
True -- just looking for more things to tackle before the end of this year's contract!  😝

**Comment by foolip** [comment]
You could always create a lot of PRs and expect them to sit unreviewed for 2 weeks.

**Comment by queengooborg** [comment]
Removing these features is no longer an "early" chore, so I'm closing this issue.
