### ISSUE TITLE
Web App Manifest New Note URL - Missing

### ISSUE THREAD

**Issue by lukewarlow** [mdn/browser-compat-data#12730]
#### What information was incorrect, unhelpful, or incomplete?
There's no entry for [Note Taking New Note URL](https://wicg.github.io/manifest-incubations/index.html#note_taking-member).

#### What did you expect to see?
An entry for it, with support data for desktop Chrome 95 (https://www.chromestatus.com/feature/5205972320518144). (And presumably Edge 95 and Opera 81 too)

**Comment by rebloor** [comment]
This feature is not included as part of the [Chrome manifest developer documentation](https://developer.chrome.com/docs/extensions/reference/manifest) yes.

**Comment by Rob--W** [comment]
This issue is not about WebExtensions, but https://developer.mozilla.org/en-US/docs/Web/Manifest
