### ISSUE TITLE
css.properties.display - Safari on iOS compatibility

### ISSUE THREAD

**Issue by Azhrei** [mdn/browser-compat-data#12735]
Safari, iOS 15.0.1

#### What information was incorrect, unhelpful, or incomplete?
Changing the live demo of `display: contents` from https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Relationship_of_Flexbox_to_Other_Layout_Methods produces the proper result.

#### What did you expect to see?
The compatibility guide caused me to think it wouldn't work.

#### Did you test this? If so, how?
See the live demo, above.

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.display`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/display
* Report started: 2021-10-07T00:40:36.375Z

</details>

**Comment by queengooborg** [comment]
The compatibility data states that `display: contents` is supported in Safari iOS.  I'm not sure what needs to be updated in our data.
