### ISSUE TITLE
css.selectors.part - Firefox for Android versions seems to work

### ISSUE THREAD

**Issue by remcovaes** [mdn/browser-compat-data#12752]
Browser version: 93.1.0
Firefox browser for android

#### What information was incorrect, unhelpful, or incomplete?
css.selectors.part is marked as not supported.

#### What did you expect to see?
Either partial or full support for the feature.

#### Did you test this? If so, how?
Run the following code on your phone:
html
`<example-component></example-component>`

css
`example-component::part(box) {
  background-color: pink;
}`

js
```
customElements.define('example-component', class extends HTMLElement {
  constructor() {
    super(); 
    
    const shadowRoot = this.attachShadow({mode: 'open'});
    shadowRoot.innerHTML = `
      <style>
        div {
            height: 150px;
            width: 150px;
            border: solid 2px;
          }
      </style>
      
      <div part="box"></div>  
      <button>Button in Shadow DOM</button>
    `;
  }
});
```

I used the following url for a quick test: https://webcomponents.dev/edit/S45Y3qIC6a9oTtamlrtS/src/index.js

<details>
<summary>MDN page report details</summary>

* Query: `css.selectors.part`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/::part
* Report started: 2021-10-08T09:42:22.105Z

</details>

**Comment by queengooborg** [comment]
This has been resolved by #13628!
