### ISSUE TITLE
css.properties.hyphens - Supported in Chrome on all platforms

### ISSUE THREAD

**Issue by BathoryPeter** [mdn/browser-compat-data#12762]
#### What information was incorrect, unhelpful, or incomplete?

Chrome supports ```hyphens: auto``` from version 88 on all operating systems now.
See: https://www.chromestatus.com/feature/5672891947417600

#### Did you test this? If so, how?

Works with Hungarian language in Vivaldi 4.2 (Chrome 93).

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.hyphens`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/hyphens
* Report started: 2021-10-09T19:31:03.308Z

</details>

**Comment by queengooborg** [comment]
This has been resolved by #18887!
