### ISSUE TITLE
api.KeyboardEvent.key - Safari support

### ISSUE THREAD

**Issue by zaygraveyard** [mdn/browser-compat-data#12849]
#### What information was incorrect, unhelpful, or incomplete?

Support for macOS and iOS Safari

#### What did you expect to see?

The version that supports it:
Feature    | Safari  | iOS Safari
-------------------|-----------|---------------
**Dead key**  | `15`^     | ?
**Non-printable keys**  | `10.1`     | `10.3`\*
**Printable keys**  | `10.1`     | `10.3`

**^**: Dead keys don't work in BrowserStack so I was unable to test it
**\***: `Enter` and `Backspace` but no `Shift` before iOS Safari `14.7` and iPadOS Safari `13.4` (other keys were not tested)

#### Did you test this? If so, how?

Yes, by using [the example on MDN](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key#result) on a mac (Safari 15), an iPhone (iOS 14.8) and using BrowserStack for older versions.

<details>
<summary>MDN page report details</summary>

* Query: `api.KeyboardEvent.key`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key
* Report started: 2021-10-14T13:44:40.194Z

</details>

**Comment by queengooborg** [comment]
Thanks for researching this!  I was actually able to trigger a dead key in BrowserStack somehow, so I could confirm all three of these were supported in Safari 10.1!
