### ISSUE TITLE
api.ResizeObserverEntry - Partial Safari 13 Support

### ISSUE THREAD

**Issue by kurtrank** [mdn/browser-compat-data#12850]
I was troubleshooting why I was having issues with an accordion component in Safari, and it turns out that the newer `contentBoxSize` property I was using is not available in Safari. It turns out that I can get around needing to use that property for my use case, but MDN lists no support at all for ResizeObserverEntry.

#### What information was incorrect, unhelpful, or incomplete?

Safari Compatibility data for ResizeObserverEntry.

#### What did you expect to see?

Support for some features of ResizeObserverEntry.

#### Did you test this? If so, how?

Yes, I tested locally with Safari 14.1.2 as well as iOS 13.2 Safari via browserstack. ResizeObserverEntry appears to be supported along with the `contentRect` and `target` properties.

<img width="755" alt="Screen Shot 2021-10-14 at 11 19 28 AM" src="https://user-images.githubusercontent.com/11091840/137348668-b1c44e35-fb84-4680-918f-13b996ec8a04.png"> 

<details>
<summary>MDN page report details</summary>

* Query: `api.ResizeObserverEntry`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserverEntry
* Report started: 2021-10-14T15:17:33.433Z

</details>

**Comment by queengooborg** [comment]
We've actually added data for this back in #3213!  For `contentBoxSize` in particular, we've updated the data in #12439 to indicate it will be coming in the following Safari release.
