### ISSUE TITLE
Update and complete RTCPeerConnection

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#1288]
There has been a massive PR to add RTCPeerConnection (#1070), a few things were left out which we should add:
https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/close
https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/addTransceiver
https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/currentRemoteDescription
https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/iceGatheringState
https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/onicecandidateerror

(we could also wait until we've initially updated the MDN pages [which will happen soon] and then update/correct this file for other issues found.)

**Comment by jlaine** [comment]
It looks as though there was some unfortunate copy-and-paste somewhere, for instance I noticed that the information about RTCPeerConnection.getSenders was not correct, see #1713. I'll check if I find any other errors.

**Comment by jlaine** [comment]
RTCPeerConnection.getReceivers was also wrong, see #1714.

**Comment by julfers** [comment]
`RTCPeerConnection.addTrack()` and `RTCPeerConnection.removeTrack()` had the same error as `getSenders()` see https://github.com/mdn/browser-compat-data/pull/1963

**Comment by Elchi3** [comment]
Looks like there is only https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/currentRemoteDescription#Browser_compatibility left to migrate here.

**Comment by Elchi3** [comment]
This was fixed in https://github.com/mdn/browser-compat-data/pull/2662
