### ISSUE TITLE
api.HTMLElement.focus - `options.preventScroll` supported in Safari 15

### ISSUE THREAD

**Issue by fritz-c** [mdn/browser-compat-data#12925]
#### What information was incorrect, unhelpful, or incomplete?
The `options.preventScroll` argument is marked as not supported in Safari 15 (desktop and mobile).
#### What did you expect to see?
The `options.preventScroll` argument is now supported in Safari 15 (desktop and mobile). The [bug tracker for adding the option has marked it as resolved as well](https://bugs.webkit.org/show_bug.cgi?id=178583).
#### Did you test this? If so, how?
Yes. I made [a codesandbox to test it](https://i1xni.csb.app/) ([source](https://codesandbox.io/s/htmlelement-focus-preventscroll-i1xni)).

https://user-images.githubusercontent.com/4413963/137767227-c19b0cc8-0180-4fd7-a732-a02a3d3f49b6.MP4

https://user-images.githubusercontent.com/4413963/137767575-8c97f61a-5491-4202-9115-cd4444bdab6c.mov

<details>
<summary>MDN page report details</summary>

* Query: `api.HTMLElement.focus`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus
* Report started: 2021-10-18T15:24:53.483Z

</details>

**Comment by woody-li** [comment]
https://developer.apple.com/safari/technology-preview/release-notes/#r124
Supported in TP 124, and Safari 15 is mapping with TP 126.

**Comment by queengooborg** [comment]
This has been fixed in #16589!
