### ISSUE TITLE
api.fetch - Nodejs not listed under "Browser Compatibility"

### ISSUE THREAD

**Issue by jeremylumanbailey** [mdn/browser-compat-data#12942]
#### What information was incorrect, unhelpful, or incomplete?
Browser compatibility

#### What did you expect to see?
Nodejs compatibility notes, it appears that the `fetch` API does not exist in Nodejs so it would make sense to list it as "no support". Deno appears to be listed, and Nodejs is usually listed on other docs, but it is not on this page.

#### Did you test this? If so, how?
Nodejs compatibility is not listed. 

<details>
<summary>MDN page report details</summary>

* Query: `api.fetch`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch
* Report started: 2021-10-20T03:11:05.024Z

</details>

**Comment by ddbeck** [comment]
Thanks again for reporting this, @jeremylumanbailey. See https://github.com/mdn/browser-compat-data/pull/13919#issuecomment-993803660 for an explanation of why this is unlikely to change.
