### ISSUE TITLE
api.Window.history - History interface compatibility in older IE

### ISSUE THREAD

**Issue by doesntgolf** [mdn/browser-compat-data#12999]
#### What information was incorrect, unhelpful, or incomplete?

The compatibility info on the History interface page (https://developer.mozilla.org/en-US/docs/Web/API/History) indicates that that API is available in IE beginning at version 10. The window.history page (https://developer.mozilla.org/en-US/docs/Web/API/Window/history) indicates that it is available beginning with IE4.

I'm guessing this means `window.history` prior to IE10 used a non-standard interface or something, but I'm not seeing any content documenting that (either on MDN or elsewhere online), so I'm not sure exactly what the case is. Otherwise, if the compat info on one of these pages is incorrect, it should just be corrected.

#### What did you expect to see?

Either:

 - `window.history` is available beginning with IE10 in compat table, or
 - an explanation of the History interface prior to IE10 (on `/Web/API/History` and/or `/Web/Window/history`)

#### Did you test this? If so, how?

No - I'm not sure how I can find the interface in IE9 or earlier.

<details>
<summary>MDN page report details</summary>

* Query: `api.Window.history`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/history
* Report started: 2021-10-21T21:52:24.433Z

</details>

**Comment by queengooborg** [comment]
I'm closing this issue since the IE data was frozen a few releases back.
