### ISSUE TITLE
inverted-colors media query - Safari is marked as full support but should be partial

### ISSUE THREAD

**Issue by lukewarlow** [mdn/browser-compat-data#12992]
#### What information was incorrect, unhelpful, or incomplete?
Safari is marked as full support, this should be partial.

#### What did you expect to see?
This attached webkit bug describes the issue fairly well, but in essence Safari's implementation is the exact opposite of what the spec says the behaviour should be. It matches for smart invert but not classic invert.

#### Did you test this? If so, how?
Yes using the MDN page.

#### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://developer.mozilla.org/en-US/docs/Web/CSS/@media/inverted-colors

https://bugs.webkit.org/show_bug.cgi?id=232041

**Comment by queengooborg** [comment]
I see the bug has been closed as "invalid", so i'm going to close this issue as well.
