### ISSUE TITLE
Add Java support information

### ISSUE THREAD

**Issue by ExE-Boss** [mdn/browser-compat-data#1301]
The Java programming language’s standard library comes with the [`java.xml` module](https://docs.oracle.com/javase/9/docs/api/java.xml-summary.html) which contains a spec compliant DOM3 implementation located in the [`org.w3c.dom` package and sub-packages](https://docs.oracle.com/javase/9/docs/api/org/w3c/dom/package-summary.html).

Java further contains a [CSS engine and an HTML4 binding in the `jdk.xml.dom` module](https://docs.oracle.com/javase/9/docs/api/jdk.xml.dom-summary.html), which are used by the JavaFX WebView (which uses WebKit as the base) to allow changes to the DOM from the Java code and the CSS engine is also used by JavaFX (albeit using non-standard features with everything prefixed).

I believe that it would be a good idea to add Java to the compatibility information, since we already have at least one non-browser entry (Node.js)

**Comment by Elchi3** [comment]
Java is out of scope for this project. Sorry.
