### ISSUE TITLE
:local-link page missing Specifications, Browser compatibility

### ISSUE THREAD

**Issue by erosman** [mdn/browser-compat-data#13029]
There is no Specifications, Browser compatibility on `:local-link` page.

MDN page: 
https://developer.mozilla.org/en-US/docs/Web/CSS/:local-link

Info: CSS Selector Level 4 » Local link pseudo-class
https://css4-selectors.com/selector/css4/local-link-pseudo-class/

**Comment by queengooborg** [comment]
https://github.com/mdn/browser-compat-data/pull/15253 attempted to add this, but no browser supports this feature, so it does not meet our criteria for addition to BCD.
