### ISSUE TITLE
javascript.builtins.Date.parse - MDN page has unincorporated compat notes

### ISSUE THREAD

**Issue by ddbeck** [mdn/browser-compat-data#13030]
#### What information was incorrect, unhelpful, or incomplete?

The page for `Date.parse` has a bunch of [compat notes outside of BCD](https://github.com/mdn/content/blob/cf607d68522cd35ee7670782d3ee3a361eaef2e4/files/en-us/web/javascript/reference/global_objects/date/parse/index.md#compatibility-notes) and several mentions of ES5 compat in the main content of the page. 

#### What did you expect to see?

All this stuff should be in BCD, rather than distributed through the content, especially the historical details.

#### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

Found out thanks to https://github.com/mdn/content/issues/9606

**Comment by Josh-Cena** [comment]
This content has been removed as it's out of scope for BCD too. @queengooborg this can be closed
