### ISSUE TITLE
Opera support Promise.any

### ISSUE THREAD

**Issue by mhf-ir** [mdn/browser-compat-data#13135]
https://github.com/mdn/browser-compat-data/blob/86ab7b04b6fc30f39462a81e70fbde2691d55c2c/javascript/builtins/Promise.json#L261

Tested on Opera 80 / Ubuntu / SnapCraft Installation
![Screenshot from 2021-10-27 12-36-28](https://user-images.githubusercontent.com/1172526/139035451-7305710b-d9bc-4cc6-8662-c379a4fedce1.png)

**Comment by Elchi3** [comment]
This is fixed https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/any#browser_compatibility
