### ISSUE TITLE
css.properties.image-rendering - It looks like Firefox now supports image-rendering: pixelated in the latest version

### ISSUE THREAD

**Issue by JoppyFurr** [mdn/browser-compat-data#13148]
#### What information was incorrect, unhelpful, or incomplete?
States that 'pixelated' is not supported on Firefox

#### What did you expect to see?
It looks like in the latest version, this has started working in Firefox

#### Did you test this? If so, how?
Created a test .html file with a 32x32 png image scaled up to 256x256, tested with Firefox 93

```html
<html>
    <body>
        <img src="test.png" width="256" height="256" style="image-rendering: pixelated">
    </body>
</html>
```

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.image-rendering`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/image-rendering
* Report started: 2021-10-27T21:03:39.389Z

</details>

**Comment by TobTobXX** [comment]
Can confirm. Tested with canvases too.

This is the Bug and change: https://bugzilla.mozilla.org/show_bug.cgi?id=856337
