### ISSUE TITLE
File System Access API - Standards track is marked as false

### ISSUE THREAD

**Issue by lukewarlow** [mdn/browser-compat-data#13149]
#### What information was incorrect, unhelpful, or incomplete?
Standards track is marked as false for all File System Access API related functions and interfaces (such as FileSystem{File|Directory}Handle)

#### What did you expect to see?
They have a WICG spec which I thought was enough to classed as standards track?

There's also multi implementor interest in form of Safari TP (See #12439 ) now supporting the origin private file system aspect of the spec (if that makes a difference)

**Comment by gsnedders** [comment]
c.f. #6103 and https://github.com/mdn/browser-compat-data/blob/main/schemas/compat-data-schema.md#status-information:

> If standard_track is true, then the feature is part of an active specification or specification process.

**Comment by lukewarlow** [comment]
Forgive me for my ignorance but is specification defined as specifically w3c anywhere? And I guess is it meant to mean that? I had a quick read of the linked issue but can't actually see a definitive conclusion.

Happy to close this issue if wicg specs is not classed as a specification for this purpose.
