### ISSUE TITLE
api.ProcessingInstruction - Microsoft Edge does not support

### ISSUE THREAD

**Issue by yecril71pl** [mdn/browser-compat-data#13164]
#### What information was incorrect, unhelpful, or incomplete?

Microsoft Edge does not support processing instructions in HTML documents.  It converts them into HTML comments.

#### What did you expect to see?

A processing instruction.

#### Did you test this? If so, how?
```html
<?xml version="1.0" ?><?custom-processing-instruction ?>
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title>Processing instruction support test</title><script type="text/javascript" >
        window.onload = function onload() {
            var l = document.forms.item(0).elements
            l.item(01).value = document.childNodes.item(l.item(0
            ) .value
            )
        }
    </script>
</head>
<body>
    <form action="#" method="post" enctype="multipart/form-data" >
        <p >
The type of node <input type="text" name="node-number" value="1" />
 is <input type="text" name="node-type" readonly />.
        </p>
    </form>
</body>
</html>
```

<details>
<summary>MDN page report details</summary>

* Query: `api.ProcessingInstruction`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/ProcessingInstruction
* Report started: 2021-10-28T10:42:04.964Z

</details>

**Comment by queengooborg** [comment]
Using your test code, I see no differences between Edge and Chrome, so I cannot confirm that it is unsupported.
