### ISSUE TITLE
CSS opacity: Safari support for percentage values

### ISSUE THREAD

**Issue by pascalduez** [mdn/browser-compat-data#13163]
#### What information was incorrect, unhelpful, or incomplete?

Safari support for `opacity` percentage values is set as none, whereas it appear to be supported, at least in recent versions.

#### What did you expect to see?

Updated data.

#### Did you test this? If so, how?

Tested with UA `"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15 Epiphany/605.1.15"` and works as expected.   
Would need investigation to understand from wich version precisely it was introduced.   

- https://webkit.org/status/#specification-css-color-level-4 (CSS color level 4 marked as supported...)

**Comment by chalkygames123** [comment]
Possibly related: https://webkit.org/blog/9672/release-notes-for-safari-technology-preview-97/

> Fixed opacity to always serialize as a number ([r251828](https://trac.webkit.org/changeset/251828/webkit/))

I have tried identifying the exact version of the stable release, but I have had no luck.

**Comment by queengooborg** [comment]
This has been fixed in #20035!
