### ISSUE TITLE
WeakRef - Opera 80 supports WeakRef but is shown as unsupported

### ISSUE THREAD

**Issue by pfriesch** [mdn/browser-compat-data#13174]
#### What information was incorrect, unhelpful, or incomplete?
The combability page for Weak Ref shows that Opera 80 does not support WeakRef, when in fact it does.

#### What did you expect to see?
Opera 80 shown as green for WeakRef

#### Did you test this? If so, how?
I ran the example code from the [MDN page for WeakRef](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakRef) in Opera 80.

**Comment by queengooborg** [comment]
Duplicate of #12523.
