### ISSUE TITLE
Opera Desktop supports justify-content & align-items: start/end in flexbox layout but it says it doesn't

### ISSUE THREAD

**Issue by xRitsu** [mdn/browser-compat-data#13184]
Opera on desktops renders justify-content & align-items: start and end in flexbox layout properly now. However, Opera Mobile always fails. You actually need to use flex-start and flex-end to do so, maybe that should be noted as well.

Pen: https://codepen.io/x-Ritsu/pen/JjyyxgW
CanIUse tables: https://caniuse.com/?search=justify-content

![Screenshot_1](https://user-images.githubusercontent.com/26928100/139527338-597641fe-52ce-44d5-91d6-fba633e995fa.png)
![Screenshot_2021-10-30-11-19-12-451_com opera browser](https://user-images.githubusercontent.com/26928100/139527411-b60f28b6-891b-45cd-aff8-b4c477b02386.jpg)

**Comment by queengooborg** [comment]
Fixed in #12602!
