### ISSUE TITLE
api.Document.fullscreenEnabled - <return undefined in in Safari browser 15>

### ISSUE THREAD

**Issue by lboradzhiev** [mdn/browser-compat-data#13228]
As you can see from the screenshot below I'm trying to verify if the fullscreen is enabled i.e. (true/false),
but I'm receiving undefined, this is working in all other browsers (Chrome, Firefox,Edge)

![image](https://user-images.githubusercontent.com/87078689/139675180-a5ecf6b0-4a9a-459b-8751-1deba7e7c6e6.png)

Workaround for code:
```      verifyFullscreenIsOn() {
    if (checkBrowser.isSafari()) {
      const screenHeight = browser.execute(() => screen.availHeight)
      const currentHeight = browser.execute(() => screen.height)
      return expect(currentHeight).toBeGreaterThanOrEqual(screenHeight)
    }
  }
```

**Comment by queengooborg** [comment]
In Safari, [this feature is implemented with the `webkit` prefix](https://developer.mozilla.org/en-US/docs/Web/API/Document/fullscreenEnabled#browser_compatibility), so you'll need to check `document.fullscreenEnabled || document.webkitFullscreenEnabled`.
