### ISSUE TITLE
api.AmbientLightSensor - Incorrect support

### ISSUE THREAD

**Issue by GiovanniIncammicia** [mdn/browser-compat-data#13253]
#### What information was incorrect, unhelpful, or incomplete?
The documentation says that the AmbientLightSensor constructor is available in Chrome-based browsers, but it doesn't seem to be the case. I tried to create a codepen with the code in the documentation and it simply says "AmbientLightSensor is not a constructor". Also, AmbientLightSensor doesn't exist in the window object.
The website caniuse.com says it's not supported
https://caniuse.com/ambient-light

Is this an error or am I missing something?

<details>
<summary>MDN page report details</summary>

* Query: `api.AmbientLightSensor`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/AmbientLightSensor
* Report started: 2021-11-02T10:20:25.162Z

</details>

**Comment by queengooborg** [comment]
It looks like this feature is behind a flag and not exposed by default, but we're not propagating the flag data down.  Will get that fixed!

**Comment by queengooborg** [comment]
This has been fixed in #18300!
