### ISSUE TITLE
javascript.builtins.Date.getTime - getTime is not working in Safari or Firefox, but is working in Chrome

### ISSUE THREAD

**Issue by sofo1413** [mdn/browser-compat-data#13289]
#### What information was incorrect, unhelpful, or incomplete?
I was trying to use the getDate() to sort a set of dates, but in Safari and Firefox it was not working, but it was in chrome.

#### What did you expect to see?
Sorted dates

#### Did you test this? If so, how?
Set a breakpoint locally in firefox and getDate() was undefined

<details>
<summary>MDN page report details</summary>

* Query: `javascript.builtins.Date.getTime`
* MDN URL: https://developer.mozilla.org/en-US/docs/web/javascript/reference/global_objects/date/gettime
* Report started: 2021-11-04T23:21:41.291Z

</details>

**Comment by queengooborg** [comment]
Hmm, both `getDate` and `getTime` have been around for a really long time.  I have a feeling this may be programmer error, but just to confirm or deny that theory, can you share your code so we can take a closer look?

**Comment by sofo1413** [comment]
Hi there!
Happy to share the code, as I would love to correct my mistake.
The data being sorted is in this format with the date and frequency.  Then,
I have the following code to sort and then I plug that dates object into a
data visualization library. This is behaving as expected in chrome, but not
safari/firefox.

Any insight would be appreciated!

dateKeyValue.sort(function(a, b) {
  return new Date(a.x).getTime() - new Date(b.x).getTime();
});

const dates = [{ id: 'Incident Freq', data: dateKeyValue }];


   1. dateKeyValue: Array(19)
         1. 0: {x: "09/01", y: 1347}
         2. 1: {x: "08/25", y: 4871}
         3. 2: {x: "09/02", y: 805}
         4. 3: {x: "08/26", y: 75}
         5. 4: {x: "09/04", y: 148}
         6. 5: {x: "08/28", y: 20}
         7. 6: {x: "08/29", y: 162}
         8. 7: {x: "08/27", y: 93}
         9. 8: {x: "09/10", y: 538}
         10. 9: {x: "09/12", y: 207}
         11. 10: {x: "09/07", y: 12}
         12. 11: {x: "09/09", y: 1147}
         13. 12: {x: "09/08", y: 33}
         14. 13: {x: "09/11", y: 194}
         15. 14: {x: "09/03", y: 31}
         16. 15: {x: "09/05", y: 152}
         17. 16: {x: "09/06", y: 1}
         18. 17: {x: "09/15", y: 160}
         19. 18: {x: "09/14", y: 4}
         20.

**Comment by queengooborg** [comment]
Thanks for sharing the code!  This is outside of the scope of the repository and isn't actually an issue with `getTime`.  Normally I'd direct you to StackOverflow for this, but I can tell you real quick that you don't need `getTime` for your sorting algorithm.  You can just subtract the dates themselves, in other words `new Date(a.x) - new Date(b.x);`.
