### ISSUE TITLE
api.Performance - node.js functions are missing

### ISSUE THREAD

**Issue by KayLeung** [mdn/browser-compat-data#13288]
#### What information was incorrect, unhelpful, or incomplete?
node.js supported more functions than it showed

#### What did you expect to see?
these docs also missing in node.js docs: https://github.com/nodejs/node/issues/40723
need to dig and test to find out the API compatibility

#### Did you test this? If so, how?
yes

<details>
<summary>MDN page report details</summary>

* Query: `api.Performance`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Performance
* Report started: 2021-11-04T12:31:04.328Z

</details>

**Comment by queengooborg** [comment]
Can you clarify what functions you're expecting to see documented and added to the compatibility tables?

**Comment by queengooborg** [comment]
Hey there, are you still interested in this issue?  Let us know by replying with the requested information and we'll be happy to get right on it!
