### ISSUE TITLE
webextensions.api.i18n.detectLanguage - mixed text is not detectect language:

### ISSUE THREAD

**Issue by arcanisgk** [mdn/browser-compat-data#13290]
i am triying this:

```javascript
var post_content_exp ='La idea es tener un sandbox donde poder probar libremente el formato  resaltado y magic links en respuestas y comentarios  evitando contaminar el sitio principal  En este caso debe ser usado para cambiar parcialmente el contenido de este POST No se puede  Edite lo que necesite despu  233 s de esta linea  not formated code  function getSecondData moveId   if moveId    undefined  moveId   14  var secondSS   SpreadsheetApp openById ss2   var secondSh   secondSS getSheetByName  Moves    var Data   secondSh getDataRange   getValues    var actorName  secondSh getRange 1 5 1 secondSh getLastColumn    getValues    Data splice 0 1   var tmpData       for var x 0   x  60 Data length   x     if Data x  3     moveId   tmpData push Data x        var finalData       for var x 0   x  60 tmpData length   x     for var y 4   y  60 tmpData x  length   y     if tmpData x  y          finalData y 3    tmpData x  y      tmpData x  0         return   data  finalData  move  moveId  files  actorName';

chrome.i18n.detectLanguage(post_content_exp, (result) => {
                    var languages = "Languages: \n";
                    for (var i = 0; i < result.languages.length; i++) {
                        languages += result.languages[i].language + " ";
                        languages += result.languages[i].percentage + "\n";
                    }
                    var is_reliable = "\nReliable? \n" + result.isReliable + "\n";
                    alert(languages + is_reliable);
                });
```

i am getting:

![image](https://user-images.githubusercontent.com/1207306/140441932-c44a7012-cb93-4df6-bc68-e04148ef5af0.png)

this is not what I expected; the text has both Spanish and English words; even the section in English is not readable because it is part of a code from which the symbols were removed; but it does not detect it is mix.

**Comment by queengooborg** [comment]
If I had to guess, this is because there is some filtering applied to remove code before performing language detection to keep results from getting skewed.  I don't think this is something we'd document in BCD; there isn't really any specification for this that indicates how a browser must accomplish such a task, so it's up to the browser to decide how to implement language detection.

**Comment by arcanisgk** [comment]
@queengooborg Well, I think that if the library is to be used by programmers, they should be able to establish the behavior that it triggers ... and not argue or speculate or expect the navigator to have a behavior that may vary from one to another ... If there are filters that eliminate code, it would be enough to add some parameter that allows the programmer to deactivate the filters.

**Comment by queengooborg** [comment]
That's not a bad idea!  I would file bugs with the browser developers requesting this functionality, you might get a desirable outcome.  ;)
