### ISSUE TITLE
window.localStorage in IE 11, throw errors

### ISSUE THREAD

**Issue by huanghairong2312** [mdn/browser-compat-data#13292]
run demo code :

try {
	localStorage.setItem('ftwo_userId','**********************');
} catch(ex) {
	console.log(ex.message);
}

some times in IE brower ,it throw error; 

IE 11 : An internal error occurred in the Microsoft Internet extended version (Original content: "在 Microsoft Internet 扩展版本中发生内部错误")

IE 11: This operation cannot be completed due to error 800000b (Original content: "由于出现错误 8000000b 而导致此项操作无法完成")

IE 11: The operation attempted to access data outside the valid range (Original content: "该操作尝试访问的数据超出了有效范围")

**Comment by queengooborg** [comment]
Closing since we're no longer actively working on IE data.
