### ISSUE TITLE
accent-color - Now supported in Safari Technology Preview 134

### ISSUE THREAD

**Issue by hteumeuleu** [mdn/browser-compat-data#13301]
#### What information was incorrect, unhelpful, or incomplete?
The [`accent-color` property](https://developer.mozilla.org/en-US/docs/Web/CSS/accent-color) is supported behind a flag in the latest version of Safari Technology Preview. Here's the option visible in the Develop > Experimental Features list : https://i.imgur.com/GTyU23p.png

#### What did you expect to see?

The Safari support on desktop should show as supported "Behind a flag". 

#### Did you test this? If so, how?

1. Open Safari Technology Preview _Release 134 (Safari 15.4, WebKit 17613.1.6.1)_. 
2. Go to https://developer.mozilla.org/en-US/docs/Web/CSS/accent-color
3. The first example on the top of the page should show a red checkbox. 

Here’s a screenshot : https://i.imgur.com/QHkjE4T.png

#### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

* Here’s the macOS feature ticket marked as resolved/fixed: https://bugs.webkit.org/show_bug.cgi?id=231464
* Here's the iOS feature ticket marked as resolved/fixed: https://bugs.webkit.org/show_bug.cgi?id=231762

**Comment by lukewarlow** [comment]
Addressed as part of https://github.com/mdn/browser-compat-data/pull/12439
