### ISSUE TITLE
webextensions.api.runtime.sendMessage - Reported browser compatibility inaccurate

### ISSUE THREAD

**Issue by Psykoral** [mdn/browser-compat-data#13302]
- Chrome v95 + 64bit
- Firefox v94 + 64bit
- Edge v95 + 64bit
- Opera v80 + 64bit
- Safari v14.1

#### What information was incorrect, unhelpful, or incomplete?
Documentation reports that `browser.runtime.sendMessage` is available in browsers starting at certain versions for each, but testing results in the opposite.

#### What did you expect to see?
The `browser` namespace, and all subsequent object properties available beginning with the versions reported in [the documentation](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/sendMessage) . 

![Screenshot 2021-11-05 10 29 21](https://user-images.githubusercontent.com/1676422/140573184-96b30afa-e5a2-4643-be71-779241836a0b.png)

Actual result in all aforementioned browsers tested: 
```
> browser
Uncaught ReferenceError: browser is not defined
    at <anonymous>:1:1
```

#### Did you test this? If so, how?
Yes, ad-hoc testing by way of attempting to use the reported functions. 

<details>
<summary>MDN page report details</summary>

* Query: `webextensions.api.runtime.sendMessage`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/sendMessage
* Report started: 2021-11-04T23:27:02.974Z

</details>

**Comment by queengooborg** [comment]
It looks like you might be testing by just using the browser's console, rather than developing a browser extension.  This is a common confusion: the data you're looking at is for extensions only, rather than use in the browser, so you won't be able to call these in code served from your webpage!
