### ISSUE TITLE
css.properties.hyphens - Browser compatibility out of date

### ISSUE THREAD

**Issue by renekoch** [mdn/browser-compat-data#13359]
#### What information was incorrect, unhelpful, or incomplete?
Browser compatibility, out of date

#### What did you expect to see?
https://caniuse.com/?search=hyphens

#### Did you test this? If so, how?
no

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.hyphens`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/hyphens
* Report started: 2021-11-08T09:40:08.462Z

</details>

**Comment by queengooborg** [comment]
I'm not sure what data is out of date, as our data seems to match perfectly with CanIUse's.  Please feel free to reply to this thread if you feel the data still needs updating, and specify how.
