### ISSUE TITLE
Include URLs and status info of spec docs

### ISSUE THREAD

**Issue by mdittmer** [mdn/browser-compat-data#1336]
I noticed that some info about standards track is already in the schema. The table of spec docs (and their statuses) stands out to me as another staple on MDN articles that would be very useful in a machine readable format.

Would it make sense to include these data in `mdn/browser-compat-data`? This would obviate the need to scrape MDN articles to deduce linkages between APIs/features and spec docs.

**Comment by Elchi3** [comment]
We've updated the schema to include "spec_url" and have added spec links for ECMAScript for a start in https://github.com/mdn/browser-compat-data/pull/2983. Many thanks to 
Michael Smith aka sideshowbarker for this work.

A linkage between |MDN docs <-> compat data <-> specifications| is now possible. We will add spec_url to more features in this repo as time permits. PRs welcome.
