### ISSUE TITLE
display: grid value compat not updated to include Edge 16

### ISSUE THREAD

**Issue by brob** [mdn/browser-compat-data#1339]
On this view: https://developer.mozilla.org/en-US/docs/Web/CSS/display#Browser_compatibility

On the chart, the compatibility is showing "Requires the vendor prefix: -ms-"

Grid was released to Edge in version 16 and is supported in the original implementation behind the -ms prefix in version 15 and previous

**Comment by Elchi3** [comment]
This has been deployed :-) Thanks for your work!
