### ISSUE TITLE
api.KHR_parallel_shader_compile - Not supported on latest Firefox/Chrome macOS

### ISSUE THREAD

**Issue by xian** [mdn/browser-compat-data#13410]
#### What information was incorrect, unhelpful, or incomplete?
`KHR_parallel_shader_compile` isn't supported on Firefox 94 for Mac or Chrome 95 for Mac.

#### What did you expect to see?
That it was supported, as indicated in compatibility matrix.

#### Did you test this? If so, how?
`gl.getExtension("KHR_parallel_shader_compile")`

<details>
<summary>MDN page report details</summary>

* Query: `api.KHR_parallel_shader_compile`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/KHR_parallel_shader_compile
* Report started: 2021-11-09T22:32:46.792Z

</details>

**Comment by Elchi3** [comment]
Was fixed in https://github.com/mdn/browser-compat-data/pull/13291
