### ISSUE TITLE
api.ReadableStreamBYOBReader - Deno 1.16 Ships with Support

### ISSUE THREAD

**Issue by Dygear** [mdn/browser-compat-data#13420]
Deno 1.16.0

#### What information was incorrect, unhelpful, or incomplete?
Deno now supports [ReadableStreamBYOBReader](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStreamBYOBReader) and all of it's methods as of 1.16.0.

#### What did you expect to see?
Currently they are all red Xs for the feature set, where they should be 1.16 on green.

#### Did you test this? If so, how?
https://deno.com/blog/v1.16#improvements-to-web-streams-api

No need to test, this is actually in their official release notes.

<details>
<summary>MDN page report details</summary>

* Query: `api.ReadableStreamBYOBReader`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/ReadableStreamBYOBReader
* Report started: 2021-11-10T05:58:33.631Z

</details>

**Comment by lucacasonato** [comment]
Merged in https://github.com/mdn/browser-compat-data/pull/13273 already
