### ISSUE TITLE
api.Window.innerWidth - Calculates incorrectly on Safari

### ISSUE THREAD

**Issue by cpotey** [mdn/browser-compat-data#13449]
#### What information was incorrect, unhelpful, or incomplete?
In Safari (v14.1.2 on MacOS Big Sur), window.innerWidth does not return the scroll bar included like the summary suggests _"The read-only Window property innerWidth returns the interior width of the window in pixels. This includes the width of the vertical scroll bar, if one is present."_

#### What did you expect to see?
I would expect Safari to do the same as the other browsers, including the vertical scrollbar within this innerWidth... Something that could be done on the MDN side: note a comment down on the compatibility table to warn users.

#### Did you test this? If so, how?
Yes, I made the Safari browser width to 1400px, and window.innerWidth shows as 1415.

<details>
<summary>MDN page report details</summary>

* Query: `api.Window.innerWidth`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/window/innerWidth
* Report started: 2021-11-11T09:21:15.204Z

</details>

**Comment by queengooborg** [comment]
There's already a compatibility note in our data that states this is the case, which was added in #6795.
