### ISSUE TITLE
webextensions.api.cookies.CookieStore - Browser compatibility shows wrong info 

### ISSUE THREAD

**Issue by liesislukas** [mdn/browser-compat-data#13509]
#### What information was incorrect, unhelpful, or incomplete?

incorrect. safari has no such API

#### What did you expect to see?

defined API like on Chrome

#### Did you test this? If so, how?

Yes. Safari 15.1

![image](https://user-images.githubusercontent.com/2733862/141655668-24908f2b-bd58-43af-9979-d164f066cbb1.png)

this seems more accurate:

![image](https://user-images.githubusercontent.com/2733862/141655680-a9c5b7b4-4050-4d01-a8e1-0c13ca25d3af.png)

https://caniuse.com/?search=CookieStore

<details>
<summary>MDN page report details</summary>

* Query: `webextensions.api.cookies.CookieStore`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/cookies/CookieStore
* Report started: 2021-11-13T18:37:17.850Z

</details>

**Comment by queengooborg** [comment]
The documentation you're reading is for web extensions -- that is, browser extensions like AdBlock and Stylus/Cascadea.  This interface will not be available directly on webpages.

Also just a note, CanIUse's data comes from here for this feature, though it seems to be out of date.  😛
