### ISSUE TITLE
No browsers/chrome_android.json data

### ISSUE THREAD

**Issue by gsouquet** [mdn/browser-compat-data#1353]
Hi, 

I've just realised that there are no two different files the versions of Chrome and Chrome android. It looks like Firefox has two different files for the desktop and the android version.

I think it could be valuable to have two different files as it seems that the release dates for the desktop and android version are sometimes different.

For example:

Chrome 65 desktop: https://chromereleases.googleblog.com/2018/03/stable-channel-update-for-desktop.html
Release date 6th of March

Chrome 65 android: https://chromereleases.googleblog.com/2018/03/chrome-for-android-update_12.html
Release date 12th of March

Keen to hear your thoughts on this one

**Comment by Elchi3** [comment]
heh, coincidently, I just did that locally! 
Will open a PR to add browsers/chrome_android.json.

**Comment by Elchi3** [comment]
See https://github.com/mdn/browser-compat-data/pull/1356

**Comment by jpmedley** [comment]
We try to keep them the same, but it doesn't always work out that way because stuff happens.
