### ISSUE TITLE
WebTransport - Missing support data entry

### ISSUE THREAD

**Issue by lukewarlow** [mdn/browser-compat-data#13542]
#### What information was incorrect, unhelpful, or incomplete?

This repo has no entry for the WebTransport API

#### What did you expect to see?
It should be in stable chrome 97 (out in a months time), so would be good to get documented.

#### Did you test this? If so, how?
https://www.chromestatus.com/feature/4854144902889472

**Comment by queengooborg** [comment]
This was fixed in #17686!
