### ISSUE TITLE
api.HTMLMediaElement.volume - Not supported on iOS Safari

### ISSUE THREAD

**Issue by hvanness** [mdn/browser-compat-data#13554]
iOS Safari doesn't support setting the volume of an HTML5 audio element.
That should be mentioned in this article.

<details>
<summary>MDN page report details</summary>

* Query: `api.HTMLMediaElement.volume`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/volume
* Report started: 2021-11-17T01:01:08.203Z

</details>

**Comment by queengooborg** [comment]
Duplicate of #12001.
