### ISSUE TITLE
api.HTMLElement.focus - preventScroll supported in Safari

### ISSUE THREAD

**Issue by fiji-flo** [mdn/browser-compat-data#13562]
#### What information was incorrect, unhelpful, or incomplete?

`preventScroll` works in Safari

https://github.com/mdn/browser-compat-data/blob/main/api/HTMLElement.json#L1202

#### What did you expect to see?

For it to show the version since it's supported.

#### Did you test this? If so, how?

Tested in Safari 15.1 `preventScroll` option works like intended.

<details>
<summary>MDN page report details</summary>

* Query: `api.HTMLElement.focus`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus
* Report started: 2021-11-17T10:12:07.728Z

</details>

**Comment by queengooborg** [comment]
Duplicate of #12925.
