### ISSUE TITLE
CSS inset property not working in chrome version <= 76 in mac Catalina os 

### ISSUE THREAD

**Issue by Shathath** [mdn/browser-compat-data#13563]
#### Did you test this? If so, how?

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.inset`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/inset
* Report started: 2021-11-17T10:30:42.776Z

</details>

**Comment by queengooborg** [comment]
I'm closing this because our data already indicates this property is not supported before Chrome 87 without enabling a flag.
