### ISSUE TITLE
api.OTPCredential - missing browser support

### ISSUE THREAD

**Issue by philnash** [mdn/browser-compat-data#13630]
#### What information was incorrect, unhelpful, or incomplete?

`OTPCredential` is supported in Chrome desktop [since version 93](https://blog.chromium.org/2021/07/chrome-93-multi-screen-window-placement.html).

#### What did you expect to see?

I expected the browser support matrix to show that Chrome desktop supported `OTPCredential`

#### Did you test this? If so, how?

I opened the Chrome browser tools and ran `"OTPCredential" in window` and it returned `true`. That was for my current version of Chrome (Version 96.0.4664.55 (Official Build) (x86_64) on macOS 12.0.1). To find historical data I found [this announcement in the Chromium blog for support in Chrome 93](https://blog.chromium.org/2021/07/chrome-93-multi-screen-window-placement.html).

<details>
<summary>MDN page report details</summary>

* Query: `api.OTPCredential`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/OTPCredential
* Report started: 2021-11-19T03:08:32.029Z

</details>

**Comment by queengooborg** [comment]
This has been fixed in #14290!

**Comment by philnash** [comment]
Thanks @queengooborg!
