### ISSUE TITLE
javascript.operators.optional_chaining - <How to use optional chaining in Node.js 16>

### ISSUE THREAD

**Issue by egemenozyurek** [mdn/browser-compat-data#13691]
Optional chaining seems to be a great feature and I really wanted to see it implemented and finally get rid of nested ifs, arbitrary functions and what not for such a simple operation.

But there's a problem, it doesn't work. I updated to Node 16 and I still get an error:
`className="banner"
      style={{
        backgroundSize: "cover",
        backgroundImage: `url(
                "https://image.tmdb.org/t/p/original/${movie?.backdrop_path}"
            )`,
        backgroundPosition: "center center",
      }}
    >`

And it gave me this error: `Syntax error {movie?.backdrop_path}` ==> '.'

What is the problem?

Do I need to change some language config or download a library to enable this feature? Or is it simply not out yet?

**Comment by queengooborg** [comment]
This repository isn't a help forum, so we cannot give feedback on how to solve your problem.  I can say with confidence that this is a coding issue rather than a feature support issue.  I'd recommend asking your question on a site like StackOverflow, and you should be able to get an answer rapidly!
