### ISSUE TITLE
BarcodeDetector will be supported on all platforms in Chromium

### ISSUE THREAD

**Issue by foolip** [mdn/browser-compat-data#13752]
This is happening in https://chromium-review.googlesource.com/c/chromium/src/+/3290206, and I'm filing this issue as a reminder since it's not very likely to be fixed otherwise. Here's an example statement that needs to be updated:

https://github.com/mdn/browser-compat-data/blob/6248a009a5a78ed3b7d370c35fe8553a4238bf87/api/BarcodeDetector.json#L8-L12

**Comment by reillyeon** [comment]
This is unfortunately not happening, but I should still update the data to show that this API has been supported on Chrome OS since Chrome 88.
