### ISSUE TITLE
api.ResizeObserverEntry.contentRect - supported by latest MacOS Safari

### ISSUE THREAD

**Issue by marcelltoth** [mdn/browser-compat-data#13822]
#### What information was incorrect, unhelpful, or incomplete?

Current MDN docs say neither property is supported by Safari on `ResizeObserverEntry` which doesn't make sense as `ResizeObserver` itself is.

#### Did you test this? If so, how?

I don't own a mac myself but I asked my teammate @rhyswfbowles to run this test code on a page using Safari:
```js
new ResizeObserver((entries) => {
	console.log(entries[0])
}).observe(document.body, {
	box: 'border-box'
});
```

and he got back to me with this screenshot:
![image](https://user-images.githubusercontent.com/543372/144221044-3f5c8917-3294-4b4f-a827-00455d21cb75.png)

This seems to indicate `contentRect` is indeed supported, while the rest are correctly indicated as unsupported.

<details>
<summary>MDN page report details</summary>

* Query: `api.ResizeObserverEntry.contentRect`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserverEntry/contentRect
* Report started: 2021-12-01T10:42:16.543Z

</details>

**Comment by queengooborg** [comment]
A version number has been added in #13836 for `contentRect`!
