### ISSUE TITLE
api.Request - ReadableStream in body

### ISSUE THREAD

**Issue by tex0l** [mdn/browser-compat-data#13854]
#### What information was incorrect, unhelpful, or incomplete?

Since Chrome 95, it seems it is possible to use a `ReadableStream` as the `body` of a `Request` : https://web.dev/fetch-upload-streaming/ and https://developer.chrome.com/origintrials/#/view_trial/3524066708417413121

#### What did you expect to see?
Which means the `Send ReadableStream in request body` and `body` lines in the table should show 95 as the version of Chrome where it is compatible.

#### Did you test this? If so, how?

<details>
<summary>MDN page report details</summary>

* Query: `api.Request`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Request
* Report started: 2021-12-03T17:36:13.721Z

</details>

**Comment by queengooborg** [comment]
This has been resolved by #18155!
