### ISSUE TITLE
css.selectors.after - Which alternative I can use to show ::after pseudo element in Safari?

### ISSUE THREAD

**Issue by Isaackomeza** [mdn/browser-compat-data#13880]
#### Which alternative I can use to show ::after pseudo-element in Safari?

<details>
<summary>MDN page report details</summary>

* Query: `css.selectors.after`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/::after
* Report started: 2021-12-06T09:32:12.046Z

</details>

**Comment by queengooborg** [comment]
The `::after` selector is definitely supported in Safari, so I believe this is a developer error.  I'd advise asking StackOverflow if you're having troubles.
