### ISSUE TITLE
api.Clipboard - Safari limitation

### ISSUE THREAD

**Issue by levenleven** [mdn/browser-compat-data#13889]
#### What information was incorrect, unhelpful, or incomplete?

In Safari writing to the clipboard is available without permission, but only from user-initiated event callbacks (same as in firefox)

#### What did you expect to see?

I'd expect to see the same remark as one for Firefox

#### Did you test this? If so, how?

Tested on Safari 15.1

<details>
<summary>MDN page report details</summary>

* Query: `api.Clipboard`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Clipboard
* Report started: 2021-12-06T14:03:46.957Z

</details>

**Comment by queengooborg** [comment]
This has been fixed by #15254!
