### ISSUE TITLE
css.properties.justify-content - 'right' property is not supported as of Safari 15.1

### ISSUE THREAD

**Issue by lohchianli** [mdn/browser-compat-data#13901]
#### What information was incorrect, unhelpful, or incomplete?
justify-content:right/left is not supported as of Safari 15.1

#### What did you expect to see?
Compatibility should be changed to 'No'

#### Did you test this? If so, how?
Test on Safari 15.1.

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.justify-content`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/justify-content
* Report started: 2021-12-07T02:43:57.895Z

</details>

**Comment by YZ1187946903** [comment]
you  yes

**Comment by queengooborg** [comment]
These values are actually supported in Safari as I have just tested.
