### ISSUE TITLE
css.properties.contain - Safari Supports Css Containments Under Experimental Features

### ISSUE THREAD

**Issue by mahdi-farnia** [mdn/browser-compat-data#13910]
#### What information was incorrect, unhelpful, or incomplete?
Safari Support Info

#### What did you expect to see?
Supports Under Flag Css Containments

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.contain`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Containment
* Report started: 2021-12-08T05:13:31.775Z

</details>

**Comment by queengooborg** [comment]
Thanks for reporting this!  We're actually not adding new flag data into BCD as it has become increasingly harder to maintain, plus many browser vendors wish for us not to include it.
