### ISSUE TITLE
css.properties.-webkit-text-stroke-color - Display issue on Android 12 Chrome browser

### ISSUE THREAD

**Issue by sboulden** [mdn/browser-compat-data#13920]
Hello, we are having some display issues with the CSS property -webkit-text-stroke-color when displayed on Chrome browser on Android devices.

I have attached a screenshot.  There are some visible "blocks" or strokes around the lettering when displayed on the mobile browser.  Notice the peculiar lines around _"We Are Your Last Stop Shop."_

![IMG_7035](https://user-images.githubusercontent.com/29697159/145283571-f2b24963-cbb9-485a-922b-45d53b6e0c4d.jpg)

The issue was present on the two Android devices we have available:
- Google Pixel 6 - Android 12 - Chrome 96.0.4664.45
- Google Pixel 3 - Android 12 - Chrome 96.0.4664.45

The issue was NOT present on these desktop browsers that were tested - Chrome, Firefox, Edge - and does not appear on Safari for iOS, nor Firefox for iOS.

The exact HTML / CSS of the text block that we are trying to display is:

`<h2 style="margin:0px auto; text-align:center;padding-bottom:10px;font-variant:small-caps;font-family:'Arial Black','Arial',sans-serif;-webkit-text-stroke-width: 1px;font-weight:bold;"><span style="color:#fff;  -webkit-text-stroke-color: black;">We Are Your</span><span style="color:#e70e2b;font-style:italic;  -webkit-text-stroke-color: white;font-weight:bold;"> Last Stop Shop.</span></h2>`

Thank you for any help or suggestions you may have.

This text currently displays on the footer of a wordpress v5.7.4 website on a Ubuntu LAMP server at https://bisonfleet.net/ , if relevant.

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.-webkit-text-stroke-color`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-text-stroke-color
* Report started: 2021-12-08T20:11:53.002Z

</details>

**Comment by lukewarlow** [comment]
Firstly, I suggest raising this as a bug in the Chromium bug tracker. I'm able to reproduce on my Android 12 device on Chrome Stable, the issue appears to be (mostly) fixed in canary however.

I am also able to get a similar odd rendering in Firefox for Android.

I don't personally think this constitutes a big enough issue to add as a note in the support data (especially if it is fixed in Canary).

**Comment by queengooborg** [comment]
This is certainly an odd issue, but honestly, it's one that I feel is small enough for us not to include here in BCD, especially if it's already fixed in Canary.
