### ISSUE TITLE
"Code review limits" configured incorrectly; contributors cannot review pull requests any more

### ISSUE THREAD

**Issue by Rob--W** [mdn/browser-compat-data#13953]
I tried to approve a PR after completing the review, but noticed that I am not able to do that any more.

According to https://github.com/mdn/browser-compat-data/blob/main/GOVERNANCE.md#privileges-and-responsibilities-matrix, contributors should be able to review pull requests. I have been a contributor here for a while, as a reviewer and as a [code contributor](https://github.com/mdn/browser-compat-data/commits?author=Rob--W). So it looks like there may be a misconfiguration on the repository that prevents me from posting reviews.

It looks like the repository's settings has been updated, with the "Code review limits" setting set to "Limit to users explicitly granted read or higher access box."
This relatively new feature was announced at https://github.blog/2021-11-01-github-keeps-getting-better-for-open-source-maintainers/#preventing-drive-by-pull-request-approvals-and-requested-changes

**Comment by Rob--W** [comment]
I just managed to post my review approval in #13940, so I guess that this issue has been fixed.

**Comment by ddbeck** [comment]
Thanks for bringing this to my attention, @Rob--W. I've removed the code review limits on the repo. I think this is now fixed, so I'm going to close the issue.

Also, since you've been in the habit of reviewing webextensions data, would you be interested in joining the project as a peer?

**Comment by Rob--W** [comment]
> Also, since you've been in the habit of reviewing webextensions data, would you be interested in joining the project as a peer?

Sure.
