### ISSUE TITLE
css.selectors.focus-visible - Webkit default support 🥳

### ISSUE THREAD

**Issue by bashunaimiroy** [mdn/browser-compat-data#13986]
#### What information was incorrect, unhelpful, or incomplete?

Safari is reported as not supporting it- the notes link to this [Webkit bug](https://bugs.webkit.org/show_bug.cgi?id=234019).

#### What did you expect to see?

Webkit now supports this as by default of December 9th, as noted in this [changeset and related patch.](https://trac.webkit.org/changeset/286783/webkit)

#### Did you test this? If so, how?

No, and to be honest I'm not 100% certain when it will be testable- can't interpret what version of Safari this will be in, which would be the most useful for the MDN support section purposes. However, I thought this would still be a useful issue for tracking

<details>
<summary>MDN page report details</summary>

* Query: `css.selectors.focus-visible`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible
* Report started: 2021-12-13T22:29:05.174Z

</details>

**Comment by lukewarlow** [comment]
It'll likely make it into Safari TP 137 or 138 and when it does we can add/update the support statement in MDN. 

In terms of release Safari versions it's anyones guess which one it'll make it into. Historically there's a .1 update in Spring but they've already had a .1 and .2 update so their release schedule seems to have changed.

**Comment by ModulesUnraveled** [comment]
According to https://caniuse.com/?search=focus-visible Safari has support since 15.4
