### ISSUE TITLE
css.types.color.hwb - supported by Firefox 96

### ISSUE THREAD

**Issue by nt1m** [mdn/browser-compat-data#14076]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1352755

<details>
<summary>MDN page report details</summary>

* Query: `css.types.color.hwb`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/hwb()
* Report started: 2021-12-19T13:37:22.954Z

</details>

**Comment by lucalves** [comment]
Hello @nt1m! I opened #14153 to solve this. Let's wait for review :)

**Comment by ddbeck** [comment]
Resolved by https://github.com/mdn/browser-compat-data/pull/14125. Thank you!
