### ISSUE TITLE
css.types.length - Safari support for Q

### ISSUE THREAD

**Issue by estelle** [mdn/browser-compat-data#14080]
https://developer.apple.com/safari/technology-preview/release-notes/
Q unit supported since 97 release.

<details>
<summary>MDN page report details</summary>

* Query: `css.types.length`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/length
* Report started: 2021-12-20T01:37:00.543Z

</details>

**Comment by queengooborg** [comment]
Fixed in #20264!
