### ISSUE TITLE
api.AudioWorkletGlobalScope - Safari data incorrect

### ISSUE THREAD

**Issue by delucis** [mdn/browser-compat-data#14169]
#### What information was incorrect, unhelpful, or incomplete?

Safari is listed as not supporting `currentFrame`, `currentTime`, `registerProcessor` and `sampleRate` in `AudioWorkletGlobalScope`. This is inaccurate as of 15.1 (if not earlier?)

#### What did you expect to see?

That Safari supports these parts of the API in `AudioWorkletGlobalScope`.

#### Did you test this? If so, how?

A little tricky to test as audio worklets can’t currently `console.log` in Safari ([WebKit Bug 220039](https://bugs.webkit.org/show_bug.cgi?id=220039)), but you can `postMessage` from a worklet and this provides the expected values. Haven’t tested on iOS, but the same may be true there.

<details>
<summary>MDN page report details</summary>

* Query: `api.AudioWorkletGlobalScope`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/AudioWorkletGlobalScope
* Report started: 2021-12-26T20:53:37.582Z

</details>

**Comment by queengooborg** [comment]
Looks like this was resolved in #14457!
