### ISSUE TITLE
Remove needs-release-note label?

### ISSUE THREAD

**Issue by queengooborg** [mdn/browser-compat-data#14228]
With our new release note system, I believe that we can simply remove this label.  What do you think @ddbeck?

**Comment by ddbeck** [comment]
No, we should continue to set the label for PRs with noteworthy changes that won't be generated automatically. For example, in [v4.1.2](https://github.com/mdn/browser-compat-data/releases/tag/v4.1.2) the note for https://github.com/mdn/browser-compat-data/pull/14003 would never have been generated automatically.

There are now fewer circumstances where the label is required, however. I've opened https://github.com/mdn/browser-compat-data/pull/14285 to revise the docs.
