### ISSUE TITLE
"IE Phone" browser type is not defined

### ISSUE THREAD

**Issue by kaycebasques** [mdn/browser-compat-data#1426]
The mobile browsers compat table for PerformanceTiming defines `IE Phone`, but this browser type doesn't seem to exist in this repo.

![image](https://user-images.githubusercontent.com/4713486/37526297-4099fd0e-292f-11e8-8e63-22385b35a899.png)

https://developer.mozilla.org/en-US/docs/Web/API/PerformanceTiming

**Comment by Elchi3** [comment]
We've decided in https://github.com/mdn/browser-compat-data/issues/659 that "IE Phone" or "IE Mobile" isn't relevant anymore and we're going to ignore this artifact of the past. :-)

**Comment by kaycebasques** [comment]
Does this go for "Firefox OS" as well?

**Comment by kaycebasques** [comment]
More generally, do you have a list of browsers that I should ignore?

**Comment by Elchi3** [comment]
Yeah, please ignore Firefox OS as well. I don't have a general ignore list unfortunately. Feel free to continue to ping me about that here, though.

**Comment by kaycebasques** [comment]
"Mozilla Servo"?

**Comment by Elchi3** [comment]
Ignore :)
