### ISSUE TITLE
window.getSelection() doesn't work in iOS 15

### ISSUE THREAD

**Issue by sholem** [mdn/browser-compat-data#14270]
window.getSelection() doesn't work in iOS 15 
 my example https://moshiach.ru/mistakes/test.php

**Comment by hamishwillee** [comment]
Thanks very much. This is now in the browser compat repo. At some point someone will chase through the data.

**Comment by higherstates** [comment]
@sholem  @hamishwillee 

I'm using Safari 14 and iOS 13.
I can confirm that `window.getSelection()` and `document.getSelection()` don't work on those.

```
const getCaretPosition = () => {
  if (window.getSelection) {
    const sel = window.getSelection()
    if (sel.getRangeAt && sel.rangeCount) {
      return sel.getRangeAt(0)
    }
  }
  return null
}
```
This block will return `null` on Safari but it works normally on Chrome.

I've been searching everywhere for a workaround for Safari but no luck yet. Can you have a look at this again?

Thank you!

**Comment by aancw** [comment]
> @sholem @hamishwillee @AnilSeervi
> 
> I'm using Safari 14 and iOS 13. I can confirm that `window.getSelection()` and `document.getSelection()` don't work on those.
> 
> ```
> const getCaretPosition = () => {
>   if (window.getSelection) {
>     const sel = window.getSelection()
>     if (sel.getRangeAt && sel.rangeCount) {
>       return sel.getRangeAt(0)
>     }
>   }
>   return null
> }
> ```
> 
> This block will return `null` on Safari but it works normally on Chrome.
> 
> I've been searching everywhere for a workaround for Safari but no luck yet. Can you have a look at this again?
> 
> Thank you!

I'm experience this issue too on MacOS Safari.

**Comment by queengooborg** [comment]
The test code above is working as expected in as early as Safari 12.1 on macOS.  It is also working in iOS 13 on an iPhone 11 with no issues.  Here is a test page demonstrating that the Selection API functions as expected:

```html
<!DOCTYPE html>
<html>
	<head>
		<style>
			.no-select {
				font-style: italic;
				pointer-events: none;
			}
		</style>
	</head>
	<body>
		<p class="no-select">Select some text. The selected text should appear below the paragraph.</p>

		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Viverra mauris in aliquam sem fringilla ut morbi. Faucibus purus in massa tempor nec. Et sollicitudin ac orci phasellus egestas tellus. Arcu dui vivamus arcu felis bibendum ut. Sed viverra ipsum nunc aliquet bibendum. Vel eros donec ac odio tempor orci dapibus. Posuere lorem ipsum dolor sit. Eu lobortis elementum nibh tellus molestie nunc non. Molestie a iaculis at erat. Risus nullam eget felis eget nunc lobortis mattis. Amet risus nullam eget felis eget nunc lobortis mattis aliquam. Nullam eget felis eget nunc lobortis mattis aliquam faucibus. In egestas erat imperdiet sed euismod. Pellentesque habitant morbi tristique senectus et netus et malesuada. Porta nibh venenatis cras sed felis. Vestibulum mattis ullamcorper velit sed. Et ultrices neque ornare aenean euismod.</p>

		<p class="no-select" id="results"></p>

		<script>
			const getCaretPosition = () => {
				if (window.getSelection) {
					const sel = window.getSelection();
					if (sel.getRangeAt && sel.rangeCount) {
						return sel.getRangeAt(0);
					}
				}
				return null;
			}

			document.onselectionchange = (e) => {
				document.getElementById('results').innerText = "Selected Text: " + getCaretPosition();
			}
		</script>
	</body>
</html>
```
