### ISSUE TITLE
javascript.builtins.WebAssembly - Vector Instructions (SIMD)

### ISSUE THREAD

**Issue by styfle** [mdn/browser-compat-data#14280]
#### What information was incorrect, unhelpful, or incomplete?

Missing Vector Instructions (often called SIMD) from the WebAssembly compat table.

#### What did you expect to see?

Another row for "Vector Instructions" or "SIMD" in the Browser Compatibility section.

#### Did you test this? If so, how?

https://wasm-feature-detect.surma.technology/

#### Specification

https://webassembly.github.io/spec/core/syntax/instructions.html#vector-instructions

<details>
<summary>MDN page report details</summary>

* Query: `javascript.builtins.WebAssembly`
* MDN URL: https://developer.mozilla.org/en-US/docs/WebAssembly
* Report started: 2021-12-29T00:07:56.251Z

</details>

**Comment by styfle** [comment]
Here's a list of implementations: https://github.com/WebAssembly/simd/issues/480

**Comment by MendyBerger** [comment]
https://webassembly.org/roadmap/

I think that adding all the parts mentioned here would make a lot of sense, especially SIMD, reference types, and exception handling, since those are areas with high interest.

Feel free to assign me if you need help with this.

**Comment by queengooborg** [comment]
Web Assembly features are now tracked in BCD since #20136!
