### ISSUE TITLE
geolocation service not working on safari 14.0 on mac

### ISSUE THREAD

**Issue by halhwadi** [mdn/browser-compat-data#14334]
Hi

geolocation service working fine on chrome and edge but not on ''safari (tested on v14.0 on mac and ios), no error is shown on developer console at all and nothing been showing on screen as well, location service and pop-windows is enabled at safari browser and OS level...

I have tested its by using this [link](https://www.w3schools.com/html/tryit.asp?filename=tryhtml5_geolocation_error) and it gives error says "**Location information is unavailable**" even though its working at chrome!, Not sure if Safari stop supporting Geolocation service...

please find the code(the same code is working properly on other browsers!):
```
`$(function getLocation() {
  let lat;
  let lon;
  if (navigator.geolocation) {
    navigator.geolocation.getCurrentPosition(showPosition,errorCallback);
  } 
  else {
    console.log("location service is blocked on this device");
  }

  function errorCallback(error) {
    if (error.code == error.PERMISSION_DENIED) {
      window.alert("Location service is disabled on this device,Please make sure its enabled to use map view properly");
    }
  }
 
 function showPosition(position) {
  lat = position.coords.latitude.toString();
  lon = position.coords.longitude.toString();
  console.log("lat1",lat,"lon1",lon);`
```

**Comment by Jayapaul12496** [comment]
Did you Find any solution for it ?

**Comment by halhwadi** [comment]
Do you use virtual mac? In my case I was testing the goelocation service by using virtual mac installed on Windows machine and thats why it didn't work, I suggest you to test it on iPhone device

**Comment by Jayapaul12496** [comment]
No ,I have using Mac Desktop. but it always return POSITION_UNAVAILABLE error.

**Comment by halhwadi** [comment]
Do you test it over https? Geolocation on apple not working over http..

**Comment by Jayapaul12496** [comment]
Yes. I have test it over https, but I have using local area network. So that it's not working. Now it's working fine in WIFI.
Thanks for your valuable time.
