### ISSUE TITLE
api.Window.scrollTo - "smooth" behavior not working

### ISSUE THREAD

**Issue by theDarkDuke** [mdn/browser-compat-data#14389]
#### What information was incorrect, unhelpful, or incomplete?
scollTo.behavior shows to be compatible on Safari mobile

#### What did you expect to see?
A smooth scroll to the desired area, however it simply snaps to the position instead.

#### Did you test this? If so, how?
tested on iPhone 13 w/ Safari browser

<details>
<summary>MDN page report details</summary>

* Query: `api.Window.scrollTo`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollTo
* Report started: 2022-01-01T16:46:37.706Z

</details>

**Comment by queengooborg** [comment]
iOS 13 doesn't support the `behavior` parameter; the table indicates that support was added in iOS 14.
