### ISSUE TITLE
No overall spec_url for javascript.operators.spread (result is broken Specifications section in MDN)

### ISSUE THREAD

**Issue by seanwbarry** [mdn/browser-compat-data#14392]
## What page(s) did you find the problem on?

[](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#on-github)

## Specific page section or heading?

spec_url - https://tc39.es/ecma262/multipage/ecmascript-language-expressions.html#prod-SpreadElement

## What is the problem?

I have provided a more specific spec_url above than is defined in the browser-compat-data repo, but, regardless, that repo has a [spec_url defined for this piece of information](https://github.com/mdn/browser-compat-data/blob/main/javascript/operators/spread.json). Yet, it isn't rendering on the url detailed above.

Problem: in the section titled "Specification" it says "No specification found"

## What did you expect to see?

A link to the relevant part of the specification: https://github.com/mdn/browser-compat-data/blob/main/javascript/operators/spread.json

## Did you test this? If so, how?

To the extent that I found the relevant part of the specification?

![issue](https://user-images.githubusercontent.com/12903479/147846548-a74f1920-d1dc-4c18-ae13-a737006be00c.PNG)

**Comment by Elchi3** [comment]
This should be looked at with https://github.com/mdn/browser-compat-data/issues/13804 in mind (the namespace for spread isn't ideal leading to problems like this)
