### ISSUE TITLE
api.Window.scroll - `behavior: smooth` does not work on Safari on macOS or iOS

### ISSUE THREAD

**Issue by nkalupahana** [mdn/browser-compat-data#14419]
#### What information was incorrect, unhelpful, or incomplete?

On the compatibility chart for window.scroll (also applies to window.scrollTo / element.scroll / element.scrollTo / etc.), it shows that the `options.behavior` parameter works on Safari for macOS and iOS. However, when you actually test it, this is not the case. See the test CodePen -- on Chrome, it scrolls smoothly. However, on iOS or macOS, it scrolls without an animation.

#### What did you expect to see?

This discrepancy should be clearly indicated. It's probably also good to recommend [a polyfill](http://iamdustan.com/smoothscroll/).

#### Did you test this? If so, how?

Testable with [this CodePen](https://codepen.io/nkalupahana/pen/eYGryXy) on *latest* Safari for iOS and macOS.

<details>
<summary>MDN page report details</summary>

* Query: `api.Window.scroll`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/scroll
* Report started: 2022-01-04T06:19:13.449Z

</details>

**Comment by queengooborg** [comment]
A note was added in #14005 for this!
