### ISSUE TITLE
api.Window.moveTo - Windows can't be moved on Wayland

### ISSUE THREAD

**Issue by lunaneff** [mdn/browser-compat-data#14422]
This issue applies to all browsers that natively support Wayland on Linux. It does **not** apply to browsers that use XWayland.  
It also applies to all other APIs that have to do with window positioning. 

#### What information was incorrect, unhelpful, or incomplete?
Wayland doesn't allow apps to move their windows

#### What did you expect to see?
The docs should mention that these APIs won't work on Wayland

#### Did you test this? If so, how?
JS console in the main window:
```js
window.open('', '', 'popup');
```

In the popup:
```js
window.moveTo(500, 500);
```

If the browser is using Wayland, the window won't move

On Firefox, set the `MOZ_ENABLE_WAYLAND` env var to 1/0 to enable/disable Wayland  
On Chromium, add `--enable-features=UseOzonePlatform --ozone-platform=wayland` to the arguments to enable Wayland

<details>
<summary>MDN page report details</summary>

* Query: `api.Window.moveTo`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/moveTo
* Report started: 2022-01-04T09:28:52.370Z

</details>

**Comment by queengooborg** [comment]
This doesn't really sound like something that should be documented in BCD, since it's an issue with Wayland rather than a browser issue.
