### ISSUE TITLE
css.selectors.has - Supported in STP 137

### ISSUE THREAD

**Issue by nt1m** [mdn/browser-compat-data#14424]
Safari technology preview 137 supports the :has() pseudo class:

https://webkit.org/blog/12156/release-notes-for-safari-technology-preview-137/

<details>
<summary>MDN page report details</summary>

* Query: `css.selectors.has`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/:has
* Report started: 2022-01-04T13:21:05.818Z

</details>

**Comment by queengooborg** [comment]
This has been resolved in #14096, then #14750!
