### ISSUE TITLE
api.Notification.requestPermission - Unsupported on Fxa and Opera Mini

### ISSUE THREAD

**Issue by NexusVanGezi** [mdn/browser-compat-data#14474]
#### What information was incorrect, unhelpful, or incomplete?
API does not work on both Firefox for android and Opera Mini for Android. 
#### Did you test this? If so, how?

<details>
<summary>MDN page report details</summary>

* Query: `api.Notification.requestPermission`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Notification/requestPermission
* Report started: 2022-01-07T20:06:42.283Z

</details>

**Comment by queengooborg** [comment]
We don't track Opera Mini in BCD, but we have added a note about Firefox's new security requirement for `Notification.requestPermission()` in #15929!
