### ISSUE TITLE
css.selectors.-webkit-scrollbar-thumb - scroll color issue ios

### ISSUE THREAD

**Issue by markrutten** [mdn/browser-compat-data#14491]
Safari iOS - iPhone XS - iOS 15.2

#### What information was incorrect, unhelpful, or incomplete?
The color of the scroller is always white

#### What did you expect to see?
the "background" color that is used in ::-webkit-scrollbar-thumb 

#### Did you test this? If so, how?
yes, the color is no longer working, also not with the example used in https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar 

<details>
<summary>MDN page report details</summary>

* Query: `css.selectors.-webkit-scrollbar-thumb`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar
* Report started: 2022-01-10T13:17:42.896Z

</details>

**Comment by queengooborg** [comment]
This pseudo-class was removed in Safari iOS 13 as is represented by #13443, so this checks out.
