### ISSUE TITLE
css.properties.align-items - No support for first/last baseline on chrome

### ISSUE THREAD

**Issue by CherniyFY** [mdn/browser-compat-data#14507]
There is no support for first/last baseline on chrome (97, android and linux)

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.align-items`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/align-items
* Report started: 2022-01-11T08:56:58.535Z

</details>

**Comment by Rolf-B** [comment]
Support in Chromia seems to be improved, Bug <https://crbug.com/885175> claims to be solved since October '22, so Chromia starting with #107 should work.

**Comment by queengooborg** [comment]
The data f
