### ISSUE TITLE
css.types.color.hwb - Firefox now has support

### ISSUE THREAD

**Issue by feikname** [mdn/browser-compat-data#14509]
#### What information was incorrect, unhelpful, or incomplete?
[MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/hwb()) lists Firefox as having no support for `hwb()`, but [since Firefox 96](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/96) it has been added.

#### What did you expect to see?
`hwb()`  marked as supported since Firefox 96

#### Did you test this? If so, how?
Yes, I quickly used Inspect Element on one of MDN's `<h1>` elements and added `style="color: hwb(194 0% 0%)"` to the tag to test. It sucessfully turned cyan.

<details>
<summary>MDN page report details</summary>

* Query: `css.types.color.hwb`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/hwb()
* Report started: 2022-01-11T14:32:18.362Z

</details>

**Comment by lucalves** [comment]
Duplicate of #14076.

**Comment by feikname** [comment]
Closing then.
