### ISSUE TITLE
api.RadioNodeList - RadioNodeList not available in Internet Explorer

### ISSUE THREAD

**Issue by julfersnlt** [mdn/browser-compat-data#14515]
Internet Explorer, all versions

#### What information was incorrect, unhelpful, or incomplete?

Compatibility table says IE 9+ fully supports `RadioNodeList`, but if RadioNodeList exists in IE, it's unclear how to get one. Internet Explorer returns `HTMLCollection`, rather than RadioNodeList when accessing the properties of a form. See https://stackoverflow.com/a/37864049 and https://stackoverflow.com/a/31063141. 

Perhaps related is that compatibility tables already show [HTMLFormControlsCollection.namedItem()](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormControlsCollection/namedItem) as unsupported in Internet Explorer, but since Internet Explorer's implementation of `form[property]` can return an html collection, it's not equivalent to [HTMLCollection.namedItem()](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCollection/namedItem) either.

#### What did you expect to see?

Accessing named radio group in a form returns a RadioNodeList with a `value` property.

#### Did you test this? If so, how?

Yes. The MDN docs example of [RadioNodeList.value](https://developer.mozilla.org/en-US/docs/Web/API/RadioNodeList/value) does not programmatically select the "red" radio button in Internet Explorer 11. Nor does the following modified example select a value programmatically or display the selected value:

```
<form>
  <label><input type="radio" name="color" value="blue">Blue</label>
  <label><input type="radio" name="color" value="red">Red</label>
</form>

<script>
var form = document.forms[0];
var radios = form.elements['color'];
console.log(radios.value)
radios.value = 'red';  // neither is selected

form.onchange = function () {
  // see what happens when clicking a radio button
  console.log('----------------')
  console.log(form.color.value)  // always "red"
  console.log(form.elements.namedItem('color').value)  // always "blue"
}
</script>
```

Also tested in IE 9 emulated by IE 11 dev tools with same results.

<details>
<summary>MDN page report details</summary>

* Query: `api.RadioNodeList.value`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/RadioNodeList
* Report started: 2022-01-11T20:40:31.826Z

</details>

**Comment by queengooborg** [comment]
I'm closing this issue as we are no longer maintaining the Internet Explorer; see the [applicable discussion](https://github.com/orgs/mdn/discussions/202) for more details.
