### ISSUE TITLE
css.properties.aspect-ratio - NOT SUPPORTED IN IOS SAFARI 15.3 (It's behind experimental feature flags)

### ISSUE THREAD

**Issue by karthik-muthumari** [mdn/browser-compat-data#14511]
#### What information was incorrect, unhelpful, or incomplete?
NOT SUPPORTED IN IOS SAFARI 15.3 (It's behind experimental feature flags)
#### Did you test this? If so, how?

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.aspect-ratio`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/aspect-ratio
* Report started: 2022-01-11T16:34:41.281Z

</details>

**Comment by queengooborg** [comment]
I have confirmed that this _is_ supported in Safari 15 on iOS.
