### ISSUE TITLE
css.types.color.hwb - Firefox now supports hwb()

### ISSUE THREAD

**Issue by zamadatix** [mdn/browser-compat-data#14514]
#### What information was incorrect, unhelpful, or incomplete?

hwb() support was added to Firefox in release 96 today

#### What did you expect to see?

Firefox marked as compatible since version 96 in the support table

#### Did you test this? If so, how

<details>
<summary>MDN page report details</summary>

* Query: `css.types.color.hwb`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/hwb()
* Report started: 2022-01-11T20:50:44.397Z

</details>

**Comment by queengooborg** [comment]
This has been fixed in #14125!
