### ISSUE TITLE
html.elements.blink - Opera 15 didn't support 

### ISSUE THREAD

**Issue by j-koreth** [mdn/browser-compat-data#14517]
#### What information was incorrect, unhelpful, or incomplete?
Opera 15 does not support <blink> 

#### What did you expect to see?
Blinking text on Opera 15. 
#### Did you test this? If so, how?
Downloaded the first version of Opera 15 and tested it against the blink tag and nothing happened.  Tested with Opera 12 to see if it works there and it did.

<details>
<summary>MDN page report details</summary>

* Query: `html.elements.blink`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/blink
* Report started: 2022-01-08T08:33:29.986Z

</details>

**Comment by queengooborg** [comment]
This is accurate as our data represents; the `<blink>` element was added into Opera 2, but then removed in Opera 15 since the transition to Chromium and Chrome/WebKit never had support.
