### ISSUE TITLE
api.URLSearchParams.keys - URLSearchParams not supported on Firefox for iOS

### ISSUE THREAD

**Issue by ebroder** [mdn/browser-compat-data#14527]
#### What information was incorrect, unhelpful, or incomplete?

On Firefox for iOS version 40.2 (build 7167), URLSearchParams.keys seems to be unsupported. Calling it throws the following exception:

```
key of defaultSearchParamsRef.current.keys is not a function. (In 'key of defaultSearchParamsRef.current.keys()', 'key of defaultSearchParamsRef.current.keys' is undefined)
```

#### Did you test this? If so, how?

My application uses `useSearchParams` from `react-router-dom` v6.2.1, and it throws the above exception.

<details>
<summary>MDN page report details</summary>

* Query: `api.URLSearchParams.keys`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/keys
* Report started: 2022-01-13T06:07:15.244Z

</details>

**Comment by ebroder** [comment]
I'm closing this for now, as I'm having a very difficult time reproducing this without the call into `react-router-dom`, so I think there's something more complex going on.

**Comment by queengooborg** [comment]
I recall that `react-router-dom` has its own handing for the basic navigation APIs like Navigator, Location, etc., so I have a feeling this is an issue with that package and its custom URLSearchParams handling, especially since this feature has been around in all browsers for a long time.

**Comment by ebroder** [comment]
It seems to be something much more bizarre than that - if I literally copy the `useSearchParams` method into the React component that was calling it, I can't repro anymore, so I think something very dark is happening with my bundling configuration or _something_.
