### ISSUE TITLE
api.KeyframeEffect - <KeyFrameEffect Safari MacOS>

### ISSUE THREAD

**Issue by Floran-mtte** [mdn/browser-compat-data#14529]
Safari 15.1 MacOS (17612.2.9.1.20), User Agent : Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.1 Safari/605.1.15
#### What information was incorrect, unhelpful, or incomplete?
The compatibility data, said KeyframeEffect was not working on Safari, but on the 15.1 MacOs version, it's working well
#### What did you expect to see?
Error on KeyframeEffect instantation
#### Did you test this? If so, how?
Tested on a local project

<details>
<summary>MDN page report details</summary>

* Query: `api.KeyframeEffect`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/KeyframeEffect
* Report started: 2022-01-13T09:11:12.311Z

</details>

**Comment by queengooborg** [comment]
Fixed in #16586!
