### ISSUE TITLE
css.types.color.hwb - Link to the spec is incorrect

### ISSUE THREAD

**Issue by captainbrosset** [mdn/browser-compat-data#14531]
#### What information was incorrect, unhelpful, or incomplete?

On the [hwb()](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/hwb()) page, the link to the spec is: https://drafts.csswg.org/css-color/#the-hwb-notation
This is incorrect as it leads to this server listing page:

![image](https://user-images.githubusercontent.com/1152698/149358312-386cfb9e-e1a5-412a-b26d-c9d9e04818a8.png)

<details>
<summary>MDN page report details</summary>

* Query: `css.types.color.hwb`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/hwb()
* Report started: 2022-01-13T15:22:35.141Z

</details>

**Comment by queengooborg** [comment]
Hmm, it looks like something got messed up on the spec server.  It's not that the link is wrong, but rather it's just broken at the moment.  I'll keep this issue open for now until it's fixed on CSSWG's end.

**Comment by captainbrosset** [comment]
Link now works fine. You're right this was just a temporary server error. Thanks!

**Comment by queengooborg** [comment]
Glad to hear!  Yeah this isn't the first time this particular link has broken.  😝

**Comment by tinandanny** [comment]
Stop messaging me I'm not cheating on my wife ur a hoe
