### ISSUE TITLE
api.MIDIAccess - Midi support should be experimental in Firefox

### ISSUE THREAD

**Issue by Half-Shot** [mdn/browser-compat-data#14549]
#### What information was incorrect, unhelpful, or incomplete?

Midi support in firefox is currently set to not supported.

#### What did you expect to see?

Midi support in firefox should be set to not experimental / behind feature flag.

#### Did you test this? If so, how?

Midi support is *experimental* under Firefox, by enabling the setting `dom.webmidi` to `true` in settings.

<details>
<summary>MDN page report details</summary>

* Query: `api.MIDIAccess`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MIDIAccess
* Report started: 2022-01-16T11:58:26.270Z

</details>

**Comment by queengooborg** [comment]
MIDI support was made available by default in Firefox 99, as per #15257, so I'd say we can close this issue now!

**Comment by Half-Shot** [comment]
Even betterer!
