### ISSUE TITLE
css.types.color.space_separated_functional_notation - <Space-separated values>

### ISSUE THREAD

**Issue by Nyco11** [mdn/browser-compat-data#14585]
#### What information was incorrect, unhelpful, or incomplete?
Internet Explorer, version 21H1 [build 19043.1466], supports the space-separeted values in the functional notation. 

#### Did you test this? If so, how?
Yes, I did. I tested a simple code (enclosed).

<details>
<summary>MDN page report details</summary>

* Query: `css.types.color.space_separated_functional_notation`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/hsla()
* Report started: 2022-01-19T08:48:54.326Z

</details
[hsla.txt](https://github.com/mdn/browser-compat-data/files/7896104/hsla.txt)
>

**Comment by queengooborg** [comment]
I'm closing this issue as we are no longer maintaining the Internet Explorer; see the [applicable discussion](https://github.com/orgs/mdn/discussions/202) for more details.
