### ISSUE TITLE
api.NavigatorUAData.getHighEntropyValues - not compatible with chrome 90+ on macintosh

### ISSUE THREAD

**Issue by ilovecoding294786** [mdn/browser-compat-data#14596]
Chrome
Version 97.0.4692.71 (Official Build) (x86_64) on mac os.

#### What information was incorrect, unhelpful, or incomplete?
Showing empty values for below hints.

#### What did you expect to see?
I expect platform & UA versions.

#### Did you test this? If so, how?
navigator.userAgentData.getHighEntropyValues(
  ["architecture",
  "model",
  "platformVersion",
  "uaFullVersion"])
  .then(ua => { console.log(ua) });

<details>
<summary>MDN page report details</summary>

* Query: `api.NavigatorUAData.getHighEntropyValues`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/NavigatorUAData/getHighEntropyValues
* Report started: 2022-01-19T21:30:12.399Z

</details>

**Comment by queengooborg** [comment]
I cannot confirm a lack of support on Chrome on macOS, either in the most recent version or in v97.
