### ISSUE TITLE
css.at-rules.media.range_syntax - Incorrect support from Firefox

### ISSUE THREAD

**Issue by Antonio-Laguna** [mdn/browser-compat-data#14593]
#### What information was incorrect, unhelpful, or incomplete?

It's said that Firefox 63 added support for this. However a media query such as

```pcss
@media (480px > width > 768px) {
  body {
    background-color: pink;
  }
}
```

Does not get executed. Simpler media queries seem to work such as `width <= 480px` but these ones do not:

#### What did you expect to see?

I'd have expected to see a note on partial support on that table

#### Did you test this? If so, how?

I tested with a simple Codepen https://codepen.io/antonio_laguna/pen/NWaVpeG on Browserstack on 63 and current version both on Windows and Mac.

<details>
<summary>MDN page report details</summary>

* Query: `css.at-rules.media`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/@media
* Report started: 2022-01-19T16:40:35.963Z

</details>

**Comment by romainmenke** [comment]
Full support seems to have shipped in Firefox 102.

Tested with `window.matchMedia('(1px < width < 99999px)')`

nothing in the release notes : https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/102

Firefox 101 :

<img width="1051" alt="Screenshot 2023-03-31 at 09 21 47" src="https://user-images.githubusercontent.com/11521496/229051940-b9f47937-1657-4136-8a69-3ee3dc272781.png">

Firefox 102 : 

<img width="1075" alt="Screenshot 2023-03-31 at 09 22 39" src="https://user-images.githubusercontent.com/11521496/229051952-4a11896b-c6d0-4aa6-995c-2ab55caf5761.png">
