### ISSUE TITLE
javascript.statements.try_catch - < optional catch binding>

### ISSUE THREAD

**Issue by neewbee** [mdn/browser-compat-data#14621]
#### What information was incorrect, unhelpful, or incomplete?

>  If you don't need the exception value, it could be omitted.

#### What did you expect to see?
 If you don't need the exception value, it could be omitted.(with optional catch binding)

#### Did you test this? If so, how?
`Uncaught SyntaxError: Unexpected token` { under android 8 and iOS 12

<details>
<summary>MDN page report details</summary>

* Query: `javascript.statements.try_catch`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch
* Report started: 2022-01-21T06:27:54.699Z

</details>

**Comment by queengooborg** [comment]
Thanks for opening an issue.  Just to clarify, can you explain what is currently inaccurate about the BCD table and what needs to be changed?  Our data currently reports that optional catch binding was added in Chromium 66 and Safari iOS 11.3.

**Comment by queengooborg** [comment]
Closing because there has been no response.
