### ISSUE TITLE
api.SVGGeometryElement - isPointInFill & isPointInStroke is not working in Chromium base browser

### ISSUE THREAD

**Issue by naramdash** [mdn/browser-compat-data#14620]
#### What information was incorrect, unhelpful, or incomplete?

Browser compatibility > Chrome, Edge > isPointInFill & isPointInStroke working from 33, 79
This is incorrect. not working even now.

##### Problem 1. Only Accept SVGPoint

Example on mdn fails with this console.error output.

`_sample_.Example.html:59 Uncaught TypeError: Failed to execute 'isPointInStroke' on 'SVGGeometryElement': parameter 1 is not of type 'SVGPoint'.  at _sample_.Example.html:59:39`

We need to make SVGPoint.

```javascript
const SvgElement = document.createElementNS('http://www.w3.org/2000/svg', 'svg')

function createPoint(position) {
  const point = SvgElement.createSVGPoint()
  point.x = position.x
  point.y = position.y
  return point
}
```

##### Problem 2. Malfunctioning

as doc, it has to return true, Point x 83 y 17.

```javascript
// temp1 
// <circle id="circle" cx="50" cy="50" r="45" fill="white" stroke="black" stroke-width="10"></circle>

temp1.isPointInFill(createPoint({x: 83, y: 17}))
// false
```

<details>
<summary>MDN page report details</summary>

* Query: `api.SVGGeometryElement`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/SVGGeometryElement
* Report started: 2022-01-21T06:15:01.333Z

</details>

**Comment by queengooborg** [comment]
Actually, the `isPointInFill()` is behaving as expected; 83,17 is outside of the circle.
