### ISSUE TITLE
api.HTMLMediaElement.setSinkId - Working on Chrome Android

### ISSUE THREAD

**Issue by stefanhuber** [mdn/browser-compat-data#14647]
#### What information was incorrect, unhelpful, or incomplete?
`setSinkId` is working on Android Chrome 

#### What did you expect to see?
The webrtc sample works, however one has to select the device from the `Audio Input Source` dropdown.

#### Did you test this? If so, how?
There is a sample from webrtc: https://webrtc.github.io/samples/src/content/devices/input-output/

<details>
<summary>MDN page report details</summary>

* Query: `api.HTMLMediaElement.setSinkId`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/setSinkId
* Report started: 2022-01-23T21:11:42.406Z

</details>

**Comment by queengooborg** [comment]
Sinks are audio _outputs,_ not audio _inputs._  Notice the audio output dropdown is disabled, which is programmatically disabled [when the `sinkId` property is unavailable](https://github.com/webrtc/samples/blob/2cefe37b2b01ee3ee9fb9bac108f55757523ab60/src/content/devices/input-output/js/main.js#L17).
