### ISSUE TITLE
api.ContactsManager - iOS for Mobile Compatibility

### ISSUE THREAD

**Issue by GlitchMasta47** [mdn/browser-compat-data#14648]
#### What information was incorrect, unhelpful, or incomplete?
Safari for iOS includes an experimental flag to enable the Contact Picker API on my iPhone XR running iOS version 15.1 (build 19B74). However, I don't know exactly when this toggle was added to iOS, and I don't have any devices on previous versions to try and check.

When the feature is enabled, Safari allows websites to select a contact from the systems contact book and returns it properly to the page, as shown below using a demo website linked on the MDN page for the Contact Picker API (sensitive/private information removed):

![BD9D86E0-C9B0-499F-AD24-F061649322E8](https://user-images.githubusercontent.com/17860556/150700703-3249ce84-491a-406b-b3fb-352b8b772b23.jpeg)
![96E338DE-62F9-4646-82C7-E78D161943BB](https://user-images.githubusercontent.com/17860556/150700704-d90f4144-b4ab-4653-9b82-02d234920512.jpeg)

#### What did you expect to see?
iOS versions starting with at least 15.1 have Contact Picker API support hidden behind a browser experimental flag.

#### Did you test this? If so, how?
You can access the Safari experimental flags menu on iOS by:
1. Open the system Settings application
2. Go to the Safari settings tab
3. Enter the Advanced menu at the bottom of the screen
4. Enter the Experimental Features menu at the bottom of the screen
5. Scroll down and enable the toggle next to Contact Picker API
![Screenshot of Experimental WebKit Features page showing the Contact Picker API toggle enabled](https://user-images.githubusercontent.com/17860556/150700463-4eb16cf7-148b-445c-bbd1-48e093efcbce.jpeg)

<details>
<summary>MDN page report details</summary>

* Query: `api.ContactsManager`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Contact_Picker_API
* Report started: 2022-01-23T22:21:15.213Z

</details>

**Comment by Th3tcp** [comment]
https://github.com/mdn/browser-compat-data/issues/6292#issue-637168965

**Comment by queengooborg** [comment]
Fixed by #15825!
