### ISSUE TITLE
api.BroadcastChannel - Safari column listed as "TP" with no entry in legend

### ISSUE THREAD

**Issue by icorbrey** [mdn/browser-compat-data#14656]
#### What information was incorrect, unhelpful, or incomplete?

Safari column was completely listed as "TP" with no entry in the legend.

#### What did you expect to see?

I expected to see some explanation as to what "TP" is.

#### Did you test this? If so, how?

No, this was not a technical issue.

<details>
<summary>MDN page report details</summary>

* Query: `api.BroadcastChannel`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Broadcast_Channel_API
* Report started: 2022-01-24T15:59:27.747Z

</details>

**Comment by queengooborg** [comment]
This is a fair point, thank you for bringing this up!  "TP" means "Technology Preview", in other words Safari's beta channel.  I'm surprised this wasn't added to the legend -- I'll ask someone with permissions to transfer this issue over to Yari so they can add this feature!

**Comment by queengooborg** [comment]
I've now opened up https://github.com/mdn/yari/pull/5207 to add this functionality!
