### ISSUE TITLE
spec_url for HTMLInputElement.reportValidity() - HTMLInputElement.reportValidity() is missing a spec_url

### ISSUE THREAD

**Issue by sockcrates** [mdn/browser-compat-data#14669]
#### What information was incorrect, unhelpful, or incomplete?
`HTMLInputElement.reportValidity()` is missing `spec_url`, so its specification isn't populating automatically in MDN.

The specific error message on MDN is `No specification data found for api.HTMLInputElement.reportValidity`.

#### What did you expect to see?
A link to the specification of `HTMLInputElement.reportValidity()`.

#### Did you test this? If so, how?
I created a page in MDN which relies on this, and it didn't show the spec. Instead, it recommended I add the spec here.

#### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?
The pull request to MDN below is the page that will use the `spec_url` that needs to be added.

- https://github.com/mdn/content/pull/12423

**Comment by sockcrates** [comment]
Oops, seems like this is the wrong place.

**Comment by queengooborg** [comment]
Actually, you made it to the right place!  😄   We moved the spec URLs into the BCD project to simplify maintenance.  I've reopened this issue accordingly, so we can get this resolved ASAP!

**Comment by sockcrates** [comment]
Thank you for clearing things up for me!
