### ISSUE TITLE
css.properties.-webkit-print-color-adjust - <PUT TITLE HERE>

### ISSUE THREAD

**Issue by Meet2000** [mdn/browser-compat-data#14683]
#### Yes. By running it on mobile

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.-webkit-print-color-adjust`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-print-color-adjust
* Report started: 2022-01-26T18:00:38.806Z

</details>

**Comment by queengooborg** [comment]
In the compatibility tables, it is indicated that:

> Chrome does not print backgrounds of the <body> element. If this property is set to exact for the <body> element, it will apply only to its descendants.
