### ISSUE TITLE
api.DOMParser.parseFromString - Firefox Exception But No parsererror

### ISSUE THREAD

**Issue by queejie** [mdn/browser-compat-data#14702]
#### What information was incorrect, unhelpful, or incomplete?
It works in Chrome (latest), but Firefox (latest, 96) fires an exception that is not catchable in a try/catch, and there is no parsererror element created to indicate validation failure.  It appears as though you cannot catch errors in any way in Firefox.

#### What did you expect to see?
Expected the parsererror node to be created, as documented.

#### Did you test this? If so, how?
Used application/xml for an HTML snippet: <p>Bad end tag/p>

<details>
<summary>MDN page report details</summary>

* Query: `api.DOMParser.parseFromString`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/DOMParser/parseFromString
* Report started: 2022-01-28T16:35:21.324Z

</details>

**Comment by queengooborg** [comment]
I'm not having any issues getting a `parsererror` node from the result of `parser.parseFromString()` in Firefox, using the example code in https://developer.mozilla.org/en-US/docs/Web/API/DOMParser/parseFromString#error_handling, in the latest version and in Firefox 96.  It does log an error to the console as well, though.
