### ISSUE TITLE
api.CustomElementRegistry.define - Use subfeatures, not notes

### ISSUE THREAD

**Issue by gsnedders** [mdn/browser-compat-data#14711]
The various browsers have notes for `api.CustomElementRegistry.define`, whereas it would make more sense to split it into the base feature and `options_extends_parameter`.

<details>
<summary>MDN page report details</summary>

* Query: `api.CustomElementRegistry.define`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry/define
* Report started: 2022-01-28T23:49:57.444Z

</details>

**Comment by queengooborg** [comment]
Fixed by #17002!
