### ISSUE TITLE
javascript.builtins.DataView - Two rows with identical descriptions

### ISSUE THREAD

**Issue by benblank** [mdn/browser-compat-data#14765]
#### What information was incorrect, unhelpful, or incomplete?

There are two rows in the compatibility table with identical descriptions ("SharedArrayBuffer accepted as buffer"), but different compatibility data. It is unclear what the difference is.

#### What did you expect to see?

Each row to have a unique description.

#### Did you test this? If so, how?

n/a

<details>
<summary>MDN page report details</summary>

* Query: `javascript.builtins.DataView`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView
* Report started: 2022-02-01T02:53:05.450Z

</details>

**Comment by Elchi3** [comment]
One is for the buffer property: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView/buffer#browser_compatibility

And the other is for the constructor: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView/DataView#browser_compatibility

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView#browser_compatibility shows them both. I guess the rendering could be improved, that's an issue for how MDN displays the compat data, though. (https://github.com/mdn/yari handles rendering)

**Comment by benblank** [comment]
Heh, I'd nearly forgotten about this. It looks like the problem was actually addressed in mdn/yari#5851 last April, so nothing needs done at this point, anyway. It's now pretty clear that the first "SharedArrayBuffer accepted as buffer" is associated with "DataView() contructor" and the second with "buffer".
