### ISSUE TITLE
javascript.builtins.String.at - 

### ISSUE THREAD

**Issue by azmu0520** [mdn/browser-compat-data#14793]
#### But got error : String.at(index) is not a function

<details>
<summary>MDN page report details</summary>

* Query: `javascript.builtins.String.at`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/at
* Report started: 2022-02-02T14:51:00.850Z

</details>

**Comment by queengooborg** [comment]
This sounds like a development issue rather than a browser compatibility issue, probably using "String" instead of the string variable.  Please note that we are not a development help forum.
