### ISSUE TITLE
WebGL 2.0 support on mobile

### ISSUE THREAD

**Issue by kainino0x** [mdn/browser-compat-data#148]
WebGL 2.0 is available on Chrome for Android as of 58, and Firefox for Android as of (I think) 51.0 (@jdashg, can you confirm?)

This probably means it will be available in Opera for Android as of 45 or so, but I haven't checked.

**Comment by jpmedley** [comment]
I can confirm the Android portion. https://www.chromestatus.com/features/6694359164518400

**Comment by Elchi3** [comment]
I think I can confirm WebGL2 on Firefox for Android 51. With the chromestatus info, we would have:

Android Webview 58
Chrome desktop 56
Chrome for Android 58
Firefox desktop 51
Firefox Android 51
Opera desktop 43
Opera for Android 43

**Comment by teoli2003** [comment]
#454 has been merged. I'm closing this.
