### ISSUE TITLE
css.properties.list-style-type - disclosure-open and disclosure-closed shipped in Chromium

### ISSUE THREAD

**Issue by AtomicNoggin** [mdn/browser-compat-data#14829]
Browser compatibility chart indicates all non-chromium browsers as not supporting disclosure-open and disclosure-closed

Should state that it's supported as of Chrome 89 (unsure of versions for Opera and/or Edge)
https://chromestatus.com/feature/6561346332131328
https://bugs.chromium.org/p/chromium/issues/detail?id=590014

Also verified by adding Details/Summary html elements on page, inspected in Chrome Devtools. Summary element utilized these list-style-type values in user agent stylesheet

(initially posted in the page issues here mdn/browser-compat-data#14830)

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.list-style-type`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/list-style-type
* Report started: 2022-02-04T16:04:02.226Z

</details>

**Comment by queengooborg** [comment]
Fixed in #18894!
