### ISSUE TITLE
api.IDBIndex.getAllKeys - Outdated Firefox compatibility 

### ISSUE THREAD

**Issue by ghost** [mdn/browser-compat-data#14856]
#### What information was incorrect, unhelpful, or incomplete?

Firefox 96 supports IDBIndex.getAllKeys.

#### What did you expect to see?

Running the following will bring up the getAllKeys method for the IDBIndex class.

```js
IDBIndex.prototype.getAllKeys
```

#### Did you test this? If so, how?

I ran the above in Firefox devtools.

![test](https://user-images.githubusercontent.com/97319620/152670231-8166d5c3-9b39-4d38-a05b-7488584d0b67.jpg)

<details>
<summary>MDN page report details</summary>

* Query: `api.IDBIndex.getAllKeys`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/IDBIndex/getAllKeys
* Report started: 2022-02-06T06:16:03.581Z

</details>

**Comment by queengooborg** [comment]
Fixed in #18586!
