### ISSUE TITLE
api.structuredClone - incorrect versioning for Chrome

### ISSUE THREAD

**Issue by chug187** [mdn/browser-compat-data#14867]
#### What information was incorrect, unhelpful, or incomplete?

Chrome 98 has shipped this functionality, but it is marked as unsupported.

#### What did you expect to see?

Chrome to indicate structuredClone support with version 98.

#### Did you test this? If so, how?

<details>
<summary>MDN page report details</summary>

* Query: `api.structuredClone`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/structuredClone
* Report started: 2022-02-07T13:52:59.660Z

</details>

**Comment by lucacasonato** [comment]
Duplicate of #14501
