### ISSUE TITLE
document.activeElement not set in WebKit on mouse click

### ISSUE THREAD

**Issue by dilyanpalauzov** [mdn/browser-compat-data#14866]
https://caniuse.com/mdn-api_document_activeelement says `document.activeElement` is supported by WebKit/Safari.

My exprience shows, that WebKit does not set `document.activeElement` when clicking by mouse.  Firefox and Chrome set `document.activeElement` when clicking by mouse.  All browsers set `document.activeElement`, when navigating with keyboard.

https://bugs.webkit.org/show_bug.cgi?id=236217 contains detais and sample snippet for reproduction.

**Comment by queengooborg** [comment]
I haven't been able to reproduce the issue on any version of Safari, and we don't currently track data for other (currently-)WebKit-based browsers.  The bug's title says `[GTK]`, so I'm assuming this was an issue that only affected GTK-based WebKit browsers.

**Comment by dilyanpalauzov** [comment]
Per https://bugs.webkit.org/show_bug.cgi?id=236217 this is now corrected in GtkWebKit.
