### ISSUE TITLE
api.structuredClone - supported browsers table is not updated for latest versions of browsers

### ISSUE THREAD

**Issue by KrofDrakula** [mdn/browser-compat-data#14885]
#### What information was incorrect, unhelpful, or incomplete?

- Chrome (as of at least 98) supports it
- Firefox (as of at least 97) supports it
- Safari doesn't support it yet

#### What did you expect to see?

Both Chrome and Firefox ship this feature in their current released versions.

#### Did you test this? If so, how?

Tested locally on Windows with Chrome 98 and Firefox Dev Edition 97. Tested Safari Desktop 15.1 on BrowserStack. Haven't tested mobile.

<details>
<summary>MDN page report details</summary>

* Query: `api.structuredClone`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/structuredClone
* Report started: 2022-02-08T12:59:33.702Z

</details>

**Comment by queengooborg** [comment]
This has been resolved in #14483 and #12671!

**Comment by KrofDrakula** [comment]
![](https://media.giphy.com/media/kyLYXonQYYfwYDIeZl/giphy.gif)
