### ISSUE TITLE
Links to drafts.csswg.org are broken

### ISSUE THREAD

**Issue by akselinurmio** [mdn/browser-compat-data#14887]
Specification links on MDN that link to `drafts.csswg.org` domain seem to be broken, as in the links' destinations are not returning the spec, but a server's index page instead:

<img width="644" alt="Screenshot 2022-02-08 at 18 10 11" src="https://user-images.githubusercontent.com/3000387/153028009-a146f72b-e4ee-4007-a82e-44a5bb9e9930.png">

There are 1,037 `spec_url` properties in this repo that have URLs under the origin https://drafts.csswg.org. I think that the preferred solution would be to work with CSS WG to fix the links.

For example following pages have broken links:

- https://developer.mozilla.org/docs/Web/CSS/background → https://drafts.csswg.org/css-backgrounds/#the-background
- https://developer.mozilla.org/docs/Web/CSS/color_value → https://drafts.csswg.org/css-color/#color-syntax

**Comment by Elchi3** [comment]
Thanks for the issue. It is a recurring issue and the CSS WG is aware. See https://github.com/w3c/csswg-drafts/issues/6528 for the issue.
