### ISSUE TITLE
javascript.builtins.Intl.DisplayNames - react native android - it says undefined is not a constructor new Intl.DisplayNames

### ISSUE THREAD

**Issue by macidori98** [mdn/browser-compat-data#14895]
#### What information was incorrect, unhelpful, or incomplete?
i get the next error when i want to run on android device, react native
E/ReactNativeJS: TypeError: undefined is not a constructor (evaluating 'new Intl.DisplayNames([currentLanguageCode], {
            type: 'language'
          })')
#### What did you expect to see?
i expected to see what i see on an ios device/emulator -> the language name in a given language
#### Did you test this? If so, how?

<details>
<summary>MDN page report details</summary>

* Query: `javascript.builtins.Intl.DisplayNames`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DisplayNames
* Report started: 2022-02-09T07:09:53.276Z

</details>

**Comment by Elchi3** [comment]
Intl.DisplayNames seems to be well supported now. If it isn't, let us know which browser you're using.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DisplayNames#browser_compatibility
