### ISSUE TITLE
api.CustomEvent - Missing NodeJS data

### ISSUE THREAD

**Issue by achingbrain** [mdn/browser-compat-data#14905]
#### What information was incorrect, unhelpful, or incomplete?

node.js is missing from the compatibility table when it is present for other events.

#### What did you expect to see?

node.js in the compatibility table.

#### Did you test this? If so, how?

N/a

<details>
<summary>MDN page report details</summary>

* Query: `api.CustomEvent`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent
* Report started: 2022-02-09T21:30:55.221Z

</details>

**Comment by queengooborg** [comment]
Fixed in #18076!
