### ISSUE TITLE
api.MediaRecorder.pause - Not working in Safari

### ISSUE THREAD

**Issue by AYUSH325** [mdn/browser-compat-data#14906]
#### What information was incorrect, unhelpful, or incomplete?
mediarecorder.pause() is not compatible with safari yet
#### What did you expect to see?
i have tested it in and recording was not paused
#### Did you test this? If so, how?
yes, tested it recording paused in both google chrome and firefox and gave me correct zip file, but in safari it says mediarecouder.pause not a function

<details>
<summary>MDN page report details</summary>

* Query: `api.MediaRecorder.pause`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder/pause
* Report started: 2022-02-09T22:24:04.789Z

</details>

**Comment by queengooborg** [comment]
Just to confirm, what Safari version are you using?  Support for this feature was added in Safari 14.4 as our data indicates.

**Comment by queengooborg** [comment]
Closing because there has been no response.
