### ISSUE TITLE
css.types.filter-function.drop-shadow - Drop Shadow does not Render Properly on iPhone

### ISSUE THREAD

**Issue by jteasley1113** [mdn/browser-compat-data#14913]
#### What information was incorrect, unhelpful, or incomplete?
All information was well. 

#### What did you expect to see?
A drop shadow effect around a blog post, as well as the documentation example. 

#### Did you test this? If so, how?
After viewing this effect on an iPhone mobile device, there are sharp breaks that occur in varying locations as the user zooms in and out. Here are two photos depicting the issue. 

![image](https://user-images.githubusercontent.com/68207403/153339777-486d6880-64f7-4bd3-941e-edf09effdbff.png)

![image](https://user-images.githubusercontent.com/68207403/153339737-e59c0cd0-8499-4621-855d-51ff34952bea.png)

<details>
<summary>MDN page report details</summary>

* Query: `css.types.filter-function.drop-shadow`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/filter-function/drop-shadow()
* Report started: 2022-02-10T04:33:42.796Z

</details>

**Comment by queengooborg** [comment]
It appears these issues have been fixed!
