### ISSUE TITLE
css.at-rules.media.resolution - Bug #78087

### ISSUE THREAD

**Issue by TyposBro** [mdn/browser-compat-data#14950]
Bug #78087 on [webkit.org](https://bugs.webkit.org/show_bug.cgi?id=78087) was fixed & patched.

<details>
<summary>MDN page report details</summary>

* Query: `css.at-rules.media.resolution`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/resolution
* Report started: 2022-02-12T19:24:25.835Z

</details>

**Comment by queengooborg** [comment]
Fixed in #18706!
