### ISSUE TITLE
css.properties.-webkit-line-clamp - <Ellipsis not getting added in safari browser>

### ISSUE THREAD

**Issue by TejaSivaVenkatesh** [mdn/browser-compat-data#14992]
#### What information was incorrect, unhelpful, or incomplete?
It has been mentioned that It gives the ellipsis at the end of the line based on the prop value.
Example: -webkit-line-clamp: 3. So according to that ellipsis should get added at the end of the third line. It is working fine in chrome but not working in safari. My safari version is **Version 15.2 (17612.3.6.1.6)**
#### What did you expect to see?
I have expected to see ellipsis at the end of the mentioned line. Mean If I give value 5 then at the 5th line.

#### Did you test this? If so, how?
I have tested it in the safari browser with different screen resolutions. It is working on Chrome browser but not on safari(mac).

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.-webkit-line-clamp`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-line-clamp
* Report started: 2022-02-15T12:22:45.874Z

</details>

**Comment by whitelabeliq** [comment]
I'm facing with the same issue and have found that the -webkit-line-clamp won't work with the animation like fadeInUp or something like that.

**Comment by pkkanzariya2022** [comment]
I'm facing with the same issue and have found that the -webkit-line-clamp won't work with the animation like fadeInUp or something like that. I have used the [wow.js](https://wowjs.uk/) and have added the fade classes. While, I remove the animation, -webkit-line-clamp works fine and with the animation it won't.

**Comment by queengooborg** [comment]
The MDN page states the following:

> It only works in combination with the [display](https://developer.mozilla.org/en-US/docs/Web/CSS/display) property set to -webkit-box or -webkit-inline-box and the [-webkit-box-orient](https://developer.mozilla.org/en-US/docs/Web/CSS/box-orient) property set to vertical.

I've confirmed that this is true, so it would make sense that animations by third-party libraries, which most likely change the display mode to something like `block` or `inline-block`, would break `-webkit-inline-clamp`.
