### ISSUE TITLE
api.Navigator.share - not working on MacOS

### ISSUE THREAD

**Issue by jaysonmulwa** [mdn/browser-compat-data#15003]
#### Did you test this? If so, how?

<details>
<summary>MDN page report details</summary>

* Query: `api.Navigator.share`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share
* Report started: 2022-02-16T05:50:05.580Z

</details>

**Comment by queengooborg** [comment]
I'm assuming that you're using this in Chrome.  This is expected, Chrome has not implemented sharing on macOS -- see https://crbug.com/1144920.

If you're referring to another browser, please indicate so by filling out the issue template above.

**Comment by jaysonmulwa** [comment]
Thanks for the response.
Yes, this is in Chrome.
