### ISSUE TITLE
Can you update your issue to contain a UTF-8 formatted title and fill out the fields in the issue body?

### ISSUE THREAD

**Issue by Kulkanya99** [mdn/browser-compat-data#15015]
Can you update your issue to contain a UTF-8 formatted title and fill out the fields in the issue body?

_Originally posted by @tacerus in https://github.com/mdn/browser-compat-data/issues/15009#issuecomment-1042313713_

**Comment by tacerus** [comment]
Is this a bot or a joke I am not getting?

**Comment by queengooborg** [comment]
@tacerus There's been a wave of bot accounts appearing on GitHub, and on this project we've been getting hit with quite a few of them.  I've got a hunch they're trying to unlock GitHub Actions support so they can mine free crypto or something.  Best thing to do is to ignore these sorts of accounts.  😛

**Comment by tacerus** [comment]
Interesting, I have seen spam in many places but never on GitHub. Sorry for triggering it!
