### ISSUE TITLE
webextensions.api.tabs.update - <PUT TITLE HERE>

### ISSUE THREAD

**Issue by Manvityagi** [mdn/browser-compat-data#15017]
#### What information was incorrect, unhelpful, or incomplete?
Tabs.update is not supported in safari 
See here - https://developer.apple.com/documentation/safariservices/safari_web_extensions/assessing_your_safari_web_extension_s_browser_compatibility 

#### Did you test this? If so, how?
I am trying to use update in one of my safari extensions and it's not working. 

<details>
<summary>MDN page report details</summary>

* Query: `webextensions.api.tabs.update`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/update
* Report started: 2022-02-17T04:48:08.718Z

</details>

**Comment by queengooborg** [comment]
Closing because there has been no response.
