### ISSUE TITLE
css.properties.text-justify - Edge no longer supports this property

### ISSUE THREAD

**Issue by ghost** [mdn/browser-compat-data#15010]
Microsoft Edge browser no longer supports text-justify property. Source: https://caniuse.com/?search=text-justify

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.text-justify`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/text-justify
* Report started: 2022-02-16T18:02:44.628Z

</details>

**Comment by queengooborg** [comment]
Fixed in #20057!
