### ISSUE TITLE
css.properties.display - CSS 'display:inline-block' compatible with Internet Explorer 5.5

### ISSUE THREAD

**Issue by sJARB** [mdn/browser-compat-data#15023]
In the CSS 'display' page on MDN Web Docs, I see that parameter 'inline-block' is compatible only with Internet Explorer 6 and more.

I have some old virtual machines, and one of them is a fresh install of Windows Millennium Edition without any updates.
When i'm trying to access to my site with its integrated browser, Microsoft Internet Explorer 5.5 (aka 5.50.4134.0100), I see that the parameter 'inline-block' also work on Internet Exploprer 5.5.

My site contains that block of code :
```html
<span style="display: inline-block; margin:10px">
	<table cellpadding="10px" cellspacing="0">
		<tr>
			<td bgcolor="#CFCFCF" style="border-radius:15px; box-shadow:0 0 3px 3px #CFCFCF; -moz-box-shadow:0 0 3px 3px #CFCFCF; -webkit-box-shadow:0 0 3px 3px #CFCFCF;">
				<img src="http://images.sjarb.fr/rsl/windows.gif" alt="Windows" />
			</td>
		</tr>
		<tr>
			<td align="center">
				<font face="Helvetica,sans-serif" size="4">Windows</font>
			</td>
		</tr>
	</table>
</span>
<span style="display: inline-block; margin:10px">
	<table cellpadding="10px" cellspacing="0">
		<tr>
			<td bgcolor="#CFCFCF" style="border-radius:15px; box-shadow:0 0 3px 3px #CFCFCF; -moz-box-shadow:0 0 3px 3px #CFCFCF; -webkit-box-shadow:0 0 3px 3px #CFCFCF;">
				<img src="http://images.sjarb.fr/rsl/arachne.gif" alt="Arachne" />
			</td>
		</tr>
		<tr>
			<td align="center">
				<font face="Helvetica,sans-serif" size="4">Arachne</font>
			</td>
		</tr>
	</table>
</span>
```
And, i clearly see that the two logos are on the same line. Also, I know that W3C don't recommand to put a 'table' into a 'span' but its just like that I found this. Like for Internet Explorer 6 and 7, it can be applied only for natural inline elements on Internet Explorer 5.5.

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.display`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/CSS/display
* Report started: 2022-02-18T00:37:52.190Z

</details>

**Comment by sJARB** [comment]
With some additional test, i've found that Microsoft Internet Explorer 5.0 (5.00.2614.3500), the one pre-installed with Windows 98 SE, is also compatible with the attribute `display:inline-block`, when applied to a natural inline element.

**Comment by queengooborg** [comment]
I'm closing this issue as we are no longer maintaining the Internet Explorer data; see the [applicable discussion](https://github.com/orgs/mdn/discussions/202) for more details.
