### ISSUE TITLE
chrome 98 doesnt seem to respect autocomplete=new-password.

### ISSUE THREAD

**Issue by sudhir-nibbles** [mdn/browser-compat-data#15038]
#### What information was incorrect, unhelpful, or incomplete?
chrome 98 doesnt seem to respect autocomplete=new-password.

#### What did you expect to see?
password field does not autofill

#### Did you test this? If so, how?
Yes, applied attribute autocomplete=new-password to password field and it didnt work for chrome. Seems to be ok for other browsers.

<details>
<summary>MDN page report details</summary>

* Query: `html.global_attributes.autocomplete`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete
* Report started: 2022-02-18T21:07:42.943Z

</details>

**Comment by queengooborg** [comment]
Fixed in #19931!
