### ISSUE TITLE
webextensions.api.windows - windows.onBoundsChanged is missing from the Compatibility Table

### ISSUE THREAD

**Issue by ryankashi** [mdn/browser-compat-data#15039]
#### What information was incorrect, unhelpful, or incomplete?
chrome.windows.onBoundsChanged is not supported by Firefox browsers, and is missing from the compatibility list here:

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Browser_support_for_JavaScript_APIs

#### What did you expect to see?
The support for windows.onBoundsChanged should be displayed in the table seen below:

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Browser_support_for_JavaScript_APIs

With there being no support for Firefox

#### Did you test this? If so, how?
I have not tested this, however when uploading my extension to Firefox I was given a warning that this function is not supported.

<details>
<summary>MDN page report details</summary>

* Query: `webextensions.api.windows`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Browser_support_for_JavaScript_APIs
* Report started: 2022-02-18T22:31:37.340Z

</details>

**Comment by evilpie** [comment]
@ryankashi Where is `windows.onBoundsChanged` documented? This function doesn't seem to exist anywhere.

**Comment by gwarser** [comment]
https://developer.chrome.com/docs/extensions/reference/windows/#event-onBoundsChanged ?

**Comment by ryankashi** [comment]
Gwarser has linked the one that I am referring to!
