### ISSUE TITLE
Issue with "<input type="time">": (Android 11 not show AM or PM)

### ISSUE THREAD

**Issue by kaominghsu** [mdn/browser-compat-data#15096]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time

#### What information was incorrect, unhelpful, or incomplete?
created an input type='time' on html
But I test the phone on Android 11 and it doesn't show AM or PM correctly
Even if I set PM 06:00, it will only show 06:00 back to input

#### Specific section or headline?
Android 11 not show AM or PM on input type="time"

#### What did you expect to see?
 if I set PM 06:00, it will only show PM 06:00 back to input

#### Did you test this? If so, how?
Yes,I test this
if I set PM 06:00, it will only show 06:00 back to input

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/input/time`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/input/time/index.md
* Last commit: https://github.com/mdn/content/commit/ec78469bbfa566ca0ca49fd95649c04efe2aec70
* Document last modified: 2022-02-14T17:12:43.000Z

</details>

**Comment by kaominghsu** [comment]
hi,
I gave the specs for the phone and video
Phone:Sony Xperia 5 II

video: https://user-images.githubusercontent.com/46553707/157206204-2c1b897e-a1bb-4160-bf8e-c525c44ba2cf.mp4

**Comment by kaominghsu** [comment]
@queengooborg  
This question has not been answered for a long time
Can anyone be sure?

**Comment by lukewarlow** [comment]
On Android 12 I see no issues with the time input depending on the system setting for 24 hour time format I get two different UIs but both work as expected.

Based on this I don't think this is an issue with the MDN data.

If you do have an issue I recommend reporting in chrome bug tracker (assuming you use chrome I don't think you mentioned which browser)


![Screenshot_20220331-152232.png](https://user-images.githubusercontent.com/32498324/161078170-6bdc3ba0-cee8-4dc7-bac0-c3273836d753.png)

![Screenshot_20220331-152304.png](https://user-images.githubusercontent.com/32498324/161078180-404cc92e-e2cf-4b17-9d29-2adcce9ca81f.png)

**Comment by kaominghsu** [comment]
> hi   @lukewarlow 
目前我發現在Samsung & Sony的手機上才會有該問題
我不確定是不是廠商在android上多加自行研發的軟體而產生
因此我才會在此發布問題
目前都是使用chrome或者手機本身的瀏覽器套件(因APP有使用類似webview的元件瀏覽網頁)
再提供給您
THANKS

**Comment by queengooborg** [comment]
I tested this on my OnePlus Nord to see what the results are, and it seems to be working as expected, displaying AM/PM in Chrome.  As such, I'm thinking it may be some bug with the manufacturer's Android implementation.

**Comment by kaominghsu** [comment]
hi, @queengooborg 

Does this notify the manufacturer of the problem?
Because of this problem, users of our products think it is a problem with our products

> I tested this on my OnePlus Nord to see what the results are, and it seems to be working as expected, displaying AM/PM in Chrome. As such, I'm thinking it may be some bug with the manufacturer's Android implementation.

**Comment by queengooborg** [comment]
I'm sorry, we don't forward bug reports to browser vendors; you'll have to reach out to the vendors yourself.
