### ISSUE TITLE
api.HTMLMediaElement.controlsList - Inaccurate compatibility list.

### ISSUE THREAD

**Issue by StefanGhiban** [mdn/browser-compat-data#15100]
#### What information was incorrect, unhelpful, or incomplete?

The browser compatibility list is inaccurate. Using the samsung internet on mobile still shows the download button for the videos, even though the compatibility list says that this feature is available on this browser. At the same time, on safari on ios, safari desktop and firefox desktop this feature works even though it says that it does not.

#### What did you expect to see?

I expected this feature to work on most browsers, bu then I followed the compatibility list and it was inaccurate.

#### Did you test this? If so, how?
I have tested this feature on multiple browsers and on multiple platforms using crossbrowsertesting (a website to test multiple platform) and also natively on iphone, android phone and macos desktop.

<details>
<summary>MDN page report details</summary>

* Query: `api.HTMLMediaElement.controlsList`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/controlsList
* Report started: 2022-02-24T09:11:19.237Z

</details>

**Comment by StefanGhiban** [comment]
It seems that on the samsung internet the issue is with the samsung assistant. They have a wrapper over the videos where they add their own buttons. Save video is one of those buttons, but the issue stands on the other browsers. This feature seems to work on everything, but the docs do not reflect that.

**Comment by lukewarlow** [comment]
I'm fairly sure this isn't supported in Safari or Firefox because I remember looking into it fairly recently. And from my quick testing just now the attribute is indeed ignored. Could it be that the browsers you tested just happen to not have the UI in the first place, for example I don't believe Firefox or Safari has a download button in their UI.
