### ISSUE TITLE
api.AbortSignal.reason - Also supported by Chrome

### ISSUE THREAD

**Issue by StigNygaard** [mdn/browser-compat-data#15113]
Tested with:
Chrome 98.0.4758.102 (Official Build) (64-bit)

#### What information was incorrect, unhelpful, or incomplete?

Chart says this doesn't work in any version of Google Chrome. However this works for me in Chrome 98 just as it does in Firefox.
Sorry, I haven't investigated further with other versions or made a simple testcase. 

#### Did you test this? If so, how?

In an (intranet) application I use Controller.abort() to set different "custom-values" to Signal.reason to abort a fetch after either 12 seconds or at page-navigation. I can see/check value (and write values to console) in my Fetch.catch() handler on "AbortErrors".

<details>
<summary>MDN page report details</summary>

* Query: `api.AbortSignal.reason`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal/reason
* Report started: 2022-02-25T09:09:57.298Z

</details>

**Comment by StigNygaard** [comment]
It looks like https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal/reason has been updated. Should this be closed?

**Comment by queengooborg** [comment]
Fixed in #16956!
