### ISSUE TITLE
http.methods.TRACE - <256>

### ISSUE THREAD

**Issue by Snakefinder** [mdn/browser-compat-data#15130]
`<!--` Tips: where applicable, specify browser name, browser version, and mobile operating system version -->

#### Did you test this? If so, how?

<details>
<summary>MDN page report details</summary>

* Query: `http.methods.TRACE`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/TRACE
* Report started: 2022-02-26T14:37:41.184Z

</details>

**Comment by Catclaws12** [comment]
Get Outlook for iOS<https://aka.ms/o0ukef>

**Comment by Catclaws12** [comment]
1.

  *

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Snakefinder ***@***.***>
Sent: Saturday, February 26, 2022 8:39 AM
To: mdn/browser-compat-data
Cc: Subscribed
Subject: [mdn/browser-compat-data] http.methods.TRACE - <256> (Issue #15130)




What information was incorrect, unhelpful, or incomplete?
What did you expect to see?
Did you test this? If so, how?
MDN page report details

  *   Query: http.methods.TRACE
  *   MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/TRACE
  *   Report started: 2022-02-26T14:37:41.184Z
