### ISSUE TITLE
Issue with "Intl.Locale": Browser compatibility Tables (Chrome)

### ISSUE THREAD

**Issue by MohsenAlyafei** [mdn/browser-compat-data#15174]
### **Chrome version 99 onwards now fully supports the remaining Instance properties of the **Intl.Locale()** constructor; namely:**

[Intl.Locale.prototype.calendar](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/calendar)

collations (broken link on page)

[Intl.Locale.prototype.hourCycles](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/hourCycles)

[Intl.Locale.prototype.numberingSystems](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/numberingSystems)

[Intl.Locale.prototype.textInfo](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/textInfo)

[Intl.Locale.prototype.timeZones](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/timeZones)

[Intl.Locale.prototype.weekInfo](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/weekInfo)

**The Browser compatibility Tables on the various pages and the main page need to be updated.**

**Comment by hamishwillee** [comment]
FYI - the chrome status in which this went in is https://chromestatus.com/feature/5566859262820352 and there is some more info here: https://github.com/tc39/proposal-intl-locale-info/blob/main/README.md#high-level-design

I don't know enough to understand all the implications, but it looks like it might affect the constructor and each of the properties, and that it probably needs the docs to be updated TOO- e.g. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/Locale#parameters could use some love around the possible options.

What confuses me is that this is already marked as supported in chrome in 74 - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/calendar so I don't know what it is that has changed - was the old data wrong?

**Comment by calvinf** [comment]
@hamishwillee The info on the [V8 v9.9 release blog post](https://v8.dev/blog/v8-release-99#javascript) is relevant:

> In v7.4 we launched the [Intl.Locale API](https://v8.dev/blog/v8-release-74#intl.locale). With v9.9, we added seven new properties to the Intl.Locale object: calendars, collations, hourCycles, numberingSystems, timeZones, textInfo, and weekInfo.

The features have been available behind a flag for a while, seemingly V8 v9.2. FWIW, the V8 version usually lines up with the Chrome version (i.e., V8 v9.9 was released as part of Chrome 99).

**Comment by hamishwillee** [comment]
Thanks, done in #15505.
