### ISSUE TITLE
css.properties.scroll-behavior - <scroll-behavior:smooth not compactable for safari browser>

### ISSUE THREAD

**Issue by VikashPR** [mdn/browser-compat-data#15173]
#### What information was incorrect, unhelpful, or incomplete?
Incorrect 

Safari browser's do not support ```scroll-behavior: smooth;``` 
But in the documentation it is mentioned safari browsers are compactable 
![Screenshot 2022-02-28 at 9 50 08 PM](https://user-images.githubusercontent.com/69889418/156018855-dcaec82c-9741-4b30-95b0-7f8469c4c70c.png)

#### What did you expect to see?
```scroll-behavior: smooth;``` is unsupportable in safari else if there is other ways of implementing in safari browsers it should be mentioned.

#### Did you test this? If so, how?
I have been working on my personal project which is enabled with ```scroll-behavior: smooth;``` init but when I test my project in safari browsers the ```scroll-behavior: smooth;``` is not working.

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.scroll-behavior`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior
* Report started: 2022-02-28T16:12:53.579Z

</details>

**Comment by queengooborg** [comment]
This is a slight rendering issue as 15.4 is a beta release, and will be fixed in https://github.com/mdn/yari/pull/5311!
