### ISSUE TITLE
javascript.operators.optional_chaining - <PUT TITLE HERE>

### ISSUE THREAD

**Issue by eieye** [mdn/browser-compat-data#15218]
... this may be "Schnee von gestern" but perhaps the information could be included, identifying the EARLIEST Safari version that supported optional chaining ... (that information is provided for the major other browsers)

#### What information was incorrect, unhelpful, or incomplete?
"?." operator is not compatible with Safari (Desktop) 12.1.2 (12607.3.10) under MacOS Sierra 10.12.6

#### What did you expect to see?
not this: Safari console reports "invalid character "'.'" at a given line -- apparently refering to the dot in the "?." operator

#### Did you test this? If so, how?
https://codepen.io/jkantner/pen/dyZjWvG
above file runs, when ".?" is replaced with "." (normal chaining) operator

<details>
<summary>MDN page report details</summary>

* Query: `javascript.operators.optional_chaining`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining
* Report started: 2022-03-01T19:56:17.242Z

</details>

**Comment by yume-chan** [comment]
If you came from MDN, after the redesign, you need to click the table cell to see versions.

![image](https://user-images.githubusercontent.com/1330321/156305243-23cba034-7892-4c13-9dcb-7e06d4c2e096.png)

**Comment by eieye** [comment]
Thank you!
(I guess I would support that request)
