### ISSUE TITLE
svg.attributes.presentation.alignment-baseline - Compatibility

### ISSUE THREAD

**Issue by DraakBZH** [mdn/browser-compat-data#15219]
#### What information was incorrect, unhelpful, or incomplete?
Compatibility is unknow
#### What did you expect to see?
correct Compatibility
#### Did you test this? If so, how?

I check in multiple browser my own SVG inline file

Firefox 97.0.1 **didn't work**
Edge Version 98.0.1108.62 is **OK**
Chrome Version 98.0.4758.102 is **OK**
IE 21H2 **didn't work**
Opera Version :84.0.4316.21 is **OK**

I Can't test mobile 

<details>
<summary>MDN page report details</summary>

* Query: `svg.attributes.presentation.alignment-baseline`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/alignment-baseline
* Report started: 2022-03-01T21:00:50.621Z

</details>

**Comment by queengooborg** [comment]
This was fixed in #21040!
