### ISSUE TITLE
html.elements.dialog - <PUT TITLE HERE>

### ISSUE THREAD

**Issue by arturotena** [mdn/browser-compat-data#15228]
#### What information was incorrect, unhelpful, or incomplete?

iOS 15.4 is still in beta. It has not been released yet.

#### What did you expect to see?

A check mark on this feature only if the browser has been released.

#### Did you test this? If so, how?

I used the example in the web page.

<details>
<summary>MDN page report details</summary>

* Query: `html.elements.dialog`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog
* Report started: 2022-03-02T06:32:11.359Z

</details>

**Comment by queengooborg** [comment]
This will be resolved in https://github.com/mdn/yari/pull/5311!
