### ISSUE TITLE
css.properties.gap - gap seems to be unsupported in older browsers

### ISSUE THREAD

**Issue by robrwo** [mdn/browser-compat-data#15241]
#### What information was incorrect, unhelpful, or incomplete?

CSS grid gap property seems to be ignored in Chrome 65 and earlier, and Firefox 60 and earlier.

#### What did you expect to see?

The gap property would not be ignored.

#### Did you test this? If so, how?

Using BrowserStack with older browser versions, on Windows Firefox and Chrome.

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.gap`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/gap
* Report started: 2022-03-02T11:46:17.118Z

</details>

**Comment by Elchi3** [comment]
The compatibility table says support started in Chrome 84 and Firefox 63. 

You can see that when clicking on the check mark. But probably it is not obvious that the checkmark is clickable?

**Comment by robrwo** [comment]
Ok, then the format of the tables has changed.

**Comment by queengooborg** [comment]
Due to overwhelmingly popular demand, version numbers were brought back to the rendered tables!
