### ISSUE TITLE
api.CredentialsContainer.store - Credential Management isn't actually supported in many browsers

### ISSUE THREAD

**Issue by ThisIsMissEm** [mdn/browser-compat-data#15245]
#### What information was incorrect, unhelpful, or incomplete?

Firefox and Safari both do not have the API functioning, per https://caniuse.com/credential-management

Chrome fails to store credentials if you're using a third-party password manager (by the looks)

#### What did you expect to see?

The table's information was misleading, so I expected to see correct data..

#### Did you test this? If so, how?

https://caniuse.com/credential-management
https://whatwebcando.today/credentials.html

<details>
<summary>MDN page report details</summary>

* Query: `api.CredentialsContainer.store`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/CredentialsContainer/store
* Report started: 2022-03-03T00:21:30.218Z

</details>

**Comment by queengooborg** [comment]
CanIUse might not be accurate in this case -- https://mdn-bcd-collector.gooborg.com/tests/api/CredentialsContainer shows that the API is supported in all three browsers.  The last link, https://whatwebcando.today/credentials.html, seems to think that `navigator.credentials` isn't supported in any of the browsers and `window.OTPCredential` is only supported in Chrome, but I believe its tests may be broken.

> if you're using a third-party password manager

Most password managers perform polyfill-like transformations to the Credential Management API.  Unfortunately, it can affect compatibility and support.

---

I'm going to close this as the collector confirms that this is supported.  If this is inaccurate, please provide a basic test case and we'll take another look!
