### ISSUE TITLE
http.headers.Set-Cookie.SameSite - ff compatibility info is stale

### ISSUE THREAD

**Issue by zesty** [mdn/browser-compat-data#15246]
#### What information was incorrect, unhelpful, or incomplete?

Firefox samesite compatibility info is outdated as of ff96

https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/96

See http section

#### Did you test this? If so, how?

<details>
<summary>MDN page report details</summary>

* Query: `http.headers.Set-Cookie.SameSite`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite
* Report started: 2022-03-03T02:24:42.158Z

</details>

**Comment by queengooborg** [comment]
Looks like the release notes are incorrect; the linked bug was closed as WONTFIX.
