### ISSUE TITLE
Safari flex-basis instinct values - In experimental phase now

### ISSUE THREAD

**Issue by deviprsd** [mdn/browser-compat-data#15251]
#### What information was incorrect, unhelpful, or incomplete?
Safari data on support for flex-basis - min-content | max-content | fit-content

#### What did you expect to see?
To be experimental phase

#### Did you test this? If so, how?
https://developer.apple.com/safari/technology-preview/release-notes/

#### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?
https://trac.webkit.org/changeset/288113/webkit/

**Comment by queengooborg** [comment]
Fixed by #16586!
