### ISSUE TITLE
api.AmbientLightSensor - Incorrect browser compatibility table for chrome on android

### ISSUE THREAD

**Issue by anaestheticsapp** [mdn/browser-compat-data#15250]
#### What information was incorrect, unhelpful, or incomplete?
All features are currently behind a flag on Chrome Android.

#### Did you test this? If so, how?
Tested on Chrome on Android. Also see open bug
https://bugs.chromium.org/p/chromium/issues/detail?id=606766

<details>
<summary>MDN page report details</summary>

* Query: `api.AmbientLightSensor`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/AmbientLightSensor
* Report started: 2022-03-03T16:46:15.929Z

</details>

**Comment by lukewarlow** [comment]
The main feature entry itself is correctly marked as behind a flag.

So it would depend on the policy for whether flag data needs duplicating?

![image](https://user-images.githubusercontent.com/32498324/160936490-c7e1829d-5c67-44f1-9a58-06c2366e8f29.png)

**Comment by Elchi3** [comment]
Duplicate of https://github.com/mdn/browser-compat-data/issues/6509
