### ISSUE TITLE
html.elements.link.rel.preload - Incorrect compatability table

### ISSUE THREAD

**Issue by grace-snow** [mdn/browser-compat-data#15263]
#### What information was incorrect, unhelpful, or incomplete?
Safari listed as having no support for preload

#### What did you expect to see?
Safari has had support since version 11

#### Did you test this? If so, how?
Tested on Safari 14.1.2 with preloading styles and it worked fine eg 
`<link rel="preload" href="style.css" as="style">`

<details>
<summary>MDN page report details</summary>

* Query: `html.elements.link.rel.preload`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/preload
* Report started: 2022-03-04T16:02:55.562Z

</details>

**Comment by Chanki-Min** [comment]
Safari do not add cors header in @font-face rule except "woff" fonts.

so we should update table as above & add caption about font preloading to do not add crossorigin="" attribute for safari
https://bugs.webkit.org/show_bug.cgi?id=86817

**Comment by queengooborg** [comment]
This was fixed in #22658!
