### ISSUE TITLE
Schema for version_ fields

### ISSUE THREAD

**Issue by robatwilliams** [mdn/browser-compat-data#15273]
In my project es-compat, I need to compare the `version_added` field with a version from browserslist. Specifically it's for this issue https://github.com/robatwilliams/es-compat/pull/46

All that's currently documented in the docs/json schema is that it's a string, can be a [ranged version](https://github.com/mdn/browser-compat-data/blob/main/schemas/compat-data.schema.json#L46), Boolean, or null.

The compound `≤` character used for range versions means semver tools won't be sufficient for comparison, as they use `<=`.

What can we rely on? Dot-separated string, with an optional prefix range character?

**Comment by robatwilliams** [comment]
From what I can see in https://github.com/mdn/browser-compat-data/tree/main/browsers, it's dotted strings up to a depth of 3

**Comment by queengooborg** [comment]
Hey @robatwilliams, this is a great question and we'd be more than happy to answer it!

The value of `version_added` and `version_removed` may be any of the following:
- `true`, meaning "yes, we don't know when"
- `false`, meaning "no support" (or "not removed" if `version_removed`)
- `null` / `undefined`, meaning "we don't know" (or "not removed" if `version_removed`)
- a semantic version string of up to three parts (major.minor.patch, usually only one), meaning "added/removed exactly in X"
- a semver prefixed by `≤` (we refer to these as "ranged values"), meaning "added/removed in X and possibly earlier"

We selectively allow ranged values for older browsers that are challenging to test, such as traditional WebView Android and pre-Chromium Opera.

When comparing ranged values, we recommend the following:
- Ranged values as `version_added` become `0`
- Ranged values as `version_removed` become the version number (i.e. `≤37` becomes `37`)

**Comment by robatwilliams** [comment]
Thanks. The "up to three parts" bit was what I found missing.
