### ISSUE TITLE
javascript.builtins.Array.at - .at(0) causes a Type Error on safari

### ISSUE THREAD

**Issue by zhen0** [mdn/browser-compat-data#15284]
#### What information was incorrect, unhelpful, or incomplete?

Browser table says Array.at should work with safari but it causes an type error

<img width="801" alt="Screen Shot 2022-03-06 at 12 37 31 PM" src="https://user-images.githubusercontent.com/40272060/156935326-1a00f11b-cfb2-4e7e-ab8b-bb6bae2f1076.png">

#### What did you expect to see?

This is what I see in chrome and would expect in safari:

<img width="561" alt="Screen Shot 2022-03-06 at 12 38 12 PM" src="https://user-images.githubusercontent.com/40272060/156935309-0c04bc94-e9a7-417d-88f8-9c4f0578f36b.png">

#### Did you test this? If so, how?
Yes - see screenshots of trying it in the console of safari (Version 15.2 (16612.3.6.1.8, 16612)) and chrome (Version 99.0.4844.51 (Official Build) (x86_64))

<details>
<summary>MDN page report details</summary>

* Query: `javascript.builtins.Array.at`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/at
* Report started: 2022-03-06T17:46:05.198Z

</details>

**Comment by queengooborg** [comment]
This feature was added in Safari 15.4, so it makes sense that it wouldn't work in 15.2.  To view the version numbers, you will need to click on the checkbox.  (We're looking into making the info a lot clearer!)
