### ISSUE TITLE
svg.attributes.presentation.fill-opacity - No browser compatibility data for any browser

### ISSUE THREAD

**Issue by oddball263** [mdn/browser-compat-data#15289]
there is no browser compatibility data for any of the browsers - just a question mark.

<details>
<summary>MDN page report details</summary>

* Query: `svg.attributes.presentation.fill-opacity`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/fill-opacity
* Report started: 2022-03-06T22:21:29.764Z

</details>

**Comment by queengooborg** [comment]
We're working to remove all uncertainties from BCD.  If you have information to aid in filling out the tables, we encourage you to open a PR, or submit an issue containing the supporting documentation if you don't feel it's PR-ready.
