### ISSUE TITLE
html.elements.dialog - Dialog API not supported

### ISSUE THREAD

**Issue by magical-obama** [mdn/browser-compat-data#15295]
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:97.0) Gecko/20100101 Firefox/97.0

#### What did you expect to see?
The Alert box openend with "The <dialog> API is not supported by this browser"
#### Did you test this? If so, how?

<details>
<summary>MDN page report details</summary>

* Query: `html.elements.dialog`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog
* Report started: 2022-03-07T10:35:59.342Z

</details>

**Comment by lukewarlow** [comment]
You seem to be reporting this from Firefox 97 and the data says it's supported as of Firefox 98, so the data is correct.
