### ISSUE TITLE
css.properties.counter-set - FAILING

### ISSUE THREAD

**Issue by estelle** [mdn/browser-compat-data#15317]
BCD is failing under [Browser compatibility](https://developer.mozilla.org/en-US/docs/Web/CSS/counter-set#browser_compatibility) for  Web/CSS/counter-set and Web/CSS/counter-reset with the message:
Unfortunately, this table has encountered unhandled error and the content cannot be shown.

This is a fairly recent issue, as my local dev environment, which I have not updated recently, is not failing.

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.counter-set`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/counter-set
* Report started: 2022-03-09T22:55:00.035Z

</details>

**Comment by queengooborg** [comment]
I'm not experiencing this issue on my end on either page.  Perhaps you ran into the bug fixed by https://github.com/mdn/yari/pull/5529, and then potentially the caching issue Jean-Yves described during the OWD-MDN planning meeting?

**Comment by estelle** [comment]
yup. it fixed itself.
