### ISSUE TITLE
api.SpeechRecognition - Firefox support

### ISSUE THREAD

**Issue by terracota-p** [mdn/browser-compat-data#15313]
#### What information was incorrect, unhelpful, or incomplete?

Browser compatibility table says "firefox = no" for all parts of the API, but as per [wiki](https://wiki.mozilla.org/Web_Speech_API_-_Speech_Recognition#How_can_I_use_it.3F) it can be enabled and used.

#### What did you expect to see?

The discrepancy should be probably fixed.

<details>
<summary>MDN page report details</summary>

* Query: `api.SpeechRecognition`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition
* Report started: 2022-03-09T15:41:35.756Z

</details>

**Comment by MrBrain295** [comment]
It is only in Firefox Nightly.

**Comment by terracota-p** [comment]
Oh, so the feature is removed in other firefox builds. Ok.
