### ISSUE TITLE
http.headers.Content-Length - <PUT TITLE HERE>

### ISSUE THREAD

**Issue by DaniChpok** [mdn/browser-compat-data#15314]
#### Did you test this? If so, how?

<details>
<summary>MDN page report details</summary>

* Query: `http.headers.Content-Length`
* MDN URL: https://developer.mozilla.org/ru/docs/Web/HTTP/Headers/Content-Length
* Report started: 2022-03-09T17:10:10.808Z

</details>

**Comment by mnuvysddtin** [comment]
في الأربعاء، ٩ مارس ٢٠٢٢ ٨:١٣ م github-actions[bot] <
***@***.***> كتب:
