### ISSUE TITLE
css.properties.text-justify - 'inter-character' value disabled in Edge

### ISSUE THREAD

**Issue by turtelneck** [mdn/browser-compat-data#15322]
#### What information was incorrect, unhelpful, or incomplete? 

text-justify doesn't work as described in Edge, Version 99.0.1150.36 (Official build)

#### What did you expect to see?

The compatibility table says the 'inter-character' value works, but each of the text examples on this page looked identical in Edge.

#### Did you test this? If so, how?

I compared a large body of text in two windows of identical width, Firefox and Edge. A clear visual difference—it works in Firefox, doesn't in Edge.

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.text-justify`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/text-justify
* Report started: 2022-03-10T05:56:18.762Z

</details>

**Comment by RyannaArline** [comment]
Yo I don’t know how to do any of this why so complicated?

**Comment by queengooborg** [comment]
Fixed in #20057!
