### ISSUE TITLE
Issue with "WebKit CSS extensions": needs updating

### ISSUE THREAD

**Issue by nt1m** [mdn/browser-compat-data#15374]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/WebKit_Extensions

#### What information was incorrect, unhelpful, or incomplete?

Safari 15.4 and previous versions have unprefixed a couple of properties, see: https://webkit.org/blog/12445/new-webkit-features-in-safari-15-4/

https://webkit.org/css-status/ is a good reference.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/webkit_extensions`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/WebKit_Extensions
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/webkit_extensions/index.md
* Last commit: https://github.com/mdn/content/commit/008f3fb65925484cdb29e8bf0506697096cd0b6a
* Document last modified: 2022-02-01T11:36:33.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks @nt1m . You're right, but IMO it is better to deal with BCD first/separately.

So moving  _this issue_ across to BCD was the right thing to do.

That said, can you create a new issue for MDN and cross link it here. This new issue should be quite specific about the required actions on MDN - including the things you have noted in https://github.com/mdn/content/issues/13864#issuecomment-1067392027

**Comment by nt1m** [comment]
Done: https://github.com/mdn/content/issues/13879

**Comment by queengooborg** [comment]
It looks like we've pretty much taken care of all these features, so I'm going to close this issue.  If there's any still left to do, please feel free to open a new issue!
