### ISSUE TITLE
Media Query Ranges - `>` and `<=` type operators used within media queries

### ISSUE THREAD

**Issue by argyleink** [mdn/browser-compat-data#15391]
#### What information was incorrect, unhelpful, or incomplete?
I don't see media query ranges listed and couldn't find the data in the repo

#### What did you expect to see?
Firefox support since like 63

#### Did you test this? If so, how?
I didn't, been preprocessing it so it's only author time.

#### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?
https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries#syntax_improvements_in_level_4

**Comment by stof** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/@media#browser_compatibility has data for `Range syntax from Media Queries Level 4`

**Comment by queengooborg** [comment]
This feature's data was added to BCD before this issue was opened, as pointed out above.
