### ISSUE TITLE
css.properties.text-align - match-parent supported by new Safari 15.4

### ISSUE THREAD

**Issue by casaper** [mdn/browser-compat-data#15404]
Safari Desktop, 15.4

#### What information was incorrect, unhelpful, or incomplete?

Safari would not support `text-align: match-parent;`.

#### What did you expect to see?

Safari 15.4 supports `text-align: match-parent;` without vendor prefixes. 

#### Did you test this? If so, how?

I did not. I rely on the vendor claiming to:

[New WebKit Features in Safari 15.4 - Retiring WebKit prefixes](https://webkit.org/blog/12445/new-webkit-features-in-safari-15-4/#retiring-webkit-prefixes)   
[WebKit CSS Feature Status](https://webkit.org/css-status/#property-text-align)

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.text-align`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/text-align
* Report started: 2022-03-16T19:56:37.131Z

</details>

**Comment by lukewarlow** [comment]
Was addressed by https://github.com/mdn/browser-compat-data/pull/15372
