### ISSUE TITLE
Date: parse: ISO 8601 format `YYYY-MM-DD HH:mm:ss` - iOS Safari incompatibility

### ISSUE THREAD

**Issue by strarsis** [mdn/browser-compat-data#15401]
#### What information was incorrect, unhelpful, or incomplete?
iOS Safari is listed as supporting the ISO 8601 date format parsing feature.

#### What did you expect to see?
iOS Safari being listed as partially supporting the feature.
iOS Safari doesn't support the `YYYY-MM-DD HH:mm:ss` ISO 8601 format - although it is in the standard.
Parsing such a formatted date string will fail with `Invalid date format`.

#### Did you test this? If so, how?
Yes, on the latest iOS Safari.

#### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?
Comprehensive SO discussion, including workarounds:
https://stackoverflow.com/questions/4310953/invalid-date-in-safari

Edit: I made a mistake in this issue - I reported the ISO 8601 format with just the date as the causative format, 
but actually it is the ISO 8601 format with date and time.

**Comment by lukewarlow** [comment]
I may be misunderstanding so forgive me if I am but it seems to work fine in version 15.4 of macOS and iOS Safari for me?

![image](https://user-images.githubusercontent.com/32498324/160935088-b2d4e300-326d-44f6-b76a-b577dd816b9e.png)

Do you happen to have a Webkit bug link to hand?

**Comment by strarsis** [comment]
@lukewarlow: It doesn't work on iPad OS `15.3.2`, and also not on the latest iPad OS `15.4`.
So this appears to be an iPad OS specific issue, that was resolved on iOS, but not on iPad OS.

There are implications for this: The app runs fine on PC/Chrome, also on recent iOS (iPhone) - but _not_ on _iPad_ OS (iPad).
It crashed there and I had to use debugging (Inspect.dev that isn't free) to find out about this JavaScript error caused by this particular input date format.

**Comment by lukewarlow** [comment]
@strarsis I've just tested with the same code as above using Safari web inspector to debug Safari on my iPad from my mac, and once again it worked (iPadOS 15.4).

Do you have something like a jsfiddle that I can run to try and reproduce the issue?

**Comment by strarsis** [comment]
@lukewarlow: Sure! I prepare something that fails in my iPad, so you can try to reproduce this issue on your devices.

**Comment by strarsis** [comment]
@lukewarlow: https://playcode.io/879708/
You can see whether the date parsing worked or not in the console output pane.

It works in that test for me, too, by the way.
But I am very sure something doesn't work because I had to modify all those dates on the API side.
I look to find a test code that causes this issue.

**Comment by lukewarlow** [comment]
The test in that URL works as expected for me. Based on this I recommend closing this issue, working on a reproduction and reporting to WebKit bug tracker.

**Comment by strarsis** [comment]
@lukewarlow: Alright, after disabling the date handling in the affected API I found a date/date format that causes the issue (`2022-03-22 17:51:57`), even on the latest iPadOS, I adjusted the test accordingly:
https://playcode.io/879708/

**Comment by lukewarlow** [comment]
Okay I can confirm this does break on Safari (macOS aswell as iOS) and not on Firefox and Chrome.

**Comment by lukewarlow** [comment]
I would recommend filing a WebKit bug if there isn't one and then pasting a link to it here. And someone can add it in a note accordingly.

**Comment by lukewarlow** [comment]
Worth noting though that the standard does say there should be a T not a space. So it technically isn't wrong. But given 2 out of 3 engines work with it, I'd say it's an interop bug.

**Comment by strarsis** [comment]
@lukewarlow: That's a good idea! I will create a new issue and link to it.

**Comment by strarsis** [comment]
@lukewarlow: Yes! A note on MDN would be great because I use MDN for looking up compatibility, too (and Can I Use sometimes doesn't include some features from MDN yet).

**Comment by strarsis** [comment]
@lukewarlow: New relevant WebKit issue: https://bugs.webkit.org/show_bug.cgi?id=238626

**Comment by Josh-Cena** [comment]
If you don't use ISO 8601 strictly, then you would be completely on your own. This is mentioned in multiple places, such as https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse:

> Only the ISO 8601 format (`YYYY-MM-DDTHH:mm:ss.sssZ`) is explicitly specified to be supported. Other formats are implementation-defined and may not work across all browsers. A library can help if many different formats are to be accommodated.

Unfortunately we can't document all formats that each browser supports, so not sure if there's anything actionable here.

**Comment by Josh-Cena** [comment]
@queengooborg Anything else to note here, or should this be closed?

**Comment by lukewarlow** [comment]
The issue itself has been addressed inside of Safari and given it was never spec incompliant I think it makes sense to close this out with no action
 @Josh-Cena
