### ISSUE TITLE
css.properties.backdrop-filter - Chrome iOS backdrop-filter compatability issue

### ISSUE THREAD

**Issue by Khorne101** [mdn/browser-compat-data#15409]
Chrome 99 for iOS 15.3.1 
backdrop-filter and -webkit-backdrop-filter using the blur function does not work properly on Chrome for iOS while working perfectly fine on Safari and on Chrome on Windows 10. It does not do anything at all on Chrome for iOS

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.backdrop-filter`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/backdrop-filter
* Report started: 2022-03-17T15:45:53.052Z

</details>

**Comment by lukewarlow** [comment]
There's no compatibility data for Chrome for iOS within this project, so if there is in fact an issue it's not relevant to this project.

**Comment by lukewarlow** [comment]
Also fwiw on iOS 15.4 the blur demo works fine in Chrome on iOS
