### ISSUE TITLE
api.ServiceWorkerRegistration.navigationPreload - Wrong version number for Firefox

### ISSUE THREAD

**Issue by saschanaz** [mdn/browser-compat-data#15414]
#### What information was incorrect, unhelpful, or incomplete?

It's enabled on Firefox 99, not Firefox 44. 

#### What did you expect to see?

As such.

#### Did you test this? If so, how?

https://bugzilla.mozilla.org/show_bug.cgi?id=1754786

<details>
<summary>MDN page report details</summary>

* Query: `api.ServiceWorkerRegistration.navigationPreload`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration/navigationPreload
* Report started: 2022-03-17T22:21:59.563Z

</details>

**Comment by Elchi3** [comment]
This now says Firefox 99
