### ISSUE TITLE
api.Window.dialogArguments - <PUT TITLE HERE>

### ISSUE THREAD

**Issue by lisafabian19** [mdn/browser-compat-data#15413]
#### Did you test this? If so, how?

<details>
<summary>MDN page report details</summary>

* Query: `api.Window.dialogArguments`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/dialogArguments
* Report started: 2022-03-17T21:18:33.075Z

</details>

**Comment by lisafabian19** [comment]
open it and title the nestpower and make the IP a machine building number

**Comment by Catclaws12** [comment]
> 
> 
> 
> 
> #### What information was incorrect, unhelpful, or incomplete?
> 
> 
> 
> #### What did you expect to see?
> 
> 
> 
> #### Did you test this? If so, how?
> 
> 
> 
> 
> 
> 
> 
> <details>
> 
> <summary>MDN page report details</summary>
> 
> 
> 
> * Query: `api.Window.dialogArguments`
> 
> * MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/dialogArguments
> 
> * Report started: 2022-03-17T21:18:33.075Z
> 
> 
> 
> </details>

- [ ]
