### ISSUE TITLE
html.manifest - <PUT TITLE HERE>

### ISSUE THREAD

**Issue by Maja-GH** [mdn/browser-compat-data#15417]
#### Did you test this? If so, how?

<details>
<summary>MDN page report details</summary>

* Query: `html.manifest`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Manifest
* Report started: 2022-03-18T03:14:43.953Z

</details>

**Comment by mnuvysddtin** [comment]
0504241591

في الجمعة، ١٨ مارس ٢٠٢٢ ٦:١٥ ص github-actions[bot] ***@***.***>
كتب:
