### ISSUE TITLE
api.BroadcastChannel - <Safari 15.4 is officially released, no pre-release version>

### ISSUE THREAD

**Issue by anavalo** [mdn/browser-compat-data#15421]
#### What information was incorrect, unhelpful, or incomplete?
Safari 15.4 is officially released.

#### What did you expect to see?
Updated browser compatibility

#### Did you test this? If so, how?
I tested BroadcastChannel api in Safari 15.4 and it receives and send messages through the channel.
https://support.apple.com/en-us/HT213187
https://webkit.org/blog/12445/new-webkit-features-in-safari-15-4/

<details>
<summary>MDN page report details</summary>

* Query: `api.BroadcastChannel`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Broadcast_Channel_API
* Report started: 2022-03-18T07:34:01.216Z

</details>

**Comment by lukewarlow** [comment]
This is no longer an issue the data has been updated to reflect this.
