### ISSUE TITLE
html.elements.dialog - Eventlistener cannot detect KeyboardEvent(s) on dialog element

### ISSUE THREAD

**Issue by jpmbiz70** [mdn/browser-compat-data#15444]
OS = Windows 11 Pro
OS Build = 22572.201
Browser = Chrome Version 97.0.4692.99 (Official Build) (64-bit)
Browser = Firefox Version 97.0.1 (64-bit)

#### What information was incorrect, unhelpful, or incomplete?
Eventlistener for <dialog> element does not detect KeyboardEvent.

#### What did you expect to see?
I expected to see the ESC key being detected on 'keydown' listener.  This is not the case.

#### Did you test this? If so, how?
I tested this by attaching an event listener to the <dialog> element.  When the <dialog> element was open I was capturing 'keydown' events.  However, nothing is captured.  I test this on Chrome and FF.

The only Keyboard Events that are captured by the 'keydown' eventlistener is if input elements have focus.  If focus is anywhere else on the <dialog> element other than input element then no keyboard events are captured. 

```js
dialog.addEventListener('keydown', (event) => {
    console.log(event);
    console.log(event.keyCode);
    if (event.keyCode === 27) {
        event.preventDefault();
    } else {
        return true;
    }
})
```

<details>
<summary>MDN page report details</summary>

* Query: `html.elements.dialog`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog
* Report started: 2022-03-19T23:16:13.395Z

</details>

**Comment by queengooborg** [comment]
I tested this out on my end using the following:

```html
<dialog open>
	<p>Greetings, one and all!</p>
	<form method="dialog">
		<button>OK</button>
	</form>
</dialog>

<script>
	document.querySelector('dialog').addEventListener('keydown', (event) => {
		console.log(event);
		console.log(event.keyCode);
		if (event.keyCode === 27) {
			alert("Escape!");
			event.preventDefault();
		} else {
			return true;
		}
	})
</script>
```

However, I am getting the alert as expected, and the dialog is not closing.  It's possible this was a bug in the past, but has since been fixed.
