### ISSUE TITLE
api.MediaSession.setActionHandler - compatibility data for MediaSessionAction enum has not been provided

### ISSUE THREAD

**Issue by OnkarRuikar** [mdn/browser-compat-data#15461]
#### What information was incomplete?
The method [MediaSession.setActionHandler()](https://developer.mozilla.org/en-US/docs/Web/API/MediaSession/setActionHandler) uses an enum object [MediaSessionAction](https://w3c.github.io/mediasession/#enumdef-mediasessionaction) for parameter values.

For the method [MediaSession.setActionHandler()](https://developer.mozilla.org/en-US/docs/Web/API/MediaSession/setActionHandler):
Firefox doesn't support "togglemicrophone", "togglecamera", and "hangup"
> Uncaught TypeError: MediaSession.setActionHandler: 'togglecamera' (value of argument 1) is not a valid value for enumeration MediaSessionAction.

Chrome doesn't support: "skipad"
> Uncaught TypeError: Failed to execute 'setActionHandler' on 'MediaSession': The provided value 'skipad' is not a valid enum value of type MediaSessionAction.

Fix for issue #4557 -> #14071 got rid of the data from BCD. 

I can't find any place where this being captured on MDN BCD. On the page https://developer.mozilla.org/en-US/docs/Web/API/MediaSession/setActionHandler there is no compatibility info regarding this.

#### What did you expect to see?
On the page [setActionHandler](https://developer.mozilla.org/en-US/docs/Web/API/MediaSession/setActionHandler), compatibility data for each action available in the enum, 

#### Did you test this? If so, how?
Tried all the actions available in the enum on Chrome and Firefox on Windows 10.

<details>
<summary>MDN page report details</summary>

* Query: `api.MediaSession`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MediaSession
* Report started: 2022-03-21T12:28:07.915Z

</details>

**Comment by queengooborg** [comment]
Fixed by #18413!
