### ISSUE TITLE
css.properties.hyphens - German is supported in Chrome

### ISSUE THREAD

**Issue by FrederikG** [mdn/browser-compat-data#15470]
#### What information was incorrect, unhelpful, or incomplete?
Under [Browser compatibility](https://developer.mozilla.org/en-US/docs/Web/CSS/hyphens#browser_compatibility) is stated, that german is not supported in browser like Chrome. But I was surprised to find out, that german is now working great with this feature in Chrome 99. I didn't test other languages or other browsers, but the table seems to be out of date.

#### What did you expect to see?
German language in Chrome as supported.

#### Did you test this? If so, how?
We used `hyphens: auto` on our website and as native german speaker I can say it worked fine.

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.hyphens`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/hyphens
* Report started: 2022-03-22T13:24:39.042Z

</details>

**Comment by alexander-nitsche** [comment]
I can also confirm that automatic German hyphenation works in Chromium 111.0.5563.64 and Vivaldi 5.7.2921.63 on Debian Bullseye (latest stable version), for example see tile titles at https://www.dfb-akademie.de/.

**Comment by Arkkimaagi** [comment]
What operating system are you using? I'm seeing big difference in hyphenating Finnish on Windows and Macos Chromes (Macos Chrome does hyphenate Finnish, Windows not so much)

**Comment by FrederikG** [comment]
@Arkkimaagi We are only talking about hyphenating the **german** language, not other languages like finnish. At least I didn't test any other languages.

**Comment by queengooborg** [comment]
Closing this issue in favor of #18172, which is a duplicate and contains more information we can use to track down implementation.
