### ISSUE TITLE
css.properties.grid-template-columns.subgrid - subgrid is activated in Safari TP

### ISSUE THREAD

**Issue by HolgerJeromin** [mdn/browser-compat-data#15514]
#### What information was incorrect, unhelpful, or incomplete?

Safari TP enabled CSS Subgrid by default
https://webkit.org/blog/12522/release-notes-for-safari-technology-preview-142/

After a few minutes searching I still have no idea how to add an TP entry for that in the json files. 
So only creating this item

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.grid-template-columns.subgrid`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Subgrid
* Report started: 2022-03-25T11:34:02.310Z

</details>

**Comment by queengooborg** [comment]
Fixed in #17829!
