### ISSUE TITLE
css.types.image.gradient.linear-gradient - outdated (or confusing?) info about Firefox

### ISSUE THREAD

**Issue by php4fan** [mdn/browser-compat-data#15523]
#### What information was incorrect, unhelpful, or incomplete?

![image](https://user-images.githubusercontent.com/13969584/160208106-6b6639bd-06e7-4bdb-964a-ca9af50fcba9.png)

#### What did you expect to see?

Regarding Firefox, 

What I understand from that is: _currently, and starting from version 49, it is only supported with the -webkit prefix_.
If it is supposed to mean something else, then it's not expressed clearly.

Instead, it currently works with no prefix (tested on version 98). Not sure if it's a very recent addition and the documentation hasn't been updated.

#### Did you test this? If so, how?
https://jsfiddle.net/ykje6x7a/

<details>
<summary>MDN page report details</summary>

* Query: `css.types.image.gradient.linear-gradient`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/gradient/linear-gradient
* Report started: 2022-03-25T21:54:10.554Z

</details>

**Comment by queengooborg** [comment]
This was a rendering issue rather than a data issue, but we have since fixed this!

**Comment by php4fan** [comment]
It still says the same though:

![image](https://github.com/mdn/browser-compat-data/assets/13969584/23b21159-4514-49d9-abf4-f679a82e4a2a)

**Comment by queengooborg** [comment]
Notice that the table cell has changed and no longer says "49" with a prefix!
