### ISSUE TITLE
FileSystemFileHandle.createWritable - Shows as not supported in Safari

### ISSUE THREAD

**Issue by lukewarlow** [mdn/browser-compat-data#15536]
#### What information was incorrect, unhelpful, or incomplete?

FileSystemHandle.createWritable() doesn't show as supported in release Safari. I believe this could be an oversight when Safari 15.2 data was added but not sure.

#### What did you expect to see?

Probably that Safari and iOS Safari 15.2 added support.

#### Did you test this? If so, how?
No

#### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://developer.mozilla.org/en-US/docs/Web/API/FileSystemFileHandle/createWritable

**Comment by queengooborg** [comment]
This wasn't an oversight; the method is indeed [unsupported in Safari](https://github.com/WebKit/WebKit/blob/main/Source/WebCore/Modules/filesystemaccess/FileSystemFileHandle.idl).
