### ISSUE TITLE
css.properties.tab-size - Safari supports length

### ISSUE THREAD

**Issue by estelle** [mdn/browser-compat-data#15531]
#### What information was incorrect, unhelpful, or incomplete?
Says safari doesn't support `<length>` as a value for tab size

#### What did you expect to see?
it not work in safari.

#### Did you test this? If so, how?
Codepen sometimes replaces tabs with spaces, so if it's not working, double check that tabs weren't converted: https://codepen.io/estelle/pen/dyJvrEX (change the tab-size value, if you don't see a change, it was converted to spaces)

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.tab-size`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/tab-size
* Report started: 2022-03-27T01:54:40.441Z

</details>

**Comment by queengooborg** [comment]
Fixed in #18893!
