### ISSUE TITLE
api.DOMException - <TYPE_MISMATCH_ERR: DOM Exception 17: The type of an object was incompatible with the expected type of the parameter associated to the object.>

### ISSUE THREAD

**Issue by Tarunvarma9** [mdn/browser-compat-data#15550]
Keycloak-React app not working in Safari. Working fine on Chrome ,but giving black layout for safari.

**Comment by Tarunvarma9** [comment]
Keycloak-React app not working in Safari. Working fine on Chrome ,but giving black layout for safari.

**Comment by queengooborg** [comment]
This sounds like it's a problem with `Keycloak-React`; I'd open an issue there instead.
