### ISSUE TITLE
javascript.builtins.Intl.NumberFormat.NumberFormat - Missing compatibility table data for `options`

### ISSUE THREAD

**Issue by spagy** [mdn/browser-compat-data#15589]
#### What information was incorrect, unhelpful, or incomplete?
The MDN article mentions various options that can be set but the compatibility table includes information on only a few of the parameters. (e.g., `currencyDisplay` and `notation` are included but `numberingSystem` and `trailingZeroDisplay` are not.

#### What did you expect to see?
I'd expect to see all the options in the table, along with compatibility information.

<details>
<summary>MDN page report details</summary>

* Query: `javascript.builtins.Intl.NumberFormat.NumberFormat`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat
* Report started: 2022-03-30T12:06:48.974Z

</details>

**Comment by adjenks** [comment]
@spagy `options.trailingZeroDisplay` appears in the table now if it did not appear there before. It seems to have very mixed support.

@Josh-Cena What are options "without data"?
