### ISSUE TITLE
.at() not compatible on safari 15.3 below

### ISSUE THREAD

**Issue by judevs** [mdn/browser-compat-data#15592]
#### What information was incorrect, unhelpful, or incomplete?
Compatibility in Safari OS 15.3 
![image](https://user-images.githubusercontent.com/32464575/160888690-eeebbba9-1783-44a0-9072-4a541dff9eb2.png)

Also tested the MDN page for .at() and it does not work.
<img width="1402" alt="Screenshot 2022-03-31 at 12 53 07 AM" src="https://user-images.githubusercontent.com/32464575/160890125-87e5fa5c-7719-4b1a-87e7-bbad17f505bb.png">

#### What did you expect to see?
Expecting to see an extracted parsed number from a file name

#### Did you test this? If so, how?
Yes, It is working on google chrome 
![image](https://user-images.githubusercontent.com/32464575/160888962-431d7964-63f1-4d0b-aa84-deace709ce7d.png)
but in safari 15.3 it is not

<details>
<summary>MDN page report details</summary>

* Query: `javascript.builtins.Array.at`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/at
* Report started: 2022-03-30T16:47:45.922Z

</details>

**Comment by queengooborg** [comment]
This is consistent with what our data indicates, that support was added in Safari 15.4.
