### ISSUE TITLE
api.OffscreenCanvas - 2D context partially supported in Firefox despite table's claims

### ISSUE THREAD

**Issue by Merlin04** [mdn/browser-compat-data#15605]
#### What information was incorrect, unhelpful, or incomplete?
Currently, the browser compatibility data for `OffscreenCanvas` says that Firefox does not support the `2d` context. However, it seems to work fine for me (Firefox 98.0) when I enable the `gfx.offscreencanvas.enabled` flag.

#### What did you expect to see?
It should say "partial support" and include the version it was first implemented in.

#### Did you test this? If so, how?
![image](https://user-images.githubusercontent.com/11800751/161136222-aeae4419-1dd3-4d1d-b1d5-8bc374122a33.png)

<details>
<summary>MDN page report details</summary>

* Query: `api.OffscreenCanvas`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas
* Report started: 2022-03-31T19:24:33.097Z

</details>

**Comment by lukewarlow** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1746750 this bug seems to agree it at least partially works as of version 98

**Comment by queengooborg** [comment]
This has been fixed in #17880!
