### ISSUE TITLE
webextensions.api.browserAction - Multiple instance of the details.windowId parameter

### ISSUE THREAD

**Issue by fabricedesre** [mdn/browser-compat-data#15608]
#### What information was incorrect, unhelpful, or incomplete?
The "details.windowId parameter" entry in the table appears 10 times.

#### What did you expect to see?

One single instance.

#### Did you test this? If so, how?

Reading the page is enough :)

<details>
<summary>MDN page report details</summary>

* Query: `webextensions.api.browserAction`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Browser_support_for_JavaScript_APIs
* Report started: 2022-03-31T21:51:56.487Z

</details>

**Comment by queengooborg** [comment]
The entry appears multiple times because it refers to support for the parameter for each method.  MDN's rendering engine has been updated to make it clearer that it is a subfeature to the feature above it!
