### ISSUE TITLE
api.ClipboardItem.ClipboardItem promise in constructor partial support out of date

### ISSUE THREAD

**Issue by dwelle** [mdn/browser-compat-data#15637]
#### What information was incorrect, unhelpful, or incomplete?

Chromium supports promises for ClipboardItem objects since 98 (https://chromestatus.com/feature/5733949474078720#details)

(would have made a PR instead, but didn't have enough time to figure out how to handle the docs update)

<details>
<summary>MDN page report details</summary>

* Query: `api.ClipboardItem.ClipboardItem`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/ClipboardItem/ClipboardItem
* Report started: 2022-04-03T17:01:26.536Z

</details>

**Comment by queengooborg** [comment]
Fixed in #18571!
