### ISSUE TITLE
api.Element.requestFullscreen - Support Matrix update for Chrome on iOS

### ISSUE THREAD

**Issue by sisirkon** [mdn/browser-compat-data#15661]
#### What information was incorrect, unhelpful, or incomplete?
Currently there is no mention of Chrome iOS even for ipad on the matrix.

 The fullscreen api seems to work out of the box without specifically mentioning webkit on a div tag. 
Where as on chrome iOS webkitEnterFullScreen is the only thing that works and only on a video tag.

Validated the api on iOS 12 / Chrome 75 and iOS 15 / Chrome 96. 

Works fine on Chrome on Android and Windows.

#### What did you expect to see?
I would expect Chrome on iOS to behave the same way as Safari on iOS on an ipad.
If not then a separate one identifying the difference.

#### Did you test this? If so, how?
Validated it on the device version mentioned above.

As an alternative , tried this as well 
https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_element_requestfullscreen_exit

<details>
<summary>MDN page report details</summary>

* Query: `api.Element.requestFullscreen`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullScreen
* Report started: 2022-04-04T18:28:47.376Z

</details>

**Comment by queengooborg** [comment]
We don't track Chrome or other third-party browsers on iOS/iPadOS, as the differences between them are far too minimal.
