### ISSUE TITLE
Issue with "SVGGeometryElement.isPointInFill()": Not working in chrome

### ISSUE THREAD

**Issue by sherifsalah** [mdn/browser-compat-data#15662]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/SVGGeometryElement/isPointInFill

Failed to execute 'isPointInFill' on 'SVGGeometryElement': parameter 1 is not of type 'SVGPoint'.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/svggeometryelement/ispointinfill`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/SVGGeometryElement/isPointInFill
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/svggeometryelement/ispointinfill/index.md
* Last commit: https://github.com/mdn/content/commit/93ae23dec42bba9d71d6f1ed45668d8d26847e9c
* Document last modified: 2022-02-18T09:26:54.000Z

</details>

**Comment by sherifsalah** [comment]
I'm not sure where to report this bug.
Should it reported as a bug in chrome? is it supported in chrome as it is written in the mdn page or not?

**Comment by sideshowbarker** [comment]
> Should it reported as a bug in chrome?

Yes, if you have a minimal reproducible example (MRE) that demonstrates the claimed problem. https://stackoverflow.com/help/minimal-reproducible-example

> is it supported in chrome as it is written in the mdn page or not?

Without you providing a minimal reproducible example, it will be impossible for anybody to evaluate whether or not it’s supported. Certainly without an MRE, nobody else will be bothered to take the time to test it themselves.

**Comment by sherifsalah** [comment]
Here is a [REPL](https://svelte.dev/repl/efbceb942f074c1db5fed683af3ad491) of the same exact code in the mdn page, nothing's changed.
