### ISSUE TITLE
api.fetch - NodeJS compatibility

### ISSUE THREAD

**Issue by PedroLimposteur** [mdn/browser-compat-data#15676]
It may be useful to tell that fetch isn't available at all in NodeJS

<details>
<summary>MDN page report details</summary>

* Query: `api.fetch`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/fetch
* Report started: 2022-04-05T14:38:59.279Z

</details>

**Comment by SuperchupuDev** [comment]
Node.js 18 has added native support for fetch
https://nodejs.org/en/blog/announcements/v18-release-announce/

**Comment by queengooborg** [comment]
There was support behind flags in versions of NodeJS prior to v18, and fully supported in v18.  This has been added into BCD by #15272.
