### ISSUE TITLE
api.Element.touchstart_event - Safari doesn't support touchstart?

### ISSUE THREAD

**Issue by greggman** [mdn/browser-compat-data#15690]
#### What information was incorrect, unhelpful, or incomplete?

MDN, via this data?, claims [Safari doesn't support touchstart events](https://developer.mozilla.org/en-US/docs/Web/API/Element/touchstart_event)

#### What did you expect to see?

Safari does support touchstart events.

#### Did you test this? If so, how?

Safari invented touchstart events.

<details>
<summary>MDN page report details</summary>

* Query: `api.Element.touchstart_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/touchstart_event
* Report started: 2022-04-07T01:33:09.859Z

</details>

**Comment by greggman** [comment]
Nevermind. I guess that's supposed to be desktop Safari

**Comment by queengooborg** [comment]
That's correct, we treat the mobile counterparts for browsers as a "separate browser" in the tables, as feature compatibility can greatly vary between the two!
