### ISSUE TITLE
api.Element.innerHTML - <PUT TITLE HERE>

### ISSUE THREAD

**Issue by seif09** [mdn/browser-compat-data#15747]
#### Did you test this? If so, how?

<details>
<summary>MDN page report details</summary>

* Query: `api.Element.innerHTML`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/innerHTML
* Report started: 2022-04-10T08:43:00.365Z

</details>

**Comment by queengooborg** [comment]
Hi there, this sounds like a development problem.  Please note that we are not a help forum and cannot assist with website development; please refer to a site like StackOverflow for development assistance.
