### ISSUE TITLE
api.WorkerNavigator.connection - Still marked as supported on Android

### ISSUE THREAD

**Issue by saschanaz** [mdn/browser-compat-data#15742]
#### What information was incorrect, unhelpful, or incomplete?

#15363 didn't cover WorkerNavigator.

#### What did you expect to see?

It should.

#### Did you test this? If so, how?

https://searchfox.org/mozilla-central/rev/c0a97899404931861a4bbec21f55d3cd79b90bb8/dom/webidl/WorkerNavigator.webidl#20

BTW, the comment on `api.Navigator.connection` is also incorrect, it argues that it's enabled by default when it's not.

<details>
<summary>MDN page report details</summary>

* Query: `api.WorkerNavigator.connection`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WorkerNavigator/connection
* Report started: 2022-04-09T11:22:12.481Z

</details>

**Comment by Elchi3** [comment]
It now appears to also be marked as removed in Firefox Android.
