### ISSUE TITLE
api.Notification.icon - on macOS, the icon can be passed, but it will not be visible

### ISSUE THREAD

**Issue by mmzeeman** [mdn/browser-compat-data#15763]
#### What information was incorrect, unhelpful, or incomplete?

on macOS, the icon will not be visible.

#### What did you expect to see?

The icon

#### Did you test this? If so, how?

https://www.bennish.net/web-notifications.html

<details>
<summary>MDN page report details</summary>

* Query: `api.Notification.icon`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Notification/icon
* Report started: 2022-04-11T13:46:48.518Z

</details>

**Comment by lukewarlow** [comment]
![image](https://user-images.githubusercontent.com/32498324/164296073-1d0ed76c-d2be-4565-b44c-c54efdee7b9d.png)

Icon appears to work fine for me in Chrome? Which browser in particular did you test with?

**Comment by queengooborg** [comment]
The lack of support for `icon` had already been represented in BCD, and support was only just recently, so there's nothing actionable here.
