### ISSUE TITLE
javascript.classes.private_class_fields - Node.js compatibility with private class methods

### ISSUE THREAD

**Issue by ForeverACE** [mdn/browser-compat-data#15764]
Although the latest versions of Node.js (i.e. 17.9 or newer) support the ES2022 class features, previous versions do not support all features. The specific one that I encountered was private methods within a class. This feature is supported starting in version 14.19.1 but is NOT supported in earlier versions.

This was tested using Node.js version 12.20.1 which caused the error "_Unexpected taken '('_" where the method is defined. I looked up the compatibility on the official Node.js site and found it wasn't supported (along with some other features) until more recent versions.

<details>
<summary>MDN page report details</summary>

* Query: `javascript.classes.private_class_fields`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields
* Report started: 2022-04-11T15:05:47.596Z

</details>

**Comment by jmaicher** [comment]
Can confirm, we based a decision on the data and ran into the same problem. Node 12 does not support private class methods. According to compat data in [javascript.classes.private_class_methods](https://github.com/mdn/browser-compat-data/blob/main/javascript/classes.json#L291), support was only added in Node 14.6.0. A hint would be beneficial.

**Comment by queengooborg** [comment]
We have separate entries for fields (properties) and methods in BCD.  I've submitted a pull request to the MDN page so that includes compatibility tables for all features.
