### ISSUE TITLE
Atomics - missing data for android browsers

### ISSUE THREAD

**Issue by connorjclark** [mdn/browser-compat-data#15780]
#### What information was incorrect, unhelpful, or incomplete?

[atomics](https://caniuse.com/?search=atomics)

#### What did you expect to see?

support for android chrome, FF

#### Did you test this? If so, how?

Yes, I have a site that uses atomics that works in both latest FF and Chrome android

#### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

Mobile Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=923807#c16 (released [M87](https://chromiumdash.appspot.com/commit/85fcdf8c1d1610a5b5f28c65f783809e0355c0c7))

Mobile FF: unknown (but I know it works in latest android FF)

**Comment by Elchi3** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Atomics#browser_compatibility shows android support now.
