### ISSUE TITLE
css.properties.overflow-x - <update chrome version, apply overflow:auto;>

### ISSUE THREAD

**Issue by wooheeyun** [mdn/browser-compat-data#15795]
#### What did you expect to see?
I didn't want the overflow auto to apply. update chrome version.
#### Did you test this? If so, how?
chrome version update.

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.overflow-x`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-x
* Report started: 2022-04-13T09:30:50.182Z

</details>

**Comment by queengooborg** [comment]
I'm closing this issue because there's not enough actionable information.  Please note that this repository is specifically for the compatibility tables at the end, not development help or browser bug fixes.
