### ISSUE TITLE
javascript.builtins.Array.at - In IOS it is not defined

### ISSUE THREAD

**Issue by pini85** [mdn/browser-compat-data#15803]
IOS all browsers, Mac safari
#### What information was incorrect, unhelpful, or incomplete?
arr.at(-1) does not work. It throws an error that it is not a function
#### What did you expect to see?
expected to see the last index of the array
#### Did you test this? If so, how?
Tested it in chrome, firefox, safari

<details>
<summary>MDN page report details</summary>

* Query: `javascript.builtins.Array.at`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/at
* Report started: 2022-04-13T14:28:45.253Z

</details>

**Comment by queengooborg** [comment]
Are you using the latest version of iOS?  As our data indicates, support was added in iOS 15.4.

**Comment by lukewarlow** [comment]
Fwiw tested on desktop and mobile safari 15.4 and it works in both for me.

**Comment by queengooborg** [comment]
Closing because there has been no response.
