### ISSUE TITLE
webextensions.api.menus.OnClickData - srcUrl support in Firefox contradictory ?

### ISSUE THREAD

**Issue by StigNygaard** [mdn/browser-compat-data#15848]
#### What information was incorrect, unhelpful, or incomplete?

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/menus/OnClickData

Is it nonsense written in support-table when it comes to Firefox and support for srcUrl, or is it just me that don't understand it ?

So the red icon in table seems to say "not supported in 59-94", which immediately makes me wonder about versions prior to 59 and especially 95 and forward. So I open details in table for further information, which from green icon ( + text below) tells me there was full support from 48. Then there's (again) a red icon showing no support in 59-94. But text just below icon says "Removed in 94 and later", so it actually did work in versions prior to 94?

I haven't done testing to actually find out when it is or was supported. I just want to report support-table that makes no sense (or is so confusing that I just don't get it?)

![image](https://user-images.githubusercontent.com/5936108/163592052-593a9f36-d441-4cef-9c85-ad30207ce829.png)

<details>
<summary>MDN page report details</summary>

* Query: `webextensions.api.menus.OnClickData`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/menus/OnClickData
* Report started: 2022-04-15T15:27:58.645Z

</details>

**Comment by StigNygaard** [comment]
I see that the red cross has been replaced with a green checkmark. But the accompanying note still doesn't make sense?...
![image](https://user-images.githubusercontent.com/5936108/226123899-e31aa03a-b604-4ae7-8ac2-7210a48151d7.png)

**Comment by StigNygaard** [comment]
_Still doesn't_ make sense to me. Still looks like screenshot shown in my comment from March:
https://github.com/mdn/browser-compat-data/issues/15848#issuecomment-1474926652

Does it work in 94 and current versions?
Does it work in version 59-93?

At least I still find it confusing...

**Comment by lukewarlow** [comment]
The data on MDN doesn't update immediately so it will take some time to reflect any recent changes
