### ISSUE TITLE
api.ScreenOrientation.unlock - NotSupportedError Operation is not supported

### ISSUE THREAD

**Issue by m-nathani** [mdn/browser-compat-data#15854]
#### What information was incorrect, unhelpful, or incomplete?
`window.screen.orientation.unlock();` does not work in `firefox version 98.0 and above`
OS: `windows 10`.

#### What did you expect to see?
A/c to the https://developer.mozilla.org/en-US/docs/Web/API/ScreenOrientation/unlock#browser_compatibility it should support all the browser above `firefox version 43.0`

#### Did you test this? If so, how?
Check the error message of how to reproduce it..
https://sentry.io/share/issue/6ff319e6eb824b6f84024e2ceefe76b2/

<details>
<summary>MDN page report details</summary>

* Query: `api.ScreenOrientation.unlock`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/ScreenOrientation/unlock
* Report started: 2022-04-16T05:37:33.093Z

</details>

**Comment by m-nathani** [comment]
@queengooborg the issue was closed, however i cant see the fixed in PR.. 🤔

**Comment by queengooborg** [comment]
Do you mean that you don't see the fixes on MDN Web Docs yet, or that the merged PR doesn't resolve your issue?

If it's the first, I release a new version of BCD every Tuesday, which gets merged and released on MDN the following Thursday.

If it's the second, can you explain how the issue isn't resolved?

**Comment by m-nathani** [comment]
Hey thanks for responding..

Since the PR [15918](https://github.com/mdn/browser-compat-data/pull/15918)  was merged yesterday.. i believe it will be live by coming thursday.

Moreover, just to confirm its fix for the issue was that the unlock feature is supposed to work on latest firefox on windows as i am getting an error on unlock function. 

So the the below changes are basically going to update the docs only ?

```json
            "firefox": {
              "version_added": "43",
              "partial_implementation": true,
              "notes": "Always throws <code>NotSupportedError</code>."
            },
```

**Comment by queengooborg** [comment]
> Moreover, just to confirm its fix for the issue that the unlock feature is supposed to work in latest firefox on windows 10 ? . As i am getting an error on `unlock` function.

I think there might be some confusion on what this repository is about.  This is for the compatibility tables that appear on the bottom of MDN Web Docs pages, and partner sites like CanIUse.  In other words, this repository is for the _documentation_ on compatibility.  If you're looking to see this feature be fixed in Firefox itself, you'll want to file a bug on Mozilla's bug tracker here: https://bugzilla.mozilla.org/home

**Comment by m-nathani** [comment]
> > Moreover, just to confirm its fix for the issue that the unlock feature is supposed to work in latest firefox on windows 10 ? . As i am getting an error on `unlock` function.
> 
> I think there might be some confusion on what this repository is about. This is for the compatibility tables that appear on the bottom of MDN Web Docs pages, and partner sites like CanIUse. In other words, this repository is for the _documentation_ on compatibility. If you're looking to see this feature be fixed in Firefox itself, you'll want to file a bug on Mozilla's bug tracker here: https://bugzilla.mozilla.org/home

Yeah.. agreed, thanks for the link.. will it report their..
