### ISSUE TITLE
Share a vcard on android chrome

### ISSUE THREAD

**Issue by Romilton-Lima** [mdn/browser-compat-data#15875]
Hi! I'm trying to add a vcard (.vcf file), to a phone using the javascript web share api, but its not working on android chrome. It works just on ios. Both browsers supports the web share api. I did some examples where I shared images and texts (.txt files) and all the examples worked on chrome and safari in both operating systems, but when it comes to a vcard (.vcf file) it runs just on ios. I thing the issue might be with the vcard. Is there any idea about how to solve this problem?

**Comment by queengooborg** [comment]
It sounds like you're looking for development help, which we're unfortunately unable to provide.  This repository is specifically for the compatibility reports at the bottom of pages on MDN.  For development help, I'd recommend a dedicated help forum like StackOverflow.
