### ISSUE TITLE
css.types.basic-shape.path - supported on Chromium and Safari

### ISSUE THREAD

**Issue by NiedziolkaMichal** [mdn/browser-compat-data#15961]
#### What information was incorrect, unhelpful, or incomplete?
In [path() page](https://developer.mozilla.org/en-US/docs/Web/CSS/path#browser_compatibility), chromium browsers have info "Only supported on the offset-path property." which is incorrect. According to [clip-path table](https://developer.mozilla.org/en-US/docs/Web/CSS/clip-path) and operational interactive example in there, path() also works in clip-path property.

It also works correctly on Safari in clip-path property, but currently Compatibility Table says that it is not supported at all.

#### Did you test this? If so, how?

<details>
<summary>MDN page report details</summary>

* Query: `css.types.basic-shape.path`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/path
* Report started: 2022-04-22T12:08:56.370Z

</details>

**Comment by iFreilicht** [comment]
@Elchi3 This was also fixed by https://github.com/mdn/browser-compat-data/pull/20062 :)
