### ISSUE TITLE
css.properties.transform-box - most of values are not supported

### ISSUE THREAD

**Issue by NiedziolkaMichal** [mdn/browser-compat-data#15985]
#### What information was incorrect, unhelpful, or incomplete?
Current compatibility table states that this property is supported everywhere, but on IE. Actually only fill-box and view-box values are supported in SVG by all modern browsers, while there is poor support for other values. Please take a look at wpt data: [test1](https://wpt.fyi/results/css/css-transforms/parsing/transform-box-valid.html?label=experimental&label=master&aligned), [test2](https://wpt.fyi/results/css/css-transforms/parsing/transform-box-computed.html?label=master&label=experimental&aligned).

#### Did you test this? If so, how?

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.transform-box`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/transform-box
* Report started: 2022-04-23T11:28:53.926Z

</details>

**Comment by queengooborg** [comment]
The data has been updated in #21023 and #22499!
