### ISSUE TITLE
api.Window.scrollTo - <Failed to execute 'scrollTo' on 'Window': No function was found that matched the signature provided>

### ISSUE THREAD

**Issue by lijiajunxs** [mdn/browser-compat-data#16005]
I got this error Chrome Mobile WebView 55 on Android because of using 

window.scrollTo({
    top: 1000,
    behavior: "smooth"
});

I think you can tell us more about the error report or provide a polyfill to fix this

Failed to execute 'scrollTo' on 'Window': No function was found that matched the signature provided

**Comment by queengooborg** [comment]
This seems to be due to the fact that you're trying to use the `behavior` option before it was supported.  Our compatibility tables state that the `behavior` option was introduced in Chrome 61.
