### ISSUE TITLE
css.properties.justify-content - flex-end/end

### ISSUE THREAD

**Issue by leereichardt** [mdn/browser-compat-data#16049]
macOS Safari 10->15.4

#### What information was incorrect, unhelpful, or incomplete?
Flexbox `justify-content:end/flex-end`. `flex-end` is supported in Safari from at least version 10. In 15.4 the value of `end` is supported without the need for the `flex-` prefix

#### What did you expect to see?
I expected to see flex-end and end not working at all in Safari. However, flex-end did work and end did work in Safari 15.4

#### Did you test this? If so, how?
I tested on browsers in Browserstack and then tested Safari 15.4 on my own machine. [Jsfiddle example to test against](https://jsfiddle.net/leereichardt1/5z6t097r/8/)

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.justify-content`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/justify-content
* Report started: 2022-04-27T20:56:52.528Z

</details>

**Comment by lukewarlow** [comment]
Similar to #15915

**Comment by machal** [comment]
Values `start`, `end`, `flex-start`, `flex-end` for `align-items` and `align-self` works in Safari too.

Tested in Safari 15.4.

Test cases:

- https://codepen.io/machal/pen/poVVXJV?editors=1100
- https://codepen.io/machal/pen/wvjjLGq?editors=1100
