### ISSUE TITLE
api.HTMLElement.inert - Update browser support

### ISSUE THREAD

**Issue by nt1m** [mdn/browser-compat-data#16040]
See: https://webkit.org/blog/12578/non-interactive-elements-with-the-inert-attribute/

Source for Chrome: https://chromestatus.com/feature/5703266176335872
Source for FF: https://bugzilla.mozilla.org/show_bug.cgi?id=1764134 (only Nightly and late beta)

<details>
<summary>MDN page report details</summary>

* Query: `api.HTMLElement.inert`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/inert
* Report started: 2022-04-27T04:25:28.210Z

</details>

**Comment by rachelandrew** [comment]
I think this should be fixed by #16046
