### ISSUE TITLE
CSS - Web APIs: dead links

### ISSUE THREAD

**Issue by bukzor** [mdn/browser-compat-data#16070]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/CSS#browser_compatibility

### What specific section or headline is this issue about?

[Browser compatibility](https://developer.mozilla.org/en-US/docs/Web/API/CSS#browser_compatibility)

### What information was incorrect, unhelpful, or incomplete?

Links within the "Browser compatibility" table are all broken.
For example, clicking on "px" leads to:

https://developer.mozilla.org/en-US/docs/Web/API/CSS/px

Which reads:

Page not found
Sorry, the page /en-US/docs/Web/API/CSS/px could not be found.

[Go back to the home page](https://developer.mozilla.org/)

### What did you expect to see?

Details of the `px` css unit.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/css`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/CSS
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/css/index.md
* Last commit: https://github.com/mdn/content/commit/cdbf7145e631cf323d3bcade9a1d5ea208426801
* Document last modified: 2022-04-06T03:40:40.000Z

</details>

**Comment by queengooborg** [comment]
Fixed in #20063!
