### ISSUE TITLE
api.BeforeInstallPromptEvent - <SUMMARIZE THE PROBLEM>

### ISSUE THREAD

**Issue by ramkumawathis** [mdn/browser-compat-data#16095]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

window.addEventListener("beforeinstallprompt", function(e) {
  // log the platforms provided as options in an install prompt
  console.log(e.platforms); // e.g., ["web", "android", "windows"]
  e.userChoice.then(function(choiceResult) {
    console.log(choiceResult.outcome); // either "accepted" or "dismissed"
  }, handleError);
});

### What browsers does this problem apply to, if applicable?

- [ ] Chromium (Chrome, Edge, Opera, Samsung Internet)
- [X] Firefox
- [ ] Safari
- [ ] Node.js
- [ ] Deno

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/BeforeInstallPromptEvent

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.BeforeInstallPromptEvent`
* Report started: 2022-05-02T10:18:20.349Z

</details>

**Comment by queengooborg** [comment]
Closing because this is just a copy-paste of the example and provides no details as to what is potentially inaccurate in BCD.
