### ISSUE TITLE
html.elements.input.input-datetime-local - Not fully supported in Firefox

### ISSUE THREAD

**Issue by bockp** [mdn/browser-compat-data#16138]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Current Firefox version (99.0) does not have full support for datetime-local.

Instead they've implemented it as a copy of the Date field's functionality, ignoring the 'Time' part.

Firefox open Bug report: 

https://bugzilla.mozilla.org/show_bug.cgi?id=1726108

### What browsers does this problem apply to, if applicable?

Firefox

### What did you expect to see?

A datetime picker similar to the one in Chrome allowing me to fill out both date AND time:

![Screenshot from 2022-05-04 18-28-02](https://user-images.githubusercontent.com/10536344/166727397-6e42407f-90f6-4e0a-b1d4-2a90b506351b.png)

Instead I got a Date picker, but the field's formatting automatically inserts --:-- (for 24 Hour time for the system) or --:-- -- (for 12H time in the system) at the end of the valid date, rendering it invalid.

### Did you test this? If so, how?

After receiving a bug report that Firefox wouldn't allow saving of an entry due to a "please enter a valid date and time" browser error, I checked the behavior of the field in both Chrome and Firefox.

In Chrome it has a correct Datetime picker setup, while firefox only gives the user a Date picker.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://bugzilla.mozilla.org/show_bug.cgi?id=1726108

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `html.elements.input.input-datetime-local`
* Report started: 2022-05-04T15:55:57.052Z

</details>

**Comment by Shadow27374** [comment]
I really didn't think that Firefox is missing something so elementary... Incomprehensible.

**Comment by petasis** [comment]
It does.

**Comment by alxndr-w** [comment]
This is still the case and a wrong information on caniuse.com

**Comment by alxndr-w** [comment]
So what did we do wrong, is it the wrong place to inform anybody who's responsible for caniuse? @bockp @Elchi3

**Comment by rabbitmaid** [comment]
Not working

**Comment by rabbitmaid** [comment]
Using the developer firefox

**Comment by AWqxKAWERbXo** [comment]
@Elchi3 eine Antwort wäre echt nett.

**Comment by AWqxKAWERbXo** [comment]
I will never try to contribute to mdn again.
