### ISSUE TITLE
css.properties.background-clip - misleading information about Edge support for "text"

### ISSUE THREAD

**Issue by NoamAnisfeld** [mdn/browser-compat-data#16135]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

According to the displayed table, Edge fully supports the value "text" since version 15, with no prefixing required.

While out of context this may be considered a true statement, it is misleading because according to [CanIUse](https://caniuse.com/background-clip-text), this support was dropped once Edge moved to be Chromium-based in version 79, and currently it only supports the "text" value with the prefixed property.

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge, Opera, Samsung Internet)

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/background-clip

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.background-clip`
* Report started: 2022-05-03T20:30:36.433Z

</details>

**Comment by Keyacom** [comment]
I was just going to report the exact same problem.

I'd also like to point out that there's an issue reported to the Chromium bug tracker for this `background-clip` and `-webkit-background-clip` discrepancy: https://crbug.com/1339290
