### ISSUE TITLE
webextensions.manifest.manifest_version - Outdated info about chrome and edge

### ISSUE THREAD

**Issue by thomasingalls** [mdn/browser-compat-data#16147]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Currently, manifest v2 is no longer recommended for new extensions in Chrome and Edge browsers, and manifest v2 will cease to work next year. 

Manifest v3 is available for Chrome and Edge and is recommended by each of these browsers.

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

I expected to see that Chrome and Edge no longer recommend using manifest v2 and both support and recommend using manifest v3

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://github.com/mdn/browser-compat-data/issues/14658

### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/manifest_version

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `webextensions.manifest.manifest_version`
* Report started: 2022-05-05T22:34:01.019Z

</details>

**Comment by queengooborg** [comment]
CC @rebloor
