### ISSUE TITLE
AV1 codec strings

### ISSUE THREAD

**Issue by hamishwillee** [mdn/browser-compat-data#16173]
### What type of issue is this?

Browser bug (a bug with a feature that may impact site compatibility)

### What information was incorrect, unhelpful, or incomplete?

These methods can take a string that contains the mime type and optionally a codec parameter, and return whether the media type is supported: [`HTMLMediaElement.canPlayType()`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/canPlayType), [`MediaCapabilities.decodingInfo()`](https://developer.mozilla.org/en-US/docs/Web/API/MediaCapabilities/decodingInfo) and [`MediaSource.isTypeSupported()`](https://developer.mozilla.org/en-US/docs/Web/API/MediaSource/isTypeSupported). Info on the [codec string here](https://developer.mozilla.org/en-US/docs/Web/Media/Formats/codecs_parameter#av1). 

Previously FF would parse codecs for AVC/H264 and VP9 video formats properly and give a fairly accurate response on support. 
VP9. However for AV1 it would  treat all codec strings starting with "av01" as av1, ignoring all codec configuration options that could be passed. This might affect support for playback, and will in most systems affect hardware decoding support (returned by `MediaCapabilities.decodingInfo()` as the 'powerEfficient' boolean. 

1. FF101 supports the codecs  param for AV1 according to spec. I was wondering if we should add (for the above methods) a subfeature `codecs_param_av1" (and equivalent for AVC/H264 and VP9) to mark that this works now. 

2. Further, chromium supports parsing this with some off-spec behaviours:
   - (a) optional parameters in the codecs string that are supposed to be "all or none", but chromium allows any subset to be specified.
   - (b) unexpected characters in the string are supposed to be interpreted by evaluating the string up to the unexpected character. Chromium instead just errors. 

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://bugzilla.mozilla.org/show_bug.cgi?id=1757861#c9

https://github.com/mdn/content/issues/15463

### Do you have anything more you want to share?

I'm after advice on the best way to capture this, if at all. 

Item 1 is not IMO a great concern/need to capture. The methods that check for support are guaranteed to return false if it can't be supported, but `true` is always assumed to be a "probably" answer. So the new behaviour is better/correct but nothing will be broken before or after.

Item 2 though is off spec behaviour which might mean a string would work for FF but fail for Chromium and visa versa.

My thinking is we could for all of these methods add a subfeature "codec parameter av1" to indicate broad support and then for chromium have two notes - one  for each of the item "2" cases.

Of course I'd rather do nothing. Testing media support is a pain :-(

**Comment by hamishwillee** [comment]
@queengooborg Would appreciate your advice on this one. It is part of https://github.com/mdn/content/issues/15463

**Comment by queengooborg** [comment]
We have a long-open issue, #6971, that talks about A/V codecs and how we should represent them in BCD, but I don't think there's been any progress on it.  A subfeature would be the closest to what we have for other types of options though, so I'm leaning towards that?
