### ISSUE TITLE
api.Node.parentElement - states it is available in IE9, but it's already available in IE8

### ISSUE THREAD

**Issue by Jemt** [mdn/browser-compat-data#16189]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

The compat. table states that parentElement is available in Internet Explorer 9, while it is in fact available in IE 8.

### What browsers does this problem apply to, if applicable?

Internet Explorer/Legacy Edge (12-18)

### What did you expect to see?

The compat. table states that parentElement is available in Internet Explorer 9, while it is in fact available version 8.

### Did you test this? If so, how?

Yes, `document.body.firstChild.parentElement` returns `<body>` element

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Node/parentElement

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.Node.parentElement`
* Report started: 2022-05-09T19:31:16.188Z

</details>

**Comment by foolip** [comment]
@Jemt I've been able to confirm this by evaluating `document.body.parentElement` in IE8. Would you be up for sending a PR to fix this? This is where you'd update it:

https://github.com/mdn/browser-compat-data/blob/e197a4654cadc8691da3f6c4a514e8166ab8ce01/api/Node.json#L1346-L1349

**Comment by Jemt** [comment]
@foolip Better late than never - I have now created a pull request: https://github.com/mdn/browser-compat-data/pull/17076

**Comment by foolip** [comment]
Thanks for the fix @Jemt!
