### ISSUE TITLE
Linter: Make sure each child version is valid relative to its parent version

### ISSUE THREAD

**Issue by escattone** [mdn/browser-compat-data#1618]
The initial idea for this issue was from @Elchi3, and further refined through discussion. First, we made our understanding of the version explicit:

* **null** == We don't know if it's been implemented or not.
* **true** == It has been implemented but we don't know when.
* **false** == It has not been implemented.
* _version_ == We know it has been implemented starting with this version.

Next, we defined the details of the check we'd like to implement for child versions.

• If the parent version is **false**, then the child version must be **false**.
• If the parent version is **true**, then the child can be anything (no validation required).
• If the parent version is **null**, then we can at least assert that if the child is either **true** or a _version_, there is a mismatch between the parent and the child, although we don't know which is in error.
• If the parent is a _version_, the child version must be the same or a greater version (where greater is determined by the order of the releases in https://github.com/mdn/browser-compat-data/tree/master/browsers).

**Comment by JeremiePat** [comment]
Hi! I find those rules great but I slightly disagree on the last one.

If the parent is a _version_, the child could also be `true` as it is possible a child is supported but it's unknown when it started to match the parent. I think that in the case of a parent with a _version_, the only true error is a version lower than the parent, everything else is potentially valid and therefor impossible to tell from a linter perspective.
