### ISSUE TITLE
api.AudioContext.AudioContext - Firefox isn't working when AudioContext and getUserMedia have mismatching sample rates

### ISSUE THREAD

**Issue by tasnim-khan** [mdn/browser-compat-data#16213]
### What type of issue is this?

Browser bug (a bug with a feature that may impact site compatibility)

### What information was incorrect, unhelpful, or incomplete?

options.sampleRate parameter doesn't work correctly in firefox. See https://bugzilla.mozilla.org/show_bug.cgi?id=1674892 & https://bugzilla.mozilla.org/show_bug.cgi?id=1725336

### What browsers does this problem apply to, if applicable?

Firefox

### What did you expect to see?

The custom sample rate is correctly applied in other browsers: (tested with chrome & safari). The same should work here too.

### Did you test this? If so, how?

Run https://jsfiddle.net/mx9gonuv/8/ on firefox. You will see in console (after granting mic permissions):

"Error: NotSupportedError: AudioContext.createMediaStreamSource: Connecting AudioNodes from AudioContexts with different sample-rate is currently not supported"

On chrome, it just says: "run completed!"

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://bugzilla.mozilla.org/show_bug.cgi?id=1674892 & https://bugzilla.mozilla.org/show_bug.cgi?id=1725336

It seems the depedent bug https://bugzilla.mozilla.org/show_bug.cgi?id=1238038 is fixed but yet no timelines for this one.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/AudioContext

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.AudioContext.AudioContext`
* Report started: 2022-05-10T05:40:28.279Z

</details>

**Comment by dhdaines** [comment]
It sure would be nice if this were mentioned in MDN if FireFox doesn't intend to fix this bug.  Being stuck on 44.1kHz (with 128-sample buffers, no less, unless you use the eternally deprecated script processor node) is bad enough.

**Comment by WofWca** [comment]
This is about `createMediaStreamSource`, but #21496 only adds info for `createMediaElementSource`.
Reopen?

**Comment by thelamer** [comment]
Why is this closed, the user provided a very clear example to test and it still fails with version 126.0.1.

This works on Chrome and Safari and is documented in your own docs for setting a sample rate for the audio context. If everything you are going to connect it to is hard coded at 44100 then what is the point of having this setting at all?
