### ISSUE TITLE
Historical support data

### ISSUE THREAD

**Issue by kaycebasques** [mdn/browser-compat-data#1622]
I was browsing how caniuse documents support data. It’s interesting that it documents the support of every version of a browser.

https://github.com/Fyrd/caniuse/blob/master/features-json/cryptography.json

**Comment by Elchi3** [comment]
In our data `version_added` is supposed to give you the earliest version a browser supported a feature, so I think our data contains "historical support data" too?!

caniuse:
"12":"y",
"13":"y",
"14":"y",
"15":"y",
"16":"y",
"17":"y",
"18":"y"

MDN bcd:
version_added: "12"

Closing as I'm unsure what we should change.
