### ISSUE TITLE
api.Navigator.share - works only on mobile browsers

### ISSUE THREAD

**Issue by RahulReddy75** [mdn/browser-compat-data#16247]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

The documentation says the Share api works with desktop chrome > 93, but this is not the case. 
The share api only works with mobile browser.

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

I expected the the documentation to reflect the appropriate compatibility.

### Did you test this? If so, how?

Manually tested with desktop and mobile chrome browser. 

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.Navigator.share`
* Report started: 2022-05-11T14:35:35.641Z

</details>

**Comment by queengooborg** [comment]
Fixed by #18857!
