### ISSUE TITLE
the parameter where "beforeend","afterend" . in some editors when injecting are not supported .

### ISSUE THREAD

**Issue by HipsterSantos** [mdn/browser-compat-data#16259]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

VM4274:1 Uncaught DOMException: Failed to execute 'insertAdjacentHTML' on 'Element': The value provided ('bebeforeend') 

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

Acceptable values are listed here 

'beforeBegin', 'afterBegin', 'beforeEnd', or 'afterEnd'.

for just in case someone got into the same problem 
I found this when I was injecting on CKEditor5 

### Did you test this? If so, how?

I did , by using this website : https://ckeditor.com/ckeditor-5/demo/

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

this happens when injecting content and passing the value "beforend" and so on which is listed here:
https://developer.mozilla.org/en-US/docs/Web/API/Element/insertAdjacentHTML 

I highly recommend update page to new ones (camelCase)

https://ckeditor.com/ckeditor-5/demo/

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Element/insertAdjacentHTML

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.Element.insertAdjacentHTML`
* Report started: 2022-05-12T09:52:16.332Z

</details>

**Comment by HipsterSantos** [comment]
for testing https://ckeditor.com/ckeditor-5/demo/

**Comment by HipsterSantos** [comment]
Solution: 

The value provided ('bebeforeend') is not one of 'beforeBegin', 'afterBegin', 'beforeEnd', or 'afterEnd'

camelCase: 

'beforeBegin', 'afterBegin', 'beforeEnd', or 'afterEnd'

**Comment by queengooborg** [comment]
Looks like you've got a typo, you've got an extra "be" in the beginning of the value (`bebeforeend` vs. `beforeend`).
