### ISSUE TITLE
Issue with "box-sizing": features sorted improperly

### ISSUE THREAD

**Issue by Long-louis** [mdn/browser-compat-data#16254]
MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/CSS/box-sizing

#### What information was incorrect, unhelpful, or incomplete?

![image](https://user-images.githubusercontent.com/41790869/167833447-1afa9bf2-682c-432a-beda-014d90a7466c.png)

#### Specific section or headline?
https://developer.mozilla.org/zh-CN/docs/Web/CSS/box-sizing#browser_compatibility

It shows that firefox version 29 has full supported , but version 49 implemented with the vendor prefix: -webkit-

#### Did you test this? If so, how?

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/web/css/box-sizing`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/CSS/box-sizing
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/css/box-sizing/index.html
* Last commit: https://github.com/mdn/translated-content/commit/1bbb4d9683edd28fc947b17804e5b882184ecfcb
* Document last modified: 2021-03-15T17:56:01.000Z

</details>

**Comment by queengooborg** [comment]
This and similar issues should be fixed by https://github.com/mdn/browser-compat-data/pull/5352!

**Comment by yin1999** [comment]
Hi @queengooborg, this issue may been fixed. Should we close this?

![image](https://user-images.githubusercontent.com/15844309/185723267-d5657954-8125-4d23-b231-973054cfaef0.png)
