### ISSUE TITLE
http.headers.Set-Cookie.SameSite - <SUMMARIZE THE PROBLEM>

### ISSUE THREAD

**Issue by babarzafar** [mdn/browser-compat-data#16255]
### What type of issue is this?

Browser bug (a bug with a feature that may impact site compatibility)

### What information was incorrect, unhelpful, or incomplete?

when I do a transaction through a payment gateway in an iframe, then after returning to the merchant site, sessions are destroyed and users log out in magento2.

### What browsers does this problem apply to, if applicable?

Firefox

### What did you expect to see?

I want to get the proper transactions through the payment gateway and sessions should not destroy.

### Did you test this? If so, how?

yes i test it.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

it works on firefox version 58 but does not work greater than 58 version of firefox.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `http.headers.Set-Cookie.SameSite`
* Report started: 2022-05-12T04:33:50.470Z

</details>

**Comment by queengooborg** [comment]
This sounds like it's a problem with specific software, probably the "magneto2" you're talking about, rather than a browser bug.  I'd recommend raising this bug on magneto2's bug tracker.

**Comment by babarzafar** [comment]
> This sounds like it's a problem with specific software, probably the "magneto2" you're talking about, rather than a browser bug. I'd recommend raising this bug on magneto2's bug tracker.

Hello @queengooborg 
 it is not a Magento issue it is a browser issue because the same thing works on all browsers except firefox.

**Comment by queengooborg** [comment]
While it may be an issue occurring in one particular browser, that doesn't mean that it's a browser issue, as it could be that Magneto has some code that's attempting to mitigate an earlier Firefox incompatibility but now breaks, or something similar.  Whatever the problem may be, I don't think this is something that we'll be able to represent in BCD.

I'd be happy to take another look if you can provide a simple test (in other words, does not use external libraries) that shows a browser feature not working, and then we can update our compatibility tables accordingly.

**Comment by babarzafar** [comment]
@queengooborg 
Could you suggest to me one more thing?

Could I change the default setting of SameSite Lax to None in Magento2? is it possible to do that? 
if possible, kindly help me to solve this issue.

**Comment by queengooborg** [comment]
Again, you'll have to refer to Magneto2 for help with their product.  I found their GitHub repository here: https://github.com/magento/magento2

(Please note that we're not a development help forum and cannot help out with development issues.  This repository is for the compatibility tables on MDN web docs pages.)
