### ISSUE TITLE
javascript.builtins.SharedArrayBuffer - Unsupported in WebView

### ISSUE THREAD

**Issue by cafealpa** [mdn/browser-compat-data#16253]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

SharedArray Buffer does not appear to be supported in Android WebView version 101.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer#browser_compatibility

### What did you expect to see?

WebView Android > SharedArrayBuffer > Not Full support

### Did you test this? If so, how?

1. Making Sample Web view app(Enable webview debug)
2. Connect chrome inspect
3. Typing "new SharedArrayBuffer(1024)"

=> console result:
Uncaught ReferenceError: SharedArrayBuffer is not defined
at <anonymous>:1:1

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `javascript.builtins.SharedArrayBuffer`
* Report started: 2022-05-12T01:50:02.595Z

</details>

**Comment by Elchi3** [comment]
They are supported. https://chromestatus.com/feature/5171863141482496

Note that you need to have certain headers like COEP/CORP.
See the security requirements: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer#security_requirements
