### ISSUE TITLE
javascript.builtins.Intl.supportedValuesOf works in Chrome; documentation says it doesn't.

### ISSUE THREAD

**Issue by amandapouget** [mdn/browser-compat-data#16310]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Chrome is listed as "no" but trying it out in Chrome works.

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

That it didn't work. But it does.

### Did you test this? If so, how?

Using Chrome dev tools.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/supportedValuesOf

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `javascript.builtins.Intl.supportedValuesOf`
* Report started: 2022-05-16T19:18:03.133Z

</details>

**Comment by Shishouille** [comment]
I have also tried `Intl.supportedValuesOf` on Firefox v102.0.1 and Edge v103.0.1264.51 in the console. It works.
