### ISSUE TITLE
webextensions.manifest.manifest_version - Safari 15.4 supports manifest version 3

### ISSUE THREAD

**Issue by dheeraj-anumula** [mdn/browser-compat-data#16320]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Safari version 15.4 supports manifest version 3

### What browsers does this problem apply to, if applicable?

Safari

### What did you expect to see?

Version 3 is supported by Safari 15.4

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

Link to Safari 15.4 [release notes](https://developer.apple.com/documentation/safari-release-notes/safari-15_4-release-notes)

### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/manifest_version

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `webextensions.manifest.manifest_version`
* Report started: 2022-05-17T08:09:20.592Z

</details>

**Comment by xeenon** [comment]
This was fixed in PR #17407.

**Comment by xeenon** [comment]
@queengooborg can you close as fixed?
