### ISSUE TITLE
css.types.global_keywords.revert-layer - it's supported on Chromium-based browsers

### ISSUE THREAD

**Issue by xiaochengh** [mdn/browser-compat-data#16336]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

The current data says "no support" for Chromium-based browsers. It's actually supported since M99+.

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

It should say "supported" since M99+.

### Did you test this? If so, how?

See https://wpt.fyi/results/css/css-cascade?label=master&label=experimental&aligned&q=revert-layer

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://groups.google.com/a/chromium.org/g/blink-dev/c/ZCN2tBZ2cUY/m/MejMhebFCAAJ

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/revert-layer

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.types.global_keywords.revert-layer`
* Report started: 2022-05-18T00:19:45.432Z

</details>

**Comment by coderfin** [comment]
I did find one issue where `revert-layer` does not work when used as the fallback value in a CSS custom property (css variable). 

I created a bug report here: https://bugs.chromium.org/p/chromium/issues/detail?id=1345101

> CSS keyword 'revert-layer' does not work as expected when used as the fallback value to a CSS custom property (CSS variable).
> For example: "background-color: var(--not-set, revert-layer)" does not actually revert-layer in the latest chrome/chrome canary.

If you checkout this code sandbox [here](https://codesandbox.io/s/var--not-set-revert-layer-41b5r1?file=/index.html) or here (https://41b5r1.csb.app/) you can test this bug.  On Firefox, Safari, and iOS you will see a green square (OK).  On Chrome/Edge you will see a red square (FAIL).

It would be great to get some updated info on MDN and caniuse.

**Comment by woody-li** [comment]
> I created a bug report here: https://bugs.chromium.org/p/chromium/issues/detail?id=1345101

The bug is resolved.
