### ISSUE TITLE
W3 Payment Request API not available via dom.payments.request.enabled preference

### ISSUE THREAD

**Issue by DXXS** [mdn/browser-compat-data#16391]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Payment_Request_API

### What specific section or headline is this issue about?

Claim: "...feature is behind the dom.payments.request.enabled preference..."

### What information was incorrect, unhelpful, or incomplete?

Claims in browser compatibility / flag : "From version 55: this feature is behind thedom.payments.request.enabled preferences (needs to be set to true). To change preferences in Firefox, visit about:config"

### What did you expect to see?

If correct, IMO, window.PaymentRequest should no longer be null, allowing test of W3 'Payment Request API' in site javascript.

### Do you have any supporting links, references, or citations?

Sample code:
if (!window.PaymentRequest) {
    onFailure('This browser does not support web payments.');
    return;
  }

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/payment_request_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Payment_Request_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/payment_request_api/index.md
* Last commit: https://github.com/mdn/content/commit/0fcf43c69308021eff1e232dedb9e7d3b81dc82b
* Document last modified: 2022-05-20T12:13:51.000Z

</details>

**Comment by DXXS** [comment]
FWIW: this occurred occurred for me when using both FireFox ~v.92, & also after upgrading to v100.0.1

**Comment by queengooborg** [comment]
Sorry it took so long to get to this -- have you also set `dom.payments.request.supportedRegions` according to the data?

**Comment by queengooborg** [comment]
Since there hasn't been any response, I'm going to close this issue.  Happy to reopen it provided any new info that shows this isn't supported!

**Comment by DXXS** [comment]
Your setting variation doesn't appear in either the link I sent, or the API links referenced thereby : if you want people to believe that your code works, and continue to contribute, why don't you provide alternate working code instead of 1.3y delayed responses?
