### ISSUE TITLE
api.Window.prompt - <SUMMARIZE THE PROBLEM>

### ISSUE THREAD

**Issue by MagicMikeJ** [mdn/browser-compat-data#16402]
### What type of issue is this?

Missing specification link (no spec_url property)

### What information was incorrect, unhelpful, or incomplete?

Module isn't providing me with thorough information

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Window/prompt

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.Window.prompt`
* Report started: 2022-05-23T20:39:58.194Z

</details>

**Comment by queengooborg** [comment]
Closing as there's not enough information regarding the problem and the description doesn't match the selected option.  Please fill out the template and provide a thorough description of the issue so we may either assist you or point you in the right direction.
