### ISSUE TITLE
css.properties.list-style-type - disclosure-closed supported in Chromium

### ISSUE THREAD

**Issue by thomashertog** [mdn/browser-compat-data#16427]
### What type of issue is this?

Incorrect browser data

### What information was incorrect, unhelpful, or incomplete?

list-style-type: disclosure-closed is listed as unsupported in Chromium, but is working in Edge 101.

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### Did you test this? If so, how?

https://codepen.io/thomashertog/pen/wvyPoVK

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/list-style-type

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.list-style-type`
* Report started: 2022-05-25T12:51:09.730Z

</details>

**Comment by queengooborg** [comment]
Fixed in #18894!
