### ISSUE TITLE
http.headers.Large-Allocation - <SUMMARIZE THE PROBLEM>

### ISSUE THREAD

**Issue by pprakash21** [mdn/browser-compat-data#16428]
### What type of issue is this?

Browser bug (a bug with a feature that may impact site compatibility)

### What information was incorrect, unhelpful, or incomplete?

Large files are not uploaded through Mozilla Firefox Version 100.

### What did you expect to see?

Previously we are able to uploaded the large files before version 100.

### Did you test this? If so, how?

We have tested it. We got error.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Large-Allocation

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `http.headers.Large-Allocation`
* Report started: 2022-05-25T13:02:34.753Z

</details>

**Comment by queengooborg** [comment]
I'm not sure what the problem is here as our data confirms what you are stating already.  Are you looking for Firefox to add this feature back or something?  If so, we are not Firefox's bug tracker, and you will need to file a bug there instead.
