### ISSUE TITLE
Update Chrome support for `chrome.action.openPopup()`

### ISSUE THREAD

**Issue by stefanvd** [mdn/browser-compat-data#16442]
### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserAction/openPopup

### What information was incorrect, unhelpful, or incomplete?

The chrome.action.openPopup(); does work in Chrome Version 101.0.4951.64

### What did you expect to see?

The `chrome.action.openPopup()` work in the Chrome extension Manifest v3. Update the Browser compatibility.

### Do you have any supporting links, references, or citations?

Chromium bug report https://bugs.chromium.org/p/chromium/issues/detail?id=436489

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/api/browseraction/openpopup`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserAction/openPopup
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/api/browseraction/openpopup/index.md
* Last commit: https://github.com/mdn/content/commit/629960fa07e15f2354d75daf14f149d4942539ec
* Document last modified: 2021-10-26T21:28:18.000Z

</details>

**Comment by Rob--W** [comment]
The `action.openPopup` API is not generally available. It only works for extensions installed through the enterprise policy, or on dev builds (e.g. Canary).

Source: https://source.chromium.org/chromium/chromium/src/+/main:chrome/common/extensions/api/_api_features.json;l=71-77;drc=2cdd5c3248b3ba5b72f4fa072670fdaff972faa5

**Comment by rebloor** [comment]
@Rob--W when you know to look for it, the policy part is documented:
![image](https://github.com/mdn/browser-compat-data/assets/7352080/458a22b5-7b8b-4ddd-a20b-c3dbd3e2f2f6)
