### ISSUE TITLE
HTMLDialogElement - marked as experimental, but it already has browser support (?)

### ISSUE THREAD

**Issue by coolemur** [mdn/browser-compat-data#16454]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement

Here HTMLDialogElement is marked as Experimental.
Isn't this info misleading?

### What did you expect to see?

Shouldn't be marked as experimental.

### Did you test this? If so, how?

Already tried it in most of modern browsers (except IE) and this feature works without "experimental" flags.

Also, caniuse.com shows 82.98% support for this feature.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement

**Comment by queengooborg** [comment]
This must have been a content issue rather than a BCD issue, as I can't find a recent PR that changes the status.  Either way, it looks like this has been resolved already!
