### ISSUE TITLE
api.AbortSignal.timeout - Missing Chrome and Safari Support

### ISSUE THREAD

**Issue by HolgerJeromin** [mdn/browser-compat-data#16481]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

Chrome and Safari will support this API.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://bugs.webkit.org/show_bug.cgi?id=236039
https://chromestatus.com/feature/5768400507764736

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal/timeout

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.AbortSignal.timeout`
* Report started: 2022-05-31T07:05:40.332Z

</details>
cc @hamishwillee

**Comment by hamishwillee** [comment]
HOwdy @HolgerJeromin , awesome. 

As I understand it, the general rule is that "the community" adds what is of interest to them, and the BCD team review and help validate the data. I add things for Firefox as I work for MDN. I also do due diligence at the point I'm working an an API to make sure the BCD reflects the other main browsers. But I don't usually come along and update APIs for the fun of it,

Upshot, would you like to add this information?

**Comment by DerBasler** [comment]
https://developer.chrome.com/blog/new-in-chrome-103/#easier-timeouts-with-abortsignaltimeout

**Comment by HolgerJeromin** [comment]
The linked PR do not contain changes for safari as far as i have seen.

**Comment by foolip** [comment]
Oh wait, Safari update was in https://github.com/mdn/browser-compat-data/pull/16586.
