### ISSUE TITLE
webextensions.api.bookmarks.BookmarkTreeNode - <SUMMARIZE THE PROBLEM>

### ISSUE THREAD

**Issue by lycd0307** [mdn/browser-compat-data#16523]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

不正確

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

 好

### Did you test this? If so, how?

不是

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

能

### Do you have anything more you want to share?

沒有

### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/bookmarks/BookmarkTreeNode

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `webextensions.api.bookmarks.BookmarkTreeNode`
* Report started: 2022-06-02T18:35:53.525Z

</details>

**Comment by queengooborg** [comment]
This issue is closed because there is not enough actionable information.  Please describe what exactly is incorrect about the compatibility data.
