### ISSUE TITLE
api.Window.unhandledrejection_event - Information about event.preventDefault() is incorrect WRT Firefox

### ISSUE THREAD

**Issue by evnp** [mdn/browser-compat-data#16524]
### What type of issue is this?

Browser bug (a bug with a feature that may impact site compatibility)

### What information was incorrect, unhelpful, or incomplete?

This section is incorrect with regard to the Firefox browser, where errors are propogated and log to console regardless of whether `event.preventDefault()` is called in the handler or not. Despite this, Firefox is listed as having "full support" in the [Browser Compatibility](https://developer.mozilla.org/en-US/docs/Web/API/Window/unhandledrejection_event#browser_compatibility) section. This behavior is tracked in this open bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1642147

### What browsers does this problem apply to, if applicable?

Firefox

### What did you expect to see?

Firefox should be listed as having "partial support" until the bug is fixed. It would also be helpful to add a caveat to the [Preventing Default Handling](https://developer.mozilla.org/en-US/docs/Web/API/Window/unhandledrejection_event#preventing_default_handling) section that makes clear that this behavior doesn't work in Firefox for the time being (until the bug is fixed).

### Did you test this? If so, how?

Tested in Firefox 101.0 (64-bit) on OSX 12.3, M1 Macbook Pro, trying to suppress PromiseRejectionErrors originating from the CKEditor library.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://bugzilla.mozilla.org/show_bug.cgi?id=1642147
https://stackoverflow.com/a/62101468/11776945

### Do you have anything more you want to share?

Apart from all that, just want to say the new MDN is amazing, and overall the content is much appreciated.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Window/unhandledrejection_event

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.Window.unhandledrejection_event`
* Report started: 2022-06-02T18:51:55.265Z

</details>

**Comment by queengooborg** [comment]
This was fixed in #21464!
