### ISSUE TITLE
Linter for obsolete data: lint for "feature[s] unsupported in all releases in the past five years"

### ISSUE THREAD

**Issue by bershanskiy** [mdn/browser-compat-data#16547]
This is a low-priority issue, I'm just recording it here for posterity.

In #16429 we added a linter rule for data guideline called ["Removal of irrelevant features"](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines.md#removal-of-irrelevant-features). However, this linter currently checks only for the first two rules:
> - a feature was never implemented in any browser and the specification has been abandoned.
> - a feature was implemented and has since been removed from all browsers dating back two or more years ago.

The third rule is currently not validated:
> - a feature is unsupported in all releases in the past five years.

@queengooborg [suggested we should implement it](https://github.com/mdn/browser-compat-data/pull/16429#pullrequestreview-995798681):
> For a follow-up, I think we could also enforce the third condition for irrelevant features, where it can be removed if "a feature is unsupported in all releases in the past five years" so we can track IE-only features better. Something for the future though!

I'm not entirely sure I understand the guideline. From reading #6429, I see that it is just a special clause written specifically for Internet Explorer. But [this source](https://techcommunity.microsoft.com/t5/windows-it-pro-blog/bringing-internet-explorer-11-to-windows-server-2012-and-windows/ba-p/325297) seems to suggest that the last release of IE 11 happened as late as 2019 (which is only 3 years ago, less than 5). I'm not sure whether that counts as a release.

**Comment by queengooborg** [comment]
Since we're planning on removing IE from BCD altogether, I now think that we no longer have to add a linter for this!
