### ISSUE TITLE
shared data

### ISSUE THREAD

**Issue by patrickkettner** [mdn/browser-compat-data#1654]
In looking through some of the data that has been migrated over to bcd, I saw that certain topics (HTML elements, for example) are tracked in two places - e.g. under [Web/API/HTMLMeterElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMeterElement#Browser_compatibility) and [Web/HTML/Element/meter](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meter#Browser_compatibility). A lot of these actually even have slightly different data (the two I just linked have a number of discrepancies). It seems like having the same data in two places is begging for problems, would it be possible to map these in some way so there is a canonical source?

**Comment by Elchi3** [comment]
Thanks for pointing this out, Patrick! I think what you're describing is actually already discussed in issue https://github.com/mdn/browser-compat-data/issues/813. I'm closing this one.
