### ISSUE TITLE
Linter: add `exceptions` parameter

### ISSUE THREAD

**Issue by bershanskiy** [mdn/browser-compat-data#16567]
Mocha has a test hook called [`after()`](https://mochajs.org/#hooks) which runs after all tests in a given block were run. This kind of hook would be useful in the BCD linter. I propose to extend linting rules with one more (optional) hook callback called `after`.

The overall linter entry would look like this:
```
export default {
  name: 'Some linting',
  description: 'Test for some linting',
  scope: 'feature',
  check(logger, { data, path }) {
    // whtewer
  },
  after(logger) { // This is the new hook!
    // Cleanup/summary code goes here
  }
};
```

Use case: The test for obsolete entries has a list of [`exceptions`](https://github.com/mdn/browser-compat-data/blob/main/test/linter/test-obsolete.js#L14) that are expected to fail. The challenge is, that there is no easy way to ensure that once a feature is removed, its exception is also removed. This does not cause any false negatives (since the feature is completely gone in this case), but it would be nice to be able to clean up the linter when needed.

**Comment by queengooborg** [comment]
Thanks for the suggestion!  I personally feel that a linter shouldn't have anything that it would need to clean up, as variables that change should be isolated to the check() call.

For the use case, I'd like to propose a different option: an `ignore` or `exceptions` property, which contains a list of feature paths that should be skipped by the test.  From there, we could create a function that will check the feature tree and validate that there aren't any invalid exceptions after we've finished the linter runs.  What do you think?

**Comment by bershanskiy** [comment]
Yes, I agree, I can create a PR.
