### ISSUE TITLE
Linter: use async I/O for greater speed

### ISSUE THREAD

**Issue by bershanskiy** [mdn/browser-compat-data#16572]
#16437 introduced a new linter which unfortunately uses only synchronous I/O: `existsSync`, `existsSync` (multiple times on the same file!), `readFileSync`, `readdirSync`.
https://github.com/mdn/browser-compat-data/blob/2888cf5f5a5a35011acf99e9ae6f037fb6dd50c9/test/lint.js#L34
https://github.com/mdn/browser-compat-data/blob/2888cf5f5a5a35011acf99e9ae6f037fb6dd50c9/test/lint.js#L39
https://github.com/mdn/browser-compat-data/blob/2888cf5f5a5a35011acf99e9ae6f037fb6dd50c9/test/lint.js#L47
https://github.com/mdn/browser-compat-data/blob/2888cf5f5a5a35011acf99e9ae6f037fb6dd50c9/test/lint.js#L63
https://github.com/mdn/browser-compat-data/blob/2888cf5f5a5a35011acf99e9ae6f037fb6dd50c9/test/lint.js#L65

This makes linter very slow, on a decent laptop with an SSD `time npm run lint` produces:
```
real    0m8.531s
user    0m0.046s
sys     0m0.106s
```

[I like async I/O a lot](https://github.com/openwebdocs/project/issues/79#issuecomment-1138158330) and if you would be interested in reviewing a PR for async I/O, I can create one.

**Comment by queengooborg** [comment]
The linter has actually not been asynchronous before!  I'm totally down for making it asynchronous though to speed it up.
