### ISSUE TITLE
css.properties.column-gap - spec missing

### ISSUE THREAD

**Issue by estelle** [mdn/browser-compat-data#16587]
### What type of issue is this?

Missing specification link (no spec_url property)

### What information was incorrect, unhelpful, or incomplete?

Spec missing for all gutter pages:

https://developer.mozilla.org/en-US/docs/Web/CSS/column-gap#specifications
https://developer.mozilla.org/en-US/docs/Web/CSS/row-gap#specifications
https://developer.mozilla.org/en-US/docs/Web/CSS/gap#specifications

### Do you have anything more you want to share?

Specs are at:

https://www.w3.org/TR/css-align-3/#propdef-row-gap (both column and row)
https://www.w3.org/TR/css-align-3/#gap-shorthand

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/column-gap

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.column-gap`
* Report started: 2022-06-07T17:28:37.453Z

</details>

**Comment by queengooborg** [comment]
Fixed in #17130!
