### ISSUE TITLE
http.headers.X-XSS-Protection - Safari will not support for XSS auditor in version 15.4

### ISSUE THREAD

**Issue by Einstrasse** [mdn/browser-compat-data#16627]
### What type of issue is this?

Incorrect support data (Safari says it will be removed from 15.4 version, but mdn says it fully supports)

### What information was incorrect, unhelpful, or incomplete?

Browser compatibility information for X-XSS-Protection http response header about Safari need to be update.

Safari has been fully supporting X-XSS-Protection as long as xss auditor, but in Safari 15.4 the xss auditor is going to be vanished.
As X-XSS-Protection header controls behavior of xss auditor, removal of xss auditor means fading out X-XSS-Protection header compatibility.

### What browsers does this problem apply to, if applicable?

Safari

### What did you expect to see?

Update safari field in browser compatibility about X-XSS-Protection page.

Maybe format can be following:
Yes
 |
Removed in 15.4 and later

### Did you test this? If so, how?

Not yet, I have no apple's product. :-(

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

Reference: [https://webkit.org/blog/12445/new-webkit-features-in-safari-15-4/#security](https://webkit.org/blog/12445/new-webkit-features-in-safari-15-4/#security)

### MDN URL

https://developer.mozilla.org/ko/docs/Web/HTTP/Headers/X-XSS-Protection

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `http.headers.X-XSS-Protection`
* Report started: 2022-06-10T08:06:50.788Z

</details>

**Comment by PNW-Hacker** [comment]
https://developer.apple.com/documentation/safari-release-notes/safari-15_4-release-notes

Removed Features
Removed the XSS Auditor.

Adding comment regarding suggested fix:

This image shows that a comment was made for when the browser of a different vendor stopped supporting the XSS Auditor. 
![image](https://user-images.githubusercontent.com/75503104/204210462-eb0662f6-6367-4b8e-93a9-e30209c716b7.png)

As seen in the below screenshot, it still states full support, vs changing it to a red icon, and commenting that this was removed in version 15.4

![image](https://user-images.githubusercontent.com/75503104/204210951-c9f7ab0f-e34f-4bbe-b165-ea629a3e049f.png)
