### ISSUE TITLE
api.ServiceWorkerRegistration.pushManager - Browser compatibility data incorrect

### ISSUE THREAD

**Issue by leegeunhyeok** [mdn/browser-compat-data#16641]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Web Push API in macOS Safari browser.

In June 2022, Apple announced the Safari 16 will support web push notification in WWDC22.

### What browsers does this problem apply to, if applicable?

Safari

### What did you expect to see?

- Current: `Browser compatibility -> Desktop -> Safari: Not supported`
- Expect: `Browser compatibility -> Desktop -> Safari: 16`
  - pushManager: 16
  - getSubscription: 16
  - hasPermission: Not supported
  - permissionState: 16
  - register: Not supported
  - registrations: Not supported
  - subscribe: 16
  - supportedContentEncodings: Not supported
  - unregister: Not supported

### Did you test this? If so, how?

Demo: https://github.com/leegeunhyeok/web-push

- Environment
  - macOS 13 Ventura (13.0 Beta (22A5266r), Developer Beta 1)
  - Safari 16 (18614.1.14.1.15)
- To reproduce
  - Setup demo project (check README.md)
  - Start demo server & open web page
  - In Safari Web Inspector > Console
    - Information: `store.serviceWorkerRegistration` is ServiceWorkerRegistration object. (check this code: https://github.com/leegeunhyeok/web-push/blob/main/src/web/index.ts#L50)
    - `pushManager`
    ```js
    const pushManager = store.serviceWorkerRegistration.pushManager;
    console.log(pushManager);
    ``` 
    ![image](https://user-images.githubusercontent.com/26512984/173245009-cf72e526-3922-47e5-8ebe-02443a66963d.png)
    - `pushManager.subscribe`
      - In demo web page, click `Subscribe` button and allow notification permission.
      - and check subscription object data from `Status section`.
      - Code: https://github.com/leegeunhyeok/web-push/blob/main/src/web/index.ts#L106-L109
    - `pushManager.getPushSubscription()`
    ```js
    (async () => {
        const subscription = await pushManager.getSubscription();
        console.log(subscription);
    })();
    ```
    ![image](https://user-images.githubusercontent.com/26512984/173245053-dee9303a-383f-4011-beb8-e8372d4c68f6.png)
    - `pushManager.permissionState`
    ```js
    (async () => {
      const permission = await pushManager.permissionState();
      console.log(permission);
    })();
    ```
    ![image](https://user-images.githubusercontent.com/26512984/173245143-ffa2ea48-48ad-4e06-ab20-03abec582e77.png)
    - `pushManager.hasPermission`: No support
    - `pushManager.register`: No support
    - `pushManager.unregister`: No support
    - `pushManager.supportedContentEncodings`: No support

---

**Push notification send & receive test**

- Open demo page in Safari browser.
  - In login page, input some ID and click `Go` Button. (safari browser id)
  - Click `Subscribe` button and check subscription data in `Status` section.
- Open demo page in Other browser.
  - In login page, input another ID and click `Go` Button.
  - Input safari browser id into `Target User ID` field in `Send Push Notification` section.
  - Click `Send` button.
- Check Safari push notification from notification center.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

**WWDC22 Session**

- [Meet Web Push for Safari](https://developer.apple.com/videos/play/wwdc2022/10098)

**Developer Apple**

In **overview**, `In Safari 16 in macOS 13 or later, Safari supports web push — push notifications that use the cross-browser Push API, Notifications API, and Service Worker standards`
- Document URL: https://developer.apple.com/documentation/usernotifications/sending_web_push_notifications_in_safari_and_other_browsers

### Do you have anything more you want to share?

Demo:  https://github.com/leegeunhyeok/web-push

![Screen Shot 2022-06-13 at 1 58 49 AM](https://user-images.githubusercontent.com/26512984/173244540-510750a9-d606-4abc-b53e-adc769520be1.png)

- OS Version
- Browser Version
- Notification Sample

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration/pushManager

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.ServiceWorkerRegistration.pushManager`
* Report started: 2022-06-12T16:49:43.483Z

</details>

**Comment by gsnedders** [comment]
d2764a80a86360d49c6920400fb6a141ce9298c7 already added this; it's just not been deployed to MDN yet.

**Comment by leegeunhyeok** [comment]
@gsnedders oh, I missed it. thank you for checking! I'll close this issue.
