### ISSUE TITLE
html.elements.datalist - treated as normal text input on Firefox Android

### ISSUE THREAD

**Issue by jimdigriz** [mdn/browser-compat-data#16652]
### What type of issue is this?

Browser bug (a bug with a feature that may impact site compatibility)

### What information was incorrect, unhelpful, or incomplete?

Firefox (Mobile) 101.2.0 on Android does not support `<datalist>`, treats it as a regular input text field.

Works fine in Firefox (Desktop) 101 and Chrome.

### What browsers does this problem apply to, if applicable?

Firefox

### What did you expect to see?

Autocompletion for the datalist

### Did you test this? If so, how?

Built page using datalist, noticed Firefox did not work as expected. Also tested the MDN example at https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist and it has the same non-functional results

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `html.elements.datalist`
* Report started: 2022-06-13T07:56:32.027Z

</details>

**Comment by queengooborg** [comment]
Our notes already indicate that no dropdown appears in Firefox Android since v79.
