### ISSUE TITLE
Remove the cross for the case “No support”

### ISSUE THREAD

**Issue by Kdmeizk** [mdn/browser-compat-data#1665]
The cross increases the complexity of the information.
It is too much, the red square + “No” are largely enough.

**Comment by ExE-Boss** [comment]
You need to [open a bug on bugzilla](https://github.com/mozilla/kuma/issues/2941) and a pull request for [mozilla/kuma](https://github.com/mozilla/kuma), specifically [this file](https://github.com/mozilla/kuma/blob/master/kuma/static/styles/wiki-compat-tables.scss) and [the files that it imports](https://github.com/mozilla/kuma/tree/master/kuma/static/styles/components/compat-tables).

**Comment by Elchi3** [comment]
This was also filed here: https://bugzilla.mozilla.org/show_bug.cgi?id=1452083
The displaying is currently still implemented in https://github.com/mdn/kumascript/issues but will hopefully  worked on at https://github.com/mdn/browser-compat-toolkit.

Closing here for now.
