### ISSUE TITLE
Next steps with TypeScript

### ISSUE THREAD

**Issue by bershanskiy** [mdn/browser-compat-data#16668]
### As of 23 Jun:
- Add NodeJS 16 to the official CI matrix. #16670
- #16897
- Fully migrate JSDoc declarations to TypeScript
- Stricter TSConfig (possibly different TS Config for dev vs CI/prod)
- Go through use of any and introduce better types where appropriate (I have a few in mind)

-----------------------
### Old list for reference:
Known bugs:
 - Since #16593 was merged, BCD script `ts-node test/lint` fails on NodeJS 16
    Demo: [CI run on NodeJS 16](https://github.com/bershanskiy/browser-compat-data/runs/6885150433?check_suite_focus=true)
    This bug was identified by @queengooborg in #16593:
    >This PR depends on https://github.com/TypeStrong/ts-node/pull/1792 to fix a small bug in `ts-node`.

     Solutions:
     - Add NodeJS 16 to the official CI matrix to catch such problems in the future. #16670
     - Incorporate the fix written by @queengooborg into our `node_modules` while we wait for `ts-node` to accept the fix. There are multiple ways to do it. #16669

 - TS declarations, data schema, and JSDoc comments can go out of sync
   Solutions:
   - Add unit tests #16590
   - Fully migrate JSDoc declarations to TypeScript

Future improvements:
 - Stricter TSconfig options #16667
    - From my experience, it's better to have two different configs: one for development and one for CI/prod. For example, `noImplicitAny` can improve type coverage, but it is tough to program with it enabled. Similarly, `allowUnreachableCode` prevents dead code, but it is also inconvenient during rapid prototyping.
    - Go through use of `any` and introduce better types where appropriate (I have a few in mind)

**Comment by queengooborg** [comment]
I've merged #16669 to mitigate the NodeJS v16 issue while we wait for upstream to merge and release the fix!

**Comment by bershanskiy** [comment]
Closing this, since all relevant tasks were completed or abandoned.
