### ISSUE TITLE
api.Window.setImmediate - Works on edge

### ISSUE THREAD

**Issue by UtterDonkey** [mdn/browser-compat-data#16682]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

edge does in fact support setImmediate

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

that edge was supported

### Did you test this? If so, how?

In the console

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

no

### Do you have anything more you want to share?

no

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Window/setImmediate

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.Window.setImmediate`
* Report started: 2022-06-15T16:02:33.705Z

</details>

**Comment by queengooborg** [comment]
I cannot confirm that current versions of Edge support this property.  Could you clarify what version of Edge you are using?

**Comment by queengooborg** [comment]
Closing because there has been no response.
