### ISSUE TITLE
MDN has two distinct JSON stringification functions

### ISSUE THREAD

**Issue by bershanskiy** [mdn/browser-compat-data#16698]
MDN has two deterministic JSON stringification functions:
 - [`scripts/fix/property-order.ts`](https://github.com/mdn/browser-compat-data/blob/main/scripts/fix/property-order.ts)
 - `stringify` from `fast-json-stable-stringify` in [`scripts/release/build.ts`](https://github.com/mdn/browser-compat-data/blob/main/scripts/release/build.ts)

It appears that these two produce the exact same output, but I did not test this. I feel like we should pick one implementation and use it consistently. Thoughts?

**Comment by bershanskiy** [comment]
1. I was wrong: MDN data is not sorted alphabetically. There is a custom [propOrder](https://github.com/mdn/browser-compat-data/blob/main/scripts/fix/property-order.ts#L10) which changes location of `spec_url`.
2. `fast-json-stable-stringify` does not support pretty-printing with indentation and there are no plans to implement it: https://github.com/epoberezkin/fast-json-stable-stringify/issues/5

Given these two observations, I do not know if we should really change anything about MDN, since this discrepancy is intentional... On the other hand, we can rewrite fix scripts to (1) avoid so many `JSON.parse()`/`JSON.stringify()` and (2) use async I/O.

**Comment by queengooborg** [comment]
I'm going to close this as we have now expanded our property sorting to enforce a specific order of properties in internal docs in #21093.  `fast-json-stable-stringify` is used in the build stage to output a consistent minified JSON file for distribution.
