### ISSUE TITLE
Mixed use of `null` and `undefined`

### ISSUE THREAD

**Issue by bershanskiy** [mdn/browser-compat-data#16694]
I noticed that BCD scripts use `null` and `undefined` interchangeably. This is not a problem in JavaScript, since most of the time the consuming code actually just checks for the truthfulness of these values and both of these are falsy anyway. There is no real issue with this. However, TypeScript is more pedantic and does differentiate `null` from `undefined` so occasionally we have to write code like this:
```
const f = (a: number | null) => { /* do something */ }

let a: number | undefined;
// initialize a somewhere
f(a || null);
```

In my opinion, `f(a || null);` is rather bizarre and it would make sense to pick one of `undefined` or `null`. Do you have a preference?

This is low-priority stuff since no real harm comes from mixing `null` and `undefined`. It's more about readability.

**Comment by queengooborg** [comment]
Thanks for raising this issue!  I'd say that `null` would probably be the better option in most cases?

**Comment by bershanskiy** [comment]
Quoting [comment](https://github.com/mdn/browser-compat-data/pull/16724#issuecomment-1159598243) by @queengooborg:

> Now that I'm seeing these changes, I'm actually thinking that `undefined` would be better. Being able to call `walk()` with no arguments is quite convenient, and contextually, `undefined` makes more sense to me!
