### ISSUE TITLE
line-clamp - Missing altogether

### ISSUE THREAD

**Issue by estelle** [mdn/browser-compat-data#16706]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

CSS3 Overflow level 3: 
https://www.w3.org/TR/css-overflow-3/#propdef-line-clamp

All browsers that haven't been deplatformed (buh-bye IE) support a prefixed version that is not quite to the new spec. https://caniuse.com/css-line-clamp

There's a PR to add the page: https://github.com/mdn/content/pull/14094

Browser compact and spec are missing because the file doesn't exist. 

Not sure if you want to create "so support yet" data for [max-lines](https://www.w3.org/TR/css-overflow-3/#propdef-max-lines), [block-ellipsis](https://www.w3.org/TR/css-overflow-3/#propdef-block-ellipsis), and [continue](https://www.w3.org/TR/css-overflow-3/#propdef-continue)

**Comment by estelle** [comment]
There are also two -webkit-line-clamp` issues open. They can both be closed. I don't have access to this repo to do that.

**Comment by gsnedders** [comment]
Currently `line-clamp` is all-false, as `-webkit-line-clamp` is defined as a separate property: https://drafts.csswg.org/css-overflow/#propdef--webkit-line-clamp, though maybe we want to consider it a partially supported prefixed implemented?

**Comment by estelle** [comment]
Closing as line-clamp isn't supported yet.
