### ISSUE TITLE
api.HTMLElement.inert - inert seems to be supported in all stable browsers except Firefox

### ISSUE THREAD

**Issue by jespertheend** [mdn/browser-compat-data#16701]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

It says inert is only supported in stable Chrome, but either not supported or behind a flag in all other browsers.

### What did you expect to see?

It is supported in Edge and Safari (stable) as well. Only Firefox doesn't have support.

### Did you test this? If so, how?

I checked the results on wpft.fyi here: https://wpt.fyi/results/inert?label=master&label=stable&aligned

And I also tried https://wpt.live/inert/inert-inlines.html on:
- Chrome 102.0.5005.115 (Official Build) (x86_64)
- Edge 102.0.1245.41 (Official build) (x86_64)
- Safari 15.5 (17613.2.7.1.8)
- Firefox 101.0.1 (64-bit)

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/inert

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.HTMLElement.inert`
* Report started: 2022-06-16T11:49:57.675Z

</details>

**Comment by jespertheend** [comment]
Ah thanks, I didn't know that.

**Comment by queengooborg** [comment]
Looks like this was fixed in #16046 and #15921!
