### ISSUE TITLE
api.HTMLMediaElement.duration - video.duration returns sometimes Infinity

### ISSUE THREAD

**Issue by funesv** [mdn/browser-compat-data#16700]
### What type of issue is this?

Browser bug (a bug with a feature that may impact site compatibility)

### What information was incorrect, unhelpful, or incomplete?

Executing this function using a video as an argument, I expected to get video.duration and video.fps to make the calculation, but the results are sometimes for video.duration = Infinity and for video.fps = NaN
```
export const getNumberOfFrames = (video) => {
  console.log('video.duration: ', video.duration + ' fps: ' + video.fps);
  return Math.floor(video.duration * video.fps);
};
```

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

I expected to see the correct figures for the video.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/duration

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.HTMLMediaElement.duration`
* Report started: 2022-06-16T11:39:08.299Z

</details>

**Comment by queengooborg** [comment]
The [Value](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/duration#value) section describes the possible values and when they occur:

> A double-precision floating-point value indicating the duration of the media in seconds. If no media data is available, the value NaN is returned. If the element's media doesn't have a known duration—such as for live media streams—the value of duration is +Infinity.

**Comment by jayenashar** [comment]
i'm working on an app where chrome on android sometimes returns infinity and sometimes return the media duration - for the same media blob.  firefox on android always returns the media duration, both with the loadedmetadata event and the durationchange event.  chrome always returns infinity with the loadedmetadata event and sometimes with the durationchange event.
