### ISSUE TITLE
Edge Mobile should specify the platform

### ISSUE THREAD

**Issue by MarkLunney** [mdn/browser-compat-data#1671]
The new compatibility tables list "Edge Mobile" under Mobile browsers, but doesn't specify the platform.

Since Edge is now available on iOS and Android, the table should specify whether support data is relevant to these platforms, or if it only applies to Windows 10 mobile.

Most of the time I'd assume it wouldn't be relevant as Edge on Android and iOS use Blink and Webkit respectively ([cite](https://blogs.windows.com/msedgedev/2017/10/05/microsoft-edge-ios-android-developer/)), so I think it's important to make this distinction.

**Comment by ExE-Boss** [comment]
We could rename it to “Edge&nbsp;Windows&nbsp;Mobile”.

**Comment by vinyldarkscratch** [comment]
Now that Edge Mobile has been removed from BCD, the platform is no longer an issue.  Closing this issue!
