### ISSUE TITLE
css.properties.background-position-y - bottom + distance not working in Chrome

### ISSUE THREAD

**Issue by woif00** [mdn/browser-compat-data#16778]
### What type of issue is this?

Browser bug (a bug with a feature that may impact site compatibility)

### What information was incorrect, unhelpful, or incomplete?

It says background-position-y is fully suppported in webkit browsers, but background-position-y: bottom <some value> doesn't work in Chrome and Opera. This can also be seen just by clicking on the example bottom 32px on the mdn site for background-position-y.

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

The background image a certain distance from the bottom. Instead it was located on top because the browser couldn't process the value.

### Did you test this? If so, how?

I've tested it on my website, and it can also be seen in the examples on the mdn page.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://developer.mozilla.org/en-US/docs/Web/CSS/background-position-y

### Do you have anything more you want to share?

I could if it's necessary, but I think the problem is pretty clear cut.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/background-position-y

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.background-position-y`
* Report started: 2022-06-24T09:10:45.444Z

</details>

**Comment by queengooborg** [comment]
This is already represented in our data through the `two_value_syntax` subfeature.
