### ISSUE TITLE
javascript.builtins.WebAssembly - Missing Deno support

### ISSUE THREAD

**Issue by Phosra** [mdn/browser-compat-data#16796]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

Deno supports `WebAssembly.{Tag, Exception}`; they've been supported since V8 v9.2 in July 2021.

### What browsers does this problem apply to, if applicable?

Deno

### What did you expect to see?

The version that Deno supported these.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `javascript.builtins.WebAssembly`
* Report started: 2022-06-25T23:43:50.808Z

</details>

**Comment by Elchi3** [comment]
This got updated to say it is supported in Deno 1.15.
