### ISSUE TITLE
`autocomplete="one-time-code"` is listed as a valid attribute, while only Safari supports it.

### ISSUE THREAD

**Issue by jasikpark** [mdn/browser-compat-data#16792]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete

### What specific section or headline is this issue about?

`autocomplete="one-time-code"`

### What information was incorrect, unhelpful, or incomplete?

This doesn't mention that Firefox and Chrome ignore the value

### What did you expect to see?

I expected to see a warning that the value is widely unsupported at the moment and that browsers will fall back to remembering the input values, which is rarely, if ever wanted for a TOTP input.

### Do you have any supporting links, references, or citations?

https://caniuse.com/?search=one-time-code - caniuse doesn't even list this as an option.

### Do you have anything more you want to share?

Thanks for the help, and writing great docs!!

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/attributes/autocomplete`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/attributes/autocomplete/index.md
* Last commit: https://github.com/mdn/content/commit/d9eb6fc6e7e909f1f862e0d22bffeead5cc371eb
* Document last modified: 2022-05-10T02:54:01.000Z

</details>

**Comment by queengooborg** [comment]
We have added the value as a feature in BCD in #20101!
