### ISSUE TITLE
mathml.elements.math - <SUMMARIZE THE PROBLEM>

### ISSUE THREAD

**Issue by scientificware** [mdn/browser-compat-data#16798]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

Hi,

Missing information about mathml support in Web Browser.
OpenJFX WebView support mathml on Windows, Linux, macOS, (Android or iOS ?)
OpenJFX WebView is the OpenJFX WebKit implementation

Best regards

### What did you expect to see?

Add this information.

### Did you test this? If so, how?

Yes I tested it in desktop applications.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

OpenJFX Objects :

[WebEngine](https://openjfx.io/javadoc/13/javafx.web/javafx/scene/web/WebEngine.html)

[WebView](https://openjfx.io/javadoc/13/javafx.web/javafx/scene/web/WebView.html)

[HTMLEditor](https://openjfx.io/javadoc/13/javafx.web/javafx/scene/web/HTMLEditor.html)

[OpenJFX WebKit Status](https://bugs.openjdk.org/browse/JDK-8278980)

[OpenJFX Web Component Bug Tracking](https://bugs.openjdk.org/browse/JDK-8286633?jql=project%20in%20(JDK)%20AND%20component%20in%20(javafx)%20AND%20Subcomponent%20in%20(web))

### Do you have anything more you want to share?

Example of use in OpenJFX HTMLEditor

![](https://user-images.githubusercontent.com/19194678/44243707-d5f9fd80-a1d0-11e8-8870-a4232a7b644e.png)

### MDN URL

https://developer.mozilla.org/fr/docs/Web/MathML

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `mathml.elements.math`
* Report started: 2022-06-26T11:00:58.217Z

</details>

**Comment by queengooborg** [comment]
OpenJFX is a JavaFX runtime, in other words an external plugin to provide features the browser does not implement.  We do not track support for third-party plugins or polyfills.

**Comment by scientificware** [comment]
Hi @queengooborg,

I supposed it's a misunderstanding.

I'm just referencing the component WebView which is included in OpenJFX, not the whole OpenJFX library.

Exactly As your document references the Android WebView component.

I forgot to mention Mozilla GeckoView too.

I'm using three of them :
- OpenJFX WebView and Mozilla GeckoView supports mathml.
- Android WebView doesn't support mathml yet (waiting Igalia implementation)

Regards.

**Comment by queengooborg** [comment]
"WebView" is, unfortunately, a common name across various technologies, so I can see where the confusion may be.  Android has a WebView component that allows applications to embed a Chrome-based web display, which is what we document here.  Another is iOS' WebView, which is effectively the same, but using Safari instead (we don't document iOS' WebView separately due to fewer compatibility differences).  I'm not all that familiar with Java development, but I'm assuming it's the same case with OpenJFX's WebView.

> OpenJFX is not a plugin, it's a library

Ah, I assumed it was a plugin since it was a Java-related project, and Java can't run in browsers without a plugin (or so I thought, until I saw that JPro is a thing).  Either way, though, OpenJFX is out of the scope of BCD.  This project is about documenting what browsers have _built-in_ support for a feature, without the use of libraries, polyfills or other scripts.

**Comment by scientificware** [comment]
Really sorry @queengooborg,

> "WebView" is, unfortunately, a common name across various technologies ...
You are right but in our case, OpenJFX WebView is equivalent to iOS WebView and Android WebView.
It's a pure HTML5 Web Browser. Like iOS WebView, it implements WebKit and supports MathML natively.

Safari is a superset of iOS WebView which implements WekKit.
Chrome is a superset of WebView which implements a fork of WebKit.
In both case, in desktop applications, you can replace them with OpenJFX WebView if you want to embed a web display.
On mobile, OpenJFX WebView is an instance of iOS WebView or Android WebView (at this time).

> Ah, I assumed it was a plugin since it was a Java-related project, and Java can't run in browsers without a plugin (or so I thought, until I saw that JPro is a thing).
You don't need a browser to run OpenJFX WebView. It's a browser running natively over several platforms.
You are talking about XXth century Java world. Today you don't need Java installed to execute Java application. You can compile or package your application and execute it as a native application or distribute it over Google, Microsoft, Apple, Amazon, ... application stores. Of course you can find some vendors shipping solutions to run Java in a browser through Java bytecode translation to javascript or a over server but it's another story.

> Either way, though, OpenJFX is out of the scope of BCD. This project is about documenting what browsers have built-in support for a feature, without the use of libraries, polyfills or other scripts.
OpenJFX WebView doesn't use any library, polyfills or other scripts to support mathml, I insist it's a pure HTML5+MathML web browser. It offers a built-in MathML support.

I'm a developer and opensource contributor but I'm also also a mathematic teacher that's why I'm supporting, promoting and involved in all technologies which run MathML. Especially those for developers. The Covid-19 shows us how scientific communications are hard over the net, our discussion is showing that this gap will be hard to fill if we discard some technologies. I'm afraid, to not convice you, sorry  wasting your time.

Best regards.
