### ISSUE TITLE
[Schema] Define version number schemas for the different browsers

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#168]
We need to investigate validating version numbers for different browsers. Otherwise we might end up with inconsistencies like "53.0" and "53", or things like "5.3" which would make no sense for Firefox, for example.

**Comment by Elchi3** [comment]
Lets collect valid versions for UAs. I'm afraid we are not able to code this into the schema, but we need to put it somewhere as a reference for contributors and make it part of a review checklist.

## Firefox
I think we want to use Firefox versions, not Gecko versions. I'm not 100% sure if we want "55.0" or "55". Leaning towards "55" until I hear differently.
### Valid
"1" - "60" (and higher)
"1.5", "3.5", "3.6"
### Invalid
"1.7" (Fx 1)
"1.8" (Fx 1.5)
"1.8.1" (Fx 2)
"1.9" (Fx 3)
"1.9.1" (Fx 3.5)
"1.9.2" (Fx 3.6)
"2.0" (Fx 4)
"25.5", "5.3" etc.

## Chrome, Chrome for Android
Chromes wants to display just integers, no "57.0" just "57".
### Valid
"1" - "60" (and higher)
### Invalid
"5.0", "57.0"

## IE
Leaning towards integers for IE as well.
### Valid
"1", "1.5", "2", "3", "4", "5", "5.5", "6", "7", "8", "9", "10", "11"
### Invalid
"12", "13"
"6.0", "8.0"

**Comment by jpmedley** [comment]
You have the numbering correct for Chrome and Chrome for Android. That scheme also applies to Android Webview.

**Comment by a2sheppy** [comment]
I agree that Firefox should be "45" and not "45.0". We only add the decimal point once there's a non-zero digit somewhere after it.

**Comment by a2sheppy** [comment]
I also agree that the time has come to bail on Gecko version numbers. Nobody cares anymore about pre-4.0 Firefoxes. :)

**Comment by wbamberg** [comment]
Also Edge is the two-digit EdgeHTML version, according to https://github.com/mozilla/kumascript/pull/131#issuecomment-291992318. So "12", "13", "14", "15".

I agree that we should use "45" not "45.0" for Firefox, but might we sometimes want to include point releases in the compat data? They do exist after all.

**Comment by Elchi3** [comment]
Thanks for all the comments! I've updated the overview above. 
I think I need help with iOS Safari versions, and the rest could use a double check as well. We discussed that we want to add a validation script to this repository that makes sure versions are valid as per these rules. I'm going to use this issue to gather the version schemas for the first set of browsers which can then be used in such a validation script. If you have more comments on correct versions of browsers, let us know here!

**Comment by stephaniehobson** [comment]
Safari iOS is tied to the operating system. The operating system definitely has point releases. Not sure where to find a full list.

**Comment by a2sheppy** [comment]
Yes, when it’s a point release, we need to say so. So it would go “45”, then “45.0.1”, then “45.1”, then “46”, etc. Use the minimum number of decimal places possible, preferring zero decimal points when possible.


Eric Shepherd
Senior Technical Writer
Mozilla Developer Network <https://developer.mozilla.org/>
Blog: https://www.bitstampede.com/
Twitter: https://twitter.com/sheppy

**Comment by a2sheppy** [comment]
Wikipedia has a list of iOS releases. The format kind of stinks, but it's pretty thorough: https://en.wikipedia.org/wiki/IOS_version_history

**Comment by Elchi3** [comment]
The testing infrastructure and an initial set of browsers to validate the version data against landed with PR #439. The remaining work is tracked in issue https://github.com/mdn/browser-compat-data/issues/591.
