### ISSUE TITLE
Compatibility tables for EPUB/MOBI renderers?

### ISSUE THREAD

**Issue by Porges** [mdn/browser-compat-data#1680]
Has this been suggested in the past? They're all just rendering HTML/CSS in the end, and it would be very useful to see exactly what is/isn't supported by different devices. For example, the Amazon Kindle documentation is often inaccurate and claims not to support a lot of things that it actually does.

**Comment by Elchi3** [comment]
This hasn't been a goal in the last 2 years and unfortunately I think we (MDN) don't have the bandwidth to do this work on our own. If vendors of epub/mobi renderers would like to help us do this work, please contact me.
