### ISSUE TITLE
add `text-space-collapse` and `text-space-trim`

### ISSUE THREAD

**Issue by jensimmons** [mdn/browser-compat-data#16819]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

MDN BDC needs to add:
- `text-space-collapse` 
- `text-space-trim`

Both are CSS properties in [Text level 4](https://www.w3.org/TR/css-text-4/). Neither have been implemented in any browsers yet.

**Comment by queengooborg** [comment]
It still looks like neither of these properties are supported in any browser, so I'm going to close this issue.  (Our policy is to not include any features that are not implemented in any browsers.)
