### ISSUE TITLE
svg.attributes.presentation.stroke* - Missing compat data for all svg stroke attributes

### ISSUE THREAD

**Issue by danielhjacobs** [mdn/browser-compat-data#16818]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

I believe every browser probably supports most of these properties, but nothing about them was mentioned in the BCD. I was trying to design an SVG loading icon, and I saw suggested to use these properties, so I tried to check if they were supported, but no data is available for any of these:

* https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke#browser_compatibility
* https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-dasharray#browser_compatibility
* https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-dashoffset#browser_compatibility
* https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-linecap#browser_compatibility
* https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-linecap#browser_compatibility
* https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-linejoin#browser_compatibility
* https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-miterlimit#browser_compatibility
* https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-opacity#browser_compatibility
* https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-width#browser_compatibility

I assume all browsers support most of them because I looked up "safari stroke-dashoffset" and found this stackoverflow link: https://stackoverflow.com/questions/37246113/svg-stroke-dashoffset-not-working-on-safari, which is about a specific issue with negative values of stroke-dashoffset in Safari and implies positive values work.

### What did you expect to see?

Support data (Yes or No)

### Did you test this? If so, how?

In the two browsers I have access to, Chrome and Firefox, stroke, stroke-dashoffset, and stroke-dasharray work at the very least.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

According to https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/3/SVG_improvements, "fallback fill/stroke are now supported", which means stroke in general has been supported in Firefox since prior to version 3.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-dasharray

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `svg.attributes.presentation.stroke-dasharray`
* Report started: 2022-06-28T18:09:01.668Z

</details>

**Comment by danielhjacobs** [comment]
Affects most svg presentation attributes: full list found on https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/Presentation#browser_compatibility

**Comment by queengooborg** [comment]
We have a new goal to ensure accuracy for SVG data, so this will automatically be fixed as a part of that goal!
