### ISSUE TITLE
javascript.builtins.String.raw - Opera browser support correction

### ISSUE THREAD

**Issue by Amarok24** [mdn/browser-compat-data#16824]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Support table says that Opera (desktop) and Opera Android does not support String.raw method.
I've proven this to be incorrect information.

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

I expected String.raw not to work on Opera.

### Did you test this? If so, how?

Tested on a static HTML page using String.raw template literal in a script, and also in browser console in the following browsers:

- Opera 87.0.4390.58 on Windows 10
- Opera 88.0.4412.53 on Windows 10

I've also tested it on a static HTML page in Opera for Android, Opera version 69.3.3606. There a sample text using String.raw template literal was rendered correctly. If String.raw would not work then no text would be shown at all.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/raw

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `javascript.builtins.String.raw`
* Report started: 2022-06-29T09:47:08.555Z

</details>

**Comment by Elchi3** [comment]
This got fixed
