### ISSUE TITLE
Issue with "HTMLElement.style": IE11 fails unsetting style using null

### ISSUE THREAD

**Issue by vlakoff** [mdn/browser-compat-data#16828]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/style

#### What information was incorrect, unhelpful, or incomplete?
To remove a given style, it is usually advised to set its property to `null`, e.g. `element.style.color = null`

However, it seems to silently fail on IE11, which requires to assign an empty string, e.g. `element.style.color = ''`

(of course, other browsers support assigning an empty string too)

#### Specific section or headline?
Yes: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/style#setting_styles

#### What did you expect to see?
If confirmed, this IE11 caveat should be documented.

#### Did you test this? If so, how?
According to this answer on Stack Overlow, and its comments:
https://stackoverflow.com/questions/18691655/remove-style-on-element/33039348#33039348

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/htmlelement/style`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/style
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmlelement/style/index.md
* Last commit: https://github.com/mdn/content/commit/18df3e5ba2ea569e7d78dbb0f1c87fe3341ba46d
* Document last modified: 2022-01-24T00:42:02.000Z

</details>

**Comment by vlakoff** [comment]
I just successfully reproduced the issue, using Internet Explorer 11 and its "emulation mode" in the developer toolbar.

All offered IE versions have the issue: 5, 7, 8, 9, 10, and even 11. (there is no IE 6, not a typo)

Setting to `''` removes the style as expected, whereas setting to `null` doesn't remove it.
Also, I didn't get any JavaScript error in the console.

**Comment by queengooborg** [comment]
I'm closing this issue since the IE data was frozen a few releases back.

**Comment by vlakoff** [comment]
How about adding a short sentence, still?

Something like:

> A style declaration is reset by setting it to `null` or an empty string, e.g., `elt.style.color = null`. Note that Internet Explorer does nothing if `null` is used, it works only with an empty string.
