### ISSUE TITLE
add `hyphenate-limit-*` properties

### ISSUE THREAD

**Issue by jensimmons** [mdn/browser-compat-data#16820]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

MDN BDC needs to add:
- `hyphenate-limit-zone`
- `hyphenate-limit-chars`
- `hyphenate-limit-lines`
- `hyphenate-limit-last`

Both are CSS properties in [Text level 4](https://www.w3.org/TR/css-text-4/). Neither have been implemented in any browsers yet.

**Comment by Semigradsky** [comment]
`hyphenate-limit-chars` exists in mdn data: https://caniuse.com/mdn-css_properties_hyphenate-limit-chars

**Comment by queengooborg** [comment]
`hyphenate-limit-chars` was added in #18149.  All other properties will be added automatically by the `mdn-bcd-collector` once support is detected in a stable browser release.
