### ISSUE TITLE
api.HTMLCanvasElement.getContext - Isn’t working with my site

### ISSUE THREAD

**Issue by BestSpark687090** [mdn/browser-compat-data#16834]
### What type of issue is this?

Browser bug (a bug with a feature that may impact site compatibility)

### What information was incorrect, unhelpful, or incomplete?

The browser compatibility

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet), Firefox, Safari

### What did you expect to see?

A image on my screen

### Did you test this? If so, how?

Yes, I used Visual Studio Code’s Live Preview to test it and DevTools to see what is wrong.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

no

### Do you have anything more you want to share?

no

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/getContext

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.HTMLCanvasElement.getContext`
* Report started: 2022-06-30T19:32:43.736Z

</details>

**Comment by queengooborg** [comment]
This sounds like a development issue, rather than a browser compatibility issue.  Please note that we cannot provide help for development issues, and we recommend asking on help forums like StackOverflow instead.
