### ISSUE TITLE
CSS order propert - claims Firefox requires a prefix

### ISSUE THREAD

**Issue by fantasai** [mdn/browser-compat-data#16833]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

MDN claims that Firefox requires a -webkit- prefix, but this in fact untrue.

### What browsers does this problem apply to, if applicable?

Firefox

### What did you expect to see?

Firefox support without conditions, because it has full support for the standard

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://developer.mozilla.org/en-US/docs/Web/CSS/order

### Do you have anything more you want to share?

Firefox *added* a -webkit- prefix in addition to the standard syntax in order to support legacy content, but much later than it shipped the standard syntax. MDN should either find out how to represent that the unprefixed syntax is supported even if a prefix is added later OR just ignore the fact that a -webkit- prefix is supported, because honestly, we don't want people to use -webkit- prefixes in Firefox, they're there for compat only and it would probably be best if devs didn't even know it was supported and were thereby encouraged to use standard syntax.

**Comment by gsnedders** [comment]
This needs to be moved to the https://github.com/mdn/yari repo, as this is a problem with rendering the BCD data.

**Comment by queengooborg** [comment]
This will be fixed in https://github.com/mdn/yari/pull/6811!
