### ISSUE TITLE
How can I get the release date and engine version of Safari browsers?

### ISSUE THREAD

**Issue by lucalves** [mdn/browser-compat-data#16861]
Hello everybody!

I usually make contributions to this repository. Mainly in browser data.

However, I would like to know how to know the engine version and release date of Safari browser versions.

For the future, also be able to contribute keeping them updated.

Could anyone help? 🙂👋

**Comment by queengooborg** [comment]
This is a great question, thank you for asking!

There's a document on Apple's website, https://support.apple.com/en-us/HT201222, that documents the release dates for each Safari version.  The engine versions, I have been grabbing from Safari itself, but a user agent database like https://developers.whatismybrowser.com/useragents/explore/ should also help with that?

**Comment by lucalves** [comment]
> This is a great question, thank you for asking!
> 
> There's a document on Apple's website, https://support.apple.com/en-us/HT201222, that documents the release dates for each Safari version. The engine versions, I have been grabbing from Safari itself, but a user agent database like https://developers.whatismybrowser.com/useragents/explore/ should also help with that?

Yesss!

Solved my question, thanks!
