### ISSUE TITLE
javascript.builtins.WebAssembly.Exception - Chromium is spec incompliant regarding `stack`

### ISSUE THREAD

**Issue by ghost** [mdn/browser-compat-data#16874]
### What type of issue is this?

Browser bug (a bug with a feature that may impact site compatibility)

### What information was incorrect, unhelpful, or incomplete?

See https://github.com/mdn/content/issues/17660#issue-1284804367

Chromium currently attaches a stack trace, irrespective of the `traceStack` parameter.
There should be an implementation note about this.

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/Exception

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `javascript.builtins.WebAssembly.Exception`
* Report started: 2022-07-08T01:51:31.594Z

</details>

**Comment by queengooborg** [comment]
I cannot confirm this behavior.  Without specifying `traceStack`, no `stack` member is added to the instance:

```js
var instance1 = new WebAssembly.Exception(
  new WebAssembly.Tag({parameters: ["i32", "i64"]}),
  ["i32", BigInt(64)]
);
instance1.stack; // "undefined"

var instance2 = new WebAssembly.Exception(
  new WebAssembly.Tag({parameters: ["i32", "i64"]}),
  ["i32", BigInt(64)],
  {traceStack: true}
);
instance2.stack; // "Error\n    at <anonymous>:1:16"
```
