### ISSUE TITLE
Feature-Policy - No longer supported features in Chromium

### ISSUE THREAD

**Issue by Simbiat** [mdn/browser-compat-data#16888]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

There are a bunch of Feature-Policy policies, which are marked as supported by Chromium browsers, but currently seem to trigger a warning in Chromium browsers (Edge 103 and Chrome 103, at least):
![image](https://user-images.githubusercontent.com/6022665/178107077-b1acd481-f7f7-4e47-98bf-2b9cd45bc34d.png)
Can be live tested on https://simbiat.ru

I do not mind trying to PR a fix for this, but I was not able to find any confirmation for these getting deprecated, so not sure if this is enough evidence, especially, since I do not know exact version, when they were removed.

Similar thing for Permissions-Policy, but the list is slightly different:
![image](https://user-images.githubusercontent.com/6022665/178107455-ce40b75f-85f4-4124-a2f8-50bf5a01f5fc.png)

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

Respective policies should be marked as not supported (perhaps deprecated?).

### Did you test this? If so, how?

Tested in Edge 103 and Chrome 103. Can be live-tested (at least for now) on https://simbiat.ru

**Comment by caugner** [comment]
The Permissions-Policy (prev Feature-Policy) data was cleaned up by https://github.com/mdn/browser-compat-data/pull/23470.

Looking at https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Permissions-Policy#browser_compatibility, the features mentioned in the warnings are either no longer in the table (because no browser supports them) or not marked as supported by Chrome.

So it looks like this issue has been resolved. Let me know if this is not the case.

**Comment by Simbiat** [comment]
Most of them were cleaned-up, yes, but technically `ambient-light-sensor`, `document-domain` and `speaker-selection` are still in the spec and are supported by Chrome through flags, even though they are experimental. If warning for them will say that they are experimental - that's fine, but current text does not fit the reality, IMHO.

**Comment by caugner** [comment]
Thank you for the quick response.

The BCD data for [ambient-light-sensor](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Permissions-Policy/ambient-light-sensor#browser_compatibility) and [document-domain](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Permissions-Policy/document-domain) already state that these permissions are supported by Chrome behind flags.

`speaker-selection`, however, seemed to have not been supported by any browser, and was therefore removed from bCD in https://github.com/mdn/browser-compat-data/pull/23470/files#diff-0ead49a748587386317090773b8cfdc12e7478bac7f30c2b35018a86ebf095d9L1373.

Could you please double-check that Chrome (still?) supports this permission (through a flag), and if so: Open a new (more specific) issue for this? Thank you. 🙏
