### ISSUE TITLE
mathml.elements.math - Supported in Chrome 106

### ISSUE THREAD

**Issue by FryingggPannn** [mdn/browser-compat-data#16890]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

MathML support was added in Chromium 106, and Chrome 106 is based on this version. Other Chromium 106-based browsers may also have MathML support in the future. See https://caniuse.com/mathml

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

MathML supported in Chrome 106

### Did you test this? If so, how?

I tested this on my MacBook Air, and also checked the support table on Can I Use.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/MathML

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `mathml.elements.math`
* Report started: 2022-07-10T01:15:49.193Z

</details>

**Comment by fred-wang** [comment]
Note that MathML is still under a flag in Chrome, so we need to wait before saying it is supported. Pull request to update the status: https://github.com/mdn/browser-compat-data/pull/17059

**Comment by fred-wang** [comment]
BTW, I'm not sure why CanIuse said 106 ; initially chromestatus.com was using that milestone but we delayed that a bit after discussion on https://groups.google.com/a/chromium.org/g/blink-dev/c/n4zf_3FWmAA ; browser-compat-data should still be updated when the flag is on by default, but that's not the case yet.
