### ISSUE TITLE
api.Element.openOrClosedShadowRoot - Chrome 88+ has it

### ISSUE THREAD

**Issue by WebReflection** [mdn/browser-compat-data#16986]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

[Chrome 88+ has it as Web extension API](https://developer.chrome.com/docs/extensions/reference/dom/)

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

Same as FIrefox, but with version 88 and the wild char to explain is extension only.

### Did you test this? If so, how?

No, but I am sure who wrote [the extension API](https://developer.chrome.com/docs/extensions/reference/dom/) did.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://developer.chrome.com/docs/extensions/reference/dom/

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Element/openOrClosedShadowRoot

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.Element.openOrClosedShadowRoot`
* Report started: 2022-07-14T10:14:57.556Z

</details>

**Comment by queengooborg** [comment]
Thanks for the information!  Since it looks like this is a method that is only available to web extensions, I feel that we should also move it out of `api.Element` as it is potentially misleading to web developers (we have a separate folder for web extensions stuff).
