### ISSUE TITLE
Tables not displaying correctly on MDN page for await

### ISSUE THREAD

**Issue by simonsarris** [mdn/browser-compat-data#1701]
The json for `await`:

https://github.com/mdn/browser-compat-data/blob/master/javascript/operators/await.json

Corresponds with this page, as is mentioned in the file:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await

But that page shows a `?` for node instead of version `7`, as it should.

The data looks correct, and it is correct for the similar page for async, which does display correctly on the corresponding MDN page.

https://github.com/mdn/browser-compat-data/blob/master/javascript/operators/async_function_expression.json

**Comment by ExE-Boss** [comment]
Press **Ctrl+Shift+R** to rebuild the page, which someone already did, so this issue is now resolved.

**Comment by jwhitlock** [comment]
That was me. It is weird how a bug hangs around for 16 hours, then two people look at a bug within 5 minutes.

**Comment by simonsarris** [comment]
Thanks for all the work you do @jwhitlock. ❤️
