### ISSUE TITLE
overflow-wrap: anywhere - Supported in Safari

### ISSUE THREAD

**Issue by darrinmn9** [mdn/browser-compat-data#17012]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

The browser compat tables seems to indicate `overflow-wrap: anywhere` is not supported in safari. But it appears to work on my safari browser (`v15.5`). You can test it here: https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap

I see a few relevant webkit bugs:
https://bugs.webkit.org/show_bug.cgi?id=195345 - still open - seems to indicate it is not implemented
https://bugs.webkit.org/show_bug.cgi?id=231152 - seems to indicate a fix was implemented

Not sure what to make of all this.

### What browsers does this problem apply to, if applicable?

Safari

### What did you expect to see?

`'overflow-wrap: anywhere` to not work in safari... but it seems to work just fine.

### Did you test this? If so, how?

https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap
https://bugs.webkit.org/show_bug.cgi?id=195345
https://bugs.webkit.org/show_bug.cgi?id=231152

**Comment by ChristianSiegert** [comment]
I can confirm `overflow-wrap: anywhere` works in Safari 15.4 and 15.6.1.

Steps to reproduce:
1. Open Safari’s JavaScript console
2. Enter `CSS.supports("overflow-wrap: anywhere")`
3. Safari 15.4 and 15.6.1 return `true` (which means they supports the queried CSS feature)

**Comment by mizdra** [comment]
It seems to have been implemented in webkit in the following commit.

- https://github.com/WebKit/WebKit/commit/6ed0b8b3e00e59aa24ef24296de726e2f4dc4b8b

From the assigned git tag, I'm guessing it was shipped with Safari TP 144 and Safari 15.4.

<img width="1497" alt="image" src="https://user-images.githubusercontent.com/9639995/189878840-92410c46-b6a5-4c12-ae4d-f8891e79677b.png">

But that does not seem to be mentioned in the release notes.

- https://webkit.org/blog/12621/release-notes-for-safari-technology-preview-144/
- https://developer.apple.com/documentation/safari-release-notes/safari-15_4-release-notes

However, according to https://github.com/mdn/browser-compat-data/issues/17012#issuecomment-1243946714, it seems to work with Safari 15.4, so I guess it was shipped with Safari 15.4 after all.
