### ISSUE TITLE
javascript.builtins.WebAssembly.Memory - shared flag compatibility is out of date

### ISSUE THREAD

**Issue by scottjmaddox** [mdn/browser-compat-data#17046]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Chrome Android says "No", i.e. no support, but according to [this](https://developer.chrome.com/blog/enabling-shared-array-buffer/) blog post, it has had support since version 88:

> Firefox was the first to ship SharedArrayBuffer with this restriction, in version 79 (July 2020).
>
> Then, in January 2021, I wrote this article, and you read it. Hello.
>
> And that's where we are now. Chrome 88 brings SharedArrayBuffer back to Android for pages that are cross-origin isolated, and Chrome 92 brings the same requirements to desktop, both for consistency, and to achieve total cross-origin isolation.

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

Chrome Android should say "88"

### Did you test this? If so, how?

No

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://developer.chrome.com/blog/enabling-shared-array-buffer/

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/Memory

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `javascript.builtins.WebAssembly.Memory`
* Report started: 2022-07-20T03:40:34.929Z

</details>

**Comment by queengooborg** [comment]
The `shared` flag is not the same thing as `SharedArrayBuffer`, so the linked article doesn't apply to this feature.  I checked results from the [mdn-bcd-collector](https://mdn-bcd-collector.appspot.com/) project to see if this _was_ supported on Chrome Android regardless, but the collector agrees it's not supported.
