### ISSUE TITLE
html.elements.input.type_date - <SUMMARIZE THE PROBLEM>

### ISSUE THREAD

**Issue by Jungtz** [mdn/browser-compat-data#17056]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

max/min
safari no support

### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/Input/date

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `html.elements.input.type_date`
* Report started: 2022-07-21T03:34:42.626Z

</details>

**Comment by queengooborg** [comment]
This issue has been closed because there is not enough information.  If this is still an issue, please fill out the issue template and reopen this issue.
