### ISSUE TITLE
css.selectors.backdrop - Supported in Firefox for `dialog` elements

### ISSUE THREAD

**Issue by Keyacom** [mdn/browser-compat-data#17070]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

For Firefox, this still says the `::backdrop` selector is unsupported, but it is supported (unsure from what version though).

### What browsers does this problem apply to, if applicable?

Firefox

### What did you expect to see?

I did not expect to see the darkening of the background. The page has a `#simple-dialog::backdrop` selector, and the ID `simple-dialog` points to a `<dialog>` element.

### Did you test this? If so, how?

I tested this by visiting [this site](https://usefulangle.com/demos/110/dialog-simple.html).

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

I have none at the moment, but the [Caniuse](https://caniuse.com/mdn-css_selectors_backdrop_dialog) page on this is outdated.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/::backdrop

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.selectors.backdrop`
* Report started: 2022-07-21T20:32:27.489Z

</details>

**Comment by Keyacom** [comment]
Please note that this will only work if the dialog is opened via `showModal()` or `show()`, manually applying the `open` attribute won't initiate the `::backdrop`.

**Comment by CGomezCOL** [comment]
> Please note that this will only work if the dialog is opened via `showModal()` or `show()`, manually applying the `open` attribute won't initiate the `::backdrop`.

Hi, do you know if the `::backdrop` will be supported using `open` attribute?

**Comment by Keyacom** [comment]
It won't, as just using the `open` attribute  won't initialize the `::backdrop` (intended!).
