### ISSUE TITLE
Issue with "::selection": (text-decoration can not be used with ::selection)

### ISSUE THREAD

**Issue by pal-crystal** [mdn/browser-compat-data#17079]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/::selection

#### What information was incorrect, unhelpful, or incomplete?

text-decoration is listed in allowed properties with pseudo-element ::selection

#### Specific section or headline?
Allowable properties

#### What did you expect to see?
to not see text-decoration in allowable properties

#### Did you test this? If so, how?
i test it in firefox 78.15.0esr (64 bits)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/_doublecolon_selection`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/::selection
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/_doublecolon_selection/index.md
* Last commit: https://github.com/mdn/content/commit/26f50bdaeb1228f458d21dbdf7dc110387b20daa
* Document last modified: 2021-08-12T23:59:09.000Z

</details>

**Comment by queengooborg** [comment]
This has been added in #21536!
