### ISSUE TITLE
css.properties.backdrop-filter - Firefox 103 supported `backdrop-filter` by default.

### ISSUE THREAD

**Issue by Genbuchan** [mdn/browser-compat-data#17137]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Firefox 103 supported `backdrop-filter` by default.

### What browsers does this problem apply to, if applicable?

Firefox

### Did you test this? If so, how?

1. Open `https://apple.com/` on Firefox 103.
2. You can see that blurred background of the top navigation bar.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://bugzilla.mozilla.org/show_bug.cgi?id=1578503

### MDN URL

https://developer.mozilla.org/ja/docs/Web/CSS/backdrop-filter

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.backdrop-filter`
* Report started: 2022-07-26T13:40:09.156Z

</details>

**Comment by evilpie** [comment]
Fixed by https://github.com/mdn/browser-compat-data/pull/17105/

**Comment by Genbuchan** [comment]
> Fixed by #17105

Thank you! I close this issue.
