### ISSUE TITLE
The `declarativeNetRequestWithHostAccess` permission is missing.

### ISSUE THREAD

**Issue by thecontemporaryflorals** [mdn/browser-compat-data#17147]
The `declarativeNetRequestWithHostAccess` permission is missing.

_Originally posted by @Rob--W in https://github.com/mdn/browser-compat-data/pull/14942#discussion_r932612701_

**Comment by Rob--W** [comment]
I don't see a need for duplicating my review comment on a draft PR - this filed issue can be closed.

**Comment by queengooborg** [comment]
Sorry @Rob--W, this is a known spam account.  I'll get Schalk to ban this user from MDN.  👍
