### ISSUE TITLE
api.PushManager.supportedContentEncodings - Firefox doesn't support this

### ISSUE THREAD

**Issue by gauntface** [mdn/browser-compat-data#17146]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Firefox 102 doesn't support `PushManager.supportedContentEncodings`. 

### What browsers does this problem apply to, if applicable?

Firefox

### What did you expect to see?

I'd expect MDN to include this in their support table.

### Did you test this? If so, how?

If you run `PushManager.supportedContentEncodings` in the developer console `undefined` is returned.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://developer.mozilla.org/en-US/docs/Web/API/PushManager/supportedContentEncodings

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/PushManager/supportedContentEncodings

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.PushManager.supportedContentEncodings`
* Report started: 2022-07-28T22:34:12.577Z

</details>

**Comment by queengooborg** [comment]
Fixed in #20237!
