### ISSUE TITLE
api.HTMLMediaElement.audioTracks - CompatData is out-of-date

### ISSUE THREAD

**Issue by Omcsesz** [mdn/browser-compat-data#17166]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

The information on browser compatibility is not updated since a few years.

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet), Firefox, Internet Explorer

### What did you expect to see?

I expected to see the following: 
Chrome - not supported as of version 103
Firefox - not supported as of version 103
Edge - not supported as of version 103

### Did you test this? If so, how?

Yes, I tested this. I used this function call in one of my programs, and it did not work (returned an empty array, instead of the array containing the audio tracks).

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/audioTracks

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.HTMLMediaElement.audioTracks`
* Report started: 2022-08-01T09:24:59.820Z

</details>

**Comment by queengooborg** [comment]
Our data indicates that support for this property is behind a flag in Chromium and Firefox respectively, so a user would have to enable the flag to use the feature.  This is represented in the table already:

<img width="129" alt="Screen Shot 2022-08-11 at 15 58 34" src="https://user-images.githubusercontent.com/5179191/184256203-455502c3-189a-4194-bc8e-c349e5921a6d.png">
