### ISSUE TITLE
html.elements.input.type_time - Not working on Firefox 103

### ISSUE THREAD

**Issue by abibhatta** [mdn/browser-compat-data#17242]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time#browser_compatibility lists support for input type "time" on version 57 onwards of firefox but this does not work on v 103.

### What browsers does this problem apply to, if applicable?

Firefox

### What did you expect to see?

I expected to see time picker support on firefox in latest version

### Did you test this? If so, how?

I pulled up this page in chrome and firefox. Chrome shows timepicker while firefox does not. 

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time#browser_compatibility

See examples

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `html.elements.input.type_time`
* Report started: 2022-08-04T00:17:46.397Z

</details>

**Comment by queengooborg** [comment]
Firefox doesn't have a time picker dropdown, but does implement special functionality for time inputs, which I have confirmed works.
