### ISSUE TITLE
track Safari data by iOS version instead of by Safari version

### ISSUE THREAD

**Issue by romainmenke** [mdn/browser-compat-data#17240]
see : https://bugs.chromium.org/p/chromium/issues/detail?id=1348792

`Safari : Mozilla/5.0 (iPhone; CPU iPhone OS 14_8_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Mobile/15E148 Safari/604.1`

Currently Chrome, Firefox, Opera, DuckDuckGo, SamgsungInternet all omit `Version/14.1.2` from their user agent string on iOS.

Up until Safari 11 the significant version was determined by the `Safari/604.1` fragment, as this mapped to the WebKit version.
With Safari 11 this part of the user agent (and `AppleWebKit/605.1.15`) was frozen.

It almost appears that this slipped through the cracks and that `Version/14.1.2` was not added to other WebKit flavoured browsers on iOS.

From this point the only relevant information in the user agent string of Chrome, Firefox, Opera, DuckDuckGo and SamgsungInternet because the iOS version.

Only Safari and Brave include `Version/14.1.2` and advertise the actual version and capabilities of the browser.

The immediate issue is that sites and services are mislabeling these user agents.
This can either be resolved by these user agents by appending `Version/14.1.2` to their user agent string or sites and services can look at the OS version.

This made we wonder if it would make sense for MDN to track and report support stats for iOS by the iOS version?

There are upsides :
- clear that these stats cover any browser on iOS
- easier for makers of tools like polyfill.io to send the correct polyfill bundle to each browser

The downside obviously is that this would be a massive undertaking and that we would need to construct a mapping for all past iOS versions on all possible devices to the Safari version that shipped with it.

**Comment by romainmenke** [comment]
It was brought up that MDN and caniuse actually do track the iOS version and not the Safari version. I always interpreted the data in MDN as Safari versions not as OS versions.

@foolip fairly sure that you know the answer to this? :)

**Comment by romainmenke** [comment]
Never mind, I spotted this bit here : https://github.com/mdn/browser-compat-data/blob/main/browsers/safari_ios.json#L115

**Comment by foolip** [comment]
> The downside obviously is that this would be a massive undertaking and that we would need to construct a mapping for all past iOS versions on all possible devices to the Safari version that shipped with it.

It was a pretty big undertaking, but yeah we now track the iOS version, not the Safari version.

**Comment by romainmenke** [comment]
Do you know when this was changed?

Depending on the time I have more or less work to do to fix the polyfill-library and postcss-preset-env.

**Comment by queengooborg** [comment]
> Do you know when this was changed?

As far as I know, we have been using iOS versions since at least when I started working on this project back in late 2018.  A good chunk of the data we had still used the Safari version instead of the iOS version, but those had been fixed over time.
