### ISSUE TITLE
api.Window.requestAnimationFrame - Migrate browser notes from mdn/content

### ISSUE THREAD

**Issue by kbrosnan** [mdn/browser-compat-data#17295]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Infobox for browser compatibility shows Firefox having a implementation note. The notes section talks about IE 12-17 

### What did you expect to see?

The IE section should have the `*`

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.Window.requestAnimationFrame`
* Report started: 2022-08-10T15:58:50.046Z

</details>

**Comment by queengooborg** [comment]
There's actually a note for Firefox as well, however it looks like notes regarding IE/Edge were added to the page content, rather than BCD.  We'll migrate the notes over!
