### ISSUE TITLE
javascript.builtins.String.raw - Opera support from v28

### ISSUE THREAD

**Issue by EladHeller** [mdn/browser-compat-data#17308]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Opera says no support, but supported from version 28.

### Did you test this? If so, how?

Yes. I run `String.raw({raw: ['a','c']},['b'])` in console. The result should be `abc`.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/raw

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `javascript.builtins.String.raw`
* Report started: 2022-08-11T16:25:06.374Z

</details>

**Comment by Schweinepriester** [comment]
At least related, probably duplicate: #16824
