### ISSUE TITLE
How to interpret a range of versions for `:-webkit-any-link` under `added`

### ISSUE THREAD

**Issue by romainmenke** [mdn/browser-compat-data#17336]
https://github.com/mdn/browser-compat-data/blob/f66362d7970fb61a554afca5341b8ad38e33c498/css/selectors/any-link.json#L68

How do we interpret a range in this case?
Was it removed in 38?

**Comment by romainmenke** [comment]
I think this should just be `37` as this was the first Blink android version and Blink had prefixed support at that point.

**Comment by queengooborg** [comment]
Ranged values means that a feature may have been added in a version earlier than "37", but we don't know exactly when.  There's another property, `version_removed`, that indicates a feature was removed from a browser.

On MDN, we remove the "range" part and just say "37" to reduce reader confusion.  Hope this helps!

**Comment by romainmenke** [comment]
Thank you @queengooborg!
