### ISSUE TITLE
api.Window.unload_event - Not firing for chrome

### ISSUE THREAD

**Issue by rohanafsan** [mdn/browser-compat-data#17412]
### What type of issue is this?

Browser bug (a bug with a feature that may impact site compatibility)

### What information was incorrect, unhelpful, or incomplete?

Browser compatibility mentions how it works with Chrome but for me its only working for Firefox

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

I expected to see the page reload to a different location or even a log in a console.

### Did you test this? If so, how?

I tried running the same task in both Firefox and Chrome, it only works in Firefox

### Do you have anything more you want to share?

```
window.addEventListener('unload', this.testConsole, false)

```

testConsole:

```
testConsole = () => {
    console.log("Testing")
  }
 ```

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Window/unload_event

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.Window.unload_event`
* Report started: 2022-08-17T16:47:27.970Z

</details>

**Comment by queengooborg** [comment]
I cannot confirm a lack of functionality in Chrome using the following simple code, telling Chrome to preserve console logging, and then reloading the page:

```js
window.addEventListener('unload', (event) => {console.log('I am unloading!')});
```

If I had to guess, looking at your code, it seems you're accidentally trying to call `this.testConsole` when you're most likely not within a class.  If that's not the case, could you provide a runnable test so we can confirm what's going on?

**Comment by mns98** [comment]
Yes observerd same in my application, please say the alternative for this onunload
