### ISSUE TITLE
api.Element.scrollIntoView - Not working in Firefox

### ISSUE THREAD

**Issue by rjwaltz** [mdn/browser-compat-data#17460]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

in MDN page **Element.scrollIntoView()**, it says **Element.scrollIntoView()** could work in FireFox, but the truth is **not**.
[MDN page link](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView#browser_compatibility)

### What browsers does this problem apply to, if applicable?

Firefox

### What did you expect to see?

Element.scrollIntoView() should work, but it's not.

### Did you test this? If so, how?

yes, I already tested it on FireFox - version 103.0.2 (64-bit), Element.scrollIntoView() is not compatible for FireFox.

### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/API/Element/scrollIntoView

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.Element.scrollIntoView`
* Report started: 2022-08-18T07:44:05.153Z

</details>

**Comment by queengooborg** [comment]
I cannot confirm that the function does not work; it works fine in Firefox 103.0.2 on my end.

I'd be happy to reopen this issue if you can provide an example as to how the feature is not working, but for now I'm going to close it as 'invalid'.

**Comment by myfonj** [comment]
Cannot confirm; it works and had been working as far as I remember. Test:

```
data:text/html,<!doctype html><title>scrollIntoView test</title>
<style>[onclick]:empty::after { content: attr(onclick)}</style>
<button onclick="document.querySelector('footer').scrollIntoView()"></button>
<hr style="height: 200vh">
<footer>Footer</footer>
```

If you enter above snippet into URL bar and click the button, you should see the "Footer"

In what context have you observed it does not work?
