### ISSUE TITLE
http.status.404 - <SUMMARIZE THE PROBLEM>

### ISSUE THREAD

**Issue by ahmed303080** [mdn/browser-compat-data#17510]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

Pictures not showing up

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404

### Do you have anything more you want to share?

https://ahmed303080.github.io/portfoilo/
![Untitled147](https://user-images.githubusercontent.com/86774912/185810864-6bc2a07d-005b-4fce-a18b-e5fe7f1d8d16.png)

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `http.status.404`
* Report started: 2022-08-21T20:54:14.533Z

</details>

**Comment by queengooborg** [comment]
We're not a development help forum.  Please don't open issues for problems with your own website.
