### ISSUE TITLE
RTCPeerConnection.connectionState

### ISSUE THREAD

**Issue by TomasHubelbauer** [mdn/browser-compat-data#1752]
I am confused about the values in `connectionState`. This API seems to be missing in both Firefox (60.0b10) and Chrome (65.0.3325.181) where I tried it, but according to the tables should be there.

```ts
new RTCPeerConnection().connectionState // undefined
new RTCPeerConnection() // connectionState is missing
```

Am I missing something (field only appers during established connection or something) or is this wrong?

**Comment by Elchi3** [comment]
@a2sheppy could you help to fix this WebRTC compat data question?

**Comment by zeeshanhyder** [comment]
@TomasHubelbauer You can use `RTCPeerConnection.iceConnectionState` to achieve the same thing.

**Comment by TomasHubelbauer** [comment]
I am curious about whether this is a field which according to spec should exist or a mistake, I noticed it by chance, not by working on a WebRTC application.

**Comment by Elchi3** [comment]
This was fixed in https://github.com/mdn/browser-compat-data/pull/2815
