### ISSUE TITLE
Element API: scrollIntoView: options parameter is supported in Safari 14.1 for macOS and iOS

### ISSUE THREAD

**Issue by jensimmons** [mdn/browser-compat-data#17542]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

Element API: `scrollIntoView`: `options` parameter states Safari has no support. This is incorrect. 

https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView

### What browsers does this problem apply to, if applicable?

Safari

### What did you expect to see?

I expect to see Element API: `scrollIntoView`: `options` parameter to convey to web developers the fact support shipped in Safari 14.1 for both macOS and iOS.

### Did you test this? If so, how?

We tested `behavior: smooth` in Safari 15.6 and noted it works. 

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

Issue: https://bugs.webkit.org/show_bug.cgi?id=161611 
Issue sighting the commit: https://bugs.webkit.org/show_bug.cgi?id=161611#c37
Commit from Jul 9, 2019: https://trac.webkit.org/changeset/247255/webkit

We also dug deep into our internal documentation and discussed to confirm this work landed in WebKit, and we shipped it in Safari 14.1.

**Comment by queengooborg** [comment]
Fixed in #19126!
