### ISSUE TITLE
api.Bluetooth - Table lacks compatibility data for Chrome for iOS

### ISSUE THREAD

**Issue by CalDayley** [mdn/browser-compat-data#17562]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

There wasn't any info on Chrome for iOS

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Web_Bluetooth_API

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.Bluetooth`
* Report started: 2022-08-25T17:16:03.581Z

</details>

**Comment by queengooborg** [comment]
Hi there!  We don't document other browsers on iOS and iPadOS because they all use the Safari version that comes with the installed iOS/iPadOS version.  In other words, you can reference the Safari on iOS table to determine when a feature is supported in Chrome on iOS.  Hope this helps!
