### ISSUE TITLE
BCD spreadsheet missing webkit scrollbar-related selectors

### ISSUE THREAD

**Issue by connorshea** [mdn/browser-compat-data#1757]
The MDN page for [::-webkit-scrollbar](https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar) is incomplete and has no data table. 

The latest stable version of Chrome for macOS, at least, definitely supports this selector, e.g. see [this page](http://plexode.com/eval3/#ht=%3Cstyle%3E%0A%23test%2C%20%3A%3A-webkit-scrollbar%20{%0A%20%20background%3A%20red%3B%0A}%0A%0A%23test%20{%0A%20%20width%3A%20100px%3B%0A%20%20height%3A%20100px%3B%0A%20%20overflow%3A%20scroll%3B%0A}%0A%3C%2Fstyle%3E%0A%0A%3Cdiv%20id%3Dtest%3E%3C%2Fdiv%3E&ohh=1&ohj=1&jt=&ojh=1&ojj=1&ms=100&oth=0&otj=0&cex=1) or in [the MDN article](https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar#Example).

<img width="1440" alt="screen shot 2018-04-10 at 11 01 25 am" src="https://user-images.githubusercontent.com/2977353/38571724-8fccf0a6-3cae-11e8-80cc-ceb8b26878f5.png">

Safari 11.1 for macOS also supports this selector, though it seems a bit buggy as to when it'll appear.

There are also a number of selectors for styling specific parts of the scrollbar, per the MDN article:

- `::-webkit-scrollbar-button`
- `::-webkit-scrollbar-thumb`
- `::-webkit-scrollbar-track`
- `::-webkit-scrollbar-track-piece`
- `::-webkit-scrollbar-corner`
- `::-webkit-resizer`

The [spreadsheet](https://docs.google.com/spreadsheets/d/1ivgyPBr9Lj3Wvj5kyndT1rgGbX-pGggrxuMtrgcOmjM/edit#gid=680932322) doesn't include these values, is that intentional? Is there another discussion somewhere about these pages that I should read?

**Comment by ExE-Boss** [comment]
The spreadsheet is rather incomplete, especially when it comes to prefixed values, so when I find an API that’s missing from it, I just add it (I did the same with MathML, SVG, HTTP, WebExtensions and some CSS stuff).

**Comment by Elchi3** [comment]
Yeah, the spreadsheet is not perfect. Please add to it, it's editable by everyone on purpose :)

**Comment by connorshea** [comment]
Is there anywhere (besides the spreadsheet) I should mention the `::-webkit-scrollbar-*` selectors missing pages? Or is there any precedence for having all the `::-webkit-scrollbar-*` selectors on a single page?

Apologies if this is a discussion that should go on Discourse instead :)

**Comment by ExE-Boss** [comment]
Well, MDN lists all the `::-webkit-scrollbar-*` selectors only on [the `::-webkit-scrollbar` page](https://developer.mozilla.org/docs/Web/CSS/%3A%3A-webkit-scrollbar#CSS_Scrollbar_Selectors).
