### ISSUE TITLE
Write "checklist for reviewers"

### ISSUE THREAD

**Issue by wbamberg** [mdn/browser-compat-data#176]
We should have a nice short doc covering things we'd like to check in the compat data, but that the schema doesn't enforce.

**Comment by Elchi3** [comment]
I think this should be part of the CONTRIBUTING file, so I've added this to PR #212.

**Comment by Elchi3** [comment]
We've improved the docs since then and also added more automated tests. Closing this. Feel free to open specific issues, where our docs or tests are lacking.
