### ISSUE TITLE
html.elements.a - Opera target="_blank" implies rel="noopener" behavior incorrect compatibility

### ISSUE THREAD

**Issue by EDVTAZ** [mdn/browser-compat-data#17607]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Browser compatibility for Opera with `target="_blank" implies rel="noopener" behavior` seems incorrect to me.
Testing with this site: https://mathiasbynens.github.io/rel-noopener/
and `Opera 90.0.4480.54` `window.opener` is already null in the newly opened tab.
I'm not sure since what version this is the case, I wasn't able to find any more info on this with a few searches.

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

Opera shown to support `target="_blank" implies rel="noopener" behavior`

### Did you test this? If so, how?

Tested with this site: https://mathiasbynens.github.io/rel-noopener/
and `Opera 90.0.4480.54` `window.opener` is already null in the newly opened tab.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

No, wasn't able to find anything.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `html.elements.a`
* Report started: 2022-08-30T11:07:57.826Z

</details>

**Comment by queengooborg** [comment]
This has been fixed in #19598!
