### ISSUE TITLE
css.properties.aspect-ratio - Unsupported in UXP-based web browsers

### ISSUE THREAD

**Issue by EchedeyLR** [mdn/browser-compat-data#17688]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

Unsupported by UXP-based web browsers.

### What did you expect to see?

That is incompatible with UXP-based web browsers.

### Did you test this? If so, how?

Just opening a website implementing it or the own example at MDN in Pale Moon and Basilisk.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/aspect-ratio

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.aspect-ratio`
* Report started: 2022-09-04T17:01:11.407Z

</details>

**Comment by queengooborg** [comment]
We do not currently track these browsers in BCD.
