### ISSUE TITLE
javascript.builtins.Intl.getCanonicalLocales - Incorrect support relating to Opera

### ISSUE THREAD

**Issue by SimekMilos** [mdn/browser-compat-data#17687]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

[Intl.getCanonicalLocales()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/getCanonicalLocales) says, that Opera doesn't support this function. I tested it and it does.

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

Version since this functionality is supported in Opera.

### Did you test this? If so, how?

In dev console in Opera. I've used this function and it yielded correct results.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/getCanonicalLocales

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `javascript.builtins.Intl.getCanonicalLocales`
* Report started: 2022-09-04T14:55:36.278Z

</details>

**Comment by queengooborg** [comment]
Fixed in #17712!
