### ISSUE TITLE
Missing data for Import Maps

### ISSUE THREAD

**Issue by gsnedders** [mdn/browser-compat-data#17701]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

Import Maps were, per https://chromestatus.com/feature/5315286962012160, shipped in Chrome 89.

However, there are no links to https://wicg.github.io/import-maps/ anywhere within BCD.

**Comment by gsnedders** [comment]
See also: https://github.com/mdn/content/issues/16150

**Comment by hamishwillee** [comment]
I'll be doing this in the next couple of weeks.
