### ISSUE TITLE
javascript.builtins.String.endsWith - <Internet Explorer column missing>

### ISSUE THREAD

**Issue by mlisowsk** [mdn/browser-compat-data#17729]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

The column for Internet Explorer is missing.

### What browsers does this problem apply to, if applicable?

Internet Explorer/Legacy Edge (12-18)

### What did you expect to see?

A column for Internet Explorer showing that String.prototype.endsWith() is not implemented by IE.

### Did you test this? If so, how?

Coded a JS application with WebBrowser calling String.endsWith(). Error "Object doesn't support property or method 'endsWith' " is thrown.

### Do you have anything more you want to share?

Please put back IE BCD. The MS WebBrowser control is based on IE and there exist business applications built on top of the WebBrowser control that behave like IE even if Edge is installed on a machine. This usage of WebBrowser control might not be reflected in browser statistics because those applications might not access the internet.

Please see below a message from Microsoft stating the the WebBrowser control will remain supported by MS even after EOS for IE:

https://docs.microsoft.com/en-us/answers/questions/855019/web-browser-control-after-june-15th-ie-retirment.html

https://docs.microsoft.com/en-us/dotnet/desktop/winforms/controls/webbrowser-control-overview?view=netframeworkdesktop-4.8

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/endsWith

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `javascript.builtins.String.endsWith`
* Report started: 2022-09-08T08:08:59.831Z

</details>

**Comment by queengooborg** [comment]
See https://github.com/orgs/mdn/discussions/202 for more details.  Closing this issue because this repository does not track the rendering of the tables on MDN pages, only the raw data.

**Comment by mlisowsk** [comment]
Thank you queengooborg. I opened this issue to indicate "demand" to roll back the PR #6602 which hides the IE BCD data in MDN. The discussion 202 you linked is only people who no longer depend on IE cheering. Would appreciate if PR #6602 could be rolled back in a timely manner - it's only one line of code and it doesn't do any harm to show IE BCD data. The announcement discussion 202 has a final conclusion that makes me believe it will take MONTHS to get the BCD data back. That's a bit long for one line of code, isn't it? Would be great if you could trigger a faster review as I don't know how to do that and the 202 discussion is closed.

As shown in the MS question 855019 the IE engine is still officially supported by MS, just not in the iexplore.exe wrapper.
Thanks a lot!

**Comment by queengooborg** [comment]
In regards to the IE data itself, we are actually not maintaining its data any longer due to the discontinuation of Internet Explorer.  We are aware that the engine will still be supported by Microsoft until 2029 due to Edge's IE Mode, however it will not be receiving security updates and developers should not be writing new IE-compatible websites in this day and age.  Even if IE is re-displayed on MDN pages, the data itself will remain frozen and will eventually be removed in the next year or two.  Although it is one line in the data, it is still a line we will have to test, validate and maintain, and if we say yes to making any updates, we will never truly have frozen IE data.

Thank you in advance for understanding!

**Comment by mlisowsk** [comment]
I think it will be OK for the IE BCD data to be frozen as IE itself is also frozen so I believe it would be fine to also drop test & validation so as to minimize maintenance on your side.
Personally, I would also prefer the legacy application to upgrade to a modern engine, as IE is missing many API calls and is also a slow engine - but it is not up to me to decide.
Once again, thank you!
