### ISSUE TITLE
Add welcome bot

### ISSUE THREAD

**Issue by queengooborg** [mdn/browser-compat-data#17744]
I think it would be helpful to add a welcome bot, as shown in https://github.com/mdn/interactive-examples/pull/2265, to BCD.

**Comment by Elchi3** [comment]
I think when the welcome (or any greeting) comes from the reviewer or any actual human being, there is a lot more empathy in the PR than when a bot does these things.

**Comment by queengooborg** [comment]
Closing this as it is stale and not mentioned since opening.
