### ISSUE TITLE
Update WebKit vendor-prefixed properties using data from the Apple documentation

### ISSUE THREAD

**Issue by connorshea** [mdn/browser-compat-data#1774]
I'm not sure if this is worth the trouble, but I found [this list](https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariCSSRef/Articles/StandardCSSProperties.html#//apple_ref/doc/uid/TP30001266-SW10) ([archive.org link just in case](https://web.archive.org/web/20180411062452/https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariCSSRef/Articles/StandardCSSProperties.html)) of vendor-prefixed CSS properties in Apple's WebKit documentation that lists what versions of Safari they started supporting each given prefix in.

A lot of the data files in this repo, e.g. `animation.json` (see below), don't list the specific version where the vendor prefix was introduced, but this data _can_ be found in the Apple documentation. It might be useful to look through these and try to fill in the blanks.

https://github.com/mdn/browser-compat-data/blob/5133d14b23996400d17fead58193e7c27c8d0f22/css/properties/animation.json#L150-L158

**Comment by vinyldarkscratch** [comment]
I think that this would be useful information to store in this repository.  A future goal of mine is for this repository to have no `true` or `null` values left, and this leads to that goal.  I'll be glad to go through and tackle this one.  :wink:

**Comment by vinyldarkscratch** [comment]
Got that [list scrubbed down](https://docs.google.com/document/d/1GBlFCgDm3AWI10IlOFoTRhXBbaIvcxqZhMmScf7KJcA/edit?usp=sharing) to just the statements that mention when the property's available in Safari, so that it can be turned into a PR -- which I will definitely tackle once I get a little more rest!

**Comment by Elchi3** [comment]
This has seen many PRs which have been merged. Is that all that is needed here or do we have more material in the Apple docs?

**Comment by vinyldarkscratch** [comment]
From what I can tell, we got everything!
