### ISSUE TITLE
api.console - Compatibly table shows multiple "Substitution strings" rows

### ISSUE THREAD

**Issue by vanowm** [mdn/browser-compat-data#17756]
### What type of issue is this?

Other

### What information was incorrect, unhelpful, or incomplete?

The table shows multiple `Substitution strings` rows without any explanation which part of `Substitution strings` it's referring to:
![image](https://user-images.githubusercontent.com/511517/189549838-2e5c9145-8f49-46af-92cc-f639d09927e0.png)

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/console

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.console`
* Report started: 2022-09-11T21:28:34.694Z

</details>

**Comment by queengooborg** [comment]
Each of these instances are actually subfeatures for the method above it -- notice the indentation.

**Comment by vanowm** [comment]
Oh, I see. It's not intuitive how it look (same goes to asterisks that don't look like clickable button), maybe if there was thinner border at name column between these rows or different background color or actual name of the main feature.... To me it looks like an incomplete name with a placeholder.

**Comment by queengooborg** [comment]
I'm down for a UI tweak to better clarify the hierarchy -- would you mind opening an issue at https://github.com/mdn/yari for this?  That repository is where the MDN engine is hosted, including the code to render the BCD tables!
