### ISSUE TITLE
`Intl.ListFormat` can be expected to fully work from Safari 16

### ISSUE THREAD

**Issue by romainmenke** [mdn/browser-compat-data#17768]
https://github.com/mdn/browser-compat-data/blob/7458d06d80d2470e8188a1f3a64b026084079be4/javascript/builtins/Intl/ListFormat.json#L82-L85

see : https://github.com/mdn/browser-compat-data/pull/12614

https://webkit.org/blog/13152/webkit-features-in-safari-16-0/

Safari 16.0 is not installabled on macOS Catalina

I am unsure if/how to update the JSON data to reflect this.

**Comment by Josh-Cena** [comment]
I'm unsure what's being suggested here. Is there a Safari version where the feature could work in Catalina?

**Comment by Josh-Cena** [comment]
"The feature is supported by Safari 14.1+" is always true; "the feature is supported by macOS 11+" is also always true. Readers infer the actual compatibility by taking the intersection of these groups. I think the current way is already unambiguous.

**Comment by romainmenke** [comment]
> "The feature is supported by Safari 14.1+" is always true; "the feature is supported by macOS 11+" is also always true. 

This is incorrect.

- a user on macOS Big Sur with Safari 14.0 would not have support `Intl.ListFormat`
- a user on Safari 14.1 and macOS Catalina would have support

Only when both pre-conditions are met will users have support for `Intl.ListFormat`.

I think it is important to communicate that Safari 16.0 has full and unconditional support.
Currently users have no way to quickly determine this.

Users would have to read through all the release notes of Safari to find which version dropped support for macOS Catalina.

Machines don't have any way to determine this information.

**Comment by Josh-Cena** [comment]
But Safari is not marked as "partial support" at the moment. @queengooborg would it be adequate to mark Safari 14.1–16 as "partial implementation" and 16+ as full support?

**Comment by Josh-Cena** [comment]
@queengooborg I'm not very familiar with the BCD schema; to me the suggestion above looks acceptable. WDYT?

**Comment by queengooborg** [comment]
Unfortunately, the above example wouldn't work either, as the linter prevents multiple statements that only have `version_added` and an optional note.  The reason for this is that in the past, some contributors to BCD had used this structure to indicate support for certain subfeatures (such as return values or parameters), instead of properly creating subfeatures...

**Comment by romainmenke** [comment]
Then I think we should close this without further action :)
There will always be weird edge cases that can't be expressed in the schema.

**Comment by queengooborg** [comment]
Sounds good -- thank you for your understanding, and if we ever revisit the idea of machine-readable OS limitation data, I'm sure this feature will be looked at again too!
