### ISSUE TITLE
Update service worker support for iOS and macOS 

### ISSUE THREAD

**Issue by RobPethick** [mdn/browser-compat-data#1776]
In Safari 11.1 service worker support for iOS and macOS was added but it is still listed as in dev on mdn 

https://developer.apple.com/library/content/releasenotes/General/WhatsNewInSafari/Articles/Safari_11_1.html

**Comment by ExE-Boss** [comment]
I already did for [`Navigator.serviceWorker`](https://developer.mozilla.org/docs/Web/API/Navigator/serviceWorker#Browser_compatibility) when I added it in #1707.

**Comment by abdonrd** [comment]
We should add it here, right?

* [mdn/browser-compat-data/api/ServiceWorker.json](https://github.com/mdn/browser-compat-data/blob/master/api/ServiceWorker.json)
* [mdn/browser-compat-data/api/ServiceWorkerContainer.json](https://github.com/mdn/browser-compat-data/blob/master/api/ServiceWorkerContainer.json)
* [mdn/browser-compat-data/api/ServiceWorkerGlobalScope.json](https://github.com/mdn/browser-compat-data/blob/master/api/ServiceWorkerGlobalScope.json)
* [mdn/browser-compat-data/api/ServiceWorkerMessageEvent.json](https://github.com/mdn/browser-compat-data/blob/master/api/ServiceWorkerMessageEvent.json)
* [mdn/browser-compat-data/api/ServiceWorkerRegistration.json](https://github.com/mdn/browser-compat-data/blob/master/api/ServiceWorkerRegistration.json)

**Comment by ExE-Boss** [comment]
> And also here?
> - [mdn/browser-compat-data/webextensions/api/browsingData.json#L237-L257](https://github.com/mdn/browser-compat-data/blob/master/webextensions/api/browsingData.json#L237-L257)
>
> https://github.com/mdn/browser-compat-data/blob/bdff84a8265089c04a56e702c4a6287cea734b53/webextensions/api/browsingData.json#L237-L257

Safari doesn’t support [WebExtensions](https://developer.mozilla.org/Add-ons/WebExtensions).
