### ISSUE TITLE
Missing feature - api.OffscreenCanvasRenderingContext2D.commit

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#17777]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

No compat data on https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvasRenderingContext2D/commit

### What did you expect to see?

Compat data on https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvasRenderingContext2D/commit

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

Seems like it is in Firefox at least https://searchfox.org/mozilla-central/source/dom/webidl/OffscreenCanvasRenderingContext2D.webidl#14

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvasRenderingContext2D/commit

**Comment by queengooborg** [comment]
This has been added in #17880!
