### ISSUE TITLE
css.selectors.selection - compat table needs a row for text-decoration support

### ISSUE THREAD

**Issue by aminomancer** [mdn/browser-compat-data#17817]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

Under [Allowable properties](https://developer.mozilla.org/docs/Web/CSS/::selection#allowable_properties), the article suggests that `text-decoration` rules will work with `::selection`, but this [doesn't seem to be implemented](https://bugzilla.mozilla.org/show_bug.cgi?id=1612598). So as with other features in the spec but not implemented, there should be a row in the compatibility table that exposes the degree of browser support for `text-decoration` on the `::selection` pseudo-element.

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet), Firefox, Legacy Edge (12-18), Safari

### What did you expect to see?

A row labeled `text-decoration` with an icon and number in each column representing level of support for the feature, per-browser.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://bugzilla.mozilla.org/show_bug.cgi?id=1612598
https://bugzilla.mozilla.org/show_bug.cgi?id=1428987

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/::selection

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.selectors.selection`
* Report started: 2022-09-16T21:02:46.814Z

</details>

**Comment by bsmth** [comment]
@aminomancer dropping a ping on this one 👋🏻
