### ISSUE TITLE
WebDriver command names and MDN urls are inconsistent

### ISSUE THREAD

**Issue by ExE-Boss** [mdn/browser-compat-data#1781]
When #1417 was merged, [`https://developer.mozilla.org⁠/docs⁠/Web⁠/WebDriver⁠/Commands‍⁠/Get_Element_Tag_Name`](https://developer.mozilla.org/docs/Web/WebDriver/Commands/Get_Element_Tag_Name) was valid, now it returns a 404 instead of a 301 to [`https://developer.mozilla.org⁠/docs⁠/Web⁠/WebDriver⁠/Commands⁠/GetElementTagName`](https://developer.mozilla.org/docs/Web/WebDriver/Commands/GetElementTagName).

By the time #1465 was merged, the page was already renamed without the link, so the [browser compatibility table for the WebDriver commands](https://developer.mozilla.org/en-US/docs/Web/WebDriver/Commands#Browser_compatibility) is now full of red-links, instead of the links to the features present [in the list at the top of the page being blue](https://developer.mozilla.org/en-US/docs/Web/WebDriver/Commands#toc).

needinfo?(@chrisdavidmills)

**Comment by connorshea** [comment]
I'm gonna try fixing this, should the JSON files be renamed or would that break too many things?

**Comment by ExE-Boss** [comment]
Renaming the JSON files won’t affect anything.

**Comment by connorshea** [comment]
@ExE-Boss ah right, but renaming this part would (I think?):

```json
{
  "webdriver": {
    "commands": {
      "Take_Screenshot": {
```

**Comment by chrisdavidmills** [comment]
@connorshea If you want to have a go at this, you are more than welcome (and I would really thank you for it!)

So basically in each file, you need to find the section that looks like this:
```
      "Accept_Alert": {
        "__compat": {
          "mdn_url": "https://developer.mozilla.org/docs/Web/WebDriver/Commands/Accept_Alert", 
```

and update them like this:

```
      "Accept Alert": {
        "__compat": {
          "mdn_url": "https://developer.mozilla.org/docs/Web/WebDriver/Commands/AcceptAlert",
```

So a space in the first one, and no space (Upper camel case) in the other. This should ensure that both the displayed command name is correct, and the links point to the correct places.
