### ISSUE TITLE
Consistently use `prefix` instead of `alternative_name` for events

### ISSUE THREAD

**Issue by saschanaz** [mdn/browser-compat-data#17822]
Currently things like `animation_event`, `fullscreenerror_event`, etc. use `"prefix": "webkit"` while some others use `"alternative_name": "webkit..."`. Namely:

* `"alternative_name": "webkitfullscreenchange"`
* `"alternative_name": "webkitfullscreenerror"`
* `"alternative_name": "webkittransitionend",`
* `"alternative_name": "webkitresourcetimingbufferfull"`
* `"alternative_name": "webkitnonreal"` (this one is in schema document 🤔)

`prefix` should be preferred if possible, so I think those 5 should be fixed. What do you think?

**Comment by queengooborg** [comment]
It looks like these have already been fixed, however I'm going to introduce a linter update to ensure this won't occur again.
