### ISSUE TITLE
api.Document.pointerlockchange_event/pointerlockerror_event - Accidentally removed by #16674?

### ISSUE THREAD

**Issue by saschanaz** [mdn/browser-compat-data#17821]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

`pointerlockchange_event` and `pointerlockerror_event`.

### What did you expect to see?

Those should exist.

### Did you test this? If so, how?

Simply search them inside the repo.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

I believe it's falsely removed by #16674. Pointer Lock API is not really a part of Pointer Events, anyway.

([MDN](https://developer.mozilla.org/en-US/docs/Web/API/Element/pointerlockchange_event) relates them to `Element` but that's simply wrong. Someone should move them under `Document`.)

**Comment by Elchi3** [comment]
I also saw this and created a PR to add them back here: https://github.com/mdn/browser-compat-data/pull/17816
Based on https://github.com/mdn/browser-compat-data/pull/16674#pullrequestreview-1028330809 I thought the correct interface is `Element`, but that's probably wrong then.

**Comment by saschanaz** [comment]
Note that https://w3c.github.io/pointerlock/#extensions-to-the-document-interface says it's Document.

**Comment by Elchi3** [comment]
Yes, you are right. I made a mistake and thought it was `Element`. Fixed in https://github.com/mdn/browser-compat-data/pull/17816 and in https://github.com/mdn/content/pull/20890 for the content pages.
