### ISSUE TITLE
javascript.builtins.Array.group - chrome support behind flag not listed

### ISSUE THREAD

**Issue by Teiem** [mdn/browser-compat-data#17837]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Chrome has no support for `Array.prototype.group()`

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

From version 100:    
  - Can be enabled using the `Experimental JavaScript` flag
  - Available via `Array.prototype.groupBy()`
    
Somewhere between Version 100 and 108   
  - Available via `Array.prototype.group()`

### Did you test this? If so, how?

Tested `Array.prototype.group()` in chrome canary v108.
Tested `Array.prototype.groupBy()` in chrome v104.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/group
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/groupToMap

https://chromestatus.com/feature/5714791975878656
https://bugs.chromium.org/p/v8/issues/detail?id=12499

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/group

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `javascript.builtins.Array.group`
* Report started: 2022-09-19T12:30:54.571Z

</details>

**Comment by queengooborg** [comment]
The feature has been deprecated and removed in favor of `Map.groupBy` and `Object.groupBy`!
