### ISSUE TITLE
api.Navigator.canShare - Windows Server 2016 Chrome shouldnt be compatible

### ISSUE THREAD

**Issue by jtrippel** [mdn/browser-compat-data#17842]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

im using navigator.canShare(data) to determine if native sharing is compatible, in case of windows server 2016 and  chrome browser (version 105.0.5195.127)  im getting true, but at the time of invoking navigator.share(data) its not poping up anything and after several seconds (probably time out) im getting the following error: "Error: AbortError: Share failed".

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

canShare(data) should return false if not supported

### Did you test this? If so, how?

Yes, on windows server 2016 with my implementation and examples on https://developer.mozilla.org/en-US/docs/Web/API/Navigator/canShare and https://developer.mozilla.org/en-US/docs/Web/API/Navigator/Share

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

No

### Do you have anything more you want to share?

![image](https://user-images.githubusercontent.com/38986089/191192761-26908a89-30cc-42a8-a559-54f7b51e8138.png)
![image](https://user-images.githubusercontent.com/38986089/191192981-206a8d8e-8369-4426-b368-86c0159c4eb5.png)

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Navigator/canShare

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.Navigator.canShare`
* Report started: 2022-09-20T06:50:14.720Z

</details>

**Comment by queengooborg** [comment]
Windows Server isn't something that we really track here in BCD.  There isn't a strong demand to document compatibility differences on Windows Server (partially because there's so few).

What I'd probably recommend doing is filing a bug on https://crbug.com to report the issue directly to the Chrome devs themselves, so they may fix the issue in future versions of Chrome.
