### ISSUE TITLE
Minimum required node version missing

### ISSUE THREAD

**Issue by CITguy** [mdn/browser-compat-data#1785]
The `npm test` command fails to execute on node versions prior to v6.

Please add one or both of the following:

1. documentation about minimum version
2. a `.node-version` file (or similar) to configure via a node version manager (nvm or nodenv)

**Comment by ExE-Boss** [comment]
There’s also the option to set the minimum node version in [the `engines` field](https://docs.npmjs.com/files/package.json#engines) in [`package.json`](https://github.com/mdn/browser-compat-data/blob/master/package.json).
