### ISSUE TITLE
javascript.builtins.Intl.NumberFormat - It doesn't list all the options

### ISSUE THREAD

**Issue by adjenks** [mdn/browser-compat-data#17853]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

I don't see "options.style" anywhere. I think other options might be missing as well. Like options.currecy

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `javascript.builtins.Intl.NumberFormat`
* Report started: 2022-09-21T18:14:13.772Z

</details>

**Comment by Josh-Cena** [comment]
Features with the same support as the root feature are not listed separately. `options.style` and `options.currency` have the same support as the constructor itself.

**Comment by adjenks** [comment]
If a compatibility table shows a long list of features and just excludes a few, then perhaps they should just be listed anyways and say "same compatibility as constructor." so that people aren't left confused.

**Comment by queengooborg** [comment]
Fixed by #20588!
