### ISSUE TITLE
css.selectors.-moz-window-inactive - chrome had supported :window-inactive.

### ISSUE THREAD

**Issue by zhangenming** [mdn/browser-compat-data#17864]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

[Browser compatibility](https://developer.mozilla.org/en-US/docs/Web/CSS/:-moz-window-inactive#browser_compatibility)

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### Do you have anything more you want to share?

https://github.com/Fyrd/caniuse/issues/4260

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/:-moz-window-inactive

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.selectors.-moz-window-inactive`
* Report started: 2022-09-23T06:05:03.482Z

</details>

**Comment by queengooborg** [comment]
I'm closing this issue as the issue template is mostly empty.  Please fill out the issue template with actionable information before opening an issue.  Thank you!
