### ISSUE TITLE
css.properties.outline-style - Certain styles not supported in Chromium

### ISSUE THREAD

**Issue by ghaste** [mdn/browser-compat-data#17862]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Chrome does not seem to support styles Ridge, Groove, Inset, and Outset, while one can infer from the document that it supports it unconditionally

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

something similar to how Firefox or Safari shows the above styles, instead all I see is a solid outline style instead. 

### Did you test this? If so, how?

https://codepen.io/ghaste/pen/YzLrzLo

### Do you have anything more you want to share?

https://codepen.io/ghaste/pen/YzLrzLo

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/outline-style

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.outline-style`
* Report started: 2022-09-22T17:16:41.474Z

</details>

**Comment by queengooborg** [comment]
These values have been added to the mdn-bcd-collector in https://github.com/openwebdocs/mdn-bcd-collector/commit/0ec4e444c24cf65ab1e56af9822bc067999fa590, so they will be automatically tracked and added to BCD!
