### ISSUE TITLE
api.OffscreenCanvas - Update compatibility table for Firefox 105

### ISSUE THREAD

**Issue by dr-vortex** [mdn/browser-compat-data#17876]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Firefox is marked as only supported via a flag, though as of Firefox 105 it is supported without flags.

### What browsers does this problem apply to, if applicable?

Firefox

### What did you expect to see?

105 listed as full support

### Did you test this? If so, how?

Not tested

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://www.mozilla.org/en-US/firefox/105.0/releasenotes/

### Do you have anything more you want to share?

![image](https://user-images.githubusercontent.com/75621402/192026591-1ad366db-1af5-47d9-94c2-f668da254642.png)

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.OffscreenCanvas`
* Report started: 2022-09-23T17:42:11.705Z

</details>

**Comment by queengooborg** [comment]
This was fixed by #17880.
