### ISSUE TITLE
javascript.builtins.Array.forEach - <SUMMARIZE THE PROBLEM>：在谷歌浏览器上面进行循环的时候，是否会乱序，在什么场景下会乱序

### ISSUE THREAD

**Issue by LoveMuZiLi** [mdn/browser-compat-data#17891]
### What type of issue is this?

Other

### What information was incorrect, unhelpful, or incomplete?

 const getCategorData = {
    "second_cname": "111",
    "third_cname": "222",
    "first_cname": "333",
    "fourth_cname": "444"
};
const list = [];
  Object.keys(getCategorData).forEach((key) => {
    if (key.includes('_cname') && getCategorData[key] !== '') {
      list.push(getCategorData[key]);
    }
  });
console.log(list, list.join(' | '));

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

在什么场景下foreach，循环会出现乱序情况

### Did you test this? If so, how?

no

### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `javascript.builtins.Array.forEach`
* Report started: 2022-09-27T06:18:00.561Z

</details>

**Comment by queengooborg** [comment]
This looks like a development help question, based upon rough machine translation.  Please note that we are not a development help forum, and we recommend using dedicated sites like StackOverflow.com for such questions!
