### ISSUE TITLE
Improve linting of browser JSON files

### ISSUE THREAD

**Issue by connorshea** [mdn/browser-compat-data#1789]
I just opened #1788 which fixes a problem with the qq_android.json file. Essentially, instead of `release_date` the file used `relase_date`.

Is there a way to have CI validate the keys to make sure they're spelled correctly, e.g. files can only have a key from this set: `['release_date', 'release_notes', 'version', 'status']`?

**Comment by ExE-Boss** [comment]
That would be done by adding the `"additionalProperties": false` entry to the correct place in the `browsers.schema.json` file.

https://github.com/mdn/browser-compat-data/blob/0d577fa66204aef4f4571561181212c39eab7d3d/schemas/browsers.schema.json#L42-L53
