### ISSUE TITLE
api.MediaRecorder - iOS record error

### ISSUE THREAD

**Issue by noisefactor** [mdn/browser-compat-data#17910]
### What type of issue is this?

Other

### What information was incorrect, unhelpful, or incomplete?

iOS support listed as fully compatible, but it's not working for iOS 14.7.1.  Recording appears under the 'Record' & 'Stop' buttons but the text field inside it says "Error"

### What did you expect to see?

iOS Safari - iOS 14.7.1

### Did you test this? If so, how?

Using an iPhone 11 Pro.  The same MediaStream_Recording_API examples page worked perfectly for OS X Chrome browser minutes before.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/MediaStream_Recording_API/Using_the_MediaStream_Recording_API

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.MediaRecorder`
* Report started: 2022-09-29T01:06:57.771Z

</details>

**Comment by queengooborg** [comment]
Although I am also seeing an error, this error is displayed on the audio element and is not an error with the API itself.  I'm guessing it has something to do with codec support.  But either way, this is not a problem with the API.
