### ISSUE TITLE
Add browser name to schema

### ISSUE THREAD

**Issue by connorshea** [mdn/browser-compat-data#1791]
It'd be nice to have a `browser_name` property for each file in [browsers/](https://github.com/mdn/browser-compat-data/tree/master/browsers).

I'm currently building a simple data viewer webapp and I have to include code like this in order to get a "normal" name for the browser:

```ruby
@browser_names = {
  chrome: "Chrome",
  edge: "Edge",
  edge_mobile: "Edge Mobile",
  firefox: "Firefox",
  firefox_android: "Firefox Android",
  ie: "Internet Explorer",
  nodejs: "NodeJS",
  opera: "Opera",
  qq_android: "QQ Android",
  safari: "Safari",
  safari_ios: "Safari Mobile",
  samsunginternet_android: "Samsung Internet for Android",
  uc_android: "UC Browser for Android",
  uc_chinese_android: "Chinese UC Browser for Android"
}
```

This means that whenever a new browser is added, I have to manually update this file. If there was a `browser_name` property I could just query that whenever I needed the browser name.

**Comment by ExE-Boss** [comment]
I’m pretty sure that these kinda of features are the goal of [browser-compat-toolkit](https://github.com/mdn/browser-compat-toolkit).

**Comment by Elchi3** [comment]
Thanks for the suggestion! For displaying on MDN, we've done this elsewhere for now (in KumaScript and hopefully soon in browser-compat-toolkit), but I think it would be nice to have it part of the data here.
Generally, we have no good idea about how to deal with localization, though. The strings you are proposing above are fine, but English. We could try to only use the brand names and avoid fill words like "for" or we start to think about how we deal with localizing these other and strings.

**Comment by connorshea** [comment]
@Elchi3 I opened #2025, which I think does a decent job of avoiding English in the browser names :)
