### ISSUE TITLE
Fragments are broken in CSS spec links

### ISSUE THREAD

**Issue by wbamberg** [mdn/browser-compat-data#17925]
- visit, say, https://developer.mozilla.org/en-US/docs/Web/CSS/animation-delay#specifications
- click the link (labelled "Unknown specification" due to a separate but related issue)
- you will go to https://w3c.github.io/csswg-drafts/css-animations-1/ , but you should go to https://w3c.github.io/csswg-drafts/css-animations-1/#animation-delay

It looks like the link in BCD is getting redirected: https://github.com/mdn/browser-compat-data/blob/1617ce437ffcbfbbc2a98a88264676dfb9185354/css/properties/animation-delay.json#L7

...and it looks like the fragment is getting lost along the way.

**Comment by queengooborg** [comment]
I think this is purely an upstream issue and shouldn't be tracked here in BCD, so I'm going to close this.
