### ISSUE TITLE
javascript.builtins.Array.lastIndexOf - Disappointed that IE <=11 Compatibility information has been dropped (appears this is the case for the entire MDN site)

### ISSUE THREAD

**Issue by jstolte** [mdn/browser-compat-data#17923]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

Missing compatibility information for IE.  While I recognize that IE has reached EOL and end-of-support from Microsoft... it is still being used in some cases... and to completely wipe all the IE compatibility information is unfortunate.  I also realize that since the decision was made to drop the IE info from the compatibility tables across the site, it is unlikely that it will return and I will have to look else where for that information when needed... at least it is still there on the W3C site.  So I really do not have any expectation that this will be addressed... but this was the only way I could think of to indicate my disappointment of this decision.

### What did you expect to see?

IE compatibility information

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/lastIndexOf

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `javascript.builtins.Array.lastIndexOf`
* Report started: 2022-09-30T16:14:38.211Z

</details>

**Comment by queengooborg** [comment]
Thanks for your feedback -- as mentioned in https://github.com/orgs/mdn/discussions/202, we are planning to do more research on what browsers our readers want before we make any more changes to the rendered tables.
