### ISSUE TITLE
css.properties.mask-image - <requires prefix in Chrome>

### ISSUE THREAD

**Issue by JanErikGunnar** [mdn/browser-compat-data#17922]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

The information says mask-image works in Chrome without prefix, it seems to require prefix in at least Chrome 105 and 106.

In Chrome "106.0.5249.61", and "105.something", the CSS property "mask-image" (without prefix) is ignored, manually adding the property through Chrome dev tools yields "Unknown property name". Prefixed version "-webkit-mask-image" works as expected in 106.

I have a feeling it has worked in earlier versions of Chrome without prefix, but cannot confirm this

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

Updated information regarding if prefix is required or not

### Did you test this? If so, how?

Tested in Chrome 105, upgraded to 106.0.5249.61, neither worked without prefix.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/mask-image

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.mask-image`
* Report started: 2022-09-30T13:58:53.892Z

</details>

**Comment by vthg2themax** [comment]
Issue still exists on Chrome 108.

**Comment by Bentroen** [comment]
I can confirm this on Chrome 110.

**Comment by Ugoku** [comment]
Confirmed on Chrome 113

**Comment by queengooborg** [comment]
Our data clearly states that Chrome requires a prefix for this CSS property, I am not sure why the reporter is saying otherwise.

**Comment by alsotang** [comment]
Confirmed on Chrome 119

**Comment by teoli2003** [comment]
There is nothing to confirm.
![Capture d’écran 2023-11-27 à 14 04 58](https://github.com/mdn/browser-compat-data/assets/1466293/51bb6db5-76ca-4b72-8d71-5b2f9aa8b18d)

**Comment by queengooborg** [comment]
I'm going to lock this issue because the thread is getting spammy.
