### ISSUE TITLE
html.elements.link.rel.preconnect - Inconsistency with CanIUse

### ISSUE THREAD

**Issue by schardev** [mdn/browser-compat-data#17926]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

MDN BCD says the `<link rel="preconnect" ...>` is still supported by Firefox, whereas the data on [caniuse](https://caniuse.com/?search=preconnect) says it has been removed after version 70.

### What browsers does this problem apply to, if applicable?

Firefox

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/preconnect

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `html.elements.link.rel.preconnect`
* Report started: 2022-10-02T15:29:43.503Z

</details>

**Comment by saurabhchardereal** [comment]
Apparently Firefox does support it (or at least in version `105.0.1`). 

![Preconnect](https://user-images.githubusercontent.com/51372520/193524733-c4788fa2-797c-4017-9daf-3db0794eef2d.png)

Will forward this issue to caniuse data repo instead.

**Comment by schardev** [comment]
The bug has been resolved and it works as expected now. Although it would be nice to have a note in the BCD table about the regression.
