### ISSUE TITLE
api.Element.wheel_event - About Safari on iOS support information problem

### ISSUE THREAD

**Issue by regchiu** [mdn/browser-compat-data#17929]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

[Safari on iOS on MDN](https://developer.mozilla.org/en-US/docs/Web/API/Element/wheel_event#browser_compatibility) says `No` but [Safari on iOS on Can I use](https://caniuse.com/mdn-api_wheelevent) says `Yes`.

### What browsers does this problem apply to, if applicable?

Safari

### What did you expect to see?

Safari on iOS support informations should be same.

### Did you test this? If so, how?

I can use wheel event on my iphone xs Safari 15.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

1. https://developer.mozilla.org/en-US/docs/Web/API/Element/wheel_event#browser_compatibility
2. https://caniuse.com/mdn-api_wheelevent

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Element/wheel_event

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.Element.wheel_event`
* Report started: 2022-10-03T07:02:55.913Z

</details>

**Comment by queengooborg** [comment]
Can you provide example code that shows the wheel event working on iOS, so we may confirm?

**Comment by regchiu** [comment]
I guess the kit(krpano) I use has done some processing, so that my safari on iOS can simulate the behavior of the wheel.

In fact I tested some simple code, wheel is not supported on iOS Safari.

Sorry for submitting a question that bothered you.
