### ISSUE TITLE
css.properties.animation-composition - supported in Safari TP

### ISSUE THREAD

**Issue by marsjaninzmarsa** [mdn/browser-compat-data#17940]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Safari/WebKit compatibility

### What did you expect to see?

Support in current Safari TP

### Did you test this? If so, how?

nope, tbh

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://developer.apple.com/safari/technology-preview/release-notes/#r140
https://bugs.webkit.org/show_bug.cgi?id=232086

### Do you have anything more you want to share?

Blink issue tracker: https://bugs.chromium.org/p/chromium/issues/detail?id=1342699&q=animation-composition&can=2

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/animation-composition

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.animation-composition`
* Report started: 2022-10-04T22:02:12.029Z

</details>

**Comment by queengooborg** [comment]
This has been resolved by #17865!
