### ISSUE TITLE
HTMLCanvasElement.getContext.powerPreference on chrome and osx works

### ISSUE THREAD

**Issue by esiegel** [mdn/browser-compat-data#17959]
The `powerPreference` option does function, at least on my intel macbook using Chrome (Version 106.0.5249.103).  It is able to switch between the discrete and non discrete gpus.  This might be a macos chrome only feature:

https://chromium.googlesource.com/angle/angle/+/HEAD/extensions/EGL_ANGLE_power_preference.txt

**Comment by queengooborg** [comment]
Fixed in #19651!
