### ISSUE TITLE
html.elements.applet - Removed from Safari

### ISSUE THREAD

**Issue by danielhjacobs** [mdn/browser-compat-data#17956]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Support says applet is still supported, with a note that removal is under consideration

### What browsers does this problem apply to, if applicable?

Safari

### What did you expect to see?

Safari no longer supports applet.

### Did you test this? If so, how?

No

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

According to https://bugs.webkit.org/show_bug.cgi?id=218677, applet was removed November 2020 from Safari. The bug in the support note for Safari was closed as a duplicate of that bug.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/applet

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `html.elements.applet`
* Report started: 2022-10-07T15:23:33.537Z

</details>

**Comment by MrBrain295** [comment]
I would be happy to work on this but I can't find any release notes that mention that this was removed.

**Comment by danielhjacobs** [comment]
Yeah, I don't see any official release notes, just the commits changelog: https://github.com/WebKit/WebKit/commit/2bbe8399428f88cf7b9bb3942f9d1a142fbeb3e6#diff-06d5c8bffbf485d8b772da40a382dfd1280cecaf7bfc2900400c8af59baace0fR1

**Comment by danielhjacobs** [comment]
That commit was part of Safari-611.1.6

According to https://en.m.wikipedia.org/wiki/Safari_version_history,  Safari 14.1 was the first release internally after that version, but this isn't mentioned in those release notes.
