### ISSUE TITLE
Problem using from TypeScript as module

### ISSUE THREAD

**Issue by stevenwdv** [mdn/browser-compat-data#17964]
I cannot seem to import `@mdn/browser-compat-data` from TypeScript as a module.

`tsconfig.json`:
```json
{
	"compilerOptions": {
		"target": "ESNext",
		"module": "NodeNext",
		"moduleResolution": "NodeNext",
		"esModuleInterop": true,
		"resolveJsonModule": true,
		"allowSyntheticDefaultImports": true
	}
}
```
(Other ESM configurations also don't seem to work.)

`main.mts`:
```ts
import bcd from '@mdn/browser-compat-data' assert { type: 'json' };
import {CompatData} from '@mdn/browser-compat-data';
import * as bcdStar from '@mdn/browser-compat-data';
type CD = bcdStar.CompatData;
```

Compile: `tsc --pretty false`
Error:
```
main.mts(1,8): error TS1259: Module '"node_modules/@mdn/browser-compat-data/data"' can only be default-imported using the 'allowSyntheticDefaultImports' flag
main.mts(2,9): error TS2305: Module '"node_modules/@mdn/browser-compat-data/data"' has no exported member 'CompatData'.
main.mts(4,11): error TS2503: Cannot find namespace 'bcdStar'.
```

To me, this seems like it may also be a bug in TypeScript, but their module config documentation is not good, so I'm not sure. In this case I can also report it there, let me know.
EDIT: it says `"node_modules/@mdn/browser-compat-data/data"` in the error; apparently it looks at `data.json` due to `exports` in package.json and gets confused.

Maybe it would also be possible to change `index.ts` to `index.d.ts` where `./data.json` is not explicitly imported? If possible, that might also fix it, and it would also be very nice anyway, because `tsc` seems to spend a lot of time parsing the JSON file for no reason.

Version info:
- `@mdn/browser-compat-data` v5.2.5
- `typescript` v4.8.4

**Comment by queengooborg** [comment]
You should be able to import BCD in TypeScript using the following:

```js
import bcd from "@mdn/browser-compat-data";
import type CompatData from "@mdn/browser-compat-data/types";
```

**Comment by stevenwdv** [comment]
@queengooborg Thanks for your reaction, however, this does not work:
```ts
main.mts(1,8): error TS1259: Module '"node_modules/@mdn/browser-compat-data/data"' can only be default-imported using the 'allowSyntheticDefaultImports' flag
main.mts(2,29): error TS2307: Cannot find module '@mdn/browser-compat-data/types' or its corresponding type declarations.
main.mts(4,38): error TS2307: Cannot find module '@mdn/browser-compat-data/types' or its corresponding type declarations.
```

`main.ts`:
```ts
import bcd from "@mdn/browser-compat-data";
import type CompatData from "@mdn/browser-compat-data/types";
// ↓ I think this is what you meant
import type {CompatData as CD2} from "@mdn/browser-compat-data/types";
```
(same `tsconfig.json`)

**Comment by queengooborg** [comment]
Whoops, fixed the original answer!

**Comment by Foxing1992** [comment]
> I cannot seem to import `@mdn/browser-compat-data` from TypeScript as a module.
> 
> `tsconfig.json`:
> 
> ```json
> {
> 	"compilerOptions": {
> 		"target": "ESNext",
> 		"module": "NodeNext",
> 		"moduleResolution": "NodeNext",
> 		"esModuleInterop": true,
> 		"resolveJsonModule": true,
> 		"allowSyntheticDefaultImports": true
> 	}
> }
> ```
> 
> (Другие конфигурации ESM также, похоже, не работают.)
> 
> `main.mts`:
> 
> ```ts
> import bcd from '@mdn/browser-compat-data' assert { type: 'json' };
> import {CompatData} from '@mdn/browser-compat-data';
> import * as bcdStar from '@mdn/browser-compat-data';
> type CD = bcdStar.CompatData;
> ```
> 
> Компиляция:`tsc --pretty false`Ошибка:
> 
> ```
> main.mts(1,8): error TS1259: Module '"node_modules/@mdn/browser-compat-data/data"' can only be default-imported using the 'allowSyntheticDefaultImports' flag
> main.mts(2,9): error TS2305: Module '"node_modules/@mdn/browser-compat-data/data"' has no exported member 'CompatData'.
> main.mts(4,11): error TS2503: Cannot find namespace 'bcdStar'.
> ```
> 
> Мне кажется, что это также может быть ошибкой в TypeScript, но их документация по конфигурации модуля не очень хороша, поэтому я не уверен. В этом случае я также могу сообщить об этом там, дайте мне знать. EDIT: it says `"node_modules/@mdn/browser-compat-data/data"` in the error; apparently it looks at `data.json` due to `exports` in package.json and gets confused.
> 
> Maybe it would also be possible to change `index.ts` to `index.d.ts` where `./data.json` is not explicitly imported? If possible, that might also fix it, and it would also be very nice anyway, because `tsc` seems to spend a lot of time parsing the JSON file for no reason.
> 
> Информация о версии:
> 
> * `@mdn/browser-compat-data`v5.2.5
> * `typescript`v4.8.4
