### ISSUE TITLE
api.WEBGL_compressed_texture_astc - Supported in Safari iOS

### ISSUE THREAD

**Issue by zcfan** [mdn/browser-compat-data#17965]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

iOS 16.0.2 support `WEBGL_compressed_texture_astc`, you can test it by open this tester page: https://codepen.io/zcfan/pen/jOxeJvy

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/WEBGL_compressed_texture_astc

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.WEBGL_compressed_texture_astc`
* Report started: 2022-10-09T11:04:01.694Z

</details>

**Comment by queengooborg** [comment]
This has been resolved in #18636.
