### ISSUE TITLE
api.Document.caretRangeFromPoint - it seems that firefox 105.0.3 om mac suoports this

### ISSUE THREAD

**Issue by DG12** [mdn/browser-compat-data#17979]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

table shows no support for firefox

### What browsers does this problem apply to, if applicable?

Firefox

### What did you expect to see?

full support

### Did you test this? If so, how?

using page[https://developer.mozilla.org/en-US/docs/Web/API/Document/caretRangeFromPoint](https://developer.mozilla.org/en-US/docs/Web/API/Document/caretRangeFromPoint)
demo section unexpectedly works :-)

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Document/caretRangeFromPoint

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.Document.caretRangeFromPoint`
* Report started: 2022-10-11T12:06:28.403Z

</details>

**Comment by queengooborg** [comment]
The demo code actually includes a fallback that uses `caretPositionFromPoint` if `caretRangeFromPoint` is not supported.  This has confused a few users, so I'm going to see if I can update the example to be more explicit about which function it's using.
