### ISSUE TITLE
api.Crypto - <SUMMARIZE THE PROBLEM>

### ISSUE THREAD

**Issue by Zacharyhzk** [mdn/browser-compat-data#17971]
### What type of issue is this?

Other

### What information was incorrect, unhelpful, or incomplete?

if my own server is not in Secure context, how I can run the Web Crypto API in my sever to test?

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

The solution of ignoring the Secure context environment.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.Crypto`
* Report started: 2022-10-11T03:50:47.871Z

</details>

**Comment by queengooborg** [comment]
We're not able to help with development.  Please refer to a dedicated website like StackOverflow for questions like these.
