### ISSUE TITLE
javascript.builtins.Intl.DateTimeFormat.DateTimeFormat - Chrome localization issue for "AZ" locale

### ISSUE THREAD

**Issue by yunusfillik** [mdn/browser-compat-data#17994]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

var date = "2022/01/01";
var locale;
function => new Intl.DateTimeFormat(locale, { month: 'long' }).format(date);

If using locale like 'az', 'az-Latn', 'az-Latn-AZ' or 'az-AZ' this function return 'M01' value.
But this value should be 'yanvar'

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### Did you test this? If so, how?

I tested it from the site below

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `javascript.builtins.Intl.DateTimeFormat.DateTimeFormat`
* Report started: 2022-10-13T13:16:51.889Z

</details>

**Comment by yunusfillik** [comment]
Hi, any update for this issue?

**Comment by rin4ik** [comment]
having the same issue with UZ locale. is there any available solution I cant seem to find any for a long time. @queengooborg can you please take a look to this problem. with other browsers month displays correctly

**Comment by rin4ik** [comment]
@yunusfillik You can try this [polyfill](https://formatjs.io/docs/polyfills/intl-datetimeformat/) 

> What I dislike about this library is that it does not work without polyfill-force and if you decide to actually use polyfill-force, you must import all the locales you would like to use and not utilise the locales that already exist within the browser which inflates the compiled package

**Comment by Josh-Cena** [comment]
Unfortunately browsers are free to output any kind of localized message. We cannot exhaustively document every instance of "unexpected output".
