### ISSUE TITLE
css.properties.backdrop-filter - <SUMMARIZE THE PROBLEM>

### ISSUE THREAD

**Issue by Mega-0064** [mdn/browser-compat-data#18036]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

My code editor was displaying: 'backdrop-filter' is not supported by Firefox, Firefox for Android.

### What browsers does this problem apply to, if applicable?

Firefox

### What did you expect to see?

How to fix the error

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/backdrop-filter

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.backdrop-filter`
* Report started: 2022-10-18T11:48:07.981Z

</details>

**Comment by queengooborg** [comment]
I can confirm that this property is supported in Firefox.  It sounds like your code editor is having some issues, and as such you should file an issue with your code editor, not this repository.
