### ISSUE TITLE
api.Document.adoptedStyleSheets - Safari now supports adoptedStyleSheets 

### ISSUE THREAD

**Issue by fwebdev** [mdn/browser-compat-data#18049]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Safari now supports adoptedStylesheet.

### What browsers does this problem apply to, if applicable?

Safari

### What did you expect to see?

Support for next Safari Version

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://github.com/WebKit/WebKit/commit/5de6ac49fed803ece2e682ac65c9b6d095e2e05b
https://bugs.webkit.org/show_bug.cgi?id=245931

https://github.com/WebKit/standards-positions/issues/42

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Document/adoptedStyleSheets

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.Document.adoptedStyleSheets`
* Report started: 2022-10-20T14:05:35.304Z

</details>

**Comment by queengooborg** [comment]
I just tested this in the latest version of Safari and I cannot confirm support.   Did you test this to confirm support yourself?  If so, how, and did you have any browser extensions?

**Comment by queengooborg** [comment]
Closing because there has been no response.
