### ISSUE TITLE
css.selectors.has - Available in Opera 72 for Android

### ISSUE THREAD

**Issue by krystian3w** [mdn/browser-compat-data#18053]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

This selector is available in Opera 72 (tested on Android).

> https://www.apkmirror.com/apk/opera-software-asa/opera/opera-72-0-3767-68191-release/
>
>> More changes/additions:
>>- Chromium 106

Opera 71 was powered by Chromium 104, so explain gap in September 2022.

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

Supported in mobile version 72

### Did you test this? If so, how?

Can I use test:

https://tests.caniuse.com/css-has - green rectangle in "Unprefixed tests"

Also tested many WebKit fancy demos:

https://codepen.io/jensimmons/pen/BaYoWea - `:has(> foo)`
https://codepen.io/jensimmons/pen/BarwGpV - dark mode based on input
https://codepen.io/jensimmons/pen/vYdKKbL - themes based on input

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/:has

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.selectors.has`
* Report started: 2022-10-20T20:30:27.489Z

</details>

**Comment by krystian3w** [comment]
https://github.com/CSS4-Selectors/website/pull/9

**Comment by krystian3w** [comment]
https://github.com/Fyrd/caniuse/issues/5602

**Comment by queengooborg** [comment]
This has been fixed by adding Opera Android 72 to the data in #18059.
