### ISSUE TITLE
CSS - Firefox `height: auto-fit` support

### ISSUE THREAD

**Issue by NicolasPineau** [mdn/browser-compat-data#18057]
https://github.com/mdn/browser-compat-data/blob/16977094c18f7c15779201a8cb33990fcc49b1c4/css/properties/height.json#L53

Tried `height: fit-content` on Firefox, and it seems to be working properly, without vendor prefix. Should compat data be updated ?

**Comment by queengooborg** [comment]
Fixed in #19522!
