### ISSUE TITLE
css.types.transform-function.scale - Hides another image behind it on iOS

### ISSUE THREAD

**Issue by Medaillek** [mdn/browser-compat-data#18058]
### What type of issue is this?

Browser bug (a bug with a feature that may impact site compatibility)

### What information was incorrect, unhelpful, or incomplete?

I found a bug using scale: 50; on a circle :

- I have an image on my page and when I scaled up a circle that covers my page with a transition-duration: 600ms; , the image disappears until animation ends.

This happenend on safari Iphone 11 Pro max.

Bug fixed using transform: scale(50)

### What browsers does this problem apply to, if applicable?

Safari

### What did you expect to see?

Image disappeared behind my scaled circle until animation was endend. Tried to use z-index but didn't work.

### Did you test this? If so, how?

``
.circle{
  transition-duration: 600ms;
  position: absolute;
  width: 50px;
  height: 50px;
  background-color: red;
  border-radius: 50%;
  right: -50px;
  top: -50px;
}
.scale-circle{
  transition-duration: 600ms;
/*   transform : scale(50);   */ --> Image doesn't disappears
  scale:50; /* --> Image disappears until transition duration ends*/
}
``

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://developer.mozilla.org/fr/docs/Web/CSS/transform-function/scale

### Do you have anything more you want to share?

https://drive.google.com/drive/folders/1HB13sujiXKI9xsm3h8g8dlaw0bFsIYrr?usp=sharing

### MDN URL

https://developer.mozilla.org/fr/docs/Web/CSS/transform-function/scale

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.types.transform-function.scale`
* Report started: 2022-10-21T15:27:49.595Z

</details>

**Comment by queengooborg** [comment]
This sounds like a niche case and isn't something we can track in BCD, so I'm going to go ahead and close this issue.
