### ISSUE TITLE
api.SpeechSynthesisEvent.charIndex - always returns 0 value.

### ISSUE THREAD

**Issue by briankarlsayen** [mdn/browser-compat-data#18063]
### What type of issue is this?

Browser bug (a bug with a feature that may impact site compatibility)

### What information was incorrect, unhelpful, or incomplete?

The charIndex property in chrome v106(latest version) doesn't seem to work properly, but in firefox v106 works fine.

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

return value changes with every word uttered.

### Did you test this? If so, how?

created a javascript app that uses a SpeechSynthesisEvent, works properly in firefox but not in chrome.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

unsolved issue bug reported on since chromium v55 see here `https://bugs.chromium.org/p/chromium/issues/detail?id=681026&q=component%3AInternals%3ESpeechSynthesis%20charIndex&can=2`

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesisEvent/charIndex

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.SpeechSynthesisEvent.charIndex`
* Report started: 2022-10-24T00:12:38.968Z

</details>

**Comment by queengooborg** [comment]
Thanks for reporting this -- could you provide test code so we can verify the compatibility issue?
