### ISSUE TITLE
Preserve IE data as a separate npm package

### ISSUE THREAD

**Issue by romainmenke** [mdn/browser-compat-data#18078]
see : https://github.com/mdn/browser-compat-data/issues/15333

We depend on the IE data in MDN for the `polyfill-library`, `postcss-preset-env`, `core-js`, ...
Would it be possible to preserve the data and publish it (once?) as a separate package.

**Comment by queengooborg** [comment]
We're currently polling for information on MDN to decide what to do with the IE data.  For now, and at least two years (since the IE data was effectively deprecated), the IE data will not be removed from BCD.  We'll make an announcement on the decision once we have enough information!

**Comment by romainmenke** [comment]
> We're currently polling for information on MDN to decide what to do with the IE data.

How or where?
