### ISSUE TITLE
Lint for overlapping statements involving preview

### ISSUE THREAD

**Issue by gsnedders** [mdn/browser-compat-data#18071]
See https://github.com/mdn/browser-compat-data/issues/17517#issuecomment-1222235139

> ```json
>             "safari": [
>               {
>                 "version_added": "15.4"
>               },
>               {
>                 "version_added": "14",
>                 "version_removed": "preview",
>                 "flags": [
>                   {
>                     "type": "preference",
>                     "name": "CSSOM View Smooth Scrolling"
>                   }
>                 ]
>               }
>             ],
> ```

We should probably be linting for things like this, as this means we have overlapping statements (added in 14 -> infinity behind a flag, added in 15.4).

**Comment by queengooborg** [comment]
This would already be covered by the irrelevant flag policy (see https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/index.md#removal-of-irrelevant-flag-data), and probably doesn't need its own linter.  We haven't implemented a linter for this guideline yet as there are some edge cases to keep for now.

**Comment by queengooborg** [comment]
Closing since such a case falls under flag removal guidelines, which will be programmatically enforced in #21512.
