### ISSUE TITLE
http.headers.Content-Disposition - Chrome support is incomplete

### ISSUE THREAD

**Issue by christianhujer** [mdn/browser-compat-data#18108]
### What type of issue is this?

Browser bug (a bug with a feature that may impact site compatibility)

### What information was incorrect, unhelpful, or incomplete?

Chrome version 107.0.5304.87 does not completely implement the Content-Disposition header as per RFC. (Firefox for example does.)

The following scenario is not supported by Chrome:

Content-Disposition: inline; filename=start.xhtml

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

On the compatibility data page, expected to see that Chrome does not fully implement the Content-Disposition header as per RFC 6266.

### Did you test this? If so, how?

I tested this by:
1. Verify that https://nelkinda.com/ is indeed sending a Content-Disposition header. It does.

2.a) Open https://nelkinda.com/ in Firefox. Go to "Save As…". Look at the filename filled in the dialog. Firefox correctly filled the filename from the Content-Disposition header (in this case "`start.xhtml`").

2.b) Open https://nelkinda.com/ in Chrome. Go to "Save As…". Look at the filename filled in the dialog. Chrome wrongly filled the filename from the title instead of the Content-Disposition header (in this case "`Nelkinda Software Craft Pvt Ltd.xhtml`").

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://www.rfc-editor.org/rfc/rfc6266

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `http.headers.Content-Disposition`
* Report started: 2022-10-30T13:56:07.989Z

</details>

**Comment by bsmth** [comment]
Thanks for reporting. I tried this out and I can reproduce it. I'm not sure if this can really be classed as "partial implementation", but it deserves a link to the most relevant bug, IMO.

__Chrome bugs:__

* https://issues.chromium.org/issues/352093465 (most active / recent)
* https://issues.chromium.org/issues/40065278

__spec details:__

In rfc6266 [section 4.3](https://www.rfc-editor.org/rfc/rfc6266.html#section-4.3) about `filename`:

>Depending on the disposition type, this information might be used
   right away (in the "save as..." interaction caused for the
   "attachment" disposition type), or later on (for instance, when the
   user decides to save the contents of the current page being
   displayed).
   
And [the examples](https://www.rfc-editor.org/rfc/rfc6266.html#section-5) are even clearer:

>Direct the UA to show "save as" dialog, with a filename of "example.html":
> 
> ```http
> Disposition: Attachment; filename=example.html
> ```
>
>Direct the UA to behave as if the Content-Disposition header field
   wasn't present, but to remember the filename "an example.html" for a
   subsequent save operation:
> ```http
> Content-Disposition: INLINE; FILENAME= "an example.html"
> ```
