### ISSUE TITLE
css.selectors.after - Animation and transition support for safari out of date

### ISSUE THREAD

**Issue by jsnkuhn** [mdn/browser-compat-data#18109]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Chart lists `Animation and transition support` of ::before as unsupported in Safari

### What browsers does this problem apply to, if applicable?

Safari

### What did you expect to see?

Safari support should be listed as version 6.1

### Did you test this? If so, how?

tested on the latest version of safari 16.1 and can confirm this works

test case:
https://codepen.io/chriscoyier/pen/nKpRBq

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

Safari bug for Transitions and animations do not apply to CSS generated content - https://bugs.webkit.org/show_bug.cgi?id=23209

This MDN article on :after has the same issue: https://developer.mozilla.org/en-US/docs/Web/CSS/::after

a blog post from chris coyer on css-tricks that tracks this: https://css-tricks.com/transitions-and-animations-on-css-generated-content/

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/::before

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.selectors.before`
* Report started: 2022-10-31T00:14:23.475Z

</details>

**Comment by jsnkuhn** [comment]
the push fixed the `:before` article but I mentioned in the OP that the `:after` article (https://developer.mozilla.org/en-US/docs/Web/CSS/::after) has the same problem and that hasn't been fixed. Do I have to file a separate bug for that one?

**Comment by Elchi3** [comment]
Thanks for letting us know! I'm reopening this bug.
