### ISSUE TITLE
css.properties.color-scheme - things about `only` keyword

### ISSUE THREAD

**Issue by LIXiangChen** [mdn/browser-compat-data#18122]
### What type of issue is this?

Incorrect support data

### What information was incorrect, unhelpful, or incomplete?

The `only` keyword seems to have been supported in Chrome, but was removed in the later versions. The current support table does not reflect these things. The same goes for _caniuse_.

There are still a lot of applications using the lower versions of Chromium kernel (such as the embedded webview in Android Apps), I think these data is useful.

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.color-scheme`
* Report started: 2022-11-02T03:00:44.196Z

</details>

**Comment by queengooborg** [comment]
This has been fixed in #21240!
