### ISSUE TITLE
http.headers.DNT - Safari on iOS has the "No" icon but says "Yes"

### ISSUE THREAD

**Issue by penguinencounter** [mdn/browser-compat-data#18139]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

The Safari for iOS data has the "No" icon (X) but says the word "Yes", see image:
![image](https://user-images.githubusercontent.com/49845522/199890451-feff6379-77aa-4765-a4f4-9b0ead947cc5.png)

### What browsers does this problem apply to, if applicable?

Safari

### What did you expect to see?

The description says the feature was removed in 12.2, so the text should be "...-12.1", the same as the Safari value

### Did you test this? If so, how?

yes. (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/DNT#browser_compatibility)

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

the [data](https://github.com/mdn/browser-compat-data/blob/main/http/headers/DNT.json) appears to be correct, this might be a rendering issue

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/DNT

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `http.headers.DNT`
* Report started: 2022-11-04T04:51:06.700Z

</details>

**Comment by penguinencounter** [comment]
oh and the hover-text says "full support"

**Comment by queengooborg** [comment]
Thanks for reporting this -- I opened https://github.com/mdn/yari/pull/7486 to take care of this!  Since this is an issue for Yari (the MDN engine) and not BCD (the data), I'm going to close this issue.
