### ISSUE TITLE
Add BCD for AccentColor and AccentColorText

### ISSUE THREAD

**Issue by wbamberg** [mdn/browser-compat-data#18134]
See https://github.com/mdn/content/pull/22023, which adds AccentColor and AccentColorText to the `<system-color>` page.

Since their compat story is different from the others, we should probably have a subfeature for them under the entry for [`<system-color>`](https://github.com/mdn/browser-compat-data/blob/84b9a62a2b28ad8ca11dee6cee0b85bc31833a80/css/types/color.json#L989). 

It seems that these values are supported in Firefox and Safari but not Chrome: https://github.com/mdn/content/pull/22023#issuecomment-1301794406, but I don't know which versions they were added in.

**Comment by queengooborg** [comment]
Fixed in #21150!
