### ISSUE TITLE
api.Navigator.share - is not supported in Chrome

### ISSUE THREAD

**Issue by n4rq5** [mdn/browser-compat-data#18168]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

[Browser Compatibility](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share#browser_compatibility) claims Dekstop Chrome supports `window.navigator.share()` function.

It does not seems to be the case, at least on MacOS and Linux platforms

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### Did you test this? If so, how?

Using examples on https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share#examples

It worked fine on Android but not on Linux or MacOS

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.Navigator.share`
* Report started: 2022-11-07T12:46:16.019Z

</details>

**Comment by gsnedders** [comment]
I believe (but haven't checked) that for Chrome's desktop release it's Windows and ChromeOS only.
