### ISSUE TITLE
iOS beta 'report error' link broken

### ISSUE THREAD

**Issue by OzBob** [mdn/browser-compat-data#1817]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of
Browser compatibility section
'

**Comment by Elchi3** [comment]
I can't reproduce this. What exactly is broken?

**Comment by OzBob** [comment]
using the iOS Safari browser 'small' viewport, makes it hard to complete the form, there is no Edit. Sorry. the full text I tried typing in the issue was.

Open: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of
Click: Browser compatibility section
Click: 'new compatibility tables are in beta' chevron.
None of the links/buttons do anything.

**Comment by connorshea** [comment]
This button no longer exists, so this can be closed :)
