### ISSUE TITLE
Navigator.requestMIDIAccess - fix updated Firefox versions notes

### ISSUE THREAD

**Issue by rpl** [mdn/browser-compat-data#18195]
As a followup to the changes applied from #18115, in the the following note 

https://github.com/mdn/browser-compat-data/blob/2e205a9b65d23a216ca246e9d619974098465910/api/Navigator.json#L3794

it seems that `107 or later` should actually be `108 or later`, given that both [Bug 1795025](https://bugzilla.mozilla.org/show_bug.cgi?id=1795025) (which sets dom-webmidi.enabled to true an all channels) and [Bug 1790621](https://bugzilla.mozilla.org/show_bug.cgi?id=1790621) (which sets dom.sitepermsaddon-provide.enabled to true) are both been landed in Firefox Nightly 108 and riding the Firefox 108 release train.

**Comment by queengooborg** [comment]
Fixed in #18213!
