### ISSUE TITLE
css.properties.transition - Firefox support transition without vendor prefix

### ISSUE THREAD

**Issue by saintogod** [mdn/browser-compat-data#18206]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

Firefox supported transition without vendor prefix now.

### What did you expect to see?

when does Firefox implemented transition without vendor prefix

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/transition

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.transition`
* Report started: 2022-11-14T05:53:37.953Z

</details>

**Comment by queengooborg** [comment]
We've said that a prefix isn't needed for a long time.  This was probably due to Yari's rendering bug.
