### ISSUE TITLE
api.Element.clientWidth - Not supported in Chrome 107

### ISSUE THREAD

**Issue by donghyun-yang** [mdn/browser-compat-data#18219]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

chrome version : 107.0.5304.105

video tag element clientWidth and clientHeight is undefined

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Element/clientWidth

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.Element.clientWidth`
* Report started: 2022-11-15T23:17:56.731Z

</details>

**Comment by queengooborg** [comment]
I cannot confirm that this feature is unsupported, so I'm going to go ahead and close this issue.
