### ISSUE TITLE
api.Blob.text - Safari support status isn't detailed enough

### ISSUE THREAD

**Issue by jrmuizel** [mdn/browser-compat-data#18210]
### What type of issue is this?

Incorrect support data

### What information was incorrect, unhelpful, or incomplete?

Safari 14.0 (610.1.28) doesn't support Blob.text()
See: https://github.com/WebKit/WebKit/commit/1e0d92dde519be9b381ec6623f4de6eb3f4d4700
and https://github.com/WebKit/WebKit/blob/1e0d92dde519be9b381ec6623f4de6eb3f4d4700/Source/WebCore/Configurations/Version.xcconfig

It looks like support may have been added in 14.0.1

### What browsers does this problem apply to, if applicable?

Safari

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Blob/text

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.Blob.text`
* Report started: 2022-11-14T15:54:42.593Z

</details>

**Comment by gsnedders** [comment]
This indeed doesn't appear in https://github.com/WebKit/WebKit/blob/releases/Apple/Safari-14-iOS-14.0/Source/WebCore/fileapi/Blob.idl but the commit on main does appear to be an ancestor of all the 14.0.1 tags.
