### ISSUE TITLE
css.at-rules.media.-webkit-animation - <SUMMARIZE THE PROBLEM>

### ISSUE THREAD

**Issue by ernestbuffington** [mdn/browser-compat-data#18242]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

Your compatibility chart for WebKit animation is off. Edge supports it and all browsers will soon. It was and has never been deprecated and this false information is very misleading.

Please remove it immediately.

### What did you expect to see?

It applies to your misleading information posted on the internet.

### Did you test this? If so, how?

I tested it and it doesn't matter. Please only post facts and stop posting things as facts when you have no idea if WebKit animation was even really being deprecated.

I can't even find a browser that doesn't support WebKit animation...

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

People are trusting you and you are not doing the right thing.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/@media/-webkit-animation

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.at-rules.media.-webkit-animation`
* Report started: 2022-11-19T17:09:48.135Z
<html>
<body>
<a class="bc-github-link external external-icon" href="https://github.com/mdn/browser-compat-data/issues/new?mdn-url=https%3A%2F%2Fdeveloper.mozilla.org%2Fen-US%2Fdocs%2FWeb%2FCSS%2F%40media%2F-webkit-animation&amp;metadata=%3C%21--+Do+not+make+changes+below+this+line+--%3E%0A%3Cdetails%3E%0A%3Csummary%3EMDN+page+report+details%3C%2Fsummary%3E%0A%0A*+Query%3A+%60css.at-rules.media.-webkit-animation%60%0A*+Report+started%3A+2022-11-19T17%3A15%3A58.118Z%0A%0A%3C%2Fdetails%3E&amp;title=css.at-rules.media.-webkit-animation+-+%3CSUMMARIZE+THE+PROBLEM%3E&amp;template=data-problem.yml" target="_blank" rel="noopener noreferrer" title="Report an issue with this compatibility data" style="box-sizing: border-box; text-decoration: underline; color: var(--text-link); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: ; font-variant-east-asian: ; font-weight: 400; font-stretch: ; font-size: 16px; line-height: ; font-family: Inter, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; width: fit-content; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">Report problems with this compatibility data on GitHub</a><figure class="table-container" style="box-sizing: border-box; margin: 0px; overflow: auto; width: 765.719px; color: rgb(27, 27, 27); font-family: Inter, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><figure class="table-container-inner" style="box-sizing: border-box; margin: 0px; min-width: max-content; padding: 0px; position: relative;">

  | desktop | mobile
-- | -- | --
 
2 – 35Toggle history | NoToggle history | NoToggle history | 15 – 22Toggle history | 4Toggle history | 18 – 35Toggle history | NoToggle history | 14 – 22Toggle history | 3.2Toggle history | 1.0 – 2.1Toggle history | 2 – 4.4.3Toggle history

</figure></figure><section class="bc-legend" style="box-sizing: border-box; color: rgb(27, 27, 27); font-family: Inter, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h3 class="visually-hidden" id="Legend" style="box-sizing: border-box; margin: -1px !important; letter-spacing: var(--heading-letter-spacing); font: var(--type-heading-h3); clip: rect(1px, 1px, 1px, 1px) !important; border: 0px !important; clip-path: inset(50%) !important; height: 1px !important; overflow: hidden !important; padding: 0px !important; position: absolute !important; white-space: nowrap !important; width: 1px !important;">Legend</h3><p class="bc-legend-tip" style="box-sizing: border-box; margin: 0px 0px 1rem; font-size: var(--type-smaller-font-size); font-style: italic;">Tip: you can click/tap on a cell for more information.</p></section>
</body>
</html>
</details>[Report problems with this compatibility data on GitHub](https://github.com/mdn/browser-compat-data/issues/new?mdn-url=https%3A%2F%2Fdeveloper.mozilla.org%2Fen-US%2Fdocs%2FWeb%2FCSS%2F%40media%2F-webkit-animation&metadata=%3C%21--+Do+not+make+changes+below+this+line+--%3E%0A%3Cdetails%3E%0A%3Csummary%3EMDN+page+report+details%3C%2Fsummary%3E%0A%0A*+Query%3A+%60css.at-rules.media.-webkit-animation%60%0A*+Report+started%3A+2022-11-19T17%3A15%3A58.118Z%0A%0A%3C%2Fdetails%3E&title=css.at-rules.media.-webkit-animation+-+%3CSUMMARIZE+THE+PROBLEM%3E&template=data-problem.yml)
desktop	mobile
Chrome
Edge
Firefox
Opera
Safari
Chrome Android
Firefox for Android
Opera Android
Safari on iOS
Samsung Internet
WebView Android
-webkit-animation media feature
Deprecated
Non-standard

2 – 35
Toggle history	
No
Toggle history	
No
Toggle history	
15 – 22
Toggle history	
4
Toggle history	
18 – 35
Toggle history	
No
Toggle history	
14 – 22
Toggle history	
3.2
Toggle history	
1.0 – 2.1
Toggle history	
2 – 4.4.3
Toggle history
Legend
Tip: you can click/tap on a cell for more information.

**Comment by queengooborg** [comment]
I'm going to close this issue because it is filled more with negative criticism and insults than it is helpful information for us to correct whatever may be incorrect.  Please note that MDN Web Docs is powered by volunteers offering their time and energy to contribute to the documentation, and without them we could never be where we are now.  Sometimes, we make mistakes and our information may be slightly inaccurate or incomplete -- but that's alright, because someone will _kindly_ report the issue or submit a pull request to fix the data.  :) 

By the way, I think you're misreading the page.  The page is referring to the proprietary WebKit media query that checks if animations are supported or not (`@media (-webkit-animation) {}`), which is indeed deprecated and removed long ago.  We are not claiming that animations as a whole are deprecated.
