### ISSUE TITLE
api.SVGStyleElement.sheet - Safari 16 does not appear to support

### ISSUE THREAD

**Issue by divbzero** [mdn/browser-compat-data#18252]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Safari says “3” but does not appear to support as of the most recent release of Safari “16”.

### What browsers does this problem apply to, if applicable?

Safari

### What did you expect to see?

<dl>
  <dt>Safari
  <dd>&times; No support
</dl>

### Did you test this? If so, how?

1.  Load [Web Color Wheel](https://arantius.github.io/web-color-wheel/) (arantius/web-color-wheel@620260f).

2.  Open browser console to view error:
    ```
    TypeError: undefined is not an object (evaluating 'svgStyle.insertRule')
    ```

3.  Confirm error by running the following command in browser console which returns `undefined`:
    ```js
    svg.querySelector('style').sheet
    ```

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/SVGStyleElement/sheet

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.SVGStyleElement.sheet`
* Report started: 2022-11-21T18:55:02.487Z

</details>

**Comment by queengooborg** [comment]
`svg.querySelector("style")` returns `null` in Chrome and Safari.  I don't see any `<style>` element inside the SVG, so I believe this is a testing error.

**Comment by divbzero** [comment]
The author of Web Color Wheel (@arantius) worked around the issue with the subsequent commit arantius/web-color-wheel@c514277. Safari might still lack support.
