### ISSUE TITLE
css.properties.text-decoration-thickness - Seems supported on Firefox for Android

### ISSUE THREAD

**Issue by cdelledonne** [mdn/browser-compat-data#18262]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

The `text-decoration-thickness` CSS property is reported as not supported on Firefox for Android, but I do see it work on Firefox for Android version 106.1.0

### What browsers does this problem apply to, if applicable?

Firefox

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-thickness

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.text-decoration-thickness`
* Report started: 2022-11-23T11:51:49.076Z

</details>

**Comment by queengooborg** [comment]
Fixed in #19555!
