### ISSUE TITLE
api.BroadcastChannel - users do not need to explicitly enable this feature when using deno

### ISSUE THREAD

**Issue by idanran** [mdn/browser-compat-data#18319]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

It is "Full support".

### What browsers does this problem apply to, if applicable?

Deno

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Broadcast_Channel_API

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.BroadcastChannel`
* Report started: 2022-11-25T15:14:37.202Z

</details>

**Comment by lucacasonato** [comment]
You need to pass `--unstable` to enable the feature in Deno CLI right now. The data is correct.

**Comment by idanran** [comment]
> You need to pass `--unstable` to enable the feature in Deno CLI right now. The data is correct.

Not listed in the documentation as Unstable API.
