### ISSUE TITLE
api.MediaDevices.getDisplayMedia - Chrome on Linux doesn't have sound option when sharing tab

### ISSUE THREAD

**Issue by thucngyyen** [mdn/browser-compat-data#18315]
### What type of issue is this?

Browser bug (a bug with a feature that may impact site compatibility)

### What information was incorrect, unhelpful, or incomplete?

When sharing a tab, the screen is captured but the sound isn't. It doesn't even have the option to share sound (the share sound button)

### What did you expect to see?

Expect to see the share sound button (when sharing tab)

### Did you test this? If so, how?

I use different browser and it still doesn't have this option

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

NA

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Screen_Capture_API/Using_Screen_Capture

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.MediaDevices.getDisplayMedia`
* Report started: 2022-11-25T04:40:42.182Z

</details>

**Comment by queengooborg** [comment]
I'm unable to confirm a lack of support in Linux; the tab audio option was available for me.  It's possible that this used to be an issue and has since been fixed, or something to do with your specific distribution (Alsa vs. PulseAudio, for example).
