### ISSUE TITLE
css.at-rules.media.resolution - Now supported on Safari 16.0+?

### ISSUE THREAD

**Issue by andrerom** [mdn/browser-compat-data#18331]
### What type of issue is this?

Incorrect support data, page says unsupported in Safari.

### What information was incorrect, unhelpful, or incomplete?

Compat data says its is not supported by Safari, but according to [webkit bug](https://bugs.webkit.org/show_bug.cgi?id=78087) and [caniuse.com](https://caniuse.com/?search=resolution) it landed in Safari 16.0. However, as per last link, several relevant CSS features for resolution is still missing in Safari.

### What browsers does this problem apply to, if applicable?

Safari

### What did you expect to see?

Info on what is supported in Safari 16 and higher.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

MDN: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/resolution
webkit bug it refers to, now marked as resolved: https://bugs.webkit.org/show_bug.cgi?id=78087
caniuse: https://caniuse.com/?search=resolution

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/@media/resolution

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.at-rules.media.resolution`
* Report started: 2022-11-28T22:33:12.768Z

</details>

**Comment by gsnedders** [comment]
> However, as per last link, several relevant CSS features for resolution is still missing in Safari.

If you're looking at "types: &lt;resolution>: dpcm unit" etc., I think that's just more out of date data (`css.types.resolution`) in BCD.

**Comment by foolip** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/resolution was updated by @queengooborg in https://github.com/mdn/browser-compat-data/pull/18706 but https://developer.mozilla.org/en-US/docs/Web/CSS/resolution is still incorrect.

@gsnedders do you know if all of the units are supported?

**Comment by foolip** [comment]
Also, I don't really see the point of having split compat data here. @Elchi3 is there any history behind CSS types having their own BCD entries? At least this case seems a lot like dictionaries to me, that it would be better mixed into the concrete places that use each type.

**Comment by Elchi3** [comment]
> Also, I don't really see the point of having split compat data here. @Elchi3 is there any history behind CSS types having their own BCD entries? At least this case seems a lot like dictionaries to me, that it would be better mixed into the concrete places that use each type.

As it is often the case, the BCD structures are modeled after the MDN doc structures. I'm not an expert when it comes to the CSS docs, but I think these types are re-used a lot in CSS and so MDN choose to document them on their own pages. I think any sort of restructuring would be better as a discussion in a new issue.

**Comment by queengooborg** [comment]
This has been fixed in #18706!
