### ISSUE TITLE
css.types.color - Chrome (Android) supports Lab/Lch colors

### ISSUE THREAD

**Issue by Bonzey2416** [mdn/browser-compat-data#18357]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

I tested lab and lch parameter in Chrome Canary 110 and it works.

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

I tested lab(61% 92 -41) in background and it was pink. It worked.

### Did you test this? If so, how?

Yes at w3schools

### Do you have anything more you want to share?

![Screenshot_2022-12-02-08-58-30-778](https://user-images.githubusercontent.com/98016194/205255108-910bd2b8-a8e7-4354-94ff-2ea84cba235a.jpg)

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/color_value

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.types.color`
* Report started: 2022-12-02T08:54:55.081Z

</details>

**Comment by ai** [comment]
We need to add Firefox support for `oklch()`, `lch()`, etc too. Firefox Nightly already support them

https://twitter.com/argyleink/status/1623008014440726528

**Comment by WillsterJohnson** [comment]
CanIUse appears to have up to date info, Chrome 111 enabled them without flags (not tested).

https://caniuse.com/?search=lch

**Comment by queengooborg** [comment]
Fixed in #19068!
