### ISSUE TITLE
ResizeObserverEntry.contentBoxSize is no longer a single object in Firefox 

### ISSUE THREAD

**Issue by Ulisseus** [mdn/browser-compat-data#18370]
### What type of issue is this?

Other

### What information was incorrect, unhelpful, or incomplete?

Comment regarding [ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver#examples) Firefox implementation: ```      // Firefox implements `contentBoxSize` as a single content rect, rather than an array``` is no longer correct. 

### What browsers does this problem apply to, if applicable?

Firefox

### What did you expect to see?

No comment is necessary. 

### Did you test this? If so, how?

Used ResizeObserver in Firefox and checked  `entry.contentBoxSize` type. 

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://bugzilla.mozilla.org/show_bug.cgi?id=1599176
https://bugzilla.mozilla.org/show_bug.cgi?id=1689645

https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserverEntry/contentBoxSize#browser_compatibility
https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver

**Comment by queengooborg** [comment]
Hmm...this seems like a rendering issue rather than a data issue.  The two sections should be swapped so that the most recent one (with no note) is up at the top, but it isn't.

<img width="497" alt="Screenshot 2022-12-07 at 02 28 15" src="https://user-images.githubusercontent.com/5179191/206154814-ff3580d7-5dff-4468-b904-ceb519ceadff.png">

Could you open an issue in https://github.com/mdn/yari instead?  They'll be able to fix the rendering over there!

**Comment by Ulisseus** [comment]
> Hmm...this seems like a rendering issue rather than a data issue. The two sections should be swapped so that the most recent one (with no note) is up at the top, but it isn't.
Maybe I'm missing something, but other pages use the same layout with the previous version on top and the latest version is at the bottom. 
![Screenshot 2022-12-07 200931](https://user-images.githubusercontent.com/3845012/206245020-2b3f4758-5b3c-4548-8469-df9259a409e8.png)
https://developer.mozilla.org/en-US/docs/Web/API/Background_Synchronization_API

But you're right, I've used the wrong repository for this issue. I should have posted to https://github.com/mdn/content to report outdated example. 

Thanks.
