### ISSUE TITLE
api.HTMLFormElement.formdata_event - mark Firefox: Android as compatible 

### ISSUE THREAD

**Issue by kbrosnan** [mdn/browser-compat-data#18385]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Firefox: Android supports the HTMLFormElement: formdata event

### Did you test this? If so, how?

https://bugzilla.mozilla.org/show_bug.cgi?id=1804144#c2

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/formdata_event

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.HTMLFormElement.formdata_event`
* Report started: 2022-12-07T07:30:57.531Z

</details>

**Comment by queengooborg** [comment]
Fixed by #18695!
