### ISSUE TITLE
api.Window.frames - Safari returns DOM element instead of window with window.frames[i]

### ISSUE THREAD

**Issue by faizanakram99** [mdn/browser-compat-data#18390]
### What type of issue is this?

Browser bug (a bug with a feature that may impact site compatibility)

### What information was incorrect, unhelpful, or incomplete?

Safari returns DOM element instead of window with window.frames[i]

### What browsers does this problem apply to, if applicable?

Safari

### What did you expect to see?

Safari returns DOM element instead of window with window.frames[i]

### Did you test this? If so, how?

Browserstack

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Window/frames

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.Window.frames`
* Report started: 2022-12-07T15:57:12.421Z

</details>

**Comment by queengooborg** [comment]
I'm not able to confirm this; `window.frames[0]` is returning a Window object in Safari.
