### ISSUE TITLE
api.Client.postMessage - WebAssembly.Instance is not delivered

### ISSUE THREAD

**Issue by eustas** [mdn/browser-compat-data#18398]
### What type of issue is this?

Browser bug (a bug with a feature that may impact site compatibility)

### What information was incorrect, unhelpful, or incomplete?

`WebAssembly.Instance` documentation says that the object could be sent using (to `Worker`) `postMessage`.

`Worker` and `Client` have very similar explanation on the data that could be sent via `postMessage`.

However, when I send `WebAssembly.Instance` to `Client` the message is silently dropped (in Chrome 108).

It is unclear if it is correct behaviour.

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

Preferably `WebAssembly.Instance` should reach `Client`. Otherwise feature is greatly limited.

Alternatively documentation should state that unlike `Client.postMessage` does not deliver `WebAssembly.Instance` objects.

### Did you test this? If so, how?

demo html page

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Client/postMessage

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.Client.postMessage`
* Report started: 2022-12-08T18:11:40.505Z

</details>

**Comment by queengooborg** [comment]
The documentation doesn't say that a web assembly `Instance` object is transferable (and the spec doesn't either).  It's possible that it did at some point, but had been corrected for accuracy.
