### ISSUE TITLE
javascript.builtins.Intl.DateTimeFormat.DateTimeFormat - `timeZoneName` full support

### ISSUE THREAD

**Issue by dzonatan** [mdn/browser-compat-data#18405]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Full support of `timeZoneName` parameter in Node.js was added in `v17.0.0`, not `v0.12.0`.

### What browsers does this problem apply to, if applicable?

Node.js

### What did you expect to see?

A note about **partial support** (`short` and `long`) up to `node v16.18.1` and **full support** (`short`, `long`, `shortOffset`, `longOffset`, `shortGeneric`, `longGeneric`) from `node v17.0.0`.

### Did you test this? If so, how?

By running `new Intl.DateTimeFormat('en-US', { timeZoneName: 'longOffset' })` in both: 
- `node v16.18.1` (latest `v16`)  which throws `out of range` exception
- and `node v17.0.0` which works as expected.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V17.md#v8-95
https://v8.dev/blog/v8-release-95

### Do you have anything more you want to share?

I believe this partial/full support issue applies for the browsers as well, I just didn't have time to find the exact versions when they've landed this extension of `timeZoneName` formats.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `javascript.builtins.Intl.DateTimeFormat.DateTimeFormat`
* Report started: 2022-12-11T15:40:25.898Z

</details>
```[tasklist]
### Tasks
```

**Comment by anurag-roy** [comment]
Yes, same thing applies for other browsers as well. Some googling and searching gave me te following results:

- Chrome says [full support was released in v95](https://chromestatus.com/feature/4506375298220032)
- Safari Technology Preview added this in [release 132](https://webkit.org/blog/11971/release-notes-for-safari-technology-preview-132/) and Safari in [15.4](https://developer.apple.com/documentation/safari-release-notes/safari-15_4-release-notes)

Would be great if the info was for these were corrected. Thanks!
