### ISSUE TITLE
javascript.builtins.Intl.NumberFormat - number param string value is decimal (not Number) supported in Chrome 108

### ISSUE THREAD

**Issue by mahnunchik** [mdn/browser-compat-data#18447]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Chrome 108 supports `number param string value is decimal (not Number)` in Intl.NumberFormat.

Test case:

```js
Intl.NumberFormat('en', { maximumFractionDigits: 18 }).format('1.01234567890123456789');
// correct return value is '1.012345678901234568'
```

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

Chrome 108 supports that feature.

### Did you test this? If so, how?

I've tested on:

Chrome 108 - supported ✅ 
```js
Intl.NumberFormat('en', { maximumFractionDigits: 18 }).format('1.01234567890123456789');
'1.012345678901234568'
```

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `javascript.builtins.Intl.NumberFormat`
* Report started: 2022-12-16T14:33:37.563Z

</details>

**Comment by mahnunchik** [comment]
Any news?

**Comment by Elchi3** [comment]
Tanks for your issue! This will be fixed by https://github.com/mdn/browser-compat-data/pull/20262
