### ISSUE TITLE
api.BroadcastChannel -  Unable to communicate between IFRAME and opened popup

### ISSUE THREAD

**Issue by maamoon95** [mdn/browser-compat-data#18471]
### What type of issue is this?

Browser bug (a bug with a feature that may impact site compatibility)

### What information was incorrect, unhelpful, or incomplete?

using Broadcast Channel to communicate using iframe and popup is not working on phone devices and Safari browser (tested with playwright), the BroadCastChannel is found in global scope but it's not sending nor receiving events in iframe -> popup communication with the same origin 

### What did you expect to see?

I expected to be able to send and receive messages through the broadcast channels between popup and iframe in mobile devices and Safari

### Did you test this? If so, how?

tests were done using e2e testing library,
I controlled the domains as follows:
let's say we have domain1 and domain2;
I created 3 pages :
Page 1:  index (domain1) -> includes click button to open page 3 and iframe of page 2
Page 2: iframe Content (domain2) -> include BroadCastChannel with name ('test-com') and this channel sends events every 3 seconds and listens for events as same.
Page 3: popup page (domain2) ->  include BroadCastChannel with name ('test-com') and this channel sends events every 3 seconds and listens for events as same.
... 
So the expected behavior is to be able to run communication between Page 2 and Page 3 
and tests failed
Note that tests were done with most modern browsers at the time of this issue creation

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

No

### Do you have anything more you want to share?

No

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Broadcast_Channel_API

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.BroadcastChannel`
* Report started: 2022-12-23T22:23:42.136Z

</details>

**Comment by queengooborg** [comment]
I am able to use BroadcastChannel across popups, new tabs and iframes on the same origin with no problems.  Without seeing the code you are using, it's hard to say whether this is an actual browser issue or a development issue.  It's possible that your testing libraries are also causing issues; I've noticed some libraries have odd effects on pages.
