### ISSUE TITLE
api.Document.requestStorageAccess - <SUMMARIZE THE PROBLEM>

### ISSUE THREAD

**Issue by ygag-kishore** [mdn/browser-compat-data#18490]
### What type of issue is this?

Browser bug (a bug with a feature that may impact site compatibility)

### What information was incorrect, unhelpful, or incomplete?

Browser is not using storage access api on ios devices specifically using firefox the same works on the safari

### What browsers does this problem apply to, if applicable?

Firefox

### What did you expect to see?

Im expecting my home page to see but it goes to 403 because session is not established

### Did you test this? If so, how?

IN real device. 

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

No

### Do you have anything more you want to share?

No

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Storage_Access_API

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.Document.requestStorageAccess`
* Report started: 2022-12-27T12:39:17.039Z

</details>

**Comment by queengooborg** [comment]
This sounds vaguely like a web development issue rather than a browser issue.
