### ISSUE TITLE
mathml.elements.math - Compat table - Chrome 109

### ISSUE THREAD

**Issue by fonsp** [mdn/browser-compat-data#18499]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Chrome 109 (currently beta) is adding support for MathML Core 🎉 https://chromestatus.com/feature/5240822173794304

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/MathML

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `mathml.elements.math`
* Report started: 2022-12-29T17:45:22.316Z

</details>

**Comment by fred-wang** [comment]
Mention of Chrome 109 support was updated in https://github.com/mdn/browser-compat-data/pull/18610

Currently https://github.com/mdn/browser-compat-data/blob/106f28d4f7131c3ba2e5e9f326f0708abd68dfa2/mathml/elements/math.json shows the following:

"version_added": "109"

"version_added": "80",
"flags": { "name": "#enable-experimental-web-platform-features", }

"version_added": "24",
"version_removed": "25",

I guess what "math element is supported" is a bit unclear, but at least the very first patch of the new implementation was https://chromiumdash.appspot.com/commit/8b8b60fb32ffcc41c3ae41224389822969e172f3 (M80) ; and the mspace support, which allows to render something interesting, is https://chromiumdash.appspot.com/commit/9ead940b1b7ad68132fc7b49de4675e3a87826a8 (M81)

So not sure what you mean by "Incorrect support data (ex. Chrome says "86" but support was added in "40")". Is there still something to fix?
