### ISSUE TITLE
api.DataTransferItem.type - <SUMMARIZE THE PROBLEM>

### ISSUE THREAD

**Issue by Chidiebere95** [mdn/browser-compat-data#18527]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

iT's not compatitble on safari

### What did you expect to see?

safari

### Did you test this? If so, how?

yeah

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/DataTransferItem/type

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.DataTransferItem.type`
* Report started: 2023-01-04T05:04:39.214Z

</details>

**Comment by queengooborg** [comment]
Can you please add a summary to the issue title for this issue, as well as provide a description on _how_ you tested lack of support, including any code samples you used?

**Comment by queengooborg** [comment]
I'm closing this as spam because I cannot confirm a lack of support and the details have not been properly filled out in the issue template.
