### ISSUE TITLE
html.elements.input.type_datetime-local - <SUMMARIZE THE PROBLEM>

### ISSUE THREAD

**Issue by victormauadieventura** [mdn/browser-compat-data#18535]
### What type of issue is this?

Browser bug (a bug with a feature that may impact site compatibility)

### What information was incorrect, unhelpful, or incomplete?

Doesn't have support for firefox, the option to put the time doesn't appear in the calendar.

### What browsers does this problem apply to, if applicable?

Firefox

### What did you expect to see?

The calendar with the option of hours to select

### Did you test this? If so, how?

Testing in different browsers

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `html.elements.input.type_datetime-local`
* Report started: 2023-01-04T13:56:17.976Z

</details>

**Comment by queengooborg** [comment]
Could you fill out the issue title with a summary, as well as provide test code and screenshots of behavior in different browsers?

**Comment by queengooborg** [comment]
Closing because there hasn't been any response and more info is needed to determine whether this is an actual browser issue or just a coding issue.
