### ISSUE TITLE
api.GeolocationPositionError - <Geolocation has been disabled in this document by permissions policy.>

### ISSUE THREAD

**Issue by Sadman211** [mdn/browser-compat-data#18567]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Geolocation has been disabled in this document by permissions policy.

### What browsers does this problem apply to, if applicable?

Chrome , Legacy Edge (12-18)

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/GeolocationPositionError

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.GeolocationPositionError`
* Report started: 2023-01-07T07:19:36.697Z

</details>

**Comment by queengooborg** [comment]
This sounds like a development problem, which we cannot help with.  We recommend checking StackOverflow for answers to this question.
