### ISSUE TITLE
api.HTMLIFrameElement.contentWindow - <SUMMARIZE THE PROBLEM>

### ISSUE THREAD

**Issue by 1557812300** [mdn/browser-compat-data#18579]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

chrome can`t use it
Uncaught TypeError: Cannot read properties of undefined (reading 'contentWindow')

### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/API/HTMLIFrameElement/contentWindow

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.HTMLIFrameElement.contentWindow`
* Report started: 2023-01-09T06:54:45.260Z

</details>

**Comment by queengooborg** [comment]
That error message states that your `iframe` element is `undefined`, so you have a coding error.  For coding help, please check out StackOverflow or other similar resources, as this is not the place to ask for coding help.
