### ISSUE TITLE
api.CanvasRenderingContext2D.drawImage ImageBitmap source inaccurate for Safari

### ISSUE THREAD

**Issue by chocolatkey** [mdn/browser-compat-data#18618]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

The data regarding Safari seems to be inaccurate, as I am able to use an ImageBitmap as the source of a drawImage call for a 2d canvas context. I'm not sure how far back in Safari this goes, as I don't have an older version available. But at the very least it's the case in 16.1 where it's currently shown as "Not supported".

Opened [in the caniuse repo](https://github.com/Fyrd/caniuse/issues/6555) originally

### What browsers does this problem apply to, if applicable?

Safari

### Did you test this? If so, how?

I've made an example here: https://jsfiddle.net/chocolatkey/jf9b5hoy

### Do you have anything more you want to share?

The example running in Safari:

![image](https://user-images.githubusercontent.com/13407784/211705557-c4045e33-f017-4e07-bdfe-92952e6dc31a.png)

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/drawImage

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.CanvasRenderingContext2D.drawImage`
* Report started: 2023-01-11T02:40:57.651Z

</details>

**Comment by queengooborg** [comment]
I added [test code into the collector project](https://github.com/GooborgStudios/mdn-bcd-collector/commit/b3887ab995263ccd9e410bc4fbeda5d039709003) to automatically test this.  This will be updated in the next collector update wave!

**Comment by davl3232** [comment]
Hey guys, this is the case with 
drawImage for svg source images:
https://caniuse.com/mdn-api_canvasrenderingcontext2d_drawimage_svgimageelement_source_image

Got svg to render with drawImage in safari 15.6.1
