### ISSUE TITLE
api.SpeechRecognition - <SUMMARIZE THE PROBLEM>

### ISSUE THREAD

**Issue by efeakaroz13** [mdn/browser-compat-data#18629]
### What type of issue is this?

Other

### What information was incorrect, unhelpful, or incomplete?

Hello, on the website as I see this feature is incompatible with Firefox. But it is on Mozilla's website. Also chrome even started to support speech recognition at version 33 according to you. I am so confused. Can you give more information?

https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition

### What browsers does this problem apply to, if applicable?

Firefox

### What did you expect to see?

Speech recognition support.

### Did you test this? If so, how?

I didn't.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition

### Do you have anything more you want to share?

https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.SpeechRecognition`
* Report started: 2023-01-11T18:56:27.596Z

</details>

**Comment by queengooborg** [comment]
MDN Web Docs (AKA developer.mozilla.org) is a documentation effort hosted by Mozilla and maintained by so many organizations and individuals to document the features of the world wide web.  This includes features that are not available in Firefox, such as the Speech Recognition API.  See https://developer.mozilla.org/about for more details on what MDN is about.
