### ISSUE TITLE
html.global_attributes.inputmode - <SUMMARIZE THE PROBLEM>

### ISSUE THREAD

**Issue by sepezz** [mdn/browser-compat-data#18623]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Safari says not supported but it is [https://caniuse.com/input-inputmode](https://caniuse.com/input-inputmode)

### What browsers does this problem apply to, if applicable?

Safari

### What did you expect to see?

Green tick

### Did you test this? If so, how?

Yes in safari

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://caniuse.com/input-inputmode

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inputmode

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `html.global_attributes.inputmode`
* Report started: 2023-01-11T09:19:07.914Z

</details>

**Comment by queengooborg** [comment]
Our data matches the data from CanIUse, where Safari iOS is supported (but not Safari Desktop).  If you're seeing support in Safari Desktop, please provide additional details as to _how you tested support,_ including test code

**Comment by myakura** [comment]
> Our data matches the data from CanIUse, where Safari iOS is supported (but not Safari Desktop). If you're seeing support in Safari Desktop, please provide additional details as to how you tested support, including test code

at least `'inputMode' in HTMLInputElement.prototype` returns true in macOS Safari.
