### ISSUE TITLE
api.Window.afterprint_event - <SUMMARIZE THE PROBLEM>

### ISSUE THREAD

**Issue by jobinspr** [mdn/browser-compat-data#18661]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

    window.print();  
window.onafterprint = function () {
     window.location="printallcard.php?id=???";

is not working on firefox and chrome devices 

### Did you test this? If so, how?

After printing and also cancel printing

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Window/afterprint_event

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.Window.afterprint_event`
* Report started: 2023-01-16T12:43:44.818Z

</details>

**Comment by queengooborg** [comment]
For an event that has been around as long as this one, it's hard to imagine a lack of support.  Without more details, we aren't able to determine if this is truly a lack of support, or simply a development issue.
