### ISSUE TITLE
css.selectors.nth-child - Chromium M111 will support selectors

### ISSUE THREAD

**Issue by sesse** [mdn/browser-compat-data#18663]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Chromium will support in :nth-child(… of S) from M111.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://chromium-review.googlesource.com/c/chromium/src/+/4166964

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-child

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.selectors.nth-child`
* Report started: 2023-01-16T13:09:16.002Z

</details>

**Comment by queengooborg** [comment]
We'll revisit this once it has shipped.  At the moment, [Chrome 111 is an estimated milestone](https://chromestatus.com/feature/5144225077788672), and we have had bad luck with adding version numbers for Chrome before features ship.

**Comment by sesse** [comment]
FWIW, I wrote the feature and committed the change to make it stable; I'll let you know if the timeline should slip. :-)

**Comment by krystian3w** [comment]
https://github.com/mdn/browser-compat-data/issues/20078
