### ISSUE TITLE
webextensions.api.dom.openOrClosedShadowRoot - content shift resulted in broken BCD table

### ISSUE THREAD

**Issue by tlylt** [mdn/browser-compat-data#18664]
### What type of issue is this?

Other

### What information was incorrect, unhelpful, or incomplete?

The changes done in https://github.com/mdn/browser-compat-data/pull/17707 moves the `openOrClosedShadowRoot` from `api.Element` to `webextensions.api.dom`, which causes the mdn docs page to show no BCD table:
- https://developer.mozilla.org/en-US/docs/Web/API/Element/openOrClosedShadowRoot#browser_compatibility
![image](https://user-images.githubusercontent.com/41845017/212729432-4438de07-532a-4cb1-90c5-bd12e2e767c1.png)

The page [here](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Browser_support_for_JavaScript_APIs#dom) shows the BCD table correctly, however, the page linked is [broken](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/dom/openOrClosedShadowRoot)
![image](https://user-images.githubusercontent.com/41845017/212729608-8e70aca9-8d8a-40ff-b847-174b03d26b24.png)
![image](https://user-images.githubusercontent.com/41845017/212729703-8d2ceb2d-2630-4137-ba68-5ff3bf9ee6e6.png)

**Comment by queengooborg** [comment]
Could you file an issue in https://github.com/mdn/content?  This is more of an issue that the content changes have not yet been performed.

**Comment by tlylt** [comment]
> Could you file an issue in [mdn/content](https://github.com/mdn/content)? This is more of an issue that the content changes have not yet been performed.

Sure
