### ISSUE TITLE
VideoEncoder is unsupported in Android Chrome

### ISSUE THREAD

**Issue by purplekidlouis** [mdn/browser-compat-data#18676]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/WebCodecs_API

### What information was incorrect, unhelpful, or incomplete?

Hi, I just test VideoEncoder with `if ('VideoEncoder' in window) {console.log('VideoEncoder is supported');}` in Android Chrome, Edge, Opera. It seems to be unsupported in all the mobile browsers. It doesn't match the support form.
The version of Android Chrome is 108.0.5359.128.

### What did you expect to see?

If there is a correct way to call VideoEncoder, welcome to point out, thanks!

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/webcodecs_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebCodecs_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/webcodecs_api/index.md
* Last commit: https://github.com/mdn/content/commit/f7dae62645a2c735ed6f6ed63f664bf279fdfc4b
* Document last modified: 2022-09-09T05:19:45.000Z

</details>

**Comment by queengooborg** [comment]
This seems to be working fine when testing Chrome Android on BrowserStack:

<img width="539" alt="Screenshot 2023-01-20 at 10 40 46" src="https://user-images.githubusercontent.com/5179191/213676083-4ba9ba92-562b-4c08-8c2d-e0676d8f5c07.png">

**Comment by hamishwillee** [comment]
VideoEncoder is not defined on the Window object, which is why your test code fails.
