### ISSUE TITLE
api.WEBGL_compressed_texture_pvrtc - Missing data for Firefox & Safari

### ISSUE THREAD

**Issue by SuperSodaSea** [mdn/browser-compat-data#18692]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

This issue comes when I am trying to add [`WEBGL_compressed_texture_pvrtc`](https://github.com/mdn/browser-compat-data/commits/main/api/WEBGL_compressed_texture_pvrtc.json) to [microsoft/TypeScript-DOM-lib-generator](https://github.com/microsoft/TypeScript-DOM-lib-generator).

We used to have `{ "version_added": "18" }` for `firefox_android`. However, in #14858, the `firefox_android` become `{ "version_added": false }` for some reason. I think this might be an mistake and we should add it back.

For Safari, I found [this Bugzilla](https://bugs.webkit.org/show_bug.cgi?id=217110) and [this commit](https://github.com/WebKit/WebKit/commit/83e24ae47382791633402600fc43daac635c598d), so Safari (on devices that support PVRTC) should also support `WEBGL_compressed_texture_pvrtc`. I don't have an iOS device myself, so if anyone can test this, I will appreciate it.

### What browsers does this problem apply to, if applicable?

Firefox, Safari

### What did you expect to see?

Correct compatibility data of `WEBGL_compressed_texture_pvrtc` for `firefox_android` and `safari_ios`.

### Did you test this? If so, how?

I don't have an Android device with PowerVR GPU or an iOS device, so I can't test this myself. If anyone have such device, I hope you can help me.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/WEBGL_compressed_texture_pvrtc

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.WEBGL_compressed_texture_pvrtc`
* Report started: 2023-01-20T10:49:32.941Z

</details>

**Comment by queengooborg** [comment]
Firefox Android does not have support, so that's accurate.  Safari iOS does seem to have support however.
