### ISSUE TITLE
api.Navigator.clipboard - not supporting latest chrome version

### ISSUE THREAD

**Issue by anupamknw** [mdn/browser-compat-data#18712]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

It's not working in chrome latest version.
        console.log(await navigator.clipboard.readText());
        
Getting error - 
[Chrome 109.0.0.0 darwin #0-0] ReferenceError: navigator is not defined        

Version 109.0.5414.87 (Official Build) (x86_64)

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

I was expecting clipboard text.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Navigator/clipboard

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.Navigator.clipboard`
* Report started: 2023-01-22T12:13:36.897Z

</details>

**Comment by queengooborg** [comment]
Your console error suggests a development issue: "navigator is not defined".  You're either overwriting `navigator` or using a scope that does not have the Navigator API available.
