### ISSUE TITLE
Add BCD for CSS Gradient Interpolation Color Spaces

### ISSUE THREAD

**Issue by jensimmons** [mdn/browser-compat-data#18719]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

CSS Gradient Interpolation Color Spaces is a thing. It'd be great for it to be included in BCD. 

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://css-tricks.com/color-spaces-for-more-interesting-css-gradients/

**Comment by queengooborg** [comment]
Are the features of this spec supported in any browser's stable or preview releases?

**Comment by nt1m** [comment]
@queengooborg They have been supported since Safari 16.2 and I think at least Chrome Canary supports them (not sure if it got supported earlier).

**Comment by flying-sheep** [comment]
Support in firefox is tracked in https://bugzilla.mozilla.org/show_bug.cgi?id=1824041

**Comment by queengooborg** [comment]
As far as I can tell, the data for this is all tracked in BCD now -- see #9489, #18827, #19426 and #19244.

If there's anything that I'm overlooking, please don't hesitate to let me know (preferably by opening a new issue indicating which feature was missed)!
