### ISSUE TITLE
css.properties.backdrop-filter - Invalid property name

### ISSUE THREAD

**Issue by Gitoffthelawn** [mdn/browser-compat-data#18722]
### What type of issue is this?

Browser bug (a bug with a feature that may impact site compatibility)

### What information was incorrect, unhelpful, or incomplete?

In Firefox 109.0, attempting to use `backdrop-filter` results in an `Invalid property name` error in devtools.

Note that the pref `layout.css.backdrop-filter.enabled` is set to `true`.

Example page:
https://developer.mozilla.org/docs/Web/CSS/backdrop-filter

It appears this could be a Firefox bug, or incorrect compatibility data on Mozilla's website.

### What browsers does this problem apply to, if applicable?

Firefox

### What did you expect to see?

HTML elements properly change appearance due to `backdrop-filter`.

### Did you test this? If so, how?

By going to https://developer.mozilla.org/docs/Web/CSS/backdrop-filter and then using Firefox's devtools to examine the example.  Previously tried adding `backdrop-filter` to elements on other pages.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://developer.mozilla.org/docs/Web/CSS/backdrop-filter

### Do you have anything more you want to share?

Support Firefox for a free and open web.  Hopefully Firefox devs can, in turn, support all of CSS3.

### MDN URL

https://developer.mozilla.org/docs/Web/CSS/backdrop-filter

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.backdrop-filter`
* Report started: 2023-01-24T02:10:38.767Z

</details>

**Comment by queengooborg** [comment]
I'm going to close this in favor of #19052 and mark this as a duplicate (even though this is older), since the other issue has more activity.

**Comment by Gitoffthelawn** [comment]
Thank you for linking to the other issue from this one.
