### ISSUE TITLE
css.properties.offset-path - Safari compatibility seems to be wrong

### ISSUE THREAD

**Issue by Discostu36** [mdn/browser-compat-data#18729]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

The page states that Safari doesn't support path() function as a value. But the example on the page uses it, and it does work on Safari for iOS 16.2.

### What browsers does this problem apply to, if applicable?

Safari

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Motion_Path

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.offset-path`
* Report started: 2023-01-24T14:43:17.794Z

</details>

**Comment by queengooborg** [comment]
Data updated in #21030!
