### ISSUE TITLE
css.properties.overscroll-behavior - wrong version reported for chrome android

### ISSUE THREAD

**Issue by Cfarjanel** [mdn/browser-compat-data#18721]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Hello, the chrome for android table reports the support since version 63 but it seems to be available only since version 109 for mobile devices.

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

The right version listed under chrome android

### Did you test this? If so, how?

The **overflow-behavior: none** property was not working in my mobile application (based on webview 108), upon checking the supported versions I found 63 on the mdn documentation but 109 on other websites (caniuse, csstricks)

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.overscroll-behavior`
* Report started: 2023-01-23T16:38:05.419Z

</details>

**Comment by queengooborg** [comment]
This is a misread of the data on CanIUse.  CanIUse only displays the most recent browser versions for mobile browsers (with some exceptions), so it _only_ shows Chrome Android 109 (or currently, 119).  It doesn't keep track of data for older versions like we do.  Chrome Android 63 is accurate.
