### ISSUE TITLE
api.Document.styleSheetSets - <SUMMARIZE THE PROBLEM>

### ISSUE THREAD

**Issue by moduller** [mdn/browser-compat-data#18735]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Not exactly sure what is going on but these errors are a lot and need some help to fix them

[console-export-2023-1-24_18-0-34.txt](https://github.com/mdn/browser-compat-data/files/10495497/console-export-2023-1-24_18-0-34.txt)

### What did you expect to see?

All errors are shown in doc

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Document/styleSheetSets

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.Document.styleSheetSets`
* Report started: 2023-01-25T01:59:37.045Z

</details>

**Comment by queengooborg** [comment]
This is not a help forum and we cannot provide development assistance.  Please refer to a website like StackOverflow for development help.
