### ISSUE TITLE
http.headers.Sec-GPC - Chrome sends sec-gpc: 1 however table says Chrome does not support this feature

### ISSUE THREAD

**Issue by ptdecker** [mdn/browser-compat-data#18741]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

The browser compatibility table for sec-gpt indicates that Chrome does not support this experimental and non-standards track feature.  However, in inspecting the request header fields being sent by Chrome Version "109.0.5414.87 (Official Build) (arm64)", I see `sec-gpc: 1` in the headers.

```text
Request: ["GET / HTTP/1.1", "Host: 127.0.0.1:6502", "Connection: keep-alive", "Cache-Control: max-age=0", "sec-ch-ua: \"Not_A Brand\";v=\"99\", \"Google Chrome\";v=\"109\", \"Chromium\";v=\"109\"", "sec-ch-ua-mobile: ?0", "sec-ch-ua-platform: \"macOS\"", "DNT: 1", "Upgrade-Insecure-Requests: 1", "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36", "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9", "Sec-Fetch-Site: none", "Sec-Fetch-Mode: navigate", "Sec-Fetch-User: ?1", "Sec-Fetch-Dest: document", "Accept-Encoding: gzip, deflate, br", "Accept-Language: en-US,en;q=0.9", "sec-gpc: 1"]
```

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

If Chrome truly didn't support this feature, I would not expect to see it in Chrome's header

### Did you test this? If so, how?

I determined this while working through Chapter 20 of The Rust Programming Language book which implements a basic web server.  Listing 20-2 provides a server that does nothing more but dump to the console the header it receives in TCP requests.  When connecting to this server from Chrome, I observed the headers listed above.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Sec-GPC

### Do you have anything more you want to share?

Server code used:

```rust
use std::{
    io::{prelude::*, BufReader},
    net::{TcpListener, TcpStream},
};

fn main() {
    let listener = TcpListener::bind("127.0.0.1:6502").unwrap();
    for stream in listener.incoming() {
        let stream = stream.unwrap();
        handle_connection(stream);
    }
}

fn handle_connection(mut stream: TcpStream) {
    let buf_reader = BufReader::new(&mut stream);
    let http_request: Vec<_> = buf_reader
        .lines()
        .map(|result| result.unwrap())
        .take_while(|line| !line.is_empty())
        .collect();
    println!("Request: {:?}", http_request);
}

```

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Sec-GPC

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `http.headers.Sec-GPC`
* Report started: 2023-01-26T00:54:11.106Z

</details>

**Comment by myakura** [comment]
> If Chrome truly didn't support this feature, I would not expect to see it in Chrome's header

Or, that could be some extensions modifying request headers.

I see the feature request https://bugs.chromium.org/p/chromium/issues/detail?id=1171730 still be open. There's a CL for supporting GPC https://chromium-review.googlesource.com/c/chromium/src/+/4177061 but those patches were abandoned.

**Comment by hugorodgerbrown** [comment]
I've just checked this (had same question) - and in my case (Chrome 120.0.6099.129) it is the EFF Privacy Badger extension setting the request header. With the extension disabled / removed, `Sec-GCP` is not set.

In the end I found it in the PB settings:

<img width="814" alt="Screenshot 2023-12-29 at 17 04 32" src="https://github.com/mdn/browser-compat-data/assets/200944/a7c63844-fe04-46e2-af6e-0edb5767a9d3">

**Comment by hamishwillee** [comment]
@hugorodgerbrown Thanks. Chrome doesn't support the feature - the extension does. We document what the "vanilla" browser supports not what any possible configuration of extensions might.

**Comment by ptdecker** [comment]
Thank you, @hamishwillee, @hugorodgerbrown, and @myakura !   This explains the issue and I will close this submission.  It shows my ignorance that I did not think to suspect extensions as the culprit.
