### ISSUE TITLE
css.selectors.-webkit-scrollbar-thumb - Background color for scrollbar thumb is not work on safari and chrome in IOS device

### ISSUE THREAD

**Issue by MTaimoor79** [mdn/browser-compat-data#18754]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

There is no support for scrollbar thumb background color on the latest version of chrome and safari on IOS devices.background-color

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet), Safari

### What did you expect to see?

I expect to see the updated scroll background color on changing in CSS.

### Did you test this? If so, how?

I test this in iPhone 14 pro max.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.selectors.-webkit-scrollbar-thumb`
* Report started: 2023-01-27T06:22:59.167Z

</details>

**Comment by queengooborg** [comment]
If you look at the compatibility table, you'll notice there's an asterisk underneath Safari iOS.  This indicates that there is a compatibility note that may affect your website.

**Comment by lukewarlow** [comment]
As @queengooborg said the support data correctly shows that ::-webkit-scrollbar is supported but only for `display: none`, and ::-webkit-scrollbar-thumb is specifically noted as no longer supported on Safari for iOS. As such this issue can be closed.
