### ISSUE TITLE
css.properties.justify-content - `start` and `end` supported

### ISSUE THREAD

**Issue by spacecakes** [mdn/browser-compat-data#18756]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

It says `start` and `end` are not supported values in Flex contexts for Safari, but they are.
Demo here: https://codepen.io/spacescakes/pen/ExppdON?editors=1100

### What browsers does this problem apply to, if applicable?

Safari

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/justify-content

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.justify-content`
* Report started: 2023-01-27T07:20:59.680Z

</details>

**Comment by queengooborg** [comment]
Could you provide test code demonstrating these values working in Safari?

**Comment by spacecakes** [comment]
> Could you provide test code demonstrating these values working in Safari?

Hi. I guess like this? https://codepen.io/spacescakes/pen/ExppdON?editors=1100

**Comment by queengooborg** [comment]
Thanks for providing the test code and confirming that the data has been updated -- looks like this was fixed in #18399!
