### ISSUE TITLE
css.properties.background-position-x - Experimental now due to unsupported properties

### ISSUE THREAD

**Issue by estelle** [mdn/browser-compat-data#18809]
### What type of issue is this?

Other

### What information was incorrect, unhelpful, or incomplete?

`background-position-x` and `background-position-y` are back to experimental and no longer in the published specification due to newer unsupported property values. They have been removed from https://drafts.csswg.org/css-backgrounds/#background-position

You will find both, along with `background-position-inline` and `background-position-block` at https://w3c.github.io/csswg-drafts/css-backgrounds-4/#background-position-longhands, with all four being worked on.

BCD says there is FF support, but I assume that is no longer the case for all values.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/background-position-x

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.background-position-x`
* Report started: 2023-02-01T23:37:40.502Z

</details>

**Comment by queengooborg** [comment]
Experimental status in BCD isn't defined by spec implementation status, rather by browser support.
