### ISSUE TITLE
html.elements.a.text_fragments - Supported on Safari

### ISSUE THREAD

**Issue by snowsign** [mdn/browser-compat-data#18818]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

While I am unable to verify the exact browser versions the "text fragments" feature became supported, I can confirm that it is functional in Safari 16.2 on both macOS and iOS. On macOS Safari, the FragmentDirective API and ::target-text CSS selector remain nonfunctional. I have not tested either of these additional features on iOS Safari.

Versions tested: macOS 13.1 (Ventura), iOS 16.2

### What browsers does this problem apply to, if applicable?

Safari

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

[Problematic MDN Page](https://developer.mozilla.org/en-US/docs/Web/Text_fragments#browser_compatibility:~:text=html.elements.a.text_fragments)

The above link utilizes a text fragment for convenience. 

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Text_fragments

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `html.elements.a.text_fragments`
* Report started: 2023-02-05T03:49:38.674Z

</details>

**Comment by snowsign** [comment]
While I haven't been able to find many sources discussing this, [a "gadget hacks" article](https://ios.gadgethacks.com/how-to/your-iphones-safari-app-includes-hidden-feature-every-web-browser-needs-and-no-one-is-talking-about-it-0385203/) claims this feature was introduced in Safari 16.1

**Comment by tkindy** [comment]
[The release notes for Safari 16.1](https://developer.apple.com/documentation/safari-release-notes/safari-16_1-release-notes#Web-API) state, "Added support for Scroll to Text Fragment."
