### ISSUE TITLE
content-visibility - not shipped in Firefox yet

### ISSUE THREAD

**Issue by myakura** [mdn/browser-compat-data#18849]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

They are marked as shipped in Firefox.

- https://github.com/mdn/browser-compat-data/blob/54f23092380d63f193c3b10259c04ad2c67ef51d/css/properties/content-visibility.json#L14-L16
- https://github.com/mdn/browser-compat-data/blob/54f23092380d63f193c3b10259c04ad2c67ef51d/api/ContentVisibilityAutoStateChangedEvent.json#L13-L15
- https://github.com/mdn/browser-compat-data/blob/54f23092380d63f193c3b10259c04ad2c67ef51d/api/Element.json#L3166-L3168

But those features are still gated behind the `layout.css.content-visibility.enabled` pref, which hasn't been set true yet.
https://hg.mozilla.org/mozilla-central/file/7ec889d035f378a40ffcd64a9eda728ac9f5bb87/modules/libpref/init/StaticPrefList.yaml#l8336

The bug for implementing `content-visibility` isn't marked as FIXED.
https://bugzilla.mozilla.org/show_bug.cgi?id=1660384

### What browsers does this problem apply to, if applicable?

Firefox

### What did you expect to see?

They are not shipped but implemented behind a pref.

### Did you test this? If so, how?

1. open Firefox Developer Tools
2. type `CSS.supports('content-visibility: auto')` in the Console
3. check out the returned value

or 

1. open `about:config`
2. type `layout.css.content-visibility.enabled`
3. check out the value next to the flag

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://bugzilla.mozilla.org/show_bug.cgi?id=1660384

**Comment by myakura** [comment]
I'm willing to write a PR; however, there is a name change to the `contentvisibilityautochanged` event that I'm working on fixing (#18848). I'd like to update Firefox status after the PR lands.

**Comment by Elchi3** [comment]
cc @hamishwillee 
https://github.com/mdn/content/issues/23687

**Comment by hamishwillee** [comment]
Thanks @Elchi3 @myakura I'm going to do a separate PR for this - since your PR just changes the name and spec URL this should be possible to merge in either order.
