### ISSUE TITLE
css.at-rules.font-face - font-feature-settings seems supported in Safari

### ISSUE THREAD

**Issue by splewako** [mdn/browser-compat-data#18863]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Browser compatibility data suggests that Safari doesn't support _font-feature-settings_ in _font-face_ but Safari 16.3 seems to support it.

### What browsers does this problem apply to, if applicable?

Safari

### What did you expect to see?

Safari marked as supporting _font-feature-settings_

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.at-rules.font-face`
* Report started: 2023-02-09T13:46:43.600Z

</details>

**Comment by queengooborg** [comment]
Fixed in #21262!
