### ISSUE TITLE
html.elements.a.text_fragments - <SUMMARIZE THE PROBLEM>

### ISSUE THREAD

**Issue by uldo** [mdn/browser-compat-data#18905]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Feature is supported (at least) in Safari 16.2

### What browsers does this problem apply to, if applicable?

Safari

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Text_fragments

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `html.elements.a.text_fragments`
* Report started: 2023-02-13T18:41:30.534Z

</details>

**Comment by queengooborg** [comment]
Hi there, could you please provide supporting evidence for support in Safari 16.2?  This could be test code, release notes or otherwise!

**Comment by queengooborg** [comment]
Closing because there has been no response.
