### ISSUE TITLE
navigator.MediaDevices.getUserMedia - This function is not supported in iOS 16.3.1 on iPhone Xs, iPhone SE (3rd gen)

### ISSUE THREAD

**Issue by Baldur10** [mdn/browser-compat-data#18920]
### What type of issue is this?

Browser bug (a bug with a feature that may impact site compatibility)

### What information was incorrect, unhelpful, or incomplete?

15/02/2023

iOS 16.3.1 does not support the full specification of the Media Recorder API on certain devices. The MediaDevices interface is absent.

<img width="1269" alt="ios_16_3_1_iPhone" src="https://user-images.githubusercontent.com/43034213/218972452-f1c91eed-de17-48d1-a177-a199fd807a42.png">

Similar results with iOS 16.2 on the iPhone Xs (via simulator)

<img width="1001" alt="ios_16_2_xs_simulator" src="https://user-images.githubusercontent.com/43034213/218984491-ce37aeca-c8f8-485d-823a-10e0c2c47da5.png">

This seems an oversight as iOS 16.2 seems to support the aformentioned interface just fine on the iPhone 14 pro max.

<img width="1432" alt="ios_16_2_simulator" src="https://user-images.githubusercontent.com/43034213/218974941-35d79f60-4962-4c63-aab8-cc30f47395ab.png">

I can confirm that it is working as intended in MacOs Ventura 13.1

<img width="848" alt="macos_13_1" src="https://user-images.githubusercontent.com/43034213/218976049-9d2a995e-c793-4e79-a350-d835c1f59591.png">

All 3 devices are on the same version of webkit, i.e, 605.1.15.

### What browsers does this problem apply to, if applicable?

Safari

### What did you expect to see?

Updated Compability chart

### Did you test this? If so, how?

Tested on 2 physical devices:
Macbook Air: MacOs 13.1
iPhone XS: iOS 16.3.1

and 2 virtual device:
iPhone 14 pro max: iOS 16.2 (via Simulator)
iPhone XS: iOS 16.2

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

Documentation for [MediaDevices](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices)

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.MediaDevices.getUserMedia`
* Report started: 2023-02-15T07:43:00.527Z

</details>

**Comment by gsnedders** [comment]
This was also reported to WebKit as https://bugs.webkit.org/show_bug.cgi?id=252303 where it was closed as invalid: the API still exists, and is still restricted to secure origins.

As I commented there:

> If rahil.local is not served from a secure origin (roughly, over https), then it is expected that MediaDevices doesn't exist.

BCD also documents this API as requiring a secure context, so there's no data issue here.

**Comment by Baldur10** [comment]
> This was also reported to WebKit as https://bugs.webkit.org/show_bug.cgi?id=252303 where it was closed as invalid: the API still exists, and is still restricted to secure origins.
> 
> As I commented there:
> 
> > If rahil.local is not served from a secure origin (roughly, over https), then it is expected that MediaDevices doesn't exist.
> 
> BCD also documents this API as requiring a secure context, so there's no data issue here.

Yeah this seems to be the confusion I had. I wasn't serving my webapp over https so secure context was disabled. When I attached a valid certificate to it, the issue was resolved and I was able to access the api
