### ISSUE TITLE
javascript.builtins.WebAssembly.Exception.stack - Incorrect support status for safari

### ISSUE THREAD

**Issue by ravisumit33** [mdn/browser-compat-data#18938]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Safari and Safari on iOS says supported on 15.2 but still not supported on 16.2

### What did you expect to see?

`WebAssembly.Exception.prototype.stack` supported on both Safari and Safari on iOS

### Did you test this? If so, how?

```js
const tag = new WebAssembly.Tag({ parameters: ["i32"] });

function throw_exception_with_stacktrace(param) {
    return new WebAssembly.Exception(tag, [param], { traceStack: true });
}

const ex = throw_exception_with_stacktrace(42);
console.log(ex.stack);
```

It prints `undefined` while it should have printed the stack trace.

### MDN URL

https://developer.mozilla.org/en-US/docs/WebAssembly/JavaScript_interface/Exception/stack

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `javascript.builtins.WebAssembly.Exception.stack`
* Report started: 2023-02-17T10:13:55.096Z

</details>

**Comment by queengooborg** [comment]
This data has been fixed!
