### ISSUE TITLE
css.properties.list-style-position - Incorrect support status for Safari

### ISSUE THREAD

**Issue by yarusome** [mdn/browser-compat-data#18934]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

The last paragraph in the "Try it" [section](https://developer.mozilla.org/en-US/docs/Web/CSS/list-style-position#try_it) of the MDN page claims different behaviors across browsers for `list-style-position: inside` with a link pointing to [Mozilla Bug 36854](https://bugzilla.mozilla.org/show_bug.cgi?id=36854), but the last [comment](https://bugzilla.mozilla.org/show_bug.cgi?id=36854#c38) in the bug contains updated info in this regard.

To summarize, the spec says that

>The marker box is generated by the ::marker pseudo-element of a list item as the list item’s first child[…]

So if a block element is placed first in a list element, the marker should be placed on the fist line and the block element on the second line. The conformance of browsers are:

 - Firefox, Opera, Internet Explorer: conforming (according to the MDN page);
 - Chrome: conforming (according to the last comment of the Mozilla Bug);
 - Safari: ~non-conforming / unclear (according to the MDN page and the [Webkit Bug 227000](https://bugs.webkit.org/show_bug.cgi?id=227000))~ See the comment below.

### What browsers does this problem apply to, if applicable?

Safari

### What did you expect to see?

~If Safari is confirmed to not conform in the mentioned cases, its support status should be changed to "partial" with an implementation note.~ The support status for Safari be updated.

### Did you test this? If so, how?

No available MacOS device to test.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

MDN page: https://developer.mozilla.org/en-US/docs/Web/CSS/list-style-position
Mozilla Bug 36854: https://bugzilla.mozilla.org/show_bug.cgi?id=36854
WebKit Bug 227000: https://bugs.webkit.org/show_bug.cgi?id=227000

### Do you have anything more you want to share?

Related MDN content issue: https://github.com/mdn/content/issues/24502

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/list-style-position

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.list-style-position`
* Report started: 2023-02-17T00:33:41.036Z

</details>

**Comment by yarusome** [comment]
The "CSS" section of the [release note](https://webkit.org/blog/11989/new-webkit-features-in-safari-15/) for Safari 15 mentions that Safari has aligned its implementation of `list-style-position: inside` with the spec, like Firefox and Chrome do.

**Comment by wbamberg** [comment]
But https://github.com/mdn/content/issues/24502#issuecomment-1483132768 suggests that Safari still not aligned, doesn't it?
