### ISSUE TITLE
api.Navigator.requestMIDIAccess - <SUMMARIZE THE PROBLEM>

### ISSUE THREAD

**Issue by geartvdveen** [mdn/browser-compat-data#18949]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

API access is gated by installation of a site permission add-on (user prompt), secure context, and Permission Policy: midi.

### What browsers does this problem apply to, if applicable?

Firefox

### What did you expect to see?

When accessing the MIDI Api from a local file:
isSecureContext == true
navigator.requestMIDIAccess == undefined (expected: function)
 

 

### Did you test this? If so, how?

Tested with Firefox version 110. Works OK from a HTTPS server but not with the same file on my local system.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Web_MIDI_API

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.Navigator.requestMIDIAccess`
* Report started: 2023-02-18T12:09:03.760Z

</details>

**Comment by queengooborg** [comment]
This is normal behavior, as this interface requires an HTTPS context!
