### ISSUE TITLE
api.Element.scrollIntoView - Safari support outdated

### ISSUE THREAD

**Issue by JackWH** [mdn/browser-compat-data#18943]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Incorrect Safari support listed for `scrollIntoView`'s `options` parameter. Support for options was [added in Safari 16](https://caniuse.com/?search=scrollIntoView).

### What browsers does this problem apply to, if applicable?

Safari

### What did you expect to see?

Safari support for `options` since v16.

### Did you test this? If so, how?

Yes, using Safari 16 to confirm support.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://caniuse.com/?search=scrollIntoView

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.Element.scrollIntoView`
* Report started: 2023-02-17T16:54:44.709Z

</details>

**Comment by queengooborg** [comment]
Fixed in #19126!
