### ISSUE TITLE
css.properties.height - Inconsistent support statuses for the `fit-content` value

### ISSUE THREAD

**Issue by yarusome** [mdn/browser-compat-data#18953]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

The support status for `height: fit-content` is "no support", which is inconsistent with the status listed on the MDN [page](https://developer.mozilla.org/en-US/docs/Web/CSS/fit-content#browser_compatibility) of the `fit-content` value.

### What browsers does this problem apply to, if applicable?

Firefox

### What did you expect to see?

Synced support status for `height: fit-content`.

### Did you test this? If so, how?

No.

### Do you have anything more you want to share?

Synchronizing the `fit-content` support statuses might be a bit complicated because this value applies to several physical and logical properties, e.g. `height`, `block-size`, `min-inline-size`, and these properties themselves have different support dates.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/height

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.height`
* Report started: 2023-02-19T12:26:12.072Z

</details>

**Comment by teoli2003** [comment]
You are mixing `fit-content`, the value added in 46, and `fit-content()` the function, mostly unsupported yet.
BCD for `fit-content`
![Capture d’écran 2023-02-19 à 13 47 05](https://user-images.githubusercontent.com/1466293/219948917-6df12f99-bee2-46f3-8233-aa336b24e1eb.png)

Table for `fit-content`
![Capture d’écran 2023-02-19 à 13 48 29](https://user-images.githubusercontent.com/1466293/219948956-7cd61f70-075a-4686-97e9-0211a05232f1.png)

BCD for `fit-content()`

![Capture d’écran 2023-02-19 à 13 49 50](https://user-images.githubusercontent.com/1466293/219949027-809bf722-86d8-430f-8b9a-4a1e3062473b.png)

And the table with both next to each other (in `height`):
![Capture d’écran 2023-02-19 à 13 50 42](https://user-images.githubusercontent.com/1466293/219949074-e0960610-bb5d-49db-bb77-e71bcade70e9.png)

**Comment by yarusome** [comment]
@teoli2003 But the last two screenshots exactly prove the inconsistency, no? (Note that all the statuses for the `fit-content` *keyword* in `height` are the same as those in the own page of `fit-content` *except for Firefox*.)

Another evidence is from the comparison between `width`, `height`, `block-size`, where the third property maps to the second one with the initial `writing-mode`:

![width](https://user-images.githubusercontent.com/97945148/220234774-f66d142a-4e41-4570-9e01-de7b37b7438b.png)

---
![height](https://user-images.githubusercontent.com/97945148/220234802-fa526bf5-3014-42fd-944c-b90164c0b97d.png)

---
![block-size](https://user-images.githubusercontent.com/97945148/220234831-864e3341-2701-4d81-b808-767a500e0ea3.png)

And for completeness:

![fit-content](https://user-images.githubusercontent.com/97945148/220234903-f1d4986f-2b69-4424-ab52-4ef54ff7c71d.png)

**Comment by queengooborg** [comment]
This was fixed in #19522!
