### ISSUE TITLE
css.properties.cursor - context menu is not in table

### ISSUE THREAD

**Issue by JustinWebDev** [mdn/browser-compat-data#18978]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

The compatibility table does not have "context menu".

### What did you expect to see?

compatibility for this option

### Did you test this? If so, how?

n/a

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/cursor

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.cursor`
* Report started: 2023-02-21T23:12:45.595Z

</details>

**Comment by queengooborg** [comment]
We've had this value declared in our tables since the cursor property was first introduced.
