### ISSUE TITLE
CSS Property: outline - outline follows the curve of border-radius in Safari 16.4 Beta

### ISSUE THREAD

**Issue by darrylnoakes** [mdn/browser-compat-data#18975]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

`outline` is said to not follow the curve of `border-radius` in Safari 16.4 TP.

### What browsers does this problem apply to, if applicable?

Safari

### What did you expect to see?

No note saying that `outline` does not follow the curve of `border-radius` in Safari 16.4.

### Did you test this? If so, how?

No

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

[Safari 16.4 Beta Release Notes](https://developer.apple.com/documentation/safari-release-notes/safari-16_4-release-notes)

### Do you have anything more you want to share?

I do not know if this is the correct way to go about this, or if I have maybe missed something.

**Comment by queengooborg** [comment]
Fixed in #20424!
