### ISSUE TITLE
api.TouchList is no longer supported by Firefox

### ISSUE THREAD

**Issue by gregorypappas** [mdn/browser-compat-data#19011]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

BCD says Firefox supports TouchList, this is not true.

### What browsers does this problem apply to, if applicable?

Firefox

### What did you expect to see?

I expected to see that Firefox does not support TouchList

### Did you test this? If so, how?

I tested it by trying to use TouchList in devtools and it failed.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://bugzilla.mozilla.org/show_bug.cgi?id=1412485

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/TouchList

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.TouchList`
* Report started: 2023-02-26T09:37:28.180Z

</details>

**Comment by queengooborg** [comment]
Fixed in #20194!
