### ISSUE TITLE
html.elements.link.rel.preload - Browser compatibility safari

### ISSUE THREAD

**Issue by wanglemicrosoft** [mdn/browser-compat-data#19025]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

Udpate Safari on iOS with Compatibility unknown (question mark), it's working on iOS version 16.3.1.
MacOS safari version 16.1 is working as well.

### What did you expect to see?

Same as above

### Did you test this? If so, how?

Yes.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel/preload

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `html.elements.link.rel.preload`
* Report started: 2023-02-27T23:14:31.904Z

</details>

**Comment by queengooborg** [comment]
Duplicate of #15263.
