### ISSUE TITLE
api.StorageManager.estimate - Safari support

### ISSUE THREAD

**Issue by captainbrosset** [mdn/browser-compat-data#19032]
### What type of issue is this?

Incorrect support data.

### What information was incorrect, unhelpful, or incomplete?

https://developer.mozilla.org/en-US/docs/Web/API/StorageManager/estimate#browser_compatibility says that the `StorageManager`'s `estimate` method is not supported in Safari.

However, support for this method was recently added in Safari Technology Preview 163.

### What browsers does this problem apply to, if applicable?

Safari

### What did you expect to see?

The BCD table for this method should mention that Safari supports it.

### Did you test this? If so, how?

No, I don't have a Mac where I can test this.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

See the release notes where this was announced: https://webkit.org/blog/13839/release-notes-for-safari-technology-preview-163/

And the commit where support was added: https://github.com/WebKit/WebKit/commit/a793d8b68a12b37482e8734a578926405f7edc45

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/StorageManager/estimate

**Comment by queengooborg** [comment]
Fixed in #20064!
