### ISSUE TITLE
api.BaseAudioContext.decodeAudioData - EncodingError: Decoding failed

### ISSUE THREAD

**Issue by khangsk** [mdn/browser-compat-data#19037]
### What type of issue is this?

Incorrect support data: promise-based syntax is not work on Safari 15.0

### What information was incorrect, unhelpful, or incomplete?

decodeAudioData "returns a Promise" is not work on Safari version 15.0.
error message: EncodingError: Decoding failed

### What browsers does this problem apply to, if applicable?

Safari

### What did you expect to see?

Decode without error.

### Did you test this? If so, how?

const audioContext = new (window.AudioContext || (window as any).webkitAudioContext)();
try {
    await audioContext.decodeAudioData(<< ArrayBuffer >>);
} catch (error) {
}

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/BaseAudioContext/decodeAudioData

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.BaseAudioContext.decodeAudioData`
* Report started: 2023-03-02T02:27:46.344Z

</details>

**Comment by queengooborg** [comment]
It seems like you've got a development error, not an issue with promise-based syntax.  We recommend checking out StackOverflow for development help questions.
