### ISSUE TITLE
Browser compatibility should show IE

### ISSUE THREAD

**Issue by Eccenux** [mdn/browser-compat-data#19048]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

We still have users using IE. Not a lot, but enough to make me think if I need a compatibility check. At least for something that is used low level (in many views and/or could break whole JS file).

### What did you expect to see?

I need IE compat in those tables.

### Did you test this? If so, how?

For example in console.trace() I don't know from MDN if it was in last IE or not.
https://developer.mozilla.org/en-US/docs/Web/API/console/trace#browser_compatibility

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/console/trace

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.console.trace`
* Report started: 2023-03-03T12:29:21.220Z

</details>

**Comment by Eccenux** [comment]
The problem is that this data is not displayed. It should be. I know that I can check other services, but compatibility is just one of the things I check on MDN (as I'm sure most users do).

**Comment by teoli2003** [comment]
See https://github.com/mdn/mdn-community/discussions/202

**Comment by Eccenux** [comment]
I don't understand @queengooborg when he/she say: "encourage web developers to port their IE-only websites to modern browsers like Chrome, Firefox and Safari."

That has nothing to do with it. I check IE explicitly to be able to make my website work in various browsers. If you want to save space then just remove Edge and other Chrome clones (Opera, Samsung).

**Comment by queengooborg** [comment]
To put it simply, we have frozen all IE data and are not showing it on MDN Web Docs as IE usage has fallen well below the usage percentage of any other browser we track (and are planning to track).  The linked discussion contains comments and responses that explain more reasoning why this decision was made.

**Comment by Eccenux** [comment]
In the discussions I see similar concerns I raised. Hidding IE is oposite of what you said. It is making the tables less useful when a dev is trying to make a website work in all browsers. In practice there are 3 major browser: FF, Chromium (Safari fork), Safari. The other one is IE. People still use IE. And when IE fails it usually fails badly.

You quote global stats. But global stats are not e.g. stats of public libraries in Poland.

I don't see a problem of supporting IE. You already have the data. No new IE version will be released so the data is static. So why not just display that?
