### ISSUE TITLE
css.types.color.lab - Chromium support outdated

### ISSUE THREAD

**Issue by svgeesus** [mdn/browser-compat-data#19067]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Chromium-based browsers are shown as not supporting `lab()` but [WPT results](https://wpt.fyi/results/css/css-color?label=master&label=experimental&aligned&view=subtest&q=lab) show Chrome 111 beta and up supporting it.

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

Up to date support matrix

### Did you test this? If so, how?

Tested on WPT

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://developer.chrome.com/blog/chrome-111-beta/#new-css-color-types-and-spaces

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/lab

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.types.color.lab`
* Report started: 2023-03-07T14:13:52.016Z

</details>

**Comment by svgeesus** [comment]
Also https://chromestatus.com/feature/5147752829288448

**Comment by ai** [comment]
I sent PR for that https://github.com/mdn/browser-compat-data/pull/19068
