### ISSUE TITLE
`offset-path` `<basic-shape>`/`<url>` - Missing browser support

### ISSUE THREAD

**Issue by strarsis** [mdn/browser-compat-data#19063]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Chrome does not support `<basic-shape>` or `<url>` as `offset-path`.
MDN does not list browser support data for these sub-features.

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet), Firefox

### What did you expect to see?

Browser support data for these sub-features and that those browsers currently do not support them.

### Did you test this? If so, how?

Yes, I made a simple CodePen and then checked whether the value of a `<basic-shape>` or an `<url>` is actually interpreted as valid by the browser. But those are not even considered valid values, and certainly not used by the browsers.

Basic shape `circle` would be really useful with `offset-path` for many things.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://developer.mozilla.org/en-US/docs/Web/CSS/offset-path

**Comment by Blackclaws** [comment]
Safari also does not support this subfeature unless I tested it incorrectly. Took me 15 minutes to figure out why my offset path wasn't working as designed.

**Comment by queengooborg** [comment]
This data has been added in #20483!
