### ISSUE TITLE
css.properties.mask - Safari 15.4 supports unprefixed `mask`

### ISSUE THREAD

**Issue by yarusome** [mdn/browser-compat-data#19079]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Safari 15.4 supports the unprefixed `mask` property. See the [release note](https://developer.apple.com/documentation/safari-release-notes/safari-15_4-release-notes).

### What browsers does this problem apply to, if applicable?

Safari

### What did you expect to see?

Updated support status of `mask` for Safari.

### Did you test this? If so, how?

No.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

Safari 15.4 release note: https://developer.apple.com/documentation/safari-release-notes/safari-15_4-release-notes

### Do you have anything more you want to share?

The longhand properties `mask-*` (excluding `mask-border-*`), e.g. `mask-origin`, do have correct support statuses.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/mask

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.mask`
* Report started: 2023-03-09T00:26:44.276Z

</details>

**Comment by queengooborg** [comment]
Fixed in #19019!
