### ISSUE TITLE
css.types.color.color-mix - Update Chromium

### ISSUE THREAD

**Issue by owaisalhashimi** [mdn/browser-compat-data#19085]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Compat is set to Preview Browser Support for Chromium  version 111 browsers. 111 is now stable.
[Chrome Platform Status](https://chromestatus.com/features#milestone%3D111)

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

Preview Browser support labels should be removed for Chromium 111 version browsers.

### Did you test this? If so, how?

-

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://chromestatus.com/features#milestone%3D111

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/color-mix

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.types.color.color-mix`
* Report started: 2023-03-09T14:38:08.711Z

</details>

**Comment by queengooborg** [comment]
Fixed in #18827!
