### ISSUE TITLE
Element.scrollIntoView: Safari does support options parameter

### ISSUE THREAD

**Issue by jackyhallyday** [mdn/browser-compat-data#19088]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView

### What specific section or headline is this issue about?

Browser Compatibility

### What information was incorrect, unhelpful, or incomplete?

The compatibility table indicates that Safari does not support options, but it does.
Tested (block and behavior) on Safari 15.6.1 desktop.

Also tested on Safari 12.6 on iPad : block is suported, but behavior: smooth is not.

### What did you expect to see?

An indication that options are supported on Safari.

**Comment by yarusome** [comment]
The [release note](https://developer.apple.com/documentation/safari-release-notes/safari-15_4-release-notes) for Safari 15.4 shows that this version adds supports for both the `scroll-behavior` CSS property and `ScrollIntoViewOptions` for `scrollIntoView()`.

**Comment by queengooborg** [comment]
Fixed in #19126!
