### ISSUE TITLE
css.properties.font-variant-alternates and css.at-rules.font-feature-values - Safari doesn’t actually support it, Chromium now does

### ISSUE THREAD

**Issue by chris-morgan** [mdn/browser-compat-data#19083]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

1. That Safari has supported it since 9.1.
2. That Chrome doesn’t support it.

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet), Safari

### What did you expect to see?

1. That Safari does not support `@font-feature-values`/`font-variant-alternates` (it doesn’t currently, and I don’t believe it ever did).
2. That Chrome supports it from 111 onwards.

### Did you test this? If so, how?

https://temp.chrismorgan.info/2023-03-09-font-feature-values-demo/

(Also other easy tests like `CSSFontFeatureValuesRule` or `CSS.supports('font-variant-alternates', 'styleset(x)')`.)

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

- Safari non-support: https://github.com/w3c/csswg-drafts/issues/552#issuecomment-253385360 confirms that six months after Safari 9.1 Safari didn’t support `@font-feature-values`. I have not found any reason to believe it ever did.
- Chromium having just landed it in M111: https://bugs.chromium.org/p/chromium/issues/detail?id=716567

### Do you have anything more you want to share?

This affects both css.properties.font-variant-alternates and css.at-rules.font-feature-values.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-alternates

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.font-variant-alternates`
* Report started: 2023-03-09T10:42:08.609Z

</details>

**Comment by gsnedders** [comment]
> css.at-rules.font-feature-values

Oh I missed you were talking about that—yeah, that's definitely wrong claiming Safari 9.1 has support. (It's also less surprising that it's wrong—because mdn-bcd-collector doesn't generate results for `css.at-rules`, and thus it's much more reliant on human editing/research, which is… much more fallible).

**Comment by chris-morgan** [comment]
Hmm, I think I accidentally tangled things up as part of reporting, in thinking there were two affected things. Also I somehow missed the whole Safari 16.2 thing.

Well then: #18529 fixed font-variant-alternates, it’s now correct, but css.at-rules.font-feature-values is still incorrect, so let’s restrict the scope of this report to just that.

**Comment by chris-morgan** [comment]
Actually, no, css.properties.font-variant-alternates is still wrong for Chromium, #18529 just fixed the Safari error.

Sigh. This is what comes of trying to report problems with two browsers in two different areas in the one report: you get at least one of the four combinations wrong! 🙂

**Comment by queengooborg** [comment]
Chrome data is all fixed in #19520!
