### ISSUE TITLE
api.Serial - <Able to view and connect to ports when site runs locally but not when when served through linux server>

### ISSUE THREAD

**Issue by Daniel-Mutter** [mdn/browser-compat-data#19087]
### What type of issue is this?

Other

### What information was incorrect, unhelpful, or incomplete?

None, just confused about why it does not work. The site is being server from centOS linux server but I am opening the page in chrome and the api is not working (I am a new developer so I apologize if I am completely off track)

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

if ("serial" in navigator) {
    console.log("yes")
  } 
else     console.log("no")

expected yes but got no

### Did you test this? If so, how?

Ran on linux server

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Web_Serial_API

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.Serial`
* Report started: 2023-03-09T18:55:26.168Z

</details>

**Comment by queengooborg** [comment]
This sounds like it's a development help question, which we cannot aid with in this repository.  We highly recommend checking out dedicated websites like StackOverflow -- most likely, someone has already asked your exact question!
