### ISSUE TITLE
css.properties.scroll-timeline - FF flag name may not be correct

### ISSUE THREAD

**Issue by estelle** [mdn/browser-compat-data#19086]
### What type of issue is this?

[edit] Flags and support are not accurate [originally, the dropdown defaulted to say it was supported in chrome 40. that was NOT accurate]

### What information was incorrect, unhelpful, or incomplete?

FF has 3 flags with similar names:

- `layout.css.scroll-driven-animations.enabled`

- _layout.css.scroll-linked-animations.enabled_

- _layout.css.scroll-linked-animations_

I believe the first, scroll-driven, is the needed flag here.

Also, Chrome and Edge support this property behind a flag as well. You need to enable `Experimental Web Platform Features` in those two browsers. I did not research Safari.

### What did you expect to see?

correct info

### Did you test this? If so, how?

https://codepen.io/estelle/pen/abaVZeP

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-timeline

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.scroll-timeline`
* Report started: 2023-03-09T18:39:40.907Z

</details>

**Comment by estelle** [comment]
note the current example in the MDN page works as a regular animation. Don't be fooled by it.

**Comment by dipikabh** [comment]
Fixed by https://github.com/mdn/browser-compat-data/pull/19148 (Firefox) and https://github.com/mdn/browser-compat-data/pull/19209 (Chrome)
