### ISSUE TITLE
css.properties.grid-template-(columns|rows) - Safari TP 163 has enabled masonry layout

### ISSUE THREAD

**Issue by yarusome** [mdn/browser-compat-data#19080]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Safari Technology Preview 163 has enabled masonry layout be default. See the "Masonry Layout" section in the [release note](https://webkit.org/blog/13839/release-notes-for-safari-technology-preview-163/).

### What browsers does this problem apply to, if applicable?

Safari

### What did you expect to see?

Updated support statues of `grid-template-columns` and `grid-template-rows` for Safari.

### Did you test this? If so, how?

No.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

WebKit Bug 250328: https://bugs.webkit.org/show_bug.cgi?id=250328
Safari TP 163 release note: https://bugs.webkit.org/show_bug.cgi?id=250328

### Do you have anything more you want to share?

The `masonry-auto-flow` property *may* have also been supported by Safari. See [WebKit Bug 247078](https://bugs.webkit.org/show_bug.cgi?id=247078) and [WebKit Bug 247079](https://bugs.webkit.org/show_bug.cgi?id=247079).

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/grid-template-columns

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.grid-template-columns`
* Report started: 2023-03-09T00:33:49.423Z

</details>

**Comment by QINGCHARLES** [comment]
This page states that only Firefox supports masonry behind a flag, but as stated above, Safari has supported it for a short while now without flag in preview:

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_grid_layout/Masonry_layout

**Comment by queengooborg** [comment]
Fixed in #20084!

**Comment by QINGCHARLES** [comment]
This page still says that it is Firefox only though?

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_grid_layout/Masonry_layout

The commits in #20084 don't seem to make any changes to that page?

**Comment by queengooborg** [comment]
MDN pages aren't maintained in this repository; you'll want to file an issue in mdn/content instead for page-related changes.
