### ISSUE TITLE
api.StorageManager - navigator.storage on Safari on iOS 15.2^ returns undefined

### ISSUE THREAD

**Issue by yoieh** [mdn/browser-compat-data#19107]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Says "full support" `Safari on iOS 15.2`  for `StorageManager` 

|    | Safari on iOS |
|---|---|
|`StorageManager` |  ![full](https://developer.mozilla.org/static/media/yes.70caad81ca5e3d9f7576.svg)  15.2  |

But `Safari on iOS 15.5/16.2/16.2` returns `undefined` on `navigator.storage` 

### What browsers does this problem apply to, if applicable?

Safari

### What did you expect to see?

I expect this to return the StorageManager singelton as documented.

### Did you test this? If so, how?

Testing it on browserstack.com on multiple iOS devices.

```
console.log(navigator.storage);
```
![image](https://user-images.githubusercontent.com/5743837/224690254-458be53b-b355-4aef-b25f-0f32ae8d4a3a.png)

![image](https://user-images.githubusercontent.com/5743837/224690114-e86d10f7-3965-4c48-8034-7f1c251360ab.png)

Directly in the browsers console.

![image](https://user-images.githubusercontent.com/5743837/224689863-925f7629-4f33-4a9b-8861-d1e5f0f4188b.png)

And just as an browser alert

```
alert(navigator.storage)
```

![image](https://user-images.githubusercontent.com/5743837/224689682-298d51db-9830-47c0-97ea-32cc705805e4.png)

But it always just returns `undefined`

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/StorageManager

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.StorageManager`
* Report started: 2023-03-13T11:04:20.939Z

</details>

**Comment by queengooborg** [comment]
`navigator.storage` is only available on HTTPS pages.  You may be trying to access it from an HTTP-only page.
