### ISSUE TITLE
api.CanvasRenderingContext2D.reset - Support added in Firefox 113

### ISSUE THREAD

**Issue by kdashg** [mdn/browser-compat-data#19149]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

Support was just added in Firefox 113 (currently Nightly).
Bug link: https://bugzilla.mozilla.org/show_bug.cgi?id=1709347

### What browsers does this problem apply to, if applicable?

Firefox

### What did you expect to see?

Marked as supported in Firefox 113.

### Did you test this? If so, how?

https://wpt.live/html/canvas/element/reset/2d.reset.basic.html
Used to fail, now passes.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://bugzilla.mozilla.org/show_bug.cgi?id=1709347

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/reset

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.CanvasRenderingContext2D.reset`
* Report started: 2023-03-16T02:38:17.347Z

</details>

**Comment by queengooborg** [comment]
Fixed in #19412!
