### ISSUE TITLE
@supports font-tech() and font-format() - Blink ships since 108

### ISSUE THREAD

**Issue by CanadaHonk** [mdn/browser-compat-data#19144]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

BCD says Blink-based browsers do not support `font-tech()` or `font-format()` but Blink report shipping it since 108: https://chromestatus.com/feature/5155718374621184

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

Shipped (supported) since 108

### Did you test this? If so, how?

Checked WPT tests:
- https://wpt.fyi/results/css/css-conditional/at-supports-font-format-001.html
- https://wpt.fyi/results/css/css-conditional/at-supports-font-tech-001.html

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://developer.mozilla.org/en-US/docs/Web/CSS/@supports#browser_compatibility

**Comment by queengooborg** [comment]
Fixed in #21250!
