### ISSUE TITLE
css.properties.-webkit-line-clamp - Incorrect spec link

### ISSUE THREAD

**Issue by yarusome** [mdn/browser-compat-data#19156]
### What type of issue is this?

Incorrect support data (example: Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

The level-less spec link points to CSS Overflow Module Level 3, but this property is actually defined in Level 4.

### What did you expect to see?

The spec link pointing to [CSS Overflow Module Level 4](https://w3c.github.io/csswg-drafts/css-overflow-4/#webkit-line-clamp).

### Did you test this? If so, how?

By clicking the current spec link.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-line-clamp

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.-webkit-line-clamp`
* Report started: 2023-03-17T02:33:31.144Z

</details>

**Comment by queengooborg** [comment]
Fixed in #19396!
