### ISSUE TITLE
api.ServiceWorkerGlobalScope.pushsubscriptionchange_event - supported only partially on Firefox

### ISSUE THREAD

**Issue by saschanaz** [mdn/browser-compat-data#19162]
### What type of issue is this?

Browser bug (a bug with a feature that may impact site compatibility)

### What information was incorrect, unhelpful, or incomplete?

It's not a full support if the corresponding interface PushSubscriptionChangeEvent is not supported

### What browsers does this problem apply to, if applicable?

Firefox

### What did you expect to see?

An indication that the support is partial

### Did you test this? If so, how?

* WPT: https://wpt.fyi/results/push-api/idlharness.https.any.serviceworker.html?label=experimental&label=master&aligned&view=subtest
* The collector (https://mdn-bcd-collector.appspot.com/tests/)

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

* https://bugzilla.mozilla.org/show_bug.cgi?id=1497429
* https://bugzilla.mozilla.org/show_bug.cgi?id=1635524

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerGlobalScope/pushsubscriptionchange_event

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.ServiceWorkerGlobalScope.pushsubscriptionchange_event`
* Report started: 2023-03-17T14:22:43.514Z

</details>

**Comment by queengooborg** [comment]
This has been fixed in #22795!
