### ISSUE TITLE
infinity, -infinity, NaN <calc-constant> - outdated data

### ISSUE THREAD

**Issue by CanadaHonk** [mdn/browser-compat-data#19168]
### What type of issue is this?

Incorrect support data (example: Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

[Chromium has been shipping this since 99](https://chromestatus.com/feature/5657825571241984), and [Safari since Technology Preview Release 134](https://developer.apple.com/safari/technology-preview/release-notes/#r134), and Firefox only supports this behind a flag (`layout.css.nan-inf.enabled`) which is currently Nightly only.

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet), Firefox, Safari

### What did you expect to see?

Correct/up to date data.

### Did you test this? If so, how?

See https://wpt.fyi/results/css/css-values/calc-infinity-nan-computed.html

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

Chrome feature status: https://chromestatus.com/feature/5657825571241984
Safari TP 134 release notes: https://developer.apple.com/safari/technology-preview/release-notes/#r134
Firefox pref source code: https://searchfox.org/mozilla-central/source/modules/libpref/init/StaticPrefList.yaml#8208-8213

**Comment by bsmth** [comment]
Thanks @CanadaHonk - this should be fixed by the linked PR. In case you're curious, the flag data is not being added as it's a candidate for removal due to the features landing in stable channels anyway. Some info on this guideline: https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/index.md#removal-of-irrelevant-flag-data

**Comment by bsmth** [comment]
Closing this as https://github.com/mdn/browser-compat-data/pull/19882 has landed. Links to references (release notes / source showing supported version numbers) are in the PR.
