### ISSUE TITLE
Method name error on commands API page

### ISSUE THREAD

**Issue by jscher2000** [mdn/browser-compat-data#1917]
On https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/commands#Browser_compatibility

Where I would expect:

    <a href="/docs/Mozilla/Add-ons/WebExtensions/API/commands/reset"><code>reset</code></a>

is

    <a href="/docs/Mozilla/Add-ons/WebExtensions/API/commands/reset">Support simple</a>

The data looks okay here:

https://github.com/mdn/browser-compat-data/blob/master/webextensions/api/commands.json

Puzzled.

**Comment by connorshea** [comment]
@ddbeck this can be closed

**Comment by ddbeck** [comment]
I think this might've been a bug in the rendering on MDN and maybe fixed there? Regardless, thank you @jscher2000 and @connorshea!
