### ISSUE TITLE
api.Element.requestFullscreen - <SUMMARIZE THE PROBLEM>

### ISSUE THREAD

**Issue by SoftwareEngineer0** [mdn/browser-compat-data#19194]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

Can you add compatibility with the iPhone chrome browser for requestFullscreen()?
My env: iphone 12 pro Max
chrome version is 111.0.5563

### What did you expect to see?

iPhone Chrome Browser's compatibility of requestFullscreen()

### Did you test this? If so, how?

I tested it on the iPhone chrome browser about it, but not working.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullscreen

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.Element.requestFullscreen`
* Report started: 2023-03-22T19:07:56.040Z

</details>

**Comment by queengooborg** [comment]
It sounds like you're requesting that support is added to the browser.  If so, this is the wrong place to request features, as we are not the browser engineers.  You can check out https://webkit.org/reporting-bugs/ for more details on how to file a bug with WebKit, the engine that powers Safari.
