### ISSUE TITLE
css.properties.list-style-type.amaric - misspelling of amharic?

### ISSUE THREAD

**Issue by gsnedders** [mdn/browser-compat-data#19200]
### What type of issue is this?

Other

### What information was incorrect, unhelpful, or incomplete?

`amharic` was previously defined in the spec (removed in https://github.com/w3c/csswg-drafts/commit/151b82abcf1d6dc1fcd0ecb18118ae6c03c4fb88); `amaric` never was.

`amaric` was never implemented in Safari, contrary to the claim; whereas `amharic` is.

### What did you expect to see?

`amharic`

### Did you test this? If so, how?

I didn't, but I did look at https://github.com/WebKit/WebKit/blob/8ae19dd1452f80508884dca039d382d84c65665d/Source/WebCore/rendering/style/ListStyleType.h#L76 and others.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/list-style-type

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.list-style-type`
* Report started: 2023-03-23T15:44:59.460Z

</details>

**Comment by teoli2003** [comment]
Thank you (long time not seen you!) I opened a PR to get this fixed.
