### ISSUE TITLE
api.Sensor - <SUMMARIZE THE PROBLEM>

### ISSUE THREAD

**Issue by Djonesr** [mdn/browser-compat-data#19282]
### What type of issue is this?

Incorrect support data (example: Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Support data

### What browsers does this problem apply to, if applicable?

Firefox, Safari

### What did you expect to see?

Correct data

### Did you test this? If so, how?

Github action

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Sensor

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.Sensor`
* Report started: 2023-03-30T19:28:24.283Z

</details>

**Comment by Elchi3** [comment]
Thanks for your issue but neither Firefox nor Safari support generic sensors
https://mozilla.github.io/standards-positions/#generic-sensor
