### ISSUE TITLE
css.at-rules.color-profile - missing compatibility and spec data

### ISSUE THREAD

**Issue by tianheg** [mdn/browser-compat-data#19299]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

https://developer.mozilla.org/en-US/docs/Web/CSS/@color-profile#browser_compatibility page don't have compatibility and spec data.

### What did you expect to see?

Someone will add data about `@color-profile`

### Did you test this? If so, how?

Yes

**Comment by queengooborg** [comment]
I'm closing this issue because there is not enough actionable information.  No details as to _how_ the feature was tested were provided.
