### ISSUE TITLE
html.elements.script.type.importmap - Supported in Safari 16.4

### ISSUE THREAD

**Issue by RaananW** [mdn/browser-compat-data#19291]
### What type of issue is this?

Incorrect support data (example: Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Safari now supports import maps, starting version 16.4

### What browsers does this problem apply to, if applicable?

Safari

### What did you expect to see?

Safari support

### Did you test this? If so, how?

Information can be found here - https://developer.apple.com/documentation/safari-release-notes/safari-16_4-release-notes

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://developer.apple.com/documentation/safari-release-notes/safari-16_4-release-notes

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script/type/importmap

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `html.elements.script.type.importmap`
* Report started: 2023-03-31T13:53:52.880Z

</details>

**Comment by gsnedders** [comment]
Duplicate of https://github.com/mdn/browser-compat-data/issues/19291
