### ISSUE TITLE
Add Bugzilla reference for unsupported but under-development APIs

### ISSUE THREAD

**Issue by erosman** [mdn/browser-compat-data#19329]
### What would you like to see added to BCD?

If possible, it would be very useful to add a link to Bugzilla for unsupported but under-development APIs.
It would help users (and BCD) to keep track of the development and possible ETA.

### How impactful do you think this enhancement will be?

Example:
[declarativeNetRequest](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/declarativeNetRequest) -> [Browser compatibility](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/declarativeNetRequest#browser_compatibility) -> Firefox

https://bugzilla.mozilla.org/show_bug.cgi?id=1687755

### Do you have anything more you want to share?

Example of where it is already added: [import Browser compatibility](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#browser_compatibility)

![image](https://user-images.githubusercontent.com/6458876/232216300-bbc88845-58cb-416c-b3f3-2dffea55468d.png)

**Comment by queengooborg** [comment]
Adding bug links is very helpful to track the implementation status of features, and definitely something we want to do -- however, I don't think that we can allocate the time and resources to turn this into a big project, especially as we have developed a system to [automatically track feature support in browsers](https://mdn-bcd-collector.gooborg.com/).  However, we will always welcome contributor pull requests that add bug links to the data!
