### ISSUE TITLE
ScreenOrientation.lock on Safari

### ISSUE THREAD

**Issue by jordyboom** [mdn/browser-compat-data#19355]
### What type of issue is this?

Incorrect support data (example: Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

The documentation states that the "lock" feature was added in Safari 16.4 but it does not support it. The Safari release notes specifically state at https://developer.apple.com/documentation/safari-release-notes/safari-16_4-release-notes:

"Added support for ScreenOrientation.type, ScreenOrientation.angle, and ScreenOrientation.onchange."

### What did you expect to see?

Not supported

### Did you test this? If so, how?

Yes.

`"lock" in window.screen.orientation`

Returns false in both Desktop and iOS Safari.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://developer.apple.com/documentation/safari-release-notes/safari-16_4-release-notes

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/ScreenOrientation

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.ScreenOrientation`
* Report started: 2023-04-11T19:47:55.783Z

</details>

**Comment by Burden50** [comment]
+1 window.screen.orientation doesnt work in safari 16.4

**Comment by Elchi3** [comment]
16.4 came from https://github.com/mdn/browser-compat-data/pull/18963 which was a mass-change.

`"lock" in window.screen.orientation` also returns `false` for me. Opening a PR.

**Comment by nhthai2811** [comment]
The "lock" feature also doesnt work on my ios device (ios 16.4).

**Comment by awm-rzhang** [comment]
screen.orientation returns undefined, ios 16.5, experimental feature flag set to true
