### ISSUE TITLE
html.elements.dialog - compatibility with safari is shown as full support, but the compatibility is not

### ISSUE THREAD

**Issue by ArtimusMaximus** [mdn/browser-compat-data#19373]
### What type of issue is this?

Other

### What information was incorrect, unhelpful, or incomplete?

<dialog> elements on Safari do not work as intended, they are already visible upon page load which is not the intention of using a <dialog> element. I believe that putting 'full support' is a bit misleading. If an individual codes up an entire website using dialog elements, under the guise that they will work as normal on Safari browser, they will have been misled by the 'full support' marking.

### What browsers does this problem apply to, if applicable?

Safari

### What did you expect to see?

I expected to see some form of middle ground compatibility. A color code perhaps, yellow instead of the green. Since this issue is right in the middle of 'it technically loads the content' & 'this will not work as intended'.

### Did you test this? If so, how?

I tested the <dialog> element on various iOS devices with safari. In addition, it is no secret that Safari does not support the <dialog> element, as it is in the 'web components' category, and they do not support web components.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `html.elements.dialog`
* Report started: 2023-04-15T21:34:09.497Z

</details>

**Comment by queengooborg** [comment]
I don't see any issues with the dialog element on Safari; it's working just fine using the MDN examples, as well as in my own use case on my own website.

**Comment by ArtimusMaximus** [comment]
My mistake. I tested my page with Safari on 3 different iOS devices, and apparently none of the browsers were updated since 03 15 2022. And no they are not all my devices! ;)
