### ISSUE TITLE
Add new browser: Vivaldi

### ISSUE THREAD

**Issue by hichxm** [mdn/browser-compat-data#1937]
Hi, recently a web browser named "**Vivaldi**" has made a mini buzz for these features.
But this browser uses the source codes of "**Chromium**".

I will want to know if there is possibility to add it in the browser folder, I tried but I did not manage to validate with the command `npm test`.

![vivaldi source](https://image.noelshack.com/fichiers/2018/17/2/1524569814-vivaldi-source.png)

[vivaldi website](https://vivaldi.com/)

**Comment by ExE-Boss** [comment]
See issues #608, #1072 and #1073 to see how this was implemented in the past.

**Comment by Elchi3** [comment]
Sorry for the late reply here. 

Unless we have commitment from a Vivaldi representative to look after their data (make data updates and review PRs from other contributors, etc), we don't have the bandwidth to support Vivaldi as part of this project. Closing.
