### ISSUE TITLE
api.ServiceWorkerGlobalScope.push_event - iOS 16.4 is supported.

### ISSUE THREAD

**Issue by Dygear** [mdn/browser-compat-data#19390]
### What type of issue is this?

Incorrect support data (example: Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Safari on iOS shows as not supported.

### What browsers does this problem apply to, if applicable?

Safari

### What did you expect to see?

Supported as of 16.4.

### Did you test this? If so, how?

I am using this currently.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://webkit.org/blog/13878/web-push-for-web-apps-on-ios-and-ipados/

### Do you have anything more you want to share?

This should be fixed across the site.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerGlobalScope/push_event

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.ServiceWorkerGlobalScope.push_event`
* Report started: 2023-04-17T04:58:23.931Z

</details>

**Comment by Samshk007** [comment]
Link

**Comment by queengooborg** [comment]
This has been fixed in #22886!
