### ISSUE TITLE
api.HTMLObjectElement.contentDocument - <SUMMARIZE THE PROBLEM>

### ISSUE THREAD

**Issue by SoftMoonWebWare** [mdn/browser-compat-data#19418]
### What type of issue is this?

Incorrect support data (example: Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

FireFox supports this feature from version 1

### What browsers does this problem apply to, if applicable?

Firefox

### What did you expect to see?

correct info

### Did you test this? If so, how?

I want to load an HTMLDocumentFragment into my HTML document.  I want it to work from a local filesystem, so no XMLHTTP requests.  First I find the &lt;object&gt; forces an HTML document head and body, etc. on my fragment, even when I specify &lt;object type='text/plain'&gt; so I cant use .innerHTML to insert the fragment in my greater HTML doc.  No problem, I can extract the relevant document node..... until I find .contentDocument is null.
My fragment sends messages to the console, and they appear first when the &lt;object&gt; loads the fragment.
Then the &lt;object onload="console.log('Foosbutt')"&gt; appears in the console.
Then my HTMLDocument.body (the parent document) onload fires, and:
the &lt;object&gt; is logged to the console, then
an error appears saying .contentDocument is null
Looking at the console, I expand the HTML &lt;object&gt; and see it does have the .contentDocument property.  Its .window property is also null.
Looking at the HTML document in the browser, I see the &lt;object&gt; with its HTML content.....but it doesn't scroll correctly.

So I tried loading a complete HTML page into the &lt;object&gt;.  Same thing.
So I tried moving a complete "included" HTML document into the same folder as its parent folder, just to make sure there wasn't a cross-origin problem.  Same thing.  This "complete" document is used with no problems elsewhere on a regular basis, so I don't think it is the included document itself.

So I must conclude that either (a) FireFox does not support this feature at all, or (b) the documentation does not show WHY this is not supported by FireFox under these conditions.  I have not tried using a server.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

This documentation says it works from FireFox version 1.
If you haven't fixed the bugs by now, .....
I'm not gonna waste my time looking.

### Do you have anything more you want to share?

I write cross-platform desktop apps using HTML/CSS/JavsScript.
Generally, SpiderMonkey is the best JS engine by far.
FireFox's rendering engine ..... not so much

Glad to see MDN back to working after a week of mostly downtime.  DDoS attack?  That sucks.
Took me a week to find out how to even attempt to make this work, and then ... it doesn't.
Well, off to try using an &lt;iframe&gt; with all its background overhead.  
Then again, &lt;object&gt; almost is the same...hope &lt;iframe&gt;  works!
Thanks!

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/HTMLObjectElement/contentDocument

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.HTMLObjectElement.contentDocument`
* Report started: 2023-04-18T15:13:22.102Z

</details>

**Comment by SoftMoonWebWare** [comment]
Github mangled my messages.  every time I referenced an HTML object in the text with the &lt; and &gt; symbols, it thinks I'm trying to use HTML and the text is missing from the message.

**Comment by queengooborg** [comment]
The fact that you're seeing `null` indicates that the property is supported; you would be seeing `undefined` if it wasn't.  As mentioned in the article, this property "returns a [Document](https://developer.mozilla.org/en-US/docs/Web/API/Document) representing the active document of the object element's nested browsing context, if any; otherwise null."

Although it's hard to determine what your issue is without code examples, it sounds like this is less of a browser issue and more of a development help issue.  Unfortunately, we are unable to assist with development issues, and we recommend dedicated websites like StackOverflow instead.
