### ISSUE TITLE
html.elements.object - <SUMMARIZE THE PROBLEM>

### ISSUE THREAD

**Issue by SoftMoonWebWare** [mdn/browser-compat-data#19419]
### What type of issue is this?

Incorrect support data (example: Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

FireFox does not support the "type" attribute

### What browsers does this problem apply to, if applicable?

Firefox

### What did you expect to see?

flying Unicorns? NO.
The truth about browser support? YES!

### Did you test this? If so, how?

I tried loading a "text/plain" document into an &lt;object&gt; and it converted it into HTML, and added a head and body, etc.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

It says it works from FireFox version 1.
I'm not gonna waste my time looking....

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/object

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `html.elements.object`
* Report started: 2023-04-18T15:02:39.728Z

</details>

**Comment by queengooborg** [comment]
Setting the `type` does not influence how the data is rendered -- for example, if you load a PDF file but specify the `type` to be `video/mp4`, the browser will still render the data in a PDF viewer.  That doesn't mean the `type` attribute is unsupported, however.
