### ISSUE TITLE
javascript.builtins.Math.pow - potentially different results on different browsers

### ISSUE THREAD

**Issue by DNiebel** [mdn/browser-compat-data#19429]
### What type of issue is this?

Other

### What information was incorrect, unhelpful, or incomplete?

Depending on input, Math.pow can produce different results on different browsers/platforms

I've categorised the browsers that I tested (see below) as Type1 and Type2 where between browsers of the same type the results are identical.

- Type1: Firefox 112.0.1 (64-Bit Windows), Safari (IOS) & Chrome (IOS)
- Type2: Chrome (64-Bit Windows), MS Edge (64-Bit Windows), Node.js (64-Bit Windows)

### What did you expect to see?

The code below should produce the same result regardless of Browser.

### Did you test this? If so, how?

Pasting this into an MDN JavaScript Demo "Try it" Window ...

A=0xb84293862ba38*2**-56 // (49 significant bits)
B=0x14147dfc6329ce*2**-52 // (48 significant bits)

console.log(Math.pow(A, B).toString(16));
// Expected output (Type1 Browsers): 	0.0538d7ca2a968d4 // (53 significant bits)
// Expected output (Type2 Browsers): 	0.0538d7ca2a968d   // (51 significant bits)

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/pow

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `javascript.builtins.Math.pow`
* Report started: 2023-04-19T12:29:07.082Z

</details>

**Comment by Josh-Cena** [comment]
Hi @DNiebel I'm not sure how to reproduce. Here's the code I assume you provided:

```js
A = 0xb84293862ba38_2 ** -56 // (49 significant bits)
B = 0x14147dfc6329ce_2 ** -52 // (48 significant bits)
console.log(Math.pow(A, B).toString(16))
```

But what I get is that both `A` and `B` become 0.

Also note that (1) floating point precision is implementation-defined (2) precision of math operations is "implementation-approximated" (i.e. they do the best to their capability) (3) the console may not choose to output to the maximum precision, so this is very likely out of scope for BCD, which documents spec discrepancies, not tolerable implementation tradeoffs.

**Comment by DNiebel** [comment]
Hi @Josh-Cena, 👍
I am sorry, when I provided the input for "**Did you test this? If so, how**?", there was an asterisk (for multiplication) in front of 2**-56 and 2**-52 that fell victim to the formatting.

Putting spaces before and after the asterisk the assignments should now work as intended:
A = 0xb84293862ba38 * 2**-56
B = 0x14147dfc6329ce * 2**-52

Regarding points (1) & (2), I looked at [ECMA-262](https://www.ecma-international.org/publications-and-standards/standards/ecma-262/) but could not find any evidence that would support your assertions. Could you please provide some pointers.

Regarding point (3), the console outputs the number as a string. Therefore there won't be a precision problem.

**Comment by Josh-Cena** [comment]
Here are the specs:

https://tc39.es/ecma262/#sec-numeric-types-number-exponentiate

> 13. Return an [implementation-approximated](https://tc39.es/ecma262/#implementation-approximated) Number value representing the result of raising [ℝ](https://tc39.es/ecma262/#%E2%84%9D)(base) to the [ℝ](https://tc39.es/ecma262/#%E2%84%9D)(exponent) power.

> An _implementation-approximated_ facility is one that defers its definition to an external source while recommending an ideal behaviour. While conforming implementations are free to choose any behaviour within the constraints put forth by this specification, they are encouraged to strive to approximate the ideal. Some mathematical operations, such as [`Math.exp`](https://tc39.es/ecma262/#sec-math.exp), are [implementation-approximated](https://tc39.es/ecma262/#implementation-approximated).

The point about floating point precision is less relevant: that's speaking about denormalized numbers, but the numbers here (after your correction) are not small enough to be denormalized. And all mainstream engines support full IEEE-754 precision.

> the console outputs the number as a string

Sorry, I see it now. Never mind that, then!

The issue is indeed that Chrome and Firefox use different floating point exponentiation precisions. To verify, try this:

```js
const A = 0xb84293862ba38 * 2 ** -56;
const B = 0x14147dfc6329ce * 2 ** -52;
const val = Math.pow(A, B);
console.log([...new Uint8Array(new Float64Array([val]).buffer).values()].map((v) => v.toString(16)).join(" "));
```

Here are the outputs in Firefox and Chrome:

```
Firefox: 35 5a aa 28 5f e3 94 3f
Chrome: 34 5a aa 28 5f e3 94 3f
```

However, this is only 1 bit of difference, which makes them both "approximately" acceptable. Again, as long as the behavior is "within the constraints put forth by this specification", it's not a bug nor an incompatibility. Remember that both are ultimately written in C where exponentiation is a bunch of bit operations.

**Comment by DNiebel** [comment]
Thank you. I understand now.
