### ISSUE TITLE
svg.attributes.presentation.color-interpolation-filters and .color-interpolation - Missing support data

### ISSUE THREAD

**Issue by kdashg** [mdn/browser-compat-data#19422]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

svg.attributes.presentation.color-interpolation-filters and svg.attributes.presentation.color-interpolation have no support data.

### What did you expect to see?

svg.attributes.presentation.color-interpolation-filters:
Firefox, Chrome, Edge, and Safari all support it.

svg.attributes.presentation.color-interpolation:
Chrome and Edge support it, but Firefox and Safari ignore it.

### Did you test this? If so, how?

I made a testcase:
https://jsfiddle.net/vy50hge7/1/

On browsers that support svg.attributes.presentation.color-interpolation, the top two rows will look visibly different.

On browsers that support svg.attributes.presentation.color-interpolation-filters, the bottom two rows will look visibly different.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

no

### Do you have anything more you want to share?

no

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/color-interpolation-filters

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `svg.attributes.presentation.color-interpolation-filters`
* Report started: 2023-04-19T00:08:00.697Z

</details>

**Comment by queengooborg** [comment]
This will be naturally fixed as we work through adding values to the SVG data, which is the '23 H2 goal!
