### ISSUE TITLE
http.headers - Service-Worker-Allowed header is missing

### ISSUE THREAD

**Issue by MendyBerger** [mdn/browser-compat-data#19424]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

The `Service-Worker-Allowed` header is missing

### What did you expect to see?

I'd love to see compat data on this header

### Did you test this? If so, how?

No

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://www.w3.org/TR/service-workers/#service-worker-allowed

**Comment by MendyBerger** [comment]
Seems to be supported by all browsers https://wpt.fyi/results/service-workers/service-worker/Service-Worker-Allowed-header.https.html?label=master&product=chrome%5Bexperimental%5D&product=edge&product=firefox%5Bexperimental%5D&product=safari%5Bexperimental%5D&aligned&q=service-worker-allowed

**Comment by skyclouds2001** [comment]
done in https://github.com/mdn/browser-compat-data/pull/25421
