### ISSUE TITLE
javascript.builtins.Array.(toReversed|toSorted|toSpliced) - Incorrect support data - supported in Deno

### ISSUE THREAD

**Issue by lionel-rowe** [mdn/browser-compat-data#19484]
### What type of issue is this?

Incorrect support data (example: Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Deno supports `Array#toReversed` as of v1.32.3.

### What browsers does this problem apply to, if applicable?

Deno

### What did you expect to see?

Updated support data

### Did you test this? If so, how?

```js
$ deno

Deno 1.32.3
exit using ctrl+d, ctrl+c, or close()
REPL is running with all permissions allowed.
To specify permissions, run `deno repl` with allow flags.
> [1, 2].toReversed()
[ 2, 1 ]
```

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/toReversed

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `javascript.builtins.Array.toReversed`
* Report started: 2023-04-25T07:11:32.860Z

</details>

**Comment by Elchi3** [comment]
Fixed in https://github.com/mdn/browser-compat-data/pull/19447 but might take a few more hours until it is live.
