### ISSUE TITLE
javascript.statements.const - <SUMMARIZE THE PROBLEM>

### ISSUE THREAD

**Issue by chaohui2** [mdn/browser-compat-data#19498]
### What type of issue is this?

Incorrect support data (example: Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Const is supported in Chrome for Android version 112 on Can I use , But MDN is 25.

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

not sure

### Did you test this? If so, how?

Const cannot be used in this User-Agent "Mozilla/5.0 (Linux; Android 5.1; Android Build/LMY47D) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/39.0.0.0 Mobile Safari/537.36"

### Do you have anything more you want to share?

![image](https://user-images.githubusercontent.com/17821872/234459435-17ced2d1-e406-480b-b6ee-e5d21bf854d4.png)

### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Statements/const

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `javascript.statements.const`
* Report started: 2023-04-26T02:18:28.247Z

</details>

**Comment by queengooborg** [comment]
CanIUse only reports the latest Chrome Android version, whereas our tables will report the earliest version the feature can be used on.
