### ISSUE TITLE
Add release notes for all major browsers

### ISSUE THREAD

**Issue by connorshea** [mdn/browser-compat-data#1951]
Since opening #1950 for adding release notes to all the releases in `nodejs.json` I've been interested in seeing what other browsers I could add release notes for. Here are my findings:

### Chrome

Chrome has two major places where new releases are catalogued:

- the "New in Chrome" series (e.g. [New in Chrome 66](https://developers.google.com/web/updates/2018/04/nic66)) on the Google Developers blog 
- the [Chrome Releases blog](https://chromereleases.googleblog.com/search/label/Stable%20updates) (e.g. [Stable Channel Update for Desktop](https://chromereleases.googleblog.com/2018/04/stable-channel-update-for-desktop.html)).

There's also the git log, but that's just a list of commits and I'm not really it's particularly useful for the purposes of this repo.

Which should be used in the JSON?

### Microsoft Edge

There are three major places where Microsoft Edge release notes seem to be collected:

- [What’s New in Microsoft Edge in the Windows 10 Fall Creators Update](https://blogs.windows.com/msedgedev/2017/10/17/edgehtml-16-fall-creators-update/), aka EdgeHTML 16, on the Microsoft Edge Developers blog
- [Microsoft Edge Developer Guide](https://docs.microsoft.com/en-us/microsoft-edge/dev-guide) ([permalink for Edge 16](https://aka.ms/devguide_edgehtml_16))
- [Microsoft Edge build 16299 changelog](https://developer.microsoft.com/en-us/microsoft-edge/platform/changelog/desktop/16299/?compareWith=15063), the Changelog uses internal build numbers rather than the integer-based release numbers (12, 13, 14, etc.), so this is fairly error-prone, but it's also the most-relevant to this dataset IMO.

Also worth noting: the "What's New" articles in the Developer Guide have proper permalinks for older versions, but the latest release (16) is only available at a URL which will change contents, e.g. https://docs.microsoft.com/en-us/microsoft-edge/dev-guide/whats-new/edgehtml-15 vs. https://docs.microsoft.com/en-us/microsoft-edge/dev-guide, they do provide a permalink via shortlink though, so that's useful.

### Safari

Safari release notes are included in [`safari.json`](https://github.com/mdn/browser-compat-data/blob/b9da1856bd9d6436057d74920aec7bfb6decb487/browsers/safari.json) right now, but it only goes back to 7, and then there a bunch of blank spots.

Unfortunately the ["What's new in Safari"](https://developer.apple.com/library/content/releasenotes/General/WhatsNewInSafari/Introduction/Introduction.html#//apple_ref/doc/uid/TP40014305-CH1-SW1) docs skip v5 and v6.1, and don't have anything for versions prior to 4. Also, older versions such as [8](https://developer.apple.com/library/content/releasenotes/General/WhatsNewInSafari/Articles/Safari_8_0.html#//apple_ref/doc/uid/TP40014305-CH7-SW1) only mention user-facing features, and say nothing about web features support.

I'm not sure where else this info would be kept, if anyone has anything that could help it'd be appreciated :)

### Safari Mobile

It's not clear how Safari for iOS versioning tracks with regards to the Safari Desktop release notes. I _assume_ they use the same WebKit versions and therefore would share release notes, but I'm not actually sure.

The version release dates are also missing, but those should be easy enough to track down since the Safari versions match the iOS versions and therefore their release dates, you can probably use [the Wikipedia article for iOS version history](https://en.wikipedia.org/wiki/IOS_version_history).

### Internet Explorer

I can't find changelogs/release notes for Internet Explorer, I found [some docs for Internet Explorer 10](https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/dev-guides/hh673549%28v%3dvs.85%29) as well as a few older versions linked from that page, but they don't seem to have any sort of release notes. I assume there are release notes _somewhere_ but I can't find them anywhere.

### Firefox

Release notes are all already complete :)

**Comment by connorshea** [comment]
Oh also, you can see all the browser info (currently v0.0.33, see the footer for the current dataset version) on a webpage with my tool [here](https://mdn-compat-data-explorer.herokuapp.com/browsers) 😉

**Comment by connorshea** [comment]
cc: @jpmedley in case you have anything to add for the Chrome release notes :)

**Comment by jpmedley** [comment]
For Chrome it would need to be both. "New in Chrome" is a rough transcript of the attached video. As a video, It often excludes things that are hard to convey in that medium. Things can also be missing because it's published when a version goes to production, whereas the other is published at beta. Sometimes things don't make it to production.

"New in Chrome" can also contain things not in the beta post because someone failed to fill out their 'paperwork' before we published the beta post.

**Comment by jpmedley** [comment]
Oops. I mixed up the beta blog with the release blog. Let me get back to you.

**Comment by jpmedley** [comment]
Use the release blog.

**Comment by connorshea** [comment]
@jpmedley thanks 👍

**Comment by connorshea** [comment]
@Elchi3 you mentioned in IRC that you have some MS contacts that could help with determining the correct Edge changelogs?

**Comment by Elchi3** [comment]
There is @erikadoyle or @patrickkettner who have been contributing here among other MS folks. (I want to point out that Microsoft has been super responsive and helpful with this project :+1: ).

**Comment by patrickkettner** [comment]
:waves: happy to help!

**Comment by connorshea** [comment]
@patrickkettner could you help determine what we should be linking for the Edge release notes, I have 3 sources mentioned in the issue description but I'm not sure which is the best choice. Thanks :)

**Comment by kypflug** [comment]
@connorshea If you want to pick one, I’d recommend the Edge Dev Guide since it includes the full API diff. The blogs are a good summary if there’s room for two angles on a single release (and they also document end-user changes), but those aren’t necessarily comprehensive. 

As you pointed out the change log is more focused on build-to-build changes so it has more noise. Long term we’d like to merge the Changelog and Dev Guide, but we’re not quite there yet.

**Comment by connorshea** [comment]
I've opened #1993 to add Edge release notes.

**Comment by connorshea** [comment]
I've opened #1994 to add Chrome's release notes, thanks for the tip @jpmedley 👍

**Comment by Elchi3** [comment]
Closing this as only IE seems to be lacking release notes links and I don't think that is a problem. Please file a new issue if you think we should be doing more work on this topic. Thanks :)
