### ISSUE TITLE
"error_event" data should be defined in `HTMLElement.json`, not `Element.json`

### ISSUE THREAD

**Issue by denk0403** [mdn/browser-compat-data#19594]
### What type of issue is this?

Incorrect support data (example: Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

`Element.json` should not contain support data for `error_event` because the [`Element` Web IDL interface](https://dom.spec.whatwg.org/#element) does not define support for `onerror`.

### What did you expect to see?

`onerror` is defined on the [`HTMLElement` Web IDL interface](https://html.spec.whatwg.org/multipage/dom.html#htmlelement), so the "error_event" support data should be moved to `HTMLElement.json`.

### Did you test this? If so, how?

```js
// `onerror` is not found on the `Element` prototype
Object.hasOwn(Element.prototype, "onerror") // false

// `onerror` is found on the `HTMLElement` prototype
Object.hasOwn(HTMLElement.prototype, "onerror") // true
```

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

- https://developer.mozilla.org/en-US/docs/Web/API/Element/error_event

**Comment by Elchi3** [comment]
The content change was made in https://github.com/mdn/content/pull/26494. I don't see a companion PR in BCD, so I will open one to unbreak the MDN page.
