### ISSUE TITLE
api.Window.beforeunload_event - <Chrome 113 had support preventDefault>

### ISSUE THREAD

**Issue by anhulife** [mdn/browser-compat-data#19640]
### What type of issue is this?

Incorrect support data (example: Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

I found that in Chrome 113, it is now possible to use event.preventDefault() to show the confirmation dialog.

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

update browser compatibility info.

### Did you test this? If so, how?

I triggered the confirmation dialog to pop up using the following code.

```
window.addEventListener('beforeunload', event => {
  event.preventDefault();
});
```

### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/API/Window/beforeunload_event

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.Window.beforeunload_event`
* Report started: 2023-05-06T03:27:01.633Z

</details>

**Comment by a-lindsay** [comment]
Chrome feature information confirming it shipped in Chrome 113

https://chromestatus.com/feature/4968823574233088
