### ISSUE TITLE
Microsoft Edge browser versions

### ISSUE THREAD

**Issue by gsouquet** [mdn/browser-compat-data#1966]
It looks like MS has released a new version of Edge according to https://blogs.windows.com/msedgedev/2018/04/30/edgehtml-17-april-2018-update/#8OmA8gQWETrrgZjS.97

However, looking at the browser data for Edge, it only mentions major version `15`, `16`. Which are on a yearly release cycle if I'm not mistaking. 

I tried to find more info regarding those incremental updates throughout the year but couldn't really find what the build number was. 

Should we change the structure of that browser compatibility file to reflect those updates more accurately? Because it shipped some pretty big features.

**Comment by connorshea** [comment]
As it says in the URL, yesterday's release was EdgeHTML 17, it just hasn't been added to the version list yet :)

**Comment by connorshea** [comment]
My understanding is that Edge and EdgeHTML version alongside one another, though I may be wrong.

**Comment by Elchi3** [comment]
I believe we should update the edge and edge_mobile data to make 17 the current version and add 18 as Nightly in case we hear about new features that will make it into the next version.

**Comment by ExE-Boss** [comment]
PR #1976 has now been merged, so this can be closed.

P.S.: You can use the “fixes #1966” syntax to [auto-close the relevant issue](https://help.github.com/articles/closing-issues-using-keywords/) once the PR gets merged.
