### ISSUE TITLE
css.types.color.oklab - wrong support tag

### ISSUE THREAD

**Issue by mzaien** [mdn/browser-compat-data#19768]
### What type of issue is this?

Incorrect support data (example: Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Firefox support for new css level 4 colors as they are being supported starting from version 113 , it is now shows as experimental 

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet), Firefox

### What did you expect to see?

supported tag 

### Did you test this? If so, how?

I did not, but there was a pr adding the support 
https://github.com/mdn/browser-compat-data/pull/19426

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

[Firefox release notes ](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/113?_gl=1*u6w03x*_ga*MTY2MTM1NjE5NS4xNjExNjkyOTQy*_ga_MQ7767QQQW*MTY4MzY5MDYzMS4xMS4xLjE2ODM2OTA2NDMuMC4wLjA)

https://github.com/mdn/browser-compat-data/pull/19426

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/oklab

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.types.color.oklab`
* Report started: 2023-05-10T03:58:10.383Z

</details>

**Comment by queengooborg** [comment]
The experimental symbol you see represents the status of that browser release, because our data has Firefox 113 marked as a beta release.  This will be fixed in the next release!

**Comment by mzaien** [comment]
> The experimental symbol you see represents the status of that browser release, because our data has Firefox 113 marked as a beta release. This will be fixed in the next release!

thanks for clarification
