### ISSUE TITLE
http.status.500 - <SUMMARIZE THE PROBLEM>

### ISSUE THREAD

**Issue by dileepg2020** [mdn/browser-compat-data#19769]
### What type of issue is this?

Other

### What information was incorrect, unhelpful, or incomplete?

I am testing the code using terraform and getting the below error:

"Error: Error creating SystemAdmin resource: Internal Server Error - Internal error when processing the request (500)"

could you please help to resolve this ASAP

thanks 

### What did you expect to see?

Resolution 

### Did you test this? If so, how?

I am testing the code using terraform and getting the below error:

"Error: Error creating SystemAdmin resource: Internal Server Error - Internal error when processing the request (500)"

could you please help to resolve this ASAP

thanks 

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `http.status.500`
* Report started: 2023-05-10T06:28:14.736Z

</details>

**Comment by queengooborg** [comment]
This is not a help forum; we cannot help with development issues.  Please refer to services like StackOverflow instead.
