### ISSUE TITLE
javascript.builtins.Intl.DisplayNames - <Language tag "prs" appears differently on browsers.>

### ISSUE THREAD

**Issue by jpark58** [mdn/browser-compat-data#19801]
### What type of issue is this?

Browser bug (a bug with a feature that may impact site compatibility)

### What information was incorrect, unhelpful, or incomplete?

Depending on browser, language tag "prs" appears differently.

1. On Chrome, "prs" appears to be Dari
<img width="604" alt="prs on chrome" src="https://github.com/mdn/content/assets/48766032/16ca453c-28c6-493c-ae56-c2f9d7cb554e">

2. On Edige, "prs" appears to be Persian
<img width="374" alt="prs on edge" src="https://github.com/mdn/content/assets/48766032/7775a44e-6074-47be-b43a-bbf69ae335da">

### What did you expect to see?

https://en.wikipedia.org/wiki/IETF_language_tag

As per IETF BCP 47 language tag contract, it should be Dari even on Edge.
Is this a known issue?

### Did you test this? If so, how?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DisplayNames#try_it

Try it on different browsers

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DisplayNames

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `javascript.builtins.Intl.DisplayNames`
* Report started: 2023-05-10T17:24:21.559Z

</details>

**Comment by Josh-Cena** [comment]
Please see https://github.com/mdn/browser-compat-data/issues/17994#issuecomment-1515125686 and other issues that deal with Intl formatter output; this falls outside the scope of BCD.
