### ISSUE TITLE
`update-bcd` Improvement Work by Bocoup

### ISSUE THREAD

**Issue by lolaodelola** [mdn/browser-compat-data#19868]
### What would you like to see added to BCD?

1. Redesign the test result schema
        -   Make a schema for the current test results format
        -   Update the web app to produce the new results format
        -   Update the "update-bcd" script and its tests
        -   Update the report data to match the schema

3. Pay down technical debt
        - Draft a proposal ideal behavior of the "update-bcd" script
        - Gather feedback on the proposal
        - Implement the proposal in the BCD repo

4. Enhancements
        - Compile & prioritize a list of enhancements using the issue tracker, project owners & other sources
        - Implement the enhancements in priority order
        - Implement any changes to test results format

### How impactful do you think this enhancement will be?

This will be very impactful to the project, we're proposing improving the `update-bcd` script, which may include rewriting the script.

#### What are the responsibilities of `update-bcd`?

Browser Compact Data (BCD) is the data that’s used to show the availability of Web APIs, CSS rules, HTML elements, etc across browsers and browser versions. The `update-bcd` script is run to ensure this data is accurate and up to date.  The `update-bcd` script does not collect data on the behaviour of specific web browsers, nor does it define how that data should be collected (that is to say: it doesn't do any compatibility testing). The `update-bcd` script only interprets information as provided by external sources in order to update the compact compatibility data structures maintained in BCD.

**Comment by queengooborg** [comment]
This issue is referring to a script from https://github.com/GooborgStudios/mdn-bcd-collector rather than a script here in BCD itself, perhaps we should open it there?

**Comment by lolaodelola** [comment]
Hey @queengooborg,

Since we want the script to live in here eventually, we (bocoup & @foolip) decided it best to live in the BCD repo.

**Comment by Elchi3** [comment]
(I asked this in the call) I think it would be great to include a description (for BCD contributors) to know at a high-level what `update-bcd` is and what it does (and doesn't). With a goal in mind, it will also help to design it better I think.

**Comment by queengooborg** [comment]
Since the decision was to leave the `update-bcd` script in the collector (which has since been moved to OWD ownership), I'm going to go ahead and close this issue.  I also would say that https://github.com/openwebdocs/mdn-bcd-collector/pull/801 has resolved this.  If there's anything that hasn't been done yet, please feel free to open a follow-up issue in the collector repo.
