### ISSUE TITLE
Cookies Having Independent Partitioned State (CHIPS) - Google I/O announced Chrome 110 supported CHIPS (Stable)

### ISSUE THREAD

**Issue by matthewvolk** [mdn/browser-compat-data#19927]
### What type of issue is this?

Incorrect support data (example: Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

In a recent YouTube video released by Google Chrome Developers (https://youtu.be/gm8O8-b2B8c?t=109), the Chrome Team shows a slide in a deck that describes that CHIPS is included in Chrome Stable 110 (Feb 2023). Currently on MDN, Chrome has support marked for "114": https://github.com/mdn/browser-compat-data/blob/92dbe85a8673cf57d6578aa84e8ba75497070216/http/headers/Set-Cookie.json#L122 

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

Chrome: `110`

### Did you test this? If so, how?

Local testing on **Chrome 113** allows me to set the header:
`'set-cookie': 'key=value; SameSite=None; Secure; Path=/; Partitioned; HttpOnly;'`

This result in the Developer Tools > Application > Cookies tab is showing as:
<img width="1512" alt="chips_in_chrome_113" src="https://github.com/mdn/browser-compat-data/assets/28374851/d5b8ee5e-6262-4ad4-83d1-2fd477ac4dfb">

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

I'm happy to open a pull request to update this, but before I do that, this issue should be scrutinized for accuracy; I'm not entirely confident that the video (https://youtu.be/gm8O8-b2B8c?t=109) counts as an official release note. Can anybody test to ensure they _**cannot**_ set a `Partitioned;` cookie in Chrome 109? Can they then test to make sure they _**can**_ set a `Partitioned;` cookie in Chrome 110? For security reasons, I'm currently not on a machine where I'm able to downgrade my Chrome version.

The Chrome Developer Page on CHIPS (https://developer.chrome.com/en/docs/privacy-sandbox/chips/#try-it-out) doesn't have any mention of Chrome 110 supporting CHIPS, though it also does not have any explicit mention that it doesn't support CHIPS in 110. It only mentions the CHIPS origin trial is available from Chrome 100 to 106.

### Do you have anything more you want to share?

When I do open the Pull Request, I plan to update the version in the code reference above (file `http/headers/Set-Cookie.json`). 

I'm not sure if I should follow the lead of https://github.com/mdn/browser-compat-data/pull/19754 which also updated file `api/CookieStore.json`... furthermore, should I also update other Chromium based browsers (Edge 79+, Opera, etc.)?

**Comment by queengooborg** [comment]
CHIPS was originally scheduled to release in 110, but it had been pushed back to 114 (https://chromestatus.com/feature/5179189105786880).  See #18591, #18785 and #19754 for the full history.
