### ISSUE TITLE
api.OffscreenCanvasRenderingContext2D.commit - is not a function

### ISSUE THREAD

**Issue by roginvs** [mdn/browser-compat-data#19929]
### What type of issue is this?

Incorrect support data (example: Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Provided example does not work on Chrome 113 & 114 on Linux. There is no `commit` method at all on `OffscreenCanvasRenderingContext2D` instance.
Works in Firefox

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

I expect `commit` to be a function

### Did you test this? If so, how?

```
  const placeholder = document.createElement("canvas");
  const offscreen = placeholder.transferControlToOffscreen();
  const ctx = offscreen.getContext("2d");

  if (!ctx) {
    throw new Error(`No context`);
  }

  console.info(`Obtained offscreen canvas`);
  if (!(ctx instanceof OffscreenCanvasRenderingContext2D)) {
    throw new Error(`Not a OffscreenCanvasRenderingContext2D!`);
  }

  // Perform some drawing using the 2d context
  ctx.fillStyle = "blue";
  ctx.fillRect(0, 0, 10, 10);

  // Push placeholder to the canvas element
  ctx.commit();
```

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvasRenderingContext2D/commit

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.OffscreenCanvasRenderingContext2D.commit`
* Report started: 2023-05-22T08:55:45.155Z

</details>

**Comment by Elchi3** [comment]
Thanks, the BCD collector confirms this and also there is no `commit` in https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/offscreencanvas/offscreen_canvas.idl.

I will send a PR.
