### ISSUE TITLE
Add browser status pages to schema

### ISSUE THREAD

**Issue by connorshea** [mdn/browser-compat-data#1995]
It'd be nice to have the status page links for each browser when they exist, the four major desktop browsers all have them:

- [Firefox](https://platform-status.mozilla.org/)
- [Chrome](https://www.chromestatus.com/features)
- [Safari/WebKit](https://webkit.org/status/)
- [Edge](https://developer.microsoft.com/en-us/microsoft-edge/platform/status/)

Safari's tracker also works for iOS Safari, and Chrome's tracker works for Chrome for Android, Android Webview, and Opera.

Something like this, in `firefox.json`:

```json
{
  "browsers": {
    "firefox": {
      "status_page": "https://platform-status.mozilla.org",
      "releases": { }
    }
  }
}
```

The status pages are really useful for checking feature support in a given browser.

**Comment by Elchi3** [comment]
As said in https://github.com/mdn/browser-compat-data/pull/3429, this is probably not worth it.
