### ISSUE TITLE
PATCH missing in spec and compat list

### ISSUE THREAD

**Issue by Zectbumo** [mdn/browser-compat-data#19965]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods

### What specific section or headline is this issue about?

specifications & compatibility

### What information was incorrect, unhelpful, or incomplete?

The specification list should have a link for PATCH:
https://www.rfc-editor.org/rfc/rfc5789

browser compatibility for PATCH is missing

### What did you expect to see?

entries for PATCH in spec and compat lists

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/methods`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/methods/index.md
* Last commit: https://github.com/mdn/content/commit/0880a90f3811475d78bc4b2c344eb4146f25f66c
* Document last modified: 2023-04-10T19:47:15.000Z

</details>

**Comment by wbamberg** [comment]
If this is to be fixed, it needs to be fixed in BCD. The page is slurping BCD using a query `http.methods` (https://github.com/mdn/content/blob/c5eee9a1e251bab50a8ae6bdb75861789a817cd3/files/en-us/web/http/methods/index.md?plain=1#LL5C17-L5C29) and that does not include PATCH.
