### ISSUE TITLE
html.elements.track - No captions displayed on audio elements

### ISSUE THREAD

**Issue by Mazurs** [mdn/browser-compat-data#19969]
### What type of issue is this?

Incorrect support data (example: Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Compatibility table says that <track> is supported by various browsers and that it can be used with <audio> tag, but at least Firefox and Chrome doesn't seem to display subtitles for audio.

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet), Firefox

### What did you expect to see?

Text transcript in audio widget.

### Did you test this? If so, how?

I applied the caption info from [track](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio) page to the [audio](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio) example. Sound was working fine but no text.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/track

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `html.elements.track`
* Report started: 2023-05-25T12:57:43.939Z

</details>

**Comment by queengooborg** [comment]
This is normal behavior for audio elements, as described in https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio#accessibility_concerns:

> The `<audio>` element doesn't directly support WebVTT. You will have to find a library or framework that provides the capability for you, or write the code to display captions yourself. One option is to play your audio using a [`<video>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video) element, which does support WebVTT.
