### ISSUE TITLE
javascript.builtins.Array.toReversed - <SUMMARIZE THE PROBLEM>

### ISSUE THREAD

**Issue by APARGA9403** [mdn/browser-compat-data#19980]
### What type of issue is this?

Other

### What information was incorrect, unhelpful, or incomplete?

I tried to use this method in codecademy using Microsoft edge browser and it said that (function does not exist) also I asked chat gpt and it states that this method is not a built in method for Javascript.

### What browsers does this problem apply to, if applicable?

Legacy Edge (12-18)

### What did you expect to see?

I expect this information to be correct, accurate 

### Did you test this? If so, how?

yes, in my code and using chat GPT for source accurate information

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/toReversed

### Do you have anything more you want to share?

![image](https://github.com/mdn/browser-compat-data/assets/62726699/22aeadb4-6d32-4b8a-b235-54ba13ee1d0d)

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/toReversed

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `javascript.builtins.Array.toReversed`
* Report started: 2023-05-27T01:14:37.993Z

</details>

**Comment by Josh-Cena** [comment]
Which Edge version are you using?

> Legacy Edge (12-18)

That seems unlikely.

> using chat GPT for source accurate information

Language models are never reliable information sources because their knowledge is bounded by their training data which does not necessarily include the latest data nor is it able to tell right from wrong for contradictory sources.

**Comment by queengooborg** [comment]
This works just fine in Edge 110, as our documentation states.  The `toReversed()` method _does_ indeed exist, as does the `reverse()` method.

**Comment by APARGA9403** [comment]
you are right it was my mistake....the method it is not supported yet by
codeacademy even though I am using this version of edge:

[image: image.png]
So my guess is that codecademy has to make a revision of this non
standard method, and include it.

Thanks.
