### ISSUE TITLE
MDN 2018 key result: Finish migration of BCD to repo

### ISSUE THREAD

**Issue by jmswisher** [mdn/browser-compat-data#1999]
The complete compat data set should be available in the BCD repository, so the data can be re-used and maintained by interested partners and third-party integrators.

See [this related epic in Taiga](https://tree.taiga.io/project/viya-mdn-durable-team/epic/2473) for previous work

**Comment by Elchi3** [comment]
To give an update where this stands, there are only 2 pages left to fully complete the 2018 year goal:

- Web/HTML/Supported_media_formats
- Web/Manifest

We have issues and PRs for these:
- https://github.com/mdn/browser-compat-data/pull/3446 (proposes schema changes which are not agreed on yet)
- https://github.com/mdn/browser-compat-data/issues/3998 (proposal is to put the data under html/)

**Comment by ddbeck** [comment]
> #3446 (proposes schema changes which are not agreed on yet)

I closed #3446 and opened #4193 in an effort to bypass the schema change question.

**Comment by bershanskiy** [comment]
Update: Web/Manifest was migrated already in PR #4218.
