### ISSUE TITLE
webextensions.api.scripting.registerContentScripts - missing properties available on Chrome 96+

### ISSUE THREAD

**Issue by danielcaldas** [mdn/browser-compat-data#19997]
### What type of issue is this?

Incorrect support data (example: Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

There's no mention to the lack of support of additional register content scripts properties:

- `allFrames`
- `css`
- `world`
- etc.

These properties are available on Chrome 96+, please refer to the [Chrome API reference guide](https://developer.chrome.com/docs/extensions/reference/scripting/#type-RegisteredContentScript).

### What browsers does this problem apply to, if applicable?

Firefox

### What did you expect to see?

Not an error, the `chrome.scripting.registerContentScripts` call should work as in chrome.

### Did you test this? If so, how?

I see the error: `Failed to infer document type Error: Type error for parameter scripts (Error processing 0: Unexpected property "world") for scripting.registerContentScripts.`

When running:

```js
chrome.scripting.registerContentScripts([
      {
        matches: ['http://*/*', 'https://*/*'],
        js: ['myapp.bundle.js'],
        world: 'MAIN',
      },
    ])
```

### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/scripting/registerContentScripts

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `webextensions.api.scripting.registerContentScripts`
* Report started: 2023-05-30T16:49:39.713Z

</details>

**Comment by rebloor** [comment]
@danielcaldas `world` is not supported in Firefox and noted as such in the BCD:
<img width="809" alt="image" src="https://github.com/mdn/browser-compat-data/assets/7352080/94b8142d-5d0b-4600-8be8-a5f14045e3f3">
