### ISSUE TITLE
Safari 11.1 supports Promise.prototype.finally

### ISSUE THREAD

**Issue by Gidgidonihah** [mdn/browser-compat-data#2001]
I would simply add a PR, but I can't find any documentation to support this. I don't know if it was added at 11 or 11.1 but I've verified that 11.1 does support `Promise.prototype.finally`.

The only documentation I can find is that [Safari Technology Preview 37](https://developer.apple.com/safari/technology-preview/release-notes/#r37) added the feature, but I'm not sure when that was incorporated into Safari proper.

**Comment by Gidgidonihah** [comment]
According to http://kangax.github.io/compat-table/es2016plus/ it was added in Safari 11.1 and iOS Safari 11.3

**Comment by ExE-Boss** [comment]
Well, the Safari version reported by iOS 11.3 is 11.1 (only the major version matches, the minor one doesn’t).

**Comment by Elchi3** [comment]
c.f https://bugzilla.mozilla.org/show_bug.cgi?id=1467561
