### ISSUE TITLE
webextensions.manifest.content_scripts - "world" property's missing

### ISSUE THREAD

**Issue by RealAlphabet** [mdn/browser-compat-data#20018]
### What type of issue is this?

Incorrect support data (example: Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Chrome support a property used to define that a script is executed in the context of the page.
https://developer.chrome.com/docs/extensions/reference/scripting/#type-ExecutionWorld

![image](https://github.com/mdn/browser-compat-data/assets/23159705/c219760c-633b-42c8-92b8-0afd499a8ca0)

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

`world` property in the compatibility table.

### Did you test this? If so, how?

N/A.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/content_scripts#browser_compatibility

### Do you have anything more you want to share?

Nothing.

### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/content_scripts

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `webextensions.manifest.content_scripts`
* Report started: 2023-06-03T15:46:33.469Z

</details>

**Comment by RealAlphabet** [comment]
> @RealAlphabet `[ExecutionWorld](https://developer.chrome.com/docs/extensions/reference/scripting/#type-ExecutionWorld)` is associated with [RegisteredContentScript.world](https://developer.chrome.com/docs/extensions/reference/scripting/#type-RegisteredContentScript). It does not refer to manifest content.

I simply used the link that points to the ExecutionWorld definition, i.e. the "scripting" API page. Here's what you're looking for in relation to the manifest. If you made the effort to consult the link, you could also have made the effort to read the beginning of the article, which specifies that the properties are the same as for the declarative version.

https://developer.chrome.com/docs/extensions/mv3/content_scripts/#isolated_world

**Comment by rebloor** [comment]
@RealAlphabet Thanks you for providing the correct reference link. I have reopened the issue. This is quite a simple BCD change - have you considered having a go at it and submitting a PR?
