### ISSUE TITLE
Node.js supports Spread in object literals since version 8.3

### ISSUE THREAD

**Issue by m4staka** [mdn/browser-compat-data#2003]
I think there might be a mistake in the browser compatibility data for the Spread syntax. To my understanding Node.js is supporting Spread in object literals since version 8.3, where the V8 engine has been upgraded to version 6.

If you can confirm that I would be happy to file a PR.

Sources:
[Node.js release notes 8.3](https://nodejs.org/en/blog/release/v8.3.0/)
[V8 release notes 6.0](https://v8project.blogspot.de/2017/06/v8-release-60.html)

**Comment by Elchi3** [comment]
This got fixed https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#Browser_compatibility
