### ISSUE TITLE
Add Thunderbird to the WebExtensions support data

### ISSUE THREAD

**Issue by ExE-Boss** [mdn/browser-compat-data#2008]
Thunderbird 60 is adding [support for WebExtension themes](https://www-stage.thunderbird.net/en-US/thunderbird/60.0/releasenotes/#new-features) and possibly other parts [of the WebExtensions APIs](https://bugzil.la/1396172).

**Comment by Elchi3** [comment]
Please see this answer https://github.com/mdn/browser-compat-data/pull/2333#issuecomment-435333658
