### ISSUE TITLE
Migrate remaining CSS @media pages

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#2009]
The migration of https://developer.mozilla.org/en-US/docs/Web/CSS/@media and sub pages is incomplete. These pages still have old compat tables:

- [x] [Web/CSS/@media/any-hover](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/any-hover)
- [x] [Web/CSS/@media/any-pointer](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/any-pointer)
- [x] [Web/CSS/@media/aspect-ratio](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/aspect-ratio)
- [x] [Web/CSS/@media/color](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/color)
- [x] [Web/CSS/@media/color-gamut](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/color-gamut)
- [x] [Web/CSS/@media/color-index](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/color-index)
- [ ] [Web/CSS/@media/device-aspect-ratio](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/device-aspect-ratio)
- [ ] [Web/CSS/@media/device-height](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/device-height)
- [ ] [Web/CSS/@media/device-width](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/device-width)
- [x] [Web/CSS/@media/display-mode](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/display-mode)
- [x] [Web/CSS/@media/grid](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/grid)
- [x] [Web/CSS/@media/height](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/height)
- [x] [Web/CSS/@media/hover](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/hover)
- [x] [Web/CSS/@media/inverted-colors](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/inverted-colors)
- [x] [Web/CSS/@media/light-level](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/light-level)
- [x] [Web/CSS/@media/monochrome](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/monochrome)
- [x] [Web/CSS/@media/orientation](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/orientation)
- [ ] [Web/CSS/@media/overflow-block](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/overflow-block)
- [ ] [Web/CSS/@media/overflow-inline](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/overflow-inline)
- [x] [Web/CSS/@media/pointer](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/pointer)
- [x] [Web/CSS/@media/resolution](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/resolution)
- [x] [Web/CSS/@media/scan](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/scan)
- [x] [Web/CSS/@media/scripting](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/scripting)
- [x] [Web/CSS/@media/update-frequency](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/update-frequency)
- [x] [Web/CSS/@media/width](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/width)
- [x] [Web/CSS/@media/-webkit-animation](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/-webkit-animation)
- [x] [Web/CSS/@media/-webkit-device-pixel-ratio](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/-webkit-device-pixel-ratio)
- [x] [Web/CSS/@media/-webkit-transform-2d](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/-webkit-transform-2d)
- [x] [Web/CSS/@media/-webkit-transform-3d](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/-webkit-transform-3d)
- [x] [Web/CSS/@media/-webkit-transition](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/-webkit-transition)

@ddbeck can you work on this?

**Comment by ddbeck** [comment]
@Elchi3 Yes, I'll start on this this week (almost recovered from jet lag, so expect a flurry of activity from me on this and other stuff this week)

**Comment by Elchi3** [comment]
We're done here, thanks a lot @ddbeck :+1:
