### ISSUE TITLE
Migrate MathML compat data

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#2010]
MathML compat data migration got started and set up in https://github.com/mdn/browser-compat-data/pull/1740.
The remaining pages are:

- [x] [MathML/Element/maction](https://developer.mozilla.org/en-US/docs/Web/MathML/Element/maction) 
- [x] [MathML/Element/math](https://developer.mozilla.org/en-US/docs/Web/MathML/Element/math) 
- [x] [MathML/Element/menclose](https://developer.mozilla.org/en-US/docs/Web/MathML/Element/menclose) 
- [x] [MathML/Element/merror](https://developer.mozilla.org/en-US/docs/Web/MathML/Element/merror) 
- [x] [MathML/Element/mfenced](https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mfenced) 
- [x] [MathML/Element/mfrac](https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mfrac) 
- [x] [MathML/Element/mglyph](https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mglyph) 
- [x] [MathML/Element/mi](https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mi) 
- [x] [MathML/Element/mlabeledtr](https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mlabeledtr) 
- [x] [MathML/Element/mmultiscripts](https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mmultiscripts) 
- [x] [MathML/Element/mn](https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mn) 
- [x] [MathML/Element/mo](https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mo) 
- [x] [MathML/Element/mover](https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mover) 
- [x] [MathML/Element/mpadded](https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mpadded) 
- [x] [MathML/Element/mphantom](https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mphantom) 
- [x] [MathML/Element/mroot](https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mroot) 
- [x] [MathML/Element/mrow](https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mrow) 
- [x] [MathML/Element/ms](https://developer.mozilla.org/en-US/docs/Web/MathML/Element/ms) 
- [x] [MathML/Element/mspace](https://developer.mozilla.org/en-US/docs/Element/MathML/Element/mspace) 
- [x] [MathML/Element/msqrt](https://developer.mozilla.org/en-US/docs/Web/MathML/Element/msqrt) 
- [x] [MathML/Element/mstyle](https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mstyle) 
- [x] [MathML/Element/msub](https://developer.mozilla.org/en-US/docs/Web/MathML/Element/msub) 
- [x] [MathML/Element/msubsup](https://developer.mozilla.org/en-US/docs/Web/MathML/Element/msubsup) 
- [x] [MathML/Element/msup](https://developer.mozilla.org/en-US/docs/Web/MathML/Element/msup) 
- [x] [MathML/Element/mtable](https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mtable) 
- [x] [MathML/Element/mtd](https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mtd) 
- [x] [MathML/Element/mtext](https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mtext) 
- [x] [MathML/Element/mtr](https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mtr) 
- [ ] [MathML/Element/munderover](https://developer.mozilla.org/en-US/docs/Web/MathML/Element/munderover)
- [ ] [MathML/Element/semantics](https://developer.mozilla.org/en-US/docs/Web/MathML/Element/semantics)

**Comment by maboa** [comment]
I'm happy to take this on.

**Comment by connorshea** [comment]
@Elchi3 fyi all the links in the original issue are broken

**Comment by Elchi3** [comment]
Sorry about that. Fixed now.

**Comment by Elchi3** [comment]
Seems like [MathML/Element/munderover](https://developer.mozilla.org/en-US/docs/Web/MathML/Element/munderover) and [MathML/Element/semantics](https://developer.mozilla.org/en-US/docs/Web/MathML/Element/semantics) are the remaining two missing here. Can you open PRs for these, @maboa ?

**Comment by Elchi3** [comment]
Opened https://github.com/mdn/browser-compat-data/pull/2180 and https://github.com/mdn/browser-compat-data/pull/2181 for the remaining two. We're done here.
