### ISSUE TITLE
Migrate the Window interface

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#2011]
There are about 130 pages for the [`Window` interface](https://developer.mozilla.org/en-US/docs/Web/API/Window) which are still showing the old tables and have no data migrated. See https://developer.mozilla.org/en-US/docs/Web/API/Window$children for all sub pages.
Migrate this data to api/Window.json. 
It is probably easier to open smaller PRs and chunk the work a bit. Maybe do like 20-30 at a time (e.g. members starting with letters A to F or so).

@maboa Do you want to start with this work?

**Comment by keshavmesta** [comment]
I can pitch in. I will get started with letters A to F.

**Comment by keshavmesta** [comment]
As I started going through the list, I quickly realized some of the sub features don't have compatibility table on MDN. How do we handle such cases?

**Comment by Elchi3** [comment]
We can ignore them for now.

**Comment by ExE-Boss** [comment]
Probably ignore them and add them to the MDN Browser Compat Data Migration Google Sheet.

**Comment by keshavmesta** [comment]
@Elchi3 I have covered A-L letters so far, but I need to get couple of things cleared before I send out a PR.

- There are few features with more than one row in the compatibility table, such as [localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage). How that gets fit into JSON? Couldn't find any details in schema file or docs.
- There are few features with support info for "Firefox Mobile", "Opera Mobile" and "Android", however I don't see direct browser identifiers for those browsers in schema doc. Should they be ignored? Or they can be mapped to "firefox_android", "opera_android" and "webview_android" respectively?

**Comment by ExE-Boss** [comment]
> There are few features with more than one row in the compatibility table, such as [`localStorage`](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage). How that gets fit into JSON? Couldn't find any details in schema file or docs.

As sub-features of sub-features.

> There are few features with support info for "Firefox Mobile", "Opera Mobile" and "Android", however I don't see direct browser identifiers for those browsers in schema doc. Should they be ignored? Or they can be mapped to "firefox_android", "opera_android" and "webview_android" respectively?

<table><thead><tr><th scope="col">Old</th><th scope="col">New</th></tr></thead><tbody>
<tr><td>Firefox Mobile</th><td><code>firefox_android</code></th></tr>
<tr><td>Opera Mobile</th><td><code>opera_android</code></th></tr>
<tr><td>Android</th><td><code>webview_android</code></th></tr>
</tbody></table>

**Comment by mlbrgl** [comment]
I had actually started working on that long list of Window properties over the past few weeks (hence my name in the Window column before the sub-rows got created in the sheet). I guess the confusion came from the fact that there was an already committed Window.json from someone's earlier work and you thought I was done with it?

Luckily (for my own sanity :)) I wasn't too far in, I'll discard my work so far and remove my name from the Window row.
It looks like you've got it covered but let me know if you need more help on this one.

**Comment by keshavmesta** [comment]
Just raised a [PR](https://github.com/mdn/browser-compat-data/pull/2109) for properties between A-F.

**Comment by jwhitlock** [comment]
Copying estimate and assignment from sprint planning

**Comment by Elchi3** [comment]
What's missing here seems to be addressing the reviewing comments and merging https://github.com/mdn/browser-compat-data/pull/2021

**Comment by wbamberg** [comment]
I just added the events and went through all the children of [`Window`](https://developer.mozilla.org/en-US/docs/Web/API/Window/). Mostly they look good, but:

* it looks like we missed [`window.cancelAnimationFrame()`](https://developer.mozilla.org/en-US/docs/Web/API/Window/cancelAnimationFrame#Browser_compatibility)

* [`window.URL`](https://developer.mozilla.org/en-US/docs/Web/API/Window/URL#Browser_compatibility) and [`window.StaticRange`](https://developer.mozilla.org/en-US/docs/Web/API/Window/StaticRange#Browser_compatibility) both still have the old-style tables and no BCD entries. Is this because they are constructors?

**Comment by connorshea** [comment]
@wbamberg they've been listed in the spreadsheet for a while, I think they should still be added

**Comment by wbamberg** [comment]
PR for `window.cancelAnimationFrame` -> https://github.com/mdn/browser-compat-data/pull/2564

**Comment by wbamberg** [comment]
Talking to @a2sheppy in IRC confirmed that we should remove the content of the window.URL and window.StaticRange pages, and make them redirect to the docs for those APIs. So I've done that too.

**Comment by wbamberg** [comment]
> Have you made sure to transfer any information that was only in window.URL to URL and window.StaticRange to StaticRange¹?

I don't think there was any.

**Comment by Elchi3** [comment]
The last one here was https://developer.mozilla.org/en-US/docs/Web/API/Window/cancelAnimationFrame#Browser_compatibility which I've just updated to use the new table. 

Thanks everyone who helped with this giant one! :tada: :tada: :tada:
