### ISSUE TITLE
css.properties.page - chrome cuts content in preview when landscape and portrait pages mixed

### ISSUE THREAD

**Issue by 13DaGGeR** [mdn/browser-compat-data#20177]
### What type of issue is this?

Browser bug (a bug with a feature that may impact site compatibility)

### What information was incorrect, unhelpful, or incomplete?

Firefox does not support the page/size directive
Chrome does not support the page/size directive on documents with mix of landscape and portrait pages.

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet), Firefox

### What did you expect to see?

Proper print preview on demo page on https://developer.mozilla.org/en-US/docs/Web/CSS/page

### Did you test this? If so, how?

Using the demo on the page https://developer.mozilla.org/en-US/docs/Web/CSS/page I see bad results on the demo while selecting the "Pages with Grouped Chapters" option.

Chrome 114.0.5735.133 (Official Build) (arm64) cuts the content of the landscape pages while displaying the page shape properly.
<img width="710" alt="image" src="https://github.com/mdn/browser-compat-data/assets/749037/005cda14-2285-413c-8216-f515d2819bb5">

Firefox 113.0.2 (64-bit) ignores `size: a4 landscape;` and displays all the pages as "portrait".
<img width="814" alt="image" src="https://github.com/mdn/browser-compat-data/assets/749037/3a7e0bf6-7cfe-478b-8f42-bea52979d06a">

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/page

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.page`
* Report started: 2023-06-20T12:48:16.601Z

</details>

**Comment by queengooborg** [comment]
I'm having no issues on Chrome; the entire page is displaying properly on my end with both my real printer and when saving to a PDF.  It might have something to do with your margins preference (I'm noticing you have set it to "none").

Firefox, on the other hand, I can confirm is not honoring the page orientation.  This is something we need to track down.

Would you mind actually opening a separate issue for each browser?  While both issues pertain to the `page` property, they are separate issues and should be tracked separately.
