### ISSUE TITLE
Pages with no data

### ISSUE THREAD

**Issue by lucian95** [mdn/browser-compat-data#2019]
I was thinking of adding all the APIs that currently have no data, and filling them with nulls or from [Confluence](https://github.com/mdn/browser-compat-data/blob/master/CONTRIBUTING.md#optional-validatecross-reference-against-web-api-confluence-dashboard). I'm thinking it's better to have empty bcd tables than no tables at all (I'll also add a `NeedsBrowserCompatibility` tag). It should greatly expedite the project and give the docs more consistency.
Thoughts?

**Comment by connorshea** [comment]
There are pros and cons to this approach, it can be hard to find the features that have no compat data (You might be able to find them with my [Explorer](https://mdn-compat-data-explorer.herokuapp.com/features) but I'm not sure how consistent that'd be, or if that'd be considered an acceptable solution given that I'm a third party).

It'll also make it appear that we're making progress when we're _technically_ not (this is debatable I suppose).

I assume there's a reason the MDN team hasn't done this already, but maybe I'm wrong :)

**Comment by Elchi3** [comment]
We're currently working on getting rid of the old tables, i.e. migrate data from the wiki into this repo. We're about 72% done with this work. Remaining pages are listed here: https://gist.github.com/Elchi3/b6863aa227fc4cd51a247957380eca5e (and also partially tracked in the spread sheet).

Creating files with null values is possible, and we have a few PRs opened that do this, but it is currently not the team's focus. So, I'm prioritizing PRs that help us getting to 100% migration done first. We can look into this again at some point, though.

**Comment by Elchi3** [comment]
I think this question was answered.
