### ISSUE TITLE
javascript.builtins.ArrayBuffer.resize - Deno data outdated

### ISSUE THREAD

**Issue by lilnasy** [mdn/browser-compat-data#20208]
### What type of issue is this?

Incorrect support data (example: Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Deno supports ArrayBuffer.prototype.resize since 1.33

### What browsers does this problem apply to, if applicable?

Deno

### What did you expect to see?

✅1.33.0

### Did you test this? If so, how?

by evaluating ArrayBuffer.prototype.resize in the repl of various versions

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://deno.com/blog/v1.33

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer/resize

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `javascript.builtins.ArrayBuffer.resize`
* Report started: 2023-06-22T20:30:49.195Z

</details>

**Comment by queengooborg** [comment]
Hey @lilnasy, thank you for opening up an issue!  We encourage you to open up a pull request to modify the [relevant file](https://github.com/mdn/browser-compat-data/blob/main/javascript/builtins/ArrayBuffer.json), and will be happy to review and merge it right away -- feel free to reach out if you need assistance!

**Comment by lilnasy** [comment]
Thanks for the pointer! It made contributing super easy.
