### ISSUE TITLE
javascript.statements.import - Available in service workers on Safari on iOS 14.1+

### ISSUE THREAD

**Issue by mfulton26** [mdn/browser-compat-data#20219]
### What type of issue is this?

Incorrect support data (example: Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Module import syntax in service workers on Safari on macOS and iOS is, I think, supported.

### What browsers does this problem apply to, if applicable?

Safari

### What did you expect to see?

Support on Safari on iOS for module import in service workers.

### Did you test this? If so, how?

No, I don't currently have access to a iOS device to confirm.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

From Release Notes for Safari Technology Preview 122](https://webkit.org/blog/11577/release-notes-for-safari-technology-preview-122/)

> Added support for modules in Service Workers ([r273224](https://trac.webkit.org/changeset/273224/webkit/))

I believe that means support was added in iOS 14.1 but I'm not certain.

### Do you have anything more you want to share?

I might be able to get an iOS device to test on next week but I'm not sure. I'd really appreciate someone else testing it for me.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `javascript.statements.import`
* Report started: 2023-06-23T19:45:06.884Z

</details>

**Comment by mfulton26** [comment]
This is great. Thank you.

I see that [Worker API: Worker() constructor: Support for ECMAScript modules](https://caniuse.com/mdn-api_worker_worker_ecmascript_modules) is updated on caniuse.com but [ServiceWorker API: Support for ECMAScript modules](https://caniuse.com/mdn-api_serviceworker_ecmascript_modules) isn't (neither is [SharedWorker API: SharedWorker() constructor: Support for ECMAScript modules](https://caniuse.com/mdn-api_sharedworker_sharedworker_ecmascript_modules) but maybe that one is a separate issue).

How can at least the service worker module support one be updated too? (And the shared worker one of applicable?)

**Comment by queengooborg** [comment]
Hey @mfulton26 -- the changes made by the merged PR will be included in the next BCD release, which occurs on Tuesdays and Fridays (usually).  CanIUse is operated independently, so we cannot say when it will be updated, but it's usually a pretty short time after we make a release of BCD!

**Comment by mfulton26** [comment]
Thank you!
