### ISSUE TITLE
javascript.builtins.Intl.NumberFormat - The supporting version chart is out of date

### ISSUE THREAD

**Issue by sven-oly** [mdn/browser-compat-data#20258]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

The NodeJs version info is out of date, e.g., roundingPriority and roundingMode are now supported in Node 20.1.

### What browsers does this problem apply to, if applicable?

Node.js

### What did you expect to see?

I expected up to date info on the support status for NodeJs, Chrome, etc., up to version 20.

### Did you test this? If so, how?

Yes, I'm running number formatting tests with rounding options in NodeJs and found that some options work in Node 20 but not in Node 18, e.g. roundingPriority

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `javascript.builtins.Intl.NumberFormat`
* Report started: 2023-06-29T18:43:25.108Z

</details>

**Comment by Elchi3** [comment]
Thanks for your issue!

I think this shipped in Chrome 106: https://chromestatus.com/feature/5707621009981440
For nodejs, 19.0.0 seems to be the first version that included this: https://nodejs.org/en/blog/release/v19.0.0#v8-10.7
