### ISSUE TITLE
css.types.length - Q

### ISSUE THREAD

**Issue by hartman** [mdn/browser-compat-data#20261]
### What type of issue is this?

Incorrect support data (example: Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Support table says that Q unit is not supported on Safari, but this is incorrect.

### What browsers does this problem apply to, if applicable?

Safari

### What did you expect to see?

Q has been supported since Safari 13.1.

### Did you test this? If so, how?

You can see it is supported by visiting https://css3test.com/#css-values-3

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

Done in: https://trac.webkit.org/changeset/251662/webkit
This revision was part of Safari 13.1 and later (See also GitHub's tag inclusion history https://github.com/WebKit/WebKit/commit/f158f1c46209e61ab185d7729aa9146e322d03fb )

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/length

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.types.length`
* Report started: 2023-06-30T11:17:33.344Z

</details>

**Comment by Elchi3** [comment]
Thanks for your issue! I've sent https://github.com/mdn/browser-compat-data/pull/20264
