### ISSUE TITLE
javascript.classes.private_class_fields - <SUMMARIZE THE PROBLEM>

### ISSUE THREAD

**Issue by kode2050** [mdn/browser-compat-data#20273]
### What type of issue is this?

Browser bug (a bug with a feature that may impact site compatibility)

### What information was incorrect, unhelpful, or incomplete?

Hello Team,

I was testing this concept on 
Chrome Version 114.0.5735.198 (Official Build) (arm64). In short, there is no difference between private and public on chrome.

However, on the same machine, it works perfectly well on Safari Version 16.5.1 (18615.2.9.11.7).

In short, I would report this as bug.

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

Example
class Developer
{
 name; 
 #age;  
 constructor ( name, age)
this.name = name;
this.#age = age;
}
let dave = new Developer ('Dave Dev',21);
console.log(Dave);

- This should not show private fields. In chrome it shows but in Safari it doesn't.

### Did you test this? If so, how?

In developer console
Example
class Developer
{
 name; 
 #age;  
 constructor ( name, age)
this.name = name;
this.#age = age;
}
let dave = new Developer ('Dave Dev',21);
console.log(Dave);

- This should not show private fields. In chrome, it shows but in Safari it doesn't.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

Chrome Version 114.0.5735.198 (Official Build) (arm64) - Does not work
Safari Version 16.5.1 (18615.2.9.11.7). - Works well

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `javascript.classes.private_class_fields`
* Report started: 2023-07-02T15:43:21.466Z

</details>

**Comment by Josh-Cena** [comment]
There's a note right on this page:

> Note: Code run in the Chrome console can access private properties outside the class. This is a DevTools-only relaxation of the JavaScript syntax restriction.

**Comment by kode2050** [comment]
Opps sorry, Thanks for clarifying this is great.
