### ISSUE TITLE
api.FileSystemSyncAccessHandle - synchronous method support needs update

### ISSUE THREAD

**Issue by rhashimoto** [mdn/browser-compat-data#20270]
### What type of issue is this?

Incorrect support data (example: Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

The browser compatibility table shows that synchronous `close`, `flush`, `getSize`, `read`, and `truncate` methods are behind a flag for Chromium browsers and aren't supported for Safari. These synchronous methods are now fully supported.

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet), Safari

### What did you expect to see?

Chromium browsers should show support as of 108, Safari as of 16.4.

### Did you test this? If so, how?

I use [FileSystemSyncAccessHandle synchronous methods to implement persistent storage for SQLite in browsers](https://github.com/rhashimoto/wa-sqlite/discussions/67). There is a demo [here](https://rhashimoto.github.io/preview/demo/ahp-demo.html).

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://developer.chrome.com/blog/new-in-chrome-108/#sync-filehandle

https://developer.apple.com/documentation/safari-release-notes/safari-16_4-release-notes (search for "Made all FileSystemSyncAccessHandle methods synchronous")

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/FileSystemSyncAccessHandle

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.FileSystemSyncAccessHandle`
* Report started: 2023-06-30T15:54:49.888Z

</details>

**Comment by queengooborg** [comment]
This was fixed in #20732!
