### ISSUE TITLE
javascript.builtins.WeakRef - Node.js supports WeakRef to symbol since v20

### ISSUE THREAD

**Issue by bojavou** [mdn/browser-compat-data#20278]
### What type of issue is this?

Incorrect support data (example: Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Node.js is reported as not supporting "Non-registered symbol as target"

### What browsers does this problem apply to, if applicable?

Node.js

### What did you expect to see?

Node.js supports this feature since v20.

### Did you test this? If so, how?

In v19.9.0 (the latest v19), `WeakRef` to a symbol throws an error.

```js
Welcome to Node.js v19.9.0.
Type ".help" for more information.
> new WeakRef(Symbol())
Uncaught TypeError: WeakRef: invalid target
    at new WeakRef (<anonymous>)
```

In v20.0.0 (the first v20 release), `WeakRef` to a symbol now works.

```js
Welcome to Node.js v20.0.0.
Type ".help" for more information.
> const symbol = Symbol()
undefined
> const ref = new WeakRef(symbol)
undefined
> ref.deref() === symbol
true
```

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakRef

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `javascript.builtins.WeakRef`
* Report started: 2023-07-03T02:59:08.429Z

</details>

**Comment by mvduin** [comment]
It was also backported to node v18.20.0
