### ISSUE TITLE
api.IdleDetector - Supported in Edge

### ISSUE THREAD

**Issue by Meir017** [mdn/browser-compat-data#20288]
### What type of issue is this?

Incorrect support data (example: Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Edge is reported to have removed support for the `IdleDetector` API, this is supported in Edge.

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

The Idle detection API is supported by Edge

### Did you test this? If so, how?

Running the example code in the edge devtools and seeing it being executed properly

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Idle_Detection_API

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.IdleDetector`
* Report started: 2023-07-04T09:07:18.605Z

</details>

**Comment by Josh-Cena** [comment]
See https://github.com/mdn/browser-compat-data/pull/16222

I cannot find it in Edge, in an HTTPS website:

<img width="336" alt="image" src="https://github.com/mdn/browser-compat-data/assets/55398995/08142f55-fbe7-4f0a-8591-fa197a6a7c00">

<img width="336" alt="image" src="https://github.com/mdn/browser-compat-data/assets/55398995/ae4748e2-1a83-4b85-9637-76d161f5d74d">

**Comment by Meir017** [comment]
@Josh-Cena I just tested using the description from #16222 is edge supports this
![image](https://github.com/mdn/browser-compat-data/assets/9786571/beaaa371-ce5e-4126-b3e8-ade55ccf2fe7)

https://mdn-bcd-collector.appspot.com/tests/api/IdleDetector

**Comment by Josh-Cena** [comment]
Weirdly, I can also find it now...

**Comment by queengooborg** [comment]
Using the new version of the collector at https://mdn-bcd-collector.gooborg.com/tests/api/IdleDetector (the version on appspot is no longer maintained), I've gone through and found that support for this was added in Edge 114, so that explains why you weren't able to find support earlier, @Josh-Cena!
