### ISSUE TITLE
api.HTMLElement.toggle_event/beforetoggle_event - Supported in Safari 17

### ISSUE THREAD

**Issue by saschanaz** [mdn/browser-compat-data#20298]
### What type of issue is this?

Incorrect support data (example: Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

#20064 forgot to update those events.

### What browsers does this problem apply to, if applicable?

Safari

### What did you expect to see?

`safari: "17"` for those items

### Did you test this? If so, how?

`document.body.ontoggle`

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://webkit.org/blog/14205/news-from-wwdc23-webkit-features-in-safari-17-beta/ (Popover)

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/toggle_event

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.HTMLElement.toggle_event`
* Report started: 2023-07-05T21:35:06.073Z

</details>

**Comment by queengooborg** [comment]
Fixed in #20906!
