### ISSUE TITLE
Lint links in the `notes` attribute

### ISSUE THREAD

**Issue by connorshea** [mdn/browser-compat-data#2029]
I've noticed two problems with links in the `notes` attribute today, it'd be nice if we could have CI automatically check for them.

Links in the `notes` attribute (and anywhere else links can be included, `description`?) should:

- always link to the language-agnostic MDN URL, e.g. use `https://developer.mozilla.org/docs/Web/CSS/text-align` instead of `https://developer.mozilla.org/en-US/docs/Web/CSS/text-align`.
- never provide a relative link, e.g. don't allow links like `/docs/Web/CSS/text-align`.

---------

An example of the second:

https://github.com/mdn/browser-compat-data/blob/5133d14b23996400d17fead58193e7c27c8d0f22/api/Animation.json#L1055

This causes links in my Explorer web app to display incorrectly, the link in this popover leads to a 404 page on the explorer site:

<img width="1146" alt="screen shot 2018-05-15 at 5 09 45 pm" src="https://user-images.githubusercontent.com/2977353/40088187-281b553a-5863-11e8-8e58-7a66a973fe97.png">

Since data is supposed to be usable outside MDN, relative links won't work.

**Comment by connorshea** [comment]
I assume [test-style.js](https://github.com/mdn/browser-compat-data/blob/d919c3f1685e44cce8d045877951a98fbd5ad8d7/test/test-style.js] would be the relevant file here.

**Comment by connorshea** [comment]
The JS regex for detecting relative URLs would be: `^(?!www\.|(?:http)s?:\/\/|[A-Za-z]:\\|\/\/).*`

See also: https://regex101.com/r/fW9eM4/18

**Comment by ExE-Boss** [comment]
Actually, that RegExp is wrong, as it misses some valid URIs, [unlike these from my code](https://github.com/ExE-Boss/new-tab-image/blob/master/src/background.js#L19-L21), which catch all possible URIs:
```javascript
const PAGE_URL_REGEX	= /^([A-Za-z0-9.+-]+:)(?:\/\/)?((?:[A-Za-z0-9-]+\.)*[A-Za-z0-9-]+)\/?/;
const PROTOCOL_REGEX	= /^[A-Za-z0-9.+-]+:(?:\/\/)?/;
const HOST_NAME_REGEX	= /^(?:[A-Za-z0-9-]+\.)*[A-Za-z0-9-]+/;
```
