### ISSUE TITLE
javascript.operators.import_meta - import.meta.resolve is synchronous in Node.js v20

### ISSUE THREAD

**Issue by bojavou** [mdn/browser-compat-data#20324]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

`import.meta.resolve` in Node.js is reported as returning a Promise.

### What did you expect to see?

Since some v20.x release, `import.meta.resolve` in Node.js now returns synchronously.

### Did you test this? If so, how?

I've not run tests.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

The latest Node.js [v19 docs](https://nodejs.org/docs/latest-v19.x/api/esm.html#importmetaresolvespecifier-parent) report returning a Promise:

>This function is asynchronous because the ES module resolver in Node.js is allowed to be asynchronous.

The current [v20 docs](https://nodejs.org/docs/latest-v20.x/api/esm.html#importmetaresolvespecifier-parent) (v20.4.0 at time of writing) report that this is now synchronous:

>In alignment with browser behavior, this now returns synchronously.

History is not given in the Node.js docs. I'm not sure which specific version first made this change.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import.meta

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `javascript.operators.import_meta`
* Report started: 2023-07-10T01:35:42.309Z

</details>

**Comment by bojavou** [comment]
This looks like the PR that made the change.

https://github.com/nodejs/node/pull/43363

**Comment by queengooborg** [comment]
This was fixed in #20726!
