### ISSUE TITLE
html.elements.fieldset - Remove chrome bug hint

### ISSUE THREAD

**Issue by bastiW** [mdn/browser-compat-data#20358]
### What type of issue is this?

Browser bug (a bug with a feature that may impact site compatibility)

### What information was incorrect, unhelpful, or incomplete?

The Chrome Bug does not exist anymore

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

No bug hint; or a version hint when this was resolved. 

### Did you test this? If so, how?

no

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

The bug is resolved see comment 40
https://bugs.chromium.org/p/chromium/issues/detail?id=262679

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/fieldset

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `html.elements.fieldset`
* Report started: 2023-07-14T08:02:15.724Z

</details>

**Comment by queengooborg** [comment]
Fixed by #20390!
