### ISSUE TITLE
html.elements.dialog - Add a row for the close method?

### ISSUE THREAD

**Issue by DanKaplanSES** [mdn/browser-compat-data#20356]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

I think this page would be more internally consistent if its compatibility table included a row for the `close` method. It already includes `open`, and both methods are mentioned in the "See also" section. 

### What did you expect to see?

Since `open` is in the table, I expected to see `close`, too. 

### Did you test this? If so, how?

N/A

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

This row already exists here: https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement/close#browser_compatibility

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `html.elements.dialog`
* Report started: 2023-07-13T22:45:41.952Z

</details>

**Comment by queengooborg** [comment]
The data for `open` here is not talking about the method, but rather the attribute (ex. `<dialog open>`). We only document the attributes in the HTML element's data.
