### ISSUE TITLE
css.properties.text-indent - each-line / hanging keywords supported since Safari 15

### ISSUE THREAD

**Issue by nt1m** [mdn/browser-compat-data#20363]
### What type of issue is this?

Incorrect support data (example: Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Says there is no Safari support

### What did you expect to see?

Supported in Safari 15

### Did you test this? If so, how?

http://wpt.live/css/css-text/text-indent/text-indent-each-line-hanging.html
https://wpt.fyi/css/css-text/text-indent/text-indent-each-line-hanging.html

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/text-indent

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.text-indent`
* Report started: 2023-07-15T21:24:21.385Z

</details>

**Comment by justinpawela** [comment]
https://caniuse.com/css-text-indent

I can personally confirm `hanging` works on macOS Safari at least as of version 16.

**Comment by queengooborg** [comment]
Fixed by https://github.com/mdn/browser-compat-data/pull/21309.
