### ISSUE TITLE
css.selectors.has - Unsupported in Firefox

### ISSUE THREAD

**Issue by rohankalamkar** [mdn/browser-compat-data#20382]
### What type of issue is this?

Browser bug (a bug with a feature that may impact site compatibility)

### What information was incorrect, unhelpful, or incomplete?

:has() function is not working in firefox. Is there any replacement for :has() for firefox. Please suggest any solution.

### What browsers does this problem apply to, if applicable?

Firefox

### What did you expect to see?

:has() function is not working in firefox. Is there any replacement for :has() for firefox. Please suggest any solution.

### Did you test this? If so, how?

:has() function is not working in firefox. Is there any replacement for :has() for firefox. Please suggest any solution.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/:has

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.selectors.has`
* Report started: 2023-07-20T12:15:56.668Z

</details>

**Comment by queengooborg** [comment]
Our data already indicates that Firefox does not support this selector by default.

> Is there any replacement for :has() for firefox. Please suggest any solution.

I'm sorry, but this is not a help forum and we can't provide development help.
