### ISSUE TITLE
Update Date.prototype.toLocaleString for Android and Opera for Android

### ISSUE THREAD

**Issue by Zacqary** [mdn/browser-compat-data#2039]
On https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString

![screen shot 2018-05-16 at 12 06 28 pm](https://user-images.githubusercontent.com/1445834/40132140-9526497a-5901-11e8-9ddd-5312285dc28f.png)

Notice that Firefox Android is marked as having no support for `locales` or `options`. However, testing http://jsbin.com/hovucawibe/edit?html,js,output on Firefox Android 60.0, which outputs the result of:
```javascript
new Date().toLocaleString('en-us', { timeZone: 'America/New_York' })
```
produces the expected result.

I'd open a PR but I don't actually know which version of Firefox Android added support.

**Comment by Elchi3** [comment]
It should be Firefox for Android 56, because this likely depends on the Intl API which was enabled in 56: https://bugzilla.mozilla.org/show_bug.cgi?id=1344625

Can you open the PR that changes these to 56? Thank you :)

**Comment by ExE-Boss** [comment]
The information for normal Android and Opera looks odd to me in that table, so let’s needinfo?(@jpmedley) and keep this open for fixing `Date.prototype.toLocaleString` support information for all browsers.
