### ISSUE TITLE
can't change ime after using eyedropper

### ISSUE THREAD

**Issue by rkawkxkdwlq** [mdn/browser-compat-data#20415]
### What type of issue is this?

Infrastructure issue

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/EyeDropper

### What specific section or headline is this issue about?

Eyedropper

### What information was incorrect, unhelpful, or incomplete?

I'm trying to use the browser's built-in eyedropper, but after using the open method, the windows ime is not being set properly.
If I click outside of the browser to break the focus state of that window or another tap and come back in, it starts working normally.

This problem seems to occur only in Windows browsers.
It doesn't occur on Mac

i'm using Chrome browser and also Edge Browser.
IME is mode for Language.
cannot change keyboard language in browser

![image](https://github.com/mdn/content/assets/24672968/33ae6771-078f-45c2-9483-ba7929bbba5d)

example)
After using the eyedropper inside https://developer.mozilla.org/en-US/docs/Web/API/EyeDropper, you can see that the IME settings are not working properly in the search input tag at the top.

https://github.com/mdn/content/assets/24672968/646a5a51-3939-4df3-b88c-a503bffa78b3

### What behavior were you expecting?

The keyboard's korean/english keys work normally after the eyedropper action

### What version(s) of BCD is the issue present in?

- [x] The current BCD release
- [X] The current version of the `main` branch

**Comment by queengooborg** [comment]
This isn't a BCD infrastructure issue, but it seems like it's probably a Windows issue, or a Chrome issue.  I'd recommend filing a bug report with Chrome if there isn't one already: https://crbug.com
