### ISSUE TITLE
createImageBitmap() - options.resize{width, height} is supported on iOS, but reported as unsupported

### ISSUE THREAD

**Issue by FrostKiwi** [mdn/browser-compat-data#20416]
### What type of issue is this?

Incorrect support data (example: Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

I use https://developer.mozilla.org/en-US/docs/Web/API/createImageBitmap and [in my use case](https://github.com/FrostKiwi/Mirrorball/commit/ecb15d7638b6f20fb999764d56b23acc00d9bff1#diff-1e418e5b4f4a2f3ab6a718440ba481e1fad44edc626dcc5edeae3d7378187215R102) I want to downscale textures via `options.resizeWidth` and `options.resizeHeight` before pushing them to the GPU via WebGL in case the texture size is not supported.
I was worried to find iOS not supporting the resizing, as reported by https://developer.mozilla.org/en-US/docs/Web/API/createImageBitmap, and having to come up with a hacky solution.
I implemented it anyways and was pleasantly surprised to find the resizing working perfectly on both Edge and Safari on an `iPhone SE iOS 16.5.1` and an `iPad 9th gen, iPadOS 16.5.1`.

### What browsers does this problem apply to, if applicable?

Safari

### What did you expect to see?

`options.resizeWidth` and `options.resizeHeight` of `createImageBitmap()` as supported.

### Did you test this? If so, how?

Tested via https://github.com/FrostKiwi/Mirrorball/commit/ecb15d7638b6f20fb999764d56b23acc00d9bff1#diff-1e418e5b4f4a2f3ab6a718440ba481e1fad44edc626dcc5edeae3d7378187215R102 on an `iPhone SE iOS 16.5.1` and an `iPad 9th gen, iPadOS 16.5.1`.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://developer.mozilla.org/en-US/docs/Web/API/createImageBitmap

**Comment by queengooborg** [comment]
Fixed in #20997!
