### ISSUE TITLE
css.properties.transform-box - Chrome partially supports `transform-box`

### ISSUE THREAD

**Issue by hbghlyj** [mdn/browser-compat-data#20412]
### What type of issue is this?

Incorrect browser support data

### What information was incorrect, unhelpful, or incomplete?

Chrome has full support for `transform-box`

### What browsers does this problem apply to, if applicable?

Chrome latest (115.0.5790.102)

### What did you expect to see?

Chrome partially supports `transform-box`: It doesn&rsquo;t support value `content-box`, `border-box`, `stroke-box`

### Did you test this? If so, how?

A screenshot of Chrome devtool autocomplete:
![image](https://github.com/mdn/content/assets/53823634/e4ec4d93-09ca-46fd-b1a4-92749eedafd3)

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/transform-box

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.transform-box`
* Report started: 2023-07-25T17:41:23.436Z

</details>

**Comment by queengooborg** [comment]
Subfeatures for these values was added in #21023!
