### ISSUE TITLE
css.properties.grid-template-columns.subgrid - Supported in Chrome

### ISSUE THREAD

**Issue by Freytag** [mdn/browser-compat-data#20452]
### What type of issue is this?

Incorrect support data (example: Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Chrome added full `subgrid` support in 117

https://caniuse.com/?search=subgrid

https://chromestatus.com/feature/5663795354533888

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

Desktop chromium showing support as of 117 (no feature flag needed)

### Did you test this? If so, how?

i have used chrome 117 to verify

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://chromestatus.com/feature/5663795354533888

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Subgrid

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.grid-template-columns.subgrid`
* Report started: 2023-08-01T15:17:48.965Z

</details>

**Comment by HolgerJeromin** [comment]
This was partly fixed by #20552
But MDN shows surprising data for mobile browsers:
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Subgrid#browser_compatibility
![image](https://github.com/mdn/browser-compat-data/assets/2410353/c3421656-fc47-425f-84f2-07a8a245cfcb)

**Comment by queengooborg** [comment]
Actually, #20552 fully fixes this!
