### ISSUE TITLE
Incorrect data for Safari and `Element.prototype.requestFullScreen`

### ISSUE THREAD

**Issue by romainmenke** [mdn/browser-compat-data#20463]
### What type of issue is this?

Incorrect support data (example: Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullScreen#browser_compatibility

`requestFullScreen` is not supported in Safari.

### What browsers does this problem apply to, if applicable?

Safari

### What did you expect to see?

I expected correct compat data

### Did you test this? If so, how?

https://wpt.fyi/results/fullscreen/api/element-request-fullscreen.html?label=master&label=experimental&aligned&q=full%20screen

And I ran the live test on an actual Safari version.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

This was introduced in https://github.com/mdn/browser-compat-data/pull/18963

**Comment by queengooborg** [comment]
Running the test in Safari 16.4 and the latest Safari, the test passes as expected.
