### ISSUE TITLE
css.selectors.-webkit-scrollbar - <SUMMARIZE THE PROBLEM> the problem is when I want to create customize scrollbar it doesn't but the same css is applied on global styles.

### ISSUE THREAD

**Issue by gaurav0909-max** [mdn/browser-compat-data#20517]
### What type of issue is this?

Incorrect support data (example: Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

the problem is when I want to create customize scrollbar it doesn't but the same css is applied on global styles.

### What did you expect to see?

work as we want like in documentation for div classname or with div id

### Did you test this? If so, how?

with my existing code

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

not now

### Do you have anything more you want to share?

nope

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.selectors.-webkit-scrollbar`
* Report started: 2023-08-09T09:26:37.547Z

</details>

**Comment by queengooborg** [comment]
It sounds like you're looking for development help, but it's hard to tell with the minimal information that has been provided.  Please note that we cannot provide development assistance, and you should refer to sites like StackOverflow for help instead.
