### ISSUE TITLE
webextensions.api.menus.onClicked - full tab data missing in Safari

### ISSUE THREAD

**Issue by daniandl** [mdn/browser-compat-data#20592]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

First off: my extension uses activeTab.
When clicking on a context menu item while the Safari extension toolbar icon is greyed out (not activated on this page), the tab data returned inside the onClicked callback is missing crucial information like the tab url.

I assume this is due to the extension getting access to the tab *after* the click handler has run.
So if you need tab data, you essentially need to `query({ tabId })` to find the tab. Thankfully, the tab ID is returned.

### What browsers does this problem apply to, if applicable?

Safari

### What did you expect to see?

This would be helpful to mention for future developers running into this issue.

### Did you test this? If so, how?

Ran the extension in Safari 16.6, followed steps as described above.

### Do you have anything more you want to share?

This page may not be the right/only place to mention this specific issue.

### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/menus/onClicked

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `webextensions.api.menus.onClicked`
* Report started: 2023-08-23T16:16:38.793Z

</details>

**Comment by rebloor** [comment]
@jdatapple are you able to shed any light on this?

**Comment by jdatapple** [comment]
This appears to be a bug. It has a fix, but it has not shipped yet.

**Comment by rebloor** [comment]
@daniandl Closing as this was indicated as a bug in Safari.

**Comment by xeenon** [comment]
@rebloor This can be closed.
