### ISSUE TITLE
WebAuthn: Chrome Update

### ISSUE THREAD

**Issue by apowers313** [mdn/browser-compat-data#2059]
Chrome 67 now supports:

* CTAP2 over USB with the flag --enable-features=WebAuthenticationCtap2
* U2F over Bluetooth with the flag --enable-features=WebAuthenticationBle

**Comment by Elchi3** [comment]
I think this got done: https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API#Browser_compatibility
