### ISSUE TITLE
javascript.classes.static - <SUMMARIZE THE PROBLEM>  The static keyword is supported from firefox version 45. But it is not working in firefox version 70. Kindly check and update the same in MDN.

### ISSUE THREAD

**Issue by hg-62** [mdn/browser-compat-data#20622]
### What type of issue is this?

Incorrect support data (example: Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

incorrect

### What browsers does this problem apply to, if applicable?

Firefox

### What did you expect to see?

The key word should work

### Did you test this? If so, how?

I have tested by running a script in console containing static key word.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/static

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `javascript.classes.static`
* Report started: 2023-08-29T11:13:17.894Z

</details>

**Comment by Josh-Cena** [comment]
In what way does it "not work"?

Static fields and static methods are two features; if you are talking about static fields, then they only work after Firefox 69; we need to port the data of https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Public_class_fields.

**Comment by queengooborg** [comment]
I'm closing this issue because there is not enough actionable information.
