### ISSUE TITLE
css.properties.offset-anchor - Supported in Chrome

### ISSUE THREAD

**Issue by xirclebox** [mdn/browser-compat-data#20628]
### What type of issue is this?

Incorrect support data (example: Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

After testing, offset-anchor works in Chrome 116.0.5845.112 (Official Build) (64-bit)

![image](https://github.com/mdn/browser-compat-data/assets/847992/353454cb-0093-45cf-9b8a-8ec124cbba71)

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

I expected the CSS to fail and the position not to update accordingly.

### Did you test this? If so, how?

I went through each of the examples on the MDN page  https://developer.mozilla.org/en-US/docs/Web/CSS/offset-anchor

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://developer.mozilla.org/en-US/docs/Web/CSS/offset-anchor

### Do you have anything more you want to share?

This also works on the latest version of the Chrome browser on Android.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/offset-anchor

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.offset-anchor`
* Report started: 2023-08-29T23:59:15.512Z

</details>

**Comment by Elchi3** [comment]
Thanks for your issue! Looks like many new features shipped in Chrome as part of shipping CSS Motion Path https://chromestatus.com/feature/5124394449371136
