### ISSUE TITLE
api.RTCPeerConnection.getReceivers - <SUMMARIZE THE PROBLEM>

### ISSUE THREAD

**Issue by maqun520** [mdn/browser-compat-data#20629]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1
浏览器获取的是空的对象数组，应该是不兼容最新的苹果浏览器

### What browsers does this problem apply to, if applicable?

Safari

### What did you expect to see?

可以获取到相关的RTCRtpReceiver

### Did you test this? If so, how?

测试过 

### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/API/RTCPeerConnection/getReceivers

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.RTCPeerConnection.getReceivers`
* Report started: 2023-08-30T08:33:52.779Z

</details>

**Comment by queengooborg** [comment]
I'm closing this issue because there is no actionable information.
