### ISSUE TITLE
Add compatibility data for `image-rendering: smooth`

### ISSUE THREAD

**Issue by yisibl** [mdn/browser-compat-data#20639]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

Firefox supports image-rendering: smooth in some version, but I can't find out which one.

![image](https://github.com/mdn/browser-compat-data/assets/2784308/1ebb0340-22b4-4298-a4de-34d337c9ce44)

### What browsers does this problem apply to, if applicable?

Firefox

### What did you expect to see?

Add compatibility data for `image-rendering: smooth`

### Did you test this? If so, how?

-

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://developer.mozilla.org/en-US/docs/Web/CSS/image-rendering#browser_compatibility

**Comment by queengooborg** [comment]
This was added in #21020!

**Comment by yisibl** [comment]
Thanks a lot, is there a link to bugzilla.mozilla.org here?

**Comment by queengooborg** [comment]
We don't really add Bugzilla links for features that are supported and don't have caveats, especially as most of our data is automatically tested and updated nowadays.
