### ISSUE TITLE
CSS image-set Support Incorrect

### ISSUE THREAD

**Issue by jonahShaf** [mdn/browser-compat-data#20632]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/image/image-set

### What specific section or headline is this issue about?

Browser compatibility

### What information was incorrect, unhelpful, or incomplete?

Current versions of Firefox do support image-set without the -webkit- vendor prefix. Not clear to me when this changed. Can I Use indicates this started somewhere around version 113-115.

### What did you expect to see?

Indication of when Firefox started fully supporting image-set

### Do you have anything more you want to share?

https://caniuse.com/css-image-set

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/image/image-set`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/image/image-set
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/image/image-set/index.md
* Last commit: https://github.com/mdn/content/commit/2a23f650d86d4f5d948614a607224a2bd52cca33
* Document last modified: 2023-04-28T05:58:54.000Z

</details>

**Comment by bsmth** [comment]
Thanks for flagging. I haven't investigated, but moved over to BCD in the meantime.

**Comment by queengooborg** [comment]
I'm not sure what would need to change in our data here.  Our data has parity with CanIUse.
