### ISSUE TITLE
api.Document.caretPositionFromPoint - Appears to be supported in chrome 115.0.5790.170

### ISSUE THREAD

**Issue by LordBaryhobal** [mdn/browser-compat-data#20644]
### What type of issue is this?

Incorrect support data (example: Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Document.caretPositionFromPoint() is marked as unsupported by Chrome but it works (at least in version 115.0.5790.170)

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

The method should be marked as compatible with Chrome

### Did you test this? If so, how?

I only tested it with Chrome 115.0.5790.170
The example provided in the documentation works as intended

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Document/caretPositionFromPoint

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.Document.caretPositionFromPoint`
* Report started: 2023-09-01T21:35:37.485Z

</details>

**Comment by queengooborg** [comment]
The example uses a fallback if the standard property isn't supported, so the example is not a good indication of support.
