### ISSUE TITLE
api.ReadableStream.from_static - Deno supports static ReadableStream.from

### ISSUE THREAD

**Issue by KnorpelSenf** [mdn/browser-compat-data#20679]
### What type of issue is this?

Incorrect support data (example: Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream/from_static is supported since Deno 1.35, see https://github.com/denoland/deno/pull/19446

### What did you expect to see?

Have `ReadableStream.from` support listed for Deno since 1.35

### Did you test this? If so, how?

No. Look at https://github.com/denoland/deno/pull/19446.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://github.com/denoland/deno/pull/19446

### Do you have anything more you want to share?

No.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream/from_static#browser_compatibility

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.ReadableStream.from_static`
* Report started: 2023-09-09T19:18:38.466Z

</details>

**Comment by queengooborg** [comment]
Fixed in #21153!
