### ISSUE TITLE
Replace/enhance manually curated data with automated tests/WPT data

### ISSUE THREAD

**Issue by JannisBush** [mdn/browser-compat-data#20677]
### What would you like to see added to BCD?

Currently BCD consist of manually curated data that can be incorrect (#20676), outdated and has to be manually updated for new browser versions.
For most of the features automated tests already exist in [WPT](https://github.com/web-platform-tests/wpt) or could be created, automated runners already exist for the main browsers (https://wpt.fyi/results/) and could be added for other browsers as well. 
Thus, I suggest to link the WPT outcomes to the compatibility tables or use another test system to automatically provide this information.

### How impactful do you think this enhancement will be?

The compat data is used by many developers and tools (e.g., [caniuse](https://caniuse.com/?search=allow-from)) and any issue in them can have negative consequences if developers are misled by them.

In addition, in the long run, having automated test outcomes in the table should reduce the manual maintaining effort as the data does not have to be manually updated for each new browser version.

### Do you have anything more you want to share?

Running all WPT tests on all browsers (particularly mobile) could be too resource intensive, however as the compat data is mostly binary (feature exist + optional notes with caveats) and does not aim to have the same granularity as WPT results, it might be enough to run a single core test for each feature to show whether the feature is working/existing at all in the browser.

**Comment by JannisBush** [comment]
I didn't know about https://github.com/foolip/mdn-bcd-collector which seems to party achieve the goal of automatically testing and updating compat data. However, it does not seem to contain any tests on HTTP headers.

**Comment by queengooborg** [comment]
We are currently working towards fully automatic data collection for features tracked in BCD (see https://mdn-bcd-collector.gooborg.com).

**Comment by JannisBush** [comment]
That's great :)
Is there any place where the progress is tracked? E.g., a github issue or project?
At least all the (security) header tests seem to be missing currently.
