### ISSUE TITLE
api.IDBIndex.keyPath - <SUMMARIZE THE PROBLEM>

### ISSUE THREAD

**Issue by dyaael** [mdn/browser-compat-data#20697]
### What type of issue is this?

Other

### What information was incorrect, unhelpful, or incomplete?

22:03:16.267 Layout was forced before the page was fully loaded. If stylesheets are not yet loaded this may cause a flash of unstyled content. login.php:1:2580
22:03:16.283 Cookie “m_pixel_ratio” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite login.php:1:2329
22:03:16.283 Cookie “wd” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite login.php:1:2329
22:03:16.299 When rendering the <html> element, the used values of CSS properties “writing-mode”, “direction”, and “text-orientation” on the <html> element are taken from the computed values of the <body> element, not from the <html> element’s own values. Consider setting these properties on the :root CSS pseudo-class. For more information see “The Principal Writing Mode” in https://www.w3.org/TR/css-writing-modes-3/#principal-flow login.php
22:03:16.267 Layout was forced before the page was fully loaded. If stylesheets are not yet loaded this may cause a flash of unstyled content. login.php:1:2580
22:03:16.267 Layout was forced before the page was fully loaded. If stylesheets are not yet loaded this may cause a flash of unstyled content. login.php:1:2580
22:03:16.267 Layout was forced before the page was fully loaded. If stylesheets are not yet loaded this may cause a flash of unstyled content. login.php:1:2580
22:03:16.267 Layout was forced before the page was fully loaded. If stylesheets are not yet loaded this may cause a flash of unstyled content. login.php:1:2580

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet), Firefox, Legacy Edge (12-18), Safari, Node.js, Deno

### What did you expect to see?

My page has been hacked I need help I asked you here before and I was helped in January 2021 and I sent for anything here that helps I couldn't find the warehouse I left here I need help now   

### Did you test this? If so, how?

My page has been hacked I need help I asked you here before and I was helped in January 2021 and I sent for anything here that helps I couldn't find the warehouse I left here I need help now   

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

Layout was forced before the page was fully loaded. If stylesheets are not yet loaded this may cause a flash of unstyled content.

https://m.facebook.com/login.php?next=https%3A%2F%2Fm.facebook.com%2FKoshary.goha.sohag%2F&ref=104&rs=6&lrs=3&rid=100076603051722&lrid=100076603051722&refsrc=deprecated&refid=17
https://profiler.firefox.com/zee-worker.js

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/IDBIndex/keyPath

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.IDBIndex.keyPath`
* Report started: 2023-09-12T16:35:59.025Z

</details>

**Comment by dyaael** [comment]
‫أُرسلت من الـ iPhone‬‫في 13‏/09‏/2023 الساعة 9:42 ص، كتب/كتبت ‏queengooborg ***@***.***>:‬﻿
Closed #20697 as not planned.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread. I do not write the topic. I can prove it with pictures and complete files. Ask for help. Can I find it or not? Message ID: ***@***.***>
These are some of the accounts they used to hack my page with a file for the page that I downloaded more than a year ago and I have files for all the followers and comments. My page had 170,000 followers. It was stolen from me about a month ago. The followers’ finger had 130,000. Do you notice the difference? He posts pictures similar to the content of the page. But it displays sexual images in the story of the page, and I am the one who designed, created and produced the video clip since the time the page was created, and no one has published it except me. Everything on it is me who designed and published it, and I put the title of the page in red in the videos and even the articles. I am the one who wrote it, so please do not say that I am familiar with the topic.html{touch-action:manipulation}body{background:#fff;color:#1c1e21;direction:ltr;line-height:1.34;margin:0;padding:0;unicode-bidi:embed}body,button,input,label,select,td,textarea{font-family:'Segoe UI Historic', 'Segoe UI', Helvetica, Arial, sans-serif;font-size:12px}h1,h2,h3,h4,h5,h6{color:#1c1e21;font-size:13px;font-weight:600;margin:0;padding:0}h1{font-size:14px}h4,h5,h6{font-size:12px}p{margin:1em 0}b,strong{font-weight:600}a{color:#385898;cursor:pointer;text-decoration:none}button{margin:0}a:hover{text-decoration:underline}img{border:0}td,td.label{text-align:left}dd{color:#000}dt{color:#606770}ul{list-style-type:none;margin:0;padding:0}abbr{border-bottom:none;text-decoration:none}hr{background:#dadde1;border-width:0;color:#dadde1;height:1px}form{margin:0;padding:0}label{color:#606770;cursor:default;font-weight:600;vertical-align:middle}label input{font-weight:normal}textarea,.inputtext,.inputpassword{border:1px solid #ccd0d5;border-radius:0;margin:0;padding:3px}textarea{max-width:100%}select{border:1px solid #ccd0d5;padding:2px}input,select,textarea{background-color:#fff;color:#1c1e21}.inputtext,.inputpassword{padding-bottom:4px}.inputtext:invalid,.inputpassword:invalid{box-shadow:none}.inputradio{margin:0 5px 0 0;padding:0;vertical-align:middle}.inputcheckbox{border:0;vertical-align:middle}.inputbutton,.inputsubmit{background-color:#4267b2;border-color:#DADDE1 #0e1f5b #0e1f5b #d9dfea;border-style:solid;border-width:1px;color:#fff;padding:2px 15px 3px 15px;text-align:center}.inputaux{background:#ebedf0;border-color:#EBEDF0 #666 #666 #e7e7e7;color:#000}.inputsearch{background:#FFFFFF url(https://z-p3-static.xx.fbcdn.net/rsrc.php/v3/yL/r/unHwF9CkMyM.png) no-repeat left 4px;padding-left:17px}.clearfix:after{clear:both;content:'.';display:block;font-size:0;height:0;line-height:0;visibility:hidden}.clearfix{zoom:1}.datawrap{word-wrap:break-word}.word_break{display:inline-block}.ellipsis{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.aero{opacity:.5}.column{float:left}.center{margin-left:auto;margin-right:auto}#facebook .hidden_elem{display:none!important}#facebook .invisible_elem{visibility:hidden}#facebook .accessible_elem{clip:rect(1px, 1px, 1px, 1px);height:1px;overflow:hidden;position:absolute;white-space:nowrap;width:1px}#facebook .accessible_elem_offset{margin:-1px}.direction_ltr{direction:ltr}.direction_rtl{direction:rtl}.text_align_ltr{text-align:left}.text_align_rtl{text-align:right}body{overflow-y:scroll}.mini_iframe{overflow-y:visible}.auto_resize_iframe{height:auto;overflow:hidden}.pipe{color:gray;padding:0 3px}#content{margin:0;outline:none;padding:0;width:auto}.profile #content,.home #content,.search #content{min-height:600px}.UIStandardFrame_Container{margin:0 auto;padding-top:20px;width:960px}.UIStandardFrame_Content{float:left;margin:0;padding:0;width:760px}.UIStandardFrame_SidebarAds{float:right;margin:0;padding:0;width:200px;word-wrap:break-word}.UIFullPage_Container{margin:0 auto;padding:20px 12px 0;width:940px}.empty_message{background:#f5f6f7;font-size:13px;line-height:17px;padding:20px 20px 50px;text-align:center}.see_all{text-align:right}.standard_status_element{visibility:hidden}.standard_status_element.async_saving{visibility:visible}img.tracking_pixel{height:1px;position:absolute;visibility:hidden;width:1px}#globalContainer{margin:0 auto;position:relative;zoom:1}.fbx #globalContainer{width:981px}.sidebarMode #globalContainer{padding-right:205px}.fbx #tab_canvas>div{padding-top:0}.fb_content{min-height:640px;padding-bottom:20px}.fbx .fb_content{padding-bottom:0}.skipto{display:none}.home .skipto{display:block}._li._li._li{overflow:initial}._aj3e,._aj3e video{display:block;height:4px;left:0;position:absolute;top:0;width:2px;z-index:-1}._910i._li._li._li{overflow:hidden}._9053 ._li._li._li{overflow-x:hidden}._72b0{position:relative;z-index:0}.registration ._li._9bpz{background-color:#f0f2f5}._li ._9bp-{padding-top:5px;text-align:center}._li ._9bp- .fb_logo{height:100px}._li ._a66f{padding-top:5px;text-align:center}._li ._a66f .fb_logo{height:80px;padding-top:72px}._5vb_ #pageFooter{display:none}html body._5vb_ #globalContainer{width:976px}._5vb_.hasLeftCol #headerArea{margin:0;padding-top:0;width:786px}._5vb_,._5vb_ #contentCol{background-color:#e9ebee;color:#1d2129}html ._5vb_.hasLeftCol #contentCol{border-left:0;margin-left:172px;padding-left:11px;padding-top:11px}._5vb_.hasLeftCol #topNav{border-left:0;margin-left:172px;padding:11px 7px 0 11px}._5vb_.hasLeftCol #topNav~#contentCol{padding-top:0}._5vb_.hasLeftCol #leftCol{padding-left:8px;padding-top:12px;width:164px}._5vb_.hasLeftCol #mainContainer{border-right:0;margin-left:0}._5vb_.hasLeftCol #pageFooter{background:none}html ._5vb_._5vb_.hasLeftCol div#contentArea{padding-left:0;padding-right:10px;width:786px}html ._5vb_._5vb_.hasLeftCol .hasRightCol div#contentArea{width:496px}._5vb_.hasLeftCol ._5r-_ div#rightCol{padding:0 7px 0 0;width:280px}._2yq #globalContainer{width:1012px!important}._2yq #headerArea{float:none!important;padding:0 0 12px 0!important;width:auto!important}._2yq #contentArea{margin-right:0;padding:0!important}._2yq #leftCol,._2yq #contentCol{padding:0!important}._2yq #rightCol{float:left;margin-top:0;padding:0!important}.tinyViewport ._2yq #pagelet_navigation.fixed_elem{position:static!important}._2yq .loggedout_menubar_container{min-width:1014px}._a704{font-size:14px;margin:auto}._a7o5{font-size:15px;margin:auto}._a705{margin:0 auto;width:800px}._a706{float:left;margin-bottom:15px;position:relative;width:inherit;word-break:break-word;z-index:0}._a707{clear:both;color:#7f7f7f;margin-bottom:20px;margin-top:10px;text-align:center}._a708{position:relative;z-index:100}._a709{background:#fff;border-radius:8px;display:flex;flex-direction:row;padding:15px}._a70a{background:#fff;border-radius:3px;display:flex;flex-direction:row;padding-bottom:15px;padding-left:2px;padding-right:15px;padding-top:15px}._a70b{background:#fff;border-radius:3px;display:flex;flex-direction:row;padding-bottom:15px;padding-left:2px;padding-right:15px;padding-top:15px}._a70c{border-radius:50%;height:16px;padding:4px;width:16px}._a70d{display:flex;flex-direction:column;justify-content:center;margin-left:8px;width:100%}._a70e{color:#1d2129;font-weight:bold;line-height:18px;margin-bottom:3px}._a70f{color:#90949c;line-height:16px}._a70g{display:flex;justify-content:space-between;margin:0 auto;width:600px}._a70h{margin-top:4px}._a7cj{background:white;box-shadow:0 1px 7px #ccc;position:fixed;width:100%;z-index:99}._acpq{background:white;border-radius:8px;margin-top:15px;padding:10px}._acpr{font-weight:bold;margin-bottom:3px}._a7co{margin-left:16px}._a7cv{align-items:center;display:flex;justify-content:end}._a7cw{align-items:center;display:flex;margin-right:16px}._a7cx{border-radius:50%;margin-right:8px}._a7cy{font-size:15px;font-weight:600}._a7cz{margin-left:8px;margin-right:16px}._a7c-{color:#000;text-decoration:none}._a7c_{height:70px;width:100%}._5aj7{display:flex}._5aj7 ._4bl7{float:none}._5aj7 ._4bl9{flex:1 0 0px}._ikh ._4bl7{float:left;min-height:1px}._4bl7,._4bl9{word-wrap:break-word}._4bl9{overflow:hidden}._8tm{padding:0}._2phz{padding:4px}._2ph-{padding:8px}._2ph_{padding:12px}._2pi0{padding:16px}._2pi1{padding:20px}._40c7{padding:24px}._2o1j{padding:36px}._6buq{padding-bottom:0;padding-top:0}._2pi2{padding-bottom:4px;padding-top:4px}._2pi3{padding-bottom:8px;padding-top:8px}._2pi4{padding-bottom:12px;padding-top:12px}._2pi5{padding-bottom:16px;padding-top:16px}._2pi6{padding-bottom:20px;padding-top:20px}._2o1k{padding-bottom:24px;padding-top:24px}._2o1l{padding-bottom:36px;padding-top:36px}._6bua{padding-left:0;padding-right:0}._2pi7{padding-left:4px;padding-right:4px}._2pi8{padding-left:8px;padding-right:8px}._2pi9{padding-left:12px;padding-right:12px}._2pia{padding-left:16px;padding-right:16px}._2pib{padding-left:20px;padding-right:20px}._2o1m{padding-left:24px;padding-right:24px}._2o1n{padding-left:36px;padding-right:36px}._iky{padding-top:0}._2pic{padding-top:4px}._2pid{padding-top:8px}._2pie{padding-top:12px}._2pif{padding-top:16px}._2pig{padding-top:20px}._2owm{padding-top:24px}._div{padding-right:0}._2pih{padding-right:4px}._2pii{padding-right:8px}._2pij{padding-right:12px}._2pik{padding-right:16px}._2pil{padding-right:20px}._31wk{padding-right:24px}._2phb{padding-right:32px}._au-{padding-bottom:0}._2pim{padding-bottom:4px}._2pin{padding-bottom:8px}._2pio{padding-bottom:12px}._2pip{padding-bottom:16px}._2piq{padding-bottom:20px}._2o1p{padding-bottom:24px}._4gao{padding-bottom:32px}._1cvx{padding-left:0}._2pir{padding-left:4px}._2pis{padding-left:8px}._2pit{padding-left:12px}._2piu{padding-left:16px}._2piv{padding-left:20px}._2o1q{padding-left:24px}._2o1r{padding-left:36px}._a6-g{background:white;border-radius:8px}._a6-h{color:#1d2129;font-weight:bold;line-height:18px}._a6-i{border-bottom:1px solid #dadde1}._a6-o,._a6-o a{color:#8d949e;line-height:16px}._a72d{padding-bottom:12px;padding-left:12px;padding-right:12px}._a6-p{color:#1d2129;line-height:17px}._a6-q{color:gray}._a6_m{font-weight:bold}._a6_n{line-height:2;text-align:left}._a6_n tbody tr th{padding:5px 5px;text-align:left;vertical-align:top;width:150px}._a6_o{max-width:100%}._a6_p{font-weight:bold}._a6_q{color:#90949c;line-height:20px;min-width:50px}._acpx{color:#90949c}._acq1{line-height:20px;padding-bottom:8px}._a6_r{line-height:20px}._a6_s{word-break:break-all}._a7nf{display:flex;padding-left:5px;margin-bottom:5px}._a7ng{padding-right:5px}._a7nh{width:20%}._4jnw{margin:0}._3-8h{margin:4px}._3-8i{margin:8px}._3-8j{margin:12px}._3-8k{margin:16px}._3-8l{margin:20px}._2-5b{margin:24px}._1kbd{margin-bottom:0;margin-top:0}._3-8m{margin-bottom:4px;margin-top:4px}._3-8n{margin-bottom:8px;margin-top:8px}._3-8o{margin-bottom:12px;margin-top:12px}._3-8p{margin-bottom:16px;margin-top:16px}._3-8q{margin-bottom:20px;margin-top:20px}._2-ox{margin-bottom:24px;margin-top:24px}._1a4i{margin-left:0;margin-right:0}._3-8r{margin-left:4px;margin-right:4px}._3-8s{margin-left:8px;margin-right:8px}._3-8t{margin-left:12px;margin-right:12px}._3-8u{margin-left:16px;margin-right:16px}._3-8v{margin-left:20px;margin-right:20px}._6bu9{margin-left:24px;margin-right:24px}._5soe{margin-top:0}._3-8w{margin-top:4px}._3-8x{margin-top:8px}._3-8y{margin-top:12px}._3-8z{margin-top:16px}._3-8-{margin-top:20px}._4aws{margin-top:24px}._2-jz{margin-right:0}._3-8_{margin-right:4px}._3-90{margin-right:8px}._3-91{margin-right:12px}._3-92{margin-right:16px}._3-93{margin-right:20px}._y8t{margin-right:24px}._5emk{margin-bottom:0}._3-94{margin-bottom:4px}._3-95{margin-bottom:8px}._3-96{margin-bottom:12px}._3-97{margin-bottom:16px}._3-98{margin-bottom:20px}._20nr{margin-bottom:24px}._av_{margin-left:0}._3-99{margin-left:4px}._3-9a{margin-left:8px}._3-9b{margin-left:12px}._3-9c{margin-left:16px}._3-9d{margin-left:20px}._4m0t{margin-left:24px}._a82f{margin-left:28px}._a6_t{display:flex;flex-direction:row;margin-bottom:12px;padding-left:24px}._a6_u{color:#90949c}._a76v{margin-top:16px}._a76v:first-child{margin-top:0}._a6_v{display:flex;flex-direction:row;margin-bottom:12px}._a6_w{display:flex;flex-direction:column;margin-left:8px}._a6_x{color:#1d2129;font-weight:bold;line-height:18px;margin-bottom:3px}._a6_y{color:#1d2129;line-height:16px}._a6_z{border-radius:50%;height:16px;padding:4px;width:16px}._a6_-{padding-left:32px}._a6__{color:#385898;line-height:20px}._6lv0{width:auto}._6sa9{width:fit-content}._6saa{width:max-content}._6sab{width:min-content}._8a4a{width:5%}._7qew{width:10%}._8g0d{width:15%}._6saj{width:20%}._75u3{width:25%}._6sak{width:40%}._9adl{width:45%}._653c{width:50%}._1aa4{width:60%}._6qk8{width:80%}._91p-{width:95%}._21op{width:100%}._91h1{max-width:30%}._91h3{max-width:30%}._91hn{max-width:50%}._4x_f{max-width:80%}._6y_w{max-width:100%}._84dk{min-width:0}Your information ﴿ أسرار و حقائق ألأرض المسطحه ﴾Home This profile's activity across FacebookSaved items and collectionsPosts, photos and videos this profile has savedYou have no data in this sectionPostsPosts this profile shared on Facebook, posts that are hidden from the profile timeline and polls it createdPhotosProfile PostsUncategorized photosPollsPolls this profile has created and participated inYou have no data in this sectionEventsResponses to events and a list of the events this profile createdYou have no data in this sectionFacebook GamingThis profile's profile for Facebook GamingYou have no data in this sectionPlacesA list of places this profile has createdYou have no data in this sectionComments and reactionsPosts, comments, Pages and profiles this profile has liked or reacted toCommentsStoriesPhotos and videos this profile shared to its storyYou have no data in this sectionShort VideosThis profile's activity with short videos on FacebookYou have no data in this sectionPages and profilesYour Pages and profiles, Pages and profiles you've liked or recommended, followed or unfollowedYou have no data in this sectionFundraisersFundraisers you've created, joined or donated toYou have no data in this sectionGroupsGroups this profile belongs to, groups managed by this profile and posts and comments within the groups it belongs toPosts in GroupsYour group member profilesYour pending posts in groupsMessagesMessages you've exchanged with other people on MessengerYou have no data in this sectionLive Audio RoomsA list of your activity as a host, speaker or listener for live audio room broadcastsYou have no data in this sectionCollaborationsYour collaborative post activities like actions you’ve taken and who you’ve collaborated withYou have no data in this sectionNavigation barA menu that includes shortcuts to things like notifications or GroupsYou have no data in this sectionOther activityOther information and activity from different areas of FacebookYou have no data in this sectionProfile informationProfile informationContact information for this profile, information in this profile's About section, life events, hobbies and musicYou have no data in this sectionOther information provided about this profileOther information you’ve providedAvatarsConnectionsFriends and followersPeople, organizations or business this profile chooses to see content from, and people who follow this profilePeople who follow youLogged informationActivity messagesA history of this profile's interactions messages on FacebookYou have no data in this sectionBonusesInformation about bonus opportunities you've participated inYou have no data in this sectionAffiliateInformation about the affiliate program you've participated in including your creator onboarding status and the program's start dateYou have no data in this sectionProfessional dashboardInformation about your activity on professional dashboardYou have no data in this sectionGenerated by Ahmed Ali on Wednesday, January 11, 2023 at 8:53 AM UTC+02:00

**Comment by Dyaaokor** [comment]
do not write the topic. I can prove it with pictures and complete files. Ask for help. Can I find it or not? 


These are some of the accounts they used to hack my page with a file for the page that I downloaded more than a year ago and I have files for all the followers and comments. My page had 170,000 followers. It was stolen from me about a month ago. The followers’ finger had 130,000. Do you notice the difference? He posts pictures similar to the content of the page. But it displays sexual images in the story of the page, and I am the one who designed, created and produced the video clip since the time the page was created, and no one has published it except me. Everything on it is me who designed and published it, and I put the title of the page in red in the videos and even the articles. I am the one who wrote it, so please do not say that I am familiar with the topic.
