### ISSUE TITLE
html.elements.link.rel.preload - safari compatibility

### ISSUE THREAD

**Issue by fraserdale** [mdn/browser-compat-data#20700]
### What type of issue is this?

Incorrect support data (example: Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Incorrect support data, safari is marked as "Compatibility unknown" but Release 178 will support 

https://github.com/WebKit/WebKit/commit/a32d1a3606d75229c4f5c2e5f38d244f545d4607

https://developer.apple.com/documentation/safari-technology-preview-release-notes/stp-release-178

https://www.mactrast.com/2023/09/apple-releases-safari-technology-preview-178-brings-bug-fixes-and-performance-improvements/#:~:text=Enabled%20responsive%20images%20in%C2%A0%3Clink%20rel%3Dpreload%3E%C2%A0(266787%40main)

### What browsers does this problem apply to, if applicable?

Safari

### What did you expect to see?

Safari Technology Preview‌ 178 as "Partial support"

### Did you test this? If so, how?

no

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://github.com/WebKit/WebKit/commit/a32d1a3606d75229c4f5c2e5f38d244f545d4607

https://developer.apple.com/documentation/safari-technology-preview-release-notes/stp-release-178

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel/preload

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `html.elements.link.rel.preload`
* Report started: 2023-09-13T18:36:11.700Z

</details>

**Comment by VojtaStanek** [comment]
Caniuse has data on this feature: https://caniuse.com/link-rel-preload

**Comment by queengooborg** [comment]
This was fixed in #22658!
