### ISSUE TITLE
css.selectors.user-valid/css.selectors.user-invalid - Support has been added with Chrome 119

### ISSUE THREAD

**Issue by tomasko126** [mdn/browser-compat-data#20720]
### What type of issue is this?

Incorrect support data (example: Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Support for Chrome has been added with Chrome 119 per the linked Chromium ticket: https://bugs.chromium.org/p/chromium/issues/detail?id=1156069

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

N/A

### Did you test this? If so, how?

Opened https://developer.mozilla.org/en-US/docs/Web/CSS/:user-valid#setting_a_color_and_symbol_on_user-valid / https://developer.mozilla.org/en-US/docs/Web/CSS/:user-invalid#setting_a_color_and_symbol_on_user-invalid on Chrome Canary 119.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://developer.mozilla.org/en-US/docs/Web/CSS/:user-valid
https://developer.mozilla.org/en-US/docs/Web/CSS/:user-invalid

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/:user-valid

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.selectors.user-valid`
* Report started: 2023-09-15T20:41:00.113Z

</details>

**Comment by Elchi3** [comment]
Fixed in https://github.com/mdn/browser-compat-data/pull/20728
