### ISSUE TITLE
api.Notification.requestPermission_static - Not working on iPhone

### ISSUE THREAD

**Issue by Maninder-cell** [mdn/browser-compat-data#20741]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

Notification is undefined.

```
const permissionResult = Notification.requestPermission(function (result) {
      resolve(result);
});
```

Notification.requestPermission never runs cause Notification is undefined on safari in iphone.

### What browsers does this problem apply to, if applicable?

Safari

### What did you expect to see?

Notification should return notification object.

### Did you test this? If so, how?

I tested it on different iPhones but not woking on any one of them. 

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Notification/requestPermission_static

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.Notification.requestPermission_static`
* Report started: 2023-09-18T09:34:58.778Z

</details>

**Comment by queengooborg** [comment]
What iOS version and browser are you using?

**Comment by queengooborg** [comment]
Closing because there has been no further response and no action can be taken without additional information.
