### ISSUE TITLE
html.global_attributes.popover - Supported in Safari 17

### ISSUE THREAD

**Issue by chengd42** [mdn/browser-compat-data#20750]
### What type of issue is this?

Incorrect support data (example: Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Popover has been supported by Safari 17.

### What did you expect to see?

Supported by safari 17

### Did you test this? If so, how?

Yes. 

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://webkit.org/blog/14445/webkit-features-in-safari-17-0/

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/popover

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `html.global_attributes.popover`
* Report started: 2023-09-19T12:28:16.130Z

</details>

**Comment by ramiy** [comment]
Fixed in #20789
