### ISSUE TITLE
Tweak linter message that disallows "individual version of Node.js" 

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#20760]
### What type of issue is this?

Infrastructure issue

### What is the issue?

Currently, the linter says:

> BCD does not record every individual version of Node.js, only the releases that update V8 engine versions or add a new feature. You may need to add the release to browsers/nodejs.json.

However, given BCD does not only record ECMAScript features for Node.js but also Web API features that do ship outside of V8 engine bumps, I wonder if we should be allowing more versions in our Node.js compat data.

There are several issues filed that complain about this:

- https://github.com/mdn/browser-compat-data/issues/20752
- https://github.com/mdn/browser-compat-data/issues/20414
- https://github.com/mdn/browser-compat-data/issues/20411

Recently, I also accepted a PR that added a new Nodejs version:
- https://github.com/mdn/browser-compat-data/pull/20726

(and I'm sure others might have done so before, too)

### What behavior were you expecting?

Update to our docs and to the linter message to allow minor Nodejs versions when there are features to record in that minor Nodejs version.

Actually, our docs seem fine: https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/browsers.md#nodejs

### What version(s) of BCD is the issue present in?

- [ ] The current BCD release
- [ ] The current version of the `main` branch

**Comment by queengooborg** [comment]
In that error message, we do also say "or add a new feature", which opens up the opportunity for additional Node.js versions to be added as needed?

**Comment by Elchi3** [comment]
Right, well... I guess I was surprised by the message and thought it would not be okay to add more node.js versions.... If that's just me then let's close this, though. Maybe I read to much into it.
