### ISSUE TITLE
html.global_attributes.popover, html.global_attributes.popovertarget and html.global_attributes.popovertargetaction - Support has been added with Opera 100

### ISSUE THREAD

**Issue by mfranzke** [mdn/browser-compat-data#20764]
### What type of issue is this?

Incorrect support data (example: Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Chromium support for this feature has been added with 114 as mentioned within the same dataset, so it's supported with the related Opera version 100 (see e.g. https://blogs.opera.com/desktop/2023/06/opera-100-0-4815-30-stable-update/).

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

Opera 100 already set to supporting.

### Did you test this? If so, how?

Opening https://mdn.github.io/dom-examples/popover-api/ and checking the example in Opera 100.

**Comment by dyaael** [comment]
Could you help me. I will do this job and thank you


في خميس، 21 سبتمبر، 2023 في 9:53 م، كتب Maximilian Franzke <
***@***.***>:
