### ISSUE TITLE
api.HTMLMediaElement.preservesPitch - Firefox information not clear

### ISSUE THREAD

**Issue by harrisi** [mdn/browser-compat-data#20766]
### What type of issue is this?

Other

### What information was incorrect, unhelpful, or incomplete?

Information for Firefox is difficult to parse. 

### What browsers does this problem apply to, if applicable?

Firefox

### What did you expect to see?

An easier to understand timeline for Firefox's support.

### Did you test this? If so, how?

Yes, in Firefox 117.0.1, `HTMLMediaElement.preservesPitch` seems to work.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/preservesPitch

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.HTMLMediaElement.preservesPitch`
* Report started: 2023-09-22T03:38:12.984Z

</details>

**Comment by dyaael** [comment]
Want to know what non-FX errors I found. a witness. It works on the
contrary in white, high-definition Java, in different and varied places of
writing, and also this idiot puts a story in the image of the page image
when you click on it for virus applications.




في جمعة، 22 سبتمبر، 2023 في 6:51 ص، كتب Ian Harris ***@***.***
