### ISSUE TITLE
api.InputDeviceInfo - Not supported on Firefox

### ISSUE THREAD

**Issue by saschanaz** [mdn/browser-compat-data#20786]
### What type of issue is this?

Incorrect support data (example: Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

It says it's supported but it's not

### What did you expect to see?

No supported version

### Did you test this? If so, how?

From the console, InputDeviceInfo doesn't exist

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://bugzilla.mozilla.org/show_bug.cgi?id=1213422

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/InputDeviceInfo

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.InputDeviceInfo`
* Report started: 2023-09-22T13:41:50.090Z

</details>

**Comment by queengooborg** [comment]
This interface is not directly exposed; they are available through `MediaDevices.enumerateDevices()` (see https://developer.mozilla.org/en-US/docs/Web/API/InputDeviceInfo#examples).

**Comment by saschanaz** [comment]
>This interface is not directly exposed;

This is not (and should not) the case anymore except for WebGL. See: https://w3c.github.io/mediacapture-main/#dom-inputdeviceinfo

```webidl
[[Exposed](https://webidl.spec.whatwg.org/#Exposed)=Window, [SecureContext](https://webidl.spec.whatwg.org/#SecureContext)]
interface [InputDeviceInfo](https://w3c.github.io/mediacapture-main/#dom-inputdeviceinfo) : [MediaDeviceInfo](https://w3c.github.io/mediacapture-main/#dom-mediadeviceinfo) {
  [MediaTrackCapabilities](https://w3c.github.io/mediacapture-main/#dom-mediatrackcapabilities) [getCapabilities](https://w3c.github.io/mediacapture-main/#dom-inputdeviceinfo-getcapabilities)();
};
```

And Firefox doesn't support it per the bug above.
