### ISSUE TITLE
css.selectors.nth-last-child - of <selector> appears to work in Chromium

### ISSUE THREAD

**Issue by geecko86** [mdn/browser-compat-data#20797]
### What type of issue is this?

Incorrect support data (example: Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

`of <selector>` syntax is marked as unsupported on chromium-based browsers. It does in fact seem to work.

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

"Fully supported" checkmark since Chrome/Edge 111.

Source: https://developer.chrome.com/articles/css-nth-child-of-s/

### Did you test this? If so, how?

Wrote this bit of css and it was not rejected, worked as intended.

![image](https://github.com/mdn/browser-compat-data/assets/825187/70bb8b39-15e3-4e41-ae04-72050b4415dd)

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://developer.chrome.com/articles/css-nth-child-of-s/

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-last-child

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.selectors.nth-last-child`
* Report started: 2023-09-23T16:12:04.671Z

</details>

**Comment by queengooborg** [comment]
Fixed in #21244!
