### ISSUE TITLE
`notes` to `impl_url` property migration leftovers

### ISSUE THREAD

**Issue by mfranzke** [mdn/browser-compat-data#20795]
> This was actually already handled in #20608!

There are some leftovers existing in the codebase.

_Originally posted by @mfranzke in https://github.com/mdn/browser-compat-data/issues/20794#issuecomment-1732329990_
            
This PR converts various implementation notes into `impl_url` keys instead, which would allow for better machine readability if needed ("See bug XXXXX" have been migrated with https://github.com/mdn/browser-compat-data/pull/20608 already).

This change was primarily performed by the following Visual Studio Code search regex and manually going through the results afterwards and analyzing for phrases that haven't been catched with the changes out of https://github.com/mdn/browser-compat-data/pull/20608): `"notes":\s*"(\S|\s)+(https:\/\/(crbug\.com(\/[^\/]+)?|bugzil\.la|webkit\.org\/b))`

**Comment by foolip** [comment]
@mfranzke how can we find the remaining cases? The regexp you posted doesn't work with `git grep -E`.

**Comment by mfranzke** [comment]
> @mfranzke how can we find the remaining cases? The regexp you posted doesn't work with `git grep -E`.

sorry, I should have mentioned this (and just adapted it to this issues description): It's a regex that works in VS Code search.

**Comment by mfranzke** [comment]
I've only found one remaining occurance: https://github.com/mdn/browser-compat-data/pull/22287
