### ISSUE TITLE
Migrate from `notes` to `impl_url` property for bug URLs

### ISSUE THREAD

**Issue by mfranzke** [mdn/browser-compat-data#20794]
We prefer to use the `impl_url` property for bug URLs, so let's use that:

_Originally posted by @queengooborg in https://github.com/mdn/browser-compat-data/pull/20787#pullrequestreview-1640800235_

**Comment by queengooborg** [comment]
This was actually already handled in https://github.com/mdn/browser-compat-data/pull/20608!

**Comment by mfranzke** [comment]
> This was actually already handled in #20608!

There are some leftovers existing in the codebase.
