### ISSUE TITLE
html.global_attributes.popover - Opera supports popover.

### ISSUE THREAD

**Issue by johann1301s** [mdn/browser-compat-data#20799]
### What type of issue is this?

Incorrect support data (example: Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Opera One(versjon: 100.0.4815.21) (arm64) supports popover.

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

Expected it to say latest version of opera that supports popover.

### Did you test this? If so, how?

<img width="1840" alt="Skjermbilde 2023-09-24 kl  14 13 11" src="https://github.com/mdn/browser-compat-data/assets/25029220/e1d4781d-8b57-411d-87cc-51abc029bba5">

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

no.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/popover

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `html.global_attributes.popover`
* Report started: 2023-09-24T11:29:07.026Z

</details>

**Comment by mfranzke** [comment]
I would expect this to be correct after the changes out of my PR https://github.com/mdn/browser-compat-data/pull/20765 have been deployed.

**Comment by mfranzke** [comment]
Indeed, the new data has been deployed an now Opera 100 even also shows up as supported.
