### ISSUE TITLE
svg.attributes.presentation.text-anchor - No browser compatibility data available

### ISSUE THREAD

**Issue by maritaria** [mdn/browser-compat-data#20809]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

The entire compatibility table for `text-anchor` is absent. All browsers are marked with "?".

### What did you expect to see?

The actual compatibility table, reporting at the least:

1. The first version from which the feature is supported.
2. If not, the absense of support for the feature.

### Did you test this? If so, how?

Looked at it, not there.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

MDN page: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/text-anchor

### Do you have anything more you want to share?

Very likely this is the same for many of the SVG attributes and elements.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/text-anchor

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `svg.attributes.presentation.text-anchor`
* Report started: 2023-09-25T12:32:11.979Z

</details>

**Comment by queengooborg** [comment]
We have a project to remove all null values and other uncertainties from BCD, however it has been on the backburner since we have other priorities.  Since this folds into one of our main projects, I'm going to close this issue.
