### ISSUE TITLE
http.headers.Authorization - Supported RFC-7616 (Chrome, Edge)

### ISSUE THREAD

**Issue by lubereH** [mdn/browser-compat-data#20812]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Browser compatibility is incorrected casuse update.
Digest SHA-256 : Chrome version 117 supported
Digest SHA-256 : Edge (I don't known version)

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

Chrome is supported RFC-7616 (SHA-256). Supported chrome's version is 117+(Maybe). I'm confirm that is not supported 116 version.
And Edge is supported RFC-7616(SHA-256). But I don't know supprted version.

### Did you test this? If so, how?

My server is working (Digest RFC-7616 and SHA-256).
I'm working firefox recently version.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

Chrome : https://bugs.chromium.org/p/chromium/issues/detail?id=1160478

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `http.headers.Authorization`
* Report started: 2023-09-26T01:46:30.388Z

</details>

**Comment by chocolatkey** [comment]
It's confirmed on this page that it's 117+ https://chromestatus.com/feature/5139896267702272
