### ISSUE TITLE
api.MouseEvent.offsetX - Padding edge?

### ISSUE THREAD

**Issue by steelow** [mdn/browser-compat-data#20828]
### What type of issue is this?

Other

### What information was incorrect, unhelpful, or incomplete?

The documents says: "Padding edge of target". Not sure what this means - utterly confusing. What is the meaning of "padding edge of target". Could you guys add some box coordinate diagram to better depict the meaning.

Thanks

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

More specific descriptive language

### Did you test this? If so, how?

No need for a functionality test. It is just a text content issue.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

N/A

### Do you have anything more you want to share?

No

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/offsetX

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.MouseEvent.offsetX`
* Report started: 2023-09-27T17:10:17.834Z

</details>

**Comment by queengooborg** [comment]
Please report the issue to https://github.com/mdn/content by using the "Report the content issue" link at the bottom of the page.  This repository is specifically for the browser compatibility tables, not for page content.
