### ISSUE TITLE
Update documentation for how to use the new update script

### ISSUE THREAD

**Issue by foolip** [mdn/browser-compat-data#20820]
### What would you like to see added to BCD?

https://github.com/mdn/browser-compat-data/pull/19971 moved the `update-bcd` script from mdn-bcd-collector into BCD, but we have not updated documentation for how to use this new script. https://github.com/mdn/browser-compat-data/blob/main/docs/contributing.md#optional-generating-data-using-the-mdn-bcd-collector-project links to https://mdn-bcd-collector.gooborg.com/docs/update-bcd.md.

### How impactful do you think this enhancement will be?

The main thing is that we should avoid any divergence between the original `update-bcd` and the one that was moved into BCD. Although a bit painful at first, I think we should do this by ensuring that the script in BCD itself is fully up to the task, and refer to it in docs.

### Do you have anything more you want to share?

cc @Elchi3 @queengooborg

**Comment by Elchi3** [comment]
Closing this as we want to keep the update scripts with the collector. I will take a look at the docs if they are good.
