### ISSUE TITLE
css.types.length - Support for new root length units and `cap` in Chromium and Safari

### ISSUE THREAD

**Issue by nilaallj** [mdn/browser-compat-data#20832]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

- `rcap`, `rch`, `rex` and `ric` not shown in support data table.
- No support data for Chromium and Safari regarding `cap`, `rcap`, `rch`, `rex` and `ric` units.
- No support data for Chromium regarding the `rlh` unit.

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet), Safari

### What did you expect to see?

- Chromium support for `rch`, `rex`, `ric` and `rlh` since version 111.
- Chromium support for `cap` and `rcap` since version 117.
- Safari TP support for `cap`, `rcap`, `rch`, `rex` and `ric`.

### Did you test this? If so, how?

Tested in stable Chrome (117) and Safari TP 179.
Used the script on the `<length>` MDN page: https://developer.mozilla.org/en-US/docs/Web/CSS/length#result

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

- MDN page: https://developer.mozilla.org/en-US/docs/Web/CSS/length
- Chrome Platform Status on `cap` and `rcap`: https://chromestatus.com/feature/5137204166262784
- Chrome Platform Status on `rch`, `rex`, `ric` and `rlh`: https://chromestatus.com/feature/5073969265246208
- Safari TP 179 release notes: https://webkit.org/blog/14532/release-notes-for-safari-technology-preview-179/

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/length

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.types.length`
* Report started: 2023-09-28T00:25:56.015Z

</details>

**Comment by nilaallj** [comment]
**Update:** Support for `cap`, `rcap`, `rch`, `rex` and `ric` included in Safari 17.2. See [release notes](https://developer.apple.com/documentation/safari-release-notes/safari-17_2-release-notes#New-Features)

**Comment by queengooborg** [comment]
Fixed in #21171!
