### ISSUE TITLE
Update disablePictureInPicture attribute compatibility for Firefox  116

### ISSUE THREAD

**Issue by meaou** [mdn/browser-compat-data#20837]
### Proposal

Hi, 
In Firefox 116, we [introduce the support](https://bugzilla.mozilla.org/show_bug.cgi?id=1811321) for the disablePictureInPicture attribute in Firefox.

Would it please be possible to update the Firefox compatibility from 116 in [this article](https://developer.mozilla.org/en-US/docs/Web/API/HTMLVideoElement/disablePictureInPicture#browser_compatibility)?

### Task list

- [ ] 

### Additional information

Please see the full description of the user experience in Firefox once the attribute support is live in release [here](https://docs.google.com/document/d/1Pd9L-6Bh5YNwnacPHIU5UVP3iv15Gui4fY4n_bQfflQ/edit). 

### Depends on

No

**Comment by hamishwillee** [comment]
We'd have added this automatically for you if you'd added the keyword `dev-doc-needed` to the bugzilla report :-).
FWIW does not appear to past the wpt live test https://wpt.live/picture-in-picture/disable-picture-in-picture.html
