### ISSUE TITLE
api.MediaStream.addTrack - Supported by Firefox Android?

### ISSUE THREAD

**Issue by saschanaz** [mdn/browser-compat-data#20835]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

addTrack exists on Android and there's no condition to not expose it in the IDL side: https://searchfox.org/mozilla-central/rev/6b91b922725838e2732aeb478b13e5b33e33ce1b/dom/webidl/MediaStream.webidl#45

### What browsers does this problem apply to, if applicable?

Firefox

### What did you expect to see?

An added_version?

### Did you test this? If so, how?

https://mdn-bcd-collector.gooborg.com/tests/api/MediaStream?exposure=Window on Android device

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/MediaStream/addTrack

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.MediaStream.addTrack`
* Report started: 2023-09-28T12:31:07.505Z

</details>

**Comment by queengooborg** [comment]
This was fixed in #22055!
