### ISSUE TITLE
Clarify "Only supports explicit" for cookies.sameSiteStatus for Safari

### ISSUE THREAD

**Issue by rebloor** [mdn/browser-compat-data#20853]
### What type of issue is this?

Other

### What information was incorrect, unhelpful, or incomplete?

cookies.sameSiteStatus for Safari includes the note "Only supports explicit". However. neither MDN nor Chrome document an `explicit` value for this type.

### What browsers does this problem apply to, if applicable?

Safari

### What did you expect to see?

n/a

### Did you test this? If so, how?

n/a

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/cookies/SameSiteStatus

**Comment by rebloor** [comment]
@jdatapple Would you be able to clarify this one?

**Comment by rebloor** [comment]
@jdatapple Would you be able to clarify this one?

**Comment by xeenon** [comment]
@rebloor  I don't know what this note originally meant. We can remove it.

**Comment by rebloor** [comment]
Thanks @xeenon - will do
