### ISSUE TITLE
api.Window.requestIdleCallback - <SUMMARIZE THE PROBLEM>

### ISSUE THREAD

**Issue by MerwillAguilera** [mdn/browser-compat-data#20854]
### What type of issue is this?

Browser bug (a bug with a feature that may impact site compatibility)

### What information was incorrect, unhelpful, or incomplete?

I cant see videos

### What browsers does this problem apply to, if applicable?

Safari

### What did you expect to see?

Video mega

### Did you test this? If so, how?

Yes

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Window/requestIdleCallback

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.Window.requestIdleCallback`
* Report started: 2023-10-02T00:03:52.959Z

</details>

**Comment by hamishwillee** [comment]
@MerwillAguilera There is nothing actionable here - the page has no videos. I presume this is spam. If you do have an actual problem, feel free to create a new post with screenshots showing the problem, and information about what browser you are using.
