### ISSUE TITLE
Removing Servo for now?

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#209]
Servo refers to https://servo.org/ which is, unlike everything else, a browser engine and not a browser. It is sponsored by Mozilla and runs on desktop systems and on Android.

I'm thinking about a few reasons why Servo isn't a good fit for this data at the moment.

- Servo has no releases yet, so we can just add "yes" or "no" and no versions.
- Servo is being integrated into Firefox and doesn't seem to be distributed (widely) as standalone software for now.
- We also don't collect compat data for Gecko or for any other engine.
- We have no process to maintain Servo's compat data, as there is no signal to us when something was implemented in Servo (no ddns like for Firefox).
- For MDN, it is unclear to me what additional value a reader (web developer) would get from seeing whether or not something is implemented in Servo.

Any other thoughts on this?

**Comment by stephaniehobson** [comment]
👍

**Comment by Elchi3** [comment]
We decided in the 4th weekly Browser Compat Data meeting today that we will remove Servo for now. As we are still in an alpha phase we are not going to worry about schema version bumping although this is in theory a breaking change. The KumaScript {{compat}} macro can handle data without servo.
