### ISSUE TITLE
Request/Response - missing detailed compatibility info for Node 18

### ISSUE THREAD

**Issue by iainmerrick** [mdn/browser-compat-data#20900]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

Node 18.0.0 is listed as compatible for both `Request` and `Response`, but compatibility for all the individual properties is unknown.

It looks like these are generally supported (e.g. `Request.url`), although it's not clear from the Node docs whether some of the newer properties might have missing or partial support.

### What browsers does this problem apply to, if applicable?

Node.js

### What did you expect to see?

Node compatibility information for each property of both `Request` and `Response`.

### Did you test this? If so, how?

I'm looking at the main online MDN docs: https://developer.mozilla.org/en-US/docs/Web/API/Request

I haven't yet written a Node test script to check compatibility.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

Node 18.0.0 release notes: https://nodejs.org/en/blog/release/v18.0.0

**Comment by queengooborg** [comment]
`null` values like these are something we're working to remove from all of BCD and replace with accurate compatibility info.  I'm going to close this issue because it folds into our primary goal.
