### ISSUE TITLE
api.Window - Conflict data of removed api

### ISSUE THREAD

**Issue by skyclouds2001** [mdn/browser-compat-data#20952]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

![image](https://github.com/mdn/browser-compat-data/assets/95597335/730e9ca6-934d-4385-b6aa-3bd7ba245d6b)

See the data suggests it supported version from 12 to 18, the below description suggest it was removed since 79

This also existed in many other api data

> And it seems that this bug only existed in Edge

### What did you expect to see?

fix to the correct data

### Did you test this? If so, how?

no

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Window

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.Window`
* Report started: 2023-10-12T13:10:37.780Z

</details>

**Comment by queengooborg** [comment]
This is an accurate description and rendering, because support was present in Edge between versions 12 and 18.  The next release after 18, which is 79, then removed support, making 18 the last Edge version to support the feature.
