### ISSUE TITLE
-webkit-line-clamp - Safari 16 rendering bug when container has block elements

### ISSUE THREAD

**Issue by Yimiprod** [mdn/browser-compat-data#20950]
### What type of issue is this?

Browser bug (a bug with a feature that may impact site compatibility)

### What information was incorrect, unhelpful, or incomplete?

On Safari 16, there's a rendering bug with `-webkit-line-clamp` when there's block elements in a `-webkit-box`.
This make each block text being clamped but not all the containing box.

<img width="378" alt="image" src="https://github.com/mdn/browser-compat-data/assets/2227867/d019f65c-6771-491c-ae72-c1771d4a64f1">

### What browsers does this problem apply to, if applicable?

Safari

### What did you expect to see?

<img width="381" alt="image" src="https://github.com/mdn/browser-compat-data/assets/2227867/9f32ff29-c8b9-4e29-80b4-54af834ffdc3">

### Did you test this? If so, how?

Reproduction environment bug, press the `toggle clamp` button to visualize the bug:
https://codepen.io/Yimiprod/full/GRPeewz

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-line-clamp

**Comment by queengooborg** [comment]
Looks like this has been fixed in as late as Safari 17.1!

**Comment by charrondev** [comment]
This still seems to be buggy as of Safari 17.3.1

JSFiddle here https://jsfiddle.net/315w826d/1/
