### ISSUE TITLE
webextensions.api.proxy.settings - Missing other browser data

### ISSUE THREAD

**Issue by erosman** [mdn/browser-compat-data#20979]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Missing other browser data

### What did you expect to see?

Other browser data added

> [!Note]
> Please note that while the API is supported by other browsers, there are differences in their details & implementation.

MDN:
- [proxy](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/proxy)
- [proxy.settings](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/proxy/settings)

Other:
- [chrome.proxy.settings](https://developer.chrome.com/docs/extensions/reference/proxy/#property-settings)
- [Supported APIs for Microsoft Edge extensions](https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/api-support)

### Did you test this? If so, how?

I use `chrome.proxy.settings.set()` in addons that I develop.

Also: [Examples](https://developer.chrome.com/docs/extensions/reference/proxy/#examples)

```js
chrome.proxy.settings.set(
  {value: config, scope: 'regular'},
  function() {}
);
```

### Note
API is not supported in Firefox on Android yet.
[Support proxy.settings API on Android](https://bugzilla.mozilla.org/show_bug.cgi?id=1725981)

### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/proxy/settings

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `webextensions.api.proxy.settings`
* Report started: 2023-10-17T14:52:56.596Z

</details>

**Comment by rebloor** [comment]
@erosman this is problematic. My understanding is that this was done deliberately to avoid the potential confusion on the part of a Firefox extension developer migrating their extension to Chrome thinking that the APIs would be essentially the same. We unfortunately don't have a mechanism for indicating that these are browser-specific APIs. Any thoughts @rpl or @Rob--W ?

**Comment by Rob--W** [comment]
Let's add a note to the BCD that emphasizes that Chrome/Edge/Opera has a different implementation under the same name.

And also a NOTE in mdn/content, with a link to Chrome's docs.

**Comment by erosman** [comment]
@Rob--W While a bit off-topic, Chrome implementation does have some good merits, especially in handling of "singleProxy".
I have brought up the issue before. It would be worthwhile to consider.
I can expand further, if needed.

See also: [Bug 1804693: Setting single proxy for all fails](https://bugzilla.mozilla.org/show_bug.cgi?id=1804693)

**Comment by erosman** [comment]
I made the following table which might be useful.

### proxy.settings API Comparison

<table>
  <thead>
    <th>Chrome</th>
    <th>Firefox</th>
  </thead>
  <tbody>
    <tr>
      <th>ProxyRules</th>
      <td></td>
    </tr>
    <tr>
      <td>singleProxy</td>
      <td>httpProxyAll</td>
    </tr>
    <tr>
      <td>proxyForHttp</td>
      <td>http</td>
    </tr>
    <tr>
      <td>proxyForHttps</td>
      <td>ssl</td>
    </tr>
    <tr>
      <td>proxyForFtp</td>
      <td>ftp</td>
    </tr>
    <tr>
      <td>fallbackProxy</td>
      <td></td>
    </tr>
    <tr>
      <td>bypassList</td>
      <td>passthrough</td>
    </tr>
    <tr>
      <th>PacScript</th>
      <td></td>
    </tr>
    <tr>
      <td>url</td>
      <td>autoConfigUrl</td>
    </tr>
    <tr>
      <td>data</td>
      <td>autoConfigUrl</td>
    </tr>
    <tr>
      <td colspan="3"></td>
    </tr>
    <tr>
      <td></td>
      <td>autoLogin</td>
    </tr>
    <tr>
      <td></td>
      <td>socks</td>
    </tr>
    <tr>
      <td></td>
      <td>socksVersion</td>
    </tr>
    <tr>
      <td></td>
      <td>proxyDNS</td>
    </tr>
  </tbody>
</table>

**Comment by rebloor** [comment]
Fix completed by changes in [Superseded by changes in Add missing __compat+mdn_url to top-level extension namespaces
#22338](https://github.com/mdn/browser-compat-data/pull/22338)

**Comment by abirhasan132** [comment]
66100af9bb891df5f5cc4e12b6c66f77184e1cc1
