### ISSUE TITLE
We should avoid giant JSON files

### ISSUE THREAD

**Issue by JeremiePat** [mdn/browser-compat-data#21]
It's very tempting to have large JSON files as it make things easier to request (do one XHR request and you get all the data you need).

However, on a maintenance stand point I think it will make things easier if we have one file per feature set (JavaScript promise is an excellent example of that). Git usually behave better on smaller files (especially if we want to change large chunk of data) and it will make pull request review way easier.

That said I understand the need for larger JSON files for XHR. What I suggest here is to add a simple node script that will build the aggregated JSON files automatically (and a pre-commit hook to have it done automatically for committers). This is pretty trivial and can help us ease the maintenance of our data in the long term.

**Comment by wbamberg** [comment]
Yes, we've talked about this and agreed that a build step seems like the best way to make things easier for contributors without making them harder for the macros.

As you say, actually building the things seems trivial. I'm more worried about where the build code is hosted and how we secure it. Even just where we are now, we're automatically building (parts of) hundreds of MDN pages from content that lives outside developer.mozilla.org. To the extent that we can trust access to this repo, that's OK, but are we further extending our trust by having a build step?

**Comment by JeremiePat** [comment]
My opinion here is that the build mechanism should be part of that repo as it will makes things easier to maintain in the short term. If we agree on #22, I would suggest the following organization:

Folder structure:
```
.src
.tools
.tools/hooks
.tools/scripts
data
```

`.src` will contain all the JSON files with our data that needs to be maintained

`data` will contain the built (aggregated, minified) JSON files ready to be used

`.tools/scripts` will contain all the necessary script (Node.js scripts) to make the build, run tests, etc.

`.tools/hooks` will contain git hooks necessary to enhance testing and build to make sure the whole data set remain coherent (at that point, as we are using Travis to automate testing, it is not a hard requirement, just some nice helpers).

On top of that, we can use NPM script to run everything is needed (at minimum I suggest `npm test` and `npm run build`)

Such organization will make things easier if it appears that maintaining the tool chain and the data in the same repo is not sustainable (but I doubt so at that stage)

**Comment by Elchi3** [comment]
WebExtension JSON files were the only ones with this problem. I'm calling this fixed.
