### ISSUE TITLE
css.types.color.system-color - Chrome doesn't support AccentColor anymore

### ISSUE THREAD

**Issue by xaddict** [mdn/browser-compat-data#21006]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Chrome doesn't support AccentColor as a color value anymore, at least in Chrome 118 and Chrome Canary 120

### What did you expect to see?

When I set an element to use `background-color: AccentColor` it should take over the currently selected accent color of the system.

### Did you test this? If so, how?

Yes, I set up a test page in Firefox, Chrome, Safari and used the inspector to set the background color of an element to AccentColor. In Firefox and Safari this worked, but in chrome the value gets ignored

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

A test page:

https://codepen.io/xaddict/pen/BavXLYM

### Do you have anything more you want to share?

![Screenshot 2023-10-18 at 13 26 18](https://github.com/mdn/browser-compat-data/assets/3295364/9bfe3f7d-9ac7-41c1-ac3e-0ae5ab230be6)

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/system-color

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.types.color.system-color`
* Report started: 2023-10-18T11:21:59.577Z

</details>

**Comment by lukewarlow** [comment]
Accent color just doesn't have its own data by the looks of things. Given it's newer than the rest of should do. (Safari should be partial support or at least with a note because it's a fake colour).

**Comment by xaddict** [comment]
> (Safari should be partial support or at least with a note because it's a fake colour).

Safari uses accentcolor = blue, like on iOS, so they fully support it, they just don't reflect the accent color of the system appearance panel

**Comment by lukewarlow** [comment]
I think it's slightly disingenuous to present that as full support given the entire purpose of the colour is to match other UA styled UI that uses the system accent color. At the very least a note should be added even if not partial flag.

**Comment by queengooborg** [comment]
#21150 added a subfeature for `AccentColor` and `AccentColorText`, marking Chrome as supported behind a flag!

**Comment by xaddict** [comment]
I know. I added that 😉

**Comment by scottromack** [comment]
The world needs AccentColor to return the system accent-color not just a static blue.

**Comment by xaddict** [comment]
> The world needs AccentColor to return the system accent-color not just a static blue.

Yes. But that's still better than Chrome with the flag off. Where the color is non-existent, and so transparent.

**Comment by scottromack** [comment]
Is there a roadmap for this feature?
This would be a really cool way to make websites very user custom.
Use AccentColor to build out a full pallet based on system prefs.

**Comment by xaddict** [comment]
> Is there a roadmap for this feature? This would be a really cool way to make websites very user custom. Use AccentColor to build out a full pallet based on system prefs.

I think this is the wrong place for that question 🙂 I would post bug tickets for Chrome and Safari (if there aren't any yet) and see if they get picked up. I personally think this should have been in an Interop.

You can always use custom properties in combination with an `@supports` to get started with a fallback.

**Comment by xaddict** [comment]
Made a simple setup in Codepen: https://codepen.io/xaddict/full/dPYyvgy

It falls back to limegreen on Chrome (to piss those people off), uses the macOS 9 blue in Safari and shows the correct colors in Firefox.
