### ISSUE TITLE
api.ServiceWorkerContainer.register - firefox seems to not support import in service workers

### ISSUE THREAD

**Issue by serapath** [mdn/browser-compat-data#21072]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

firefox is supposed to support import in service workers since version 114, but in firefox 118 it doesnt seem to work

### What browsers does this problem apply to, if applicable?

Firefox

### What did you expect to see?

i did expect the service worker script to register successfully in firefox

### Did you test this? If so, how?

I created a repository with github page and it doesnt register the service worker in firefox 118

https://github.com/serapath/ff-sw-import/

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

i created a comment here:
* https://github.com/w3c/ServiceWorker/issues/1585#issuecomment-1776461160

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerContainer/register

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.ServiceWorkerContainer.register`
* Report started: 2023-10-24T03:31:44.163Z

</details>

**Comment by asutherland** [comment]
Agreed, https://bugzilla.mozilla.org/show_bug.cgi?id=1360870 tracks (finishing) implementing support for modules in ServiceWorkers.  Firefox does not support use of import in ServiceWorkers at this time.

**Comment by serapath** [comment]
Is this supposed to be fixed soon or will this stay open for a potentially indefinite, or at least let's say probably a long time?

Knowing this would help me to make architecture decisions.

**Comment by queengooborg** [comment]
This lack of support for ECMAScript modules as service workers is documented in BCD: https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorker#browser_compatibility

> Is this supposed to be fixed soon or will this stay open for a potentially indefinite, or at least let's say probably a long time?

Based on the comments that I see in the bug linked above, it appears that there is active work on this at the moment.  I can't vouch for when this would be completed, that's an answer only Firefox engineers can give.

---

Anyways, I'm going to close this issue since there is no action for BCD to take.
