### ISSUE TITLE
css.properties.counter-set - Added to Safari Technology Preview 178 and works in Safari 17.1

### ISSUE THREAD

**Issue by Edwardmunn** [mdn/browser-compat-data#21097]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

counter-set was added to Safari Technology Preview 178 and works in (at least) Safari 17.1.

https://www.webkit.org/blog/14435/release-notes-for-safari-technology-preview-178/

### What browsers does this problem apply to, if applicable?

Safari

### What did you expect to see?

counter-set should display as 'Full support' for Safari 17.1

### Did you test this? If so, how?

counter-set works as expected on Safari 17.1

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://www.webkit.org/blog/14435/release-notes-for-safari-technology-preview-178/
https://github.com/WebKit/WebKit/commit/35c672ab42641db0295b649a694a3355bf2b03e2

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/counter-set

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.counter-set`
* Report started: 2023-10-26T11:57:01.976Z

</details>

**Comment by queengooborg** [comment]
Fixed in #21267!
