### ISSUE TITLE
http.status.406 - <SUMMARIZE THE PROBLEM>

### ISSUE THREAD

**Issue by OwnerSam** [mdn/browser-compat-data#21111]
### What type of issue is this?

Browser bug (a bug with a feature that may impact site compatibility)

### What information was incorrect, unhelpful, or incomplete?

![Screenshot_2023-10-28_100022](https://github.com/mdn/browser-compat-data/assets/149259106/2fb1ed8f-92df-420d-8ded-fb5b09ef309a)

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

Login website for Gwent: The Witcher Card Game.

### Did you test this? If so, how?

Through the applicaton and clicking on login link in website playgwent.com

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://login.gog.com/auth?brand=gwent&client_id=48992752450954498&gog_lc=EN_USD_es-ES&layout=branded&redirect_uri=https%3A%2F%2Fwww.playgwent.com%2Fes%2Fon_login_success&response_type=code&start_from=login

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/406

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `http.status.406`
* Report started: 2023-10-28T16:17:22.780Z

</details>

**Comment by queengooborg** [comment]
This repository is not for reporting issues with specific sites.  Please report this issue to the website maintainers instead.
