### ISSUE TITLE
new OffscreenCanvas().getContext("webgl2") in web worker - reported as not working in Mobile Safari, does work

### ISSUE THREAD

**Issue by doctorpangloss** [mdn/browser-compat-data#21127]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Safari and Safari on iOS support for OffscreenCanvas getContext for `webgl` and `webgl2` is incorrectly marked as **not supported* in https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas

### What did you expect to see?

Safari and Safari on iOS support for OffscreenCanvas getContext for `webgl` and `webgl2` should be marked as checked for 17 in https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas

### Did you test this? If so, how?

Visit https://threejs.org/examples/webgl_worker_offscreencanvas.html on an iOS device with the latest OS update at the time of running (iOS 17.1) and on a macOS Sonoma installation.

Also run `new OffscreenCanvas(1280,720).getContext("webgl2")` in a web console and observe it works in both Safari 17 on Sonoma and Mobile Safari in iOS 17.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas

### Do you have anything more you want to share?

https://stackoverflow.com/questions/76380311/offscreencanvas-threejs-issue-on-safari

**Comment by queengooborg** [comment]
This was fixed in #22742!
