### ISSUE TITLE
api.URL.canParse_static - `URL.canParse()` may mark as experimental

### ISSUE THREAD

**Issue by skyclouds2001** [mdn/browser-compat-data#21131]
### What type of issue is this?

Other

### What information was incorrect, unhelpful, or incomplete?

URL.canParse may mark as experimental

### What did you expect to see?

-

### Did you test this? If so, how?

![image](https://github.com/mdn/browser-compat-data/assets/95597335/8217d3ad-3518-467e-bbc9-3fc3276b76d7)

URL.canParse hasn't support by some major browsers

![image](https://github.com/mdn/browser-compat-data/assets/95597335/bcf42be2-ad47-4691-bddf-d66f4345bb3d)

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/URL/canParse_static

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.URL.canParse_static`
* Report started: 2023-10-31T12:09:56.428Z

</details>

**Comment by Josh-Cena** [comment]
Firefox 115 + Safari 17 (which are both stable releases) are two major implementations, so it qualifies for MDN's criteria for non-experimental.

**Comment by queengooborg** [comment]
Please see https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/index.md#setting-experimental for the criteria on when experimental status is chosen and when it is not.  Closing.

**Comment by skyclouds2001** [comment]
Thanks, I now understand why
