### ISSUE TITLE
api.WorkerGlobalScope - Add compatibility data for `rejectionhandled` event and `unhandledrejection` event

### ISSUE THREAD

**Issue by skyclouds2001** [mdn/browser-compat-data#21147]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

`WorkerGlobalScope.rejectionhandled` event and `WorkerGlobalScope.unhandledrejection` event does not has its compatibility data

### What did you expect to see?

-

### Did you test this? If so, how?

-

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

see https://html.spec.whatwg.org/multipage/workers.html#the-workerglobalscope-common-interface for standard

also may see https://github.com/microsoft/TypeScript/blob/main/src/lib/webworker.generated.d.ts#L8428 as a reference

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.WorkerGlobalScope`
* Report started: 2023-11-02T03:27:06.551Z

</details>

**Comment by caugner** [comment]
Related: https://github.com/mdn/content/issues/29869

**Comment by queengooborg** [comment]
The mdn-bcd-collector detects support, so these will be added during a pass of the feature addition process.
