### ISSUE TITLE
api.SpeechSynthesisUtterance - <getVoices not working on safari>

### ISSUE THREAD

**Issue by myanch200** [mdn/browser-compat-data#21142]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

For Safari version 16.6 (18615.3.12.11.2) window.speechSynthesis.getVoices() does not work.
No errors in the console or any warning, just the voices are not loaded.

I tried the example from this page:
https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesisUtterance

But it didn't work

### What did you expect to see?

I expected my select box to be populated with options from the getVoices() function. This works perfectly fine on Google Chrome.

### Did you test this? If so, how?

I tested this manually it works on Google Chrome, but not on safari

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesisUtterance

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.SpeechSynthesisUtterance`
* Report started: 2023-11-01T17:35:25.473Z

</details>

**Comment by queengooborg** [comment]
Running `speechSynthesis.getVocies()` works in Safari 17.1, and I haven't run into any issues of lack of support in Safari 16.6.  If it's still not working on your end, there may be something else going on.
