### ISSUE TITLE
api.ReadableStream.from_static - nodejs/deno versions

### ISSUE THREAD

**Issue by jcbhmr** [mdn/browser-compat-data#21152]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Node.js latest and Deno latest both support `ReadableStream.from()` but they aren't listed on MDN

### What browsers does this problem apply to, if applicable?

Node.js, Deno

### What did you expect to see?

Them being listed with ✅ and a version number

### Did you test this? If so, how?

```sh
jcbhmr@PIG-2016:~/Documents/deno-response-test$ node
Welcome to Node.js v21.1.0.
Type ".help" for more information.
> ReadableStream.from
[Function: from]
>
```

```sh
jcbhmr@PIG-2016:~/Documents/deno-response-test$ deno
Deno 1.38.0
exit using ctrl+d, ctrl+c, or close()
REPL is running with all permissions allowed.
To specify permissions, run `deno repl` with allow flags.
> ReadableStream.from
[Function: from]
>
```

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://nodejs.org/api/webstreams.html#readablestreamfromiterable

> Added in: v20.6.0

https://github.com/nodejs/node/pull/48395

---

https://github.com/denoland/deno/releases/tag/v1.35.0#:~:text=feat%3A-,ReadableStream.from,-(%2319446)

> v1.35.0

https://github.com/denoland/deno/pull/19446

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream/from_static

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.ReadableStream.from_static`
* Report started: 2023-11-03T00:26:24.710Z

</details>

**Comment by hamishwillee** [comment]
Thanks very much!. This should be fixed by https://github.com/mdn/browser-compat-data/pull/21153

Note, you're welcome to create your own PRs for these kind of fixes.
