### ISSUE TITLE
http.status.500 - Unable to open Roblox and Roblox Studio

### ISSUE THREAD

**Issue by MrDude76** [mdn/browser-compat-data#21173]
### What type of issue is this?

Browser bug (a bug with a feature that may impact site compatibility)

### What information was incorrect, unhelpful, or incomplete?

I can't open Roblox or Roblox studio because of an HTTP 500 Error. It always crashes every time I try to open them.

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

I expected for them to load properly so I can play my games.

### Did you test this? If so, how?

Yes. I've uninstalled and reinstalled,  searched the internet to find this forsaken problem that has been going for 5 months right now.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `http.status.500`
* Report started: 2023-11-06T14:07:11.005Z

</details>

**Comment by queengooborg** [comment]
If this is a genuine report, you are definitely in the wrong place.  You will have to talk to Roblox themselves for your problem.

**Comment by limck620** [comment]
> ### What type of issue is this?
> 
> Browser bug (a bug with a feature that may impact site compatibility)
> 
> ### What information was incorrect, unhelpful, or incomplete?
> 
> I can't open Roblox or Roblox studio because of an HTTP 500 Error. It always crashes every time I try to open them.
> 
> ### What browsers does this problem apply to, if applicable?
> 
> Chromium (Chrome, Edge 79+, Opera, Samsung Internet)
> 
> ### What did you expect to see?
> 
> I expected for them to load properly so I can play my games.
> 
> ### Did you test this? If so, how?
> 
> Yes. I've uninstalled and reinstalled,  searched the internet to find this forsaken problem that has been going for 5 months right now.
> 
> ### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?
> 
> _No response_
> 
> ### Do you have anything more you want to share?
> 
> _No response_
> 
> ### MDN URL
> 
> https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500
> 
> ### MDN metadata
> 
> 
> <details>
> <summary>MDN page report details</summary>
> 
> * Query: `http.status.500`
> * Report started: 2023-11-06T14:07:11.005Z
> 
> </details>
