### ISSUE TITLE
css.selectors.nesting - needs updating

### ISSUE THREAD

**Issue by argyleink** [mdn/browser-compat-data#21189]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Chrome 120 ships relaxed nesting  
Firefox 117 shipped nesting (with relaxed syntax)  
Safari tech preview has relaxed nesting  

### What did you expect to see?

expected to see Firefox on caniuse with nesting support

### Did you test this? If so, how?

https://codepen.io/web-dot-dev/pen/BaMpXbV/b8ae3f25f6430792108b6444190bb590

**Comment by nt1m** [comment]
The relaxed nesting is also in Safari 17.2 beta: https://developer.apple.com/documentation/safari-release-notes/safari-17_2-release-notes

**Comment by romainmenke** [comment]
I think this is already up to date?

see : https://github.com/mdn/browser-compat-data/pull/21668

**Comment by queengooborg** [comment]
Yep, that PR resolves this AFAICT!
