### ISSUE TITLE
api.fetch -  init.keepalive param supported in nodejs v19

### ISSUE THREAD

**Issue by mirzafaisalbaig** [mdn/browser-compat-data#21215]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

In the Browser compatibility table/info, the support for init.keepalive param was missing or wasn't  updated.

### What browsers does this problem apply to, if applicable?

Node.js

### What did you expect to see?

I was expecting the browser compatible table to be updated. 

### Did you test this? If so, how?

const http = require('http');

const agent = new http.Agent({
  keepAlive: true,
  maxSockets: 10,
});

const server = http.createServer((req, res) => {
  res.setHeader('Connection', 'keep-alive');
  res.end('Hello, World!');
});

server.listen(8080, () => {
  console.log('Server listening on port 8080');
});

### Do you have anything more you want to share?

https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API#browser_compatibility

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.fetch`
* Report started: 2023-11-11T07:49:58.331Z

</details>

**Comment by queengooborg** [comment]
The `http` module is not the same as the `fetch()` method described on this page.
