### ISSUE TITLE
css.properties.backdrop-filter - If I add backdrop-filter: blur(10px) on parent, and it has child's position fixed, then position fixed doesn't work.

### ISSUE THREAD

**Issue by raviinstaller** [mdn/browser-compat-data#21318]
### What type of issue is this?

Other

### What information was incorrect, unhelpful, or incomplete?

I need details about parent child relationship or compatibility.

In my case:
```
<parent backdrop-filter=blur(10px)>
    <child position="fixed">something here...</child>
</parent>
```

this code is for simple explanation only.

### What did you expect to see?

I want to make child's position fixed.

### Did you test this? If so, how?

Yes, in chrome browser.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/backdrop-filter

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.backdrop-filter`
* Report started: 2023-11-22T10:03:06.356Z

</details>

**Comment by queengooborg** [comment]
Can confirm this is an issue in Chrome 119.  `position: fixed` seems to act just like `position: absolute` when the containing element has a `backdrop-filter`.

This feels like an edge case and is too specific to document in BCD, though.  However, it's an issue that should be fixed, so I recommend filing a bug report with Chrome at https://bugs.chromium.org/ (if there isn't already one).
