### ISSUE TITLE
api.HTMLInputElement.showPicker - 'time' erroneously marked as not supported in Firefox for Android

### ISSUE THREAD

**Issue by lukewarlow** [mdn/browser-compat-data#21360]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Currently it says that firefox for android doesn't support showPicker method on the time input.

### What browsers does this problem apply to, if applicable?

Firefox

### What did you expect to see?

It should show it's supported. I'm assuming as of v101 but haven't confirmed.

### Did you test this? If so, how?

Yes on Firefox for Android v120.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/showPicker

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.HTMLInputElement.showPicker`
* Report started: 2023-11-27T14:41:53.305Z

</details>

**Comment by makotokato** [comment]
Fixed by https://github.com/mdn/browser-compat-data/pull/21357.

(Also, month and week are broken now. It is https://bugzilla.mozilla.org/show_bug.cgi?id=1853797)
