### ISSUE TITLE
api.SpeechRecognition - <SUMMARIZE THE PROBLEM>

### ISSUE THREAD

**Issue by DeaconSt** [mdn/browser-compat-data#21393]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

Se supone que la API es compatible con todos los navegadores basados en chromium, pero algunos como por ejemplo en brave o en Wolvic (Navegador en realidad virtual)

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

Esperaba que la API funcionara correctamente

### Did you test this? If so, how?

Implementando el siguiente script: if (
  "SpeechRecognition" in window ||
  "webkitSpeechRecognition" in window ||
  "OculusSpeechRecognition" in window
) {
  // Intenta acceder directamente a la propiedad proporcionada por el entorno
  recognition = new (window.SpeechRecognition ||
    window.webkitSpeechRecognition ||
    window.OculusSpeechRecognition)();
  recognition.lang = "es-ES"; // Establece el idioma de reconocimiento en español
  console.log("API de reconocimiento soportada");
} else {
  console.log("API de reconocimiento no soportada");
  alert("La API de reconocimiento de voz no es compatible con este navegador."); // Muestra un mensaje de error de compatibilidad
  document.getElementById("startButton").disabled = true; // Deshabilita el botón de inicio
}

, pero parece que la api no es soportada (else)

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.SpeechRecognition`
* Report started: 2023-11-29T16:49:31.970Z

</details>

**Comment by queengooborg** [comment]
Hola @DeaconSt -- no tenemos data para otro navegadores basados en Chromium como Brave o Wolvic (pero tenemos data para Edge y Opera).  No podemos decir si hay compatibilidad en estos navegadores, lo siento.

(Translation for others who may see this issue: the reporter is stating that the SpeechRecognition API does not appear to be supported in Brave or Wolvic.  I responded stating that we don't track data for either of those browsers.)
