### ISSUE TITLE
api.fetch - Safari 17.2 supports fetch priority

### ISSUE THREAD

**Issue by saschanaz** [mdn/browser-compat-data#21421]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Safari supports this but BCD says no.

### What browsers does this problem apply to, if applicable?

Safari

### What did you expect to see?

A support version

### Did you test this? If so, how?

`fetch("", { get priority() { console.log('priority') } })`

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

Enabled by default in the main branch on August: https://github.com/WebKit/WebKit/commit/793f132ba08ba69462713ded8e74294bd400023e, which can be confirmed in Feature Flags in Safari 17.2.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/fetch

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.fetch`
* Report started: 2023-12-02T11:43:13.590Z

</details>

**Comment by queengooborg** [comment]
Hey @saschanaz!  Would you be down to submit a PR for this?

**Comment by saschanaz** [comment]
I have no good way to say which exact Safari version got it, do you?

**Comment by saschanaz** [comment]
> However, I see in this feature's commit that there's only two tags, and neither of them have `Safari-`:

Hmm, I see no Safari- tags in new tags: https://github.com/WebKit/WebKit/tags, has Apple changed the tag system? 🤔

> I did test this feature in Safari 17.1, however, and confirmed that there's no support, so either "17.2" or "preview" would apply here, I'd say?

It's enabled by default per the config (see OP) so I guess it's 17.2. 👍

**Comment by Elchi3** [comment]
17.2 seems likely. In https://github.com/mdn/browser-compat-data/pull/21267 the collector found the following:

api.HTMLLinkElement.fetchPriority
api.HTMLImageElement.fetchPriority
api.HTMLScriptElement.fetchPriority 
html.elements.link.fetchpriority 
html.elements.script.fetchpriority 
html.elements.img.fetchpriority 

api.fetch.init_priority_parameter is probably not automatically checked for support right now unfortunately.

**Comment by queengooborg** [comment]
This has been fixed in #21850!
