### ISSUE TITLE
Investigate use of better-ajv-errors

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#2143]
The goal of https://www.npmjs.com/package/better-ajv-errors is to provide better error messages when schema validation fails. We should investigate if integrating this package improves our typical error messages.

**Comment by octref** [comment]
Have you thought about using TypeScript? With it you can:

- Explicitly define your schema in code
- Export the generated type definition, which allows editor to offer auto completion, jump to definition, etc
- Do schema validation with the help of types, which should make it easier

**Comment by ExE-Boss** [comment]
@octref The data is stored in JSON format, and the code portion is relatively simple and is invisible to consumers of the data.

As for the type definition, see #2308.
