### ISSUE TITLE
api.Navigator.userAgentData - <SUMMARIZE THE PROBLEM>

### ISSUE THREAD

**Issue by vegetablez8848** [mdn/browser-compat-data#21436]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

android webview can use navigator.userAgentData in 120

### What did you expect to see?

you can change it.

### Did you test this? If so, how?

yes

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://developer.mozilla.org/en-US/docs/Web/API/Navigator/userAgentData

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Navigator/userAgentData

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.Navigator.userAgentData`
* Report started: 2023-12-03T09:42:30.490Z

</details>

**Comment by queengooborg** [comment]
Hi there -- FYI, just being able to change a value (ex. `navigator.userAgentData = "foo"`) isn't an indication of support.  Please refer to https://mdn-bcd-collector.gooborg.com/tests/api/Navigator/userAgentData for a simple test to determine if the property is, in fact, supported.  If it is, please provide details as to what app you're using, your WebView version, your Android device model, and your Android version.
