### ISSUE TITLE
api.HTMLInputElement. showPicker 'month' and 'week' now supported in Firefox for Android

### ISSUE THREAD

**Issue by lukewarlow** [mdn/browser-compat-data#21524]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

It's marked as unsupported.

### What browsers does this problem apply to, if applicable?

Firefox

### What did you expect to see?

Support from Firefox for Android 121

### Did you test this? If so, how?

Tested with https://demo.lukewarlow.dev/showPicker/ in Firefox 122 nightly but the bug shows it's been pulled into 121.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://bugzilla.mozilla.org/show_bug.cgi?id=1853797

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/showPicker

**Comment by queengooborg** [comment]
The [linked commit](https://hg.mozilla.org/releases/mozilla-beta/rev/c6f495f8acbd) says 121, so let's go for that!  Would you be down to submit a PR for this?

**Comment by lukewarlow** [comment]
Yeah happy to submit one tomorrow mostly raised as a reminder to do it :)
