### ISSUE TITLE
api.URLSearchParams.delete - the `value` parameter of `delete()` method and `has()` method in chromium is supported

### ISSUE THREAD

**Issue by skyclouds2001** [mdn/browser-compat-data#21546]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

the value parameter of `delete()` method and `has()` method in chromium is supported

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

fix the compat data

### Did you test this? If so, how?

just go to https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/delete or https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/has to see the live example

tested already on Chrome 119.0.6045.200

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/delete
https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/has

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/delete

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.URLSearchParams.delete`
* Report started: 2023-12-08T16:36:12.135Z

</details>

**Comment by queengooborg** [comment]
This was fixed in #22743!
