### ISSUE TITLE
HTMLElement cancel event - incorrect links and no root support data

### ISSUE THREAD

**Issue by Cipscis** [mdn/browser-compat-data#21585]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

The MDN page for the ["cancel" event](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/cancel_event) for the `HTMLElement` interface reports no compatability data exists. However, there is compatability data for the "cancel" event for `HTMLDialogElement` and for `HTMLInputElement`, which are two separate pieces of functionality relating to the same event. They just don't display on the page for this event.

Also, the `HTMLDialogElement` entry tries incorrectly to link to the event specifically for the `HTMLDialogElement` interface, but no such documentation exists. Rather, there is a page for this event directly for the `HTMLElement` interface. The entry for the event against the `HTMLInputElement` interface does not link anywhere.

### What did you expect to see?

I think this split between support for these different types of element makes sense, but the "cancel" event itself should display a breakdown of support for these two types of behaviour - for `HTMLDialogElement` and for `HTMLInputElement`.

The entries for the "cancel" event for the `HTMLDialogElement` and for the `HTMLInputElement` should both link to the page for the "cancel" event for the `HTMLElement` interface.

### Did you test this? If so, how?

I didn't test this - data seems correct, just needs improved organisation.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

[HTMLElement/cancel_event](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/cancel_event)

**Comment by skyclouds2001** [comment]
Coming here as https://github.com/mdn/content/pull/30946 has been closed

This event only fires at `<dialog>` element and `<input>` element, though the event can be listened on any `HTMLElement`s

see the spec https://html.spec.whatwg.org/multipage/indices.html#event-cancel

![image](https://github.com/mdn/browser-compat-data/assets/95597335/cf9396ea-1d99-4be1-9491-e42ba5bebfe5)

for the normal behavior, the BCD of the event will only add to `HTMLInputElement` and `HTMLDialogElement`
