### ISSUE TITLE
api.LockManager - navigator.locks not defined

### ISSUE THREAD

**Issue by deniskkk** [mdn/browser-compat-data#21595]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

browser support for locks

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet), Firefox

### What did you expect to see?

navigator.locks to be defined

### Did you test this? If so, how?

console.log(navigator.locks.request);

### Do you have anything more you want to share?

getting error 
main.ts:5 ERROR TypeError: Cannot read properties of undefined (reading 'request')

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/LockManager

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.LockManager`
* Report started: 2023-12-11T15:30:36.946Z

</details>

**Comment by queengooborg** [comment]
This is contradictory to the results of the mdn-bcd-collector -- see https://mdn-bcd-collector.gooborg.com/tests/api/Navigator/locks.  Running that test in all current versions of browsers shows that it is working as expected.

Please note that you will need a secure context to use this API.
