### ISSUE TITLE
api.Window.open - does not work on iOS

### ISSUE THREAD

**Issue by mr-fixit** [mdn/browser-compat-data#21661]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

The table says window.open() works on iOS, but it doesn't. 
A google search for "ios js window.open" will find plenty of posts that agree it doesn't work.

### What browsers does this problem apply to, if applicable?

Safari

### What did you expect to see?

Point Safari (macOS) debugger at a webview on iOS (either in Safari-iOS or any iOS app that lets you see its WKWebViews), Execute `window.open("https://apple.com")` in the console.

### Did you test this? If so, how?

above

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://developer.mozilla.org/en-US/docs/Web/API/Window/open

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Window/open

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.Window.open`
* Report started: 2023-12-18T17:18:54.439Z

</details>

**Comment by queengooborg** [comment]
It appears that this method doesn't work if the target is unspecified or is `_blank`.  Using `_self`, `_parent` and `_top` as the target works as expected.
