### ISSUE TITLE
html.elements.input.type_time - Safari doesn't "fully support" time input, no time picker UI.

### ISSUE THREAD

**Issue by StyxOfDynamite** [mdn/browser-compat-data#21674]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Browser comaptibiity table suggest that time input is supported by safari, but its only partial support, there is no "picker ui", the clock icon, that offers drop downs for hours and minutes.

### What browsers does this problem apply to, if applicable?

Safari

### What did you expect to see?

I expected to see partial support for time input.

### Did you test this? If so, how?

compared https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_type_time in chrome, edge and safair

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

No

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `html.elements.input.type_time`
* Report started: 2023-12-19T12:05:53.501Z

</details>

**Comment by queengooborg** [comment]
A UI difference does not mean that a feature isn't supported.  Browsers are free to implement a UI however they'd like to.  Note that the field has proper validation and constraints for the input.
