### ISSUE TITLE
css.selectors.has - now supported in a released version of Firefox Desktop (121)

### ISSUE THREAD

**Issue by zymurgic** [mdn/browser-compat-data#21682]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Firefox has publicly released version 121, which adds support for :has() in CSS

### What browsers does this problem apply to, if applicable?

Firefox

### What did you expect to see?

Support for :has() showing for Firefox

### Did you test this? If so, how?

Tested :has() functionality in Firefox Desktop 121, examples as per https://developer.mozilla.org/en-US/docs/Web/CSS/:has

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://developer.mozilla.org/en-US/docs/Web/CSS/:has

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/:has

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.selectors.has`
* Report started: 2023-12-19T19:08:24.331Z

</details>

**Comment by aidenguinnip** [comment]
Came here to say the same thing. I've been counting down the days 😄

**Comment by sassquad** [comment]
I came here also for the same reason. Let's do this! :)

**Comment by queengooborg** [comment]
BCD already states that `has` is supported in Firefox 121; see https://developer.mozilla.org/en-US/docs/Web/CSS/:has#browser_compatibility.  The MDN website just hasn't updated yet to say that Firefox 121 is a stable release.
