### ISSUE TITLE
api.Navigator.registerProtocolHandler - <SUMMARIZE THE PROBLEM>

### ISSUE THREAD

**Issue by shiywsg** [mdn/browser-compat-data#21684]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

I am using Chrome version 120.0.6099.110 from computer and it says not supported.

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

the support information is displayed.

### Did you test this? If so, how?

I clicked a a few times and it says not supported.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Navigator/registerProtocolHandler

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.Navigator.registerProtocolHandler`
* Report started: 2023-12-19T22:12:31.507Z

</details>

**Comment by queengooborg** [comment]
Hi @shiywsg -- thank you for your report, however I cannot confirm a lack of support by using the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com/tests/api/Navigator/registerProtocolHandler).  Please provide more details as to how exactly you do not see support, including the OS you're using, the code you're using, and a screenshot of the issue.
