### ISSUE TITLE
XDR table is missing IE10

### ISSUE THREAD

**Issue by Mouvedia** [mdn/browser-compat-data#2169]
XHR+CORS coexisted with XDR on IE10

correct
https://developer.mozilla.org/fr/docs/Web/API/XDomainRequest

incorrect
https://developer.mozilla.org/en-US/docs/Web/API/XDomainRequest

**Comment by Elchi3** [comment]
This was updated: https://developer.mozilla.org/en-US/docs/Web/API/XDomainRequest#Browser_compatibility

**Comment by Mouvedia** [comment]
No it wasn't:

> It was removed in Internet Explorer 10

This is not true.
cf https://developer.mozilla.org/fr/docs/Web/API/XDomainRequest

**Comment by connorshea** [comment]
#2507 was where this was added, @Mouvedia are you saying the version_removed for all XDR APIs should be IE 11 instead of 10?

If so, do you have a source other than the french MDN article? :)

**Comment by connorshea** [comment]
The IE 11 Compatibility Docs state that XDomainRequest is "replaced by CORS for XMLHttpRequest", so I guess we'll go with it being removed in IE 11?

https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/dev-guides/bg182625(v=vs.85)#legacy-api-additions-changes-and-removals

**Comment by Mouvedia** [comment]
It's my domain of expertise, like I said [up there](https://github.com/mdn/browser-compat-data/issues/2169#issue-327037717) the french one is correct:

> XDomainRequest is an implementation of HTTP access control (CORS) that worked in Internet Explorer 8–10. It was removed in Internet Explorer 11 in favor of using XMLHttpRequest with proper CORS; if you are targeting Internet Explorer 10 (which supports CORS) or later, or wish to support any other browser, you need to use standard HTTP access control.
>
> This interface can send both GET and POST requests.

**Comment by connorshea** [comment]
@Mouvedia fair enough, that works for me.

I found [one source](https://www.xul.fr/ajax/xdomainrequest.php) which describes the `contentType` property but I can't find anything about a `create` method?

I see you use it here: https://github.com/Mouvedia/cb-fetch/blob/7067c56b54a8b688d6372513b31a9d70fe611c2d/index.js#L210

**Comment by Mouvedia** [comment]
`contentType`: t's not a big deal if it's since it _should_ always return `text/plain`
`create`: it's just an alias of `new XDomainRequest()`

Since you are not doing a TypeScript type definition, I don't mind the omissions really. What matters is not having inaccuracies.

**Comment by connorshea** [comment]
👍 I've opened #2652 to change the version_removed values to "11".

**Comment by Mouvedia** [comment]
> I found one source

I wouldn't rely on it: `contentType` is readonly.
