### ISSUE TITLE
html.elements.track - No UA supports `kind="descriptions"`

### ISSUE THREAD

**Issue by aardrian** [mdn/browser-compat-data#21698]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

The table shows all browsers support the `kind` attribute and have for years. However, no browser supports the [`descriptions` value](https://html.spec.whatwg.org/multipage/media.html#attr-track-kind-keyword-descriptions), which is intended for UAs to use to synthesize audio descriptions.

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet), Firefox, Safari

### What did you expect to see?

Partial support for `kind` attribute.

### Did you test this? If so, how?

Yes. I built a demo and tested:
https://adrianroselli.com/2023/12/ad-support-in-html-video.html#Synthesized

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

WHATWG [HTML outlines how it should work](https://html.spec.whatwg.org/multipage/media.html#attr-track-kind-keyword-descriptions):

> Textual descriptions of the video component of the [media resource](https://html.spec.whatwg.org/multipage/media.html#media-resource), intended for audio synthesis when the visual component is obscured, unavailable, or not usable (e.g. because the user is interacting with the application without a screen while driving, or because the user is blind). Synthesized as audio.

WHATWG [HTML even has parsing rules](https://html.spec.whatwg.org/multipage/media.html#playing-the-media-resource):

> One example of when a [media element](https://html.spec.whatwg.org/multipage/media.html#media-element) would be [paused for in-band content](https://html.spec.whatwg.org/multipage/media.html#paused-for-in-band-content) is when the user agent is playing [audio descriptions](https://html.spec.whatwg.org/multipage/media.html#attr-track-kind-descriptions) from an external WebVTT file, and the synthesized speech generated for a cue is longer than the time between the [text track cue start time](https://html.spec.whatwg.org/multipage/media.html#text-track-cue-start-time) and the [text track cue end time](https://html.spec.whatwg.org/multipage/media.html#text-track-cue-end-time).

But I think WHATWG HTML punted to WebVTT, and I think [WebVTT itself](https://w3c.github.io/webvtt/#introduction) has not sorted this:

> The majority of the current version of this specification is dedicated to describing how to use WebVTT files for captioning or subtitling. There is minimal information about chapters and time-aligned metadata and nothing about video descriptions at this stage.

So while this may be a double-spec issue, it is still reported incorrectly here.

### Do you have anything more you want to share?

Consider breaking the table down further by the values of `kind` and noting support for each:
* `captions`
* `chapters`
* `descriptions`
* `metadata`
* `subtitles`

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/track

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `html.elements.track`
* Report started: 2023-12-20T14:27:44.138Z

</details>

**Comment by aardrian** [comment]
And I filed (or updated) the relevant bugs with the browsers:

* Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=1447858#c4
* WebKit: https://bugs.webkit.org/show_bug.cgi?id=266724
* FIrefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1871143

**Comment by Elchi3** [comment]
Thanks for all your research! I've created https://github.com/mdn/browser-compat-data/pull/21720 to add `<track kind='descriptions'>` to the compat data.

**Comment by skyclouds2001** [comment]
@Elchi3 @teoli2003 I guess this issue can be close as the data has been added in #21720
