### ISSUE TITLE
api.HTMLLinkElement - Broken URL for crossOrigin attribute

### ISSUE THREAD

**Issue by TheOldMan2000** [mdn/browser-compat-data#21695]
### What type of issue is this?

Other

### What information was incorrect, unhelpful, or incomplete?

Hi, 
I noticed a broken URL for the attribute crossOrigin in the compatibility table on page [](https://developer.mozilla.org/en-US/docs/Web/API/HTMLLinkElement ). 

The broken link is currently:
`https://developer.mozilla.org/en-US/docs/Web/API/HTMLLinkElement/crossOrigin`

Possibly should be unless more relevant page exists:
`https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin`

All the best.

### What did you expect to see?

Correct working URL instead of 404.

### Did you test this? If so, how?

Clicked on the current link for crossOrigin

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/HTMLLinkElement

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.HTMLLinkElement`
* Report started: 2023-12-20T15:05:07.341Z

</details>

**Comment by fwqaaq** [comment]
It might just be that page doesn't exsit, and these two links are not related.

**Comment by skyclouds2001** [comment]
it should link to `HTMLLinkElement.crossOrigin`, but just the documentation of `HTMLLinkElement.crossOrigin` is not written yet

the solution should be add an documentation for `HTMLLinkElement.crossOrigin`, rather then change the url

**Comment by TheOldMan2000** [comment]
Thank you!
