### ISSUE TITLE
css.properties.scrollbar-gutter - Feature flag support in safari

### ISSUE THREAD

**Issue by manuelmeister** [mdn/browser-compat-data#21693]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

This feature can be enabled with a feature flag: 

### What browsers does this problem apply to, if applicable?

Safari

### What did you expect to see?

`Not supported` & `User must explicitly enable this feature.`

### Did you test this? If so, how?

If I enable this flag in Safari 17.1 (17616.2.9.11.9, 17616) it works.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://github.com/WebKit/WebKit/commit/85da54052e1c789e78ffae77d3dde373f2952da0
https://bugs.webkit.org/show_bug.cgi?id=167335

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-gutter

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.scrollbar-gutter`
* Report started: 2023-12-20T11:58:37.865Z

</details>

**Comment by fwqaaq** [comment]
<img width="926" alt="image" src="https://github.com/mdn/browser-compat-data/assets/82551626/3dd0ea23-33e1-4c4f-875d-b86b361bf09f">

No supported, and there are no reports of bugs like this [here](https://developer.apple.com/documentation/safari-release-notes/safari-17_1-release-notes).

**Comment by manuelmeister** [comment]
@fwqaaq Did you turn on the feature flag in the dev menu?

**Comment by fwqaaq** [comment]
@manuelmeister Thanks for your reminder.

**Comment by queengooborg** [comment]
Hey @manuelmeister!  It looks like you've researched this pretty well, would you be down to submit a PR to add the flag data?
