### ISSUE TITLE
iterator-helpers are no longer supported in Chrome

### ISSUE THREAD

**Issue by debiru** [mdn/browser-compat-data#21691]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Iterator#browser_compatibility

BCD table says iterator-helpers are supported in Chrome 117. Currently, however, these do not work in Chrome.

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

I'm not sure. In the issue, it is commented that it should be set to false.

https://github.com/mdn/browser-compat-data/pull/20573#issuecomment-1701965025

### Did you test this? If so, how?

Does not work with the latest Chrome browser.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Iterator#browser_compatibility
- https://github.com/mdn/browser-compat-data/pull/20573#issuecomment-1701965025

**Comment by Elchi3** [comment]
Fixed in https://github.com/mdn/browser-compat-data/pull/22024
