### ISSUE TITLE
javascript.operators.conditional - <SUMMARIZE THE PROBLEM>

### ISSUE THREAD

**Issue by bajaj689** [mdn/browser-compat-data#21743]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

No information about Internet explorer compatibility for ternary operator.

### What did you expect to see?

Information about Internet explorer compatibility  for ternary operator.

### Did you test this? If so, how?

No

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_operator

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `javascript.operators.conditional`
* Report started: 2023-12-26T11:41:04.873Z

</details>

**Comment by queengooborg** [comment]
Hi @bajaj689 -- FYI, we are no longer maintaining IE support data in this project as of over a year ago, and will eventually remove the existing IE data.
