### ISSUE TITLE
api.HTMLCanvasElement.toBlob - quality parameter is supported in Safari desktop and mobile

### ISSUE THREAD

**Issue by opusonline** [mdn/browser-compat-data#21770]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

HTMLCanvasElement.toBlob "quality" parameter support is saying "not supported" in Safari and Safari on iOS.

### What browsers does this problem apply to, if applicable?

Safari

### What did you expect to see?

quality parameter is supported in Safari and Safari on iOS since version 11.

### Did you test this? If so, how?

I wrote an example app that uses the same function, but with 2 different quality parameter values to compare the result. The example was then tested on browserstack on different browsers. I saw it working back until Safari and Safari on iOS version 11.1.2 and 11.0.

### Do you have anything more you want to share?

Sample code:
(Please note, that the image src is a base64 string of an example image. It's removed in this example since it's too long. You can find the original image here: https://file-examples.com/index.php/sample-images-download/sample-jpg-download/)
```html
<body>
    <h1>Canvas quality test</h1>
    <p><canvas id="canvas-preview"></canvas></p>
    <p id="result"></p>
    <p id="ua"></p>
<script>
const $ = document.querySelector.bind(document);
const canvas = $('#canvas-preview');
const context = canvas.getContext('2d');
const formatter = new Intl.NumberFormat('default', { style: 'percent', maximumFractionDigits: 2 });
const convertToBlob = (canvas, type, quality) => new Promise(resolve => canvas.toBlob(resolve, type, quality));

const init = async () => {
    $('#ua').textContent = navigator.userAgent;
    try {
        const img = await loadImage();
        canvas.width = img.width;
        canvas.height = img.height;
        context.drawImage(img, 0, 0);
        const result = await Promise.all([
            convertToBlob(canvas, 'image/jpeg', 1.0),
            convertToBlob(canvas, 'image/jpeg', 0.1),
        ]);
        const size1 = result[0].size;
        const size2 = result[1].size;
        console.log(size1, size2);
        if (size1 === size2) {
            $('#result').textContent = 'No difference!';
        }
        $('#result').textContent = `10% quality results in an image that is ${formatter.format(size2 / size1)} of the file size.`;
    } catch (error) {
        console.error(error);
        $('#result').textContent = `Error: ${error.toString()}`;
    }
};

const loadImage = () => {
    return new Promise((resolve, reject) => {
        const img = new Image();
        img.onload = () => {
            resolve(img);
        };
        img.onerror = () => {
            reject();
        };
        img.src = 'data:image/jpeg;base64,...';
    });
};

init();
</script>
</body>
```

![Screenshot 2023-12-28 at 11 22 50](https://github.com/mdn/browser-compat-data/assets/484618/fc75ce1f-10d8-4df4-b0cd-7c25b413c56c)
![Screenshot 2023-12-28 at 11 25 33](https://github.com/mdn/browser-compat-data/assets/484618/13401e79-071b-425a-b0ea-b85017e962e5)

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.HTMLCanvasElement.toBlob`
* Report started: 2023-12-28T09:59:48.211Z

</details>

**Comment by francescorn** [comment]
I am addressing the issue at: https://github.com/mdn/browser-compat-data/pull/21775

There was a commit written and merged on the "quality" parameter support into WebKit on Jul 17, 2017 which was two months before the release of Safari 11 on September 19, 2017 at: https://github.com/WebKit/WebKit/commit/d79600d2a2e805ab46022cfa1d550bc90067b01a

**Comment by Elchi3** [comment]
Fixed by https://github.com/mdn/browser-compat-data/pull/21775

**Comment by opusonline** [comment]
For your interest: I've noticed, that caniuse.com is still showing this parameter in Safari as not supported.

https://caniuse.com/mdn-api_htmlcanvaselement_toblob_quality_parameter
![Screenshot 2024-01-03 at 11 26 22](https://github.com/mdn/browser-compat-data/assets/484618/433d05a2-2f69-4344-9fa6-2cc456a1a2a0)

**Comment by francescorn** [comment]
File an issue in the GitHub CanIUse repository as well to streamline the process possibly - https://github.com/Fyrd/caniuse/issues?page=1&q=is%3Aissue+is%3Aopen @opusonline

**Comment by francescorn** [comment]
You can file CanIUse issues here: https://github.com/Fyrd/caniuse/issues.

**Comment by opusonline** [comment]
> You can file CanIUse issues here: https://github.com/Fyrd/caniuse/issues.

Thanks!
