### ISSUE TITLE
http.methods - It says that Edge didn't support the usual HTTP requests (GET, HEAD, POST, PUT, etc.) before 12. I don't think that's correct.

### ISSUE THREAD

**Issue by kailando** [mdn/browser-compat-data#21789]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

I'm pretty sure that GET & POST & more were always supported.

### What browsers does this problem apply to, if applicable?

Legacy Edge (12-18)

### What did you expect to see?

That it was always supported.

### Did you test this? If so, how?

I didn't.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

[https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods)

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods

### MDN metadata

<details>
<summary>MDN page data report details</summary>

* Query: `http.methods`
* Report started: 2023-12-31T21:03:28.797Z

</details>

**Comment by queengooborg** [comment]
Edge never had a release before v12; Edge was a direct continuation off of Internet Explorer, which last release v11.

**Comment by carlosjeurissen** [comment]
@queengooborg could we simply prepend the IE data to Edge as proposed here:
https://github.com/mdn/browser-compat-data/issues/15333#issuecomment-1259928480

To prevent confusions like this?
