### ISSUE TITLE
api.ClipboardEvent.clipboardData - Incorrect availability banner

### ISSUE THREAD

**Issue by edmondwinston** [mdn/browser-compat-data#21794]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

The browser compatibility section down the page shows an early full-compatible across all browser, but the banner displays _Limited availability_

![image](https://github.com/mdn/browser-compat-data/assets/132081506/0521dd00-a169-4318-bf98-6948211b596e)

### What did you expect to see?

A green banner, I suppose.

### Did you test this? If so, how?

Tested on incognito and different regions.

### Do you have anything more you want to share?

This is not a big deal if you knew the thing, but if I have never heard of this API, found it, and see that yellow banner, I'd might have immediately gone back without any further scrolling.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/ClipboardEvent/clipboardData

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.ClipboardEvent.clipboardData`
* Report started: 2024-01-01T05:52:29.400Z

</details>

**Comment by queengooborg** [comment]
That data comes from Baseline, which is not maintained in this repository.  See https://github.com/web-platform-dx/web-features for more details on Baseline.
