### ISSUE TITLE
api.fetch - Safari 17.2 supports setting priority of fetch

### ISSUE THREAD

**Issue by erikt9** [mdn/browser-compat-data#21838]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Safari is marked as not supporting priority with the fetch api at all

### What browsers does this problem apply to, if applicable?

Safari

### What did you expect to see?

Safari 17.2 where support for fetchpriority in general was added 

### Did you test this? If so, how?

In Safari 17.2: 

Went to https://www.google.com/

Open web inspector and right click in the network tab body to show priority of requests

In the console run:
`fetch('https://www.google.com/', { priority: 'low' })`

and

`fetch('https://www.google.com/', { priority: 'high' })`

Network tab shows low and high priority requests respectively

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://developer.apple.com/documentation/safari-release-notes/safari-17_2-release-notes

Safari 17.2 release notes:

> Added support for Fetch Priority. (106852027)

### Do you have anything more you want to share?

Inaccuracy may apply to other fetch priority related pages as well.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/fetch

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.fetch`
* Report started: 2024-01-04T01:35:34.016Z

</details>

**Comment by queengooborg** [comment]
Thanks for the report!  This looks straightforward to me -- would you be down to create a pull request to update the data accordingly?

**Comment by erikt9** [comment]
@queengooborg 
Will try to do in the next day or so

**Comment by erikt9** [comment]
@queengooborg Added a pr
