### ISSUE TITLE
css.selectors.has - Baseline status banner incorrect

### ISSUE THREAD

**Issue by foscjos2** [mdn/browser-compat-data#21871]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

Top Baseline banner on page shows that the :has selector is not supported in firefox, while the banner at the bottom of the page shows that support was added recently. 

### What browsers does this problem apply to, if applicable?

Firefox

### What did you expect to see?

Firefox listed as supported. 

### Did you test this? If so, how?

No. 

### MDN URL

https://developer.mozilla.org/en-US/docs/web/css/:has

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.selectors.has`
* Report started: 2024-01-08T14:29:07.918Z

</details>

**Comment by queengooborg** [comment]
This repository is not responsible for maintaining the Baseline banner data.  Please report this issue to https://github.com/web-platform-dx/web-features.
