### ISSUE TITLE
api.RTCRtpReceiver.transform - Chrome support encoded stream transform

### ISSUE THREAD

**Issue by SetoKaiba** [mdn/browser-compat-data#21887]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

api.RTCRtpReceiver.transform - Chrome support encoded stream transform. But I'm not sure when it began to support.

### What did you expect to see?

It should so the correct support info

### Did you test this? If so, how?

At least the latest version supports it.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Using_Encoded_Transforms

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.RTCRtpReceiver.transform`
* Report started: 2024-01-10T10:12:02.969Z

</details>

**Comment by queengooborg** [comment]
This doesn't seem to be the case; https://mdn-bcd-collector.gooborg.com/tests/api/RTCRtpReceiver/transform shows no support.  Could you provide the test code used to determine support for this feature?

**Comment by SetoKaiba** [comment]
It seems that I misunderstanding it. Chrome supports WebRTC Encoded Transforms by using RTCRtpReceiver.createEncodedStreams. But it's not listed in the doc. I thought that it's a global availability for WebRTC Encoded Streams.

**Comment by queengooborg** [comment]
Ah, gotcha!  No worries, often times browsers will implement a part of the spec, but then it changes and browsers haven't updated to adhere to the new spec version.
