### ISSUE TITLE
api.HTMLAnchorElement.hrefTranslate&html.elements.a.hreftranslate - Missing browser compat data

### ISSUE THREAD

**Issue by skyclouds2001** [mdn/browser-compat-data#21898]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

the data of api.HTMLAnchorElement.hrefTranslate and html.elements.a.hreftranslate are missing

### What did you expect to see?

add data

### Did you test this? If so, how?

test in Chrome 120 and is supported, and reference to many blogs, this might be supported since Chrome 81

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

The spec proposal https://github.com/dtapuska/html-translate, issue https://github.com/w3ctag/design-reviews/issues/301 (closed), pull request https://github.com/whatwg/html/pull/3870 (not merged and not active for more than 3 years) and the feature seems impossible to add to the standard

Chrome group discuss https://groups.google.com/a/chromium.org/g/blink-dev/c/4DZIDt9o1ME

**Comment by queengooborg** [comment]
Added to the collector in https://github.com/openwebdocs/mdn-bcd-collector/pull/1053, this is now tracked and will be added soon.
