### ISSUE TITLE
css.selectors.host - Discrepancies between the baseline widget and the full compatibility table

### ISSUE THREAD

**Issue by elchininet** [mdn/browser-compat-data#21925]
### What type of issue is this?

Other

### What information was incorrect, unhelpful, or incomplete?

In [the `:host` entry on MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/:host). The baseline widget states:

>This feature is not Baseline because it does not work in some of the most widely-used browsers.

<img width="805" alt="image" src="https://github.com/mdn/browser-compat-data/assets/3728220/1cb525c1-b798-4295-8d4a-ca384d28a7d5">

If one clicks on the `See full compatibility` link, the `Browser compatibility` table shows full compatibility and states: `Full support`.

<img width="807" alt="image" src="https://github.com/mdn/browser-compat-data/assets/3728220/e10dc018-454f-491d-8815-e85151a586c4">

### What did you expect to see?

No discrepacies between both sections. If there is full compatibility it should state the same in the `baseline widget` and if there is no full compatibility it should state what are the compatibility issues in the compatibility table.

### Did you test this? If so, how?

I have tested the `:host` selector and it works on Chrome, Safari and Firefox (I have not tested on Edge).

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://developer.mozilla.org/en-US/docs/Web/CSS/:host

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/:host

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.selectors.host`
* Report started: 2024-01-13T15:02:49.243Z

</details>

**Comment by queengooborg** [comment]
This repository is not responsible for maintaining the Baseline banner data. Please report this issue to https://github.com/web-platform-dx/web-features.
