### ISSUE TITLE
webextensions.api.userScripts - Chrome now supports userscripts

### ISSUE THREAD

**Issue by MrBrain295** [mdn/browser-compat-data#21922]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Chrome now supports userscripts.

### What did you expect to see?

Chrome support for userscripts shown.

### Did you test this? If so, how?

Using userscripts in chrome.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://developer.chrome.com/docs/extensions/reference/api/userScripts

### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/userScripts

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `webextensions.api.userScripts`
* Report started: 2024-01-12T20:06:52.869Z

</details>

**Comment by Rob--W** [comment]
The userScripts API currently documented on MDN is Firefox's original userScripts API, consisting of the `user_scripts` manifest key and the `userScripts.register` method. The `userScripts` API that Chrome supports is a new API behind the "userScripts" permission and several other methods, completely including a `userScripts.register` method with a different signature. This new API was designed in the WECG at https://github.com/w3c/webextensions/issues/375, and Chrome was the first to implement it. In Firefox we are currently looking into scheduling the implementation work of the new API.

To clarify the documentation, let's introduce the distinction between the "old" API (userScripts.register methid taking an object and returning a promise resolving to an object with the unregister method, only available to MV2 extensions with the user_scripts manifest key) and the new/standard API (userScripts.register method taking an array of RegisteredUserScript objects and returning an empty promise). Note: confusingly Firefox's return value (with the unregister method) is also called RegisteredUserScript. Let's emphasize that RegisteredUserScript.unregister is Firefox-only.

**Comment by Rob--W** [comment]
The bug tracking Firefox's implementation of the userScripts API is at https://bugzilla.mozilla.org/show_bug.cgi?id=1875475

**Comment by rebloor** [comment]
Closing, as relevant documentation updates will be made on conclusion of [Firefox bug 1875475](https://bugzil.la/1875475)
