### ISSUE TITLE
Incorrect compatibility of EventTarget.addEventListener in MSIE 11

### ISSUE THREAD

**Issue by aristov** [mdn/browser-compat-data#2192]
I checked in SauceLabs and found, that MSIE 11 supports `options` object (third parameter can be either options or a Boolean, for backwards compatibility). 
The `capture` and `once` options work well. I did not check the `passive` option support.

**Comment by vinyldarkscratch** [comment]
Thanks for reporting this!  Have you tested it in other IE versions as well, or just 11?  I'm curious if it was supported in earlier versions.

**Comment by vinyldarkscratch** [comment]
After manual testing, using the [example on MDN](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#Safely_detecting_option_support), I've found that these properties are actually NOT supported in IE 11.  I shall close this issue as a result, but if I'm mistaken, don't hesitate to let me know and we'll re-open this!

<img width="528" alt="Screen Shot 2019-04-28 at 15 47 32" src="https://user-images.githubusercontent.com/5179191/56871044-261a9800-69cd-11e9-93e0-9e83b96311f4.png">
<img width="241" alt="Screen Shot 2019-04-28 at 15 46 55" src="https://user-images.githubusercontent.com/5179191/56871045-2b77e280-69cd-11e9-9f95-283786e9f731.png">
