### ISSUE TITLE
html.elements.input.type_file - The type of python file in some Windows's browser is not recognized

### ISSUE THREAD

**Issue by Liao-elevens** [mdn/browser-compat-data#21932]
### What type of issue is this?

Browser bug (a bug with a feature that may impact site compatibility)

### What information was incorrect, unhelpful, or incomplete?

The type of python file in some windows's browser is not recognized as `type: "text/x-python-script" `;
it show `type: ""` .

![input](https://github.com/mdn/browser-compat-data/assets/48711575/902d4c35-f395-4f5c-ac71-80f055339518)

### What did you expect to see?

to see the correct file type, like `type: "text/x-python-script"`

### Did you test this? If so, how?

**xiaomi windows 11** is incorrect `type: ""`,
but Thinkpad is correct file type
![input](https://github.com/mdn/browser-compat-data/assets/48711575/c2d33313-51f9-46c1-9f17-c729356d27dc)

**Comment by Liao-elevens** [comment]
xiaomi windows 11 is `type:''`,
but thinkpad is correct file type

**Comment by queengooborg** [comment]
There is not enough actionable information to be able to update BCD in any meaningful way.  Please provide clear information of what browser and browser version you are using when experiencing the issue.
