### ISSUE TITLE
css.properties.font-family -  < is not working>

### ISSUE THREAD

**Issue by code-with-kuldeep** [mdn/browser-compat-data#21930]
before some days i am facing an issue in the VS CODE. whenever  I am trying to change my default font family its not working its only showing default font over the browser even I reinstalled the windows as well as my VS CODE but still I am facing same issue and also i checked my code on subline text here  I am also facing the same issue. 

if any one have solution so please feel free to call me and it will help full for me 
7827680083

**Comment by code-with-kuldeep** [comment]
![Uploading Screenshot 2024-01-14 162833.png…]()

**Comment by queengooborg** [comment]
This is not the place to ask for coding assistance, much less software configuration assistance.
