### ISSUE TITLE
Navigation: navigate event - add Bugzilla reference

### ISSUE THREAD

**Issue by erosman** [mdn/browser-compat-data#21952]
### What type of issue is this?

Other

### What information was incorrect, unhelpful, or incomplete?

Add [Bug 1777171: Implement Navigation API](https://bugzilla.mozilla.org/show_bug.cgi?id=1777171) reference to [navigate](https://developer.mozilla.org/en-US/docs/Web/API/Navigation/navigate_event#browser_compatibility)

### What browsers does this problem apply to, if applicable?

Firefox

### What did you expect to see?

Reference added

### Did you test this? If so, how?

n/a

**Comment by queengooborg** [comment]
Hey @erosman!  Would you be down submit a PR to add this?

**Comment by erosman** [comment]
I am not familiar with the browser-compat-data  PR process.
Is there a similar example that I can look at?

**Comment by queengooborg** [comment]
Oh!  I could have sworn you had written a PR or two before, my apologies!

Adding the bug URL is pretty straightforward, you can reference https://github.com/mdn/browser-compat-data/pull/21907 as an example.  Additionally, you can review the description of BCD's file schema here: https://github.com/mdn/browser-compat-data/blob/main/schemas/compat-data-schema.md

**Comment by erosman** [comment]
> You must be on a branch to make or propose changes to this file

Which branch would that be?

**Comment by queengooborg** [comment]
Where are you seeing that message?

**Comment by erosman** [comment]
When I click the edit button...

![image](https://github.com/mdn/browser-compat-data/assets/6458876/622a853b-f771-44a3-ba2e-084ebbc363ff)

**Comment by queengooborg** [comment]
Huh...that's...odd.  I'm noticing that you don't have the branch selection dropdown either.  What URL are you on?  https://github.com/mdn/browser-compat-data/blob/main/api/Navigation.json?

**Comment by erosman** [comment]
I was on a permanent URL (resulted from searching for `navigate`)

https://github.com/mdn/browser-compat-data/blob/9e245478a79c555698cfaf2df9ba1b05fef264c6/api/Navigation.json#L275

I will try again.

**Comment by queengooborg** [comment]
Ah, that explains it -- yeah, if you're on a commit blob, you won't be able to use the Edit button!
