### ISSUE TITLE
DedicatedWorkerGlobalScope.requestAnimationFrame - Not supported in nested Web Workers on Chromium

### ISSUE THREAD

**Issue by ArhanChaudhary** [mdn/browser-compat-data#21964]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

My testing has shown that requestAnimationFrame functionality within nested web workers on Chromium browsers is not yet supported. Chromium browsers should instead be marked as partially compatible with this caveat for now.

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

The functionality should work in accordance with the compatibility data.

### Did you test this? If so, how?

Here is the code snippet I used to test for this functionality:

`index.html`
```html
<script>
  new Worker('worker1.js').onmessage = (e) => {
    if (e.data === 'worker1 works')
      document.write("first worker raf works<br>");
    else if (e.data === 'worker2 works')
      document.write("nested worker raf works");
  }
</script>
```
`worker1.js`
```js
requestAnimationFrame(() => self.postMessage("worker1 works"));
new Worker('worker2.js').onmessage = () => self.postMessage("worker2 works");
```
`worker2.js`
```js
requestAnimationFrame(() => postMessage(undefined));
```

When it fails, it errors:
```
Uncaught DOMException: Failed to execute 'requestAnimationFrame' on 'DedicatedWorkerGlobalScope': requestAnimationFrame not supported in this Worker.
```

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

The [current compatibility data](https://github.com/mdn/browser-compat-data/blob/9e245478a79c555698cfaf2df9ba1b05fef264c6/api/DedicatedWorkerGlobalScope.json#L344), the [spec](https://html.spec.whatwg.org/multipage/imagebitmap-and-animations.html#animationframeprovider), and the [MDN page](https://developer.mozilla.org/en-US/docs/Web/API/DedicatedWorkerGlobalScope/requestAnimationFrame).

Paraphrasing the spec, it mentions that one way requestAnimationFrame is considered supported is if its associated web worker initiator also supports requestAnimationFrame. In the above code snippet on Chromium browsers, the first web worker is always able to run requestAnimationFrame successfully while its nested web worker fails, thus contradicting the spec.

**Comment by skyclouds2001** [comment]
This is what I'm saying in https://github.com/mdn/content/pull/30880#discussion_r1422009358, and I've fired an issue to Chromium in https://bugs.chromium.org/p/chromium/issues/detail?id=1510413, which seems that will be fixed in v122

**Comment by ArhanChaudhary** [comment]
Sounds great. The compat tables should still be updated though, right?
