### ISSUE TITLE
http.headers.Permissions-Policy.publickey-credentials-create - Incorrect information about Chrome and missing information about Firefox

### ISSUE THREAD

**Issue by dasJ** [mdn/browser-compat-data#21979]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

- It says Firefox does not support the feature at all
- It says Chrome supports the feature since 88

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet), Firefox

### What did you expect to see?

- Firefox supports this feature from version 123: https://phabricator.services.mozilla.com/D196856
- Chrome supports the feature but only as the HTTP header and not when used in the `allow` directive of an iframe: https://chromestatus.com/feature/5175677674586112

### Did you test this? If so, how?

- Tested the Firefox change by adding a unit test to the change
- Didn't test Chrome but linked the docs in the previous question

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

Edge is probably the same as Chrome

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Permissions-Policy/publickey-credentials-create

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `http.headers.Permissions-Policy.publickey-credentials-create`
* Report started: 2024-01-23T17:21:27.413Z

</details>

**Comment by hamishwillee** [comment]
This will be looked at as part of https://github.com/mdn/content/issues/31890

**Comment by queengooborg** [comment]
The Firefox data was updated in #22172, and I just opened https://github.com/mdn/browser-compat-data/pull/23487 to track the support when used as an `iframe`'s `allow` property!
