### ISSUE TITLE
api.HTMLMediaElement.setSinkId - Browser support ETA

### ISSUE THREAD

**Issue by morcena09** [mdn/browser-compat-data#22080]
### What type of issue is this?

Browser bug (a bug with a feature that may impact site compatibility)

### What information was incorrect, unhelpful, or incomplete?

All information was neither  incorrect, unhelpful, or incomplete.

### What did you expect to see?

 I was hoping for an ETA where the API setSinkID() will be supported on Safari, Chrome Android , iOS Safari and or Samsung Internet.

### Did you test this? If so, how?

I have tested this by creating a simple Web app for switching sound devices , specifically speakers. The setSinkID was still limited to Chrome, Edge, Firefox, Opera desktop browsers.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/setSinkId

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/setSinkId

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.HTMLMediaElement.setSinkId`
* Report started: 2024-01-29T00:43:44.752Z

</details>

**Comment by queengooborg** [comment]
We can't really provide an ETA on when, or even if, this feature will be added to those browsers.  We're currently discussing a potential way to indicate this on MDN.
