### ISSUE TITLE
api.Clipboard.writeText - doesnot work in safari browser

### ISSUE THREAD

**Issue by SushmithaBilasunur** [mdn/browser-compat-data#22096]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

It is said to be compatible with the safari browser but this api throws a request not allowed error in the browser safari.

### What browsers does this problem apply to, if applicable?

safari

### What did you expect to see?

No error , copy to clipboard functionality to work properly

### Did you test this? If so, how?

I tested this with a request to backend, I wanted to copy the response i receive to clipboard. This API completely works fine in chrome browser not in safari.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/writeText

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.Clipboard.writeText`
* Report started: 2024-01-29T14:38:40.719Z

</details>

**Comment by Akunxin** [comment]
This API completely works fine in chrome browser not in safari.  me too

**Comment by queengooborg** [comment]
Using the example from the MDN page, I'm not experiencing any issues in Safari:

```html
<div id="test">
	<button id="button">Click me!</button>
	<p id="log"></p>
</div>

<script>
	const button = document.getElementById("button");
	const log = document.getElementById("log");

	button.addEventListener("click", () => writeClipboardText("<empty clipboard>"));

	async function writeClipboardText(text) {
		try {
			await navigator.clipboard.writeText(text);
			log.innerHTML = "Success!";
		} catch (error) {
			log.innerHTML = error.message;
		}
	}
</script>
```

There is a note in the compat tables that states that the method must be called within user gesture event handlers.  If the method is called outside of user gesture, then an error is thrown stating that it is not allowed.
