### ISSUE TITLE
scrollbar-width: none does not take affect on Windows Chrome

### ISSUE THREAD

**Issue by DarrylLeRoux** [mdn/browser-compat-data#22141]
### What type of issue is this?

Browser bug (a bug with a feature that may impact site compatibility)

### What information was incorrect, unhelpful, or incomplete?

Does not take effect in Chrome on Windows 
![Screenshot 2024-02-02 at 10 49 19](https://github.com/mdn/browser-compat-data/assets/102359359/9c1e11be-5242-49b4-bccd-0ab38490b2f2)

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

Scrollbar to be hidden due to scrollbar-width: none;

### Did you test this? If so, how?

I have, yes. Tested on multiple browsers, on both Mac and Windows. Windows Chrome greys out the attribute. 

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-width

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.scrollbar-width`
* Report started: 2024-02-02T08:47:21.278Z

</details>

**Comment by queengooborg** [comment]
The `scrollbar-width` property was introduced in Chrome 121.  You most likely need to update your browser.  If you are on Chrome 121, let us know and we'll look into it further!
