### ISSUE TITLE
WebGPU - Supported in Chrome Android since 121

### ISSUE THREAD

**Issue by quinton-ashley** [mdn/browser-compat-data#22159]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

Support on some Androids since Google Chrome 121
https://developer.chrome.com/blog/new-in-webgpu-121

Support in Safari Developer Preview
https://webkit.org/blog/14879/webgpu-now-available-for-testing-in-safari-technology-preview/

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet), Safari

### What did you expect to see?

partially supported in Google Chrome Android

in development for Safari and iOS Safari

### Did you test this? If so, how?

no

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/WebGPU_API

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.GPU`
* Report started: 2024-02-03T14:47:43.983Z

</details>

**Comment by skyclouds2001** [comment]
also includes other WebGPU features, like *api.GPUDevice*, etc.
