### ISSUE TITLE
css.selectors.-webkit-scrollbar - Not supported in Chrome

### ISSUE THREAD

**Issue by BoufaiedDev** [mdn/browser-compat-data#22186]
### What type of issue is this?

Browser bug (a bug with a feature that may impact site compatibility)

### What information was incorrect, unhelpful, or incomplete?

it doesnt apply width

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

I smaller width 

### Did you test this? If so, how?

yes , it was always displaying my width as 6px but now it display the default chrome width

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.selectors.-webkit-scrollbar`
* Report started: 2024-02-07T15:13:51.519Z

</details>

**Comment by queengooborg** [comment]
I'm not having any issues changing the width in Chrome.  Please provide your test code so that we can confirm the issue.
