### ISSUE TITLE
https://www.facebook.com/kiriroli

### ISSUE THREAD

**Issue by Kiriroland** [mdn/browser-compat-data#22199]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

https://www.facebook.com/kiriroli

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet), Safari

### What did you expect to see?

https://www.facebook.com/kiriroli

### Did you test this? If so, how?

https://www.facebook.com/kiriroli

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://www.facebook.com/kiriroli

### Do you have anything more you want to share?

https://www.facebook.com/kiriroli

### MDN URL

https://www.facebook.com/kiriroli

### MDN metadata

https://www.facebook.com/kiriroli

**Comment by hamishwillee** [comment]
Please don't use this site as a sandbox. It wastes developer time.
