### ISSUE TITLE
webextensions.manifest.theme tab_background_separator and toolbar_field_separator should be marked as deprecated in Firefox 89

### ISSUE THREAD

**Issue by rpl** [mdn/browser-compat-data#22215]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

The two theme properties named `tab_background_separator` and `toolbar_field_separator` have been both deprecated in Firefox 89 (see blog post https://blog.mozilla.org/addons/2021/04/19/changes-to-themeable-areas-of-firefox-in-version-89/), changes to the MDN content were tracked by mdn/content#4390 and that has been already merged some time ago (and so the MDN docs highlight that these two properties have been deprecated), but the compat data has not been updated yet and so the compatibility table still show both as supported in Firefox.

### What browsers does this problem apply to, if applicable?

Firefox

### What did you expect to see?

The compatibility table below the MDN page at https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/theme#browser_compatibility should show  `tab_background_separator` and `toolbar_field_separator` as not suported (and optionally point to the blogpost for more details about their deprecation)

### Did you test this? If so, how?

This was a change that was expected to be part of the followups of the Firefox 89 restyling (codenamed Proton), it was tracked on bugzilla by [Bug 1705792](https://bugzilla.mozilla.org/show_bug.cgi?id=1705792) and I noticed the inconsistency while retriaging the bug. The blog post we published at the time also mention these two theme properties as deprecated: https://blog.mozilla.org/addons/2021/04/19/changes-to-themeable-areas-of-firefox-in-version-89/.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

- blogpost: https://blog.mozilla.org/addons/2021/04/19/changes-to-themeable-areas-of-firefox-in-version-89/
- bugzilla tracking issue: [Bug 1705792](https://bugzilla.mozilla.org/show_bug.cgi?id=1705792)
- github issue tracking the changes applied to the MDN content (already fixed and pull request linked to the issue): mdn/content#4390

**Comment by rebloor** [comment]
@Rob--W should we also remove the documentation from MDN?

**Comment by Rob--W** [comment]
> @Rob--W should we also remove the documentation from MDN?

Let's start by clearly marking them as deprecated. The advantage of keeping them documented is that people who encounter them in old themes can try to understand what it did in order to know how to update the theme for the latest Firefox.

**Comment by rebloor** [comment]
Thanks @Rob--W we are good then, as they are noted already:
<img width="995" alt="image" src="https://github.com/mdn/browser-compat-data/assets/7352080/8c4c2ded-3df9-494c-b53a-584f90e860bb">
