### ISSUE TITLE
getVideoPlaybackQuality() data for Safari is wrong

### ISSUE THREAD

**Issue by foolip** [mdn/browser-compat-data#22221]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

BCD claims that the `getVideoPlaybackQuality()` method is supported on iOS but the `VideoPlaybackQuality` it returns isn't:
https://developer.mozilla.org/en-US/docs/Web/API/HTMLVideoElement/getVideoPlaybackQuality#browser_compatibility
https://developer.mozilla.org/en-US/docs/Web/API/VideoPlaybackQuality#browser_compatibility

### What did you expect to see?

The `VideoPlaybackQuality` interface needs updating to match test results:
https://mdn-bcd-collector.gooborg.com/tests/api/VideoPlaybackQuality

### Did you test this? If so, how?

https://mdn-bcd-collector.gooborg.com/tests/api/HTMLVideoElement/getVideoPlaybackQuality
https://mdn-bcd-collector.gooborg.com/tests/api/VideoPlaybackQuality

### Do you have anything more you want to share?

While trying to fix this, I found that the data is wrong in other ways. iOS 10 does *not* support this API surface in my testing, so the mirroring of Safari 8 is wrong.

https://github.com/WebKit/WebKit/commit/27dee3c249271155975bc4ac8ab21b1e7d8e00d5 added support for `getVideoPlaybackQuality()` but behind the `MEDIA_SOURCE` compile-time flag. That might suggest they should have the same status on iOS as MSE does, but the `MEDIA_SOURCE` guard was removed here:
https://github.com/WebKit/WebKit/commit/b4c26716c070bb88c5e11809689836841cbd7c49

**Comment by foolip** [comment]
@queengooborg this is sufficiently messy that I'd like to use the collector results, but I see iOS results are only available for the latest iOS release. Do you have a way to run on older iOS manually and make results available?

**Comment by queengooborg** [comment]
I can run the collector on a few older Safari iOS versions if need be, but I'd say that it's out of scope for the time being, since my focus is the STF-funded OWD projects.

**Comment by foolip** [comment]
No worries, I finally found the commit and confirmed with manual testing.
