### ISSUE TITLE
CSS Paint Order - Bug Fixed in Chrome 123

### ISSUE THREAD

**Issue by 5e-Cleric** [mdn/browser-compat-data#22244]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Paint order lists as partially supported due to chromium bug https://issues.chromium.org/issues/41372165, which has been recently fixed, chrome version 123 does not have this bug.

Have not checked yet, but the bug should be fixed in Edge 123 and Opera 107-108 as well.

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

Full support in Chrome 123 and forward.

### Testing

You can check using this demo: https://codesandbox.io/p/sandbox/eager-resonance-nrd0b?file=%2Fsrc%2Findex.js

![image](https://github.com/mdn/browser-compat-data/assets/91662974/498e6ed4-e68e-4c0c-9328-918cdf2fa8f1)
If the bug is fixed in your chrome version, it will look like the left example.

### Bugs, pull requests, or MDN pages

Paint-order: https://developer.mozilla.org/en-US/docs/Web/CSS/paint-order

Chromium bug issue: https://issues.chromium.org/issues/41372165

Fixed by: https://chromium-review.googlesource.com/c/chromium/src/+/5274097

**Comment by queengooborg** [comment]
Fixed in #22205!
