### ISSUE TITLE
api.Window.devicePixelRatio - Does not change with page zoom in Safari (webkit)

### ISSUE THREAD

**Issue by mmoss** [mdn/browser-compat-data#22277]
### What type of issue is this?

Browser bug (a bug with a feature that may impact site compatibility)

### What information was incorrect, unhelpful, or incomplete?

Safari (webkit) does not change the `window.devicePixelRatio` value does not change with [page zoom](https://drafts.csswg.org/cssom-view/#page-zoom).

### What browsers does this problem apply to, if applicable?

Safari

### What did you expect to see?

The `window.devicePixelRatio` should change with [page zoom](https://drafts.csswg.org/cssom-view/#page-zoom) in Safari. The value remains static with page zoom.

### Did you test this? If so, how?

Tested with the [MDN Examples for the `window.devicePixelRatio` API](https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio#examples)

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

* Existing bug in the webkit tracker: https://bugs.webkit.org/show_bug.cgi?id=124862
* W3C CSSOM View Module Speficiation: https://drafts.csswg.org/cssom-view/#dom-window-devicepixelratio
* MDN API Page: https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.Window.devicePixelRatio`
* Report started: 2024-02-21T18:58:18.709Z

</details>

**Comment by steffchep** [comment]
This is a problem when working with @property, as this page here shows: http://stephaniepeters.de/at-prop.html
And it is still happening on Safari
