### ISSUE TITLE
css.properties.display - no compatibility information for run-in

### ISSUE THREAD

**Issue by Akindin** [mdn/browser-compat-data#22288]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

No information about run-in compatibility

### What did you expect to see?

run-in compatibility entry

### Did you test this? If so, how?

No

### Do you have anything more you want to share?

Spec https://drafts.csswg.org/css-display/#typedef-display-outside

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/display

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.display`
* Report started: 2024-02-25T21:24:43.833Z

</details>

**Comment by queengooborg** [comment]
No browser supports the `run-in` display property value.  BCD doesn't include features that aren't supported in any browsers.
