### ISSUE TITLE
css.properties.justify-content - `safe` and `unsafe` keywords for `<overflow-position>` in Safari

### ISSUE THREAD

**Issue by silverwind** [mdn/browser-compat-data#22478]
### What type of issue is this?

Incorrect support data

### What information was incorrect, unhelpful, or incomplete?

The [table](https://developer.mozilla.org/en-US/docs/Web/CSS/justify-content#browser_compatibility) lists `safe and unsafe` [`<overflow-position>`](https://www.w3.org/TR/css-align-3/#typedef-overflow-position) as not supported on the following properties while they actually are:

- `align-content` - [supported](https://webkit.org/css-status/#property-align-content)
- `align-items` - [supported](https://webkit.org/css-status/#property-align-items)
- `align-self` - [supported](https://webkit.org/css-status/#property-align-self)
- `justify-content` - [supported](https://webkit.org/css-status/#property-justify-content)
- `justify-items` - unsupported
- `justify-self` - unsupported

### What browsers does this problem apply to, if applicable?

Safari

### What did you expect to see?

Supported status on above four properties since v17.3 or earlier, exact version unknown.

### Did you test this? If so, how?

https://jsfiddle.net/silverwind/k81wj5b4/ works as expected in Safari 17.3.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

 I searched https://bugs.webkit.org but did not find any relevant closed bug.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/justify-content

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.justify-content`
* Report started: 2024-03-03T19:25:04.507Z

</details>

**Comment by queengooborg** [comment]
It looks like your example has an issue: instead of `safe`, it looks like you typed in `save`.  Could you fix your example and try again?

**Comment by silverwind** [comment]
You are right, here is the updated example: https://jsfiddle.net/silverwind/k81wj5b4/4/

Rendering in Safari 17.3 indicates no support for `justify-content`:

<img width="89" alt="image" src="https://github.com/mdn/browser-compat-data/assets/115237/e15f5887-c8ab-400f-a550-024aff00ea79">

Sorry for the confusion, it looks like the typo made the statement invalid and it reverted to default value of `normal`, which in this example renders the same as `safe center`.

**Comment by silverwind** [comment]
[Here](https://jsfiddle.net/silverwind/k81wj5b4/5/) is another update that makes the difference clear. A supporting browser renders like this:

<img width="147" alt="image" src="https://github.com/mdn/browser-compat-data/assets/115237/ea38b5f5-692b-4d00-a770-bda5e566b281">

Safari renders like this:

<img width="121" alt="image" src="https://github.com/mdn/browser-compat-data/assets/115237/fe7bec74-5b89-4d4f-a256-f1fb8ca79055">
