### ISSUE TITLE
text-align values (left, center and right) mistakenly marked as deprecated and non-standard?

### ISSUE THREAD

**Issue by datvm** [mdn/browser-compat-data#22524]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/text-align

### What information was incorrect, unhelpful, or incomplete?

See also [StackOverflow](https://stackoverflow.com/questions/78102109/is-css-text-align-center-really-deprecated-if-so-whats-the-alternative).

Right now there doesn't seem to be anything indicating the 3 values are deprecated. I think there is a mistake with [this commit change](https://github.com/mdn/content/commit/05a463a3bc1af6e1b1e0d6a273582d954ae00ed0).

### What did you expect to see?

The values `left`, `center` and `right` should not have deprecated and non-standard tags.

### Do you have any supporting links, references, or citations?

https://drafts.csswg.org/css-text/#text-align-property

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/text-align`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/text-align
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/text-align/index.md
* Last commit: https://github.com/mdn/content/commit/05a463a3bc1af6e1b1e0d6a273582d954ae00ed0
* Document last modified: 2024-02-21T08:43:26.000Z

</details>

**Comment by queengooborg** [comment]
Fixed in #22535!
