### ISSUE TITLE
CSSStyleSheet - Not supported on iOS

### ISSUE THREAD

**Issue by maltaesousa** [mdn/browser-compat-data#22563]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Safari on iOS says it supports CSSStyleSheet() constructor but it actually does not.

### What browsers does this problem apply to, if applicable?

Safari

### What did you expect to see?

CSSStyleSheet() working

### Did you test this? If so, how?

Yes, here's a simple example using CSSStyleSheet() constructor:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>CSSStyleSheet test</h1>
    <word-count></word-count>
    <script>
        class WordCount extends HTMLElement {
            constructor() {
                super();
                const shadow = this.attachShadow({ mode: "open" });
                const sheet = new CSSStyleSheet();
                sheet.replaceSync("p { color: red; }");
                shadow.adoptedStyleSheets = [sheet];

                const node = document.createElement("div");
                node.innerHTML = `<p>Hello</p>`;
                shadow.appendChild(node);
            }
        }
        customElements.define("word-count", WordCount);
    </script>
</body>
</html>
```

Demo page for convenience: https://sitn.ne.ch/web/csss/

This works in Firefox, Chrome and Edge (Windows + Mac), not on iOS (either Safari or Chrome)

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://github.com/mdn/browser-compat-data/blob/c7aacd8c2c2238ded8bc467e45e804fef6c8a140/api/CSSStyleSheet.json#L72

**Comment by queengooborg** [comment]
The result looks the same on Chrome and Safari on desktop as it does Safari on iOS. 
 If I had to guess, you may be using an older version of iOS than support was introduced in (16.4).

If you are using iOS 16.4 or greater, please try again with a minimal example (basically, none of the shadow root stuff).  If it's still not working, share screenshots and your iOS version, and we'd be happy to take another look.

**Comment by maltaesousa** [comment]
Oh yes you're right, I was able to make is work on newer iOS. Thanks a lot for your help!
