### ISSUE TITLE
http.headers.Access-Control-Allow-Methods - wildcard support in all modern versions of the listed browsers

### ISSUE THREAD

**Issue by jub0bs** [mdn/browser-compat-data#22588]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

The compatibility table claims that the wildcard isn't supported in the following browsers:

- Safari
- Firefox for Android
- Safari on iOS

However, according to my tests, the wildcard is supported in (at least) the following versions of those browsers:

- Safari 16.6 
- Firefox for Android 123.1.0
- Safari on iOS (exact version unknown, but at least the latest)

I don't know in exactly which versions support for the wildcard in the ACAM header was added, though.

### What browsers does this problem apply to, if applicable?

Firefox, Safari

### What did you expect to see?

Green ticks on the entire row labeled _Wildcard (`*`)_.

### Did you test this? If so, how?

I submitted the form on [this instance of Jake Archibald's CORS playground](https://jakearchibald.com/2021/cors/playground/?prefillForm=1&requestMethod=PUT&requestUseCORS=1&requestSendCredentials=&preflightStatus=204&preflightAllowOrigin=*&preflightAllowCredentials=&preflightAllowMethods=*&preflightAllowHeaders=*&responseStatus=200&responseAllowOrigin=*&responseAllowCredentials=&responseExposeHeaders=*&requestHeaderName=Foo&requestHeaderValue=bar) in the various browsers and inspected the results.

### Do you have anything more you want to share?

Accurate compatibility tables about wildcard support is useful to maintainers of CORS middleware library. For instance, in my own CORS library, because the wildcard is now universally supported in modern browsers, I'm free to remove [a configuration option that catered for older browsers that didn't support the wildcard](https://pkg.go.dev/github.com/jub0bs/fcors/risky#AssumeNoExtendedWildcardSupport).

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Methods

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `http.headers.Access-Control-Allow-Methods`
* Report started: 2024-03-10T15:35:58.921Z

</details>

**Comment by queengooborg** [comment]
This was fixed in #23363 and the newly merged #23463!
