### ISSUE TITLE
http.headers.Access-Control-Expose-Headers - wildcard support in Firefox for Android?

### ISSUE THREAD

**Issue by jub0bs** [mdn/browser-compat-data#22589]
### What type of issue is this?

Incorrect support data: Firefox for Android is said not to support the wildcard in the `Access-Control-Expose-Headers`, but it does

### What information was incorrect, unhelpful, or incomplete?

The compatibility table claims that the wildcard isn't supported in Firefox for Android. However, I was able to confirm that v123.1.0 (at least) supports the wildcard in the `Access-Control-Expose-Headers` header.

### What browsers does this problem apply to, if applicable?

Firefox

### What did you expect to see?

A green tick on the entire row labeled _Wildcard (`*`)_ and the column labeled _Firefox for Android_.

### Did you test this? If so, how?

I deployed a page consisting of the following HTML:

```html
<script>
  const url = 'https://jakearchibald.com/2021/cors/playground/?prefillForm=1&requestMethod=GET&requestUseCORS=1&preflightStatus=204&preflightAllowOrigin=*&responseStatus=200&responseAllowOrigin=*&responseExposeHeaders=*';
  fetch().then(resp => alert(resp.headers.get('content-type')));
</script>
```

I then visited the page in Firefox v123.0.1 on my Android phone, which caused an alert box containing the response's content-type value.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

 - https://github.com/mdn/browser-compat-data/issues/22588
 - https://github.com/mdn/browser-compat-data/issues/22586

### Do you have anything more you want to share?

Accurate compatibility tables about wildcard support is useful to maintainers of CORS middleware library. For instance, in my own CORS library, because the wildcard is now universally supported in modern browsers, I'm free to remove [a configuration option that catered for older browsers that didn't support the wildcard](https://pkg.go.dev/github.com/jub0bs/fcors/risky#AssumeNoExtendedWildcardSupport).

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `http.headers.Access-Control-Expose-Headers`
* Report started: 2024-03-10T16:38:32.022Z

</details>

**Comment by queengooborg** [comment]
This was fixed in #23363!
