### ISSUE TITLE
javascript.builtins.Intl - Misspell timezone 'Europe/Kiev'. It is "Kyiv" not "Kiev".

### ISSUE THREAD

**Issue by commanddotcom** [mdn/browser-compat-data#22622]
### What type of issue is this?

Other

### What information was incorrect, unhelpful, or incomplete?

The title of the timezone is incorrect.

### What did you expect to see?

`Kyiv` not `Kiev`

### Did you test this? If so, how?

Yes. I run `Intl.DateTimeFormat().resolvedOptions().timeZone` in my Chrome browser.

### Do you have anything more you want to share?

Kiev is Russian pronounce for the Ukrainian capital. It was official back in USSR and widely used by Russian now to underline colonial history of Ukraine.

- The Guardian: [How to pronounce and spell ‘Kyiv’, and why it matters](https://www.theguardian.com/world/2022/feb/25/how-to-pronounce-and-spell-kyiv-kiev-ukraine-and-why-it-matters)
- Wikipedia [#KyivNotKiev](https://en.wikipedia.org/wiki/KyivNotKiev)

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `javascript.builtins.Intl`
* Report started: 2024-03-14T07:55:23.599Z

</details>

**Comment by Elchi3** [comment]
Thanks for your issue, it looks like this is a bug in Chromium?
https://bugs.chromium.org/p/v8/issues/detail?id=13360

2022b release of tz code did rename this:
https://mm.icann.org/pipermail/tz-announce/2022-August/000071.html

Maybe chromium hasn't update to the latest version of tz code?

**Comment by queengooborg** [comment]
I'm not finding any entries for specific time zones in BCD, aside from the general IANA time zone names feature.  Is this something we'd want to add to BCD?

**Comment by Josh-Cena** [comment]
No we don't document Intl data changes. We only document changes to the JS API.
