### ISSUE TITLE
javascript.builtins.JSON.parse - add new context parameter of reviver callback and its source property

### ISSUE THREAD

**Issue by myfonj** [mdn/browser-compat-data#22664]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

Docs on host page describe ECMAScript 2020 (ES11) feature and illustrate it with [snippet](https://github.com/mdn/content/blob/1f8083f578e69f849b96c3ba8eadca49b2195ca4/files/en-us/web/javascript/reference/global_objects/json/parse/index.md?plain=1#L73-L82) that works as expected in current V8 but not Firefox (not even Nightly).

It would be nice to have overview there showing where and since when such snippet could work.

### What browsers does this problem apply to, if applicable?

(All of them.)

### What did you expect to see?

new `reviver#context.source` (or similar, I don't know proper notation for callbacks optional argument's property) table row under existing `parse` row, with some green boxes in "Chrome" columns and red boxes in Firefox columns. Maybe some grey boxes for variety.

### Did you test this? If so, how?

```JavaScript
JSON.parse(
 `{"s":"\u0068\u006f","n":1e3}`,
  function(){
   console.log(arguments);
   return arguments[1]
});
```

Logs arguments with three entries twice in Chrome/Edge. Logs arguments only with two entries always in Firefox.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `javascript.builtins.JSON.parse`
* Report started: 2024-03-19T16:30:00.593Z

</details>

**Comment by queengooborg** [comment]
#22642 was opened prior to the opening of this issue, which adds the feature you're referring to!

**Comment by myfonj** [comment]
@queengooborg @hamishwillee no pressure, but is it going to be merged in a foreseeable future?

(I do not know much about issue workflow here, but from the "closed completed" state of this issue I'd expect seeing the fix in production at this point. Is ot more complicated than this?)
