### ISSUE TITLE
css.types.image.gradient.linear-gradient - Firefox linked bug for interpolation space has been closed as "fixed"

### ISSUE THREAD

**Issue by afontenot** [mdn/browser-compat-data#22665]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Firefox support for "Interpolation color space" and "Hue interpolation method" is set to "No" with a link to https://bugzilla.mozilla.org/show_bug.cgi?id=1824041 but this bug was closed as fixed 4 months ago now.

### What browsers does this problem apply to, if applicable?

Firefox

### What did you expect to see?

I think **most likely** this should be changed to https://bugzilla.mozilla.org/show_bug.cgi?id=1861363 if I understand the issue correctly. It's not clear to me from reading the bug reports what is currently expected to work -- see test case.

### Did you test this? If so, how?

Opened the following HTML file in Firefox 123, and also Chromium 122.

```html
<!DOCTYPE html>
<head>
  <style>
    html, body {width: 100%; height: 100%; margin: 0;}
    body {background: linear-gradient(in oklab, blue, red);}
  </style>
  <title>gradient test</title>
</head>
<body>
<div><span>text</span></div>
</body>
</html>
```

Result:

 * Works as expected in Chromium
 * No gradient renders *at all* in Firefox, not even an sRGB blended gradient. Console prints `Error in parsing value for ‘background’.  Declaration dropped.`

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://hg.mozilla.org/mozilla-central/rev/e34ec04eb981

> The patch will parse and make available the interpolation method, but no
rendering changes are made, so all gradients will still render in srgb.

This patch is supposed to be in 116, but maybe it's behind a flag, because my test case above suggests that Firefox is dropping the CSS rule rather than parsing `in oklab` as expected.

See also: https://bugzilla.mozilla.org/show_bug.cgi?id=1852513 (marked fixed as of 121)

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/gradient/linear-gradient

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.types.image.gradient.linear-gradient`
* Report started: 2024-03-19T18:38:05.329Z

</details>

**Comment by flying-sheep** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1861363 is fixed now too

So the data should say it’s supported from the (upcoming) Firefox 127 on.

**Comment by Elchi3** [comment]
Yes, I think so! 👍

**Comment by flying-sheep** [comment]
but on this page, there’s still a bunch of red: https://developer.mozilla.org/en-US/docs/Web/CSS/color-interpolation-method

**Comment by zadeviggers** [comment]
That's my bad, sorry, @flying-sheep! I accidentally only added the support to one gradient type, not all of them. #23246 fixes this.
