### ISSUE TITLE
Release for v5.5.17 failed

### ISSUE THREAD

**Issue by bkardell** [mdn/browser-compat-data#22675]
### What type of issue is this?

Other

### What information was incorrect, unhelpful, or incomplete?

there is missing data.json asset for [5.5.17](https://github.com/mdn/browser-compat-data/releases/tag/v5.5.17)

### What did you expect to see?

a data.json available, like the other releases

### Did you test this? If so, how?

There's not something to test really, it should be in the page and also there should be a non-404 at https://github.com/mdn/browser-compat-data/releases/tag/v5.5.17/data.json 

### Do you have anything more you want to share?

Thank you!

**Comment by queengooborg** [comment]
Thanks for the head's up!  It appears that the [release process failed](https://github.com/mdn/browser-compat-data/actions/runs/8350977571/job/22858471166#step:7:1), so v5.5.17 was never actually released (we consider the release to be complete when it's published to NPM).  I opened #22677 to "unrelease" it (basically just revert the version number), and will be talking to the rest of the MDN team to figure out what happened.

**Comment by queengooborg** [comment]
I've just tried to release another version and it failed again.  Looks like something happened with NPM access.  I've escalated the issue internally and removed any mention of a 5.5.17 release (since it never properly released).  I'm going to close this issue in the meantime, thanks for the report!
