### ISSUE TITLE
css.properties.resize - <Resize is not compatible on firefox but on chrome and brave it works perfectly>

### ISSUE THREAD

**Issue by MaximeWang888** [mdn/browser-compat-data#22672]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

css.properties.resize - <Resize is not compatible on firefox but on chrome and brave it works perfectly>

### What did you expect to see?

css.properties.resize - <Resize is not compatible on firefox but on chrome and brave it works perfectly>

### Did you test this? If so, how?

css.properties.resize - <Resize is not compatible on firefox but on chrome and brave it works perfectly>

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/resize

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.resize`
* Report started: 2024-03-20T13:16:34.269Z

</details>

**Comment by queengooborg** [comment]
I'm closing this issue because the issue template was not properly filled out.  Please be sure to fill out all questions asked properly, instead of just copy-pasting the BCD key for every answer.
