### ISSUE TITLE
html.manifest.screenshots - Missing Chrome compatibility

### ISSUE THREAD

**Issue by RayBB** [mdn/browser-compat-data#22674]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

There is no known data listed for Chrome (only Chrome Android).

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

The version of chrome it was released in.

### Did you test this? If so, how?

No

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

It should list Chrome 108 per [this](https://developer.chrome.com/blog/richer-install-ui-desktop/). I couldn't find it mentioned in the 108 release notes though. The intent to ship says 106 [here](https://chromestatus.com/feature/5206272861798400) but I don't see a note of it in release notes for 106 or 107. Maybe someone that's a bit more experienced with the issue tracker can help lock down what version it came out in.

Also perhaps a note should be added about form_factor that:
"From Chrome 109, only screenshots with the form_factor set to "wide" are displayed on desktop." per [this](https://web.dev/articles/add-manifest#screenshots).

You could also add a note that it is definitely not supported in FF but can be tracked here https://bugs.webkit.org/show_bug.cgi?id=222356 (also related to https://github.com/mozilla/standards-positions/issues/492) 

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Manifest/screenshots

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `html.manifest.screenshots`
* Report started: 2024-03-20T14:56:44.034Z

</details>

**Comment by queengooborg** [comment]
The linked ChromeStatus page now says "no active development", so I think that this is not supported.  I'm going to close this issue accordingly, but happy to reopen if there's additional info or testing that shows it is supported!
