### ISSUE TITLE
api.AbortSignal.any_static - According to the FF124 release notes this is now supported

### ISSUE THREAD

**Issue by blama** [mdn/browser-compat-data#22700]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

According to the FF124 release notes this is now supported. MDN lists it as Preview browser support, which either means MDN does not know v124 has been releases or that the data in MDN is wrong.

### What did you expect to see?

A check-mark like for other browsers

### Did you test this? If so, how?

No

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://www.mozilla.org/en-US/firefox/124.0/releasenotes/

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal/any_static

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.AbortSignal.any_static`
* Report started: 2024-03-25T08:55:30.175Z

</details>

**Comment by hamishwillee** [comment]
@queengooborg The data is correct - shows it is released in 124  https://github.com/mdn/browser-compat-data/blob/main/api/AbortSignal.json#L233. So there is some kind of update lag in MDN.

**Comment by queengooborg** [comment]
BCD releases have been stalled due to an access token issue, so that's probably why!
