### ISSUE TITLE
html.elements.textarea - autocorrect browser compatibility not listed

### ISSUE THREAD

**Issue by nexxai** [mdn/browser-compat-data#22704]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

There is nothing about the `autocorrect` attribute. 

### What did you expect to see?

Information about which browsers support `autocorrect` and which don't

### Did you test this? If so, how?

n/a

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `html.elements.textarea`
* Report started: 2024-03-26T08:24:45.625Z

</details>

**Comment by pepelsbey** [comment]
FYI, the `autocorrect` attribute is now the [part of the HTML spec](https://html.spec.whatwg.org/multipage/interaction.html#autocorrection) and I expect other browsers to start implementing it, too. Or not :) Still worth adding it to BCD, even as Safari-only.

**Comment by hamishwillee** [comment]
I'll look at it as part of https://github.com/mdn/content/issues/35593
