### ISSUE TITLE
javascript.statements.import - imports with `type: "css"` are not included

### ISSUE THREAD

**Issue by jespertheend** [mdn/browser-compat-data#22717]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

`with {type: 'json'}` is listed, but it would be useful to also show support for css imports `with {type: 'css'}`.

### What did you expect to see?

`with {type: 'css'}` which currently only seems to be supported in Chrome

### Did you test this? If so, how?

json-and-css-import-attributes.glitch.me

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://web.dev/articles/css-module-scripts

### Do you have anything more you want to share?

This is related to #22716

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `javascript.statements.import`
* Report started: 2024-03-27T10:11:04.524Z

</details>

**Comment by queengooborg** [comment]
This was fixed in #22821!
