### ISSUE TITLE
http.headers.Permissions-Policy.ambient-light-sensor - Chart says Chrome 88+ supports this directive, but directive does not work

### ISSUE THREAD

**Issue by thngkaiyuan** [mdn/browser-compat-data#22752]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

The [browser compatibility chart for the Permissions-Policy directive `ambient-light-sensor`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Permissions-Policy/ambient-light-sensor#browser_compatibility) claims Chrome 88+ supports the directive, but use of the directive results in an error.

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

I expected not to see any errors with the use of the directive on Chrome v88+ browsers.

### Did you test this? If so, how?

I tested this by navigating to a site that uses the `ambient-light-sensor` directive, and confirming I see "Error with Permissions-Policy header: Unrecognized feature: 'ambient-light-sensor'."

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://developer.mozilla.org/en-US/docs/Web/API/AmbientLightSensor#browser_compatibility

### Do you have anything more you want to share?

![image](https://github.com/mdn/browser-compat-data/assets/10496851/395c4803-27d3-4f1c-92c2-883f226adba6)

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Permissions-Policy/ambient-light-sensor

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `http.headers.Permissions-Policy.ambient-light-sensor`
* Report started: 2024-04-01T16:51:58.865Z

</details>

**Comment by hamishwillee** [comment]
The feature is behind a flag chrome://flags/#enable-generic-sensor-extra-classes

This is enabled by default on Edge, but disabled by default on Chrome. Haven't checked the others. So yes, the data is incorrect, and flag needs to be added for Chrome.

**Comment by hamishwillee** [comment]
The feature is behind a flag chrome://flags/#enable-generic-sensor-extra-classes

This is enabled by default on Edge, but disabled by default on Chrome. Haven't checked the others. So yes, the data is incorrect, and flag needs to be added for Chrome.

**Comment by hamishwillee** [comment]
Thanks. Should be fixed by #22753
