### ISSUE TITLE
http.headers.sec-webSocket-accept - missing BCD

### ISSUE THREAD

**Issue by fwqaaq** [mdn/browser-compat-data#22762]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

See: <https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Sec-WebSocket-Accept>

### What did you expect to see?

There is BCD in the MDN page.

### Did you test this? If so, how?

No

**Comment by bsmth** [comment]
Thanks for reporting, this is fixed in https://github.com/mdn/browser-compat-data/pull/25115
