### ISSUE TITLE
light-dark() CSS function supported by Opera 109, Edge 123 and Safari 17.5 (Beta)

### ISSUE THREAD

**Issue by legendofmi** [mdn/browser-compat-data#22778]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/light-dark

### What specific section or headline is this issue about?

Browser support for light-dark() function

### What information was incorrect, unhelpful, or incomplete?

Browser support is incorrect. The page says light-dark is not supported by Opera 109, Edge 123, and Safari 17.5 (beta) when all support it (support added on Chromium 123).

### What did you expect to see?

light-dark() should show as supported by Opera, Edge, and Safari (beta).

### Do you have any supporting links, references, or citations?

I tested the MDN page on Opera 109 and Edge 123 and both work. I couldn’t test on Safari 17.5 beta, but the support is mentioned on their release notes:
https://developer.apple.com/documentation/safari-release-notes/safari-17_5-release-notes

**Opera 109:**
![image](https://github.com/mdn/content/assets/94787966/5f126acb-465c-4d10-ad26-6e330bbb6f3c)
109.0.5097.38 – 2024-04-02 [blog post](https://blogs.opera.com/desktop/2024/04/opera-109-0-5097-38-stable-update/)
- CHR-9695 Update Chromium on desktop-stable-123-5097 to 123.0.6312.87

**Edge 123:**
<img width="705" alt="image" src="https://github.com/mdn/browser-compat-data/assets/94787966/bb9e9ef6-6ff0-4337-aae7-0a9d2701ef07">

**Safari 17.5 (Beta):** 
I didn’t test it, but it’s on the release notes:
https://developer.apple.com/documentation/safari-release-notes/safari-17_5-release-notes

**Comment by bsmth** [comment]
Thanks for raising this. I've moved it into the BCD repo which is the right place to track this data.

This was introduced here:

- [x] https://github.com/mdn/browser-compat-data/pull/20935

And updated here:

- [x] https://github.com/mdn/browser-compat-data/pull/22128

I think the fix might be to remove the `impl_url` although there might be a display improvement with Opera and Edge mirroring `true` support when there's a version (support=true) in Chrome.

Compat table: https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/light-dark#browser_compatibility

**Comment by legendofmi** [comment]
Thanks! I just realised it’s also supported by Safari 17.5 Beta. I updated the title and the description.

**Comment by bsmth** [comment]
> I think the fix might be to remove the `impl_url` 

This is not the case, the data from mirrored browsers is not updated yet. Here's the light-dark entry:

https://github.com/mdn/browser-compat-data/blob/ba6f18fce411d2a58a55d5bc0b21362a5de00236/css/types/color.json#L801-L839

And even though this was added in 109, Opera (desktop) versions in this repo are listed up to 108:
https://github.com/mdn/browser-compat-data/blob/main/browsers/opera.json#L816

**Comment by legendofmi** [comment]
What about Safari? 17.5 seems to be already there. Is it just missing "version_added" for the light-dark entry?

**Comment by Elchi3** [comment]
Safari 17.5 data is being updated in this PR: https://github.com/mdn/browser-compat-data/pull/22765

**Comment by legendofmi** [comment]
Safari 17.5 and Edge 123 are now showing as supported. The only one missing is Opera 109, but the browser was already added to the list (updated today):
https://github.com/mdn/browser-compat-data/blob/main/browsers/opera.json#L816

I will check again tomorrow and close the ticket if it shows as supported.

**Comment by legendofmi** [comment]
MDN is now showing correctly the light-dark support.
