### ISSUE TITLE
Support of "File" API in Node.js is missing in "Browser compatibility" section

### ISSUE THREAD

**Issue by ZuBB** [mdn/browser-compat-data#22786]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

It looks like `File` API is [supported](https://nodejs.org/api/globals.html#class-file) in Node.js. Would be nice to reflect that in the compatibility table

### What browsers does this problem apply to, if applicable?

Node.js

### What did you expect to see?

A new column in the table in that section that contains data about `File` support in Node

### Did you test this? If so, how?

I come up with next, but not sure if its OK
```
vv@my-precious ~/work/freelance/semantix-sphere/source-code $ node -e 'console.log(typeof File)'
function
vv@my-precious ~/work/freelance/semantix-sphere/source-code $ 
```

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://github.com/nodejs/node/pull/47153

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/File

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.File`
* Report started: 2024-04-06T16:57:24.776Z

</details>

**Comment by Josh-Cena** [comment]
@queengooborg This should be https://github.com/mdn/browser-compat-data/labels/data%3Aapi%20%3Arabbit2%3A
