### ISSUE TITLE
css.types.global_keywords.revert-layer - Revert layer supported in webkit browsers

### ISSUE THREAD

**Issue by Akindin** [mdn/browser-compat-data#22812]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Information about Chrome, Opera and Edge not supporting revert-layer value

### What did you expect to see?

Support version for browsers other than Firefox

### Did you test this? If so, how?

Run second example in corresponding browsers

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/revert-layer

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.types.global_keywords.revert-layer`
* Report started: 2024-04-09T17:22:00.333Z

</details>

**Comment by queengooborg** [comment]
Duplicate of #16336.
