### ISSUE TITLE
Response.Body - body is a readable byte stream `supported` in the Safari and Deno

### ISSUE THREAD

**Issue by fwqaaq** [mdn/browser-compat-data#22831]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

Deno and Safari. Link: <https://developer.mozilla.org/en-US/docs/Web/API/Response/body>

### What did you expect to see?

The version number supported by Deno and Safari

### Did you test this? If so, how?

Deno: <img width="625" alt="image" src="https://github.com/mdn/browser-compat-data/assets/82551626/51608f7e-095b-4dc7-a37c-9622a27d1b49">

Safari: 
<img width="811" alt="image" src="https://github.com/mdn/browser-compat-data/assets/82551626/a1150d98-a09a-41b5-9e60-3506c029feb1">

**Comment by kpietraszko** [comment]
I'm curious why this was closed, and `readable_byte_stream` was not updated. At the same time WebKit's bugzilla doesn't indicate this was implemented https://bugs.webkit.org/show_bug.cgi?id=250549 so I'm surprised it works.

**Comment by fwqaaq** [comment]
@kpietraszko Yeah, in fact, the safari doesn't support it. You can get it a try in Safari.
