### ISSUE TITLE
api.Window.navigator - <Is it compatible with detecting the WeChat browser in China?>

### ISSUE THREAD

**Issue by zethic-imran** [mdn/browser-compat-data#22849]
### What type of issue is this?

Other

### What information was incorrect, unhelpful, or incomplete?

Information is not available for the WeChat browser 

### What did you expect to see?

I want to detect the WeChat browser in Chinathe 

### Did you test this? If so, how?

I am in India. I can not test

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Window/navigator

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.Window.navigator`
* Report started: 2024-04-17T04:54:33.426Z

</details>

**Comment by queengooborg** [comment]
We are not tracking data for WeChat in this project, sorry.
