### ISSUE TITLE
css.types.image.gradient.linear-gradient - interpolation is supported by firefox but flagged

### ISSUE THREAD

**Issue by yukulele** [mdn/browser-compat-data#22853]
### What type of issue is this?

"Firefox" say "gradient interpolation" not supported but flagged

### What information was incorrect, unhelpful, or incomplete?

gradient interpolation is marked as not supported by firefox but Firefox support it (but disabled by `layout.css.gradient-color-interpolation-method.enabled` flag)

### What browsers does this problem apply to, if applicable?

Firefox

### What did you expect to see?

* marked as flag
* replace bug with https://bugzilla.mozilla.org/show_bug.cgi?id=1861363

### Did you test this? If so, how?

* about:config
* enable `layout.css.gradient-color-interpolation-method.enabled`
* go to https://bug1824041.bmoattachments.org/attachment.cgi?id=9324578

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://bugzilla.mozilla.org/show_bug.cgi?id=1861363

### Do you have anything more you want to share?

to be fixed on:
* css.types.image.gradient.linear-gradient 
* css.types.image.gradient.radial-gradient 
* css.types.image.gradient.conical-gradient

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/gradient/linear-gradient

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.types.image.gradient.linear-gradient`
* Report started: 2024-04-17T10:41:12.385Z

</details>

**Comment by queengooborg** [comment]
This was resolved by #23246!
