### ISSUE TITLE
Many values are missing in align-items

### ISSUE THREAD

**Issue by octref** [mdn/browser-compat-data#2291]
https://github.com/mdn/browser-compat-data/blob/master/css/properties/align-items.json
https://developer.mozilla.org/en-US/docs/Web/CSS/align-items

Is it because the other values has been in standard forever and have no support information, so they become omitted?

**Comment by ddbeck** [comment]
The `null` values mean only that support information is missing. If you have a source for more information about a browser's support for a particular feature, you can open a pull request updating those values. Check out the [`CONTRIBUTING.md`](https://github.com/mdn/browser-compat-data/blob/master/CONTRIBUTING.md) file to learn about how to do that. Thank you!
