### ISSUE TITLE
api.HTMLElement.popover - Safari for iOS should be partial support

### ISSUE THREAD

**Issue by lukewarlow** [mdn/browser-compat-data#22927]
### What type of issue is this?

Browser bug (a bug with a feature that may impact site compatibility)

### What information was incorrect, unhelpful, or incomplete?

Currently the popover API is marked as fully supported in iOS Safari.

### What browsers does this problem apply to, if applicable?

Safari

### What did you expect to see?

There's a bug where the light dismiss (tap outside to close) behaviour of popovers doesn't work on iOS Safari. See https://bugs.webkit.org/show_bug.cgi?id=267688

### Did you test this? If so, how?

Yes I've tested this on my iPad running iOS 17.4 using the demo on MDN.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://bugs.webkit.org/show_bug.cgi?id=267688

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Popover_API

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.HTMLElement.popover`
* Report started: 2024-04-23T20:33:38.611Z

</details>

**Comment by callionica** [comment]
I came here to open this bug. Thanks for saving me the trouble. Light dismiss for popover still does not work on Safari in iOS 17.6.1.

**Comment by MattWilcox** [comment]
There do still appear to be iOS Safari specific bugs related to popover:

https://codepen.io/mattwilcoxuk/pen/dPoWQWx
