### ISSUE TITLE
Review CSS property value data with ranges

### ISSUE THREAD

**Issue by foolip** [mdn/browser-compat-data#22931]
There's CSS data with these ranges for CSS property values based on https://github.com/openwebdocs/mdn-bcd-collector where data going back to the original support of the property wasn't available.

We can't use this data in web-features, and https://github.com/mdn/browser-compat-data/pull/22928 sorted out one such case where we had tagged the BCD features without realizing this. Similar ranges remain in many files in css/properties/.

A "burndown list" can be formed from these commands inside css/properties:

```sh
git grep -lF '"≤13.1"' # Safari, 193 matches
git grep -lF '"≤80"' # Chrome, 168 matches
git grep -lF '"≤11"' # IE, 131 matches
git grep -lF '"≤72"' # Firefox, 130 matches
git grep -lF '"≤83"' # Chrome, 28 matches
```

There are also Edge ≤79 ranges, but those are much fewer and probably not of the same origin.

cc @Elchi3 @queengooborg

**Comment by queengooborg** [comment]
At the moment, Open Web Docs' priority is to ensure accuracy for browsers releases in 2020 or later.  While replacing all of the ranges with specific version numbers is a goal we have, it is not a current priority.  In the meantime, for calculating Baseline, I would recommend simply dropping the range denominator when performing version checking.

I'm going to close this as it's a subset of a primary goal we already have for BCD.
