### ISSUE TITLE
css.properties.scrollbar-gutter - no information on both-edges value compatibility

### ISSUE THREAD

**Issue by Akindin** [mdn/browser-compat-data#22942]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

Not all values compatibility presented

### What did you expect to see?

Compatibility for [both-edges](https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-gutter#both-edges) value

### Did you test this? If so, how?

Testing is not applicable to this issue

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-gutter

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.scrollbar-gutter`
* Report started: 2024-04-25T09:57:52.760Z

</details>

**Comment by queengooborg** [comment]
As reported by the mdn-bcd-collector (https://mdn-bcd-collector.gooborg.com/tests/css/properties/scrollbar-gutter/both-edges), no browsers support this value.  We do not include data for features that have no support in any browser, so the lack of data is an indication that it isn't supported.
