### ISSUE TITLE
http.headers.Retry-After - <SUMMARIZE THE PROBLEM>

### ISSUE THREAD

**Issue by Shadownite22** [mdn/browser-compat-data#22954]
### What type of issue is this?

Other

### What information was incorrect, unhelpful, or incomplete?

It says network error on linky

### What did you expect to see?

My chats

### Did you test this? If so, how?

Yes same message of network error 

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

No

### Do you have anything more you want to share?

No

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `http.headers.Retry-After`
* Report started: 2024-04-28T00:04:18.164Z

</details>

**Comment by Shadownite22** [comment]
I'm receiving a network error message on linky app

**Comment by queengooborg** [comment]
This is not the place to report issues with apps or websites.  Please contact the app developers instead.
