### ISSUE TITLE
Link browser bugs for relative color support

### ISSUE THREAD

**Issue by foolip** [mdn/browser-compat-data#22961]
Partial implementation and notes is used for a bunch of the `relative_syntax` entries, from https://github.com/mdn/browser-compat-data/pull/21937.

I've sent https://github.com/mdn/browser-compat-data/pull/22960 for two notes I suspect are wrong. These are the remaining notes that should ideally have a bug link so that it's possible to check if it's resolved or not:

`color()` in Safari:

https://github.com/mdn/browser-compat-data/blob/712e11aa4181a6c92aa552690c93e0354038b705/css/types/color.json#L148-L152

HSL in Chrome and Safari:

https://github.com/mdn/browser-compat-data/blob/712e11aa4181a6c92aa552690c93e0354038b705/css/types/color.json#L401-L405

https://github.com/mdn/browser-compat-data/blob/712e11aa4181a6c92aa552690c93e0354038b705/css/types/color.json#L418-L422

HWB in Chrome and Safari:

https://github.com/mdn/browser-compat-data/blob/712e11aa4181a6c92aa552690c93e0354038b705/css/types/color.json#L543-L547

https://github.com/mdn/browser-compat-data/blob/712e11aa4181a6c92aa552690c93e0354038b705/css/types/color.json#L560-L564

LCH in Safari:

https://github.com/mdn/browser-compat-data/blob/712e11aa4181a6c92aa552690c93e0354038b705/css/types/color.json#L784-L788

Oklch in Safari:

https://github.com/mdn/browser-compat-data/blob/712e11aa4181a6c92aa552690c93e0354038b705/css/types/color.json#L1128-L1132

@romainmenke do you have bug links handy for any of these? Are there any you know to be fixed already?

**Comment by romainmenke** [comment]
For Safari I do not have any bug links.

For Chrome only HSL seems to be still open.
This issue seems relevant : https://issues.chromium.org/issues/41488645

I don't know exactly when this was fixed.

Chrome 124 is still broken, 126 seems fine.

**Comment by woody-li** [comment]
Yeah, it seems fixed in Chrome 125, both HSL and HWB.

**Comment by jamesnw** [comment]
https://github.com/mdn/browser-compat-data/issues/24528 says these are all resolved- do we still need to document the resolved bugs, or can this be closed?
