### ISSUE TITLE
css.properties.white-space - SVG style text white-space: break-spaces is not respected (at least) on Chrome 124

### ISSUE THREAD

**Issue by smurp** [mdn/browser-compat-data#22998]
### What type of issue is this?

Browser bug (a bug with a feature that may impact site compatibility)

### What information was incorrect, unhelpful, or incomplete?

The claim that Chrome supports SVG text {white-space: break-spaces} is wrong for Chrome 124, at least.

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

I expected to see in the result the following text wrapping onto multiple lines.

Here is an English paragraph
that is broken into multiple lines
in the source code so that it can
be more easily read and edited
in a text editor.

### Did you test this? If so, how?

Yes, by looking at it in Chrome and seeing it fail, then checking in Firefox and seeing it work.

![image](https://github.com/mdn/browser-compat-data/assets/774119/8038a60c-8344-4322-bc8d-b965a7fa5f96)

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/white-space

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.white-space`
* Report started: 2024-05-03T15:18:42.225Z

</details>

**Comment by queengooborg** [comment]
BCD has already stated that there is no support for this CSS property on SVG elements in Chrome.
