### ISSUE TITLE
Synchronized console for simultaneous compat evaluation in multiple browsers?

### ISSUE THREAD

**Issue by caugner** [mdn/browser-compat-data#2302]
When gathering compat data, it would be handy to have an "app" that one could connect to with multiple devices/browsers at the same time and evaluate code in all of the devices in real-time.

Is anybody aware of a solution for this or even has experiences to share?

P.S.: I was wondering whether [karma](https://github.com/karma-runner/karma) could be used for this.

**Comment by jwhitlock** [comment]
This sounds like https://github.com/GoogleChromeLabs/confluence. @mdittmer has a project to integrate this with BCD - https://github.com/mdittmer/mdn-confluence

**Comment by Elchi3** [comment]
Yes, this is basically confluence. We're not planning on implementing something like this ourselves at the moment. Closing, but thanks for the idea.
