### ISSUE TITLE
api.Window.documentPictureInPicture - <Need to know if edge supports this>

### ISSUE THREAD

**Issue by venkateshcoolmoon** [mdn/browser-compat-data#23029]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Document picture in picture support not available in edge browser 116

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

Need to know version from which document picture in picture supported on edge

### Did you test this? If so, how?

With script which works on chrome browser and not on edge

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Document_Picture-in-Picture_API

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.Window.documentPictureInPicture`
* Report started: 2024-05-07T18:23:37.425Z

</details>

**Comment by queengooborg** [comment]
The API is very much working since Edge 116 using the demo that's linked on the MDN article.  If you are seeing otherwise, please provide additional details such as screenshots and code examples.
