### ISSUE TITLE
http.headers.X-Content-Type-Options - <SUMMARIZE THE PROBLEM>

### ISSUE THREAD

**Issue by sanjayyadavOcode** [mdn/browser-compat-data#23043]
### What type of issue is this?

Other

### What information was incorrect, unhelpful, or incomplete?

Recewving this error in chrome browser
Refused to execute script from 'https://www-admin.XYZ.com/static/version1715107006/adminhtml/Magento/spectrum/en_US/TikTokShop/ControlPanel.min.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.   

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

ControlPanel.min.js this file should be loaded

### Did you test this? If so, how?

by replicating code to different environment

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `http.headers.X-Content-Type-Options`
* Report started: 2024-05-09T11:24:13.977Z

</details>

**Comment by queengooborg** [comment]
This is not the place to ask for development help.  Please use a dedicated help forum website instead.
