### ISSUE TITLE
counter-reset: list-item - is not fully implemented in Safari WebKit

### ISSUE THREAD

**Issue by glmvc** [mdn/browser-compat-data#23070]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

There is a [bug entry in WebKit](https://bugs.webkit.org/show_bug.cgi?id=260436) stating "`counter-reset: list-item` is not fully implemented".

### What browsers does this problem apply to, if applicable?

Safari (tested in version 17.4)

### What did you expect to see?

A note that `list-item` for the CSS `counter-reset` property is not *fully* implemented in Safari.
https://github.com/mdn/browser-compat-data/blob/8a5bcae99ad4145e534f83d93005daf91984ab95/css/properties/counter-reset.json#L47

### Did you test this? If so, how?

`counter-reset: list-item` seems to work for generated `::marker` content in Safari, but results in incorrect values for content generated with the `counter()` function, for example.

This incorrect behavior can be observed in this CodePen example: https://codepen.io/glmvc/pen/dyLBEgP

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

Related site on MDN where the compat-data is used in the browser compatibility table:
https://developer.mozilla.org/en-US/docs/Web/CSS/counter-reset

**Comment by myfonj** [comment]
Don't have real Safari at hand, but in Playwright's `AppleWebKit/605.1.15` and **even any Chromium-derived browser** on my machine touching `list-item` by either `counter-reset` or `counter-set` does not seem to have any effect at all:

```HTML
data:text/html,
on LI:
<ol>
 <li>Expected: 1.
 <li>Expected: 2.
 <li style="counter-reset: list-item 10;">Expected: 11.
</ol>

on OL:

<ol style="counter-reset: list-item 10;">
 <li>Expected: 11.
 <li>Expected: 12.
 <li>Expected: 13.
</ol>
```
([sandbox](https://myfonj.github.io/sandbox.html#data:text/html,on%20LI%3A%20%3Col%3E%0A%20%3Cli%3EExpected%3A%201.%0A%20%3Cli%3EExpected%3A%202.%0A%20%3Cli%20style%3D%22%0A%20%20counter-reset%3A%20list-item%2010%3B%0A%20%22%3EExpected%3A%2011.%0A%3C%2Fol%3E%0A%0Aon%20OL%3A%0A%0A%3Col%0A%20style%3D%22%0A%20%20counter-reset%3A%20list-item%2010%3B%0A%20%22%3E%0A%20%3Cli%3EExpected%3A%2011.%0A%20%3Cli%3EExpected%3A%2012.%0A%20%3Cli%3EExpected%3A%2013.%0A%3C%2Fol%3E%0A%0A%3Cscript%3E%0Adocument.write(%0A%20navigator.userAgent%0A)%3B%0A%3C%2Fscript%3E))

Anything but Firefox still counts 1 - 2 - 3 in both lists:

![Both list goes 1 - 2 - 3; user agent string contains Chrome/122](https://github.com/mdn/browser-compat-data/assets/1761395/5eba0ebf-d9e4-4667-9257-720ab4967b91)

Correct rendering in Firefox:

![First list is 1 - 2 - 11, second 11 - 12 - 13; user agent string contains Firefox/127](https://github.com/mdn/browser-compat-data/assets/1761395/3562626d-d6f4-4323-8951-f46a016b9792)

**Comment by glmvc** [comment]
@myfonj Thanks for your insights. There seems to be a [bug in Chromium](https://issues.chromium.org/issues/338233131) that affects the `::marker` content. Check following screenshot:
![list-item-counter](https://github.com/mdn/browser-compat-data/assets/95487764/b0738de1-a119-40e2-9519-a8b8dd63e9f9)

Safari on macOS seems to generate the `::marker` content correctly (although Safari has no "real" support to adapt `::marker` content with CSS), but the values of the `counter()` function for content are different compared to Firefox and Chrome:
![list-item-content](https://github.com/mdn/browser-compat-data/assets/95487764/ee56cbdc-0f62-4bd8-877c-5df7604df251)

Here is a [complete example on CodePen](https://codepen.io/glmvc/pen/OJGYZEV) showing different scenarios.
Please note that I use the latest stable browser versions for testing. As of May 2024.

**Comment by myfonj** [comment]
@glmvc these are great demonstrations, and man, what Safari does is wild! My even wilder guess is that they are 1) incrementing the counter precisely on the `::marker` (instead of on the `li`) and 2) in their implementation, `::marker` comes ***after*** `::after`. That's hilarious! XD

Anyway, given all the evidence here, I think it is safe to declare support of `list-item` under `counter-*` stuff in Safari and even Chrome as incomplete.
