### ISSUE TITLE
api.Element.checkVisibility - Missing opacityProperty data

### ISSUE THREAD

**Issue by woody-li** [mdn/browser-compat-data#23086]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

Currently, the checkVisibility data includes `contentVisibilityAuto` and `visibilityProperty` options, `checkOpacity` and `checkVisibilityCSS` aliases options.

But missing `opacityProperty` option.

### What did you expect to see?

Add opacityProperty option compatibility data.

### Did you test this? If so, how?

No

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Element/checkVisibility

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.Element.checkVisibility`
* Report started: 2024-05-14T02:05:51.542Z

</details>

**Comment by queengooborg** [comment]
This was fixed in #23159!
