### ISSUE TITLE
remove spread_in_destructuring from javascript/operators/spread.json

### ISSUE THREAD

**Issue by jcsahnwaldt** [mdn/browser-compat-data#2309]
I think `spread_in_destructuring` should be removed from [javascript/operators/spread.json](https://github.com/mdn/browser-compat-data/blob/master/javascript/operators/spread.json#L115). As far as I can tell, `rest_in_objects` in [javascript/operators/destructuring.json](https://github.com/mdn/browser-compat-data/blob/master/javascript/operators/destructuring.json#L180) describes the same feature and is included on the correct MDN page.

Details:

The [compat table on MDN page "Spread syntax"](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#Browser_compatibility) has a line about "Spread in destructuring" (equivalent to section `spread_in_destructuring` in [javascript/operators/spread.json](https://github.com/mdn/browser-compat-data/blob/master/javascript/operators/spread.json#L115)), but destructuring is hardly mentioned in the text of the page.

I think the feature is described in [section "Rest in Object Destructuring" on page "Destructuring assignment"](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#Rest_in_Object_Destructuring). The [compat table on that page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#Browser_compatibility) has a line about "Rest in objects", which is equivalent to `rest_in_objects` in [javascript/operators/destructuring.json](https://github.com/mdn/browser-compat-data/blob/master/javascript/operators/destructuring.json#L180).

**Comment by ddbeck** [comment]
Fixed by https://github.com/mdn/browser-compat-data/pull/9472.
