### ISSUE TITLE
webextensions.api.management.setEnabled - <support Enabling/Disabling Extensions addons in Firefox>

### ISSUE THREAD

**Issue by leic4u** [mdn/browser-compat-data#23106]
### What type of issue is this?

Other

### What information was incorrect, unhelpful, or incomplete?

Chromium's setEnabled() API allows enabling/disabling extensions. Please support it in firefox.

### What browsers does this problem apply to, if applicable?

Firefox

### What did you expect to see?

A extension is allowed enabling/disabling the other extensions.

### Did you test this? If so, how?

https://github.com/JasonGrass/auto-extension-manager/issues/5

### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/management/setEnabled

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `webextensions.api.management.setEnabled`
* Report started: 2024-05-16T09:01:26.849Z

</details>

**Comment by queengooborg** [comment]
It sounds like you're trying to request feature implementation in Firefox, not reporting an issue with the compatibility data BCD reports.  Please file a bug with the Firefox team instead at https://bugzil.la.
