### ISSUE TITLE
http.headers.Reporting-Endpoints - Missing

### ISSUE THREAD

**Issue by voxpelli** [mdn/browser-compat-data#23136]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

When I was looking at https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Reporting-Endpoints I noticed it couldn't find any browser compat data and I verified it is indeed missing in this repository.

It is defined by this spec: https://www.w3.org/TR/reporting-1/#header

### What did you expect to see?

I expected to see compatibility data and to have that data mention the spec: https://www.w3.org/TR/reporting-1/#header

### Did you test this? If so, how?

I looked in the `http/headers/` folder and found no `Reporting-Endpoints` file

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

* MDN-page: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Reporting-Endpoints
* MDN-page source: https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/reporting-endpoints/index.md
* Spec for header: https://www.w3.org/TR/reporting-1/#header
* GitHub repo: https://github.com/w3c/reporting
* Explainer: https://github.com/w3c/reporting/blob/main/EXPLAINER.md#enabling-reporting

**Comment by skyclouds2001** [comment]
Maybe whether any of the browser has support this feature need additional check

**Comment by voxpelli** [comment]
Chrome is shipping it: https://developer.chrome.com/docs/capabilities/web-apis/reporting-api

**Comment by skyclouds2001** [comment]
> Chrome is shipping it: https://developer.chrome.com/docs/capabilities/web-apis/reporting-api

Thanks.

I did more research and notice this feature is behide a flag, see:

https://issues.chromium.org/issues/40122847
https://issues.chromium.org/issues/40122847

**Comment by queengooborg** [comment]
This has been added in #24047!
