### ISSUE TITLE
api.MediaRecorder.isTypeSupported_static - MediaRecorder.isTypeSupported wrongfully states true

### ISSUE THREAD

**Issue by KO81** [mdn/browser-compat-data#23174]
### What type of issue is this?

Other

### What information was incorrect, unhelpful, or incomplete?

MediaRecorder.isTypeSupported("video/webm;codecs=opus") states true in 126.0 (64-bit) but it isn't

### What browsers does this problem apply to, if applicable?

Firefox

### What did you expect to see?

MediaRecorder.isTypeSupported actually returns a statement, which is true.

### Did you test this? If so, how?

`x=['webm','ogg','mp4','x-matroska','3gpp','3gpp2','3gp2','quicktime','mpeg','aac','flac','wav'],y=['vp9','vp8','avc1','av1','h265','h.265','h264','h.264','opus','pcm','aac','mpeg','mp4a'],z={capture:false,passive:true,once:false};init();a=[];
for(d of ['video','audio']){let e0,e1,e2,e3=_('t');
	for(e0 of x){
		for(e1 of y){e2=d+'/'+e0+';codecs='+e1;
			if(MediaRecorder.isTypeSupported(e2)&&!a.includes(e2)&&d=='video'){a.push(e2)
			}if(a.length==2){i(e3,e0+';codecs='+e1);e3.dataset.array=a[0].split('/')[1]+','+a[1].split('/')[1]
			}
		}
	}
}`

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

[https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder/isTypeSupported_static](url)

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder/isTypeSupported_static

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.MediaRecorder.isTypeSupported_static`
* Report started: 2024-05-26T07:41:32.871Z

</details>

**Comment by skyclouds2001** [comment]
I think this is too detail to mention in BCD project

**Comment by queengooborg** [comment]
I'm closing this issue for the following reasons:
- The example provided is invalid, as:
  - It is not runnable
  - It does not highlight how the video format doesn't work despite reporting it does
- BCD does not record information about what codecs/formats are supported in browsers
- And, most importantly, I did test a WebM file with Opus audio, and it's completely functional!
