### ISSUE TITLE
Browser Compatibility Table use wrong Firefox logo

### ISSUE THREAD

**Issue by FormularSumo** [mdn/browser-compat-data#23175]
### What type of issue is this?

Other

### What information was incorrect, unhelpful, or incomplete?

The logo used next to Firefox and Firefox for Android is the general Firefox brand logo, rather than the logo for the Firefox browser.

More context:
![FX_Design_Blog_Logos_Family](https://github.com/MicrosoftEdge/MSEdgeExplainers/assets/36278229/10d83e56-0f0e-4c5b-9d5b-70a8155cd90f)
https://blog.mozilla.org/opendesign/firefox-the-evolution-of-a-brand/

This is an example of the logo that I think should be used instead:
![firefox-browser](https://github.com/MicrosoftEdge/MSEdgeExplainers/assets/36278229/3920dee4-a582-43e0-baa3-15b6b58a0575)

Whereas this is the current one:
![firefox](https://github.com/mdn/browser-compat-data/assets/36278229/69baf2ab-a563-4fb1-82c4-85626d9d83b9)
For example:
![image](https://github.com/mdn/browser-compat-data/assets/36278229/22afdc84-9004-4c8c-b240-76b44ac72d63)

### What browsers does this problem apply to, if applicable?

Firefox

### What did you expect to see?

Firefox browser logo used

### Did you test this? If so, how?

Visit an MDN page with a Browser compatibility table, eg https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API#browser_compatibility

**Comment by queengooborg** [comment]
Rendering of BCD on MDN Web Docs is not handled in this repository.  This would be an issue to report to GitHub.com/mdn/yari.
