### ISSUE TITLE
api.Sanitizer - Chrome support data error

### ISSUE THREAD

**Issue by 22jcampb** [mdn/browser-compat-data#23186]
The compatibility table states Chrome does not support the Sanitizer API. Chrome does support the Sanitizer API as of Chrome version `125.0.6422.112` on platforms `Mac, Windows, Linux, ChromeOS, Android, Fuchsia, Lacros` with the #sanitizer-api flag.

**Comment by hamishwillee** [comment]
@Elchi3 @queengooborg Can we make an exception to normal rules and purge the old santizer data entirely - then restart?

The data is correct, but unhelpful. The old API was released "prematurely" - because the new and old API share some API names this can really only confuse people. They point to documentation of the old API too, which I would also like to delete.

Thoughts?

**Comment by Elchi3** [comment]
I haven't looked into the Sanitizer API in details but seems reasonable to do that do avoid confusion.
Looks like it was removed in Chromium in September 2022, so *almost* two years ago. 
CC'ing another BCD owner for opinions: @foolip.

**Comment by foolip** [comment]
I'd be happy to make an exception for `Sanitizer`, or even change the guideline to 1 year.

**Comment by hamishwillee** [comment]
Thanks @foolip 

OK, @22jcampb can you point me to "evidence" of the addition in version 125.0.6422.112 and what exactly was added - i.e. is it a precise implementation that fully reflects the current spec, or something else? Does it support all the configuration options (or will it) and so on. I can't find anything on "new work" in chromestatus.

That affects how we might do this work (not so much this data, but corresponding changes in MDN content).

**Comment by 22jcampb** [comment]
> Thanks @foolip 
> 
> OK, @22jcampb can you point me to "evidence" of the addition in version 125.0.6422.112 and what exactly was added - i.e. is it a precise implementation that fully reflects the current spec, or something else? Does it support all the configuration options (or will it) and so on. I can't find anything on "new work" in chromestatus.
> 
> That affects how we might do this work (not so much this data, but corresponding changes in MDN content).
> 
> 

![Screenshot_20240610-211655.png](https://github.com/mdn/browser-compat-data/assets/85803754/5be14ab9-ac4d-4639-a475-69691e439d3b)

This is all it says, the flag "enables the Sanitizer API" and links to the GitHub page. No specific details on implementation.

**Comment by queengooborg** [comment]
The data for the Sanitizer API had been completely removed in #23989, so I'd say that this issue can be closed!
