### ISSUE TITLE
css.properties.translate - seems to be wrong. AFAIK it's not implemented in chrome yet, for example (might not be implement in other browsers too)

### ISSUE THREAD

**Issue by alonemanuel** [mdn/browser-compat-data#23194]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

seems to be wrong. AFAIK it's not implemented in chrome yet, for example (might not be implement in other browsers too)

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

That it's unsupported

### Did you test this? If so, how?

Yes, on the latest chrome

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/translate

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.translate`
* Report started: 2024-05-28T12:13:11.710Z

</details>

**Comment by queengooborg** [comment]
This property is _definitely_ supported in Chrome.  Closing as there is not enough actionable information.
