### ISSUE TITLE
html.elements.script.type.speculationrules - Not working on Android WebView 

### ISSUE THREAD

**Issue by senthil5053** [mdn/browser-compat-data#23213]
### What type of issue is this?

Other

### What information was incorrect, unhelpful, or incomplete?

Speculation rules is not working android Webview version: 125.0.6422.54. 

However the same speculation rules on the same website works fine on the chrome browser (Version: 125.0.6422.112) in the same android device (Samsung S23 running Android 14)

### What did you expect to see?

I expect to see the speculation rules working on android webview (v 125.0.6422.54.)

### Did you test this? If so, how?

Also checked the speculation Rules API prerendering demo page https://prerender-demos.glitch.me/ (as mentioned in https://developer.chrome.com/docs/web-platform/prerender-pages?utm_source=devtools ) and observed the same behavior where the speculation rules were successful on Android Chrome browser and failure on Android WebView. Yes, tested this with internal website.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script/type/speculationrules

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `html.elements.script.type.speculationrules`
* Report started: 2024-05-30T14:37:50.962Z

</details>

**Comment by skyclouds2001** [comment]
can be confired from https://chromestatus.com/features#speculation%20rules

**Comment by senthil5053** [comment]
@skyclouds2001  thanks for the info. I don't see anything related to android WebView in there. Looks like this speculation rules API were never supported on android WebView.  Do you happen to know if this speculation rules API work on android WebView ?
