### ISSUE TITLE
Confusing historical support badge appearance in notes

### ISSUE THREAD

**Issue by myfonj** [mdn/browser-compat-data#2321]
(This was probably discussed in the past, but I couldn't find it in issues.)

The `version_added .. version_removed` badge in the Notes pane has same appearance as "Not supported" in the Summary pane, although in given context has opposite message:

[![SVG/Element/font](https://user-images.githubusercontent.com/1761395/41467372-953d9aaa-70a6-11e8-9174-2e497dff2a11.png)](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/font)

Considering the "Chrome" column, 

https://github.com/mdn/browser-compat-data/blob/97da40b0ba9197d069274859f1272ead7dea76ca/svg/elements/font.json#L12-L22

- `4-38` tells that it was supported in that range (so one would probably expect green colour)
- `38-51` tells that support was somewhat limited (IDK what would be proper appearance here, but red seems inappropriate here as well)

Also, first row should better display **whole support range** (sum of adjacent, i.e. `4-51`) but perhaps it should have been in the JSON in the first place (?)(producing overlapping ranges `4-51` + `38-51 with note`? Or `partial_implementation` should be there?).

**Comment by connorshea** [comment]
If it was removed that means current versions of chrome don’t support it, which is why the cell background is red. I agree that it’s kind of confusing, but I’d say this is correct.

**Comment by myfonj** [comment]
Sure, it really makes sense for the first overview line, but what should observer think about such view, where legend clearly states "No support":
![image](https://user-images.githubusercontent.com/1761395/41502813-02a2802a-71c3-11e8-8442-fc731cf84ea4.png)

**Comment by connorshea** [comment]
Hmm, in that case I suppose it should probably be listed as partial support.

**Comment by vinyldarkscratch** [comment]
I think you're right in that `partial_implementation` should be noted, especially if it's limited to specific operating systems.  However, the red background for "no support" is accurate in this case.  I think it's less the color, and possibly more of the footnote.  More accurately, the red background refers to "No support in current browser version".

That being said, that compatibility data looks...weird.  Between versions 4 through 38, was it supported on all platforms, and then that support was just dropped in 38?  That might need a little more review.

**Comment by vinyldarkscratch** [comment]
I'm deciding to close this issue since it's both stale and primarily based upon a misinterpretation of the data.  If this is something that others believe is essential to fix, I'm happy to re-open this!

**Comment by myfonj** [comment]
>  More accurately, the red background [of the footnote badge about past feature support] refers to "No support in current browser version".

Adhering to this logic, shouldn't be _future_ versions in any context painted red as well?

(They are not, "current" browser version for Firefox browser is 66, here is 68 (current Nightly) painted green :)
https://developer.mozilla.org/en-US/docs/Web/CSS/::marker#Browser_compatibility
![image](https://user-images.githubusercontent.com/1761395/56871363-ec717d80-6a1c-11e9-9263-875b7f4128aa.png).

I'm OK with closing this issue, after all, it is perhaps the most marginal scenario in compat data, but, you know, that semantic itch… In feature in question, this feature is currently obsolete and mostly unsupported, but in the past it was (more or less) standardized and even supported, what is properly recorder in JSON and communicated in text after all. But FMOPW color really contradicts what text and data tell.

**Comment by ddbeck** [comment]
@myfonj thanks for raising this issue. I think the right place for issues to do with the style and appearance of compat tables is https://github.com/mdn/kumascript (at least I'm pretty sure — @Elchi3 might correct me). It looks like the underlying data is correct (or at least reasonable), which is our main focus on this repo.

The question of coloration for future versions probably also belongs there. I think the issue with the table is that it uses the term "current" which is a bit ambiguous. It's probably more accurate to say something like "the most recent nightly, beta, or stable release for which we have data", but that's a bit of a mouthful. To learn more about how we use browser data in this repo, you might want to check out the `/browsers/` and `/schemas/` directories.
