### ISSUE TITLE
WebKit nightly and Safari Tech Preview

### ISSUE THREAD

**Issue by yoavweiss** [mdn/browser-compat-data#23217]
### What would you like to see added to BCD?

It seems like there's no current way to update BCD regarding featuers that are available in WebKit Nightly as well as features that are available in a particular Safari Tech Preview release.
It'd be good to add those.

### How impactful do you think this enhancement will be?

It would enable BCD to reflect the status of features available in e.g. WebKit GTK, or are available for testing in a Safari Tech Preview release.

**Comment by queengooborg** [comment]
We actually do have a way to indicate Safari TP release support!  The BCD schema includes the ability to specify `"preview"` as the version number, which indicates a beta, nightly or other prerelease version of a browser.  I've updated the docs in #23495 to better represent this!
