### ISSUE TITLE
ESM and javascript.statements.import - baseline "limited availability"?

### ISSUE THREAD

**Issue by lionel-rowe** [mdn/browser-compat-data#23231]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Surely it would be correct to say the core features of ESM are now _widely available_?

Articles for [Modules](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules) and [import](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import) both claim "limited availability", but the article for [export](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export) has "widely available".

I guess it's something to do with support for typed imports using `with` and the legacy `assert`, but I don't think those are what people would understand by "support for modules" "support for `import`".

Relevant:

https://github.com/mdn/browser-compat-data/blob/55e4274fe41fefad611050b2c183526879a38a22/javascript/statements.json#L1216-L1222

And

https://github.com/web-platform-dx/web-features/blob/d3d6f97b7d32b289cbfb87134251e12fb963a54e/features/js-modules.yml#L12-L20

All the features cited in web-platform-dx `js-modules.yml` are widely supported, so I'm not sure that's where the problem lies.

### What did you expect to see?

Widely available

### Did you test this? If so, how?

N/A

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `javascript.statements.import`
* Report started: 2024-06-03T01:30:45.843Z

</details>

**Comment by queengooborg** [comment]
Please see https://github.com/web-platform-dx/web-features to report Baseline-related issues.  Baseline is not tracked here in BCD.
