### ISSUE TITLE
Compatibility tables just say "Yes" - What versions?

### ISSUE THREAD

**Issue by csbrown** [mdn/browser-compat-data#23256]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

Some compatibility tables just say "Yes" and do not include a version number.  There is not additional info explaining what "Yes" means.  Presumably, HTTP Range requests are not supported on Chrome version 1.0 from 2008.  What does "Yes" mean?

### What did you expect to see?

A version number, or at least some explanation of what "Yes" means.

### Did you test this? If so, how?

no

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Range

**Comment by queengooborg** [comment]
"Yes" means that the feature has been supported in some version of the browser, we just don't know which version.  We're working on replacing all uncertainties in the data with proper version numbers!

**Comment by csbrown** [comment]
Would it be possible to change this issue to "document the meaning of 'Yes'" somewhere"?  I witnessed first-hand as an entire team of experienced web developers misunderstood the compatibility table on [this page](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Range).  Some were like "oh, we need FF 117 to do Range requests".  Literally nobody took "Yes" to mean "It will probably work in recent versions of the browser, but the team at Mozilla isn't quite sure".

**Comment by queengooborg** [comment]
We have it documented in the schema docs for those who are using/modifying the JSON data directly: https://github.com/mdn/browser-compat-data/blob/main/schemas/compat-data-schema.md#version_added

In regards to updating how it's displayed on MDN Web Docs pages, I'd recommend opening an issue on the repository that handles rendering MDN pages, including the BCD tables (this repository only handles the data, not how it's rendered): https://github.com/mdn/yari

(Ultimately, "Yes" will vanish entirely once we have accomplished our goal of researching the version numbers!)

**Comment by csbrown** [comment]
@queengooborg one last question: Suppose that I happen to know which version support for a feature was added, and I would like to submit this information to MDN for inclusion in a compatibility table.  How would I go about that?

**Comment by queengooborg** [comment]
If you happen to know a version that the feature was added, we would love for you to submit a pull request to update the data accordingly!  Our [contributing](https://github.com/mdn/browser-compat-data/blob/main/docs/contributing.md) guide includes most of the information needed to contribute to the project!
