### ISSUE TITLE
`externally_connectable` is missing from `manifest.json`

### ISSUE THREAD

**Issue by abitrolly** [mdn/browser-compat-data#2326]
https://developer.chrome.com/extensions/manifest/externally_connectable - Firefox complains if this property is present in manifest.json file.

**Comment by abitrolly** [comment]
Related https://discourse.mozilla.org/t/send-a-message-from-my-website-to-my-extension-background-page/22361

**Comment by caugner** [comment]
Neither [MDN](https://developer.mozilla.org/search?q=externally_connectable) nor [browser-compat-data](https://github.com/mdn/browser-compat-data/search?q=externally_connectable) currently have any information about the `externally_connectable`.

Would you like to add this information to `browser-compat-data`?

**Comment by abitrolly** [comment]
@caugner sent PR #2329.
