### ISSUE TITLE
Status information: add specifications with version that added/removed a feature

### ISSUE THREAD

**Issue by caugner** [mdn/browser-compat-data#2327]
### Background

Status information [currently contain three mandatory properties](https://github.com/mdn/browser-compat-data/blob/master/schemas/compat-data-schema.md#status-information):

```json
"__compat": {
  "status": {
    "experimental": true,
    "standard_track": true,
    "deprecated": false
  }
}
```

### Problem

There is currently no way to add additional information about the status, let alone about the standard that defined a feature or which version of the standard added or removed it.

I have had two specific cases where I would have liked to add additional status information:

* #2233 – `HTMLKeygenElement` was removed in HTML 5.2.
* #2263 – `<unknown>` is currently part of SVG 2 draft, but is likely to be removed in the final version.

In general, this data is currently stored in the *Specifications* section of MDN articles.

### Proposal

I propose to support additional status information by extending the schema with at least one of these two properties:

1. A `notes` property for additional status information as a `string` or an `array` of zero or more `string`s. 
2. A `specifications` property for information about the specification(s) that define the feature, as a `specification_statement` or an `array` of zero or more `specification_statement`s with the following properties:
(i) `track` – the identifier of the `standard_track` which defines the feature,
(ii) `version_added` – the version of the specification that added the feature,
(iii) `version_removed` – the version of the specification that removed the feature,
(iv) `notes` – additional information about the specification w.r.t. the feature.

For the `notes` property I see use cases like these:

* Describe why a feature is `experimental` or what this depends on.
* Describe why a feature is not in any `standard_track` but still implemented.
* Describe why a feature is `deprecated` or still implemented despite its deprecation.

**Comment by Elchi3** [comment]
Thanks for your idea! We're currently not planning to dig deeper into this proposal.
