### ISSUE TITLE
Custom exports for custom aggregation tables

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#233]
I'm wondering if we should add custom exports in addition to the exports by feature identifiers. 
Right now, we are exporting e.g "api.WebGLRenderingContext" and we are getting back the whole interface's compat data. This works in most cases, also for css, http and webextensions.

Sometimes, there are use cases for custom aggregates, though. Like, for example, all WebGL extensions: https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Using_Extensions#Browser_compatibility
This table is still static and would consist of "api.ANGLE_instanced_arrays", "api.EXT_blend_minmax" and 26 more interfaces, which I can't display like this using the {{compat}} macro at the moment.

I think an additional export like "custom.webgl-extensions" (or similar) that would load all these interfaces would be useful.

Other ideas on how to deal with custom aggregate tables?

**Comment by wbamberg** [comment]
I think we're definitely going to want some way to group things if we're to be able to build interesting aggregate tables. Also for example think of a table showing compat status for all Grid properties.

But this doesn't seem like compat data, it seems like general metadata, so it might be better to represent it in mdn/data. This data might have other uses than compat tables - for example, a page might want to use it to build a sidebar, or even to build the page's main content.

(For example, a Grid landing page could use mdn/data to get the set of Grid properties, use that to build a sidebar and its content, and also use that data to index into the compat data, to build an aggregate table.)

Does that make sense?
