### ISSUE TITLE
Non-informative messages about JSON errors

### ISSUE THREAD

**Issue by abitrolly** [mdn/browser-compat-data#2330]
I left trailing comma in https://github.com/mdn/browser-compat-data/pull/2329/commits/9acd41646c210dc0598fd2ed8d6a5d9d99851e2d but Travis reported something weird
https://travis-ci.org/mdn/browser-compat-data/builds/393218140#L827

Can linter be replaced with something more user friendly? If I didn't knew about trailing commas problem in JSON, I could probably spend an hour trying to hunt it down.

**Comment by ExE-Boss** [comment]
This is likely related to #2143.
