### ISSUE TITLE
webextensions.api.scripting.ExecutionWorld - Firefox Nightly (128) now supports MAIN

### ISSUE THREAD

**Issue by danielhjacobs** [mdn/browser-compat-data#23325]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Support for MAIN on Firefox did not mention version 128 supporting it.

### What browsers does this problem apply to, if applicable?

Firefox

### What did you expect to see?

Firefox Nightly (128) now supports MAIN.

### Did you test this? If so, how?

Use an ExecutionWorld MAIN script of Firefox Nightly and it worked.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://bugzilla.mozilla.org/show_bug.cgi?id=1736575

Still marked as dev-doc-needed

### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/scripting/ExecutionWorld

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `webextensions.api.scripting.ExecutionWorld`
* Report started: 2024-06-10T18:30:35.508Z

</details>

**Comment by danielhjacobs** [comment]
See also https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/scripting/executeScript#browser_compatibility

**Comment by rebloor** [comment]
I'm closing to avoid duplication as the dev-doc-needed flag on https://bugzilla.mozilla.org/show_bug.cgi?id=1736575 is sufficient.
