### ISSUE TITLE
html.global_attributes.autocomplete - FF supported version for one-time-code

### ISSUE THREAD

**Issue by rrehbein** [mdn/browser-compat-data#23347]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Firefox is listed as not supporting `autocomplete="one-time-code"` however appears to have had support added in version 109.

### What browsers does this problem apply to, if applicable?

Firefox

### What did you expect to see?

Since version 109

### Did you test this? If so, how?

Verified autofill did not happen on FireFox v126 when the autocomplete was set to one-time-code.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

Bug report / feature request to add one-time-code to firefox:

https://bugzilla.mozilla.org/show_bug.cgi?id=1547294

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `html.global_attributes.autocomplete`
* Report started: 2024-06-11T14:25:10.709Z

</details>

**Comment by Elchi3** [comment]
Thank you, fixed in https://github.com/mdn/browser-compat-data/pull/21929
