### ISSUE TITLE
css.properties.image-rendering - Chrome does not support `crisp-edges` 

### ISSUE THREAD

**Issue by xnuk** [mdn/browser-compat-data#23385]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

`image-rendering: crisp-edges` is not supported in Chromium-based browsers (since at least 41+, I guess from the Chrome dev blog)

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

Switch `crisp-edges` support of Chrome to "No"

### Did you test this? If so, how?

Type
```
data:text/html,<style>@supports(image-rendering:crisp-edges){body{background:red}}</style>
```
in the URL bar. Chromium-based browsers does not show a red background. (Confirmed in Chromium 125.0.6422.60)

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

- https://caniuse.com/css-crisp-edges
- https://developer.chrome.com/blog/pixelated
  - "Chrome 41 (Beta in January 2015) introduces a new CSS property image-rendering: pixelated (Spec) that gives you a little more control over how the browser renders a scaled up image."
- "Support the new image-rendering CSS properties (crisp-edges)" in Chromium issue tracker, still opened https://issues.chromium.org/issues/41073066
- Maybe related: #22161

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/image-rendering

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.image-rendering`
* Report started: 2024-06-14T16:52:23.731Z

</details>

**Comment by queengooborg** [comment]
Our data says that the property is implemented under a different name, `-webkit-optimize-contrast`.  You'll need to use that as the value, not `crisp-edges`.
