### ISSUE TITLE
Speech Recognition not working In Edge browser,Speech is not recognizing (only using intranet office network)

### ISSUE THREAD

**Issue by Saravana5** [mdn/browser-compat-data#23383]
### What type of issue is this?

Infrastructure issue

### What is the issue?

![Capturecolor](https://github.com/mdn/browser-compat-data/assets/49557943/2cafe193-91e5-47ef-a661-db4166e9c65d)
Network
Issue while connecting to intranet network, it works fine in personal network
Even in intranet network(office network) it was working as expected in chrome, only issue in edge browser It is not working in edge browser while connecting to a VPN or connecting to office internet

### What behavior were you expecting?

It needs to work in edge browser while connecting vpn or office network

### What version(s) of BCD is the issue present in?

- [x] The current BCD release
- [X] The current version of the `main` branch

### Do you have anything more you want to share?

private startListening = () => {
        // const SpeechRecognition = SpeechRecognition || webkitSpeechRecognition
        if (window.SpeechRecognition || window.webkitSpeechRecognition) {
            this.recognition = new (window.SpeechRecognition || window.webkitSpeechRecognition)();
            this.recognition.continuous = false;
            this.recognition.interimResults = false;
            this.recognition.lang = 'en-US';
            this.recognition.onresult = (event) => {
                const transcript = event.results[0][0].transcript;
                this.setState({ searchInputValue: transcript });
                console.log(transcript);
                // this._updateQuerySuggestions(transcript);
                this.setState({ listening: false })
            };

            this.recognition.onerror = (event) => {
                this.setState({ listening: false })
                console.error("speecherror detected" + event.error)
            }

        };
        this.recognition.onend = () => {
            this.setState({ listening: false })
        }

        if (this.recognition) {
            this.recognition.start();
            this.setState({ listening: true })
        }
    }

This is the Actual code

**Comment by queengooborg** [comment]
This is not a BCD issue.  We are not able to help with troubleshooting.
