### ISSUE TITLE
html.elements.embed - Embed on Edge triggers download

### ISSUE THREAD

**Issue by binber18** [mdn/browser-compat-data#23415]
### What type of issue is this?

Browser bug (a bug with a feature that may impact site compatibility)

### What information was incorrect, unhelpful, or incomplete?

When you embed a pdf on edge with the embed tag it triggers a download of that file and the file does not show on the page

### What did you expect to see?

An embedded PDF like on safari

### Did you test this? If so, how?

Embedding a pdf file on an html page

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/embed

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `html.elements.embed`
* Report started: 2024-06-17T13:58:15.754Z

</details>

**Comment by queengooborg** [comment]
I am not able to confirm this issue.  I added a simple embed to a test page -- `<embed type="application/pdf" src="/static/test.pdf" width="600px" height="800px" />` -- and it displayed as embedded as expected.

Could you provide details about your environment?  In particular, the following would be helpful:
- Operating System
- Browser Version
- Test Code Used
