### ISSUE TITLE
Some problems with the TextMetrics API

### ISSUE THREAD

**Issue by connorshea** [mdn/browser-compat-data#2345]
The [TextMetrics API](https://developer.mozilla.org/en-US/docs/Web/API/TextMetrics) has a subfeature called `Advanced text metrics properties`:

https://github.com/mdn/browser-compat-data/blob/019938c3984a4ff8b3f0bdf22ab85079eb40168c/api/TextMetrics.json#L104-L161

This was introduced in #894 as a subfeature that would cover implementation of all of these subfeatures: `actualBoundingBoxLeft, actualBoundingBoxRight, fontBoundingBoxAscent, fontBoundingBoxDescent, actualBoundingBoxAscent, actualBoundingBoxDescent, emHeightAscent, emHeightDescent, hangingBaseline, alphabeticBaseline, ideographicBaseline`

Should each of these subfeatures be tracked separately? In [the MDN article](https://developer.mozilla.org/en-US/docs/Web/API/TextMetrics) they're listed as separate properties, albeit without actual articles.

**Comment by Elchi3** [comment]
Yeah, in order to have the data machine-readable, we should split this out. Should be a good first bug.
