### ISSUE TITLE
api.FileSystemSyncAccessHandle.write - Write success but data is empty

### ISSUE THREAD

**Issue by linhttbk97** [mdn/browser-compat-data#23459]
### What type of issue is this?

Other

### What information was incorrect, unhelpful, or incomplete?

I use "write" file api on safari 16.1 ( macos 13.0.1) to write simple 10 bytes of data with OPFS. 
The write function return result as success but then I read that file again, my data is gone. 
here is the code: 

```js
const isOPFSPersistenceSupported = async () => {
  try {
    const storage = await navigator.storage.getDirectory();
    const fileHandle = await storage.getFileHandle(`test.db`, { create: true });
    const sampleData = new ArrayBuffer(1000);
    const writable = await fileHandle.createSyncAccessHandle();
    writable.flush();
    writable.close();
    const readable = await fileHandle.createSyncAccessHandle();
    const dataFromPreviousTest = await readable.getSize();
    return dataFromPreviousTest === sampleData.byteLength;
  } catch (error) {
    return false;
  }
};
```

### What browsers does this problem apply to, if applicable?

Safari, Chrome, Android webview

### What did you expect to see?

When I read that file again, I can see my data

### Did you test this? If so, how?

Sure, I test this on two macos ( safari 16.1 and safari 16.5) 

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/FileSystemSyncAccessHandle/write

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.FileSystemSyncAccessHandle.write`
* Report started: 2024-06-20T04:55:22.297Z

</details>

**Comment by queengooborg** [comment]
I'm afraid that the code example you provided is not available.  Could you please provide the code once again, perhaps directly in a comment here?

**Comment by linhttbk97** [comment]
https://drive.google.com/file/d/1LCcVHFoT9b_P8tqGRT5ct9M9vfOFk7zx/view?usp=sharing
here is the sample typescript code

**Comment by queengooborg** [comment]
Thanks for providing the sample code!  I added it directly to your original message and converted it from TypeScript to pure JavaScript to simplify the test.

Looking at the code, I see that you create the sync access handle, you flush it, and then you close it.  But you don't actually _write_ any data; `sampleData` is unused in this function.

**Comment by linhttbk97** [comment]
@queengooborg  No,I deleted it when copying, my mistake. Pls reopen this issue
<img width="786" alt="Screen Shot 2024-07-05 at 08 52 20" src="https://github.com/mdn/browser-compat-data/assets/107523533/3a2d6dbc-aaf1-49c0-abb6-d81c3645a7e7">

**Comment by queengooborg** [comment]
I just took another look, this time attempting to run the code provided (after converting it from TypeScript again -- FYI, for ease of testing, you should always provide pure JavaScript examples in test code, unless there's an absolute need to use TypeScript in the example), and I've found that the contents of the file have been written properly in Safari 16.5 and 17.5, as well as Chrome 126.

<img width="827" alt="Screenshot 2024-07-05 at 19 50 56" src="https://github.com/mdn/browser-compat-data/assets/5179191/0b3679d4-b2eb-4db3-abdc-793c373121ec">

**Comment by linhttbk97** [comment]
I think i could be happen on lower memory (maybe full disk) but I don't know why the QuotaExceededError doesn't throw

**Comment by linhttbk97** [comment]
It was tested on 3 mac machines, my mac worked normally but other two didn't
