### ISSUE TITLE
Keeping up to date with Chrome's flags

### ISSUE THREAD

**Issue by connorshea** [mdn/browser-compat-data#2346]
The `TextMetrics` JSON mentions a flag in Chrome called `ExperimentalCanvasFeatures`:

https://github.com/mdn/browser-compat-data/blob/019938c3984a4ff8b3f0bdf22ab85079eb40168c/api/TextMetrics.json#L111-L119

However, I can't find any such flag in Chrome Stable or Canary for macOS. 

Is there a way to automatically keep track of Chrome's flags and make sure the BCD only references flags that still exist?

### Chrome Flags page

Chrome Canary available flags:

<img width="1312" alt="screen shot 2018-06-20 at 12 28 22 pm" src="https://user-images.githubusercontent.com/2977353/41677427-7a549b7a-7485-11e8-9fa1-d98ddc97c313.png">

Chrome Canary available flags:
<img width="1312" alt="screen shot 2018-06-20 at 12 28 25 pm" src="https://user-images.githubusercontent.com/2977353/41677428-7a675ddc-7485-11e8-9c3c-22641b822863.png">

cc: @jpmedley in case you have any ideas here

**Comment by jpmedley** [comment]
There is no automated way to do this. By the way, this is why I rarely note runtime flags in the data that I submit. I'm currently trying to improve this, but I have nothing to report. When I'm comfortable that it's consistent on [Chrome Status](https://www.chromestatus.com/features) I'll worry about BCD.

[Here's what happened](https://chromium-review.googlesource.com/c/chromium/src/+/957646) to experimental canvas features. This is Chrome 67 onward.

**Comment by Elchi3** [comment]
I'm closing this now that https://github.com/mdn/browser-compat-data/pull/2547 is merged.

**Comment by connorshea** [comment]
Just for future note if anyone is trying to find it: This is the file where the Chrome Flags are located now https://chromium.googlesource.com/chromium/src/+/10a2f454c96b677280c2e380a052fadf740df1fb/third_party/blink/renderer/platform/runtime_enabled_features.json5

**Comment by jpmedley** [comment]
Oh, I wish it were that simple!  First, that's a commit. This is the [canonical source](https://cs.chromium.org/chromium/src/third_party/blink/renderer/platform/runtime_enabled_features.json). Among the problems:

* Items under 'Experimental Web Platform Features' which can sometimes be hard to nail down.
* The occasional practice of moving things from dedicated flags to 'Experimental' and vice versa. 
* The fact that some flags default to 'default' and are set either to enabled or disabled somewhere in code.

**Comment by connorshea** [comment]
@jpmedley and that URL doesn’t seem to work 😅

**Comment by jpmedley** [comment]
https://cs.chromium.org/chromium/src/third_party/blink/renderer/platform/runtime_enabled_features.json5

Though actually the flag ahcors as they appear in chrome://flags is in https://cs.chromium.org/chromium/src/chrome/browser/about_flags.cc
