### ISSUE TITLE
html.global_attributes.draggable - draggable tag not working as expected in Chrome.

### ISSUE THREAD

**Issue by alfonzeta** [mdn/browser-compat-data#23502]
### What type of issue is this?

Browser bug (a bug with a feature that may impact site compatibility)

### What information was incorrect, unhelpful, or incomplete?

https://developer.mozilla.org/es/docs/Web/HTML/Global_attributes/draggable
It says is fully compatible with Google Chrome, and It isn't.

### What did you expect to see?

draggable tag is not working as expected in Google Chrome. It works perfectly fine in other browsers, but when using Chrome, draggable elements work randomly. Sometimes they work, sometimes they dont, if I scroll down, or up, I can drag some elements, and not some others. In other web browsers like firefox, draggable divs are perfectly dragged when clicked on them and it works perfect.

### Did you test this? If so, how?

I've tried to run the website with draggable div element in various web browsers but it is Chrome the only one not working as expected.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://github.com/angular/protractor/issues/583

### MDN URL

https://developer.mozilla.org/es/docs/Web/HTML/Global_attributes/draggable

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `html.global_attributes.draggable`
* Report started: 2024-06-24T08:55:37.597Z

</details>

**Comment by queengooborg** [comment]
Reading through the linked issue, it doesn't appear to have any relation to the `draggable` HTML attribute.  The linked issue talks about issues with dragging and dropping in a _Selenium WebDriver_ context, which is not relevant to the issue you're describing or the page you have linked.

I'm going to close this as there is no actionable information.  However, if you are able to provide code demonstrating a simple test case that demonstrates the problem you are describing (that is, no frameworks and as few lines of code as possible), I'd be happy to revisit this.
