### ISSUE TITLE
Standard name for worker support

### ISSUE THREAD

**Issue by connorshea** [mdn/browser-compat-data#2351]
Right now the dataset has `worker_support` and `available_in_workers` as the two primary names for a feature being "available in workers".

Should we have a standard name for this? `available_in_workers` has 15 occurrences and `worker_support` has 22 occurrences.

**Comment by ExE-Boss** [comment]
I vote for `worker_support`.

**Comment by Elchi3** [comment]
I vote for `worker_support`, too. Thanks for standardizing this, Connor! :+1:

**Comment by connorshea** [comment]
so I assume I can open a PR for this? :)

**Comment by Elchi3** [comment]
Yes, feel free :)

**Comment by connorshea** [comment]
Opened #2362 :)
