### ISSUE TITLE
api.SpeechRecognition - when applied on mobile H5 ,only 1 sentence can be recognized

### ISSUE THREAD

**Issue by fbzcmk** [mdn/browser-compat-data#23678]
### What type of issue is this?

Other

### What information was incorrect, unhelpful, or incomplete?

when using SpeechRecognition on mobile h5 applcation , the access to mobile microphone stream data was bloced after the first sentence recognized , need some way to keep the mobile microphone data access.  

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

some additional api to apply for whole life cycle mobile microphone data access authorization

### Did you test this? If so, how?

it works well on pc ,but not well with the following same setting
this.recognition = new webkitSpeechRecognition();
				this.recognition.lang = 'zh-CN';
				this.recognition.continuous = true;
				this.recognition.interimResults = true; 

### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/API/Web_Speech_API

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.SpeechRecognition`
* Report started: 2024-07-06T11:25:07.428Z

</details>

**Comment by queengooborg** [comment]
This is the first time I've heard of the term "H5" in this context, but from what I can tell, it seems that this is typically a term used for describing webpages opened within an embedded view in WeChat and similar.

If this is what you mean by "mobile H5", then I'm afraid that this issue isn't something that we can document in BCD, as we do not document those apps as browsers.
