### ISSUE TITLE
css.selectors.target-text - now supported in Safari 

### ISSUE THREAD

**Issue by Neptune919** [mdn/browser-compat-data#23692]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Safari was marked as not supporting target-text.

### What browsers does this problem apply to, if applicable?

Safari

### What did you expect to see?

Safari listed as supporting target-text. 

### Did you test this? If so, how?

Yes, I saw it in action using a URL containing a Text Fragment. 

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/::target-text

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.selectors.target-text`
* Report started: 2024-07-08T07:17:52.629Z

</details>

**Comment by queengooborg** [comment]
Safari supports text fragments, but it does not support the `::target-text` selector to style them yet.  Here's a side-by-side comparison of Chrome and Safari:

<img width="1962" alt="Screenshot 2024-07-08 at 00 44 10" src="https://github.com/mdn/browser-compat-data/assets/5179191/69fc64ac-1698-46f2-9764-c59190c3c541">

**Comment by Neptune919** [comment]
That’s not true. The only difference in the automatically generated screenshot example is the color of the highlighting.

**Comment by queengooborg** [comment]
Uh...yes, that's exactly what I'm trying to show.  The color of the highlighting (and the text color) is exactly what shows if `::target-text` is supported.  The example page has the following CSS:

```css
::target-text {
  background-color: rebeccapurple;
  color: white;
}
```

We can see that in Chrome (left), the background color is correctly set to `rebeccapurple`, but it is not in Safari (right).

**Comment by Neptune919** [comment]
Oh, now I see.  Sorry for my misunderstanding. I was unaware of the color specification. Thanks.
