### ISSUE TITLE
api.ImageCapture - ImageCapture is supported behind a feature flag starting from safari 17.4 

### ISSUE THREAD

**Issue by AkiSakurai** [mdn/browser-compat-data#23727]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

Missing compatibility data for safari 17.4 behind feature flag

### What did you expect to see?

 ImageCapture is supported behind a feature flag starting from safari 17.4 

### Did you test this? If so, how?

yes

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/ImageCapture

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.ImageCapture`
* Report started: 2024-07-09T13:24:16.842Z

</details>

**Comment by queengooborg** [comment]
Can you provide supporting details, such as commits, bug reports, or details of the tests?

**Comment by queengooborg** [comment]
I'm afraid the information provided isn't all that helpful.  The release notes don't mention the API, and you have not specified what flag you have enabled.

**Comment by AkiSakurai** [comment]
Behind webkit feature flag "Image Capture API"

<img width="827" alt="Screenshot 2024-07-09 at 10 55 51 PM" src="https://github.com/mdn/browser-compat-data/assets/75532970/697a153c-33aa-46ba-a367-732a045412e9">

**Comment by AkiSakurai** [comment]
Bug reports
https://bugs.webkit.org/show_bug.cgi?id=262467
https://bugs.webkit.org/show_bug.cgi?id=262412
https://bugs.webkit.org/show_bug.cgi?id=265188
https://bugs.webkit.org/show_bug.cgi?id=262466

**Comment by AkiSakurai** [comment]
Here is what info we have now:

1. The release notes refer to a version code in the WebKit repository, which contains the source code for image capture.
2. The verifications on the MDN collector.
3. A screenshot of the flag I enable while running the collect.
4. A report in Bugzilla for WebKit, referencing a commit in the WebKit repository.

Could you let me know what additional information you need?
