### ISSUE TITLE
api.FileSystemEntry - Chromium based browsers do not have this interface (or sub interfaces)

### ISSUE THREAD

**Issue by heyitsdoodler** [mdn/browser-compat-data#23771]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

Compatibility data claimed support but actual use led to reference errors.

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

I expected to be able to check if a FileSystemEntry was a FileSystemDirectoryEntry or FileSystemFileEntry.

### Did you test this? If so, how?

Check the global scope for FileSystemEntry in a Chromium and Non-Chromium browser through the console.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

[FileSystemEntry](https://developer.mozilla.org/en-US/docs/Web/API/FileSystemEntry#browser_compatibility)
[FileSystemDirectoryEntry](https://developer.mozilla.org/en-US/docs/Web/API/FileSystemDirectoryEntry#browser_compatibility)
[FileSystemFileEntry](https://developer.mozilla.org/en-US/docs/Web/API/FileSystemFileEntry#browser_compatibility)

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/FileSystemEntry

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.FileSystemEntry`
* Report started: 2024-07-11T13:04:22.677Z

</details>

**Comment by queengooborg** [comment]
Not all interfaces are exposed on the global scope, and these interfaces are one of them.  BCD does not currently track global exposure of interfaces; that has been requested in #6720.

If you're looking to check if a `FileSystemEntry` object is a file or directory, you should use the `isFile` or `isDirectory` instance properties instead.
