### ISSUE TITLE
WEB ble sensors value tutorial : https://docs.arduino.cc/tutorials/nicla-sense-me/web-ble-dashboard/ is not working with my Mac (Chrome)

### ISSUE THREAD

**Issue by robby-proj** [mdn/browser-compat-data#23783]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

The Nicla sense ME sensor hangs on " connecting to device...."
<img width="1728" alt="Screenshot 2024-07-11 at 11 56 42 AM" src="https://github.com/mdn/browser-compat-data/assets/69437918/6bd91e72-5a8a-449a-a5d9-4cfdfd78476e">

### What did you expect to see?

Nicla Sense ME connected to WEB ble dashboard

### Did you test this? If so, how?

[video1517842553.mp4.zip](https://github.com/user-attachments/files/16182398/video1517842553.mp4.zip)
here is a video for it's been tested.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Web_Bluetooth_API

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.Bluetooth`
* Report started: 2024-07-11T17:08:49.758Z

</details>

**Comment by queengooborg** [comment]
This sounds like a development help request, which I'm afraid we are unable to assist with.  I would recommend asking on a dedicated help forum such as StackOverflow.
