### ISSUE TITLE
api.Crypto.randomUUID - available in NodeJS 18

### ISSUE THREAD

**Issue by mehulkar** [mdn/browser-compat-data#23784]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Crypto: randomUUID() is available in node 18, but MDN says it's available only in node 19 
![CleanShot 2024-07-11 at 12 23 40@2x](https://github.com/mdn/browser-compat-data/assets/490968/2f9f797d-bf13-49b7-957a-fd66d07e332f)

### What browsers does this problem apply to, if applicable?

Node.js

### What did you expect to see?

Node 18

### Did you test this? If so, how?

```
> process.version
'v18.18.0'
> require('crypto').randomUUID()
'865e9c01-4e30-4656-85b7-e73ada6a2580'
> 
```

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://nodejs.org/docs/latest-v18.x/api/crypto.html#cryptorandomuuidoptions

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.Crypto.randomUUID`
* Report started: 2024-07-11T19:22:50.780Z

</details>

**Comment by queengooborg** [comment]
Our data actually states that the feature was added in NodeJS 16.7.0 -- if you look at the compatibility table on the MDN page, you'll notice an ellipsis in the cell for NodeJS, which indicates there is more data to display.  Clicking on the cell will reveal the additional data.

However, looking at the NodeJS docs, there's some inconsistencies between it and our data, so this needs to be reviewed further, it looks like.

**Comment by skyclouds2001** [comment]
this is node.js's `crypto` module's `randomUUID()` method, they are complemently different method

**Comment by skyclouds2001** [comment]
the `randomUUID()` of `crypto` module is supported in v15.6.0 and v14.17.0, but the `randomUUID()` of Web `Crypto` class is supported in v16.7.0
