### ISSUE TITLE
handler.get/setPrototypeOf () seems to work with nodejs v6.4.0.

### ISSUE THREAD

**Issue by segayuu** [mdn/browser-compat-data#2379]
see https://node.green/#ES2015-built-ins-Proxy--setPrototypeOf--handler

**Comment by Elchi3** [comment]
This is fixed https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/handler/setPrototypeOf#Browser_compatibility
