### ISSUE TITLE
Organize json files into directories

### ISSUE THREAD

**Issue by a2sheppy** [mdn/browser-compat-data#238]
Currently, all the JSON is in one directory. Right now, that's not too bad... but eventually we're going to have hundreds of them, and it will become unmanageable. We should preempt this issue by deciding on a directory structure for the data and start using it right away.

We could simply divide it by API, with folders named things like "DOM" and "Intersection_Observer", or we could use API groups, or some other structure that makes sense.

Florian tells me the code already scans all the subfolders if any for JSON, so the structure doesn't matter at all. That means we can make this change just by creating directories and moving existing files into them.

**Comment by teoli2003** [comment]
Mmh, I have some doubt here. For API, we have 1 file per interface, named <interface_name>.json. It is trivial to find the right face for updating it (or to create it). Having directories per API forces us to know the API it relates to, and this is non trivial.

For example this is the difference between the way Gecko stores .webidl files: they are in one single directory and easy to find. Blink, put them in directories, and finding the right one is always difficult.

I would propose not to do this.

**Comment by a2sheppy** [comment]
I mostly agree, although there would be times it would be nice to have a
way to quickly grab the all of the JSON for a specific API. Perhaps some
sort of a catalog of the JSON files for each API? Hm.


Eric Shepherd
Senior Technical Writer, MDN
MDN: https://developer.mozilla.org/
Blog: https://www.bitstampede.com/

On October 3, 2017 at 8:33:31 AM, Jean-Yves Perrier (
notifications@github.com) wrote:

I would propose not to do this.

**Comment by Elchi3** [comment]
> Perhaps some sort of a catalog of the JSON files for each API? Hm.

Over in https://github.com/mdn/browser-compat-data/issues/233 we agreed that this catalog is actually what we have as groupdata.json so far and the plan is that a polished groupdata will live in the mdn/data repository one day.

I agree with what Jean-Yves said.
