### ISSUE TITLE
api.SpeechRecognition - Mozilla says Firefox is not supported

### ISSUE THREAD

**Issue by harikt** [mdn/browser-compat-data#23812]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

[SpeechRecognition](https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API#api.speechrecognition) says Firefox is not supported.

### What browsers does this problem apply to, if applicable?

Firefox

### What did you expect to see?

Yes, it is supported.

### Did you test this? If so, how?

Yes. I tested online.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.SpeechRecognition`
* Report started: 2024-07-14T04:14:55.275Z

</details>

**Comment by queengooborg** [comment]
The [example](https://mdn.github.io/dom-examples/web-speech-api/speech-color-changer/) for speech recognition that is linked on that page does not work in Firefox, as the Speech Recognition API is not supported, let alone exposed.  Since you had not provided details on how you had tested for support, I am closing this as there is no actionable information.

**Comment by harikt** [comment]
@queengooborg Sorry for the confusion. I was under the impression it was supported.

![image](https://github.com/user-attachments/assets/9bdfb826-9522-4d38-aff8-9d2e3138d73b)

From the mozilla page https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API , it mentions 

> This feature is well established and works across many devices and browser versions. It’s been available across browsers since September 2018. 

which confused me. It looks firefox don't have support yet. So wonder why the text above is shown though.

**Comment by queengooborg** [comment]
Hmm, it seems that the Baseline banner might only be based on one aspect of the Web Speech API, which is the speech synthesis, not speech recognition.  I'd recommend filing an issue with the repository responsible for Baseline: https://github.com/web-platform-dx/web-features
