### ISSUE TITLE
api.InputEvent.data - <SUMMARIZE THE PROBLEM>

### ISSUE THREAD

**Issue by Smarysz** [mdn/browser-compat-data#23828]
### What type of issue is this?

Browser bug (a bug with a feature that may impact site compatibility)

### What information was incorrect, unhelpful, or incomplete?

-

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

When I trigger "input" event on <input> using pasting (CTRL + V), .data property contains null value. This bug occurs only in Chrome and chrome based browsers. In Firefox in works good.

### Did you test this? If so, how?

I tested and I got null in .data

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

-

### Do you have anything more you want to share?

-

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/InputEvent/data

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.InputEvent.data`
* Report started: 2024-07-16T15:23:40.673Z

</details>

**Comment by queengooborg** [comment]
Duplicate of #21953.
