### ISSUE TITLE
Browsers nodejs compat data

### ISSUE THREAD

**Issue by gsouquet** [mdn/browser-compat-data#2389]
Hi, 

I had a look at `browsers/nodejs.json` and noticed that there were three current version.

- nodejs v6
- nodejs v8
- nodejs v10

According to [nodejs.org](https://nodejs.org/en/), v8 is LTS and v10 is current. That would make sense to have those two as `current` in the compat table.
Is it possible to add "notes" for those browsers?

I believe that nodejs v6 should now be `retired` can you confirm that this is correct? 

Let me know and I'll go ahead with a PR to fix those things

**Comment by franklinyu** [comment]
v6 should be "maintenance mode", not retired, according to the schedule:

![schedule](https://github.com/nodejs/Release/raw/2ec87a51ebc6eef442fdaff1b6f5907a247c5416/schedule.png)

**Comment by jcsahnwaldt** [comment]
Related: #2294 **Update Node.js versions**

**Comment by gsouquet** [comment]
Thanks for linking the two issues @jcsahnwaldt. Mine looks duplicate, i'll close it
