### ISSUE TITLE
alignment-baseline does not work on <text> in Firefox

### ISSUE THREAD

**Issue by tomfroehle** [mdn/browser-compat-data#23921]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/alignment-baseline

#### What information was incorrect, unhelpful, or incomplete?

The example has the alignmnet-baseline attribute on a text element. This is not supported (see the comment under the image: 'For object alignment in other elements (such as `<text>`), see dominant-baseline.')

#### Specific section or headline?

Example section

#### What did you expect to see?

An example where the attributes are applied to supported elements.

#### Did you test this? If so, how?

https://codepen.io/tomfroehle/pen/yLoXKZz

Example in Chrome 95.0.4638.54: 
![image](https://user-images.githubusercontent.com/3189110/139236347-b370a2c6-c7f4-4ffc-856c-49a43c01c028.png)

Example in FireFox 93.0: 
![image](https://user-images.githubusercontent.com/3189110/139236501-d4609b25-c834-4a49-99b4-aeceb9a27c3b.png)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/svg/attribute/alignment-baseline`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/alignment-baseline
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/svg/attribute/alignment-baseline/index.md
* Last commit: https://github.com/mdn/content/commit/bd3f490ef78b600a1435dfe3611a27f3f2fbf4ef
* Document last modified: 2021-09-23T21:22:12.000Z

</details>

**Comment by queengooborg** [comment]
This data was fixed in #23545!
