### ISSUE TITLE
"Experimental should be set to false as the feature is supported in multiple browser engines" rule is too strict

### ISSUE THREAD

**Issue by SelenIT** [mdn/browser-compat-data#23968]
### What type of issue is this?

Linter issue

### What is the issue?

"Experimental should be set to false as the feature is supported in multiple browser engines" rule forces to mark features with de facto support as non-experimental regardless their actual standardisation status

### What behavior were you expecting?

There should be no strict dependency between de facto support and experimental status of the feature. There are features with a quite good support (though not complete interoperable) despite being in early stage of standardisation process. The rule itself is useful, but it probably should generate a warning rather than an error.

### What version(s) of BCD is the issue present in?

- [ ] The current BCD release
- [X] The current version of the `main` branch

### Do you have anything more you want to share?

The `background-clip:text` CSS feature (its status I tried to update in PR #23966) is an example case where de facto implementation status and standardisation status do not match. It was introduced as a non-standard (vendor-prefixed) extension in WebKit engine, became widely popular because of the popularity of WebKit/Blink browsers, and was added to Firefox for compatibility (though its implementation still [has many open issues](https://bugzilla.mozilla.org/show_bug.cgi?id=1656784)). However, it's still only specified in the [CSS Backgrounds 4 Editor's Draft](https://drafts.csswg.org/css-backgrounds-4/#background-clip) which is marked as "Not Ready For Implementation". Marking such a feature as "non-experimental" feels really wrong :(

**Comment by queengooborg** [comment]
BCD's experimental status is defined as the history of browser support, and is not defined by the standards track at all.  This is because a specification may still be in early draft stages, but all browsers had implemented the spec; or a specification has been a final draft for a long time, but a browser had only just implemented the feature.

In regards to your PR, the message is displayed because both Chrome and Safari support the feature without any caveats, so experimental status should indeed be false.

**Comment by SelenIT** [comment]
Thanks a lot for the clarification! My initial understanding was based on the [schema description page](https://github.com/mdn/browser-compat-data/blob/main/schemas/compat-data-schema.md#status-information) saying that `experimental: false` "means the functionality is mature and _no significant changes are expected in the future_", which might be not the case for an early draft feature regardless its implementation status (there were cases when well-supported features got significantly rewritten, e.g. CSS Gradients syntax) 😳

I guess this issue can be closed as invalid. However, it would be nice to have a special kind of warning for features that are on standards track, with decent de facto support, not deprecated, but also not stable/mature in the spec terms and thus likely subject to change in the future, even if "experimental" doesn't fit there.
