### ISSUE TITLE
css.properties.ruby-position - Firefox & Chrome don't support inter-character value

### ISSUE THREAD

**Issue by nt1m** [mdn/browser-compat-data#23971]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

MDN says Chrome & FF support all values except alternate

### What did you expect to see?

inter-character has its own row with Chrome & FF marked as unsupported, and Safari marked as supported.

### Did you test this? If so, how?

Yes, it's rejected at parse time in devtools

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://drafts.csswg.org/css-ruby/#rubypos

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/ruby-position

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.ruby-position`
* Report started: 2024-07-29T07:45:51.675Z

</details>

**Comment by estelle** [comment]
In Safari, the `inter-character` is supported only on the prefixed property, 
`-webkit-ruby-position: inter-character;` with the unprefixed property, `ruby-position` not supported at all in Safari (which the BCD accurately reflects).
