### ISSUE TITLE
css.at-rules.counter-style - Safari 17 does not support @counter-style example given

### ISSUE THREAD

**Issue by darylbarnes** [mdn/browser-compat-data#24022]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Compatibility table says Safari 17 supports the example given but it does not.

### What browsers does this problem apply to, if applicable?

Safari

### What did you expect to see?

I expected to see the thumbs up.

### Did you test this? If so, how?

Yes tested on Safari 17 on Mac.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/@counter-style

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.at-rules.counter-style`
* Report started: 2024-08-01T17:58:41.991Z

</details>

**Comment by queengooborg** [comment]
The example is working for me in Safari 17.5, both with ordered and unordered lists:

<img width="912" alt="Screenshot 2024-08-01 at 13 45 19" src="https://github.com/user-attachments/assets/17967c8c-a44b-4ec6-bd3e-89df0e3fabc3">
