### ISSUE TITLE
css.types.calc-constant - Rename to calc-keyword

### ISSUE THREAD

**Issue by Josh-Cena** [mdn/browser-compat-data#24036]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

See https://github.com/mdn/content/issues/34348; the `calc-constant` key should be renamed to `calc-keyword`.

### What did you expect to see?

The correct key name that matches the type name.

### Did you test this? If so, how?

See https://github.com/mdn/content/issues/34348 for motivation

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/calc-keyword

**Comment by bsmth** [comment]
Also linking the following:

- [x] https://github.com/web-platform-dx/web-features/pull/2442
