### ISSUE TITLE
html.elements.input.type_time - widget is not shown on mac on firefox 128

### ISSUE THREAD

**Issue by giomessina** [mdn/browser-compat-data#24074]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

The docs say that input type=time has full support on Firefox (all platforms) but on Firefox 128 (macOS) the hour/minute widget is not displayed  and the time must be entered manually
 

### What browsers does this problem apply to, if applicable?

Firefox

### What did you expect to see?

the widget to select the time is visible

### Did you test this? If so, how?

I have opened the page https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time#result in firefox 128 on a macOS 14.5 and the widget is not visible

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time#result

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `html.elements.input.type_time`
* Report started: 2024-08-09T13:49:55.867Z

</details>

**Comment by Josh-Cena** [comment]
There is no requirement that browsers must show a dropdown list to select times. Our references never mentioned that either. Different browsers will always provide input widgets with different UX and that is up to them.
