### ISSUE TITLE
`css.properties.cursor` - Conflicting reports about support on iOS

### ISSUE THREAD

**Issue by ddbeck** [mdn/browser-compat-data#24142]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Caniuse says [this property](https://caniuse.com/css3-cursors) is not supported on Safari for iOS and there's an issue on caniuse that says that BCD is incorrect. See https://github.com/Fyrd/caniuse/issues/7066.

### What browsers does this problem apply to, if applicable?

Safari

### What did you expect to see?

I'd expect caniuse and BCD to tell the same story. Given the more recent report about support on the caniuse repository and the fact that an automated test produced the support data for BCD, I'm inclined to believe that BCD is more likely to be the wrong party.

### Did you test this? If so, how?

I haven't tested it. @queengooborg has tested it with the collector: https://github.com/mdn/browser-compat-data/pull/22444. It's unclear to me how the collector actually tests cursor behavior like this.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

Discovered in the course of https://github.com/web-platform-dx/web-features/pull/1596/

**Comment by queengooborg** [comment]
I just did a test, and it turns out: the cursor property _is_ supported!  However, it's a very small subset, and it's only supported on iPadOS with a trackpad (as expected).  I'll be submitting a PR to correct BCD according to my findings soon!
