### ISSUE TITLE
webextensions.api.scripting.ExecutionWorld - Not supported in firefox

### ISSUE THREAD

**Issue by YuvalSivan** [mdn/browser-compat-data#24178]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Firefox says "ISOLATED" and "MAIN" are supported from Firefox 102.
But it says 102 on all versions of all browsers.
![image](https://github.com/user-attachments/assets/3b409eff-90ca-4ef8-a5fa-0b4d9feefafe)
this is probably a bug in the generation of the support table HTML. Or a data entry error.

Execution World is not supported in Firefox at all

### What did you expect to see?

unsupported

### Did you test this? If so, how?

Looked at it (screenshot provided)

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

no

### Do you have anything more you want to share?

no

### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/scripting/ExecutionWorld

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `webextensions.api.scripting.ExecutionWorld`
* Report started: 2024-08-20T11:50:29.642Z

</details>

**Comment by queengooborg** [comment]
I'm closing this issue as there is not enough information provided.  Please provide supporting information that demonstrates how the feature is not supported in Firefox.
