### ISSUE TITLE
api.PushMessageData - WebView is WONTFIX

### ISSUE THREAD

**Issue by jtotht** [mdn/browser-compat-data#24248]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

The table says the support in Android WebView is “No”, which usually means that it’s yet to be implemented in that browser. However, per https://issues.chromium.org/issues/40388442#comment27 (May 2024), there are no plans to ever support the Push API in WebView.

### What did you expect to see?

A notice that makes it clear that the support status in WebView is WONTFIX (due to architectural constraints).

### Did you test this? If so, how?

–

### Do you have anything more you want to share?

This applies to all interfaces, events etc. of the Push API, I just happened to find it through this particular interface.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/PushMessageData

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.PushMessageData`
* Report started: 2024-08-29T12:14:39.871Z

</details>

**Comment by queengooborg** [comment]
A "No" in the compatibility table means that the browser doesn't support the feature.  It does not make any claims that the browser will eventually add support.  There's also already a link to the bug, so there is no change to be made.

**Comment by jtotht** [comment]
> A "No" in the compatibility table means that the browser doesn't support the feature. It does not make any claims that the browser will eventually add support.

The general expectation is that browsers support standards, because that’s what standards are for. Any deviation is surprising, and further explanation is welcome.

>  There's also already a link to the bug

With the information buried in comments, plus a teeny-tiny, black-on-white chip saying “Infeasible”. Neither of them is really discoverable.

> there is no change to be made.

I’ve already discovered what’s the case, I just wanted to help fellow web developers discover it more quickly. I guess I won’t…
