### ISSUE TITLE
api.Element.currentCSSZoom - broken - shows always 1

### ISSUE THREAD

**Issue by yelodevopsi** [mdn/browser-compat-data#24246]
### What type of issue is this?

Incorrect support data: currentCSSZoom claims to be supported in firefox 126 and above.

### What information was incorrect, unhelpful, or incomplete?

Incorrect support data: currentCSSZoom claims to be supported in firefox 126 and above.

### What browsers does this problem apply to, if applicable?

Firefox
### What did you expect to see?

currentCSSZoom  is not currently supported with even latest version (129.0.2 (64-bit))

element.currentCSSZoom returns 1 as value regardless of zoom

### Did you test this? If so, how?

* console.log(element.currentCSSZoom)

* Edge (128.0.2739.42 (Official build) (64-bit)) and chrome ( 128.0.6613.114 (Offisiell delversjon) (64-bit))  is currently in preview with the currentCSSZoom feature, and is properly calculated when the zoom changes.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Element/currentCSSZoom

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.Element.currentCSSZoom`
* Report started: 2024-08-29T11:28:36.609Z

</details>

**Comment by queengooborg** [comment]
The example on the MDN page is working in Chrome for me:

<img width="618" alt="Screenshot 2024-09-08 at 23 33 21" src="https://github.com/user-attachments/assets/467f8016-9575-4350-b519-a9fe3acf019b">
