### ISSUE TITLE
meta: Remove references to "version_added": true or null from compat data schema documentation

### ISSUE THREAD

**Issue by danielhjacobs** [mdn/browser-compat-data#24257]
### What type of issue is this?

Schema issue

### What is the issue?

https://github.com/mdn/browser-compat-data/blob/main/schemas/compat-data-schema.md#the-__compat-object, https://github.com/mdn/browser-compat-data/blob/main/schemas/compat-data-schema.md#version_added, and https://github.com/mdn/browser-compat-data/blob/main/schemas/compat-data-schema.md#flags make references to `"version_added": null` and/or `"version_added": true`.

Looking at https://github.com/search?q=repo%3Amdn%2Fbrowser-compat-data+%22%5C%22version_added%5C%22%3A+null%22&type=code, explicit mention of `"version_added": null` has already been fully removed from the BCD, only being referenced in that documentation and in a test that checks it to be the default when compatibility data is not provided.

Looking at https://github.com/search?q=repo%3Amdn%2Fbrowser-compat-data+%22%5C%22version_added%5C%22%3A+true%22&type=code, `"version_added": true` is only being used in 12 remaining files (outside the documentation page), and there has recently been a concerted effort to remove the remaining instances.

It's also worth noting this is the only remaining document that mentions `"version_removed": true`: https://github.com/search?q=repo%3Amdn%2Fbrowser-compat-data+%22%5C%22version_removed%5C%22%3A+true%22&type=code

### What behavior were you expecting?

The schema documentation shouldn't reference a deprecated way of indicating browser support. There's an argument to be made for not removing this until those other 12 files are updated, but I think it's a poor argument, as the documentation says it's only noting the "common possible support statements", and this support statement is no longer common.

### What version(s) of BCD is the issue present in?

- [x] The current BCD release
- [x] The current version of the `main` branch

**Comment by danielhjacobs** [comment]
For reference, 12 files are left that would be affected by this PR, and that will reduce to 0 over time:

1) https://github.com/mdn/browser-compat-data/blob/main/webextensions/api/commands.json - Chrome data, not fixed
2) https://github.com/mdn/browser-compat-data/blob/main/webextensions/api/cookies.json - Chrome data, not fixed
3) https://github.com/mdn/browser-compat-data/blob/main/webextensions/api/privacy.json - Chrome data, not fixed
4) https://github.com/mdn/browser-compat-data/blob/main/webextensions/api/management.json - Chrome data, not fixed
5) https://github.com/mdn/browser-compat-data/blob/main/webextensions/manifest/dictionaries.json - Firefox data, not fixed
6) https://github.com/mdn/browser-compat-data/blob/main/webextensions/api/storage.json - Partially fixed by https://github.com/mdn/browser-compat-data/pull/24084, Firefox for Android data for sync not fixed
7) https://github.com/mdn/browser-compat-data/blob/main/webextensions/api/devtools.json - Chrome data, not fixed
8) https://github.com/mdn/browser-compat-data/blob/main/webextensions/api/webRequest.json - Firefox data, not fixed
9) https://github.com/mdn/browser-compat-data/blob/main/webextensions/manifest/background.json - Chrome data, not fixed
10) https://github.com/mdn/browser-compat-data/blob/main/webextensions/manifest/optional_permissions.json - Partially fixed by https://github.com/mdn/browser-compat-data/pull/24093, though some Chrome data and some Firefox data is not fixed by that PR
11) https://github.com/mdn/browser-compat-data/blob/main/webextensions/api/menus.json - Chrome data, not fixed
12) https://github.com/mdn/browser-compat-data/blob/main/webextensions/manifest/commands.json - Chrome and Firefox data, not fixed

**Comment by danielhjacobs** [comment]
1) https://github.com/mdn/browser-compat-data/blob/main/webextensions/api/commands.json
    - https://issues.chromium.org/issues/40965122#comment11 - On Jul 28, 2020, Chromium added tab to onCommand.
    - Looking at the content of the file https://chromium.googlesource.com/chromium/src.git/+/f055a2b9a97be9a20650d7ccbbabd0a7dcbc6fb6/chrome/common/extensions/api/commands.json at that time, it also already included the other properties currently marked as `"version_added": true`

**Comment by queengooborg** [comment]
This is already covered in #24174, which will be merged once the remaining usage of nonreal values is finally removed.

As far as removing the mention of these values from the docs before they're fully removed from BCD, I do not think that updating the docs early is a good idea.  While I'm all for finally getting rid of nonreal values (I'm leading the project after all!), they are still valid values, so we should document them and describe them while they're still present.  Additionally, we're so close to getting rid of them all, so there's no need to remove the documentation early!

**Comment by danielhjacobs** [comment]
Ok, for what it's worth if it helps the effort:

1. https://github.com/mdn/browser-compat-data/blob/main/webextensions/api/commands.json
    - https://issues.chromium.org/issues/40965122#comment11 - On Jul 28, 2020, Chromium added tab to onCommand.
    - Looking at the content of the file https://chromium.googlesource.com/chromium/src.git/+/f055a2b9a97be9a20650d7ccbbabd0a7dcbc6fb6/chrome/common/extensions/api/commands.json at that time, it also already included the other properties currently marked as `"version_added": true`
2. https://github.com/mdn/browser-compat-data/blob/main/webextensions/api/cookies.json
    - https://chromium.googlesource.com/chromium/src.git/+/80f95f518b2a3ff472a23abe087cd4ef2e7b00bb was merged Dec 19, 2011. It was code cleanup, so any content there was already supported before then, but was supported at least since then.
    - Looking at the content of the file https://chromium.googlesource.com/chromium/src.git/+/80f95f518b2a3ff472a23abe087cd4ef2e7b00bb/chrome/common/extensions/api/cookies.json, at the time CookieStore.ids and CookieStore.tabIds were already supported
    - https://chromium.googlesource.com/chromium/src.git/+/b64117935cebab402aafe0248ee17fb89252f1cb was merged March 22, 2016
    - Looking at https://chromium.googlesource.com/chromium/src.git/+/b64117935cebab402aafe0248ee17fb89252f1cb%5E%21/#F3, it added support for sameSiteStatus.lax, sameSiteStatus.no_restriction, and sameSiteStatus.strict
    - https://chromium.googlesource.com/chromium/src.git/+/218d4eae63313b8fcf80f4befab679d1a200c57b was merged May 7, 2019
    - Looking at https://chromium.googlesource.com/chromium/src.git/+/218d4eae63313b8fcf80f4befab679d1a200c57b%5E%21/#F2, it added support for sameSiteStatus.unspecified
3. https://github.com/mdn/browser-compat-data/blob/main/webextensions/api/privacy.json
    - https://chromium.googlesource.com/chromium/src.git/+/80f95f518b2a3ff472a23abe087cd4ef2e7b00bb was merged Dec 19, 2011. It was code cleanup, so any content there was already supported before then, but was supported at least since then.
    - It was experimental at the time, but that commit already supported services.alternateErrorPagesEnabled and services.autofillEnabled.
    - The privacy API was moved out of the experimental status in https://chromium.googlesource.com/chromium/src.git/+/607e6522f841933e0d3130c09d33207876850948, merged Jan 25, 2012.
    - Not sure when support was added for network.httpsOnlyMode. Even to this day in https://chromium.googlesource.com/chromium/src.git/+/main/chrome/common/extensions/api/privacy.json, I don't see mention of it.

**Comment by danielhjacobs** [comment]
Continued:

4. https://github.com/mdn/browser-compat-data/blob/main/webextensions/api/management.json 
    - https://chromium.googlesource.com/chromium/src.git/+/7e7b782e9dbbc5d3e63fc832ff44a364e0d0163e was merged August 3, 2012
    - Looking at https://chromium.googlesource.com/chromium/src.git/+/7e7b782e9dbbc5d3e63fc832ff44a364e0d0163e%5E%21/#F14, it added support for ExtensionInfo.installType
5. Skipping for now, Firefox data needs to be found in the Gecko source code.
6. https://github.com/mdn/browser-compat-data/blob/main/webextensions/api/storage.json - https://github.com/mdn/browser-compat-data/pull/24084 is already open for the Chromium data, Firefox for Android data for sync needs to be found.
