### ISSUE TITLE
api.BeforeInstallPromptEvent - Inconsistent

### ISSUE THREAD

**Issue by apoleo88** [mdn/browser-compat-data#24352]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Browser compatibility is different from what is reported on another page: https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Guides/Making_PWAs_installable#browser_support

### What did you expect to see?

A correct, up to date, table

### Did you test this? If so, how?

no

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Guides/Making_PWAs_installable#browser_support
https://developer.mozilla.org/en-US/docs/Web/API/BeforeInstallPromptEvent#browser_compatibility

### Do you have anything more you want to share?

It doesn't show any iOS supported browser.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/BeforeInstallPromptEvent

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.BeforeInstallPromptEvent`
* Report started: 2024-09-05T15:40:48.619Z

</details>

**Comment by queengooborg** [comment]
This is correct data, Safari iOS does not have support for the BeforeInstallPromptEvent interface.  It doesn't mean that it doesn't support progressive web apps.

Please make sure that you test whether a feature is supported before opening an issue saying that it is.
