### ISSUE TITLE
http.headers.Set-Cookie.Partitioned - firefox android nightly

### ISSUE THREAD

**Issue by gamebeaker** [mdn/browser-compat-data#24416]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

Here: https://developer.mozilla.org/en-US/docs/Web/Privacy/Privacy_sandbox/Partitioned_cookies#browser_compatibility on the table is Firefox for Anfroid "No" it sould be "Nightly"

### What browsers does this problem apply to, if applicable?

Firefox

### What did you expect to see?

"Nightly" for Firefox for Android

### Did you test this? If so, how?

I help an open source addon and debugged this addon on firefox android and firefox android nightly only on nightly worked this code:

```
let cookies = await browser.cookies.getAll({domain: urlparts[urlparts.length-2]+"."+urlparts[urlparts.length-1],partitionKey: {}});
cookies = cookies.filter(item => item.partitionKey != undefined);
```

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Privacy/Privacy_sandbox/Partitioned_cookies

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `http.headers.Set-Cookie.Partitioned`
* Report started: 2024-09-11T07:22:07.870Z

</details>
```[tasklist]
### Tasks
```

**Comment by Elchi3** [comment]
This was updated in https://github.com/mdn/browser-compat-data/pull/24382 and should be released to BCD's consumers soon.
