### ISSUE TITLE
webextensions.api.action.setBadgeTextColor - Available since Chrome 110

### ISSUE THREAD

**Issue by jakubpivonka** [mdn/browser-compat-data#24429]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Browser compatibility table for `action.getBadgeTextColor()` and `action.setBadgeTextColor()`.

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

Supported since Chrome 110.

### Did you test this? If so, how?

Developed an extensions using `webextension-polyfill`. The `action.setBadgeTextColor()` worked not only in Firefox as expected, but in Chrome and Edge as well. Safari did not work, but that was to be expected.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

- https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/action/getBadgeTextColor
- https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/action/setBadgeTextColor#browser_compatibility
- https://developer.chrome.com/docs/extensions/reference/api/action#method-getBadgeTextColor
- https://developer.chrome.com/docs/extensions/reference/api/action#method-setBadgeTextColor

### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/action/setBadgeTextColor

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `webextensions.api.action.setBadgeTextColor`
* Report started: 2024-09-12T15:48:20.703Z

</details>

**Comment by rebloor** [comment]
Fixed by #25321
