### ISSUE TITLE
status values in browsers/*.json

### ISSUE THREAD

**Issue by jcsahnwaldt** [mdn/browser-compat-data#2446]
(This is based on [a comment](/mdn/browser-compat-data/pull/2294#issuecomment-404138204) on #2294).

There seems to be no good way to specify correct and useful `status` values in [browsers/nodejs.json](/mdn/browser-compat-data/blob/master/browsers/nodejs.json):
- Node.js [frequently releases new versions](/nodejs/node/blob/master/CHANGELOG.md) (every few weeks).
- Very few of these releases introduce or remove features that are tracked by BCD.
- `nodejs.json` should only contain releases which actually introduce or or remove features. 
  - Currently, these are 0.10.0, 0.12.0, 4.0.0, 5.0.0, 6.0.0, 6.5.0, 7.0.0, 7.6.0, 8.0.0, 8.3.0, 8.7.0, 8.10.0, 10.0.0, and 10.4.0.
- All of these releases are technically "retired". For example, 8.11.3 is the current LTS version, so 8.10.0 is "retired".
- Ergo, all releases in `nodejs.json` have status "retired", which is not useful and may be confusing.

Temporary solution: Make `status` optional, remove all `status` values from `nodejs.json`.

**This issue is intended to help collect ideas about long-term solutions.**

I think the root problem is that BCD data mostly deals with specific _releases_, but a status applies to a _release line_ (at least for Node.js), and the syntax of the `browsers/*.json` files doesn't offer a way to distinguish these two cases.

Examples:
- In most cases, BCD needs to specify in which particular release a certain feature was added or removed, e.g. `"version_added": "7.0.0", "version_removed": "7.6.0"`. The syntax of the `browsers/*.json` files works fine for this use case.
- A status like "LTS" or "Current" applies to a release line: Node.js 8.x is "LTS", 10.x is "Current". The syntax of the `browsers/*.json` files has no way to express that.

I can think of several ways to deal with this.

### 1. Give all releases status "retired"
As explained above.

Of course, that's not quite correct, and what's worse, it makes the status values quite useless.

### 2. Give all releases of a release line the same status
Example:
```
        "10.0.0": {
          "release_date": "2018-04-24",
          "release_notes": "https://nodejs.org/en/blog/release/v10.0.0/",
          "status": "current"
        },
        "10.4.0": {
          "release_date": "2018-06-06",
          "release_notes": "https://nodejs.org/en/blog/release/v10.4.0/",
          "status": "current"
        }
```
Of course, that's not quite correct either. Release line 10.x is "current", but release 10.4.0 isn't. Maybe that's OK though. Depends on how the status values are actually used.

### 3. Add all Node.js versions to `nodejs.json`

This would mean that BCD has all the version data and correct up-to-date status values, e.g. as of today, 8.11.3 would be "esr" and 8.11.2 would be "retired". It would also mean that `nodejs.json` gets quite large (currently, about 280 versions). See [this version of nodejs.json](/jcsahnwaldt/browser-compat-data/blob/afb1454d5cd44ce89ecfd30d71e93a144d419097/browsers/nodejs.json).

To reduce manual work, this should probably be done by a script that runs once every day or so, pulls data about Node.js releases from somewhere and generates a pull request whenever a new release comes out.

The bash one-liners in [my initial comment](/mdn/browser-compat-data/pull/2294#issue-194138798) on #2294 might be a good start. But I have no clue if this would be a good idea...

### 4. New syntax
Introduce new syntax in `browsers/*.json` files, e.g. "release_lines" in addition to "releases". This would probably mean that the "status" property should be removed from the individual releases. Example:

```
{
  "browsers": {
    "nodejs": {
      "name": "Node.js",
      "release_lines": {
        "8": {
          "status": "esr"
        },
        "10": {
          "status": "current"
        }
      },
      "releases": {
        ...
        "10.4.0": {
          "release_date": "2018-06-06",
          "release_notes": "https://nodejs.org/en/blog/release/v10.4.0/",
        }
      }
    }
  }
}
```
Maybe it would make sense to add some dates to the release lines, e.g. `"esr_start_date": "2017-10-31"`... No, much better - allow arrays (a bit like for feature versions):
```
      "release_lines": {
        "8": [
          {
            "status": "current",
            "start_date": "2017-05-30"
            "end_date": "2017-10-31"
          },
          {
            "status": "esr",
            "start_date": "2017-10-31"
          }
        ],
```
This would allow BCD to include all the data listed here: https://en.wikipedia.org/wiki/Node.js#Releases
I have no clue if this idea makes sense. Maybe it's overkill.

**Comment by jcsahnwaldt** [comment]
Currently, solution 4 (New syntax) seems best to me, but it also requires the most changes - it affects all browsers/*.json files and changes the data model.

I'm sure there are other solutions, and I'm probably missing a lot of details...

**Comment by caugner** [comment]
I have got two thoughts on this:
1. As regards the frequent releases, wouldn't it suffice to only manage minor versions of Node.js (e.g. `8.11`, `10.6`)? Since patch releases shouldn't introduce features, I would say they are irrelevant for compat data (and if a patch release is relevant, it could be mentioned in the `notes`).
2. When a feature is introduced in both release lines at the same time (e.g. `8.11` and `10.6`), wouldn't it suffice to set `version_added` to the higher version? I'm not sure the additional release line (with presumably backported features?) are relevant enough for compat data that it justifies the additional complexity.

**Comment by jcsahnwaldt** [comment]
> wouldn't it suffice to only manage minor versions of Node.js

Hey, there are only 71 comments on #2294, why didn't you read them? ;-) tl;dr: Node.js versions like `8.7` in BCD would probably be confusing, so we use full versions like `8.7.0` (but only the ones that introduce new features).

> When a feature is introduced in both release lines at the same time (e.g. `8.11` and `10.6`), wouldn't it suffice to set `version_added` to the higher version?

1. As far as I can tell, that has never happened. In each row on http://node.green, there's a monotonic "increase" from red to green. This means it suffices to set `version_added` to the lowest version in which a feature was added.

1. You have to distinguish between _release lines_ and _releases_. BCD mainly provides the information in which particular _release_ a feature was added, e.g. `version_added: 8.7.0`. As far as I can tell, _release lines_ wouldn't have anything to do with this information. BCD would only use them to assign the `status` to something, because there seems to be no good way to assign a meaningful `status` to specific _releases_.

**Comment by jcsahnwaldt** [comment]
A few more thoughts: The syntax separating `release_line` and `release` values probably wouldn't make sense for Chrome and Firefox (and maybe others). If I understand correctly,

- for Firefox, the latest release is `current`, and the previous release is `esr`,
- while for Chrome, the latest release is `current`, and there is no `esr` release.

In other words, there are no 'release lines'. Or at least, there is no distinction between 'release' and 'release line'. So the syntax I proposed above may make sense for Node.js, but it would be unnatural and tedious for others.

I could think of many alternative syntaxes, but as long as it's quite unclear how the `status` values may be used, I guess that's idle speculation... :-)
