### ISSUE TITLE
The description for RegExp lookbehind assertions uses > instead of the <.

### ISSUE THREAD

**Issue by Wevah** [mdn/browser-compat-data#2450]
Current description in RegExp.json:

`"lookbehind assertions (<code>(?&gt;= )</code> and <code>(?&gt;! )</code>)"`

The `&gt;`s should be `&lt;`s.

**Comment by caugner** [comment]
Good catch, @Wevah, would you like to submit the PR yourself?

**Comment by Wevah** [comment]
Sure.

**Comment by ddbeck** [comment]
Thanks for the report and the fix, @Wevah!
