### ISSUE TITLE
api.ServiceWorkerRegistration.getNotifications - Ony return some new notification

### ISSUE THREAD

**Issue by dzungle054** [mdn/browser-compat-data#24536]
### What type of issue is this?

Browser bug (a bug with a feature that may impact site compatibility)

### What information was incorrect, unhelpful, or incomplete?

When use ServiceWorkerRegistration: getNotifications() method, it only return some new notifications, old notification of yesterday can not get and when click on it, nothing happen. This error happen with PWA on chrome in android device.

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

My expect is there can get all notifications.

### Did you test this? If so, how?

I test in web PWA on chrome for android

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration/getNotifications

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.ServiceWorkerRegistration.getNotifications`
* Report started: 2024-09-26T03:03:24.210Z

</details>

**Comment by queengooborg** [comment]
This is probably something that's beyond BCD's scope to document, but my best guess based upon the MDN article is that your service worker had been re-registered, based upon: "Notifications created by one service worker on the same origin will not be available to other active service workers on that same origin."
