### ISSUE TITLE
@page rule - Not supported in Safari

### ISSUE THREAD

**Issue by jamesnw** [mdn/browser-compat-data#24566]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

`css.at-rules.page` was marked as having Safari support in https://github.com/mdn/browser-compat-data/pull/20144. However, my testing shows that the @page rule does not work in Safari.

### What browsers does this problem apply to, if applicable?

Safari

### What did you expect to see?

No support for Safari for `css.at-rules.page` or `css.at-rules.page.size`.

### Did you test this? If so, how?

Using the example from https://developer.mozilla.org/en-US/docs/Web/CSS/@page, I printed. The rules inside the `@page` rule were not respected. 

A narrower test is https://tests.caniuse.com/at-page/size.html, and I compared Chrome and Safari print preview.

**Comment by ddbeck** [comment]
There's an unresolved webkit bug too. https://bugs.webkit.org/show_bug.cgi?id=15548

I'll open a PR.
