### ISSUE TITLE
api.MediaStreamTrackProcessor - constructor not available on Safari 18

### ISSUE THREAD

**Issue by allsey87** [mdn/browser-compat-data#24569]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

I believe this entry is incorrect. When I try to create a new instance of a `MediaStreamTrackProcessor`, I am hit with:
```
ReferenceError: Can't find variable: MediaStreamTrackProcessor
```

### What browsers does this problem apply to, if applicable?

Safari

### What did you expect to see?

The constructor run correctly and no exception

### Did you test this? If so, how?

In the Javascript console of Safari: `new MediaStreamTrackProcessor()` - this should fail since I have not provided any arguments, but it should not throw a reference error exception.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://github.com/mdn/browser-compat-data/pull/23367

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrackProcessor

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.MediaStreamTrackProcessor`
* Report started: 2024-09-28T11:35:55.380Z

</details>

**Comment by skyclouds2001** [comment]
Maybe the version of Safari you test does not match v18?

**Comment by allsey87** [comment]
@skyclouds2001 did you try and get a different result? I tested on 18.0

**Comment by ludovit-as** [comment]
I can confirm that on Safari 18.0.1, the MediaStreamTrackProcessor is NOT available.

**Comment by skyclouds2001** [comment]
I can see the interface is included in source code yet, but can't found the commit in release refs, maybe it has not added to release yet?

![image](https://github.com/user-attachments/assets/1b7e7e8c-8559-42e2-b89e-bc41bab8499e)

see [source](https://github.com/WebKit/WebKit/blob/main/Source/WebCore/Modules/mediastream/MediaStreamTrackProcessor.idl), [commit](https://github.com/WebKit/WebKit/commit/b65f4ed6d7773e43c59f050351d01b7396f8e0d8) and [commit](https://github.com/WebKit/WebKit/commit/35a56e6b2d4ab965fadb5efe9bedc6dc3ce9308d), [bug](https://bugs.webkit.org/show_bug.cgi?id=267317) and [bug](https://bugs.webkit.org/show_bug.cgi?id=267763)

see also [spec](https://w3c.github.io/mediacapture-transform/)

**Comment by skyclouds2001** [comment]
But safari release note says it is supported, see https://developer.apple.com/documentation/safari-release-notes/safari-18-release-notes#WebRTC

**Comment by allsey87** [comment]
> But safari release note says it is supported, see https://developer.apple.com/documentation/safari-release-notes/safari-18-release-notes#WebRTC

Perhaps it is only partially implemented? Those release notes do not specifically mention `MediaStreamTrackProcessor`...

**Comment by skyclouds2001** [comment]
> > But safari release note says it is supported, see https://developer.apple.com/documentation/safari-release-notes/safari-18-release-notes#WebRTC
> 
> Perhaps it is only partially implemented? Those release notes do not specifically mention `MediaStreamTrackProcessor`...

I think this item says `MediaStreamTrackProcessor` is supported.

![image](https://github.com/user-attachments/assets/d21eb96f-9d8e-4841-9657-74d94cdc4e42)

**Comment by ludovit-as** [comment]
> I think this item says MediaStreamTrackProcessor is supported.

Did you test it?

**Comment by linusbrolin** [comment]
I have been looking at this aswell.
Safari 18 **have** implemented both `MediaStreamTrackProcessor` and `VideoTrackGenerator`, but only in dedicated workers, just like their release notes say.

So they are not available in the main thread, you must create a `Worker` to use them.

Example for testing their availability:
```
// somewhere in the main code
console.log('main', `MediaStreamTrackProcessor: ${'MediaStreamTrackProcessor' in globalThis}, VideoTrackGenerator: ${'VideoTrackGenerator' in globalThis}, TransformStream: ${'TransformStream' in globalThis}`);

const worker = new Worker('worker.js');

worker.onmessage = ({ data }) => { console.log('worker', data); };
worker.postMessage('');

// worker.js file
addEventListener('message', ({ data }) => {
  postMessage(`MediaStreamTrackProcessor: ${'MediaStreamTrackProcessor' in globalThis}, VideoTrackGenerator: ${'VideoTrackGenerator' in globalThis}, TransformStream: ${'TransformStream' in globalThis}`);
});

// console log results
main MediaStreamTrackProcessor: false, VideoTrackGenerator: false, TransformStream: true
worker MediaStreamTrackProcessor: true, VideoTrackGenerator: true, TransformStream: true
```

**Comment by skyclouds2001** [comment]
> Did you test it?

I mean, I think this item indicate the support of `MediaStreamTrackProcessor`

**Comment by allsey87** [comment]
Out of interest, what is the intended workflow then if you start with `getUserMedia` (not available in workers) and want to use it with `MediaStreamTrackProcessor` (only available in workers)? Which object and at what point are you supposed to send stuff to the worker via `postMessage`?

**Comment by allsey87** [comment]
I haven't tested this in a worker yet, but will close since the data seems to be correct after all.
