### ISSUE TITLE
api.Navigator.xr - Edge Android has supported WebXR api in canary 131.0.2866.0. Please help update the compatibility diagram

### ISSUE THREAD

**Issue by Leteno** [mdn/browser-compat-data#24576]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

Edge Android has supported webxr now, starting from canary 131.0.2866.0.
Please help update the compatibility page.

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

- 

### Did you test this? If so, how?

You could just try https://immersive-web.github.io/webxr-samples/ in the latest Edge canary Android. It is working now.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/WebXR_Device_API

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.Navigator.xr`
* Report started: 2024-09-30T09:02:29.818Z

</details>

**Comment by Leteno** [comment]
Hi, @queengooborg  
In the compatibility page we list many Android device, could we add Edge Android as well?
![image](https://github.com/user-attachments/assets/f7c5d987-97bd-4c6e-9a17-d0a5bf9e5f9c)

**Comment by queengooborg** [comment]
We currently have no plans to add Edge Android as it has not been requested by anyone else.  However, you're more than welcome to open an issue to request Edge Android to be added so that it may be added to the meeting agenda and discussed!

**Comment by Leteno** [comment]
> We currently have no plans to add Edge Android as it has not been requested by anyone else. However, you're more than welcome to open an issue to request Edge Android to be added so that it may be added to the meeting agenda and discussed!

Hello @queengooborg  I am not familiar with the flow, could you please show me the link to submit?
I search around and see these two, which one is correct way to submit a request.

https://github.com/mdn/browser-compat-data/issues/new?assignees=&labels=&projects=&template=data-problem.yml&title=%3CNAME+THE+FEATURE%3E+-+%3CSUMMARIZE+THE+PROBLEM%3E

https://github.com/mdn/mdn/issues/new?assignees=&labels=proposal%2Cneeds+triage&projects=&template=content-or-feature-suggestion.yml&title=Enter+your+proposal+here
