### ISSUE TITLE
Add `deprecated` filter for `traverse` script

### ISSUE THREAD

**Issue by jamesnw** [mdn/browser-compat-data#24609]
### What would you like to see added to BCD?

When running `npm run traverse` it would be helpful to be able to omit any keys marked as deprecated, perhaps with a `--deprecated false` flag.

### How impactful do you think this enhancement will be?

The impact would likely be limited to users of the `traverse` script- I'm not sure how widespread that is.

**Comment by caugner** [comment]
`--deprecated false` or `--no-deprecated`

**Comment by jamesnw** [comment]
> `--deprecated false` or `--no-deprecated`

Having `--deprecated false` would allow for `--deprecated true` which could also be useful.

**Comment by jamesnw** [comment]
> `--deprecated false` or `--no-deprecated`

Oh, I misunderstood- I opted to allow either usage in #24707.
