### ISSUE TITLE
lquote_rquote_attributes - Remove irrelevant feature

### ISSUE THREAD

**Issue by fred-wang** [mdn/browser-compat-data#24681]
### What type of issue is this?

Other

### What information was incorrect, unhelpful, or incomplete?

lquote/rquote attributes of the MathML `<ms>` element are documented, but per https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/index.md#removal-of-irrelevant-features it will become irrelevant  on November 15, 2024

### What browsers does this problem apply to, if applicable?

Firefox

### What did you expect to see?

This should be removed when it becomes irrelevant.

### Did you test this? If so, how?

No

**Comment by fred-wang** [comment]
cc @ icesfont

**Comment by queengooborg** [comment]
Irrelevant features are automatically watched for and removed through the linter.  Once it becomes irrelevant, a PR will be submitted to remove it.

**Comment by fred-wang** [comment]
:+1:
