### ISSUE TITLE
api.RTCDataChannel - `transferable` is marked as not supported by Chromium

### ISSUE THREAD

**Issue by josephrocca** [mdn/browser-compat-data#24680]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

`transferable` is marked as not supported by Chromium:

https://developer.mozilla.org/en-US/docs/Web/API/RTCDataChannel#browser_compatibility

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

`transferable` is now supported by Chromium: https://issues.chromium.org/issues/40787712

### Did you test this? If so, how?

Yes, I tested this demo in Chrome v130:
* https://tguilbert-google.github.io/RTCDataChannel/index.html
* https://issues.chromium.org/issues/40787712#comment27

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/RTCDataChannel

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.RTCDataChannel`
* Report started: 2024-10-10T03:59:31.651Z

</details>

**Comment by skyclouds2001** [comment]
\cc @josephrocca seems it will be supported in M130, seems it is not included by https://github.com/mdn/browser-compat-data/pull/24663

**Comment by josephrocca** [comment]
> seems it will be supported in M130

Yep, that's what I observed, but I see now that I opened the issue 5 days early - since it hadn't officially released yet.

Thanks!
