### ISSUE TITLE
CSS Container Style Queries - Incorrect Safari 18.1 TP Data

### ISSUE THREAD

**Issue by gavinmorrow** [mdn/browser-compat-data#24763]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

The footnote “3 The root element cannot be a container” should also apply to Safari 18.1 TP.

### What browsers does this problem apply to, if applicable?

Safari

### What did you expect to see?

It should match the data from <https://caniuse.com/mdn-css_at-rules_container_style_queries_for_custom_properties> (footnote 1). Footnote 3 from the incorrect page should also apply to Safari 18.1 TP and not just Safari 18.0

### Did you test this? If so, how?

I did not test this.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

- https://developer.apple.com/documentation/safari-release-notes/safari-18_1-release-notes : the issue is not listed as fixed, and the date is before the fix landed
- https://bugs.webkit.org/show_bug.cgi?id=271040
- https://caniuse.com/mdn-css_at-rules_container_style_queries_for_custom_properties

### Do you have anything more you want to share?

I’m mostly sure that the [first page](https://caniuse.com/css-container-queries-style) is wrong, but it’s possible I misinterpreted the data and it’s actually the [second page](https://caniuse.com/mdn-css_at-rules_container_style_queries_for_custom_properties).

**Comment by caugner** [comment]
> The footnote “3 The root element cannot be a container” should also apply to Safari 18.1 TP.

This footnote is coming [from caniuse](https://github.com/Fyrd/caniuse/blob/70c776f91992f5ac7ff10c13e64d64d2d988b7fd/features-json/css-container-queries-style.json#L662-L666), and is not originating from BCD.

Please consider opening an issue in the [caniuse repo](https://github.com/Fyrd/caniuse) instead. 🙏
