### ISSUE TITLE
api.WakeLock - <SUMMARIZE THE PROBLEM>

### ISSUE THREAD

**Issue by HenriqueMatias** [mdn/browser-compat-data#24799]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Wakelock Interface documentation claims that this feature is available in safari

When trying to access it on safari mobile or desktop is not possible to access.
Returning undefined

### What browsers does this problem apply to, if applicable?

Safari

### What did you expect to see?

I expected to see the same result as in other browsers:

Chrome:
WakeLock {  }

Firefox:
WakeLock {  }

Sarafi:
Undefined

But I got undefined.

### Did you test this? If so, how?

When navigating to a webpage in Safari open the console and try to access  "navigator.wakeLock".  Or when debugging on mobile.
The result is undefined.  

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/WakeLock

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.WakeLock`
* Report started: 2024-10-23T07:38:57.382Z

</details>

**Comment by Elchi3** [comment]
@HenriqueMatias do you know you can click on the cell in the MDN compat tables to see notes?

It says:

> Does not work in standalone Home Screen Web Apps. See [bug 254545](https://webkit.org/b/254545#c32).
