### ISSUE TITLE
zoom: reset should not be standard_track

### ISSUE THREAD

**Issue by jamesnw** [mdn/browser-compat-data#24790]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

`css.properties.zoom.reset` was marked "standard_track" in https://github.com/mdn/browser-compat-data/pull/22972. However, there is no mention of `reset` in the [spec](https://drafts.csswg.org/css-viewport/#zoom-property) or the [previous spec](https://www.w3.org/TR/2016/WD-css-device-adapt-1-20160329/).

It was implemented for awhile in Chromium and then removed. It still is available in Safari. 

[MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/zoom#reset)  advises against its use.

### What did you expect to see?

`standard_track: false`. I'm uncertain if it should also be marked as deprecated, since it appears to have never been `standard_track`.

### Did you test this? If so, how?

no

**Comment by caugner** [comment]
@jamesnw I agree. Since `css.properties.zoom.reset` has no `spec_url`, we should set `standard_track` back to `false`. Would you up for opening a PR?

**Comment by jamesnw** [comment]
@caugner I can. Should it also be deprecated?

**Comment by jamesnw** [comment]
This was updated in #25035 - apologies for not connecting these two!
