### ISSUE TITLE
css.properties.animation-timeline.scroll - doesnt work in ios chrome

### ISSUE THREAD

**Issue by DebugBhandari** [mdn/browser-compat-data#24818]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

scroll() property doesnt work in ios chrome. incomplete info.

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

added scroll() in my page and works fine in pcs but not in ios chrome as well as safari.

### Did you test this? If so, how?

Tested on my phone.

### Do you have anything more you want to share?

Just trying to update info.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/animation-timeline/scroll

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.animation-timeline.scroll`
* Report started: 2024-10-24T23:58:45.772Z

</details>

**Comment by queengooborg** [comment]
Chrome on iOS, like any browser on iOS, just uses Safari as its engine, so you should always refer to Safari iOS data to determine support.
