### ISSUE TITLE
webextensions.api.windows.create - desc about `focused: false` is misleading

### ISSUE THREAD

**Issue by danny0838** [mdn/browser-compat-data#24888]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

The description gives an impression that `focused: false` works normally in Firefox < 86, while it actually causes an error to be thrown in those versions.

### What browsers does this problem apply to, if applicable?

Firefox

### What did you expect to see?

Should have described that `focused: false` causes an error in Firefox < 86.

### Did you test this? If so, how?

I confirmed that `focused: false` causes an error in Firefox 68.

### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/windows/create

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `webextensions.api.windows.create`
* Report started: 2024-10-31T03:08:32.913Z

</details>

**Comment by rebloor** [comment]
@danny0838 can you confirm what error occurs and whether you're referring to versions 86 or 68

**Comment by danny0838** [comment]
`Error: Type error for parameter createData (Property "focused" is unsupported by Firefox) for windows.create.` was raised when `focused` property exists, no matter of its value.
