### ISSUE TITLE
webextensions.api.windows.create - missing ending quote for tabId for Firefox

### ISSUE THREAD

**Issue by danny0838** [mdn/browser-compat-data#24889]
### What type of issue is this?

Other (typo fix)

### What information was incorrect, unhelpful, or incomplete?

The description about tabId for Firefox has a missing ending quote.

### What did you expect to see?

The tabId should be quoted correctly.

### Did you test this? If so, how?

Typo fix doesn't need a test.

### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/windows/create

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `webextensions.api.windows.create`
* Report started: 2024-10-31T03:14:52.362Z

</details>

**Comment by rebloor** [comment]
This refers to the note `"'url' and 'tabId options can't both be set together."`
