### ISSUE TITLE
Support lint `"tags"` field in BCD

### ISSUE THREAD

**Issue by skyclouds2001** [mdn/browser-compat-data#24960]
### What type of issue is this?

Linter issue

### What is the issue?

Current the *tags* is mantually added by hand according to https://github.com/web-platform-dx/web-features/, but no lint will run for this field. This may cause some mistakes like: incorrect tag in  https://github.com/mdn/browser-compat-data/pull/24913, or tag added to mismatched feature, or tag not added to matched feature.

### What behavior were you expecting?

Support lint *tags* field in BCD. May need to check: whether the tag name s correct, whether the tag is added to the matched feature, whether the tag is not added to a matched feature, etc.

### What version(s) of BCD is the issue present in?

- [ ] The current BCD release
- [X] The current version of the `main` branch

**Comment by queengooborg** [comment]
Those tags are actually added via a script, not manually added.  The script in question already handles renames, deleted web features, etc.
