### ISSUE TITLE
RTCRtpReceiver: inconsistencies with Chrome-based browsers

### ISSUE THREAD

**Issue by caugner** [mdn/browser-compat-data#2497]
`RTCRtpReceiver` compat data was migrated in #993, and #2463 made me have a look at it:

[![image](https://user-images.githubusercontent.com/495429/42910462-efe795cc-8ae7-11e8-89a4-617e4c334ce0.png)](https://developer.mozilla.org/en-US/docs/Web/API/RTCRtpReceiver#Browser_compatibility)

There are three inconsistencies:

1. `getStats` is supported from 58 in Chrome and 55 in WebView, but basic support is only from 59.
2. `getStats` is supported from 45 in Opera/Opera Mobile, but no basic support is declared.

I would expect all `RTCRtpReceiver` features (except `getSynchronizationSources`) to be consistently added in version 59 for `webview_android`, `chrome` and `chrome_android` and in version 45 for `opera` and `opera_android`.

**Comment by caugner** [comment]
@jpmedley Could you confirm this?

**Comment by ddbeck** [comment]
This seems to have been fixed by #3181. 🎉
