### ISSUE TITLE
Derive Opera data from Chrome

### ISSUE THREAD

**Issue by ddbeck** [mdn/browser-compat-data#2510]
Prompted by @caugner on https://github.com/mdn/browser-compat-data/pull/2272#issuecomment-406727651. I think it would be helpful to discuss the prospect of deriving Opera data from Chrome data.

It appears that a large number of features appear in Opera 13 versions behind Chrome. If someone knows something about Opera development and how exceptions to that rule might be identified, then we could 1) document that for contributors and 2) systematically derive that data in places where we currently have gaps.

Not an urgent issue, but I wanted to write it down before I forgot.

**Comment by caugner** [comment]
Maybe https://github.com/SamsungInternet/mdn-bcd-map-browser-data could be generalized for this.

**Comment by Elchi3** [comment]
https://github.com/mdn/browser-compat-data/issues/3264 might help for this.

**Comment by vinyldarkscratch** [comment]
This would also help eliminate the sudden inconsistency in the Opera Android versions, and this same process would help with WebView and Samsung Internet.  I took a look at that repo, and it seems to cover a good chunk of the copying process.  I'd say that #3264 won't just help, it's the key component to making this process function smoothly.  For now, I've done a simple mirroring process (see #3869) that copies Chrome onto its derivatives (as well as Firefox onto Firefox Android).

**Comment by Elchi3** [comment]
We've done this in the CSS and JavaScript folders and for many APIs as well. The mirroring script that is about to land will also allow this to be done by anyone. Closing.

**Comment by caugner** [comment]
See: #4729
