### ISSUE TITLE
MDN states "Full support" for sub-feature, even if some sub-sub-features are not supported

### ISSUE THREAD

**Issue by caugner** [mdn/browser-compat-data#2514]
Example:

Firefox seemingly has **Full support** for sub-feature `background` of [manifest.json](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json).

![grafik](https://user-images.githubusercontent.com/495429/43069329-16aa9154-8e6d-11e8-937e-3295f727cc66.png)

![grafik](https://user-images.githubusercontent.com/495429/43069374-2f67a498-8e6d-11e8-92fc-b6c33b0d1b77.png)

**But** sub-sub-feature `persistent` of [manifest.json/background](https://developer.mozilla.org/de/Add-ons/WebExtensions/manifest.json/background) is **not supported** by Firefox:

![grafik](https://user-images.githubusercontent.com/495429/43069413-4aefb020-8e6d-11e8-94b7-38821c9ecd60.png)

Expectation:
* The compat table should distinguish between full support (i.e. has basic support and support for all – standard-track?! – sub-features) and partial support (e.g. orange background-color for this?).
* Additionally, a thin progress bar could visualize the proportion of supported/not-supported sub-features.
* Also, if different sub-features were added in different versions, the "Full support" cell shouldn't simply show the `version_added` of the "Basic support", but rather the range of versions or the max of versions.

**Comment by ddbeck** [comment]
To be honest, I'm not sure this is the right place for this bug report, since it's mostly about how MDN is chooses to summarize the data, rather than the data itself.

@wbamberg do you know if there's a better place for this bug (maybe filed against MDN directly)? I wasn't sure and I thought you might know

**Comment by caugner** [comment]
You're probably right, sorry about that, and I suppose https://github.com/mdn/kumascript is the right place.

**Comment by ExE-Boss** [comment]
It might be a good idea to also do it for [mdn/browser‑compat‑toolkit](https://github.com/mdn/browser-compat-toolkit) (see also #2354).

**Comment by Elchi3** [comment]
In https://github.com/mdn/kumascript/pull/559 we decided against computing partial support, and so far this was the only report requesting it to be re-implemented somehow. I don't think we will do that for now. If this becomes problematic for more things, please do file again.
