### ISSUE TITLE
api.Serial - <Serial web monitoring via Vivaldi browser, a Chromium based browser>

### ISSUE THREAD

**Issue by N0YHR** [mdn/browser-compat-data#25298]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

I use Vivaldi's browser in Windows and Linux Mint.  I can connect via serial in Windows, but not Mint.

Vivaldi is a Chromium based browser, and has a flag that tells websites that it is Chrome.

### What did you expect to see?

I expect it to find my Meshtastic devices that are connected via USB (serial).

### Did you test this? If so, how?

Yes, I attempted to connect.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

No

### Do you have anything more you want to share?

No

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Web_Serial_API

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.Serial`
* Report started: 2024-12-02T15:57:15.801Z

</details>

**Comment by queengooborg** [comment]
Based upon the description, it sounds like you're looking for technical support.  This repository is for documenting what features are supported in browsers.

If I'm misunderstanding, please let me know!
