### ISSUE TITLE
Consider renaming the `applications` manifest key to `browser_specific_settings`

### ISSUE THREAD

**Issue by ExE-Boss** [mdn/browser-compat-data#2540]
As both Firefox and Edge support `browser_specific_settings` (which is also [what’s in the spec](https://browserext.github.io/browserext/#dom-browserextmanifest-browserspecificsettings)), but only Firefox supports it as `applications`, I believe it should be considered for renaming.

See also #2541, https://discourse.mozilla.org/t/31394, https://bugzil.la/1487982.

**Comment by wagnerand** [comment]
@irenesmith We are experiencing broken add-ons on AMO since the addons-server does not know about this keyword yet (we only just learned about it). Until support has landed, could we please revert this patch and rename the MDN page back to https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/applications please? We expect to add support for this next week or the week after (see https://github.com/mozilla/addons-server/issues/9989)

**Comment by ExE-Boss** [comment]
@wagnerand I have added a&nbsp;warning to&nbsp;the&nbsp;top of&nbsp;[the&nbsp;MDN&nbsp;page](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_specific_settings) about the&nbsp;AMO&nbsp;issue.

**Comment by Elchi3** [comment]
> Until support has landed, could we please revert this patch and rename the MDN page back to https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/applications please?

Where are we with this @irenesmith @wagnerand @ExE-Boss ? It looks like the page was renamed but https://github.com/mdn/browser-compat-data/pull/3064 wasn't backed out. I'll release a new compat data package to MDN prod next week, so currently #3064 is not on the production site, but will be soon if there is no back out.

**Comment by irenesmith** [comment]
I have completed backing out this change.

**Comment by Elchi3** [comment]
Thank you, @irenesmith! :+1:

**Comment by wagnerand** [comment]
We are waiting on https://github.com/mozilla/addons-linter/pull/2285 which should be landing on production next week Thursday.

**Comment by ExE-Boss** [comment]
I don’t think merging https://github.com/mdn/browser-compat-data/pull/3122 right now was necessary, as it will take another week before this will be landing in production.
