### ISSUE TITLE
Object.entries() incorrectly lists iOS Safari as "No Support" 

### ISSUE THREAD

**Issue by chris-brighton** [mdn/browser-compat-data#2546]
On the [Object.entries()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries) page, the entry for iOS Safari should be *YES* insead of *No Support*. 

I'm not sure which version, but I've tested the function on the current latest version and it works.

**Comment by connorshea** [comment]
[The ES6 compat table agrees](http://kangax.github.io/compat-table/es2016plus/#test-Object_static_methods_a_href=_https://tc39.github.io/ecma262/#sec-object.entries_Object.entries_/a_a_href=_https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries_title=_MDN_documentation_img_src=_../mdn.png_alt=_MDN_(Mozilla_Development_Network)_logo_width=_15_height=_13_/_/a_nbsp;), I assume the version added would be the same as desktop Safari, so 10.1.
