### ISSUE TITLE
html.global_attributes.popover - <SUMMARIZE THE PROBLEM>

### ISSUE THREAD

**Issue by TrentHawke** [mdn/browser-compat-data#25545]
### What type of issue is this?

Browser bug (a bug with a feature that may impact site compatibility)

### What information was incorrect, unhelpful, or incomplete?

There seems to be an Accessibility Issue with the HTML Popover API. This might just be a new Bug but if an HTML Popover contains an input of type date then it causes unexpected focus changes when navigating through other elements with the Tab Key.

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet), Firefox, Safari

### What did you expect to see?

I was expecting to see some kind of indication that it is a known issue

### Did you test this? If so, how?

I did test this using the following HTML Markup

`<div>`
`  <button popovertarget="examplePopover">Open Popover</button>`
`</div>`
`<div id="examplePopover" popover>`
`  <div>`
`    <input type="date" />`
`  </div>`
`  <div>`
`    <input type="text" />`
`  </div>`
`</div>`

Then clicking on the "Open Popover" button, once the Popover opens, pressing the Tab Key will move the focus to the input date correctly but then pressing the Tab Key again will not move the focus to the next segment of the input date. The input date seems to effect other subsequent focusable elements as well, being unable to tab past the input date and onto other elements in the Popover.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/popover

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `html.global_attributes.popover`
* Report started: 2024-12-31T10:18:18.611Z

</details>

**Comment by TrentHawke** [comment]
Sorry, I missed the title

**Comment by queengooborg** [comment]
If this is something that affects all browsers, then I think it would be better to report this in the content repository to have a note added there.

**Comment by TrentHawke** [comment]
Thank you @queengooborg , I will give that a go!
