### ISSUE TITLE
Outdated data on MDN itself?

### ISSUE THREAD

**Issue by phistuck** [mdn/browser-compat-data#2557]
https://developer.mozilla.org/en-US/docs/Web/API/ParentNode/append shows Edge as not supporting `append`, but https://github.com/mdn/browser-compat-data/blame/master/api/ParentNode.json#L578 has been mentioning for three months that Edge 17 supports it.
![image](https://user-images.githubusercontent.com/184400/43035746-a75a28b6-8cfd-11e8-93f0-6506493c7fff.png)
![image](https://user-images.githubusercontent.com/184400/43035752-b1517d6a-8cfd-11e8-92c0-44c71f57b4de.png)

Or maybe I should file this at Bugzilla instead?

**Comment by jwhitlock** [comment]
@phistuck it shows "17" for me on https://developer.mozilla.org/en-US/docs/Web/API/ParentNode/append now.

Updating an MDN page to show new data requires regenerating the page. See https://github.com/mdn/browser-compat-data#browser-compatibility-tables-on-mdn, step 4:

> For updates to converted pages, a logged-in MDN user force-refreshes the page to regenerate it.

I imagine someone force-refreshed the page after reading your issue, but didn't update the ticket.

**Comment by phistuck** [comment]
@jwhitlock - it might have been me, but I still did not see the updated data. Now I do, so, yes, this is fixed. Thank you!
