### ISSUE TITLE
CSP (CSP v3.0) support table is unclear

### ISSUE THREAD

**Issue by rugk** [mdn/browser-compat-data#2558]
Full story here: https://discourse.mozilla.org/t/mdn-should-mention-csp-3-0-support-is-still-being-implemented-for-external-script-hashes/30694

In short:;
* What is "With external scripts" supposed to mean?
* As it seems, CSP v3.0 (especially, `’<hash-algorithm>-<base64-value>'` with external scripts) is not yet implemented in Chromium/Firefox & likely others. This should be reflected in the table.

**Comment by nickolay** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1409200#c6 is the bug about Firefox implementation of hashes for external scripts.

**Comment by vinyldarkscratch** [comment]
This has been fixed in #4373, which has a feature that explicitly mentions external scripts.  Thanks for your report!
