### ISSUE TITLE
SharedArrayBuffer was re-enabled in Chrome 68

### ISSUE THREAD

**Issue by chicoxyzzy** [mdn/browser-compat-data#2569]
I'm not sure how to add data properly for this.
Current compat-data: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer#Browser_compatibility
Confirmation of SAB re-enabling from V8 team: https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/wvV42Hxct3g

**Comment by Elchi3** [comment]
This is being taken care of in https://github.com/mdn/browser-compat-data/pull/2545

**Comment by chicoxyzzy** [comment]
There is some inconsistency in table. SAB was enabled and disabled in Edge, same as in Chrome, Firefox and Safari, though in Chrome and Firefox it's marked as available but in Safari and Edge it's unavailable.

I think it would be better to extend current format not to have just `version_added` and `version_removed` but an array of such periods, so every period could also reflect some feature for example was available under CLI flag, then under flag in browser options, then on by default, then disabled for some reason and the re-enabled again.

**Comment by connorshea** [comment]
You can have ranges and they should be used in cases like this, but they weren’t for whatever reason.

**Comment by chicoxyzzy** [comment]
@connorshea Is there any documentation about ranges?

**Comment by connorshea** [comment]
@chicoxyzzy the `array_support_statement` is how you'd represent a range https://github.com/mdn/browser-compat-data/blob/master/schemas/compat-data-schema.md#the-support_statement-object

**Comment by connorshea** [comment]
#2545 was merged so this can be closed
