### ISSUE TITLE
scroll-behavior works in Chrome 68 without Experimental Web Features flag

### ISSUE THREAD

**Issue by Vultraz** [mdn/browser-compat-data#2580]
I noticed while working on a project that the `scroll-behavior` CSS key works in at least Chrome 68 sans _Enable experimental web platform features_ flag. This is in conflict with what its [MDN page](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior#Browser_compatibility) says. Not sure about support between versions 61 and 68, though.

**Comment by vinyldarkscratch** [comment]
It looks like this has already been resolved by #3250.  This issue can be closed/
