### ISSUE TITLE
browser compatibility table for e.g.: String.sup 

### ISSUE THREAD

**Issue by jho1965us** [mdn/browser-compat-data#2584]
the browser compatibility table (new format) on e.g.:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/sup
Gives a number for Mozilla browsers  but there is no explanation of what that number means
I assume it is a version number but there should be some explanation

**Comment by ExE-Boss** [comment]
It is and always has been the version in which this feature was first supported.

**Comment by jho1965us** [comment]
@ExE-Boss "always has been" does not help new users on the page

**Comment by Elchi3** [comment]
What kind of explanation would you expect? Your assumption that it's a version number is correct.

**Comment by connorshea** [comment]
It might help to have the release date of the release on-hover, where possible. With that I'll have a general idea of what kind of support is to be expected (e.g. a Chrome release from two days ago doesn't really matter much in terms of support right this instant, but a Chrome release from a year ago means that I've probably comfortably got 50% of users, at the least.

I think that'd make it clearer that this is referring to version numbers, but I'm not sure if it really solves the problem (or if it's a problem at all).

**Comment by jho1965us** [comment]
@Elchi3 Just a simple text simmilar to the other legend below the table will do e.g. "The numer in the box refers to the version numbers of the product, Yes means ..." 
But havent figured out yet when "Yes" is used instead of a nummber.

**Comment by ExE-Boss** [comment]
> But havent figured out yet when "Yes" is used instead of a number.

That’s used when the version when support was first added is unknown, but it’s known to be supported in the latest stable release ([it’s stored as `true` in the data](https://github.com/mdn/browser-compat-data/blob/master/schemas/compat-data-schema.md#version_added)).

**Comment by vinyldarkscratch** [comment]
Closing this issue as it is stale.  Plans to remove "Yes" due to confusion like this are underway and discussed in #3021.
