### ISSUE TITLE
[HTTP headers] Which headers applies to what content

### ISSUE THREAD

**Issue by Malvoz** [mdn/browser-compat-data#2602]
When it comes to HTTP headers, it is often overlooked in blog posts and in specs (I found nothing) to mention for what content an HTTP header applies to.

For example, `Content-Security-Policy` is only really useful for files with `Content-Type: text/html;` and is redundant for other resources such as images, CSS, JS etc.

On the other hand we have header field names that could apply to anything such as `Accept-Ranges` or `Content-Length`.

To prevent header bloat and misconfigurations it would help tremendously to map out when or when not to apply headers and when it would be redundant/risky to do so.

**Comment by Elchi3** [comment]
I think this is a documentation issue rather than a compatibility information issue. Feel free to add such info to the MDN wiki pages. I don't think we'll display this in the compat tables.
