### ISSUE TITLE
PermissionStatus.status

### ISSUE THREAD

**Issue by connorshea** [mdn/browser-compat-data#2605]
The PermissionStatus API was added in #2284.

PermissionStatus has `state` and `status` subfeatures. `status` was the original name some browsers used for `state`, but it was removed in favor of the `state` property that was defined in the specification. 

Currently, the `PermissionStatus.json` file mentions `status` as an old, alternative name for `state`. However, MDN has [an entire separate article for `status`](https://developer.mozilla.org/en-US/docs/Web/API/PermissionStatus/status).

https://github.com/mdn/browser-compat-data/blob/a630fb3d8c53d29c7b9f354932192a8ecaa5ae13/api/PermissionStatus.json#L43-L50

Should we leave `status` as an alternative name or give it a separate subfeature? Also, should the MDN article for `status` be merged into `state`?

**Comment by Elchi3** [comment]
Fixed in #2606 

I've also redirected https://developer.mozilla.org/en-US/docs/Web/API/PermissionStatus/status to https://developer.mozilla.org/en-US/docs/Web/API/PermissionStatus/state
