### ISSUE TITLE
Push API is not updated on the article

### ISSUE THREAD

**Issue by crutchcorn** [mdn/browser-compat-data#2617]
Currently, on the Push API page https://developer.mozilla.org/en-US/docs/Web/API/Push_API, it does not seem to use the new data, however the browser compat migration spreadsheet https://docs.google.com/spreadsheets/d/1ivgyPBr9Lj3Wvj5kyndT1rgGbX-pGggrxuMtrgcOmjM/edit#gid=926663640 shows the article as being updated

**Comment by connorshea** [comment]
The Push_API page is an overview and, as far as I know, the plan is to not update any overview pages with the new data. I'm not sure of the exact reason, I just know that's the plan.

**Comment by ExE-Boss** [comment]
The plan, as far as I know, is to eventually handle Overview pages using another macro (see also https://github.com/mdn/kumascript/pull/650)

**Comment by vinyldarkscratch** [comment]
Closing this issue as it is stale and is no longer applicable (linked page uses new compatibility table).
