### ISSUE TITLE
Update CONTRIBUTING.md with details what versions of browsers should be used etc.

### ISSUE THREAD

**Issue by jakub-g** [mdn/browser-compat-data#2620]
It would be good IMO to document in `CONTRIBUTING.md` what versions are expected to be provided in the compat data

- Edge shows two versions when you go to its Settings screen, the browser itself like `Microsoft Edge 42.17134.1.0` and the engine version like `Microsoft EdgeHTML 17.17134`. It seems that the latter is used on MDN (`Edge 17`)
- When it comes to mobile Safari, should the version of Safari or version of iOS be provided? This is not clear (they are not always in sync, for example Safari 11.1 is shipped in iOS 11.3 -> seems that Safari version is used
- Whether versions of Safari should be like `11.0` or `11` -> seems that `11` format is used

(Also on MDN itself, maybe when you hover over those browsers, it should say which version are we talking about).

WDYT?

**Comment by vinyldarkscratch** [comment]
You've brought up some really good points, and to most, these may come off as confusing.

> Edge shows two versions when you go to its Settings screen, the browser itself like `Microsoft Edge 42.17134.1.0` and the engine version like `Microsoft EdgeHTML 17.17134`. It seems that the latter is used on MDN (`Edge 17`)

This, I intend to resolve in #3166.

> When it comes to mobile Safari, should the version of Safari or version of iOS be provided? This is not clear (they are not always in sync, for example Safari 11.1 is shipped in iOS 11.3 -> seems that Safari version is used

We've been using the Safari versions, but Apple [states that it should be the iOS version](https://github.com/mdn/browser-compat-data/issues/2006#issuecomment-457277312).

> Whether versions of Safari should be like `11.0` or `11` -> seems that `11` format is used

This is correct, and should definitely be addressed in the documentation.
