### ISSUE TITLE
The migration spreadsheet is no longer accessible

### ISSUE THREAD

**Issue by ExE-Boss** [mdn/browser-compat-data#2629]
The following is displayed when I try to access the browser‑compat‑data migration spreadsheet:
![screenshot_2018-08-19 access denied](https://user-images.githubusercontent.com/3889017/44304327-6a8f6780-a359-11e8-8fc6-4982c1839f40.png)

**Comment by Elchi3** [comment]
I get the same and I think I created the doc (and therefore should be the owner?). Not sure what to do here. Can ownership be "stolen" somehow when sheets are publicly editable?

**Comment by Elchi3** [comment]
We've resolved this thanks to @teoli2003! :tada:

**Comment by ExE-Boss** [comment]
It seems to be accessible again now.
