### ISSUE TITLE
Q: *_support (or safely detect metadata branches)

### ISSUE THREAD

**Issue by epistemex** [mdn/browser-compat-data#2633]
Hi. I noticed several different branches ends in `_support` like the [`worker_support`](https://github.com/mdn/browser-compat-data/blob/master/schemas/compat-data-schema.md#api-specific-subfeatures) .

Is it safe to assume that these (and any future ones) are all (API specific) sub-features when they end in `_support` ?

So far I've found these:
```text
accel_support
animation_and_transition_support
animation_support
blob_data_support
block_level_support
cors_support
custom_text_support
font_stretch_support
pinch-to-zoom_support
pseudo-element_support
region_support
service_workers_support
sharedarraybuffer_support
svg_support
textarea_support
transfer_argument_support
worker_support
```

as well as this one  (under `api.BaseAudioContext.createPeriodicWave`):

    disableNormalisation_supported

and this seem to be one as well (?):

    SharedArrayBuffer_as_param

and of course, in case of the latter, the question is pretty much answered; if so, could we have a flag or something to mark a API specific sub-feature as such?

PS: The dataset start looking pretty good btw!

**Comment by ExE-Boss** [comment]
See @wbamberg’s reply in https://github.com/mdn/browser-compat-data/issues/2568#issuecomment-412690231:
> Sorry to be slow responding.
>
> > are all such nesting ending with _context? I also see some 2d_context, webgl_context etc.
>
> No, there's no convention about this.

**Comment by epistemex** [comment]
Thank you @ExE-Boss but I was probably not clear enough. I'm not asking about naming convention in general, but specifically about these support branches, or rather *metadata* branches.

For example, `Worker` would be a feature, but `worker_support` is not, it just indicates that the feature it's attached to, as a "API specific sub-feature", can be used inside a Worker. And the same with "cors_support", "SharedArrayBuffer_as_param" etc.

The problem in my case is that when you do a search, these metadata entries will show up in the results as well - this produces extra steps for the user (this is in a CLI context), but they don't represent actual features per-se, just metadata which IMO is only useful in context of the actual feature.

I hope to see something that enabled one to reliably filter out these when searching but be able to show them in a accumulated presentation (i.e. table). Right now I would have to more or less guess what to filter based on the name, and as I assumed and as stated, this is not a safe path.

For that reason there would be need for something like a flag, or a string that can be checked to see if the branch in question is an actual feature, or metadata *for* one. Which could just as easily be ignored for those who don't need it, and without any drastic change.

For example, roughly what I have in mind, just as an illustration:
```json
{
  "api": {
    "ImageData": {
      "__compat": {},
      "worker_support": {     // metadata branch
        "__compat": {
          "metadata": true,   // marked here (for example) or above in root of branch
          "description": "Available in workers",
          "support": {}
        }
      }
    }
  }
}
```
or more tedious but less wasteful/more useful (e.g. "search all features that can be used in worker"):

    ...
    "metadata": "worker"
    ...


That way the name itself can be ignored completely but we can reliably see that the current branch is intended to be metadata for its parent feature (there are probably better ways, but just to hopefully indicate more clearly what I mean).

Would this be something that could be considered? Right now the alternative is to build a map/list based entirely on names or even descriptions in the case of worker, and since there is no set pattern nor intent for one, that would not bode well, as they say.

**Comment by epistemex** [comment]
Just adding a few example showing some of these metadata branches are used publicly (but not documented?) and treated in a special way for presentation (table), I assume based off the sub-feature name (?) -

"svg_support", "textarea_support":
https://developer.mozilla.org/en-US/docs/Web/CSS/white-space#Browser_compatibility

"worker_support":
https://developer.mozilla.org/en-US/docs/Web/API/WebGLBuffer#Browser_compatibility

"sharedarraybuffer_as_param":
https://developer.mozilla.org/en-US/docs/Web/API/WebGL2RenderingContext/texImage3D#Browser_compatibility

etc.

**Comment by epistemex** [comment]
(sorry, I am moving a bit between projects so I have to rearrange my head between these posts).

Is the property `description` intended for this purpose? (ala pseudo: `presentation-text = description || propertyname`).

I have assumed description to be a generic description of what the feature does, but the assumption may be wrong? I see that schema address it as a title (which would be a better property name in that case?).

**Comment by epistemex** [comment]
Okay, I see what goes on in the code. There seem to a small undocumented hierarchy when determining when to use the content of `description` vs property name (pseudo):

     presented name = description || property-name

This should probably be documented somewhere as it's not very clear atm.

A follow-up question in that regard: will "description" be used solely for these cases (and if so enable one to detect the branch as a metadata branch), or will this too be an unsafe assumption?

(if anyone wonders what implications this has: I am currently implementing locale support and the description fields are in English only - I'm trying to find a way around but there are too many of these cases to cover properly. It also affects search results in the case of mdncomp as it bases search on flattened api paths and these metadata branches will occasionally be included in the result and not be very useful on its own).
