### ISSUE TITLE
Array.prototype.includes and String.prototype.includes exists in IE 11

### ISSUE THREAD

**Issue by aifrim** [mdn/browser-compat-data#2634]
Found `IE 11.547.16299.0`

```
Array.prototype.includes and
String.prototype.includes evaluates to 
function includes() { [native code] }
```

**Comment by ExE-Boss** [comment]
Fyrd/caniuse#4448

**Comment by connorshea** [comment]
It exists, but that doesn't necessarily mean it's properly supported. 

caniuse says it's unsupported, and [the Edge Status site](https://developer.microsoft.com/en-us/microsoft-edge/platform/status/arrayprototypeincludeses2016/) also lists IE11 as unsupported.

**Comment by ExE-Boss** [comment]
Also, if you discover any incompatibilities, then you should document them in the [`notes`](https://github.com/mdn/browser-compat-data/blob/master/schemas/compat-data-schema.md#notes) section and set [`partial_implementation` to `true`](https://github.com/mdn/browser-compat-data/blob/master/schemas/compat-data-schema.md#partial_implementation).

**Comment by jakub-g** [comment]
For the record, I have a (seemingly) up-to-date Win10 Pro and it has IE `11.1.17134.0` which doesn't have any of those. So it seems dangerous to me to say that "IE 11" supports this. 

BTW Do you use regular version of Windows, or an insider build @aifrim ?

**Comment by ExE-Boss** [comment]
needinfo?(@erikadoyle, @libbymc)

**Comment by aifrim** [comment]
@jakub-g an Insider build apparently.  Was researching something at work and I saw that.
So... that `jscript9.dll` is due for a update, it seems.

**Comment by saschanaz** [comment]
![image](https://user-images.githubusercontent.com/3396686/46604441-3f432080-cb31-11e8-974c-e358680765ec.png)

Unavailable in IE 11.1000.18252.0.

**Comment by jakub-g** [comment]
@Elchi3 IMO this ticket can be safely closed at this point - publicly available versions of IE11 do not support `Array.prototype.includes()`.
