### ISSUE TITLE
WebExtensions & Installed Progressive Web Apps on Firefox for Android

### ISSUE THREAD

**Issue by ohenepee** [mdn/browser-compat-data#2648]
Are WebExtensions loaded and reachable (communicate-able) from device-installed PWAs in Firefox for Android?

@Loirooriol I'm tagging you b'cos all over the Mozilla IRC channels (`#mobile`, `#extdev`, `#webextensions`, `#addons`) no one seem to know much about the two technologies combined... I keep getting redirected from one channel to the other and yet know one seems to know the answer.

**Comment by Loirooriol** [comment]
@ohenepee Sorry, I have never used device-installed PWAs in Firefox for Android, so I don't have much idea either. Maybe https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_messaging?

**Comment by ExE-Boss** [comment]
I would think that they do if they have the right host permissions.

**Comment by ohenepee** [comment]
I've tested several webextensions on Firefox for Android and none seems to work on PWAa, however since I don't have the source code to these webextensions I can't draw any solid conclusions... maybe someone else can try.

**Comment by marcelklehr** [comment]
I don't think Webextension APIs are accessible by PWAs. It's two different things.

**Comment by queengooborg** [comment]
PWAs, along with any website, doesn't have access to Web Extension APIs, no.  Web Extension APIs may only be accessed through a web extension.
