### ISSUE TITLE
Missing compat data for HTMLMediaElement.play() returning a Promise

### ISSUE THREAD

**Issue by dharFr** [mdn/browser-compat-data#2649]
The browser compatibility data from https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/play is missing data about the when browsers started returning a `Promise`.

The lastest available information on MDN seems to be from this revision: https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/play$revision/1328923

**Comment by jakub-g** [comment]
Compat data I managed to figure out so far:

Chrome 50 https://www.chromestatus.com/feature/5920584248590336
Firefox 53 https://bugzilla.mozilla.org/show_bug.cgi?id=1244768
Safari: shipped May 2016 in webkit, not sure about exact version of Safari when it landed https://bugs.webkit.org/show_bug.cgi?id=157400
Edge: Edge 17 returns Promise, not sure when it was shipped
IE11: `undefined`

**Comment by dharFr** [comment]
It seems to be available since Safari 5 (from [safari release notes](https://developer.apple.com/safari/technology-preview/release-notes/))

**Comment by connorshea** [comment]
Preview 5 was released May 25, 2016: https://webkit.org/blog/6415/release-notes-for-safari-technology-preview-5/

Based on the fact that [Safari 9.1 released in March 2016](https://webkit.org/blog/6008/new-web-features-in-safari/) and 10.1 released [with changes from previews 14 through 20](https://webkit.org/blog/7477/new-web-features-in-safari-10-1/), that means it must have been added in Safari 10. For whatever reason the WebKit blog had no post for Safari 10 🤷‍♂️
