### ISSUE TITLE
Migrate remaining CSS compat data

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#2684]
This might not be everything remaining in terms of CSS compat data, but it's all I've found so far. 
Need to decide if we want to migrate this over, or merge into existing data, or delete the page, etc.

See below for an updated checklist, https://github.com/mdn/browser-compat-data/issues/2684#issuecomment-421428277

**Comment by ExE-Boss** [comment]
For most of the `-moz-` prefixed properties, I’d probably recommend moving those under the `/docs/Mozilla/` tree.

**Comment by caugner** [comment]
I will migrate the `box-*` properties.

**Comment by ExE-Boss** [comment]
I’ve now created the https://developer.mozilla.org/docs/Mozilla/Gecko/Chrome/CSS page to complement @chrisdavidmills’s https://developer.mozilla.org/docs/Mozilla/Gecko/Chrome/API page, to which internal CSS properties can be moved to.

**Comment by connorshea** [comment]
Should the [`-webkit-mask-composite`](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-mask-composite) article be merged into [`mask-composite`](https://developer.mozilla.org/en-US/docs/Web/CSS/mask-composite)? The APIs are very different, but they do have the same name.

**Comment by connorshea** [comment]
I've opened #2773 to add data for [`-webkit-mask-repeat-x`](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-mask-repeat-x), [`-webkit-mask-repeat-y`](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-mask-repeat-y), and [`-webkit-mask-position-x`](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-mask-position-x).

**Comment by connorshea** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/:-ms-input-placeholder was also redirected

**Comment by championshuttler** [comment]
Hi i want to contribute to it , can any one help how can i get started ?

**Comment by championshuttler** [comment]
Hi all added a PR for https://developer.mozilla.org/en-US/docs/Web/CSS/-moz-image-region [here](https://github.com/mdn/browser-compat-data/pull/2825/)

**Comment by connorshea** [comment]
@championshuttler I think you meant to link #2853?

**Comment by championshuttler** [comment]
@connorshea yeah , sorry i forgot to add the issue no.

**Comment by vinyldarkscratch** [comment]
Just submitted two PRs to aid with this issue, as shown right above this comment.  That only leaves one remaining page in need of migration: `repeating-radial-gradient`!

**Comment by connorshea** [comment]
7 CSS properties left to merge! 🎉

**Comment by Elchi3** [comment]
Found one more https://developer.mozilla.org/en-US/docs/Web/CSS/max-block-size#Browser_compatibility

**Comment by connorshea** [comment]
This is complete now :D 

The max-block-size article needs to be updated. Other than that, the only pages remaining for CSS are pages without existing tables.

**Comment by Elchi3** [comment]
Thanks for the help everyone! :tada:
