### ISSUE TITLE
CSS Scroll Snap compatibility

### ISSUE THREAD

**Issue by connorshea** [mdn/browser-compat-data#2762]
[Chrome Status](https://www.chromestatus.com/feature/5721832506261504) says that support for the W3C candidate recommendation of the spec was implemented in Chrome 69. It also mentions:

>As of June 2018: IE, Edge, and Firefox ship a deprecated version of the specification, Safari ships the current CR specification which is what Chrome implements as well.

This isn't quite what the current compat data reports, e.g. see [this MDN article](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-snap-type#Browser_compatibility). I'm not sure how to determine what's correct since there are multiple different implementations of different versions of the spec across different browsers, so I figured I'd open an issue instead of a PR for now :)

See also [caniuse](https://caniuse.com/#feat=css-snappoints)

**Comment by saschanaz** [comment]
MDN lacks new updated properties including `scroll-margin`.

**Comment by Elchi3** [comment]
I think we're done here now thanks to @rachelandrew. 
Rachel, `scroll-margin` and friends got done, right? Do you think the compat data is up-to-date?

**Comment by Elchi3** [comment]
Thanks Rachel, let's close this issue then.
Connor, please let us know if there is more work left to be done here.
