### ISSUE TITLE
Edge properties/methods on HTMLElement, not Element.

### ISSUE THREAD

**Issue by RichTeaTime** [mdn/browser-compat-data#2766]
In Edge 40.15063.674.0 (EdgeHTML 15.15063), the following methods are defined on the HTMLElementPrototype, not the ElementPrototype:

- getElementsByClassName
- insertAdjacentElement
- insertAdjacentHTML
- insertAdjacentText
- scrollIntoView

This means that these methods cannot be applied on non-HTMLElement elements, e.g. SVGElement subclasses.

**Comment by vinyldarkscratch** [comment]
Looks like in Edge 18, these were moved to the Element prototype -- beforehand, they were on the HTMLElement prototype as you mention.  Will submit a PR to fix this!
