### ISSUE TITLE
Add documentation and linter for escaping HTML in the `notes` property

### ISSUE THREAD

**Issue by connorshea** [mdn/browser-compat-data#2799]
Currently we don't use the linter to automatically check for HTML elements in the data files, nor do we have documentation on escaping HTML elements in the data files. ([The docs do mention that you _can_ use `a` and `code`, but they say nothing about any other elements](https://github.com/mdn/browser-compat-data/blob/28f01acf62c205d53415c3f5da26a5847e90bdc0/schemas/compat-data-schema.md#notes))

Examples:

- https://github.com/mdn/browser-compat-data/pull/2776#discussion_r216154175
- https://github.com/mdn/browser-compat-data/pull/2770#discussion_r216065017
- https://github.com/mdn/browser-compat-data/pull/2211#discussion_r197425652

An unescaped `<button>` element actually made it into the `input type="submit"` data (it was mentioned in review but never fixed):

https://github.com/mdn/browser-compat-data/blob/28f01acf62c205d53415c3f5da26a5847e90bdc0/html/elements/input/submit.json#L24

`<a href='url-not-important'>persists the dynamic disabled state</a> of a <code><button></code> across page loads`

I didn't really think about this with my explorer app (my bad, admittedly), so theoretically this could be used to inject scripts into a site (or editor, e.g. VS Code) that uses the data: 

<img width="517" alt="screen shot 2018-09-10 at 12 08 50 pm" src="https://user-images.githubusercontent.com/2977353/45315763-6f77af00-b4f2-11e8-8a39-f7603765ceb0.png">

MDN handles it better, but oddly adds a closing tag as well?

<img width="1072" alt="screen shot 2018-09-10 at 12 09 47 pm" src="https://user-images.githubusercontent.com/2977353/45315764-70104580-b4f2-11e8-9519-cdb2cfa0acc0.png">

Two main things we should do here:

- Add a linter rule to fail on cases like this (excluding `a` and `code`, maybe others I'm forgetting?), because using regex to parse HTML is _so_ easy :P 
- Add docs that mention the best way to escape HTML elements when using them in the BCD notes (e.g. replacing `<code><button></code>` with `<code>&lt;button&gt;</code>`?)

Alternatively, we could just make sure the docs warn third party implementors that we don't guarantee the safety of the data files and that they should only allow `a` and `code` in notes/descriptions, and no other HTML elements.

**Comment by vinyldarkscratch** [comment]
Started off some regex to use as a pattern, however for some reason the `$` causes the test to instantly freeze.  I thought I'd leave it here anyways, just to give something to possibly work off of!

```regex
^(([^<>]+)|(([^<>]?)(<(a|code)[^>]*>)([^<>]+)(<\/(a|code)>)([^<>]?)))+$
```
