### ISSUE TITLE
Convert HTML compat data from in-page in MDN to JSON Format

### ISSUE THREAD

**Issue by teoli2003** [mdn/browser-compat-data#280]
We have pretty extensive HTML compat info  on MDN and we should convert it to the JSON format.

To coordinate the work, I've created this spreadsheet: https://docs.google.com/spreadsheets/d/1ivgyPBr9Lj3Wvj5kyndT1rgGbX-pGggrxuMtrgcOmjM/edit#gid=0

**Comment by Elchi3** [comment]
The input element is the only one missing and we are using the sheet to track the migration work. Lets close this.
