### ISSUE TITLE
Publish “built” form of BCD that includes MDN articles titles, summaries (and spec URLs), like epistemex/mdncomp-data

### ISSUE THREAD

**Issue by sideshowbarker** [mdn/browser-compat-data#2836]
It would be useful to have an enhanced form of BCD that included not only the static data maintained in this repo but also the titles and (seo)summaries from the corresponding MDN articles.

Providing such a distribution could require some build step that pulled/scraped the corresponding MDN article titles and summaries from MDN itself.

Also, until the `spec_urls` data (as discussed in #1336 and #1531) is added/moved to BCD, the build would need for now to also pull the spec-URL data from MDN itself.

https://github.com/epistemex/mdncomp-data already provides such a distribution, with the MDN summaries and spec URLs — and may [eventually also include the article titles](https://gitlab.com/epistemex/mdncomp/issues/2) — but I hope that the MDN staff team can consider providing the same thing upstream in some way.

**Comment by Elchi3** [comment]
Basically you're asking for MDN as structured data and we agree that we should go down that path. We have no ETA for it, but it is likely that we will come up with something and then load in BCD into that project to provide compat data and spec links. It is certainly a bigger thing than BCD itself, so this repo isn't a good place to design these API and to brainstorm on such a project. I will let you know when we have more concrete design documents on this idea.
