### ISSUE TITLE
Did Firefox 36 hide `will-change` behind a flag?

### ISSUE THREAD

**Issue by saschanaz** [mdn/browser-compat-data#2854]
Currently [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/will-change) says Firefox 36 added `will-change` and then Firefox 31-43 hid it behind a flag. This is weird, probably a mistake?

**Comment by Elchi3** [comment]
I guess it means that the preference was removed in 43. So, you can't turn it off anymore using said flag. The default enabling was in 36, but the preference wasn't entirely removed then, only in 43. I'm not sure if this is useful the way it is in the data or if we should have the flag from version 31-36.

**Comment by vinyldarkscratch** [comment]
It looks like this was a not-so-good import of the original docs.  Right before switching to the new compat table macro, there was a footnote for Firefox stating the following:

> [1] From Firefox 31 to 35, will-change was available, but only if the user flipped the layout.css.will-change.enabled flag to true. The preference has been removed in Firefox 43.
