### ISSUE TITLE
There is no IE beyond IE11 yet IE15 appears in browser compatibility

### ISSUE THREAD

**Issue by Eccenux** [mdn/browser-compat-data#287]
Hi.

In generated browser compatibility data Internet Explorer appears to have a version 15. E.g.:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/padEnd
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/padStart

IE11 is said to be the last version and IIRC first Edge was internally 13 (or 14 I'm not sure). So they skipped a version probably leaving a gap to release IE12...

In any case there is no IE15 and browser compatibility tables generated are misleading. For IE it should say "No support" like e.g. here:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/values#Browser_compatibility

**Comment by Elchi3** [comment]
You're absolutely right; this is a mistake in the data. It has been fixed in #286 and will be deployed soon.
Thanks for letting us know!
