### ISSUE TITLE
Fixed incorrectly classified top level en-US documents

### ISSUE THREAD

**Issue by ExE-Boss** [mdn/browser-compat-data#2887]
The following en-US documents were incorrectly classified as [top-level](https://web.archive.org/web/20180929123935/https://developer.mozilla.org/en-US/docs/top-level) ([I took the&nbsp;snapshot after I&nbsp;fixed most of&nbsp;these](https://developer.mozilla.org/en-US/docs/top-level)):

## Web:
- [Web/API/BluetoothDevice](https://developer.mozilla.org/en-US/docs/Web/API/BluetoothDevice)
- [Web/API/BluetoothDevice/name](https://developer.mozilla.org/en-US/docs/Web/API/BluetoothDevice/name)
- [Web/API/BluetoothDevice/paired](https://developer.mozilla.org/en-US/docs/Web/API/BluetoothDevice/paired)
- [Web/API/BluetoothDevice/uuid](https://developer.mozilla.org/en-US/docs/Web/API/BluetoothDevice/uuid)
- [Web/API/RTCTrackEvent/transceiver](https://developer.mozilla.org/en-US/docs/Web/API/RTCTrackEvent/transceiver)
- [Web/API/SVGFEColorMatrixElement](https://developer.mozilla.org/en-US/docs/Web/API/SVGFEColorMatrixElement)
- [Web/API/MediaCapabilities](https://developer.mozilla.org/en-US/docs/Web/API/MediaCapabilities)
- [Web/API/Media_Capabilities_API](https://developer.mozilla.org/en-US/docs/Web/API/Media_Capabilities_API)

## Mozilla:
- [Mozilla/Add-ons/WebExtensions/API/bookmarks/export](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/bookmarks/export) (incidentally, this one is nearly identical to [Archive/Add-ons/bookmarks.export](https://developer.mozilla.org/en-US/docs/Archive/Add-ons/bookmarks.export))
- [Mozilla/Firefox/Enterprise_deployment](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Enterprise_deployment)

To solve this, I moved each page under [Sandbox](https://developer.mozilla.org/en-US/docs/Sandbox) and then back to the original location.

**Comment by Elchi3** [comment]
Thanks for the work, but what is this issue about? Do we need compat data for any of this?

**Comment by ExE-Boss** [comment]
Most of this is already done or has a PR open, with the exception of [`browser.bookmarks.export(…)`](https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/API/bookmarks/export).
