### ISSUE TITLE
Broken link to README.md needs fixing on MDN

### ISSUE THREAD

**Issue by SamB** [mdn/browser-compat-data#29]
The URL <https://github.com/mdn/browser-compat-data/README.md>, which I found hidden on <https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition$edit> in a way that leads me to suspect that it is also found on many other pages, unfortunately _does not actually work_.

I suspect <https://github.com/mdn/browser-compat-data#readme> would do nicely, but lack the means to do a global search/replace on MDN (and anyway, it's safer to get bulk edits reviewed *before* they are done).

**Comment by Elchi3** [comment]
Grr. My mistake! Thanks for filing this. I will take a look.

**Comment by Elchi3** [comment]
Fixed.
