### ISSUE TITLE
Contribution is unclear

### ISSUE THREAD

**Issue by marcoscaceres** [mdn/browser-compat-data#2908]
A little context: I'm a specification editor and I want to make sure data gets updated as stuff lands in the specs I work on. 

However, reading: https://github.com/mdn/browser-compat-data/blob/master/CONTRIBUTING.md

I'm not sure how to update the data (or what process went into gathering the initial data)? Obviously, I can do it manually... but that seems extremely error prone. Is there some tool I can use to help me with this?

**Comment by jpmedley** [comment]
Specs themselves are listed here: https://github.com/mdn/kumascript/blob/master/macros/SpecData.json

I apologize that you'll need to infer the correct status abbreviation. We've never created a schema for this.

As for the BCD data there is no automated way to do it. As far as I can remember, you're the first spec author to volunteer. So thank you for that. A couple of things though.

Somewhere in one of Google's public github repos is an IDL scraper for specs. I can see if I can find it, but it doesn't output BCD data.

Second, and this is the most important thing, you really don't want to add data for unimplemented specs. They may or may not get implemented, or they may change before they get implemented. All of which is extra noise and maintenance. (Incidentally, we absolutely do not document unimplemented features on MDN.)

I work for Google, but my job is _Web_ documentation not necessarily _Chrome_ documentation. Feel free to reach out to me for help or questions as your spec advances. jmedley@google.com

**Comment by Elchi3** [comment]
> Somewhere in one of Google's public github repos is an IDL scraper for specs. I can see if I can find it, but it doesn't output BCD data.

WebIDL to BCD is here: https://github.com/dontcallmedom/webidl2mdnbcd

> Second, and this is the most important thing, you really don't want to add data for unimplemented specs. 

I agree to this.

**Comment by Elchi3** [comment]
Closing this. Not sure how we could further help here. Haven't heard this again in the last few months. Please re-open if there are new ideas that could help spec authors. Sideshowbarker might be a good spec person to talk to as well given his frequent contributions and tooling he's built.
