### ISSUE TITLE
Add tabHide permission to compat table

### ISSUE THREAD

**Issue by mconca** [mdn/browser-compat-data#2913]
The tabHide permission needs to be added to the compat table for WebExtensions manifest permissions.  It should show it as available only in Firefox since version 61.

**Comment by vinyldarkscratch** [comment]
Happy to get this in.  May I ask where you've sourced your information from?  Also, is it just Firefox, or does Firefox Android also apply?

**Comment by mconca** [comment]
I'm the Product Manager for the WebExtensions API, so ... I guess I'm my own source?

Alternatively, here is the original implementation bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1423725

And it is desktop only, no Android support.  Thanks!

**Comment by vinyldarkscratch** [comment]
...I totally should have looked at your profile, haha.  Whoops!

Submitting a PR now.  :wink:
