### ISSUE TITLE
Upgrade to latest ajv major version

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#2921]
We're using https://www.npmjs.com/package/ajv as our JSON schema validator. It comes with a new major version 6 and which we should upgrade to it. I haven't read the changelog yet, but maybe things got faster or maybe there are new features which we could be using.

**Comment by ExE-Boss** [comment]
I might be able to get this done as part of #2338.

**Comment by Elchi3** [comment]
Thanks, https://github.com/mdn/browser-compat-data/pull/2338 is now merged.
