### ISSUE TITLE
WorkerNavigator.sendBeacon() was dropped from the spec and has never been implemented

### ISSUE THREAD

**Issue by sideshowbarker** [mdn/browser-compat-data#2953]
See https://github.com/w3c/beacon/issues/37 and https://github.com/w3c/beacon/commit/95e6a1f0efb7f374ab8fae20f30b79ce412deed4

**Comment by Elchi3** [comment]
Let remove the data and the MDN page then.

**Comment by tristangio** [comment]
There is some remaining references of WorkerNavigator.sendBeacon : 
- https://developer.mozilla.org/en-US/docs/Web/API/Beacon_API/Using_the_Beacon_API#WorkerNavigator.sendBeacon()
- https://developer.mozilla.org/en-US/docs/Web/API/Beacon_API#Worker_context

**Comment by Elchi3** [comment]
@tristangio could file a new content issue for that? https://github.com/mdn/sprints/issues/new?template=issue-template.md&projects=mdn/sprints/2&labels=user-report&title=https%3A//developer.mozilla.org/en-US/docs/Web/API/Beacon_API/Using_the_Beacon_API

**Comment by tristangio** [comment]
[Done](https://github.com/mdn/sprints/issues/1736), sorry for the delay
