### ISSUE TITLE
Mapping of Safari Tech Previews to actual Safari releases?

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#2991]
The Safari docs and support information sources are sparse. This makes it hard to review data update PRs. The Safari TP release notes are quite good, however. Does anyone know how you can map TP versions to actual Safari versions?

What we know:
TP 1-13: Safari 10
TP 14-20: Safari 10.1
TP 21-36: Safari 11
TP 37-47: Safari 11.1
TP 48-58: Safari 12
TP 59-76: Safari 12.1
TP 77-89: Safari 13
TP 90-98: Safari 13.1
TP 99-109: Safari 14
TP 110-122: Safari 14.1
TP 123-129: Safari 15

**Comment by a2sheppy** [comment]
That's a good idea, potentially.

The bigger problem in the short term, I think, is that we currently have no way to indicate that a feature landed in a particular TP version. The notion of the browser actually having different version number standards in its developer build releases is not something our schema allows for.

**Comment by Elchi3** [comment]
Good news, everyone! At least for Safari 12.1 Apple provides us with such a mapping, see the release notes: https://webkit.org/blog/8718/new-webkit-features-in-safari-12-1 all the way down to "Feedback":

"Changes in this release of Safari were included in the following Safari Technology Preview releases: 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76."

So, that's a lot of features we could mark as "12.1".

**Comment by Elchi3** [comment]
For Safari 11: 

"Changes in this release of Safari were included in the following Safari Technology Preview releases: 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36."

Source: https://webkit.org/blog/7956/new-webkit-features-in-safari-11/

**Comment by vinyldarkscratch** [comment]
For Safari 10.1:

"The changes included in this release of Safari span Safari Technology Preview releases 14, 15, 16, 17, 18, 19, and 20."

Source: https://webkit.org/blog/7477/new-web-features-in-safari-10-1/

**Comment by craigkovatch** [comment]
Apple also removed the release notes for Safari under 12 from their developer pages :( Anyone have a contact there they could ping?

**Comment by vinyldarkscratch** [comment]
The following blog post makes it sound like Safari TP 84 is when changes are frozen for Safari 13's release: https://webkit.org/blog/9170/safari-technology-preview-84-with-safari-13-features-is-now-available/

**Comment by a2sheppy** [comment]
We should start archiving copies of release notes for browsers, so that we have access to them even if the developer decides to remove them from their site.

**Comment by Elchi3** [comment]
https://webkit.org/blog/9674/new-webkit-features-in-safari-13/ says "changes in this release of Safari were included in the following Safari Technology Preview releases: 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89."

Thus updated our mapping for Safari 13. 
Still waiting on something for Safari 13.1.

**Comment by jculver050** [comment]
Close

**Comment by LeaVerou** [comment]
Tried to update compat data for various color features that were introduced in Safari TP [120](https://webkit.org/blog/11548/release-notes-for-safari-technology-preview-120/) and [121](https://webkit.org/blog/11555/release-notes-for-safari-technology-preview-121/), but since they haven't launched yet, I'm not sure what Safari version to add. Any ideas?

**Comment by vinyldarkscratch** [comment]
We've yet to allow data to be added for Safari TP versions, but are now working on it -- see https://github.com/mdn/browser-compat-data/pull/10334.

**Comment by Elchi3** [comment]
This is resolved now given we allow "preview" as a version number. 

The Safari team has also updated "preview" values to the actual Safari version numbers whenever a feature ships in Safari stable.
