### ISSUE TITLE
References to Chrome Runtime Flags should use link form instead of text form.

### ISSUE THREAD

**Issue by jpmedley** [mdn/browser-compat-data#2992]
Chrome runtime flags (accessed at chrome://flags have two forms: a string that appears as a heading and  a URL anchor form. Google prefers that the anchor form be used because it's less likely to change than the string form.

This ticket is to track two tasks made at @Elchi3's request:

* Document this preference in an appropriate place. (In the schema documentation?)
* Make this testable so that existing and future references to flags will be corrected. (Schema change?)

**Comment by jpmedley** [comment]
@Elchi3 Can you please hold off on updating the linter until you hear from me again. Many of our flags are not intended for tire kicking. We are working on pulling that information from Chrome Status. This request may turn out to be 'don't allow Chrome flags.' I'll keep you posted.

**Comment by Elchi3** [comment]
I never heard back from Joe and there was also no answer from Joe in recent PRs on this issue. See e.g. https://github.com/mdn/browser-compat-data/pull/5504#issuecomment-601209491

Closing.
