### ISSUE TITLE
Macro HTML/CSS feedback.

### ISSUE THREAD

**Issue by stephaniehobson** [mdn/browser-compat-data#30]
Trying to get feedback on the HTML structure in early - but only because I am assuming it's hard to refresh the pages with the macro on them. If it's easy to refresh those pages this can all be adjusted later.

**Put row headings into a <th scope="row"> tag.**

`<th scope="row">Basic Support</th>`

**Don't include the zone in the class names**

Namespacing for zone specific classes is usually a good idea :) Since in this case we want this code to be used in other zones eventually, if you pick a more universal name space we can move the classes to the global style sheets more easily when they're ready.

I suggest `.ct` for compat-table.

**Rather than hard coding widths on the browser name cells, add classes to indicate they are browser names and add a parent class to the table to indicate how wide they should be.**

```
<table class="ct-summary ct-browsers-5">
```

```
<th class="ct-browser">
```

```
.ct-browsers-5 .ct-browser { width: 12%; }
```

This will make it easier to to adjust the tables for mobile display and change widths globally if we want to.

**Use a consistent namespace for all CSS classes**

```
.ct-summary
.ct-browser
.ct-support-full
.ct-support-unknown 
.ct-support-no
```

**Comment by Elchi3** [comment]
Stephanie, thanks for your feedback. I think we'll have a fresh start at designing the tables on MDN and that's not an issue for this repository. Here it is all about data only. Closing.
