### ISSUE TITLE
Chrome supports inline-size/block-size

### ISSUE THREAD

**Issue by saschanaz** [mdn/browser-compat-data#3005]
Related bug: https://bugs.chromium.org/p/chromium/issues/detail?id=538475

**Comment by jpmedley** [comment]
Is

**Comment by cartinez** [comment]
Apparently Opera and Chrome/Opera for Android support this too.

**Comment by Elchi3** [comment]
Fixed in https://github.com/mdn/browser-compat-data/pull/3012
