### ISSUE TITLE
Firefox’s support for the CSS property flex is confusing

### ISSUE THREAD

**Issue by jaller94** [mdn/browser-compat-data#3008]
The support list for the CSS property `flex` in Firefox has issues:

1. The list seems unordered. The version ranges described should have some ascending or descending order.
2. I cannot see what version of Firefox fully supported flex.

https://github.com/mdn/browser-compat-data/blob/ab222f95f5b453014e9e75e238c8952558221737/css/properties/flex.json#L44

**Comment by saschanaz** [comment]
Firefox 20 added the support in prefix-less way, and then later it added webkit prefix for compatibility.

But do we really need to list the webkit thing here? 🤔

**Comment by vinyldarkscratch** [comment]
Took me a little bit to diagnose what was going on here, and it looks like it was possibly a bad import from MDN.  I was able to restructure the data a little bit and fix the issue, PR incoming
