### ISSUE TITLE
Idea: tooltip showing info such as browser release date when hovering over browser version number (or a link to a page)

### ISSUE THREAD

**Issue by hi2u** [mdn/browser-compat-data#3030]
While most of us who do a lot of web development have a vague idea on roughly when versions of IE came out (without needing to look it up), it's much less memorable with the other browsers/devices.

My idea wouldn't require a design change to the normal display of the table, but it would be really handy if when hovering my mouse over the browser version number, it shows a tooltip with that version's release date.

Additionally maybe even some extra info too?

For example, hovering over IE11 could show a tooltip such as:

```
Release date: 2013-10-17
Bundled with: Windows 8.1
```

Alternatively (or additionally)... instead of a tooltip, maybe just clicking on the version number could go to a page with this info, and some relevant market share stats, maybe EOL dates (for those that exist).

**Comment by atopal** [comment]
This come up again last week during the PAB meeting and we generally agreed that it would be a useful addition. Tooltip is fine for now.

**Comment by jpmedley** [comment]
Here's the Chrome release dates. 

Version	Feature Freeze	Beta	Stable	Quarter	Landmark
73	Jan 11, 2019			Q1	
72	Nov 9, 2018	Dec 13, 2018			Jelly Bean no longer supported. ↑
71	Sep 28, 2018	Oct 25, 2018	Dec 4, 2018	Q4	
70	Aug 17, 2018	Sep 13, 2018	Oct 16, 2018		
69	Jun 22, 2018	Aug 2, 2018	Sep 4, 2018	Q3	
68	May 11, 2018	Jun 7, 2018	Jul 19, 2018		
67	Mar 30, 2018	Apr 26, 2018	May 29, 2018	Q2	
66	Feb 16, 2018	Mar 15, 2018	Apr 17, 2018		
65	Jan 5, 2018	Feb 1, 2018	Mar 6, 2018	Q1	
64	Nov 10, 2017	Dec 14, 2018	Jan 23, 2018		
63	Sep 29, 2017	Oct 26, 2017	Dec 5, 2018	Q4	
62	Aug 18, 2017	Sep 14, 2017	Oct 17, 2017		
61	Jun 23, 2017	Aug 3, 2017	Sep 5, 2017	Q3	
60	May 12, 2017	Jun 8, 2017	Jul 25, 2017		
59	Mar 31, 2017	Apr 27, 2017	May 30, 2017	Q2	
58	Feb 17, 2017	Mar 16, 2017	Apr 13, 2017		
57	Jan 6, 2017	Feb 2, 2017	Mar 7, 2017	Q1	
56	Nov 4, 2016	Dec 8, 2016	Jan 24, 2017		
55	Sep 23, 2016	Oct 20, 2016	Nov 29, 2016	Q4	
54	Aug 12, 2016	Sep 8, 2016	Oct 11, 2016		
53	Jun 17, 2016	Jul 28, 2016	Aug 30, 2016	Q3	
52	May 6, 2016	Jun 2, 2016	Jul 19, 2016		
51	Mar 25, 2016	Apr 21, 2016	May 24, 2016	Q2	
50	Feb 12, 2016	Mar 10, 2016	Apr 12, 2016		
49	Dec 18, 2015	Jan 28, 2016	Mar 1, 2016	Q1	
48	Oct 30, 2015	Dec 3, 2015	Jan 19, 2015		
47	Sep 18. 2015	Oct 15, 2015	Nov 17, 2015	Q4	
46	Aug 7, 2015	Sep 3. 2015	Oct 6, 2015		
45	June 12, 2015	Jul 23, 2015	Aug 25, 2015	Q3	
44	May 1, 2015	May 28, 2015	Jul 14, 2015		Android 4 (Ice Cream Sandwich) no longer supported. ↑
43	Mar 20, 2015	Apr 16, 2015	May 19, 2015	Q2	
42	Feb 6, 2015	Mar 5, 2015	Apr 7, 2015		
41	Dec 12, 2014	Jan 22, 2015	Feb 24, 2015	Q1	
40	Oct 24, 2014	Nov 20, 2014	Jan 13, 2015		
39	Sep 12, 2014	Oct 9, 2014	Nov 11, 2014	Q4	
38	Aug 1, 2014	Aug 28, 2014	Sep 30, 2014		
37	June 6, 2014	Jul 17, 2014	Aug 19, 2014	Q3	webview=chromium ↑
36	Apr 25, 2014	May 22, 2014	Jun 24, 2014		
35	Mar 14, 2014	Apr 10, 2014	May 13, 2014	Q2	
34	Jan 31, 2014	Feb 27, 2014	Apr 1, 2014		
33	Dec 6, 2013	Jan 16, 2014	Feb 18, 2014	Q1	
32	Oct 18, 2013	Nov 14, 2013	Jan 7, 2014		
31	Sep 6, 2013	Oct 3, 2013	Nov 5, 2013	Q4	
30	Jul 26, 2013	Aug 22, 2013	Sep 24, 2013		
29	June 7, 2013	Jul 11, 2013	Aug 13, 2013	Q3	
28	Apr 19, 2013	May 23, 2013	Jun 25, 2013		Blink ↑
27	Mar 8, 2013	Apr 4, 2013	May 7, 2013	Q2	Webkit ↓
26	Jan 25, 2013	Mar 26, 2013	Mar 26, 2013		
25	Nov 30, 2012	Jan 10, 2013	Feb 12, 2013	Q1	
24	Oct 12, 2012	Nov 8, 2012	Dec 18, 2012		
23	Aug 31, 2012	Sep 27, 2012	Oct 30, 2012	Q4	
22	Jul 20, 2012	Aug 16, 2012	Sep 18, 2012		
21	June 1, 2012	Jun 28, 2012	Aug 7, 2012	Q3	
20	Apr 20, 2012	May 17, 2012	Jun 19, 2012		
19	Mar 9, 2012	Apr 5, 2012	May 8, 2012	Q2	
18	Jan 13, 2012	Feb 9, 2012	Mar 13, 2012		First Chrome Android (6/27) ↑
17	Nov 11, 2011	Dec 15, 2011	Jan 31, 2012	Q1	
16	Sep 30, 2011	Oct 27, 2011	Dec 6, 2011		
15	Aug 19, 2011	Sep 15, 2011	Oct 18, 2011	Q4	
14	June 24, 2011	Aug 4, 2011	Sep 6, 2011		
13	May 13, 2011	June 9, 2011	Jul 26, 2011	Q3	
12	Apr 1, 2011	April 28, 2011	May 31, 2011		
11	Feb 18, 2011	Mar 17, 2011	Apr 19, 2011	Q2	
10	Jan 7, 2011	Feb 3, 2011	Mar 8, 2011		
9	Nov 5, 2010	Dec 9, 2010	Jan 25, 2011	Q1	
8	Sep 24, 2010	Oct 21, 2010	Nov 30, 2010		
7	Aug 13, 2010	Sep 9, 2010	Oct 12, 2010	Q4	
6	Unknown	Unknown	Sep 2, 2010	Q3	
5	Unknown	Unknown	May 25, 2010	Q2	
4	Unknown	Unknown	Jan 25, 2010	Q1	
3	Unknown	Unknown	Sep 15, 2009	Q3	
2	Unknown	Unknown	May 21, 2009	Q2	
1	Unknown	Unknown	Sep 2008	Q3

**Comment by jpmedley** [comment]
Here are Chrome release dates.
Version,Feature Freeze,Beta,Stable,Quarter,Landmark
73,"Jan 11, 2019",,,Q1,
72,"Nov 9, 2018","Dec 13, 2018",,,Jelly Bean no longer supported. ↑
71,"Sep 28, 2018","Oct 25, 2018","Dec 4, 2018",Q4,
70,"Aug 17, 2018","Sep 13, 2018","Oct 16, 2018",,
69,"Jun 22, 2018","Aug 2, 2018","Sep 4, 2018",Q3,
68,"May 11, 2018","Jun 7, 2018","Jul 19, 2018",,
67,"Mar 30, 2018","Apr 26, 2018","May 29, 2018",Q2,
66,"Feb 16, 2018","Mar 15, 2018","Apr 17, 2018",,
65,"Jan 5, 2018","Feb 1, 2018","Mar 6, 2018",Q1,
64,"Nov 10, 2017","Dec 14, 2018","Jan 23, 2018",,
63,"Sep 29, 2017","Oct 26, 2017","Dec 5, 2018",Q4,
62,"Aug 18, 2017","Sep 14, 2017","Oct 17, 2017",,
61,"Jun 23, 2017","Aug 3, 2017","Sep 5, 2017",Q3,
60,"May 12, 2017","Jun 8, 2017","Jul 25, 2017",,
59,"Mar 31, 2017","Apr 27, 2017","May 30, 2017",Q2,
58,"Feb 17, 2017","Mar 16, 2017","Apr 13, 2017",,
57,"Jan 6, 2017","Feb 2, 2017","Mar 7, 2017",Q1,
56,"Nov 4, 2016","Dec 8, 2016","Jan 24, 2017",,
55,"Sep 23, 2016","Oct 20, 2016","Nov 29, 2016",Q4,
54,"Aug 12, 2016","Sep 8, 2016","Oct 11, 2016",,
53,"Jun 17, 2016","Jul 28, 2016","Aug 30, 2016",Q3,
52,"May 6, 2016","Jun 2, 2016","Jul 19, 2016",,
51,"Mar 25, 2016","Apr 21, 2016","May 24, 2016",Q2,
50,"Feb 12, 2016","Mar 10, 2016","Apr 12, 2016",,
49,"Dec 18, 2015","Jan 28, 2016","Mar 1, 2016",Q1,
48,"Oct 30, 2015","Dec 3, 2015","Jan 19, 2015",,
47,Sep 18. 2015,"Oct 15, 2015","Nov 17, 2015",Q4,
46,"Aug 7, 2015",Sep 3. 2015,"Oct 6, 2015",,
45,"June 12, 2015","Jul 23, 2015","Aug 25, 2015",Q3,
44,"May 1, 2015","May 28, 2015","Jul 14, 2015",,Android 4 (Ice Cream Sandwich) no longer supported. ↑
43,"Mar 20, 2015","Apr 16, 2015","May 19, 2015",Q2,
42,"Feb 6, 2015","Mar 5, 2015","Apr 7, 2015",,
41,"Dec 12, 2014","Jan 22, 2015","Feb 24, 2015",Q1,
40,"Oct 24, 2014","Nov 20, 2014","Jan 13, 2015",,
39,"Sep 12, 2014","Oct 9, 2014","Nov 11, 2014",Q4,
38,"Aug 1, 2014","Aug 28, 2014","Sep 30, 2014",,
37,"June 6, 2014","Jul 17, 2014","Aug 19, 2014",Q3,webview=chromium ↑
36,"Apr 25, 2014","May 22, 2014","Jun 24, 2014",,
35,"Mar 14, 2014","Apr 10, 2014","May 13, 2014",Q2,
34,"Jan 31, 2014","Feb 27, 2014","Apr 1, 2014",,
33,"Dec 6, 2013","Jan 16, 2014","Feb 18, 2014",Q1,
32,"Oct 18, 2013","Nov 14, 2013","Jan 7, 2014",,
31,"Sep 6, 2013","Oct 3, 2013","Nov 5, 2013",Q4,
30,"Jul 26, 2013","Aug 22, 2013","Sep 24, 2013",,
29,"June 7, 2013","Jul 11, 2013","Aug 13, 2013",Q3,
28,"Apr 19, 2013","May 23, 2013","Jun 25, 2013",,Blink ↑
27,"Mar 8, 2013","Apr 4, 2013","May 7, 2013",Q2,Webkit ↓
26,"Jan 25, 2013","Mar 26, 2013","Mar 26, 2013",,
25,"Nov 30, 2012","Jan 10, 2013","Feb 12, 2013",Q1,
24,"Oct 12, 2012","Nov 8, 2012","Dec 18, 2012",,
23,"Aug 31, 2012","Sep 27, 2012","Oct 30, 2012",Q4,
22,"Jul 20, 2012","Aug 16, 2012","Sep 18, 2012",,
21,"June 1, 2012","Jun 28, 2012","Aug 7, 2012",Q3,
20,"Apr 20, 2012","May 17, 2012","Jun 19, 2012",,
19,"Mar 9, 2012","Apr 5, 2012","May 8, 2012",Q2,
18,"Jan 13, 2012","Feb 9, 2012","Mar 13, 2012",,First Chrome Android (6/27) ↑
17,"Nov 11, 2011","Dec 15, 2011","Jan 31, 2012",Q1,
16,"Sep 30, 2011","Oct 27, 2011","Dec 6, 2011",,
15,"Aug 19, 2011","Sep 15, 2011","Oct 18, 2011",Q4,
14,"June 24, 2011","Aug 4, 2011","Sep 6, 2011",,
13,"May 13, 2011","June 9, 2011","Jul 26, 2011",Q3,
12,"Apr 1, 2011","April 28, 2011","May 31, 2011",,
11,"Feb 18, 2011","Mar 17, 2011","Apr 19, 2011",Q2,
10,"Jan 7, 2011","Feb 3, 2011","Mar 8, 2011",,
9,"Nov 5, 2010","Dec 9, 2010","Jan 25, 2011",Q1,
8,"Sep 24, 2010","Oct 21, 2010","Nov 30, 2010",,
7,"Aug 13, 2010","Sep 9, 2010","Oct 12, 2010",Q4,
6,Unknown,Unknown,"Sep 2, 2010",Q3,
5,Unknown,Unknown,"May 25, 2010",Q2,
4,Unknown,Unknown,"Jan 25, 2010",Q1,
3,Unknown,Unknown,"Sep 15, 2009",Q3,
2,Unknown,Unknown,"May 21, 2009",Q2,
1,Unknown,Unknown,Sep 2008,Q3,

**Comment by Elchi3** [comment]
I agree. Let's track this on the rendering side. BCD provides the release dates to data consumers already.
