### ISSUE TITLE
env() now supported in more browser

### ISSUE THREAD

**Issue by scheinercc** [mdn/browser-compat-data#3052]
The "Browser compatibility" is outdated for the env() CSS function 
https://developer.mozilla.org/en-US/docs/Web/CSS/env#Browser_compatibility

based on current "Can I Use" data: https://caniuse.com/#feat=css-env-function

**Comment by Elchi3** [comment]
Looks like this was updated. Most recently by https://github.com/mdn/browser-compat-data/pull/3244 which we will deploy today.
