### ISSUE TITLE
Fetch API not supported in Safari 10.0.2

### ISSUE THREAD

**Issue by Neztore** [mdn/browser-compat-data#3059]
The compatibility table [here](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API#Browser_compatibility) shows that Safari 10 supports the new window.fetch API, however I've found that it isn't. 
I tried (and failed) to find the file for this.

The actual error for reference:
`ReferenceError: Can't find variable: fetch`

Browser version: Safari 10.0.2

**Comment by saschanaz** [comment]
It's added in 10.1 so definitely not in 10.0. https://webkit.org/blog/7477/new-web-features-in-safari-10-1/
