### ISSUE TITLE
Performance.toJson() is already supported by chrome desktop

### ISSUE THREAD

**Issue by abduwaly** [mdn/browser-compat-data#3065]
As I tested, `Performance.toJson()` is supported by chrome-desktop, but capability status on [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Performance#Browser_compatibility) is not up to date

**Comment by irenesmith** [comment]
I have confirmed that Chrome supports this method and created a [pull request](https://github.com/mdn/browser-compat-data/pull/3067) to update the BCD data on MDN.

**Comment by Elchi3** [comment]
Fixed in https://github.com/mdn/browser-compat-data/pull/3067
