### ISSUE TITLE
Need guidance for callback functions.

### ISSUE THREAD

**Issue by jpmedley** [mdn/browser-compat-data#3068]
Such as this: https://drafts.csswg.org/resize-observer-1/#resize-observer-callback

There are currently no callbacks listed in BCD and no guidance in the help on how to do them.

**Comment by vinyldarkscratch** [comment]
Looking around, I found that BCD actually *does* have some callbacks within the data, for example [`RTCSessionDescriptionCallback`](https://github.com/mdn/browser-compat-data/blob/master/api/RTCSessionDescriptionCallback.json).  It appears we're essentially treating them like separate APIs.

**Comment by vinyldarkscratch** [comment]
Closing this issue since it's stale.  Happy to reopen or create a new issue for work on the specific callback!

**Comment by ddbeck** [comment]
I'm reopening this. Even if that's how we mean to deal with callbacks, we still don't have documentation that tells contributors how to add this data (it's not obvious to me, for example, how you would name a callback feature or where it should be structured in BCD).

**Comment by vinyldarkscratch** [comment]
Ah, I see what you mean, good point!

**Comment by vinyldarkscratch** [comment]
I know this is a pretty stale issue, but since I had last commented, we've removed all of the callbacks from BCD, as well as mdn/content, so we aren't documenting them anymore (especially since the interface attribute that utilizes it will cover its data).

I'm wondering if we should document what BCD won't include in the data guidelines?

**Comment by jpmedley** [comment]
We have?! This particular callback is still supported in Chrome. (At least, it's still in the IDL.) We have 144 more.

**Comment by jpmedley** [comment]
It seems like we shouldn't remove things from MDN or BCD ahead of browsers deprecating and removing them.

**Comment by vinyldarkscratch** [comment]
There are many WebIDL features that don't make sense to document separately from the interface features that utilize them, including typedefs, enums, and callbacks. These are never directly exposed to web developers, and will never have their own compatibility separate from the interfaces.

**Comment by queengooborg** [comment]
Considering we've removed all of the callbacks and are working to remove non-interface data from the API folder (#6810), should we close this issue @ddbeck?  Or should we leave it open as a reminder to update our documentation?

**Comment by ddbeck** [comment]
@queengooborg We haven't quite removed all callbacks. But I've written up a draft guideline that ought to close this issue, if it lands. See https://github.com/mdn/browser-compat-data/issues/3068.
