### ISSUE TITLE
Edge mobile 15+ doesn't exist

### ISSUE THREAD

**Issue by saschanaz** [mdn/browser-compat-data#3116]
The latest released version is 15. We should remove any newer versions to prevent users from being confused.

**Comment by Elchi3** [comment]
I'd like to hear thoughts on this from @erikadoyle and/or @patrickkettner.

**Comment by VFDan** [comment]
The preview releases are 15+, and they should be there for people to know exactly when they'll get feature support.

**Comment by saschanaz** [comment]
There is no preview release for Windows 10 Mobile. Actually even the support cycle for the latest version will cease this year.

**Comment by kumarharsh** [comment]
Edge mobile 15 did exist. v16 did not. I removed it in one of my PRs for some grid properties: https://github.com/mdn/browser-compat-data/pull/2500

**Comment by VFDan** [comment]
> Edge mobile means the version for W10M in BCD.

Sorry, I thought it meant Edge Mobile for Android/IOS.

**Comment by saschanaz** [comment]
@VFDan That's #1671. Definitely confusing as W10M is dead now...

**Comment by kumarharsh** [comment]
@vfdan Edge of Android is the same as Opera or Chrome - all use blink, so there's really no need to document what is and isn't supported there.

**Comment by saschanaz** [comment]
@kumarharsh We already have `chrome_android` and `webview_android` though.

**Comment by kumarharsh** [comment]
And Edge in iOS is a again just WebKit, same like  Chrome on iOS.

**Comment by ExE-Boss** [comment]
@saschanaz Well, **Opera&nbsp;for&nbsp;Android**&nbsp;10, 11 and 12 used Presto, same with **Opera&nbsp;for&nbsp;Desktop**&nbsp;1&nbsp;–&nbsp;12.
