### ISSUE TITLE
Integrate bcd-review-bot

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#3127]
@dontcallmedom wrote "a first version node-based webhook https://github.com/dontcallmedom/bcd-review-bot/" that will help flagging people for review.

The idea is to have pull requests to BCD that touch on a specific browser dataset to
be flagged automatically or assigned to "owners" of the said browser. "Owners" are likely employees of the given browser vendors.

This issue is about integrating Dom's tool.

**Comment by ExE-Boss** [comment]
If you want automatic request review based on code ownership, then just make use of [GitHub’s `CODEOWNERS` file](https://help.github.com/articles/about-codeowners/).

As an example, see the one from [ExE&#x2011;Boss/SMW&#x2011;Workspace](https://github.com/ExE-Boss/SMW-Workspace/blob/master/.github/CODEOWNERS).

**Comment by a2sheppy** [comment]
This is a great idea. I'm very excited to see things like this happen.

**Comment by vinyldarkscratch** [comment]
#3800 adds a `CODEOWNERS` file that does a bit of what we're looking for, however it seems that the `bcd-review-bot` also has browser-specific control.  I'm curious, is the browser-specific review something we're aiming for?  For things like reordering and restructuring support blocks, I can see it possibly becoming annoying for those that were automatically requested a review.

**Comment by ExE-Boss** [comment]
Well, when reordered, the objects are still deeply equal, they just no longer have their properties in the same order.

**Comment by Elchi3** [comment]
>  I'm curious, is the browser-specific review something we're aiming for?

The idea was to have representatives from browser vendors help review data for their browser(s). We only have people from Mozilla and Google caring about the data right now, so I think this tool isn't providing that much value at this point. Maybe it will once this community has grown a bit more and there are other vendors involved.

**Comment by vinyldarkscratch** [comment]
Gotcha.  Yeah, it would be nice to get some Microsoft developers on board with the project as well to help clarify IE/Edge data, but if the `CODEOWNERS` file presented in #3800 is sufficient enough for our purposes at this point, we should revisit this later on.
