### ISSUE TITLE
Update Firefox for Android support for window.print

### ISSUE THREAD

**Issue by gpmetheny** [mdn/browser-compat-data#3131]
Per https://github.com/mdn/browser-compat-data/blob/master/api/Window.json, Firefox for Android has support for window.print, but I receive the following error when using the function in my .js:

```
TypeError: window.print is not a function
```

I've reproduced on multiple websites (both in a script and directly from the console) with a fresh install of Firefox and Firefox Nightly on two different Android devices. I believe `api/Window/print/_compat/support/firefox_android/version_added` should be `null`.

![screenshot 2018-11-24 07 16 55](https://user-images.githubusercontent.com/19560286/48969815-f5b37580-efb8-11e8-9bdc-59cd3b9d9e4f.png)

![screenshot 2018-11-24 07 15 42](https://user-images.githubusercontent.com/19560286/48969811-d3b9f300-efb8-11e8-9dae-a95815731a53.png)

apptype: mobile/android
vendor: Mozilla
name: Fennec
version: 63.0.2
appbuildid: 20181105152108

**Comment by saschanaz** [comment]
Possibly related issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1247609

**Comment by gpmetheny** [comment]
@saschanaz, that does look like the same issue. @kbrosnan, @bsmedberg, is this bug still active?

[window.print() doesn't respond in Firefox for Android](https://bugzilla.mozilla.org/show_bug.cgi?id=1247609)
