### ISSUE TITLE
Browser name/icon missing from tables in 'Browser support for JavaScript APIs' page

### ISSUE THREAD

**Issue by DanStevens** [mdn/browser-compat-data#3149]
I'm looking at the the [Browser support for Javascript APIs](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Browser_support_for_JavaScript_APIs) page on mozilla.org and I'm finding it a little difficult to use because the browser names/icons are missing.

![screenshot_2018-11-28 browser support for javascript apis](https://user-images.githubusercontent.com/286017/49172207-05f38980-f306-11e8-892c-5a6560bcfbaf.png)

**Comment by jwhitlock** [comment]
Thanks @DanStevens. We recently shipped an update, and the page needed to be regenerated. We've regenerated pages with the ``{{Compat}}`` macro, but we need to also regenerate pages with some other macros.

Any logged in user can regenerate a page with a force-refresh to regenerate a page. I've done this for this page, but there are several others that need it.

The style is off for these pages, which is tracked in [bug 1509833](https://bugzilla.mozilla.org/show_bug.cgi?id=1509833).
