### ISSUE TITLE
Compat data for input features

### ISSUE THREAD

**Issue by stof** [mdn/browser-compat-data#3157]
Currently, the only compat data regarding `<input>` is the support for the different types. But there is no data for other features. For instance, today, I looked for support for the `pattern` validation of the text input, and there is nothing about it in BCD or MDN.

**Comment by ArfyFR** [comment]
I also looked for this doc in MDN (pattern introduced with HTML5 for some input types: text, date, search, url, tel, email, and password).  I found one there:
https://www.w3schools.com/tags/att_input_pattern.asp
