### ISSUE TITLE
Payment Request API - it should be mentioned that dom.payments.request.supportedRegions should contain your country

### ISSUE THREAD

**Issue by ashucg** [mdn/browser-compat-data#3164]
I was trying the API and `window.PaymentRequest` was returning `undefined`, but thanks to [caniuse](https://caniuse.com/#search=payment%20request) I came to know about `dom.payments.request.supportedRegions` config and on adding my country's code, i.e., **IN**, PaymentRequest finally worked.

I believe that it must be mentioned on MDN as well, because if I am using MDN, I am expecting it to contain all the information I need to try new APIs

**Comment by ddbeck** [comment]
Huh, this is an interesting issue! I looked into it and [bug 1501102](https://bugzilla.mozilla.org/show_bug.cgi?id=1501102) seems to show that before Firefox 65 the only supported region was California. We probably need to document the pref on 65+ and add a note for [the existing 55 entry](https://github.com/mdn/browser-compat-data/blob/9591bc084e3e3a6b6054ffb5302f455bd7c6a5a8/api/PaymentRequest.json#L33).

**Comment by vinyldarkscratch** [comment]
Closing this as #3096 seems to have already added the `supportedRegions` preference.
