### ISSUE TITLE
Document JSDOM Web API and HTML support

### ISSUE THREAD

**Issue by ExE-Boss** [mdn/browser-compat-data#3180]
The [JSDOM](https://github.com/jsdom/jsdom)&nbsp;[<img align="top" alt="(on&nbsp;npm)" src="https://img.shields.io/npm/v/jsdom.svg"/>](https://www.npmjs.com/package/jsdom) node&nbsp;package implements a&nbsp;headless browser for testing HTML content and is also used extensively for testing the output of KumaScript macros.

It’d be helpful to know which APIs are supported by JSDOM when writing unit tests or [using it in WebWorkers](https://github.com/jsdom/jsdom/blob/master/README.md#running-jsdom-inside-a-web-browser).

**Comment by Elchi3** [comment]
I think this is out of scope for this project for now.
Yes, it might be interesting, but I'm not aware of a data displayer for this. I haven't heard that MDN or VS Code is interested in showing JSDOM data. If we have demand for this, we might reconsider.
