### ISSUE TITLE
Node.removeChild() marked as Deprecated and Non-Standard

### ISSUE THREAD

**Issue by Konrud** [mdn/browser-compat-data#3192]
I can't find any info that this method is either deprecated or non-standard (btw it was modified in DOM Level 3 [according to W3C](https://www.w3.org/TR/DOM-Level-3-Core/core.html#ID-1734834066)). In [the MDN page for this method](https://developer.mozilla.org/en-US/docs/Web/API/Node/removeChild) in browser compatibility table it is marked as deprecated and non-standard. I couldn't find this table here in the repository in order to change it.

**Comment by ddbeck** [comment]
Thanks for noting this issue, @Konrud. If you're looking for this data to contribute a PR to fix this, then it's here: https://github.com/mdn/browser-compat-data/blob/master/api/Node.json#L1980

**Comment by ddbeck** [comment]
Fixed by #3215.
