### ISSUE TITLE
Need standard way to handle interface moves.

### ISSUE THREAD

**Issue by jpmedley** [mdn/browser-compat-data#3196]
PR #3154 replaces `"alternative_name": "navigator.getDisplayMedia"` with a note stating the same because as someone put it, '`alternative_name` is meant to cover a change in name, not a move from one interface to another.' 

I've seen moves happen often enough that there should be a JSON way of describing them. This seems to happen most frequently in the case of a method or property moving to an interfaces parent class.

**Comment by Elchi3** [comment]
Duplicate of https://github.com/mdn/browser-compat-data/issues/3463
