### ISSUE TITLE
Weird data for CSS scrollbars on IE

### ISSUE THREAD

**Issue by stof** [mdn/browser-compat-data#3200]
The compat data for CSS scrollbars are saying that only Firefox support them. But the MDM page starts by saying `CSS Scrollbars standardizes the obsolete scrollbar color properties introduced in 2000 by Windows IE 5.5.`.

So is this indeed not supported in IE ?

**Comment by stof** [comment]
OK, looking at MDM, there are other `-ms-scrollbar-*` properties for old IE: https://developer.mozilla.org/fr/docs/Web/CSS/-ms-scrollbar-base-color

So BCD might be fine here.

**Comment by ddbeck** [comment]
Thanks for bringing this up, @stof. I took a look at this and it does seem consistent. It does not appear any version of IE supported the new CSS specification, so only the `-ms-scollbar-*` data reflects the (non-standard) IE support.

**Comment by ddbeck** [comment]
I'd suggest either editing the wiki page directly (if you have an idea for a clearer wording for that introduction) or, if you want to have a discussion about changes to that page, then [the MDN Discourse topic](https://discourse.mozilla.org/c/mdn) is probably the right place for that.
