### ISSUE TITLE
Data for multi-position color stops in gradients

### ISSUE THREAD

**Issue by stof** [mdn/browser-compat-data#3201]
https://hacks.mozilla.org/2018/12/firefox-64-released/ says that Firefox 64 adds support for multi-position color stops in gradients (https://developer.mozilla.org/en-US/docs/Web/CSS/linear-gradient#Gradient_with_multi-position_color_stops). It would be great to have an entry for that feature in BCD.

**Comment by jpmedley** [comment]
#3135 There's already an open PR on this. It's moving slowly because it's December.

Please note the the PR calls them 'double-position' because that's the term currently used by the spec author. (I had an email discussion with him so no link.)

**Comment by vinyldarkscratch** [comment]
The referenced PR is already merged -- may we close this issue?

**Comment by Elchi3** [comment]
Looks like so. Please re-open or file new issues if there is something left to do here. Thanks!
