### ISSUE TITLE
Data for new Intl APIs

### ISSUE THREAD

**Issue by stof** [mdn/browser-compat-data#3225]
It would be great if compat data for `Intl.RelativeTimeFormat` (already documented on MDM without the compat table) and `Intl.ListFormat` (not yet documented) could be available.

Current status for `Intl.RelativeTimeFormat`:
- shipped in Chrome 71: https://developers.google.com/web/updates/2018/10/intl-relativetimeformat
- may be partially shipped in Firefox 65: https://bugzilla.mozilla.org/show_bug.cgi?id=1504334 and https://bugzilla.mozilla.org/show_bug.cgi?id=1504334
- no idea for other browsers (probably not supported though)

Current status for `Intl.ListFormat`:
- shipped in Chrome 72: https://developers.google.com/web/updates/2018/12/intl-listformat
- https://bugzilla.mozilla.org/show_bug.cgi?id=1433306

**Comment by evilpie** [comment]
Would be nice to have `Intl.RelativeTimeFormat` soon, considering it's already in Firefox Beta.

**Comment by littledan** [comment]
cc @romulocintra

**Comment by littledan** [comment]
@romulocintra Does that PR give you a good model to use for the ListFormat data?

**Comment by romulocintra** [comment]
@littledan  yes will use as reference, but did not get further cause had trouble running confluence now is ok docs are https://github.com/mdn/browser-compat-data/blob/master/USING-CONFLUENCE.md

**Comment by Elchi3** [comment]
The use of confluence is entirely optional. It is a somewhat flaky tool that can help with finding data, but you don't really need to use it if you know which versions you want to submit for a feature.

**Comment by evilpie** [comment]
For `Intl.RelativeTimeFormat`, I didn't add `Intl.RelativeTimeFormat.prototype.formatToParts` and `Intl.RelativeTimeFormat.supportedLocalesOf`.

**Comment by romulocintra** [comment]
@evilpie  

I created an issue to track some parts of Documentation if want to have a look at : https://github.com/tc39/proposal-intl-relative-time/issues/102   and if you contribute with missing parts will be tracked cross both repositories

**Comment by littledan** [comment]
@evilpie Do you mean compat data for those specific methods? (Probably the issue @romulocintra can be used to track the documentation pages, and we'll track compat data here.) AFAIK no one ships part of RelativeTimeFormat and not all of it; is there some way to represent that in the compat data here?
