### ISSUE TITLE
DocumentFragment() constructor displayed as not working in Edge, however it works in Edge 17

### ISSUE THREAD

**Issue by mrtt1000** [mdn/browser-compat-data#3229]
https://developer.mozilla.org/en-US/docs/Web/API/DocumentFragment

The browser compatability table states that it is not supported in Edge, however upon testing it, i found that it works. Maybe it did not work with an older version of Edge.

**Comment by saschanaz** [comment]
![image](https://user-images.githubusercontent.com/3396686/51006939-d5e80900-1588-11e9-836a-82e06d86b482.png)

It looks okay now.

**Comment by Elchi3** [comment]
Was fixed in https://github.com/mdn/browser-compat-data/pull/3155
