### ISSUE TITLE
Webextension support on Firefox for Android

### ISSUE THREAD

**Issue by buttercookie42** [mdn/browser-compat-data#3233]
As of Firefox 65, Firefox for Android [now supports](https://bugzilla.mozilla.org/show_bug.cgi?id=1429488) the `headerUrl`/`theme_frame` properties in Webextension themes. `accentcolor` is supported, too (in theory right since support for that was added on desktop, but for simplicity we could claim 65 for that as well).
However unlike Desktop Firefox, `headerUrl`/`theme_frame` is still mandatory.

**Comment by irenesmith** [comment]
[PR 3575](https://github.com/mdn/browser-compat-data/pull/3575) created to update BCD.

**Comment by vinyldarkscratch** [comment]
Closing this issue as the PR has been merged.
