### ISSUE TITLE
nobr element supported in Firefox and Chromium (at least)

### ISSUE THREAD

**Issue by born2webdesign** [mdn/browser-compat-data#3240]
`nobr` element supported in FF 60 and Chromium 72 (and probably any other version and probably many other browsers).

**Comment by ExE-Boss** [comment]
Fixed&nbsp;by&nbsp;https://github.com/mdn/browser-compat-data/issues/3268, please&nbsp;close.

needinfo?(@ddbeck, @Elchi3)

**Comment by Elchi3** [comment]
Thanks

**Comment by born2webdesign** [comment]
Thank you!
