### ISSUE TITLE
Duplicate data for Cache Storage API

### ISSUE THREAD

**Issue by pwnall** [mdn/browser-compat-data#3243]
https://github.com/mdn/browser-compat-data/blob/f4f8ce8eb117281c5037d15cac257293fd19301c/api/Cache.json and https://github.com/mdn/browser-compat-data/blob/f4f8ce8eb117281c5037d15cac257293fd19301c/api/CacheStorage.json seem to refer to the same API.

**Comment by ddbeck** [comment]
These seem like two distinct APIs, with different names. The [service workers spec](https://w3c.github.io/ServiceWorker/#cache-objects) seems to support this. That said, I'm not really an expert on this. Can you elaborate on why you think the data is for the same API?

**Comment by jpmedley** [comment]
There are two interfaces in the spec and there are two interfaces implemented in Chrome and other browsers.

I would like to know what's confusing or concerning you. We may need to edit the text of the reference pages to make sure they're clear.

**Comment by pwnall** [comment]
Sorry, my bad. I just got confused. Definitely not an expert in the API :)

FWIW I was looking into this data because MDN says Safari does not support Cache Storage (the API), and it does, as of last year. Now that I know Cache / CacheStorage are legit separate interfaces, I'll try to find time to send a PR for the Safari support.
