### ISSUE TITLE
Shorten URL for WebKit Bugzilla

### ISSUE THREAD

**Issue by FranklinYu** [mdn/browser-compat-data#3267]
This is a linter feature request. Currently we enforce shorten URL for Mozilla Bugzilla:

https://github.com/mdn/browser-compat-data/blob/39947f56ac43ffe08beffc4b1b08c9c2595edd6d/test/test-style.js#L56-L62

as well as Chrome bug:

https://github.com/mdn/browser-compat-data/blob/39947f56ac43ffe08beffc4b1b08c9c2595edd6d/test/test-style.js#L97-L103

Would it be useful if we also apply short URL for https://bugs.webkit.org/show_bug.cgi?id=100000 to https://webkit.org/b/100000?

<sub>Actually there is a third-party website for shorten URL [wkb.ug](https://github.com/omo/wkb.ug) but I think we need official support here.</sub>

**Comment by vinyldarkscratch** [comment]
+1 for this!  wkb.ug looks nice considering how short it is, however we should probably stick with the official URLs as much as we can.  Will submit a PR to implement this soon.  :wink:
