### ISSUE TITLE
AbortController and AbortSignal not supported in Safari 12

### ISSUE THREAD

**Issue by DavidBruant** [mdn/browser-compat-data#3273]
[Current browser compat](https://developer.mozilla.org/en-US/docs/Web/API/AbortController#Browser_compatibility) suggests it is supported, but [caniuse informs the object is a useless placeholder](https://caniuse.com/#feat=abortcontroller)

**Comment by Elchi3** [comment]
Did this PR solve this https://github.com/mdn/browser-compat-data/pull/3241? Or is it really completely useless and should be marked `false`?

**Comment by ddbeck** [comment]
@Elchi3 FWIW, when reviewing that PR, I considered asking the author to go with `false` instead. My reasoning for not doing it was by analogy to something that came up in the CSS migrations, where some properties were recognized but didn't do anything. This is surprising, non-standard behavior (as opposed to an obvious `ReferenceError`).

**Comment by DavidBruant** [comment]
> Did this PR solve this #3241?

oh i didn't look for PRs, sorry
it's the same topic indeed

> Or is it really completely useless and should be marked `false`?

I would argue in the direction of `false` given that, from what i understand, the global is useless and doesn't abort fetch requests (which is the main use case for this feature at this point)

But i guess the "partial implementation" is fine at this point since it seems like it should be in the [next version of Safari](https://bugs.webkit.org/show_bug.cgi?id=174980#c29), so this detail will soon be lost in the history of the web

**Comment by Elchi3** [comment]
Thanks! The table is showing the partial support for now with a link to details of the situation. Hopefully a future Safari version fixes it.
