### ISSUE TITLE
Assisting BCD updates with automation

### ISSUE THREAD

**Issue by foolip** [mdn/browser-compat-data#3308]
There is already [tooling in place](https://github.com/mdn/browser-compat-data/blob/master/USING-CONFLUENCE.md) to compare the BCD data with [Web API Confluence
](http://web-confluence.appspot.com/) and to update data based on the support in Confluence.

There are also other data sources, like [the sum of the web platform's IDL definitions](https://github.com/tidoust/reffy-reports/tree/master/whatwg/idl), which could feed into updating BCD.

This issue is for collecting requirements and putting together a design doc: [auto-updating MDN’s browser compat data (BCD)](https://docs.google.com/document/d/13kpKPN-qdWakN5wIbrF2IgDxfPwGzIsYBkaxy4YYxTs/edit?usp=sharing).

Discussing here or on the doc is OK.

**Comment by foolip** [comment]
@Elchi3 @samthor

**Comment by foolip** [comment]
I've expanded a fair bit on the design doc today, please review.

**Comment by Elchi3** [comment]
Left a few comments, great work @foolip! Summarizes well what our options are. 
I will try to circulate this other interested people and see if they have thoughts.

**Comment by foolip** [comment]
@vinyldarkscratch given your work in https://github.com/mdn/browser-compat-data/pull/3658 and other PRs, I think this issue may interest you. We have both been using Web IDL to make updates to BCD but in slightly different ways, but I'd love to collaborate to combine all of our good ideas! Would you mind taking a look at the design doc linked in this issue to see if that approach makes sense to you?

**Comment by vinyldarkscratch** [comment]
Thanks for reaching out to me regarding this, I would love to help combine all of our efforts into one!  I'm all for utilizing the power of automation to increase productivity as well, thus removing human error where we can.  I'll definitely read through within the next 12 hours!

**Comment by foolip** [comment]
Closing this issue. The plans have evolved as a result of experimenting, but basically this work is happening in https://github.com/foolip/mdn-bcd-collector now.
