### ISSUE TITLE
Proxy handler getPrototypeOf needs updating

### ISSUE THREAD

**Issue by evilpie** [mdn/browser-compat-data#3321]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/handler/getPrototypeOf

Works at least in Chrome

**Comment by evilpie** [comment]
`setPrototypeOf` also needs updating

**Comment by jpmedley** [comment]
I tried to get a version number on this. I need help from a guy who's out of the office until February.

@Elchi3 Can you assign this ticket to me to help me remember to follow up.

**Comment by evilpie** [comment]
@jpmedley did you get an update?

**Comment by jpmedley** [comment]
I apologize. This slipped my mind. I've reached out to our expert and hope to have an answer within a day.

**Comment by jpmedley** [comment]
The method is [supported in this file](https://cs.chromium.org/chromium/src/v8/src/bootstrapper.cc?q=CreateJSProxyMaps&dr=CSs&l=3635) as part of the code for Proxy and Reflect. The original commit of that code is missing.
* [Mathias Bynens](https://developers.google.com/web/resources/contributors/mathiasbynens) asserts this was part of Proxy and Reflect and that they shipped in 49.
* The [Chrome 49 beta post](https://blog.chromium.org/2016/02/chrome-49-beta-css-custom-properties.html) lists Proxy and Reflect as part of that release.

Chrome 49 is what I would add to the BCD.
