### ISSUE TITLE
Headers.get() doesn't return all headers

### ISSUE THREAD

**Issue by duduindo** [mdn/browser-compat-data#3355]
## Line to change
https://github.com/mdn/browser-compat-data/blob/master/api/Headers.json#L612-L615

## Details
In the specification says: 

```markdown
## The get(name) method, when invoked, must run these steps:
 If name is not a name, then throw a TypeError.
```
https://fetch.spec.whatwg.org/#headers-class

## Related issues
https://github.com/mdn/sprints/issues/860

## MDN Doc
https://developer.mozilla.org/en-US/docs/Web/API/Headers#Browser_compatibility

**Comment by vinyldarkscratch** [comment]
Closing this and explaining why on the Sprints issue.
