### ISSUE TITLE
Is the work on CSS Stalled?

### ISSUE THREAD

**Issue by praveenpuglia** [mdn/browser-compat-data#336]
Because there doesn't seem to be much going on in the CSS Side.. I had started something very similar here...
https://github.com/praveenpuglia/css-support
but if this project is gonna be actively maintained, I would rather contribute here than doing things on my own where it's hard to get contribution.

**Comment by Elchi3** [comment]
Thanks for your interest in this repository! The work on CSS compat data is not stalled! We're planning to add more data really soon now. Stay tuned!
