### ISSUE TITLE
Chrome supports prefix-less navigator.getUserMedia()

### ISSUE THREAD

**Issue by saschanaz** [mdn/browser-compat-data#3389]
https://developer.mozilla.org/en-US/docs/Web/API/Navigator/getUserMedia

Currently MDN says there is no prefix-less support.

**Comment by vinyldarkscratch** [comment]
On the page you linked, I see a note that states "Later versions of Chrome support the unprefixed `MediaDevices.getUserMedia()` which replaced this deprecated method."  I'm not sure what's stating no unprefixed support?

**Comment by saschanaz** [comment]
That’s about navigator.mediaDevices.getUserMedia, not navigator.getUserMedia.

________________________________

**Comment by saschanaz** [comment]
Related Chromium issue: https://bugs.chromium.org/p/chromium/issues/detail?id=607439

________________________________

**Comment by vinyldarkscratch** [comment]
Ah, I see what you're getting at now.  Since this is a feature that's shipped in an official Chrome release, mentioning it in the browser compatibility is needed.

**Comment by jpmedley** [comment]
Just to be clear:
* Implemented in Chrome 21 behind a prefix (navigator.webkitGetUserMedia()).
* At some point the prefix was removed. (I'll try to find out.)
* Implemented in Chrome 52 as navigator.mediaDevices.getUserMedia().

**Comment by jpmedley** [comment]
@Elchi3 Can you assign this to me. It's got some complexity I'd like to handle myself.

**Comment by saschanaz** [comment]
>At some point the prefix was removed. (I'll try to find out.)

Per the aforementioned issue it's M53.

**Comment by jpmedley** [comment]
Update in #3938 
FYI, the prefix was not removed and the unprefixed version was implented [in Chrome 53](https://storage.googleapis.com/chromium-find-releases-static/489.html#489f502a4d2d39665eb58158dc5df313ee2dbf15), not 52 as previously stated.

**Comment by vinyldarkscratch** [comment]
Closing this issue since the related PR has been merged.
