### ISSUE TITLE
 DOMPointReadOnly.toJSON() is not supported in Firefox 31 and not even ESR 60

### ISSUE THREAD

**Issue by icl7126** [mdn/browser-compat-data#3398]
See the docs:
https://developer.mozilla.org/en-US/docs/Web/API/DOMPointReadOnly/toJSON

It says Firefox 31 is supported however not even Firefox 60 is supporting it.
But it seems to work in Firefox 65.

You can try it with the example code that will fail in 60 with the follworing error:
**TypeError: topLeft.toJSON is not a function[Learn More]**

**Comment by vinyldarkscratch** [comment]
Testing in LambdaTest revealed that Firefox 31 does not support it; 62 was the first version to support the function.  It looks like it was set to 62 before BCD, but during the conversion, got changed by accident.  Submitting a PR to fix this now!
