### ISSUE TITLE
Add webext chrome.management data

### ISSUE THREAD

**Issue by evilpie** [mdn/browser-compat-data#34]

**Comment by wbamberg** [comment]
Fixed (I hope):
https://github.com/mdn/browser-compat-data/commit/bf34bb5e9ce85f3adef97bef9d51bcf56662644c
https://github.com/mdn/browser-compat-data/commit/2ec727a571d1b4d311e06eda12db3e99c4287de2
https://github.com/mdn/browser-compat-data/commit/004053f799550b66c917eee5d0830edfe8c23ef8
