### ISSUE TITLE
Conic gradient on MDN site shows no compar data despite being present in file

### ISSUE THREAD

**Issue by crutchcorn** [mdn/browser-compat-data#3406]
https://developer.mozilla.org/en-US/docs/Web/CSS/conic-gradient#Browser_compatibility

I believe this is because it's expected to be under `gradient` when in the JSON file it's it's own item, although I could be wrong

https://github.com/mdn/browser-compat-data/blob/master/css/types/image.json#L109

**Comment by Elchi3** [comment]
Yeah, this should be fixed with #3360 which will make today's release to the site.

**Comment by Elchi3** [comment]
This is fixed on MDN now.
