### ISSUE TITLE
Require desktop browsers in lint and add them where missing

### ISSUE THREAD

**Issue by foolip** [mdn/browser-compat-data#3410]
Here is a piece of Attr.json:
```
      "localName": {
        "__compat": {
          "mdn_url": "https://developer.mozilla.org/docs/Web/API/Attr/localName",
          "support": {
            "chrome": {
              "version_added": "46",
              "notes": "This API was previously available on the <a href='https://developer.mozilla.org/docs/Web/API/Node'><code>Node</code></a> API."
            },
            "firefox": {
              "version_added": "48",
              "notes": "This API was previously available on the <a href='https://developer.mozilla.org/docs/Web/API/Node'><code>Node</code></a> API."
            },
            "firefox_android": {
              "version_added": "48",
              "notes": "This API was previously available on the <a href='https://developer.mozilla.org/docs/Web/API/Node'><code>Node</code></a> API."
            },
            "ie": {
              "version_added": null
            },
            "opera": {
              "version_added": true
            },
            "opera_android": {
              "version_added": null
            },
            "safari": {
              "version_added": null
            },
            "safari_ios": {
              "version_added": null
            },
            "webview_android": {
              "version_added": null
            }
          },
          "status": {
            "experimental": false,
            "standard_track": true,
            "deprecated": false
          }
        }
      },
```

Some browsers, like "edge" and "chrome_android", are missing here, while others are present with `"version_added": null`.

While it's possible to write code that deals with either case, it would be a bit more convenient if a lint enforced one style or the other.

@Elchi3 preferences?

**Comment by foolip** [comment]
I've sent https://github.com/mdn/browser-compat-data/pull/3411 and https://github.com/mdn/browser-compat-data/pull/3412 to show what it would look like to fill in the missing vs. erase the existing cases like this.

Looking at that, I think that having the entries where we will likely fill them will lead to less churn and merge conflicts. But adding them for all browsers always seems excessive. I'd like to suggest adding a field to browsers/*.json to say whether entries are required for that browser or not. Then add that rule to the lint.

**Comment by Elchi3** [comment]
Good issue, thanks for thinking about this!

Looking at both PRs, I think I would also rather prefer to require a few browsers to be added and not remove all `null` values. From a new contributors point of view seeing a "null" and replacing it seems more straightforward than looking up the browser key and then also adding it correctly (alphabetically) etc.

Now the reason why we didn't require entries for all browsers with at least `null` is that some areas like webextensions/ won't ever have certain browsers. That said, I don't think it makes sense to expose this "meta flag" to browsers/*.json. 
Instead, we have this test https://github.com/mdn/browser-compat-data/blob/master/test/test-browsers.js which already checks if browsers make sense for a technology (like only a allow a subset of browsers in webextensions/). So in there we could probably also add those we always want to see for a given technology with at least "null".

**Comment by foolip** [comment]
Alright, I've sent https://github.com/mdn/browser-compat-data/pull/3413 which adds it to the lint. The set of browsers which are required are controlled in code, so no metadata in browsers/*.json.

**Comment by Elchi3** [comment]
To finalize this, it would be nice to change the docs as they currently say "No browser identifier is mandatory." to something like "Desktop browser identifier are mandatory, you need to add them at least with a `null` value". or something.

https://github.com/mdn/browser-compat-data/blob/master/schemas/compat-data-schema.md#browser-identifiers

**Comment by foolip** [comment]
Sent https://github.com/mdn/browser-compat-data/pull/3419 with your wording adapted a bit.
