### ISSUE TITLE
question: difference between version_added types

### ISSUE THREAD

**Issue by amilajack** [mdn/browser-compat-data#3425]
What is the difference between `version_added: false`,`version_added: true`, and `version_added: null`?

**Comment by vinyldarkscratch** [comment]
`version_added: true` or `version_added: "some browser version number"` means that the feature has been implemented in the browser.  When `true`, a specific version is unknown.  `version_added: false` means that the browser does not support the feature, and never has.  `version_added: null` means that we have no idea if the browser has support for the feature.  (A major goal is to get rid of as many of the `null` values we can and replace them with real data from the browsers.)

Hope this helps!

**Comment by amilajack** [comment]
@vinyldarkscratch this helped me so much. Thanks!
