### ISSUE TITLE
Intl.NumberFormat data seems wrong for the Android WebView

### ISSUE THREAD

**Issue by stof** [mdn/browser-compat-data#3432]
See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat#Browser_compatibility

![image](https://user-images.githubusercontent.com/439401/52582279-232bf480-2e2d-11e9-9687-1eb10ab8a590.png)

Having `Basic support` on 4.4 but without `format` support looks wrong to me.

**Comment by jpmedley** [comment]
@Elchi3 @ddbeck Self-assigning on numbers.

**Comment by stof** [comment]
According to my testing, `format` looks supported on Android 4.4.

I still don(t understand why `format` is separate from the basic support though. I would say that a NumberFormat without its `format` method has no kind of support anyway.

**Comment by jpmedley** [comment]
Because that's how the macro renders the JSON. For most interfaces it's fine, but NumberFormat is an edge case.

**Comment by stof** [comment]
Closing that as #3453 fixed it
