### ISSUE TITLE
`:is(…)` selector compat table is broken

### ISSUE THREAD

**Issue by ExE-Boss** [mdn/browser-compat-data#3452]
See https://developer.mozilla.org/en-US/docs/Web/CSS/:is#Browser_compatibility

This is&nbsp;probably a&nbsp;bug in&nbsp;the&nbsp;`{{Compat}}` macro that might end up being fixed as&nbsp;part of&nbsp;https://github.com/mdn/kumascript/pull/1010.

**Comment by Elchi3** [comment]
Re-rendered the page: https://developer.mozilla.org/en-US/docs/Web/CSS/:is#Browser_compatibility
Looks good now.
