### ISSUE TITLE
Firefox, Safari and Chrome support cjk-earthly-branch for list-style-type?

### ISSUE THREAD

**Issue by willowcheng** [mdn/browser-compat-data#3455]
Not sure if there is resources I could find source of truth which version of these browsers starts to support it, but it looks like Firefox, Safari and Chrome all support `cjk-earthly-branch` for `list-style-type` of their most up-to-date versions. 🤔 Same thing may apply to other `list-style-type` reserved values as well.

Chrome:
<img width="1552" alt="screen shot 2019-02-13 at 4 36 07 pm" src="https://user-images.githubusercontent.com/6239076/52745676-a5dbbd80-2fad-11e9-88be-61e162a0f78e.png">

Firefox:
![screen shot 2019-02-13 at 4 36 32 pm](https://user-images.githubusercontent.com/6239076/52745682-abd19e80-2fad-11e9-92f0-18bcde944a4f.png)

Safari:
![screen shot 2019-02-13 at 4 37 09 pm](https://user-images.githubusercontent.com/6239076/52745688-af652580-2fad-11e9-90db-42bc60f2dbc4.png)

**Comment by vinyldarkscratch** [comment]
Thanks for reporting this!  I'll be testing them all out and writing a PR to update the data.  :wink:

**Comment by jpmedley** [comment]
I tried to find a version number for this. I [found an early mention of it](https://chromium.googlesource.com/chromium/src/+/2eaed561962f97e91dc34a383e8ecfc271c63bf7), from 2012, but not the actual first commit :(

You'll need to set `chrome`, `chrome_android`, and `webview_android` to `true`. :(

**Comment by vinyldarkscratch** [comment]
_Hiss, `true` values begone!_

Totally understandable, thanks for looking into it!  I’ll set the values to true when I return home.  😉
