### ISSUE TITLE
DocumentOrShadowRoot APIs are marked as too new

### ISSUE THREAD

**Issue by saschanaz** [mdn/browser-compat-data#3504]
Nearly everything there is marked as added in Chrome 53/Firefox 63, but those versions are really the ones that added ShadowRoot support. Many APIs there had been existed in `Document` before `DocumentOrShadowRoot` so we have to properly represent them.

**Comment by foolip** [comment]
Related: https://github.com/mdn/browser-compat-data/issues/472

**Comment by vinyldarkscratch** [comment]
I believe that we can resolve this by turning both Chrome and Firefox into arrays of compatibility statements.  Specifically, one with the version that was added, with a partial implementation flag and a note stating "Only available in the Document API."

**Comment by foolip** [comment]
We could do that, but that wouldn't be machine readable. I think spitting the entries would be better.

@Elchi3 FYI, here's a concrete case of mixin troubles.
