### ISSUE TITLE
Raise minimum node version to 8 in April 30, 2019

### ISSUE THREAD

**Issue by ExE-Boss** [mdn/browser-compat-data#3509]
> Questions before I merge this:
> - Do we also want to lower the minimum node version now?
> - If so, do we also check what minimum node versions our (dev)Dependencies have?

_Originally posted by @Elchi3 in https://github.com/mdn/browser-compat-data/pull/3442#pullrequestreview-204797517_

**Comment by jwhitlock** [comment]
We should not support a version of node that is not supported by the [Node Foundation](https://github.com/nodejs/Release). Even if we're compatible with earlier versions, we should require node 6, and raise that to 8 in April 2019.

**Comment by Elchi3** [comment]
Thanks John, I agree.

**Comment by vinyldarkscratch** [comment]
Well, now it is April, and soon, the EOL of v6 of Node.  I strongly agree -- on April 30th, 2019, let us raise the minimum Node version to 8.
