### ISSUE TITLE
How should we handle CSS methods?

### ISSUE THREAD

**Issue by jpmedley** [mdn/browser-compat-data#3513]
I stumbled on [this bug fix](https://bugs.chromium.org/p/chromium/issues/detail?id=703898). It seems there's no good place to document this. We don't really handle CSS methods as separate items in either BCD or on MDN. 

The question is should we?

**Comment by ddbeck** [comment]
CSS has very few genuine methods/functions. [This came up ages ago](https://github.com/mdn/browser-compat-data/pull/642), when I was migrating CSS data. Mostly, it has function-like notations for some value types. Right now, it appears that the `<color>` type is represented only by features on the `css.properties.color` (such that the [`<color>` page uses the property data](https://developer.mozilla.org/en-US/docs/Web/CSS/color#Browser_compatibility)).

The right thing to do is probably migrating the subfeatures of `css.properties.color` to `css.types.color`, then adding a subfeature for floating point numbers in the `rgb()` notation.

**Comment by Elchi3** [comment]
I think we addressed this topic in https://github.com/mdn/browser-compat-data/pull/1342
Is this something different?

**Comment by jpmedley** [comment]
@Elchi3, no. And your memory is better than mine. Almost a year on I'm thinking we should give this more thought. Specifically:
* The compat table is kind of [a jumbled mess](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#Browser_compatibility). How machine-friendly is this?
* I could organize this better by grouping statements about the same function? This would require duplicating entries that cover more than one function. It's not a huge problem now, but it could be in the future. 
* Giving the functions their own entries would make it possible to display this information hierarchically.

**Comment by Elchi3** [comment]
I'm going to close this stalled issue. 
We're thinking about introducing feature groups to BCD and so there will be a new approach that should address large compat tables and grouping statements etc.
