### ISSUE TITLE
How should we handle modifiers on getModifierState()

### ISSUE THREAD

**Issue by jpmedley** [mdn/browser-compat-data#3514]
I recently ran across [this Chromium ticket](https://bugs.chromium.org/p/chromium/issues/detail?id=265458) which shows that Chromium has, at least in the past, had variations on the values that can be passed to `getModifierState()`. After [consulting the MDN page](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/getModifierState#Browser_compatibility) for this function, I realized that Chromium is not the only browser family with variations. 

The question is should we include modifier data as a sub-level to `KeyboardEvent.getModifierState()`. This issue also applies to `MouseEvent.getModifierState()`.

**Comment by jpmedley** [comment]
Pinging this thread again.

**Comment by Elchi3** [comment]
I would add these as sub features of `getModifierState`. The table on that page will then render these in their own rows.

**Comment by vinyldarkscratch** [comment]
Looks like we already have "Accel" split out.  I'm working on something to resolve this now!
