### ISSUE TITLE
JSON linter: don't allow version_added === version_removed

### ISSUE THREAD

**Issue by a2sheppy** [mdn/browser-compat-data#3531]
We have a couple of places here and there where version_added is invalidly the same as version_removed; we need to update the linter to catch this.

**Comment by ddbeck** [comment]
Would you mind sharing a couple of these examples?

**Comment by a2sheppy** [comment]
I just submitted a PR that will fix them, but `RTCPeerConnection.onaddstream` has this problem, for instance:

https://github.com/mdn/browser-compat-data/blob/master/api/RTCPeerConnection.json#L1999

**Comment by ExE-Boss** [comment]
I’m also fixing https://github.com/mdn/browser-compat-data/blob/master/api/RTCPeerConnection.json#L1999 in #1712.

**Comment by vinyldarkscratch** [comment]
+1 for this.  Having a feature removed in the same version it was introduced in doesn’t make any sense!

**Comment by Elchi3** [comment]
I thought this would be checked here https://github.com/mdn/browser-compat-data/blob/master/test/test-versions.js#L51

But maybe it is suitable to test this in the consistency tests as well. I haven't reviewed it yet.

**Comment by ExE-Boss** [comment]
The test should be `compareVersions(a, b) >= 0`.
