### ISSUE TITLE
counter-increment support not up-to-date

### ISSUE THREAD

**Issue by av3** [mdn/browser-compat-data#3568]
I got an error using "counter-increment" in my CSS code that Edge 18 wouldn't support that property. But it's working and on https://caniuse.com/#search=counter-increment there are much more browser supported as in the counter-increment.json listed.

**Comment by vinyldarkscratch** [comment]
Can confirm both this and `counter-reset` work in Chrome, Edge, and Firefox!  I've updated the data for `counter-increment` based upon the data in `counter-reset` (they're both part of the same spec and work off of each other).
