### ISSUE TITLE
Edge's prefix for ::placeholder is -webkit-input-?

### ISSUE THREAD

**Issue by jaller94** [mdn/browser-compat-data#3578]
https://github.com/mdn/browser-compat-data/blob/ab222f95f5b453014e9e75e238c8952558221737/css/selectors/placeholder.json#L27-L34

According to this repo Edge's prefix for ::placeholder is `-webkit-input-`. This contradicts the [CanIUse](https://caniuse.com/#feat=css-placeholder) which claims that it is the more common `-ms-` prefix.

Can someone with access to Edge find out, if the browser is in fact using a webkit prefix?
If this is the case, please add an annotation or URL to strengthen confidence in this uncommon prefix.

**Comment by alexmayo** [comment]
Edge uses both the `-webkit-input-` prefix and `-ms-` prefix, it simply uses which ever one was set last.

**Comment by vinyldarkscratch** [comment]
Some testing revealed that Edge 18 does indeed support `-ms-input-` (just `-ms-` alone doesn't work) as well as `-webkit-input-`.  Internet Explorer does not support either.  Since Edge is going to be using Blink as its engine soon, we should add it in as a note.
