### ISSUE TITLE
Cookie max-age and prefix support

### ISSUE THREAD

**Issue by indolering** [mdn/browser-compat-data#36]
[This test](http://inikulin.github.io/cookie-compat/) states that neither IE nor Edge support `max-age`.  I have similar concerns about support for cookie prefixes....

**Comment by Elchi3** [comment]
Thanks for the issue!

max-age support is stored here https://github.com/mdn/browser-compat-data/blob/master/http/headers/set-cookie.json#L51
cookie prefixes support is stored here https://github.com/mdn/browser-compat-data/blob/master/http/headers/set-cookie.json#L147

I will happily review a PR that updates the compat data for these two features.
