### ISSUE TITLE
translate attribute data is potentially misleading

### ISSUE THREAD

**Issue by wbamberg** [mdn/browser-compat-data#3600]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1482896, especially https://bugzilla.mozilla.org/show_bug.cgi?id=1482896#c2.

As the comment says, the BCD for [`translate`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/translate) only indicates whether it can be scripted, which is I think generally the interpretation of "support" that we use for attributes. But in this case it's potentially misleading since it's still a useful attribute to include.

The comment suggests adding a kind of overall note to the BCD for this attribute, but I don't think BCD supports this - notes can only be attached to support statements. We could add a note for each browser that doesn't support the attribute, but that would tend to hide it (the attribute would look unsupported with an asterisk, which is pretty low-key).

Or we could add a paragraph in the Wiki page, but then BCD doesn't get to capture this nuance at all, so other consumers of this data won't get it.

Or we could mark it supported, but indicate that this does not include the ability to script it (or make scripting it a subfeature or something). This would be inconsistent with other attributes AFAIK but perhaps the most helpful.

**Comment by queengooborg** [comment]
Looking at the original Bugzilla report, it seems that this was filed when no browsers indicated support, but we've long since populated the data.  I think this can be safely closed.
