### ISSUE TITLE
":any-link" unprefixed support of Chrome and Safari missing

### ISSUE THREAD

**Issue by 1jj** [mdn/browser-compat-data#3641]
Unprefixed support of `:any-link` pseudo-class in not up to date.
It's in Chome 65
https://www.chromestatus.com/feature/5724922840088576
and Safari 9
https://developer.apple.com/library/archive/releasenotes/General/WhatsNewInSafari/Articles/Safari_9_0.html#//apple_ref/doc/uid/TP40014305-CH9-SW34

**Comment by vinyldarkscratch** [comment]
Closing this issue as both PRs that perform these updates.
