### ISSUE TITLE
Prefix spelled differently in CSS and API

### ISSUE THREAD

**Issue by jpmedley** [mdn/browser-compat-data#3670]
This came up in the context of PR #3571. In Chrome the webkit prefix is different in CSS and APIs. In [CSS it is enclosed in dashes (`-webkit-`)](https://cs.chromium.org/chromium/src/third_party/blink/web_tests/webexposed/css-property-listing-expected.txt) while [in IDL and the JS interfaces they create](https://chromium.googlesource.com/chromium/src/+/aa0ed75290c068427f90ede29a6efaf02e6e6522%5E%21/#F4), they are not. 

This ticket has two parts.

* [ ] Create a lint test to ensure that webkit references in css/ have dashes and that those in api/ do not.
* [x] Update all Chromium webkit references to exclude the dashes.

I assume that I will do this work if MDN agrees, but I cannot assign tickets to myself.

**Comment by ddbeck** [comment]
Good idea on linting this, @jpmedley!

I think it makes sense to have dashes for CSS data (`some-property` + `-webkit-` = `-webkit-some-property`) and to not have them in API data (`SomeAPI.method` + `webkit` = `SomeAPI.webkitmethod`). Though this relates to #3488 for many interfaces.

Here are the API files that contain (likely dubious) `"prefix": "-webkit-"` entries:

```
SourceBuffer.json
SourceBufferList.json
Navigator.json
HTMLMediaElement.json
Notification.json
MediaSource.json
```

I couldn't find any CSS entries that _did not_ have dashes (i.e., all the CSS prefixes containing the string `webkit` were `-webkit-`).

**Comment by jpmedley** [comment]
My quick glance didn't find any either. The API errors are a hypercorrection based on CSS.

**Comment by jpmedley** [comment]
The second bullet was addressed in #3672

**Comment by vinyldarkscratch** [comment]
I'm willing to bet that this doesn't just apply to Chromium, but all browsers.  A quick search revealed "-moz-" prefixes in the API files, when a manual test revealed that the true prefix is without dashes (plus dashes are not allowed in class/method names).

I'm submitting a new PR that will adjust the remaining prefixes in api/*.

**Comment by jpmedley** [comment]
I'll go one step further and say that this was deliberate, not coincidence, since CSS names have dashes and API names don't. Developers were just being consistent with established practice.

**Comment by Elchi3** [comment]
https://github.com/mdn/browser-compat-data/pull/3939 added this to the linter. Closing.
