### ISSUE TITLE
 tabs.captureTab() doesn't exist in Android

### ISSUE THREAD

**Issue by icl7126** [mdn/browser-compat-data#3679]
See:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/captureTab#Browser_compatibility

Android doesn't support this API.

**Comment by Elchi3** [comment]
Thanks for your report, @icl7126! Do you want to open a PR and mark this as unsupported?

**Comment by icl7126** [comment]
Sure... I will try to be less lazy next time 😃 
https://github.com/mdn/browser-compat-data/pull/3714

I've also notified author of this feature:

**Comment by vinyldarkscratch** [comment]
Closing this issue as the PR that fixes this has been merged.
