### ISSUE TITLE
Add Microsoft Edge on Chromium

### ISSUE THREAD

**Issue by bershanskiy** [mdn/browser-compat-data#3705]
I could not find an issue discussing this therefore I'm creating a new one. If I missed it, please point me to it.

As you are probably aware already, a while ago Microsoft has [announced](https://github.com/MicrosoftEdge/MSEdge) that they are switching Edge from EdgeHTML and Chakra to V8 and Blink. Now the first (unofficial) previews are appearing online. Since the new Edge will likely be more similar to Chrome rather than the previous Edge, I propose addition of the new browser to represent the change.

I believe that Edge on Chromium needs a separate listing the same way as Opera needs one even though it is based on Chromium. Also, I believe using the same name (just "Edge") would create more confusion than since it does not reflect the change.

**Comment by jpmedley** [comment]
+1 to all of this. We need someone from MS directly involved in this to advise us. Unfortunately Patrick and Erika have moved on to other projects. I currently do not have a contact.

**Comment by vinyldarkscratch** [comment]
#3264 is highly relevant to this issue, and on the other hand, I would say that separating Chromium-based Edge into a separate browser would be inconsistent with how this repository has done such changes, like with Opera and Webview.

**Comment by vinyldarkscratch** [comment]
I'm going to go ahead and close this issue since there have been other instances where we've shown disinterest in splitting browsers based upon their engine.
