### ISSUE TITLE
Make `npm run lint` more convenient for local testing?

### ISSUE THREAD

**Issue by ddbeck** [mdn/browser-compat-data#371]
Running `npm run lint` is a helpful way to find problems locally before submitting a PR. That said, the output is quite long. If your edits are early in the output, you might have to scroll back a long ways to find the error.

I'd like to suggest that `npm run lint` (or an alternative command) does something to control the output so that errors appear more conveniently. For instance, the linter could (optionally?) exit at the point a failure is discovered or show errors only (omitting output for `.json` files that pass linting).

**Comment by Elchi3** [comment]
I think this is fixed by having `console.error` calls and introducing the `npm run show-errors` command.
