### ISSUE TITLE
Intl.DateTimeFormat.prototype.formatToParts not supported on Edge

### ISSUE THREAD

**Issue by targumon** [mdn/browser-compat-data#3720]
The Browser compatibility table for [formatToParts](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat/formatToParts) claims that Edge has basic support for it.

Just checked on a Windows 10 machine with Edge 17.17134 and sadly it does not.

EDIT: Checked another machine and `formatToParts` does exist on Edge/18.17763

**Comment by Elchi3** [comment]
Thanks for this issue, confluence agrees with your findings. http://web-confluence.appspot.com/#!/catalog?releases=%5B%22Edge_17.17134_Windows_10.0%22,%22Edge_18.17763_Windows_10.0%22%5D&q=%22formatToParts%22

Do want to open a PR to update the data?

**Comment by targumon** [comment]
Done :-)

BTW, what does "edge_mobile" mean? I assume it refers to Edge on a **Windows Phone**.

Asking because I tested this function on various builds of Edge for **Android** and found that until recently it had the same `dayperiod` vs. `dayPeriod` issue that Chromium had, but I don't know if it's relevant.

**Comment by Elchi3** [comment]
>  I assume it refers to Edge on a Windows Phone.

Yeah, that's correct. 
(I'm unsure if we will continue with data gathering for edge_mobile, we will ask what Microsoft thinks at some point when they are doing doing the switch to Chromium on the desktop side).

**Comment by ddbeck** [comment]
Merged #3749, so this looks fixed to me. Thank you!
