### ISSUE TITLE
Should Internet Explorer be merged into Microsoft Edge?

### ISSUE THREAD

**Issue by ExE-Boss** [mdn/browser-compat-data#3725]
I’m asking because **Microsoft Edge** is a continuation of **Internet Explorer** and the version numbers continue where **IE** left off.

---

/cc @erikadoyle, @libbymc

**Comment by vinyldarkscratch** [comment]
With the probable addition of #3877 as well, this would be relatively easy to do.  Personally, I feel that merging them will help eliminate inconsistencies, and I support this.  At the same time, though, they're pretty heavily identified as separate products by Microsoft and other third parties.  It would be great to get someone from Microsoft to advise us!

**Comment by ddbeck** [comment]
>  At the same time, though, they're pretty heavily identified as separate products by Microsoft and other third parties. It would be great to get someone from Microsoft to advise us!

I think Microsoft's documentation rather clearly distinguishes between Internet Explorer and Edge ([example](https://docs.microsoft.com/en-us/microsoft-edge/deploy/microsoft-edge-faq#whats-the-difference-between-microsoft-edge-and-internet-explorer-11-how-do-i-know-which-one-to-use)). It's not as if Edge is a codename for a version of Internet Explorer (e.g., it'd be confusing and wrong to refer to "Microsoft Edge 8" or "Internet Explorer 14"). Absent a request from Microsoft to combine the IE and Edge, I think we should continue to keep the two browsers' data separate.

**Comment by vinyldarkscratch** [comment]
I was thinking the same thing: there are precise distinctions between IE and Edge in various places -- in the Microsoft documentation, on W3Schools...  At the same time, merging them would eliminate duplicate data in the repository, along with inconsistencies between such data.  This is definitely not an easy question to answer.

**Comment by ddbeck** [comment]
Are there examples of duplicate or inconsistent data _between_ Edge and IE? I'm not sure quite what you're getting at there.

**Comment by erikadoyle** [comment]
Sorry! Didn't see this earlier--I'm no longer with the Edge team.

@travisleithead, could you help advise here? Thanks!

**Comment by guidobouman** [comment]
Edge and IE have distinct different renderers. Edge will make the switch to the Chromium engine in the near future (beta's already available). And IE11 is still installed as a separate executable on all windows platforms. So, no, I don't think it's a good idea to merge the two. Supporting IE11 is a substantial task for a lot of developers, keep it as a different entity in the compat tables.

**Comment by Elchi3** [comment]
Yeah, IE and Edge continue to co-exist. So, we will not merge them.
