### ISSUE TITLE
globalThis is supported in Safari 12.1

### ISSUE THREAD

**Issue by renchap** [mdn/browser-compat-data#3741]
`globalThis` (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis) support has been added in this webkit commit: https://trac.webkit.org/changeset/239464/webkit

Verified in Safari version 12.1 (14607.1.40.1.4). Console output:
```
> globalThis
< Window {document: #document, window: Window, NaN: NaN, Infinity: Infinity, undefined: undefined, …}
```

**Comment by connorshea** [comment]
Confirmed by the ESCMAScript compat table: https://kangax.github.io/compat-table/esnext/#test-globalThis
