### ISSUE TITLE
text-decoration-thickness and text-underline-offset CSS properties

### ISSUE THREAD

**Issue by connorshea** [mdn/browser-compat-data#3786]
Safari implemented these two properties in Safari 12.1, sources here:

- https://trac.webkit.org/changeset/237835/webkit/ 
- https://trac.webkit.org/changeset/237903/webkit/
- https://webkit.org/blog/8496/release-notes-for-safari-technology-preview-70/
- https://webkit.org/blog/8718/new-webkit-features-in-safari-12-1/

Should we create new JSON files for them, or should we wait until another browser has them?

**Comment by Elchi3** [comment]
If they belong to an active standards document, I think we can go ahead and create the compat files as well as the MDN pages. @rachelandrew might know how stable these are right now.

**Comment by rachelandrew** [comment]
Currently FPWD https://drafts.csswg.org/css-text-decor-4/ so early days

**Comment by Elchi3** [comment]
I think we've added things that only shipped in one browser (and are also part of a spec). 
So, I'd say we can add this, it is part of the "Safari web" now :)

**Comment by vinyldarkscratch** [comment]
We've added proprietary MS-prefixed APIs only available in Edge.  Yeah, let's add them in!
