### ISSUE TITLE
Safari 12.1 supports CSS Logical Properties

### ISSUE THREAD

**Issue by connorshea** [mdn/browser-compat-data#3788]
This changeset is pretty huge: https://trac.webkit.org/changeset/234798/webkit/

Includes the following (I may have missed a few):

- `border-block-start`
- `border-block-end`
- `border-block-start-width`
- `border-block-start-style`
- `border-block-start-color`
- `border-block-end-width`
- `border-block-end-style`
- `border-block-end-color`
- `border-inline-start`
- `border-inline-end`
- `border-inline-start-width`
- `border-inline-start-style`
- `border-inline-start-color`
- `border-inline-end-width`
- `border-inline-end-style`
- `border-inline-end-color`
- `inline-size`
- `block-size`
- `max-block-size`
- `min-block-size`
- `max-inline-size`
- `min-inline-size`
- `margin-block-start`
- `margin-block-end`
- `margin-inline-start`
- `margin-inline-end`
- `padding-block-start`
- `padding-inline-start`
- `padding-block-end`
- `padding-inline-end`

It was included in [Safari TP 64](https://webkit.org/blog/8406/release-notes-for-safari-technology-preview-64/) and therefore Safari 12.1. Also listed on [caniuse](https://caniuse.com/#feat=css-logical-props).

**Comment by rachelandrew** [comment]
I can do these as I have been working round these recently

**Comment by connorshea** [comment]
I think this can be closed now?

**Comment by Elchi3** [comment]
I think so, yes.
