### ISSUE TITLE
Mirror data to eliminate inconsistencies

### ISSUE THREAD

**Issue by vinyldarkscratch** [mdn/browser-compat-data#3869]
Something to help eliminate inconsistency issues is to mirror all the data from the primary browsers over to their mobile counterparts and forked browsers.  This is an issue to track a huge series of pull requests that do just that, mirroring Firefox onto Firefox Android, and Chrome onto Chrome Android, Webview, Samsung Internet, and Opera.  (Not Opera Android just yet.)

The PRs are as follows:
- [x] #3747, #3826, #3827, #3828, #3829, #3830, #3831, #3832, #3833, #3834, #3835, #3836, #3837, #3838, #3839, #3840, #3841, #3842, #3843, #3856, #3857, #3858, #3859, #3860, #3861, #3862, #3863
- [ ] #3864
- [x] #3865, #3866, #3867, #3868
- [ ] #4636
- [ ] #4637
- [ ] #4705
- [ ] #4709

Another part is checking the primary browsers with their mobile counterparts and derivatives (such as Chrome to Opera, Firefox to Firefox Android) and making sure they roughly match.  I went through and ran a script that checks to see if the counterparts/derivatives have values marked as "false" when their inheritance does not (i.e. Chrome has support for feature "foo_bar" but Opera does not).  They are all listed here: https://gist.github.com/vinyldarkscratch/55e77caec88a5e67739f4fa80204db53

**Comment by vinyldarkscratch** [comment]
@jpmedley Would you say that this is a reasonable method of getting rid of the `null` and `true` values that have answers within the desktop versions?  (Something to note is that this doesn't replace `false` values, or existing version numbers, so features that we have determined were disabled in Webview or came to Chrome Android at a later date will not be affected.)

**Comment by jpmedley** [comment]
I'm worried about the edge cases where desktop and Android didn't ship in the same version. I would only do it with the following rules:

* Set WebView to false for anything listed [in this file](https://cs.chromium.org/chromium/src/android_webview/tools/system_webview_shell/test/data/webexposed/not-webview-exposed.txt).
* Replace null with true when desktop shows support. Use true even if desktop has a number. I can filter by these later and work to change true to a specific number.
* Leave alone any places where WebView and Android show true while desktop shows a number.

My actual preference would be to review all your PRs. My problem is I'm on the hook for content related to a Chrome beta release and [Google IO](https://events.google.com/io/) which both happen in about two weeks.

**Comment by vinyldarkscratch** [comment]
I totally understand what you mean there, thanks for taking the time to reply!  Yeah, this doesn't affect any Android versions that were set to anything other than `null`; only `null` values are replaced with their desktop mirroring, which covers the first and third rules.  I'm willing to bet that all the WebView non-exposed APIs have already been set to `false`, but I'll be sure to do a double-check and make sure that there weren't any stray values hanging around.  :wink:

**Comment by vinyldarkscratch** [comment]
As mentioned in @ddbeck's [comment](https://github.com/mdn/browser-compat-data/pull/4637#issuecomment-522557066), this should follow the bulk update process we have been formalizing recently.  So, let's give this a shot after we have completed migration 001, to sort features alphabetically!

**Comment by vinyldarkscratch** [comment]
I'm closing this PR in favor of #4719.
