### ISSUE TITLE
Deprecate unmaintained Chromium browsers?

### ISSUE THREAD

**Issue by vinyldarkscratch** [mdn/browser-compat-data#3875]
I'm really curious about what others think about dropping other web browsers aside from the main ones, such as UC Browser and QQ Browser.  Since they are derived from Chrome (specifically Chrome Android), updating them independently may not be needed.

These browsers include the following:
- Samsung Internet
- QQ Browser
- UC Browser
- Chinese UC Browser

**Comment by Elchi3** [comment]
I'm not sure about the Chromium-based browsers. In fact, I think, they have decent marketshare (varies largely on country) and we should keep them.

For Edge Mobile, it might make sense to drop it. Would be cool to get a word from Microsoft on this. I'll try to find an answer.

**Comment by vinyldarkscratch** [comment]
I see what you mean.  What I'm thinking about is that they're browsers based upon Chrome, and I think that they would follow the same data as Chrome Android, based upon whatever Chromium versions they derive from.

Maybe this won't be as important with the browser engines.

**Comment by Elchi3** [comment]
They are based upon Chrome, but there are differences sometimes actually. Otherwise, we could indeed drop the data and programmatically expose version numbers based upon a chrome mapping for those interested in chrome derivative browser versions. However, right now, we don't know these differences. Adding the engines to the schema and mirroring where we think we should mirror, will eventually reveal the differences (that's my hope at least).

**Comment by vinyldarkscratch** [comment]
I went ahead and separated Edge Mobile into its own issue to keep its discussion separate.  As far as the Chromium browsers, I'm curious to test this out a little, see if we can find some differences!

**Comment by jpmedley** [comment]
There are instances where Opera deliberately removed things when they ported. I've also been told by Samsung folks that though they start with a particular Chromium version, they've been known to pull features from later versions. As for other Chromium forks, who knows?

**Comment by vinyldarkscratch** [comment]
Yeouch, that certainly makes it confusing for Samsung Internet.  Why wouldn’t they just update the Chromium version as a whole rather than the specific features?  😫

**Comment by jpmedley** [comment]
They do what's judged to make money. That's all I know.

**Comment by HM100** [comment]
Samsung Internet is always a few Chromium versions ahead, as usual 😉.

**Comment by Elchi3** [comment]
The browsers listed in the first comment aren't really a priority this year, but I don't think we want to remove them at this point. Closing here.

**Comment by jpmedley** [comment]
UC dominates Asia. As some point this repo should have 100% coverage for UC features. I have no idea how to achieve that.

**Comment by Elchi3** [comment]
I agree whole-heartily. I hope we can get to that next year.
