### ISSUE TITLE
Deprecate Edge Mobile?

### ISSUE THREAD

**Issue by vinyldarkscratch** [mdn/browser-compat-data#3888]
This is related to #1671 and #3116.  For clarification, Edge Mobile is referring to the Windows Phone edition.

The Windows Phone OS is officially a [deprecated platform](https://support.microsoft.com/en-us/help/4485197/windows-10-mobile-end-of-support-faq), Edge Mobile is deprecated as well.  Due to the fact that the Edge Mobile iOS edition uses Safari WebKit, and the Android version uses Chromium/WebView, it has already been covered by existing compatibility data.  Retaining only the desktop data may be the better route.

Advice from Microsoft members would be nice to have as we push forward.

**Comment by atopal** [comment]
This was discussed at the last MDN product advisory board meeting on June 5 2019. Kyle Pflug from Microsoft suggested we drop Edge Mobile from the tables and the data.

**Comment by vinyldarkscratch** [comment]
Thanks for your comment, @atopal!  In that case, let us work towards dropping Edge Mobile from the compatibility data.

**Comment by C-Lodder** [comment]
@vinyldarkscratch @atopal Edge Mobile is still available on Android and has not been discontinued, so is dropping it really a good option?

**Comment by ddbeck** [comment]
The Edge Mobile data we have is specifically for Edge on Windows Mobile. IIRC, Edge on Android is an Android WebView.

**Comment by vinyldarkscratch** [comment]
The moment has finally come where we can officially say: this issue is complete, Edge Mobile has been removed!

**Comment by ddbeck** [comment]
With #4280 merged, this one is all wrapped up. 🎉 

Now let's pour one out for Edge Mobile 🍺
