### ISSUE TITLE
Firefox version for Server-Timing support incorrect?

### ISSUE THREAD

**Issue by SebastianZ** [mdn/browser-compat-data#3901]
According to [bug 1413999](https://bugzilla.mozilla.org/show_bug.cgi?id=1413999), support for the `Server-Timing` trailing header was already added in Firefox 59 and not in 61. What was added in 61 was the support for the related JavaScript interface `PerformanceServerTiming` (see [bug 1423495](https://bugzilla.mozilla.org/show_bug.cgi?id=1423495)).

I didn't verify this so far, though.

@Elchi3 Do you remember why you added 61 as version for that?

Sebastian

**Comment by Elchi3** [comment]
I think the `Server-Timing` header is useless if its data isn't surfaced anywhere, so 59 is misleading. Originally, it was planned to land it together with the JS API in 59 (see tracking flags in https://bugzilla.mozilla.org/show_bug.cgi?id=1423495), but then it slipped to 61.

**Comment by Elchi3** [comment]
Please re-open if that didn't answer your question.
