### ISSUE TITLE
Need data for web-supported regular expressions

### ISSUE THREAD

**Issue by jpmedley** [mdn/browser-compat-data#3937]
Not that we need any more work, but I just found this: https://www.chromestatus.com/features/5653365786673152

There's currently no way to represent that regex named capture groups are only supported from Chrome 64 onward.

**Comment by vinyldarkscratch** [comment]
We could perhaps through it into a note?  It's how we've seemingly done such indication before.

**Comment by jpmedley** [comment]
That would work if this were an edge case. It is not.

**Comment by jpmedley** [comment]
I wouldn't expect this to be done right away. I think we'd all like to finish something first like eliminating all the nulls and trues. Pick your threshold.

**Comment by Elchi3** [comment]
I think, much like lookbehind assertions, this should be a subfeature. See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp#Browser_compatibility and https://github.com/mdn/browser-compat-data/blob/master/javascript/builtins/RegExp.json#L722
