### ISSUE TITLE
api.Request.destination is supported on Safari 10+

### ISSUE THREAD

**Issue by wanderview** [mdn/browser-compat-data#3959]
I just tested `Request.destination` on safari 11.1 and 12.0 in browser stack.  It seems to be supported in both versions.  MDN currently claims its not implemented on safari:

https://developer.mozilla.org/en-US/docs/Web/API/Request/destination#Browser_compatibility

**Comment by vinyldarkscratch** [comment]
Can confirm this by testing in LambdaTest on Safari 11.0 as well.  Sending a PR to fix this now.  ;)
