### ISSUE TITLE
Testing infrastructure: BrowserStack, for owners and/or peers?

### ISSUE THREAD

**Issue by vinyldarkscratch** [mdn/browser-compat-data#4000]
**This is a question dedicated directly towards the repository owners.**

A little backstory: I've been using LambdaTest now, but I've been increasingly frustrated with the number of major bugs and issues that prevent me from accurately testing features for BCD.  Even though their customer service is responsive, I'm already wanting to switch after just two weeks with them.  I've been thinking about switching to BrowserStack for a while, for their wide range of browsers and platforms, and their relatively high ratings (also that Mozilla's already partnered with them).  Then, I noticed that they have a free, practically unlimited plan for open source projects, with five parallel connections allowed.  All they ask for in return is a little statement in the readme.

This may be something less for BCD and more for MDN as a whole, or maybe it's completely out of the question and I shouldn't even be mentioning it.  I just figured that I would throw my thoughts to the wind and see if it sticks!

**Comment by Elchi3** [comment]
The MDN team has access to Saucelabs. I'm using it quite frequently for BCD questions. Are you asking for access or an account? We might be able to get you something, I guess. I would have to check on that with my boss (@chrisdavidmills).

**Comment by chrisdavidmills** [comment]
I would be more than happy to give @vinyldarkscratch a saucelabs account. Let me know your interest.

**Comment by vinyldarkscratch** [comment]
Yxwwhww

**Comment by vinyldarkscratch** [comment]
Yeah, that would be great, thank you so much!   💜  In that case, we should probably move to private emails — I’ll shoot you one shortly, @chrisdavidmills.  😉

**Comment by chrisdavidmills** [comment]
OK, cool.
