### ISSUE TITLE
Error in <base> element note

### ISSUE THREAD

**Issue by jwhitlock** [mdn/browser-compat-data#403]
There's an extra ``>`` in this note for the base element, so that the display is ``nearest value of <>base> is used``:

https://github.com/mdn/browser-compat-data/blob/dc21a168d784fe66a799b5b6379042a28637633a/html/elements/base.json#L31

It was reported to Bugzilla as [bug 1401216](https://bugzilla.mozilla.org/show_bug.cgi?id=1401216).

**Comment by daddykotex** [comment]
Thanks, I did not know this was hosted here
