### ISSUE TITLE
Chrome/Firefox: css.selectors.fullscreen appears to be unsupported

### ISSUE THREAD

**Issue by vinyldarkscratch** [mdn/browser-compat-data#4030]
**I decided an issue would be better than a pull request since this may require discussion.**

Chrome indicated support for the `:fullscreen` selector under the `:-webkit-full-screen` alternative name.  However, from manual testing, I haven't been able to identify support for this in Chrome, or even Firefox.  I tested on both macOS and Windows 10 with the latest of both browsers, and Windows XP in Chrome 15.

<img width="2032" alt="Screen Shot 2019-04-30 at 17 03 43" src="https://user-images.githubusercontent.com/5179191/57000998-23ee4000-6b6b-11e9-8f7e-71a93ced7c49.png">
<img width="551" alt="Screen Shot 2019-04-30 at 17 04 44" src="https://user-images.githubusercontent.com/5179191/57000999-23ee4000-6b6b-11e9-95da-2f50b34139cf.png">

This was the code that I used, which is based upon the example on the MDN page (I switched to `:fullscreen` to test Firefox):

```html
<!DOCTYPE html>
<html>
	<head>
		<style>
			#fs-toggle:not(:-webkit-full-screen) {
				background-color: #afa;
			}

			#fs-toggle:-webkit-full-screen {
				background-color: #faa !important;
			}
		</style>
	</head>
	<body>
		<h1>MDN Web Docs Demo: :fullscreen pseudo-class</h1>
		<p>This demo uses the <code>:fullscreen</code> pseudo-class to automatically change the style of a button used to toggle full-screen mode on and off, entirely using CSS.</p>
		<button id="fs-toggle">Toggle Fullscreen</button>
	</body>
</html>

```

**Comment by vinyldarkscratch** [comment]
@jpmedley, would you be willing to provide feedback for Chrome?

**Comment by jpmedley** [comment]
I can confirm that this does not work in Chrome 74. I don't know if it ever worked in Chrome much less when it might have been removed.

**Comment by vinyldarkscratch** [comment]
Closing this issue as support was proven.  (The selector relies on the Full Screen API; Menu > Enter Full Screen will not trigger the selector.)
