### ISSUE TITLE
Lint for unnnecessary attributes in markup (e.g. inside notes)

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/browser-compat-data#4033]
As per https://github.com/mdn/browser-compat-data/pull/3981#issuecomment-488245877

We ought to update the linter to flag unneccessary attributes (like title attributes in notes); they aren't useful and mean more of a buden if we try to localize BCD in the future.

**Comment by ExE-Boss** [comment]
I’m working on this right now.
