### ISSUE TITLE
Chrome Android release dates are wrong

### ISSUE THREAD

**Issue by connorshea** [mdn/browser-compat-data#4045]
I noticed after looking at the data in [my explorer app](https://mdn-compat-data-explorer.herokuapp.com/browsers/chrome_android) that the release dates for Chrome Android 65 and 66 say 2017 when they should say 2018. At least, I assume that's what they should say.

https://github.com/mdn/browser-compat-data/blob/6f84c3789e4f44a655907287fd9f4527bc134cad/browsers/chrome_android.json#L210-L216

I think these are the only versions without proper release dates, but you can take a look at [this page](https://mdn-compat-data-explorer.herokuapp.com/browsers/chrome_android) to verify that the versions are sorted correctly (they're sorted by release date, and the version number should go in order if the dates are correct).

----

p.s. please enjoy this Haskell my friend wrote to kinda parse the MDN BCD JSON

<details>
<summary>Haskell</summary>

```haskell
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE NoMonomorphismRestriction #-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE NoMonomorphismRestriction #-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE TypeApplications #-}
module Blow where

import Network.HTTP.Conduit (simpleHttp)
import qualified Data.ByteString.Lazy as BS
import Control.Lens
import Data.Aeson
import Data.Aeson.Lens
import qualified Data.Text as Text
import Data.Data.Lens
import Data.HashMap.Strict (HashMap)

getUrl :: IO BS.ByteString
getUrl = simpleHttp "https://gist.githubusercontent.com/connorshea/f38fe42635170fd60c4e5cee0a76f20c/raw/a8cbacbe35a24aef3d7430368d3d38df5c12ef73/lmao.json"

urlLens 
  = _Object 
  . traversed
  . _Object
  . traversed
  . _Object
  . traversed
  . _Object
  . at "__compat"
  . _Just
  . _Object
  . at "mdn_url"
  . _Just
  . _String

-- Or, be very lazy and let uniplate do the work
-- This will change any key of "mdn_url" that is a string, recursively
plateLens
  = _Object
  . cosmosOf uniplate
  . at "mdn_url"
  . _Just
  . _String

unsecure = Text.replace "https" "http"

test = do
  r <- getUrl
  BS.writeFile "jsonOut.json" $
    (urlLens %~ unsecure) r
  BS.writeFile "urls.json" $ review _String
    (view plateLens r)
```
</details>

**Comment by connorshea** [comment]
It may be worth making a lint check to ensure that browsers versions and release dates both increase with every subsequent version (though I know this would only work for certain browsers, since some of them have weird versioning schemes).

**Comment by Elchi3** [comment]
Great catch, thank you! :+1: 
I'm not sure it is worth to lint this, as there are indeed sometimes weird versioning schemes.
