### ISSUE TITLE
Use Prettier to enforce code styling

### ISSUE THREAD

**Issue by vinyldarkscratch** [mdn/browser-compat-data#4074]
_This issue initially discussed both Prettier and ESLint together for code styling and quality, but has been revised to focus solely on Prettier._

When reviewing a number of pull requests related to the linter updates, I noticed that there were a number of styling updates within them that caused review to be a little bit challenging.  It made me realize, however, that we should enforce a code styling format for our JavaScript.  From what I can tell, Prettier seems to be the dominant library for code styling, and from my testing, is pretty easy to configure.

**Comment by ExE-Boss** [comment]
I’ve got #3737 to do the same thing.

**Comment by vinyldarkscratch** [comment]
Looking into it, I've found out that Prettier is only a code formatting plugin, and not a code quality plugin.  I think that what we're looking for is more along the lines of code quality, though I can only speak for myself on that one.  Regardless, from what I can tell, this is an MDN-wide decision, not just a BCD decision.

I'm opening an issue on the MDN main repository to help start a discussion.

**Comment by vinyldarkscratch** [comment]
Closing this issue -- we'll worry about this when we've reached an MDN-wide conclusion.

**Comment by vinyldarkscratch** [comment]
I'm reopening this issue as we seem to be reaching a final conclusion for MDN as a whole pretty quickly, and have basically come to a decision for BCD already.  An ADR is in development now, see https://github.com/mdn/mdn/pull/73 for more details.
