### ISSUE TITLE
`matchAll` available for Node V12

### ISSUE THREAD

**Issue by mets11rap** [mdn/browser-compat-data#4087]
Unfortunately, I am unable to make a pull request, but I just wanted to let you know, `String.prototype.matchAll()` was added in Node V12

**Comment by vinyldarkscratch** [comment]
Thanks for reporting this!  I'm unable to find any documentation stating as such (I checked node.green and the changelog back to version 8.0.0).  If you could link some sources to help confirm this, that would be great!

**Comment by mets11rap** [comment]
It seems I was wrong. I apologize.

**Comment by vinyldarkscratch** [comment]
You're all good, no worries -- thanks for double-checking!
