### ISSUE TITLE
Linter: Forbid true and null per browser per folder

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#4121]
Now that we have 100% real values for IE in `css/` (see #3801), I would like to forbid adding `true` and `null` for IE in the `css/` folder in new PRs, so that we don't regress this.

I think https://github.com/vinyldarkscratch/browser-compat-data/blob/traverse-script/scripts/traverse.js could be re-used for that, but re-written as `test-real-values.js` (or similar).

For now it is only IE in `css/`, soon it might be Firefox in `css/` and hopefully next quarter this will expand to more browsers and more folders (I haven't checked, but maybe we already provide full real values for browser x in folder y.

**Comment by vinyldarkscratch** [comment]
I'm down for this plan!  Actually, regarding that script, I recently upgraded it to support command line arguments and turned it into a PR (#4120).  I'd be more than happy to refactor it into a linter test to satisfy this issue!

**Comment by Elchi3** [comment]
Sounds good to me! Actually, I think both could be useful.
