### ISSUE TITLE
Document traverse script usage

### ISSUE THREAD

**Issue by ddbeck** [mdn/browser-compat-data#4147]
A new `npm run traverse` script was added #4120. It does have some help text (via `npm run traverse -- --help`), but it's not clear what the script's for or how to use it.

We should document in a bit more detail what it means to "test for" a specified value (e.g., is the test equality or something else? what happens if a given browser-feature is an array of support statements?) and illustrate it with some examples. In other words, we should explain what problems the script solves and how to use it to solve those problems.

(probably of interest to @Elchi3 and @vinyldarkscratch)

**Comment by vinyldarkscratch** [comment]
I'm more than happy to tackle this one.  The main purpose of the script is to track down all of the `null` and `true` values in browsers to reach our 2019 Key Result, though can also be used to find all the entries in a specific browser version, say "37" in WebView.  I'm thinking about adding the documentation to docs/testing.md, but maybe we should create a new file called `scripts.md` to include the other scripts, such as `statistics`?
