### ISSUE TITLE
Complete list-style-type types

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#4148]
https://developer.mozilla.org/en-US/docs/Web/CSS/list-style-type is a property that can accept many values and we don't currently capture all of them in our data.

My findings:

## Chrome
Supports all of these as they are mentioned in https://cs.chromium.org/chromium/src/third_party/blink/renderer/core/css/css.dict?l=263

1. arabic-indic (**missing**) (Chrome 6) (as it was in Safari 4.1 and in WebKit then)
2. armenian (in BCD) (Chrome 1)
3. bengali (**missing**) (Chrome 6) (as it was in Safari 4.1 and in WebKit then)
4. cambodian  (**missing**) (Chrome 6) (as it was in Safari 4.1 and in WebKit then)
5. circle (**missing**) (Chrome 1)
6. cjk-earthly-branch (**missing**) (Chrome 6) (as it was in Safari 4.1 and in WebKit then)
7. cjk-heavenly-stem (**missing**) (Chrome 6) (as it was in Safari 4.1 and in WebKit then)
8. cjk-ideographic (in BCD) (Chrome 1)
9. decimal (**missing**) (Chrome 1)
10. decimal-leading-zero (in BCD) (Chrome 1)
11. devanagari (**missing**) (Chrome 6) (as it was in Safari 4.1 and in WebKit then)
12. disc (**missing**) (Chrome 1)
13. ethiopic-halehame (**missing**) (Chrome 45)
14. ethiopic-halehame-am (**missing**) (Chrome 45)
15. ethiopic-halehame-ti-er (**missing**) (Chrome 6) (as it was in Safari 4.1 and in WebKit then)
16. ethiopic-halehame-ti-et (**missing**) (Chrome 6) (as it was in Safari 4.1 and in WebKit then)
17. georgian (in BCD) (Chrome 1)
18. gujarati (**missing**) (Chrome 6) (as it was in Safari 4.1 and in WebKit then)
19. gurmukhi (**missing**) (Chrome 6) (as it was in Safari 4.1 and in WebKit then)
20. hangul (**missing**) (Chrome 6) (as it was in Safari 4.1 and in WebKit then)
21. hangul-consonant (**missing**) (Chrome 6) (as it was in Safari 4.1 and in WebKit then)
22. hebrew (in BCD) (Chrome 1)
23. hiragana (in BCD) (Chrome 1)
24. hiragana-iroha (in BCD) (Chrome 1)
25. kannada (**missing**) (Chrome 6) (as it was in Safari 4.1 and in WebKit then)
26. katakana (in BCD) (Chrome 1)
27. katakana-iroha (in BCD) (Chrome 1)
28. khmer (**missing**) (Chrome 6) (as it was in Safari 4.1 and in WebKit then)
29. korean-hangul-formal (**missing**) (Chrome 45) (see https://github.com/chromium/chromium/commit/4cbe679952bd804d06298edc553748d3c7d96d18)
30. korean-hanja-formal (**missing**) (Chrome 45) (see https://github.com/chromium/chromium/commit/11a6b28298816374c68a8aa8ec665079ad4db26a)
31. korean-hanja-informal (**missing**) (Chrome 45) (see https://github.com/chromium/chromium/commit/11a6b28298816374c68a8aa8ec665079ad4db26a)
32. lao (**missing**) (Chrome 6) (as it was in Safari 4.1 and in WebKit then)
33. lower-alpha (**missing**) (Chrome 1)
34. lower-armenian (**missing**) (Chrome 13) (as it was in Safari 5.1 and in WebKit then)
35. lower-greek (in BCD) (Chrome 1)
36. lower-latin (in BCD) (Chrome 1)
37. lower-roman (**missing**) (Chrome 1)
38. malayalam (**missing**) (Chrome 6) (as it was in Safari 4.1 and in WebKit then)
39. mongolian (**missing**) (Chrome 6) (as it was in Safari 4.1 and in WebKit then)
40. myanmar (**missing**) (Chrome 6) (as it was in Safari 4.1 and in WebKit then)
41. oriya (**missing**) (Chrome 6) (as it was in Safari 4.1 and in WebKit then)
42. persian (**missing**) (Chrome 6) (as it was in Safari 4.1 and in WebKit then)
43. simp-chinese-formal
44. simp-chinese-informal
45. square (**missing**) (Chrome 1)
46. telugu (**missing**) (Chrome 6) (as it was in Safari 4.1 and in WebKit then)
47. thai (**missing**) (Chrome 6) (as it was in Safari 4.1 and in WebKit then)
48. tibetan (**missing**) (Chrome 6) (as it was in Safari 4.1 and in WebKit then)
49. trad-chinese-formal
50. trad-chinese-informal
51. upper-alpha (**missing**) (Chrome 1)
52. upper-armenian  (**missing**) (Chrome 13) (as it was in Safari 5.1 and in WebKit then)
53. upper-latin (in BCD) (Chrome 1)
54. upper-roman (**missing**) (Chrome 1)
55. urdu (**missing**) (Chrome 6) (as it was in Safari 4.1 and in WebKit then)

Chrome removed support for a few styles in https://bugs.chromium.org/p/chromium/issues/detail?id=413631 ([this landed in Chrome 45](https://storage.googleapis.com/chromium-find-releases-static/2b9.html#2b9f211d1b5e481a4bfb3c3e6efc81a11268541a)) (see also https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/C_GpBXGLyOM)
- binary (**missing**) (added in Chrome 6, removed in Chrome 45)
- lower-hexadecimal (**missing**) (added in Chrome 6, removed in Chrome 45)
- octal (**missing**) (added in Chrome 6, removed in Chrome 45)
- upper-hexadecimal (**missing**) (added in Chrome 6, removed in Chrome 45)
- afar (**missing**) (added in Chrome 6, removed in Chrome 45)
- ethiopic-halehame-aa-et (**missing**) (added in Chrome 6, removed in Chrome 45)
- ethiopic-halehame-aa-er (**missing**) (added in Chrome 6, removed in Chrome 45)
- amharic (**missing**) (added in Chrome 6, removed in Chrome 45)
- ethiopic-halehame-am-et (**missing**) (added in Chrome 6, removed in Chrome 45)
- amharic-abegede (**missing**) (added in Chrome 6, removed in Chrome 45)
- ethiopic-abegede-am-et (**missing**) (added in Chrome 6, removed in Chrome 45)
- ethiopic (**missing**) (added in Chrome 6, removed in Chrome 45)
- ethiopic-halehame-gez (**missing**) (added in Chrome 6, removed in Chrome 45)
- ethiopic-abegede (**missing**) (added in Chrome 6, removed in Chrome 45)
- ethiopic-abegede-gez (**missing**) (added in Chrome 6, removed in Chrome 45)
- lower-norwegian (**missing**) (added in Chrome 6, removed in Chrome 45)
- oromo (**missing**) (added in Chrome 6, removed in Chrome 45)
- ethiopic-halehame-om-et (**missing**) (added in Chrome 6, removed in Chrome 45)
- sidama (**missing**) (added in Chrome 6, removed in Chrome 45)
- ethiopic-halehame-sid-et (**missing**) (added in Chrome 6, removed in Chrome 45)
- somali (**missing**) (added in Chrome 6, removed in Chrome 45)
- ethiopic-halehame-so-et (**missing**) (added in Chrome 6, removed in Chrome 45)
- tigre (**missing**) (added in Chrome 6, removed in Chrome 45)
- ethiopic-halehame-tig (**missing**) (added in Chrome 6, removed in Chrome 45)
- tigrinya-er (**missing**) (added in Chrome 6, removed in Chrome 45)
- tigrinya-er-abegede (**missing**) (added in Chrome 6, removed in Chrome 45)
- ethiopic-abegede-ti-er (**missing**) (added in Chrome 6, removed in Chrome 45)
- tigrinya-et (**missing**) (added in Chrome 6, removed in Chrome 45)
- asterisks  (**missing**) (added in Chrome 13, removed in Chrome 45)
- footnotes (**missing**) (added in Chrome 13, removed in Chrome 45)

 ## Firefox 
Supports all of these mentioned in https://dxr.mozilla.org/mozilla-central/source/layout/style/res/counterstyles.css

1. -moz-arabic-indic (in BCD) (Fx 1)
2. -moz-bengali (in BCD) (Fx 1)
3. -moz-cjk-earthly-branch (in BCD) (Fx 1)
4. -moz-cjk-heavenly-stem (in BCD) (Fx 1)
5. -moz-devanagari (in BCD) (Fx 1)
6. -moz-ethiopic-halehame (**missing**) (Fx 1)
7. -moz-ethiopic-halehame-am (**missing**) (Fx 1)
8. -moz-ethiopic-halehame-ti-er (**missing**) (Fx 1)
9. -moz-ethiopic-halehame-ti-et (**missing**) (Fx 1)
10. -moz-ethiopic-numeric (in BCD) (Fx 1)
11. -moz-gujarati (in BCD) (Fx 1)
12. -moz-gurmukhi (in BCD) (Fx 1)
13. -moz-hangul (**missing**) (Fx 1)
14. -moz-hangul-consonant (**missing**) (Fx 1)
15. -moz-japanese-formal (in BCD) (Fx 1)
16. -moz-japanese-informal (in BCD) (Fx 1)
17. -moz-kannada (in BCD) (Fx 1)
18. -moz-khmer (in BCD) (Fx 1)
19. -moz-lao (in BCD) (Fx 1)
20. -moz-malayalam (in BCD) (Fx 1)
21. -moz-myanmar (in BCD) (Fx 1)
22. -moz-oriya (in BCD) (Fx 1)
23. -moz-persian (in BCD) (Fx 1)
24. -moz-simp-chinese-formal (in BCD) (Fx 1)
25. -moz-simp-chinese-informal (in BCD) (Fx 1)
26. -moz-tamil (in BCD) (Fx 1)
27. -moz-telugu (in BCD) (Fx 1)
28. -moz-thai (in BCD) (Fx 1)
29. -moz-trad-chinese-formal (in BCD) (Fx 1)
30. -moz-trad-chinese-informal (in BCD) (Fx 1)
31. -moz-urdu (**missing**) (Fx 1)
32. arabic-indic (in BCD) (Fx 33) ([commit](https://hg.mozilla.org/releases/mozilla-beta/rev/8e9b139e30b9))
33. armenian (in BCD) (Fx 1)
34. bengali (in BCD) (Fx 33) ([commit](https://hg.mozilla.org/releases/mozilla-beta/rev/8e9b139e30b9))
35. cambodian (**missing**) (Fx 33) ([commit](https://hg.mozilla.org/releases/mozilla-beta/rev/8e9b139e30b9))
36. cjk-decimal (in BCD) (Fx 28)
37. cjk-earthly-branch (in BCD) (Fx 33) ([commit](https://hg.mozilla.org/releases/mozilla-beta/rev/8e9b139e30b9))
38. cjk-heavenly-stem (in BCD) (Fx 33) ([commit](https://hg.mozilla.org/releases/mozilla-beta/rev/8e9b139e30b9))
39. cjk-ideographic (in BCD) (Fx 1)
40. decimal-leading-zero (in BCD) (Fx 1)
41. devanagari (in BCD) (Fx 33) ([commit](https://hg.mozilla.org/releases/mozilla-beta/rev/8e9b139e30b9))
42. georgian (in BCD) (Fx 1)
43. gujarati (in BCD) (Fx 33) ([commit](https://hg.mozilla.org/releases/mozilla-beta/rev/8e9b139e30b9))
44. gurmukhi (in BCD) (Fx 33) ([commit](https://hg.mozilla.org/releases/mozilla-beta/rev/8e9b139e30b9))
45. hebrew (in BCD) (Fx 1)
46. hiragana (in BCD) (Fx 1)
47. hiragana-iroha (in BCD) (Fx 1)
48. kannada (in BCD) (Fx 33) ([commit](https://hg.mozilla.org/releases/mozilla-beta/rev/8e9b139e30b9))
49. katakana (in BCD) (Fx 1)
50. katakana-iroha (in BCD) (Fx 1)
51. khmer (in BCD) (Fx 33) ([commit](https://hg.mozilla.org/releases/mozilla-beta/rev/8e9b139e30b9))
52. lao (in BCD) (Fx 33) ([commit](https://hg.mozilla.org/releases/mozilla-beta/rev/8e9b139e30b9))
53. lower-alpha (**missing**) (Fx 1)
54. lower-armenian (**missing**) (Fx 33) ([commit](https://hg.mozilla.org/releases/mozilla-beta/rev/8e9b139e30b9))
55. lower-greek (in BCD) (Fx 1)
56. lower-latin (in BCD) (Fx 1)
57. lower-roman (**missing**) (Fx 1)
58. malayalam (in BCD) (Fx 33) ([commit](https://hg.mozilla.org/releases/mozilla-beta/rev/8e9b139e30b9))
59. mongolian (in BCD) (Fx 33) ([commit](https://hg.mozilla.org/releases/mozilla-beta/rev/8e9b139e30b9))
60. myanmar (in BCD) (Fx 33) ([commit](https://hg.mozilla.org/releases/mozilla-beta/rev/8e9b139e30b9))
61. oriya (in BCD) (Fx 33) ([commit](https://hg.mozilla.org/releases/mozilla-beta/rev/8e9b139e30b9))
62. persian (in BCD) (Fx 33) ([commit](https://hg.mozilla.org/releases/mozilla-beta/rev/8e9b139e30b9))
63. tamil (in BCD) (Fx 33) ([commit](https://hg.mozilla.org/releases/mozilla-beta/rev/8e9b139e30b9))
64. telugu (in BCD) (Fx 33) ([commit](https://hg.mozilla.org/releases/mozilla-beta/rev/8e9b139e30b9))
65. thai (in BCD) (Fx 33) ([commit](https://hg.mozilla.org/releases/mozilla-beta/rev/8e9b139e30b9))
66. tibetan (**missing**) (Fx 33) ([commit](https://hg.mozilla.org/releases/mozilla-beta/rev/8e9b139e30b9))
67. upper-alpha (**missing**) (Fx 1)
68. upper-armenian (**missing**) (Fx 33) ([commit](https://hg.mozilla.org/releases/mozilla-beta/rev/8e9b139e30b9))
69. upper-latin (in BCD) (Fx 1)
70. upper-roman (**missing**) (Fx 1)

Also supports complex counter styles:
- korean-hangul-formal (in BCD) (Fx 28)
- japanese-informal (in BCD) (Fx 28)
- japanese-formal (in BCD) (Fx 28)
- korean-hanja-formal (in BCD) (Fx 28)
- korean-hanja-informal (in BCD) (Fx 28)
- simp-chinese-formal (in BCD) (Fx 28)
- simp-chinese-informal (in BCD) (Fx 28)
- trad-chinese-formal (in BCD) (Fx 28)
- trad-chinese-informal (in BCD) (Fx 28)
- ethiopic-numeric (in BCD) (Fx 33)

And symbolic styles:
- disc (**missing**)  (Fx 1)
- circle (**missing**)  (Fx 1)
- square (**missing**)  (Fx 1)
- disclosure-open (in BCD) (Fx 33)
- disclosure-closed (in BCD) (Fx 33)

## Safari
See https://github.com/WebKit/webkit/blob/9b169b6c85394d94f172e5d75ca2f6c74830e99c/Source/WebCore/css/CSSValueKeywords.in#L332

1. afar (**missing**) (Safari 4.1 – [WebKit commit 2010-01-18](https://github.com/WebKit/webkit/commit/3974e472daf8d63470023afef8a06e1f06d87fcc#diff-d613125bb3b51d54ea429c74f263c097))
2. amharic (**missing**) (Safari 4.1 – [WebKit commit 2010-01-18](https://github.com/WebKit/webkit/commit/3974e472daf8d63470023afef8a06e1f06d87fcc#diff-d613125bb3b51d54ea429c74f263c097))
3. amharic-abegede (**missing**) (Safari 4.1 – [WebKit commit 2010-01-18](https://github.com/WebKit/webkit/commit/3974e472daf8d63470023afef8a06e1f06d87fcc#diff-d613125bb3b51d54ea429c74f263c097))
4. arabic-indic (**missing**) (Safari 4.1 – [WebKit commit 2010-02-07](https://github.com/WebKit/webkit/commit/4b0fa3ae40d3b022e045a7c1a256ee11de5ddd0b#diff-fb435c4214366f5ed474b2b7fbcbbcb1))
5. armenian (in BCD) (Safari 1 – in WebKit initial revision)
6. asterisks (**missing**) (Safari 5.1 – [WebKit commit 2010-08-27](https://github.com/WebKit/webkit/commit/ab35e2941ceceface481ca7f1cf4e300706b9aaa#diff-d613125bb3b51d54ea429c74f263c097))
7. bengali (**missing**) (Safari 4.1 – [WebKit commit 2010-02-07](https://github.com/WebKit/webkit/commit/4b0fa3ae40d3b022e045a7c1a256ee11de5ddd0b#diff-fb435c4214366f5ed474b2b7fbcbbcb1))
8. binary (**missing**) (Safari 4.1 – [WebKit commit 2010-02-07](https://github.com/WebKit/webkit/commit/4b0fa3ae40d3b022e045a7c1a256ee11de5ddd0b#diff-fb435c4214366f5ed474b2b7fbcbbcb1))
9. cambodian (**missing**) (Safari 4.1 – [WebKit commit 2010-02-07](https://github.com/WebKit/webkit/commit/4b0fa3ae40d3b022e045a7c1a256ee11de5ddd0b#diff-fb435c4214366f5ed474b2b7fbcbbcb1))
10. circle (**missing**) (Safari 1 – in WebKit initial revision)
11. cjk-earthly-branch (**missing**) (Safari 4.1 – [WebKit commit 2010-01-18](https://github.com/WebKit/webkit/commit/3974e472daf8d63470023afef8a06e1f06d87fcc#diff-d613125bb3b51d54ea429c74f263c097))
12. cjk-heavenly-stem (**missing**) (Safari 4.1 – [WebKit commit 2010-01-18](https://github.com/WebKit/webkit/commit/3974e472daf8d63470023afef8a06e1f06d87fcc#diff-d613125bb3b51d54ea429c74f263c097))
13. cjk-ideographic (**missing**) (Safari 1 – in WebKit initial revision)
14. decimal (**missing**) (Safari 1 – in WebKit initial revision)
15. decimal-leading-zero (in BCD) (Safari 1 – in WebKit initial revision)
16. devanagari (**missing**) (Safari 4.1 – [WebKit commit 2010-02-07](https://github.com/WebKit/webkit/commit/4b0fa3ae40d3b022e045a7c1a256ee11de5ddd0b#diff-fb435c4214366f5ed474b2b7fbcbbcb1))
17. disc (**missing**) (Safari 1 – in WebKit initial revision)
18. ethiopic (**missing**) (Safari 4.1 – [WebKit commit 2010-01-18](https://github.com/WebKit/webkit/commit/3974e472daf8d63470023afef8a06e1f06d87fcc#diff-d613125bb3b51d54ea429c74f263c097))
19. ethiopic-abegede (**missing**) (Safari 4.1 – [WebKit commit 2010-01-18](https://github.com/WebKit/webkit/commit/3974e472daf8d63470023afef8a06e1f06d87fcc#diff-d613125bb3b51d54ea429c74f263c097))
20. ethiopic-abegede-am-et (**missing**) (Safari 4.1 – [WebKit commit 2010-01-18](https://github.com/WebKit/webkit/commit/3974e472daf8d63470023afef8a06e1f06d87fcc#diff-d613125bb3b51d54ea429c74f263c097))
21. ethiopic-abegede-gez (**missing**) (Safari 4.1 – [WebKit commit 2010-01-18](https://github.com/WebKit/webkit/commit/3974e472daf8d63470023afef8a06e1f06d87fcc#diff-d613125bb3b51d54ea429c74f263c097))
22. ethiopic-abegede-ti-er (**missing**) (Safari 4.1 – [WebKit commit 2010-01-18](https://github.com/WebKit/webkit/commit/3974e472daf8d63470023afef8a06e1f06d87fcc#diff-d613125bb3b51d54ea429c74f263c097))
23. ethiopic-abegede-ti-et (**missing**) (Safari 4.1 – [WebKit commit 2010-01-18](https://github.com/WebKit/webkit/commit/3974e472daf8d63470023afef8a06e1f06d87fcc#diff-d613125bb3b51d54ea429c74f263c097))
24. ethiopic-halehame-aa-er (**missing**) (Safari 4.1 – [WebKit commit 2010-01-18](https://github.com/WebKit/webkit/commit/3974e472daf8d63470023afef8a06e1f06d87fcc#diff-d613125bb3b51d54ea429c74f263c097))
25. ethiopic-halehame-aa-et (**missing**) (Safari 4.1 – [WebKit commit 2010-01-18](https://github.com/WebKit/webkit/commit/3974e472daf8d63470023afef8a06e1f06d87fcc#diff-d613125bb3b51d54ea429c74f263c097))
26. ethiopic-halehame-am-et (**missing**) (Safari 4.1 – [WebKit commit 2010-01-18](https://github.com/WebKit/webkit/commit/3974e472daf8d63470023afef8a06e1f06d87fcc#diff-d613125bb3b51d54ea429c74f263c097))
27. ethiopic-halehame-gez (**missing**) (Safari 4.1 – [WebKit commit 2010-01-18](https://github.com/WebKit/webkit/commit/3974e472daf8d63470023afef8a06e1f06d87fcc#diff-d613125bb3b51d54ea429c74f263c097))
28. ethiopic-halehame-om-et (**missing**) (Safari 4.1 – [WebKit commit 2010-01-18](https://github.com/WebKit/webkit/commit/3974e472daf8d63470023afef8a06e1f06d87fcc#diff-d613125bb3b51d54ea429c74f263c097))
29. ethiopic-halehame-sid-et (**missing**) (Safari 4.1 – [WebKit commit 2010-01-18](https://github.com/WebKit/webkit/commit/3974e472daf8d63470023afef8a06e1f06d87fcc#diff-d613125bb3b51d54ea429c74f263c097))
30. ethiopic-halehame-so-et (**missing**) (Safari 4.1 – [WebKit commit 2010-01-18](https://github.com/WebKit/webkit/commit/3974e472daf8d63470023afef8a06e1f06d87fcc#diff-d613125bb3b51d54ea429c74f263c097))
31. ethiopic-halehame-ti-er (**missing**) (Safari 4.1 – [WebKit commit 2010-01-18](https://github.com/WebKit/webkit/commit/3974e472daf8d63470023afef8a06e1f06d87fcc#diff-d613125bb3b51d54ea429c74f263c097))
32. ethiopic-halehame-ti-et (**missing**) (Safari 4.1 – [WebKit commit 2010-01-18](https://github.com/WebKit/webkit/commit/3974e472daf8d63470023afef8a06e1f06d87fcc#diff-d613125bb3b51d54ea429c74f263c097))
33. ethiopic-halehame-tig (**missing**) (Safari 4.1 – [WebKit commit 2010-01-18](https://github.com/WebKit/webkit/commit/3974e472daf8d63470023afef8a06e1f06d87fcc#diff-d613125bb3b51d54ea429c74f263c097))
34. footnotes (**missing**) (Safari 5.1 – [WebKit commit 2010-08-27](https://github.com/WebKit/webkit/commit/ab35e2941ceceface481ca7f1cf4e300706b9aaa#diff-d613125bb3b51d54ea429c74f263c097))
35. georgian (in BCD) (Safari 1 – in WebKit initial revision)
36. gujarati (**missing**) (Safari 4.1 – [WebKit commit 2010-02-07](https://github.com/WebKit/webkit/commit/4b0fa3ae40d3b022e045a7c1a256ee11de5ddd0b#diff-fb435c4214366f5ed474b2b7fbcbbcb1))
37. gurmukhi (**missing**) (Safari 4.1 – [WebKit commit 2010-02-07](https://github.com/WebKit/webkit/commit/4b0fa3ae40d3b022e045a7c1a256ee11de5ddd0b#diff-fb435c4214366f5ed474b2b7fbcbbcb1))
38. hangul (**missing**) (Safari 4.1 – [WebKit commit 2010-01-18](https://github.com/WebKit/webkit/commit/3974e472daf8d63470023afef8a06e1f06d87fcc#diff-d613125bb3b51d54ea429c74f263c097))
39. hangul-consonant (**missing**) (Safari 4.1 – [WebKit commit 2010-01-18](https://github.com/WebKit/webkit/commit/3974e472daf8d63470023afef8a06e1f06d87fcc#diff-d613125bb3b51d54ea429c74f263c097))
40. hebrew (**missing**) (Safari 1 – in WebKit initial revision)
41. hiragana (**missing**) (Safari 1 – in WebKit initial revision)
42. hiragana-iroha (**missing**) (Safari 1 – in WebKit initial revision)
43. kannada (**missing**) (Safari 4.1 – [WebKit commit 2010-02-07](https://github.com/WebKit/webkit/commit/4b0fa3ae40d3b022e045a7c1a256ee11de5ddd0b#diff-fb435c4214366f5ed474b2b7fbcbbcb1))
44. katakana (**missing**) (Safari 1 – in WebKit initial revision)
45. katakana-iroha (**missing**) (Safari 1 – in WebKit initial revision)
46. khmer (**missing**) (Safari 4.1 – [WebKit commit 2010-02-07](https://github.com/WebKit/webkit/commit/4b0fa3ae40d3b022e045a7c1a256ee11de5ddd0b#diff-fb435c4214366f5ed474b2b7fbcbbcb1))
47. lao (**missing**) (Safari 4.1 – [WebKit commit 2010-02-07](https://github.com/WebKit/webkit/commit/4b0fa3ae40d3b022e045a7c1a256ee11de5ddd0b#diff-fb435c4214366f5ed474b2b7fbcbbcb1))
48. lower-alpha (**missing**) (Safari 1 – in WebKit initial revision)
49. lower-armenian (**missing**) (Safari 5.1 – [WebKit commit 2010-12-04](https://github.com/WebKit/webkit/commit/690c9cb5c175c61f3d51cdd5d33de856e1ec93fd))
50. lower-greek (in BCD) (Safari 1 – in WebKit initial revision)
51. lower-hexadecimal (**missing**) (Safari 4.1 – [WebKit commit 2010-02-07](https://github.com/WebKit/webkit/commit/4b0fa3ae40d3b022e045a7c1a256ee11de5ddd0b#diff-fb435c4214366f5ed474b2b7fbcbbcb1))
52. lower-latin (in BCD) (Safari 1 – in WebKit initial revision)
53. lower-norwegian (**missing**) (Safari 4.1 – [WebKit commit 2010-01-18](https://github.com/WebKit/webkit/commit/3974e472daf8d63470023afef8a06e1f06d87fcc#diff-d613125bb3b51d54ea429c74f263c097))
54. lower-roman (**missing**) (Safari 1 – in WebKit initial revision)
55. malayalam (**missing**) (Safari 4.1 – [WebKit commit 2010-02-07](https://github.com/WebKit/webkit/commit/4b0fa3ae40d3b022e045a7c1a256ee11de5ddd0b#diff-fb435c4214366f5ed474b2b7fbcbbcb1))
56. mongolian (**missing**) (Safari 4.1 – [WebKit commit 2010-02-07](https://github.com/WebKit/webkit/commit/4b0fa3ae40d3b022e045a7c1a256ee11de5ddd0b#diff-fb435c4214366f5ed474b2b7fbcbbcb1))
57. myanmar (**missing**) (Safari 4.1 – [WebKit commit 2010-02-07](https://github.com/WebKit/webkit/commit/4b0fa3ae40d3b022e045a7c1a256ee11de5ddd0b#diff-fb435c4214366f5ed474b2b7fbcbbcb1))
58. octal (**missing**) (Safari 4.1 – [WebKit commit 2010-02-07](https://github.com/WebKit/webkit/commit/4b0fa3ae40d3b022e045a7c1a256ee11de5ddd0b#diff-fb435c4214366f5ed474b2b7fbcbbcb1))
59. oriya (**missing**) (Safari 4.1 – [WebKit commit 2010-02-07](https://github.com/WebKit/webkit/commit/4b0fa3ae40d3b022e045a7c1a256ee11de5ddd0b#diff-fb435c4214366f5ed474b2b7fbcbbcb1))
60. oromo (**missing**) (Safari 4.1 – [WebKit commit 2010-01-18](https://github.com/WebKit/webkit/commit/3974e472daf8d63470023afef8a06e1f06d87fcc#diff-d613125bb3b51d54ea429c74f263c097))
61. persian (**missing**) (Safari 4.1 – [WebKit commit 2010-02-07](https://github.com/WebKit/webkit/commit/4b0fa3ae40d3b022e045a7c1a256ee11de5ddd0b#diff-fb435c4214366f5ed474b2b7fbcbbcb1))
62. sidama (**missing**) (Safari 4.1 – [WebKit commit 2010-01-18](https://github.com/WebKit/webkit/commit/3974e472daf8d63470023afef8a06e1f06d87fcc#diff-d613125bb3b51d54ea429c74f263c097))
63. somali (**missing**) (Safari 4.1 – [WebKit commit 2010-01-18](https://github.com/WebKit/webkit/commit/3974e472daf8d63470023afef8a06e1f06d87fcc#diff-d613125bb3b51d54ea429c74f263c097))
64. square (**missing**) (Safari 1 – in WebKit initial revision)
65. telugu (**missing**) (Safari 4.1 – [WebKit commit 2010-02-07](https://github.com/WebKit/webkit/commit/4b0fa3ae40d3b022e045a7c1a256ee11de5ddd0b#diff-fb435c4214366f5ed474b2b7fbcbbcb1))
66. thai (**missing**) (Safari 4.1 – [WebKit commit 2010-02-07](https://github.com/WebKit/webkit/commit/4b0fa3ae40d3b022e045a7c1a256ee11de5ddd0b#diff-fb435c4214366f5ed474b2b7fbcbbcb1))
67. tibetan (**missing**) (Safari 4.1 – [WebKit commit 2010-02-07](https://github.com/WebKit/webkit/commit/4b0fa3ae40d3b022e045a7c1a256ee11de5ddd0b#diff-fb435c4214366f5ed474b2b7fbcbbcb1))
68. tigre (**missing**) (Safari 4.1 – [WebKit commit 2010-01-18](https://github.com/WebKit/webkit/commit/3974e472daf8d63470023afef8a06e1f06d87fcc#diff-d613125bb3b51d54ea429c74f263c097))
69. tigrinya-er (**missing**) (Safari 4.1 – [WebKit commit 2010-01-18](https://github.com/WebKit/webkit/commit/3974e472daf8d63470023afef8a06e1f06d87fcc#diff-d613125bb3b51d54ea429c74f263c097))
70. tigrinya-er-abegede (**missing**) (Safari 4.1 – [WebKit commit 2010-01-18](https://github.com/WebKit/webkit/commit/3974e472daf8d63470023afef8a06e1f06d87fcc#diff-d613125bb3b51d54ea429c74f263c097))
71. tigrinya-et (**missing**) (Safari 4.1 – [WebKit commit 2010-01-18](https://github.com/WebKit/webkit/commit/3974e472daf8d63470023afef8a06e1f06d87fcc#diff-d613125bb3b51d54ea429c74f263c097))
72. tigrinya-et-abegede (**missing**) (Safari 4.1 – [WebKit commit 2010-01-18](https://github.com/WebKit/webkit/commit/3974e472daf8d63470023afef8a06e1f06d87fcc#diff-d613125bb3b51d54ea429c74f263c097))
73. upper-alpha (**missing**) (Safari 1 – in WebKit initial revision)
74. upper-armenian (**missing**) (Safari 5.1 – [WebKit commit 2010-12-04](https://github.com/WebKit/webkit/commit/690c9cb5c175c61f3d51cdd5d33de856e1ec93fd))
75. upper-greek (**missing**) (Safari 4.1 – [WebKit commit 2010-01-18](https://github.com/WebKit/webkit/commit/3974e472daf8d63470023afef8a06e1f06d87fcc#diff-d613125bb3b51d54ea429c74f263c097))
76. upper-hexadecimal (**missing**) (Safari 4.1 – [WebKit commit 2010-02-07](https://github.com/WebKit/webkit/commit/4b0fa3ae40d3b022e045a7c1a256ee11de5ddd0b#diff-fb435c4214366f5ed474b2b7fbcbbcb1))
77. upper-latin (in BCD) (Safari 1 – in WebKit initial revision)
78. upper-norwegian (**missing**) (Safari 4.1 – [WebKit commit 2010-01-18](https://github.com/WebKit/webkit/commit/3974e472daf8d63470023afef8a06e1f06d87fcc#diff-d613125bb3b51d54ea429c74f263c097))
79. upper-roman (**missing**) (Safari 1 – in WebKit initial revision)
80. urdu (**missing**) (Safari 4.1 – [WebKit commit 2010-02-07](https://github.com/WebKit/webkit/commit/4b0fa3ae40d3b022e045a7c1a256ee11de5ddd0b#diff-fb435c4214366f5ed474b2b7fbcbbcb1))

**Comment by vinyldarkscratch** [comment]
Awesome work, @Elchi3!  :tada:  That seems to be everything for `list-style-type`, so I'll go ahead and close this issue.  :wink:

**Comment by Elchi3** [comment]
Thanks for the quick reviews, @vinyldarkscratch :+1:

**Comment by foolip** [comment]
As part of https://github.com/mdn/browser-compat-data/issues/7844 I'm double checking Chrome 45 versions, and even though https://storage.googleapis.com/chromium-find-releases-static/2b9.html#2b9f211d1b5e481a4bfb3c3e6efc81a11268541a was used (which can incorrectly point to Chrome 45) this appears correct based on the commit date, June 9, 2015, which is between the branch points for Chrome 44 and 45 in https://www.chromium.org/developers/calendar/.
