### ISSUE TITLE
Fix compatibility table for CustomEvent 

### ISSUE THREAD

**Issue by kwin** [mdn/browser-compat-data#4151]
In your table it still says that Safari and Safari Mobile are not supported (https://github.com/mdn/browser-compat-data/blob/23723e55ee3c85233d1a46d9576c7da51f1cfb88/api/CustomEvent.json#L131) but according to https://developer.apple.com/documentation/webkitjs/customevent/1629625-initcustomevent it should be supported since Safari/Safari Mobile 10+.

**Comment by vinyldarkscratch** [comment]
Testing in Safari 12.1 revealed support for the CustomEvent API, so I think this is valid.  Thanks for reporting this!  I'll have a PR opened up soon to fix this up.

**Comment by vinyldarkscratch** [comment]
After further review, it looks like `CustomEvent` was available in Safari 8.0 as well.  We'll need to do some more digging into exactly which version added support.  My best guess would have to be Safari 6 based upon WebKit versions between the note and browser data.

**Comment by vladnicula** [comment]
According to https://caniuse.com/#feat=customevent it seems that:

<img width="544" alt="Screenshot 2019-06-27 at 10 47 02" src="https://user-images.githubusercontent.com/126038/60251507-f0a90280-98c8-11e9-88df-2bfd98579515.png">

Safar 6.1 added support for them.
