### ISSUE TITLE
Require notes for partial_implementation

### ISSUE THREAD

**Issue by ddbeck** [mdn/browser-compat-data#4162]
The `partial_implementation` data alone isn't very useful. We should consider requiring the `notes` property for any support statement that has `partial_implementation: true`. I started doing [the schema work to do this](https://github.com/mdn/browser-compat-data/compare/master...ddbeck:partial_notes), but it turned out there are more such cases than I would've guessed. At the moment, such support statements appear in the following features:

- [x] `api.CSS.supports`
- [x] `api.Crypto.subtle`
- [x] `api.GeometryUtils`
- [x] `api.SubtleCrypto`
- [x] `api.VisualViewport.onresize`
- [x] `api.VisualViewport.onscroll`
- [x] `api.VisualViewport.resize_event`
- [x] `api.VisualViewport.scroll_event`
- [x] `api.WindowOrWorkerGlobalScope.indexedDB`
- [ ] `css.properties.appearance`
- [ ] `css.properties.appearance.compat`
- [x] `css.properties.filter`
- [ ] `css.properties.font-feature-settings`
- [ ] `css.properties.font-size.rem_values`
- [ ] `css.properties.text-decoration.shorthand`
- [x] `html.elements.input.input-range`
- [x] `html.elements.script.integrity`
- [x] `html.elements.source.sizes`
- [x] `html.elements.source.srcset`
- [ ] `webextensions.api.events.Event`

Note: many of these features have more than support statement with a `partial_implementation` and no note.

**Comment by Elchi3** [comment]
Thanks Daniel, I strongly support enforcing this in the schema.

> css.properties.appearance
> css.properties.appearance.compat

I just stumbled upon these two. In fact, here, we don't need a note but in my opinion we need to properly break out all values in their own rows (or objects) in the data. This might apply to other features listed in this issue as well.
