### ISSUE TITLE
IE toLocaleString timezone options

### ISSUE THREAD

**Issue by wbt** [mdn/browser-compat-data#4164]
[This line](https://github.com/mdn/browser-compat-data/blob/fd8c5be234acffe692d753c19134c6633205c7df/javascript/builtins/Date.json#L2667) reports that the `options` in [toLocaleString](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString) is implemented as of IE11.  

However, when using an IANA time zone database identifier as indicated under [Parameters](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString#Parameters), IE11 throws a `RangeError` that the `option value for 'timeZone' is outside of valid range. Expected: ['UTC']`.

**It would be helpful to know that IE does not support those time zones as options.**   

I am not sure if this should be listed as a separate property, like options.timeZone.IANAzones or similar label.  I am inclined against making a pull request to change the data directly on `options` because of the permissive implementation language (*The only value implementations must recognize is "UTC"...Implementations **may** also recognize the time zone names of the IANA time zone database, such as `Asia/Shanghai`, `Asia/Kolkata`, `America/New_York`"*).  Therefore I don't think it would be fair to say IE is out of standard.  However, it would be very helpful to know they haven't fully implemented that aspect of `options`.

Related:  [#4162 ("Require notes for partial_implementation")](https://github.com/mdn/browser-compat-data/issues/4162).

**Comment by vinyldarkscratch** [comment]
This was fixed in #4513.  Closing!
