### ISSUE TITLE
Missing compat info for rgb() aliasing rgba()

### ISSUE THREAD

**Issue by wbamberg** [mdn/browser-compat-data#4169]
Over in https://github.com/mdn/interactive-examples/pull/1348 a contributor changed the example to use `rgba()` instead of `rgb()` because they are passing an alpha component as the fourth argument.

According to https://developer.mozilla.org/en-US/docs/Web/CSS/color_value, in CSS Color Level 4 `rgb()` and `hsl()` behave the same as `rgba()` and `hsla()`. But the compat table on that page doesn't help me here.

I think it would be helpful to have a subfeature of `color` that describes support specifically for this aliasing.

I can confirm that these examples work in Firefox (68) and Chrome (74), but not in Safari (12).

**Comment by vinyldarkscratch** [comment]
I'm down for this, yeah!  Playing around, I've found that this aliasing was implemented in Chrome 65, Firefox 52, and Safari 12.1 (no support in Edge 18).  Will be writing up a PR to reflect that!
