### ISSUE TITLE
Document linter usage

### ISSUE THREAD

**Issue by ddbeck** [mdn/browser-compat-data#4179]
This is a follow up to #4024.

As a contributor, I want instructions for installing the project dependencies and running the tests, so I can submit PRs that pass CI.

Acceptance criteria:

- [ ] Update https://github.com/mdn/browser-compat-data/blob/master/docs/testing.md#validating-the-data with step-by-step instructions for the linter
- [ ] Add a brief description of what the linter and tests check
- [ ] Add links to the schema and schema docs

**Comment by queengooborg** [comment]
Fixed by https://github.com/mdn/browser-compat-data/pull/11134.
