### ISSUE TITLE
Difference between US and French version of Object.prototype.assign

### ISSUE THREAD

**Issue by masonlouchart** [mdn/browser-compat-data#4182]
In the US version the method `Object.prototype.assign` is define as not supported by `IE`. And it is not supported. But in the French version the method is described as _"supported"_ by IE and of course, it is not.

**en-US version**
<img width="1327" alt="Capture d’écran 2019-05-20 à 12 05 04" src="https://user-images.githubusercontent.com/2325091/58014138-6c5ca600-7af8-11e9-9bfc-396f6e088870.png">

**French version**
<img width="1327" alt="Capture d’écran 2019-05-20 à 12 05 48" src="https://user-images.githubusercontent.com/2325091/58014131-66ff5b80-7af8-11e9-865a-da3440abc763.png">

I don't know how to change it since there is _(I found)_ only one file to define the method compatibility and the value is [`false`](https://github.com/mdn/browser-compat-data/blob/master/javascript/builtins/Object.json#L415).

**Comment by ddbeck** [comment]
The French version of the page hadn't been regenerated to reflect the new data. I refreshed the French page and IE now matches the English page (logged in users can force-refresh the page to trigger regeneration; [see the contributing docs for a little more information](https://github.com/mdn/browser-compat-data/blob/master/docs/contributing.md#updating-compatibility-tables-on-mdn)). Thank you, @masonlouchart!
