### ISSUE TITLE
Update @page/size compatibility for Chromium

### ISSUE THREAD

**Issue by S2F0amEgS2xvdmVy** [mdn/browser-compat-data#4192]
For https://developer.mozilla.org/en-US/docs/Web/CSS/@page/size I tested the preset page sizes for Chromium, with 8/10, or 16/20 working, and I'm not sure how to class the compatibility. I've included the test page, and also some screenshots with descriptive texts.

Portrait/landscape are respected if the page size is recognised, but ignored if the page size is not recognised. JIS-B5 and JIS-B4 are both not recognised, and as a result the "More settings" for printing shows up, and the landscape is ignored and set to portrait.

Chromium Version 74.0.3729.131 (RPMFusion Build) chromium-vaapi (64-bit), but can try on Edge 76 and Chrome Dev Windows also.

Edit: works on all 3, but not when using the Microsoft print to pdf function. So perhaps it only works when using the chromium pdf saving tool.

![A4-portrait](https://user-images.githubusercontent.com/25454644/58093267-7224bb00-7bce-11e9-8355-1816204a0019.png)
![JIS-B4-landscape_(note:moreSettings)](https://user-images.githubusercontent.com/25454644/58093279-7650d880-7bce-11e9-9967-8ad65e694a81.png)
[at-page.zip](https://github.com/mdn/browser-compat-data/files/3202331/at-page.zip)

**Comment by vinyldarkscratch** [comment]
Thanks for raising this issue!  After further review, it was determined that Chrome simply doesn't have support for the CSS `@page` `size` rule (see #4368).  As such, I'm going to close this issue.

**Comment by takenspc** [comment]
@vinyldarkscratch I would be grateful if you could review this again.  Google Chrome has supported @page/size and added jis-b5 and jis-b4 support recently.

https://www.chromestatus.com/feature/5112328557166592
https://blog.chromium.org/2020/04/chrome-83-beta-cross-site-scripting.html

AFAIK, the easiest way to verify is

1. Select Print to PDF in print preview
2. Open generated PDF and check its dimension

I confirmed on Chrome Canary (86.0.4227.0) on Windows 10 (Version 1909 (Build 18363.997)).

If I missed something, please let me know.

**Comment by vinyldarkscratch** [comment]
The `@page` rule __does__ seem to be working on Chrome 84 now!  I'll go ahead and reopen this.

**Comment by Elchi3** [comment]
I've sent https://github.com/mdn/browser-compat-data/pull/7280 to fix this issue.
