### ISSUE TITLE
Cross-Origin-Opener-Policy header

### ISSUE THREAD

**Issue by connorshea** [mdn/browser-compat-data#4197]
Firefox 67 introduces the Cross-Origin-Opener-Policy header https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/67#HTTP https://bugzilla.mozilla.org/show_bug.cgi?id=1521808

**Comment by Elchi3** [comment]
This isn't true actually. See https://bugzilla.mozilla.org/show_bug.cgi?id=1521808#c20. I've removed it from the Fx67 release notes.
