### ISSUE TITLE
Add linter for duplicate features

### ISSUE THREAD

**Issue by connorshea** [mdn/browser-compat-data#4200]
For example, if someone copy-pastes an existing JSON file when tracking a new feature (which I definitely have done a lot) and then forgets to change the feature title, you could have the same feature path (e.g. `css.properties.-webkit-box-reflect`) for two separate features.

```jsonc
// In one file.
{
  "css": {
    "properties": {
      "-webkit-box-reflect": {
          // etc.
      }
    }
  }
}

// In another file.
{
  "css": {
    "properties": {
      "-webkit-box-reflect": {
          // etc.
      }
    }
  }
}
```

I don't think this would ever cause false-positives, since as far as I know you're never supposed to have duplicate feature names anyway.

I'm not sure how exactly to write a performant means of doing this, but I imagine someone smarter than me could figure it out :)

This would help detect issues like the one fixed in #4199.

**Comment by connorshea** [comment]
I'm pretty sure I suggested a fix for this at some point before, but it was about requiring that the filename and main feature name match, and that was too likely to have false positives. Hopefully this one would work better? :)

**Comment by ddbeck** [comment]
I think part of the thinking behind having the full hierarchy in every file was that we might want to split up very large APIs into multiple files (for instance, splitting subfeatures of `window` across multiple files). I don't think we actually do this anywhere, at least not yet, but it might be good to to make sure and also ask ourselves whether we ever intend to actually intend to split up large features before taking away the option.

**Comment by ddbeck** [comment]
🤦‍♂ OK, yeah, that makes sense! I misunderstood this as detecting duplication of a `css.properties.-webkit-box-reflect` in general, not `css.properties.-webkit-box-reflect.__compat` specifically.

**Comment by connorshea** [comment]
I probably could have been more clear on that point :)

**Comment by Elchi3** [comment]
This becomes a higher priority with the new mixin approach: https://github.com/mdn/browser-compat-data/issues/8929

**Comment by queengooborg** [comment]
Duplicate features across multiple files has been basically disallowed by #9821, and a better error message for it in #15479.

**Comment by queengooborg** [comment]
With the better error message in #15479, I think that this has been resolved!
