### ISSUE TITLE
Where should asm.js data be recorded

### ISSUE THREAD

**Issue by jpmedley** [mdn/browser-compat-data#4223]
I'm asking because Chrome has supported this [since version 61](https://www.chromestatus.com/feature/5053365658583040)

http://asmjs.org/spec/latest/

**Comment by Elchi3** [comment]
@chrisdavidmills Where on MDN do we document asm.js? Are there any features that would need compat data, or is it just "asm.js" supported as a whole?

**Comment by chrisdavidmills** [comment]
@Elchi3 we don't have much on asm.js; basically just this minimal article here:
https://developer.mozilla.org/en-US/docs/Games/Tools/asm.js

And an associated techniques article:
https://developer.mozilla.org/en-US/docs/Games/Techniques/Async_scripts

The first article could perhaps include a compat table.

**Comment by Elchi3** [comment]
Thanks Chris.

@jpmedley Are you planning to document compatibility of individual asm.js features, or are you interested in a single compat entry for "asm.js" as a whole?

**Comment by jpmedley** [comment]
For now, just the top level. 

I actually don't know what kind of depth it needs. Is this a can of worms I'm going to regret opening?

**Comment by Elchi3** [comment]
> Is this a can of worms I'm going to regret opening?

Yes :)

**Comment by Elchi3** [comment]
Closing this can for now. :)
