### ISSUE TITLE
Support for the x alias of dppx in resolution media queries

### ISSUE THREAD

**Issue by fvsch** [mdn/browser-compat-data#4224]
Simple test case: https://fvsch.github.io/test-pages/css-mq-resolution

For the `x` unit:
- I'm getting positive results in Firefox 69, and Chrome 74, Chrome 70, Chrome 68, Opera 55.
- Negative in Safari 12.1, Edge 18, Chrome 67, Opera 54.

**Comment by nhoizey** [comment]
The same table ( https://developer.mozilla.org/en-US/docs/Web/CSS/resolution#Browser_compatibility ) should also have compatibility information for `dpi`

**Comment by fvsch** [comment]
I think the compatibility for `dpi` is basically the first row, labelled `<resolution>`.
That's probably a bad label because it could be read as "all resolution type units are supported", when it actually means something like "the first time that a browser supported _some_ resolution unit(s)".

Maybe we should change the label to `dpi`?
Not sure about the support of `dpcm`.

**Comment by fvsch** [comment]
Moved the test case to GitHub Pages because CodePen doesn't work in IE11. :P
Support for dpcm seems old, for now I'm getting similar results as for dpi in IE, Firefox and Chrome (tested Firefox 32 and Chrome 40; lower might be possible but Firefox 8 and Chrome 20 failed on TLS support).

Running some tests via BrowserStack.

### Desktop browsers

IE9 and IE11:
- dpi: OK
- dpcm: OK
- dppx: nope
- x: nope

Firefox:
- dpi: OK
- dpcm: OK
- dppx: OK
- x: OK since 62

Chrome:
- dpi: OK
- dpcm: OK
- dppx: OK
- x: OK since 68

Safari:
- dpi: nope
- dpcm: nope
- dppx: nope
- x: nope
(No support for the unprefixed min/max-resolution queries?)

### Mobile browsers

Chrome (Android): same as desktop
Firefox (Android): same as desktop
Safari (iOS): same as desktop
Opera (Android): same as desktop
Samsung Internet (Android) 9.2: no support for `x`

**Comment by nhoizey** [comment]
> I think the compatibility for `dpi` is basically the first row, labelled `<resolution>`.

I think both should exist, there is a difference between "supports the resolution MQ" and "supports resolution expressed in dpi"

**Comment by nhoizey** [comment]
@fvsch so it looks like using `dpi` instead of `dppx` gives us support for IE, but we still need to add webkit's specific syntax… 😥

**Comment by fvsch** [comment]
> there is a difference between "supports the resolution MQ" and "supports resolution expressed in dpi"

Yeah but there's no difference in practice, and I'm not fond of having the same enormous object three times. :/

**Comment by fvsch** [comment]
So we have:

## Resolution media query

- MDN page: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/resolution
- Compat data: in `css/at-rules/media.json`

## `<resolution>` type

- MDN page: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/resolution
- Compat data: `css/types/resolution.json`

@nhoizey My take is that the resolution type page should not cover if browsers support the resolution media query itself (supported by all browsers except Safari). It should only list support for the different units.

I wasn't sure what to do with the "Safari doesn't support this, but supports -webkit-device-pixel-ratio" information, so I erred on the side of putting it on both pages.

**Comment by nhoizey** [comment]
I agree we don't need a dedicated line to know if browsers support the resolution MQ, because supporting at least one unit is a good enough indication.

**Comment by fvsch** [comment]
> we don't need a dedicated line to know if browsers support the resolution MQ

According to project members we do need one for some of the software making use of this data.

So ideally we need:

- a root support entry, which means "at least one unit is supported",
- then one entry per unit
