### ISSUE TITLE
Missing IDBFactory.databases()

### ISSUE THREAD

**Issue by Jack-Works** [mdn/browser-compat-data#4237]
https://w3c.github.io/IndexedDB/#dom-idbfactory-databases

**Comment by bershanskiy** [comment]
This should go into table comments:
Firefox issue: https://bugzilla.mozilla.org/show_bug.cgi?id=934640
Chromium (is there a more detailed bug?): https://bugs.chromium.org/p/chromium/issues/detail?id=886981
