### ISSUE TITLE
Make "intrinsic sizes" info consistent

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#4256]
Follow-up from https://github.com/mdn/browser-compat-data/pull/4242

> "Intrinsic sizes" refers to min-content, max-content, fit-content, fill-available values
> I'd love to see a PR that expands this description text to be more informative

Sometimes we used "intrinsic_sizes" in the data and sometimes we have multiple data points with the actual values min-content, max-content, fit-content, fill-available. I think we should always have the values, as entries that summarize "intrinsic sizes" would then also need a matches object, which we should avoid when possible imo.

**Comment by ddbeck** [comment]
Related to this is Chromium's non-standard `intrinsic` (alias for the standard `fit-content`) and `min-intrinsic` (alias for `min-content`). #5953 and #5962 have cleaned up the data for these, but not completely. But the other property-value pairs needs to be made consistent too:

| Property   	| intrinsic 	| min-intrinsic 	|
|------------	|-----------	|---------------	|
| width      	| ✅         	| ✅             	|
| height     	|           	|               	|
| max-height 	|           	|               	|
| min-height 	|           	|               	|
| max-width  	|           	|               	|
| min-width  	|           	|               	|

**Comment by queengooborg** [comment]
We only have one remaining instance of `intrinsic_sizes` as a combined subfeature and I've just submitted a PR to remove it.  As such, I'd say this is resolved.
