### ISSUE TITLE
Intl.DateTimeFormat not supported in Edge?

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/browser-compat-data#4263]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1553432 for original details. Looks like there is a question over whether Edge supports this.

**Comment by vinyldarkscratch** [comment]
I am able to replicate this issue in Edge 17 and below, but Edge 18 seems to fix it.  However, this is not lack of support for `Intl.DateTimeFormat`.  This is more in regards to the `"default"` value of the `locales` argument getting passed in.  From reading through MDN, `"default"` isn't mentioned as an allowed value, as it mentions `undefined` will match that behavior.

Should we add a new subfeature regarding the acceptance of `"default"` for the `locales` argument?

**Comment by vinyldarkscratch** [comment]
Looking back on this, `"default"` isn't a standard value for the locale field (the correct value is `undefined`), and since Edge fixed this in Edge 18 anyways (as well as in Chrome-based editions), I think we should simply close this issue.
