### ISSUE TITLE
Storage Event duplication 

### ISSUE THREAD

**Issue by Konrud** [mdn/browser-compat-data#4269]
There is seems to be 2 different pages (_one of which is not up to date_) that talks about the **StorageEvent**, one in the context of the [window event](https://developer.mozilla.org/en-US/docs/Web/API/Window/storage_event) and the other as a separate page for the [StorageEvent](https://developer.mozilla.org/en-US/docs/Web/API/StorageEvent) interface. Should we keep them both and then keeps the page regarding **StorageEvent** as the window event up to date or can we remove this page in favor of **StorageEvent** interface page?

**Comment by vinyldarkscratch** [comment]
This is less of a question regarding BCD and more about the MDN docs themselves.  Looking at those two pages, they should definitely remain separate, as they refer to two separate pieces: one for the `storage` event on `Window`, and the other for the `StorageEvent` class itself.
