### ISSUE TITLE
DB error in {{cssinfo}} table on `outline-offset` page

### ISSUE THREAD

**Issue by Konrud** [mdn/browser-compat-data#4281]
Page for [outline-offset](https://developer.mozilla.org/en-US/docs/Web/CSS/outline-offset) has an DB error, displayed in `{{cssinfo}}` table for `Media` property. I would be happy to fix it, but unfortunately, I don't seem to find where and how this can be done.

**Comment by vinyldarkscratch** [comment]
Based upon my research, it looks like the `{{cssinfo}}` macro pulls from https://github.com/mdn/data.  I don't know much about MDN repositories outside of this one, but I've been able to track down `outline-offset` to this particular line: https://github.com/mdn/data/blob/master/css/properties.json#L6630

I hope that this helps point you in the right direction!
