### ISSUE TITLE
`transferSize` not supported in Firefox?

### ISSUE THREAD

**Issue by jeffkaufman** [mdn/browser-compat-data#4289]
On https://developer.mozilla.org/en-US/docs/Web/API/PerformanceResourceTiming/transferSize I see Firefox as listed as not supporting `Performance​Resource​Timing​.transfer​Size`, but when I open up Firefox and run `"transferSize" in performance.getEntriesByType("resource")[0]` I see `true`.  Quick searching doesn't turn up an announcement of adding support, but this does seem to be supported now.

**Comment by ddbeck** [comment]
It looks like this was added in Firefox 45, along with a few other pieces of `Performance​Resource​Timing​`: https://bugzilla.mozilla.org/show_bug.cgi?id=1154309
