### ISSUE TITLE
Computed Property Names - Appears supported in Safari now

### ISSUE THREAD

**Issue by RyanEwen** [mdn/browser-compat-data#4307]
Computed Property Names (on the Destructuring Assignment page) appear to be supported in Safari. I am not sure which version and I do not own a Mac myself to provide any more detail. I see references of it being used in Safari for years now and had a friend run a test for me to confirm.

If anyone has more detail it would be great to update the compatibility table with it :)

**Comment by vinyldarkscratch** [comment]
Looks like this was implemented in Safari 10.  Will be writing a PR to fix this!
