### ISSUE TITLE
Define link `rel` types on appropriate elements

### ISSUE THREAD

**Issue by antross** [mdn/browser-compat-data#4308]
The [MDN page listing link types for the `rel` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types) contains a table showing allowed and disallowed elements for each possible value. Currently all values are only listed under the data for the `<link>` element in BCD.

This presents two problems:
1. Not all values are valid on `<link>` (e.g. `noopener`), but appear to be in the data
2. The data doesn't express which values are valid on `<a>`, `<area>`, and `<form>`

I figure the issue can be solved by removing unsupported values from `<link>` data and copying other values under `rel` to the data for appropriate elements (`<a>`, `<area>`, or `<form>` as appropriate). This does lead to some data duplication that could potentially get out-of-sync in the future, but also has the flexibility of representing certain values not being implemented on all possible elements in the same version of a browser.

Does this sound reasonable?

**Comment by vinyldarkscratch** [comment]
It looks like this has been resolved by #5978 and #5983!
