### ISSUE TITLE
Express which CSS value types can be used with a property

### ISSUE THREAD

**Issue by antross** [mdn/browser-compat-data#4309]
BCD currently defines support for a number of CSS types, but doesn't represent which types are supported by a given CSS property. This is typically represented in the MDN website under the "Values" heading (e.g. [Values for `border`](https://developer.mozilla.org/en-US/docs/Web/CSS/border#Values)).

I'd love to see something similar represented in BCD. We'd plan to consume this in webhint to recognize when certain value types such as the alpha hex syntax for colors should be tested for in a property like `border`. Otherwise we'd need to maintain separate side lists or use an alternate data source to determine this relationship.

**Comment by antross** [comment]
@Elchi3 Bumping this as we webhint was recently impacted by moving much of the data under the `color` property to a type (#5640). We're using a manual mapping in our code currently to mitigate. 

Rather than continuing to build out an expansive set of property->types mappings I'd love to start putting this directly in the MDN data if we can agree on a schema (most of the data is already in MDN pages, just not part of BCD). Thoughts?

E.g.
```json
{
  "css": {
    "properties": {
      "color": {
        "__compat": {
          "types": ["color"]
        }
      }
    }
  }
}
```

**Comment by Elchi3** [comment]
> @Elchi3 Bumping this as we webhint was recently impacted by moving much of the data under the color property to a type (#5640). We're using a manual mapping in our code currently to mitigate.

Sorry about that! Fortunately, we only rarely move data around.

> Rather than continuing to build out an expansive set of property->types mappings I'd love to start putting this directly in the MDN data if we can agree on a schema (most of the data is already in MDN pages, just not part of BCD). Thoughts?

Hm, I'm not sure these kinds of relationships really ought to be maintained in BCD. All we really do here is hierarchical trees with parent -> child relationships. New schema based relationships would definitely make the project more complex imho.

We have https://github.com/mdn/data that has this kind of information for CSS properties, types and syntaxes, etc., although I'm not sure how accessible it it is for you in your described case. But maybe this kind of external mapping to how the CSS feature atoms work together is what you are looking for. If BCD is then somewhat stable about where in the hierarchical trees the CSS feature atoms live, then maybe mdn/data and some additional mapping could help you, I would guess.

Sorry, but this is all I can offer for now :)

**Comment by antross** [comment]
Actually that looks perfect! I didn't realize this was available in a separate repo, thanks!
