### ISSUE TITLE
[META] Indexed Database API 3.0

### ISSUE THREAD

**Issue by bershanskiy** [mdn/browser-compat-data#4318]
Indexed Database API 3.0 draft [introduces a few novelties](https://w3c.github.io/IndexedDB/#revision-history) that are already documented in MDN and need compatibility tables:
 - `IDBFactory.databases()` method
   - [spec](https://w3c.github.io/IndexedDB/#revision-history)
   - [MDN page](https://developer.mozilla.org/en-US/docs/Web/API/IDBFactory/databases)
   - Issue: #4237 
   - PR: #4317
   - Data: See the PR

 - `IDBTransaction.commit()` method
    - [spec](https://w3c.github.io/IndexedDB/#dom-idbtransaction-commit)
    - [MDN page](https://developer.mozilla.org/en-US/docs/Web/API/IDBTransaction/commit)
    - PR: upcoming
    - Data:
       - [Chrome Platform Status](https://www.chromestatus.com/feature/5375472036741120): shipped in Chrome 76 (everywhere)
 - `IDBCursor.request` attribute
    - [spec](https://w3c.github.io/IndexedDB/#dom-idbcursor-request)
    - [MDN page](https://developer.mozilla.org/en-US/docs/Web/API/IDBCursor/request)
    - PR: upcoming
    - Data:
       - [Chrome Platform Status](https://chromestatus.com/feature/5432744081358848): implemented, but not shipped yet.
       - [Firefox issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1536540) - not implemented

**Comment by Elchi3** [comment]
This is probably done by now. Please re-open if not.
