### ISSUE TITLE
Comparing of CSS syntax 

### ISSUE THREAD

**Issue by imkremen** [mdn/browser-compat-data#4350]
I can't find an appropriate place to define compatibility of ["range context"](https://www.w3.org/TR/mediaqueries-4/#mq-range-context) and ["media condition"](https://www.w3.org/TR/mediaqueries-4/#media-conditions). Where should it be in the current CSS structure?

**Comment by vinyldarkscratch** [comment]
Since both of those links are from Media Queries Level 4, I would say that [css/at-rules/media.json](https://github.com/mdn/browser-compat-data/blob/master/css/at-rules/media.json) is the file you're looking for!
