### ISSUE TITLE
Add data about window features

### ISSUE THREAD

**Issue by a2sheppy** [mdn/browser-compat-data#4357]
We currently do not include information about the window features you fan specify when calling `window.open()`. We need to add this information.

I propose adding these a level below "open" in the `Window.json` file.

https://developer.mozilla.org/en-US/docs/Web/API/Window/open#Window_features
https://html.spec.whatwg.org/#dom-open

**Comment by Elchi3** [comment]
I think this is done now https://developer.mozilla.org/en-US/docs/Web/API/Window/open#browser_compatibility
