### ISSUE TITLE
Verify version that iOS Safari first supported touch-action: manipulation

### ISSUE THREAD

**Issue by lpd-au** [mdn/browser-compat-data#4366]
Since before BCD began, the [MDN page](https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action) has listed iOS Safari as supporting `touch-action: manipulation` since 9.1:

- [Page edit diff](https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action$compare?locale=en-US&to=1108441&from=996861)
- [Justification in edit reason](https://developer.apple.com/library/mac/releasenotes/General/WhatsNewInSafari/Articles/Safari_9_1.html)

However, these release notes are not as granular as BCD's versions of Safari; it has release notes for 9.0 and 9.1 whereas BCD has distinct versions for 9.0, 9.1, 9.2 and 9.3. [The equivalent feature on caniuse (css-touch-action)](https://caniuse.com/#feat=css-touch-action) lists support as starting from 9.3 only. Please verify whether `css.properties.touch-action` and `css.properties.touch-action.manipulation` were indeed released in 9.1 or should be changed to 9.3.

**Comment by ddbeck** [comment]
Thanks for the info, @lpd-au. This issue has been fixed and the version changed to 9.3.
