### ISSUE TITLE
document.policy vs document.featurePolicy: What do we do?

### ISSUE THREAD

**Issue by bershanskiy** [mdn/browser-compat-data#4367]
[Feature Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Feature_Policy) JS API spec elements were [renamed in December last year](https://github.com/w3c/webappsec-feature-policy/pull/262/commits/919192a1e51de519cd6422e2407a431bc4df040e). Most importantly, `document.policy` was renamed to `document.featurePolicy` and shipped under the new name in Chrome. Firefox still has the old names which are behind a flag and are obviously incompatible with Chrome's.

How should MDN and specifically this repo document this API? Should `document.policy` be marked as 

### Here is the background on this (as of writing):
 - [Spec changes](https://github.com/w3c/webappsec-feature-policy/pull/262/commits/919192a1e51de519cd6422e2407a431bc4df040e):
    - interface `Policy` renamed to `FeaturePolicy`
    - `Document` readonly attribute renamed from `policy` to `featurePolicy` (read `document.policy` renamed to `document.featurePolicy`)
       Please note that this is the breaking change for most developers, unless they specifically account for this difference.
 - [Chrome Platform status](https://www.chromestatus.com/features/5190687460950016) describes `document.policy`, not `document.featurePolicy` (even though [the APIs were renamed in January](https://bugs.chromium.org/p/chromium/issues/detail?id=917057), before enabling by default)
 - MDN:
    - https://developer.mozilla.org/en-US/docs/Web/API/Document/policy
 - this repo:
    - Contains [`api.Document.policy`](https://github.com/mdn/browser-compat-data/blob/master/api/Document.json#L8231) which was not updated yet
  - there are no W3C tests yet, as far as I know

I'll create a PR with `document.featurePolicy` that would contain info about Chrome. But what should we do with `document.policy`?

**Comment by vinyldarkscratch** [comment]
Since `featurePolicy` is the new official name, I would do as follows:

1. Rename `api.Document.policy` to `api.Document.featurePolicy`.
2. Add an `"alternative_name": "policy"` to all browsers, including Chrome.
3. Turn the BCD for Chrome into an array as follows, with XXX being whatever Chrome version shipped with the new name:

```json
"chrome": [
  {
    "version_added": "XXX"
  },
  {
    "version_added": "69",
    "version_removed": "XXX",
    "alternative_name": "policy"
  }
]
```

We should also probably open up in issue in https://github.com/mdn/sprints if one hasn't been opened already, for renaming the MDN doc and URL.

**Comment by bershanskiy** [comment]
Notes to self:

#### Pages that need updating
 - [ ] Delete https://developer.mozilla.org/en-US/docs/Web/API/Document/policy
 - [ ] Delete https://developer.mozilla.org/en-US/docs/Web/API/HTMLIFrameElement/policy

#### Data
 - [ ] Create `api.FeaturePolicy`
    - [ ] `allowsFeatureSection`
    - [ ] `featuresSection`
    - [ ] `allowedFeaturesSection`
    - [ ] `getAllowlistForFeatureSection`
 - [ ] Rename `api.Document.policy` into `api.Document.featurePolicy`
 - [ ] Rename `api.HTMLIFrameElement.policy` into `api.HTMLIFrameElement.featurePolicy`
