### ISSUE TITLE
Chrome doesn't have ontransitionend on elements

### ISSUE THREAD

**Issue by Menci** [mdn/browser-compat-data#4437]
```js
> window.ontransitionend
< null
> document.ontransitionend
< undefined
> document.body.ontransitionend
< undefined
```

Chrome: Version 75.0.3770.100 (Official Build) (64-bit)

**Comment by vinyldarkscratch** [comment]
Thanks for your report, but it looks like this is already reflected within our data.  See https://github.com/mdn/browser-compat-data/blob/a48ed965518bcb748beb57112ec7f20adcc10271/api/Window.json#L9365 for an example.
