### ISSUE TITLE
Error.stack Browser Compatibility says Edge doesn't support the property; however, it seems the property is indeed supported.

### ISSUE THREAD

**Issue by TylerBreau** [mdn/browser-compat-data#4444]
On my Windows 10, I am using...

- Microsoft Edge 44.17763.1.0
- Microsoft EdgeHTML 18.17763

[Error.Stack Browser Compatibility](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/stack#Browser_compatibility) for Edge is marked as "No Support".
I opened up the Edge dev tools, went to console and entered `new Error().stack`. The output was...
```
"Error
   at eval code (eval code:1:1)"
```

New to reporting this stuff, so I'm not sure if there's any other steps required to ensure that .stack is fully supported by Edge.

**Comment by vinyldarkscratch** [comment]
Thanks for raising this issue!  This is indeed incorrect, as anything that IE supports, Edge supports.  Thus, Edge should be `12` in this case.  I'll be submitting a PR to fix this shortly!

**Comment by vinyldarkscratch** [comment]
Thanks for raising this issue!  This is indeed incorrect, as anything that IE supports, Edge supports.  Thus, Edge should be `12` in this case.

The good news is that this is already fixed by #4249, so I'm closing this issue.
