### ISSUE TITLE
Allow "≤37" as a valid version for webview_android.

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#4479]
The discussion in https://github.com/mdn/browser-compat-data/issues/4330 has settled. 

A few tasks come out of this (this is the acceptance criteria for this ticket)

- Implement `"<=37"` as a valid version for `webview_android`. (choosing `"<=37"` now as it needs no localization)
- Document this special version and announce it in release notes.
- Investigate and report back (or open PRs) how much "true" values we could set to "<=37" (in css/ for a start and for other folders if time allows).

Other things we've decided:
- Don't hoist other old Android real values to "<=37".
- If someone has more precise data (a change from "<=37" to "4.2", for example), we still allow this.

**Comment by ddbeck** [comment]
A wild deviation here, but I figured I'd mention it before we got too far along: what do you think of using `≤` instead of `<=`?

**Comment by Elchi3** [comment]
`≤` is probably even better, yes.

**Comment by jpmedley** [comment]
> Investigate and report back (or open PRs) how much "true" values we could set to "<=37" (in css/ for a start and for other folders if time allows).

I'll take this since it's my company's product and I have the tools to discover it. What's the deadline?

**Comment by ExE-Boss** [comment]
As I said in https://github.com/mdn/browser-compat-data/pull/3881#issuecomment-510482703:
> I’d rather if the `<=` to `≤` conversion was performed either during loading or within KumaScript’s `{{Compat}}` macro, since `≤` is a pain to input.

**Comment by jpmedley** [comment]
> I’d rather if the <= to ≤ conversion was performed either during loading or within KumaScript’s {{Compat}} macro, since ≤ is a pain to input.

I was wondering about that myself.

**Comment by Elchi3** [comment]
> I'll take this since it's my company's product and I have the tools to discover it. What's the deadline?

We would like to get CSS compat data sorted in the next few weeks. 
For other compat data, there is no deadline other than the year goal as described in #3555.

**Comment by Elchi3** [comment]
> I was wondering about that myself.

Let's discuss this further in #3881

**Comment by jpmedley** [comment]
**How many true values are in the `webview_android` field of BCD?***
The effort of doing API, HTML, HTTP, and JavaScript in addition to CSS is marginal. Total numbers as of July 15, 2019 using BCD 86 are as follows:


Category | Count
-- | --
API | 2556
CSS | 257
HTML | 417
HTTP | 109
JavaScript | 432
**Total** | **3771**

Complete data is available [in this spreadsheet](https://docs.google.com/spreadsheets/d/1X9kRky0u4-rT0flqNUntH8zDqOIcIv4KzlphvfzANfQ/edit?userstoinvite=medleyj64119@gmail.com&ts=5d2cf1b3#gid=1965112432)

**Comment by Elchi3** [comment]
Thanks Joe! I don't think all of these `true` values would become  `≤37`but probably a good amount of them. Maybe we could investigate the 257 CSS values next and see which ones would clearly be `≤37`. What do you think?

**Comment by jpmedley** [comment]
I don't have strong feelings on where to start.

If those numbers seem large, consider that Chrome 37 came out 5 years ago next month. We're talking about a version that was already a mature platform. Didn't @vinyldarkscratch write a script that copies values from Chrome? The first step I'd suggest is sanity checking the data by rerunning her script and seeing what comes out.

**Comment by vinyldarkscratch** [comment]
I did, good memory!  I still have the Python* script laying around and can give it another whirl in about an hour or so.  Should the scope be confined to just CSS, or do we want to run the script for ALL WebView entries that are true or null?

_* Python’s my native coding language for those that don’t know, NodeJS is still a bit foreign to me_

**Comment by Elchi3** [comment]
> Should the scope be confined to just CSS, or do we want to run the script for ALL WebView entries that are true or null?

Our current focus is CSS, so that's where you will most likely get review. If this stuff works well however, we might want to expand it to other areas.

**Comment by jpmedley** [comment]
Running against everything at least tells us where we are, even if we don't act on that knowledge immediately.

**Comment by vinyldarkscratch** [comment]
Since #4583 is now merged, I believe that we can safely close this issue.  Please let me know if I have assumed incorrectly!
