### ISSUE TITLE
Epic: Implement "historical support"/"pre" values for old versions 

### ISSUE THREAD

**Issue by jmswisher** [mdn/browser-compat-data#4482]

**Comment by vinyldarkscratch** [comment]
Is this something in regards to the ranged values we've recently added in #4479?  If so, I think we can safely close this issue.  If not, would you be willing to provide a little more detail on this one?

**Comment by Elchi3** [comment]
We've added "≤37" as a valid version for webview_android. I think I would want to leave this open as we likely need to investigate if we need this for other browsers and versions when we move on from updating css/ to updating javascript/ and other folders.

**Comment by vinyldarkscratch** [comment]
That makes sense, yeah — one related issue would be #4610, which is my question about whether we allow Opera to ranged values as well.  Alrighty, keeping it open it is!
