### ISSUE TITLE
Epic: Make it easier for people to contribute to compat data

### ISSUE THREAD

**Issue by jmswisher** [mdn/browser-compat-data#4484]

**Comment by vinyldarkscratch** [comment]
I believe that the [CODEOWNERS](https://github.com/mdn/browser-compat-data/blob/master/.github/CODEOWNERS) file is what's of interest to us on this one -- in fact, we've already got some progress upon it.  Currently, we have the following rules:

- Irene reviews ALL webextensions-based data
- Florian reviews any non-data PRs (linters, schema changes, anything in the root folder, etc.)

**Comment by Elchi3** [comment]
Sorry this wasn't fully fleshed out so far. We need to get better at communicating these things out.

I think we reworded this epic to "Make it easier for people to contribute to compat data" and so it stands for any work we do on improving contribution to BCD and making things more efficient.

A project that contributes to this epic is a feedback mechanism we're adding to the tables on MDN. The PR for that is https://github.com/mozilla/kuma/pull/5598 It allows people to easily contribute to BCD by signalling issues with the data.

Another project is looking into probot and GitHub actions and so forth to optimize the workflows on this repo. Daniel is currently investigating this.
