### ISSUE TITLE
:host() CSS pseudo-class function

### ISSUE THREAD

**Issue by hsablonniere** [mdn/browser-compat-data#4489]
Hey ;-)

In my experience, the `:host()` CSS pseudo-class function works on Safari 12 (at least). How can I make sure of this and update the table properly?

**Comment by Elchi3** [comment]
Hey, thanks for your issue! This was actually already fixed in https://github.com/mdn/browser-compat-data/pull/4448 which I've just merged (it is actually available starting with Safari 10). The table on MDN will be updated in a few days when the weekly packaging has happened. Cheers!

**Comment by hsablonniere** [comment]
@Elchi3 Awesome ;-)
