### ISSUE TITLE
Method definitions seams to be supported on safari on mac

### ISSUE THREAD

**Issue by mhewedy** [mdn/browser-compat-data#4512]
According to  [the mdn web site](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Method_definitions#Browser_compatibility) method definitions is not supported on safari on mac. but it seems to be supported.

I've tested using:
 ```javascript
<script>
     var obj = {
         firstName: 'Mohammad',
         lastName: 'Hewedy',
         getFullname() {
             return this.firstName + ' ' + this.lastName;
         }
     };
 (function(){
     alert(obj.getFullname());
 }());
 </script>
```
And it is working on safari Version 12.0 (14606.1.36.1.9).

**Comment by vinyldarkscratch** [comment]
This has been fixed by #4452.  Closing this issue!
