### ISSUE TITLE
Keeping track of pages on MDN that need to be regenerated

### ISSUE THREAD

**Issue by teoli2003** [mdn/browser-compat-data#453]
Hi!

Currently we don't have pages on MDN automatically regenerated. That means that after a deployment we need to go back to the pages affected by the PRs included in the deployment and do this manually.

We have no easy way to track which PRs have pages that need to be regenerated. I propose to add a new label 'NeedsMDNRegen' that we add on PRs that have this need. Once the pages have been regenerated, we remove the label from the PR. That way we can be sure not to forget one.

@Elchi3 : what do you think?

**Comment by Elchi3** [comment]
I added two new labels:
- MDNPages:MacroNeeded (we still need to replace the static table with a macro call)
- MDNPages:RerenderNeeded (already migrated data changed, so force-refresh is enough)
