### ISSUE TITLE
MDN-managed compat data explorer

### ISSUE THREAD

**Issue by Malvoz** [mdn/browser-compat-data#4536]
I'd just like to express my interest in seeing an MDN-managed compat data explorer, such as https://github.com/Fyrd/caniuse or https://github.com/connorshea/mdn-compat-data-explorer. As described by @jpmedley in https://github.com/GoogleChrome/web.dev/issues/1157 these are both "the work of a single individual making it a single point of failure for all pages that reference it".

I'd imagine this is something that's been discussed before, if so what was the conclusion?

**Comment by ddbeck** [comment]
I'm going to close this issue. In some ways, this has been satisfied by partnering with Caniuse (Caniuse is now a consumer of BCD). But I also think this is in some ways out of scope for BCD itself—it represents an additional effort to build a tool around the data that BCD provides—and it's not something the team actively working on BCD has the resources for right now. Thanks!
