### ISSUE TITLE
createElementNS support in IE

### ISSUE THREAD

**Issue by targumon** [mdn/browser-compat-data#4543]
According to an old MDN page about [browser feature detection](https://developer.mozilla.org/en-US/docs/Archive/Web/Browser_feature_detection), `createElementNS` is not supported on IE6 & 7.

It seems IE8 did support it, with [some flakiness](https://code.google.com/archive/p/svgweb/issues/625).

I made a couple of PRs to BCD before but with them I could verify the info. Since this time I can't, please guide me. Thanks!

**Comment by vinyldarkscratch** [comment]
Thanks for reporting this!  I'm actually not able to get IE 8 to work with the `createElementNS` function at all, only in IE 9.  I'm wondering if, especially based upon the reported delay, it's the work of a polyfill skewing the tests mentioned in that issue.  I'm leaning towards stating that the compatibility was introduced in IE 9 as a result, does that sound reasonable?
