### ISSUE TITLE
Should MediaSession.setActionHandler have subentries for actions?

### ISSUE THREAD

**Issue by jpmedley** [mdn/browser-compat-data#4557]
Chrome is [adding `stop` in 77](https://www.chromestatus.com/feature/6140125320839168). (There's a [whole list](https://w3c.github.io/mediasession/#enumdef-mediasessionaction) in the spec.) What I'm really asking is what's the preferred way to note this in BCD?

**Comment by vinyldarkscratch** [comment]
To answer your question: yes.  If we can, we should add all the subfeatures for each action on an API.  :wink:
