### ISSUE TITLE
iOS Safari Response object data incorrect

### ISSUE THREAD

**Issue by tjcrowder** [mdn/browser-compat-data#4580]
The entries for [`Response.ok`](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok#Browser_compatibility) and [`Response.status`](https://developer.mozilla.org/en-US/docs/Web/API/Response/status#Browser_compatibility) say that Safari and iOS Safari don't support them.

iOS Safari supports them at least as of iOS v12.3.1. They're **incredibly** basic features, it seems hard to believe Safari would support `fetch` at all without them, but I don't have access to older versions to test.

Here's some ES5-level code to test it ([live copy here](http://farsightsoftware.com/temp/response.html)):
```js
"use strict";
// Avoided ES2015+ features to allow testing with old Safari versions
function log(msg) {
    var p = document.createElement("p");
    p.style.fontFamily = "monospace";
    p.appendChild(document.createTextNode(msg));
    document.body.appendChild(p);
}

function enumerableKeys(obj) {
    var rv = [];
    for (var key in obj) {
        rv.push(key);
    }
    return rv;
}

fetch("thisdoesnotexist")
.then(function(response) {
    log("reponse properties: " + enumerableKeys(response).join(", "));
    log("response.ok = " + response.ok);
    log("response.status = " + response.status);
})
.catch(function(error) {
    log("Error: " + error);
});
```
Not sure what to do. I could do a PR stating basic support in iOS Safari v12.3.1 (the only version I have handy to test), but that seems like it would be a bit too incomplete?

**Comment by dbandstra** [comment]
`response.headers` worked for me on Safari 12.1.1 for Mac.

**Comment by vinyldarkscratch** [comment]
Further research shows that both of these properties were supported since the Response API was introduced into Safari 10.1.  Will be creating a PR to reflect this now!
