### ISSUE TITLE
Chrome & Safari CSS compat data: scroll-* properties improperly propogate from `body` to viewport

### ISSUE THREAD

**Issue by mirisuzanne** [mdn/browser-compat-data#4598]
CSSWG Discussion:
- https://github.com/w3c/csswg-drafts/issues/3740

Test Case:
- Editor View: https://codepen.io/mirisuzanne/pen/yLBNpdQ?editors=1100
- Debug View: https://s.codepen.io/mirisuzanne/debug/yLBNpdQ

Chrome is supported there with a workaround, but Safari only works if you apply the properties to `body` instead of `html`. Safari also fails inside an iframe, which is why I've linked the "debug" view.

Bugs:
- Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=952711
- Webkit: https://bugs.webkit.org/show_bug.cgi?id=200643

**Comment by Elchi3** [comment]
(triaging old issues)
Looks like these browser bugs have been fixed long time ago. I'm going to close this old issue. Please feel free to reopen if we should still record incompatibilities about scroll-* properties in 2023.
