### ISSUE TITLE
Remove flags from webview_android

### ISSUE THREAD

**Issue by bershanskiy** [mdn/browser-compat-data#4609]
## Summary
As came up a few times in conversation, Android Webview does not have the ability to set flags so the `flags` attribute in the compatibility data is useless. We should remove flags from data first and then eventually remove it from the schema.

### Remove flags from `webview_android` schema
Patch `schemas/compat-data.schema.json` to remove flags. I already made a simple patch which I'll share soon.

### Remove flags from `webview_android` data
I edited the schema and this is that was logged (should probably fix before :
 - [ ] api/AuthenticationAssertion.json
 - [ ] api/Headers.json
 - [ ] api/MediaCapabilities.json
 - [ ] api/Navigator.json
 - [ ] api/OffscreenCanvas.json
 - [ ] api/PaymentCurrencyAmount.json
 - [ ] api/Response.json
 - [ ] api/ScopedCredential.json
 - [ ] api/ScopedCredentialInfo.json
 - [ ] api/VideoTrackList.json
 - [ ] api/WebAuthentication.json
 - [x] api/Window.json
 - [ ] css/properties/color.json
 - [ ] css/properties/column-gap.json
 - [ ] css/properties/font-size-adjust.json
 - [ ] css/properties/grid-column-start.json
 - [ ] css/properties/grid-column.json
 - [ ] css/properties/line-height-step.json
 - [ ] css/properties/text-align-last.json
 - [ ] css/types/image.json
 - [ ] html/elements/img.json
 - [ ] html/elements/video.json
 - [ ] html/global_attributes.json
 - [ ] http/headers/feature-policy.json

**Comment by vinyldarkscratch** [comment]
Thank you for taking the time to dig down into this one!  Yes, we should definitely remove all entries with flags in them for WebView Android.  Perhaps a linter test may also be reasonable to include, as so to reduce human error during the review process.  Thoughts?

**Comment by Elchi3** [comment]
I think this should follow the bulk change process which were are currently defining.

**Comment by bershanskiy** [comment]
FYI: I made a [commit](https://github.com/bershanskiy/browser-compat-data/commit/acbe980fc206d500015aa1e1f7630809cbff37d8) (also linked above) that fixes this. It's just a draft at this point so I haven't opened a PR.

> Perhaps a linter test may also be reasonable to include

I had changed the data schema to disallow `webview_android` to have flags so this is already covered by `test/test-schema.js`.

> I think this should follow the bulk change process which were are currently defining.

Definitely. That is tracked in #4469, right?

**Comment by vinyldarkscratch** [comment]
After a little more research, I found out that Samsung Internet doesn't have flags either.  It might be a good idea to expand the scope of this to also encompass Samsung Internet!  Thoughts?

**Comment by Elchi3** [comment]
Can you file a separate issue for that? We can then cc Samsung folks there and get it approved / done separately.

**Comment by vinyldarkscratch** [comment]
And we’re all done here, woo!
