### ISSUE TITLE
Firefox supports -webkit-mask properties

### ISSUE THREAD

**Issue by tdsmith** [mdn/browser-compat-data#4649]
Current Firefox supports the prefixed properties:

* -webkit-mask-composite
* -webkit-mask-position-x
* -webkit-mask-position-y

but the MDN pages say otherwise: e.g. https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-mask-position-x

I believe these rode to release in Firefox 53, along with the unprefixed variants.

**Comment by Elchi3** [comment]
Thanks for your issue!

-webkit-mask-composite was implemented here https://bugzilla.mozilla.org/show_bug.cgi?id=686281 and seems to have been indeed enabled in Firefox 53 in https://bugzilla.mozilla.org/show_bug.cgi?id=1251161

-webkit-mask-position-x and -webkit-mask-position-y were implemented here https://bugzilla.mozilla.org/show_bug.cgi?id=550426 and that seems to have shipped in Firefox 49 already.
