### ISSUE TITLE
Update compatibility for :is()

### ISSUE THREAD

**Issue by bksivn** [mdn/browser-compat-data#4670]
The :is() pseudo-class works in Chrome 76.0.3809.100 with enabled "Experimental Web Platform Features". The matches() pseudo-class doesn't work at all.

**Comment by vinyldarkscratch** [comment]
Thanks for your report.  I'm able to confirm that the `:is()` selector works without an alternative name like `:matches()`, with the flag specified.  I'll look into what version of Chrome this had changed in and submit a PR!
