### ISSUE TITLE
Remove Safari Desktop 4.1?

### ISSUE THREAD

**Issue by vinyldarkscratch** [mdn/browser-compat-data#4679]
From all of my research, Safari 4.1.x was released as a port of Safari 5.0.x for Mac OS X 10.4.  Both have the same WebKit versions, and the same release dates.  The only difference I can find is that Safari 5 has a few more added features like Development Tools, Bing Search, and others that we wouldn't really track here in BCD.

I'm thinking we should simply drop Safari 4.1 out of our data to reduce confusion.

**Comment by Elchi3** [comment]
Hm, yes, looking at our browser data, it seems a bit weird to have both of them. Do you have any release posts or docs that explain why there have been these two versions?
Also, how much data in bcd says 4.1 vs. how much says 5?

**Comment by vinyldarkscratch** [comment]
Running the traverse script, it looks like there are 77 entries with "4.1", and 132 with "5".  As for documentation, a [Wikipedia article on Safari](https://en.wikipedia.org/wiki/Safari_(web_browser)#Safari_5) states the following:

> Apple also released Safari 4.1 concurrently with Safari 5, exclusively for Mac OS X Tiger. The update included the majority of the features and security enhancements found in Safari 5.

An old [Cnet article](https://www.cnet.com/news/apple-releases-safari-5-0-and-safari-4-1-for-tiger/) backs this up a bit:

> The update is available for both Intel and PowerPC machines, and requires OS X 10.5.8 or later. Apple has also released Safari 4.1 for people who are still running OS X 10.4 "Tiger."

**Comment by ddbeck** [comment]
I just want to point out that this is the opposite of the recommendation in the data guidelines 🙃  https://github.com/mdn/browser-compat-data/blob/master/docs/data-guidelines.md#release-lines-and-backported-features

(Maybe this is OK, but maybe we should also delete that section from the guidelines.)

**Comment by vinyldarkscratch** [comment]
You’ve got a point @ddbeck!  It does have some weird conflicts with that guideline, since Safari 4.1 and 5.0 are basically the same browser version, just that the first is backported for older Mac OS X versions.  I think the guideline is fine, but maybe add a little note describing Safari 4.1 and 5.0?
