### ISSUE TITLE
'import' has different compatibility for workers

### ISSUE THREAD

**Issue by VirtualTim** [mdn/browser-compat-data#4687]
This is in reference to the table here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#Browser_compatibility

Basically `import` inside a worker currently only works in Chrome (+Edge beta) with "Experimental Web Platform features" enabled.
Attempting this in Firefox displays `SyntaxError: dynamic module import is not implemented`.

Perhaps it would be good to add a note about this not being supported in workers?

**Comment by vinyldarkscratch** [comment]
Thanks for researching this!  Rather than a note, we can actually represent this using a subfeature called `worker_support` as described in the [data guidelines](https://github.com/mdn/browser-compat-data/blob/master/docs/data-guidelines.md#web-workers-worker_support).
