### ISSUE TITLE
Organize test/ folder

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#4688]
The `test/` folder has grown organically. There are tests in there that form the "BCD linter" and there are now other files testing BCD scripts. We should organize ourselves a bit better there.

The linting scripts could live in a sub folder "linter" and be implemented consistently. These tests have probably quite a few things in common. Like they always have to walk the data and check it against the different rules and always spit out error messages. Can they share common functionality instead of re-implementing things?

Then there is test code that doesn't check data but rather tests for scripts we've started to add to BCD. Like traversing, stat generations, migration tests, and also the main bcd load function should be tested. I guess this stuff could be in subfolders, too, but not sure yet.

Let's draw a picture of how this could look better and then decide how to refactor this a bit. Post your proposals here before doing work! :-)

- [x] Move linting scripts to linter/ folder
- [x] Move common functionalities into utils file
- [x] Split lints and make them more readable and expandable
- [x] Test the lints

**Comment by ExE-Boss** [comment]
I think the `linter` folder would make sense.

There should probably also be the following files:
- `linter/index.js` that would export an object containing all the current `test‑*.js` functions.
- `linter/utils.js` that would contain common test functionality:
	- Function to walk BCD files (each test currently its own algorithm, each of which is slightly different, and some are more error prone than others)
	- All the functions moved in https://github.com/mdn/browser-compat-data/commit/e8e2d10d17c535a231433cd07178f69e1aa533fb.
	- The commonly implemented Logger.

**Comment by Elchi3** [comment]
Sounds good to me @ExE-Boss :+1: 

I wonder if @vinyldarkscratch and/or @ddbeck have more thoughts on this before we proceed.

**Comment by ddbeck** [comment]
That sounds reasonable to me. My only request is that, to the extent it's practical, the changes happen incrementally and successively. It can be hard to review compound changes (e.g., moving to a new folder and also refactoring at the same time can be tough to follow), so I'd prefer a series of smaller PRs rather than one big-bang cleanup.

**Comment by Elchi3** [comment]
We started to organize ourselves a bit better now but there are still issues we need to look into. If you for example refactor or improve the linting scripts like in https://github.com/mdn/browser-compat-data/pull/4686, you have to manually verify it still does lint all the cases. I think it would make sense to write tests for the linting cases. So, right now we already moved the linter into its own directory:

test/linter/

- index.js 	
- test-browsers.js
- test-links
- test-prefix.js
- test-real-values.js
- test-schema.js
- test-style.js
- test-versions.js

I think it would be good to add tests and rename the lint scripts. For example like this:

test/linter/
- index.js 	
- lint-browsers.js
- lint-browsers.test.js
- lint-links.js
- lint-links.test.js
- lint-prefixes.js
- lint-prefixes.test.js
- lint-real-values.js
- lint-real-values.test.js
- lint-style.js
- lint-style.test.js
- lint-versions.js
- lint-versions.test.js
- validate-schema.js

Instead of a large PR that does all this, we could do this lint by lint and also require it for new linters.
Opinions on that?

**Comment by queengooborg** [comment]
We've effectively achieved this (minus unittests for every linter), so I'd say this can be closed and the remainder left for adding more unittests!
