### ISSUE TITLE
Make use of mdn_url in Webextensions

### ISSUE THREAD

**Issue by teoli2003** [mdn/browser-compat-data#471]
mdn_url is very practical for reviewers, it also allows to find easily pages that needs to be regenerated.

We also use it all over the places. I think it is worth the time to add it in javascript-apis.json.

@Elchi3, @wbamberg What do you think?

**Comment by Elchi3** [comment]
Yes, we want to do this, but the WebExtension URLs are changing soon, so Will and I agreed to wait until that's done.

**Comment by teoli2003** [comment]
Makes sense to wait :-)

**Comment by Elchi3** [comment]
For WebExtension APIs, this got done in https://github.com/mdn/browser-compat-data/pull/682
Still need to get in the URLs for WebExtension manifest keys.

**Comment by Elchi3** [comment]
Manifest keys got done in https://github.com/mdn/browser-compat-data/pull/686
