### ISSUE TITLE
Add linter test for description of selected items.

### ISSUE THREAD

**Issue by jpmedley** [mdn/browser-compat-data#4725]
I'm not sure that all needed descriptions can be identified programmatically. Those that can should be included in the linter:

* Items ending in "_event".
* Constructors (items whose name exactly equals the parent).

**Comment by vinyldarkscratch** [comment]
I'm thinking that the linter would check against all features that are described in the [data guidelines](https://github.com/mdn/browser-compat-data/blob/master/docs/data-guidelines.md) documentation to ensure the proper description.  (Events are not in there yet -- I've opened #4727 to get that resolved.)  It shouldn't be too challenging to get something up and running for that!

**Comment by gsouquet** [comment]
I'd be keen to give this a go if no one else has claimed this already.
I'll be reading up on the data guidelines mentioned above and try to automate as much as I can

**Comment by vinyldarkscratch** [comment]
This was resolved by #4790, so I'll go ahead and close this issue.
