### ISSUE TITLE
Sorting of constructors (or any uppercase features)

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#4726]
I think something that was confusing to Joe in https://github.com/mdn/browser-compat-data/pull/4552 is that the sorting now sorts in constructors (which are uppercase properties) just like any other (lower-case) property. They've traditionally been put after __compat.

**Comment by Elchi3** [comment]
Need to decide if we want to go forward with sorting upper-case properties just like anything else or if they should appear first (like they have traditionally)

**Comment by Elchi3** [comment]
Unfortunately "Foo" sorts in nicely regardless of case. Change it to "Xoo" and then this test fails.
https://github.com/mdn/browser-compat-data/blob/master/test/test-compare-features.js#L19

**Comment by vinyldarkscratch** [comment]
I'm leaning towards having constructors appear first, as I believe that users will be expecting such a feature at the top.  Sorting uppercase features first would be much easier to implement, and we typically avoid uppercase values in the subfeatures.

**Comment by a2sheppy** [comment]
I feel strongly that constructors must always be at the top, however it's accomplished.

**Comment by jpmedley** [comment]
I also think constructors should be first. 

(I don't care how you implement, but I would note that for constructors name of self === name of parent.)

**Comment by vinyldarkscratch** [comment]
I've started work on this in #4730, as Migration 003!
