### ISSUE TITLE
Add data guidelines documentation about events

### ISSUE THREAD

**Issue by vinyldarkscratch** [mdn/browser-compat-data#4727]
Thinking about it some more, we should probably add some documentation to the data guidelines regarding events.  That way, we'll have our policies for events in written word!

**Comment by ddbeck** [comment]
Could you describe in more detail what you want to cover in the docs? We have some guidelines for [naming events](https://github.com/mdn/browser-compat-data/blob/master/docs/data-guidelines.md#dom-events-eventname_event). What would you like to see added?

**Comment by vinyldarkscratch** [comment]
(I swear I'm losing my mind at this point...)  Sorry, please ignore this issue -- I totally glazed over that section when initially reading through the data guidelines doc.  >~<
