### ISSUE TITLE
Samsung Internet doesn't support flags

### ISSUE THREAD

**Issue by vinyldarkscratch** [mdn/browser-compat-data#4753]
After review, it seems that Samsung Internet doesn't support flags, just like WebView.  Just like WebView in #4609, we should perform the same bulk update: remove the flags in the data, and enforce it in the schema.

**Comment by Elchi3** [comment]
Hey @torgo, can you confirm that it doesn't make sense to have feature flags for Samsung Internet? (e.g. like in Chrome "chrome://flags/#enable-experimental-web-platform-features")

**Comment by vinyldarkscratch** [comment]
This was confirmed in https://github.com/mdn/browser-compat-data/pull/5033#issuecomment-546499289 -- Samsung Internet doesn't have flags (other than a small set).
