### ISSUE TITLE
Meaning of/Remove javascript.builtins.RegExp.toString.generic_function?

### ISSUE THREAD

**Issue by vinyldarkscratch** [mdn/browser-compat-data#4759]
Going through the JavaScript built-ins, I found `javascript.builtins.RegExp.toString.generic_function`, which originated from the original MDN data.  However, as a user, I have no idea what this means from it's description.  Firefox is the only browser that has data entered as well, so I'm wondering if it's one of those Firefox-specific traits.

Can anyone answer what exactly this means?  If not, perhaps we should consider removing it?

**Comment by Elchi3** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1079919 is the background here. I think it is very minor and we can probably remove this info.
