### ISSUE TITLE
Increase quality of JavaScript compat data

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#4771]
To support the year goal, we would like to continue to improve compat data quality and get rid of `true` and `null` values. This epic issue is for the `javascript/` folder. It was prioritized next as  JavaScript (as in ECMAScript) is the most popular area on MDN and has the largest readership.

Status as of version 0.0.93 (released on 2019-09-05) for the `javascript/`directory: 

| browser | real values | ranged values | `true` values | `null` values |
| --- | --- | --- | --- | --- |
| All 8 tracked browsers | 60.20% | 0.00% | 34.13% | 5.67% |
| chrome | 55.71% | 0.00% | 39.72% | 4.57% |
| chrome android | 42.87% | 0.00% | 52.56% | 4.57% |
| edge | 67.36% | 0.00% | 25.03% | 7.62% |
| firefox | 100.00% | 0.00% | 0.00% | 0.00% |
| ie | 65.94% | 0.00% | 28.73% | 5.33% |
| safari | 51.90% | 0.00% | 39.06% | 9.03% |
| safari ios | 49.62% | 0.00% | 40.59% | 9.79% |
| webview android | 48.20% | 0.00% | 47.33% | 4.46% |

Depends on finding real values for:
- [x] Chrome (381 values) (#4947)
- [x] Edge (300 values) (#4772)
- [x] Firefox (already completed)
- [x] IE (313 values) (#4935)
- [x] Safari (436 values) (#4948)

Depends on mirroring real values for:
- [x] chrome android (#5139)
- [x] safari ios (#5483)
- [x] webview android (#5482)

**Comment by vinyldarkscratch** [comment]
I've been working on finding real values for Chrome and Safari.  I should have something to show fairly soon!  :wink:

**Comment by Elchi3** [comment]
Status as of version 0.0.95 (released on 2019-10-02) for the `javascript/` directory: 

| browser | real values | ranged values | `true` values | `null` values |
| --- | --- | --- | --- | --- |
| All 8 browsers | 64.23% | 0.03% | 32.17% | 3.58% |
| chrome | 58.54% | 0.00% | 39.72% | 1.74% |
| chrome android | 45.70% | 0.00% | 52.56% | 1.74% |
| edge | 87.05% | 0.00% | 9.47% | 3.48% |
| firefox | 100.00% | 0.00% | 0.00% | 0.00% |
| ie | 68.99% | 0.00% | 28.62% | 2.39% |
| safari | 52.56% | 0.00% | 39.06% | 8.38% |
| safari ios | 50.27% | 0.00% | 40.59% | 9.14% |
| webview android | 50.71% | 0.22% | 47.33% | 1.74% |

**Comment by Elchi3** [comment]
Status as of version 0.0.98 (released on 2019-10-24) for the javascript/ directory: 

| browser | real values | ranged values | `true` values | `null` values |
| --- | --- | --- | --- | --- |
| All 8 browsers | 71.95% | 0.58% | 25.73% | 1.74% |
| chrome | 64.21% | 0.00% | 35.25% | 0.54% |
| chrome android | 51.19% | 0.00% | 48.26% | 0.54% |
| edge | 100.00% | 0.00% | 0.00% | 0.00% |
| firefox | 100.00% | 0.00% | 0.00% | 0.00% |
| ie | 100.00% | 0.00% | 0.00% | 0.00% |
| safari | 55.53% | 0.00% | 38.72% | 5.75% |
| safari ios | 53.47% | 0.00% | 40.02% | 6.51% |
| webview android | 51.19% | 4.66% | 43.60% | 0.54% |

(Chrome is next in the sprints that starts Monday.)

**Comment by Elchi3** [comment]
Status as of version 0.0.99 (released on 2019-11-14) for the javascript/ directory: 

| browser | real values | ranged values | `true` values | `null` values |
| --- | --- | --- | --- | --- |
| All 8 browsers | 85.01% | 0.84% | 12.62% | 1.53% |
| chrome | 99.89% | 0.00% | 0.11% | 0.00% |
| chrome android | 86.77% | 0.00% | 13.23% | 0.00% |
| edge | 100.00% | 0.00% | 0.00% | 0.00% |
| firefox | 100.00% | 0.00% | 0.00% | 0.00% |
| ie | 100.00% | 0.00% | 0.00% | 0.00% |
| safari | 55.42% | 0.00% | 38.83% | 5.75% |
| safari ios | 53.36% | 0.00% | 40.13% | 6.51% |
| webview android | 84.60% | 6.72% | 8.68% | 0.00% |

Many thanks to @vinyldarkscratch for working on Chromium values! :purple_heart:
(Mirroring and/or Safari is next in the sprint that starts on Monday).

**Comment by jpmedley** [comment]
Yes. Big thank you.
Joe Medley | Technical Writer, Chrome DevRel | jmedley@google.com |
 816-678-7195
*If an API's not documented it doesn't exist.*

**Comment by Elchi3** [comment]
Status as of version 1.0.1 (released on 2019-12-04) for the javascript/ directory: 

| browser | real values | ranged values | `true` values | `null` values |
| --- | --- | --- | --- | --- |
| All 8 browsers | 87.86% | 0.84% | 10.15% | 1.15% |
| chrome | 100.00% | 0.00% | 0.00% | 0.00% |
| chrome android | 100.00% | 0.00% | 0.00% | 0.00% |
| edge | 100.00% | 0.00% | 0.00% | 0.00% |
| firefox | 100.00% | 0.00% | 0.00% | 0.00% |
| ie | 100.00% | 0.00% | 0.00% | 0.00% |
| safari | 60.32% | 0.00% | 35.46% | 4.22% |
| safari ios | 57.73% | 0.00% | 37.30% | 4.97% |
| webview android | 84.86% | 6.70% | 8.43% | 0.00% |

**Comment by Elchi3** [comment]
Status as of version 1.0.2 (released on 2019-12-12) for the javascript/ directory: 

| browser | real values | ranged values | `true` values | `null` values |
| --- | --- | --- | --- | --- |
| All 8 browsers | 89.65% | 0.84% | 8.47% | 1.04% |
| chrome | 100.00% | 0.00% | 0.00% | 0.00% |
| chrome android | 100.00% | 0.00% | 0.00% | 0.00% |
| edge | 100.00% | 0.00% | 0.00% | 0.00% |
| firefox | 100.00% | 0.00% | 0.00% | 0.00% |
| ie | 100.00% | 0.00% | 0.00% | 0.00% |
| safari | 67.46% | 0.00% | 28.76% | 3.78% |
| safari ios | 64.86% | 0.00% | 30.59% | 4.54% |
| webview android | 84.86% | 6.70% | 8.43% | 0.00% |

**Comment by Elchi3** [comment]
Happy New Year everyone! We're getting close with this one:

Status as of version 1.0.4 (released on 2020-01-09) for the javascript/ directory: 

| browser | real values | ranged values | `true` values | `null` values |
| --- | --- | --- | --- | --- |
| All 8 browsers | 94.57% | 0.85% | 4.24% | 0.34% |
| chrome | 100.00% | 0.00% | 0.00% | 0.00% |
| chrome android | 100.00% | 0.00% | 0.00% | 0.00% |
| edge | 100.00% | 0.00% | 0.00% | 0.00% |
| firefox | 100.00% | 0.00% | 0.00% | 0.00% |
| ie | 100.00% | 0.00% | 0.00% | 0.00% |
| safari | 87.89% | 0.00% | 11.03% | 1.08% |
| safari ios | 83.89% | 0.00% | 14.49% | 1.62% |
| webview android | 84.76% | 6.81% | 8.43% | 0.00% |

**Comment by vinyldarkscratch** [comment]
Whoo, we've hit that sweet 100% now!

**Comment by Elchi3** [comment]
| browser | real values | ranged values | `true` values | `null` values |
| --- | --- | --- | --- | --- |
| All 8 browsers | 98.95% | 1.05% | 0.00% | 0.00% |
| chrome | 100.00% | 0.00% | 0.00% | 0.00% |
| chrome android | 100.00% | 0.00% | 0.00% | 0.00% |
| edge | 100.00% | 0.00% | 0.00% | 0.00% |
| firefox | 100.00% | 0.00% | 0.00% | 0.00% |
| ie | 100.00% | 0.00% | 0.00% | 0.00% |
| safari | 100.00% | 0.00% | 0.00% | 0.00% |
| safari ios | 100.00% | 0.00% | 0.00% | 0.00% |
| webview android | 91.64% | 8.36% | 0.00% | 0.00% |


Yep, this is done! Not going to chase the old webview versions here. The goal is reached, but I think it makes sense to mirror data for nodejs and the Operas, so that MDN can display tables with real values everywhere. I'll review the mirroring script soon. Calling this done for now.
