### ISSUE TITLE
Edge JavaScript compat data: provide real version numbers

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#4772]
Lists of JavaScript features that have `true` or `null` for Edge.
Part of #4771. 
Total amount of features: 300

<details><summary>1) Built-ins: TypedArrays (#4775) ✅</summary>
<p>

- [x] javascript.builtins.Float32Array.constructor_without_arguments
- [x] javascript.builtins.Float32Array.iterable_in_constructor
- [x] javascript.builtins.Float64Array.constructor_without_arguments
- [x] javascript.builtins.Float64Array.iterable_in_constructor
- [x] javascript.builtins.Int16Array
- [x] javascript.builtins.Int16Array.constructor_without_arguments
- [x] javascript.builtins.Int16Array.iterable_in_constructor
- [x] javascript.builtins.Int16Array.new_required
- [x] javascript.builtins.Int32Array
- [x] javascript.builtins.Int32Array.constructor_without_arguments
- [x] javascript.builtins.Int32Array.iterable_in_constructor
- [x] javascript.builtins.Int32Array.new_required
- [x] javascript.builtins.Int8Array
- [x] javascript.builtins.Int8Array.constructor_without_arguments
- [x] javascript.builtins.Int8Array.iterable_in_constructor
- [x] javascript.builtins.Int8Array.new_required
- [x] javascript.builtins.Uint16Array
- [x] javascript.builtins.Uint16Array.constructor_without_arguments
- [x] javascript.builtins.Uint16Array.iterable_in_constructor
- [x] javascript.builtins.Uint16Array.new_required
- [x] javascript.builtins.Uint32Array
- [x] javascript.builtins.Uint32Array.constructor_without_arguments
- [x] javascript.builtins.Uint32Array.iterable_in_constructor
- [x] javascript.builtins.Uint32Array.new_required
- [x] javascript.builtins.Uint8Array
- [x] javascript.builtins.Uint8Array.constructor_without_arguments
- [x] javascript.builtins.Uint8Array.iterable_in_constructor
- [x] javascript.builtins.Uint8Array.new_required
- [x] javascript.builtins.Uint8ClampedArray
- [x] javascript.builtins.Uint8ClampedArray.constructor_without_arguments
- [x] javascript.builtins.Uint8ClampedArray.iterable_in_constructor
- [x] javascript.builtins.Uint8ClampedArray.new_required
- [x] javascript.builtins.TypedArray
- [x] javascript.builtins.TypedArray.BYTES_PER_ELEMENT
- [x] javascript.builtins.TypedArray.constructor_without_arguments
- [x] javascript.builtins.TypedArray.index_properties_not_consulting_prototype
- [x] javascript.builtins.TypedArray.iterable_in_constructor
- [x] javascript.builtins.TypedArray.name
- [x] javascript.builtins.TypedArray.named_properties
- [x] javascript.builtins.TypedArray.new_required
- [x] javascript.builtins.TypedArray.prototype
- [x] javascript.builtins.TypedArray.toLocaleString
- [x] javascript.builtins.TypedArray.toString
- [x] javascript.builtins.TypedArray.@@iterator
- [x] javascript.builtins.TypedArray.@@species

</p></details>

<details><summary>2) Built-ins: Functions (#4787) ✅</summary>
<p>

- [x] javascript.builtins.Function.apply.generic_arrays_as_arguments
- [x] javascript.builtins.Function.length.configurable_true
- [x] javascript.builtins.Function.name.configurable_true
- [x] javascript.builtins.Function.name.inferred_names
- [x] javascript.builtins.GeneratorFunction
- [x] javascript.builtins.GeneratorFunction.prototype

</p></details>

<details><summary>3) Built-ins: Intl (#4789) ✅</summary>
<p>

- [x] javascript.builtins.Array.toLocaleString.locales
- [x] javascript.builtins.Array.toLocaleString.options
- [x] javascript.builtins.Intl
- [x] javascript.builtins.Intl.Collator.caseFirst
- [x] javascript.builtins.Intl.Collator.compare
- [x] javascript.builtins.Intl.Collator.prototype
- [x] javascript.builtins.Intl.Collator.resolvedOptions
- [x] javascript.builtins.Intl.Collator.supportedLocalesOf
- [x] javascript.builtins.Intl.DateTimeFormat.hourCycle
- [x] javascript.builtins.Intl.DateTimeFormat.iana_time_zone_names
- [x] javascript.builtins.Intl.DateTimeFormat.prototype
- [x] javascript.builtins.Intl.DateTimeFormat.supportedLocalesOf
- [x] javascript.builtins.Intl.NumberFormat.format
- [x] javascript.builtins.Intl.NumberFormat.formatToParts
- [x] javascript.builtins.Intl.NumberFormat.prototype
- [x] javascript.builtins.Intl.NumberFormat.supportedLocalesOf
- [x] javascript.builtins.Intl.PluralRules.PluralRules
- [x] javascript.builtins.Intl.PluralRules.prototype
- [x] javascript.builtins.Intl.PluralRules.resolvedOptions
- [x] javascript.builtins.Intl.PluralRules.select
- [x] javascript.builtins.Intl.PluralRules.supportedLocalesOf

</p></details>

<details><summary>4) Built-ins: Math (#4774) ✅</summary>
<p>

- [x] javascript.builtins.Math.E
- [x] javascript.builtins.Math.LN2
- [x] javascript.builtins.Math.LN10
- [x] javascript.builtins.Math.LOG2E
- [x] javascript.builtins.Math.LOG10E
- [x] javascript.builtins.Math.PI
- [x] javascript.builtins.Math.SQRT1_2
- [x] javascript.builtins.Math.SQRT2
- [x] javascript.builtins.Math.atan2
- [x] javascript.builtins.Math.clz32
- [x] javascript.builtins.Math.expm1
- [x] javascript.builtins.Math.log1p
- [x] javascript.builtins.Math.log2
- [x] javascript.builtins.Math.log10

</p></details>

<details><summary>5) Built-ins: Number (#4782) ✅</summary>
<p>

- [x] javascript.builtins.Number
- [x] javascript.builtins.Number.EPSILON
- [x] javascript.builtins.Number.MAX_SAFE_INTEGER
- [x] javascript.builtins.Number.MAX_VALUE
- [x] javascript.builtins.Number.MIN_SAFE_INTEGER
- [x] javascript.builtins.Number.MIN_VALUE
- [x] javascript.builtins.Number.NEGATIVE_INFINITY
- [x] javascript.builtins.Number.POSITIVE_INFINITY
- [x] javascript.builtins.Number.prototype
- [x] javascript.builtins.Number.toLocaleString
- [x] javascript.builtins.Number.toLocaleString.locales
- [x] javascript.builtins.Number.toLocaleString.options
- [x] javascript.builtins.Number.toString
- [x] javascript.builtins.Number.valueOf

</p></details>

<details><summary>6) Built-ins: RegExp (#4883) ✅</summary>
<p>

- [x] javascript.builtins.RegExp
- [x] javascript.builtins.RegExp.flags
- [x] javascript.builtins.RegExp.global.prototype_accessor
- [x] javascript.builtins.RegExp.ignoreCase.prototype_accessor
- [x] javascript.builtins.RegExp.multiline.prototype_accessor
- [x] javascript.builtins.RegExp.n
- [x] javascript.builtins.RegExp.property_escapes
- [x] javascript.builtins.RegExp.prototype
- [x] javascript.builtins.RegExp.source.empty_regex_string
- [x] javascript.builtins.RegExp.source.escaping
- [x] javascript.builtins.RegExp.source.prototype_accessor
- [x] javascript.builtins.RegExp.sticky.anchored_sticky_flag
- [x] javascript.builtins.RegExp.sticky.prototype_accessor
- [x] javascript.builtins.RegExp.toString
- [x] javascript.builtins.RegExp.toString.escaping
- [x] javascript.builtins.RegExp.@@match
- [x] javascript.builtins.RegExp.@@replace
- [x] javascript.builtins.RegExp.@@search
- [x] javascript.builtins.RegExp.@@species
- [x] javascript.builtins.RegExp.@@split

</p></details>

<details><summary>7) Built-ins: String (#4891) ✅</summary>
<p>

- [x] javascript.builtins.String
- [x] javascript.builtins.String.localeCompare.locales
- [x] javascript.builtins.String.localeCompare.options
- [x] javascript.builtins.String.prototype
- [x] javascript.builtins.String.toLocaleLowerCase.locale
- [x] javascript.builtins.String.toLocaleUpperCase.locale
- [x] javascript.builtins.String.toString
- [x] javascript.builtins.String.trimEnd
- [x] javascript.builtins.String.trimStart
- [x] javascript.builtins.String.unicode_code_point_escapes
- [x] javascript.builtins.String.valueOf
- [x] javascript.builtins.String.@@iterator

</p></details>

<details><summary>8) Built-ins: Misc (#4894) ✅</summary>
<p>

- [x] javascript.builtins.JSON
- [x] javascript.builtins.Map.@@iterator
- [x] javascript.builtins.Object
- [x] javascript.builtins.Object.defineGetter
- [x] javascript.builtins.Object.defineSetter
- [x] javascript.builtins.Object.lookupGetter
- [x] javascript.builtins.Object.lookupSetter
- [x] javascript.builtins.Object.preventExtensions.ES2015_behavior
- [x] javascript.builtins.Object.proto
- [x] javascript.builtins.Object.prototype
- [x] javascript.builtins.Promise
- [x] javascript.builtins.Promise.Promise
- [x] javascript.builtins.Promise.prototype
- [x] javascript.builtins.Proxy.handler.isExtensible
- [x] javascript.builtins.Proxy.handler.setPrototypeOf
- [x] javascript.builtins.RangeError
- [x] javascript.builtins.ReferenceError
- [x] javascript.builtins.Set.@@iterator
- [x] javascript.builtins.Symbol.match
- [x] javascript.builtins.Symbol.replace
- [x] javascript.builtins.Symbol.search
- [x] javascript.builtins.Symbol.split
- [x] javascript.builtins.Symbol.@@toPrimitive
- [x] javascript.builtins.SyntaxError
- [x] javascript.builtins.TypeError
- [x] javascript.builtins.URIError
- [x] javascript.builtins.WeakMap.prototype
- [x] javascript.builtins.WeakSet.prototype

</p></details>

<details><summary>9) Built-ins: top-level functions (#4783) ✅</summary>
<p>

- [x] javascript.builtins.Infinity
- [x] javascript.builtins.NaN
- [x] javascript.builtins.decodeURI
- [x] javascript.builtins.decodeURIComponent
- [x] javascript.builtins.encodeURI
- [x] javascript.builtins.encodeURIComponent
- [x] javascript.builtins.escape
- [x] javascript.builtins.eval
- [x] javascript.builtins.isFinite
- [x] javascript.builtins.isNaN
- [x] javascript.builtins.null
- [x] javascript.builtins.parseFloat
- [x] javascript.builtins.parseInt
- [x] javascript.builtins.parseInt.leading_zero_strings_as_decimal
- [x] javascript.builtins.undefined
- [x] javascript.builtins.unescape

</p></details>

<details><summary>10) Functions (#4896) ✅</summary>
<p>

- [x] javascript.functions
- [x] javascript.functions.arguments
- [x] javascript.functions.arguments.callee
- [x] javascript.functions.arguments.length
- [x] javascript.functions.arguments.@@iterator
- [x] javascript.functions.arrow_functions
- [x] javascript.functions.arrow_functions.trailing_comma
- [x] javascript.functions.block_level_functions
- [x] javascript.functions.default_parameters.destructured_parameter_with_default_value_assignment
- [x] javascript.functions.get
- [x] javascript.functions.get.computed_property_names
- [x] javascript.functions.method_definitions
- [x] javascript.functions.method_definitions.async_generator_methods
- [x] javascript.functions.method_definitions.async_methods
- [x] javascript.functions.method_definitions.generator_methods_not_constructable
- [x] javascript.functions.set
- [x] javascript.functions.set.computed_property_names

</p></details>

<details><summary>11) Grammar (#4897) ✅</summary>
<p>

- [x] javascript.grammar.array_literals
- [x] javascript.grammar.boolean_literals
- [x] javascript.grammar.decimal_numeric_literals
- [x] javascript.grammar.hashbang_comments
- [x] javascript.grammar.hexadecimal_escape_sequences
- [x] javascript.grammar.hexadecimal_numeric_literals
- [x] javascript.grammar.null_literal
- [x] javascript.grammar.numeric_separators
- [x] javascript.grammar.regular_expression_literals
- [x] javascript.grammar.string_literals
- [x] javascript.grammar.unicode_escape_sequences
- [x] javascript.grammar.trailing_commas
- [x] javascript.grammar.trailing_commas.trailing_commas_in_object_literals

</p></details>

<details><summary>12) Operators (#4784) ✅</summary>
<p>

- [x] javascript.operators.arithmetic.addition
- [x] javascript.operators.arithmetic.decrement
- [x] javascript.operators.arithmetic.division
- [x] javascript.operators.arithmetic.increment
- [x] javascript.operators.arithmetic.multiplication
- [x] javascript.operators.arithmetic.remainder
- [x] javascript.operators.arithmetic.subtraction
- [x] javascript.operators.arithmetic.unary_negation
- [x] javascript.operators.arithmetic.unary_plus
- [x] javascript.operators.assignment.addition
- [x] javascript.operators.assignment.bitwise_and
- [x] javascript.operators.assignment.bitwise_or
- [x] javascript.operators.assignment.bitwise_xor
- [x] javascript.operators.assignment.division
- [x] javascript.operators.assignment.exponentiation
- [x] javascript.operators.assignment.left_shift
- [x] javascript.operators.assignment.multiplication
- [x] javascript.operators.assignment.remainder
- [x] javascript.operators.assignment.right_shift
- [x] javascript.operators.assignment.simple
- [x] javascript.operators.assignment.subtraction
- [x] javascript.operators.assignment.unsigned_right_shift
- [x] javascript.operators.await
- [x] javascript.operators.bitwise.and
- [x] javascript.operators.bitwise.left_shift
- [x] javascript.operators.bitwise.not
- [x] javascript.operators.bitwise.or
- [x] javascript.operators.bitwise.right_shift
- [x] javascript.operators.bitwise.unsigned_right_shift
- [x] javascript.operators.bitwise.xor
- [x] javascript.operators.class
- [x] javascript.operators.comma
- [x] javascript.operators.comparison.equality
- [x] javascript.operators.comparison.inequality
- [x] javascript.operators.comparison.identity
- [x] javascript.operators.comparison.non_identity
- [x] javascript.operators.comparison.greater_than
- [x] javascript.operators.comparison.greater_than_or_equal
- [x] javascript.operators.comparison.less_than
- [x] javascript.operators.comparison.less_than_or_equal
- [x] javascript.operators.conditional
- [x] javascript.operators.delete
- [x] javascript.operators.delete.temporal_dead_zone
- [x] javascript.operators.function
- [x] javascript.operators.function_star
- [x] javascript.operators.function_star.trailing_comma
- [x] javascript.operators.grouping
- [x] javascript.operators.in
- [x] javascript.operators.instanceof
- [x] javascript.operators.logical.and
- [x] javascript.operators.logical.or
- [x] javascript.operators.logical.not
- [x] javascript.operators.new
- [x] javascript.operators.new_target
- [x] javascript.operators.object_initializer
- [x] javascript.operators.object_initializer.computed_property_names
- [x] javascript.operators.object_initializer.shorthand_method_names
- [x] javascript.operators.object_initializer.shorthand_property_names
- [x] javascript.operators.property_accessors
- [x] javascript.operators.super
- [x] javascript.operators.this
- [x] javascript.operators.typeof
- [x] javascript.operators.void
- [x] javascript.operators.yield
- [x] javascript.operators.yield.IteratorResult
- [x] javascript.operators.yield_star

</p></details>

<details><summary>13) Statements (#4899) ✅</summary>
<p>

- [x] javascript.statements.async_function
- [x] javascript.statements.block
- [x] javascript.statements.break
- [x] javascript.statements.class
- [x] javascript.statements.const
- [x] javascript.statements.continue
- [x] javascript.statements.debugger
- [x] javascript.statements.default.switch
- [x] javascript.statements.do_while
- [x] javascript.statements.empty
- [x] javascript.statements.for
- [x] javascript.statements.for_in
- [x] javascript.statements.for_of.async_iterators
- [x] javascript.statements.for_of.closing_iterators
- [x] javascript.statements.function
- [x] javascript.statements.function.trailing_comma_in_parameters
- [x] javascript.statements.generator_function.not_constructable_with_new
- [x] javascript.statements.generator_function.trailing_comma_in_parameters
- [x] javascript.statements.if_else
- [x] javascript.statements.import_meta
- [x] javascript.statements.label
- [x] javascript.statements.return
- [x] javascript.statements.switch
- [x] javascript.statements.throw
- [x] javascript.statements.try_catch
- [x] javascript.statements.var
- [x] javascript.statements.while
- [x] javascript.statements.with 

</p></details> 

<hr>
If we're doing this manually and are opening one PR for each chunk, this would be 13 PRs to write and to review. If we say we need 3 hours for each PR round (some might be smaller, some bigger), the total estimation would be 39 hours (or 1 week) to complete Edge data.

**Comment by Elchi3** [comment]
So, in less than a day I was able to bake half of the Edge data updates into PRs and Vinyl reviewed them. So, probably my estimation above is nuts and JS isn't similar to CSS or I'm just hitting on easy cases. (Edge is probably the easiest of the 4 for which we need to find values).

**Comment by vinyldarkscratch** [comment]
After all the PRs have been merged (woo!), there's a couple that were missed.  They are as follows:

- [ ] javascript.builtins.Function.name.configurable_true
- [ ] javascript.builtins.Intl.PluralRules.PluralRules
- [ ] javascript.builtins.Symbol.@@toPrimitive
- [ ] javascript.functions.block_level_functions
- [ ] javascript.functions.set
