### ISSUE TITLE
Firefox 60 and higher only partly supports ES6 Modules 

### ISSUE THREAD

**Issue by kp2017** [mdn/browser-compat-data#4785]
Firefox does not support using imports in existing ES6 modules. If you try, you get an error "SyntaxError: import declarations may only appear at top level of a module".  In my test case, line 1 of my ES6 Module was "import test from '../testMod';" where test was the default export class.

**Comment by vinyldarkscratch** [comment]
Looking around, I found a [StackOverflow post](https://stackoverflow.com/questions/37624819/es2015-import-doesnt-work-even-at-top-level-in-firefox) with the same issue that you're having.  The part that would most interest you in the answer is the following: _you need to explicitly state that you're loading a module - only then the use of modules is allowed._  In other words, you must add `type="module"` to the `script` tag's attributes.

Hope this helps!
