### ISSUE TITLE
Consider renaming "safari_ios" to simply "ios"

### ISSUE THREAD

**Issue by a2sheppy** [mdn/browser-compat-data#4833]
Currently, the mobile version of Safari on iOS is represented in BCD using the keyword `safari_ios`. The problem is that we aren't actually using the Safari version number; we're using the iOS version number, instead. This is (IMO) exactly what we ought to be doing. However, because of that, the keyword name is not entirely accurate or logical.

I think we should consider renaming **`safari_ios`** to simply **`ios`**. Not only will this remove the confusion about what numbers to use (this is especially frustrating when the numbers are close but not quite the same, and you're getting test errors because the numbers aren't valid even though they are in fact a match for the Safari version number on the iOS release.

Since we're using iOS version numbers, we should call it that.

This would also let us use this field to support other browsers on iOS (Chrome, Firefox, Edge, etc). In some cases we would need a note added explaining that a feature isn't available in non-Safari WebKit views, or that kind of thing, but it would be feasible and there aren't that many features that have compatibility differences like that, really.

**Comment by ddbeck** [comment]
> This would also let us use this field to support other browsers on iOS (Chrome, Firefox, Edge, etc). In some cases we would need a note added explaining that a feature isn't available in non-Safari WebKit views, or that kind of thing, but it would be feasible and there aren't that many features that have compatibility differences like that, really.

I'm not particularly excited about this proposal. We've had very little participation from Apple/WebKit on BCD. There's already some ambiguity about how Safari for iOS versioning _really_ works (e.g., matching WebKit releases to iOS releases, iPad variants, and more). Without participants well-versed in WebKit and iOS, I just don't see the participants who are already here developing the expertise needed to make high-quality generic iOS data, on top of the existing workload. And that's putting aside the impact that changing the name and semantics of an existing browser identifier would have on BCD's current consumers.

> [Using iOS versions] is especially frustrating when the numbers are close but not quite the same, and you're getting test errors because the numbers aren't valid even though they are in fact a match for the Safari version number on the iOS release

This seems like a more tractable problem. With improvements to the linter, we might be able to provide better hints when things fail. It seems reasonable to me that if you try to use a valid desktop version number for iOS, then the linter could remind you of the possibility that you're following the wrong versioning scheme.

**Comment by Elchi3** [comment]
Closing this. I don't think this actionable right now. If the linter messages are unhelpful, please file specific issues about that.
