### ISSUE TITLE
Move worker_support to the top of the list on output

### ISSUE THREAD

**Issue by a2sheppy** [mdn/browser-compat-data#4836]
Currently, the `worker_support` entry for an API is being listed alphabetically. This looks and feels wrong. This should be special-cased to be placed at the top, just below the constructor if any. It should be granted an exception from the alphabetical sorting rule and/or should automatically get moved to the top where it belongs when building the compatibility tables.

**Comment by ExE-Boss** [comment]
Same&nbsp;probably for&nbsp;`secure_context_required`.

**Comment by shap3e** [comment]
hi
