### ISSUE TITLE
chrome 21 does not support -webkit-flex-grow and -webkit-flex-shrink

### ISSUE THREAD

**Issue by SuperPat45** [mdn/browser-compat-data#4839]
According your data, you say that -webkit-flex-grow and -webkit-flex-shrink  are supported form chrome 21 but it is not the case, In reality, it is supported from Chrome 22.

**Comment by vinyldarkscratch** [comment]
Thanks for raising an issue.  May I ask what the source of your data is?  (Manual testing is valid, but links and documentation help!)

**Comment by SuperPat45** [comment]
Manual testing with chromium portable version 21 and 22. I didn't found chrome 22 changelog.

**Comment by jpmedley** [comment]
Where did you get your devices?

**Comment by SuperPat45** [comment]
On old linux powered laptop

**Comment by jpmedley** [comment]
Please be careful with your terminology. There is no 'portable version' of Chrome. There is an Android version. Laptops run the desktop version.

**Comment by Elchi3** [comment]
Hey @SuperPat45 this is fixed now! :) 
We have the assumption that it isn't very important to get old compat data right. We assume the majority just doesn't care if it was Chrome 21 or 22 at this point. Can you share with us why this case is important to you? That might inform us better. Thank you!
