### ISSUE TITLE
How to change data for Safari Technology Preview (TP)?

### ISSUE THREAD

**Issue by Schweinepriester** [mdn/browser-compat-data#4840]
Coming from <https://webkit.org/blog/9568/release-notes-for-safari-technology-preview-92/> and <https://caniuse.com/#feat=mdn-api_rtcdatachannel_send> I wanted to do a PR for <https://developer.mozilla.org/en-US/docs/Web/API/RTCDataChannel/send#Browser_compatibility> to show support for Safari TP.

Is there a way to do that?

Changing <https://github.com/mdn/browser-compat-data/blob/master/api/RTCDataChannel.json#L1308> to `true` doesn't seem appropriate?
<https://github.com/mdn/browser-compat-data/blob/master/browsers/safari.json> does not list TP…

Apologies if this is documented somewhere and I didn't find it.

**Comment by vinyldarkscratch** [comment]
We're working on a Safari TP -> Safari Release mapping in #2991.  We do have Safari 13 beta in our browser data, however.  Since TP 92 should be introduced in Safari 13, I would say, set the Safari value to 13 in your PR.  :wink:

**Comment by Schweinepriester** [comment]
Alright, thanks!

> Since TP 92 should be introduced in Safari 13, I would say, set the Safari value to 13 in your PR. 

Via the screenshot in <https://github.com/Fyrd/caniuse/pull/5067> at the latest TP 91 switched to showing 13.1… soooo should I wait for 13.1 to be added, or how to proceed? 0:-)

**Comment by vinyldarkscratch** [comment]
Oh, huh, I guess it *would* be 13.1 then -- thanks for pointing that out!  In that case, yes, we should add 13.1 into the browser data.  😝

**Comment by Elchi3** [comment]
We're recording the Safari <-> TP mappings in https://github.com/mdn/browser-compat-data/issues/2991 but are aren't planning to support the TP browser or it's versions in BCD. We only support browsers released to end users and no nightlies, canaries or TPs.
We don't have the bandwidth.
