### ISSUE TITLE
Safari & BigInt

### ISSUE THREAD

**Issue by MartyIX** [mdn/browser-compat-data#4848]
Hi,

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt is not supported on Safari supposedly. However, https://developer.apple.com/safari/technology-preview/release-notes/ mentions BigInt in Release 57 which was released AFAIK. 

I'm not a Mac user. Maybe somebody can elaborate on what the current state of BigInt support in Safari is.

Regards,
M.

**Comment by stof** [comment]
I suspect that these release notes are generated from a commit history. They might have a partial implementation of BigInt behind some flag for now.
https://bugs.webkit.org/show_bug.cgi?id=179001 is their tracking bug for that, and it still has a bunch of unresolved dependencies.

**Comment by vinyldarkscratch** [comment]
Safari 13 doesn't support `BigInt` objects as per manual testing (and I have not found any flags that can be enabled that would enable its support, so I'm thinking it's potentially a compilation flag).  As such, I will be closing this issue.

**Comment by cvkline** [comment]
I see lots of updates to BigInt support in the Safari TP release notes, but for some reason even as of Version 101 which is the latest, they do not appear to work.

> const foo = 12n
< SyntaxError: No identifiers allowed directly after numeric literal
> BigInt
< ReferenceError: Can't find variable: BigInt
> BigInt(5)
< ReferenceError: Can't find variable: BigInt

**Comment by stof** [comment]
Well, I guess they generate the release notes based on some commit log or on closed issues, without taking into account flags which make the feature unavailable.

**Comment by sideshowbarker** [comment]
@vinyldarkscratch given https://github.com/mdn/browser-compat-data/issues/4848#issuecomment-553233354 maybe this issue should actually be closed? (Of course anyone can still comment here after it’s closed.)

**Comment by vinyldarkscratch** [comment]
Sorry, good catch!  I must have forgotten to hit “Close” before...  🤦‍♀️
