### ISSUE TITLE
Add localization to render.js

### ISSUE THREAD

**Issue by Meteor0id** [mdn/browser-compat-data#4851]
There isn't much output to localize, but there is some. Because it is only a few words, we can keep this within GitHub and don't need a whole localization project in my opinion.

Strings to localize are found in: browser-compat-data/scripts/render.js
Seems only "Yes" "No" and "Update compatibility data" require localization.
I haven't seen the string "Full support" anywhere though.

**Comment by Elchi3** [comment]
We've removed render.js in the meantime. https://github.com/mdn/browser-compat-data/pull/5032

Thanks for your issue anyway :)
