### ISSUE TITLE
-webkit-appearance shipped enabled by default in Firefox 64

### ISSUE THREAD

**Issue by digitarald** [mdn/browser-compat-data#4873]
Per Mike Taylor.

**Comment by miketaylr** [comment]
I blame @chrisdavidmills https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/64#CSS

**Comment by chrisdavidmills** [comment]
Ah, so the [appearance page](https://developer.mozilla.org/en-US/docs/Web/CSS/appearance#Browser_compatibility) is still saying supported in 62 but behind a pref, but we need to update it so that it says enabled by default in 64?

I must've clean forgot to submit the BCD ;-)
