### ISSUE TITLE
http/headers/if-none-match Non-standard, experimental and deprecated ?

### ISSUE THREAD

**Issue by ArfyFR** [mdn/browser-compat-data#4924]
Hi,
Wondering if it is really Non-standard, experimental and deprecated or if it is a typo ?

URL: https://github.com/mdn/browser-compat-data/blob/master/http/headers/if-none-match.json

**Comment by antonjuulnaber** [comment]
It seems you are correct. The header is part of the [HTTP/1.1 spec](https://tools.ietf.org/html/rfc7232#section-3.2), and it does not seem to be deprecated.

I have made a pull-request (#4959) that will fix it, but i have limited experience with web standards documentation, so I don't feel qualified to approve this change.

We need someone else to validate that this change is correct and approve the pull-request.

**Comment by Elchi3** [comment]
Fixed in https://github.com/mdn/browser-compat-data/pull/4959
