### ISSUE TITLE
VisualViewport Browser Compatibility

### ISSUE THREAD

**Issue by nitishk72** [mdn/browser-compat-data#4928]
I saw on twitter that iOS13 supports visual viewport. I don't know exactly how to update the docs that's why I creating the issue instead of sending the pull request.

Ref : https://twitter.com/jesper_vos/status/1179673256925814785
<img width="1393" alt="Screenshot 2019-10-04 at 2 05 19 PM" src="https://user-images.githubusercontent.com/15886737/66193825-0771a900-e6b1-11e9-820a-ef105e9084ab.png">

**Comment by gsouquet** [comment]
Hey @nitishk72 ,

Thank you for raising this issue, 

You can fork this repo and then update the file `api/VisualViewport.json`. You will find a good contributing guide on [here](https://github.com/mdn/browser-compat-data/blob/master/docs/contributing.md#updating-compatibility-tables-on-mdn)

Looking at the [Safari 13 release notes](https://developer.apple.com/documentation/safari_release_notes/safari_13_release_notes), it seems that there is added support for `VisualViewport` on that browser version. 

I'm wondering whether we should open a broader issue to review the compat data for everything mentioned in that release log (ping @Elchi3 ?)

**Comment by vinyldarkscratch** [comment]
This has actually already been fixed by #4850, which added the compatibility data for Safari 13 for VisualViewport.  As such, I'm closing this issue!
