### ISSUE TITLE
Include specification level in the status information for better UI grouping

### ISSUE THREAD

**Issue by lpd-au** [mdn/browser-compat-data#493]
Related to https://github.com/mdn/kumascript/issues/345, would you consider adding the specification level in which features were first defined to the status information? This could be achieved by modifying the `standard_track` property to accept non-booleans or adding an entirely new optional property to the `status` object. Doing so would help interfaces to more concisely represent repetitive machine-readable data of subfeatures. Additionally, this data could be used for ordering the subfeatures or even directly displaying their spec level.

**Comment by teoli2003** [comment]
I think the specification level is not really relevant overall. Moreover, it is a very misleading information as some features have been defined in some spec, than moved to another one, and eventually being modified.

I'm not sure to see the problem you are trying to solve: can you describe it more concretely? Even if I don't like the proposed solution, the problem may still be worth to solve :-)

**Comment by lpd-au** [comment]
The main problem I'm trying to solve is grouping items of trivially different support that ought to fall under basic support. To continue with the PointerEvent example, imagine MDN web docs has implemented some row grouping and now presents these five rows:

- Basic support (IE10 prefix)
- `pointerId`, `tiltX`, `tiltY` and `isPrimary` (IE10 supported)
- `width`, `height`, `pressure` and `pointerType` (IE10 partial)
- `tangentialPressure` and `twist` (level 2)
- `getCoalescedEvents()` (level 2 extension)

The way humans have chosen to represent this data previously on the top level page, and in my opinion the most logical way, is to further group the first three rows into one:

- Basic support (IE10 prefixed & partial)
- `tangentialPressure` and `twist` (level 2)
- `getCoalescedEvents()` (level 2 extension)

Which subfeatures are wholly vs partially implemented, of an interface that is prefixed anyway, is not very interesting at this level of overview. (I am assuming that the already grouped partially implemented subfeatures already have an aggregated note deferring to the individual subfeature pages anyway.) However, in these cases of slightly unequal support, the data repo has limited machine readable info to indicate which subfeatures are likely to be related. Trying to guess has the potential to be slow and/or buggy. Providing some info about what's considered "base"/level 1 and what's not would help resolve this.

---

The second problem to solve is the ordering of rows. Iirc the documentation offers no advice on this, but searching for duplicate issues before creating this one showed that rows are simply presented in the order they're added in the JSON, with the intention that this will reflect the order in which new subfeatures were implemented. This makes sense for new features, but when importing existing features (99% of this repo) it is just as likely that subfeatures will be added in the order that they appear on MDN web docs, which is alphabetical properties then methods. Providing the spec level in the data would allow the same sort to be guaranteed very easily rather than relying on reviewers to enforce a particular order.

And thirdly: maybe a third party site or even MDN web docs would be interested in this data. It could be possible to show a small badge, correlating to the specifications table, in each table row.

**Comment by Elchi3** [comment]
Thanks for your issue, but I'm marking this as won't fix.

The specification level is still not really relevant overall to web developers and we've also removed the "Basic support" terminology in the mean time, so that shouldn't cause so much confusion anymore.

For ordering, we agreed that strict alphabetical is what is most convenient for us.

I'm not aware of any interest in spec levels from any third party data consumer.
