### ISSUE TITLE
Missing data in the Feature Policy Browser compatibility table

### ISSUE THREAD

**Issue by ghost** [mdn/browser-compat-data#4930]
You are missing data on the following Browser compatibility see link here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy#Browser_compatibility

Basically on the same web page you have the following property: 

![image](https://user-images.githubusercontent.com/55155131/66217844-ef555600-e6bf-11e9-8915-8a08e16729bf.png)

`wake-lock` is not listed in the Browser compatibility table

**Comment by verde79** [comment]
I fancy trying this as my first contribution to a large project

**Comment by ddbeck** [comment]
@verde79 Go for it! The changes you'll want to make will probably be in this file https://github.com/mdn/browser-compat-data/blob/master/http/headers/feature-policy.json

Feel free to ask any questions, if you need help.

**Comment by verde79** [comment]
Thanks @ddbeck, is testing necessary for this or just providing links to relevant info?

**Comment by ddbeck** [comment]
@verde79 If you have an authoritative source for your updates (such as release notes, bug tracker links, or something similar), then testing is not necessary. Links in the PR description is fine. Thank you!
