### ISSUE TITLE
Edge: JavaScript - Trailing comma in functions are now supported

### ISSUE THREAD

**Issue by krisztianb** [mdn/browser-compat-data#4940]
According to this page Edge is not supporting trailing commas in functions: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas

But it does work in the recent version up to this writing.

**Comment by vinyldarkscratch** [comment]
Hey there, thanks for reporting this.  I'm happy to say that we're currently working on this in #4899!
