### ISSUE TITLE
Browser engines: add JavaScript engine to schema?

### ISSUE THREAD

**Issue by queengooborg** [mdn/browser-compat-data#4954]
After some thought regarding Chromium and NodeJS, I had an idea that we should add a new field to the browser schema: JavaScript engines.  This will allow us to perform mirroring from Chrome to NodeJS by storing each version's V8 engine.

**Comment by Elchi3** [comment]
> After some thought regarding Chromium and NodeJS, I had an idea that we should add a new field to the browser schema: JavaScript engines.

What external use cases are there for exposing this data? We already have engine data, isn't that enough?

>  This will allow us to perform mirroring from Chrome to NodeJS by storing each version's V8 engine

Given our nodejs data is almost complete, this isn't something we want to invest in right now.

**Comment by Elchi3** [comment]
Closing. This isn't something we're interested in maintaining right now.
