### ISSUE TITLE
Prefer `const` and `let` over `var` in scripts

### ISSUE THREAD

**Issue by bershanskiy** [mdn/browser-compat-data#4973]
The test and build scripts use a `var` in a few cases; also, sometimes `let` is used where `const` would work as well.

For readability purposes, I would like to use `const` and `let` wherever possible. Would you be interested in a patch if I prepared it?

**Comment by Elchi3** [comment]
I think we could review such a PR. Note that we're also looking into prettier etc. as a start to enforce some code styling. So, I wouldn't want you to create lots of PRs around further stylistic code changes as we would like to rather rely on common libraries for this task. For this particular issue, I believe we could review a PR, though. Thanks for caring about it! :+1:
