### ISSUE TITLE
Features enabled in Fennix/GeckoView before it is released

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/browser-compat-data#4983]
So, we stopped recording data for Firefox for Android past [version 68](https://github.com/mdn/browser-compat-data/blob/master/browsers/firefox_android.json#L434) because the old FxA ("Fennec") is being discontinued.

It will be replaced by the new FxA ("Fenix") at some point in the future, when the first version of it is released. At that, we will start recording data again.

One thing we will do is look at all the things that were released between Gecko 68 and \<version when new FxA comes out>, and set all those things to `version_added: "<version when new FxA comes out>"` for `firefox_android`. We'll just skip a few versions.

For most of the features, it'll be obvious — if they got in Gecko, they'll also be in GeckoView.

But there are a few items that it may not be as obvious for, and I'll like to start recording them here so that we know about them when the time comes to do the above task.

1. [x] [Enable Pointer events on GeckoView by default](https://bugzilla.mozilla.org/show_bug.cgi?id=1507495) — pointer events were enabled on desktop quite a while ago, but it has taken a while to get them into FxA, eventually it has happened in GeckoView 70.
1. [x] [Implement Web Share API](https://bugzilla.mozilla.org/show_bug.cgi?id=1402369) — this has been documented already, but will eventually land in GeckoView in Fx 72. Probably after it is released, but recording here just in case...
1. [x] [Restrict BatteryManager to chrome script](https://bugzilla.mozilla.org/show_bug.cgi?id=1441976). In this case a feature has been unexposed form the web, and we'll need to update the FxA data when Fenix is released to say it is completely unexposed as of that version.
1. [x] [Remove support for third-party vibrate](https://bugzilla.mozilla.org/show_bug.cgi?id=1591113). In this case, the latest note added to Fx just needs to be repeated on FxA.
1. [x] Also need document the change to the `GeolocationCoordinates`, `GeolocationPosition`, and `GeolocationPositionError` interfaces, when Fenix lands
1. [x] Also need to document the changes to `Notification.requestPermission()` (inside user gesture only, no longer from insde cross-origin iframes) and `PushManager.subscribe()` (inside user gesture only)
1. [x] [IDBTransaction.commit() now supported](https://bugzilla.mozilla.org/show_bug.cgi?id=1497007)
1. [x] [Ship inputmode attribute on GeckoView](https://bugzilla.mozilla.org/show_bug.cgi?id=1631681)
1. [x] [Remove window.onappinstalled event, as it was never used or shipped](https://bugzilla.mozilla.org/show_bug.cgi?id=1625384)
1. [x] [Implement IDBCursor request attribute](https://bugzilla.mozilla.org/show_bug.cgi?id=1536540)

**Comment by a2sheppy** [comment]
Starting to get requests to update BCD for Fenix fwiw.

**Comment by Elchi3** [comment]
> One thing we will do is look at all the things that were released between Gecko 68 and \<version when new FxA comes out>, and set all those things to `version_added: "<version when new FxA comes out>"` for `firefox_android`. We'll just skip a few versions.

It seems that the \<version when new FxA comes out> is 79. Caniuse already prepared a PR for this: https://github.com/Fyrd/caniuse/issues/5561

I think it is still a staged release vs an all-in release, but probably 79 is the number we should go with for Fx Android.

Generally the plan is still this: if a feature got in Gecko 68-79, they'll also be in GeckoView/Fenix/FxA 79. So, all features we have recorded for `firefox` 69-79 should now be marked as supported in `firefox_android` 79.
It also means that we'll allow 79 as a version and I assume that going forward we will see regular android engine updates again, so probably also version 80 and so forth (this needs to be confirmed with someone who knows).

**Comment by hamishwillee** [comment]
Web share API stuff in https://github.com/mdn/browser-compat-data/pull/8850

@chrisdavidmills Should "someone" go through and test these now that gecko is out? Or is there something this is still waiting on?

**Comment by chrisdavidmills** [comment]
@hamishwillee yes, they totally should.

**Comment by Elchi3** [comment]
I think this shouldn't be closed. It remains a problem that not all Firefox for Android data is updated with the 79 release.

See https://github.com/mdn/browser-compat-data/issues/4983#issuecomment-669943788 for what the plan is here.

**Comment by ddbeck** [comment]
Sorry, this is my fault. I didn't notice that #9168 had the closing text (I don't think it was intentional).

**Comment by queengooborg** [comment]
Everything that's listed up above has now been taken care of, either in existing PRs or new ones I've just created!
