### ISSUE TITLE
How can I update compatibility in such a situation?

### ISSUE THREAD

**Issue by aleen42** [mdn/browser-compat-data#4996]
Recently, I have found that `Array.prototype.splice` as mentioned in [the document](https://github.com/aleen42/PersonalWiki/issues/32#issuecomment-542499587), is not really full supported under IE8, and how can I update the compatibility in MDN?

**Comment by vinyldarkscratch** [comment]
Hey @aleen42 -- you can represent this by adding a note to the compatibility statement that describes the IE8 issues, as such:

```json
"ie": {
  "version_added": "8",
  "notes": "[Details on the IE8 issue here]"
}
```
