### ISSUE TITLE
Data for SameSite=None in Set-Cookie compat data

### ISSUE THREAD

**Issue by stof** [mdn/browser-compat-data#4997]
It would be great to have a dedicated support entry for `SameSite=None` in the Set-Cookie compat data.

My suggestion is to mark it as supported by browsers which ignore it (treating it as if not set) and for which the default behavior matches the `None` behavior. This makes sense because the behavior will be the expected one.

Safari 12 would need to be marked as unsupported there due to their bug where an unknown value for `SameSite` is treated like `Strict`. And this case is precisely the one justifying to have a dedicated entry IMO.

**Comment by jpmedley** [comment]
This is worth doing for all values. Google has proposed [a spec change](https://tools.ietf.org/html/draft-west-cookie-incrementalism-00) to make `Lax` the default. We already have [plans to implement this](https://www.chromestatus.com/features/5088147346030592) next year. Developers need to know how this works for different browsers and browser versions.
