### ISSUE TITLE
Does Safari for desktop now support File.lastModified and File.webkitRelativePath?

### ISSUE THREAD

**Issue by suzannehamilton** [mdn/browser-compat-data#4998]
These browser compatibility tables suggest that Safari for desktop doesn't support the `lastModified` and `webkitRelativePath` properties of the `File` interface.

- https://developer.mozilla.org/en-US/docs/Web/API/File#Browser_compatibility
- https://developer.mozilla.org/en-US/docs/Web/API/File/lastModified#Browser_compatibility
- https://developer.mozilla.org/en-US/docs/Web/API/File/webkitRelativePath#Browser_compatibility

I've tested the examples on those pages in a few different versions of Safari, and they do work in recent versions.

In Safari 10.1 for OS X Sierra, it looks like the properties are undefined. But they return the correct path and last modified date in Safari 11.1 (High Sierra), and Safari 12.1 and 13.0 (Mojave).

I'm raising this as an issue rather than a PR because I can't find any Safari release notes saying that these properties are officially supported. There is a [comment from 2017 in the Chromium bug tracker](https://bugs.chromium.org/p/chromium/issues/detail?id=124187#c19) saying:

> Now that Edge/Firefox/Safari have implemented support for webkitRelativePath...

but it doesn't have any details about when it started being supported.

Can anyone confirm whether these properties are now supported by Safari? Do you know of any Apple documentation about them?

**Comment by Hyumiris** [comment]
I couldn't find anything for webkitRelativePath. A quick test on my machine confirmed that it exists (Safari 13) but that's it.

However lastModified is mentioned in the [webkit js documentation](https://developer.apple.com/documentation/webkitjs/file/1777749-lastmodified). According to this it is supported since 10.0.
