### ISSUE TITLE
CSS content property is missing data for its values

### ISSUE THREAD

**Issue by jpmedley** [mdn/browser-compat-data#5012]
The CSS content property is [missing data for most of its values](https://github.com/mdn/browser-compat-data/blob/master/css/properties/content.json). The only value I'm currently able to supply is for the &lt;string> property, which [landed in Chrome in 79](https://bugs.chromium.org/p/chromium/issues/detail?id=860016).

**Comment by Elchi3** [comment]
This landed in Chromium 77 https://www.chromestatus.com/feature/4550056227110912 and was fixed in BCD in https://github.com/mdn/browser-compat-data/pull/6001
