### ISSUE TITLE
Object.assign() is highly likely supported by Android WebView

### ISSUE THREAD

**Issue by pubmikeb** [mdn/browser-compat-data#5027]
According to the `Object.assign()` browser [compatibility matrix](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Browser_compatibility), Android WebView (AWV) doesn't support this method. But AWV is based on V8 engine, which supports this API.

Perhaps, it's worth checking wherever in recent versions of AWV the support of JS features has been expanded.

**Comment by jpmedley** [comment]
`Object.assign()` is supported in WebView.

**Comment by pubmikeb** [comment]
Then it's a time to update the browser compatibility matrix.
