### ISSUE TITLE
 BiquadFilterNode constructor miss the Chrome note

### ISSUE THREAD

**Issue by teoli2003** [mdn/browser-compat-data#503]
Hi! (This time is the correct repo)

BiquadFilterNode's constructor (has a note for Chromes and Operas:
"[1] Before Chrome 59, the default values were not supported. "

I missed it during my review, hence this issue, sorry @chrisdavidmills.

**Comment by chrisdavidmills** [comment]
I've added these, and resubmitted the PR.

**Comment by teoli2003** [comment]
As I already merged the previous one, I think you need to create a new PR (from the same branch)

**Comment by chrisdavidmills** [comment]
OK, I've done so. I hope that works OK ;-)
