### ISSUE TITLE
Prior to Safari .. 13?, inputmode of numeric breaks numeric keyboards

### ISSUE THREAD

**Issue by lol768** [mdn/browser-compat-data#5085]
`<input type="text" pattern="[0-9]*">`  works fine on these devices, but `<input type="text" pattern="[0-9]*" inputmode="numeric">` breaks the numeric keyboard.

We should add a note to document that this is not implemented properly on older versions of iOS Safari.

I've worked around it myself with:

```
if (navigator.userAgent.match(/(iPod|iPhone|iPad)/)) {
    $('#field').removeAttr('inputmode');
}
```

Sample UAs:

`Mozilla/5.0 (iPhone; CPU iPhone OS 12_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Mobile/15E148 Safari/604.1`

`Mozilla/5.0 (iPod touch; CPU iPhone OS 12_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Mobile/15E148 Safari/604.1`

**Comment by lol768** [comment]
Behaviour violates the `inputmode` spec:

>  The user agent should display a virtual keyboard capable of numeric input. This keyword is useful for PIN entry.

Even if the browser does not support the `inputmode` spec, this behaviour also flies in the face of the followng recommendation dating back to HTML 2 and here taken from the HTML 4 spec:

> If a user agent encounters an attribute it does not recognize, it should ignore the entire attribute specification (i.e., the attribute and its value).

**Comment by lol768** [comment]
Test case: https://lol768.github.io/lol768/ios.html

<details>
<p><a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/2552726/68132094-03d27b80-ff16-11e9-8a27-f5537234d067.png"><img src="https://user-images.githubusercontent.com/2552726/68132094-03d27b80-ff16-11e9-8a27-f5537234d067.png" alt="534BD639-70BA-4C6B-8B84-27104DBAB1F4" style="max-width:100%;"></a><br>
<a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/2552726/68132096-046b1200-ff16-11e9-8741-3c542a9eaa88.png"><img src="https://user-images.githubusercontent.com/2552726/68132096-046b1200-ff16-11e9-8741-3c542a9eaa88.png" alt="6D9BA9C8-BFC0-4332-AB1D-614CCEA6CBEB" style="max-width:100%;"></a></p>
</details>

**Comment by queengooborg** [comment]
Sorry that it's taken so long to review this issue.  Based upon your screenshot, I"m noticing that it IS switching to a numerical input, it's just the numerical-and-symbol keyboard instead of a number pad.  I've noticed this behavior is present in iOS 12.3, but not iOS 12.1 or lower and iOS 13 or higher.

Because this behavior in iOS 12.3 and 12.4 is just a UI difference that only applies to those particular iOS versions, and it _is_ compliant with the spec and showing a numerical input, I don't think this is worthwhile to document in BCD.

**Comment by lol768** [comment]
If you're going to use that definition of "compliant with the spec" then iOS could just display the default soft keyboard to be considered compliant, which is "capable of numeric input" (if you tap to switch away from the alphabetical view), no?

IMHO the screenshot below is the only thing that should be considered compliant, but I take your point that it only impacts a small range of iOS versions. Hopefully if anyone else gets bitten by this bug, the PR will at least be surfaced by a search engine.

![image](https://user-images.githubusercontent.com/2552726/218097392-5d261a2e-bdba-49a9-aae2-33083d89eca4.png)

**Comment by queengooborg** [comment]
> If you're going to use that definition of "compliant with the spec" then iOS could just display the default soft keyboard to be considered compliant, which is "capable of numeric input" (if you tap to switch away from the alphabetical view), no?

Well...no, actually.  If the keyboard that appeared was an alphabetical keyboard, I would consider the `inputmode` feature to be unsupported.  However, iOS 12.3/12.4 is pulling up the _numeric_ keyboard layout when the user taps on the input.
