### ISSUE TITLE
Feature-Policy: vr / xr-spatial-tracking

### ISSUE THREAD

**Issue by Malvoz** [mdn/browser-compat-data#5094]
_"Development of the WebVR API has halted in favor of being replaced the [WebXR Device API](https://immersive-web.github.io/webxr/)."_
&dash; https://immersive-web.github.io/webvr/spec/1.1/

The `vr` feature ([feature-policy.json#L1641](https://github.com/mdn/browser-compat-data/blob/master/http/headers/feature-policy.json#L1641)) should be considered deprecated, will need to find potential bugs for its removal.

WebXR Device API defines the [`xr-spatial-tracking`](https://immersive-web.github.io/webxr/#feature-policy) feature instead. Need to track implementations.

**Comment by bershanskiy** [comment]
@Malvoz I prepared a PR #5193 that addresses all these issues.

**Comment by ddbeck** [comment]
Closing this up. Thank you, @Malvoz and @bershanskiy!
