### ISSUE TITLE
Feature-Policy: webauthn => publickey-credentials

### ISSUE THREAD

**Issue by Malvoz** [mdn/browser-compat-data#5095]
The `webauthn` feature ([feature-policy.json#L1689](https://github.com/mdn/browser-compat-data/blob/master/http/headers/feature-policy.json#L1689)) should be considered deprecated, as it was [renamed](https://github.com/w3c/webauthn/pull/1284) to [`publickey-credentials`](https://w3c.github.io/webauthn/#sctn-feature-policy). Need to track bugs for removal/implementation.

**Comment by bershanskiy** [comment]
@Malvoz I prepared a PR #5193 that addresses all this.

**Comment by bershanskiy** [comment]
FYI, according to the BCD, no browser ever used `webauthn` name so the PR removes it altogether.

**Comment by Malvoz** [comment]
Awesome, thanks @bershanskiy!

**Comment by Malvoz** [comment]
Closing due to merging of https://github.com/mdn/browser-compat-data/pull/5193, thanks!
