### ISSUE TITLE
javascript builtins Set, Map, WeakSet, and WeakMap have misleading info for IE11

### ISSUE THREAD

**Issue by dgoldstein0** [mdn/browser-compat-data#5108]
IE11's Set, Map, (and WeakSet/WeakMap) do not fully conform to the ES2015 spec.  As such, I believe it's dangerous to show them as fully supported in the data:

https://github.com/mdn/browser-compat-data/blob/master/javascript/builtins/Set.json
https://github.com/mdn/browser-compat-data/blob/master/javascript/builtins/Map.json

Yet Set.add and Map.set both have caveats in IE11, and some other subfeatures just aren't supported (such as construction from an iterable).  I think it would make more sense if the top level entry for Map/Set/WeakMap/WeakSet included these caveats too, to be clear the support for these in IE11 is not full.

**Comment by vinyldarkscratch** [comment]
Hey @dgoldstein0, thanks for reporting this issue.  Can you describe the caveats you mention, and provide links if possible?

**Comment by dgoldstein0** [comment]
so I believe all the caveats are already documented in your data - just not under the top level collection object Set/WeakSet/Map/WeakMap but rather as sub-features.

E.g. https://caniuse.com/#feat=mdn-javascript_builtins_set shows green on IE11, but the add subfeature shows partial support: https://caniuse.com/#feat=mdn-javascript_builtins_set_add; values and entries functions are both missing in IE11.... etc.

really the easiest place to see this is the browser compatibility chart at the bottom of https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set (my understanding is this is the same data).  My objection is that to say that the feature is green is misleading when there are subfeatures of it that have caveats or aren't implemented at all.

I suppose my expectation is that the Set builtin would show up as fully supported only in the browsers that implemented it per the original ES2015 spec (though I could also see that we could just treat "Set" as referring to whatever the latest ecmascript spec included... either way though, IE11 has never been totally compliant with any of the standard collections, as it came out before the es2015 spec was finalized).

the other collections objects (Map/WeakSet/WeakMap) have the same sorts of issues.

Does that help to clarify?

**Comment by queengooborg** [comment]
I'm closing this issue because IE data has been frozen and will be removed in the future, so we're not making any more changes to IE data.
