### ISSUE TITLE
Data for text-decoration-thickness is out of date

### ISSUE THREAD

**Issue by jensimmons** [mdn/browser-compat-data#5110]
`text-decoration-thickness` shipped in Firefox 70.

The data (as it displays on Can I Use) says that `text-decoration-thickness` is only partially supported, with two notes. 
https://caniuse.com/#feat=mdn-css_properties_text-decoration-thickness 
> 1 Uses the non-standard name: text-decoration-width
> 2 Can be enabled by setting layout.css.text-decoration-width.enabled to true

Both of these things are no longer true. The notes should simply be removed. And Firefox should get full-support green boxes, just like Safari has. Firefox 70 shipped with full support for the current spec. 

All references to `text-decoration-width` can simply be removed completely — from here and from MDN Docs. That was an earlier name that was considered as part of the CSSWG process. There are zero implementations that use `-width` at this point, and no historical reason to keep the info around. It just confuses things. 

This technology is not "experimental" either. That flag should be removed from MDN. (Which I attempted to do, but it's still showing up.)

**Comment by Elchi3** [comment]
Thanks for your report, @jensimmons!

This was updated by @chrisdavidmills end of September for the Firefox 70 release in https://github.com/mdn/browser-compat-data/pull/4825
The MDN docs actually show it green and shipping in 70 https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-thickness#Browser_compatibility, so I think caniuse hasn't updated yet.

@Fyrd How often do you update caniuse's import of the MDN compat data? Seems like this isn't there yet.

> This technology is not "experimental" either. That flag should be removed from MDN. (Which I attempted to do, but it's still showing up.)

I hope to remove the concept of "experimental" altogether, see https://github.com/mdn/browser-compat-data/issues/1528 (there seems to be consensus about getting rid of it finally).

**Comment by Fyrd** [comment]
Looks like the data's up to date but the converter's not processing the data correctly. Will work on a fix for this soon!

**Comment by Fyrd** [comment]
Got a fix in, should appear as expected now.

**Comment by Elchi3** [comment]
Thanks for the very quick fix @Fyrd! :+1: 

I'm going to close this, but conversations about "experimental" will continue in https://github.com/mdn/browser-compat-data/issues/1528.
