### ISSUE TITLE
Location.pathname and HTMLHyperlinkElementUtils.pathname show different browser compatibilities

### ISSUE THREAD

**Issue by silverAndroid** [mdn/browser-compat-data#5159]
The `pathname` row for [`Location`](https://developer.mozilla.org/en-US/docs/Web/API/Location#Browser_compatibility) shows that Opera has full support for the property but [`HTMLHyperlinkElementUtils.pathname`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLHyperlinkElementUtils/pathname) (which is where clicking on the property leads to) shows no support for the property.

I'm not quite sure which one to follow.

**Comment by wbt** [comment]
Came here to report the same issue.  What timing, @vinyldarkscratch!
