### ISSUE TITLE
Input type="time" and MIcrosoft Edge

### ISSUE THREAD

**Issue by RWAP** [mdn/browser-compat-data#5172]
It seems as though <input type="time"> is simply no longer supported on Microsoft Edge at all - if you click on the control on https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time, the page simply reloads

Reported to Microsoft in 2017, this remains unresolved, so browser compatability needs to be set to NONE

**Comment by Fixkey** [comment]
Are you sure? Sounds more like an Edge bug than incompatibility. It works fine on my system.

Microsoft Edge 44.18362.449.0
Microsoft EdgeHTML 18.18362
Windows 10 Pro build 18362

**Comment by vinyldarkscratch** [comment]
I am able to use the `time` element in Edge (EdgeHTML version, not the new Chrome version) without any issues.  The issue you are describing sounded like a bug, though I am not able to replicate it on my end.

Closing this issue, especially since it's gotten quite stale.

**Comment by RWAP** [comment]
This is not stale (reported in November last year - also reported some years ago) - still the same problem here on Edge:

Microsoft Edge 44.18362.449.0
Microsoft EdgeHTML 18.18363

Go to https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time

Left Click on the area shown highlighted with red circle.  Page reloads - without any error / or ability to select the time.

![image](https://user-images.githubusercontent.com/500350/72928812-89650b00-3d50-11ea-9d49-4f7c97aba66d.png)

Why might it work in your copy of Edge, but not mine?

I have removed any extensions from Edge, I am using the latest Windows 10, enabled popups and anything else which might be relevent in settings.

Still cannot use a simple time element control

**Comment by RWAP** [comment]
(By the way, I see you commented on 6th December 2019 - I got the notification for that comment a few seconds before the notification for your comment earlier today where you closed the issue)

**Comment by vinyldarkscratch** [comment]
I can’t really say why it would be having such issue on your end, but my best guess is you have some sort of issue with your Edge installation.  I tested this in SauceLabs as well and had no issues, so that’s the only plausible answer I really have.  I would recommend double-checking your Windows installation for any corruption (`DISM.exe /Online /Cleanup-image /Restoreheath` in an administrative command line).

**Comment by RWAP** [comment]
Hmm - that has made no difference whatsoever - I am running Windows 10 Pro x64 
Version 1909
OS Build: 18363.592

**Comment by RWAP** [comment]
Oddly - sometimes I also get an error after clicking on the time input elements:

![image](https://user-images.githubusercontent.com/500350/72963674-c3192e80-3daf-11ea-9b26-82dbc74c24e4.png)

I will test the page on my other computer which runs Windows 10 Home x64 later today.

I am also in the UK, using en_GB language - just in case that has any potential impact

**Comment by RWAP** [comment]
Tested now on 2 other machines running Windows 10 (Home and Pro) x64 - they work properly (although I noticed that the Version was 1903 instead of 1909 - OS Build was the same)

The only difference is that my main machine was upgraded from Windows 7 Pro x64 some time ago

**Comment by RWAP** [comment]
Checked today after full reboot - still an issue on my desktop PC - what I did notice is that when I click on the time element, the wheel appears for about 20 seconds before it decides to reload the page....
