### ISSUE TITLE
Make the status information mandatory

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#519]
We've mentioned in several reviews that we'd like to see the status property added (https://github.com/mdn/browser-compat-data/blob/master/compat-data-schema.md#status-information).

As WebExtensions did not use this property from the start, we made it optional in the schema. Now, however, the WebExtension data also wants to have status information (https://bugzilla.mozilla.org/show_bug.cgi?id=1408494). I think we should make the status property required after we've added it for WebExtensions to ease the reviewing work and to have this checked automatically.

**Comment by jpmedley** [comment]
I like this as a goal, but in the short term is has problems. If I'm updating one call, my PR may not pass because of content that someone else chose to leave out. This would have an impact on my time that neither me nor my bosses would be particularly happy about.

What about having the test print a warning that says in x months this will be required, please fill it out now?

**Comment by teoli2003** [comment]
That's a really good point, @jpmedley. The automatic tests are preventing us to merge a schema change that would break (and not fix in the same PR) the validity of any bcd already migrated, so there is no risk of leading to extra work at an unexpected moment.

And I 100% agree with you, having a warning would be super useful, though I don't know if this is technically feasable (possible yes, but easily…)

**Comment by Elchi3** [comment]
I did the additional work for existing data in PR #526. WebExtensions will follow. 
After that, the schema can enforce this, so the linter will complain about it and not the reviewers :)

**Comment by wbamberg** [comment]
I've been thinking about this a bit. Suppose a feature is deprecated, and it has 10 subfeatures. Do we now have to repeat `status.deprecated: true` for every subfeature? Would it even make sense to have a subfeature of a deprecated feature that wasn't itself deprecated?

Or take for example the [`downloads`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/bookmarks) API. It has 54 atomic subfeatures and is nonstandard. There doesn't seem to be any value in repeating `standard_track: false` 54 times, especially when it doesn't seem to make sense for a nonstandard thing to contain a subfeature that is itself standardised. 

It seems to me that what we really want isn't "a status field in every subfeature" but, "for every feature, an answer to the question: what's the status of this subfeature?". 

So rather than make this field mandatory for every `__compat` object, why not allow inheritance, so if a feature has no `status.standard_track`, for instance, you can look at its parent, and so on up to the top, and error if you don't find one?

**Comment by Elchi3** [comment]
I think, so far, there is no case in BCD where an entire API is non-standard and I think there are many cases in BCD where e.g. only a few methods of an interface are non-standard, or experimental and not the interface itself or all methods/properties. Thanks for bringing up yet a new data nuance. 

However, I can think of a comparative case: there have been entire APIs marked as experimental. So far we've marked every subfeature of these APIs as `experimental: true` as well. You could argue the same there, why did you mark it as experimental when the entire API is experimental already?

"Experimental" adds the experimental icon to every subfeature in the table and in the future it might control whether or not an experimental banner is shown also at the top of [subpages](https://developer.mozilla.org/en-US/docs/Web/API/VRDisplay/cancelAnimationFrame). So sub-features have their own pages often, and also want to answer the question "am I non-standard or not". So I guess that's why they also appear everywhere as experimental: true in the data.

And currently the logic is very simple, because we are providing the status block everywhere. Otherwise we are requiring the data consumer to fill in the non-existing data with logic.

Current practice: 
- Main feature is standard, some sub-features are non-standard, but we have a status block everywhere anyway, so everything is clear. Every (sub) feature knows its own status, so wherever we display it, we just have to query the (sub) feature itself to know its status.

Current logic (due to having status optional, I was hoping to get rid of this logic and let just data speak):
- if there is no a status block, assume standard, non-experimental, non-deprecated

Proposed extended logic (while keeping the current logic):
-  If a main feature is non-standard and no sub-feature has status block, all sub-features are also non-standard. So, if there is no status block, walk up the tree, and if you find something take that status block, otherwise also assume standard, non-experimental, non-deprecated.

I'm quite convinced that we would eliminate the current logic (and not introduce more :grin: ), make the status required, strictly validate that here on BCD, and have no further implementation needs for MDN or anyone else. I think it possible to implement this logic, though.

I would love to hear what other data consumers think and would want. Is the additional logic to walk up the tree just fine? Or is it better if every (sub)feature knows its status atomically on its own?

**Comment by connorshea** [comment]
2157-ish features are missing status info right now :(

Would it be possible to make the linter only fail on non-WebExtensions features that are missing status info? It looks like there are about 80 of those in the data set right now, the other 2000+ are WebExtensions data.

**Comment by connorshea** [comment]
Here are all the files without status info, outside of the WebExtensions data:
- api/CanvasRenderingContext2D.json - 15 error(s)
- api/Comment.json - 1 error(s)
- api/Console.json - 6 error(s)
- api/DOMTokenList.json - 1 error(s)
- api/FetchEvent.json - 1 error(s)
- api/HTMLCanvasElement.json - 6 error(s)
- api/Headers.json - 1 error(s)
- api/IDBCursor.json - 2 error(s)
- api/IDBCursorWithValue.json - 1 error(s)
- api/IDBDatabase.json - 1 error(s)
- api/IDBEnvironment.json - 1 error(s)
- api/IDBFactory.json - 1 error(s)
- api/IDBIndex.json - 2 error(s)
- api/IDBKeyRange.json - 1 error(s)
- api/IDBObjectStore.json - 2 error(s)
- api/IDBOpenDBRequest.json - 1 error(s)
- api/IDBRequest.json - 2 error(s)
- api/IDBTransaction.json - 2 error(s)
- api/IDBVersionChangeEvent.json - 1 error(s)
- api/ImageData.json - 1 error(s)
- api/NavigatorConcurrentHardware.json - 1 error(s)
- api/NavigatorLanguage.json - 1 error(s)
- api/NavigatorOnLine.json - 1 error(s)
- api/OffscreenCanvas.json - 4 error(s)
- api/Request.json - 7 error(s)
- api/Response.json - 2 error(s)
- api/SharedWorker.json - 1 error(s)
- api/SpeechRecognition.json - 1 error(s)
- api/TextMetrics.json - 1 error(s)
- api/WindowEventHandlers.json - 2 error(s)
- api/WindowOrWorkerGlobalScope.json - 11 error(s)
- api/Worker.json - 1 error(s)
- api/WorkerGlobalScope.json - 1 error(s)
- api/XMLHttpRequest.json - 1 error(s)
- css/properties/overflow.json - 1 error(s)

**Comment by connorshea** [comment]
I opened #2382 to require the status block in all data except those in `webextensions/`

**Comment by connorshea** [comment]
#2382 has been merged so this is now enforced by the linter 👍 WebExtensions data is currently excluded, though it’d be nice if someone could go through and add status info to all the WebExtensions data so we can make it mandatory there too :)

**Comment by vinyldarkscratch** [comment]
Posting this here as I plan to tackle these:

- [ ] webextensions/match_patterns.json – 11 error(s)

**webextensions/api**
- [ ] webextensions/api/alarms.json – 7 error(s)
- [ ] webextensions/api/bookmarks.json – 24 error(s)
- [ ] webextensions/api/browserAction.json – 35 error(s)
- [ ] webextensions/api/browserSettings.json – 14 error(s)
- [ ] webextensions/api/browsingData.json – 28 error(s)
- [ ] webextensions/api/clipboard.json – 1 error(s)
- [ ] webextensions/api/commands.json – 5 error(s)
- [ ] webextensions/api/contentScripts.json – 3 error(s)
- [ ] webextensions/api/contextualIdentities.json – 14 error(s)
- [ ] webextensions/api/cookies.json – 17 error(s)
- [ ] webextensions/api/devtools.json – 22 error(s)
- [ ] webextensions/api/dns.json – 1 error(s)
- [ ] webextensions/api/downloads.json – 54 error(s)
- [ ] webextensions/api/events.json – 10 error(s)
- [ ] webextensions/api/extension.json – 9 error(s)
- [ ] webextensions/api/extensionTypes.json – 4 error(s)
- [ ] webextensions/api/find.json – 3 error(s)
- [ ] webextensions/api/history.json – 16 error(s)
- [ ] webextensions/api/i18n.json – 5 error(s)
- [ ] webextensions/api/identity.json – 2 error(s)
- [ ] webextensions/api/idle.json – 6 error(s)
- [ ] webextensions/api/management.json – 19 error(s)
- [ ] webextensions/api/menus.json – 30 error(s)
- [ ] webextensions/api/notifications.json – 19 error(s)
- [ ] webextensions/api/omnibox.json – 7 error(s)
- [ ] webextensions/api/pageAction.json – 15 error(s)
- [ ] webextensions/api/permissions.json – 7 error(s)
- [ ] webextensions/api/privacy.json – 12 error(s)
- [ ] webextensions/api/proxy.json – 7 error(s)
- [ ] webextensions/api/runtime.json – 48 error(s)
- [ ] webextensions/api/search.json – 2 error(s)
- [ ] webextensions/api/sessions.json – 14 error(s)
- [ ] webextensions/api/sidebarAction.json – 17 error(s)
- [ ] webextensions/api/storage.json – 11 error(s)
- [ ] webextensions/api/tabs.json – 129 error(s)
- [ ] webextensions/api/theme.json – 7 error(s)
- [ ] webextensions/api/topSites.json – 4 error(s)
- [ ] webextensions/api/types.json – 2 error(s)
- [ ] webextensions/api/webNavigation.json – 34 error(s)
- [ ] webextensions/api/webRequest.json – 181 error(s)
- [ ] webextensions/api/windows.json – 61 error(s)

**webextensions/manifest**
- [ ] webextensions/manifest/author.json – 1 error(s)
- [ ] webextensions/manifest/background.json – 4 error(s)
- [ ] webextensions/manifest/browser_action.json – 7 error(s)
- [ ] webextensions/manifest/browser_specific_settings.json – 1 error(s)
- [ ] webextensions/manifest/chrome_settings_overrides.json – 19 error(s)
- [ ] webextensions/manifest/chrome_url_overrides.json – 4 error(s)
- [ ] webextensions/manifest/commands.json – 8 error(s)
- [ ] webextensions/manifest/content_scripts.json – 10 error(s)
- [ ] webextensions/manifest/content_security_policy.json – 1 error(s)
- [ ] webextensions/manifest/default_locale.json – 1 error(s)
- [ ] webextensions/manifest/description.json – 1 error(s)
- [ ] webextensions/manifest/developer.json – 1 error(s)
- [ ] webextensions/manifest/devtools_page.json – 1 error(s)
- [ ] webextensions/manifest/externally_connectable.json – 1 error(s)
- [ ] webextensions/manifest/homepage_url.json – 1 error(s)
- [ ] webextensions/manifest/icons.json – 1 error(s)
- [ ] webextensions/manifest/incognito.json – 4 error(s)
- [ ] webextensions/manifest/manifest_version.json – 1 error(s)
- [ ] webextensions/manifest/name.json – 1 error(s)
- [ ] webextensions/manifest/offline_enabled.json – 1 error(s)
- [ ] webextensions/manifest/omnibox.json – 2 error(s)
- [ ] webextensions/manifest/optional_permissions.json – 26 error(s)
- [ ] webextensions/manifest/options_ui.json – 4 error(s)
- [ ] webextensions/manifest/page_action.json – 8 error(s)
- [ ] webextensions/manifest/permissions.json – 39 error(s)
- [ ] webextensions/manifest/protocol_handlers.json – 7 error(s)
- [ ] webextensions/manifest/short_name.json – 1 error(s)
- [ ] webextensions/manifest/sidebar_action.json – 6 error(s)
- [ ] webextensions/manifest/theme.json – 43 error(s)
- [ ] webextensions/manifest/version.json – 1 error(s)
- [ ] webextensions/manifest/version_name.json – 1 error(s)
- [ ] webextensions/manifest/web_accessible_resources.json – 1 error(s)

**Comment by Elchi3** [comment]
We've already made this mandatory for everything but WebExtensions. I think WebExtensions will never get this info. Closing
