### ISSUE TITLE
Chore: cleanup data in notes

### ISSUE THREAD

**Issue by queengooborg** [mdn/browser-compat-data#5190]
As I was reviewing the Samsung Internet mirroring PRs, I noticed various points of data expressed in the notes that had significant information regarding the support in the browser.  For example, in Chrome Android, there was support from the initial release, but then there was a note indicating how it's only supported in Windows and Linux.  Obviously, this should make Chrome Android support `false` instead.

When we have some time, we should skim through the notes and update their data, removing redundant information and overall cleaning up.

(Speaking of, do we want to keep our "This value is recognized, but has no effect." notes? 
 We had a discussion about this somewhere, but I can't remember what the outcome was.)

**Comment by ddbeck** [comment]
> (Speaking of, do we want to keep our "This value is recognized, but has no effect." notes?
> We had a discussion about this somewhere, but I can't remember what the outcome was.)

I think this was the end of that discussion: https://github.com/mdn/browser-compat-data/pull/3904#issuecomment-484484932. The short answer is yes, keep the notes. The discussion was more about how it interacted with "partial_implementation": if you have a real version number for such a (mis-)feature, set `"partial_implementation": true` and keep the note. If you don't have a real version number, keep the note and set `"version_added": false`. In other words, it's an editorial decision that privileges version number accuracy over the correctness of the `"partial_implementation"` flag.

I ought to write this up in the data policies doc.

**Comment by ddbeck** [comment]
> I ought to write this up in the data policies doc.

[Oh wait I already did](https://github.com/mdn/browser-compat-data/blob/master/docs/data-guidelines.md#non-functional-defined-names-imply-partial_implementation), though I didn't address the notes question specifically.

**Comment by Elchi3** [comment]
I'm closing this stalled issue. I think the introduction of "mirror" cleaned out a lot of weird notes.
