### ISSUE TITLE
Linter for mdn_url

### ISSUE THREAD

**Issue by bershanskiy** [mdn/browser-compat-data#5201]
Sometimes the `__compat.mdn_url` property is incorrect, e.g. as shown in #5195. After seeing that issue, I looked for more similar bugs and found a couple, so I propose we make an explicit linter check for `mdn_url`. Below is a draft checklist, please tell me if it sounds reasonable.

# Checks
1. Any top-level feature has a proper link, e.g. `api.feature` has a link `https://developer.mozilla.org/docs/Web/API/feature`
2. Any sub-feature has a link that extends from the parent
E.g. `api.feature.attribute` has a link `https://developer.mozilla.org/docs/Web/API/feature/attribute` and `api.feature.feature_event` has link `https://developer.mozilla.org/docs/Web/API/feature/feature_event`

**Comment by bershanskiy** [comment]
Notes to self:
https://developer.mozilla.org/docs/Web/API/FileReaderSync

**Comment by bershanskiy** [comment]
As per @vinyldarkscratch's request, I started writing a linter for all MDN URLs in all folders and here are odd URLs I don't know what to do about:
 - `javascript.builtins.Intl` has reasonable URL: 
    ```
     https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl
     ```
    but its children have URLs without `Intl`, e.g. `javascript.builtins.Intl.Collator` has
    ```
    https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Collator
     ```
     These URLs might be inconsistent with MDN practices.

**Comment by bershanskiy** [comment]
@sideshowbarker I noticed you filed #5256 and #5257, which actually help with linter (since they fix some values that linter would fail on). If you are interested, here are some more similar issues (some of these might be false positives):

× api\CSSMathNegate.json
  mdn_urls – 1 error:

    Actual: "https://developer.mozilla.org/docs/Web/API/CSSMathNegate/value"
    Expected pattern: "^https://developer.mozilla.org/docs/Web/API/CSSMathNegate/values$"
√ api\CSSMathNegate.json
× api\DOMHighResTimestamp.json
  mdn_urls – 1 error:

    Actual: "https://developer.mozilla.org/docs/Web/API/DOMHighResTimeStamp"
    Expected pattern: "^https://developer.mozilla.org/docs/Web/API/DOMHighResTimestamp$"
√ api\DOMHighResTimestamp.json
× api\Headers.json
  mdn_urls – 2 errors:

    Actual: "https://developer.mozilla.org/docs/Web/API/Headers/get"
    Expected pattern: "^https://developer.mozilla.org/docs/Web/API/Headers/has$"

    Actual: "https://developer.mozilla.org/docs/Web/API/Headers/Headers"
    Expected pattern: "^https://developer.mozilla.org/docs/Web/API/Headers/headers$"
√ api\Headers.json
× api\MediaKeyStatusMap.json
  mdn_urls – 1 error:

    Actual: "https://developer.mozilla.org/docs/Web/API/MediaKeyStatusMap/[@@iterator]"
    Expected pattern: "^https://developer.mozilla.org/docs/Web/API/MediaKeyStatusMap/iterator$"
√ api\MediaKeyStatusMap.json
× api\PaintWorkletGlobalScope.json
  mdn_urls – 3 errors:

    Actual: "https://developer.mozilla.org/docs/Web/API/PaintWorklet"
    Expected pattern: "^https://developer.mozilla.org/docs/Web/API/PaintWorkletGlobalScope$"

    Actual: "https://developer.mozilla.org/docs/Web/API/PaintWorklet/devicePixelRatio"
    Expected pattern: "^https://developer.mozilla.org/docs/Web/API/PaintWorkletGlobalScope/devicePixelRatio$"

    Actual: "https://developer.mozilla.org/docs/Web/API/PaintWorklet/registerPaint"
    Expected pattern: "^https://developer.mozilla.org/docs/Web/API/PaintWorkletGlobalScope/registerPaint$"
√ api\PaintWorkletGlobalScope.json
× api\Selection.json
  mdn_urls – 2 errors:

    Actual: "https://developer.mozilla.org/docs/Web/API/Selection/removeAllRanges"
    Expected pattern: "^https://developer.mozilla.org/docs/Web/API/Selection/empty$"

    Actual: "https://developer.mozilla.org/docs/Web/API/Selection/collapse"
    Expected pattern: "^https://developer.mozilla.org/docs/Web/API/Selection/setPosition$"
√ api\Selection.json
× api\ServiceWorkerRegistration.json
  mdn_urls – 7 errors:

    Actual: "https://developer.mozilla.org/docs/Web/API/ServiceWorkerRegistration/showNotification"
    Expected pattern: "^https://developer.mozilla.org/docs/Web/API/ServiceWorkerRegistration/showNotification/actions$"

    Actual: "https://developer.mozilla.org/docs/Web/API/ServiceWorkerRegistration/showNotification"
    Expected pattern: "^https://developer.mozilla.org/docs/Web/API/ServiceWorkerRegistration/showNotification/badge$"

    Actual: "https://developer.mozilla.org/docs/Web/API/ServiceWorkerRegistration/showNotification"
    Expected pattern: "^https://developer.mozilla.org/docs/Web/API/ServiceWorkerRegistration/showNotification/data$"

    Actual: "https://developer.mozilla.org/docs/Web/API/ServiceWorkerRegistration/showNotification"
    Expected pattern: "^https://developer.mozilla.org/docs/Web/API/ServiceWorkerRegistration/showNotification/image$"

    Actual: "https://developer.mozilla.org/docs/Web/API/ServiceWorkerRegistration/showNotification"
    Expected pattern: "^https://developer.mozilla.org/docs/Web/API/ServiceWorkerRegistration/showNotification/renotify$"

    Actual: "https://developer.mozilla.org/docs/Web/API/ServiceWorkerRegistration/showNotification"
    Expected pattern: "^https://developer.mozilla.org/docs/Web/API/ServiceWorkerRegistration/showNotification/requireInteraction$"

    Actual: "https://developer.mozilla.org/docs/Web/API/ServiceWorkerRegistration/showNotification"
    Expected pattern: "^https://developer.mozilla.org/docs/Web/API/ServiceWorkerRegistration/showNotification/vibrate$"
√ api\ServiceWorkerRegistration.json
× html\elements\html.json
  mdn_urls – 1 error:

    Actual: "https://developer.mozilla.org/docs/Web/HTML/Using_the_application_cache"
    Expected pattern: "^https://developer.mozilla.org/docs/Web/HTML/Element/html/manifest$"
√ html\elements\html.json
× html\elements\iframe.json
  mdn_urls – 1 error:

    Actual: "https://developer.mozilla.org/docs/Mozilla/Gecko/Chrome/API/Browser_API"
    Expected pattern: "^https://developer.mozilla.org/docs/Web/HTML/Element/iframe/mozbrowser$"
√ html\elements\iframe.json
× http\data-url.json
  mdn_urls – 1 error:

    Actual: "https://developer.mozilla.org/docs/Web/HTTP/Basics_of_HTTP/Data_URIs"
    Expected pattern: "^https://developer.mozilla.org/docs/Web/HTTP/data-url$"
√ http\data-url.json
× http\headers\clear-site-data.json
  mdn_urls – 4 errors:

    Actual: "https://developer.mozilla.org/docs/Web/HTTP/Headers/Clear-Site-Data"
    Expected pattern: "^https://developer.mozilla.org/docs/Web/HTTP/Headers/Clear-Site-Data/cache$"

    Actual: "https://developer.mozilla.org/docs/Web/HTTP/Headers/Clear-Site-Data"
    Expected pattern: "^https://developer.mozilla.org/docs/Web/HTTP/Headers/Clear-Site-Data/cookies$"

    Actual: "https://developer.mozilla.org/docs/Web/HTTP/Headers/Clear-Site-Data"
    Expected pattern: "^https://developer.mozilla.org/docs/Web/HTTP/Headers/Clear-Site-Data/executionContexts$"

    Actual: "https://developer.mozilla.org/docs/Web/HTTP/Headers/Clear-Site-Data"
    Expected pattern: "^https://developer.mozilla.org/docs/Web/HTTP/Headers/Clear-Site-Data/storage$"
√ http\headers\clear-site-data.json
× javascript\builtins\Object.json
  mdn_urls – 4 errors:

    Actual: "https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Object/__defineGetter__"
    Expected pattern: "^https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Object/defineGetter$"

    Actual: "https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Object/__defineSetter__"
    Expected pattern: "^https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Object/defineSetter$"

    Actual: "https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Object/__lookupGetter__"
    Expected pattern: "^https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Object/lookupGetter$"

    Actual: "https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Object/__lookupSetter__"
    Expected pattern: "^https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Object/lookupSetter$"
√ javascript\builtins\Object.json
× javascript\builtins\Promise.json
  mdn_urls – 1 error:

    Actual: "https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Promise"
    Expected pattern: "^https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Promise/Promise$"
√ javascript\builtins\Promise.json
× webextensions\api\cookies.json
  mdn_urls – 2 errors:

    Actual: "https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/API/cookies/set"
    Expected pattern: "^https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/API/cookies/Cookie/sameSite$"

    Actual: "https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/API/cookies/set"
    Expected pattern: "^https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/API/cookies/sameSiteStatus$"
√ webextensions\api\cookies.json

**Comment by sideshowbarker** [comment]
> @sideshowbarker I noticed you filed #5256 and #5257, which actually help with linter (since they fix some values that linter would fail on). If you are interested, here are some more similar issues (some of these might be false positives)

Thanks — I’ll be happy to raise PRs for those

**Comment by vinyldarkscratch** [comment]
Speaking of which, @bershanskiy, would you be willing to re-share your linter code (particularly in the form of a PR), since we repurposed the original PR for just the API folder updates?

**Comment by bershanskiy** [comment]
@vinyldarkscratch 
> would you be willing to re-share your linter code

Done! #5273

**Comment by Elchi3** [comment]
I'm going to close this in favor of https://github.com/mdn/browser-compat-data/issues/5201 which suggests to test for broken links.
