### ISSUE TITLE
`Object.getOwnPropertyDescriptor` does not have full support in IE 8

### ISSUE THREAD

**Issue by ljharb** [mdn/browser-compat-data#5202]
Specifically, `Object.getOwnPropertyDescriptor(arguments, '')` will throw, where it should not.

I found the line that needs updating: https://github.com/mdn/browser-compat-data/blob/7f8137d2b78bc1ec37f8eb11e27c128772e6c09e/javascript/builtins/Object.json#L768 but i'm not sure what to put there, since it's not not *added* in IE 8, it's not experimental, or deprecated - it's just got partial support.

**Comment by vinyldarkscratch** [comment]
Thanks for finding this, and sorry for the lack of response until now!  What we'll want to do is add `"partial_implementation": true` on the line right below, followed by `"notes": "[Explanation of why it's only got partial support]"`.

**Comment by ljharb** [comment]
Looks like the solution for defineProperty was to just indicate IE 9, not 8, with a note explaining the partial support in IE 8 - i'll go with that :-)

**Comment by ljharb** [comment]
Filed #5542.
