### ISSUE TITLE
Indicate property value compatibility

### ISSUE THREAD

**Issue by while0pass** [mdn/browser-compat-data#5247]
Is it possible to indicate compatibility on a property value basis?

For instance, [`column-fill`](https://github.com/mdn/browser-compat-data/blob/master/css/properties/column-fill.json) is reported to be supported by Chrome, though all the versions, the latest v78 included, only support `auto` and `balance` values and don't support [`balance-all`](https://developer.mozilla.org/en-US/docs/Web/CSS/column-fill) ("invalid property value"). I can't figure out if it is possible to more granularly report compatibility for property values instead of whole properties.

![image](https://user-images.githubusercontent.com/140562/69958074-0de79a00-1515-11ea-996b-97786b625897.png)

**Comment by vinyldarkscratch** [comment]
For such instances, we typically create a subfeature with the ident as whatever the property value is, and a description stating it's that very value.  We should certainly have a subfeature marked for this value.  I can confirm `balance-all` isn't available in Chrome, thanks for raising the issue!
