### ISSUE TITLE
IDB APIs: Internet Explorer has notes that just read "partial"

### ISSUE THREAD

**Issue by vinyldarkscratch** [mdn/browser-compat-data#5261]
I noticed that all of the IDB APIs have notes on Internet Explorer that simply reads "partial", with no additional details.  Obviously, this is confusing, and doesn't give us much details.  We should find out why there where such notes, or remove them entirely.

**Comment by joebabineau** [comment]
i never subscribed assholes fuckoff or else

**Comment by ddbeck** [comment]
Maybe these notes can be replaced with `"partial_implementation": true` and the problem of what it _means_ can be subsumed into #4162.

**Comment by vinyldarkscratch** [comment]
Okay, yeah -- I'll get a PR rolling for this ASAP!
