### ISSUE TITLE
Input Type Time working on Safari on iOS 13

### ISSUE THREAD

**Issue by lucasperretta** [mdn/browser-compat-data#5275]
It seems that as of Safari 13.2.3 the ```<input type="time">``` html tag works, currently it's marked as not compatibile.

I'm not entirely sure of when it started working but it seems that at least in this version it's working fine.
One of the things that I could notice it seems not to be working is the **step** property.

![WhatsApp Image 2019-12-05 at 12 15 05](https://user-images.githubusercontent.com/13281823/70247982-04e70a80-1759-11ea-941f-1291929292fc.jpeg)

**Comment by ddbeck** [comment]
Thanks for opening this issue @lucasperretta.

I can't confirm when this feature was first supported on iOS either, but this WebKit bug suggests that it has been supported for some time: https://bugs.webkit.org/show_bug.cgi?id=119175. #5293 partly fixes this issue by marking it as true, but it'd be nice to know when this first appeared. Something to revisit in the future.

**Comment by myakura** [comment]
per their [release notes](https://developer.apple.com/documentation/safari_release_notes/safari_12_1_release_notes), support for `<input type="color">` was added in Safari 12.1.

**Comment by queengooborg** [comment]
This was fully fixed by #19888!
