### ISSUE TITLE
Change "Optional Chaining" Spec from Stage 3 to Stage 4

### ISSUE THREAD

**Issue by djamshed** [mdn/browser-compat-data#5322]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining#Specifications
says the  "Optional Chaining" is on `Stage 3`, whereas it recently hit `State 4` https://github.com/tc39/proposal-optional-chaining#status 

I would gladly put out a PR, but couldn't find a related document/guide (it probably isn't part of browser compatibility json, which has clear guidelines).

**Comment by ddbeck** [comment]
@djamshed good catch! As you've pointed out, it's not really part of the browser compatibility data. That spec information is part of the MDN content. You can edit that MDN page yourself, if you click the "Edit in wiki" link at the top of the page, then click the "Edit" link on that page. It'll eventually get reflected in the regular, published page. Thanks!
