### ISSUE TITLE
Remove events from HTML data?

### ISSUE THREAD

**Issue by vinyldarkscratch** [mdn/browser-compat-data#5354]
A couple of times, I've noticed that we have information about JavaScript events in our `html/` data folder, however we also have this information inside of the `api/` counterparts.  I'm thinking that we should keep it all within `api/` and remove it from `html/`, de-referencing JavaScript features in `html/`.

**Comment by ddbeck** [comment]
Could you add a few examples to this issue? Source links would be ideal—I'm not sure what data this refers to.

**Comment by vinyldarkscratch** [comment]
Of course!  #5320 is a recent example that modifies the events data on both `html/events/body.json` and the Window API data.  I feel we should de-duplicate it.

**Comment by ddbeck** [comment]
Oh, OK! This is interesting. It's a fine distinction, but we have at least three different kinds of features when it comes to events:

* the event API itself (e.g., a `foo_event` feature)
* the event handler API (e.g., an `onfoo` feature, like all those `on` handlers in [GlobalEventHandlers](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers))
* the event handler attribute in HTML (e.g., `<tagname onfoo="bar">`)

So it's not that there's event data in `/html` per se, but we do have data for the attributes which correspond to events.

My first impression here is to let all three kinds of features stand. I'm a bit reluctant to say, yes, let's cover every attribute for every HTML tag except for a rather large number of attributes. Plus I'm not sure I'd bet on all browsers having implemented all their event attributes at the same time as implementing the event API.

**Comment by vinyldarkscratch** [comment]
Ahhhhh, that’s right, I legitimately completely forgot HTML has attributes for event handlers...  /)_-
