### ISSUE TITLE
webkitGetAsEntry Safari info is incorrect

### ISSUE THREAD

**Issue by 3cp** [mdn/browser-compat-data#5356]
https://developer.mozilla.org/en-US/docs/Web/API/DataTransferItem/webkitGetAsEntry

The safari support is incorrect. safari got it since 2017.

https://trac.webkit.org/changeset/221177/webkit

**Comment by sideshowbarker** [comment]
> https://developer.mozilla.org/en-US/docs/Web/API/DataTransferItem/webkitGetAsEntry
> 
> The safari support is incorrect. safari got it since 2017.
> 
> https://trac.webkit.org/changeset/221177/webkit

Small correction: https://trac.webkit.org/changeset/221177/webkit says:

>  What is not supported: … dataTransferItem.webkitGetAsEntry() …

https://trac.webkit.org/changeset/222412/webkit seems to be the change that actually turned on `webkitGetAsEntry`. So that means it shipped in Safari 11.1 in 2018.
