### ISSUE TITLE
Decide what to do with remaining "experimental" CSS features

### ISSUE THREAD

**Issue by rachelandrew** [mdn/browser-compat-data#5392]
I've been working through the features marked as experimental in https://github.com/mdn/sprints/issues/2402. It was suggested that those I identified as actually experimental, I created a list of. As discussed in that issue I think it would be better to have a way of marking that there are issues raised against the spec for a feature. The table I have created is as follows, these features are currently still flagged experimental, pending a decision.

| Property/Value                             | MDN Page | Issue |
| ------------------------------------------ | -------- | ----- |
| css.at-rules.document                      | https://developer.mozilla.org/en-US/docs/Web/CSS/@document | postponed to L4. Currently does not appear in any spec. See: https://www.w3.org/TR/2012/WD-css3-conditional-20121213/#changes |
| css.at-rules.document.regexp               | as above | as above |
| css.properties.appearance                  | https://developer.mozilla.org/en-US/docs/Web/CSS/appearance | https://drafts.csswg.org/css-ui-4/#appearance-switching |
| css.properties.background-position-x | https://developer.mozilla.org/en-US/docs/Web/CSS/background-position-x | https://drafts.csswg.org/css-backgrounds-4/#background-position-longhands (only marked as experimental in the data repo, not BCD) |
| css.properties.background-position-y | https://developer.mozilla.org/en-US/docs/Web/CSS/background-position-y | https://drafts.csswg.org/css-backgrounds-4/#background-position-longhands (only marked as experimental in the data repo, not BCD) |
| css.properties.break-after.region_context  | https://developer.mozilla.org/en-US/docs/Web/CSS/break-after | Regions are themselves in flux, difficult to declare this as stable due to that. |
| css.properties.break-before.region_context | https://developer.mozilla.org/en-US/docs/Web/CSS/break-before | as above |
| css.properties.break-inside.region_context         |https://developer.mozilla.org/en-US/docs/Web/CSS/break-inside|as above|
| css.properties.column-width.intrinsic_sizes |https://developer.mozilla.org/en-US/docs/Web/CSS/column-width|https://drafts.csswg.org/css-writing-modes-4/#auto-multicol|
| css.properties.initial-letter-align |https://developer.mozilla.org/en-US/docs/Web/CSS/initial-letter-align|Potential of renaming: https://drafts.csswg.org/css-inline/#sizing-drop-initials|
| css.properties.initial-letter |https://developer.mozilla.org/en-US/docs/Web/CSS/initial-letter|Potential of renaming: https://drafts.csswg.org/css-inline/#sizing-drop-initials|
| css.properties.line-height-step |https://developer.mozilla.org/en-US/docs/Web/CSS/line-height-step|Issue re animation: https://drafts.csswg.org/css-rhythm/#line-height-step|
| css.properties.max-height |https://developer.mozilla.org/en-US/docs/Web/CSS/max-height|fit-content is defined only as a function, stretch deferred to L4 currently does not have a spec.|
| css.properties.max-width |https://developer.mozilla.org/en-US/docs/Web/CSS/max-width|as above|
| css.properties.min-height |https://developer.mozilla.org/en-US/docs/Web/CSS/min-height|as above|
| css.properties.min-width |https://developer.mozilla.org/en-US/docs/Web/CSS/min-width|as above|
| css.properties.ruby-align |https://developer.mozilla.org/en-US/docs/Web/CSS/ruby-align|https://drafts.csswg.org/css-ruby/#ruby-align-property|
| css.properties.ruby-position |https://developer.mozilla.org/en-US/docs/Web/CSS/ruby-position|https://drafts.csswg.org/css-ruby/#rubypos|
| css.properties.text-align.string |https://developer.mozilla.org/en-US/docs/Web/CSS/text-align|https://drafts.csswg.org/css-text-4/#alignment|
| css.properties.text-decoration-skip |https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-skip|https://drafts.csswg.org/css-text-decor-4/#text-decoration-skip-property|
| css.properties.text-overflow.fade_function |https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow|https://drafts.csswg.org/css-text-decor-4/#text-decoration-skip-property|
| css.properties.text-size-adjust |https://developer.mozilla.org/en-US/docs/Web/CSS/text-size-adjust|https://drafts.csswg.org/css-size-adjust/#adjustment-control|
| css.selectors.blank |https://developer.mozilla.org/en-US/docs/Web/CSS/:blank|https://drafts.csswg.org/selectors-4/#blank-pseudo (at-risk) see: https://github.com/w3c/csswg-drafts/issues/1967|
| css.types.attr |https://developer.mozilla.org/en-US/docs/Web/CSS/attr|at-risk in the CR https://drafts.csswg.org/css-values-3/|
| css.types.image.element |https://developer.mozilla.org/en-US/docs/Web/CSS/image|https://drafts.csswg.org/css-images-4/#element-notation|

**Comment by Elchi3** [comment]
Great research, Rachel! I will dive into this some more, but my first feeling is that we should re-label these as "unstable". It would be a new nomenclature in BCD, but I can see it replacing "experimental". Probably it shouldn't be just a boolean value either, but require an explanatory note.

**Comment by rachelandrew** [comment]
Yes, I think unstable with a note to explain why would be a good call.

**Comment by queengooborg** [comment]
I checked through about half of the entries in the list and have found that they are either no longer marked as experimental or have been removed.  As such, I'm going to go ahead and close this issue.  If I missed any, please feel free to open a new issue and ping me, and I'll happily get it resolved!
