### ISSUE TITLE
missing document visibilitychange_event 

### ISSUE THREAD

**Issue by SKalt** [mdn/browser-compat-data#5447]
[Web/API/Document/visibilitychange_event](https://developer.mozilla.org/en-US/docs/Web/API/Document/visibilitychange_event#Browser_compatibility) is missing.
The relevant information is contained in [Document/visibilityState](https://developer.mozilla.org/en-US/docs/Web/API/Document/visibilityState#Browser_compatibility) and [Document/onvisibilitychange](https://developer.mozilla.org/en-US/docs/Web/API/Document/onvisibilitychange#Browser_compatibility).

**Comment by vinyldarkscratch** [comment]
Looks like this was added in #6763!
