### ISSUE TITLE
Apparently conflicting data for "onunhandledrejection" compatibility

### ISSUE THREAD

**Issue by forevermatt** [mdn/browser-compat-data#5449]
The [Window page's Browser compatibility list](https://developer.mozilla.org/en-US/docs/Web/API/Window#Browser_compatibility) says that `onunhandledrejection` is only supported by Chrome, Edge, Firefox, and Firefox for Android.

However, the [WindowEventHandlers.onunhandledrejection page's Browser compatibility list](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onunhandledrejection#Browser_compatibility) says that `onunhandledrejection` is supported by several more browsers than that.

Does one of these need to be updated, or are they referring to different things?

**Comment by vinyldarkscratch** [comment]
Good catch, thank you!  From what it seems like, this was duplicated data that was never removed.  https://developer.mozilla.org/en-US/docs/Web/API/Window/onunhandledrejection also redirects to https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onunhandledrejection.  I'll get a PR going to remove the bad data!
