### ISSUE TITLE
Allow multiple prefs/flags per data point

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/browser-compat-data#546]
Firefox's Streams API implementation is hidden behind two flags, so I initially wrote the BCD like this:

```
          "firefox": {
            "version_added": "57",
            "flag": {
              "type": "preference",
              "name": "dom.streams.enabled",
              "value_to_set": "true"
            },
            "flag": {
              "type": "preference",
              "name": "javascript.options.streams",
              "value_to_set": "true"
            }
          },
```
But this probably won't work, or at least will result in a mess in the table output.

Instead we should probably support an array for the data, e.g.

  ```
          "firefox": {
            "version_added": "57",
            "flag": [
              {
                "type": "preference",
                "name": "dom.streams.enabled",
                "value_to_set": "true"
              },
              "flag": {
                "type": "preference",
                "name": "javascript.options.streams",
                "value_to_set": "true"
              }
            ]
          },
```

And make sure the table output works for such a case.

**Comment by teoli2003** [comment]
Yes, I agree, we should do the second. Adapting the schema is likely easy (and backward compatible), but we also need to adapt the {{Compat}} macro.

**Comment by Elchi3** [comment]
`flag` has been renamed to `flags` and accepts an array now.
The docs have been updated, too. https://github.com/mdn/browser-compat-data/blob/master/compat-data-schema.md#flags
