### ISSUE TITLE
Show compat data for default browser set(s)

### ISSUE THREAD

**Issue by malqinneh** [mdn/browser-compat-data#5462]
Display browser sets within user accounts:
- [ ] identify a default list of browsers
- [ ] users can toggle browser sets on or off
- [ ] users can see supported browsers on article pages

Acceptance criteria:
- [ ] engineering (Tobin) sign-off
- [ ] pm (Kadir) sign-off

**Comment by jmswisher** [comment]
@vinyldarkscratch Thanks for triaging, but please don't close issues opened by staff members (which includes @malqinneh) with out checking with them.

**Comment by vinyldarkscratch** [comment]
Oh wait, they’re a staff member?  Ack!  I’m so sorry...  There were similar issues opened months ago and I assumed they were all spam.  >~<

If I may ask though, I’m not sure how these issues are related to the BCD itself.  Wouldn’t this be a design thing for the MDN pages?  AFAIK, this repository only focuses on the data, not really the display of said data.

**Comment by vinyldarkscratch** [comment]
Pinging @Elchi3.

**Comment by malqinneh** [comment]
Ah, they're in the wrong place, I'll move them.

**Comment by Elchi3** [comment]
Yeah, we could move these to mdn/sprints, I guess. It would be nice if we (me + the browser-compat-data community) could get some heads up and context about this project and then it is not so much of a surprise when we see issues like this.
