### ISSUE TITLE
Update browser version JSON to latest versions

### ISSUE THREAD

**Issue by a2sheppy** [mdn/browser-compat-data#5464]
Chrome doesn't yet go up to version 80, and Firefox stops at 71 nightly, but nightly is now 80.

**Comment by Elchi3** [comment]
I think this has been fixed this week in https://github.com/mdn/browser-compat-data/pull/5456 and https://github.com/mdn/browser-compat-data/pull/5457. Please update to latest master and re-open if there is still an issue.
