### ISSUE TITLE
Element.scrollWidth has support in IE

### ISSUE THREAD

**Issue by aleen42** [mdn/browser-compat-data#5491]
I have tested that `scrollWidth` property can be used under IE, and searched some refererred exceptions:

- https://stackoverflow.com/questions/30900154/workaround-for-issue-with-ie-scrollwidth

But, why is it unknown compatible?

**Comment by ddbeck** [comment]
@aleen42 Unknown compatibility means we don't have data for that feature (i.e., it's a `null` value). If you want to contribute an update to that feature, you can find it in `/api/Element.json`: https://github.com/mdn/browser-compat-data/blob/master/api/Element.json#L7059 Thank you!

**Comment by aleen42** [comment]
OK, I'll research this and ccreate PR later

**Comment by vinyldarkscratch** [comment]
Hey @aleen42, do you plan to return to this issue?

**Comment by aleen42** [comment]
Sorry for the late PR.
