### ISSUE TITLE
Capture when WebView drops support for an Android version

### ISSUE THREAD

**Issue by jpmedley** [mdn/browser-compat-data#5503]
Yesterday it was [announced on the Chromium-dev group](https://groups.google.com/a/chromium.org/forum/#!topic/chromium-dev/ypAS49lvN1M) that starting in Chrome 82, Android 6 (KitKat) will [no longer be supported](https://bugs.chromium.org/p/chromium/issues/detail?id=1041930).

This [happened for Lolipop in 72](https://bugs.chromium.org/p/chromium/issues/approval?id=847939) and [Icecream Sandwich in 44](https://www.chromium.org/Home/ice-cream-sandwich-support-deprecation-faq). (I would need to investigate earlier deprecations.)

This should be captured in the BCD data and surfaced in compatibility tables.

**Comment by vinyldarkscratch** [comment]
This is certainly an interesting question!  I guess it could also expand to other browsers, potentially as an “OS support” field or something.  We’d certainly need to see if BCD users would want this data, but overall I’m down for working something out.

**Comment by ddbeck** [comment]
If I'm understanding correctly, then Android users on older versions of Android can't upgrade WebView (and presumably Chrome for Android) past some version number (e.g., KitKat users will never have a WebView >81 and Lolipop users will never have a WebView >71).

If that's the case, then I'm not sure this is in scope for BCD. I wouldn't expect, for example, that BCD would have data on which versions of Windows got IE or Edge releases, or which Apple hardware got Safari for iOS updates. (Of course, it would be great to have data like that—I can imagine a lot of uses for it—but I'm skeptical that it's something that we could keep on top of.)

**Comment by stof** [comment]
@jpmedley FYI, the link about lolilop only displays a `Permission denied.` message.

**Comment by ddbeck** [comment]
Sorry about this, but I don't expect this issue to be taken up and I'm going to close it. Apart from the scope question, I don't expect the MDN team to have the resources to work on it anytime soon (e.g., adding a new layer of data to MDN compat tables).
