### ISSUE TITLE
Update Chrome compat of navigator.cookieEnabled

### ISSUE THREAD

**Issue by jakub-g** [mdn/browser-compat-data#5508]
https://developer.mozilla.org/en-US/docs/Web/API/Navigator/cookieEnabled

# Need an update:

- Chrome compat says 59, but it seems this has been since the beginning of Chrome (See this crbug from 2008 -> https://bugs.chromium.org/p/chromium/issues/detail?id=1850#c15). I tested successfully with Chrome37 on BrowserStack (it reports `true` when cookies enabled, and `false` when disabled). Git blame for Chrome 59 info is this: https://github.com/mdn/browser-compat-data/pull/2069/files#diff-db17ac884a304ccf650cf9b05dc94bbbR432 but it's not clear where it came from.

# No update needed:

- Safari entry says just 'yes'. I was suspicious and I found this Apple page says 'Safari 10.0+' but it's actually wrong.
https://developer.apple.com/documentation/webkitjs/navigator/1633873-cookieenabled. I tested in Safari 5 on BrowserStack and it works (note also the crbug linked before talks about Safari 3.x)

- I also confirm that it works in IE, even old ones (sometimes IE info is not reliable). See also this SO thread: https://stackoverflow.com/a/6125366/245966 as another confirmation.

**Comment by vinyldarkscratch** [comment]
Thanks for raising this issue!  I did some digging around in some VMs of mine, and found that `navigator.cookieEnabled` was nowhere _near_ implemented in Chrome 59.  In fact, it was implemented all the way since Safari 1.0.  I'm opening up a PR to fix this right away!
