### ISSUE TITLE
Presto-based Opera: add data and double-check features set to "15"

### ISSUE THREAD

**Issue by queengooborg** [mdn/browser-compat-data#5514]
Something I've been thinking about for a while is our Opera data.  A lot of times, I find myself leaving a feature as "true" or "null" when performing mirroring from Chrome to Opera for features that have been around for a long time, but sometimes we have put "15" (the first Chrome-based version), even if the version number may not be accurate.  I've opened up a PR to introduce ranged versions for Opera, but at the same time, I feel we should double-check the validity of our Opera data, and provide the real version numbers if we can prove otherwise.

I'm already working on this project, starting with the CSS folder (then moving onto JavaScript), so this issue is primarily for tracking purposes only.  Of course, if anyone would like to help out, I'd be grateful -- simply [grab some virtual machines](https://drive.google.com/open?id=1w6nVUMD5MwkoevzuhCDuDpbxyk3ywCRY) and start finding (or re-finding) version numbers for anything marked as `true`, `null`, or `15` for Opera!

## To Do (Now)

- [ ] api
- [x] css/at-rules (#5513)
- [x] css/properties (#5521)
- [x] css/selectors (#5526)
- [x] css/types (#5528)
- [x] javascript/builtins (#5611 / #5612 / #5613 / #5614 / #5615 / #5616 / #5617 / #5618)
- [x] javascript/functions (#5619)
- [x] javascript/grammar (#5620)
- [x] javascript/operators (#5621)
- [x] javascript/statements (#5622)

## To Do (After Chrome Data is Completed)

- [ ] html/global_attributes
- [ ] html/elements
- [ ] html/manifest
- [ ] http/data-url
- [ ] http/headers
- [ ] http/methods
- [ ] http/status
- [ ] svg/attributes
- [ ] svg/elements
- [ ] webdriver/commands
- [ ] webextensions/api
- [ ] webextensions/manifest
- [ ] webextensions/match_patterns

**Comment by WebMechanic** [comment]
Opera Legacy releases for the (once) many supported systems dating back to v10:
 - https://ftp.opera.com/ftp/pub/opera/
There are more folders "above" with variations of the same beasts named "Suite" or "Developer". No need to bother.

And there's https://portableapps.com/apps/internet/opera_portable also hosting a "Legacy" 12.8 with Presto.

Enjoy!

**Comment by vinyldarkscratch** [comment]
Thanks @WebMechanic, but actually I've [already set up a collection of VMs](https://drive.google.com/drive/u/0/folders/1w6nVUMD5MwkoevzuhCDuDpbxyk3ywCRY) for this very purpose.  :wink:

**Comment by WebMechanic** [comment]
jepp, just saw the VMs; 
I for one can't "virtualize" for some bizarre reason.

**Comment by WebMechanic** [comment]
I know it's "off-topic", but is there a similar issue regarding EdgeHTML Edge/12-18 vs Chromium Edg/79+?
Thanks.

**Comment by vinyldarkscratch** [comment]
There is, yep!  Feel free to check out #5214 for that -- in all honesty we're pretty much done with the issue, it just needs review and merging.

**Comment by WebMechanic** [comment]
I was just curious :) Thank you!
