### ISSUE TITLE
outdated info: min-content/max-content/fit-content are now all supported in Edge

### ISSUE THREAD

**Issue by o-t-w** [mdn/browser-compat-data#5538]
As of Edge version 79 you can use `min-content`, `max-content` and `fit-content` for setting `min-width`, `max-width` and `width`.

**Comment by vinyldarkscratch** [comment]
We plan to mirror data from Chrome to Edge soon (see #5214) to fix these issues, and should have something up soon!

(For now, I’ll go ahead and close this issue since it’s already discussed in the other issue.)
