### ISSUE TITLE
Safari does not support force-end keyword value of hanging-punctuation property

### ISSUE THREAD

**Issue by matori** [mdn/browser-compat-data#5541]
Now, CSS `hanging-punctuation` property compat table shows Safari fully supports this property.
https://developer.mozilla.org/ja/docs/Web/CSS/hanging-punctuation#Browser_compatibility

Test case: https://codepen.io/Matori/pen/GRgzmgy

In this test case, results of `allow-end` and `force-end` should be same, but Safari is not.
(I checked with Safari 13.0.4)
<img width="244" alt="test case result on safari" src="https://user-images.githubusercontent.com/2851102/72957331-86b4f500-3de6-11ea-8e59-4db17e7a9db8.png">

And Webkit source has no `force-end` keyword in `BreakingContext`. (`first`, `last`, `allow-end` are exist.)
https://github.com/WebKit/webkit/blob/master/Source/WebCore/rendering/line/BreakingContext.h#L699-L701

**Comment by vinyldarkscratch** [comment]
Thanks for raising the issue!  I see what you mean, yeah -- Safari recognizes `force-end`, but it's not really performing the expected behavior (in other words, "the value is recognized but has no effect").  I'll open up a PR for this to add a note!
