### ISSUE TITLE
Ranged values: place data in browser files?

### ISSUE THREAD

**Issue by queengooborg** [mdn/browser-compat-data#5574]
A random thought had just come to mind regarding the allowed ranged values.  Currently, we have a dictionary of what browsers support what ranged values, but I'm thinking maybe we should put said data into our browser JSON?  This would make the data a little more machine-readable, and I feel it's a better place than simply in our linter files.

Example:

```json
{
  "browsers": {
    "webview_android": {
      "name": "WebView Android",
      "releases": {
        "37": {
          "release_date": "2014-09-03",
          "release_notes": "https://chromereleases.googleblog.com/2014/09/chrome-for-android-update.html",
          "status": "retired",
          "engine": "Blink",
          "engine_version": "37",
          "allow_range": true
        },
      }
    }
  }
}
```

(The variable name can be changed of course!)

**Comment by vinyldarkscratch** [comment]
As we're working to rid all ranged version data as it is, this schema change is probably less desirable.

**Comment by queengooborg** [comment]
I'm going to close this issue as we may be less restrictive about which versions can be ranged values anyways.
