### ISSUE TITLE
Safari 13: Element.getBoundingClientRect().top now supported in Safari Version 13.0.4 

### ISSUE THREAD

**Issue by hongsidev** [mdn/browser-compat-data#5589]
`Element.getBoundingClientRect().x` and `Element.getBoundingClientRect().y` are now supported in Safari.

Can test in [here](https://developer.mozilla.org/ko/docs/Web/API/Element/getBoundingClientRect) with plain JS 
`console.log(document.getElementById('nav-footer').getBoundingClientRect().x)`
`console.log(document.getElementById('nav-footer').getBoundingClientRect().y)`

if it is now supported, can I create PR for this issue?

**Comment by vinyldarkscratch** [comment]
Looks like this has been supported since Safari 11, thanks for opening the issue!  Yeah, feel free to open a PR for this.  :wink:
