### ISSUE TITLE
ScrollToOptions are working fine in Safari and latest Edge

### ISSUE THREAD

**Issue by sergeykaikin** [mdn/browser-compat-data#5594]
ScrollToOptions seem to be working fine in latest mobile and desktop Edge browsers. And also in iOS Safari 12.2 and iOS Safari 13.3, and on MacOS with Safari 13.x.

I don't really know since which versions those vendors started supporting ScrollToOptions hence can't create a PR. Sorry 😅

**Comment by vinyldarkscratch** [comment]
Thanks for the issue!  Regarding the Edge data, we’re working to mirror all the data over from Chrome soon (we’re currently at the Mozilla All Hands 2020 conference), so we’ll be getting that resolved soon.  As far as Safari data, I’ll look into it!
