### ISSUE TITLE
Edge 79 can use named capture groups

### ISSUE THREAD

**Issue by jianlin** [mdn/browser-compat-data#5601]
don't know how to contribute yet... do I have to provide test case data and make sure the test runs, and send a pull request, or can I just modify the compatibility table and send a pull request?

right now it is about 
https://caniuse.com/#feat=mdn-javascript_builtins_regexp_named_capture_groups

Edge 79 can really use it:

```
"Lee, Mary".match(/(?<last>\w+), (?<first>\w+)/)

(3) ["Lee, Mary", "Lee", "Mary", index: 0, input: "Lee, Mary", groups: {…}]
0: "Lee, Mary"
1: "Lee"
2: "Mary"
index: 0
input: "Lee, Mary"
groups: {last: "Lee", first: "Mary"}
length: 3
```

**Comment by vinyldarkscratch** [comment]
We've actually got some pull requests open to mirror the Chrome data to Edge, thus resolving the issue (see #5561).  All that's left is to review and merge them, and then we're good to go!

I'm going to close this issue since it's a subset of #5214 -- but don't worry, we'll get a fix out soon.
