### ISSUE TITLE
navigator.sayswho is not documented

### ISSUE THREAD

**Issue by Adamkillander96** [mdn/browser-compat-data#5610]
`navigator.sayswho` prints "Chrome 79" in Microsoft Edge (Version 79.0.309.71, 64 bit).

Does anyone know what it's used for? Not quite sure what it means or does. 

![image](https://user-images.githubusercontent.com/34036252/73449377-4ebc2d80-4363-11ea-88e0-aeb2a8528b0e.png)

**Comment by vinyldarkscratch** [comment]
I believe this is created by whatever webpage you're on; this isn't an actual feature.  A quick test in both Chrome and Edge shows as such:

<img width="1920" alt="Screen Shot 2020-01-30 at 15 55 42" src="https://user-images.githubusercontent.com/5179191/73460549-f859e980-4378-11ea-988f-37cf566b8edf.png">

Closing this PR as a result.

**Comment by Adamkillander96** [comment]
Man do I feel stupid! 
Found out it is a variable set by Onetrust, which explains why I saw it on multiple sites. Sorry for the lack of research.

**Comment by vinyldarkscratch** [comment]
No worries, happens all the time!
