### ISSUE TITLE
Implement dependabot?

### ISSUE THREAD

**Issue by vinyldarkscratch** [mdn/browser-compat-data#5632]
I noticed "dependabot" was added to the new `stumptown-renderer` project, and I was thinking that maybe we should implement it into this repository as well?

**Comment by ExE-Boss** [comment]
I personally recommend @renovatebot instead.

**Comment by Elchi3** [comment]
I activated dependabot in settings some time ago, but it so far only did a PR for a security related upgrade: https://github.com/mdn/browser-compat-data/pull/5837
Maybe it needs configuration or it doesn't work with our pinned versions?

**Comment by ExE-Boss** [comment]
[Renovate](https://github.com/apps/renovate) supports pinned versions.

**Comment by vinyldarkscratch** [comment]
Probably just needs a little bit of configuration, if I had to guess?  One thing I noticed is that there is no Dependabot config file in the repo, so I'd assume we'd have to add that in.

**Comment by Elchi3** [comment]
cc'ing @schalkneethling who might have an idea. Schalk, how to configure dependabot?

We switched from renovate to dependabot over in https://github.com/mdn/interactive-examples/issues/1549 and I think BCD will also work with what the majority of the MDN team uses and has knowledge about.

**Comment by schalkneethling** [comment]
It is configured :)

**Comment by schalkneethling** [comment]
![Screenshot 2020-03-24 at 20 47 23](https://user-images.githubusercontent.com/10350960/77464992-abdad980-6e10-11ea-8385-d4edfe41a579.png)

One just needs to log into Dependabot.com and add the repo.

**Comment by schalkneethling** [comment]
And there is the first bump https://github.com/mdn/browser-compat-data/pull/5872

**Comment by vinyldarkscratch** [comment]
Oh really?  I thought there had to be a `.dependabot/config.yml` file present, huh...  I'm not too familiar with Dependabot though (or any similar bots to be honest), but I just saw that new bump go live!

**Comment by schalkneethling** [comment]
> Oh really? I thought there had to be a `.dependabot/config.yml` file present, huh... I'm not too familiar with Dependabot though (or any similar bots to be honest), but I just saw that new bump go live!

You can add it if you need additional custom config, but just adding it via the admin takes care of the basics.

**Comment by vinyldarkscratch** [comment]
Ahhhh, gotcha -- thanks for the information!

I think that we can close this issue now that we've got Dependabot going.
