### ISSUE TITLE
Safari TP 97 includes ResizeObserver

### ISSUE THREAD

**Issue by scheinercc** [mdn/browser-compat-data#5657]
I just found this: 
> ResizeObserver was enabled by default as of Safari Technology Preview 97*
https://webkit.org/blog/9997/resizeobserver-in-webkit/

Wasn't sure if "TP" would be just added as string for the version or if it is done differently:
https://github.com/mdn/browser-compat-data/blob/83f27ae03a9ce31837bf51a3b30ecd0c48415747/api/ResizeObserver.json#L32

_*They are currently at 99: https://developer.apple.com/safari/technology-preview/release-notes/_

**Comment by sideshowbarker** [comment]
> Wasn't sure if "TP" would be just added as string for the version or if it is done differently:

For Safari releases, BCD doesn’t (yet) provide any way for marking features as supported in a particular Safari Technology Preview version, nor in a particular future/upcoming stable release.

So for now, unless a feature shipped in Safari 13, we don’t have any way to update BCD for it.

**Comment by Elchi3** [comment]
It's on purpose. BCD aims talks about shipped products and not really about Developer Editions, Technical Previews, Nightlies, and Canaries of browsers. It's already quite a task to have good data about features available in released browsers, so preview browser versions are not really our focus.

On Safari TPs, there is https://github.com/mdn/browser-compat-data/issues/2991#issue-370118399 which tries to collect a mapping from TP versions to actual Safari releases. So, when there is a new Safari release, we can then look up TP release notes and add the corresponding Safari version to BCD. Of course, all this would be easier if Apple/WebKit would support BCD with updates, much like Google, Microsoft, or Samsung do for their products here.

**Comment by scheinercc** [comment]
Thanks! Closing as 'wontfix'. If anything, #2991 looks already after this  anyway.
