### ISSUE TITLE
data for HTMLFormElement#requestSubmit

### ISSUE THREAD

**Issue by stof** [mdn/browser-compat-data#5695]
This API is released in Firefox 73 according to https://hacks.mozilla.org/2020/02/firefox-73-is-upon-us/ but the [MDN page linked in the blog post](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/requestSubmit) is missing the compat data.

**Comment by ddbeck** [comment]
The hacks post was updated with a correction to show that the feature is behind a flag after all. PRs that relate to this issue:

* #5488 (merged) added the data
* #5710 (in progress) partially reverts this for Firefox
* #5717 (in progress) fixes the status data

I think this can be closed once the incorrect Firefox data is fixed.

**Comment by Elchi3** [comment]
Ships in 75 now. Data updated:
https://github.com/mdn/browser-compat-data/pull/5805#pullrequestreview-377746431
