### ISSUE TITLE
Firefox 73 update

### ISSUE THREAD

**Issue by bershanskiy** [mdn/browser-compat-data#5713]
Firefox 73 reached stable a few days ago, but some data from release notes did not reach BCD yet. This is a meta issue for tracking smaller independent PRs that should be easier to review than a monolithic one.

[Firefox 73 for developers](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/73)

## Work in progress

> The `yearName` and `relatedYear` fields have been made available in the `DateTimeFormat.prototype.formatToParts()` method, enabling useful formatting options for CJK calendars (bug 1591664).

This is blocked on #5709. After that's merged, `DateTimeFormat` constructor can be extended with all yet undocumented constructor argument attributes.

> Added WebDriver:Print to print the current page as a PDF document (bug 1604506).
> Webdriver:TakeScreenshot now always captures the top-level browsing context and not the currently-selected browsing context, if no element to capture has been specified (bug 1398087, bug 1606794).
> Using Webdriver:TakeScreenshot's full argument causes the complete page to be captured (bug 1571424).

All this probably fits into a single PR, right?

## Related PRs
 - #5712 - Firefox 73: MathML <mfenced> and <mo> removed

**Comment by bershanskiy** [comment]
@vinyldarkscratch I'm not sure this issue needs "bulk update" label, since it is a lot of tiny manual changes done and reviewed manually without a script.

**Comment by vinyldarkscratch** [comment]
I wasn’t sure what other label would apply, so I figured the bulk update label made the most sense (ignoring the migration script parts), since it’s a number of changes that aren’t really exclusive to one or a few folders.  No worries though, I’m not expecting any scripts for this work.  😉

**Comment by Elchi3** [comment]
Thanks for your issue. I'm not sure what work is left here. If there is anything please re-open and leave a comment what that work is.
