### ISSUE TITLE
Element: wheel event does not work correctly in IE

### ISSUE THREAD

**Issue by e-dong** [mdn/browser-compat-data#5723]
### Reproduction steps: 
1. Navigate to https://developer.mozilla.org/en-US/docs/Web/API/Element/wheel_event on `Chrome`, and `Edge`.
2. Scroll down to the Example with the interactive demo, "Scale me with your mouse wheel."
3. Scaling occurs when using the mouse wheel.
4. Repeat steps (1-2) for `IE11`
6. Scaling does not occur
7. Repeat steps (1-2) for `Firefox`
8. Scaling occurs very slowly compared to `Chrome` and `Edge`

Either the `Browser compatibility` is incorrect for IE or this should be working on IE.

### Browsers Used
| Browser | Version | Behavior |
| --- | ----------- | -------------------------------|
| Chrome| Version 79.0.3945.130 (Official Build) (64-bit) | Normal |
| Firefox | 68.4.1esr (32-bit) | Requires more wheel turns to scale same distance (compared to Chrome, Edge) |
| Edge | Microsoft Edge 44.17763.831.0, Microsoft EdgeHTML 18.17763    | Normal |
| IE      |   11.1039.17763.0CO  | Scaling does not occur

**Comment by vinyldarkscratch** [comment]
This behavior appears to be represented in the note added in #5687.
