### ISSUE TITLE
Android Chrome (Huawei P20 Pro)  canvas.toDataURL image doesn't display

### ISSUE THREAD

**Issue by stewa11** [mdn/browser-compat-data#5780]
When the image Chrome is changed with image.src = canvas.toDataURL(), the image doesn't display on mobile, when the image displays fine on PC Windows 10 Chrome. 

The image on mobile is just a black square ..0:-/

Is this a known issue?

I'll keep testing.

Thanks
Stew

The **unchanged** generated HTML is below:

`<div class='infoDiv'><h2> bradgate park</h2></br>Longitude,Latitude:   52.6970518736761,-1.19853481403909</br>Person QR Text:    </br>Location QR Text:   http://www.bradgatepark.org<div><img src="data:image/jpg;base64,/9j/4AAQSkZJRgABAQEAAAAAAAD/2wBDABsSFBcUERsXFhceHBsgKEIrKCUlKFE6PTBCYFVlZF9VXVtqeJmBanGQc1tdhbWGkJ6jq62rZ4C8ybqmx5moq6T/2wBDARweHigjKE4rK06kbl1upKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKT/wAARCACWASwDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDFuoxJcyvEoVGclV6YGelReQ/tWkYuOKimkY/IImBxj1//AFVClcbVij5D+lSQxbZVMi5XPIq8I8Jkjn0FIiq/IBpc47Gljw+/WLb+D/0pfK8Pf3f/AEZWf5NMkQIu4gn6Uc4cppeV4d9P/RlZerw2IaM6cWIOd4OcDpjr+NSeT7UeTRzhymVsYfwmja3ofyrTaNVOD1pu2PBORgU+YLFSzgWa5jjlfykY4LntWz/YmndtTT/vpf8AGqflLgn+719qTYnHzDnp70c4WLY0G1PTVYvyH/xVEvh6JbeSVL9H2KWwEHOB9apiNTkgjjrz0o8tD0YevWjmCxnHgkUma0TGnPzLx15pPKT+8OBnrRzCsZ+a1bPQrq7tkuI3h2vnAYnPXHpUPkA9MVKgljGI5HX/AHWIo5kFiQ+HL8dBEfo1QXGjX1tG0kkQCL1IcVMJrsdLmYf9tDTZJLqRCj3EzKeoLkg0+ZBYzDlTgikzVowAtzyaWO1EhwuPz9OtCdwsVM1fttJvrqBZoYd0bdDuA749aj+yj0rrNDXZpMC/73/oRpp3Ezm/7B1L/n3/APH1/wAayK9JNebUwCiiigAooooAKKKKACiiigAooooAKKKKAOj20EADJ4FPxQVBGDXJc1IABnO7Jz0z70qAAcgLjI69ql8tfT9aPLX0P507hYTbVS/RinX5eMAdzV4CmPFvlRiflTkD1NEZWdxNEUORGCSGTGQ3t70SSqgXClixxgDmn/Z2WGSJSMMTtz2B7U02SK8bRDaVOTknkU7oNRspQbGZGyAW6DIGOc/nUeyI/KS5T7gPGBnn6+lW5YwzpmPcOcnOMf40jxjcrCHcfrgD3xQmFitmPynzvIYgnkZOf5D60rQqhU4cnBYAYOOQfxqRY+T/AKOy8f3z+XFO271UNCVAyOGPA/CncLECiPa8YYndwDj1/wD10SwpsYsxGz5cgeuP8amCgjJtyCvzY9x2/QUMAyszQSZY8rk88D/P4UXCxGyIzEB8FwCOPT/9VR+XG3zeYctxjae49PwqyyoGB8hy3rySOvf8P1oWKNk2+S4BHQk9ugp3FYhMCiVQX+ckHAHXj/6xpsYRUwsmSwwuEPp1/WrRCEiQxPkng4ORg/pTPKjUIRHJgYIAXOM//qouFhsESKrIrbgpxz2pZV2gcEgntUkCLuBVZE453Dr1/wAamKAjBqW9RmYVyVG48cgY7U6K2DNuDMOh46c1aNmhOe/0qZYwowKbn2FYgEQAwB0roLDiwt/+uS/yrGYAKT6CtmAeXBGn91QP0rSlrcUiY15vXoNy+22lb0Qn9K8+rVkhRRRSAKKKKACiiigAooooAKKKKACiiigDp6WggqSD1HBoriNRiGVy21FwpxyxH9KcVmAyUj/77P8AhS25IllX3Dfpj+lWK1SRF2V9k/8Acj/77P8AhS7J/wC5H/32f8KmXIO05PfNKxwPenyoLsrkTAZKR/8AfZ/wpHdo8eYYUz03SYz+lWQOOaqyqY5nd1+U/wDLQnp7H0o5YhzMeolYBlWIg9CHP+FO2z/3I/8Avs/4VDhlYNE209xjIb61J9sxw0Emf9nBH86OVBzMdtm/uR/99n/CjbN/cT/vs/4VGZbh+crGp6ADJH49KQR5HMspPrvP9KORC5mSDzCxXamR1G/p+lKwkUEsqAD/AGv/AK1QtFGgBG7zCeGB+Y/jTZmlaMJIRvHPHRh/iPSq9mh8zH/aD/c/8eo+0HOPL/WqoY9MnFPQGXKAcnoBR7NC5mTi5yB8h596Xz/VCOcZzURXDEYwR1z2pMdanlQczLu1/wC7+tG1/wC7+tPgO6FD3xzmnjpS5UPmZDtf+5+tNQh0Vh0YZqdjhSfQVBENsSD0UCpkkik7jZgTC+Ou01tVlx/61M92A/WtYitqOzJmVtQO2wnP+wRXBV3GscadL+H8xXD1q9yQooopAFFFFABRRRQAUUUUAFFFFABRRRQB2JRXYsV5Jz1o8pP7v61X0+dp4SzZzuxzVqnyx7BdlcqEuht6On8j/wDXqWopOJIT7sn6Z/pUtYy3ARulVVvP3jbo8AZIycHGcdPWlvnJQQqfmkO36Dufy/nSFAEA/hToDyB+FVFK2oPbQFviZEDRYRmCg7uefarlYckkhlR4gBt6en1wanN1OVwZOfZaXKBa2Kl06oNq7FO0cDOTTwPmIrPV33FzIxY8ZzS/amRsF8EjqaqwjRwKa8gQc9aqrcyY52n3NMkl3LgrnLDcSeo9PamOxZikR2JDhn/T8PWm3JygRGPmkjYByc/570kt5DImGt2cjopx/jUsdzbICIYzk9ljIz+lSA97NWGR8rEc46U63jEBYtjLegwBUam5PzmVVJ/g25A/rSCBTlpBvkJzvHBH09KrW1mLS9yeeJXKsenTIqI2pDDc25e46Gm7ngU7mMkfrjkfXHX69frVqM7lVsg8dRUNWGAOTgLjj8qXfGDgOuemM0jgsODj8aYYQWbDDceR7VIx07f6PIR/dP8AKpwq4xtHHtVSXCxSK7AMykAdKtr1P1q4ruBDe5jty8YAdSpBx3yKoG6uS2WuZAx7ZxVzU322h9SQKw3uQmVxz6mnJO9kIuXV5PJGYnmLg9RgVg1owyl0KkD5e/rWdTQBRRRTAKKKKACiiigAooooAKKKKACiiigDf0ZwWkGTnAIGa1KxNJIW74GNykf1/pW3VR2B7le4GFDf3ZFP58f1qTOBmmXX+ol9k3D6jmmzyiKFpD0UZ+tZSWoytnzbt3J+WMbBn16n/Ci5fZFgcE8DFFts8oKsgdhyxBzyarTOXlJ7DgVQvMdbRedIEBxQIzjqAfQkCmLxSklnwPXigQ9lUDlue2MH+tRkdjSrBPuwQXHqOf1pwR87SuG4x7elMBA7gqEIAzzk1JKrLyzA57Z6fpTRBLx8vBzzkdqXyJSSMc5xyRU8uoETMVGeSO+KVSCARjBqQQuUDDBH1/z6GmvG6HDD9aoNR8MauSGZl+gJ/P0600kxsQDyDjIJpFdwCFcrng4PWkhDE4ZRkDgA9aWg7j2EtwNvmEDqc/8A1qmWKWGNdkoXHU9c5PJweKepccCLA9cinHcUwyDaV5OelZSqSWxSSe5C3mOUAlfcy7mOcYHHYY7ml+yh/wDWPJIPR3z/AEptv80pZucIoyBxySeP0qzXTBJq7M5NpjFRY0REUKu5Rge5FaI7/WqBGWQf7a/zFX16fiaJaOwR2KmqnbbBv7rZ/Q1zbbid7D73c9639ZWWSJI4lLE5JA9OKzNQ3QyCJBtTaMDPtUlENt0b8Ko1ftf9Q/HeqFT1AKKKKYBRRRQAUUUUAFFFFABRRRQAUUUUAaNlJtu4j/tY/Piuhrn0VQQw7cjFdApyAfWiLExrqG+U9CCDUFsS0MbHrtH8qsN1U+9V4OEI9HYfqamYwnjjZGZ41YgHGRms+08ow5fbn/aLc/l+NaUhGxs9MVjQ/wCrX6VMR3sSsRzjOCeKT8aTtTdhdgQTn271ZLLKyjHLybj3z37U5WiYk7WPQck57f4GovIfBPH0p8bRqj52bsdGUnJ9iOnFF77DSAyIc5Q/dIHPfOc0edHkkRYP+8fSmJEzgkcDtmkkiZVIPHbIouhFmF4GwHiGc9c9aey/MWTaq+65P86oruA+bmnMxPBJIHqalq4XLRmQDGdx74prpsXdvww7YPHPY9+tRJC7dto9TxmrQj/dhdxlKkYDE4A+n0qW4xLSvuLBmSMM3f2ouZMAKMYPBA6n2xTZ3ZdoGA7dBnikhi2ZZjudurHv/gP8+1TCm5u45SUVYfAmwEtyxOT9f8/yqXcvHH6U0Ak4AzUqRAcnk11uUYKxjZsYCDPCMYy39DVxfuiq55lix2Y/+gmpBNGpCFvmxz7fX0qFLm1KtYG5nH+yv8z/APWrD1lgbzH91QK2WOLl/wDcX+ZrAvmMt3KR696YCQYEHXkkms+tBBthUVn1C3GFFFFMAooooAKKKKACiiigAooooAKKKKANTI9MVrwufsasgywTge9Y4U1q6e262AznaSKmG4MgF5J5ir8zNkblxwB+VWU/1sw/28/oKmZQVPHaof8Al5b3RT/OnPYBLhS0EijqVIFZSAFeeMdR3rSnm8t0Gxnzn7uKzCcyuwyAWJGevWojcb2FOM45xTopArBuooiTzJFTIGTjJpZbdYQGGQWPIZdpq7XRNupOPL67zx6uahnKs2V/GmEFeT+VCjcwUd6lRs73AejL0ZmXtkGpNkW0kPub3NPNgyqGLgjODt5qaFIkxt2k5xncM0pLsNLuVY7d25PyD1NWYoY0AYYb0JpbiSCJQGkUhjxt9aeo2Lg8A5INTOXulxVmID5nzLkdsEEVGk6iRkOC44UDPP408T/OF28EcHOaSewiZ9xQjJ5KcE/pURi2tRu1yK3XcWlY5Z/wwM8D9P5VZUAsAe9LHEFixhvlAA5P+FOiXcTs6jg8/wD1q6k0o2Rk027kgwBgCmSeYR8qn+ufzqQDBI9KWsGUQxBxMu8k/Kx5/D396DY5mL+YdjHJUjPP1p5/4+F/65t/Nas1rARUc/vJfYgfoP8AGsmVCZ2JZjk9K0rggTSe5/oKpuuWqmBWl4JHasutOU/N+NZlSgCiiimAUUUUAFFFFABRRRQAUUUUAFFFFAGoCSM5xWhprcOuO+azNvP3qvaYdsrL6ipjuBp1WfieL3Rh+RFWKrz/AHovaQjP1BqpiRVc77l3XHyjYPr3/pVNkZSAwx9avSW67967lPohxuqpmUKv2gELzkkZAOeOn9aVrIY0KzZKrketSCEBSS656YHJp6y+ZhQuFxyQM49sU+GNAgIAqbSe+gXQ1UGPuM/PG44qXLKBtRVHfAzUnygcfzx/SnArzwPbJP8AhRyxHdkOZOrhD9ARTg0obKkBeBgsR6//AFqkyO4XGOxPFMAUNTaTFewjB5hliDjkcf40igZ2/P8ARuc09mKjPb1pCwIw/bp65qHdPQq99xFKgDDLjuRxRJcSuh2lMjlQwHNM2gAFkG0dAB0qVVUKNvT2q7tonYbJdYjDRx8kcb1xye2O9WolYKC+N+OcDGPaq9ggaBZW+ZySck57kcelW6hsBRS0nam/xAZPv71Iw63A/wCubfzFWKrp/rT7L/WrFbQ2EzOuDmVvrUBNSz8yt9TUT/dbHpVAUWPIrOrRbGRnpWdUoAooopgFFFFABRRRQAUUUUAFFFFABRRRQBoVYsGxdIAevWqwXk559qkgOyeM44DCoW4G7UFzwhPo6n9QKmqG6/1Mv+4T+VayEhp+Ytg/d7YqNlEqlGQlfTkf0pF8zlQmFPGTzke9AfaR5u38QBj9ay5hkRs4MhSrLt5G1jz+lSyQxqWJLjnOQx7+1IJYt3SIenzjNThgwIxkH8c0cwyusQHPnTEfT/EUqrKVJVw3PAZCP1/+tTyic5Epz1/dn/CnqyRx4wyqO7KR/OnzeQiImRfvR5wM5Vsj9cU1pY9wDblLdAykZ/Ophc27LnzUH1bFOaSHDAuuMcjNK6YEWWPQY+tCgAZPJ9TTols5siOOFtvXCD/CnNb2q/eiiH4AUcyCw0etROGHyRcM/QenqakK2o+5KkZ/2GA/TpSxoVPyOWY8s4AwR6d6L9gsTqvlQqiDO0ACjdJz8v6D/Gow0ik7ix/7Zsf6VIrMeFyPrGRUWYx4355YEew/+vQACxOBn1phE2c/OR6KF/qacGkJ5hcfUr/jRysAQ/v3/wB1f5mrFQKjCRnIwGCgfgT/AI1NW0FZCZmynMjfU1FJ/q2+lCndlj1z1pJeIjTApN1xWfV8n56oVKAKKKKYBRRRQAUUUUAFFFFABRRRQAUUUUAaLMAxHP4UEjA96KKzA3EO5QfUZoYZIHrkUUVs9hEKwSqoUSpwMcof8aLdWG9S/Kyc4HXgH+tFFCSWwErOofaS3P6VIBgYoopgLUdxCJ4WiJwG70UUAUILKNrTDu+3ceBjr0/pTvs1u8jEvPuk4bkc80UUrATW0FtCSEQksM5bB9asBznARR+P/wBaiimA5pGVclR78/8A1qY1wFYj046UUUAItzvUEdzj7v8A9epcuR2z9aKKAGM0gHPGPQ//AFqYJiWCbjnO3kUUUAWG7fWloopAYyFgvrzRMf3X1ooqehRSJ5NUaKKSEFFFFMAooooAKKKKACiiigAooooAKKKKAP/Z" alt="No image."></div></div>`

**Comment by vinyldarkscratch** [comment]
I'm unable to replicate this issue using BrowserStack and a similar setup.  I'm assuming that you're loading an image into the canvas first -- if so, I'd double-check to make sure that the image is preloaded before exporting as a data URL.
