### ISSUE TITLE
≤ is ambiguous on MDN

### ISSUE THREAD

**Issue by saschanaz** [mdn/browser-compat-data#5782]
![image](https://user-images.githubusercontent.com/3396686/75923260-fea22080-5e64-11ea-8d03-861659719fe2.png)

https://developer.mozilla.org/en-US/docs/Web/API/MediaSession

It makes me think that Edge supported the feature *until* version 79, not *at-least-since* 79. There is no description about what `≤` actually means. I think this is a problem.

**Comment by vinyldarkscratch** [comment]
This seems like it's more of a rendering thing than a BCD thing.  Can you file this in https://github.com/mdn/kumascript instead?

**Comment by saschanaz** [comment]
Could you transfer this if you happen to have a proper permission?

**Comment by vinyldarkscratch** [comment]
I do not have the ability to transfer issues to that repository as I only have write access to this one.
