### ISSUE TITLE
Figure out what to do AudioBufferSourceNode.stop

### ISSUE THREAD

**Issue by ddbeck** [mdn/browser-compat-data#5794]
> `AudioBufferSourceNode` inherits from `AudioScheduledSourceNode` (which provides `stop` and `start` members — so that’s why the spec doesn’t shows `stop` as a member of `AudioBufferSourceNode` itself
> […]
> Intuitively, it seems to me like we’d not want to forever retain the `stop` feature/member in the `api/AudioBufferSourceNode.json` source, in addition to `api/AudioScheduledSourceNode.json` source. But as I said, I don’t know what the precedents/conventions are for this kind of case.

_Originally posted by @sideshowbarker in https://github.com/mdn/browser-compat-data/pull/5525#issuecomment-577432782_

@sideshowbarker raised this question on #5525. Honestly, I'm not sure I understand the API in question enough to figure out what has happened here. I kept meaning to figure it out, but rather than letting it get lost in a PR comment no one will ever see again, I've decided to open this issue.

**Comment by vinyldarkscratch** [comment]
I think that since the members are implemented on `AudioScheduledSourceNode` rather than `AudioBufferSourceNode`, then we should remove the members from `AudioBufferSourceNode`?

**Comment by Elchi3** [comment]
This is probably a duplicate of https://github.com/mdn/browser-compat-data/issues/3463

Other, maybe related, complicated issues: https://github.com/mdn/browser-compat-data/issues/472, https://github.com/mdn/browser-compat-data/issues/3441

**Comment by foolip** [comment]
I accidentally filed what amounts to a dupe of this, where now there's a fair bit of detail/discussion: https://github.com/mdn/browser-compat-data/issues/6656

OK to close this, even though it was earlier?

**Comment by ddbeck** [comment]
Yeah, let's move the discussion to #6656 and close this one. The new issue includes `api.AudioBufferSourceNode.stop` and other features on the same hierarchy.
