### ISSUE TITLE
Tracking WebAssembly features

### ISSUE THREAD

**Issue by petamoriken** [mdn/browser-compat-data#5796]
WebAssembly features implemented in browsers is unknown. Fortunately, [the WebAssembly feature detection library](https://github.com/GoogleChromeLabs/wasm-feature-detect) is available and it can be tracked.

FYI: https://github.com/WebAssembly/proposals/issues/21

**Comment by gsnedders** [comment]
The biggest part of this is we need to decide how to model many of these extensions (i.e., what granularity we want… do we want to have a compat entry for each [instruction](https://webassembly.github.io/spec/core/appendix/index-instructions.html)? or do we want to group these by high-level extensions like "threads"?).

**Comment by MendyBerger** [comment]
@gsnedders think tracking hi level extensions makes the most sense, browsers have for the most part been adding whole new extensions at once, not instruction by instruction.
In the case where a browser does add only parts of an extension it can be marked with `partial_implementation`.

Thoughts?

**Comment by MendyBerger** [comment]
@Queengooborg what do you think? (I was told that you're the one that can make a decision here)

Feel free to assign to me if you agree with my previous comment.

**Comment by queengooborg** [comment]
This sounds great and would certainly be a big help in keeping BCD auto-maintained!  Perhaps this is something we can integrate into the collector project?  https://github.com/foolip/mdn-bcd-collector

**Comment by MendyBerger** [comment]
@queengooborg what about making them part of BCD? Think it would make sense to track these features in here, it's less than 20 features altogether.
