### ISSUE TITLE
Add data for Samsung Internet 11

### ISSUE THREAD

**Issue by AdaRoseCannon** [mdn/browser-compat-data#5804]
@vinyldarkscratch would it be possible for me to use your script to do this?

If so, is there a guide to using it?

**Comment by vinyldarkscratch** [comment]
Thank you for asking!  Currently, the mirroring script isn’t quite capable of handling this scenario programmatically, as I was planning on getting that functionality implemented after the initial review and merge.  I guess...perhaps the best way for the time being is to run the script with `—modify=false`* to only adjust entries set to “false”, and cherry-pick changes that set the version number to “11”?  It’s not great, unfortunately, but it’s something for now!

* That long hyphen is actually a double-hyphen — I’m on my iPhone while writing this

**Comment by Elchi3** [comment]
The script is in https://github.com/mdn/browser-compat-data/pull/4729 btw and I plan to review it in within the next week and see if it would be extendable easily for this case.

**Comment by AdaRoseCannon** [comment]
Thank you so much!

**Comment by AdaRoseCannon** [comment]
This works well,

One thing that comes up a lot is overriding notes e.g.
```
              "notes": "Starting with Samsung Internet 7.0 and Opera 45, setting this property to false does nothing, as per <a href='https://github.com/whatwg/dom/issues/211'>spec discussion</a>."
```
becomes
```
              "notes": "Starting with Samsung Internet 58 and Opera 45, setting this property to false does nothing, as per <a href='https://github.com/whatwg/dom/issues/211'>spec discussion</a>."
```

When the associated version_added is boolean, if a note is already present it could probably be ignored.
