### ISSUE TITLE
"npm test <filespec>" should error if <filespec> doesn't match a file

### ISSUE THREAD

**Issue by a2sheppy** [mdn/browser-compat-data#5811]
The `npm test` command, which runs the tests on the docs, lets you provide a parameter indicating a subset of the files to test. However, it doesn't appear to produce an error if the file doesn't exist.

`> npm test foo.bar`

Results in:
```
> mdn-browser-compat-data@1.0.11 test /Users/sheppy/Development/projects/mozilla/forks/browser-compat-data
> npm run lint "foo.bar"


> mdn-browser-compat-data@1.0.11 lint /Users/sheppy/Development/projects/mozilla/forks/browser-compat-data
> node test/lint "foo.bar"

Checking formatting...
All matched files use Prettier code style!
```

This is not clearly distinguishable (if it is at all) from a successful test. If you mistype your test command, you could have a false impression of what's going on.

**Comment by jculver050** [comment]
Close
