### ISSUE TITLE
CSS color-scheme property

### ISSUE THREAD

**Issue by takamoso** [mdn/browser-compat-data#5825]
Drafts: https://drafts.csswg.org/css-color-adjust/#color-scheme-prop

Caution: according to https://drafts.csswg.org/css-color-adjust/#valdef-color-scheme-only

> Per spec, only can only be used with light. Apple’s implementation allows it with dark as well. The concern with only dark is that pages won’t consider UAs that can’t support dark schemes, and will thus render brokenly. This value might be expanded to all schemes or removed entirely depending on further consideration.

And support status:

|   | IE | Edge | Firefox | Chrome | Safari | Opera | iOS Safari | Android |
|- |-   |-         |-            |-              |-          |-           |-                 |-             |
| `normal` `light` `dark` `only light` | - | 81 | - | 81 | 13 | 68 | 13 | 81|
| `only dark` | - | - | - | - | 13 | - | 13 | - |

**Comment by noelleleigh** [comment]
Chrome bug: https://crbug.com/929098
Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1576289
Safari blog post: https://webkit.org/blog/8840/dark-mode-support-in-webkit/

**Comment by connorshea** [comment]
I'd appreciate this as well.

The original CSSWG Draft: https://github.com/w3c/csswg-drafts/issues/3299

CSS Tricks article: https://css-tricks.com/a-complete-guide-to-dark-mode-on-the-web/#ua-styles

**Comment by Elchi3** [comment]
I've sent https://github.com/mdn/browser-compat-data/pull/7253, which attempts to record the current compat situation. Would appreciate a look!
