### ISSUE TITLE
Auto-labeler having issues?

### ISSUE THREAD

**Issue by vinyldarkscratch** [mdn/browser-compat-data#5843]
Hey @ddbeck, the past couple of PRs I've seen haven't been automatically labeled.  Wondering if there's something up with the labeler?

**Comment by ddbeck** [comment]
@vinyldarkscratch The most recent open PRs have been labeled. Can you link to at least one example of this problem?

**Comment by vinyldarkscratch** [comment]
Sure thing!  Looking back, apparently some of them are getting labeled, but here's one that I saw that wasn't: https://github.com/mdn/browser-compat-data/pull/5842

**Comment by ddbeck** [comment]
Glitch had some downtime earlier, which coincides with the time on that issue: https://status.glitch.com/incidents/40ttchslv5yg. I don't think there's anything for us to do about it, so I'm going to close this issue.

**Comment by vinyldarkscratch** [comment]
Ah okay, gotcha -- thanks for the quick response!

**Comment by vinyldarkscratch** [comment]
Hmm...just created two PRs and manually labeled the one right beforehand.  #5856, #5857, #5858.  🙁

**Comment by ddbeck** [comment]
It looks like Glitch is having some persistent problems: https://status.glitch.com/incidents/rsms0r0vykr7. I suggest we leave this issue open until Glitch's outage is announced as fixed, then check for an missed labels on PRs created during the outage period. I don't think this is critical enough to fuss with redeploying elsewhere.

**Comment by ddbeck** [comment]
Glitch has marked the outage as resolved and their uptime charts don't show any significant issues in the last few days. I'm going to close this issue. I'll also rename the issue ("Auto-labeler outage (Glitch downtime)") to make it easier to find should we ever need to revisit the uptime question again.
