### ISSUE TITLE
SharedWorker API information for "Chrome on Android" _seems_ to be incorrect...

### ISSUE THREAD

**Issue by AubreyHewes** [mdn/browser-compat-data#5850]
Hi, I figure this is the place to report this.. let me know if this should be reported elsewhere!

|Feature|Browser|Version|
|---|---|---|
|SharedWorker API|Chrome for Android|80.0.3987.132|

The [SharedWorker API](https://developer.mozilla.org/en-US/docs/Web/API/SharedWorker) information for "Chrome for Android" seems to be incorrect. The `window.SharedWorker` is `undefined` on "Chrome for Android" version `80.0.3987.132`

The [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/SharedWorker) says it should be supported but not which version...

(it works on (desktop) Chrome `80.0.3987.149`)

**Comment by vinyldarkscratch** [comment]
Hey @AubreyHewes, you've come to the right place!  I just confirmed support in desktop myself.  Curious, is just `window.SharedWorker` undefined, or is just plain `SharedWorker` undefined as well?

**Comment by AubreyHewes** [comment]
@vinyldarkscratch Nope, both are `undefined`

Test via https://md5pm.codesandbox.io/  ([source](https://codesandbox.io/s/brave-star-md5pm))

On Chrome for Android (v80.0.3987.132) 

````json
{
  "window.SharedWorker": "undefined", 
  "SharedWorker": "undefined",
  "navigator":"5.0 (Linux; Android 9; SM-A530F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.137 Mobile Safari/537.36"}
}
````

On desktop chrome (80.0.3987.149) 

````json
{
  "window.SharedWorker":"function SharedWorker() { [native code] }",
  "SharedWorker":"function SharedWorker() { [native code] }",
  "navigator":"5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36"}
}
````
