### ISSUE TITLE
Synchronize <menu> and HTMLMenuElement?

### ISSUE THREAD

**Issue by saschanaz** [mdn/browser-compat-data#5853]
Somehow [`<menu>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/menu) is marked as widely unsupported while [`HTMLMenuElement`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMenuElement) is marked as widely supported. Maybe should be synchronized?

**Comment by vinyldarkscratch** [comment]
Looks like this has been fixed in #11303!
