### ISSUE TITLE
Remove copyright notices from source files

### ISSUE THREAD

**Issue by ddbeck** [mdn/browser-compat-data#5879]
Some (but not all) of the project source files contain a notice [like this](https://github.com/mdn/browser-compat-data/blob/master/scripts/migrations/001-sort-features.js#L2):

```javascript
/* Any copyright is dedicated to the Public Domain.
 * http://creativecommons.org/publicdomain/zero/1.0/ */
```

I propose that we remove this comment from our source files. The main issue is that we can't consistently apply this notice to every source file. The bulk of BCD's source is in JSON files that do not permit comments. By inconsistently marking files with a copyright notice, I worry that we may create confusion about what terms apply. Similarly, we have a `LICENSE` file that the notice does not mention, further creating the possibility of confusion.

Also, I personally dislike the wording of the notice: the _work_ is dedicated to the public domain and, besides, CC0 is rather more broad (it dedicates a work to the public domain where possible and waives copy and other rights where it is not).

**Comment by jculver050** [comment]
Close
