### ISSUE TITLE
MS Edge changed their logo

### ISSUE THREAD

**Issue by VFDan** [mdn/browser-compat-data#5883]
Microsoft Edge has changed their logo (along with the engine change, #5214). It is now 
![image](https://user-images.githubusercontent.com/44413950/77587966-4e519600-6ebf-11ea-8cad-a1fc5087c6b3.png)

However, the MDN page hasn't updated.  It still shows 
![image](https://user-images.githubusercontent.com/44413950/77588076-835de880-6ebf-11ea-829d-9294fe5dc942.png)

**Comment by vinyldarkscratch** [comment]
Thanks for your report!  This is actually not the correct repository for this, however.  Please refer to https://github.com/mdn/kuma/issues/new/choose to create a new issue in the correct location!

**Comment by VFDan** [comment]
Ah thanks, I thought it was the correct repository because the logo is in the compatibility table.
