### ISSUE TITLE
Add browser release data for all browsers

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#591]
I've added a JSON file that contains browsers and their releases (with a release version, release date, and release notes link). This data is also used for validation of `version_added` and `version_removed` in the compat data itself. However, the initial PR did not include all browsers and their release data. This issue is about adding this for all browsers.

To-do list:

- [x] chrome
- [x] chrome_android
- [x] webview_android
- [x] edge
- [x] edge_mobile
- [x] firefox
- [x] firefox_android
- [x] ie
- [x] nodejs (see https://github.com/mdn/browser-compat-data/pull/596)
- [x] opera
- [x] opera_android
- [x] safari (see https://github.com/mdn/browser-compat-data/pull/595)
- [x] safari_ios (see https://github.com/mdn/browser-compat-data/pull/831)
- [x] samsunginternet_android

Each browser has a file with this data added at https://github.com/mdn/browser-compat-data/blob/master/browsers/

**Comment by richardkmichael** [comment]
@Elchi3 I'm looking to help and wonder: is Wikipedia an acceptable source for this information? For example, regarding `chrome-android`, `Android` is indicated on releases in the Wikipedia version history -- can that data be wrangled into the required JSON format here?

**Comment by Elchi3** [comment]
@richardkmichael Yeah, Wikipedia might be a good start. Ideally, we would get this information directly from the vendors (or their websites), though. 

Maybe @jpmedley can help us to get this data for browsers of the Chrome or Android family.

**Comment by jpmedley** [comment]
For Android and Webview, just copy the Chrome file. They're identical. I suspect opera_android is identical to Opera, but I don't know enough about their release process.

**Comment by jpmedley** [comment]
I should have said parallel instead of identical. All three flavors of Chrome share a version number, but the release dates don't always match;.

**Comment by ExE-Boss** [comment]
I have #1712 open to add information about Opera for Android.

**Comment by Elchi3** [comment]
This is now done. Phew! :tada:
