### ISSUE TITLE
Separate CSS combinators from selectors?

### ISSUE THREAD

**Issue by vinyldarkscratch** [mdn/browser-compat-data#5917]
In #5892, the MDN URLs have changed to refer to certain CSS selection features such as siblings (“a b”), children (“a > b”), and others as “combinators”.  This seems to follow a change within Level 4 of the Selectors spec.  I’m wondering if we should separate them into a separate `css/combinators/` folder?

**Comment by jculver050** [comment]
Close

**Comment by ddbeck** [comment]
(A spam notification caused me to notice this for the first time. Convenient?!)

The Selectors Level 4 spec appears to regard combinators as a component of a selector. For example, [in the definition complex selector](https://drafts.csswg.org/selectors-4/#complex):

>  A complex selector is a sequence of one or more compound selectors separated by combinators. It represents a set of simultaneous conditions on a set of elements in the particular relationships described by its combinators.

The combinators are also listed in [the spec's table of selectors](https://drafts.csswg.org/selectors-4/#overview).

Taken together, I don't think there's a formal reason to separate them at a high level. I also don't think we really add much by further subdividing `css.selectors` (and at the cost of a semver major release).

For all those reasons, I think we should stick with the current structure, unless and until there's consumer interest in changing it.
