### ISSUE TITLE
Drop NodeJS v8 support

### ISSUE THREAD

**Issue by vinyldarkscratch** [mdn/browser-compat-data#5931]
As of January 2020, [Node v8 is no longer in LTS](https://nodejs.org/en/about/releases/).  For our v1.0.13 release, we decided to [bump the minimum Node version to v10](#5806) -- however after user stories in #5852 explaining their inability to upgrade from Node v8 and the breaking nature of our changes, we reverted that change.  Now that many of our dependencies are dropping Node v8 support, it's the time for us to do so as well for a v2.0.0 release.

As suggested by @ddbeck (see https://github.com/mdn/browser-compat-data/pull/5930#issuecomment-607803416), our process should be the following:
1. In the first release of this process, post a note in the release notes stating the intent to drop Node v8 support
2. In the following release, emit a deprecation warning to users running Node v8
3. Perform one or more releases normally, leaving the deprecation warning
4. Require Node v10+, update our dependencies, and release v2.0.0

This whole process should take roughly a month from start to finish, which should give users enough time to upgrade their NodeJS (if they haven't done so already).

Dependencies we use that have already dropped NodeJS 8 support include the following:
- chalk
- ora
- prettier
- yargs

**Comment by Elchi3** [comment]
> In our next release (v1.0.16), post a note in the release notes stating the intent to drop Node v8 support

I haven't done that today and I think it doesn't hurt to think more about this and start the process at the earliest next week, or later on when we feel confident about it.

**Comment by vinyldarkscratch** [comment]
Sounds good!  I updated the issue to give a more general timeline.  😉

**Comment by ddbeck** [comment]
This has been fixed by #7155.
