### ISSUE TITLE
User reported HTML data issues in March 2020

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#5932]
Compat tables on MDN have a feedback button ("What are we missing?") where readers can report data issues. Here's what they have to say for HTML in March 2020. Note that these claims might not be true, but are probably worth checking.

Page | Affected browsers | What is wrong? | Feature | Do you have supporting material?
-- | -- | -- | -- | --
Web/HTML/Element/summary | Edge | The end of the explanation says see "Edge bug" and links to a Chromium bug. | display: list-item
Web/HTML/Element/input/datetime-local | Chrome | At our work, we are using it for a web development, and some workers saw the seconds and some dosen't. | type="datetime-local" |  
Web/HTML/Global_attributes/autocapitalize | Chrome, Edge, Firefox, Internet Explorer, Opera, Safari, Android webview, Chrome for Android, Firefox for Android, Opera for Android, Safari on iOS, Samsung Internet | Browser compatibility is not shown at all for the attribute 'autocapitalize' | autocapitalize | Browser compatibility for all browsers is set to "?"
Web/HTML/Preloading_content | Chrome | Chrome does not support this due to a bug preventing it to execute the preload command. This affects several "as" types, e.g. media, video and document. | preload↵Experimental | https://bugs.chromium.org/p/chromium/issues/detail?id=593267
Web/HTML/Global_attributes/spellcheck | Firefox | the example on this page does not work. | spellcheck | Firefox version 73.0.1
Web/HTML/Element/input/file | Internet Explorer | Browse Button coming Differently in Internet Explorer and cannot choose any files. | type="file" |  
Web/HTML/Global_attributes/title | Opera | compatability unknown | title | codepen
Web/HTML/Global_attributes/contenteditable | Safari, Safari on iOS | is supported in Safari | contenteditable="plaintext-only" Experimental |  
Web/HTML/Preloading_content | Firefox | It looks like the Firefox bug for version 57 & 58 has been resolved. | preload↵Experimental | Link: https://bugzilla.mozilla.org/show_bug.cgi?id=1405761
Web/HTML/Element/picture | Firefox | Seems not correct: Full Support since 38, but behind a flag from 32 - 52? | picture |  
Web/HTML/Element/input/tel | Chrome | The type="tel" input is NOT supported in Chrome, at least as of Chrome v80.* | type="tel" | https://www.w3schools.com/tags/att_input_type_tel.asp↵↵And opening this page in a Chrome browser on MacOS.
Web/HTML/Element/option | Firefox | Second note (*) is unclear. The sentence↵“For better Web compatibility (and for technical reasons), when Firefox is in multi-process mode and the <select> element is displayed as a drop-down list.”↵does not contain subject, only condition.↵Have a good day. | label |  
Web/HTML/Element/input/checkbox | Edge | Checked' attribute is Not working. i'm using Microsoft Edge 44.18362.449.0. My Chrome browser is fine. | type="checkbox" |  
Web/HTML/Element/form | Safari | Looks like Safari supports novalidate? Tested on macOS Safari 13.05. | novalidate |  
Web/HTML/Attributes/autocomplete | Chrome | autocomplete=off doesn't work | autocomplete | https://bugs.chromium.org/p/chromium/issues/detail?id=587466
Web/HTML/Element/details | Edge | Edge does *not* support details/summary. It is listed incorrectly. Thank you for reading my feedback. | details |  
Web/HTML/Global_attributes/inputmode | Firefox | Input type email, number etc is supported by Mozilla Firefox | inputmode |  
Web/HTML/Element/table | Chrome, Firefox, Internet Explorer, Chrome for Android, Firefox for Android | the cell spacing in making tables. | align |

**Comment by vinyldarkscratch** [comment]
Happy to say that everything's done for this now, and all PRs have been created! Rows that were not affected by PRs were invalid, whether incorrect data, not enough information, or outdated.  (Two of the rows were separated into an issue rather than a PR since I don't feel qualified to review them.)
