### ISSUE TITLE
User reported CSS data issues in March 2020

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#5933]
Compat tables on MDN have a feedback button ("What are we missing?") where readers can report data issues. Here's what they have to say for CSS in March 2020. Note that these claims might not be true, but are probably worth checking.

Page | Affected browsers | What is wrong? | Feature | Do you have supporting material?
-- | -- | -- | -- | --
Web/CSS/pointer-events | Internet Explorer | doesnot work in IE | pointer-events |  
Web/CSS/line-height | Chrome, Edge, Firefox | line-height not applied to select elements | line-height | https://bugs.chromium.org/p/chromium/issues/detail?id=1057638↵https://bugzilla.mozilla.org/show_bug.cgi?id=1619297↵↵https://jsbin.com/zeludideqi/1/edit?html,css,output
Web/CSS/font-family | Firefox | At least on fedora, system-ui is setting the typeface to cantarell. | system-ui |  
Web/CSS/animation-duration | Internet Explorer | Trying to change animation-duration using javascript as inline style was not working. The speed was same. | animation-duration | document.getElementById("scrollText").style.animationDuration = spanLength + "s";
Web/CSS/object-fit | Chrome | Error: Invalid CSS after " object-fit": expected ";", was ": cover;"↵on line 124 of standard input | object-fit |  
Web/CSS/width | Edge | min-intrinsic not working on edge and chrome | min-content |  
Web/CSS/:any-link | Samsung Internet | Some bug when using this property | :any-link |  
Web/CSS/ratio | Firefox | Single `<number>` values are not supported yet in Firefox. | Accepts <number> / <number> or single <number> as a value. | The feature got implemented in https://bugzil.la/1565562 but didn't get shipped yet (`layout.css.aspect-ratio-number.enabled` is `false` by default).↵↵I've created https://bugzil.la/1621090 now for letting the feature ride the trains.
Web/CSS/text-underline-position | Firefox | Firefox 74 now has support. | text-underline-position | https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/74
Web/CSS/text-underline-position | Firefox | i think firefox 74 supports this | text-underline-position | https://www.mozilla.org/en-US/firefox/74.0/releasenotes/
Web/CSS/text-underline-position | Chrome, Edge, Firefox, Internet Explorer, Opera, Safari, Android webview, Chrome for Android, Firefox for Android, Opera for Android, Safari on iOS, Samsung Internet | YES, I CAN PROVIDE A BRIEF EXPLANATION. | text-underline-position | YES.
Web/CSS/font-smooth | Chrome | Subpixel rendering was removed from MacOS in 2018.  This should be mentioned in the "WebKit implements a similar property" box. | font-smooth↵Non-standard |  
Web/CSS/:checked | Firefox | For select -> option elements doesn't work :-( | :checked |  
Web/CSS/text-underline-position | Firefox | It's now supported in Firefox 74 and according to Github, the data json was updated, but the changes seem not visible here. | text-underline-position | https://github.com/mdn/browser-compat-data/blob/4f0c7371a1b970e4c6012505e2fd5d9a716f41c8/css/properties/text-underline-position.json
Web/CSS/initial | Firefox | It shows FF19+ has full support to this property value, but FF1-24 support it only with vendor prefix. This is a contradiction for FF19-24. | initial |  
Web/CSS/text-emphasis-color | Chrome | I'm using Chrome Version 80.0.3987.132 (Official Build) (64-bit). It says that it does not support text-emphasis-color or text-emphasis-style. Inspecting the example on this page shows "Unknown property name" for the text-emphasis properties. | text-emphasis-color | Just view this page in Chrome.Where it says "This has emphasis marks", it just looks like regular italic text in Chrome.
Web/CSS/scroll-margin | Safari | scroll-margin is not supported by latest Safari (13.0.5) | scroll-margin |  
Web/CSS/::placeholder | Internet Explorer | maybe ie 11 supports this, because i see my placeholder text in this version | ::placeholder |  
Web/CSS/font-kerning | Chrome | Works in chrome (edge, opera) without the prefix↵Only safari needs the prefix. | font-kerning | https://caniuse.com/#search=font-kerning
Web/CSS/color-adjust | Chrome, Safari | It's not just the -webkit- prefix that we need to add to make it work in chrome and safari, we actually need a different property, which is called "-webkit-print-color-adjust". Notice the extra word `print`. | color-adjust | https://stackoverflow.com/a/51147616/670839
Web/CSS/@font-face/font-display | Chrome | some issue run javascript | font-display | [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: https://fonts.gstatic.com/s/karla/v13/qkBbXvYC6trAT7RVLtw.woff2↵index.html:1 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: https://use.fontawesome.com/releases/v5.12.1/webfonts/fa-regular-400.woff2↵index.html:1 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/fonts/fontawesome-webfont.woff2?v=4.7.0↵index.html:1 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: https://use.fontawesome.com/releases/v5.12.1/webfonts/fa-solid-900.woff2
Web/CSS/min-width | Internet Explorer | IE11 does not support min-width:initial, because IE11 does not support initial at all. I understand you don't want to repeat this at every property, but a hint somewhere (e.g. a * when you suggest min-width:initial) would be nice. | min-width | https://developer.mozilla.org/en-US/docs/Web/CSS/initial↵https://developer.mozilla.org/en-US/docs/Web/CSS/min-width#Syntax
Web/CSS/counters | Chrome | ::marker↵doesn't support in last Chrome Version 80.0.3987.149 (Official Build) (64-bit) | counters() |  
Web/CSS/position | Chrome, Chrome for Android | i need to enable the flag webplatform in chromium to use it. | sticky |  
Web/CSS/scrollbar-width | Firefox | Firefox doesn't accept length values.↵↵Tested on Firefox 74 on win10 :↵Used scrollbar-width: 0.1875rem; | scrollbar-width |  
Web/CSS/:focus-within | Chrome | 52↵⇥No support | :focus-within | F
Web/CSS/:focus-within | Firefox | Firefox , Safari , | :focus-within | Firefox
Web/CSS/content | Firefox | Setting an alt text for the image on Firefox make the property value invalid.↵Example:↵content: url('https://mozorg.cdn.mozilla.net/media/img/favicon.ico') / 'alt text'; | Element replacement |  
Web/CSS/@supports | Chrome, Edge | @supports selector() works/ships in ↵Chrome/82+ Canary↵Edg/81 Dev | selector() | Tested in both browsers↵@supports selector(:is(a,b)) and selector(p > em) {↵⇥b {color:rebeccapurple}↵}↵↵https://caniuse.com/#feat=mdn-css_at-rules_supports_selector↵only reports Chrome 82 not Edgium↵↵HTML file with style to test:↵https://gist.github.com/WebMechanic/a75071e67d952f49a17c60b3216b23bb
Web/CSS/scroll-snap-stop | Chrome, Firefox | scroll-snap-stop:always does not work in chrome but does work on firefox | scroll-snap-stop |  
Web/CSS/::part | Safari | Is now supported. | ::part |  
Web/CSS/display | Internet Explorer | Weired dot notation of property: 'display-outside.run-in'.↵Should this be `<display-outside> run-in`, `display-outside: run-in` or just `run-in`? | display-outside.run-in↵Experimental |  
Web/CSS/width | Edge | min content does not work with microsoft edge, the property underlined in red when I inspect the element | min-content |  
Web/CSS/::part | Safari, Safari on iOS | Safari 13.1 (released in iOS 13.4 + MacOS 10.15.4) both now support CSS Shadow Parts. | ::part | https://developer.apple.com/documentation/safari_release_notes/safari_13_1_beta_release_notes↵↵https://codepen.io/web-padawan/pen/PowOjYq
Web/CSS/border-top | Safari, Safari on iOS | border-top-style: dotted; is not workin properly, the dots are turned into squares | border-top |

**Comment by vinyldarkscratch** [comment]
Happy to say that everything's done for this now, and all PRs have been created!  Rows that were not affected by PRs were invalid, whether incorrect data, not enough information, or outdated.
