### ISSUE TITLE
User reported JavaScript data issues in March 2020

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#5934]
Compat tables on MDN have a feedback button ("What are we missing?") where readers can report data issues. Here's what they have to say for JavaScript in March 2020. Note that these claims might not be true, but are probably worth checking.

Page | Affected browsers | What is wrong? | Feature | Do you have supporting material?
-- | -- | -- | -- | --
Web/JavaScript/Reference/Statements/async_function | Safari on iOS | https://caniuse.com/#feat=async-functions lists Safari on iOS support starting at v11. Not sure who is right. | async function | https://caniuse.com/#feat=async-functions
Web/JavaScript/Reference/Global_Objects/String/toUpperCase | Node.js | Doesn't seem to work | toUpperCase |  
Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer/SharedArrayBuffer | Node.js | Node.js currently supports the SharedArrayBuffer constructor. It appears to have been officially supported since v9.11.2. I have tested it on the latest LTS version (v12.16.1), and it works fine. | SharedArrayBuffer() constructor | Please see:↵https://node.green/#ES2017-features-shared-memory-and-atomics
Web/JavaScript/Reference/Global_Objects/Date/toLocaleString | Firefox for Android | seems to work on Firefox for Android 68.5.0 | toLocaleString | open on Firefox for Android https://jsbin.com/kilaratico/
Web/JavaScript/Reference/Global_Objects/NumberFormat/formatToParts | Internet Explorer | Not supported | formatToParts↵Experimental |  
Web/JavaScript/Reference/Global_Objects/Date/UTC | Safari | Safari (11.1.2) returns NaN on e.g.↵↵   Date.UTC(70, 0, 1, 0, 0, 0, 1583776800000) | UTC |  
Web/JavaScript/Reference/Classes | Firefox | Status is fixed now | Static class fields | https://bugzilla.mozilla.org/show_bug.cgi?id=1535804
Web/JavaScript/Reference/Operators/Destructuring_assignment | Safari | This is supported in Safari now. | Rest in arrays | var [a, ...rest] = [1,2,3]; console.log(rest);↵↵in Safari's web inspector.
Web/JavaScript/Reference/Global_Objects/String/localeCompare | Android webview | It now works | options | bar.localeCompare.toString() -> gives "function localeCompare() { [native code] }" so its not a polyfill↵↵"bar".localeCompare("Bar" ) -> gives 1, so default is case sensitive↵↵"bar".localeCompare("Bar", 'en', {sensitivity: 'base'} ) -> gives 0, so the options are being used
Web/JavaScript/Reference/Global_Objects/Promise/allSettled | Edge, Safari on iOS | Message from browser: Object doesn't support property or method 'allSettled' at processPromises | allSettled() |  
Web/JavaScript/Reference/Functions/Arrow_functions | Safari | Arrow function for example iframe.onload = => () {↵        this.ngZone.run(() => {↵})↵} on safari 12.1.1 version doesn't work well. | Arrow functions |  
Web/JavaScript/Reference/Global_Objects/Array/forEach | Internet Explorer | All the examples show forEach() with the use of arrow functions. IE support as listed does support forEach but not with arrow functions which maybe unclear and easily missed. | forEach |  
Web/JavaScript/Reference/Trailing_commas | Safari, Safari on iOS | It seems as though trailing commas in functions are actually supported in Safari. We recently added them all over our Javascript bundle, and when I checked the site in Safari 13.0.4, didn't see the kind of catastrophic failures that I'd expect if something like this was actually broken. ↵↵I was able to see support added in the release notes for Safari Technology Preview release 7 (link included below), but I'm not sure exactly which version of consumer Safari that equates to.↵↵Here's the Safari TP release notes: https://developer.apple.com/safari/technology-preview/release-notes/#r7↵↵Here's a pen demoing all the test cases I could immediately think of trailing commas in functions: https://codepen.io/alex-cs/pen/wvammQr?editors=0010↵Everything worked as expected for me in Safari 13 | Trailing comma in functions | Here's the Safari TP release notes: https://developer.apple.com/safari/technology-preview/release-notes/#r7↵↵Here's a pen demoing all the test cases I could immediately think of trailing commas in functions: https://codepen.io/alex-cs/pen/wvammQr?editors=0010↵Everything worked as expected for me in Safari 13
Web/JavaScript/Reference/Global_Objects/Promise/reject | Internet Explorer | IE11 should provide Promise.reject (tested on BrowserStack) | reject() | the prototype Promise.reject is not equal to undefined
Web/JavaScript/Reference/Global_Objects/Object/assign | Internet Explorer | Looks like it is supported on new IE | assign |  
Web/JavaScript/Reference/Global_Objects/Array/forEach | Internet Explorer | forEach it's not supported by IE in any version. | forEach | https://caniuse.com/#search=forEach
Web/JavaScript/Reference/Global_Objects/NumberFormat/formatToParts | Internet Explorer | Its not suppoerted by IE11! | formatToParts↵Experimental |  
Web/JavaScript/Reference/Global_Objects/NumberFormat/formatToParts | Internet Explorer | FormatToParts errors out on internet explorer 11 | formatToParts↵Experimental |  
Web/JavaScript/Reference/Statements/let | Edge | The Older Edge version is a partial (i.e. not missing) implementation. | let |  
Web/JavaScript/Reference/Global_Objects/String/matchAll | Safari, Safari on iOS | The matchAll demo on this page works on iOS Mobile Safari. This docs page states otherwise. | matchAll |  
Web/JavaScript/Reference/Operators/Destructuring_assignment | Safari | const test = [1, 2, 3, 4];↵const [a, b, ...rest] = test;↵console.log(rest);↵// Output: [3, 4] (2) | Destructuring assignment | https://codepen.io/wsedlacek/pen/dyoQYQJ?editors=0012
Web/JavaScript/Reference/Global_Objects/NumberFormat/formatToParts | Internet Explorer | This method doesn't work in IE11↵Intl.NumberFormat('us-US').formatToParts(100000000)↵Object doesn't support property or method 'formatToParts' | formatToParts↵Experimental | IE Version 11.1098.17763.0
Web/JavaScript/Reference/Template_literals | Chrome, Edge, Firefox, Internet Explorer, Opera, Safari, Android webview, Chrome for Android, Firefox for Android, Opera for Android, Safari on iOS, Samsung Internet, Node.js | This table is very useful to know if support is present now, but also to know if the support is recent or has been around longer. For that I'd have to look up release dates for all the browser versions. That's a lot of work, which could be avoided by putting the release date (or at least the year) in the table (for example as mouseover text). | Template literals |  
Web/JavaScript/Reference/Global_Objects/Float64Array | Internet Explorer | I'm getting an "Object doesn't support property or method 'from'" in IE 11 for Float64Array.from | Float64Array |  
Web/JavaScript/Reference/Global_Objects/BigInt | Edge | I'm currently working on a project that requires use if BitInt, Microsoft Edge not only doesn't recognize the n value but also keeps asking for a value for BigInt even when I specify one. It doesn't recognize it. | BigInt 
Web/JavaScript/Reference/Operators/Nullish_coalescing_operator | Safari | Safari supports Nullish coalescing operator (??) | Nullish coalescing operator (??) |  
Web/JavaScript/Reference/Global_Objects/Array/forEach | Internet Explorer | IE does not appear to support the => syntax. | forEach | In dev console:↵var arr = ["a", "b", "c", ["d", "e", "f"]]↵arr.forEach(el => console.log(el));↵↵This results in "Syntax error"
Web/JavaScript/Reference/Statements/break | Chrome | i'm using https://www.khanacademy.org/ on chrome and the "break" dose not work | break |  
Web/JavaScript/Reference/Operators/Optional_chaining | Safari, Safari on iOS | Safari has this feature as of iOS 13.4 and Safari 13.1 on macOS. | Optional chaining operator (?.) | https://jsbin.com/kiqizix/edit?js,console
Web/JavaScript/Reference/Global_Objects/Object/assign | Internet Explorer | On Internet Explorer v11.1365.17134.0↵I tried the Demo code and worked like charm.↵↵Ps: I'm not sure if it matters but it was inside an Angular 9 project using Angular CLI with polyfills:↵import 'core-js/features/array';↵import 'zone.js/dist/zone'; | assign |

**Comment by vinyldarkscratch** [comment]
Happy to say that everything's done for this now, and all PRs have been created! Rows that were not affected by PRs were invalid, whether incorrect data, not enough information, or outdated. (One of the rows was separated into an issue rather than a PR since I don't feel qualified to review them, however it was closed since it's just a subset of this issue...)

**Comment by sideshowbarker** [comment]
https://trac.webkit.org/browser/webkit/trunk/Source/JavaScriptCore/features.json?format=txt is useful resource for identifying JavaScript feature support in WebKit. It unfortunately doesn’t document which WebKit version a particular feature went into — but looking at the revision log for it at https://trac.webkit.org/log/webkit/trunk/Source/JavaScriptCore/features.json can help.

Also unfortunately, since it’s not been updated in more than year, it’s not useful at this point for any features that may have gotten added after January 2019.

**Comment by vinyldarkscratch** [comment]
And now that we’ve gotten through all of them, I’d say it’s now safe to close this issue!  (Happy to provide a table containing data on which were ignored and why.)

**Comment by Elchi3** [comment]
How was it to work on these issues? If I would file new user reported issues for April, is there anything you'd like me to do differently?

**Comment by vinyldarkscratch** [comment]
Hmmm...honestly, I think the way the data was represented worked well!  I was able to copy-paste into Numbers and keep track of all the entries easily.  (Really the only thing was the new line characters got in the way a few times, so probably use spaces instead, but that’s super minor.)
