### ISSUE TITLE
/en-US/docs/Web/API/Navigator/maxTouchPoints

### ISSUE THREAD

**Issue by mgoszcz2** [mdn/browser-compat-data#5954]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
It seems that since at least iOS 13 and macOS 10.15 (Catalina), Navigator.maxTouchPoints is [supported](https://trac.webkit.org/changeset/246070/webkit/) on Apple devices. I tested it with both.

**Comment by jculver050** [comment]
Close

**Comment by vinyldarkscratch** [comment]
Looks like this was fixed in #6588!
