### ISSUE TITLE
WebVR is removed in Chrome 80

### ISSUE THREAD

**Issue by a2sheppy** [mdn/browser-compat-data#5966]
Update all the WebVR data to add a `version_removed` of `"80"` for Chrome and other Chromium-based browsers.

See https://bugs.chromium.org/p/chromium/issues/detail?id=960132 for the Chrome bug under which these changes were made.

**Comment by jpmedley** [comment]
It looks like this has already been done.

**Comment by ddbeck** [comment]
This is largely complete by #5678 satisfied this. There are a few features that seem like they might still show support WebVR:

* `VRStageParameters`
* `api.Window.onvrdisplaypresentchange`
* `api.Gamepad.displayId`
