### ISSUE TITLE
Idea: Add test to check that every browser is listed in every "support" record

### ISSUE THREAD

**Issue by a2sheppy** [mdn/browser-compat-data#5973]
While the scenario in which a missing browser does *sort of* get caught now, it's caught by a fatal error occurring due to attempting to look up a version record using a non-existent keyword, and the resulting output is difficult to navigate and diagnose.

We should add a simple test that just goes through each record and reports specifically which if any browsers aren't included in that record. With even halfway decent output, this would save a ton of time.

**Comment by vinyldarkscratch** [comment]
We actually already have a test file for this.  See https://github.com/mdn/browser-compat-data/blob/master/test/linter/test-browsers.js

**Comment by LuckyLuv** [comment]
[#chrome-extentions://microsoft.skydrive.atlslscsrv.app/at last security services-laura's secure web browser](https://www.google.com/search?newwindow=1&safe=active&authuser=1&bih=675&biw=964&hl=en&tbm=nws&sxsrf=ALeKk01ydzpYUy3x9G8hbeAjxsgaeRFuWw%3A1586730931163&ei=s5eTXpy5CazH_Qabv5bgDg&q=AT+Last+Security+Services+-Laura%27s+Secure+Web+Browser%2C+89th+Avenue+North%2C+St.+Petersburg%2C+FL&oq=AT+Last+Security+Services+-Laura%27s+Secure+Web+Browser%2C+89th+Avenue+North%2C+St.+Petersburg%2C+FL&gs_l=psy-ab.12...3002.3002.0.6615.1.1.0.0.0.0.96.96.1.1.0....0...1c.1.64.psy-ab..0.0.0....0.NPZ81x3408s) 
![b1ed702b-42d7-4f1c-9165-61956301ec93_LLVSitePic](https://user-images.githubusercontent.com/47076136/79083017-716ea900-7cf9-11ea-8f4b-00ef2d6d8886.jpg)

**Comment by ddbeck** [comment]
> While the scenario in which a missing browser does sort of get caught now, it's caught by a fatal error occurring due to attempting to look up a version record using a non-existent keyword, and the resulting output is difficult to navigate and diagnose.

Can you provide some sample source where you've seen this happen? We ought to guard against incomplete compat statements (as the linked `test-browsers.js` file ought to be doing). But if we're getting cryptic errors that suggests something is broken or incomplete.

**Comment by queengooborg** [comment]
I'm going to close this since there hasn't been any response and it doesn't seem like this issue has been experienced again.  Always happy to reopen if this is still an issue though!
