### ISSUE TITLE
CSS minmax() on Internet Explorer 11

### ISSUE THREAD

**Issue by supersimplenet** [mdn/browser-compat-data#5982]
It does work, apart from `auto` value, on Internet Explorer 11: https://jsfiddle.net/z2gf75ry/

More info:
* [CSS Grid in IE: Debunking Common IE Grid Misconceptions](https://css-tricks.com/css-grid-in-ie-debunking-common-ie-grid-misconceptions/#article-header-id-2)
* [About: CSS Grid for IE11
](https://gist.github.com/pagelab/23455c37347696c8cdf28eecacb0a7e2#user-content-about-css-grid-for-ie11)

**Comment by queengooborg** [comment]
I'm closing this issue as we are no longer maintaining the Internet Explorer; see the [applicable discussion](https://github.com/orgs/mdn/discussions/202) for more details.
