### ISSUE TITLE
include JavaScriptCore in compatibility table

### ISSUE THREAD

**Issue by vujevits** [mdn/browser-compat-data#6000]
Although [JavaScriptCore](https://developer.apple.com/documentation/javascriptcore) is not a browser, but it's an increasing target platform thanks to `react-native`. There are quite a few differences regarding compatibility, so it would be very useful for the developer community.

**Comment by vinyldarkscratch** [comment]
Just out of curiosity, is there any reason to have JavaScriptCore data separate from Safari?

**Comment by sideshowbarker** [comment]
> Just out of curiosity, is there any reason to have JavaScriptCore data separate from Safari's data?

I guess for a reason similar to that we already use for having WebView separate from Chrome?

For the record here: It seems part of what adds some confusion around this is that Apple uses the name "JavaScriptCore" for two different things: both for the JavaScript engine that runs inside Safari, and also for a completely separate framework built on top of that JavaScript engine (to let people developing Apple apps in Swift and Objective-C to run JavaScript code in their apps).

The JavaScriptCore framework doesn’t seem to be released/versioned based on Safari releases.

How it *is* versioned instead doesn’t seem to be clear, though — I mean, whether it’s released/versioned along with macOS (and iOS releases), or maybe along with XCode releases (if that makes any sense; I dunno, I’m not a macOS/iOS developer…), or what.

**Comment by ddbeck** [comment]
This strikes me as one of those things we can't act on without help from the people at Apple. If we were to add JavaScriptCore, we'd need reviewers from Apple that could give some definitive answers on versioning questions. Otherwise, the quality of such data would be rather low, or have very poor coverage. I'm not suggesting we close this issue, but I'd regard it as blocked without participation from Apple.

**Comment by jpmedley** [comment]
Aside from its use in react native, this seems analogous to V8, which is used in Node and Chromium forks. BCD has entries for those, but not for V8 as a separate entity.

**Comment by vinyldarkscratch** [comment]
I did some more research into React Native as a part of a personal project I've been working on.  In its [docs](https://reactnative.dev/docs/javascript-environment), it mentions the following:

> When using React Native, you're going to be running your JavaScript code in two environments:
> - In most cases, React Native will use JavaScriptCore, the JavaScript engine that powers Safari. Note that on iOS, JavaScriptCore does not use JIT due to the absence of writable executable memory in iOS apps.
> - When using Chrome debugging, all JavaScript code runs within Chrome itself, communicating with native code via WebSockets. Chrome uses V8 as its JavaScript engine.

Considering that Safari is integrated so deeply into the OS, I'm betting that React uses the same JavaScriptCore version as Safari itself, which is based upon the iOS editions.  As such, we wouldn't need JavaScriptCore as a separate entity.

**Comment by queengooborg** [comment]
Since there hasn't been any further discussion on this issue and the Safari iOS data seems to suffice for the most part, I'm going to go ahead and close this issue.  There's not much difference between JSC and Safari iOS, and I feel that if there are any differences, we'd document them in notes.

**Comment by LinusU** [comment]
> [...] and I feel that if there are any differences, we'd document them in notes.

`TextEncoder` isn't supported in React Native, even though Safari and Chrome supports it. Could this be added as a note?

ref: https://github.com/hapijs/joi/issues/2141, https://stackoverflow.com/q/55868484/148072, https://snack.expo.dev/@linusu/text-encoder-test
