### ISSUE TITLE
Update Intl.RelativeTimeFormat Edge support

### ISSUE THREAD

**Issue by benmccann** [mdn/browser-compat-data#6006]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RelativeTimeFormat says it works in Chrome and not Edge. But isn't Edge based off Chromium now? Apologies, I don't have a Windows machine to test with myself

**Comment by Elchi3** [comment]
Hey, thanks for your issue! I think you're right! Probably missed this in our mass-update as I added this specific data just add the time when we were mass updating for the new Edge on Chromium.
If you like, open a PR and change this!
