### ISSUE TITLE
vector-effect/non-scaling-stroke

### ISSUE THREAD

**Issue by strarsis** [mdn/browser-compat-data#6022]
The `vector-effect: non-scaling-stroke` property-value combination is very useful for scalable custom borders in CSS. A plain SVG as background or `border-image` scales also its border-widths. 
I found this useful Codepen for testing: https://codepen.io/ZachSaucier/pen/ONGJab

It works in Chrome, Firefox (Normal + Dev), but not in Edge.

**Comment by strarsis** [comment]
It seems to work in recent Edge now (2021).

**Comment by jculver050** [comment]
Close

**Comment by lPadier** [comment]
This data was added to caniuse: 
https://github.com/Fyrd/caniuse/commit/ba6b94f516887306e90eb4bf5519eee425f99522#diff-35b794599927a40af0a2078a4031a9cbbad09e5b1c9faa2d1f8a5576186b6a5d
https://caniuse.com/vector-effect

Added to firefox 15: https://website-archive.mozilla.org/www.mozilla.org/firefox_releasenotes/en-us/firefox/15.0/releasenotes/buglist

For other browsers, I'm not sure where the info comes from in caniuse, maybe the author of that commit knows more
