### ISSUE TITLE
FontLoading API supported in Edge >= 79

### ISSUE THREAD

**Issue by Dangoo** [mdn/browser-compat-data#6041]
MDN states compatibility for FontLoading API for Edge as `<= 79` which in fact is not true since Chromium (now Edges underlying engine) supports that API since `35`:
https://chromestatus.com/feature/6244676289953792

The change was introduced here:
https://github.com/mdn/browser-compat-data/blob/62ef5901a48ecefb4072ebd17450b6cf918d592e/api/FontFace.json#L14

In fact it should have been `≥`

https://caniuse.com/#feat=font-loading

Should I open a PR?

**Comment by Elchi3** [comment]
Thanks for your issue!

"≤79" means it's supported in version 79 (first version of Edge that uses Chromium) or in earlier versions of Edge (12-18). So, if the FontLoading API wasn't in the old Edge, we can update "≤79"  to "79" and a PR would be very much welcome! :+1:
