### ISSUE TITLE
New features in Intl.NumberFormat

### ISSUE THREAD

**Issue by stof** [mdn/browser-compat-data#6046]
https://v8.dev/features/intl-numberformat describes a set of new features for Intl.NumberFormat, which are supported in Chrome. It would be great to have data for them in BCD (and so MDM)

**Comment by Elchi3** [comment]
I think they haven been all added: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat#Browser_compatibility

**Comment by stof** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat#Syntax still lists more options than what the table shows

**Comment by stof** [comment]
but there is nothing in that page which indicators which options are part of the basic support, which makes things confusing for users not already knowing it.

**Comment by Elchi3** [comment]
ok, reopening.
