### ISSUE TITLE
Add data for Chrome 84, Chrome for Android 84

### ISSUE THREAD

**Issue by lpd-au** [mdn/browser-compat-data#6056]
https://chromestatus.com/features#milestone%3D84

**Comment by vinyldarkscratch** [comment]
Pinging @jpmedley for this one, considering Chrome's recent schedule irregularity!

**Comment by jpmedley** [comment]
I have no information at this time. I don't mean I have no information I can share. I mean I have no information.

**Comment by vinyldarkscratch** [comment]
No problem!  We’ll revisit this issue later then.  😉

**Comment by lpd-au** [comment]
Is this accurate? https://chromiumdash.appspot.com/schedule

**Comment by vinyldarkscratch** [comment]
Joe has asked to review all updates to the Chrome releases during this time.  Chrome 82 was skipped due to the COVID19 pandemic, and additional version skips may happen as well.

**Comment by jpmedley** [comment]
That link is accurate. I didn't even know it was public until this morning. I think it's only recently been made so.

I hearby retract by request to review, but I'm always available for sanity check. Feel free to ping me whenever.
