### ISSUE TITLE
setPointerCapture and releasePointerCapture are supported on Safari desktop and iOS

### ISSUE THREAD

**Issue by dbismut** [mdn/browser-compat-data#6062]
Related entry: https://developer.mozilla.org/en-US/docs/Web/API/Element/setPointerCapture

iOS Safari 13.4.1 and Safari Desktop 13.1 do seem to support `setPointerCapture` and `releasePointerCapture`.

Codesandbox: https://codesandbox.io/s/musing-cherry-d84qr

**Comment by aghasyedbilal** [comment]
https://github.com/mdn/browser-compat-data/issues/6062#issue-610833999
