### ISSUE TITLE
Styling WEBVTT is not supported on chrome on macos

### ISSUE THREAD

**Issue by caeser1996** [mdn/browser-compat-data#6063]
`<style type="text/css" class="vttStyles">::cue { background-color:rgba(0,0,0,0.1) !important;color:#b1a5a5 !important;text-align:center !important;font-family:Arial !important;font-name:Arial.ttf !important;font-size:16 !important;font-weight:normal !important;font-style:normal !important;background-alpha:255 !important; }</style>`

Above is the sample code the same code is working pretty fine in ubuntu and windows but for same browser (version ) on mac os it's not working.

**Comment by vinyldarkscratch** [comment]
Sorry it's taken so long to reply to this issue.  Can you inform us what browser (and versions if applicable) you're using?

**Comment by queengooborg** [comment]
I'm closing this issue since there hasn't been any response and there's not enough actionable information.  If this is still an issue, please feel free to reopen it and add a comment with the requested information!
