### ISSUE TITLE
font-variant-caps works in Safari and iOS Safari

### ISSUE THREAD

**Issue by ryanditjia** [mdn/browser-compat-data#6070]
[Data ref](https://github.com/mdn/browser-compat-data/blob/master/css/properties/font-variant-caps.json)
`font-variant-caps: small-caps` and `font-variant-caps: all-small-caps` work on my:

- Safari (macOS 10.15.4)
- iOS Safari (13.4.1)

And I seem to remember it working from even earlier versions.

**Comment by ddbeck** [comment]
Fixed by #9789. 🎉
