### ISSUE TITLE
Add Samsung Internet

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#608]
We want to add the Samsung Internet Android browser to the data. 

To add a new browser we need to:
1) Agree on a [browser identifier](https://github.com/mdn/browser-compat-data/blob/master/compat-data-schema.md#browser-identifiers)

I guess this could be "`samsung_internet`" or "`samsung_internet_android`" (although that seems a bit long). Browser identifiers try to have the form of "browsername_platform". This identfier is used everywhere in the data then. See the [CSS background property](https://github.com/mdn/browser-compat-data/blob/master/css/properties/background.json) for an example data set and the other browser identifiers.

2) Add browser release info to [browsers.json](https://github.com/mdn/browser-compat-data/blob/master/browsers/browsers.json)

Here, we need to expand the JSON with all the releases that Samsung Internet had so far. The `release_notes` property is optional, but would be nice to have. Status is one of these "retired", "current", "beta", "nightly", "esr", "planned".

```
 "samsung_internet": {
    "releases": {

    ...   

     "5.4": {
        "release_date": "2017-05-17",
        "release_notes: "https://medium.com/samsung-internet-dev/announcing-samsung-internet-v5-4-stable-fd941e0dcd58",
        "status": "retired"
      },
      "6.2": {
        "release_date": "2017-10-30",
        "release_notes: "https://medium.com/samsung-internet-dev/samsung-internet-v6-2-now-stable-ab7f95ed8b4b"
        "status": "current"
      }
  }
}
```

3) The browser identifier needs to be added to the docs and the schema files
- https://github.com/mdn/browser-compat-data/blob/master/compat-data-schema.md#browser-identifiers
- https://github.com/mdn/browser-compat-data/blob/master/browsers/browsers.schema.json#L34
- https://github.com/mdn/browser-compat-data/blob/master/compat-data.schema.json#L68

**Comment by poshaughnessy** [comment]
Hi @Elchi3.

Thanks again for kicking this off.

1. The presedent so far is [browser name / short name]_[platform], so how about we go with `samsunginternet_android`? I don't think there's a very good way to shorten "Samsung Internet". I think we should keep the platform given we already have Samsung Internet for DeX and who knows what else might happen in the future.

2. `browsers.json`: Looks simple enough, I'll check with my colleagues to try to firm up our data on the older versions. I'll start to prepare a PR for this and for the following...

3. Please may I check:
* `compat-data-scheme.md`: Just a 1 line addition here?
* `browsers.schema.json`: Just a 1 line addition here? What does `browser_statement` refer to?
* `compat-data.schema.json`: Just a 1 line addition to this actual file? Then actually adding the support info to all the individual APIs and features? Will we need to add Samsung Internet to all of them upfront, or can we get Samsung Internet in place and add it to more of the features as we go, over time?

Thanks!

**Comment by Elchi3** [comment]
Hi @poshaughnessy,

sorry for the late reply, I was on vacation.

1. `samsunginternet_android` sounds good to me, lets go with that.
2.  Awesome!
3.  * `compat-data-scheme.md`: Yes, just the 1 liner.
     * `browsers.schema.json`: Also, just the 1 liner and `browser_statement` just refers to the object containing the browser releases (which has to have the "releases" property).
     * `compat-data.schema.json`: Again just a 1 line addition.

> Then actually adding the support info to all the individual APIs and features? Will we need to add Samsung Internet to all of them upfront, or can we get Samsung Internet in place and add it to more of the features as we go, over time

You can add `samsunginternet_android`as you go. No need to add it to all features upfront. If `samsunginternet_android` has not been added to a feature's compat data, it will display a question mark (?) on the MDN pages, like it does for Opera Android on this page, for example: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Collator/resolvedOptions#Browser_compatibility
