### ISSUE TITLE
Fix SourceBuffer.audioTracks/videoTracks/textTracks support version number 

### ISSUE THREAD

**Issue by saschanaz** [mdn/browser-compat-data#6102]
From https://github.com/mdn/browser-compat-data/issues/5781#issuecomment-599274380:

>* Chrome added flagged support for audioTracks/videoTracks in [March 2016](https://chromium.googlesource.com/chromium/src/+/92333c0e5ca6b7768e5bcf6d41ff8fc733ebbfc1), but no textTracks 
>* Safari added support for all of them in [January 2015](https://trac.webkit.org/changeset/178172/webkit)

So the Chrome version number should be at least 49 instead of current 23 and the Safari one should be at least 11 instead of current 8.

**Comment by SnyderTheOne** [comment]
On https://developer.mozilla.org/en-US/docs/Web/API/SourceBuffer, 'Firefox for Android' lists `SourceBuffer` as an unsupported feature, even though this seems to be implemented. Support for MSE is listed correctly on https://developer.mozilla.org/en-US/docs/Web/API/Media_Source_Extensions_API.

**Comment by jculver050** [comment]
Close

**Comment by saschanaz** [comment]
Fixed by #6644, #6655, etc.
