### ISSUE TITLE
Missing types in link types compat table

### ISSUE THREAD

**Issue by AdriVanHoudt** [mdn/browser-compat-data#6104]
I notices that not all link types are represented in the compat table.
The `what are we missing` button doesn't allow me to report missing reports, so hence this issue.

Things that are missing are for example `noopener`. (ref can I use link https://caniuse.com/#feat=rel-noopener)

If there is a process to add these I don't mind looking at it, but not quite sure where to start or if there is a reason it is missing.

**Comment by jculver050** [comment]
Close

**Comment by jculver050** [comment]
Close

**Comment by AdriVanHoudt** [comment]
Even I barely remember this issue but thanks for fixing!!
