### ISSUE TITLE
Blob.arrayBuffer works in Android Firefox 75 Beta

### ISSUE THREAD

**Issue by chrbsg** [mdn/browser-compat-data#6108]
https://developer.mozilla.org/en-US/docs/Web/API/Blob/arrayBuffer has "no" for "Firefox for Android". Not sure when support was introduced, but it works in Android Beta (FF75).

**Comment by vinyldarkscratch** [comment]
Currently, we're not tracking Fenix versions in BCD, such as the beta version you are currently running.  Once Fenix has deployed as a stable release, however, we will be sure to update our data!
