### ISSUE TITLE
backdrop-filter does not work in Firefox 76.0, despite config changes

### ISSUE THREAD

**Issue by sam-cross** [mdn/browser-compat-data#6118]
It appears that `backdrop-filter` does not work in Firefox 76.0, despite having set the following flags:

* `layout.css.backdrop-filter.enabled = true`
* `gfx.webrender.all = true`

It does not work on the demo page:

![image](https://user-images.githubusercontent.com/6699307/81411559-7416bf80-913a-11ea-9c30-9a714b1e6fb2.png)

... And doesn't work on my own site, either, even with the `-webkit-` prefix.

**Comment by ddbeck** [comment]
Thanks for reporting this, @sam-cross. I tried it out myself and it worked for me, though I needed to restart Firefox before it took effect.

Based on that, I'd say the data in [`backdrop-filter.json`](https://github.com/mdn/browser-compat-data/blob/master/css/properties/backdrop-filter.json) is correct and I'm going to close this issue. But if I've missed some detail or you think there's more to the story here, please feel free to reopen with additional information. Thank you again!
