### ISSUE TITLE
HTML/preloading: Chrome + Firefox data issues

### ISSUE THREAD

**Issue by queengooborg** [mdn/browser-compat-data#6120]
Cherry-picked from #5932.  Users have reported issues with preloading in Chrome, and a potential fix for preloading in Firefox.

Chrome
> Chrome does not support this due to a bug preventing it to execute the preload command. This affects several "as" types, e.g. media, video and document.  https://bugs.chromium.org/p/chromium/issues/detail?id=593267

Firefox
> It looks like the Firefox bug for version 57 & 58 has been resolved. 
 https://bugzilla.mozilla.org/show_bug.cgi?id=1405761

**Comment by Elchi3** [comment]
Looks like https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel/preload has the updated info
