### ISSUE TITLE
HTTP Header Length Limits

### ISSUE THREAD

**Issue by bershanskiy** [mdn/browser-compat-data#6125]
Over time, browser vendors realized that some developers do not keep track of HTTP header lengths and cause a lot of extra traffic. In response to this header bloat browsers implemented header length limits and it would be nice to document these limits in MDN and BCD.

Relevant information for future PRs:
### Maximum cookie length (e.g., in `Set-Cookie`)
 - Might be useful: http://browsercookielimits.squawky.net
 - Standard: [RFC 2109](https://tools.ietf.org/html/rfc2109) section 6.1:
   > at least 4096 bytes per cookie (as measured by the size of the characters that comprise the cookie non-terminal in the syntax description of the Set-Cookie header)
 - [Chrome]() other quotas and [Firefox](https://github.com/mozilla/gecko-dev/blob/26ec48f853b94a8bdc4fc7a47940fcb6430773c3/netwerk/cookie/CookieService.cpp#L1036) follow the standard
 - There was a unusual behavior/bug in WebKit resulting in duplicate cookies, I think

- Other quotas: [Chromium](https://github.com/chromium/chromium/blob/master/net/cookies/cookie_monster.cc#L140)

**Comment by queengooborg** [comment]
It looks like this has been fixed by #6130!
