### ISSUE TITLE
Move HTMLOrForeignElement out of HTMLElement?

### ISSUE THREAD

**Issue by bershanskiy** [mdn/browser-compat-data#6129]
`HTMLOrForeignElement` is a mixin that describes several features common to the `HTMLElement`, `SVGElement` and `MathMLElement` interfaces. It even has it's own page ([`HTMLOrForeignElement`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOrForeignElement))and its members are documented on pages that are children pages to that page. Yet, for some reason `__compat` data about members of `HTMLOrForeignElement` lives under corresponding elements.

We should consider either of the two things:
 1. Create a single separate file `api/HTMLOrForeignElement.json`
    [`HTMLOrForeignElement.dataset`](https://wiki.developer.mozilla.org/en-US/docs/Web/API/HTMLOrForeignElement/dataset?raw) says "Please change the compat macro's paramter to api.HTMLOrForeignElement.dataset after BCD is updated."
 2. Create separate BCD entries for `HTMLElement`, `SVGElement` and `MathMLElement` but make a single documentation page
   E.g., for `HTMLOrForeignElement.nonce` each of `HTMLElement.nonce`, `SVGElement.nonce`, and `MathMLElement.nonce` will have a separate `__compat` like they do now, but they will link to a single article `HTMLOrForeignElement.nonce`.

**Comment by Elchi3** [comment]
This is tricky and we haven't addressed this issue. See https://github.com/mdn/browser-compat-data/issues/472 and https://github.com/mdn/browser-compat-data/issues/3463 for some prior discussions.

**Comment by bershanskiy** [comment]
Thanks. Closing this as a duplicate of the linked bugs.
