### ISSUE TITLE
CSP form-action and inconsistent redirect behavior

### ISSUE THREAD

**Issue by johnp** [mdn/browser-compat-data#6132]
The Content-Security-Policy `form-action` compatibility table should have a mention that its behavior is currently [inconsistent](https://github.com/w3c/webappsec-csp/issues/8) in browsers with regards to redirects after form submission. A warning was added to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/form-action) in 2018, but I suppose that should be moved/added [here](https://github.com/mdn/browser-compat-data/blob/master/http/headers/content-security-policy.json), so that [caniuse](https://caniuse.com/#feat=mdn-http_headers_csp_content-security-policy_form-action) picks it up as well.

**Comment by johnp** [comment]
Ah, I suppose this should be reported at the caniuse [data repository](https://github.com/Fyrd/caniuse/). Sorry for the noise.

**Comment by johnp** [comment]
Reopening because the caniuse data actually comes from [here](https://github.com/mdn/browser-compat-data/blob/master/http/headers/content-security-policy.json).

**Comment by jculver050** [comment]
Close
