### ISSUE TITLE
"MediaTrackConstraints API: cursor" is outdated

### ISSUE THREAD

**Issue by LukasKalbertodt** [mdn/browser-compat-data#6133]
- https://caniuse.com/#feat=mdn-api_mediatrackconstraints_cursor
- https://github.com/mdn/browser-compat-data/blob/0bb9a8a01cc3ef53dd3467125886dd62a5ff27f0/api/MediaTrackConstraints.json

This is outdated: Chrome (and presumably the new Edge) already support capturing the cursor. For example, check [this test page](https://www.webrtc-experiment.com/getDisplayMedia/), select "cursor: always" and share. You will see the cursor with Chrome 81 (and I think in many previous versions, too).

**Comment by millzee01** [comment]
The cursor constraint doesn't work.  If I set it to "never" on the test page then the cursor is always captured.

**Comment by LukasKalbertodt** [comment]
That's a good point. I incorrectly assumed a cursor in the video stream would imply that the `cursor` constraints is checked. But as it seems unconditional, the current data is correct.
