### ISSUE TITLE
Misleading version of Edge in BroadcastChannel

### ISSUE THREAD

**Issue by waghvikrant** [mdn/browser-compat-data#6134]
Currently, on [https://developer.mozilla.org/en-US/docs/Web/API/BroadcastChannel](https://developer.mozilla.org/en-US/docs/Web/API/BroadcastChannel) Edge version is ≤79, which translates to less than or equal to 79. This is misleading. The version_added attribute for Edge can be changed to 79 to correctly reflect that the BroadcastChannel APIs are added in version 79.

**Comment by jculver050** [comment]
Close

**Comment by vinyldarkscratch** [comment]
This was resolved in #9184!
