### ISSUE TITLE
animationend is supported by IE11

### ISSUE THREAD

**Issue by tjcrowder** [mdn/browser-compat-data#6135]
I'm not sure what to do here. The browser compat data doesn't say when IE got support for the `animationend` event, so I tried it in IE11 and it worked. (It doesn't work in IE9.) I don't have IE10 to try it on.

Do I do a PR for `/api/HTMLElement.json` saying: `"version_added": "11"` even though I don't know whether it was added in 10 or 11?

**Comment by vinyldarkscratch** [comment]
Hi there, thanks for opening the issue!  Let's hold off on a PR for now until we are able to determine whether support was added in 10 or 11.  If you'd like to tackle this one, I happen to have a collection of virtual machines featuring several browser versions, including IE 10, [available for download](https://drive.google.com/open?id=1w6nVUMD5MwkoevzuhCDuDpbxyk3ywCRY)!

**Comment by tjcrowder** [comment]
@vinyldarkscratch - Thanks! I'll grab one and see if the event works.
