### ISSUE TITLE
Support for SourceBuffer listed incorrectly for Firefox on Android

### ISSUE THREAD

**Issue by SnyderTheOne** [mdn/browser-compat-data#6137]
On https://developer.mozilla.org/en-US/docs/Web/API/SourceBuffer, 'Firefox for Android' lists `SourceBuffer` as an unsupported feature, even though this seems to be implemented. Support for `MSE` is listed correctly on https://developer.mozilla.org/en-US/docs/Web/API/Media_Source_Extensions_API.

**Comment by jculver050** [comment]
Close
