### ISSUE TITLE
Firefox has window.event unflagged in v66 onward

### ISSUE THREAD

**Issue by tjcrowder** [mdn/browser-compat-data#6145]
From the [v63 release notes](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/63#APIs):

> We implemented the `Window.event` property to improve web compatibility, now that it's become standard (bug 218415). However, due to some web compat issues (e.g. bug 1479964), this was quickly disabled in non-Nightly channels, hidden behind the `dom.window.event.enabled` pref (bug 1493869).

And then the [v66 release notes](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/66#APIs):

> The Window.event and Event.returnValue properties — originally proprietary IE features, then also supported across other browsers for compatibility purposes — have been re-introduced in Firefox 66, after first being added in versions 63 and 64 respectively but then removed again due to compatibility issues. 

I'm slightly uncertain how to update `Window.json` to include that information. This is what it currently looks like:

```js
"firefox": {
  "version_added": "63",
  "notes": "This was briefly enabled by default in 65, then removed again while related compatibility issues are sorted out (see <a href='https://bugzil.la/1520756'>bug 1520756</a>).",
  "flags": [
    {
      "type": "preference",
      "name": "dom.window.event.enabled",
      "value_to_set": "true"
    }
  ]
},
```
Happy to do a PR if someone can tell me what to do with it. For instance, would the following be correct?
```js
"firefox": [
  {
    "version_added": "66"
  },
  {
    "version_added": "63",
    "notes": "This was <a href="https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/63#APIs">briefly enabled by default in 63 then quickly put behind a flag</a>, and re-introduced without a flag in <a href="https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/66#APIs">v66</a>.",
    "flags": [
      {
        "type": "preference",
        "name": "dom.window.event.enabled",
        "value_to_set": "true"
      }
    ]
  }
],
```

**Comment by ddbeck** [comment]
Thanks for this issue! You're on the right track here and this is a tricky one (see #3357 for how this was originally added). Your proposal is good, though I would leave the original note as it is—reading through the bugs, I think 65 was the only version where a release build had it enabled by default (though @chrisdavidmills might be in a better position to confirm that).

I'd be happy to review your PR, when you open it. Thank you!

**Comment by chrisdavidmills** [comment]
This looks about right to me.

**Comment by jculver050** [comment]
Close

**Comment by vinyldarkscratch** [comment]
Since the flag data has been removed in #9927, I think we can safely close this!
