### ISSUE TITLE
Safari 13 and iOS Safari 13 can use flow-root

### ISSUE THREAD

**Issue by badcat** [mdn/browser-compat-data#6148]
Browser compatibility chart still states Safari and iOS Safari cannot take advantage of display flow-root. Flow-root appears to work since Safari 13 and iOS Safari 13. I think this is also confirmed with Can I Use. https://caniuse.com/#feat=flow-root

**Comment by ddbeck** [comment]
It does appear to have shipped with Safari 13, based on a few details:

* [WebKit changeset 245494](https://trac.webkit.org/changeset/245494/webkit/)
* Safari [TP 84](https://webkit.org/blog/9170/safari-technology-preview-84-with-safari-13-features-is-now-available/) release notes
* Safari [TP 83](https://webkit.org/blog/8967/release-notes-for-safari-technology-preview-83/) release notes

This change would need to go into the `css.properties.display.flow-root` feature in https://github.com/mdn/browser-compat-data/blob/master/css/properties/display.json#L455, if you're keen to open a PR.
