### ISSUE TITLE
String localeCompare: locales/options functional in WebView?

### ISSUE THREAD

**Issue by vinyldarkscratch** [mdn/browser-compat-data#6150]
Cherry-picked from #5934.  A user reported that in WebView, `localeCompare`'s `locales` and `options` parameters function, which is most likely true.  I wanted to open an issue rather than submit a PR as I have yet to obtain the tools needed to test different WebView versions.

**Comment by ddbeck** [comment]
I'm not clear on what this adds over the original issue, so I'm going to close this. I'd be OK with breaking out specific issues from #5934 (leaving the original as a tracking issue), but any new issues need to copy over all the relevant info and the table in #5934 needs to be updated to point to the subordinate issue.

**Comment by vinyldarkscratch** [comment]
Well the reason I’m splitting it out is to give this its own focus and discussion thread.  I’ve been going through all the feedback tables to weed out all the bad feedback and submit PRs for the good ones, but a few of them are currently beyond the abilities of my utilities, so I want to get a discussion going for them.
