### ISSUE TITLE
Why is specification status in browser compat data?

### ISSUE THREAD

**Issue by wbamberg** [mdn/browser-compat-data#616]
According to the README:

> "Browser compatibility data describes which platforms (where "platforms" are usually, but not always, web browsers) support particular Web APIs."

This doesn't seem to encompass spec status at all. Spec status seems like an independent attribute of an API, and would live more appropriately in the `data` repo.

**Comment by jpmedley** [comment]
It's status of individual interfaces and members. In this repo there's a 1:1 ratio between a member and it's status.

**Comment by teoli2003** [comment]
Yes, jpmedley is right. Experimental status of a feature is somewhat (mostly?) unrelated to the status of the specs that describe it. The status of the specs is in data. The experimental status (or not) of a feature is in browser-compat-data.

**Comment by Elchi3** [comment]
I think the `status` object informs about whether it's a good idea to use a certain feature. If `standard_track `is false, there are likely serious interoperability issues now or in the future.

The status of specs itself is not stored in browser-comat-data and will be on mdn/data hopefully soon.
