### ISSUE TITLE
Outdated about mobile Firefox

### ISSUE THREAD

**Issue by erlendorf** [mdn/browser-compat-data#617]
You're outdated about [WebExtensions/manifest.json/options_ui](https://github.com/mdn/browser-compat-data/blob/master/webextensions/manifest/options_ui.json) (and possibly related features): [Support for it has been added in mobile Firefox 56](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/options_ui).

**Comment by Elchi3** [comment]
This was fixed in https://github.com/mdn/browser-compat-data/pull/804 I believe.
