### ISSUE TITLE
Reduce the number of special case feature groups

### ISSUE THREAD

**Issue by ddbeck** [mdn/browser-compat-data#6175]
Some consumers have to handle special groups of features in the structure of the data. We should reduce or eliminate these special cases.

In general, we have a few broad namespaces in BCD, in which features with `__compat` data reside. The `api` namespace is typical of this: `api.<featurename>` is a parent of `__compat` data. `css` is more finely divided, with `css.properties`, `css.selectors`, etc.

The trouble is within a namespace, such as [`css.properties.gap`](https://github.com/mdn/browser-compat-data/blob/master/css/properties/gap.json). `css.properties.gap` is _not_ a parent to `__compat` data. Instead, it's a surprise namespace for `flex_context`, `grid_context`, etc. We should avoid these surprises in the structure of the data.

The first step to resolving this would be to make a list of all paths through the structure which are not parents to `__compat`.

**Comment by jculver050** [comment]
Close

**Comment by ddbeck** [comment]
This is dupe of https://github.com/mdn/browser-compat-data/issues/13804 (well, actually, a subset of). Closing in favor of the other issue, since it's a bit more comprehensive.
