### ISSUE TITLE
WebExtensions data should include specification status

### ISSUE THREAD

**Issue by wbamberg** [mdn/browser-compat-data#618]
For [bug 1408494](https://bugzilla.mozilla.org/show_bug.cgi?id=1408494), let's figure out the  specification status of the browser extension APIs.

[Here's a spreadsheet](https://docs.google.com/spreadsheets/d/1mOwAdDkxM6pLIjLGwbS_e8n3EoPsgaZXUC8YGAIMv8E/edit?usp=sharing) that we can use to work out what to put for the [`status`](https://github.com/mdn/browser-compat-data/blob/master/compat-data-schema.md#status-information) property.

It includes all APIs and manifest keys that we currently document on MDN, one sheet for APIs, one sheet for keys. For each item, I'd like to record the value of `status` we want.

So far:

* I've included values for `standard_track`, based on the [standard](https://browserext.github.io/browserext/).
* I didn't know which ones are `experimental` except [`find`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/find), which is given as an example of `experimental` [in the Wiki](https://wiki.mozilla.org/WebExtensions/Spec).
* I don't think any are `deprecated` at this level.

Of course there will be more detail at the next level down. There are lots of nonstandard additions to
 standard-track APIs, and I know some individual APIs, like [`tabs.getSelected()`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/getSelected), are deprecated. But I think this is a start.

@andymckay , @mconca, I'd love to know if you think this is a good approach, and if you would like to see any changes in the data here. Are there any other `experimental` or `deprecated` APIs or keys?

Once we have an outline at the top level, we can go to the next level down.

**Comment by wbamberg** [comment]
@andymckay , I saw you added some things to the spreadsheet. Thanks!

I'm not clear though what the criteria are for calling things `standard_track`. I was marking things `standard_track` based only on whether they are in the draft specification, but many of the APIs you've marked `standard_track` are not in the draft spec.

Also, I saw you marked `contextualIdentities` as `experimental`. I would probably have done the same, except that the [Wiki page](https://wiki.mozilla.org/WebExtensions/Spec) gives it as an example of type 2, which is `standard_track=false`, `experimental=false`. Is the Wiki wrong here?

**Comment by andymckay** [comment]
Sorry I got this completely wrong didn't I. Let me fix this up.

**Comment by andymckay** [comment]
Alright so, "a stable API that is recommended as a standard but not part of a track yet". It then says " An example could be the find API". Note the word "could be". 

We haven't got any structure for recommending as a standard, haven't spoken to the community group about it. They just had TPAC this week and we are planning to start up meetings at some point.

So technically, nothing is experimental. So what should be the bar here? Things that we think we might recommend to the group? It seems to me everything that's not in the standard would be the next step.

**Comment by andymckay** [comment]
Let's make the assumption that everything that's in Chrome or any other browser could implement is experimental and some point we'll talk about getting into the spec. I'm updating now.

**Comment by wbamberg** [comment]
> Let's make the assumption that everything that's in Chrome or any other browser could implement is experimental and some point we'll talk about getting into the spec. I'm updating now.

This seems over-conservative to me. I think there's a significant different between, say, `alarms`, which has [solid cross-browser support](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Browser_support_for_JavaScript_APIs#alarms) and doesn't do anything very fancy, and something like `pkcs11`, which at this point is basically a wrapper around an XPCOM API. Giving both the same status flags doesn't capture that difference.

At the moment, the tooltip for the "experimental" icon says _"Non-standard. Expect poor cross-browser support"_ (see for example the [pkcs11 table](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Browser_support_for_JavaScript_APIs#pkcs11)). This seems like a discouraging message to have for quite fundamental APIs.

My suggestion would be, as a rule of thumb: if an API has reasonably good cross-browser support, then `experimental=false`.

But of course this is your call. I'm not the one who has to maintain compatibility :).

**Comment by wbamberg** [comment]
Anyway, that aside: for the next level down, I think a good rule of thumb is:

* if an API at the top-level is _standard_track_, then:

    * its subfeatures might be _experimental_ (for example, perhaps `webRequest` is _standard_track_ but `webRequest.filterResponseData()` is _experimental_).

    * its subfeatures might be _deprecated_ (for example, perhaps `tabs` is _standard_track_ but `tabs.getSelected()` is _experimental_.

* if an API at the top level is `experimental`, then all its subfeatures will also be `experimental`.

**Comment by wbamberg** [comment]
I've updated the spreadsheet with a new tab "webextensions-apis", that contains proposed detailed status info for the APIs only (i.e. not the manifest keys yet).

https://docs.google.com/spreadsheets/d/1mOwAdDkxM6pLIjLGwbS_e8n3EoPsgaZXUC8YGAIMv8E/

It has a row for every item that has compat data associated with it.

I've done the following:

* if an API at the top level is "experimental", then all the rows under that API have `"standard_track":false` and `experimental":true`

* if an API at the top level is "standard_track", then for each row:
    * if it's in the spec it has `"standard_track":true` and `experimental":false`  (e.g. `browserAction.getBadgeBackgroundColor`)

    * if it isn't, it has `"standard_track":false` and `experimental":true` (e.g. `browserAction.openPopup`)

Apart from that, I marked a few rows with `"deprecated":true`, but not many: I might have missed some.

@andymckay , @mconca, please review this and let me know if it's correct. Once we're agreed, I can  use this to prepare a PR.

**Comment by wbamberg** [comment]
I've now updated the spreadsheet for manifest keys, following the same process as for APIs, in the previous comment.

**Comment by andymckay** [comment]
I think this is good, but I'd also really like to discuss it with the W3C group. Is it a pain if we change these later?

**Comment by wbamberg** [comment]
It'll be a lot easier for me to get agreement once and make one big PR.

**Comment by Elchi3** [comment]
I think this won't happen after all. Closing.
