### ISSUE TITLE
Firefox does indeed work with RegExp: Unicode property escapes

### ISSUE THREAD

**Issue by koehn** [mdn/browser-compat-data#6185]
I don't know why it says otherwise in the data, but it's easy to verify that Firefox's Javascript engine supports regular expression unicode property escapes. 

console.log('hello. #ժամանակ #foo.'.match(/(?:^|\B)#(?![\p{Nd}\p{Pc}]+\b)([\p{L}\p{Nl}\p{Nd}\p{Pc}]{1,30})(?:\b|\r)?/gu));

correctly prints out `[ '#ժամանակ', '#foo' ]`

Tested on FF76.0.1/MacOS 10.15.4.

**Comment by ddbeck** [comment]
Hi @koehn, thanks for opening this issue. I think this is for feature [`javascript.builtins.RegExp.property_escapes`](https://github.com/mdn/browser-compat-data/blob/cc7979f43a6a8dee18c3e6868ecbff113cd6e08e/javascript/builtins/RegExp.json#L1063).

I tried your test case and it worked in Firefox Nightly (v78), but not in 77 or 76. I did some looking and [bug 1361876](https://bugzilla.mozilla.org/show_bug.cgi?id=1361876) seems to indicate this was only resolved in Firefox 78. Is it possible that you tried this in Nightly?

I'd welcome a PR, if you're interested in updating that feature to show `"version_added": "78"`. Thank you!

**Comment by koehn** [comment]
Below is a screenshot of the output of the above regex working inside FF 76.0.1.
<img width="457" alt="Screen Shot 2020-05-21 at 6 24 24 AM" src="https://user-images.githubusercontent.com/583888/82554584-d81e8800-9b2b-11ea-9f07-eaacdfd1b6b0.png">

Although I also see that if you run the code in the console in the same browser, you get:
<img width="847" alt="Screen Shot 2020-05-21 at 6 27 40 AM" src="https://user-images.githubusercontent.com/583888/82554775-32b7e400-9b2c-11ea-8b64-446aaa63fc20.png">

And that's pretty weird.

**Comment by ddbeck** [comment]
Huh, that is pretty weird. Is it possible you're using a babel plugin or something with the working page?

I can't get any of the examples in [the interactive example for RegExp Unicode property escapes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Unicode_Property_Escapes) to work properly in 77 or 76, but it does work in 78.

It seems like your page _shouldn't_ work. It's a regex miracle, the exact opposite of my usual experience with regex. 😄

**Comment by koehn** [comment]
You're right; behind the scenes babel was rescuing me. Sorry for the confusion; my bad. 

That said, I'm really happy that somebody made those escapes work for me!
