### ISSUE TITLE
Is @viewport standard track?

### ISSUE THREAD

**Issue by ddbeck** [mdn/browser-compat-data#6213]
In the course of #6165, I read up a little on the CSS at-rule `@viewport`. According to https://github.com/w3c/csswg-drafts/issues/4766, it's been resolved to drop `@viewport` due to lack of browser vendor interest. That said, it doesn't appear that the rule has been removed from the text of the corresponding specification.

At what point do we mark the data as `"standard_track": "false"`? Now, or when the specification is updated?

**Comment by sideshowbarker** [comment]
> At what point do we mark the data as `"standard_track": "false"`? Now, or when the specification is updated?

When the specification is updated, I’d think. For one thing, that preempts the problem of somebody coming along later who’s read the spec and found it (still) defined there, and then filing an issue or PR to report that the BCD data is wrong (because the feature is still in the spec).

**Comment by ddbeck** [comment]
Thank you, @sideshowbarker. That's just the sort of practical answer I was hoping for.

I guess I'll leave this open until there's a change to the spec and close it when we've updated the standard track data here.

**Comment by jpmedley** [comment]
If you're the person trying to update something on MDN or BCD, I suggest sending an email to the spec authors asking if they're still planning to make the change. It's usually the case that the spec authors have let this slip. When I've done this, I think they've almost always profusely apologized for letting the update slip. 

It doesn't take long, and frankly, I think of it as an act of platform hygiene.

**Comment by jculver050** [comment]
Close

**Comment by queengooborg** [comment]
I'd say that this has been fixed by #7514, which marks `@viewport` as non-standard!
