### ISSUE TITLE
insertBefore for IE

### ISSUE THREAD

**Issue by sorawee** [mdn/browser-compat-data#6226]
According to https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/aa752495(v=vs.85), it looks like `insertBefore` is supported since IE6, but the compat data here says it's only added in IE9.

**Comment by ddbeck** [comment]
Thanks for this report, @sorawee.

It looks like feature `api.Node.insertBefore` is the one that needs updating, specifically around [this line](https://github.com/mdn/browser-compat-data/blob/master/api/Node.json#L779). It should be a one-line fix, to change `"version_added": "9"` to `"version_added": "6"`.

I'd welcome a PR making this change!

**Comment by sorawee** [comment]
I hope that anyone can actually confirm that the information is indeed correct. The same issue applies to `replaceChild` too, and perhaps more.

**Comment by ddbeck** [comment]
I'm willing to trust the Microsoft docs on this, especially given how old the browser is. 

This is the page for `replaceChild`: https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/aa752504(v=vs.85) It's a similar change for that feature (in the same file, even).

**Comment by ddbeck** [comment]
While reviewing #6237, I found that [QuirksMode reports](https://quirksmode.org/dom/core/#t92) having tested support to IE 5.5 (with some old caveats that are probably not worth mentioning at this point).

**Comment by jculver050** [comment]
Close

**Comment by vinyldarkscratch** [comment]
This was fixed in #9001!
