### ISSUE TITLE
Location.hostname for Opera

### ISSUE THREAD

**Issue by edg2s** [mdn/browser-compat-data#6239]
Currently it is claimed there is no support for this in Opera. I am able to test back to version 11, but I suspect it should be version 3 like the other properties of the Location API.

**Comment by edg2s** [comment]
Given that Opera switched to Blink in version 15, I wonder if it possible to automatically scan for places where claimed for support is below the equivalent version of Chromium: https://help.opera.com/en/opera-version-history/#history

e.g. If Chrome support is >=28 then Opera support should be at least >=15

**Comment by ddbeck** [comment]
This has been partly addressed by #6286 (setting the values to `true`).

**Comment by jculver050** [comment]
Close

**Comment by vinyldarkscratch** [comment]
This has been resolved by #7202!
