### ISSUE TITLE
More precise support data for DOMTokenList

### ISSUE THREAD

**Issue by stof** [mdn/browser-compat-data#6248]
currently, the initial feature set of DOMTokenList (see places where Chrome is marked at version 1 for what I include here) is marked as fully supported in IE 11. But the reality is more nuanced. the implementation in IE 11 supports only one argument in `add` and `remove`, and does not support the `force` argument for `toggle`.
It would be great if this could be highlighted (either by changing these rows to partial support, or by adding new sub-features).

see https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList#Browser_compatibility for the support table.

**Comment by ddbeck** [comment]
Thanks for pointing this out, @stof. You're right that the feature is a bit more nuanced than that. The good news is that we do have subfeatures for the issues you mention, if you click through the specific methods:

* https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList/add#Browser_compatibility
* https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList/toggle#Browser_compatibility

As for the summary on the parent table, that's a harder issue to resolve. I suppose this is a display problem, where a more sophisticated table would show some counter for supported subfeatures (or a progress bar or something). It might be more appropriate to open an issue about this display problem on the [KumaScript repo](https://github.com/mdn/kumascript/issues?q=is%3Aissue+is%3Aopen+label%3Abcd).

I'm going to close this issue (as the data problem appears to be resolved), but if I've missed something, we can reopen it. Thank you!
