### ISSUE TITLE
Complete nodejs data

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#6249]
We're getting lots of positive feedback about providing nodejs compat data on our ECMAScript docs. So, lets complete our dataset.

The task here is: For the following data points, replace `true` or `null` with a version number for `nodejs`.

I'm happy to mentor newcomers about this or review PRs if anyone wants to pick up this work. Currently, I don't have the time to finish this myself.

The data points with missing nodejs version numbers are:

### SAB (done in https://github.com/mdn/browser-compat-data/pull/6294 :tada:)

javascript.builtins.DataView.buffer.sharedarraybuffer_support

### Map and Set (done in https://github.com/mdn/browser-compat-data/pull/6283 :tada: )

javascript.builtins.Map.Map
javascript.builtins.Map.get
javascript.builtins.Map.has
javascript.builtins.Map.set
javascript.builtins.Set.Set
javascript.builtins.Set.add
javascript.builtins.Set.has

### Functions (done in https://github.com/mdn/browser-compat-data/pull/7567 :tada: )

javascript.builtins.Function
javascript.builtins.Function.Function
javascript.builtins.Function.apply
javascript.builtins.Function.apply.generic_arrays_as_arguments
javascript.builtins.Function.arguments
javascript.builtins.Function.bind
javascript.builtins.Function.call
javascript.builtins.Function.caller
javascript.builtins.Function.length
javascript.builtins.Function.length.configurable_true
javascript.builtins.Function.name
javascript.builtins.Function.name.configurable_true
javascript.builtins.Function.name.inferred_names
javascript.builtins.Function.toString
javascript.builtins.Generator.next
javascript.builtins.GeneratorFunction
javascript.functions
javascript.functions.arguments
javascript.functions.arguments.callee
javascript.functions.arguments.length
javascript.functions.arguments.@@iterator
javascript.functions.arrow_functions
javascript.functions.arrow_functions.trailing_comma
javascript.functions.block_level_functions
javascript.functions.default_parameters.destructured_parameter_with_default_value_assignment
javascript.functions.default_parameters.parameters_without_defaults_after_default_parameters
javascript.functions.get
javascript.functions.get.computed_property_names
javascript.functions.method_definitions
javascript.functions.rest_parameters.destructuring
javascript.functions.set
javascript.functions.set.computed_property_names

### Object (see https://github.com/mdn/browser-compat-data/pull/7572)

javascript.builtins.Object
javascript.builtins.Object.Object
javascript.builtins.Object.constructor
javascript.builtins.Object.create
javascript.builtins.Object.defineGetter
javascript.builtins.Object.defineProperties
javascript.builtins.Object.defineProperty
javascript.builtins.Object.defineSetter
javascript.builtins.Object.freeze
javascript.builtins.Object.getOwnPropertyDescriptor
javascript.builtins.Object.getOwnPropertyNames
javascript.builtins.Object.getPrototypeOf
javascript.builtins.Object.hasOwnProperty
javascript.builtins.Object.isExtensible
javascript.builtins.Object.isFrozen
javascript.builtins.Object.isPrototypeOf
javascript.builtins.Object.isSealed
javascript.builtins.Object.keys
javascript.builtins.Object.lookupGetter
javascript.builtins.Object.lookupSetter
javascript.builtins.Object.preventExtensions
javascript.builtins.Object.preventExtensions.ES2015_behavior
javascript.builtins.Object.propertyIsEnumerable
javascript.builtins.Object.proto
javascript.builtins.Object.seal
javascript.builtins.Object.toLocaleString
javascript.builtins.Object.toString
javascript.builtins.Object.valueOf

### Regexp (done in https://github.com/mdn/browser-compat-data/pull/6618 :tada)

javascript.builtins.RegExp
javascript.builtins.RegExp.RegExp
javascript.builtins.RegExp.compile
javascript.builtins.RegExp.exec
javascript.builtins.RegExp.global
javascript.builtins.RegExp.global.prototype_accessor
javascript.builtins.RegExp.ignoreCase
javascript.builtins.RegExp.ignoreCase.prototype_accessor
javascript.builtins.RegExp.input
javascript.builtins.RegExp.lastIndex
javascript.builtins.RegExp.lastMatch
javascript.builtins.RegExp.lastParen
javascript.builtins.RegExp.leftContext
javascript.builtins.RegExp.multiline
javascript.builtins.RegExp.multiline.prototype_accessor
javascript.builtins.RegExp.n
javascript.builtins.RegExp.rightContext
javascript.builtins.RegExp.source
javascript.builtins.RegExp.source.empty_regex_string
javascript.builtins.RegExp.source.escaping
javascript.builtins.RegExp.source.prototype_accessor
javascript.builtins.RegExp.sticky
javascript.builtins.RegExp.sticky.anchored_sticky_flag
javascript.builtins.RegExp.sticky.prototype_accessor
javascript.builtins.RegExp.test
javascript.builtins.RegExp.toString
javascript.builtins.RegExp.toString.escaping
javascript.builtins.RegExp.unicode

### Symbol (done in https://github.com/mdn/browser-compat-data/pull/6331 :tada:)

javascript.builtins.Symbol
javascript.builtins.Symbol.Symbol
javascript.builtins.Symbol.for
javascript.builtins.Symbol.keyFor
javascript.builtins.Symbol.toString
javascript.builtins.Symbol.valueOf

### Grammar (done in https://github.com/mdn/browser-compat-data/pull/6332 :tada:)

javascript.grammar.array_literals
javascript.grammar.boolean_literals
javascript.grammar.decimal_numeric_literals
javascript.grammar.hashbang_comments
javascript.grammar.hexadecimal_escape_sequences
javascript.grammar.hexadecimal_numeric_literals
javascript.grammar.null_literal
javascript.grammar.numeric_separators
javascript.grammar.octal_numeric_literals
javascript.grammar.regular_expression_literals
javascript.grammar.string_literals
javascript.grammar.unicode_escape_sequences
javascript.grammar.unicode_point_escapes
javascript.grammar.shorthand_object_literals
javascript.grammar.trailing_commas
javascript.grammar.trailing_commas.trailing_commas_in_object_literals

**Comment by gilmoreorless** [comment]
I'm happy to help with this (I may come to regret saying that 😉). Having just been through the process of correcting all the `Intl` data for Node (#6202), I've now got a bunch of scripts and helpers to quickly test features on all the versions of Node listed in the `browsers` data.

**Comment by joneskj55** [comment]
@Elchi3 I'd be happy to jump on some of this. I can start doing the functions. I'm just not sure the best way to retrieve the appropriate version numbers. Would it be possible for you to point me in the right direction for getting this data?

**Comment by gilmoreorless** [comment]
@joneskj55 Before you get too far into it, I already have a branch mostly done for the functions. I was just waiting on some of the tasks in #6861 to be taken care of before making a PR. (I should get onto that now that it's all done.)

The object data is still up for grabs though, feel free to jump on that. :smile:

For getting the version numbers, I've used a few techniques. The new decision to make `0.10.0` the minimum version helps a lot. Here's a rough list of what I check:

- Any feature that has a listed Chrome version of 24 or lower will be in Node.js `0.10.0`, because of the V8 version in use.
- Otherwise, see if the feature is listed at [node.green](https://node.green/) (it might be named differently there, though).
- Finally, I manually check some things on different Node.js versions locally using `nvm` if needed.

**Comment by joneskj55** [comment]
@gilmoreorless Thanks for letting me know, I wasn't sure if this was still being worked on. Also, thanks for the info about getting the version data! If you are working on this I'll defer to you on whether or not to start on the object data. If you wanted to complete this issue I don't want to step on your toes. However, I'm also willing to work on it. Please let me know what you think, I'm fine either way. Thanks!

**Comment by gilmoreorless** [comment]
My spare time's been fairly fragmented lately, so I'm not likely to start on the object data any time soon. Feel free to grab it.
