### ISSUE TITLE
MediaSession API missing features for setActionHandler actions and setPositionState

### ISSUE THREAD

**Issue by ddbeck** [mdn/browser-compat-data#6265]
Some data was suggested as missing in #6002. I've reviewed the PR discussion and compiled this table of potential data point updates and, where possible, citations. Mostly derived from https://github.com/mdn/browser-compat-data/pull/6002#issuecomment-626678766 and https://github.com/mdn/browser-compat-data/pull/6002#issuecomment-626686162

| Done | Feature                                                                                    | Firefox | Firefox notes                                        | Chrome | Chrome notes                                                                                                   |
|------|--------------------------------------------------------------------------------------------|---------|------------------------------------------------------|--------|----------------------------------------------------------------------------------------------------------------|
| ✅ | ~`api.MediaSession.setActionHandler.nexttrack`~ `api.MediaSessionAction.nexttrack`         | 71 🎏    |                                                      | 73     |                                                                                                                |
| ✅  | ~`api.MediaSession.setActionHandler.pause`~ `api.MediaSessionAction.pause`                 | 71 🎏    |                                                      | 73     |                                                                                                                |
| ✅  | ~`api.MediaSession.setActionHandler.play`~ `api.MediaSessionAction.play`                   | 71 🎏    |                                                      | 73     |                                                                                                                |
| ✅  | ~`api.MediaSession.setActionHandler.previoustrack`~ `api.MediaSessionAction.previoustrack` | 71 🎏    |                                                      | 73     |                                                                                                                |
| ✅  | ~`api.MediaSession.setActionHandler.scrubTo`~ `api.MediaSessionAction.scrubTo`                   |    N/A     |                                                      | N/A     | https://storage.googleapis.com/chromium-find-releases-static/f23.html#f230e6257d8bd8637314b5dd4d7acb4ae997f604 |
| ✅  | ~`api.MediaSession.setActionHandler.seekbackward`~ `api.MediaSessionAction.seekbackward`   | 76 🎏    | https://bugzilla.mozilla.org/show_bug.cgi?id=1580623 | 73     |                                                                                                                |
| ✅  | ~`api.MediaSession.setActionHandler.seekforward`~ `api.MediaSessionAction.seekforward`     | 76 🎏    | https://bugzilla.mozilla.org/show_bug.cgi?id=1580623 | 73     |                                                                                                                |
| ✅  | ~`api.MediaSession.setActionHandler.seekto`~ `api.MediaSessionAction.seekto`               | 80 🎏    |                                                      | 77     | https://storage.googleapis.com/chromium-find-releases-static/f23.html#f230e6257d8bd8637314b5dd4d7acb4ae997f604 |
| ✅  | ~`api.MediaSession.setActionHandler.skipad`~ `api.MediaSessionAction.skipad`               | 80 🎏    |                                                      | 73     | https://storage.googleapis.com/chromium-find-releases-static/b02.html#b0281b1250cdec351658e9bf07dd5f5d3331ef91 |
| ✅  | ~`api.MediaSession.setActionHandler.stop`~ `api.MediaSessionAction.stop`                   | 71 🎏    |                                                      | 73     |                                                                                                                |
| ✅  | `api.MediaSession.setPositionState`                                                        | 76 🎏    | https://bugzilla.mozilla.org/show_bug.cgi?id=1582509 | 78     |                                                                                                                |

Notes:

* ~The original PR used a different structure. For example, referring to the spec's enum for `MediaSessionAction`. `MediaSessionAction` isn't a concrete object; it seems to be an enum only for the purposes of specifying permitted values for the `setActionHandler()` method and the values in the object it passes to the handler function. I've suggested putting this feature data closer to its actual point of use, rather than creating a new (abstract) parent feature.~ Mooted.

**Comment by a2sheppy** [comment]
> The original PR used a different structure. For example, referring to the spec's enum for `MediaSessionAction`. `MediaSessionAction` isn't a concrete object; it seems to be an enum only for the purposes of specifying permitted values for the `setActionHandler()` method and the values in the object it passes to the handler function. I've suggested putting this feature data closer to its actual point of use, rather than creating a new (abstract) parent feature.

So, I disagree here. I believe firmly that we should have BCD records for enums like this. It certainly isn't the first time I've done so. WebXR and WebRTC are full of them, for instance, and I believe I've introduced them to Web Audio as well. I think they're a better way to express this information, since it's a single point of contact for updates and maintenance, and it's trivial for tools using BCD's data to present the information any way they wish.

As for presenting within MDN's text, it's also trivial to embed information about these from the MediaSessionAction page into pages documenting things like `setActionHandler()`. I don't see a good reason not to do it the more flexible way.

**Comment by ddbeck** [comment]
An enum like this presents problems similar to mixins: there's no object that a web developer can interact with called `MediaSessionAction`. The actual argument to `setActionHandler()` is a string.

The compat tree for an enum like this is suggestive of concrete compat data, but is quite difficult to scrutinize. There's lots of potential meanings for an abstract enum, but it's hard for BCD to communicate that meaning (and #6002 itself didn't really attempt to).

Consider `api.MediaSessionAction.nexttrack` as an example:

Does support for `api.MediaSessionAction.nexttrack` mean support for the string `"nexttrack"`? That's trivially true and captured elsewhere.

Perhaps it means that the `"nexttrack"`string is supported in at least one place that expects an enumerated value. That's interesting, but it's not really actionable for a web developer. I'd need a list of supported enums for each of the concrete implementations. To get the full compat story, I'd need, in addition to `api.MediaSessionAction.nexttrack`, features under `api.MediaSession.setActionHandler` to tell me which strings it supports. Which makes me wonder why we'd bother with `api.MediaSessionAction` in the first place.

Or perhaps it means that `"nexttrack"` is supported in _all_ the places that expect an enumerated value. That's kinda interesting but it could create difficult-to-maintain compat data. Suppose a future spec adds a new method to `MediaSession` that uses this enum. If the new method is unsupported in a browser, then it implies that the until-then fully-supported `MediaSessionAction` must be changed to `"partial_implementation": true` even though no part of its support actually changed. That's weird and hard to maintain.

I'm willing to be pragmatic on this stuff though. In the near term, mixins are a problem we're stuck with, though one I think we could confront within BCD, given adequate development time (e.g., building a shared data mechanism; mixins in MDN content is a post-Kuma problem). But for something like this, the surface area of seemingly-duplicate features is quite small. It seems like doing the right thing is in reach and we should do it.

**Comment by a2sheppy** [comment]
Support for `api.MediaSessionAction.nexttrack` means support for the string `nexttrack` anywhere that expects a media session action string. This allows us to easily manage support for these strings across anyplace that makes use of them, both now and in the future. This seems pretty simple to me. I was surprised to find out that anyone was confused by it, as (a) I've been doing this for ages, and (b) as I said, this is a pretty obvious definition for this. Obviously `MediaSessionAction` isn't a real object. And perhaps the BCD `description` and the MDN page should be instead titled "Media Session Action Strings" rather than "MediaSessionAction". Would that help to resolve this?

**Comment by ddbeck** [comment]
I'm receptive to this suggestion. Before you open a PR though, I'd like to get @Elchi3 to make sure I'm not approving unilaterally something novel.

> perhaps the BCD description and the MDN page should be instead titled "Media Session Action Strings" rather than "MediaSessionAction". Would that help to resolve this?

Yes, this sounds like a good compromise to me. That's much clearer about the root `MediaSessionAction` being an abstraction and not a real, named object. I think this still leaves some ambiguity about whether the leaves are supported somewhere (like we do for CSS types) or everywhere (like you've suggested here). But this API is pretty small, so it seems low risk to do that. 👍

> Obviously

Maybe I was a bit slow on this, but I had to read the spec rather closely before I understood the data. If we're lucky I'm a bit of an outlier, but it's not a hypothetical source of confusion. Thank you for your patience, especially in areas where you have a lot of domain expertise.

**Comment by Elchi3** [comment]
I think it is not at all yet _obvious_ how we should best organize dictionaries or enums like `MediaSessionAction`. I think I've been in the camp that also would rather like to see them inline in the docs and inline in BCD and not separated out, but we don't have clear API page structures (recipes) for these types yet. Once these are in place, I think should follow that.

Compromising seems to be a good idea for now especially since you'll probably find both variants in BCD: I believe some enums/dictionaries are inline and others have their own files. I hope we can be more consistent once we have more clarity about our API doc structures.

**Comment by a2sheppy** [comment]
OK, then, what I'll do is change the page name and add a description to the BCD and proceed with that for now.

Here's the PR for the media session action types (`MediaSessionAction`) with the description "Media Session action types": PR #6488.

I've also moved the definitions of these strings on MDN into a new page located at https://wiki.developer.mozilla.org/en-US/docs/Web/API/MediaSessionAction but named "Media Session action types". Adjustments to other pages in the Media Session API reference have been made to work with this change.

More PRs are on the way to continue to flesh out the API but those will be covered elsewhere...

**Comment by ddbeck** [comment]
#6492 and #6488 may have resolved this. I need to step through my table and double-check.

**Comment by ddbeck** [comment]
#6760 will fix `api.MediaSession.setPositionState`, which leaves only `api.MediaSessionAction.scrubTo`.

@foolip regarding the `scrubTo` Media Session action. Is that… real? I can't find any mention of it in the spec, but you participated in https://bugs.chromium.org/p/chromium/issues/detail?id=977375 so I thought you might be able to give me a clue about this.

**Comment by foolip** [comment]
@ddbeck The string "scrubto" or "crub" (allowing for "scrubTo" or "ScrubTo") has never appeared in [Blink's media_session.idl](https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/modules/mediasession/media_session.idl;drc=1aa881a174c40e713c3efaa5d0d7f9d7120d46a5) per my local git log grepping.

The action is however in [media_controller.h](https://source.chromium.org/chromium/chromium/src/+/master:services/media_session/media_controller.h;drc=e5b869b7cdb7a7c0ba4da77cf318f9abcd0acb54) and other places, and probably is used when scrubbing (seeking by dragging) in the lockscreen controls, or something like that.

It's not web exposed however, so shouldn't be in BCD.

**Comment by ddbeck** [comment]
> It's not web exposed however, so shouldn't be in BCD.

Great. Thank you so much, @foolip! I'm closing this now (finally!).
