### ISSUE TITLE
api.MediaSession.playbackState for Firefox is out of date

### ISSUE THREAD

**Issue by ddbeck** [mdn/browser-compat-data#6266]
MediaSession.playbackState is reported as added in Firefox 76: https://bugzilla.mozilla.org/show_bug.cgi?id=1582508. It's unclear if the feature is behind a preference. We ought to closely review the bug or test to figure out its status, then update `api.MediaSession.playbackState` accordingly.

_Originally raised in https://github.com/mdn/browser-compat-data/pull/6002#issuecomment-626688459_

**Comment by a2sheppy** [comment]
Submited PR #6464.
