### ISSUE TITLE
Why is HTMLElement.offsetTop experimental?

### ISSUE THREAD

**Issue by shirotech** [mdn/browser-compat-data#6274]
https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetTop

It seems to have full browser support, was wondering why it is considered experimental? We're keen to use this in production.

**Comment by sideshowbarker** [comment]
Thanks for reporting this. I’ve raised https://github.com/mdn/browser-compat-data/pull/6298 with a fix.
