### ISSUE TITLE
Add extension compat data for Android Browsers

### ISSUE THREAD

**Issue by freaktechnik** [mdn/browser-compat-data#6281]
It appears Chromium based Android browsers are also starting to add extension support. Most prominently there's **Kiwi Browser**, which is open source and likely where other implementations pull from. The Yandex browser apparently also supports extensions, and other browsers like Brave and apparently some others, according to https://www.xda-developers.com/at-least-3-chromium-based-browsers-enable-extensions-support-thanks-kiwi-browser/ working on adding support, too.

CC @rebloor

**Comment by queengooborg** [comment]
Thanks for opening this issue, and sorry it has taken so long to respond!

As nice as it would be to include data for these browsers, the truth of the matter is that they don't have enough market share (at least, as far as I can tell by https://gs.statcounter.com/browser-market-share) for us to add them to BCD.  While our upcoming build-time mirroring plans should resolve about 90% of the maintenance issue, we still won't be able to provide the maintenance efforts required at this point in time.  We may reconsider our stance for adding new browsers (especially Chromium forks) in the future.

Thank you for understanding!
