### ISSUE TITLE
MediaDeviceInfo incorrectly listed as unsupported on iOS

### ISSUE THREAD

**Issue by koenkivits** [mdn/browser-compat-data#6284]
`MediaDevices.enumerateDevices()` is supported in iOS since version 11 ([MDN correctly shows this](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/enumerateDevices)). This method returns a Promise that resolves with an array of `MediaDeviceInfo` objects, which works as expected on iOS. MDN still lists `MediaDeviceInfo` as unsupported on iOS though: https://developer.mozilla.org/en-US/docs/Web/API/MediaDeviceInfo

I think it can be marked as supported?

**Comment by vinyldarkscratch** [comment]
Looks like this was resolved in #2929!
