### ISSUE TITLE
Known Issues: Chrome83 handles getUserMedia constraints ideal value wrong

### ISSUE THREAD

**Issue by Laubeee** [mdn/browser-compat-data#6285]
Can this be added to the known issues?

When I use `getUserMedia` with a frame-rate constraint outside the capable range, chrome (currently on Chrome83) won't start the video at all and throw an error, instead of requesting the closest possible value. Doesnt matter if I use `{ video: { frameRate: 35 } }` or `{ video: { frameRate: { ideal: 35 } } }`, both fail when my device supports max 30hz.

See also: [this SO discussion](https://stackoverflow.com/a/62304632/540725)
It seems the same issue applied to resolution properties in the past

**Comment by jpmedley** [comment]
@rkochman Do you know if this is a real bug or a hardware-related issue. When APIs interact with hardware, they rarely have the ability to report whether the underlying failure is a lack of hardware support. So an API that works on one device model may not work on another. If this is genuinely a bug, a Chrome ticket needs to be opened. If it's the hardware support issue, that's what needs to be in the compat data.

**Comment by rkochman** [comment]
Seems like a bug. Per the engineer: Can you file a bug at crbug.com? Please provide all the information you have, including repro steps, chrome and OS version, and info about the device (e.g., output of video capture tab in chrome://media-internals).

Thanks..

**Comment by Laubeee** [comment]
> Seems like a bug. Per the engineer: Can you file a bug at crbug.com? Please provide all the information you have, including repro steps, chrome and OS version, and info about the device (e.g., output of video capture tab in chrome://media-internals).
> 
> Thanks..

done, see https://bugs.chromium.org/p/chromium/issues/detail?id=1096734
if you need anything else, let me know.

**Comment by Laubeee** [comment]
so, per the comment made there:

> The problem seems to be the presence of the sensor camera, which probably doesn't work with gUM.
For that camera, for which chromium does not know the supported video modes, chromium is assuming it supports some fallback video modes.
In some cases, these fallback modes (which in this case are not really supported), make gUM select the sensor camera instead of the real one when certain constraints are passed to gUM.
A possible mitigation could be to make Chromium ignore the existence of the sensor camera.

It seems to be a bug that only occurs on specific HW (presence of sensor camera)

**Comment by vinyldarkscratch** [comment]
It appears that the Chromium bug has been closed due to lack of response to a test request.  It's uncertain whether this is a bug in Chrome, issues with a flag/extension, or if it's some oddity with your particular webcam.  Is there another bug open with a similar issue (IR sensor mishandled by `getUserMedia`)?

**Comment by Laubeee** [comment]
huh, I thought one of the developers could identify where it's coming from...
Anyway I don't seem to be able to reproduce the error with current chrome (90), so I'll close this.
