### ISSUE TITLE
[SVG] srcset, media queries

### ISSUE THREAD

**Issue by strarsis** [mdn/browser-compat-data#631]
I am not able to find up to date information on these topics:

- How well is `srcset`/`sizes` supported in `<image>` in SVG?
- How well are media queries supported in SVGs?

**Comment by Elchi3** [comment]
I'm sorry this repo doesn't yet provide information on SVG compatibility data.
For media queries in SVG this looks like a good article, https://jakearchibald.com/2016/svg-media-queries/. To get more specific help or information, consulting a forum like StackOverflow might get you better answers than here.

**Comment by strarsis** [comment]
@Elchi3: Thank you for these proposals.
A systematic, automated approach among browsers concerning these features would be great.
This is maybe something for caninuse instead?

**Comment by Elchi3** [comment]
We're planning to add detailed compat about SVG to this repository, it just isn't our top priority right now. We're finishing work on a detailed compat data set about CSS first, and we will likely add SVG compat information some time next year. Stay tuned :)
