### ISSUE TITLE
Add "iPadOS" to label of the "Safari on iOS" column

### ISSUE THREAD

**Issue by a2sheppy** [mdn/browser-compat-data#6326]
We currently label the mobile Safari column "Safari on iOS". We should change this to either "Safari on iOS/iPadOS" or "Safari (iOS/iPadOS)". This will help to ensure clarity.

**Comment by Elchi3** [comment]
The current labeling was discussed with Apple and approved by them, so I don't think we should just change this.
@apple-web-evangelist, what do you think about this suggestion?

**Comment by a2sheppy** [comment]
Was that before or after iPadOS was separated from iOS? I don’t recall the timing of this decision.


Eric "Sheppy" Shepherd
Senior Technical Writer
MDN Web Docs
Mozilla

**Comment by ddbeck** [comment]
See https://github.com/mdn/browser-compat-data/blob/master/docs/data-guidelines.md#safari-for-ios-versioning and #2006 for background on this.

I'm disinclined to do this without some reassurances from Apple that iOS and iPadOS data is strictly equivalent. To change the identifier for iOS to also cover iPadOS now would be a strong retroactive claim about the data. For example, we haven't been asking contributors to show some evidence for both iOS _and_ iPadOS when we're reviewing iOS data. If we changed the identifier, it might give people a false idea about the rigor of that data.

**Comment by othermaciej** [comment]
Maybe it should be a separate column? There's some things that are available in iPadOS Safari but not iOS (for example, Media Source Extensions), and I think also vice versa. Another example is Fullscreen API.

**Comment by vinyldarkscratch** [comment]
iOS and iPadOS are still just about the same OS at this point, and I doubt there will be much compatibility differences in the future.  As such, I don't think that creating a new column and a new browser entry are the right way to go about it.  Since there are few differences in compatibility between Safari for iOS and Safari for iPadOS, using notes has been sufficient.

Of course, there could be major compatibility changes down the line.  Let's see what Apple wants us to do going forward!

**Comment by othermaciej** [comment]
We prefer to align Safari for all platforms when possible, but when there's a split, in the future it will more likely be between macOS+iPadOS on the one hand, and iOS on the other.

**Comment by vinyldarkscratch** [comment]
(I just saw your profile and realize that you work at Apple, @othermaciej -- oops, sorry for not noticing before!)

**Comment by othermaciej** [comment]
No worries, I didn't exactly highlight it. We'll try to come up with a proposal for the best way to handle this issue too.

**Comment by a2sheppy** [comment]
> No worries, I didn't exactly highlight it. We'll try to come up with a proposal for the best way to handle this issue too.

Good deal. I'm fine with dropping this for now then. Glad to have had this discussion though!
