### ISSUE TITLE
CSS aspect-ratio: Claims compatibility in places where it's only available internally

### ISSUE THREAD

**Issue by a2sheppy** [mdn/browser-compat-data#6337]
The compat data for `aspect-ratio` lists it as available on browsers like Firefox where it's still an internal-only attribute not available to web content.

For instance, this is the bug covering implementing it on Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=aspect-ratio

**Comment by ddbeck** [comment]
Fixed by #6903 and #6918.
