### ISSUE TITLE
contextmenu event: Safari on iOS does not support it.

### ISSUE THREAD

**Issue by cookiengineer** [mdn/browser-compat-data#6376]
The contextmenu event isn't supported on iOS 13 and later and needs a lot of quirky hacks with a custom setTimeout() callback in order to behave the same as on other Browsers.

A lot of other issues in libraries claim that this is the result of intermixing touch and pointer events, though this assumption in general is wrong.

In this very simple test case, it won't work on iOS Safari 13+, and will instead open the magnifier overlay that magnifies the text (even if none is there) under it.

Even if you add the `-webkit-user-select: none` (aka `user-select: none` in WebKit nightly) CSS fix to the element, the `contextmenu` event won't be fired.

```html
<!DOCTYPE html>
<html>
	<head>
<style>
#test {
	display: block;
	width: 200px;
	height: 200px;
	background: red;
	/* This Fix ain't working either */
	/* -webkit-user-select: none; */
}
#test.contextmenu {
	background: green;
}
</style>
	</head>
	<body>
		<div id="test"></div>
	<script>
		let element = document.querySelector('#test');
		if (element !== null) {
			element.addEventListener('contextmenu', () => {

				element.className = 'contextmenu';

				setTimeout(() => {
					element.className = '';
				}, 2000);

			});
		}
	</script>
	</body>
</html>
```

**Comment by saschanaz** [comment]
Seems there is a bug about this: https://bugs.webkit.org/show_bug.cgi?id=213953

**Comment by cookiengineer** [comment]
@saschanaz Yes, this bug was indeed filed by me.

**Comment by jculver050** [comment]
Close

**Comment by robatwilliams** [comment]
It's not fired in 12 either
