### ISSUE TITLE
cssFloat incorrectly marked as unsupported in Firefox

### ISSUE THREAD

**Issue by GKFX** [mdn/browser-compat-data#6392]
I don't know which version of Firefox first supported it (presumably a very early one), but `cssFloat` is supported by Firefox now so should not be marked as false:
https://github.com/mdn/browser-compat-data/blob/4c4326016dc01976d0eb1bd5acca35a0116cab2c/api/CSSStyleDeclaration.json#L63-L65

**Comment by vinyldarkscratch** [comment]
This has been resolved by #6976!
