### ISSUE TITLE
file.name works in Safari on iOS and Firefox on Android

### ISSUE THREAD

**Issue by lgommans** [mdn/browser-compat-data#6414]
It is indicated that [Safari on iOS and Firefox on Android have no support at all for `file.name`](https://github.com/mdn/browser-compat-data/blob/e4b9484aed0a116a47f71efe1baf0de06838d135/api/File.json#L227-L242). If I understand it correctly, this should not work:

    <input id=x type=file>
    <script>
        $("#x").onchange = function(){
            doSomethingWith( $("#x").files[0].name );
        };
    </script>

However, it does work when testing with Fennec 68.10.1esr (which is Firefox but recompiled on F-Droid, requiring it to be rebranded due to trademark stuff) as well as on Safari 13.1.2 running on an iOS device.

Do we need to figure out the exact version when it was added before it can be fixed, or can we fix the table to at least be correct for the current versions? The current data seems to have been introduced in [this commit](https://github.com/mdn/browser-compat-data/commit/a85a9f499da574ca4078dbb3b322394bddf6a619) but I don't see any source referenced for those values.

(I also reported this through the MDN page and was linked to the general issue tracker to track my report, but they're not showing up here so I don't know into which fifo that went.)

**Comment by ddbeck** [comment]
If you've tested this API and it works, I'd welcome a PR updating it. Some of the data—especially older data as in the case—was converted from old, hand-written tables on MDN pages, which we didn't closely verify at the time. Based on the age of the API, I'd expect the Android data to map from the desktop Firefox at version 5.
