### ISSUE TITLE
<dialog> support in Firefox

### ISSUE THREAD

**Issue by plonibarploni** [mdn/browser-compat-data#6466]
Firefox has enabled `<dialog>` in Nightly beginning with Firefox 80 (see [bug 1645046](https://bugzilla.mozilla.org/show_bug.cgi?id=1645046)). How should this be reflected in the compat data, if at all?

**Comment by foolip** [comment]
I've tested https://software.hixie.ch/utilities/js/live-dom-viewer/?saved=8406 in Firefox 80 on BrowserStack and Firefox Developer Edition 81 locally shows that it's still a HTMLUnknownElement. It doesn't look like this feature is enabled by default, after all.

**Comment by sideshowbarker** [comment]
At least in current Nightly — 82.0a1 (2020-08-31) — for https://software.hixie.ch/utilities/js/live-dom-viewer/?saved=8406 I get `log: object "[object HTMLDialogElement]"…` (not `HTMLUnknownElement`).

So I wonder if it’s the case that maybe the first release branch this went into was the version 82 branch.

**Comment by sideshowbarker** [comment]
Sorry, ignore my previous comment. I’d forgotten that I have the `dom.dialog_element.enabled` preference set to true in my Nightly. When I set that to false in v82 current Nightly, I also get `HTMLUnknownElement`.

So yeah I agree it doesn’t seem to actually be enabled yet — not even in 82, let alone in 80.

**Comment by smaug----** [comment]
dialog is currently enabled on Nightly only.dom. https://searchfox.org/mozilla-central/rev/0c682c4f01442c3de0fa6cd286e9cadc8276b45f/modules/libpref/init/StaticPrefList.yaml#1590,1593

**Comment by sideshowbarker** [comment]
For the record here, in https://freenode.logbot.info/whatwg/20200901#c4947970 @smaug---- also pointed out to me that `dom.dialog_element.enabled` is set to true by default in Nightly. So manually setting it to false isn’t reflective of the default support.

**Comment by sideshowbarker** [comment]
Paging in @sefeng211 (assignee for https://bugzilla.mozilla.org/show_bug.cgi?id=1645046)

**Comment by queengooborg** [comment]
If something is enabled by default only in Nightly/Aurora/Dev builds, we'd been just mentioning as such in notes.  However, considering that we're working to remove flag data from BCD, I don't feel like this is something we wish to record, since most users will be on the normal builds anyways.
