### ISSUE TITLE
Show Firefox Reality as a separate browser for XR APIs

### ISSUE THREAD

**Issue by Manishearth** [mdn/browser-compat-data#6512]
Currently, on the Browser Compatibility section of WebXR APIs ([example](https://developer.mozilla.org/en-US/docs/Web/API/XRSystem/requestSession#Browser_compatibility), Firefox is listed as "No".

This is correct in that Firefox for Desktop (downloaded from [here](https://www.mozilla.org/en-US/exp/firefox/new/)) does not ship these APIs, however Firefox Reality (downloaded from various app stores) does. This includes Firefox Reality for Hololens, which actually uses a completely different engine (Servo).

It would be nice if, for WebXR APIs, the Browser Compatibility section had an additional column for Firefox Reality. I understand there are issues with the space the section takes up, which is why I'm only proposing this for WebXR APIs.

At the moment Servo and Firefox Reality do not differ in the APIs they ship unpreffed, but if that changes in the future we might need to distinguish there as well.

Other solutions that allow us to clearly show that some APIs are supported on FxR would also work.

cc @a2sheppy

**Comment by a2sheppy** [comment]
I would like for us to find a way to get this referenced in the tables because, well, currently our tables imply that Chrome is the only place to go for WebXR, which isn't true. Finding a way to get this clearly presented in the tables will improve our XR mindshare, I think.

**Comment by a2sheppy** [comment]
I kind of wonder if we could supplant the Firefox for Android column with Firefox Reality in the WebXR documentation, though I doubt that's realistic, and it may be a terrible idea.

**Comment by a2sheppy** [comment]
As for Servo, the trick is that we do this by browser, not runtime. Not sure what to do with that -- especially with Reality using different runtimes on different platforms. Tricky.

**Comment by Manishearth** [comment]
> Not sure what to do with that -- especially with Reality using different runtimes on different platforms. Tricky.

For Servo mostly I think we could get away with pref annotations saying things like "Available behind pref `foo` on Firefox Reality, Available unpreffed on Firefox Reality for Hololens."

However, I do have some interest in having Servo somewhere in the _data_ even if it's not exposed on the website. For example, right now Bikeshed shows the [XRSystem API](https://immersive-web.github.io/webxr/#xrsystem-interface) as being implemented by one browser engine (in the little side bubble) even though it's implemented by three. But this is a smaller issue.

**Comment by Manishearth** [comment]
Also, having servo separate would be useful for feeding into caniuse.

**Comment by jculver050** [comment]
Close

**Comment by Elchi3** [comment]
https://support.mozilla.org/en-US/kb/end-support-firefox-reality
