### ISSUE TITLE
.scrollTo() behavior: 'smooth' property isn't supported on Google Chrome

### ISSUE THREAD

**Issue by Roger-Melo** [mdn/browser-compat-data#6518]
Hi!

.scrollTo() behavior: 'smooth' property isn't supported in Google Chrome. Maybe the compatibility should be changed?

**Comment by ddbeck** [comment]
Thanks for opening this issue. I'd welcome a PR fixing this!

The data in question would be need to be updated in [`/api/ScrollToOptions.json`](https://github.com/mdn/browser-compat-data/blob/52fb1728cbda3a152420839c3a2173c073355767/api/ScrollToOptions.json#L50). It would probably need a note, like Safari. To actually merge such a change, we'd also need some sort of test or reference showing that the feature is unsupported.

Thank you!

**Comment by jpmedley** [comment]
Chromium forks should inherit `smooth` from [ScrollOptions](https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/core/frame/scroll_options.idl). What version of Chrome are you using? Can we see your code?

**Comment by queengooborg** [comment]
I'm closing this because there has been no response for over a year and the `smooth` behavior appears to function as expected.
