### ISSUE TITLE
`request.body.formData` don't work in safari or TP

### ISSUE THREAD

**Issue by jimmywarting** [mdn/browser-compat-data#6520]
I have tried it in safari's console but it don't work. the compatibility table says it is supported...

https://github.com/mdn/browser-compat-data/blob/4c4326016dc01976d0eb1bd5acca35a0116cab2c/api/Body.json#L489

(tested on safari v14)
![image](https://user-images.githubusercontent.com/1148376/90340000-4e306f00-dff5-11ea-81ab-8b4ae4853f14.png)

There is even an open issue about this here:
https://bugs.webkit.org/show_bug.cgi?id=212858

**Comment by jimmywarting** [comment]
Hey 
btw, it later turned out that safari did support `res.formData()` 
but only if the Form has at least one entry (the formdata could not be empty)

```js
// Works
fd = new FormData()
fd.set('a', 'b')
new Response(fd).fromData()
```

```js
// Do not work
fd = new FormData()
new Response(fd).fromData()
```

I later created a WPT test for this and it turns out chrome have this bug too

- wpt: https://github.com/web-platform-tests/wpt/issues/28607
- chrome bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1204594 (still affect chrome 104)
- safari bug: https://bugs.webkit.org/show_bug.cgi?id=225238 (still affect safari 15.6.1)

**Comment by foolip** [comment]
@jimmywarting if you want that to be reflected in BCD, can you file a new issue? A comment on a closed issue will only show up as a notification, and will easily be lost.
