### ISSUE TITLE
Intl.NumberFormat default option useGrouping=true does not work in Safari Version 13.1.2 (15609.3.5.1.3)

### ISSUE THREAD

**Issue by fildaniels** [mdn/browser-compat-data#6525]
![image](https://user-images.githubusercontent.com/5132707/90478199-16c4de00-e12d-11ea-8559-6a039d4f11fc.png)

**Comment by ddbeck** [comment]
It appears that this would be a new subfeature of `api.Intl.NumberFormat.NumberFormat`, like the other `options` keys listed there. My guess is that Safari doesn't yet support _any_ options for `Intl.NumberFormat`.

I'd welcome a PR adding this feature to [`NumberFormat.json`](https://github.com/mdn/browser-compat-data/blob/master/javascript/builtins/intl/NumberFormat.json). Thank you!

**Comment by gilmoreorless** [comment]
I'm not sure I understand this issue. The screenshot shows the feature working correctly.

From the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat):

> `useGrouping`
    Whether to use grouping separators, such as thousands separators or thousand/lakh/crore separators. Possible values are true and false; the default is true.

This matches Safari's behaviour on my machine:

<img width="484" alt="image" src="https://user-images.githubusercontent.com/159415/91296929-c3aff280-e7e0-11ea-9c75-9cc052d2a32d.png">

**Comment by ddbeck** [comment]
@gilmoreorless Thanks for testing this. I've duplicated your results.

I'm going to close this, but if there's more to the story, @fildaniels, please comment. Thank you!
