### ISSUE TITLE
Remove BudgetState and BudgetService APIs

### ISSUE THREAD

**Issue by ddbeck** [mdn/browser-compat-data#6536]
On or after October 16, 2020, the features `api.BudgetState` and `api.BudgetService` (and their descendants) should be removed, in keeping with [the irrelevance guideline](https://github.com/mdn/browser-compat-data/blob/master/docs/data-guidelines.md#removal-of-irrelevant-features).

Related to #6535.

**Comment by jculver050** [comment]
Close
