### ISSUE TITLE
contentBoxSize in ResizeObserverSize is supported in Chrome

### ISSUE THREAD

**Issue by MMDF** [mdn/browser-compat-data#6537]
https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserverEntry/contentBoxSize shows the compat status for chrome to be No. However, I see this property in my Chrome 84.0.4147.125 on macOS. The property differs from the spec in that it is just an Array with a single element which is as the spec describes.

**Comment by sideshowbarker** [comment]
Paging in @jpmedley to get his review on this

**Comment by jpmedley** [comment]
This [shipped in 84](https://storage.googleapis.com/chromium-find-releases-static/1ba.html#1bad5fbcc0e36e2fb16d044a40527b23d231a5df) on all three Chrome flavors, and somebody forgot to tell me.

**Comment by sideshowbarker** [comment]
@MMDF Nice catch — thanks much for having taken time to report this, and sorry for the delay

**Comment by MMDF** [comment]
Glad to be of help!
