### ISSUE TITLE
ANGLE_instanced_arrays: alt. name for Chromium confusing?

### ISSUE THREAD

**Issue by vinyldarkscratch** [mdn/browser-compat-data#6540]
For our data for `ANGLE_instanced_arrays`, we mark it as supported under the alternative name of `ANGLEInstancedArrays`.  However, this may be confusing for web developers, as this alternate name **only** applies to its [implementation within the IDL](https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/modules/webgl/angle_instanced_arrays.idl), and nothing that would matter to web developers.  To access the interface, a user must still use the original name when calling `gl.getExtension()` (AKA `gl.getExtension('ANGLE_instanced_arrays');`, see example below).

<img width="312" alt="Screen Shot 2020-08-19 at 17 10 07" src="https://user-images.githubusercontent.com/5179191/90701932-d6558500-e23e-11ea-973a-73b88003f1d7.png">

I've tested this has been the case in all the Chrome versions, so I'm thinking we should remove the alt. name?  (cc @jpmedley / @foolip)

**Comment by Elchi3** [comment]
> However, this may be confusing for web developers, as this alternate name **only** applies to its [implementation within the IDL](https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/modules/webgl/angle_instanced_arrays.idl), and nothing that would matter to web developers.

Thanks Vinyl, I'm saying exactly the same in this PR: https://github.com/mdn/browser-compat-data/pull/6499
Please use what the spec says and not what's only in Chrome IDL.

**Comment by vinyldarkscratch** [comment]
Sounds good!  I'll spend some time fixing up these alt. names for all the WebGL extensions.  😉

**Comment by Elchi3** [comment]
Given these extensions are a bit of a special snowflake, I also think that we should probably move them to `api/webgl_extensions/ANGLE_instance_arrays.json` etc. but maybe that's for another day.

**Comment by foolip** [comment]
I agree that it's not useful to expose the alternative names here. The interface objects aren't exposed, and the only way to notice the difference in what Blink's IDL says is with something like `Object.getPrototypeOf(canvas.getContext('webgl').getExtension('ANGLE_instanced_arrays')).constructor.name` (or `.toString()`) where one can see "ANGLEInstancedArrays".

**Comment by Elchi3** [comment]
I Firefox I get `[object ANGLE_instanced_arrays]` which is per spec, but I guess it is really minor that Chromiums don't exactly expose that spec name here.

**Comment by Elchi3** [comment]
Same story in #6499 btw, so maybe we can resolve the discussion there, too.
