### ISSUE TITLE
Wrong compatibility data for ServiceWorkerRegistration (Safari on macOS)

### ISSUE THREAD

**Issue by FlorianRaediker** [mdn/browser-compat-data#6557]
According to [web-confluence.appspot.com](https://web-confluence.appspot.com/#!/catalog?releases=%5B%22Edge_18.17763_Windows_10.0%22,%22Safari_13.0.2_OSX_10.15%22,%22Chrome_78.0.3904.70_Windows_10.0%22,%22Firefox_70.0_Windows_10.0%22%5D&q=%22ServiceWorkerRegistration%22), the following properties of `ServiceWorkerRegistration` are not supported by Safari (on macOS):
`getNotifications`, `navigationPreload`, `paymentMethod` and `pushManager`

However, according to [ServiceWorkerRegistration.json](https://github.com/mdn/browser-compat-data/blob/bce11b3da31a3b3425280730360ee42d7cc55328/api/ServiceWorkerRegistration.json), they are all supported since 11.1 or - in case of .paymentMethod - the support is unknown. It looks like this information was mostly added in #1881, which addressed ServiceWorker support in general.

The following table gives an overview of the incorrect data; all of the following properties are not supported by Safari:

| Property of ServiceWorkerRegistration | Supported according to this repository? | Comments |
| -------------------------------------- | ---------------------------------------- | ----------- |
| `getNotifications` | [11.1](https://github.com/mdn/browser-compat-data/blob/bce11b3da31a3b3425280730360ee42d7cc55328/api/ServiceWorkerRegistration.json#L211) | |
| `navigationPreload` | [11.1](https://github.com/mdn/browser-compat-data/blob/bce11b3da31a3b3425280730360ee42d7cc55328/api/ServiceWorkerRegistration.json#L331) | Support for `NavigationPreloadManager` [is currently unknown](https://github.com/mdn/browser-compat-data/blob/bce11b3da31a3b3425280730360ee42d7cc55328/api/NavigationPreloadManager.json#L34), this should probably be changed to unsupported as well |
| `paymentManager` | [unknown](https://github.com/mdn/browser-compat-data/blob/bce11b3da31a3b3425280730360ee42d7cc55328/api/ServiceWorkerRegistration.json#L460) | |
| `pushManager` | [1.11](https://github.com/mdn/browser-compat-data/blob/bce11b3da31a3b3425280730360ee42d7cc55328/api/ServiceWorkerRegistration.json#L568) | The PushManager interface is correctly [marked as not supported](https://github.com/mdn/browser-compat-data/blob/bce11b3da31a3b3425280730360ee42d7cc55328/api/PushManager.json#L45) |

If desired, I can try to create a Pull Request to fix the compatibility data.

**Comment by sideshowbarker** [comment]
> If desired, I can try to create a Pull Request to fix the compatibility data.

Yes please — it’d be great if you could create a PR. If you do, I can commit to reviewing it.

**Comment by FlorianRaediker** [comment]
> Yes please — it’d be great if you could create a PR. If you do, I can commit to reviewing it.

Here it is, would be nice if you could review it!
