### ISSUE TITLE
Remove ie_mobile

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#659]
We're thinking about removing ie_mobile from the redesigned compat tables (see https://discourse.mozilla.org/t/beta-testing-new-compatability-tables/21269 on how to get the new table design on MDN).

I'm also wondering if it's really worth to keep maintaining compat data about ie_mobile in this repository. It's a discontinued mobile browser and seems really hard to find information about what was supported once. Also, unlike IE desktop, it had no real relevance to web developers.

So, are there any arguments for not removing ie_mobile from
a) the redesigned table
b) the data ?

cc @erikadoyle

**Comment by erikadoyle** [comment]
No arguments from our side--let's remove it. Thanks!

**Comment by a2sheppy** [comment]
As much as I tend to oppose outright removing information, this is a case where it makes sense, I agree.

**Comment by Elchi3** [comment]
We removed `ie_mobile`.
