### ISSUE TITLE
TODO for future Opera releases

### ISSUE THREAD

**Issue by foolip** [mdn/browser-compat-data#6601]
A tracking bug for a few things that will need updating in the future for Opera and Opera for Android, based on what is in Chromium.

Chromium M84:
  - [ ] [ContentIndex and ContentIndexEvent](https://github.com/mdn/browser-compat-data/pull/6547) (Android only)
  - [ ] [Element.getAnimations()](https://github.com/mdn/browser-compat-data/pull/6592)

**Comment by foolip** [comment]
@ddbeck FYI that I've filed this and https://github.com/mdn/browser-compat-data/issues/6602. Can you keep an eye out for updates in browsers/opera.json? We can try it once and if it works, maybe formalize it all with labels and whatnot?

**Comment by foolip** [comment]
I closed https://github.com/mdn/browser-compat-data/issues/6602 as not useful. I guess this too wouldn't be useful if someone updates all Opera data for each release. I guess nobody is doing that?

**Comment by ddbeck** [comment]
Hey @foolip, I opened #6561 which sorta covers how we might do this. How do you feel about scoping this to a specific release (M84)? I kinda like the idea of making sure our issues have some sort of criteria to help us know when to close them, rather than letting them live on perpetuity.

**Comment by foolip** [comment]
Sure, I'd be happy for you to rename/reformat this issue, or close it and create a new one.

**Comment by foolip** [comment]
I didn't keep updating this issue, and I think the approach is completely unworkable, but nevertheless I've sent https://github.com/mdn/browser-compat-data/pull/7300 to mirror the two things I did note to close this issue.

**Comment by ddbeck** [comment]
@foolip Yeah, I agree this isn't really working. https://github.com/mdn/browser-compat-data/pull/7020#issuecomment-722739785 also suggests this is not going to happen properly. I think your diff tool might be a better route for us, actually. I'll update in #6561.

In the mean time, we should not continue to expand on this issue.
