### ISSUE TITLE
TODO for future Samsung Internet releases

### ISSUE THREAD

**Issue by foolip** [mdn/browser-compat-data#6602]
A tracking bug for a few things that will need updating in the future for Samsung Internet, based on what is in Chromium.

Chromium M84:
  - [ ] [ContentIndex and ContentIndexEvent](https://github.com/mdn/browser-compat-data/pull/6547)

**Comment by foolip** [comment]
@AdaRoseCannon do you have any use for tracking issues like this? I just saw https://github.com/mdn/browser-compat-data/pull/6589...

**Comment by AdaRoseCannon** [comment]
Not especially as I mostly use the script for cloning the appropriate chrome data for each version then manually fixing the points where we differ.

**Comment by foolip** [comment]
Alright, I'll go ahead and close this.
