### ISSUE TITLE
Update api.Body.formData for Safari 14.1

### ISSUE THREAD

**Issue by foolip** [mdn/browser-compat-data#6620]
A tracking bug for a few things that will need updating for future releases of Safari and Safari for iOS. This might be guesses based on what's currently in Safari Technology Preview, or recent commits to WebKit.

Safari 14.1:
- [ ] api.Body.formData (https://github.com/mdn/browser-compat-data/pull/6616, https://github.com/mdn/browser-compat-data/pull/6619, https://webkit.org/b/215671, https://trac.webkit.org/r266087)

@apple-web-evangelist FYI. If there's anything that could be done to make it easier to update Safari data for each release, that would be great :D

**Comment by foolip** [comment]
This idea of a tracking issue didn't work out.

**Comment by foolip** [comment]
However, there was one TODO which is still in the future, so renaming and reopening to track just that one thing.

**Comment by jculver050** [comment]
Close
