### ISSUE TITLE
Mirroring script: account for flags, alt. names, etc. better

### ISSUE THREAD

**Issue by queengooborg** [mdn/browser-compat-data#6625]
This comment was made in response to the Chrome -> Edge mirroring to check if Chrome is `false`:

> This bit makes me wonder what happens for a feature behind a flag. This script doesn't seem to handle flags at all. The data for Edge seems to mostly have flags copied, but it seems to me there's still a bug waiting here: if the feature was added behind a flag in Chrome, `chromeFalse` will still end up false here, and we'll mark it as supported in Edge. I've verified this by modifying Bluetooth.json locally.
> 
> I think we'll need a step where support statements are pre-processed to apply flags, alternative_name, and perhaps more.
> 
> It's fine to do that in a follow-up though, it's a generic problem, not specific to mirroring Edge.

_Originally posted by @foolip in https://github.com/mdn/browser-compat-data/pull/6582#discussion_r478951583_

**Comment by jculver050** [comment]
Close

**Comment by queengooborg** [comment]
Since this was opened, mirroring has been greatly simplified for Edge as it no longer considers IE data for mirroring.  Closing this as resolved.
