### ISSUE TITLE
Describe how IE's writing-mode implementation differs

### ISSUE THREAD

**Issue by ddbeck** [mdn/browser-compat-data#6641]
The note on `css.properties.writing-mode` for IE is not particularly descriptive:

https://github.com/mdn/browser-compat-data/blob/35be77ac695a6eba53c3615a072fe7a57a6807fa/css/properties/writing-mode.json#L72

It'd be nice to research how the implementation differs and provide a more descriptive summary in place of this note (and the other notes like it in this file).

**Comment by jculver050** [comment]
Close

**Comment by queengooborg** [comment]
I'm closing this issue since the IE data was frozen a few releases back.
