### ISSUE TITLE
Document mirroring subtleties and best practices

### ISSUE THREAD

**Issue by ddbeck** [mdn/browser-compat-data#6662]
Mirroring from one browser to another is a good way to complete some browser data, but there's complexities and quirks that aren't self-evident. We should have a contributor doc that describes:

* known mirroring relationships (e.g., Chrome to Edge)
* notable deviations from mirroring (e.g., WebVeiw doesn't support Chrome's flags; some features may be toggled off on Android)
* pitfalls (e.g., Safari and Safari for iOS versioning schemes aren't actually the same; you can't mirror browsers before they've released a corresponding version)

This is probably related to #6561.

**Comment by queengooborg** [comment]
Since we've moved to automatic mirroring using a "mirror" keyword, I think that the need to describe these complexities isn't as important as when it was a script that modified the data directly and required manual review.  I think we can close this.
