### ISSUE TITLE
Add HTMLVideoElement#playsInline

### ISSUE THREAD

**Issue by saschanaz** [mdn/browser-compat-data#6663]
It seems Blink and WebKit support the attribute.

**Comment by foolip** [comment]
@vinyldarkscratch I see that https://mdn-bcd-collector.appspot.com/tests/api/HTMLVideoElement/playsInline returns true, so this should be a simple test case for adding entirely new entries based on the collector results.

**Comment by saschanaz** [comment]
Fixed by #7604
