### ISSUE TITLE
Edge data for -webkit-mask-repeat-x seems wrong

### ISSUE THREAD

**Issue by foolip** [mdn/browser-compat-data#6669]
https://github.com/mdn/browser-compat-data/pull/2907 set this as support in Edge 18.

However, running these tests on Edge 18 it does not seem to be supported:
https://software.hixie.ch/utilities/js/live-dom-viewer/?saved=6782
https://mdn-bcd-collector.appspot.com/tests/css/properties/-webkit-mask-repeat-x

@merih do you know what might be going on here? Might there be more from https://github.com/mdn/browser-compat-data/pull/2907 that is incorrect?

**Comment by jculver050** [comment]
Close
