### ISSUE TITLE
Compat data for most Intl.Collator options are missing

### ISSUE THREAD

**Issue by pacien** [mdn/browser-compat-data#6680]
The browser compatibility table for `Intl.Collator` lacks entries for most of the documented options (`numeric`, `usage`, etc).

* page: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Collator/Collator
* source: browser-compat-data/javascript/builtins/intl/Collator.json

**Comment by jculver050** [comment]
Close
