### ISSUE TITLE
api.Element.accessKey should be removed

### ISSUE THREAD

**Issue by foolip** [mdn/browser-compat-data#6697]
This data is used on https://wiki.developer.mozilla.org/en-US/docs/Web/API/Element/accessKey, but the API is actually on HTMLElement: https://html.spec.whatwg.org/multipage/dom.html#htmlelement

https://wiki.developer.mozilla.org/en-US/docs/Web/API/HTMLElement/accessKey should be created, https://wiki.developer.mozilla.org/en-US/docs/Web/API/Element/accessKey archived, and then api.Element.accessKey deleted from BCD.

Judging by [Confluence](http://web-confluence.appspot.com/#!/catalog?releases=%5B%22Edge_18.17763_Windows_10.0%22,%22Safari_13.0.2_OSX_10.15%22,%22Chrome_78.0.3904.70_Windows_10.0%22,%22Firefox_70.0_Windows_10.0%22%5D&q=%22accessKey%22), `accessKey` hasn't been on `Element` in any browser for any of the browsers in Confluence. (If it had, a row with all red for the browsers shown would still be listed.)

**Comment by foolip** [comment]
https://wiki.developer.mozilla.org/en-US/docs/Web/API/HTMLElement/accessKey exists now, with a little help from @jpmedley after I messed up the creation. The data there is a lot more useful than https://wiki.developer.mozilla.org/en-US/docs/Web/API/Element/accessKey, which just points to `HTMLElement`.

@ddbeck how does one go about archiving https://wiki.developer.mozilla.org/en-US/docs/Web/API/Element/accessKey and could the BCD entry be removed right after it's been archived?

**Comment by ddbeck** [comment]
@foolip The BCD can be removed even before archiving the page, since it doesn't reach the site until we do a BCD release (and a deploy by the dev team). So you can open a PR for that whenever.

In the mean time, I've asked about the privileges and process for archiving pages. I'll get back to this when I have an answer.

**Comment by foolip** [comment]
@ddbeck I've sent https://github.com/mdn/browser-compat-data/pull/6746 to remove the entry.

**Comment by ddbeck** [comment]
OK, `Element.acessKey` redirects to `HTMLElement.accessKey` now.
