### ISSUE TITLE
api.Element.attributeStyleMap should be on HTMLElement/SVGElement/MathMLElement

### ISSUE THREAD

**Issue by foolip** [mdn/browser-compat-data#6698]
The spec for this is here: https://drafts.css-houdini.org/css-typed-om-1/#declared-stylepropertymap-objects

The attribute isn't on `Element` directly, but on the subinterfaces of `Element` that the browser supports, which may or may not include `MathMLElement`.

**Comment by jculver050** [comment]
Close

**Comment by vinyldarkscratch** [comment]
Looks like this was fixed by #10686!
