### ISSUE TITLE
Gamepad#hapticActuators is supported in Chrome

### ISSUE THREAD

**Issue by saschanaz** [mdn/browser-compat-data#6701]
The Firefox flag is also wrong, it's `dom.gamepad.extensions.enabled` instead of `dom.gamepad-extensions.enabled`.

**Comment by saschanaz** [comment]
Also Gamepad#hapticActuators and GamepadHapticActuator.

**Comment by vinyldarkscratch** [comment]
The data for Gamepad itself has been fixed in #7885!
