### ISSUE TITLE
Animation#updatePlaybackRate is supported on Chrome

### ISSUE THREAD

**Issue by saschanaz** [mdn/browser-compat-data#6703]
Also:

* Animation#pending
* Animation#ready
* Animation#updatePlaybackRate
* AnimationPlaybackEvent

**Comment by saschanaz** [comment]
Mostly fixed by https://github.com/mdn/browser-compat-data/pull/9274 except Animation#updatePlaybackRate.

**Comment by ddbeck** [comment]
Opened #10126 to resolve this.
