### ISSUE TITLE
Remove duplicated items

### ISSUE THREAD

**Issue by saschanaz** [mdn/browser-compat-data#6708]
For example, Window#isSecureContext and WindowOrWorkerGlobalScope#isSecureContext coexist.

**Comment by foolip** [comment]
There is unfortunately a lot of this going on around mixins, and no consensus on what we should do with them, see https://github.com/mdn/browser-compat-data/issues/472. 😢

**Comment by jculver050** [comment]
Close

**Comment by jculver050** [comment]
Close

**Comment by saschanaz** [comment]
Fixed by #11518
