### ISSUE TITLE
onpushsubscriptionchange is not supported in Chrome and Firefox

### ISSUE THREAD

**Issue by saschanaz** [mdn/browser-compat-data#6715]
Same as PushSubscriptionChangeEvent, at least per https://mdn-bcd-collector.appspot.com/tests/.

**Comment by vinyldarkscratch** [comment]
The data for the event interface itself was fixed in #10763, #10863, and #11322!  The event handler _does_ seem to be supported in Firefox as reported by the collector, however.  We'll probably need to do some more digging into this one.

**Comment by Elchi3** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1157108 and https://chromestatus.com/feature/6242325854420992 also say `onpushsubscriptionchange`/ the `pushsubscriptionchange` event is supported in Firefox. I guess we can close this given the interface was fixed.
