### ISSUE TITLE
HTMLIFrameElement#allowPaymentRequest is available without preference in Chrome

### ISSUE THREAD

**Issue by saschanaz** [mdn/browser-compat-data#6724]

**Comment by jculver050** [comment]
Close

**Comment by Elchi3** [comment]
https://chromestatus.com/feature/5511036157296640 has some version numbers for this.

https://bugs.chromium.org/p/chromium/issues/detail?id=1127988 is the bug to deprecate/remove it in Chromium. 

Firefox already removed in 83.
