### ISSUE TITLE
api.RTCPeerConnection.canTrickleIceCandidates - supported on Chrome

### ISSUE THREAD

**Issue by saschanaz** [mdn/browser-compat-data#6732]

**Comment by Elchi3** [comment]
Seems to be supported since version 82.

https://groups.google.com/g/discuss-webrtc/c/5igOLQMgseg?pli=1
https://bugs.chromium.org/p/chromium/issues/detail?id=708484
https://storage.googleapis.com/chromium-find-releases-static/47b.html#47bfc2a8519a67075c592a34d4496d174bce43d7
