### ISSUE TITLE
Interim project goals

### ISSUE THREAD

**Issue by ddbeck** [mdn/browser-compat-data#6738]
## Background

Right now, MDN doesn't have full-time staff focused on managing BCD ([read more about this on Hacks](https://hacks.mozilla.org/2020/08/an-update-on-mdn-web-docs/)). As a contractor, this has led to me being a mostly-solo caretaker for BCD, while MDN revises its goals and establishes long-term project plans.

In the interest of transparency and to calibrate expectations, I've decided to lay out my near-term goals for BCD and what I hope that means for the project.

## Current goals

In rough order of priority, this is where **my** focus is going to be:

1. Provide project continuity. This means maintaining high expectations for data quality, issuing releases on most Thursdays, and preserving a welcoming, convivial project culture.
2. Share the work. Answer questions and document processes that help others contribute to BCD and work on reducing the "lottery factor" for continuing efforts on BCD.
3. Review routine data pull requests and provide timely feedback to contributors.

I expect other contributors to have their own goals and aspirations—to scratch their own itch, as it were—and I want to support that. In short, I want to help you to help keep the project going.

## A principle: don't make any difficult-to-revert decisions

Points one and two are slightly in tension with each other: sometimes making decisions means breaking with the past. To the extent that I'm able to, I plan to make decisions that permit us to experiment, try things, and change our mind.

The principle that's going to guide me is this: favor decisions that are easy to revert. This may lead to some untidiness in data structure, or writing more verbose notes, or asking contributors for more issues or documentation, but I hope it will ensure that BCD's future can fit into whatever's next for MDN and the needs of BCD’s other consumers.

That said, I don't expect this exact posture to remain forever, so please expect refinements and changes as we go.

## Thanks

I know several people have stepped up their participation here recently, or continued your ongoing efforts to contribute to BCD. Thank you, thank you, thank you. This is essential to keeping BCD healthy.

**Comment by ddbeck** [comment]
CCing @vinyldarkscratch, @jpmedley, @sideshowbarker, @foolip. You're the most active Peers right now, so I wanted to first emphasize my thanks to you. Plus I wanted to make sure you saw what my focus was going to be in the near term. Thank you!

**Comment by foolip** [comment]
Thank you @ddbeck, it's been a pleasure working in the project so far! The principle of avoiding difficult-to-revert decisions is one that I can easily get behind right now, and is actually one that might help resolve certain long-standing issues, at least tentatively.

For my own involvement in the project, I would say my goals are twofold:
- That api.* entries exist for everything that has been exposed in any browser in the past two years.
- That api.* are 100% real data.

That sounds simple enough when written down, but actually represents a mountain of work. @vinyldarkscratch is doing *a lot* work here now, and believe we can do it!

For MDN readers and for caniuse.com, the effect I'm hoping for is that the compat tables will never mislead people into avoiding an API which is well supported, or conversely but less common, thinking that an API is widely supported when it is not.

**Comment by foolip** [comment]
There are also side benefits to high-quality API data that I'm exploring: https://github.com/microsoft/TSJS-lib-generator/issues/918

**Comment by ddbeck** [comment]
This issue has faded from relevance. We weathered some complicated times and I think we have a better idea of where we'll all headed now. Thanks, everyone!

**Comment by foolip** [comment]
Thanks for steering the ship steadily through those times!
