### ISSUE TITLE
Inconsistent naming of at-rules

### ISSUE THREAD

**Issue by eduardoboucas** [mdn/browser-compat-data#674]
Is there any reason why `@font-face` compat data is at `css['at-rules']['font-face']` (without `@`) but `@counter-style` is at `css['at-rules']['@counter-style']` (with `@`)?

Thanks!

**Comment by ddbeck** [comment]
No, there's no reason, sorry. They're supposed to be consistent but apparently I missed this one with #629. Oops!

**Comment by eduardoboucas** [comment]
No problem at all! Thanks for the prompt reply. 🙂

**Comment by Elchi3** [comment]
This should be fixed (on master now, will be in the next release).
