### ISSUE TITLE
References to "Edge OS"

### ISSUE THREAD

**Issue by RichardD2** [mdn/browser-compat-data#6740]
Any implementation notes for Chrome which refer to "Chrome OS" appear to have been copied verbatim to Edge, along with references to "Edge OS". Unless that's referring to the OS specifically used to manage an EdgeRouter, those references are incorrect.

For example, see the Edge implementation notes for:
https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getDisplayMedia#Browser_compatibility

> On Windows and **Edge OS** the entire system audio can be captured, ...

**Comment by vinyldarkscratch** [comment]
Ack, good catch!  Most of this data was generated by a script that mirrors Chrome -> Edge, and in turn replaces the word "Chrome" with "Edge".  Didn't think about Chrome OS...  😅

I'll be sure to adjust the mirroring script to accommodate!

**Comment by ddbeck** [comment]
@vinyldarkscratch can we fix the "Edge OS" mentions without the bulk update process? Only two files seem to contain a mention of it (and varations—found with `rg -i '(edge) ?os'`)
