### ISSUE TITLE
Unsupported features should not have flag/partial_implementation data

### ISSUE THREAD

**Issue by queengooborg** [mdn/browser-compat-data#6742]
When working on #6679, I noticed that the linter doesn't prevent features with `"version_added": false` from having `flags`, `partial_implementation`, `prefix`, or `alternative_name`.  I don't think that it makes sense for an unsupported feature to have anything other than a note.  We should add statements to the linter that prevent flags/partial implementation if support is `false`.

**Comment by ddbeck** [comment]
Something that would be helpful to move on this: how many features are currently affected by this. If there are few (or no) features with `"version_added": false` and unexpected fields, then it's pretty easy to change the schema to prevent it. If not, there's a data quality project to work on before we can clamp down the schema.

**Comment by jculver050** [comment]
Close

**Comment by ddbeck** [comment]
This wasn't resolved by #15551. The PR did remove the data, but didn't change the schema or linting to prevent it from happening in the future.
