### ISSUE TITLE
Pipeline operator is available in Firefox 58+

### ISSUE THREAD

**Issue by Akiyamka** [mdn/browser-compat-data#6747]
https://github.com/mdn/browser-compat-data/blob/master/javascript/operators/pipeline.json

Under flag `--enable-pipeline-operator`
https://bugzilla.mozilla.org/show_bug.cgi?id=1405943

**Comment by Elchi3** [comment]
Thanks for your issue!

If features are behind a compile or configuration flag, we're marking support as `false`. 
(If this would ship under a user-settable preference, then we would add the preference info. Not the case here, however)
