### ISSUE TITLE
Certain MessagePort members are available on Firefox for Android where the compatibility chart says they are not

### ISSUE THREAD

**Issue by edbaafi** [mdn/browser-compat-data#6748]
<img width="1020" alt="Screen Shot 2020-09-22 at 3 24 12 PM" src="https://user-images.githubusercontent.com/1187708/93928462-5e202a80-fce8-11ea-9629-16c4494fc05e.png">

from https://developer.mozilla.org/en-US/docs/Web/API/MessagePort it would seem that `MessagePort` (and thus `MessageChannel`) is essentially broken in Firefox for Android.  This page claims no support for `message` events, `onmessage` event handlers, or the `postMessage` method.  However it seemed odd that onmessageerror was listed as supported when the message event wasn't so I tried this demo (https://mdn.github.io/dom-examples/channel-messaging-basic/ ) in a simulator with the latest Firefox for Android:

<img width="925" alt="Screen Shot 2020-09-22 at 3 09 07 PM" src="https://user-images.githubusercontent.com/1187708/93928525-76904500-fce8-11ea-8cd1-102fffb3eb91.png">

The demo clearly uses `message` events, the `onmessage` handler, and the `postMessage` method so the docs seem to be wrong or at least outdated.  I'm not sure the exact version this works from or I would just make a pull request.  I suppose the API's that are tested could just be changed to `YES` and those that aren't tested could be changed to `?` but perhaps others have a more definitive way of verifying support.  I read the contribution guidelines and sadly I could not find any bug stating that this was fixed/added, although I also couldn't find anything that would explain why the compat data was originally uploaded with all these `NO` values.

**Comment by edbaafi** [comment]
@vinyldarkscratch I'd like to fix this so others don't have to go through the testing I had to, or to assume these APIs aren't universally available and avoid using them.  Should I just submit a pull request with FF for Android indicating `YES` since I have no idea why these were initially marked as unavailable and thus can't find a bug that indicates when this was "fixed".   As far as I can tell there is no special handling for these APIs in FF for Android vs FF proper.

**Comment by ddbeck** [comment]
Thanks for your patience on this, @edbaafi. I'd welcome a PR updating [`MessagePort.json`](https://github.com/mdn/browser-compat-data/blob/master/api/MessagePort.json). Since we don't have version numbers for most of the Firefox data in that set of features, then `true` values would be acceptable for now, or we could work on finding specific values in the course of the PR.

**Comment by jculver050** [comment]
Close

**Comment by vinyldarkscratch** [comment]
This has been partially resolved in #7890, but it seems that some of the events haven't been updated yet.

**Comment by queengooborg** [comment]
Looks like the event data was updated in #13015!
