### ISSUE TITLE
Chrome on iOS should be separately tracked.

### ISSUE THREAD

**Issue by vicary** [mdn/browser-compat-data#6758]
For example, constructor option `currencyDisplay` in `Intl.NumberFormat(...)` in iOS only supports "code", "symbol", or "name". Using "narrowSymbol" will throw in iOS 14, this neither matches Chrome Safari (assuming WebView) nor vanilla Chrome.

**Comment by vinyldarkscratch** [comment]
I think you may be confusing WebView and WebKit.  WebView is a browser API for Android devices so that developers may integrate website support into their apps.  WebKit is the name of the engine that powers Safari, and iOS/iPadOS support is indicated through the "Safari for iOS" column.

Does that help?

**Comment by vicary** [comment]
Please correct me if I am wrong, I've heard that Chrome in iOS is asked to use the native engine (not sure it's `UIWebView` or `WKWebView`) so I'm assuming they should have the same behavior in iOS.

**Comment by vinyldarkscratch** [comment]
This is correct, all browsers on iOS and iPadOS must use Safari's engine, which is WebKit (not WebView).  In this repository, the "WebView" column refers to the rendering engine on Android.

I don't do iOS development so I hadn't heard of `UIWebView` (deprecated) or `WKWebView`.  After doing some research, it looks like internally, Apple _also_ uses the name "WebView" to refer to an interactive web content object inside of an app, in other words the same sort of infrastructure as Android's WebView.  I'm assuming that the `WK` in `WKWebView` stands for "WebKit".

**Comment by vinyldarkscratch** [comment]
Closing this issue since there's been no more activity and the question seems to be answered.  If you have any further inquiries regarding this, feel free to reply to this issue and I'll be happy to reopen it!
