### ISSUE TITLE
Track release notes in the repository

### ISSUE THREAD

**Issue by ddbeck** [mdn/browser-compat-data#6759]
Right now, release notes are in GitHub's [releases page](https://github.com/mdn/browser-compat-data/releases) only. This is probably OK, but it would be good to put them into git. This would make writing release notes collaborative and incremental, add a layer of review, and duplicate them outside a proprietary tool.

To do this we'd need:

- [x] copy existing release notes into a `RELEASE_NOTES.md` or similar
- [x] docs for how to write and update the notes
- [x] change the release notes script to update the file and use it as a source for adding a new release to GitHub

**Comment by jculver050** [comment]
Close

**Comment by vinyldarkscratch** [comment]
I believe it's safe to close this issue, as you've now done every step in that checklist?

**Comment by ddbeck** [comment]
Yes, thank you!
