### ISSUE TITLE
Update Compatibility Data on window.status

### ISSUE THREAD

**Issue by Yash-Singh1** [mdn/browser-compat-data#6761]
The `window.status` variable is now removed for security reasons. It should not be compatible:
https://www.w3schools.com/jsref/prop_win_status.asp

**Comment by ddbeck** [comment]
Related to #7255. This is one of several features specified as obsolete: https://html.spec.whatwg.org/multipage/window-object.html#dom-window-status

> For historical reasons, the status attribute on the Window object must, on getting, return the last string it was set to, and on setting, must set itself to the new value. When the Window object is created, the attribute must be set to the empty string. It does not do anything else.

So this is supported, but it shouldn't do anything other than store and return a string. https://github.com/mdn/browser-compat-data/blob/4a9c9810013c0a72cddc07148674dee5fb938e22/api/Window.json#L9181 I suspect the data is correct, but the status needs updating.

**Comment by Yash-Singh1** [comment]
@ddbeck Agreed

**Comment by sideshowbarker** [comment]
Raised https://github.com/mdn/browser-compat-data/pull/7383
