### ISSUE TITLE
HTMLElement.focus() at IE8

### ISSUE THREAD

**Issue by 853419196** [mdn/browser-compat-data#6764]
When I tried to use the HTMLElement.focus() function on IE8, I found it worked. But the data in the database pointed out that the function does not work on IE8. Is this a bug?
Link: https://developer.mozilla.org/docs/Web/API/HTMLElement/focus

**Comment by ddbeck** [comment]
Thanks for checking on this data! Our data sometimes contains mistakes and this looks like one of them. If you'd like to update this entry, then you'd need to update the data in [`HTMLElement.json`, around line 891 in the current file](https://github.com/mdn/browser-compat-data/blob/master/api/HTMLElement.json#L891). I'd welcome a pull request switching the value for IE to version 8. Thanks again!

**Comment by jculver050** [comment]
Close

**Comment by vinyldarkscratch** [comment]
Looks like this was resolved in #7247!
