### ISSUE TITLE
Remove totally unimplemented things

### ISSUE THREAD

**Issue by saschanaz** [mdn/browser-compat-data#6768]
Below are interfaces that have never been implemented per the data, or just no data.

Marked as deprecated/obsolete:

- [x] [BluetoothAdvertisingData](https://developer.mozilla.org/docs/Web/API/BluetoothAdvertisingData)
- [x] [DOMConfiguration](https://developer.mozilla.org/docs/Web/API/DOMConfiguration)
- [x] [DOMImplementationList](https://developer.mozilla.org/docs/Web/API/DOMImplementationList)
- [x] [HTMLIsIndexElement](https://developer.mozilla.org/docs/Web/API/HTMLIsIndexElement)
- [x] [Notation](https://developer.mozilla.org/docs/Web/API/Notation)
- [x] [PushRegistrationManager](https://developer.mozilla.org/docs/Web/API/PushRegistrationManager)
- [x] [SVGColorProfileElement](https://developer.mozilla.org/docs/Web/API/SVGColorProfileElement)
- [x] [SVGSolidcolorElement](https://developer.mozilla.org/docs/Web/API/SVGSolidcolorElement)
- [x] [SVGAltGlyphDefElement](https://developer.mozilla.org/docs/Web/API/SVGAltGlyphDefElement)
- [x] [SVGAltGlyphItemElement](https://developer.mozilla.org/docs/Web/API/SVGAltGlyphItemElement)
- [x] [SVGFontElement](https://developer.mozilla.org/docs/Web/API/SVGFontElement)
- [x] [SVGFontFaceElement](https://developer.mozilla.org/docs/Web/API/SVGFontFaceElement)
- [x] [SVGFontFaceFormatElement](https://developer.mozilla.org/docs/Web/API/SVGFontFaceFormatElement)
- [x] [SVGFontFaceNameElement](https://developer.mozilla.org/docs/Web/API/SVGFontFaceNameElement)
- [x] [SVGFontFaceSrcElement](https://developer.mozilla.org/docs/Web/API/SVGFontFaceSrcElement)
- [x] [SVGFontFaceUriElement](https://developer.mozilla.org/docs/Web/API/SVGFontFaceUriElement)
- [x] [SVGGlyphElement](https://developer.mozilla.org/docs/Web/API/SVGGlyphElement)
- [x] [SVGGlyphRefElement](https://developer.mozilla.org/docs/Web/API/SVGGlyphRefElement)
- [x] [SVGHKernElement](https://developer.mozilla.org/docs/Web/API/SVGHKernElement)
- [x] [SVGMissingGlyphElement](https://developer.mozilla.org/docs/Web/API/SVGMissingGlyphElement)
- [x] [SVGRenderingIntent](https://developer.mozilla.org/docs/Web/API/SVGRenderingIntent)
- [x] [SVGTRefElement](https://developer.mozilla.org/docs/Web/API/SVGTRefElement)
- [x] [SVGVKernElement](https://developer.mozilla.org/docs/Web/API/SVGVKernElement)

Not an interface nor a mixin:

- [x] [ConstrainULong](https://developer.mozilla.org/docs/Web/API/ConstrainULong)
- [x] [RTCIceCandidateType](https://developer.mozilla.org/docs/Web/API/RTCIceCandidateType)
- [x] [RTCIceComponent](https://developer.mozilla.org/docs/Web/API/RTCIceComponent)
- [x] [ULongRange](https://developer.mozilla.org/docs/Web/API/ULongRange)

Experimental (probably okay to exist):

- [x] [PerformanceFrameTiming](https://developer.mozilla.org/docs/Web/API/PerformanceFrameTiming)
- [x] [RTCIdentityAssertion](https://developer.mozilla.org/docs/Web/API/RTCIdentityAssertion)
- [x] [RTCIdentityProviderGlobalScope](https://developer.mozilla.org/docs/Web/API/RTCIdentityProviderGlobalScope)
- [x] [RTCIdentityProviderRegistrar](https://developer.mozilla.org/docs/Web/API/RTCIdentityProviderRegistrar)
- [x] [RTCStatsEvent](https://developer.mozilla.org/docs/Web/API/RTCStatsEvent)
- [x] [SVGFilterPrimitiveStandardAttributes](https://developer.mozilla.org/docs/Web/API/SVGFilterPrimitiveStandardAttributes)
- [x] [SVGMeshElement](https://developer.mozilla.org/docs/Web/API/SVGMeshElement)
- [x] [SVGURIReference](https://developer.mozilla.org/docs/Web/API/SVGURIReference)

**Comment by sideshowbarker** [comment]
+1 to removing all of those. And it seems like a good list at first glance — but it’d also be great if we could have reproducible automation/script anybody could run themselves that’d programatically identify such ought-to-be-removed features.

Otherwise, without going in and manually double-checking one-by-one each feature in the list in the issue description, nobody has any way to know if some feature might have crept into the list by mistake but shouldn’t actually be included — nor whether there are features missing from the list which should have been included.

**Comment by guest271314** [comment]
Should implemented and not specified be removed or remain?

**Comment by ddbeck** [comment]
Yeah, I'm supportive of removing never-implemented features. We have a [data guideline](https://github.com/mdn/browser-compat-data/blob/master/docs/data-guidelines.md#removal-of-irrelevant-features) that is meant to cover just such situations. That said, a lot of these have corresponding MDN pages and a pretty old, so it's probably worth the effort to make sure these things actually don't exist in browsers (and not do a mass deletion). 

> Should implemented and not specified be removed or remain?

Yes. BCD tracks the things browsers actually do, even if they're non-standard. We do have [status information](https://github.com/mdn/browser-compat-data/blob/master/schemas/compat-data-schema.md#status-information) to note this, however.

**Comment by saschanaz** [comment]
I think we can immediately remove "Not an interface nor a mixin" things, what do you think?

**Comment by saschanaz** [comment]
Do we want to remove experimental-but-unimplemented things here or should I keep them? I guess notes to tracking bugs would be helpful if we want to keep them.

**Comment by ddbeck** [comment]
@saschanaz Yeah, I think it makes sense to take a look at anything that hasn't been implemented, experimental or not. For each one, we could take a closer look to see if it's in an active spec or if an implementation is in progress. Then we can use notes to make it clear what's going on with those features that we should retain, or remove them if not.

**Comment by jculver050** [comment]
Close

**Comment by sideshowbarker** [comment]
The following elements all had been included in the issue description here, but subsequently the data was updated to reflect that they all actually have been implemented, in WebKit.

* [SVGAltGlyphDefElement](https://developer.mozilla.org/docs/Web/API/SVGAltGlyphDefElement)
* [SVGAltGlyphItemElement](https://developer.mozilla.org/docs/Web/API/SVGAltGlyphItemElement)
* [SVGFontElement](https://developer.mozilla.org/docs/Web/API/SVGFontElement)
* [SVGFontFaceElement](https://developer.mozilla.org/docs/Web/API/SVGFontFaceElement)
* [SVGFontFaceFormatElement](https://developer.mozilla.org/docs/Web/API/SVGFontFaceFormatElement)
* [SVGFontFaceNameElement](https://developer.mozilla.org/docs/Web/API/SVGFontFaceNameElement)
* [SVGFontFaceSrcElement](https://developer.mozilla.org/docs/Web/API/SVGFontFaceSrcElement)
* [SVGFontFaceUriElement](https://developer.mozilla.org/docs/Web/API/SVGFontFaceUriElement)
* [SVGGlyphElement](https://developer.mozilla.org/docs/Web/API/SVGGlyphElement)
* [SVGGlyphRefElement](https://developer.mozilla.org/docs/Web/API/SVGGlyphRefElement)
* [SVGHKernElement](https://developer.mozilla.org/docs/Web/API/SVGHKernElement)
* [SVGMissingGlyphElement](https://developer.mozilla.org/docs/Web/API/SVGMissingGlyphElement)
* [SVGRenderingIntent](https://developer.mozilla.org/docs/Web/API/SVGRenderingIntent)
* [SVGTRefElement](https://developer.mozilla.org/docs/Web/API/SVGTRefElement)
* [SVGVKernElement](https://developer.mozilla.org/docs/Web/API/SVGVKernElement)

I edited the issue description to mark them in strikethrough — but it seems like it’d be fine to further edit the issue description to completely remove any mention of them.

**Comment by queengooborg** [comment]
I just did a check and found that everything has either been removed or actually is supported, so this is now good to close!
