### ISSUE TITLE
Chromium does not support RTCDataChannel.binaryType = "blob"

### ISSUE THREAD

**Issue by guest271314** [mdn/browser-compat-data#6770]
Chromium and Chrome browsers do not support `channel.binaryType = "blob"` https://bugs.chromium.org/p/webrtc/issues/detail?id=2276

That is not clear at 
- https://developer.mozilla.org/en-US/docs/Web/API/RTCDataChannel
- https://developer.mozilla.org/en-US/docs/Web/API/RTCDataChannel/binaryType
where the compatibility data just states

> `binaryType`
> Yes

which is not a complete dataset. 

The table needs to be expanded to include row and column for `"blob"` and `"arraybuffer"` support.

**Comment by jculver050** [comment]
Close
