### ISSUE TITLE
Chrome Android shows compatibility for speechSynthesis.onboundary however doesnt work

### ISSUE THREAD

**Issue by clarodanesh** [mdn/browser-compat-data#6772]
On Chrome Android regardless of TTS engine selected, the onboundary event does not fire see: [bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1122143&q=1122143&can=2)

**Comment by joaoeudes7** [comment]
Any notice?

**Comment by clarodanesh** [comment]
> Any notice?

no notice so far

**Comment by sideshowbarker** [comment]
Raised https://github.com/mdn/browser-compat-data/pull/7385
