### ISSUE TITLE
Add range for Safari ≤3?

### ISSUE THREAD

**Issue by vinyldarkscratch** [mdn/browser-compat-data#6807]
Considering how challenging it is to test Safari 1-2, I'm thinking we should add a range for Safari 3 and lower?

**Comment by foolip** [comment]
@vinyldarkscratch you've recently been sending PRs setting Safari versions <3, did you work out a way to test Safari 1-2?

In any case, I certainly supporting adding ranges where it's very hard to test older versions, for whatever reason.

**Comment by vinyldarkscratch** [comment]
I have a way to test Safari 1-2, yes, but it's very challenging.  To put it simply, I have a Windows XP virtual machine that runs a PowerPC emulator, with an unreliable network bridge between them (before the network bridge, I typed out the tests manually.) Some days, I simply cannot get the VM to function properly at all...

**Comment by foolip** [comment]
I see, that doesn't sounds reasonable to just distinguish between things introduced in 2003 vs. 2007, both are in the distant past now.

How about Safari 3, how does one test that? The oldest available on BrowserStack is now Safari 4.

**Comment by vinyldarkscratch** [comment]
I have a collection of VMs for browser versions older than what is in SauceLabs (though I should probably add Edge 13-14 for BrowserStack), of which are available here: https://drive.google.com/drive/folders/1w6nVUMD5MwkoevzuhCDuDpbxyk3ywCRY This collection includes Safari 3, of which was the first version supported on Windows, thus eliminating the need for emulating it on PowerPC.

**Comment by foolip** [comment]
Aha, Safari for Windows. I would expect there are some differences between that and OS X, so testing on OS X on as old versions of Safari as possible would be good still.

Anyway, ≤3 seems reasonable.
