### ISSUE TITLE
Edge supports Navigator#share only on Windows

### ISSUE THREAD

**Issue by saschanaz** [mdn/browser-compat-data#6817]
... at least since version 85, while Chrome does not. (It's a partial support as the return value never rejects)

**Comment by juner** [comment]
chromium edge support Navigator#share 81 or later. (windows only.) \
https://caniuse.com/web-share \
https://github.com/Fyrd/caniuse/pull/5567

SUPPORTED Build Number 88 ... \
https://developer.microsoft.com/en-us/microsoft-edge/status/webshareapi/?q=web%20share

**Comment by saschanaz** [comment]
But Edge 88 doesn't exist, does it? Even Canary is version 87 currently.

**Comment by juner** [comment]
@saschanaz  Version 89 has arrived in the canary.
[We've updated you to the latest build. This is Microsoft Edge Canary Build 89.0.720.0](https://www.microsoftedgeinsider.com/en-us/welcome/update?channel=canary&version=89.0.720.0)
[Feature: Web Share API](https://www.chromestatus.com/feature/5668769141620736)
[Feature: Web Share API Level 2](https://www.chromestatus.com/feature/4777349178458112)

**Comment by saschanaz** [comment]
Fixed by https://github.com/mdn/browser-compat-data/pull/6829, but AFAIK it's only available on Windows, as also pointed in the [intent-to-ship](https://groups.google.com/a/chromium.org/g/blink-dev/c/GfVrt1CwxK8/m/i9Rv8Jp5BwAJ?pli=1). @vinyldarkscratch ?

**Comment by jculver050** [comment]
Close

**Comment by saschanaz** [comment]
#9444 correctly mark macOS as unsupported and the same should be done for Edge.
