### ISSUE TITLE
Many notes on api.Document.* refer to the spec-only HTMLDocument alias

### ISSUE THREAD

**Issue by foolip** [mdn/browser-compat-data#6839]
Many entries in api.Document.* have notes like this one for api.Document.alinkColor:
> Before Chrome 64, this property was accessed through the <code>HTMLDocument</code> alias.

This refers to the `HTMLDocument` property being defined as an alias in https://html.spec.whatwg.org/multipage/window-object.html:
> For historical reasons, `Window` objects must also have a writable, configurable, non-enumerable property named `HTMLDocument` whose value is the `Document` interface object.

However, this aliasing has happened only in the spec, no implementation has followed, see https://github.com/whatwg/html/issues/4792.

It would be better if these notes refer to what is actually in implementations, and refer to the `HTMLDocument` interface.

@vinyldarkscratch I spotted these notes while reviewing https://github.com/mdn/browser-compat-data/pull/6820.

**Comment by ddbeck** [comment]
@foolip, do you know if this is resolved? Were these all fixed by #6865?

**Comment by foolip** [comment]
There is one note about an issue like this which still remains:
https://github.com/mdn/browser-compat-data/blob/b79d65e3abdc2d9b1986cae0fa0467561dc8ee5c/api/Document.json#L933-L940

It seems to me this can just be made consistent with the other notes.

**Comment by foolip** [comment]
I've sent https://github.com/mdn/browser-compat-data/pull/10683 to fix that last case and filed https://github.com/mdn/browser-compat-data/issues/10682 about the inconsistency of it all :)
