### ISSUE TITLE
Remove api.Document.contains

### ISSUE THREAD

**Issue by vinyldarkscratch** [mdn/browser-compat-data#6841]
This feature's MDN URL is a 404, and is assumed to be a duplicate of the inherited `api.Node.contains`.

**Comment by foolip** [comment]
Closing as a dupe of https://github.com/mdn/browser-compat-data/issues/6832, sorry I should have linked that in context where I asked about this entry!

**Comment by vinyldarkscratch** [comment]
Oops, sorry, forgot to check for duplicates!
