### ISSUE TITLE
place-self supported in Safari 14.0 (or earlier?)

### ISSUE THREAD

**Issue by janosh** [mdn/browser-compat-data#6846]
According to https://caniuse.com/mdn-css_properties_place-self_flex_context which sources its data here, `place-self` is not supported in any version of Safari.

However, testing with Safari 14.0 on macOS 10.15.7, `place-self` is working just fine as shown here:

![place-self](https://user-images.githubusercontent.com/30958850/94992820-bed32100-058c-11eb-95da-43e4c7c8ecd5.png)

`place-items` and `place-content` have been supported since Safari 11.0 so either there's been a mistake here and `place-self` has been supported for a while as well or support for it was added in the update to 14.0 on Sep 17, 2020.

## HTML for testing

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body style="display: grid; height: 100vh">
    <div
      style="width: 100px; height: 100px; background: black; place-self: center"
    ></div>
  </body>
</html>
```

**Comment by janosh** [comment]
Looks like this data was added in #711.

**Comment by janosh** [comment]
Related issue over at Fyrd/caniuse#5638.

**Comment by sideshowbarker** [comment]
Yeah — thanks for catching this and taking time to report it. I think `place-self` has been in Safari for relatively quite a while now — several releases back. Anyway, I’ll investigate and raise a PR with an update (after I figure out the exact release).

**Comment by sideshowbarker** [comment]
Raised https://github.com/mdn/browser-compat-data/pull/6847
