### ISSUE TITLE
Should webextensions include `standard_track: false`?

### ISSUE THREAD

**Issue by saschanaz** [mdn/browser-compat-data#6851]
From #6813:

I found that some webext APIs are marked as `standard_track: false` and thus got flags: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/theme_experiment

![image](https://user-images.githubusercontent.com/3396686/95226271-065fe400-07fd-11eb-839c-ed8d719a4204.png)

But do we want it? Every webext APIs are nonstandard so I think it's not very helpful to have such flag. Can we skip `standard_track` only for those?

**Comment by saschanaz** [comment]
Or maybe even `standard_track: null` where standard doesn't exist?

**Comment by ddbeck** [comment]
The status block is optional in `webextensions`, though I'm not sure if the individual members of `status` are optional. It's probably best to drop status blocks (or perhaps the standard_track key—not sure if that's allowed) in those cases.

**Comment by saschanaz** [comment]
I heard the browser extension community group intends to restart, so maybe worth waiting.

**Comment by Elchi3** [comment]
See also https://github.com/mdn/browser-compat-data/issues/618

**Comment by queengooborg** [comment]
#17471 disallows the `status` property for web extensions altogether, so I think that it's safe to close this issue as resolved.
