### ISSUE TITLE
Guideline proposal: operating system limitations imply partial_implementation

### ISSUE THREAD

**Issue by ddbeck** [mdn/browser-compat-data#6906]
It's not always clear when to use `partial_implementation`. One case that feels pretty clear-cut however, is when a feature that otherwise has no reason to be limited by operating system only works on a specific OS. I'm proposing a wording along these lines:

> If a browser or engine is available on more than one operating system and a feature only works on a subset of those operating systems, then the support statement should set `"partial_implementation": true`. For example, if a browser supports both Windows and Linux, but only implements a feature on Windows, then a support statement for that feature should should set `"partial_implementation": true`.
>
> However, this guideline does not apply to features where the browser's expected behavior is conditional on the behavior of the operating system. For example, a browser can fully implement a CSS media query even if an underlying operating system can never satisfy the media query's condition because it does not support the requisite hardware.

This seems kinda clear to me, but I'd love some early input before moving toward a PR.

@foolip and @vinyldarkscratch this was inspired by a few comments in #6840. I'd appreciate your take on this.

**Comment by foolip** [comment]
That seems very clear to me, including the final caveat.

**Comment by vinyldarkscratch** [comment]
Having `partial_implementation` sounds good to me, yeah!

**Comment by UZ334334** [comment]
> It's not always clear when to use `partial_implementation`. One case that feels pretty clear-cut however, is when a feature that otherwise has no reason to be limited by operating system only works on a specific OS. I'm proposing a wording along these lines:
> 
> > If a browser or engine is available on more than one operating system and a feature only works on a subset of those operating systems, then the support statement should set `"partial_implementation": true`. For example, if a browser supports both Windows and Linux, but only implements a feature on Windows, then a support statement for that feature should should set `"partial_implementation": true`.
> >
> > However, this guideline does not apply to features where the browser's expected behavior is conditional on the behavior of the operating system. For example, a browser can fully implement a CSS media query even if an underlying operating system can never satisfy the media query's condition because it does not support the requisite hardware.
> 
> This seems kinda clear to me, but I'd love some early input before moving toward a PR.
> 
> @foolip and @vinyldarkscratch this was inspired by a few comments in #6840. I'd appreciate your take on this.
