### ISSUE TITLE
Decide if/how to mark up feature data to indicate missing platform functionality on desktop (examples: HTMLElement.enterKeyHint, inputmode, autocapitalize)

### ISSUE THREAD

**Issue by sideshowbarker** [mdn/browser-compat-data#6914]
See discussion at https://github.com/mdn/browser-compat-data/pull/6891#discussion_r504456062

**Comment by makotokato** [comment]
There is same issues on `inputmode` (https://github.com/mdn/browser-compat-data/issues/6921) and `autocapitalize`.
Blink implements DOM binding on all platforms, but these attributes aren't used as UX.

**Comment by sideshowbarker** [comment]
> There is same issues on `inputmode` (#6921) and `autocapitalize`.
> Blink implements DOM binding on all platforms, but these attributes aren't used as UX.

Thanks — I’ve updated the issue title to mention those as well

**Comment by ddbeck** [comment]
@sideshowbarker I opened issue #6906 for dealing with `"partial_implementation"`'s relationship to OS limitations. Does the guideline text there help with this?

**Comment by sideshowbarker** [comment]
> @sideshowbarker I opened issue #6906 for dealing with `"partial_implementation"`'s relationship to OS limitations. Does the guideline text there help with this?

Yeah — that was a great update, so thanks for taking time to put it together

**Comment by jculver050** [comment]
Close

**Comment by jculver050** [comment]
Close

**Comment by queengooborg** [comment]
I believe that #6906 covers this issue well, so I am going to go ahead and close it...three years later than it probably should have been closed.  :P
