### ISSUE TITLE
HTML: Add <nobr> element to compat data

### ISSUE THREAD

**Issue by a2sheppy** [mdn/browser-compat-data#697]
The non-standard <nobr> element should be included in the compat database, since it was supported by some browsers and is included in our documentation.

**Comment by amitsin6h** [comment]
@Elchi3 @a2sheppy can I work on this issue.

**Comment by a2sheppy** [comment]
Please do.

Eric Shepherd
Senior Technical Writer
MDN Web Docs: https://developer.mozilla.org/
Blog: http://www.bitstampede.com/
Twitter: http://twitter.com/sheppy

On Dec 5, 2017 at 8:14 AM, Amit singh <notifications@github.com> wrote:


@Elchi3 <https://github.com/elchi3> @a2sheppy <https://github.com/a2sheppy>
can I work on this issue.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/mdn/browser-compat-data/issues/697#issuecomment-349300484>,
or mute the thread

**Comment by a2sheppy** [comment]
Yeah. That's why I think we just need to update the page on MDN to use the
compat data.

-- 
Eric Shepherd
Senior Technical Writer
Mozilla Developer Network
https://developer.mozilla.org/
Blog: http://www bitstampede.com/
Twitter: https://twitter.com/sheppy


On Dec 14, 2017 at 5:34 AM, Jean-Yves Perrier <notifications@github.com>
wrote:


I think does exist: see
https://github.com/mdn/browser-compat-data/blob/master/html/elements/nobr.json

@a2sheppy <https://github.com/a2sheppy> Is this issue just about adding the
table in the MDN page?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/mdn/browser-compat-data/issues/697#issuecomment-351686264>,
or mute the thread

**Comment by teoli2003** [comment]
I don't know why you didn't see the new table, but I updated the article on Sep 19th, months before you opened the issue. And I do see the new table.
A refresh problem?

Anyway, I'm closing this as there is nothing to fix.
