### ISSUE TITLE
Merge MDN deprecation notes into BCD?

### ISSUE THREAD

**Issue by saschanaz** [mdn/browser-compat-data#6975]
Currently MDN documents have their own deprecation notes, which sometimes deviates from BCD data. For example, [PerformanceNavigation](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceNavigation) has a deprecation note on MDN but is not marked as deprecated on BCD. Could we merge those notes into BCD and make MDN use it?

**Comment by ddbeck** [comment]
I think this is something that might be plausible in [the new MDN platform](https://github.com/mdn/yari). I'd suggest reopening this issue there, @saschanaz. It'd be super nice to let BCD drive that aspect of MDN content.

**Comment by saschanaz** [comment]
Some MDN documents has customized deprecation notes, as the aforementioned PerformanceNavigation does. BCD needs to use string field for `deprecated` field if we merge such notes. What do you think?

**Comment by ddbeck** [comment]
I've been thinking about this for a bit and I'm still inclined to say that this is out of scope for BCD. It's tempting to bring this information into BCD, but I don't think that it is, strictly speaking, compatibility information.

The actual deprecation flag seems like a significant qualifier to the actual compat data we have. A deprecated feature might have cross-browser support, but that information is deeply misleading without an indicator that the feature is deprecated.

But what alternatives are available to you could be quite editorialized (e.g., there might be more than one plausible alternative to a deprecated feature and which one you choose isn't definitive) or complex (e.g., there are several interrelated features which supplant the deprecated one). It feels risky to bring that content into BCD itself and, in any case, it doesn't change the underlying compatibility data.

I guess what I'm saying is, whether or not something is compatible is in scope for BCD, but precisely what to do about it isn't. I'm going to close this, but thank you for nudging me to consider this idea—not a bad one, just one that doesn't quite fit here.
