### ISSUE TITLE
selectionchanged data incompleted

### ISSUE THREAD

**Issue by jcampbell05** [mdn/browser-compat-data#6985]
The data provided to caniuse.com for the selectionchanged event is incomplete https://caniuse.com/?search=selectionchange

If you compare this to the actual data they have on the spec https://caniuse.com/?search=selection

The incomplete nature of this data makes it not very useful  to know if its useable or not and paints a misleading picture

**Comment by queengooborg** [comment]
It appears that this data has been since updated and populated with real values, which matches CanIUse's data closely!  I'm going to close this issue accordingly, but if you still think there's something missing from BCD's data, let us know and we'll be happy to get right on it.  :)
