### ISSUE TITLE
Help data consumers reason about what matters in the real world

### ISSUE THREAD

**Issue by foolip** [mdn/browser-compat-data#6986]
A while back I filed [Compatibility panel warns about CSS cursor property, which is fairly harmless and not actionable](https://bugzilla.mozilla.org/show_bug.cgi?id=1659649) which was closed as WONTFIX because of resource constraints, and:

> Right now, the Compatibility panel uses data as is from the MDN Compatibility repository. Perhaps it's more actionable to open this issue on that project. Its results feed into the Compatibility panel in Firefox DevTools.

While I think quality of results is ultimately the responsibility of the product, maybe there is something that could be done in BCD? Other data consumers might have similar needs.

To address only the case given in the bug report, we would need a "do things degrade gracefully in the absence of support" test which could be applied for either a whole CSS property, or a CSS property+value.

**Comment by Elchi3** [comment]
Thanks for raising this! I now remember this was discussed similarly with webhint already. 
I think this is a dupe of https://github.com/mdn/browser-compat-data/issues/3365.

**Comment by foolip** [comment]
@Elchi3 I agree, this is a dupe of https://github.com/mdn/browser-compat-data/issues/3365, I'll subscribe to that.
