### ISSUE TITLE
notifications.onButtonClicked is not yet implemented, but is claimed to be in FF 47.0

### ISSUE THREAD

**Issue by makyen** [mdn/browser-compat-data#7]
The [current code](http://mxr.mozilla.org/mozilla-central/source/toolkit/components/extensions/ext-notifications.js#155) has notifications.onButtonClicked events ignored:
`onButtonClicked: ignoreEvent(context, "notifications.onButtonClicked"),`
This is because buttons are not yet implemented ([comment from the code](http://mxr.mozilla.org/mozilla-central/source/toolkit/components/extensions/ext-notifications.js#106)):

> // FIXME: Lots of options still aren't supported, especially
> // buttons.

**Comment by wbamberg** [comment]
Thanks for reporting this! -> https://github.com/mdn/browser-compat-data/commit/48737c535692968be6d61d0d1b8d907ba53295a7.
