### ISSUE TITLE
Update feGaussianBlur browser compatibility

### ISSUE THREAD

**Issue by zineeworld** [mdn/browser-compat-data#7006]
as-is 2020.10.22.
![image](https://user-images.githubusercontent.com/12759765/96809560-152dd400-1456-11eb-9043-313c3f2c4e79.png)

to-be
IE : >=10 
<img width="1260" alt="ie9" src="https://user-images.githubusercontent.com/12759765/96817994-87ed7e00-145b-11eb-85c4-c6d07c2c9f93.png">
<img width="1267" alt="ie10" src="https://user-images.githubusercontent.com/12759765/96817996-89b74180-145b-11eb-90f2-0e35c8497c48.png">
<img width="1262" alt="ie11" src="https://user-images.githubusercontent.com/12759765/96818001-8b810500-145b-11eb-8799-ede67fe87a51.png">

Chrome : YES
<img width="1532" alt="chrome" src="https://user-images.githubusercontent.com/12759765/96817984-8459f700-145b-11eb-8245-562b66a6a543.png">

**Comment by foolip** [comment]
Resolved by https://github.com/mdn/browser-compat-data/pull/7007. 감사합니다!
