### ISSUE TITLE
focus-visible landed in Chrome 86

### ISSUE THREAD

**Issue by jakub-g** [mdn/browser-compat-data#7009]
Source: https://www.chromestatus.com/feature/5823526732824576

Relevant file:
https://github.com/mdn/browser-compat-data/blob/master/css/selectors/focus-visible.json#L10-L27

(I don't know how to edit the JSON to tell "67 with flag, 86 without flag)

**Comment by sideshowbarker** [comment]
> (I don't know how to edit the JSON to tell "67 with flag, 86 without flag)

Yeah, I guess the JSON syntax used for that’s a bit unintuitive/quirky:

```json
"chrome": [
  {
    "version_added": "86"
  },
  {
    "version_added": "67",
    "flags": [
      {
        "name": "#enable-experimental-web-platform-features",
        "type": "preference",
        "value_to_set": "enabled"
      }
    ]
  }
]
```
…that is, you need to change the object into an array of objects.

But at https://github.com/mdn/browser-compat-data/blob/master/schemas/compat-data-schema.md#the-support_statement-object it is actually documented with a good example of exactly that.

Anyway, now you know for next time :) For this I went ahead and raised #7011.

**Comment by sideshowbarker** [comment]
Quick work! — change merged to the main branch just now. Thanks much for raising this @jakub-g

**Comment by jakub-g** [comment]
Thx folks, that was fast! ⚡
