### ISSUE TITLE
Intl.ListFormat supported in all Chromium based Edge versions

### ISSUE THREAD

**Issue by netizen-ais** [mdn/browser-compat-data#7022]
[Intl.ListFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/ListFormat) works in every Edge release using chromium base (tested)

**Comment by sideshowbarker** [comment]
Thanks — I’ve opened https://github.com/mdn/browser-compat-data/pull/7027 for this
