### ISSUE TITLE
Travis wedged? Merge PRs anyway?

### ISSUE THREAD

**Issue by sideshowbarker** [mdn/browser-compat-data#7159]
https://travis-ci.org/github/mdn/browser-compat-data/pull_requests shows that Travis has not run CI automation for most all our PRs submitted over the last 24 hours.

https://www.traviscistatus.com/ shows that status of the service overall is OK — there’s no service-wide problem — so it seems we have some project-specific problem.

I have no idea how to troubleshoot a problem with Travis like this, and I can’t find any info at https://travis-ci.org/ about how to report a problem to them. So it seems like we’re on our own.

Given that the Node.js CI GithHub Actions automated check is running fine, should we just go ahead and merge any PRs that have been reviewed and approved and that are green for Node.js CI GithHub Actions check?

**Comment by vinyldarkscratch** [comment]
That'd be my fault, haha -- with the mass number of PRs I submitted about 48 hours ago, Travis has been running quite slowly as it seems to only check one PR/branch/commit in a repository at a time.  As we're phasing out Travis, however (and since results will be the same as the GitHub Actions check), feel free to merge PRs regardless of the status for Travis!

**Comment by sideshowbarker** [comment]
> That'd be my fault, haha -- with the mass number of PRs I submitted about 48 hours ago,

Ah OK yeah — I figured that might have something to do with it

> Travis has been running quite slowly as it seems to only check one PR/branch/commit in a repository at a time

Yipes.. I didn’t know Travis had that serious of a limitation on throughput for processing of builds — but knowing that, I’m now even more glad we’re phasing out Travis

> As we're phasing out Travis, however (and since results will be the same as the GitHub Actions check), feel free to merge PRs regardless of the status for Travis!

OK,  thanks much — I’ll go ahead now and close this, then

**Comment by foolip** [comment]
Can we go ahead and merge PRs without waiting for Travis to finish? @ddbeck?

**Comment by ddbeck** [comment]
@foolip Yes, go ahead and merge without Travis if (and only if) the GitHub Actions CI passes. We'll drop Travis CI for good when we merge #7155 (probably Thursday afternoon or Friday).
