### ISSUE TITLE
Upgrade to Prettier 2.x

### ISSUE THREAD

**Issue by ddbeck** [mdn/browser-compat-data#7163]
~~Blocked on #6640, #5931 and #6741.~~

After we upgrade to Node.js 10+ (see #5931), we should upgrade to Prettier 2+. It's one of several upgrades which have been blocked by Node.js 8 support.

When we upgrade, we need to:

- [ ] revert #6110 
- [x] remove it from the dependabot config (see #6741)
- [ ] fix any files found to be malformatted as a consequence

**Comment by jculver050** [comment]
Close
