### ISSUE TITLE
Missing api.HTMLInputElement.width entry

### ISSUE THREAD

**Issue by foolip** [mdn/browser-compat-data#7165]
We have the `height` entry:
https://github.com/mdn/browser-compat-data/blob/af4fb4307e0812ba51ed9cb9c9277f4a749f59a1/api/HTMLInputElement.json#L484

But no `width` entry, even though it's just as much a part of the spec:
https://html.spec.whatwg.org/multipage/input.html#dom-input-width

**Comment by foolip** [comment]
@vinyldarkscratch how hard would it be to teach update-bcd.js to add new entries like this based on test results?

**Comment by vinyldarkscratch** [comment]
I'd imagine that adding in new results shouldn't be too tricky!  I imagine that we can mostly automate setting the `status` variables, which would be the most challenging part.

**Comment by foolip** [comment]
Setting them all to a value that would fail the lint and require a human to change them would also be okay, and very simple :)

**Comment by foolip** [comment]
This was fixed in https://github.com/mdn/browser-compat-data/pull/7671.
