### ISSUE TITLE
BarcodeDetector is not supported by Chrome on all platforms

### ISSUE THREAD

**Issue by foolip** [mdn/browser-compat-data#7184]
I realized this when asked to review https://chromium-review.googlesource.com/c/chromium/src/+/2508448

https://developer.mozilla.org/en-US/docs/Web/API/BarcodeDetector#Browser_compatibility doesn't reflect this. I don't know exactly when support was added on each platform, but we should figure that out. `BarcodeDetector` was still exposed unconditionally, so mdn-bcd-collector will be misled.

cc @vinyldarkscratch @reillyeon

**Comment by saschanaz** [comment]
The support status says it's version 83. https://www.chromestatus.com/feature/4757990523535360

**Comment by foolip** [comment]
Yep, and that must be wrong too :) chromestatus.com doesn't supporting recording different versions per platform.

**Comment by saschanaz** [comment]
Well, mdn-bcd-results says Chrome 81 didn't have it on Windows/macOS and Chrome 83 has it on both Windows/macOS, so it should be either 82 or 83.

**Comment by reillyeon** [comment]
The API was made visible on all platforms at the same time in 83, but has not ever been supported on Windows, Linux and Chrome OS. Chrome OS support should be launching in Chrome 88 which is why the patch @foolip was reviewing included that in the stable list.

**Comment by ddbeck** [comment]
Discovered this via #9030 (closed as duplicate). 

> The API was made visible on all platforms at the same time in 83

This doesn't appear to be the case. In addition to the report from #9030, testing on BrowserStack seems to show that `BarcodeDetector` is undefined on Windows, but exposed on macOS, as one example.

It's a bit ugly, but here are the changes that ought to happen in BCD now:

- For the applicable desktop browsers, set `partial_implementation` on `BarcodeDetector` to `true` and add a note that says what platform(s) are unsupported (e.g., "Not supported on Windows or Linux."). This follows [our guideline](https://github.com/mdn/browser-compat-data/blob/master/docs/data-guidelines.md#operating-system-limitations-imply-partial_implementation) on per-OS limitations.
- `window.BarcodeDetector` isn't in BCD yet. Whatever we do for `api.BarcodeDetector` ought to be reiterated with a new `api.Window.BarcodeDetector` feature.

When additional platforms get support, we'll need to update or add notes accordingly. If platforms get it sequentially, then it'll be a lot of notes. For example, "From 83 to X, not supported on Windows or Linux." and "From X, not supported on Windows." and so on until we can have a new non-partial support statement). I suppose we should leave this issue open until that happens.

**Comment by ilyestearti5** [comment]
So Resume,
Barcode detector work only in mobile and macOs ? That it!
