### ISSUE TITLE
Issues with CSS Font Loading APIs

### ISSUE THREAD

**Issue by foolip** [mdn/browser-compat-data#7231]
A few things I noticed while reviewing https://github.com/mdn/browser-compat-data/pull/7225...

## Chromium constructor

`FontFaceSet` should have a constructor, but doesn't in Chrome. This constructor isn't represented in BCD, but should be.

## WebKit events

While WebKit doesn't have the `FontFaceSetLoadEvent` interface, it does have the `onloading`, `onloadingdone` and `onloadingerror` event handler attributes on `FontFaceSet`:
https://trac.webkit.org/browser/webkit/trunk/Source/WebCore/css/FontFaceSet.idl?rev=269244#L48

And yet, it never creates and fires events named "loading", "loadingdone" or "loadingerror", it seems. There's a FIXME for the first:
https://trac.webkit.org/browser/webkit/trunk/Source/WebCore/css/FontFaceSet.cpp?rev=269244#L196

We should add notes or use `partial_implementation` for `onloading`, `onloadingdone` and `onloadingerror` to say that the events are never actually fired.

**Comment by foolip** [comment]
@vinyldarkscratch can you add the missing constructor using mdn-bcd-collector test results?

**Comment by vinyldarkscratch** [comment]
The constructor was taken care of in #8097, so it looks like we can close this issue!
