### ISSUE TITLE
Compatibility data out of date?

### ISSUE THREAD

**Issue by kbrandwijk** [mdn/browser-compat-data#724]
I was reading https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt and noticed it was missing some compatibility info on Edge. 
![image](https://user-images.githubusercontent.com/852069/34065626-0cd04eb4-e204-11e7-8168-b9240aa9e5c4.png)

So I came over here to update it, and found the correct entry here: https://github.com/mdn/browser-compat-data/blob/1090ee7c9ec6348d285af5f104e6017f5b4c7b53/javascript/builtins/globals.json#L705-L719

As you see, the value is already there, but it doesn't show on the website.

**Comment by kbrandwijk** [comment]
Thanks for the tip about the rerender. It looks good for me now too, so closing this...

**Comment by Elchi3** [comment]
> Generally speaking, it always takes a few days before commits to this repo show up on MDN. For kumascript, you can see the current status on What's Deployed but I don't think there's something similar for the compat data.

We are making this data available as an npm package which KumaScript can use. I'm usually releasing a new version every Monday, but as a Mozilla employee I attended a company-wide meetup last week, so there was no release last week. Sorry about that. I plan to publish a new version at end of my Monday (CET) today.
