### ISSUE TITLE
Investigate GitHub Actions labeler misses

### ISSUE THREAD

**Issue by ddbeck** [mdn/browser-compat-data#7250]
The GitHub Actions labeling workflow seems to be missing some files. Reported in https://github.com/mdn/browser-compat-data/pull/7244#issuecomment-720845154.

It might be a misconfiguration or it might be that we're affected by a bug in `actions/labeler`: https://github.com/actions/labeler/issues/107. This is probably worth testing to figure out which it is, probably on a fork to limit noise on this repo.

**Comment by saschanaz** [comment]
The glob:

https://github.com/mdn/browser-compat-data/blob/987951eac85b164f99a166cdb198debefd49b098/.github/labeler.yml#L30-L31

Is it a valid syntax? Should it be `**/*.md` instead?
