### ISSUE TITLE
Mark obsolete HTML features as deprecated

### ISSUE THREAD

**Issue by foolip** [mdn/browser-compat-data#7255]
Everything in https://html.spec.whatwg.org/multipage/obsolete.html is standardized with no intention of ever being removed from the web platform, but obsolete and discouraged from use. https://github.com/mdn/browser-compat-data/pull/7252 marked `document.all` as deprecated on these grounds, and we should do it for the rest of these features.

@sideshowbarker this may interest you.

**Comment by sideshowbarker** [comment]
Progress report: For all features in the first two subsections of https://html.spec.whatwg.org/multipage/obsolete.html — which is basically about obsolete elements and attributes I’ve already raised PRs (most or all of which have now already been merged).

What remains is to raise PRs for the final subsection at https://html.spec.whatwg.org/multipage/obsolete.html#requirements-for-implementations — which is about obsolete APIs and obsolete members of APIs. I’ll spend some time looking at that now.

**Comment by Elchi3** [comment]
This is really great, @sideshowbarker! :tada:

**Comment by foolip** [comment]
I realized after merging https://github.com/mdn/browser-compat-data/pull/7589 that a few attributes weren't correctly marked as deprecated. Mentioning here so that it won't be overlooked before closing this issue. @vinyldarkscratch can you update those statuses?

**Comment by sideshowbarker** [comment]
> What remains is to raise PRs for the final subsection at https://html.spec.whatwg.org/multipage/obsolete.html#requirements-for-implementations — which is about obsolete APIs and obsolete members of APIs. I’ll spend some time looking at that now.

Update: I got through a good part of that section before I needed to be away for a bit. But I’ll be getting back to it again soon.

> I realized after merging #7589 that a few attributes weren't correctly marked as deprecated. Mentioning here so that it won't be overlooked before closing this issue. @vinyldarkscratch can you update those statuses?

I guess that means I didn’t reach yet reach `HTMLHRElement` in my journey through the rest of that HTML spec section. Anyway, I’ll make sure it doesn’t fall between the cracks — either by raising the PR for it myself once I reach that point in my audit of BCD against the spec, or else by reviewing @vinyldarkscratch’s PR, if she happens to get to it before I manage to.

**Comment by queengooborg** [comment]
It appears that all appropriate elements have been marked as `deprecated`, so I'd say that this can be closed!
