### ISSUE TITLE
Sort out notes for the defer attribute in IE

### ISSUE THREAD

**Issue by foolip** [mdn/browser-compat-data#7258]
Filing an issue to follow up on https://github.com/mdn/browser-compat-data/pull/7246#discussion_r516931091.

We have two bits of data about `defer` with notes that aren't super specific about what works and not, which should be aligned:

https://github.com/mdn/browser-compat-data/blob/82f3394ae95f1021302bf962c1e9662303fcbbfe/api/HTMLScriptElement.json#L209-L218

https://github.com/mdn/browser-compat-data/blob/82f3394ae95f1021302bf962c1e9662303fcbbfe/html/elements/script.json#L168-L171

**Comment by foolip** [comment]
Reopening because I think the notes still don't really spell out what web developers need to be aware of, ultimately if they can use `defer` or not with IE9.

Notes in https://caniuse.com/script-defer link to https://github.com/h5bp/lazyweb-requests/issues/42, and it seems like it's the order of execution which isn't reliably for IE9 and below. That seems like something that would be best spelled out with a new range with `partial_implementation` and a note to that effect for both of the entries.

@vinyldarkscratch I unassigned you because this is sort of tangential to the API update project, but would you like to take a shot at this? We'd need to figure out how far back the `defer` content attribute and IDL attribute is supported to update the data...

**Comment by queengooborg** [comment]
I'm closing this issue since the IE data was frozen a few releases back.
