### ISSUE TITLE
TODO Intl.toString for SamsungAd 14+, OperaAd 16+, Safari14.2+

### ISSUE THREAD

**Issue by hamishwillee** [mdn/browser-compat-data#7294]
Intl.toString was added in https://github.com/mdn/browser-compat-data/pull/7020. We know that this will go into some of the other browsers (based on same engine) but the corresponding releases are not out yet.

- [samsunginternet_android](https://github.com/mdn/browser-compat-data/blob/master/browsers/samsunginternet_android.json) - current version is  `13.0` which depends on Blink 83. Need to update BCD entry when a version of this appears that uses Blink 86.
- [opera_android](https://github.com/mdn/browser-compat-data/blob/master/browsers/opera_android.json) - current version is 60 based on Blink 85. Need to update BCD entry when a version of this appears that uses Blink 86.
- Safari - Being discussed in https://github.com/mdn/browser-compat-data/pull/7293 and https://github.com/mdn/browser-compat-data/pull/7248

**Comment by jculver050** [comment]
Close
