### ISSUE TITLE
Migrating compat data from MDN

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#731]
I'm using the MDN search to look for pages that still use the old compat tables, meaning that the compat information has not been added to this repo yet. 

Pages we still need to migrate are listed here: https://gist.github.com/Elchi3/b6863aa227fc4cd51a247957380eca5e

**Feel free to help migrating data!** 

More information is available here https://developer.mozilla.org/en-US/docs/MDN/Contribute/Structures/Compatibility_tables

If you have questions, you can ask them in this issue.

**Comment by Oluwasetemi** [comment]
Hi @Elchi3 
 I am willing to help in the Migration.
 How do I go about it?
regards.
Ojo Oluwasetemi

**Comment by Elchi3** [comment]
Hi @Oluwasetemi!  Sorry, I only saw this now. 
You can have a look at one of the issues with ["help wanted"](https://github.com/mdn/browser-compat-data/labels/help%20wanted). There are further instructions in these issues.

**Comment by patrickkettner** [comment]
@Elchi3 fwiw, a handful of the pages lack any compat table at all

```
Web/API/AuthenticatorResponse                                                    
Web/API/AuthenticatorResponse/clientDataJSON                                     
Web/API/FileSystemDirectoryReader/readEntries                                    
Web/API/GlobalEventHandlers/onanimationend                                       
Web/API/StorageEstimate/quota                                                    
Web/API/StorageEstimate/usage                                                    
Web/Events/Activate
```

**Comment by Elchi3** [comment]
@patrickkettner Yes, the list is not perfect. I'm using our ElasticSearch index and that one isn't really reliable unfortunately.

**Comment by Elchi3** [comment]
I'm closing this. We're almost finished migrating data and the remaining pages require some MDN content refactoring that is currently underway. No longer interested in help. Thanks everyone who helped!
