### ISSUE TITLE
Confirm the names of mobile browsers

### ISSUE THREAD

**Issue by ddbeck** [mdn/browser-compat-data#7328]
Via https://github.com/mdn/yari/issues/1672 and some related issues, the MDN dev team discovered an inconsistency with the way browser names were generated on MDN. We should confirm that BCD's browser data correctly reflects each browser's conventional name.

For the desktop browsers, I think we're already OK. It's the mobile browsers that present problems, because vendors don't always seem to reliably use the same name to show what platform they run on. We should probably just ask the vendors how they prefer to indicate the non-desktop version or, if that's not an option, find some common use on the vendor's site (preferably from pages with a developer audience).

Check up on these mobile browsers:

- [ ] Chrome
- [x] Firefox
- [ ] Opera
- [x] Safari
- [ ] WebView

Update the `"name"` data, if applicable:

- [x] "Firefox Android" → "Firefox for Android"
- [x] "iOS Safari" → "Safari on iOS"

**Comment by vinyldarkscratch** [comment]
Looking through the commit history, omitting the word "for" was an intentional decision for localization purposes (see https://github.com/mdn/browser-compat-data/issues/1791#issuecomment-382345899).  Are we still concerned with localization?

**Comment by jensimmons** [comment]
For Safari, it's "Safari on iOS".

Can I Use is about to make this change as well. https://github.com/Fyrd/caniuse/issues/5815

**Comment by ddbeck** [comment]
Thanks, @jensimmons. This will be updated in today's release.

**Comment by ddbeck** [comment]
Also, I suppose we've surrendered on the question for localization for now.

**Comment by ddbeck** [comment]
We did not hear from other vendors, but we also didn't exactly _ask_, either.

**Comment by jculver050** [comment]
Close

**Comment by queengooborg** [comment]
Developers from Google have referred to it as Chrome Android and WebView Android.  Opera seems to be called "Opera Mobile" on CanIUse.  I think "Opera Android" is clearer that it's referring to the Android version (as some may confuse Opera Mobile for iOS).  With that, I think this issue can be safely closed.
