### ISSUE TITLE
Backdrop-filter

### ISSUE THREAD

**Issue by Mottie** [mdn/browser-compat-data#734]
> backdrop-filter is now enabled by default in Edge included in Windows 10 Insider Preview Build 17063

Sources:
* https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/9160189-backdrop-filters
* https://caniuse.com/#feat=css-backdrop-filter (reported as being added to Edge v17)

**Comment by teoli2003** [comment]
As soon as PR #807 (and its dependencies) will be deployed in prod), we will be able to close this.

**Comment by Elchi3** [comment]
This got done and the MDN page is updated.
