### ISSUE TITLE
autoplay support data not accurate

### ISSUE THREAD

**Issue by rsepierre** [mdn/browser-compat-data#7342]
Hello.
I am not sure this is the intended way to provide feedback and hope this isn't too much of an inconvenience.

Following recent tests and looking at 
https://caniuse.com/?search=autoplay

I think that the data should be somewhat reflecting that Firefox for Android is out of the box blocking autoplay for both audio and video whether it is muted or not.

Which drops the "usage %" probably by about 4%

Mozilla's own documentation on autoplay states that "muted autoplay elements" would play but actually, firefox for Android's recommended (and default) setting is to block all video autoplay (whether it is muted or not) and doesn't provide any way to ask for "consent" to autoplay videos.

It should be fair to assume that most users will not enable it.

Note that you can use GIFs ( which is 10 to 100 times less optimised and nowhere close on quality ) instead

**Comment by queengooborg** [comment]
Hey there!  Huge apologies for not responding sooner than this -- it has definitely been a wild ride for all of us, haha!

Upon looking into this now, it appears that the [default has now changed to only block autoplaying videos with audio enabled](https://github.com/mozilla-mobile/fenix/issues/19922).  It appears that this change had landed in Firefox Android 91, making its behavior identical to other browsers.

Looking through our data, I'm noticing that it only states that Safari iOS disallows unmuted autoplay in a note, but I know for a fact that this is incorrect -- Chrome Desktop blocks autoplay of any audio.  I opened up a PR to sort this out and include the findings about Firefox Android!
