### ISSUE TITLE
Autoremove branches after merging them

### ISSUE THREAD

**Issue by saschanaz** [mdn/browser-compat-data#7346]
I think I don't need those branches after PRs being merged. GitHub has an option to do that automatically, so please consider enabling it.

**Comment by ddbeck** [comment]
We have this setting (specifically, **Automatically delete head branches** in the repository _Settings_ page) turned on. I know it works for branches on this repository, but it doesn't have any effect on branches on forks that are merged.

I knew that my fork's branches aren't deleted when a PR is merged—I delete them manually—but I just checked and that setting was turned off on my fork (despite the setting upstream). I turned it on just now, but I don't know if it will have any effect when a PR is merged upstream. I guess I'll find out when my current open PR gets merged. 🤷

**Comment by sideshowbarker** [comment]
> I knew that my fork's branches aren't deleted when a PR is merged—I delete them manually—but I just checked and that setting was turned off on my fork (despite the setting upstream). I turned it on just now, but I don't know if it will have any effect when a PR is merged upstream. I guess I'll find out when my current open PR gets merged.

I think you’re gonna find the PR branches in your fork don’t get auto-deleted. I’ve tried myself already, and what I’ve found is, unfortunately, auto-deletion of PR branches only works when the branches are in the same repo (here, upstream) where they get merged. It doesn’t work for PR branches from a fork. And there’s currently no way to make it work; specifically, even if you enable auto-deletion of PR branches in your fork, the branches there won’t get deleted after they’re merged here (upstream).

**Comment by ddbeck** [comment]
> even if you enable auto-deletion of PR branches in your fork, the branches there won’t get deleted after they’re merged here (upstream).

Hmm. I think it did work, though? I opened and merged #7415 and GitHub deleted my branch.

**Comment by sideshowbarker** [comment]
> Hmm. I think it did work, though? I opened and merged #7415 and GitHub deleted my branch.

Interesting. So, on the one hand I’m glad to find out it actually works; but on the other hand, I have no idea why it doesn’t work for my fork with the same setting enabled, while it does work for yours

**Comment by saschanaz** [comment]
I enabled on my fork, I hope it work for me.

**Comment by ddbeck** [comment]
OK, I've figured out the full story: GitHub _will_ delete your fork's branch, if the fork's `master` branch is synchronized with the upstream repo. It looked automatic to me because I routinely run [a script](https://gist.github.com/ddbeck/485b853ee232f5057e9c9c07e74b4e8b) to do just that. 🤦

**Comment by sideshowbarker** [comment]
> OK, I've figured out the full story: GitHub _will_ delete your fork's branch, if the fork's `master` branch is synchronized with the upstream repo.

aha — then I guess that also explains why it doesn’t work in my case, because the master branch of my fork intentionally has differences from upstream (specifically, it adds thousands of `spec_url` values).

So I guess I’d need to create another separate fork

**Comment by ddbeck** [comment]
Ah, yeah. Or you could find a way to use a branch other than master for the `spec_url` stuff? Sorry that's so fussy.

**Comment by sideshowbarker** [comment]
> Ah, yeah. Or you could find a way to use a branch other than master for the `spec_url` stuff?

Yeah, I reckon I'll just do that

**Comment by ddbeck** [comment]
OK, I guess this is as far as we can take this. I'm going to close this issue for now, but should GitHub ever give us a better solution, I'd welcome a follow-up comment to reopen the issue at that time.
