### ISSUE TITLE
Opera for Android appears to not support flags

### ISSUE THREAD

**Issue by ddbeck** [mdn/browser-compat-data#7354]
Like Samsung Internet (#4753), Opera for Android appears to expose a very limited set of flags—not the full complement like Chrome for Android does. We should probably remove and bar flag data in `"opera_android"` entries.

**Comment by vinyldarkscratch** [comment]
Can confirm, viewing `opera://flags` reveal only one flag on Android (as opposed to the near match of entries that Chrome has).

![screenshot-1605292332952](https://user-images.githubusercontent.com/5179191/99108000-8e26d400-259b-11eb-88f8-a84d5173923e.jpg)
![Screenshot 2020-11-13 103442](https://user-images.githubusercontent.com/5179191/99108256-f1186b00-259b-11eb-8451-2435b6fdb28c.png)

**Comment by jculver050** [comment]
Close
