### ISSUE TITLE
Update "npm run render" to build new-style compat table

### ISSUE THREAD

**Issue by a2sheppy** [mdn/browser-compat-data#736]
The output from `npm run render` is currently the old-style compat table. We need to update this to build a modern compat table.

**Comment by a2sheppy** [comment]
Anyone out there have time to try to do this? It's slowing down reviews to have to go through tables that look all funky and different. :)

**Comment by vinyldarkscratch** [comment]
Is `npm run render` deprecated at this point, since we have [`mdn-browser-compat-toolkit`](https://github.com/mdn/browser-compat-toolkit) now?

**Comment by ExE-Boss** [comment]
@vinyldarkscratch Well, [<code>mdn&#x2011;compat&#x2011;toolkit</code>](https://github.com/mdn/browser-compat-toolkit) is&nbsp;essentially abandoned at&nbsp;this point (see&nbsp;https://github.com/mdn/mdn/issues/41#issuecomment-427508791)

**Comment by vinyldarkscratch** [comment]
That's what I thought, just wanted to confirm.  Perhaps we should remove the script entirely as to reduce confusion and clean up code?

**Comment by stof** [comment]
What is the state of this ? Is there any uptodate replacement for this outdated `npm run render` ?

Being able to check how our change looks like when rendered seems a good idea.

**Comment by vinyldarkscratch** [comment]
Since the render script has been removed in #5032, this issue is no longer relevant.  As such, I will go ahead and close it.
