### ISSUE TITLE
Remove WorkerGlobalScope.close()

### ISSUE THREAD

**Issue by saschanaz** [mdn/browser-compat-data#7362]
It has been moved to DedicatedWorkerGlobalScope and SharedWorkerGlobalScope as the current BCD item says. to remove it from ServiceWorkerGlobalScope.

An open question is that whether we need to mention that it once also existed on ServiceWorkerGlobalScope. I guess probably not?

**Comment by ddbeck** [comment]
Is this is a specific case of #3463? Or is there a subtlety I'm missing?

**Comment by saschanaz** [comment]
Those are mixins, so not exactly the prototype chain issue.
