### ISSUE TITLE
private_fields and private_methods

### ISSUE THREAD

**Issue by gamgamstylep** [mdn/browser-compat-data#7366]
Adding javascript.options.experimental.private_fields and javascript.options.experimental.private_methods is not working. Still getting "Uncaught SyntaxError: private fields are not currently supported"

![image](https://user-images.githubusercontent.com/43586166/99191288-2d9ac100-276c-11eb-8759-31da1616ff95.png)

**Comment by vinyldarkscratch** [comment]
Closing this issue as this is not the right location to report bugs like this.  Please refer to https://bugzilla.mozilla.org/ to report Firefox bugs.
