### ISSUE TITLE
Update npm run render to build and display in one shot

### ISSUE THREAD

**Issue by a2sheppy** [mdn/browser-compat-data#737]
Currently, `npm run render` simply spits out the raw HTML of the compatibility table. We should add an option to `npm run render` that builds a full HTML document with the needed CSS in a `<style>` block, then opens it in your preferred browser automatically, so you can see the table easily.

This can be done by just building the HTML into a file in the user's temporary files directory (/tmp or whatever) and then opening that.

**Comment by ddbeck** [comment]
As a workaround in the meantime, you can pipe to a script like [`browser`](https://gist.github.com/defunkt/318247) (on a Mac you can install it with `brew install browser`, if you like).

**Comment by gsouquet** [comment]
I have played a bit with that task. I succesfully created a webpage that contains the output and open that in the user's default browser. 

However I have two questions to be able to complete this task:

- What should the option to open this in a browser look like?
- How do we handle styles? As far as I can see, the styles are contained the mozilla/kuma repo, they are on their SCSS form. When I check the MDN source, it looks like those asset a compiled and a hash is inserted in the filename, making it quite difficult for me to hardcode anything in the render task. All the solutions I can think of are really hacky... I was wondering if any of you had an input on this one?

**Comment by Elchi3** [comment]
Yeah, the MDN compat production styles are not standalone unfortunately.

The prototypes are here: http://stephaniehobson.github.io/browsercompat/5.0/#here
https://github.com/stephaniehobson/stephaniehobson.github.io/tree/master/browsercompat/5.0

Here's a similar SVG rendered version: https://github.com/epistemex/mdncomp

**Comment by vinyldarkscratch** [comment]
Since the render script has been removed in #5032, this issue is no longer relevant.  As such, I will go ahead and close it.
