### ISSUE TITLE
Sort version numbers

### ISSUE THREAD

**Issue by saschanaz** [mdn/browser-compat-data#7388]
Typically the version numbers in BCD are sorted in reverse order so that the latest one comes to the top position.

But [it's not always the case](https://developer.mozilla.org/en-US/docs/Web/API/BluetoothRemoteGATTServer/getPrimaryServices):

![image](https://user-images.githubusercontent.com/3396686/99467645-25df4600-293f-11eb-9ae7-5bd9273c67eb.png)

I think it should be sorted, what do you think?

(And shouldn't limited platform support be partial_implementation?)

**Comment by Elchi3** [comment]
I think this is a duplicate of https://github.com/mdn/browser-compat-data/issues/1596

**Comment by saschanaz** [comment]
Oh right, thanks!
