### ISSUE TITLE
Linearize support version info

### ISSUE THREAD

**Issue by saschanaz** [mdn/browser-compat-data#7403]
This is related to #1596.

Currently the version info becomes "parallel" when it comes to the legacy webkit aliases.

In [`flex-basis`](https://developer.mozilla.org/en-US/docs/Web/CSS/flex-basis):

![image](https://user-images.githubusercontent.com/3396686/99595556-3baf4280-29f5-11eb-911c-966c5dbc3806.png)

This is correct but the reader needs to get the information in "parallel" way:

* 22+ just supports it
* 49 added -webkit- alias
* 44 added -webkit- alias behind flag
* 18 supported behind flag and removed the flag in 28 (while the above confusingly does not say when the flag was removed)

This is needlessly complex, I think the version info should be linear per item:

* 49 supports both the original property and the alias (could be helpful if `alternative_name` can indicate whether the original name also exists)
* 44 added alias behind flag
* 22 added the support
* 18 supported the support behind flag (and forget when the flag was removed. Use `version_removed` only when the feature itself is removed)

Or even split them (but having two sources for prefixes (`alternative_name` or a subitem) is not very good):

* `flex-basis`:
   * 22 added the support
   * 18-21 supported the support behind flag
* `-webkit-flex-basis`:
   * 49 supports both the original property and the alias (could be helpful if `alternative_name` can indicate whether the original name also exists)
   * 44-48 added alias behind flag

Changes in #7401 mainly has this kind of complexity. What do you think?

**Comment by ddbeck** [comment]
This feels like one of those things that would be less clumsy if we could tombstone dead flags. See https://github.com/mdn/browser-compat-data/issues/3318.

In this case, if we could mark the entry about 44 adding the `-webkit-` alias behind flag as removed in version 49, the version history would be a lot cleaner, with only two open-ended support statements: one prefixed and one unprefixed.
