### ISSUE TITLE
Prevent `version_added: false` in array

### ISSUE THREAD

**Issue by saschanaz** [mdn/browser-compat-data#7404]
https://developer.mozilla.org/en-US/docs/Web/API/Element/setPointerCapture#Browser_compatibility

![image](https://user-images.githubusercontent.com/3396686/99597975-20463680-29f9-11eb-8192-efe59d05c4b1.png)

This is confusing 😳

**Comment by vinyldarkscratch** [comment]
Huh, I thought we had something to prevent this, but it looks like all we have is preventing multiple `version_added` only statements.  We definitely should not have statements that are simply `null` or `false` when there are other statements.

**Comment by sideshowbarker** [comment]
> We definitely should not have statements that are simply `null` or `false` when there are other statements.

Would that prevent `implementation_url` also? As in https://github.com/mdn/browser-compat-data/pull/7417/files#diff-8fab952a0eb6022dc4191132842e8bc0f7a58a66dc2da930640697b9768e74ecL32-L81 —

```
          "safari": {
            "version_added": false
            "implementation_url": "https://trac.webkit.org/changeset/266172/webkit"
          },
```

**Comment by saschanaz** [comment]
> Would that prevent `implementation_url` also?

Your example is not an array so it shouldn't be affected. 😉

**Comment by jculver050** [comment]
Close
