### ISSUE TITLE
Linter: disallow Edge 13+ as version if IE is truthy?

### ISSUE THREAD

**Issue by queengooborg** [mdn/browser-compat-data#7458]
Since Microsoft Edge is a direct continuation from Internet Explorer, it is safe to assume that most everything present in IE will be in Edge 12.  However, I've noticed that at times, our data will have a version number besides Edge 12 when IE is truthy.  We should add a linter to make sure that if IE is truthy and Edge is truthy, Edge must be set to "12".

**Comment by bershanskiy** [comment]
I created a draft PR (linked above) that checks exactly that:
> We should add a linter to make sure that if IE is truthy and Edge is truthy, Edge must be set to "12".

There are a few edge cases to consider:
 - what if IE/Edge has multiple version ranges? Can we select the last for IE and the earliest for Edge?
 - is it safe to ignore the prefixed aliases or features behind flaggs?

**Comment by ddbeck** [comment]
@bershanskiy Can you add a list here of affected features? That might help to judge how helpful this sort of linting would be.

**Comment by bershanskiy** [comment]
@ddbeck Here is the current list printed out by #7477 (108 files):
<details>
<summary>List</summary>

✖ api\CustomEvent.json
  → api.CustomEvent.initCustomEvent
✖ api\Document.json
  → api.Document.releaseCapture
✖ api\Element.json
  → api.Element.click_event.on_disabled_form_elements
  → api.Element.copy_event
  → api.Element.currentStyle
  → api.Element.cut_event
  → api.Element.prefix
  → api.Element.runtimeStyle
✖ api\HTMLBaseFontElement.json
  → api.HTMLBaseFontElement.color
✖ api\HTMLElement.json
  → api.HTMLElement.transitionend_event
✖ api\HTMLOptionsCollection.json
  → api.HTMLOptionsCollection.length
✖ api\HTMLScriptElement.json
  → api.HTMLScriptElement.crossOrigin
✖ api\HTMLStyleElement.json
  → api.HTMLStyleElement.disabled
✖ api\MediaSource.json
  → api.MediaSource.onsourceclose
  → api.MediaSource.onsourceended
  → api.MediaSource.onsourceopen
✖ api\MessageEvent.json
  → api.MessageEvent.lastEventId
✖ api\PerformanceTiming.json
  → api.PerformanceTiming.secureConnectionStart
✖ api\RadioNodeList.json
  → api.RadioNodeList.value
✖ api\SourceBuffer.json
  → api.SourceBuffer.onabort
  → api.SourceBuffer.onerror
  → api.SourceBuffer.onupdate
  → api.SourceBuffer.onupdateend
  → api.SourceBuffer.onupdatestart
✖ api\SourceBufferList.json
  → api.SourceBufferList.onaddsourcebuffer
  → api.SourceBufferList.onremovesourcebuffer
✖ api\Window.json
  → api.Window.beforeunload_event.custom_text_support
  → api.Window.showModalDialog
✖ api\WindowEventHandlers.json
  → api.WindowEventHandlers.onbeforeunload.custom_text_support
✖ api\WorkerGlobalScope.json
  → api.WorkerGlobalScope.navigator
✖ api\XMLHttpRequest.json
  → api.XMLHttpRequest.abort_event
  → api.XMLHttpRequest.error_event
  → api.XMLHttpRequest.load_event
  → api.XMLHttpRequest.loadend_event
  → api.XMLHttpRequest.loadstart_event
  → api.XMLHttpRequest.progress_event
  → api.XMLHttpRequest.timeout_event
✖ api\XMLHttpRequestEventTarget.json
  → api.XMLHttpRequestEventTarget.onabort
  → api.XMLHttpRequestEventTarget.onerror
  → api.XMLHttpRequestEventTarget.onload
  → api.XMLHttpRequestEventTarget.onloadend
  → api.XMLHttpRequestEventTarget.onloadstart
  → api.XMLHttpRequestEventTarget.onprogress
  → api.XMLHttpRequestEventTarget.ontimeout
✖ api\XMLHttpRequestUpload.json
  → api.XMLHttpRequestUpload
✖ css\properties\-ms-scrollbar-track-color.json
  → css.properties.-ms-scrollbar-track-color
✖ css\properties\display.json
  → css.properties.display.display-outside.run-in
✖ css\properties\font-feature-settings.json
  → css.properties.font-feature-settings
✖ css\properties\line-break.json
  → css.properties.line-break
✖ css\properties\scrollbar-3dlight-color.json
  → css.properties.scrollbar-3dlight-color
✖ css\properties\scrollbar-arrow-color.json
  → css.properties.scrollbar-arrow-color
✖ css\properties\scrollbar-base-color.json
  → css.properties.scrollbar-base-color
✖ css\properties\scrollbar-darkshadow-color.json
  → css.properties.scrollbar-darkshadow-color
✖ css\properties\scrollbar-face-color.json
  → css.properties.scrollbar-face-color
✖ css\properties\scrollbar-highlight-color.json
  → css.properties.scrollbar-highlight-color
✖ css\properties\scrollbar-shadow-color.json
  → css.properties.scrollbar-shadow-color
✖ css\selectors\placeholder-shown.json
  → css.selectors.placeholder-shown
✖ html\elements\audio.json
  → html.elements.audio.played
✖ html\elements\bgsound.json
  → html.elements.bgsound
✖ html\elements\col.json
  → html.elements.col.bgcolor
✖ html\elements\colgroup.json
  → html.elements.colgroup.bgcolor
✖ html\elements\fieldset.json
  → html.elements.fieldset.disabled
✖ html\elements\iframe.json
  → html.elements.iframe.sandbox-allow-same-origin
✖ html\elements\link.json
  → html.elements.link.rel.alternate_stylesheet
  → html.elements.link.rel.prerender
✖ html\elements\rb.json
  → html.elements.rb
✖ html\elements\rp.json
  → html.elements.rp
✖ html\elements\rt.json
  → html.elements.rt
✖ html\elements\tbody.json
  → html.elements.tbody.bgcolor
✖ html\elements\td.json
  → html.elements.td.bgcolor
✖ html\elements\tfoot.json
  → html.elements.tfoot.bgcolor
✖ html\elements\th.json
  → html.elements.th.bgcolor
✖ html\elements\thead.json
  → html.elements.thead.bgcolor
✖ html\elements\tr.json
  → html.elements.tr.bgcolor
✖ http\headers\content-security-policy-report-only.json
  → http.headers.Content-Security-Policy-Report-Only
✖ http\headers\content-security-policy.json
  → http.headers.csp.Content-Security-Policy
  → http.headers.csp.Content-Security-Policy.sandbox
✖ svg\elements\feGaussianBlur.json
  → svg.elements.feGaussianBlur
✖ javascript\builtins\TypedArray.json
  → javascript.builtins.TypedArray.buffer
  → javascript.builtins.TypedArray.byteLength
  → javascript.builtins.TypedArray.byteOffset
  → javascript.builtins.TypedArray.length
  → javascript.builtins.TypedArray.set
  → javascript.builtins.TypedArray.subarray
✖ javascript\builtins\WeakMap.json
  → javascript.builtins.WeakMap.clear
✖ webdriver\commands\AcceptAlert.json
  → webdriver.commands.AcceptAlert
✖ webdriver\commands\AddCookie.json
  → webdriver.commands.AddCookie
✖ webdriver\commands\Back.json
  → webdriver.commands.Back
✖ webdriver\commands\CloseWindow.json
  → webdriver.commands.CloseWindow
✖ webdriver\commands\DeleteAllCookies.json
  → webdriver.commands.DeleteAllCookies
✖ webdriver\commands\DeleteCookie.json
  → webdriver.commands.DeleteCookie
✖ webdriver\commands\DeleteSession.json
  → webdriver.commands.DeleteSession
✖ webdriver\commands\DismissAlert.json
  → webdriver.commands.DismissAlert
✖ webdriver\commands\ElementClear.json
  → webdriver.commands.ElementClear
✖ webdriver\commands\ElementClick.json
  → webdriver.commands.ElementClick
✖ webdriver\commands\ElementSendKeys.json
  → webdriver.commands.ElementSendKeys
✖ webdriver\commands\ExecuteAsyncScript.json
  → webdriver.commands.ExecuteAsyncScript
✖ webdriver\commands\ExecuteScript.json
  → webdriver.commands.ExecuteScript
✖ webdriver\commands\FindElement.json
  → webdriver.commands.FindElement
✖ webdriver\commands\FindElementFromElement.json
  → webdriver.commands.FindElementFromElement
✖ webdriver\commands\FindElements.json
  → webdriver.commands.FindElements
✖ webdriver\commands\FindElementsFromElement.json
  → webdriver.commands.FindElementsFromElement
✖ webdriver\commands\Forward.json
  → webdriver.commands.Forward
✖ webdriver\commands\FullscreenWindow.json
  → webdriver.commands.FullscreenWindow
✖ webdriver\commands\GetActiveElement.json
  → webdriver.commands.GetActiveElement
✖ webdriver\commands\GetAlertText.json
  → webdriver.commands.GetAlertText
✖ webdriver\commands\GetAllCookies.json
  → webdriver.commands.GetAllCookies
✖ webdriver\commands\GetCurrentURL.json
  → webdriver.commands.GetCurrentURL
✖ webdriver\commands\GetElementAttribute.json
  → webdriver.commands.GetElementAttribute
✖ webdriver\commands\GetElementCSSValue.json
  → webdriver.commands.GetElementCSSValue
✖ webdriver\commands\GetElementProperty.json
  → webdriver.commands.GetElementProperty
✖ webdriver\commands\GetElementRect.json
  → webdriver.commands.GetElementRect
✖ webdriver\commands\GetElementTagName.json
  → webdriver.commands.GetElementTagName
✖ webdriver\commands\GetElementText.json
  → webdriver.commands.GetElementText
✖ webdriver\commands\GetNamedCookie.json
  → webdriver.commands.GetNamedCookie
✖ webdriver\commands\GetPageSource.json
  → webdriver.commands.GetPageSource
✖ webdriver\commands\GetTimeouts.json
  → webdriver.commands.GetTimeouts
✖ webdriver\commands\GetTitle.json
  → webdriver.commands.GetTitle
✖ webdriver\commands\GetWindowHandle.json
  → webdriver.commands.GetWindowHandle
✖ webdriver\commands\GetWindowHandles.json
  → webdriver.commands.GetWindowHandles
✖ webdriver\commands\GetWindowRect.json
  → webdriver.commands.GetWindowRect
✖ webdriver\commands\IsElementEnabled.json
  → webdriver.commands.IsElementEnabled
✖ webdriver\commands\IsElementSelected.json
  → webdriver.commands.IsElementSelected
✖ webdriver\commands\MaximizeWindow.json
  → webdriver.commands.MaximizeWindow
✖ webdriver\commands\MinimizeWindow.json
  → webdriver.commands.MinimizeWindow
✖ webdriver\commands\NavigateTo.json
  → webdriver.commands.NavigateTo
✖ webdriver\commands\NewSession.json
  → webdriver.commands.NewSession
✖ webdriver\commands\NewWindow.json
  → webdriver.commands.NewWindow
✖ webdriver\commands\PerformActions.json
  → webdriver.commands.PerformActions
✖ webdriver\commands\Refresh.json
  → webdriver.commands.Refresh
✖ webdriver\commands\ReleaseActions.json
  → webdriver.commands.ReleaseActions
✖ webdriver\commands\SendAlertText.json
  → webdriver.commands.SendAlertText
✖ webdriver\commands\SetTimeouts.json
  → webdriver.commands.SetTimeouts
✖ webdriver\commands\SetWindowRect.json
  → webdriver.commands.SetWindowRect
✖ webdriver\commands\Status.json
  → webdriver.commands.Status
✖ webdriver\commands\SwitchToFrame.json
  → webdriver.commands.SwitchToFrame
✖ webdriver\commands\SwitchToParentFrame.json
  → webdriver.commands.SwitchToParentFrame
✖ webdriver\commands\SwitchToWindow.json
  → webdriver.commands.SwitchToWindow
✖ webdriver\commands\TakeElementScreenshot.json
  → webdriver.commands.TakeElementScreenshot
✖ webdriver\commands\TakeScreenshot.json
  → webdriver.commands.TakeScreenshot
</details>

**Comment by jculver050** [comment]
Close

**Comment by queengooborg** [comment]
I'm going to close this because legacy Edge is no longer much of a concern and we're looking to potentially deprecate IE data soon.
