### ISSUE TITLE
CSS: update `conic-gradient` compatibility for Firefox 

### ISSUE THREAD

**Issue by monkeypox8** [mdn/browser-compat-data#7467]
`conic-gradient` support has landed in [Firefox 83](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/83), but the double-position color stops entry has not been updated. [See this page in Firefox](https://developer.mozilla.org/en-US/docs/Web/CSS/conic-gradient()#Gradient_pie-chart) for verification.

### references
- https://bugzilla.mozilla.org/show_bug.cgi?id=1632351
- https://bugzilla.mozilla.org/show_bug.cgi?id=1175958

**Comment by ddbeck** [comment]
Fixed by #7468. Thank you!
