### ISSUE TITLE
Review AppCache removal in Chromium 90

### ISSUE THREAD

**Issue by hamishwillee** [mdn/browser-compat-data#7480]
Chromium 90 is planned to remove App Cache: https://www.chromestatus.com/feature/6192449487634432

- There is more information about timelines, and also for Safari/Webkit in https://web.dev/appcache-removal/
- FF support removed in FF84 (see https://github.com/mdn/browser-compat-data/pull/7481)

**Comment by jculver050** [comment]
Close

**Comment by queengooborg** [comment]
This was resolved in #7622!
