### ISSUE TITLE
Remove ghost feature: api.HTMLAreaElement.hreflang

### ISSUE THREAD

**Issue by vinyldarkscratch** [mdn/browser-compat-data#7504]
A number of my recent PRs have been setting `api.HTMLAreaElement.hreflang` to `false`. It has been determined that this feature is actually a ghost feature, with no implementation or spec. This feature should be removed from BCD.

---

There’s no `HTMLAreaElement.prototype.hreflang` in Blink or Gecko either — and https://html.spec.whatwg.org/multipage/image-maps.html#htmlareaelement doesn’t actually define a `hreflang` member for `HTMLAreaElement`, not even as an obsolete member in https://html.spec.whatwg.org/multipage/obsolete.html#HTMLAreaElement-partiall. And there is actually no https://developer.mozilla.org/en-US/docs/Web/API/HTMLAreaElement/hreflang article.

So it seems to me we should just remove this entire feature.

_Originally posted by @sideshowbarker in https://github.com/mdn/browser-compat-data/pull/7402#discussion_r527275934_

**Comment by jculver050** [comment]
Close

**Comment by vinyldarkscratch** [comment]
Resolved by #7539.
