### ISSUE TITLE
Storage Access API data is not accurate

### ISSUE THREAD

**Issue by andybons** [mdn/browser-compat-data#7510]
The Storage Access API (`document.{request|has}StorageAccess`) is not available by default in Chrome unless a [flag](chrome://flags/#storage-access-api) is set.

[Chrome bug](https://bugs.chromium.org/p/chromium/issues/detail?id=989663)
[Chrome Platform Status](https://www.chromestatus.com/feature/5612590694662144)

Not sure if this is the right format for this bug so let me know how I can help!

**Comment by ddbeck** [comment]
Thanks for this report, @andybons. That's a helpful report. Linking to the bug and Platform Status entry is ideal. 👍

Looks like there was a little uncertainty about this when it was added in the first place: https://github.com/mdn/browser-compat-data/pull/6836#discussion_r502331769 (though I'm still wondering whether Edge flipped this one on).

I'd welcome a PR editing these features in `Document.json`:

https://github.com/mdn/browser-compat-data/blob/771d341d083b2c8cd9a2d75d6ae76485d465a906/api/Document.json#L6262-L6316

https://github.com/mdn/browser-compat-data/blob/771d341d083b2c8cd9a2d75d6ae76485d465a906/api/Document.json#L10267-L10321

**Comment by andybons** [comment]
From testing on Edge 87.0.664.57 (macOS), the Storage Access API is turned on by default. Makes sense since MS engineers appear to be driving the implementation in Blink.

I’ll take a look and send a PR. I may have questions along the way so I’ll just ask here :)
