### ISSUE TITLE
Consistent use of partial_implementation and notes for prototype moves

### ISSUE THREAD

**Issue by foolip** [mdn/browser-compat-data#7517]
Over time, many members of `HTMLElement` or `SVGElement` have been moved up to `Element`, and all members of `HTMLDocument` have been moved up `Document`. The way this is represented in BCD varies a lot. A sample:

https://github.com/mdn/browser-compat-data/blob/5e7ff0a7194088756dedebb561d776abaf7ed03d/api/Document.json#L255-L256

https://github.com/mdn/browser-compat-data/blob/5e7ff0a7194088756dedebb561d776abaf7ed03d/api/Document.json#L1614

https://github.com/mdn/browser-compat-data/blob/5e7ff0a7194088756dedebb561d776abaf7ed03d/api/Document.json#L916

https://github.com/mdn/browser-compat-data/blob/5e7ff0a7194088756dedebb561d776abaf7ed03d/api/Element.json#L1684-L1685

https://github.com/mdn/browser-compat-data/blob/5e7ff0a7194088756dedebb561d776abaf7ed03d/api/Element.json#L1434-L1435

Since this problem is receding into the past and isn't something developers need to keep worrying about, I believe that we should consistently use `partial_implementation` and a note for the versions of each browser where the member was on a child interface and thus not supported on all instances of the interface, and separately have a support statement without notes from when the problem was fixed. Like this:

https://github.com/mdn/browser-compat-data/blob/5e7ff0a7194088756dedebb561d776abaf7ed03d/api/Document.json#L3108-L3118

**Comment by foolip** [comment]
I should also say this only applies for moves *up* the prototype chain. https://github.com/mdn/browser-compat-data/issues/3463 is about the problem of moves more generally, and not all are the same.

**Comment by jpmedley** [comment]
LGTM

**Comment by ddbeck** [comment]
Having a rule we can apply to at least some of these moves is a step in the right direction. I like this and I'd be happy to see a PR with a data guideline codifying it. I have two questions, though:

Does this proposal require that the member appear only on the specified prototype and not the prototype it moved from? Or is this proposal only for the data on the destination prototype and agnostic about is previous place on the prototype chain?

Is the note text here part of the proposal? Do you think the note text above could act as a template for all such moves? (This would be nice to have, as it might help us locate such moves later, should we come up with a more comprehensive solution.)

**Comment by jpmedley** [comment]
>Does this proposal require that the member appear only on the specified prototype and not the prototype it moved from?

The members may not work the way you think. That was certainly true for me. Open a browser console and look at `window.document` and `window.HTMLDocument`. `document.dir` may only be available when the document type is HTML, but it doesn't actually appear on `HTMLDocument`. I had initially thought that this was a straight forward inheritance pattern and that access would be `HTMLDocument.dir`.

>Do you think the note text above could act as a template for all such moves?

I do not. The situation I just described I believe is unique to `Document` and `Element`.

**Comment by foolip** [comment]
> Does this proposal require that the member appear only on the specified prototype and not the prototype it moved from? Or is this proposal only for the data on the destination prototype and agnostic about is previous place on the prototype chain?

Are you asking about a situation like `AudioScheduledSourceNode.prototype.start` and `AudioBufferSourceNode.prototype.start`, where per spec a member should appear at multiple places in the prototype chain, but it wasn't always so? (Here, `AudioScheduledSourceNode` was inserted into the prototype at some point, and most members of `AudioBufferSourceNode` moved up.)

If so, then I'm only proposing a guideline for simple moves up the prototype chain. Other situation are rare, and I think we can handle them individually, probably doing something similar.

> The members may not work the way you think. That was certainly true for me. Open a browser console and look at `window.document` and `window.HTMLDocument`. `document.dir` may only be available when the document type is HTML, but it doesn't actually appear on `HTMLDocument`. I had initially thought that this was a straight forward inheritance pattern and that access would be `HTMLDocument.dir`.

@jpmedley by now all members of `HTMLDocument` have been moved to `Document` in all engines, so it's no longer to explore this with this example. I'm not sure what everyone already knows and not, so I'll just point out a few things that aren't at all obvious at first about how Web IDL interfaces behave.
- The interface objects (`HTMLDocument`) and prototypes (`HTMLDocument.prototype`) aren't the same, but form separate and paralleled hierarchies. So `Object.getPrototypeOf(HTMLElement) === Element` and `Object.getPrototypeOf(HTMLElement.prototype) === Element.prototype` but `Object.getPrototypeOf(HTMLElement) !== HTMLElement.prototype`. The interface objects don't really matter that much when there's no constructor, and that's why their non-exposure has been pretty common historically.
-  The notation used for BCD properties might mislead. `Element.matches` is undefined, it's *not* on the interface object but on the prototype, `Element.prototype.matches`.
- `HTMLElement.prototype.matches` is there and `'matches' in HTMLElement.prototype` is true, but that's not the same as `matches` being *on* the `HTMLElement` prototype. To test that the more pedantic test `HTMLElement.prototype.hasOwnProperty('matches')` is needed, which returns false. It's on `Element`, so `Element.prototype.hasOwnProperty('matches')` return true.

> Is the note text here part of the proposal? Do you think the note text above could act as a template for all such moves? (This would be nice to have, as it might help us locate such moves later, should we come up with a more comprehensive solution.)

I think the note text would largely be a template, yes, where we'd replace only the name of the two interfaces involved. However, which other interfaces to call out, if any, will vary. For a `HTMLElement` &rarr; `Element` move it's useful to name `SVGElement` as the most common other kind of element where it wouldn't work, but there must be prototype moves where it's not very useful to give the example.

So I'd suggest this template note text in general:

> Only supported for `Interface`, not all `ParentInterface` objects.

And this one where there's a sibling interface worth noting:

> Only supported for `Interface`, not all `ParentInterface` objects, such as `SiblingInterface`.

**Comment by foolip** [comment]
https://github.com/mdn/browser-compat-data/pull/9613 proposed a guideline for this.

**Comment by ddbeck** [comment]
Closing as fixed! Thank you, @foolip!
