### ISSUE TITLE
Removal of features should be a "breaking change"

### ISSUE THREAD

**Issue by robatwilliams** [mdn/browser-compat-data#7535]
I didn't find any version policy here. I propose that this project uses semver so that dependent packages avoid being broken by breaking changes made to the schema, and maintainers can learn about such breaking changes without reading every release note.

I use this package in my compatibility checker tool. When arithmetic operators were moved by #6246, it was [released](https://github.com/mdn/browser-compat-data/releases/tag/v1.0.25) as a patch version although mentioned in the release notes. As is common practice, I used a version specifier `^1.0.25` to allow updates to any minor or patch version, expecting that any breaking change would be a major version. Since a breaking change was released as a patch version, it caused bug https://github.com/robatwilliams/es-compat/issues/22.

Just to be clear, the breakage is my own fault because I assumed this project would use semver - due to it being common for npm packages.

**Comment by vinyldarkscratch** [comment]
Hey @robatwilliams, this is really big point, thanks for bringing it up.  We do attempt to stick with semantic versioning rules, but we hadn't considered removal of features in the data to be a "breaking change".  It seems, however, that this certainly qualifies as a breaking change.

@ddbeck, you'll probably want to take a look at this one.

**Comment by ddbeck** [comment]
@robatwilliams Thank you for alerting me to this problem. Treating feature names as being subject to semver seems like a reasonable request to me. I was kinda thinking that this might be a good idea, but nobody complained before, so I hadn't acted on it yet.

I'm putting it on my to-do list to document our semver practices and flag that in a semver minor release. 😄

**Comment by ddbeck** [comment]
@robatwilliams An update on this: #7615 begins the process of protecting some parts of BCD for backwards compatibility and SemVer. If you have any thoughts on this, I'd appreciate your input on that PR (or issue #7563). It's not all encompassing (at least not yet), but it should limit the circumstances where a breakage like yours occurs.

**Comment by robatwilliams** [comment]
Both look good, I've put my comments on the issue.

As a tool maintainer I have a few options:
1. Lock down to exact dependency version, which stops users benefiting from data updates until I release.
1. Remain with my unsafe usage (or similar) which breaks the tool spectacularly so someone is likely to tell me about it.
1. Make the tool tolerant of missing data and report warnings to the user, which someone might tell me about
1. ... leading to the likely best solution - run the unit tests daily using the latest BCD that satisfies my dependency version string

**Comment by ddbeck** [comment]
OK, I think with v3.0.0 we've improved the situation quite a bit. Thank you again, @robatwilliams. I'm going to close this PR now, but please feel welcome to open new issues should we cause you any more trouble. 😅
