### ISSUE TITLE
Change WebView range from ≤37 to ≤4.4?

### ISSUE THREAD

**Issue by vinyldarkscratch** [mdn/browser-compat-data#7543]
We added WebView Android ≤37 as the first version range to reduce the number of `true` values lurking around.  However, we can also obtain data for WebView Android 4.4 and 4.4.3 by mirroring Chrome Android 30 and 33 respectively.  Perhaps we should change the range to be ≤4.4 instead, since we can confirm their data?

**Comment by foolip** [comment]
IIUC, WebView switched to using Chromium at 4.4, but the versioning scheme was changed later. So 4.4 is the more significant version, where Android WebView switched from WebKit to Chromium. @jpmedley is that right?

**Comment by Elchi3** [comment]
The story that lead us to invent ≤37 is in this issue, fwiw: https://github.com/mdn/browser-compat-data/issues/4330

There is also https://github.com/mdn/browser-compat-data/issues/3561 which advocates "webview_android to refer only to Chromium-based webviews.".

**Comment by jpmedley** [comment]
Pre 37, WebView was neither Webkit, nor Chromium. It was one built for the Android OS before Google acquired the platform. At least, that's my understanding.

**Comment by jpmedley** [comment]
The reason for the true and false values was that someone had marked one of those values in MDN's compatibility tables (the source of the origin BCD data). The features were old enough that we had no way to determine which version off Android received them.

**Comment by jpmedley** [comment]
Sorry for the spam, but I keep remembering different aspects of this. I recall being told that there were different WebViews depending on which Android manufacturer had compiled your OS.

**Comment by vinyldarkscratch** [comment]
Regarding the source of my data, a [web article from Google Chrome Developers](https://developer.chrome.com/multidevice/webview/overview) says that "Since Android 4.4 (KitKat), the WebView component is based on the Chromium open source project... The WebView shipped with Android 4.4 (KitKat) is based on the same code as Chrome for Android version 30... The updated WebView shipped with Android 4.4.3 has the version number 33.0.0.0.

**Comment by jpmedley** [comment]
Then I don't know why we settled on 37 as the inflection point, unless it had something to do with Android L. 36 shipped with the developer preview. If Chrome 37 has been out by the time L shipped, it probably would have went out with it. Regardless, replacing 4.4 and 4.4.3 with 30 and 33 sounds right. 

Would anything earlier become ≤30?

**Comment by foolip** [comment]
Since it's not been mentioned in this issue yet, here's the `engine_version` data behind this:

https://github.com/mdn/browser-compat-data/blob/c577e40417cf835a97f37df9981553176977f674/browsers/webview_android.json#L75-L88

That was added in https://github.com/mdn/browser-compat-data/pull/3877 by none other than @vinyldarkscratch, not sure if there are additional sources listed there which would help.

**Comment by ddbeck** [comment]
I think a close reading of [the page that Vinyl linked to about the relationship between Android and WebView 30, 33, 36, and 37](https://developer.chrome.com/docs/multidevice/webview/overview/#what-version-of-chrome-is-it-based-on) suggests we should be careful about drawing conclusions about versions before WebView 37:

- We can't safely mirror from Chrome 30 to WebView 30 ("This WebView does not have full feature parity with Chrome for Android")
- The relationship between WebView 33 and Chrome 33 is ambiguous, at best ("The updated WebView shipped with Android 4.4.3 has the version number 33.0.0.0.").
- WebView 36 wasn't a real release, only appearing in a version of Android that was never generally available ("Caution: You cannot publish apps using the L Developer Preview to the Google Play store.").

I'm not convinced that we can safely move the version range from ≤37 to 4.4 or 4.4.3, based on the information we have.

But even if we could, I'm not excited about this proposal. It's not clear to me that it makes contributing data any easier and, as far as I know, there's no consumer or audience that seems especially concerned about the exact boundary here. If we're going to put any more energy into this idea, we ought to have that first.

**Comment by jpmedley** [comment]
I wonder if this is why we made the decision to use ≤37 and we've simply
forgotten.
Joe Medley | Technical Writer, Chrome DevRel | jmedley@google.com |
 816-678-7195
*If an API's not documented it doesn't exist.*

**Comment by vinyldarkscratch** [comment]
It's known that WebView Android explicitly disables certain features.  Perhaps that is what the documentation means, regarding WebView for Android 4.4?

On a related note, I recently managed to get my hands on an Android 4.4 emulator as well, so I'll be able to test and submit data with its assistance.  That should help with getting some more ranges turned into real values in the future.

**Comment by jpmedley** [comment]
"It's known that WebView Android explicitly disables certain features.
Perhaps that is what the documentation means, regarding WebView for Android
4.4?"

I'm not sure what you mean by that. WebView lacks certain features because
they're provided by the native app wrapper.
Joe Medley | Technical Writer, Chrome DevRel | jmedley@google.com |
 816-678-7195
*If an API's not documented it doesn't exist.*

**Comment by vinyldarkscratch** [comment]
> "It's known that WebView Android explicitly disables certain features. Perhaps that is what the documentation means, regarding WebView for Android 4.4?" I'm not sure what you mean by that. WebView lacks certain features because they're provided by the native app wrapper.

Sorry, I'm bad at explaining things...

What I mean is: there are several features that are in Chrome Android, but explicitly disabled (as documented in the [`not-webview-exposed.txt`](https://source.chromium.org/chromium/chromium/src/+/master:android_webview/tools/system_webview_shell/test/data/webexposed/not-webview-exposed.txt?q=not-webview-exposed) file).  I'm wondering if the part of the documentation that says "This WebView does not have full feature parity with Chrome for Android" is referring to that?

**Comment by jpmedley** [comment]
No way to tell, but I doubt it. That was before Chromium started providing
native-like features, so there were fewer reasons to deliberately break
parity in those days.
Joe Medley | Technical Writer, Chrome DevRel | jmedley@google.com |
 816-678-7195
*If an API's not documented it doesn't exist.*

**Comment by ddbeck** [comment]
I don't think there's much more to discuss here, so I'm going to close this. Thanks everyone!
