### ISSUE TITLE
iPhone compatibility missing?

### ISSUE THREAD

**Issue by corysimmons** [mdn/browser-compat-data#7558]
For instance, "Chrome for Android" is listed here, but no iPhone data?

https://developer.mozilla.org/en-US/docs/Web/API/Navigator/xr#Browser_compatibility

**Comment by vinyldarkscratch** [comment]
We do track data for iOS and iPadOS, see the "Safari for iOS" column.  There's been some discussion to rename the label to just "iOS" to reduce the confusion (see #4833).  To give some more context, all browsers on iOS use a Safari WebKit version built into the operating system, regardless of the app -- thus, Chrome on iOS is actually just Safari on iOS with a different UI.

Hope this helps!

**Comment by corysimmons** [comment]
>Chrome on iOS is actually just Safari on iOS with a different UI

Oh fascinating. Thank you
