### ISSUE TITLE
exportparts supported from Firefox 72

### ISSUE THREAD

**Issue by rsgranne** [mdn/browser-compat-data#7560]
https://caniuse.com/?search=exportparts shows that Firefox does not support the `exportparts` attribute. However, my own testing on Browser Stack shows that `exportparts` is supported as of Firefox 72 on Windows 10, using this URL: https://codepen.io/websanity/pen/ExgjbxZ?editors=1100.

**Comment by ddbeck** [comment]
Thanks for reporting this, @rsgranne! Your tests are backed up by a couple of Firefox bugs too:

https://bugzilla.mozilla.org/show_bug.cgi?id=1559074
https://bugzilla.mozilla.org/show_bug.cgi?id=1594275

I'd welcome a PR setting the value to version "72" (for desktop) and "79" (for Android), if you (or another contributor) is interested. Here's the relevant portion of `global_attributes.json`:

https://github.com/mdn/browser-compat-data/blob/2b87a204e620723a3bbebbf5aceb91734cfc52a1/html/global_attributes.json#L866-L910

Thank you!

**Comment by Elchi3** [comment]
Fixed in https://github.com/mdn/browser-compat-data/pull/7382
