### ISSUE TITLE
scroll-margin-top is now supported in safari

### ISSUE THREAD

**Issue by NicoHood** [mdn/browser-compat-data#7564]
https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-margin-top

The linked issue has been recently closed. I am not sure which browser version fixes the issue (also not sure about ios), but it seems that compatibility can be marked green now.

https://bugs.webkit.org/show_bug.cgi?id=189265

**Comment by vinyldarkscratch** [comment]
This has been resolved by #10129, I believe!
