### ISSUE TITLE
Javascript Export Statement: Android WebView Support

### ISSUE THREAD

**Issue by aaronransley** [mdn/browser-compat-data#7571]
With Android [WebViews being handled by Chrome starting in v7](https://www.androidpolice.com/2016/07/20/google-explains-chrome-will-become-webview-android-7-0/), I am curious why the [`export` statement here](https://github.com/mdn/browser-compat-data/blob/33e16f5c6d29a8475b4520987614f7a059eb38dd/javascript/statements.json#L580-L688) is marked as incompatible across all versions of Android WebView.

![image](https://user-images.githubusercontent.com/5669055/101213718-10a13180-3638-11eb-9114-5673fd4f0410.png)

**Comment by ddbeck** [comment]
Hi @aaronransley, thanks for reporting this. Looking at the history the data, it looks like this feature data was brought into BCD during our initial migration from the (unverified) hand-written tables on MDN. It's extremely likely that the WebView version should be the same as Chrome and Chrome for Android. I'd welcome a PR updating those values in the file that you linked to. Thank you again!

**Comment by jculver050** [comment]
Close
