### ISSUE TITLE
<video playsinline> and <video webkit-playsinline> content attributes

### ISSUE THREAD

**Issue by foolip** [mdn/browser-compat-data#7611]
https://github.com/mdn/browser-compat-data/pull/7604 adds the reflected `playsInline` IDL attribute, but we're missing the content attribute in html/elements/video.json.

There's a prefixed variant, `webkit-playsinline`, which was added way back in https://trac.webkit.org/changeset/160733/webkit, and then unprefixed in https://trac.webkit.org/changeset/202660/webkit. There was never a prefixed IDL attribute, however.

It's probably a good to add notes to the IDL attribute about the content attribute being supported earlier.

**Comment by jculver050** [comment]
Close
