### ISSUE TITLE
Attributes potentially incorrectly set to introduced in Chrome 44

### ISSUE THREAD

**Issue by foolip** [mdn/browser-compat-data#7755]
The kind of issue with attributes, and in particular `length` attributes, mentioned in https://github.com/mdn/browser-compat-data/pull/7749#pullrequestreview-551329381 appears to already have happened in BCD.

These are attributes claimed to be introduced in Chrome 44 that need double checking:
- api.AudioBufferSourceNode.detune
- api.CSSKeyframesRule.cssRules
- api.CSSKeyframesRule.name
- api.CSSStyleDeclaration.length
- api.Document.scrollingElement
- api.HTMLAllCollection.length
- api.TextTrackList.length

**Comment by foolip** [comment]
https://github.com/mdn/browser-compat-data/issues/7843 is similar, but for Chrome 43.

**Comment by ddbeck** [comment]
I don't follow the problem for length here. Can you elaborate on what we're talking about here? The linked review wasn't particularly illuminating (just "suspicious").

**Comment by foolip** [comment]
I haven't looked into the details, but `length` properties seem to often be different from other attributes, appearing on instances rather than on the prototype even after the point where attributes in general moved from the instances to prototypes in various engines.

But in addressing this issue there's no need to handle `length` properties differently, like for all attributes we just need to check if they're on an instance rather than just looking at the prototype.

**Comment by queengooborg** [comment]
I researched this and found the following info:

- api.AudioBufferSourceNode.detune - Comes from #1579, confirmed by the collector
- api.CSSKeyframesRule.cssRules - Comes from #6908, collector test is returning "null"
- api.CSSKeyframesRule.name - Also comes from #6908, collector test is returning "null"
- api.CSSStyleDeclaration.length - Comes from #6976, collector now says "1"
- api.Document.scrollingElement - Comes from #1324 (wiki migration), but collector agrees
- api.HTMLAllCollection.length - Comes from #2470 (wiki migration), collector now says "6"
- api.TextTrackList.length - Updated in #14352

I'll submit PRs for these!

**Comment by queengooborg** [comment]
PRs have been submitted for the two I'm able to update at this point -- I plan to follow up with `CSSKeyframesRule` in the future, once the test is fixed!

**Comment by foolip** [comment]
@queengooborg did you mean to close this even though the fixes aren't landed yet?

**Comment by queengooborg** [comment]
I did, with the thought that we will follow up with collector results as it is.  If you'd prefer, we can keep it open until the collector's fixed and the data has all been fixed!

**Comment by foolip** [comment]
With https://github.com/mdn/browser-compat-data/pull/15864 merged only `CSSKeyframesRule` remains from the original list.

**Comment by foolip** [comment]
Two more that will need to be checked, added since I filed this issue:
- api.Notification.data
- api.Response.redirect

**Comment by foolip** [comment]
https://mdn-bcd-collector.appspot.com/tests/api/Notification/data confirmed with Chrome 43/44, and that test doesn't use prototype testing.

**Comment by foolip** [comment]
api.Response.redirect is a method, so can't have this problem. Closing.
