### ISSUE TITLE
api.HTMLHyperlinkElementUtils - Chromium notes about "member moving" are misleading

### ISSUE THREAD

**Issue by here-nerd** [mdn/browser-compat-data#7823]
#### What information was incorrect, unhelpful, or incomplete?
The page indicates that "Starting in Chrome 52, the members of this interface were moved to URL" while they are, in fact, still available in Chrome 87. This misleads the developers to avoid using this interface while it is still working fine as documented in the HTML Living Standard on 14 Dec 2020, (https://html.spec.whatwg.org/multipage/links.html#htmlhyperlinkelementutils) and there is no evidence that Chrome 52 deprecated / removed those interface members (https://developers.google.com/web/updates/2016/06/chrome-52-deprecations). Please correct it.

#### What did you expect to see?
Just simply 'yes'. 

#### Did you test this? If so, how?
- yes
- open a console in Chrome 87 and try this code:
x = document.createElement('a') // <a>​</a>​
x.href = 'https://www.bol.com' // "https://www.bol.com"
x.hostname // "www.bol.com"
x.protocol // "https:"

<details>
<summary>MDN page report details</summary>

* Query: `api.HTMLHyperlinkElementUtils`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLHyperlinkElementUtils
* Report started: 2020-12-14T18:54:48.619Z

</details>

**Comment by ddbeck** [comment]
Thanks for reporting this, @here-nerd. It's a weird note, isn't it?

This note was added to [`HTMLHyperlinkElementUtils.json`](https://github.com/mdn/browser-compat-data/blob/master/api/HTMLHyperlinkElementUtils.json) during the migration from the (former) wiki into this project (#1265). I think notes originally tried to capture something else and got mixed up in migration. The changes in [Chrome bug 604644](https://bugs.chromium.org/p/chromium/issues/detail?id=604644) (which appears to have landed in Chrome 52) shows a move _from_ the historic `URLUtils` interface _to_ the contemporary `HTMLHyperlinkElementUtils`.

A couple of ideas for fixes here:

1. The formally correct, but still also unhelpful-to-developers option is to rewrite the note to say something along the lines of "Before version 52, the members of this interface are part of the obsolete `URLUtils` interface."
2. The less correct but probably less confusing option is to remove these notes.

Mixins have always proved troublesome, so I'm not actually sure what the right call is here.

@Elchi3, maybe you've got an opinion on this? You were a reviewer on the original PR, after all. 🙃

**Comment by Elchi3** [comment]
> @Elchi3, maybe you've got an opinion on this? You were a reviewer on the original PR, after all. upside_down_face

I believe this is an instance of https://github.com/mdn/browser-compat-data/issues/7517? It is a complex issue and I haven't researched more into it yet. However, I'm also wondering if these details of the platform are really useful to expose. Maybe documentation sometimes needs to decide that information is better left out to avoid confusion :)

**Comment by vinyldarkscratch** [comment]
I agree, this note is certainly misleading and implies that there is no support past Chrome 52.  Looking at the [diff](https://chromium.googlesource.com/chromium/src.git/+/40ebec288b976477aaa318b26899dc08f5b15426%5E%21/#F1) for the commit linked by Daniel up above, the `URLUtils` mixin was renamed to `HTMLHyperlinkElementUtils`, and its members were copied to `URL` (vs. implementing the mixin before).  Thus, there isn't really any difference to web developers, and so I feel that these notes should simply be removed.
