### ISSUE TITLE
Attributes incorrectly claimed to be added in Chrome 43

### ISSUE THREAD

**Issue by foolip** [mdn/browser-compat-data#7843]
Chrome 43 fixed its bindings so that Web IDL attributes appear on the prototypes:
https://developers.google.com/web/updates/2015/04/DOM-attributes-now-on-the-prototype-chain

Because of this, tests like `'attributeName' in InterfaceName` can be misleading, suggesting that something was added in Chrome 43. This has come up a lot in @vinyldarkscratch's and my work on https://github.com/foolip/mdn-bcd-collector.

Not all cases of this have been caught in review, and `npm run traverse chrome api 43` lists a lot of features. Some of these were introduced earlier, for example api.HTMLMediaElement.volume is much older.

We need to go through any attributes claimed to be added in Chrome 43 and check if they were really available earlier.

**Comment by foolip** [comment]
https://github.com/mdn/browser-compat-data/issues/7755 is similar, but for Chrome 44.

**Comment by foolip** [comment]
While reviewing https://github.com/mdn/browser-compat-data/pull/7990 I spotted some that I'm almost certain are incorrect and need fixing as part of this issue, namely api.HTMLMediaElement.*. Those are all very old APIs, not introduced in Chrome 43.

**Comment by ddbeck** [comment]
@foolip What's the trick to testing that attributes are supported before 43? Testing on actual instances, instead of the prototype?

**Comment by foolip** [comment]
@ddbeck exactly, an instance is needed, and that's what collector fixes like https://github.com/foolip/mdn-bcd-collector/pull/1247 ends up doing.

**Comment by queengooborg** [comment]
I think that we've pretty much fixed this, and any additional instances should be catchable by the collector.  I'm going to close this issue and consider it to be a part of the bigger collector synchronization goal.
