### ISSUE TITLE
Audit Chrome 45 versions

### ISSUE THREAD

**Issue by foolip** [mdn/browser-compat-data#7844]
The "Find Releases" tool at the bottom of https://omahaproxy.appspot.com/ is often used by BCD contributors to figure out which Chrome release a certain Chromium commit was first included in.

Back in [Sep 2015](https://chromium.googlesource.com/chromium/src/+/b59b6df51a249895fbba24f92b661f744e031546), the Blink and Chromium repositories were merged. That was for Chrome 47. Whether related to that merge or not, I have observed that trying to use the "Find Releases" tool with commits much older than that often incorrectly says that something was in Chrome 45, despite it actually being in an earlier release.

As an example, https://storage.googleapis.com/chromium-find-releases-static/243.html#24375f20cd603d56b8847b329209964c1281ba7a says "initially landed in 45.0.2454.101" but looking up the time of the commit with https://www.chromium.org/developers/calendar gives Chrome 43. I've seen this many times.

I would treat Chrome 45 as worthy of extra scrutiny in review, and moreover think we should go over the list of features in `npm run traverse chrome api 45` and make sure the data can be confirmed by http://mdn-bcd-collector.appspot.com/. Where we have no tests, the existing data might well be wrong because of this reason. 

@ddbeck @Elchi3 @jpmedley @sideshowbarker @vinyldarkscratch FYI

**Comment by jculver050** [comment]
Close

**Comment by foolip** [comment]
See https://github.com/mdn/browser-compat-data/pull/11631#discussion_r673354547 about `CSSGroupingRule`, a change that *did* happen in Chrome 45 but should perhaps be tweaked per https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines.md#apis-moved-on-the-prototype-chain

**Comment by foolip** [comment]
Burndown list to verify or fixed based on `npm run traverse chrome all 45`:

- [ ] api.CSSGroupingRule.* - https://github.com/mdn/browser-compat-data/issues/7844#issuecomment-883580883
- [ ] api.CSSKeyframesRule.appendRule (as insertRule)
- [ ] api.Client.postMessage
- [ ] api.Document.pointerlockchange_event (webkit prefix)
- [ ] api.Document.pointerlockerror_event (webkit prefix)
- [ ] api.FetchEvent.isReload
- [ ] api.FontFace.load
- [ ] api.FontFace.load
- [ ] api.FontFace.loaded
- [ ] api.FontFace.loaded
- [ ] api.HTMLElement.contextMenu
- [ ] api.HTMLLinkElement.integrity
- [ ] api.HTMLScriptElement.integrity
- [ ] api.MIDIAccess.sysexEnabled
- [ ] api.MediaQueryList.EventListener_objects
- [ ] api.MediaQueryList.EventTarget_inheritance
- [ ] api.MediaQueryList.change_event
- [ ] api.MediaStream.active
- [ ] api.MediaStream.active_event
- [ ] api.MediaStream.clone
- [ ] api.MediaStream.getTracks
- [ ] api.MediaStream.inactive_event
- [ ] api.MediaStreamTrack.clone
- [ ] api.Notification.worker_support
- [ ] api.PerformanceEntry.toJSON
- [ ] api.Range.compareNode
- [ ] api.SVGFESpecularLightingElement.kernelUnitLengthX
- [ ] api.SVGFESpecularLightingElement.kernelUnitLengthY
- [ ] api.SVGRenderingIntent
- [ ] api.ServiceWorkerContainer.getRegistrations
- [ ] api.ServiceWorkerRegistration.showNotification.actions
- [ ] api.ServiceWorkerRegistration.showNotification.vibrate
- [ ] api.ServiceWorkerRegistration.update
- [ ] api.Text.replaceWholeText
- [ ] api.UIEvent.layerX
- [ ] api.UIEvent.layerY
- [ ] css.at-rules.keyframes.ignore_important_declarations
- [ ] css.at-rules.media.display-mode
- [ ] css.properties.list-style-type.*
- [ ] html.elements.link.integrity
- [ ] html.elements.script.integrity
- [ ] svg.elements.feComposite.operator.lighter
- [ ] javascript.builtins.Array.copyWithin
- [ ] javascript.builtins.Array.fill
- [ ] javascript.builtins.Array.find
- [ ] javascript.builtins.Array.findIndex
- [ ] javascript.builtins.Array.from
- [ ] javascript.builtins.Array.of
- [ ] javascript.builtins.Object.assign
- [ ] javascript.builtins.Symbol.unscopables
- [ ] javascript.builtins.TypedArray.*
- [ ] javascript.functions.arrow_functions

**Comment by queengooborg** [comment]
All Chrome 45 data has now been audited!
