### ISSUE TITLE
css.properties.scale - support as of STP 117

### ISSUE THREAD

**Issue by graouts** [mdn/browser-compat-data#7853]
As of Safari Technology Preview 117, the `scale` property is fully supported as reported on this [WebKit blog post](https://webkit.org/blog/11420/css-individual-transform-properties/).

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.scale`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/scale
* Report started: 2020-12-15T08:17:43.686Z

</details>

**Comment by vinyldarkscratch** [comment]
This was included in the Safari 14.1 release, which is expressed in the changes from #10129!
