### ISSUE TITLE
javascript.builtins.Object.assign - incorrect support stated for IE11 

### ISSUE THREAD

**Issue by essentin** [mdn/browser-compat-data#7872]
#### What information was incorrect, unhelpful, or incomplete?
Browser compatibility chart states that `Object.assign` is not supported by IE11

#### What did you expect to see?
`Object.assign` support at least for IE11

#### Did you test this? If so, how?
Tested on local IE11 and remote one via browserstack. Entered `Object.assign({a:1},{b:2})` directly in the console and got a correct return value of `{a:1,b:2}`

<details>
<summary>MDN page report details</summary>

* Query: `javascript.builtins.Object.assign`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign
* Report started: 2020-12-15T13:28:43.170Z

</details>

**Comment by ddbeck** [comment]
Hi @essentin and thanks for opening this issue. I'd welcome a PR (from you or another contributor) correcting this data in [`Object.json`](https://github.com/mdn/browser-compat-data/blob/master/javascript/builtins/Object.json#L108). At that time, we might want to test to confirm that `"11"` is the correct `"version_added"` value, but that seems likely.

**Comment by joneskj55** [comment]
@ddbeck @essentin I can knock this out real quick if you would like. But if someone is already doing it please let me know.

**Comment by Elchi3** [comment]
The kangax table does show this as unsupported in IE11 too. I think it would be good to double-check first before changing this.

**Comment by ddbeck** [comment]
OK, I just tested with IE10 in BrowserStack and it failed. So we're good to go with `"11"`. 👍

**Comment by Elchi3** [comment]
> So we're good to go with `"11"`. +1

Are you sure? We had this story before:
First https://github.com/mdn/browser-compat-data/pull/3965 and then https://github.com/mdn/browser-compat-data/pull/4029

Are we again tricked by polyfills here?

**Comment by ddbeck** [comment]
Ugh, yes, I goofed here. I misread @Elchi3's earlier comment as the kangax table showing that it was _supported_, so  I tried it in IE 10 but not 11. I just tested in IE11 and it _also_ failed there. I rushed things—sorry about that.

I guess I'll close this since the data is correct. Though I wish we could we mark some data as "no, seriously". 😳

**Comment by Elchi3** [comment]
I reckon IE 11 not having Object.assign is one of the top pain points for web developers. So much that they want to change the compat table regularly :smile:
