### ISSUE TITLE
javascript.operators.this - текст ltr

### ISSUE THREAD

**Issue by DarkGoanna** [mdn/browser-compat-data#7887]
Chrome Версия 87.0.4280.88
<a href="https://ibb.co/R6PyFZm"><img src="https://i.ibb.co/X5p8QNg/image.png" alt="image" border="0"></a>

<details>
<summary>MDN page report details</summary>

* Query: `javascript.operators.this`
* MDN URL: https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/this
* Report started: 2020-12-15T19:31:44.118Z

</details>

**Comment by vinyldarkscratch** [comment]
Closing this issue since this is a styling issue, not an issue with the browser compatibility table.
