### ISSUE TITLE
Pointer events in Safari?

### ISSUE THREAD

**Issue by arivoir** [mdn/browser-compat-data#7898]
Pointer events seems to work on Safari for mac.

<details>
<summary>MDN page report details</summary>

* Query: `api.HTMLElement.pointerdown_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/pointerdown_event
* Report started: 2020-12-15T23:52:36.386Z

</details>

**Comment by ddbeck** [comment]
Thanks for reporting this, @arivoir. Since #8709 contains more information, I'm marking this issue as a duplicate and closing it. If you'd like to contribute more details or participate in fixing this data, please check out #8709. Thank you again!
