### ISSUE TITLE
javascript.builtins.Generator - wrong output

### ISSUE THREAD

**Issue by reza-bm** [mdn/browser-compat-data#7922]
**the output of the example is wrong :**
console.log(gen.next().value); // 1
console.log(generator().next().value); // 1
console.log(generator().next().value); // 1

**correct output :**
console.log(gen.next().value); // 1
console.log(generator().next().value); // 2
console.log(generator().next().value); // 3

<details>
<summary>MDN page report details</summary>

* Query: `javascript.builtins.Generator`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator
* Report started: 2020-12-16T11:12:19.989Z

</details>

**Comment by vinyldarkscratch** [comment]
This sounds like it's not a problem with BCD, but a problem with the page's content.  Can you open up an issue using the "report a problem" link at the _very_ bottom of the page (not the one above the compat table)?
