### ISSUE TITLE
api.Notification.Notification - Chrome Android is not supported

### ISSUE THREAD

**Issue by O-Ami** [mdn/browser-compat-data#7923]
#### What information was incorrect, unhelpful, or incomplete?
Notification constructor is not supported on Chrome Android. It throws an error `Failed to construct 'Notification': Illegal constructor. Use ServiceWorkerRegistration.showNotification() instead.` [According to google developer doc](https://developers.google.com/web/updates/2015/05/notifying-you-of-changes-to-notifications#android_notifications) and [Chrome Issue Tracker](https://developer.mozilla.org/en-US/docs/Web/API/Notification/Notification#Browser_compatibility), this was never supported on android. 

#### What did you expect to see?
On Browser compatibility for `Notification constructor` ([Link](https://developer.mozilla.org/en-US/docs/Web/API/Notification/Notification#Browser_compatibility)), it should state `No` for Chrome Android

#### Did you test this? If so, how?
I've tested `new Notification('test')` on Chrome Android and it throws the above error. It is working on desktop.

<details>
<summary>MDN page report details</summary>

* Query: `api.Notification.Notification`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Notification/Notification
* Report started: 2020-12-16T16:03:07.208Z

</details>

**Comment by ddbeck** [comment]
Thanks for opening this issue, @O-Ami. You're right that the data is off here. It's also unsupported in WebView (listed in [`not-webview-exposed.txt`](https://source.chromium.org/chromium/chromium/src/+/master:android_webview/tools/system_webview_shell/test/data/webexposed/not-webview-exposed.txt)).

I'd welcome a PR (from you or another contributor), setting the `chrome_android` and `webview_android` values to `false` throughout [`Notification.json`](https://github.com/mdn/browser-compat-data/blob/master/api/Notification.json).

**Comment by ddbeck** [comment]
#8113 fixed this for Chrome for Android. Leaving the derivative browsers (webview_android and likely opera_android and samsung_internet, now that I think of it.)

**Comment by ddbeck** [comment]
OK, I goofed here, which I discovered while reviewing #9077. I misunderstood the linked documentation. The story with `Notification` on Android appears to be more complex than I first realized. Here's the main story:

1. WebView does not support notifications. At all. See [bug 551446](https://bugs.chromium.org/p/chromium/issues/detail?id=551446).
2. Chrome for Android does support notifications, but only in the context of a service worker. [This Google article](https://developers.google.com/web/updates/2015/05/notifying-you-of-changes-to-notifications#android_notifications) says that `new Notification('')` has never been supported on Android, but goes on to say that  

   > However, with push notification support now on Chrome for Android, notifications can be created from a ServiceWorker, but not from a web page, meaning this feature detect is no longer appropriate. If you try and create a notification on Chrome for Android you'll receive this error message:
   >
   > _Uncaught TypeError: Failed to construct 'Notification': Illegal constructor. Use ServiceWorkerRegistration.showNotification() instead_

   I take this to mean that:

   * the `Notification` interface exists on Chrome for Android in all versions where the push API is supported ([which is Chrome 42 and later](https://www.chromestatus.com/feature/5480344312610816))
   * the `Notification()` constructor is unsupported in all contexts on Chrome for Android

So, to get this right, we need to do the following:

- Revert #8113.
- Report `api.Notification.Notification` as unsupported on Chrome for Android (etc.)
- Report `api.Notification.*` as unsupported on WebView
- Dig deeper into the various subfeatures of `api.Notification` to get the data into more reliable shape

**Comment by ddbeck** [comment]
On that last point: @vinyldarkscratch and @foolip, I'd be interested in hearing how you'd go about testing for this oddity in `api.Notification` (`new Notification()` throws an unusual exception which doesn't actually indicate lack of support). It's very strange, but only strange on Chrome for Android.

**Comment by foolip** [comment]
@ddbeck the generated tests for constructors attempt to call the constructor with no arguments and if an exception is thrown, looks at the error message:
https://github.com/foolip/mdn-bcd-collector/blob/213350e4716a8d3a5c2bdc0709cce234472dfc13/static/resources/harness.js#L113-L145

@vinyldarkscratch came up with this and it's worked surprisingly well (avoids finding the right arguments for every constructor!) but in this case it did the wrong thing, because the error in Chromium comes after the generating constructor bindings code which our tests probe for:
https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/modules/notifications/notification.cc;l=76;drc=b7abd7675ebce2f944c389f580f9fc1512c40875

I've filed https://github.com/foolip/mdn-bcd-collector/issues/970.

**Comment by ddbeck** [comment]
I opened https://github.com/mdn/browser-compat-data/pull/9139 to make the Chrome for Android data somewhat less incorrect, reverting #8113.

**Comment by bh3605** [comment]
What a great idea using eval("new Notification('')") as a feature detector! I thought I'd be forced to do some browser version sniffing in the user agent string.
