### ISSUE TITLE
Support data for constants?

### ISSUE THREAD

**Issue by saschanaz** [mdn/browser-compat-data#7936]
I had to manually remove some undersupported `CSSRule` constants while working on https://github.com/saschanaz/types-web/commit/88295d4f3fc491098b8f6cf1c9bc98f1514ede11, and found there is no support data for the constants except for `KeyboardEvent`. Would it be helpful to include them?

**Comment by vinyldarkscratch** [comment]
There's been some discussion on this, for example https://github.com/mdn/browser-compat-data/pull/7580#issuecomment-739839319.  I can't find the exact PR/issue where it was mentioned, but overall we figured that constant data is not useful to web developers.

**Comment by ddbeck** [comment]
Based on the discussion on #7585, I think we have consensus that we shouldn't include constants (unless we discover there are real compatibility issues raised by constants). I'd welcome a data guideline to document this policy (or I'll get to it… eventually).

**Comment by sideshowbarker** [comment]
> Based on the discussion on #7585, I think we have consensus that we shouldn't include constants (unless we discover there are real compatibility issues raised by constants). I'd welcome a data guideline to document this policy (or I'll get to it… eventually).

I went ahead and raised #8062 with proposed language.

**Comment by ddbeck** [comment]
We now have a guideline rejecting new constants in BCD. See https://github.com/mdn/browser-compat-data/pull/8062.

Repeating myself for anyone watching here: we'll need a separate issue for finding and pruning constants that have already slipped in, if that's something we want to do, but I think we've answered the question that kicked off the issue in the first place. If there's no objections, I'll close this one.
