### ISSUE TITLE
api.Window.scrollTo - `ScrollToOptions` parameter is supported by Safari

### ISSUE THREAD

**Issue by souldzin** [mdn/browser-compat-data#7959]
#### What information was incorrect, unhelpful, or incomplete?

The browser compatability info for `ScrollToOptions` in Safari seems to be inaccurate:

<details>
<summary>Screenshot</summary>

![Screen Shot 2020-12-16 at 1 49 32 PM](https://user-images.githubusercontent.com/4908127/102398945-8fd22600-3fa5-11eb-83d2-516da5b5d685.png)

</details>

#### What did you expect to see?

It looks like Safari actually does support `ScrollToOptions` parameter, which is even consistent with https://developer.mozilla.org/en-US/docs/Web/API/ScrollToOptions.

#### Did you test this? If so, how?

I ran `window.scrollTo({ top: 0 })` in the dev console of any site and it behaved as expected.

<details>
<summary>MDN page report details</summary>

* Query: `api.Window.scrollTo`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollTo
* Report started: 2020-12-16T19:47:33.426Z

</details>

**Comment by ddbeck** [comment]
Thanks for reporting this issue, @souldzin. It looks like the [`api.Window.scrollTo`](https://github.com/mdn/browser-compat-data/blob/master/api/Window.json#L8348) and [`api.ScrollToOptions`](https://github.com/mdn/browser-compat-data/blob/master/api/ScrollToOptions.json) data needs to be updated (and reconciled).

The missing piece here would be to find out when Safari introduced support for this, either by direct testing or to search through WebKit's bugs or changes.

**Comment by ddbeck** [comment]
I didn't realize this issue already existed when I started following up on #9059. Since there's additional detail there, I'm going to close this one in favor the other (even though this one came first).
