### ISSUE TITLE
javascript.classes - Incorrect link

### ISSUE THREAD

**Issue by joneit** [mdn/browser-compat-data#7962]
#### What information was incorrect, unhelpful, or incomplete?

\[Private class fields] in the _Browser Compatibility_ table links to Public Class Fields page not Private Class Fields page

#### Did you test this? If so, how?

<details>
<summary>MDN page report details</summary>

* Query: `javascript.classes`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes
* Report started: 2020-12-17T02:14:35.915Z

</details>

**Comment by ddbeck** [comment]
Thanks for reporting this issue, @joneit. I suspect the content moved after the BCD feature was created.

To fix this, the data in [`classes.json`](https://github.com/mdn/browser-compat-data/blob/master/javascript/classes.json#L479) needs to be corrected. Specifically, the `mdn_url` field for `private_class_fields` needs to be changed to point to https://developer.mozilla.org/docs/Web/JavaScript/Reference/Classes/Private_class_fields.

I'd welcome a PR (from you or another contributor), making this fix. Thank you!

**Comment by ddbeck** [comment]
This was fixed in #8024. Closing this up.
