### ISSUE TITLE
api.Animation.currentTime - Safari support

### ISSUE THREAD

**Issue by nathggns** [mdn/browser-compat-data#7992]
#### What information was incorrect, unhelpful, or incomplete?

`Animation.prototype.currentTime` is reported to not exist at all on Safari. This seems to apply also for `.pause` and `.play` (and possibly others).

#### What did you expect to see?

Considering I can use these features in Safari 14 and Safari 13.1 at least, it seems this information is at least inaccurate for Safari 14 and Safari 13.1.

#### Did you test this? If so, how?

I tested with [this CodeSandbox](https://codesandbox.io/s/animation-sync-bwbz7?file=/src/App.js) which allows you to add and remove spinners whilst the animations stay in sync using a combo of `currentTime`, `pause`, and `play`. You can toggle the sync code on/off for new spinners with a checkbox, and the not synced ones are shown in red. You can remove a spinner by clicking on it. 

Screenshot from the demo showing some in sync and some not (though they were added to the page at different times). You should really try the demo out first though. 

![image](https://user-images.githubusercontent.com/719814/102517340-d304c580-4087-11eb-8792-69e50e3793b0.png)

It's written in React but it should be a fairly accessible demo even for those who are not familiar. The important code is this, which runs when the spinners are added to the page

```js
const node = ref.current; // Get our new spinner from React
const spinners = Array.from(document.querySelectorAll(".Spinner"));

if (spinners.length > 1) {
  for (const spinner of spinners) {
    spinner.getAnimations()[0].pause();
  }

  const spinner = spinners.find((spinner) => spinner !== node);

  node.getAnimations()[0].currentTime = spinner.getAnimations()[0].currentTime;

  for (const spinner of spinners) {
    spinner.getAnimations()[0].play();
  }
}
```

This *definitely* works in Safari 14 running on macOS Catalina which I've ran on my machine. I've also tested this demo on Safari 13.1 on macOS Catalina via Browserstack where it works. I don't have access to a Safari 13 instance but this demo doesn't work on Safari 12 (though this is because getAnimations isn't support there at all). 

<details>
<summary>MDN page report details</summary>

* Query: `api.Animation.currentTime`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Animation/currentTime
* Report started: 2020-12-17T16:18:58.398Z

</details>

**Comment by ddbeck** [comment]
Thanks for reporting this (and very thoroughly!), @nathggns! I've got some more context and next steps.

WebKit [implemented this attribute](https://trac.webkit.org/changeset/224163/webkit) long before it actually shipped in Safari proper. Based on the changesets in WebKit, I expect that this appeared in the first Safari release with Web Animations turned on by default, which was [Safari 13.1](https://webkit.org/blog/10247/new-webkit-features-in-safari-13-1/). Earlier versions of Safari may have supported it behind an experimental preference, but it was sufficiently long ago that I don't think we should bother investigating it.

To actually fix this data, we need a PR (from you or another contributor) which changes the `currentTime` data in [`Animation.json`](https://github.com/mdn/browser-compat-data/blob/master/api/Animation.json#L298-L371). Specifically, the values for Safari and Safari for iOS need to be changed to 13.1 and 13.4, respectively.

**Comment by nathggns** [comment]
@ddbeck thanks for detailing how to address this. I don't have a huge amount of time to research if other properties are available in Safari but I've submitted a PR addressing for the properties listed here. https://github.com/mdn/browser-compat-data/pull/8712
