### ISSUE TITLE
share_target - Add data for web app manifest

### ISSUE THREAD

**Issue by Yash-Singh1** [mdn/browser-compat-data#8007]
#### What information was incorrect, unhelpful, or incomplete?

`share_target` is not in the compatibility data

#### What did you expect to see?

The compatibility data to be there

#### Did you test this? If so, how?

Checked the directory `html/manifest`

#### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

Google's docs: https://web.dev/web-share-target/

#### Note

It isn't even in the `mdn` docs.

**Comment by ddbeck** [comment]
Thanks for reporting this, @Yash-Singh1.

To create the data, we need a PR from you (or another contributor) which creates a new `share_target.json` file in [`/html/manifest/`](https://github.com/mdn/browser-compat-data/tree/master/html/manifest). I don't have any detailed information to add about support, though there does seem to be some information on Chrome Platform Status ([1](https://chromestatus.com/feature/5662315307335680), [2](https://chromestatus.com/feature/6124071381106688)).

One last thing:

> It isn't even in the `mdn` docs.

If you'd like to see something like this documented, then please open a PR or issue on [mdn/content](https://github.com/mdn/content/).

**Comment by jculver050** [comment]
Close

**Comment by queengooborg** [comment]
Looks like this has been resolved by #13803!
