### ISSUE TITLE
version_added is not a version

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/browser-compat-data#8074]
Sometimes `version_added` is not a version like `1.1.2.56` but is a string that starts with `<=` like `"<=1.1.1.1"`.

**Comment by vinyldarkscratch** [comment]
For certain browsers, it is near impossible to test older versions.  As such, we create ranges for the versions to say "it's at least in this version, but it could be implemented in an older version" (ex. `≤37` means "version 37 or before").  This decision was made in #4330, and has expanded for other browsers in #4610, #6807, and #7337.

**Comment by mattiapontonio** [comment]
I understand why but this can create issues on both the JSON schema and the React if we were to process the data.

So I think it is useful to stay _consistent with the type_ and name `"version_added"` of type "_Version_" and at most find another place to communicate this information.

If we really wanted to be strict the answer is `null` because the data is not known. 

You could add a key if you want with an estimate but I am focused on this in object. 
Let's assume we had to break it down by character `.`other characters can create issues.

**Comment by vinyldarkscratch** [comment]
Do you have a particular example of the ranged version (a version with a `≤` prefix) causing issues?

**Comment by mattiapontonio** [comment]
![Screenshot_20201221-022335.png](https://user-images.githubusercontent.com/44380480/102730109-b68cb580-4333-11eb-8f3c-8f950b55b853.png)

- In this table we say version in the table header.
- The range is clear here but not in the "final reader".
- The data is a version number and not a range of version.
- When the row should be green and when red?

- https://github.com/mdn/yari/issues/1925

**Comment by vinyldarkscratch** [comment]
Thanks for the example, and I see your point.  From your first linked issue (https://github.com/mdn/yari/issues/1925), I found https://github.com/mdn/yari/issues/1607 which talks more about the display on the MDN web docs pages.  May we get your input on that issue?  (I'm seeing this as more of a display issue on the MDN pages rather than a data issue, but I'll ask @ddbeck what he thinks when he is back.)

**Comment by mattiapontonio** [comment]
https://github.com/mdn/yari/issues/1607 Is the more discussed. Is everiting "_connected_".

The point is that datas are 2 types:

- `added`: a `version number` or `null`
- `supported`: a `boolean`

The range could be important for example if We want to say always N versions so 

- `implemented`
- `unsupported`
- `current`
- `supported` (boolean computed from the 3 version above)

**Comment by mattiapontonio** [comment]
In my opinion, the best thing in the state of the art would be to transform all the unknown versions into `null`s ...
