### ISSUE TITLE
javascript.builtins.Array.findIndex - Work at IE 11

### ISSUE THREAD

**Issue by leon716** [mdn/browser-compat-data#8081]
#### What information was incorrect, unhelpful, or incomplete?
Browser Compatibility on Array.findIndex said No to Internet Explorer.
#### What did you expect to see?
It works at IE 11
#### Did you test this? If so, how?
Using Console of IE 11
var a = [1,2,3]
a.findIndex(function(s){return s ===2}); // return 1

<details>
<summary>MDN page report details</summary>

* Query: `javascript.builtins.Array.findIndex`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/findIndex
* Report started: 2020-12-21T05:54:52.953Z

</details>

**Comment by Elchi3** [comment]
IE 11 does not support findIndex. Which page did you test this on? It probably implements a Polyfill that makes it look like IE11 would support it.
