### ISSUE TITLE
css.properties.-webkit-text-security - firefox compatibility

### ISSUE THREAD

**Issue by 9652818689** [mdn/browser-compat-data#8098]
#### Did you test this? If so, how?

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.-webkit-text-security`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-text-security
* Report started: 2020-12-21T11:32:49.748Z

</details>

**Comment by vinyldarkscratch** [comment]
Please provide more detail on _exactly_ what is wrong with the Firefox compatibility.

**Comment by 9652818689** [comment]
In Firefox this style( style="-webkit-text-security" ) is not working ,how
to fix this problem?

**Comment by vinyldarkscratch** [comment]
This matches our browser compatibility data, Firefox does not support this property.  :)
