### ISSUE TITLE
Consider a way to avoid duplication for entries that share compat data

### ISSUE THREAD

**Issue by ddbeck** [mdn/browser-compat-data#813]
From comments on #725, about avoiding duplication when data is duplicated between entries that differ only in name:

@ddbeck:
> It might be nice to some day have this package to allow a sort of "see also" format (something like `{ "__compat": { "see": "css.properties.some_prop" } }`) to avoid the duplication, though hashing out what that's supposed to mean exactly might be complicated. Should I open an issue for that or is it too rare to matter?

@Elchi3:
> I think the "see also" format is interesting. For APIs, there are sometimes entire feature trees that have the same compat data and we're repeating this info leading to some giant JSON files. On the other hand, and from a data consumer point of view, I feel like I don't want to deal with yet another thing to resolve for displaying the data :-) File an issue, good to have a discussion about this on record.

**Comment by ddbeck** [comment]
Thinking about this now, maybe another pathway to reducing duplication might be something like inlining data, where the data exposed by the package is duplicated, but the source files are free to reference each other (e.g., if `css.properties.prop_b` is marked as a duplicate of `css.properties.prop_a`, querying `css.properties.prop_b` transparently returns `prop_a`'s data, instead of the consumer having to resolve the link).

**Comment by Elchi3** [comment]
That sounds like a promising idea to me! Maybe the [export loader](https://github.com/mdn/browser-compat-data/blob/master/index.js) could resolve the references in the source files before exposing data. I'd love to see a prototype for this.

**Comment by ExE-Boss** [comment]
We might also be able to do:
```json5
"__import": {
  "<ref_to_import>": {
    // Override stuff here when necessary.
  }
}
```

**Comment by Elchi3** [comment]
Bulk data updates through external sources and scripts are our preferred approach to better compat data right now and we're not currently considering de-duplicating version data. Therefore I'm closing this issue. Thanks for your thoughts here! Maybe we will reconsider this idea at a later stage.
