### ISSUE TITLE
How to represent units

### ISSUE THREAD

**Issue by teoli2003** [mdn/browser-compat-data#818]
Some CSS types have units, like: <frequency> are s or ms, <angle> can be deg, rad, grad, or turn…

Where to put these?

As a unit match only one type, we should put it inside the relevant \<type>

So s and ms will be sub-features of \<angle> (css.types.angle) with id css.types.angle.s and css.types.angle.ms, respectively.

As there are very few units (maybe 40) and new are added very rarely (1-2 a year I would say), I think we should explicitely list all of them.

Note that if we decide this, we should update the BCD docs before closing this.

**Comment by Elchi3** [comment]
We already started this for angle units, see this PR https://github.com/mdn/browser-compat-data/pull/518
I would do the same for the other CSS units.

**Comment by myfonj** [comment]
Watch out for (hopefully ephemeral) contextual border cases: for example at this moment Chrome supports angle units (deg/rad/grad/turn) well in transforms and such, but for some reason [not in HSL/HSLA color expressions](https://crbug.com/786139) (from CSS Color Module Level 4).  I would not be surprised if more such discrepancies emerge.

**Comment by Elchi3** [comment]
I think this question is answered. We're organizing these with their corresponding CSS types in this folder: https://github.com/mdn/browser-compat-data/tree/master/css/types

If some properties do not support certain units or types, that info will be added as notes or as sub features of the CSS property.
