### ISSUE TITLE
Check Firefox for Android compat for WebExtensions

### ISSUE THREAD

**Issue by wbamberg** [mdn/browser-compat-data#824]
Apparently I had a faulty understanding about how to figure out if an API is supported on Firefox for Android: https://github.com/mozilla/addons/issues/611#issuecomment-356025664.

We should go through and check that there aren't any similar errors in the data.

**Comment by wbamberg** [comment]
Yes, this is still an issue. To resolve it, check with the Add-ons team whether https://github.com/mozilla/addons/issues/611#issuecomment-356025664 is still correct.

* If it is:

    * go through the files linked in https://github.com/mozilla/addons/issues/611#issuecomment-356057968 and cross-check them against the current Firefox for Android BCD for WebExtensions

    * file a PR to fix any discrepancies, and ask for a review from the Add-ons team

* If it isn't (I don't expect this will happen, but it's worth checking), find out what the correct method for determining this is, and re-check using that method.

**Comment by Elchi3** [comment]
For a while now, we're using "mirror" in WebExtensions as well (Firefox Android support is derived from Firefox Desktop).
I'm closing this issue but I'd encourage the WebExtenstions community to file a new issue(s) for wrong compat data for Firefox Android.
