### ISSUE TITLE
http.headers.Feature-Policy.picture-in-picture - Supported in Chrome

### ISSUE THREAD

**Issue by nharper** [mdn/browser-compat-data#8260]
#### What information was incorrect, unhelpful, or incomplete?

The Browser compatibility table on https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy/picture-in-picture appears to be out of date. It shows that `picture-in-picture` is not supported on any browser. I think it is supported on some browsers.

#### What did you expect to see?

I expected the table to indicate support for it in some browsers, because based on my testing it appears that it is supported.

#### Did you test this? If so, how?

In Chrome 87 (on macOS), I loaded a test page structured as follows. The main frame has an iframe to a page on another origin that has a video and on user action will launch picture-in-picture. Triggering the picture-in-picture causes the video to switch to picture-in-picture mode. (So far, this is all expected behavior and doesn't have to do with the `picture-in-picture` feature policy.) Now, I modified the iframe to add `allow="picture-in-picture 'none'"` and reload the page. With that change, when I try to trigger the picture-in-picture, it doesn't switch to that mode, and I get in the console "Uncaught (in promise) DOMException: Failed to execute 'requestPictureInPicture' on 'HTMLVideoElement': Access to the feature "picture-in-picture" is disallowed by feature policy."

This appears to be evidence that Chrome 87 supports the `picture-in-picture` feature policy.

I haven't tested in other browsers (or even other versions of Chrome to determine when this support was introduced), so unfortunately I don't have advice for how the table should be updated.

<details>
<summary>MDN page report details</summary>

* Query: `http.headers.Feature-Policy.picture-in-picture`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy/picture-in-picture
* Report started: 2020-12-23T22:27:36.234Z

</details>

**Comment by ddbeck** [comment]
Hi @nharper and thanks for opening this issue. I did a little digging and it looks like you're correct.

Some additional background: according to the first commit in [Chromium bug 806249](https://bugs.chromium.org/p/chromium/issues/detail?id=806249), the feature policy was introduced rather early in the development process, before picture-in-picture was enabled by default. I think we can safely assume that the feature policy appeared in Chrome when picture-in-picture shipped. According to [this Chrome status entry](https://chromestatus.com/features/5729206566649856), that happened in Chrome 71 (this also suggests that some of our other picture-in-picture data is off, but let's set that aside for now).

I'd welcome a PR from you or another contributor that updates the `picture-in-picture` feature in [`feature-policy.json`](https://github.com/mdn/browser-compat-data/blob/master/http/headers/feature-policy.json#L1342-L1389) and sets the desktop Chrome value to 71. Thank you again!
