### ISSUE TITLE
api.RTCSessionDescriptionCallback - Not an interface

### ISSUE THREAD

**Issue by saschanaz** [mdn/browser-compat-data#8397]
#### What information was incorrect, unhelpful, or incomplete?

This is not an interface but a callback function.

#### What did you expect to see?

This shouldn't exist

#### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://developer.mozilla.org/en-US/docs/Web/API/RTCSessionDescriptionCallback

This should be merged to `api.RTCPeerConnection.createAnswer` and `api.RTCPeerConnection.createOffer`.

**Comment by jculver050** [comment]
Close

**Comment by vinyldarkscratch** [comment]
This was removed in #11057!
