### ISSUE TITLE
css.selectors.first-letter - <does not work in firefox>

### ISSUE THREAD

**Issue by Yucatanwebpages** [mdn/browser-compat-data#8398]
#### Did you test this? If so, how?

<details>
<summary>MDN page report details</summary>

* Query: `css.selectors.first-letter`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/::first-letter
* Report started: 2020-12-28T04:24:03.663Z

</details>

**Comment by vinyldarkscratch** [comment]
The example on the page works fine in the latest Firefox.  Since there's no other details, I'm closing this issue.
