### ISSUE TITLE
html.elements.data - BRAVE

### ISSUE THREAD

**Issue by thepowderriverfarrier** [mdn/browser-compat-data#8401]
This does not work in the Brave browser.

Expected to see the values.

Used the copy and pasted code.

<details>
<summary>MDN page report details</summary>

* Query: `html.elements.data`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/data
* Report started: 2020-12-28T14:50:42.785Z

</details>

**Comment by vinyldarkscratch** [comment]
This repository doesn't track data for the Brave Browser, as we have not gotten any developer/consumer interest for Brave Browser data.
