### ISSUE TITLE
Data with "This value is recognized, but has no effect." should be shown as not supported

### ISSUE THREAD

**Issue by yume-chan** [mdn/browser-compat-data#845]
Currently there are some data with `{ version_added: true, note: "This value is recognized, but has no effect." }` in [css.properties.align-content and css.properties.justify-content](https://github.com/mdn/browser-compat-data/search?utf8=%E2%9C%93&q=This+value+is+recognized%2C+but+has+no+effect.&type=)

I think it's normal that if someone sees a "Yes" on a compatibility table, they think they can use the feature. But in fact it doesn't work.

I suggest we set the `version_added` to `false` until these browsers truly support them.

One more thing, Edge also recognize some value (but has no effect), they need to be updated.

**Comment by teoli2003** [comment]
It is a bit more tricky than this as even if a feature "does nothing", the fact that it is supported may alter some side behaviour.
```
{
  justify-content: space-evenly;  
  justify-content: start;
}
```
has "No effect" on a browser that supports `start` but doesn't apply an effect.
But will behave as `space-evenly` for a browser that doesn't support `start` at all.

So we need to store the distinction.

I think using `false` in such cases is even misleading, although I agree that the current message is a bit light. Maybe we should use `partial_implementation` for these cases?
