### ISSUE TITLE
javascript.classes.static - Safari on iOS 14 is not compatible

### ISSUE THREAD

**Issue by rileyjohngibbs** [mdn/browser-compat-data#8468]
#### What information was incorrect, unhelpful, or incomplete?

The page says iOS Safari 9 supports static variables. This does not seem to be the case for iOS Safari 14.

Running iOS 14.2 on an iPhone 11 Pro Max.

#### What did you expect to see?

This should either not display compatibility or it should say that it doesn’t work above a certain version number.

#### Did you test this? If so, how?

Tested this on my device (running iOS 14.2 on an iPhone 11 Pro Max) using the demo on the page. I get the following output:

> Error: Unexpected token '='. Expected an opening '(' before a method's parameter list.

I get the same behavior on Safari on my desktop computer, with the same error in the console, from another page that uses the same syntax.

<details>
<summary>MDN page report details</summary>

* Query: `javascript.classes.static`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/static
* Report started: 2020-12-30T19:25:28.741Z

</details>

**Comment by ddbeck** [comment]
Hi @rileyjohngibbs and thanks for opening this issue. You're right that this feature is not supported in Safari (it doesn't work on desktop either). Looking at the git blame, this was migrated from historic MDN tables (without verification) during the initial seeding of BCD.

To fix this, I'd welcome a PR from you or another contributor that updates the data in the `static` feature of [`classes.json`](https://github.com/mdn/browser-compat-data/blob/a09b0824cda8a2ac0bb0e554d34ae3eb821adc37/javascript/classes.json#L736-L741) to replace `"9"` with `false` for both Safari and Safari for iOS. Thanks again!
