### ISSUE TITLE
api.ScreenOrientation.lock - doesn't work with Firefox Android 84.1.2

### ISSUE THREAD

**Issue by Neph-Oo** [mdn/browser-compat-data#8524]
#### What information was incorrect, unhelpful, or incomplete?
The lock() property of ScreenOrientation for Firefox Android doesn't seem to work, at least on old devices / OS.

#### What did you expect to see?
The locking of the screen of the device in landscape-primary orientation (or another orientation) when ``ScreenOrientation.lock("chosen-orientation")`` is called in fullscreen mode. 

#### Did you test this? If so, how?
I've tested with emscripten using different methods (deprecated methods too) and with a simple script that doesn't seem to work too :  

```
function lock (orientation) {
  if (document.documentElement.requestFullscreen) {
    document.documentElement.requestFullscreen();
  } else if (document.documentElement.mozRequestFullScreen) {
    document.documentElement.mozRequestFullScreen();
  } else if (document.documentElement.webkitRequestFullscreen) {
    document.documentElement.webkitRequestFullscreen();
  } else if (document.documentElement.msRequestFullscreen) {
    document.documentElement.msRequestFullscreen();
  }

  screen.orientation.lock(orientation);
}

function unlock () {
  screen.orientation.unlock();

  if (document.exitFullscreen) {
    document.exitFullscreen();
  } else if (document.webkitExitFullscreen) {
    document.webkitExitFullscreen();
  } else if (document.mozCancelFullScreen) {
    document.mozCancelFullScreen();
  } else if (document.msExitFullscreen) {
    document.msExitFullscreen();
  }
}
```

**Hardware and OS version :**
- Samsung Galaxy Tab (SM-T533) running Android Lolipop (Android 5.1.1)
- Samsung Galaxy S4 (GT-I9505) running CyanogenMod 12.1 (Android 5.1.1)

**Firefox version :**
- Fifrefox 84.1.2
- Firefox nightly 210103 (build \#2015785225)

I don't have any problem with chrome based browsers.

<details>
<summary>MDN page report details</summary>

* Query: `api.ScreenOrientation.lock`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/ScreenOrientation/lock
* Report started: 2021-01-04T01:20:07.765Z

</details>

**Comment by saschanaz** [comment]
Tracking bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1681572

**Comment by ddbeck** [comment]
Thanks for reporting this issue, @Neph-Oo. The bug that @saschanaz linked to seems to confirm this. One thing is a bit unclear to me, however, and that's whether this was a regression or if the feature never did the expected thing. The answer to that question would tell us whether we need to structure this as multiple support statements, or if we need one note and one `partial_implementation` flag.

**Comment by hamishwillee** [comment]
This previously worked (apparently) but according to https://bugzilla.mozilla.org/show_bug.cgi?id=1697647#c16 it was probably broken on Firefox 69 or so as part of the Fenix rewrite or as part of the Fennec code removal project (bug 1582218). However there is no easy way to tell - you'd have to bisect using the APKs and also the test attachment: https://bugzilla.mozilla.org/show_bug.cgi?id=1697647

Further, this was supposed to be fixed behind preference in FF97 in https://bugzilla.mozilla.org/show_bug.cgi?id=1697647#c16 . However the above test case does not work on FF97 on android for me, and of course you can only set the preference on nightly. This can't be tested on desktop.

@ddbeck  How do we proceed - I can't even work out which version I'd test corresponding to FF69 in https://github.com/mozilla-mobile/fenix/releases?page=27

**Comment by ddbeck** [comment]
@hamishwillee I'd proceed with 69. It seems likely, we have a citation for it (i.e., we didn't independently guess), and we have a paper trail to help folks refine this data in the future (if needed). I'd go ahead with these support statements:

1. Added 69, partial (since the API exists), with a note describing the current misbehavior.
2. Added 43, removed 69 (representing for the former, working behavior).
