### ISSUE TITLE
css.properties.clip-path - path() is supported in Safari and Chrome 88+

### ISSUE THREAD

**Issue by upsuper** [mdn/browser-compat-data#8661]
#### What information was incorrect, unhelpful, or incomplete?

The table says `clip-path: path()` is not supported in Safari and Chrome.

#### What did you expect to see?

It's supported in Safari for a while, and Chrome also starts shipping it in 88.

#### Did you test this? If so, how?

I do. Actually our product relies on that on Safari.

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.clip-path`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/clip-path
* Report started: 2021-01-05T23:44:04.749Z

</details>

**Comment by myakura** [comment]
> It's supported in Safari for a while

Support for the `path()` functional notation was added to the `-webkit-clip-path` property in Occtober 2015.
https://github.com/WebKit/WebKit/commit/45619f56d800a95b67320b3efc74a51ee00ebda3
So I believe it was first shipped in Safari 10 (released in September 2016).

`-webkit-clip-path` was unprefixed in October 2019.
https://github.com/WebKit/WebKit/commit/b27057cf7aa96764b2daeafff162ec581746111f
Although the tech notes didn't cover it, the change should be part of Safari TP 97 (per its revision range).
https://webkit.org/blog/9672/release-notes-for-safari-technology-preview-97/

And changes made in STP 97 made their release in Safari 13.1.
https://webkit.org/blog/10247/new-webkit-features-in-safari-13-1/
