### ISSUE TITLE
webextensions.api.i18n.getUILanguage - typo mistake

### ISSUE THREAD

**Issue by ahmetlii** [mdn/browser-compat-data#8673]
#### What information was incorrect, unhelpful, or incomplete?
"seperate" should be "separate". Apparently misspelled.

#### What did you expect to see?
Seeing "separate" rather than "seperate".

#### Did you test this? If so, how?
There's nothing to test obviously. Just a tiny typo mistake.

<details>
<summary>MDN page report details</summary>

* Query: `webextensions.api.i18n.getUILanguage`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/I18n/getUILanguage
* Report started: 2021-01-06T18:57:30.101Z

</details>

**Comment by ddbeck** [comment]
@ahmetlii Thanks for reporting this problem!

To add a little detail here, it looks like the typo is in a note for the Firefox data in [`i18n.json`](https://github.com/mdn/browser-compat-data/blob/master/webextensions/api/i18n.json#L122). I'd welcome a PR from you (or another contributor) correcting the typo. Thanks again!
