### ISSUE TITLE
javascript.builtins.BigInt - Cut out an example with finding prime numbers

### ISSUE THREAD

**Issue by zazaulola** [mdn/browser-compat-data#8674]
#### What information was incorrect, unhelpful, or incomplete?
Last example with prime numbers.

#### What did you expect to see?
This method is optimal for find prime numbers: https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes

#### Did you test this? If so, how?
The example you gave is a very bad practice.

<details>
<summary>MDN page report details</summary>

* Query: `javascript.builtins.BigInt`
* MDN URL: https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/BigInt
* Report started: 2021-01-06T22:38:32.641Z

</details>

**Comment by ddbeck** [comment]
Hi @zazaulola. This repository for data which is used to generate the compatibility tables on MDN, not the general page content. For content changes, please check out https://github.com/mdn/content/. Thank you!
