### ISSUE TITLE
counter() and counters() - Broken MDN links

### ISSUE THREAD

**Issue by joshsalverda** [mdn/browser-compat-data#8681]
#### What information was incorrect, unhelpful, or incomplete?

Links to MDN for counter() and counters() aren't being parsed correctly:

<img width="301" alt="Screen Shot 2021-01-07 at 2 56 43 PM" src="https://user-images.githubusercontent.com/3029989/103938682-a2e59b00-50f8-11eb-8b4d-6c6c850b81ab.png">

The last `)` gets placed outside of the anchor link.

The links are correct in the source json:

https://github.com/mdn/browser-compat-data/blob/master/css/types/counter.json
and
https://github.com/mdn/browser-compat-data/blob/master/css/types/counters.json

so it must be something with whatever is actually rendering it maybe?

#### What did you expect to see?

Not broken links :D

#### Did you test this? If so, how?

N/A

#### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

N/A

**Comment by ddbeck** [comment]
@joshsalverda Where was this screenshot taken? A link to the page(s) where the links are broken is essential here. Thank you!

**Comment by joshsalverda** [comment]
The screenshot was from caniuse.com, and I'm just realizing now that the link to GitHub I followed from there was to the compatibility data repo instead of the actual web site source 😅 

Sorry! I'll see if I can find the correct repo to post this to instead.

**Comment by ddbeck** [comment]
@joshsalverda No problem! I thought that might be the case—these things happen. 😄
