### ISSUE TITLE
Disallow version_added and version_removed set to the same range?

### ISSUE THREAD

**Issue by foolip** [mdn/browser-compat-data#8684]
This situation came up in https://github.com/mdn/browser-compat-data/pull/8301#discussion_r548840112, with additions like this:

```json
{
  "version_added": "≤37",
  "version_removed": "≤37",
  "prefix": "webkit"
}
```

What these entries communicate is that there is at least one version ≤37 where the feature was supported, and that isn't supported after 37.

Quoting some key bits of discussion:

@ddbeck:

> Two version ranges feels like a `null` in disguise. My take: omitting this support statement is in the spirit of the irrelevant feature/flag removal guidelines and we should do that.

@foolip:

> I don't think this is analogous to irrelevant flags, however, prefixed APIs are just support with a different name, and I think we should accept the data and reject its removal where we can know what the real ranges are.

@ddbeck:

> Also, to clarify something I said before, I realize this is not analogous to irrelevant flags, but I do think this particular case is analogous to irrelevant features. Suppose that, in an alternate universe, BCD has distinct features for `api.Blob.slice` and `api.Blob.webkitslice` (instead of prefixes). The `webkitslice` feature would be eligible for removal, since it went away over 2 years go. That was the point I was trying to make with dropping the prefixed statements here.

We have cases like this in BCD now, for example for `MutationObserver`:

https://github.com/mdn/browser-compat-data/blob/50a17da8e7568cdd6f78eace6f9250c1a7211810/api/MutationObserver.json#L75-L85

Should we disallow this and clean up the existing cases?

**Comment by ddbeck** [comment]
Thanks for writing this up, @foolip. Seeing this laid out, I think I conflated a few things. A bunch of more specific, delineated thoughts:

1. I think my impression that a pair of ranged values is a `null` in disguise was misguided. It's more like a `true` in disguise.

   For example, for Edge, this support statement:
 
   ```json
   {
     "version_added": "≤18",
     "version_removed": "≤79",
   }
   ```

   is equivalent to:
 
   ```json
   {
     "version_added": true,
     "version_removed": "≤79",
   }
   ```
 
   That's not as bad as a `null`, but it's still a problem, for two reasons:

   - The first support statement appears to have real values, but it doesn't. Seems like cheating.
   - If it's cheating, then I wouldn't want to approve a PR containing the cheat, but we don't actually say anywhere that this is forbidden. We should fix that, at least.

2. The point about prefixes being irrelevant features is probably more restrictive than I first thought. You probably wouldn't want to remove something like:

   ```json
   {
     "version_added": "≤37",
     "version_removed": "≤37",
     "prefix": "webkit"
   }
   ```

   unless _every_ browser has removed the `webkit` prefix (like you would with an irrelevant feature). Maybe that's not so helpful after all.

3. The good news: except for Edge, all of our currently-accepted ranged values are for very old versions. I think a bias toward dropping such data (e.g., replacing with `"version_added": false`) is unlikely to produce suprising results.

It would be nice to know how many cases we have where a ranged `version_added` is paired with a ranged `version_removed`, and how many of those cases are for prefixes. That might give us a clue as to how broad a policy we need here.

**Comment by jculver050** [comment]
Close

**Comment by foolip** [comment]
Fixed by https://github.com/mdn/browser-compat-data/pull/9610.
