### ISSUE TITLE
api.MediaDevices.devicechange_event - Safari Support

### ISSUE THREAD

**Issue by Lytigas** [mdn/browser-compat-data#8688]
Safari Version 13.1.2 (15609.3.5.1.3)

#### What information was incorrect, unhelpful, or incomplete?

Safari support for the `devicechange` event.

#### What did you expect to see?

Safari listed as supported in the table.

#### Did you test this? If so, how?

1. Open a webpage using device permissions.
2. Attempt `navigator.mediaDevices.addEventListener('devicechange', console.log)`
3. Attach a new device, and observe that the event fires.

<details>
<summary>MDN page report details</summary>

* Query: `api.MediaDevices.devicechange_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/devicechange_event
* Report started: 2021-01-08T20:24:06.942Z

</details>

**Comment by ddbeck** [comment]
Thanks for reporting this, @Lytigas. I did a bit of digging and confirmed that this is right; the feature was introduced in Safari 11. This aligns with the data we have for `ondevicechange`. To correct this, I invite you (or another contributor) to open a pull request to modify the `devicechange_event` feature in [`MediaDevices.json`](https://github.com/mdn/browser-compat-data/blob/d50feadacff082c5fb240367170082c3e5a1b800/api/MediaDevices.json#L50-L98). Thanks again!
