### ISSUE TITLE
http.status - add status 505-511

### ISSUE THREAD

**Issue by arihant2math** [mdn/browser-compat-data#8692]
The compatibility data after errors 504, 425, 308, 226 are not shown, could this be fixed?

<details>
<summary>MDN page report details</summary>

* Query: `http.status`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
* Report started: 2021-01-09T23:27:28.364Z

</details>

**Comment by vinyldarkscratch** [comment]
Could you clarify on what HTTP status codes you're looking to have added?

**Comment by arihant2math** [comment]
I am looking for 505-511.

**Comment by ddbeck** [comment]
Thanks for reporting this, @arihant2math. I think there's some broader questions about filling HTTP status code gaps in BCD, so I opened #8936 to handle this systematically. I'd consider this blocked until we have an answer on the questions raised there, so I'm going to mark this issue as not-ready. Thanks again for the report!

**Comment by jculver050** [comment]
Close

**Comment by Elchi3** [comment]
Closing as duplicate of https://github.com/mdn/browser-compat-data/issues/8936
