### ISSUE TITLE
api.MediaRecorder.ondataavailable - available on ios since 14.3

### ISSUE THREAD

**Issue by possan** [mdn/browser-compat-data#8710]
#### What information was incorrect, unhelpful, or incomplete?
It says the feature is unavailable on iOS Safari, which isn't correct anymore, finally.

#### What did you expect to see?
Available since 14.3

#### Did you test this? If so, how?
Tested on device with os version 14.3 where MediaRecorder is now available.
Reference: https://webkit.org/blog/11353/mediarecorder-api/

<details>
<summary>MDN page report details</summary>

* Query: `api.MediaRecorder.ondataavailable`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder/ondataavailable
* Report started: 2021-01-12T10:10:54.016Z

</details>

**Comment by ddbeck** [comment]
It looks like the `MediaRecorder`API generally has appeared on iOS 14.3. I'd welcome a PR updating this data, though this is blocked by a lack of data regarding Safari on iOS 14.3 in [`safari_ios.js`](https://github.com/mdn/browser-compat-data/blob/master/browsers/safari_ios.json). That will need to be updated before data on this feature could be recorded.

**Comment by jculver050** [comment]
Close

**Comment by vinyldarkscratch** [comment]
Looks like this was resolved in #8838!
