### ISSUE TITLE
api.Animation.finished - It worked on my edge browser even though it says its incompatible

### ISSUE THREAD

**Issue by Kostas-Xafis** [mdn/browser-compat-data#8728]
#### What information was incorrect, unhelpful, or incomplete?
The compatibility of the Animation class need an update i guess?
#### What did you expect to see?
I expected for animation.fineshed to not work but it did
#### Did you test this? If so, how?
I tested it on my some custom animations and it worked on my edge browser (Version 87.0.664.75)
You might want to check what is compatible and what not.

<details>
<summary>MDN page report details</summary>

* Query: `api.Animation.finished`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Animation/finished
* Report started: 2021-01-12T22:14:49.279Z

</details>

**Comment by ddbeck** [comment]
Thanks for reporting this issue, @Kostas-Xafis. It looks like this feature appeared in [Chrome (and Edge, etc.) 84](https://chromestatus.com/feature/5126405660606464). I'd welcome a PR from you (or another contributor) that sets the corresponding value in [`Animation.json`](https://github.com/mdn/browser-compat-data/blob/master/api/Animation.json#L520-L591). We could even work with you to mirror that data to the other Chromium-derived browsers.

@foolip I dug this up by finding that the attribute showed up in the IDL with `RuntimeEnabled=WebAnimationsAPI` [circa 2015](https://bugs.chromium.org/p/chromium/issues/detail?id=483272) and then figuring out that `WebAnimationsAPI` was turned on by default in [version 84](https://bugs.chromium.org/p/chromium/issues/detail?id=978551), but I didn't look closely at the implementation. Is that a sensible approach for figuring out when something like this shipped? Either way, it looks like a lot changed with regards to animations in 84; it might be a rich target for collector work.

**Comment by jculver050** [comment]
Close

**Comment by vinyldarkscratch** [comment]
This was resolved in #9274!
