### ISSUE TITLE
api.ResizeObserverEntry.borderBoxSize - Firefox 82 does not return an array

### ISSUE THREAD

**Issue by vmizg** [mdn/browser-compat-data#8730]
#### What information was incorrect, unhelpful, or incomplete?
The `borderBoxSize` as well as `contentBoxSize` both come as objects instead of arrays in Firefox. Specification defines that these properties should contain "an array containing objects".

#### What did you expect to see?
Expected as per specification (Chrome Version 87.0.4280.141 (Official Build) (64-bit)):
![image](https://user-images.githubusercontent.com/9007308/104406155-98fce580-5599-11eb-865c-c86cd6bbdca0.png)

Actual (Firefox 84.0.2 (64-bit)):
![image](https://user-images.githubusercontent.com/9007308/104406062-618e3900-5599-11eb-9cea-403e69387475.png)

#### Did you test this? If so, how?
Tested by accessing both `borderBoxSize.blockSize` as well as `borderBoxSize[0].blockSize`. The latter fails with TypeError in Firefox:
![image](https://user-images.githubusercontent.com/9007308/104406368-1b85a500-559a-11eb-8458-ca0a960a366b.png)

I have solved this temporarily by giving it a fallback:
![image](https://user-images.githubusercontent.com/9007308/104406314-fe50d680-5599-11eb-925e-425eb06ed21a.png)

<details>
<summary>MDN page report details</summary>

* Query: `api.ResizeObserverEntry.borderBoxSize`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserverEntry/borderBoxSize
* Report started: 2021-01-13T04:08:46.172Z

</details>

**Comment by ddbeck** [comment]
Thanks for reporting this, @vmizg, and providing very clear evidence of the deviation from the spec and other browsers.

I'd welcome a PR (from you or another contributor) to add a note to the Firefox entries in [`ResizeObserverEntry.json`](https://github.com/mdn/browser-compat-data/blob/master/api/ResizeObserverEntry.json#L50-L145), for features `contentBoxSize` and `borderBoxSize` (something along the lines of `"note": "The property type is a <code>ResizeObserverSize</code> object, not an array of <code>ResizeObserverSize</code> objects."` or whatever makes sense). We might also want to set `"partial_implementation": true` for those as well.

**Comment by queengooborg** [comment]
It looks like this was partially fixed by #10939, and I'm opening a PR to take care of the other half now!
