### ISSUE TITLE
Sort out data for autofocus

### ISSUE THREAD

**Issue by foolip** [mdn/browser-compat-data#8745]
This is very similar to https://github.com/mdn/browser-compat-data/issues/7519, but need not be solved together with that issue.

Per [spec](https://html.spec.whatwg.org/#htmlorsvgelement), there should be `autofocus` members on `HTMLElement` and `SVGElement`. BCD instead has it on `HTMLButtonElement`, `HTMLInputElement` and `HTMLSelectElement`. Probably it was on those interfaces in implementations originally as well, but has migrated to `HTMLElement` at least in Chromium.

This will need careful investigation of when `autofocus` was supported on which types of HTML elements, and potentially notes.

https://github.com/mdn/browser-compat-data/pull/8112 was a PR to add api.HTMLElement.autofocus, but it should be done together with the removal of the others.

**Comment by foolip** [comment]
In https://github.com/mdn/browser-compat-data/pull/8112/files#r548334335 @vinyldarkscratch found that the move happened in [Chrome 79](https://storage.googleapis.com/chromium-find-releases-static/0fb.html#0fbf9bdd80bfef802dcc57ab0c295a95a3fa39b3).

**Comment by foolip** [comment]
I've just discovered that the attributes is additionally on `HTMLTextAreaElement` in Firefox and Safari, and one `SVGGraphicsElement` in Firefox.

**Comment by jculver050** [comment]
Close

**Comment by foolip** [comment]
https://github.com/mdn/browser-compat-data/pull/11680 sorted out the mess. I'm not sure the "Supported for <code>HTMLButtonElement</code>, <code>HTMLInputElement</code>, <code>HTMLSelectElement</code>, and <code>HTMLTextAreaElement</code>" notes are 100% accurate going all the way back to the first versions claimed to have partial support, but it's more than good enough.
