### ISSUE TITLE
api.HTMLElement.pointerup_event - Safari is compatible with pointer events on ios safari

### ISSUE THREAD

**Issue by mherchel** [mdn/browser-compat-data#8747]
#### What information was incorrect, unhelpful, or incomplete?
The page states that IOS Safari does not support pointer events
#### Did you test this? If so, how?
Yes. I tested on an ipad running IOS 13.7.
See https://webkit.org/blog/10247/new-webkit-features-in-safari-13-1/

<details>
<summary>MDN page report details</summary>

* Query: `api.HTMLElement.pointerup_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/pointerup_event
* Report started: 2021-01-13T22:04:16.320Z

</details>

**Comment by ddbeck** [comment]
Thanks for reporting this, @mherchel. Since this relates to #8709, which has already had some activity, I'm marking this issue as a duplicate and closing it. If you'd like to contribute more details or participate in fixing this data, please check out #8709. Thank you again!
