### ISSUE TITLE
Audit WebGL platform-dependent extensions and add notes

### ISSUE THREAD

**Issue by foolip** [mdn/browser-compat-data#8750]
Support for WebGL extensions often depends on the device/hardware/OS support, with `WEBGL_draw_buffers ` as an example explained in https://github.com/mdn/browser-compat-data/pull/8271#issuecomment-759934133.

I strongly suspect that our data for WebGL extensions isn't very accurate, because testing for support doesn't work if one is testing on a device that doesn't have the right underlying support. As a result we might have changed the support back and forth over time based on such testing.

If we want this data to be accurate I think we'd need to:
- have guidelines for when to claim support for something that is very rarely supported in practice
- audit the data we have by testing on a wider range of devices and inspecting browser source history
- add detailed notes about what is required for support and what to expect in the typical case

cc @vinyldarkscratch

**Comment by queengooborg** [comment]
I think that we've narrowed these WebGL extensions down pretty well with the collector results, so I'm going to go ahead and close this.
