### ISSUE TITLE
Incomplete information for Accept-CH page

### ISSUE THREAD

**Issue by ayumi-cloud** [mdn/browser-compat-data#8767]
Related to this location: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-CH

This page is missing a huge amount of data, it seems to only cover: 

- DPR
- Viewport Width
- Width

Yet Client Hints cover a lot more, such as:

- Device Memory
- Rtt
- Downlink
- Ect
- Save-Data
etc.

I would like to see the MDN team update the information on the page to add these extra Client Hints and also update the Browser compatibility table.

Thanks.

**Comment by vinyldarkscratch** [comment]
Sounds like this is an issue more suitable for https://github.com/mdn/content as it's primarily talking about page content.  Can you open up an issue there?  (We could probably keep this one open since it invokes BCD as well.)

**Comment by ayumi-cloud** [comment]
Sure added it here: https://github.com/mdn/content/issues/1408
