### ISSUE TITLE
api.Clipboard - Compatibility table is bullshit

### ISSUE THREAD

**Issue by teo1978** [mdn/browser-compat-data#8779]
Chrome 87 on Linux 

#### What information was incorrect, unhelpful, or incomplete?

https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API
https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/writeText

Either the compatibility table is wrong, or the way you are supposed to access the clipboard is wrong.

The examples use
```
navigator.clipboard
```

The compatibility table says it works in Chrome, particularly `navigator.clipboard.writeText`.

That's bullshit. In Chrome, `navigator.clipboard` is undefined.

#### What did you expect to see?

accurate information 

#### Did you test this? If so, how?

```
navigator.clipboard.writeText("ksjdbksdb");
VM21966:1 Uncaught TypeError: Cannot read property 'writeText' of undefined
    at <anonymous>:1:21
```

<details>
<summary>MDN page report details</summary>

* Query: `api.Clipboard`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API
* Report started: 2021-01-17T17:17:25.728Z

</details>

**Comment by vinyldarkscratch** [comment]
Looking into this, it's possible that you were trying to use the Clipboard API on an insecure context (in other words, `http://` not `https://`).  I did some testing and confirmed that `navigator.clipboard` is not defined on insecure contexts, but is defined as a `Clipboard` object when checking on a secure context (or `localhost`; Chrome treats `localhost` as secure for convenience during development).

(By the way, no need to use colorful language when creating an issue.  🙂 )
