### ISSUE TITLE
api.HTMLElement.pointerdown_event - Safari compat

### ISSUE THREAD

**Issue by fonsp** [mdn/browser-compat-data#8788]
#### What information was incorrect, unhelpful, or incomplete?
The table shows that Safari does not support pointer events, but it does, since version 13:
https://caniuse.com/pointer

#### Did you test this? If so, how?
Yes, on latest safari, there is a demo here:
https://javascript.info/pointer-events

<details>
<summary>MDN page report details</summary>

* Query: `api.HTMLElement.pointerdown_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/pointerdown_event
* Report started: 2021-01-18T13:08:25.124Z

</details>

**Comment by ddbeck** [comment]
Thanks for reporting this, @fonsp. Since #8709 is already open, I'm marking this issue as a duplicate and closing it. If you'd like to contribute more details or participate in fixing this data, please check out #8709. Thank you again!
