### ISSUE TITLE
api.TrackEvent.track - Supported on Firefox

### ISSUE THREAD

**Issue by saschanaz** [mdn/browser-compat-data#8791]
#### What information was incorrect, unhelpful, or incomplete?

It says Firefox `.track` support is unknown

#### What did you expect to see?

It should be marked as supported

#### Did you test this? If so, how?

`TrackEvent.prototype.track`

#### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://developer.mozilla.org/en-US/docs/Web/API/TrackEvent#browser_compatibility

**Comment by ddbeck** [comment]
Looks like it appeared when `TrackEvent` appeared: https://bugs.webkit.org/show_bug.cgi?id=71178 and https://trac.webkit.org/changeset/99261/webkit. A cursory test (e.g., `"track" in TrackEvent.prototype`) points toward Safari 10 as a likely version added.

**Comment by vinyldarkscratch** [comment]
Resolved by #10875!
