### ISSUE TITLE
css.properties.aspect-ratio - full support in Chrome 88 

### ISSUE THREAD

**Issue by Benimation** [mdn/browser-compat-data#8797]
#### What information was incorrect, unhelpful, or incomplete?
Currently it only shows that aspect-ratio is supported behind a flag in Chrome 84, but not that it is fully supported (without a flag) in Chrome 88.

#### What did you expect to see?
Future versions with known support. Sites like caniuse.com use this data, but now incorrectly show that it's still behind a flag in Chrome 88.

#### Did you test this? If so, how?
Yes, it works in the current Chrome Canary version.

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.aspect-ratio`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/aspect-ratio
* Report started: 2021-01-19T19:11:54.319Z

</details>

**Comment by janosh** [comment]
It's also available in [Safari Technology Preview 118](https://webkit.org/blog/11439/release-notes-for-safari-technology-preview-118).

**Comment by ddbeck** [comment]
Thanks for reporting this, @Benimation! It was fixed by #8802.

**Comment by ddbeck** [comment]
@janosh:

> It's also available in [Safari Technology Preview 118](https://webkit.org/blog/11439/release-notes-for-safari-technology-preview-118).

#8847 is now open for the Safari data (it's a bit complicated, details coming soon).
