### ISSUE TITLE
api.Blob.arrayBuffer - Safari 14 compatibility

### ISSUE THREAD

**Issue by poicooler** [mdn/browser-compat-data#8798]
#### What information was incorrect, unhelpful, or incomplete?
It is said that it is not supported in Safari.

#### What did you expect to see?
Blob.arraybuffer works on Safari 14

#### Did you test this? If so, how?
Yes, imported a file and `file.arrayBuffer()` works

<details>
<summary>MDN page report details</summary>

* Query: `api.Blob.arrayBuffer`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Blob/arrayBuffer
* Report started: 2021-01-19T19:36:43.800Z

</details>

**Comment by ddbeck** [comment]
Hi @poicooler, and thanks for reporting this issue.

A quick test shows that `Blob.arrayBuffer()` was first exposed in Safari 14 (it's not available in Safari 13). It's probably safe to assume that this is true in Safari for iOS as well.

I'd welcome a PR from you (or another contributor) to update [`Blob.json`](https://github.com/mdn/browser-compat-data/blob/master/api/Blob.json#L101-L149) to show that the `arrayBuffer` feature was added in version 14.

Thank you!

**Comment by foolip** [comment]
Fixed by @joneskj55 in https://github.com/mdn/browser-compat-data/pull/8996. \o/

**Comment by pastelmind** [comment]
It seems iOS Safari 14 does not support `blob.arrayBuffer`.

- Tested on iPhone 12 mini (iOS 14.1)
- My user agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 14_1 like Mac OS X) AppleWebkit/605.1.15 (KHTML, like Gecko) Version/14.0 Mobile/15E148 Safari/604.1`
- Test link: https://runjs.co/s/ZWfL02tRY

**Comment by foolip** [comment]
@pastelmind can you file a new issue about this? I just tested https://runjs.co/s/ZWfL02tRY and https://mdn-bcd-collector.appspot.com/tests/api/Blob/arrayBuffer in Safari iOS 14.5 and it is supported there. It's possible it wasn't in Safari 14, but it sounds like I tested just that in https://github.com/mdn/browser-compat-data/pull/8996#pullrequestreview-584566856.

**Comment by foolip** [comment]
I also tested https://mdn-bcd-collector.appspot.com/tests/api/Blob/arrayBuffer on iOS 14 on BrowserStack, and it's also supported.

**Comment by pastelmind** [comment]
I ran some tests on several iPhones and iPads; please make of it what you will.

- I checked for existence of the following methods on `Blob.prototype`: `arrayBuffer()`, `stream()`, `text()`.
- For iOS/iPadOS version numbers, I went to Settings > General > About.
    - Note: mdn-bcd-collector seems to report iOS version numbers differently, e.g. it reports iOS version 14.5 for iPhone 12 Pro below.
- I also checked the values of `window.navigator.userAgent`.

| Device | iOS Version | `arrayBuffer()` | `stream()` | `text()` | User Agent string |
|----|:--:|:--:|:--:|:--:|----|
| iPhone 12 mini | 14.1 | ❌ | ❌ | ❌ | `Mozilla/5.0 (iPhone; CPU iPhone OS 14_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Mobile/15E148 Safari/604.1` |
| iPhone 12 Pro | 14.7.1 | 🟢 | 🟢 | 🟢 | `Mozilla/5.0 (iPhone; CPU iPhone OS 14_7_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Mobile/15E148 Safari/604.1` |
| iPhone 8 Plus | 15.2 | 🟢 | 🟢 | 🟢 | `Mozilla/5.0 (iPhone; CPU iPhone OS 15_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Mobile/15E148 Safari/604.1` |
| iPad mini 2 | 9.3.5 | ❌ | ❌ | ❌ | `Mozilla/5.0 (iPad; CPU OS 9_3_5 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13G36 Safari/601.1` |
| iPad 8 | 14.4.2 | 🟢 | ❌ | 🟢 | `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15` |
| iPad mini 4 | 15.7.8 | 🟢 | 🟢 | 🟢 | `Mozilla/5.0 (iPad; CPU OS 15_7_8 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6.6 Mobile/15E148 Safari/604.1` |

**Comment by foolip** [comment]
Thank you @pastelmind for that detailed testing!

I took a look at WebKit source, and it appears that this was shipped in iOS 14.2:

https://github.com/WebKit/WebKit/blob/releases/Apple/Safari-14-iOS-14.1/Source/WebCore/fileapi/Blob.idl (not present)
https://github.com/WebKit/WebKit/blob/releases/Apple/Safari-14.0.1-iOS-14.2/Source/WebCore/fileapi/Blob.idl (present)

It was also in Safari 14.0.1 on macOS:
https://github.com/WebKit/WebKit/blob/releases/Apple/Safari-14.0.1-macOS-11.0/Source/WebCore/fileapi/Blob.idl

So most likely, I was testing Safari 14.0.1 or later in https://github.com/mdn/browser-compat-data/pull/8996#pullrequestreview-584566856.

If we had it in BCD, the correct iOS version to record would be 14.2. I'm not too sure what we should do given that we don't have it in BCD. Would you mind filing a new issue about this?

**Comment by foolip** [comment]
Actually, I've sent https://github.com/mdn/browser-compat-data/pull/22682, no need to file an issue.
