### ISSUE TITLE
`hyphens: auto` is now supported in Chrome 88 on desktop platforms

### ISSUE THREAD

**Issue by jakub-g** [mdn/browser-compat-data#8809]
Chrome 88 shipped `hyphens: auto` on additional operating systems

https://developer.mozilla.org/en-US/docs/Web/CSS/hyphens
https://www.chromestatus.com/feature/5672891947417600

**Comment by ddbeck** [comment]
Thanks for reporting this, @jakub-g.

The data in [`hyphens.json`](https://github.com/mdn/browser-compat-data/blob/master/css/properties/hyphens.json) is a bit messy. Here's what needs to happen to fix this:

- Create a new subfeature in `hypens.json` for each of the named values for `hyphens`: `auto`, `none`, and `manual`
- Restructure the notes on the main feature into data for the new values subfeatures
- Set the `auto` value for Chrome's `"version_added"` to 88, as indicated by the linked Chrome status entry

I'd welcome one or more PRs carrying out this work, from you or another contributor. Let me know if there are any questions.

**Comment by dimovpetar** [comment]
Hello @jakub-g ,

Chrome 92.0.4515.131 (Official Build) (64-bit) still doesn't support many languages like Lithuanian, Russian, Norwegian and many more. Speaking about Windows. Do you have any idea where to check which languages are supported?
