### ISSUE TITLE
api.MediaDevices.getDisplayMedia - Browser compatibility is not up to date

### ISSUE THREAD

**Issue by jhorbowicz** [mdn/browser-compat-data#8821]
#### What information was incorrect, unhelpful, or incomplete?
In Browser compatibility section, there are annotations for mobile Firefox and Android Web View, indicating, that the `getDisplayMedia` API is exposed but always returns NotAllowedError. I checked that in codesandbox linked below, and also done some research. There were some [bugs in implementation in chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=1038244#c2) (link for chromium bug report) as well as in [Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1624181) (link for bugzilla). Both bugs were fixed, and I tested that on WebView and Mobile Firefox `getDisplayMedia` in not a function. Although this bug is still present in mobile Chrome.

#### What did you expect to see?
Remove annotation regarding `getDisplayMedia` API for WebView and mobile Firefox, but create one for mobile Chrome.
#### Did you test this? If so, how?
I prepared simple site on codesandbox, that checks, if there is `navigator.MediaDevices.getDisplayMedia` of type "function" -> https://codesandbox.io/s/is-getdisplaymedia-enabled-my091 and checked it in deifferent browsers and devices.

<details>
<summary>MDN page report details</summary>

* Query: `api.MediaDevices.getDisplayMedia`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getDisplayMedia
* Report started: 2021-01-19T07:54:07.799Z

</details>

**Comment by ddbeck** [comment]
Thanks for reporting this, @jhorbowicz!

Looking over the bugs, it does look like we need to update the data for [`getDisplayMedia` in `MediaDevices.json`](https://github.com/mdn/browser-compat-data/blob/master/api/MediaDevices.json#L173-L263). Specifically:

- `chrome_android`:
   - from version 88, no support
   - from version 72 to 88, partial support (with a note saying that the method always rejects)
- `firefox_android`:
  - from version 79, no support
  - from version 66 to 79, partial support (with a note saying that the method always rejects)
- `webview_android`:
   - from version 88, no support
   - from version 72 to 88, partial support (with a note saying that the method always rejects)

I'd welcome a PR from you (or another contributor), to make these changes happen. Thanks again!

**Comment by jhorbowicz** [comment]
@ddbeck Thanks for the response.

I'll try to prepare a Pull Request today or during the weekend :)

Best Regards!
