### ISSUE TITLE
api.URLSearchParams - URLSearchParams.prototype.toString doesn't work as expected until Firefox 54

### ISSUE THREAD

**Issue by romainmenke** [mdn/browser-compat-data#8829]
#### What information was incorrect, unhelpful, or incomplete?

`URLSearchParams.prototype.toString` is stated as supported (without notice)  from Firefox 29.

#### What did you expect to see?

Working `URLSearchParams.prototype.toString` from Firefox 29.

In practice you get `[Object Object]` URL encoded.

This works correctly from Firefox 54

#### Did you test this? If so, how?

Ran this code in all browsers available in Browserstack :

```js
var params = new URLSearchParams({ key: "730d67" });
params.toString() === "key=730d67";
```

also see : https://github.com/Financial-Times/polyfill-library/pull/983

<details>
<summary>MDN page report details</summary>

* Query: `api.URLSearchParams`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams
* Report started: 2021-01-22T18:46:34.190Z

</details>

**Comment by ddbeck** [comment]
Hi @romainmenke and thanks for reporting this issue.

It's possible this might actually be a problem with the `URLSearchParams()` constructor (`api.URLSearchParams.URLSearchParams`), not `toString` per se. It looks like Firefox didn't accept records as the `init` argument until Firefox 54: https://bugzilla.mozilla.org/show_bug.cgi?id=1331580.

For example, compare the output from this in Firefox 53 and 54:

```js
var z = new URLSearchParams({'abc': 123});
console.log(z.get('abc')); // null, then 123
z.get('abc') === "123"; // false, then true
```

I'd suggest instead that we correct this by adding a subfeature to `api.URLSearchParams.URLSearchParams` (like `USVString_sequence`) in [`URLSearchParams.json`](https://github.com/mdn/browser-compat-data/blob/5d2366a7237c9fbb63ad38bd69e7a0c534d29f3c/api/URLSearchParams.json#L61) that represents support for record objects as `init`. I'd welcome a PR (from you or another contributor) seeding this data with Firefox versions alone, though experimentation in other browsers would also be welcome.

Thanks again!

**Comment by romainmenke** [comment]
@ddbeck I agree. Wrote more tests to get a better view of browser support for records as init arguments.
Will get back to you when I have some results.

**Comment by romainmenke** [comment]
Still need to run more tests but at first glance it seems these all landed at different times :
- `new URLSearchParams( "foo=bar" ); // firefox 29`
- `new URLSearchParams( [["foo", "bar"]] ); firefox 53`
- `new URLSearchParams( { "foo": "bar" } ); // firefox 54`

**Comment by romainmenke** [comment]
Results :

| `constructor` | chrome | edge | firefox | ie | ios | opera (presto only) | safari |
| --- | --- | --- | --- | --- | --- | --- | --- |
| no args | 49 | 17 | 29 | false | 10* | false | 10.1 |
| string | 49 | 17 | 29 | false | 10* | false | 10.1 |
| sequence | 58 | 17 | 53 | false | 11 | false | 11.1 |
| record | 61 | 17 | 54 | false | 11 | false | 11.1 |

* ios tests only go back to 10

---------

| `toString` | chrome | edge | firefox | ie | ios | opera (presto only) | safari |
| --- | --- | --- | --- | --- | --- | --- | --- |
|  | 49 | 17 | 29 | false | 10* | false | 10.1 |

----------

search for `URLSearchParams` to see full test scores : https://mrhenry.github.io/web-tests/

test sources files are located here : https://github.com/mrhenry/web-tests/tree/main/specifications/whatwg/url
The `test.pure.js` file in each folder is the relevant one.

**Comment by ddbeck** [comment]
@romainmenke I really appreciate the effort you've put into this. It's excellent and detailed!

To fill in one blank here: we can probably mirror from desktop Safari to iOS using the data in `/browsers`, so it's probably not strictly necessary to test on older versions. And it looks like we can mirror Chrome to Opera (from the first Blink-based version), as well.

The next step would be to start a PR on this. Is this something you're interested in doing yourself @romainmenke?

**Comment by romainmenke** [comment]
@ddbeck Thank you 🙂 
I opened a PR with proposed changes.
As stated there I am still getting my bearings here so any feedback and extra info is really appreciated!

**Comment by ddbeck** [comment]
@romainmenke Thank you! I will review it soon—hopefully we can get the data into this week's release.
