### ISSUE TITLE
css.properties.border-color - <This Property Doesn't work on input tags anymore>

### ISSUE THREAD

**Issue by itzhammad** [mdn/browser-compat-data#8835]
#### Did you test this? If so, how?

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.border-color`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/border-color
* Report started: 2021-01-23T18:44:43.952Z

</details>

**Comment by vinyldarkscratch** [comment]
This property is still functional on ￼`input` elements (I use it on my own website).  Have you set `appearance`, `-webkit-appearance` and `-moz-appearance` to`none`?  https://developer.mozilla.org/docs/Web/CSS/appearance
