### ISSUE TITLE
css.properties.aspect-ratio - Safari Technology Preview 118 added support behind "CSS Aspect Ratio" flag

### ISSUE THREAD

**Issue by ansipes** [mdn/browser-compat-data#8847]
#### What information was incorrect, unhelpful, or incomplete?

<img width="1075" alt="Screen Shot 2021-01-24 at 6 07 31 PM" src="https://user-images.githubusercontent.com/25012869/105646701-5b3c6e80-5e6f-11eb-852e-3d8e8330c808.png">

Safari Technology Preview 118 added support for css.properties.aspect-ratio behind the `CSS Aspect Ratio` flag.

Support is mentioned in release notes: https://developer.apple.com/safari/technology-preview/release-notes/

Support aspect-ratio on non-replaced elements: https://trac.webkit.org/changeset/270551/webkit/

Support aspect-ratio on replaced elements: https://trac.webkit.org/changeset/270618/webkit/

#### What did you expect to see?

I expected to see Safari marked as having `partial` support with a flag icon, or perhaps a dropdown like Google Chrome, instructing readers on how to enable the feature for testing.

#### Did you test this? If so, how?

Yes, I tested it using a CodePen: https://codepen.io/ansipes/pen/QWKXGpB

<img width="1234" alt="Screen Shot 2021-01-24 at 6 03 02 PM" src="https://user-images.githubusercontent.com/25012869/105646546-78bd0880-5e6e-11eb-98aa-c16189bdaa52.png">

<img width="1528" alt="Screen Shot 2021-01-24 at 6 04 20 PM" src="https://user-images.githubusercontent.com/25012869/105646608-c174c180-5e6e-11eb-9b40-270fe7fd6b08.png">

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.aspect-ratio`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/aspect-ratio
* Report started: 2021-01-24T22:54:38.686Z

</details>

**Comment by ddbeck** [comment]
Thanks for reporting this, @ansipes.

Unfortunately, tracking Safari Technology Preview data isn't something we can do just yet, since it hasn't been practical for us to map TP versions to regular Safari versions. See https://github.com/mdn/browser-compat-data/pull/8103#issuecomment-759330072 for a little more detail.

We can proceed with this when a non-TP Safari beta/final release appears with this feature, giving us a proper version number to enter for this feature. In the meantime, I'm going to label this as blocked. If/when we can move ahead on this, I'd welcome a nudge (or PR). Thank you again!

**Comment by ddbeck** [comment]
https://github.com/mdn/browser-compat-data/pull/8802#issuecomment-769794256 also mentioned some details about this.

**Comment by ansipes** [comment]
Thanks @ddbeck , I will read those!

I'll keep an eye on it, and if it makes it to Safari 15 Beta or Release, I'll nudge. In the meantime, I'll look at some past PRs and see if I can submit a PR instead of just a nudge!

**Comment by jculver050** [comment]
Close

**Comment by bramjoosten** [comment]
@ddbeck bump
https://developer.apple.com/documentation/safari-release-notes/safari-15-beta-release-notes
excited because it will be the last browser starting to support this :)

**Comment by Schweinepriester** [comment]
I believe this issue can be closed, because #11135/Safari 15 and more importantly that is has been updated already? 0:-)
- https://developer.mozilla.org/en-US/docs/Web/CSS/aspect-ratio#browser_compatibility
- https://caniuse.com/mdn-css_properties_aspect-ratio

**Comment by queengooborg** [comment]
Yep, this has been taken care of in #11135!
