### ISSUE TITLE
javascript.builtins.Date.toLocaleDateString - en-GB not working

### ISSUE THREAD

**Issue by mwasigala** [mdn/browser-compat-data#8862]
#### What information was incorrect, unhelpful, or incomplete?
 new Date(date).toLocaleDateString("en-GB")
it works on other browsers and on the desktop but not of mobile chrome
#### What did you expect to see?
Assuming date is equal to this day am writing this issue
i was expecting the date to be in the format:  26/01/2021 

#### Did you test this? If so, how?
I tested in tor mobile browser its working fine and i get the format i configured but in chrome mobile i get the date in the format: 1/26/2021
but it works fine in desktop chrome

<details>
<summary>MDN page report details</summary>

* Query: `javascript.builtins.Date.toLocaleDateString`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString
* Report started: 2021-01-26T08:48:40.084Z

</details>

**Comment by ddbeck** [comment]
Thanks for reporting this issue, @mwasigala. A few questions for you to help confirm this issue

- Can you confirm the operating system you were using for each browser, desktop and mobile (e.g. Android, iOS, Windows, macOS)?
- Can you provide version numbers for each of the browsers that you tested?

Thank you!

**Comment by queengooborg** [comment]
I'm going to go ahead and close this issue since there has been no response and more info is needed to proceed.  If this is still an issue, please reply to this thread with the requested information and I'll be happy to reopen this!
