### ISSUE TITLE
css.selectors.not - Add complex selector support

### ISSUE THREAD

**Issue by takamoso** [mdn/browser-compat-data#8874]
#### What information was incorrect, unhelpful, or incomplete?

CSS `:not()` now supports complex selectors:

```css
p:not(article *) {
  /* select all <p>s that are not descendants of <article> */
}
```

#### What did you expect to see?

| Edge | Firefox | Chrome | Safari | iOS Safari | Android |
|------|--------|---------|-------|-----------|---------|
|   88  |    84     |     88      |     9     |         9       |      88     |

#### Did you test this? If so, how?

Tested by BrowserStack.

#### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

- Firefox https://hacks.mozilla.org/2020/12/and-now-for-firefox-84/
- Chrome https://blog.chromium.org/2020/12/chrome-88-digital-goods-lighting.html
- Safari https://webkit.org/blog/3615/css-selectors-inside-selectors-discover-matches-not-and-nth-child/

**Comment by ddbeck** [comment]
Thanks for opening this issue, @takamoso, and for providing a lot of helpful details and direct testing. 👏 

After we sort out the structure in that PR, #7376 will fix this for Firefox and Safari. After that, we can do a follow-up PR for Chrome and Edge and Opera. I'll follow up here with next steps when that PR is done.

**Comment by queengooborg** [comment]
It looks like #7376 has also taken care of Chromium, so this issue can now be closed!
