### ISSUE TITLE
html.elements.article - not supported in Internet Explorer

### ISSUE THREAD

**Issue by Badlapje** [mdn/browser-compat-data#8876]
When looking at [caniuse for the article element](https://caniuse.com/mdn-html_elements_article) it says that it's fully supported on IE11.  However, this turns out to not be true.  When using the document.querySelectorAll method to retrieve a list of articles from the DOM, the childnodes are always empty.  This is despite the fact that if you retrieve the grandparent you'll see the nodes in question correctly displayed as the child of the child.

Changing the article to a div resolves the problem.  Using the html5shiv does not.

Interestingly: [caniuse on html5 semantic elements](https://caniuse.com/html5semantic) does say only main is supported.  So the data is part right.

**Comment by ddbeck** [comment]
Thanks for reporting this issue, @Badlapje. Unfortunately, I wasn't able to reproduce the problem described here, nor was I able to find any other evidence that the element is unsupported (e.g., the object representing the `<article>` element being an instance of `HTMLUnknownElement`).

I'm going to close this issue, but if you think this problem still applies, please follow-up with a minimal test case (with both HTML and JavaScript code) to demonstrate the problem. Thank you again!
