### ISSUE TITLE
CSS flex-direction - Firefox supports overflow

### ISSUE THREAD

**Issue by machal** [mdn/browser-compat-data#8883]
According [to Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1042151) starting from Firefox version 81 this is no longer true:

> Does not support overflow when using `*-reverse`. 

- https://github.com/mdn/browser-compat-data/blob/master/css/properties/flex-direction.json
- https://caniuse.com/mdn-css_properties_flex-direction

**Comment by ddbeck** [comment]
Thanks for reporting this, @machal.

To fix this, the notes [`flex-direction.json`](https://github.com/mdn/browser-compat-data/blob/master/css/properties/flex-direction.json#L41) ought to be rewritten to say something like:

> Before Firefox 81, overflow with <code>*-reverse</code> is unsupported. See <a href='https://bugzil.la/1042151'>bug 1042151</a>.

I'd welcome a PR from you (or another contributor) to make this change for both Firefox and Firefox for Android.
