### ISSUE TITLE
api.MediaDevices.getUserMedia - compatibility matrix does not distinguish between browserand wbview differences

### ISSUE THREAD

**Issue by gedw99** [mdn/browser-compat-data#8884]
https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia

You need to show how running in a browser and running in a webview has different API's enabled.

getUserMedia does work on apple browsers on desktop but does not work on desktop as a webview.
It also does not work on apple ios mobile as a webview.

this is a feature btw thagt is holdng back webrtc video conferencing systemsbeing built as a PWA.

**Comment by ddbeck** [comment]
Thanks for reporting this issue, @gedw99.

Unfortunately, we don't track the differences between iOS/macOS views compared to Safari. We lack the resources or community involvement needed to consider these as alternative engines (see [_Addition of browsers_](https://github.com/mdn/browser-compat-data/blob/master/docs/data-guidelines.md#addition-of-browsers) in our docs for a little more background). Until those resources and community involvement emerge and those alternative engines are adopted, we can't record this data.

As a consequence, I must close this issue. Thank you for your understanding.
