### ISSUE TITLE
css.properties.{scroll-margin,scroll-padding} - Implemented in Safari

### ISSUE THREAD

**Issue by ddbeck** [mdn/browser-compat-data#8887]
I'm parking some information from #8103, which can't yet be merged, in this issue.

#8103 was opened on the expectation that the following features are likely to ship in the next release of Safari, since it's in Safari Technology Preview now:

- `css.properties.scroll-margin`
- `css.properties.scroll-margin-bottom`
- `css.properties.scroll-margin-left`
- `css.properties.scroll-margin-right`
- `css.properties.scroll-margin-top`
- `css.properties.scroll-padding`
- `css.properties.scroll-padding-bottom`
- `css.properties.scroll-padding-left`
- `css.properties.scroll-padding-right`
- `css.properties.scroll-padding-top`

(see the original PR for more detail, tests, etc.)

But we can't actually add data for these features until either #7396 merges or an actual release of Safari ships with these features.

**Comment by vinyldarkscratch** [comment]
Looks like #10129 took care of all the `scroll-margin-*` properties!  I'm surprised that the `scroll-padding-*` ones weren't included -- looks like a good opportunity for a follow-up.

**Comment by queengooborg** [comment]
The remaining properties were resolved by #12834!
