### ISSUE TITLE
javascript.builtins.Array.isArray - isArray present since Node 6

### ISSUE THREAD

**Issue by paceaux** [mdn/browser-compat-data#8890]
#### What information was incorrect, unhelpful, or incomplete?

Node.js Version is incorrect for `Array.isArray`
#### What did you expect to see?

Expected to see version 6.4, not Node v 10. 

#### Did you test this? If so, how?
1. Used iNVM to install node 6.4
2. Ran the below in the node terminal:

```
var arr = [];
Array.isArray(arr); 
```
It returned `true`;

This compatibility chart shows support in 6.4 https://node.green/#ES2015-built-ins-Proxy

<details>
<summary>MDN page report details</summary>

* Query: `javascript.builtins.Array.isArray`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray
* Report started: 2021-01-28T22:59:23.711Z

</details>

**Comment by ddbeck** [comment]
Thanks for reporting this, @paceaux. I did some checking and I'm satisfied by the data for `Array.isArray`. A few points:

- I didn't see v10.0.0 mentioned in the MDN page included in this report. I'm guessing this is an (understandable) misreading of v0.10.0 (note the leading zero). But if I'm mistaken and you saw an issue with a different page, then feel free to post a follow-up comment linking the problem page.
- I double-checked that `Array.isArray([])` in Node.js v0.10.0 and it works as expected. This is the first version of Node.js that BCD records. See the [schema documentation on initial versions](
https://github.com/mdn/browser-compat-data/blob/master/schemas/compat-data-schema.md#initial-versions) and https://github.com/mdn/browser-compat-data/issues/6861, if you'd like to know why we don't record versions before Node.js v0.10.0.
- The node.green table entry you linked to is about the behavior of `Proxy` with `Array.isArray`. As far as I can tell, we do not record data for that specific interaction, but we do correctly report `Proxy` as introduced in Node.js v6.0.0 (see [`Proxy.json`](https://github.com/mdn/browser-compat-data/blob/master/javascript/builtins/Proxy.json) for detail). Conversely, node.green doesn't appear to track the availability of the `Array.isArray` static method, so I can't directly compare our results to theirs for the method itself.

All that said, if I've missed anything, please let us know. In the mean time, I'm going to close this issue. Thanks again!
