### ISSUE TITLE
Missing compat data for Intl.Segmenter

### ISSUE THREAD

**Issue by foolip** [mdn/browser-compat-data#8894]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Segmenter doesn't have any compat table because BCD doesn't have any entries for `Intl.Segmenter`.

I don't know this API, but I can see that these bits are shipping in Chrome:
- `Intl.Segmenter` constructor
- `Intl.Segmenter.prototype.resolvedOptions` method
- `Intl.Segmenter.prototype.segment` method
- `Intl.Segmenter.supportedLocalesOf` method (static, not on the prototype)

This is one of very few JS things I've found to be missing via https://github.com/foolip/mdn-bcd-collector/issues/917.

**Comment by foolip** [comment]
`Intl.Segmenter` was [shipped in Chrome 87](https://groups.google.com/a/chromium.org/g/blink-dev/c/MJ1OpvkcA8s/m/_iD0XzioBwAJ). cc @jpmedley

**Comment by jculver050** [comment]
Close

**Comment by jculver050** [comment]
Close
