### ISSUE TITLE
api.ParentNode.replaceChildren - Display Safari as supported

### ISSUE THREAD

**Issue by joedakroub** [mdn/browser-compat-data#8895]
#### What information was incorrect, unhelpful, or incomplete?
It looks like desktop Safari now supports `ParentNode.replaceChildren`: https://bugs.webkit.org/show_bug.cgi?id=198578

#### What did you expect to see?
Desktop Safari should be checked to show support for `ParentNode.replaceChildren`

#### Did you test this? If so, how?
I tested this in desktop Safari 14.0.2 running on macOS Catalina 10.15.7

<details>
<summary>MDN page report details</summary>

* Query: `api.ParentNode.replaceChildren`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/ParentNode/replaceChildren
* Report started: 2021-01-29T15:52:46.249Z

</details>

**Comment by joedakroub** [comment]
This is a duplicate of https://github.com/mdn/browser-compat-data/issues/8145

**Comment by ddbeck** [comment]
> This is a duplicate of #8145

This is correct. Since #8145 has a little extra detail (e.g., which file needs to be edited), let's close this one in favor of that one. Thank you for confirming the details and locating the original issue, @joedakroub!
