### ISSUE TITLE
http.methods.GET - Calling Places API using Ajax on browser side giving error

### ISSUE THREAD

**Issue by myur2707** [mdn/browser-compat-data#8901]
We have generated the Google Places API and by calling the below API we can get the result. 
https://maps.googleapis.com/maps/api/place/autocomplete/json?input=Ahmedabad&key=MY-API-KEY&sessiontoken=1234567890

But, when I call using Ajax on the browser side. It gives me the below error. Please find the attachment for more details about the error.
jquery-1.8.0.js:8241 Access to XMLHttpRequest at 'https://maps.googleapis.com/maps/api/place/autocomplete/json?input=Ahmedabad&key=MY-API-KEY&sessiontoken=1234567890' from origin 'http://localhost:5137' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Google Maps JavaScript API error: ApiNotActivatedMapError
https://developers.google.com/maps/documentation/javascript/error-messages#api-not-activated-map-error

We have enabled only Places API, not the Maps JavaScript API. Do we need to enable it? Now, what we need to do to use API on the client-side using ajax? Please advise.

**Comment by ddbeck** [comment]
Hi @myur2707. It looks like you're trying to get help with a Google API. This repository is for MDN's browser compatibility data, not Google or general web development help. I suggest you seek help with Google directly. Thank you!
