### ISSUE TITLE
api.Element.dblclick_event - dblclick is supported on Chrome for Android

### ISSUE THREAD

**Issue by toBeOfUse** [mdn/browser-compat-data#8904]
#### What information was incorrect, unhelpful, or incomplete?

The compatibility table says that dblclick events are not supported on Chrome Android. However, the demo of the event on [the event page](https://developer.mozilla.org/en-US/docs/Web/API/Element/dblclick_event) works on my OnePlus HD1907 with Chrome version 88.0.4324.93.

#### What did you expect to see?

I expected either the compatibility data to show that dblclick events work on Mobile Chrome or for the event not to fire on the demo page.

#### Did you test this? If so, how?

I also accessed the phone with remote debugging and logged a dblclick event from it to the console to show that it actually existed and had the correct type:
![image](https://user-images.githubusercontent.com/49729978/106362990-cfee2d80-62f3-11eb-87ea-650303a52c37.png)

<details>
<summary>MDN page report details</summary>

* Query: `api.Element.dblclick_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/dblclick_event
* Report started: 2021-01-30T16:53:50.376Z

</details>

**Comment by ddbeck** [comment]
Thanks for reporting this, @toBeOfUse.

I'd like to understand the details a little better here before suggesting a change to the data. When you tested this on your device, how did you trigger the `dblclick` event? Physically, with a mouse or by touch? Or triggering it programmatically? If the latter, can you provide some sample code?

Thanks again for your help!

**Comment by toBeOfUse** [comment]
I only used code to log the event to the console; in the remote debugging session, I selected the paragraph element in the "Elements" tab and used it as a temporary variable in the console, writing `$0.addEventListener("dblclick", (e)=>console.log(e))`. I then triggered the event by double-tapping the element on my phone with my finger, which produced the log above. I can go back and take more screenshots or make a screen recording if that would help

**Comment by toBeOfUse** [comment]
To create an example with as few confounding variables as possible, I have created a CodePen that listens for dblclick events on the body element and logs them to the innerHTML of the body: https://codepen.io/tobeofuse/pen/yLVeWzB

Here is a .gif screen recording of me triggering dblclick events on my phone in Android Chrome, with little white circles added by the recording software that show where and how I touched the screen:

![dblclick](https://user-images.githubusercontent.com/49729978/107083552-cff29f80-67c3-11eb-9e01-f1a9a3e798c7.gif)

**Comment by toBeOfUse** [comment]
I should note: on sites that are not optimized for mobile and are therefore rendered in a virtual viewport and scaled down, double-taps result in zooming in and out instead of triggering dblclick events (this can be tested on sites like https://unixpapa.com/js/testmouse.html.) I have not tested if this behavior can be cancelled. However, the dblclick event is definitely still supported in Android Chrome and is easily triggered on mobile-optimized sites.

**Comment by ddbeck** [comment]
Thank you, @toBeOfUse! You went above and beyond here. Playing with your demo, I suspect the story here is that the API existed since the same version as the desktop Chrome (that is, the very first releases of Chrome for Android), though triggering the event physically may be hardware dependent (I got mixed results in emulators). That makes sense and it's nice when things make sense.

To move this forward, I would propose updating the [`dblclick_event` feature in `Element.json`](https://github.com/mdn/browser-compat-data/blob/master/api/Element.json#L2723-L2772). Specifically, we'd need to set `chrome_android`'s version to `"18"`. We could probably also set the WebView value to `"≤37"`. I'd welcome a PR from you (or another contributor) to make this change.

Thank you again!

**Comment by jculver050** [comment]
Close
