### ISSUE TITLE
webextensions.api.windows - No mention of limits on API Availability

### ISSUE THREAD

**Issue by randycasburn** [mdn/browser-compat-data#8905]
#### What information was incorrect, unhelpful, or incomplete?
This API is a Chromium Extension only API that is only available within Chrome Extensions
#### What did you expect to see?
Either the declaration that this is only available in Chrome Extensions, or a link to a W3C spec stating otherwise
#### Did you test this? If so, how?
Yes.

1. Open any browser
2. Open dev console in that session
3. Attempt to access `chrome`, or `chrome.windows` or `chrome.tab`, or  **`windows`**, `Windows.`, etc.
4. The API is unavailable in any browser

Note: Although the `chrome` object is available, neither the `windows` nor the `tab` objects exist

<details>
<summary>MDN page report details</summary>

* Query: `webextensions.api.windows.WindowState`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/windows/WindowState
* Report started: 2021-01-30T17:40:06.896Z

</details>

**Comment by queengooborg** [comment]
Sorry it took so long to answer this question.  Yes, this is correct, the `windows` API is only for use within web extensions.  This goes for anything within the `webextensions` BCD category, or the "Browser Extensions" pages on MDN (anything with `/Add-ons/WebExtensions` in the URL); these pages document the APIs available in web extensions.
