### ISSUE TITLE
javascript.builtins.String.replace - IE5.0 doesn't seem to support a function as a second argument

### ISSUE THREAD

**Issue by unterwulf** [mdn/browser-compat-data#8908]
#### What information was incorrect, unhelpful, or incomplete?
IE has full support of javascript.builtins.String.replace since IE4

#### What did you expect to see?
I haven't checked IE4, but at least IE5.00.2314.1003 under Windows 95 doesn't take a function as a second parameter. Instead it always interpret it as a string, even when there are no quotes.

#### Did you test this? If so, how?
`alert('abc'.replace(/./g, function(c) { return '%' + c.charCodeAt(0).toString(16); }));`
##### I expected to see:
%61%62%63
##### I actually saw:
function(c) { return '%' + c.charCodeAt(0).toString(16); }))function(c) { return '%' + c.charCodeAt(0).toString(16); }))function(c) { return '%' + c.charCodeAt(0).toString(16); }))'

<details>
<summary>MDN page report details</summary>

* Query: `javascript.builtins.String.replace`
* MDN URL: https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Global_Objects/String/replace
* Report started: 2021-01-30T23:15:24.269Z

</details>

**Comment by ddbeck** [comment]
Thanks for reporting this issue, @unterwulf.

I'm only able to test as far back as IE 6 (via BrowserStack) and it does work there, but I'll take your word for it that this fails in IE 5. To fix this in the compat data, we'd need to set the IE value to `"≤6"` in the [`replace` feature in `String.json`](https://github.com/mdn/browser-compat-data/blob/master/javascript/builtins/String.json#L1807-L1858).

Alternatively, if you're able to test this is in IE 5.5, we could set a more specific value. If it works in IE 5.5, we can use `"5.5"`; if it doesn't, then we can use `"6"`. If you are able to test this, I'd appreciate it if you could update this issue with the results (whether you can do this next part or not).

I'd welcome a PR from you (or another contributor) making this change to the data. Thank you!

**Comment by unterwulf** [comment]
Tested the same JS code on IE 5.50.4134.0600 under Win 95 4.00.950 B and it works as expected. So I guess 5.5 is the minimal IE version that fully supports this method.

Sorry, I can't create a PR as I'm completely stranger in this project, just using these webpages as a reference doing retro websites.

**Comment by ddbeck** [comment]
Fixed by https://github.com/mdn/browser-compat-data/pull/9725. Thank you, @unterwulf!
