### ISSUE TITLE
javascript.builtins.FinalizationRegistry - Opera 70+ supports it

### ISSUE THREAD

**Issue by aptiko** [mdn/browser-compat-data#8910]
#### What information was incorrect, unhelpful, or incomplete?

The page says the feature isn't supported by Opera.

#### What did you expect to see?

It *is* supported by Opera, at least version 73.

#### Did you test this? If so, how?

I ran Opera 73 on my system, opened the browser console, and typed "registry = new FinalizationRegistry(() => 'hello')" and it worked.

<details>
<summary>MDN page report details</summary>

* Query: `javascript.builtins.FinalizationRegistry`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/FinalizationRegistry
* Report started: 2021-01-31T11:05:07.798Z

</details>

**Comment by ddbeck** [comment]
Thanks for reporting this, @aptiko. It looks like `FinalizationRegistry` appeared in Chrome 84, which would correspond to Opera 70 and Opera Android 60; a quick check shows this is in fact available in Opera 70 but not 69. I'd welcome a PR (from you or another contributor) updating [`FinalizationRegistry.json`](https://github.com/mdn/browser-compat-data/blob/master/javascript/builtins/FinalizationRegistry.json) with those values. Thank you again!
