### ISSUE TITLE
api.InputEvent.data - Safari support

### ISSUE THREAD

**Issue by benhormann** [mdn/browser-compat-data#8912]
<https://webkit.org/blog/7358/enhanced-editing-with-input-events/>
> Input events are enabled by default as of Safari Technology Preview 18, and available in Safari 10.1 in the recent beta releases of macOS 10.12.4 and iOS 10.3.

Please also update `api.InputEvent.dataTransfer`, `api.InputEvent.InputEvent`. Maybe remove the experimental flag too?

I can only confirm these three features to be working (Safari 14 - macOS 15), not sure about [InputEvent.inputType 'insertFromPasteAsQuotation'](https://developer.mozilla.org/en-US/docs/Web/API/InputEvent/inputType#browser_compatibility).

<details>
<summary>MDN page report details</summary>

* Query: `api.InputEvent.data`
* MDN URL: https://developer.mozilla.org/en-us/docs/Web/API/InputEvent/data
* Report started: 2021-01-31T11:16:47.856Z

</details>

**Comment by ddbeck** [comment]
Thanks for reporting this, @benhormann.

I'm willing to accept the WebKit blog's report that this landed in Safari 10.1, for the features mentioned in that blog post (the constructor, `data`, `dataTransfer`, etc.).

I'd welcome a PR from you (or another contributor) updating this data in [`InputEvent.json`](https://github.com/mdn/browser-compat-data/blob/master/api/InputEvent.json). Thank you again!

(It looks like `insertFromPaste…` feature is specific to Firefox. We can leave that alone for now.)
