### ISSUE TITLE
html.elements.video - intrinsicsize remove

### ISSUE THREAD

**Issue by tomByrer** [mdn/browser-compat-data#8918]
#### What information was incorrect, unhelpful, or incomplete?

[`intrinsicsize` proposal is withdrawn](https://github.com/WICG/intrinsicsize-attribute#note-this-proposal-is-no-longer-active-instead-efforts-are-focused-on-the-alternate-approach-in-issue-16)
It was behind a flag in Chrome, but also removed there; IMHO historical is not good enough reason to keep this around & clutter an already long list.

<details>
<summary>MDN page report details</summary>

* Query: `html.elements.video`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video
* Report started: 2021-01-31T21:18:09.852Z

</details>

**Comment by ddbeck** [comment]
Thanks for raising this issue, @tomByrer. Unfortunately, not enough time has yet elapsed to remove this feature from BCD. Under [our irrelevance guideline](https://github.com/mdn/browser-compat-data/blob/master/docs/data-guidelines.md#removal-of-irrelevant-features), we wait two years from the feature's removal before dropping such features from our data. This eligible to removed in November 2021; feel free to re-raise this issue then. Thank you!
