### ISSUE TITLE
css.selectors.where - Available on Edge

### ISSUE THREAD

**Issue by NagayamaToshiaki** [mdn/browser-compat-data#8931]
#### What information was incorrect, unhelpful, or incomplete?
:where selector is available on Edge version 88.
#### Did you test this? If so, how?
The Example at [https://developer.mozilla.org/en-US/docs/Web/CSS/:where](https://developer.mozilla.org/en-US/docs/Web/CSS/:where) works as intended.

<details>
<summary>MDN page report details</summary>

* Query: `css.selectors.where`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/:where
* Report started: 2021-02-02T12:41:26.491Z

</details>

**Comment by ddbeck** [comment]
Thanks for reporting this, @NagayamaToshiaki. This aligns with the data we already have for Chrome 88 in [`where.json`](https://github.com/mdn/browser-compat-data/blob/24626f2fe468aae9bf314a8fef7a75d5c34f84fa/css/selectors/where.json#L42).

I'd welcome a PR from you (or another contributor) to update Edge's value for the `:where` feature and its subfeature to version 88. Thank you!
