### ISSUE TITLE
Should we have features for all HTTP status codes?

### ISSUE THREAD

**Issue by ddbeck** [mdn/browser-compat-data#8936]
Inspired by #7561, #8016, and #8692.

As #8692 highlights, not all specified HTTP status codes are tracked in BCD. Should they be?

The main problem with status codes is that many do not present an obvious compatibility question for web developers. Many (most?) are specified such that they do not call for any additional user agent behavior that's not already covered by the default x00 behaviors. In such cases, what would such feature data mean except as a reiteration of the x00 data?

For example, consider 451 (for which we do have some data). [The spec](https://tools.ietf.org/html/rfc7725) doesn't appear to call for any user agent behavior in addition to [the default behavior for 4xx-series](https://tools.ietf.org/html/rfc7231#section-6.5.1) statuses. For any browser that supports 400, is there anything additional to be said about its support for 451 (barring some noteworthy bug)?

Accepting new data for such statuses becomes quite challenging to review. If a user agent safely ignores a status, is that a kind of support too? See #7561 for an example of this in action.

That said, it does seem like an obvious gap for BCD to omit such data. Consumers have already raised this; see #8692 for an example.

We should probably answer a few questions about HTTP status codes:

- Are we going to include all codes?
- If we're going to include all codes, can we come up with a guideline or set of guidelines to determine when to mark a browser as supporting a code (if the spec is otherwise silent on the matter)?
- If we're going to selectively include codes, what's the (ir)relevance criteria for a status code?

However we answer these questions, we probably ought to come up with a list of status codes to include or remove and open issues or PRs accordingly.

**Comment by queengooborg** [comment]
Since #23529 was just merged which removes most of the HTTP status codes, I'm going to close this as resolved!
