### ISSUE TITLE
Remove "matches" object from schema

### ISSUE THREAD

**Issue by ddbeck** [mdn/browser-compat-data#8945]
## Summary

The [`matches`](https://github.com/mdn/browser-compat-data/blob/master/schemas/compat-data-schema.md#the-matches-object) has had poor uptake since being introduced to BCD. We should deprecate and remove it from the schema, data, and documentation.

## Background

In https://github.com/mdn/browser-compat-data/pull/3631 we added `matches` to the support object, which provides for tokens or regexes to use to identify code that corresponds to a given BCD feature.

In https://github.com/mdn/browser-compat-data/issues/3709, we tried to solicit more `matches` data, but little activity followed.

Ultimately, we have four features with `matches` data:

- `css.properties.transform-origin.three_value_syntax`
- `css.properties.transform.3d`
- `css.selectors.backdrop`
- `css.types.color.alpha_hexadecimal_notation`

To support those four features we have written 70+ lines of code in an already complex linter, 20+ lines in the schema, and almost 200 words of documentation.

## Proposal

We ought to remove `matches` from the schema. The costs of keeping it are high and the risks of removing it are low.

The psychic cost of keeping `matches` around is high:

- It’s a burden on new BCD consumers and contributors who read the schema documentation. They must learn about `matches` and learn to ignore it.
- It's a burden on BCD's maintainers. I periodically notice this sad, disused bit of the schema and feel wistful about it.

The cost and risk of removing `matches` is low:

- Few parts of BCD itself relies on this—it’s largely self-contained—so stripping it out wouldn't be a particularly complicated or demanding effort.
- Given so little data uses this part of the schema, consumer dependence on it must be rare.

That's not to say that removal is is completely without penalty, however:

- Some consumers do use it, most notably webhintio. See [this example](https://github.com/webhintio/hint/blob/752e027aa54a9a326bd216f8903e4924b2cfab2f/packages/utils-compat-data/src/css.ts#L62-L93). There's not much we can do about this.
- Removal itself could annoy consumers. Removal would cause a backwards-incompatible change, necessitating a SemVer major release. We could partly mitigate this by delaying the removal until we have other breaking changes to make.
 
Overall, I think this points towards removal as a good option.

## Implementation

To do this would require a few tasks:

- Issue a SemVer minor release noting that `matches` is deprecated, will be removed in a future release, and new data will not be accepted for it. Also update the documentation accordingly.
- Remove `matches` from the schema, the data, and any mentions of it in the documentation.
- Issue a SemVer major release with those changes.

## Next steps

To move forward on this, we need to make a decision about whether we actually want to do it. I'd like to hear feedback on this proposal, so the project owners can make a decision.

**Comment by ddbeck** [comment]
`css.properties.transform-origin.three_value_syntax` will eventually be removed as a consequence of https://github.com/mdn/browser-compat-data/issues/8964

**Comment by Elchi3** [comment]
I agree to remove this.

**Comment by Fyrd** [comment]
Wanted to point out that caniuse actually has been using the "keywords" value that the matches object provides in some places, however I also have my own way of adding keywords to BCD features, so not a huge loss.

**Comment by jculver050** [comment]
Close

**Comment by jculver050** [comment]
Close

**Comment by Elchi3** [comment]
Hey @antross, webhintio uses this feature in https://github.com/webhintio/hint/blob/e93ca2b82542e408994f2d50374b86d5ebef110c/packages/utils-compat-data/src/css.ts#L62. We now have a PR to remove (https://github.com/mdn/browser-compat-data/pull/15781) and so if we merge it at some point soon (along with semver major bump), it would break your code. What do you think about it?

**Comment by antross** [comment]
FYI @molant

Thanks for the heads-up @Elchi3. I'm bummed, but supportive of the change. I agree the `matches` annotations would only provide value long-term if they were being incorporated into new entries. Since that's unfortunately not been happening removal seems appropriate.

As far as impact on webhint goes, this will cause webhint to stop reporting lack-of-support by browsers for the few existing cases (`transform-origin` 3-value syntax, 3D transform keywords, hex colors with alpha, etc.) We'll separately review the current browser support for these features to decide if it's worth special-casing on our side or to just let this flow through.
