### ISSUE TITLE
api.Notification.data - Chrome for Android should be marked as supporting the feature

### ISSUE THREAD

**Issue by fpetitit** [mdn/browser-compat-data#8946]
#### What information was incorrect, unhelpful, or incomplete?

The page mentions that Chrome for Android does not support Notification.data, but it does.

#### What did you expect to see?

Chrome for Android should be marked as supporting the feature.

#### Did you test this? If so, how?

Yes, on a Motorola E4 device using Android 7.1.1 and Chrome 88 (last version at the moment).

<details>
<summary>MDN page report details</summary>

* Query: `api.Notification.data`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Notification/data
* Report started: 2021-02-03T13:08:36.870Z

</details>

**Comment by ddbeck** [comment]
Thanks for reporting this, @fpetitit.

[This Chrome Platform Status entry](https://chromestatus.com/feature/5736434757533696) says this shipped in Chrome 44 and testing confirms that this is true. This feature seems to have appeared on all the Chromiums simultaneously.

To fix this, the `data` feature in [`Notification.json`](https://github.com/mdn/browser-compat-data/blob/master/api/Notification.json#L329-L376) needs to be updated to show that it was added in Chrome 44, Chrome for Android 44, WebView 44, Opera 31, and Opera for Android 32.

I'd welcome a PR from you or another contributor that makes this change. Thank you again!

**Comment by fpetitit** [comment]
PR created : https://github.com/mdn/browser-compat-data/pull/9077

**Comment by ddbeck** [comment]
Fixed by #9077.
