### ISSUE TITLE
html.elements.menuitem - Should mark all properties behind flag

### ISSUE THREAD

**Issue by evilpie** [mdn/browser-compat-data#8947]
PR #8019 marked the main `<menuitem>` feature as behind a flag. Looking at the MDN page https://developer.mozilla.org/en-US/docs/Web/HTML/Element/menuitem, all other attributes `checked` are not marked as behind a flag.

**Comment by ddbeck** [comment]
This is related to #6509. We never really specified whether flags ought to cascade to descendant features. I think we need to settle #6509 before committing to resolving this _within_ BCD, or whether this should be a BCD consumer problem (e.g., that the table renderer needs to sort ths out).

**Comment by foolip** [comment]
I just came across this issue as well and it goes beyond the question of cascading flags. Parts of this feature are still marked as unconditionally supported in Firefox but are in fact behind a flag ("dom.menuitem.enabled") now:
- https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/contextMenu
- api.GlobalEventHandlers.onshow (no MDN page)
- `label` and `type` in https://developer.mozilla.org/en-US/docs/Web/API/HTMLMenuElement#browser_compatibility
- https://developer.mozilla.org/en-US/docs/Web/API/HTMLMenuItemElement#browser_compatibility
- Probably https://developer.mozilla.org/docs/Web/API/Element/show_event and other things one would find by searching for "contextmenu"

**Comment by foolip** [comment]
This is all complicated by the fact that `<menu>` remains in HTML but is really only for semantics now:
https://html.spec.whatwg.org/multipage/grouping-content.html#the-menu-element

Care has to be taken with `<menu>` and `HTMLMenuElement`.
