### ISSUE TITLE
Remove three_value_syntax subfeatures

### ISSUE THREAD

**Issue by foolip** [mdn/browser-compat-data#8964]
These subfeatures were added in https://github.com/mdn/browser-compat-data/pull/4882 and the current state can be seen here:
https://developer.mozilla.org/en-US/docs/Web/CSS/mask-position#browser_compatibility
https://developer.mozilla.org/en-US/docs/Web/CSS/object-position#browser_compatibility
https://developer.mozilla.org/en-US/docs/Web/CSS/perspective-origin#browser_compatibility
https://developer.mozilla.org/en-US/docs/Web/CSS/position_value#browser_compatibility
https://developer.mozilla.org/en-US/docs/Web/CSS/shape-outside#browser_compatibility

Support was removed from WebKit in https://bugs.webkit.org/show_bug.cgi?id=189142 and matching the version numbers that rolled out with Safari 13.1 / iOS 13.4.

I started fixing the data but there's too much. In addition to the WebKit change, there are lots of prefixed entries which don't have the `version_removed` bits, and support is still claimed for Firefox for Android. The entries should also be made non-standard and deprecated.

Since the entries won't be found by looking for features removed everywhere, I'm filing this issue to eventually remove them, two years after the Safari 13.1/13.4 release date, which will be 2022-03-24.

cc @rachelandrew

**Comment by jculver050** [comment]
Close
