### ISSUE TITLE
api.FontFaceSet.check - Partially supported in Firefox

### ISSUE THREAD

**Issue by kingkrayz** [mdn/browser-compat-data#8966]
#### What information was incorrect, unhelpful, or incomplete?  
Firefox supports of FontFaceSet.check()
#### What did you expect to see?
Although Firefox will not throw an error when using document.fonts.check(), this function will always return true irrespective if font exists.  The primary reason is likely for privacy.  Because this function does not work as intended intentionally by Firefox, it is an error to state Firefox supports FontFaceSet.check().
#### Did you test this? If so, how?
Yes, for webpage design.

<details>
<summary>MDN page report details</summary>

* Query: `api.FontFaceSet.check`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/FontFaceSet/check
* Report started: 2021-02-04T11:16:28.776Z

</details>

**Comment by ddbeck** [comment]
Hi @kingkrayz and thank you for reporting this issue.

The spec changed in 2020 to remove the error condition. Now, Firefox has the behavior specified in [the CSS Font Loading spec](https://drafts.csswg.org/css-font-loading/#font-face-set-check), emphasis mine:

> Two special cases in this method’s behavior should be noted, as they are non-obvious:
>
> * If the specified fonts exist, but all possible faces are ruled out due to their unicode-range not covering the provided text, the method returns `true`, as the text will be rendered in the UA’s fallback font instead, and won’t trigger any font loads.
> * Likewise, **if none of the specified fonts exist (for example, names are mis-spelled), the method also returns `true`**, because using this font list will not trigger any loads; instead, fallback will occur.

Additional background:

* https://bugzilla.mozilla.org/show_bug.cgi?id=1252821
* https://github.com/w3c/csswg-drafts/issues/5744
* https://github.com/w3c/csswg-drafts/pull/5757

This suggests that Chrome's implementation is the one that's incorrect. [Bug 591602](https://bugs.chromium.org/p/chromium/issues/detail?id=591602) was opened about this issue, but closed as WontFix.

To report this in BCD, we ought to add a note to Chrome's data (and its derivative browsers) in [`FontFaceSet.json`](https://github.com/mdn/browser-compat-data/blob/master/api/FontFaceSet.json#L146-L193), reporting that those browsers return `false` for unrecognized fonts.

I'd welcome a PR (from you or another contributor) to add those notes. Thank you!

**Comment by queengooborg** [comment]
This has been fixed by #17954!
