### ISSUE TITLE
webextensions.api.webNavigation - Update TransitionQualifier and TransitionType features introduced from Bug 1263723 in Firefox 49

### ISSUE THREAD

**Issue by rpl** [mdn/browser-compat-data#9019]
#### What information was incorrect, unhelpful, or incomplete?

In [Bug 1263723](https://bugzilla.mozilla.org/show_bug.cgi?id=1263723) we have introduced the following feature:
- TransitionQualifier: from_address_bar
- TransitionType: typed, generated, keyword, auto_bookmark (when coming from the awesomebar autocompletion)

#### What did you expect to see?

we should update the `version_added` compat property for the features listed in [Bug 1263723 comment 0](https://bugzilla.mozilla.org/show_bug.cgi?id=1263723#c0).

#### Did you test this? If so, how?

the build infrastructure is testing this for us ;-)
- [browser/components/extensions/test/browser/browser_ext_webNavigation_urlbar_transitions.js](https://searchfox.org/mozilla-central/source/browser/components/extensions/test/browser/browser_ext_webNavigation_urlbar_transitions.js)

#### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

- [Bug 1263723](https://bugzilla.mozilla.org/show_bug.cgi?id=1263723).

**Comment by rpl** [comment]
I'm happy to create the PR or review it if someone open it before I get back to this.

**Comment by jculver050** [comment]
Close

**Comment by jculver050** [comment]
Close
