### ISSUE TITLE
Missing and wrong non-standard flags in WebExt APIs

### ISSUE THREAD

**Issue by freaktechnik** [mdn/browser-compat-data#902]
Just noticed the new compat tables, very neat!

While looking at https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Browser_support_for_JavaScript_APIs I noticed a few things about the usage of "non-standard":

 - Assuming the standard is https://browserext.github.io/browserext/ (though currently it seems it's Firefox)
 - `menus` is in fact the non-standard namespace
 - Only APIs that Firefox does not implement are marked as non-standard, instead of many, many more APIs

I also wondered if it'd make sense to add a reference to the browser ext standard in docs near the end, similar to the web documentation.

**Comment by wbamberg** [comment]
Please see: https://github.com/mdn/browser-compat-data/issues/618.

It's actually quite unclear what we should call non-standard, and whether we should indeed use https://browserext.github.io/browserext/ as the source of truth, especially as it hasn't been updated in almost a year. So I'm waiting for https://github.com/mdn/browser-compat-data/issues/618 to progress before updating any of this.
