### ISSUE TITLE
html.manifest.screenshots - <ISSUE>

### ISSUE THREAD

**Issue by macsystem-code** [mdn/browser-compat-data#9028]
#### Did you test this? If so, how?

<details>
<summary>MDN page report details</summary>

* Query: `html.manifest.screenshots`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Manifest/screenshots
* Report started: 2021-02-07T16:24:11.503Z

</details>

**Comment by ddbeck** [comment]
There's no issue here to resolve. Closing.
