### ISSUE TITLE
html.elements.video - crossorigin attribute broken on Firefox until 74

### ISSUE THREAD

**Issue by andref** [mdn/browser-compat-data#9038]
#### What information was incorrect, unhelpful, or incomplete?

Firefox (desktop) support for the `<video>` element's `crossorigin` attribute was broken until version 74, according to [Bugzilla #1532722](https://bugzilla.mozilla.org/show_bug.cgi?id=1532722). Only the first request sends cookies when `crossorigin="use-credentials"`. Seek requests do not.

#### What did you expect to see?

The minimum compatibility version should be 74 and not 12.

#### Did you test this? If so, how?

Not directly. A user reported being unable to play video on Firefox 60.9.esr (which I could reproduce) and I found the aforementioned Bugzilla report when the cause turned out to be missing `Cookie` headers in all but the first video request.

<details>
<summary>MDN page report details</summary>

* Query: `html.elements.video`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video
* Report started: 2021-02-08T17:56:55.342Z

</details>

**Comment by ddbeck** [comment]
Hi @andref and thank you for reporting this. This does seem like a significant compatibility issue in this feature.

To fix this compatibility data, the data for the `crossorigin` feature in [`video.json`](https://github.com/mdn/browser-compat-data/blob/master/html/elements/video.json#L255-L301) needs to be changed. Specifically, we'll need to update the Firefox data to have two support statements showing:

1. Full support with `version_added` 74 (desktop) or 79 (Android)
2. Partial support with `version_added` 12 (desktop and Android) and `version_removed` 74 (desktop) or 79 (Android), with `partial_implementation` and a note linking the bug you've cited.

I'd welcome a PR from you or another contributor making these changes. Thank you!

**Comment by andref** [comment]
@ddbeck There it is. Sorry for not providing it along with the bug report.

**Comment by ddbeck** [comment]
@andref Thanks for opening the PR! I'll review it soon. And no need for apologies—a good report really helpful too!
