### ISSUE TITLE
Consistency checker doesn't walk the tree (for mixins)

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#9044]
I'm working on demixing! 

One thing I noticed is that the consistency checker apparently doesn't walk the tree. 

Assume you have `api/ShadowRoot.json`
Basic support (root `__compat` object, so `api.ShadowRoot`) says chrome 53.

Now you add to that `api.ShadowRoot` tree in a file called `_mixins/DocumentOrShadowRoot__ShadowRoot.json`
And so the tree gets `api.ShadowRoot.activeElement` and it says chrome 1.

This makes no sense. ShadowRoot sub features can't exist before the ShadowRoot main interface exist. The consistency lint doesn't detect this.

**Comment by ddbeck** [comment]
I don't have a precise solution in mind for this yet, but I think this mostly stems from the fact that our checks run on a per-file basis. We might use this as an opportunity to distinguish between checks on the source (i.e., that it parses and it's formatted correctly), checks on a single feature (or its components—such as note formatting, etc.), and checks against a tree or subtree (i.e., that a tree in a given file or the whole tree is consistent).

**Comment by jculver050** [comment]
Close

**Comment by vinyldarkscratch** [comment]
Hey @jculver050, please stop posting "Close" as a reply to issues throughout this repository.  Thanks.

**Comment by foolip** [comment]
This is a bit of an issue for https://github.com/mdn/browser-compat-data/pull/10646, where I know there's some lack of consistency introduced, but I don't know how much.

**Comment by queengooborg** [comment]
This was resolved by introducing the next-gen linter in #16437!
