### ISSUE TITLE
http.status - 510 Not Extended

### ISSUE THREAD

**Issue by donaldmcdougal** [mdn/browser-compat-data#9047]
#### What information was incorrect, unhelpful, or incomplete?
"fulfill" is misspelled as "fulfil" on Microsoft Edge 88.0.705.63
#### What did you expect to see?
"fulfill"
#### Did you test this? If so, how?
No; N/A

<details>
<summary>MDN page report details</summary>

* Query: `http.status`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
* Report started: 2021-02-09T14:59:39.189Z

</details>

**Comment by ddbeck** [comment]
Hi, @donaldmcdougal. This is an issue with the content, not the compatibility table. If you'd like to see this typo fixed, please open a PR or issue on [mdn/content](https://github.com/mdn/content/). Thank you!

**Comment by donaldmcdougal** [comment]
Ah. I've never actually done this before. Thanks for letting me know!
