### ISSUE TITLE
api.FetchEvent.respondWith - Missing Safari Support

### ISSUE THREAD

**Issue by tejohnso** [mdn/browser-compat-data#9054]
#### What information was incorrect, unhelpful, or incomplete?

The Browser Compatibility indicates no support in Safari (Desktop) which is contradicted in [Is ServiceWorker Ready](https://jakearchibald.github.io/isserviceworkerready/index.html#fetchevent.respondwith()) referenced in the See Also section.

#### What did you expect to see?

Safari 11.1+ support as indicated [here](https://jakearchibald.github.io/isserviceworkerready/index.html#fetchevent.respondwith())

#### Did you test this? If so, how?

Yes, using a Browserstack live session on Safari 11.1 and the [test](https://jakearchibald.github.io/isserviceworkerready/demos/fetchevent/) included on the [Is ServiceWorker Ready](https://jakearchibald.github.io/isserviceworkerready/index.html#fetchevent.respondwith()) site.

<details>
<summary>MDN page report details</summary>

* Query: `api.FetchEvent.respondWith`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/FetchEvent/respondWith
* Report started: 2021-02-10T17:13:56.431Z

</details>

**Comment by ddbeck** [comment]
Hi @tejohnso. Thanks for raising this issue.

I was able to confirm that your test (and another) works in Safari 11.1 (but not earlier). It's likely this also applies to Safari for iOS 11.3.

To fix this, the data in [`FetchEvent.json`](https://github.com/mdn/browser-compat-data/blob/master/api/FetchEvent.json#L440-L497), in the `respondWith` feature, needs to be updated.

I would welcome a PR from you (or another contributor) making these changes.

Thank you again!

**Comment by vinyldarkscratch** [comment]
Resolved by #10680!
