### ISSUE TITLE
api.Element.scrollIntoView - Options working in Safari

### ISSUE THREAD

**Issue by liboz** [mdn/browser-compat-data#9055]
macOS Catalina 10.15.7 
Safari: Version 14.0 (15610.1.28.1.9, 15610)

#### What information was incorrect, unhelpful, or incomplete?
`scrollIntoViewOptions` is listed as not working in Safari at all

#### What did you expect to see?
It seems to work.

#### Did you test this? If so, how?
i went to a page and grabbed the reference to an element. I ran `element.scrollIntoView({block: 'center'})` and it seemed to scroll to the middle of the page.

<details>
<summary>MDN page report details</summary>

* Query: `api.Element.scrollIntoView`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView
* Report started: 2021-02-10T16:28:21.920Z

</details>

**Comment by ddbeck** [comment]
This appears to be closely related to #9055. I wouldn't be surprised if the versions were the same and the codepen linked in that issue might be easily repurposed to test this one.

**Comment by ddbeck** [comment]
Oh I forgot to say: Thanks for reporting this, @liboz! If we can establish a test for this, then we can confirm the applicable version numbers for this feature and ultimately how to update the data.

**Comment by liboz** [comment]
> This appears to be closely related to #9055. I wouldn't be surprised if the versions were the same and the codepen linked in that issue might be easily repurposed to test this one.
@ddbeck did you mean to list a different issue. 9055 is this issue

**Comment by ddbeck** [comment]
@liboz yes, you are right. I meant to link to #9059, about `Element.scrollTo`.

**Comment by Dangoo** [comment]
Stumbled across the same behavior and found the respective bug tracker entry (patched 2019-07-09). Maybe it can be of assistance:
https://bugs.webkit.org/show_bug.cgi?id=161611

Is there any information about support in Safari 13 yet, could only verify for Safari 14?

**Comment by ddbeck** [comment]
@Dangoo That's a helpful link—it constrains the range of possible versions. What I need next is a simplified test case and haven't been able to find the time to write one myself. I'm happy to actually do the test in Sauce Labs or BrowserStack to figure out whether it first appeared in 13, 13.1, or 14, but it hasn't got very high on my to do list yet.

**Comment by zuzusik** [comment]
@ddbeck maybe you could use some of these tests: https://github.com/web-platform-tests/wpt/blob/master/css/cssom-view/scrollintoview.html

**Comment by queengooborg** [comment]
This has been resolved by #19126!
