### ISSUE TITLE
api.Window.scrollTo.scrollToOptions - seems to work in Safari, for both desktop and iOS

### ISSUE THREAD

**Issue by cduque89** [mdn/browser-compat-data#9059]
I tried the following code snippet in our application:

`    
const options = {
      top: window.scrollY + topPosition,
      left: 0,
      behavior: 'smooth',
};
document.body.scrollTo(options);
`

It worked for both Safari Version 14.0.2 (16610.3.7.1.9) - Mac OS X Big Sur and on the latest iOS on an iPhone 11 Pro

#### What information was incorrect, unhelpful, or incomplete?

It states it's not compatible with Safari but it seems to work fine.

#### What did you expect to see?

It's compatible with Safari.

#### Did you test this? If so, how?

Yes, corporate application with the code snippet shown above.

<details>
<summary>MDN page report details</summary>

* Query: `api.Window.scrollTo`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollTo
* Report started: 2021-02-11T09:47:46.453Z

</details>

**Comment by ddbeck** [comment]
Thanks for reporting this, @cduque89.

For `window.scrollTo`, I was able to test this in different versions of Safari and confirm that you're right. To fix this in the data set, [the `api.Window.scrollTo.ScrollToOptions` feature of `Window.json`](https://github.com/mdn/browser-compat-data/blob/master/api/Window.json#L8547-L8587) needs to be updated to versions 10 of both Safari and Safari for iOS. I'd welcome a PR making this change.

For `api.Element.scrollTo` (as in `document.body.scrollTo`), I had some trouble testing this myself (something about my test case wouldn't work in any browser and I needed to move on to other tasks). I'd be happy to test this in different browsers to get a correct version number, but I would need a reduced test case (e.g., something in CodePen or similar) to work with. I'd welcome any links or sample code on this point.

Thank you again!

**Comment by cduque89** [comment]
Raised a PR for window.scrollTo.

I will try to reproduce my code in a CodePen and raise another PR. 

I assume the correct file is api/Element.json

**Comment by cduque89** [comment]
Get a look here: https://codepen.io/cduque89/pen/jOVVaej

**Comment by ddbeck** [comment]
Thank you so much for the test case and the PR, @cduque89!

It looks like those shipped in the same versions of Safari that shipped `Element.scrollTo` in the first place (10.1 and 10.3, respectively).

You're correct that that `api/Element.json` ([around line 7254](https://github.com/mdn/browser-compat-data/blob/master/api/Element.json#L7254)) needs the fix. Would you like to open a PR to fix that too?

**Comment by ddbeck** [comment]
Bringing this forward from the now-closed #7959:

It looks like [`api.ScrollToOptions`](https://github.com/mdn/browser-compat-data/blob/master/api/ScrollToOptions.json) data needs to be updated (and reconciled) with `Window.scrollTo.scrollToOptions` and `Element.scrollTo.scrollToOptions` alongside the other changes discussed here.

**Comment by jculver050** [comment]
Close

**Comment by queengooborg** [comment]
I think it's safe to close this issue now -- it appears that our data now correctly represents support for the individual options, and was fixed in #12490 during the removal of `api.ScrollToOptions`!
