### ISSUE TITLE
Add <input> element compat data

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#911]
The [HTML compat data ](https://github.com/mdn/browser-compat-data/tree/master/html/elements) is missing `<input>` element compat data.

MDN pages to migrate:

- [ ] [Web/HTML/Element/input](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input)
- [x]  [Web/HTML/Element/input/color](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/color)
- [x] [Web/HTML/Element/input/date](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/data)
- [x] [Web/HTML/Element/input/datetime-local](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local)
- [x] [Web/HTML/Element/input/email](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/email)
- [x] [Web/HTML/Element/input/file](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file)
- [x] [Web/HTML/Element/input/hidden](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/hidden)
- [x] [Web/HTML/Element/input/month](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/month)
- [x] [Web/HTML/Element/input/number](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number)
- [x] [Web/HTML/Element/input/radio](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/radio)
- [x] [Web/HTML/Element/input/range](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range)
- [x] [Web/HTML/Element/input/reset](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/reset)
- [x] [Web/HTML/Element/input/submit](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/submit)
- [x] [Web/HTML/Element/input/tel](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/tel)
- [x] [Web/HTML/Element/input/text](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/tel)
- [x] [Web/HTML/Element/input/url](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/url)
- [x] [Web/HTML/Element/input/week](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/week)
- [x] [Web/HTML/Element/input/button](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/button)
- [x] [Web/HTML/Element/input/checkbox](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox)
- [x] [Web/HTML/Element/input/search](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/search)
- [x] [Web/HTML/Element/input/time](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time)

The data should be stored at `html/elements/input.json `and there will be some deeper nesting involved for the various attributes and input types.

* html.elements.input
  * accept
    * mime_type
    * file_extension
    * ...
  * form
  * list
  * ...
  * type
    * email
    * week
    * ...

See also the [archived input compat table](https://developer.mozilla.org/en-US/docs/Archive/%3Cinput%3E_archive).

For more information on how to help with this work, see https://developer.mozilla.org/en-US/docs/MDN/Contribute/Structures/Compatibility_tables

**Comment by jmswisher** [comment]
Taking this out of the sprint 4 milestone, since it's not being worked on by the core staff team.

**Comment by connorshea** [comment]
All of these have been updated except `range`.

This list is missing a few more which also haven't been updated: `button`, `checkbox`, `search`, and `time`.

**Comment by wbamberg** [comment]
> This list is missing a few more which also haven't been updated: button, checkbox, search, and time.

All these seem to be done now, can we close this?

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#Browser_compatibility

**Comment by Elchi3** [comment]
Looks like so. Thanks Will!
