### ISSUE TITLE
api.Element/api.Node - Review IE 4/5 data

### ISSUE THREAD

**Issue by queengooborg** [mdn/browser-compat-data#9124]
Born from #9068.  @foolip pointed out that in IE 4, you can obtain an `Element` object via `document.forms`.  Based upon this, we should double-check our data for the `Element` and `Node` APIs.

**Comment by foolip** [comment]
Other element collections supposedly supported in IE 4 are `document.anchors`, `document.applets`, `document.embeds`, `document.images` and `document.links`.

Assuming an object that looks like an `Element` or `HTMLElement` can be found via any of these, then checking if `Attr` and `Text` nodes respectively can be found via an `Element` would be nice.

**Comment by queengooborg** [comment]
Closing since IE data is now frozen.
