### ISSUE TITLE
Get rid of WindowOrWorkerGlobalScope without splitting the entries

### ISSUE THREAD

**Issue by foolip** [mdn/browser-compat-data#9127]
Filing an issue for a problem raised in https://github.com/mdn/browser-compat-data/issues/7849#issuecomment-745534078 and https://github.com/mdn/browser-compat-data/issues/8929#issuecomment-773207773.

When getting rid of mixins, the default outcome would be replacing `api.WindowOrWorkerGlobalScope.fetch` with `api.Window.fetch` + `api.WorkerGlobalScope.fetch`, but that doesn't seem great. 

It's an accident of how Web IDL works that the exposure set of interfaces like [`Request`](https://fetch.spec.whatwg.org/#request-class) is defined using `[Exposed=(Window,Worker)]` while the exposure set of methods like [`fetch`](https://fetch.spec.whatwg.org/#fetch-method) is defined using `partial interface mixin WindowOrWorkerGlobalScope`.

I think we should find a common way to represent the worker exposure. Many different approaches could work, but my first suggestion would be `api.WindowOrWorkerGlobalScope.fetch` &rarr; `api.fetch` and working through the many consequences of that.

**Comment by saschanaz** [comment]
Do you intend to file an issue in Web IDL, because it kinda makes sense to me?

**Comment by foolip** [comment]
I hadn't planned on that, no. That would require new syntax for putting methods, attributes and constants on the global object, and I'm not sure what that would look like? I guess something like this?

```webidl
[Exposed=Window]
Promise<Response> fetch(...);
```

Maybe that would be nice?

But I think it need not inform how we deal with this in BCD, it would be changing the syntax of Web IDL but not what the resulting JS environment is like.

**Comment by saschanaz** [comment]
```webidl
[Exposed=Window]
global Promise<Response> fetch(...);
[Exposed=Window]
global attribute Navigator navigator;
```

I guess this form would be easier to read both for machines and humans. But yeah, it's not a blocker for BCD of course.

**Comment by foolip** [comment]
`WindowOrWorkerGlobalScope` is now one of a few remaining mixins in https://github.com/mdn/browser-compat-data/issues/8929.

I still think that we should have a single entry for these things, but I'm not sure if it should be `api.fetch`, `api.builtins.fetch` (like `javascript.builtins.*`) or something else. There's a similar question for the MDN structure.

@ddbeck @Elchi3 do you agree that we should keep single entries here? If it's only a matter of picking the structure, do you have any preferences? I would be happy with almost anything that unblocks https://github.com/mdn/browser-compat-data/issues/8929 :)

**Comment by ddbeck** [comment]
`api.fetch` would be the first thing i would try. I don't think we need to follow the `builtins` example. JS is a bit of a special case, since we also track a bunch of things which aren't in a real namespace (e.g., syntax features).

**Comment by Elchi3** [comment]
In https://github.com/mdn/browser-compat-data/issues/9125#issuecomment-876444294 @teoli2003 proposes to split. What you think about it, @foolip?

**Comment by foolip** [comment]
@Elchi3 that issue is about `WorkerLocation` and `WorkerNavigator` which aren't mixins and I think the solution might be different for those than for `WindowOrWorkerGlobalScope`. I'll comment over there though.

**Comment by Elchi3** [comment]
To understand better what we are trying to achieve here, I opened two draft PRs:

- https://github.com/mdn/browser-compat-data/pull/11517
- https://github.com/mdn/browser-compat-data/pull/11518

The first one (that proposes to split) felt more naturally fitting into BCD to me, but I'm happy to hear feedback. Also, let me know if I misunderstood what exactly was meant by not splitting this mixin.

**Comment by foolip** [comment]
https://github.com/mdn/browser-compat-data/pull/11518 matches what I had in mind, and I like what I'm seeing there. If the MDN pages are also merged, there would be a single place to learn about, for example, `isSecureContext`, and where it can be used. To my eye, it's a good thing that syntax and examples would be pushed in the direction of working in either context, so that developers can copy it regardless of where their code is running.

**Comment by Elchi3** [comment]
Yes, I think the unified approach has benefits for MDN readers. I will work on refining that PR further so we can see how it would go.

Does anyone else have thoughts on how a unified approach would break a bit an exact mapping from Web IDL to BCD paths? Is that a thing people care about?

**Comment by saschanaz** [comment]
>Does anyone else have thoughts on how a unified approach would break a bit an exact mapping from Web IDL to BCD paths? Is that a thing people care about?

It matters in https://github.com/microsoft/TypeScript-DOM-lib-generator. I hope it should be easy enough to remap, but since the mapping is breaking further and further, I'll probably write a new library that represents exact mapping 🤔

**Comment by saschanaz** [comment]
> but since the mapping is breaking further and further, I'll probably write a new library that represents exact mapping 🤔

For anyone interested: I published https://www.npmjs.com/package/bcd-idl-mapper

**Comment by foolip** [comment]
@saschanaz do you have an example of how to use bcd-idl-mapper together with a bunch of IDL and BCD? From the docs it sounds like it's just a BCD-like object, but I'm not quite sure how to use it.

**Comment by saschanaz** [comment]
It's basically same as getting the corresponding data from BCD. Say the wanted item is about `WindowOrWorkerGlobalScope`'s `setTimeout`, it's `(await import("bcd-idl-mapper")).default.__mixins.WindowOrWorkerGlobalScope.setTimeout`.

**Comment by foolip** [comment]
I see, so it seems like bcd-idl-mapper is actually a reorganized version of BCD, I assumed based on the name that it would provide some mapping (IDL to BCD path) and not the BCD data directly. And it seems like as long as BCD still has some mixin data, bcd-idl-mapper is going to be a mix of styles, like `__mixins.WindowOrWorkerGlobalScope.setTimeout` (no `.Window.`) but `__mixins.CanvasDrawImage.drawImage.CanvasRenderingContext2D`.

**Comment by foolip** [comment]
@Elchi3 can you give a post-vacation refresher of the status and plans for this? I favor the approach in https://github.com/mdn/browser-compat-data/pull/11518 and would be happy to do some reviewing work to make it happen, but I'm not sure what it's blocked on.

**Comment by Elchi3** [comment]
I guess we need to make a call which route we want to go:

- https://github.com/mdn/browser-compat-data/pull/11517 or
- https://github.com/mdn/browser-compat-data/pull/11518

It seems like the `_globals` folder has more traction, so we could go down that path. Objections?

**Comment by foolip** [comment]
No objections, strong support! :)

**Comment by Elchi3** [comment]
I believe https://github.com/mdn/content/pull/8351 fixed this.

**Comment by ddbeck** [comment]
> Propose a guideline for when features should be added to `_globals`.

@Elchi3 I still don't think we have docs for when to use globals. Unless I've missed something. I think we should keep this open until it's done.

**Comment by Elchi3** [comment]
Oh yes, sorry. I'm assigning this to @foolip then.

**Comment by foolip** [comment]
I have "Guideline for _globals" written on a piece of paper here, so one day :)

**Comment by queengooborg** [comment]
The guidelines have been added in #12652, so I think it's safe to close this issue now!
