### ISSUE TITLE
Safari 11-14 - Performance.getEntriesByType('navigation') returns always an empty array

### ISSUE THREAD

**Issue by jakub-g** [mdn/browser-compat-data#9128]
https://developer.mozilla.org/en-US/docs/Web/API/Performance/getEntriesByType
#### What information was incorrect, unhelpful, or incomplete?

Incomplete: This states Safari 11 has full support, but it doesn't support all the relevant sub-specs.

#### What did you expect to see?

There should be an additional note and asterisk, saying that `getEntriesByType("navigation")` returns empty array in Safari

#### Did you test this? If so, how?
Yep, in Safari 14 desktop on browserstack

#### Links
https://bugs.webkit.org/show_bug.cgi?id=184363 (looks like it's actively being worked on, hopefully to be shipped in 14.1)

**Comment by ddbeck** [comment]
Thanks for reporting this, @jakub-g.

It's a bit of an odd situation: we have data for each of [the corresponding interfaces](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceEntry/entryType#performance_entry_type_names), but it's not clear to me how we might make the connection between the strings accepted by `getEntriesByType()` to the interfaces that the browser supports.

@Elchi3 maybe you've got an opinion on this?

**Comment by Elchi3** [comment]
Either we introduce sub features here, or we use partial_support and a note for Safari

I guess it depends if we are expecting very different support version for the sub-specs here or if Safari not supporting `navigation` is just an oddity and partial_support captures it well enough.

**Comment by ddbeck** [comment]
Thanks, @Elchi3! That's a very helpful answer.

I did a little more digging into this and found that there's another API, `PerformanceObserver.supportedEntryTypes`, that enumerates the supported strings. Chromium, Firefox, and Safari support it. This suggests to me that it's understood by the API designers that support for all of the specified strings (and underlying interfaces) is unlikely or that they expect the list to change in the future.

Since a few APIs use these strings, I think it'd be extremely helpful for MDN to document how to use `PerformanceObserver.supportedEntryTypes` to feature detect supported types instead of relying solely on the compat table. In other words, I think this is a content problem in disguise. I've opened https://github.com/mdn/content/issues/2667.

That said, we _could_ record this data, but there's at least two methods that use the strings. I'm not sure we ought to record that much duplicate data, especially when an API provides a discovery mechanism.

If there's no objection, I'm inclined to let the content problem be the only problem and close this issue.

**Comment by Elchi3** [comment]
I think I'm fine with making this a content problem, too.

@jakub-g thoughts?

**Comment by jakub-g** [comment]
Hi, thx for investigations!

> I did a little more digging into this and found that there's another API, PerformanceObserver.supportedEntryTypes

Cool finding, I didn't know about that!

> This suggests to me that it's understood by the API designers that support for all of the specified strings (and underlying interfaces) is unlikely or that they expect the list to change in the future.

Yes, that's the thing. For example in Firefox 86 it returns:
`[ "mark", "measure", "navigation", "paint", "resource" ]`

In Chrome 89:
`["element", "event", "first-input", "largest-contentful-paint", "layout-shift", "longtask", "mark", "measure", "navigation", "paint", "resource"]`

The tricky thing is that `PerformaceObserver` is newer and less supported than `performance/getEntriesByType()`; and `PerformanceObserver.supportedEntryTypes` even less (Safari 12.1 only, for example).

Since each version of browser can add more types supported, telling "* partial support" is not a good solution.

What I think could be done is:

1) Update MDN content: https://developer.mozilla.org/en-US/docs/Web/API/Performance/getEntriesByType saying that different browsers support different types of entries and that it's evolving.

2) Optionally: Create sub-features in MDN compat table? WDYT?

I.e. each of those would be a sub-feature:
`["element", "event", "first-input", "largest-contentful-paint", "layout-shift", "longtask", "mark", "measure", "navigation", "paint", "resource"]`

(I can help gathering data on support for each sub-feature if you think it's useful)

**Comment by ddbeck** [comment]
> What I think could be done is:
> 
> 1. Update MDN content: https://developer.mozilla.org/en-US/docs/Web/API/Performance/getEntriesByType saying that different browsers support different types of entries and that it's evolving.

Yes, that's probably a good thing to note in the docs. I've noted your suggestion in https://github.com/mdn/content/issues/2667. 👍

>  2. Optionally: Create sub-features in MDN compat table? WDYT?

OK, I'm somewhat convinced to do this by the argument that the `supportedEntryTypes` property is less well-supported than the APIs which need the strings from that property. Perhaps we could consolidate these subfeatures underneath `PerformanceEntry.entryType` and cross-reference to that set of features from other places that use the string. But that's getting ahead of things a little bit.

First, we need the data. I would very much appreciate your help on this—I doubt this is something I'll have time to get too soon.

For browsers that support `PerformaceObserver.supportedEntryTypes`, it's probably a matter of just getting the results of that property for each successive version and recording the first appearance of each. The only exception would be the strings shown in the earliest version with `supportedEntryTypes`.

For those, it's likely you'd need to write some tests that produce meaningful results. Something which might help with that is something I found writing my previous comment, this spec showing a (complete?) list of entry type strings: https://w3c.github.io/timing-entrytypes-registry/#registry

Let me know if there are any questions about this. Happy to provide assistance, where I can.

**Comment by Elchi3** [comment]
I think we addressed this.
