### ISSUE TITLE
Add compat data for HTML global attributes

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#914]
The [HTML compat data ](https://github.com/mdn/browser-compat-data/tree/master/html/) is missing data for [HTML global attributes](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes).

MDN pages to migrate:

- [x] [Web/HTML/Global_attributes](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes)
- [x] [Web/HTML/Global_attributes/accesskey](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/accesskey)
- [x] [Web/HTML/Global_attributes/class](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/class)
- [x] [Web/HTML/Global_attributes/contextmenu](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/contextmenu)
- [x] [Web/HTML/Global_attributes/data-*](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/data-*)
- [x] [Web/HTML/Global_attributes/dir](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/dir)
- [x] [Web/HTML/Global_attributes/dropzone](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/dropzone)
- [x] [Web/HTML/Global_attributes/hidden](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/hidden)
- [x] [Web/HTML/Global_attributes/itemid](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/itemid)
- [x] [Web/HTML/Global_attributes/itemref](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/itemref)
- [x] [Web/HTML/Global_attributes/itemscope](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/itemscope)
- [x] [Web/HTML/Global_attributes/lang](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang)
- [x] [Web/HTML/Global_attributes/slot](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/slot)
- [x] [Web/HTML/Global_attributes/spellcheck](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/spellcheck)
- [x] [Web/HTML/Global_attributes/style](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/style)
- [x] [Web/HTML/Global_attributes/tabindex](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex)
- [x] [Web/HTML/Global_attributes/title](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title)
- [x] [Web/HTML/Global_attributes/translate](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/translate)

The data should be migrated into `html/global_attributes.json `.
* html.global_attributes.
  * class
  * dir
  * ...

For more information on how to help with this work, see https://developer.mozilla.org/en-US/docs/MDN/Contribute/Structures/Compatibility_tables

**Comment by frittate** [comment]
I'd like to give this a try!

**Comment by frittate** [comment]
https://github.com/mdn/browser-compat-data/pull/1089
