### ISSUE TITLE
css.properties.caret-color - iOS Safari does not support this correctly

### ISSUE THREAD

**Issue by djadu** [mdn/browser-compat-data#9142]
#### What information was incorrect, unhelpful, or incomplete?
When testing the caret-color css on iOS Safari (14.2) the caret color does not change as expected, so it is not correctly supported by this browser.

#### What did you expect to see?
In both the CSS Demo and Examples sections, when you select an input that has a custom color set, the caret color should reflect that.

#### Did you test this? If so, how?
Tested on iOS 14.2 Safari:
- Go to the Examples section near the bottom of the page.
- Tap in the first input field that uses the default caret: caret is blue
- Tap in the second input field with a custom caret color of red: caret is blue
- Tap in the paragraph with a custom caret color of green: caret is red
- Tap in the first input field that uses the default caret: caret is green

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.caret-color`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/caret-color
* Report started: 2021-02-16T17:05:24.086Z

</details>

**Comment by ddbeck** [comment]
Hi @djadu, thanks for reporting this.

Did you happen to test this on a physical Apple device or did you use a simulator or testing service such as BrowserStack? The reason I ask is because while I could reproduce this problem in BrowserStack and in the Apple simulator, I couldn't do so consistently. I wonder if it has something to do with the physical interaction itself.

**Comment by djadu** [comment]
Hi @ddbeck I tested this on physical MacBook and iPhone devices. It was reproducible on both consistently

**Comment by ddbeck** [comment]
Thanks, @djadu. That's helpful. Here's what I think should happen next.

Based on the still-open status of [WebKit bug 177489](https://bugs.webkit.org/show_bug.cgi?id=177489), I think the right way to present this would be to mark Safari on iOS as partial, with a note that links to the bug. I'm not sure how to describe this in a note, however. Here's my first attempt:

> While the property is recognized, implementation is incomplete. The color of the caret does not always match the color set for the element in focus. See [bug 177489](https://bugs.webkit.org/show_bug.cgi?id=177489).

Do you think that adequately describes the situation on iOS?

**Comment by djadu** [comment]
Thanks @ddbeck, that sounds good.

**Comment by ddbeck** [comment]
Opened #9251 to fix this. Thanks!
