### ISSUE TITLE
api.GlobalEventHandlers.onselectstart - onselectstart not called on iOS

### ISSUE THREAD

**Issue by otacke** [mdn/browser-compat-data#9144]
#### What information was incorrect, unhelpful, or incomplete?

- The table lists iOS among the devices supporting the `onselectstart` handler. `onselectstart` does not to be supported by iOS 12 at least.
- That behavior seems to be known at least since 2016, cmp. https://gist.github.com/robertknight/ad9f1bca8280b3fa325817aa3ed9935c, so other iOS versions are likely to be affected, too. 

- CanIUse lists iOS 14 as minimum version, see https://caniuse.com/?search=onselectstart

#### What did you expect to see?
I expected the `onselectstart` handler to be called when starting to select text.

#### Did you test this? If so, how?
Yes. I used https://codepen.io/otacke/pen/wvodWBo to verify that the `onselectstart` handler is in fact not called.

<details>
<summary>MDN page report details</summary>

* Query: `api.Document.selectstart_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document/selectstart_event
* Report started: 2021-02-16T19:32:09.578Z

</details>

**Comment by ddbeck** [comment]
Hi @toacke and thanks for raising this issue and the related #9143. Apparently `selectstart` has [a number](https://github.com/w3c/selection-api/issues/53) of [issues associated with it](https://bugs.webkit.org/showdependencytree.cgi?id=60424&hide_resolved=0).

A quick test shows that `onselectstart` does exist in the interface (e.g., `"onselectstart" in document` is `true`) but if it never fires fire, that's a bit misleading. I propose that we mark the feature as supported with a `partial_implementation` set to `true` and a note saying, "The `selectstart` event never fires and never invokes this handler."

To fix this, these need to be updated:

- `onselectstart` (partial implementation) in https://github.com/mdn/browser-compat-data/blob/e07c447ba01fd6fef734ab88cf40ba8ff55ce517/api/Document.json#L10758
- `onselectstart` (partial implementation) in https://github.com/mdn/browser-compat-data/blob/ee47fa52c6e57dd06b40a0e8f9aa072176226ab1/api/GlobalEventHandlers.json#L4155
- `selectstart` (`"version_added": false`) https://github.com/mdn/browser-compat-data/blob/e07c447ba01fd6fef734ab88cf40ba8ff55ce517/api/Document.json#L10758

I would welcome a PR from you (or another contributor) making these changes.

Thank you again!

(I'll duplicate this comment on the other issue, though this is not, strictly speaking, a duplicate.)

**Comment by otacke** [comment]
@ddbeck Thanks for taking your time to verify the issue (and correct my observation). I have created a pull request at https://github.com/mdn/browser-compat-data/pull/9256
