### ISSUE TITLE
javascript.operators.optional_chaining - Samsung Internet supports it

### ISSUE THREAD

**Issue by saschanaz** [mdn/browser-compat-data#9146]
#### What information was incorrect, unhelpful, or incomplete?

Samsung Internet supports optional chaining but BCD doesn't say so

#### What did you expect to see?

A supported version (probably 13.0)

#### Did you test this? If so, how?

https://kangax.github.io/compat-table/es2016plus/

#### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://github.com/mdn/browser-compat-data/blob/5c9fce3086e91e9994ce8e8b37791c34512718e9/javascript/operators/optional_chaining.json#L91-L93

**Comment by ddbeck** [comment]
Thanks for opening this, @saschanaz. I opened #9233 to fix this.
