### ISSUE TITLE
Mention latest browser version in compatibility table 

### ISSUE THREAD

**Issue by pm-harshad-mane** [mdn/browser-compat-data#9155]
#### What information was incorrect, unhelpful, or incomplete?
In the compatibility tables we see the browser version from which a particular API became available.

#### What did you expect to see?
Along with current browser version details, it will be very helpful to see
- what is the latest version of the browser, this can be mentioned with the browser name
- What is the current market share of the browser version mentioned
This information gives better understanding whether an API is widely available in the live browser market.

#### Did you test this? If so, how?
Nope.

<details>
<summary>MDN page report details</summary>

* Query: `javascript.operators.await`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await
* Report started: 2021-02-17T19:16:19.160Z

</details>

**Comment by pm-harshad-mane** [comment]
Something like https://caniuse.com/?search=await :-)

**Comment by mattiapontonio** [comment]
This repository does not manage the table, it only manages the data.
[This](https://github.com/mdn/yari) repository manages the table and doesn't manage as far as I know [these kind of JSON](https://www.github.com/mdn/browser-compat-data/tree/master/browsers%2Ffirefox.json) in which there is an object with a list of properties which are the releases.

**Comment by vinyldarkscratch** [comment]
Thanks for opening an issue @pm-harshad-mane.  This repository is explicitly for the table _content,_ rather than the table _display._  I found an issue on the appropriate repository that discusses this, see https://github.com/mdn/yari/issues/1400.
