### ISSUE TITLE
css.selectors.focus-visible - supported in Edge

### ISSUE THREAD

**Issue by liesahead** [mdn/browser-compat-data#9167]
#### What information was incorrect, unhelpful, or incomplete?
The new versions of edge support `focus-visible` (I tested it myself and caniuse.com also states the same)

![image](https://user-images.githubusercontent.com/32300784/108326114-87c77a00-71d2-11eb-8ec7-cf0445b64541.png)
![image](https://user-images.githubusercontent.com/32300784/108326275-bba29f80-71d2-11eb-8076-a3cd80a56fad.png)

#### Did you test this? If so, how?
Opened MDN `focus-visible` page and tested it in edge.

<details>
<summary>MDN page report details</summary>

* Query: `css.selectors.focus-visible`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible
* Report started: 2021-02-17T11:58:40.179Z

</details>

**Comment by ddbeck** [comment]
Hi @liesahead and thanks for raising this issue.

It does appear that this data is out of data.

To fix this, the Edge data in [`focus-visible.json`](https://github.com/mdn/browser-compat-data/blob/f5417741503d02a893039fe06f0d8b4f6b4d9c24/css/selectors/focus-visible.json#L4) needs to be updated to reflect (it'll match the data for Chrome, in this case).

I would welcome a PR from you (or another contributor) making these changes.

Thank you again!

**Comment by ddbeck** [comment]
Fixed by #9345! 🎉
