### ISSUE TITLE
css.at-rules.media.prefers-color-scheme - Firefox Android

### ISSUE THREAD

**Issue by Leptopoda** [mdn/browser-compat-data#9171]
#### What information was incorrect, unhelpful, or incomplete?
prefers-color-scheme is listed as not supported on android mobile
#### What did you expect to see?
It being listed as supported
#### Did you test this? If so, how?
using a simple 
```
@media (prefers-color-scheme: dark) {
    body { color: #eee; background: #121212; }
}
```
does work on FF android (probably since fenix got released but I'm not shure)

<details>
<summary>MDN page report details</summary>

* Query: `css.at-rules.media.prefers-color-scheme`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme
* Report started: 2021-02-18T12:36:25.428Z

</details>

**Comment by filiptronicek** [comment]
Tested on the Samsung Galaxy S20, works as expected
![image](https://user-images.githubusercontent.com/29888641/108489384-cc6e1680-72a1-11eb-8b99-5d3457bb855a.png)

**Comment by Leptopoda** [comment]
ok I just got back to this and it seemed to be a bit odd that firefox android 67 (fennec) supported `no-preference` but didn't support `prefers-color-scheme`
so I grabbed 67.0.3 from apk-mirror and it seems like `prefers-color-scheme` was already supported back then (you an see the css snippet I use in my first post)

do you know anything more specific about this?
