### ISSUE TITLE
html.elements.head - <asmashiekh-naat>

### ISSUE THREAD

**Issue by niceali** [mdn/browser-compat-data#9177]
#### Did you test this? If so, how?

<details>
<summary>MDN page report details</summary>

* Query: `html.elements.head`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/head
* Report started: 2021-02-18T10:06:17.079Z

</details>

**Comment by vinyldarkscratch** [comment]
Closing due to lack of details.  If there's an issue with the compatibility data, please explain what the issue is and we'll be happy to resolve it!
