### ISSUE TITLE
javascript.builtins.String.matchAll - Supported in Samsung Internet

### ISSUE THREAD

**Issue by Amarok24** [mdn/browser-compat-data#9196]
#### What information was incorrect, unhelpful, or incomplete?
The table with overview of supported browsers says that Samsung Internet Browser does _not_support the matchAll method. 

#### What did you expect to see?
I expected to see a broken test result on my testpage where I used matchAll( )

#### Did you test this? If so, how?
Samsung Internet Browser version 13.2.2.4 on Android version 8.0.0

<details>
<summary>MDN page report details</summary>

* Query: `javascript.builtins.String.matchAll`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/matchAll
* Report started: 2021-02-19T14:06:43.287Z

</details>

**Comment by ddbeck** [comment]
Thanks for reporting this, @Amarok24. I've opened #9465 to resolve.
