### ISSUE TITLE
api.DataTransfer.items - Safari information incorrect, Safari has full support

### ISSUE THREAD

**Issue by ienzam** [mdn/browser-compat-data#9200]
#### What information was incorrect, unhelpful, or incomplete?

Browser compatibility > Safari 

#### What did you expect to see?

Full support

#### Did you test this? If so, how?

Tested in a Safari browser.

Browser version: 14.0.2

http://whatismybrowser.com/w/HJ66Q9Q

<details>
<summary>MDN page report details</summary>

* Query: `api.DataTransfer.items`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/items
* Report started: 2021-02-20T09:50:56.808Z

</details>

**Comment by ddbeck** [comment]
Thanks for reporting this, @ienzam. I've opened #9467 to fix this.
