### ISSUE TITLE
api.DataTransferItemList.add - Incorrect compatibility data for Microsoft Edge

### ISSUE THREAD

**Issue by MobButcher** [mdn/browser-compat-data#9211]
#### What information was incorrect, unhelpful, or incomplete?
DataTransferItemList.add() compatibility data showing that it is supported from MS Edge 12 to 79.

#### What did you expect to see?
Just 12, with it being still compatible to this day.

#### Did you test this? If so, how?
Yes, I did test this with current settings:
Windows 7 x64
Microsoft Edge version 88.0.705.74 (Official build) (64-bit)
I used the demonstration on the official MDN website and observed the same behavior compared to Chrome Dev version 90.0.4421.5 (Official Build) dev (64-bit): the drag-and-drop still worked, DevTools console still logged all of the strings into the console, and the object was successfully rendered and moved the way it was supposed to.

<details>
<summary>MDN page report details</summary>

* Query: `api.DataTransferItemList.add`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/DataTransferItemList/add
* Report started: 2021-02-21T22:16:05.288Z

</details>

**Comment by ddbeck** [comment]
Good discovery, @MobButcher!

It looks like the original data was part of a bulk update that picked up some out-of-date data and this feature was updated along with the rest of it. I can also replicate the test described above. 👍

**Comment by ddbeck** [comment]
#9212 fixes this. 🎉
