### ISSUE TITLE
html.elements.datalist - event key codes comes out undefined

### ISSUE THREAD

**Issue by Kodatham** [mdn/browser-compat-data#9217]
Input element with datalist: on arrow keys up or down, onkeyup or onkeydown never detects the arrow keys and the event keycodes always comes as undefined.

In Mozilla firefox, arrow keys are detected. However, does not have onkeyup or onchange events are not aligned as Chrome.

<details>
<summary>MDN page report details</summary>

* Query: `html.elements.datalist`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist
* Report started: 2021-02-22T02:58:50.602Z

</details>

**Comment by ddbeck** [comment]
Hi @Kodatham. A few questions for you:

* Testing: How did you test this? What versions of Chrome and Firefox did you use? What did you expect to happen in each browser? What was the outcome of the test in each browser?
* What did you expect the compatibility table to tell you about the difference between the browsers?
* Can you share any links to bugs, documentation, or other material which may have been helpful for you while investigating this issue?

---

A look on my own suggests that key events for datalist is currently undefined behavior in the relevant specifications: https://github.com/whatwg/html/issues/2605

**Comment by jculver050** [comment]
Close

**Comment by queengooborg** [comment]
I'm going to go ahead and close this issue, since there has been no response and more info is needed to proceed.  If this is still an issue, please reply to this thread with the requested information and I'll be happy to reopen this!
