### ISSUE TITLE
html.elements.a - Ping attribute supported by Safari

### ISSUE THREAD

**Issue by nicholas-l** [mdn/browser-compat-data#9219]
#### What information was incorrect, unhelpful, or incomplete?

The compatibility data states that Safari does not support the `ping` attribute on anchor tags. The `ping` attribute seems to be supported by Safari according to https://caniuse.com/ping and when I created a small test locally.

#### What did you expect to see?

Safari to be supported instead it says No.

#### Did you test this? If so, how?

1. Added an anchor tag with `ping` attribute
2. Clicked on it in Safari (v14.0.3)
3. Checked network tab in Web Inspector, shows network request to ping url.

<details>
<summary>MDN page report details</summary>

* Query: `html.elements.a`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a
* Report started: 2021-02-22T09:27:05.147Z

</details>

**Comment by ddbeck** [comment]
Thanks for reporting this, @nicholas-l. I've confirmed that this is true and opened #9470 to fix it.
