### ISSUE TITLE
Issues with `fs` library

### ISSUE THREAD

**Issue by chrisopedia** [mdn/browser-compat-data#923]
Attempted to add this lib to a tool I was building and I'm getting an error such as: `Error: Can't resolve 'fs'`.

I tried recreating it on a REPL and got a different error with `fs`: https://repl.it/@chrisopedia/DarkkhakiWingedDragonfly

**Comment by jpmedley** [comment]
This is the [node File System](https://nodejs.org/api/fs.html) module. So at a command line:

`npm install fs`

**Comment by chrisopedia** [comment]
Yeah, did that, although not sure why you'd have to, but it still came up with the same error.

**Comment by Elchi3** [comment]
I'm unclear what we should be doing about this. 
The repl.it REPL says "Native Browser JavaScript", but this is project a nodejs/npm package, so it uses the nodejs file system. Are you suggesting this package should also be available as package outside of node? Maybe use webpack or similar?
