### ISSUE TITLE
api.PushEvent - Edge compatibility

### ISSUE THREAD

**Issue by tcitworld** [mdn/browser-compat-data#9234]
#### What information was incorrect, unhelpful, or incomplete?

Edge information about PushEvent's compatibility is *probably* outdated since Edge is now based on Blink.

#### What did you expect to see?

Edge 16 replaced by Edge 79.

#### Did you test this? If so, how?

Didn't test.

<details>
<summary>MDN page report details</summary>

* Query: `api.PushEvent`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Push_API
* Report started: 2021-02-23T19:06:59.848Z

</details>

**Comment by ddbeck** [comment]
Thanks for reporting this, @tcitworld. It turns out that the data we had was sorted incorrectly, hiding the fact that the `PushEvent` features are in fact supported in Edge (since before Blink, even). I've opened #9483 to fix this. Thank you again!
