### ISSUE TITLE
api.Node.appendChild - <in chrome it is not werking for me>

### ISSUE THREAD

**Issue by noamloev** [mdn/browser-compat-data#9237]
#### Did you test this? If so, how?

<details>
<summary>MDN page report details</summary>

* Query: `api.Node.appendChild`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Node/appendChild
* Report started: 2021-02-23T20:11:59.453Z

</details>

**Comment by ddbeck** [comment]
This issue was closed because it appears to be empty. The issue is not different from the issue template and no actionable information has been provided. If this has been closed in error, edit the title and body, and post a follow-up comment.
