### ISSUE TITLE
api.Navigator.share - Firefox for Android doesn't support Text, either

### ISSUE THREAD

**Issue by MisterY** [mdn/browser-compat-data#9252]
#### What information was incorrect, unhelpful, or incomplete?

The article notes that Firefox for Android does not support sharing files.

#### What did you expect to see?

The article should also state that sharing Text is also not supported.

#### Did you test this? If so, how?

Added `navigator.share({ title: 'title', text: 'text' })` to a page server over HTTPS and clicked the button.
Only the title gets through, whether the destination is a file manager or a chat application.

<details>
<summary>MDN page report details</summary>

* Query: `api.Navigator.share`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share
* Report started: 2021-02-24T16:21:40.537Z

</details>

**Comment by saschanaz** [comment]
Confirmed: https://github.com/mozilla-mobile/fenix/issues/11946

**Comment by ddbeck** [comment]
In that case, would it be correct to report that Firefox for Android only supports sharing URLs?

**Comment by saschanaz** [comment]
It does share the title even when the issue claims it doesn't. Maybe it changed the behavior later.

**Comment by ddbeck** [comment]
OK, let's only mention the text and files then. I've opened #9392 to fix this.
