### ISSUE TITLE
api.RTCRtpTransceiver.stop - it's in chrome 88

### ISSUE THREAD

**Issue by hoodie** [mdn/browser-compat-data#9253]
#### What information was incorrect, unhelpful, or incomplete?

[`RTCRtpTransceiver.stop`](https://developer.mozilla.org/en-US/docs/Web/API/RTCRtpTransceiver/stop)

#### What did you expect to see?

`Transceiver.stop` is mentioned to not work on chrome, but it has actually been [added in chrome 88](https://www.chromestatus.com/feature/5410592384876544)

#### Did you test this? If so, how?

no sorry

<details>
<summary>MDN page report details</summary>

* Query: `api.RTCRtpTransceiver.stop`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/RTCRtpTransceiver/stop
* Report started: 2021-02-24T17:31:36.242Z

</details>

**Comment by ddbeck** [comment]
Thanks for reporting this issue, @hoodie. I've opened #9255 to fix this.
