### ISSUE TITLE
css.properties.overflow - Chrome support version wrong (89 -> 90)

### ISSUE THREAD

**Issue by gptt916** [mdn/browser-compat-data#9258]
#### What information was incorrect, unhelpful, or incomplete?
Chrome browser support version
Previously added in https://github.com/mdn/browser-compat-data/pull/8803, however looks like Chrome delayed release to v90
#### What did you expect to see?
90
#### Did you test this? If so, how?
https://www.chromestatus.com/feature/5638444178997248

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.overflow`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/overflow
* Report started: 2021-02-24T20:11:46.766Z

</details>

**Comment by ddbeck** [comment]
Fixed by #9259.
