### ISSUE TITLE
api.ResizeObserver - Show Full Support in Firefox for Android 85

### ISSUE THREAD

**Issue by depthdev** [mdn/browser-compat-data#9261]
#### What information was incorrect, unhelpful, or incomplete?

Firefox for Android v85 supports all of the ResizeObserver API

#### What did you expect to see?

Currently the data on MDN shows it's not supported.

#### Did you test this? If so, how?

I used the API online via Firefox for Android and checked for all of its methods using version 85.  I also successfully ran the code in strict mode without error or warning.

<details>
<summary>MDN page report details</summary>

* Query: `api.ResizeObserver`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver
* Report started: 2021-02-25T01:00:52.592Z

</details>

**Comment by lucalves** [comment]
Hello @depthdev, I opened a PR to solve this.

However, I'm not sure if any functionality was present in any version before v85.

Anyway, let's wait for the review :)
