### ISSUE TITLE
String.prototype.replaceAll() - UC Browser does NOT support it

### ISSUE THREAD

**Issue by No5972** [mdn/browser-compat-data#9262]
#### What information was incorrect, unhelpful, or incomplete?
Missing - UC Browser does NOT implement this feature.
#### What did you expect to see?
All corresponding parts of the string can be replaced.
#### Did you test this? If so, how?
* UC Browser Mobile International Version V13.3.2.1303
* Visit [https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll)
And run the JavaScript Demo
```Error: p.replaceAll is not a function```

#### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?
[https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll)

**Comment by vinyldarkscratch** [comment]
Due to a lack of maintainer support for UC Browser, we've decided to drop their data from BCD, see https://github.com/mdn/browser-compat-data/pull/7240.  As a result, we're not tracking data for UC Browser any longer.
