### ISSUE TITLE
http.headers.Feature-Policy - Firefox doesn't support the Feature-Policy header

### ISSUE THREAD

**Issue by evilpie** [mdn/browser-compat-data#9264]
The Feature-Policy header was only ever enabled on Nightly for a short period? I think roughly 74-77.

#### What information was incorrect, unhelpful, or incomplete?
Marked as supported.

#### What did you expect to see?
Marked as behind pref.

#### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?
https://bugzilla.mozilla.org/show_bug.cgi?id=1627890

**Comment by evilpie** [comment]
It's probably also good to note that Feature-Policy has been renamed to Permissions-Policy in the spec: https://w3c.github.io/webappsec-permissions-policy/#permissions-policy-http-header-field

**Comment by hamishwillee** [comment]
Thanks. Done in #9280
