### ISSUE TITLE
api.BeforeInstallPromptEvent - not is called in mobile chrome

### ISSUE THREAD

**Issue by Thiago-bs** [mdn/browser-compat-data#9266]
I completely configured the PWA, even performed tests on the chrome desktop and it is working normally, but the BeforeInstallPromptEvent method is not being called when accessing via mobile chrome.

I dont have a log, just not called on chrome mobile
My code :

```js
var deferredPrompt;

window.addEventListener('beforeinstallprompt', (e) => {
		e.preventDefault();
		deferredPrompt = e;

});
```

**Comment by ddbeck** [comment]
Hi @Thiago-bs and thanks for opening this issue. Unfortunately, you haven't provided enough information to determine what compatibility data you're having trouble with (alternatively, if you're looking for general web development help, this repository unable to provide that help).

To move further on this, I'd recommend either using the "Report problems with this compatibility data on GitHub" link from the MDN page where you're having trouble or start a new issue using [the data problem template](https://github.com/mdn/browser-compat-data/issues/new/choose). Either way, please answer all of the questions and leave any automatically generated text in place.

Thank you!
