### ISSUE TITLE
api.Window.close - Add not for IE11

### ISSUE THREAD

**Issue by Termiux** [mdn/browser-compat-data#9270]
Tested on Internet Explorer 11, Edge 84 and Edge 88 (Chromium based)

Add a note on implementation that Internet Explorer 11 continues to disregard the security functionality and will close a window regardless of if was opened by a script via `window.open`

Consider adding a note (asteriks) on the section to show IE will still close the window

#### Simple test

```
<html>
<body>
	<h1>Test</h1>
	<a href="javascript: window.close();">Click to Close</a>
</body>
</html>
```

Ran on IE 11, Edge 84 and Edge 88 Chromium, before the Chromium switch edge will exhibit the same behavior as Internet Explorer 11

<details>
<summary>MDN page report details</summary>

* Query: `api.Window.close`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/close
* Report started: 2021-02-25T15:56:24.413Z

</details>

**Comment by ddbeck** [comment]
Thanks for reporting this, @Termiux. I've opened #9492 to fix this.
