### ISSUE TITLE
api.Notification - Functions in Chrome Android

### ISSUE THREAD

**Issue by MIhailsPopovs** [mdn/browser-compat-data#9273]
#### I've integrated Notification API in a web app I'm building and it works fine. (Tested on Android v11, Android Chrome v88.0.4324.181 )

<details>
<summary>MDN page report details</summary>

* Query: `api.Notification`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/notification
* Report started: 2021-02-25T19:20:31.259Z

</details>

**Comment by ddbeck** [comment]
Thanks for reporting this, @MIhailsPopovs. This is a known problem with the `Notification` data. See https://github.com/mdn/browser-compat-data/issues/7923#issuecomment-778359481 for more information on what needs to be done to fix this. I'll be closing this issue a duplicate. Thank you again!
