### ISSUE TITLE
html.elements.meta.name.theme-color - Browser compatibility outdated

### ISSUE THREAD

**Issue by jdabtieu** [mdn/browser-compat-data#9282]
Currently on Desktop Microsoft Edge 88.

#### What information was incorrect, unhelpful, or incomplete?
In the browser compatibility section, Edge is listed as not supporting the theme-color meta property, but the latest version of Edge (88) does in progressive web apps.

#### What did you expect to see?
I expected setting a theme-color property to not change the appearance of a PWA since MDN docs says that Microsoft Edge doesn't support theme-color, but it did change the window color.

#### Did you test this? If so, how?
Here are two versions of a site. The one on the left has `<meta name="theme-color" content="#0d6efd">` and the one one the right does not have a theme-color property set. It appears to be using the dominant color of the favicon by default.

![image](https://user-images.githubusercontent.com/62577178/109259290-e63fba00-77c9-11eb-99b9-e3dad627a597.png)

<details>
<summary>MDN page report details</summary>

* Query: `html.elements.meta.name.theme-color`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name/theme-color
* Report started: 2021-02-26T05:22:22.678Z

</details>

**Comment by ddbeck** [comment]
Thanks for reporting this, @jdabtieu. I've opened #9494 to fix it, among other problems with the data there.
