### ISSUE TITLE
api.MediaRecorder - supported under iOS 14.3

### ISSUE THREAD

**Issue by mvdpwork** [mdn/browser-compat-data#9283]
#### What information was incorrect, unhelpful, or incomplete?
In the latest Safari 14.0.3  (for iOS and also MacOS Catalina, there is MediaRecorder Support.
And it's working fine. See also:
https://webkit.org/blog/11353/mediarecorder-api/

#### What did you expect to see?
Nothing. I was expecting it didn't work, under Safari, but it did. :-)

#### Did you test this? If so, how?
I was adapting the MDN example of WebDictaphone. https://github.com/mdn/web-dictaphone
for my 'own' application and it's using MediaRecorder all over the place. 

Two things you have to adapt to the WebDictaphone code;
 - remove or adapt the visualizer from that code,  it is working. Because pure WebAudio is still not fully supported, the visualizer in that application is not working alright, but that's something else.
 - change the blobtype to apples favourite: 

 ```
const blob = new Blob(chunks, { 'type': 'audio/mp4' });
```

I tested it on an 'old' iPad air, an iPhone 6S both updated to iOS 14.3, and under MacOS Catalina, Safari 14.0.3 and it worked!
In earlier versions I had to go into Development mode and turn on the 'MediaRecorder support option. But now now.

<details>
<summary>MDN page report details</summary>

* Query: `api.MediaRecorder`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder
* Report started: 2021-02-26T15:53:59.800Z

</details>

**Comment by ddbeck** [comment]
Thanks for reporting this, @mvdpwork! This has fixed by https://github.com/mdn/browser-compat-data/pull/8838.
