### ISSUE TITLE
api.Path2D.Path2D - Edge now supports string consisting of SVG path data

### ISSUE THREAD

**Issue by hoomanaskari** [mdn/browser-compat-data#9291]
Since Edge browser is now Chromium based, it now supports 'string consisting of SVG path data'.
This makes the feature fully available in all major browsers (and who cares about IE anymore?)
It's time to finally take the 'Experimental' flag off of this feature.

**Comment by ddbeck** [comment]
Thanks for reporting this, @hoomanaskari. I've opened https://github.com/mdn/browser-compat-data/pull/9495 to fix it.
