### ISSUE TITLE
HTTP > Content Length : Added to safelisted response header in specific versions

### ISSUE THREAD

**Issue by hamishwillee** [mdn/browser-compat-data#9300]
The [Content-Length](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Length#browser_compatibility) HTTP response header got added to the [CORS safelisted response headers](https://developer.mozilla.org/en-US/docs/Glossary/CORS-safelisted_response_header)  in a [late revision to the spec](https://github.com/whatwg/fetch/pull/626). 

- This was just added to FF list in FF87 - https://bugzilla.mozilla.org/show_bug.cgi?id=1460299
- was added to "non Blink Edge" but the info on version is now hidden behind a broken link to the original bug https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/17440391/
- Added to Safari/Webkit https://bugs.webkit.org/show_bug.cgi?id=185473
- Chrome  - can't find any mention. 

So the question is, "what is the best way to add this to BCD". My thought was as a subfeature "cors_response_safelist" with FF87 and Safari added (either with version if I can find it or true, the rest null).  Is that reasonable?

Who can we ask about Chrome/Blink? 

@ddbeck Advice appreciated please.

**Comment by ddbeck** [comment]
> * Chrome  - can't find any mention.

For Chrome, I found this: https://storage.googleapis.com/chromium-find-releases-static/5e9.html#5e97971dd8d45819d5758b2a5fd53ebdce7e7138

> So the question is, "what is the best way to add this to BCD". My thought was as a subfeature "cors_response_safelist" with FF87 and Safari added (either with version if I can find it or true, the rest null). Is that reasonable?

Do you mean a subfeature of `http.headers.Access-Control-Expose-Headers` or some other feature?

**Comment by ddbeck** [comment]
> * as added to "non Blink Edge" but the info on version is now hidden behind a broken link to the original bug https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/17440391/

Oh and this one I wasn't able to sort out. A shame Microsoft took that site offline. Ideally, a test case that we could run on old versions in BrowserStack or SauceLabs would settle it. If that's too much hassle, `≤79` would be satisfactory.

**Comment by hamishwillee** [comment]
> Do you mean a subfeature of http.headers.Access-Control-Expose-Headers or some other feature?

My thinking was to add it as a subfeature of Content-Length. But probably it should be added to all of the safelisted headers: Cache-Control, Content-Language, Content-Length, Content-Type, Expires, Last-Modified, Pragma.

Currently the information is in a table at the top of pages, but would not hurt for it to be in BCD, especially now this is a compatibility thing.

![image](https://user-images.githubusercontent.com/5368500/110401020-e3e43680-80cc-11eb-9332-c2c92e223da3.png)

**Comment by ddbeck** [comment]
OK. That makes sense. I'd welcome a PR that does this for one or two of the headers, so we can see what it looks like before filling them out for every single one.

**Comment by hamishwillee** [comment]
Excellent. Test case in #9456
