### ISSUE TITLE
javascript.builtins.String.replace - $<name> not listed in compatibility table

### ISSUE THREAD

**Issue by jho1965us** [mdn/browser-compat-data#9307]
#### What information was incorrect, unhelpful, or incomplete?

section "Specifying a string as a parameter" at the very end says "Only available in browser versions supporting named capturing groups." about $<name> but the compatibility table do not list which version support $<name>

#### What did you expect to see?

the compatibility table should list which version support $<name>

#### Did you test this? If so, how?

<details>
<summary>MDN page report details</summary>

* Query: `javascript.builtins.String.replace`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace
* Report started: 2021-03-01T19:00:17.837Z

</details>

**Comment by ddbeck** [comment]
Thanks for reporting this, @jho1965us. This data is reported as [a "Named capture groups" subfeature of `RegExp`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp). Unfortunately, many methods rely on RegExp features, but there's not yet a way to inline additional compat data across different APIs. We'll keep this in mind (it's come up several other places), but, for now, there's nothing more I can do here. Thanks for your understanding.
