### ISSUE TITLE
Issue with "Response": Response.ok seems to be defined for Chrome and Firefox on Android

### ISSUE THREAD

**Issue by BjornMoren** [mdn/browser-compat-data#9309]
#### What information was incorrect, unhelpful, or incomplete?

The docs say Response.ok is not defined for Chrome and Firefox on Android. Some tests indicate otherwise. Please respond to this thread with the correct information so I know if I can use it in my code.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/response`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Response
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/response/index.html
* Last commit: https://github.com/mdn/content/commit/da644b35271bf64b2ffec0472d2dd883eb962769
* Document last modified: 2021-02-24T03:30:04.000Z

</details>

**Comment by ddbeck** [comment]
Thanks for opening this issue, @BjornMoren.

It looks like the data for `api.Response.ok` is quite old, being more or less unchanged when it was migrated from the wiki: https://github.com/mdn/browser-compat-data/blob/2084025a3264621792d82cc5f76f397bf9727335/api/Response.json#L548

I think this is a case where we could safely mirror from desktop Chrome and Firefox to resolve this issue. I've opened #9335 to do that.

**Comment by BjornMoren** [comment]
Thanks @ddbeck, that made coding much easier!

**Comment by jdom** [comment]
what about `Response.status`? Is that supported in Chrome/Firefox for Android? I didn't confirm, just read about it in caniuse.com, but we'd have had tons of errors if this wasn't working.
