### ISSUE TITLE
svg.attributes.presentation.color  There is no browser compatibility data

### ISSUE THREAD

**Issue by adijha** [mdn/browser-compat-data#9316]
#### Did you test this? If so, how?

<details>
<summary>MDN page report details</summary>

* Query: `svg.attributes.presentation.color`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/color
* Report started: 2021-03-02T18:32:21.436Z

</details>

**Comment by ddbeck** [comment]
I'm closing this issue because it appears to be empty. The issue template is incomplete and no actionable information has been provided.

If this has been closed in error, edit the title and body, and post a follow-up comment.
