### ISSUE TITLE
api.CanvasRenderingContext2D.isPointInPath - Wrong Safari support info

### ISSUE THREAD

**Issue by ramhugger** [mdn/browser-compat-data#9328]
#### System info:

| Browser | Version |          OS          | OS Arch |
|:-------:|:-------:|:--------------------:|:-------:|
|  Safari |  14.0.3 | MacOS Big Sur 11.2.2 |   ARM   |

#### The information was incorrect

<img width="628" alt="MDN Support Table (incorrect)" src="https://user-images.githubusercontent.com/37934707/109939417-5326e880-7cd1-11eb-8a4f-0ac72c605b3c.png">

The documentation page in question claims that Safari does not support the method `CanvasRenderingContext2D.isPointInPath()` with the following syntax:

```js
ctx.isPointInPath(path, x, y [, fillRule]);
```

#### How I tested this

After I had a look at the compatibility table which is online right now, I thought it was pretty weird for a browser like Safari not being featuring such a simple method for such a widely used Web API.
I tried then to call `isPointInPath()` using the ~unsupported~ syntax.
I'm sure you already guessed that it worked like a charm.

After that test I went to read the official Safari documentation at [developer.apple.com](https://developer.apple.com).
Their parameters list doesn't say anything about the second syntax of this method, but it can be found in the method declaration; like this:

<img width="967" alt="Apple Developer documentation (should be right...?)" src="https://user-images.githubusercontent.com/37934707/109940811-c2510c80-7cd2-11eb-9d42-716a082a04b8.png">

I don't know which one is supposed be the correct one, and I don't know why all the other tables I could find about this method in Safari do not mention clearly the second syntax, but what I know is that it works without any issue and that it seems to be fully supported.

Because of the reasons discussed above, I think that Safari's support status for

> Path parameter

should be changed to **Full support** since **v10.0**.

<details>
<summary>MDN page report details</summary>

* Query: `api.CanvasRenderingContext2D.isPointInPath`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/isPointInPath
* Report started: 2021-03-04T08:44:31.172Z

</details>

**Comment by ddbeck** [comment]
Fixed by #9427
