### ISSUE TITLE
api.SVGFECompositeElement.in - Name doesn't match with Web IDL

### ISSUE THREAD

**Issue by saschanaz** [mdn/browser-compat-data#9337]
#### What information was incorrect, unhelpful, or incomplete?

`api.SVGFECompositeElement.in1` is renamed to `api.SVGFECompositeElement.in` and this no longer matches IDL attribute name defined by [the spec](https://drafts.fxtf.org/filter-effects/#InterfaceSVGFECompositeElement):

```webidl
interface SVGFECompositeElement : SVGElement {
  /* ... */
  readonly attribute SVGAnimatedString in1;
  readonly attribute SVGAnimatedString in2;
  /* ... */
};
```

#### What did you expect to see?

It should match the IDL name?

#### Did you test this? If so, how?

`"in1" in SVGFECompositeElement.prototype`

#### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://github.com/mdn/browser-compat-data/pull/9074#pullrequestreview-596091879

**Comment by ddbeck** [comment]
Ugh, I misread the spec. But in my defense, it's very unfriendly that the interface uses a different name for the attribute than the element. 🙄

Opened #9343
