### ISSUE TITLE
min-height: fill-available is already supported in Chrome

### ISSUE THREAD

**Issue by Akronix** [mdn/browser-compat-data#934]
The value [fill-available for min-height](https://developer.mozilla.org/en-US/docs/Web/CSS/min-height) is already supported in Google Chrome using `-webkit-fill-available`. As well as it's in Opera.
However, it isn't reflected in the [corresponding compat table](https://developer.mozilla.org/en-US/docs/Web/CSS/min-height#Browser_compatibility).

**Comment by Elchi3** [comment]
Thanks for this issue, the data is stored here https://github.com/mdn/browser-compat-data/blob/master/css/properties/min-height.json#L102 I will happily review a pull request that adds this information.
