### ISSUE TITLE
http.headers.Clear-Site-Data - <Unrecognized type: *.>

### ISSUE THREAD

**Issue by catsalt** [mdn/browser-compat-data#9340]
Dear masters, there is one question, when I use the clear-site-data to clean up data:

Rsponse Header:
Clear-Site-Data: cache
Clear-Site-Data: *
Content-Length: 3
Content-Type: text/plain; charset=UTF-8
Date: Fri, 05 Mar 2021 06:18:50 GMT

but in the console of Chrome, shows:

Clear-Site-Data header on 'http://localhost:9999/logout': Unrecognized type: cache.
login.html:1 Clear-Site-Data header on 'http://localhost:9999/logout': Unrecognized type: *.
login.html:1 Clear-Site-Data header on 'http://localhost:9999/logout': No recognized types specified.

Dears, is there any way to resolve that?

**Comment by vinyldarkscratch** [comment]
While this repository isn't meant for Q&A regarding web development assistance, I took a quick look and think I have an answer for you.  Looking at the MDN web docs page for this, it states:

> All directives must comply with the quoted-string grammar. A directive that does not include the double quotes is invalid.

In other words, if you wrap your values in quotes (`Clear-Site-Data: "*"`), that should fix the issue.
