### ISSUE TITLE
Add `SameParty` attribute to compatibility table on Set-Cookie page

### ISSUE THREAD

**Issue by summercms** [mdn/browser-compat-data#9375]
Joined to this issue: https://github.com/mdn/content/issues/2907

MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie

What information was incorrect, unhelpful, or incomplete?
Missing content.

Specific section or headline?
Add information about the new SameParty attribute.

What did you expect to see?
I've merged all the information on the web about this new attribute, you can find here:
https://github.com/ayumi-cloud/sc-security-module/blob/master/docs/cookie_first_party_sets.md

Did you test this? If so, how?
No, testing needed. Just need to add info about this new attribute to the page and also update the Browser compatibility table. Google Chrome has added it in v89 see here: https://www.chromestatus.com/feature/5280634094223360

**Comment by ddbeck** [comment]
Thanks for opening this issue, @ayumi-cloud.

This appears to be a feature that's available only as an origin trial in Chrome only. At Google's request, we don't track features which are only available in origin trials. Feel free to open a new issue (or ask to reopen this one), should this feature become available by default (in any browser). In the meantime, I'll close this. Thank you again!
