### ISSUE TITLE
api.Navigator.share - Chrome Support since v89

### ISSUE THREAD

**Issue by araareon** [mdn/browser-compat-data#9396]
#### What information was incorrect, unhelpful, or incomplete?
Chrome does support the function since V89

#### What did you expect to see?
Updated the table

#### Did you test this? If so, how?
see https://chromestatus.com/features#milestone%3D89

<details>
<summary>MDN page report details</summary>

* Query: `api.Navigator.share`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share
* Report started: 2021-03-09T07:10:32.664Z

</details>

**Comment by lucalves** [comment]
Hello @araareon, how are you? 

I opened PR #9444 which corrects this. Let's wait for the @mdn team to review!
