### ISSUE TITLE
html.elements.iframe - link to Firefox ticket for new "loading" attribute missing

### ISSUE THREAD

**Issue by scheinercc** [mdn/browser-compat-data#9416]
#### What information was incorrect, unhelpful, or incomplete?
Bug https://bugzilla.mozilla.org/show_bug.cgi?id=1622090 can be added to "Browser compatibility > Firefox > loading"

#### What did you expect to see?
Checking the table for "Browser compatibility > Firefox > loading" I expected to see a little star next to the "No" as per Safari.

<details>
<summary>MDN page report details</summary>

* Query: `html.elements.iframe`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe
* Report started: 2021-03-10T06:01:17.370Z

</details>

**Comment by ddbeck** [comment]
Thanks for reporting this, @scheinercc. I've opened https://github.com/mdn/browser-compat-data/pull/9496 to fix.
