### ISSUE TITLE
javascript.operators - Row "Trailing comma in parameters" is listed twice

### ISSUE THREAD

**Issue by thomasd** [mdn/browser-compat-data#9417]
#### What information was incorrect, unhelpful, or incomplete?
Row "Trailing comma in parameters" is listed twice with different compatibilities for Opera and iOS Safari.

#### What did you expect to see?
Only one row with correct compatibilities.

#### Did you test this? If so, how?

<details>
<summary>MDN page report details</summary>

* Query: `javascript.operators`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators
* Report started: 2021-03-10T07:58:29.682Z

</details>

**Comment by ddbeck** [comment]
@thomasd Thanks for reporting this. It uncovered some significant issues. You're right that it appears as if there are duplicate features. Unfortunately, there's a couple compounding problems here.

In this case, there are two features involved: trailing commas for `function` and `function*` (generator functions). It's more obvious on their respective pages: [function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/function) and [function*](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/function*). That said, it was challenging to figure this out—even for a regular contributor to the data—so I ended up making some substantial changes with #9592.

As a follow up to that, I opened #9594 to fix the discrepancies you noticed. It was possible, though unlikely, that Safari supported trailing commas in one function type but not another. Testing confirmed that this was not the case.

As a secondary issue, the tables rendered on MDN should be more explicit about subfeatures. I've opened https://github.com/mdn/yari/issues/3321 to request that subfeatures have some sort of indication.

Once #9592 and #9594 are merged, then we can close this issue. Thanks!
