### ISSUE TITLE
UserTiming Level 3

### ISSUE THREAD

**Issue by jakub-g** [mdn/browser-compat-data#9419]
Affected pages:

https://developer.mozilla.org/en-US/docs/Web/API/Performance/mark
https://developer.mozilla.org/en-US/docs/Web/API/Performance/measure

Description:

Since Chrome 78 (and soon Safari 14.1), those APIs use UT L3, which means, they 1) return a value, and 2) `mark` accepts `startTime`. Those should be added as sub-features in the data table I think.

Linked MDN content issue for content update: https://github.com/mdn/content/issues/3001

**Comment by ddbeck** [comment]
Thanks for reporting this, @jakub-g. Skimming over the spec, I agree it sounds like new subfeatures would be desirable. I'd welcome a PR from you (or another contributor) to add this data.

To confirm, it looks like the main changes to make here would be:

- a new subfeature to `api.Performance.mark`, perhaps named `returns_performance_mark` with a description such as `"Returns a <code>PerformanceEntry</code> object"`
- a similar new `returns_performance_mark` subfeature to `api.Performance.measure`
- a new subfeature to `api.Performance.mark`, perhaps named `startTime_option` with a description such as `"<code>startTime</code> option"`

And, of course, the data filled out for each. Borrowing from the linked content issue, here are some useful links for filling in the data:

- [Supported in Chrome 78](https://www.chromestatus.com/feature/5149401886490624)
- [Supported soon in Safari](https://webkit.org/blog/11333/release-notes-for-safari-technology-preview-115/)
- [Unsupported in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1581705)
