### ISSUE TITLE
api.FormData.get - Not supported in Safari 11.0, Supported in Safari 11.1

### ISSUE THREAD

**Issue by DhruvM7** [mdn/browser-compat-data#9425]
#### What information was incorrect, unhelpful, or incomplete?
FormData.get's Browser Compatibility table says `get` is supported since Safari 11. However it's not supported in Safari 11.0, it's only supported from Safari 11.1.

#### What did you expect to see?
Supported Safari version should say 11.1, not 11.

#### Did you test this? If so, how?
Not tested myself. However digging into Safari/Webkit version history explains it:

1. Safari 11.0 released on September 19, 2017 and is based on Webkit 604.2.4 
2. Safari 11.1 released on March 29, 2018 and is based on 605.1.33 (As per [wikipedia](https://en.wikipedia.org/wiki/Safari_version_history#Safari_11))
3. .get() was added to Webkit by [commit 221839](https://trac.webkit.org/changeset/221839/webkit/trunk/Source/WebCore/html/DOMFormData.cpp) only on Sept 10, 2017.
4. Webkit 604.2.4 was created/tagged on [Aug 17, 2017](https://trac.webkit.org/search?q=604.2.4&noquickjump=1&changeset=on&wiki=on) and Webkit 605.1.33 on [Feb 28, 2018](https://trac.webkit.org/search?q=605.1.33&noquickjump=1&changeset=on&wiki=on)

Hence get() would not be available in Webkit 604.2.4 and Safari 11.0.

<details>
<summary>MDN page report details</summary>

* Query: `api.FormData.get`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/FormData/get
* Report started: 2021-03-11T08:18:37.498Z

</details>

**Comment by ddbeck** [comment]
Thanks for reporting this, @DhruvM7. I confirmed your explanation—you're right. I'd welcome a PR (from you or another contributor) updating the data in [`FormData.json`](https://github.com/ddbeck/browser-compat-data/blob/3b36fbeef0199f4582e98ca3210ea5b601307425/api/FormData.json#L393-L440). Thank you again!
