### ISSUE TITLE
Issue with "Blob.text()" - Opera is supporting blob.text()

### ISSUE THREAD

**Issue by T410** [mdn/browser-compat-data#9469]
#### What information was incorrect, unhelpful, or incomplete?
In here https://github.com/mdn/browser-compat-data/blob/master/api/Blob.json it shows that Opera is not supporting `Blob.text()`
#### What did you expect to see?
I expected it to see that Opera is supporting this method
#### Did you test this? If so, how?
I have tested this code block in Opera's developer console and it works.

```
const blob = new Blob([JSON.stringify({hello: "world"}, null, 2)], {type : 'application/json'});
const text = await blob.text();
```
#### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?
https://developer.mozilla.org/en-US/docs/Web/API/Blob/text
https://developer.mozilla.org/en-US/docs/Web/API/Blob

**Comment by lucalves** [comment]
I opened PR #9622 to resolve this.
