### ISSUE TITLE
api.Element.scroll_event iOS Safari version is unknown

### ISSUE THREAD

**Issue by aquaductape** [mdn/browser-compat-data#9474]
#### What information was incorrect, unhelpful, or incomplete?
The iOS Safari version value is set to "unknown".

#### What did you expect to see?
At minimum the iOS Safari version should be at 12.4.7

#### Did you test this? If so, how?
I only tested on two iOS Safari versions 12.4.7 and 14.3 on this [codepen demo](https://codepen.io/Kahlub/pen/zYoMpmy) and the Element scroll event works.

<details>
<summary>MDN page report details</summary>

* Query: `api.Element.scroll_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/scroll_event
* Report started: 2021-03-15T19:40:01.358Z

</details>

**Comment by ddbeck** [comment]
Thanks for reporting this issue, @aquaductape, and providing an excellent test case.

As far back as I can test with BrowserStack (to Safari 4), this was supported. Circumstantially, it appears that this event was implemented a long time ago, [circa 2004](https://github.com/WebKit/WebKit/commit/b533f41a30b65ae7727faa00c288c9162b719c36). This is consistent with [the data we have for `onscroll`](https://github.com/mdn/browser-compat-data/blob/44f3b7e5d1bb4e1c971f4858ae34baf21d78f4c0/api/GlobalEventHandlers.json#L3895-L3900), which says this appeared in Safari 1.3 and Safari for iOS 1 (which @vinyldarkscratch seems to have had tested in https://github.com/mdn/browser-compat-data/pull/8580).

I would welcome a PR (from you or another contributor) that updates the Safari data for `scroll_event` to those version numbers. You can find the relevant data here: https://github.com/mdn/browser-compat-data/blob/44f3b7e5d1bb4e1c971f4858ae34baf21d78f4c0/api/Element.json#L7081-L7129

Thank you again!

**Comment by jculver050** [comment]
Close

**Comment by jculver050** [comment]
Close
