### ISSUE TITLE
http.headers.Feature-Policy.accelerometer - Suggested experimental flag doesn't seem to exist in Chrome 89

### ISSUE THREAD

**Issue by Hueburtsonly** [mdn/browser-compat-data#9499]
Chrome Linux 89.0.4389.90 and Chrome Android 89.0.4389.90

#### What information was incorrect, unhelpful, or incomplete?

Regarding Chrome Android compatibility, it says "From version 69: this feature is behind the #enable-experimental-productivity-features preferences (needs to be set to Enabled). To change preferences in Chrome Android, visit chrome://flags." Similar info is provided for desktop Chrome. However, there is no such #enable-experimental-productivity-features flag in either Chrome Desktop or Chrome Android.

#### What did you expect to see?

As above, information that would enable me to turn on this feature OR an indication that it's not available in Chrome 89 (and if so, what should be used instead).

#### Did you test this? If so, how?

By navigating to chrome://flags and trying to find the flags.

<details>
<summary>MDN page report details</summary>

* Query: `http.headers.Feature-Policy.accelerometer`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy/accelerometer
* Report started: 2021-03-18T05:33:24.235Z

</details>

**Comment by ddbeck** [comment]
Thanks for reporting this, @Hueburtsonly. This lead to me uncovering several troublesome issues with flags and Feature Policy data. I've opened https://github.com/mdn/browser-compat-data/pull/9707 to fix. Thank you again!
