### ISSUE TITLE
webextensions.api.browserAction.setBadgeText - Missing information about parameter 'windowId'

### ISSUE THREAD

**Issue by arielgee** [mdn/browser-compat-data#9503]
#### What information was incorrect, unhelpful, or incomplete?
Missing information about parameter 'windowId'

#### What did you expect to see?
Which Firefox version support the function parameter 'windowId'.
For example, there is NO support for parameter 'windowId' in Firefox version 59.

#### Did you test this? If so, how?
Tested with a web extension on version 59 and 86.

In 59 the following error was generated:
`Error: Type error for parameter details (Unexpected property "windowId") for browserAction.setBadgeText.`

<details>
<summary>MDN page report details</summary>

* Query: `webextensions.api.browserAction.setBadgeText`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserAction/setBadgeText
* Report started: 2021-03-18T11:15:38.981Z

</details>

**Comment by ddbeck** [comment]
Thanks for reporting this issue, @arielgee.

The data for the `setBadgeText` feature is here: https://github.com/mdn/browser-compat-data/blob/d61696555037f2a20020fea925c665d10e0f7d4c/webextensions/api/browserAction.json#L610

To fix this, I'd suggest that we add a subfeature covering support for the `windowId` property. But before that happens, here would be the next steps:

- If possible, share minimal sample code that would test this feature.
- Test this in different versions of Firefox, to find which version introduced support for this property. (For this part, we have access to browser testing tools. If there's a test case to use, then we could get the relevant version numbers quickly.)

**Comment by jculver050** [comment]
Close

**Comment by vinyldarkscratch** [comment]
This data is actually present in BCD already -- see #2586 which added it in.

**Comment by ddbeck** [comment]
Good catch, @vinyldarkscratch.

I think the reason we're not seeing in the table is because the feature is wrapped in a `detail` (non-compat) object. Either the depth of the macro call on that page needs to be extended or (my preference), we could unwrap the `windowId` feature, then add a description like `"<code>details.windowId</code> argument"`.
