### ISSUE TITLE
api.Response.headers - works in safari 13.1.2 even tho it's claimed it doesn't

### ISSUE THREAD

**Issue by danieltroger** [mdn/browser-compat-data#9512]
#### What information was incorrect, unhelpful, or incomplete?
Here: https://developer.mozilla.org/en-US/docs/Web/API/Response/headers

It says that Response.headers doesn't work at all in safari

#### What did you expect to see?
Correct data

#### Did you test this? If so, how?
Opened up safari and pasted in a fetch request generated by right clicking a request in the network pane in firefox debugger and selecting "copy as fetch".

`Object?.fromEntries?.(stock_response?.headers?.entries?.())` and it worked. If this page was correct it wouldn't.

<details>
<summary>MDN page report details</summary>

* Query: `api.Response.headers`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Response/headers
* Report started: 2021-03-19T10:11:20.112Z

</details>

**Comment by ddbeck** [comment]
Thanks for reporting this, @danieltroger. I confirmed your report and opened #10122 to update the data.
