### ISSUE TITLE
"Feature Policy" has been renamed "Permissions Policy"

### ISSUE THREAD

**Issue by jpmedley** [mdn/browser-compat-data#9556]
https://github.com/mdn/browser-compat-data/blob/master/http/headers/feature-policy.json

- File and feature name will need to be renamed.
- Name change history will need to be captured.

**Comment by ddbeck** [comment]
Spec: https://w3c.github.io/webappsec-permissions-policy/

**Comment by ddbeck** [comment]
I searched for features matching the (case-insensitive) regex `.*feature.*policy.*` in either the feature's dotted path or description. The following features are likely to be impacted by this (probably with renames and `alternative_name` support entries):

```
api.Document.featurePolicy
api.FeaturePolicy
api.FeaturePolicy.allowedFeatures
api.FeaturePolicy.allowsFeature
api.FeaturePolicy.features
api.FeaturePolicy.getAllowlistForFeature
api.HTMLIFrameElement.featurePolicy
http.headers.Feature-Policy
http.headers.Feature-Policy.accelerometer
http.headers.Feature-Policy.ambient-light-sensor
http.headers.Feature-Policy.autoplay
http.headers.Feature-Policy.battery
http.headers.Feature-Policy.camera
http.headers.Feature-Policy.display-capture
http.headers.Feature-Policy.document-domain
http.headers.Feature-Policy.encrypted-media
http.headers.Feature-Policy.fullscreen
http.headers.Feature-Policy.geolocation
http.headers.Feature-Policy.gyroscope
http.headers.Feature-Policy.layout-animations
http.headers.Feature-Policy.legacy-image-formats
http.headers.Feature-Policy.magnetometer
http.headers.Feature-Policy.microphone
http.headers.Feature-Policy.midi
http.headers.Feature-Policy.oversized-images
http.headers.Feature-Policy.payment
http.headers.Feature-Policy.picture-in-picture
http.headers.Feature-Policy.publickey-credentials-get
http.headers.Feature-Policy.sync-xhr
http.headers.Feature-Policy.unoptimized-images
http.headers.Feature-Policy.unsized-media
http.headers.Feature-Policy.usb
http.headers.Feature-Policy.vibrate
http.headers.Feature-Policy.vr
http.headers.Feature-Policy.wake-lock
http.headers.Feature-Policy.web-share
http.headers.Feature-Policy.xr-spatial-tracking
```

**Comment by jpmedley** [comment]
Chrome has not changed the name of the APIs. I don't know if we're planning to, but I'm looking into it.

**Comment by ddbeck** [comment]
Thanks. [The spec does rename the APIs](https://w3c.github.io/webappsec-permissions-policy/#idl-index) and it'd be nice if the spec and API could be in agreement, one way or another.

**Comment by jpmedley** [comment]
I just talked to the spec author, Ian Clelland, who said this:

>I'm working on a transition plan for that interface, but it won't be a straight rename. Most of the API is completely unused, and I think that the remaining parts may be melded into the Permissions API instead. There's no timeline for this yet, though. We will definitely keep you (and chromestatus) up to date with plans as they solidify.

**Comment by jpmedley** [comment]
He pinged me again just now to say that he'll be updating the spec soon .
