### ISSUE TITLE
api.Window.storage_event - Safari supports storage event

### ISSUE THREAD

**Issue by kodyli** [mdn/browser-compat-data#9558]
#### What information was incorrect, unhelpful, or incomplete?
Safari supports storage event, but not sure from which version.
#### What did you expect to see?
version number
#### Did you test this? If so, how?
No

<details>
<summary>MDN page report details</summary>

* Query: `api.Window.storage_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/storage_event
* Report started: 2021-03-22T17:25:15.856Z

</details>

**Comment by ddbeck** [comment]
Thanks for reporting this, @kodyli. I opened #10183 to resolve this.
