### ISSUE TITLE
api.Window.orientation - Doesn't work on Safari on iOS

### ISSUE THREAD

**Issue by lucypoly** [mdn/browser-compat-data#9569]
Safari iOS 13.1.3 - e.g. iPhone 8 Plus

api.Window.orientation is not indicating landscape or portrait

<details>
<summary>MDN page report details</summary>

* Query: `api.Window.orientation`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/orientation
* Report started: 2021-03-23T08:31:47.316Z

</details>

**Comment by ddbeck** [comment]
Hi @lucypoly and thanks for reporting this issue.

Can you provide any additional details about this (mis)behavior? [A test run on iOS](https://mdn-bcd-collector.appspot.com/tests/api/Window/orientation) shows that `window.orientation` exists, but if you found that it returns something unexpected, then we may need to add a note describing the behavior. If you have any sample code or console logs that might illustrate the problem, that would be especially appreciated.

Thank you again!

**Comment by queengooborg** [comment]
I'm closing this issue because no response has been given and there is not enough actionable information.  If this is still an issue, please reply to this thread with the requested information, and I'll be happy to reopen this!
