### ISSUE TITLE
api.Response.redirected - Update Safari compatibility

### ISSUE THREAD

**Issue by dasa** [mdn/browser-compat-data#9595]
#### What information was incorrect, unhelpful, or incomplete?

The compatibility table says No support for Safari.

#### What did you expect to see?

The version of Safari when support began.

#### Did you test this? If so, how?

`(new Response()).redirected` return `false` in Safari 14.0

<details>
<summary>MDN page report details</summary>

* Query: `api.Response.redirected`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Response/redirected
* Report started: 2021-03-24T21:15:58.657Z

</details>

**Comment by ddbeck** [comment]
Thanks for reporting this. I've opened #10184 to fix it.
