### ISSUE TITLE
Add compat data for Animation interface

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#961]
MDN pages to migrate:

- [x] [Web/API/Animation](https://developer.mozilla.org/en-US/docs/Web/API/Animation)
- [x] [Web/API/Animation/Animation](https://developer.mozilla.org/en-US/docs/Web/API/Animation/Animation)
- [x] [Web/API/Animation/cancel](https://developer.mozilla.org/en-US/docs/Web/API/Animation/cancel)
- [x] [Web/API/Animation/currentTime](https://developer.mozilla.org/en-US/docs/Web/API/Animation/currentTime)
- [x] [Web/API/Animation/effect](https://developer.mozilla.org/en-US/docs/Web/API/Animation/effect)
- [x] [Web/API/Animation/finish](https://developer.mozilla.org/en-US/docs/Web/API/Animation/finish)
- [x] [Web/API/Animation/finished](https://developer.mozilla.org/en-US/docs/Web/API/Animation/finished)
- [x] [Web/API/Animation/id](https://developer.mozilla.org/en-US/docs/Web/API/Animation/id)
- [x] [Web/API/Animation/oncancel](https://developer.mozilla.org/en-US/docs/Web/API/Animation/oncancel)
- [x] [Web/API/Animation/onfish](https://developer.mozilla.org/en-US/docs/Web/API/Animation/onfinish)
- [x] [Web/API/Animation/pause](https://developer.mozilla.org/en-US/docs/Web/API/Animation/pause)
- [x] [Web/API/Animation/pending](https://developer.mozilla.org/en-US/docs/Web/API/Animation/pending)
- [x] [Web/API/Animation/play](https://developer.mozilla.org/en-US/docs/Web/API/Animation/play)
- [x] [Web/API/Animation/playbackRate](https://developer.mozilla.org/en-US/docs/Web/API/Animation/playbackRate)
- [x] [Web/API/Animation/playState](https://developer.mozilla.org/en-US/docs/Web/API/Animation/playState)
- [x] [Web/API/Animation/ready](https://developer.mozilla.org/en-US/docs/Web/API/Animation/ready)
- [x] [Web/API/Animation/reverse](https://developer.mozilla.org/en-US/docs/Web/API/Animation/reverse)
- [x] [Web/API/Animation/startTime](https://developer.mozilla.org/en-US/docs/Web/API/Animation/startTime)
- [x] [Web/API/Animation/timeline](https://developer.mozilla.org/en-US/docs/Web/API/Animation/timeline)

The data should be migrated into the file `api/Animation.json`.

For more information on how to help with this work, see https://developer.mozilla.org/en-US/docs/MDN/Contribute/Structures/Compatibility_tables

**Comment by CalmBit** [comment]
If you wouldn't mind, I can take a crack at this 😄

**Comment by CalmBit** [comment]
PR #975 should do it!
