### ISSUE TITLE
api.Window.print - <doesn't work in Chrome>

### ISSUE THREAD

**Issue by jcbernard33** [mdn/browser-compat-data#9631]
#### Did you test this? If so, how?

<details>
<summary>MDN page report details</summary>

* Query: `api.Window.print`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/print
* Report started: 2021-03-26T19:10:53.628Z

</details>

**Comment by ddbeck** [comment]
I'm closing this issue because it appears to be empty. The issue template is incomplete and no actionable information has been provided.

If this has been closed in error, edit the title and body, and post a follow-up comment.
