### ISSUE TITLE
javascript.builtins.Function - <PUT TITLE HERE>

### ISSUE THREAD

**Issue by JulieBf69** [mdn/browser-compat-data#9632]
`<!--` Tips: where applicable, specify browser name, browser version, and mobile operating system version -->

#### Did you test this? If so, how?

<details>
<summary>MDN page report details</summary>

* Query: `javascript.builtins.Function`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function
* Report started: 2021-03-26T20:46:37.965Z

</details>

**Comment by lucalves** [comment]
Hello @JulieBf69, your Issue was created without information about the problem. Can you write what's wrong with that page?
