### ISSUE TITLE
css.properties.overflow-x - clip value is now supported in Chrome 90

### ISSUE THREAD

**Issue by raphaelsaunier** [mdn/browser-compat-data#9635]
#### What information was incorrect, unhelpful, or incomplete?

the `clip` value for `overflow(-x|-y)` properties is now supported in Chrome. c.f. https://www.chromestatus.com/feature/5638444178997248

#### What did you expect to see?

A green box indicating that the value is supported in Chrome 90+

#### Did you test this? If so, how?

By setting an `overflow-x: clip` value on a relatively positioned div with an absolutely positioned child element that overflows the parent div.

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.overflow-x`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-x
* Report started: 2021-03-27T15:03:47.578Z

</details>

**Comment by ddbeck** [comment]
Thanks for reporting this, @raphaelsaunier. You're right, we need to reconcile the `clip` subfeature data for `overflow`, `overflow-x`, and `overflow-y`. Thanks to the details you provided, this was quick to fix and https://github.com/mdn/browser-compat-data/pull/10281 is now open to resolve this.

**Comment by jculver050** [comment]
Close
