### ISSUE TITLE
Add compat data for BatteryManager

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#968]
MDN pages to migrate:

- [x] [Web/API/BatteryManager](https://developer.mozilla.org/en-US/docs/Web/API/BatteryManager)
- [x] [Web/API/BatteryManager/charging](https://developer.mozilla.org/en-US/docs/Web/API/BatteryManager/charging)
- [x] [Web/API/BatteryManager/chargingTime](https://developer.mozilla.org/en-US/docs/Web/API/BatteryManager/chargingTime)
- [x] [Web/API/BatteryManager/dischargingTime](https://developer.mozilla.org/en-US/docs/Web/API/BatteryManager/dischargingTime)
- [x] [Web/API/BatteryManager/level](https://developer.mozilla.org/en-US/docs/Web/API/BatteryManager/level)
- [x] [Web/API/BatteryManager/onchargingchange](https://developer.mozilla.org/en-US/docs/Web/API/BatteryManager/onchargingchange)
- [x] [Web/API/BatteryManager/onchargingtimechange](https://developer.mozilla.org/en-US/docs/Web/API/BatteryManager/onchargingtimechange)
- [x] [Web/API/BatteryManager/ondischargingtimechange](https://developer.mozilla.org/en-US/docs/Web/API/BatteryManager/ondischargingtimechange)
- [x] [Web/API/BatteryManager/onlevelchange](https://developer.mozilla.org/en-US/docs/Web/API/BatteryManager/onlevelchange)

The data should be migrated into the file `api/BatteryManager.json`.

For more information on how to help with this work, see https://developer.mozilla.org/en-US/docs/MDN/Contribute/Structures/Compatibility_tables

**Comment by gsouquet** [comment]
I'll take care of this one if no one has claimed it already 👍

**Comment by Elchi3** [comment]
Got done in https://github.com/mdn/browser-compat-data/pull/1102. Will likely be deployed later today.
