### ISSUE TITLE
Add compat data for Blob

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#969]
MDN pages to migrate:

- [ ] [Web/API/Blob](https://developer.mozilla.org/en-US/docs/Web/API/Blob)
- [ ] [Web/API/Blob/Blob](https://developer.mozilla.org/en-US/docs/Web/API/Blob/Blob)
- [ ] [Web/API/Blob/size](https://developer.mozilla.org/en-US/docs/Web/API/Blob/size)
- [ ] [Web/API/Blob/type](https://developer.mozilla.org/en-US/docs/Web/API/Blob/type)
- [ ] [Web/API/Blob/slice](https://developer.mozilla.org/en-US/docs/Web/API/Blob/slice)

The data should be migrated into the file `api/Blob.json`.

For more information on how to help with this work, see https://developer.mozilla.org/en-US/docs/MDN/Contribute/Structures/Compatibility_tables

**Comment by CalmBit** [comment]
Gonna go for gold and tackle this one too, if no one minds!

**Comment by CalmBit** [comment]
So `Blob` seems to be a little problematic...

The compatibility table suggests a mobile Firefox version of `13`, but the linter complains that `13` isn't a valid value for that field.

Additionally, it doesn't seem to like me using arrays instead of objects for compatibility entries with multiple versions, e.g. 
```json
"chrome": [
              {
                "version_added": 21
              },
              {
                "version_added": "5",
                "prefix": "webkit",
                "notes": "<snip>"
              }
            ]
```
This should be valid, according to the compatibility tables document - maybe I'm reading it wrong?

**Comment by Elchi3** [comment]
Some original tables get this wrong for Firefox for Android which never saw the versions 11-13. You can find the valid versions here: https://github.com/mdn/browser-compat-data/blob/master/browsers/firefox_android.json#L40 and there should be an error message containing the valid support versions as well. 

Firefox for Android version 13 in the original table should be version 14 in the data.

**Comment by CalmBit** [comment]
Alrighty, thank you! It'll be done very soon!

**Comment by CalmBit** [comment]
PR #988 should do the trick 😀
