### ISSUE TITLE
Add compat data for BlobEvent

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#970]
MDN pages to migrate:

- [x] [Web/API/BlobEvent](https://developer.mozilla.org/en-US/docs/Web/API/BlobEvent)
- [x] [Web/API/BlobEvent/BlobEvent](https://developer.mozilla.org/en-US/docs/Web/API/BlobEvent/BlobEvent)
- [x] [Web/API/BlobEvent/data](https://developer.mozilla.org/en-US/docs/Web/API/BlobEvent/data)
- [x] [Web/API/BlobEvent/timecode](https://developer.mozilla.org/en-US/docs/Web/API/BlobEvent/timecode)

The data should be migrated into the file `api/BlobEvent.json`.

For more information on how to help with this work, see https://developer.mozilla.org/en-US/docs/MDN/Contribute/Structures/Compatibility_tables

**Comment by CalmBit** [comment]
I'm hoping I'm not seen as greedy, but I'll definitely take this one if no one minds!

**Comment by CalmBit** [comment]
PR #1033 should take care of it :smile:
