### ISSUE TITLE
javascript.statements.async_function - <PUT TITLE HERE>

### ISSUE THREAD

**Issue by Bruna17** [mdn/browser-compat-data#9705]
> `

<details>
<summary>Details</summary>

</details>

#### Did you test this? If so, how?

<details>
<summary>MDN page report details</summary>

* Query: `javascript.statements.async_function`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function
* Report started: 2021-04-01T09:28:56.558Z

</details>

**Comment by ddbeck** [comment]
I'm closing this issue because it appears to be empty. The issue template is incomplete and no actionable information has been provided.

If this has been closed in error, edit the title and body, and post a follow-up comment.
