### ISSUE TITLE
Add compat data for BroadcastChannel

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#971]
MDN pages to migrate:
- [ ] [Web/API/BroadcastChannel](https://developer.mozilla.org/en-US/docs/Web/API/BroadcastChannel)
- [ ] [Web/API/BroadcastChannel/BroadcastChannel](https://developer.mozilla.org/en-US/docs/Web/API/BroadcastChannel/BroadcastChannel)
- [ ] [Web/API/BroadcastChannel/name](https://developer.mozilla.org/en-US/docs/Web/API/BroadcastChannel/name)
- [ ] [Web/API/BroadcastChannel/onmessage](https://developer.mozilla.org/en-US/docs/Web/API/BroadcastChannel/onmessage)
- [ ] [Web/API/BroadcastChannel/onmessageerror](https://developer.mozilla.org/en-US/docs/Web/API/BroadcastChannel/onmessageerror)
- [ ] [Web/API/BroadcastChannel/close](https://developer.mozilla.org/en-US/docs/Web/API/BroadcastChannel/close)
- [ ] [Web/API/BroadcastChannel/postMessage](https://developer.mozilla.org/en-US/docs/Web/API/BroadcastChannel/postMessage)

The data should be migrated into the file `api/BroadcastChannel.json`.

For more information on how to help with this work, see https://developer.mozilla.org/en-US/docs/MDN/Contribute/Structures/Compatibility_tables

**Comment by gsouquet** [comment]
Hi, I'll give it a go if no one has already claimed this issue.

**Comment by Elchi3** [comment]
No one has claimed this yet, please go ahead! :)
