### ISSUE TITLE
javascript.classes.static - Static methods show as unsupported for Safari

### ISSUE THREAD

**Issue by AaronAsAChimp** [mdn/browser-compat-data#9710]
#### What information was incorrect, unhelpful, or incomplete?
The browser compatibility table shows that static is not supported by Safari.

#### What did you expect to see?
Safari, since at least version 12 according to the [kangax tables](http://kangax.github.io/compat-table/es6/#test-class_static_methods), supports static methods. Having separate entries in the table for static methods and static properties would resolve this.

#### Did you test this? If so, how?
I ran the JavaScript Demo in Safari 14.0.3. After removing the static property, I get the expected result of "static method has been called."

<details>
<summary>MDN page report details</summary>

* Query: `javascript.classes.static`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/static
* Report started: 2021-04-01T13:44:46.031Z

</details>

**Comment by jculver050** [comment]
Close

**Comment by vinyldarkscratch** [comment]
This was updated in #10129!
