### ISSUE TITLE
Add compat data for BudgetService and BudgetState

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#972]
MDN pages to migrate:

- [ ] [Web/API/BudgetService](https://developer.mozilla.org/en-US/docs/Web/API/BudgetService)
- [ ] [Web/API/BudgetService/getBudget](https://developer.mozilla.org/en-US/docs/Web/API/BudgetService/getBudget)
- [ ] [Web/API/BudgetService/getCost](https://developer.mozilla.org/en-US/docs/Web/API/BudgetService/getCost)
- [ ] [Web/API/BudgetService/reserve](https://developer.mozilla.org/en-US/docs/Web/API/BudgetService/reserve)
- [ ] [Web/API/BudgetState](https://developer.mozilla.org/en-US/docs/Web/API/BudgetState)
- [ ] [Web/API/BudgetState/budgetAt](https://developer.mozilla.org/en-US/docs/Web/API/BudgetState/budgetAt)
- [ ] [Web/API/BudgetState/time](https://developer.mozilla.org/en-US/docs/Web/API/BudgetState/time)

The data should be migrated into the files `api/BudgetService.json` and `api/BudgetState.json`.

For more information on how to help with this work, see https://developer.mozilla.org/en-US/docs/MDN/Contribute/Structures/Compatibility_tables

**Comment by gsouquet** [comment]
Will work on this one if no one has done it already
