### ISSUE TITLE
http.headers.Content-Type - can i get a content type for android?

### ISSUE THREAD

**Issue by chunyin0103** [mdn/browser-compat-data#9760]
#### Did you test this? If so, how?

<details>
<summary>MDN page report details</summary>

* Query: `http.headers.Content-Type`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type
* Report started: 2021-04-05T06:04:09.125Z

</details>

**Comment by vinyldarkscratch** [comment]
I'm not sure what you're trying to ask, but this repository isn't a development help forum -- this is for the browser compatibility table.  If you're seeking development assistance, I would suggest something like StackOverflow.
