### ISSUE TITLE
api.Clipboard.writeText - <大部分手机浏览器不支持复制功能>

### ISSUE THREAD

**Issue by koiluo** [mdn/browser-compat-data#9762]
#### Did you test this? If so, how?

<details>
<summary>MDN page report details</summary>

* Query: `api.Clipboard.writeText`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/API/Clipboard/writeText
* Report started: 2021-04-05T11:02:49.135Z
大部分手机浏览器不支持复制功能
</details>

**Comment by koiluo** [comment]
大部分手机浏览器不支持复制功能

**Comment by vinyldarkscratch** [comment]
Closing this issue as the "copy" function isn't a thing, and the `write` and `writeText` functions _are_ supported in mobile browsers.
