### ISSUE TITLE
Add compat data for Cache

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#977]
MDN pages to migrate:

- [ ] [Web/API/Cache](https://developer.mozilla.org/en-US/docs/Web/API/Cache)
- [ ] [Web/API/Cache/add](https://developer.mozilla.org/en-US/docs/Web/API/Cache/add)
- [ ] [Web/API/Cache/addAll](https://developer.mozilla.org/en-US/docs/Web/API/Cache/addAll)
- [ ] [Web/API/Cache/delete](https://developer.mozilla.org/en-US/docs/Web/API/Cache/delete)
- [ ] [Web/API/Cache/keys](https://developer.mozilla.org/en-US/docs/Web/API/Cache/keys)
- [ ] [Web/API/Cache/match](https://developer.mozilla.org/en-US/docs/Web/API/Cache/match)
- [ ] [Web/API/Cache/matchAll](https://developer.mozilla.org/en-US/docs/Web/API/Cache/matchAll)
- [ ] [Web/API/Cache/put](https://developer.mozilla.org/en-US/docs/Web/API/Cache/put)

The data should be migrated into the file `api/Cache.json`.

For more information on how to help with this work, see https://developer.mozilla.org/en-US/docs/MDN/Contribute/Structures/Compatibility_tables

**Comment by gsouquet** [comment]
I'll be doing this one ☝️

**Comment by gsouquet** [comment]
It looks like there's a lot of conflicting data in the current documentation

The browser compatibility does not match between in the two following pages: 

* https://developer.mozilla.org/en-US/docs/Web/API/Cache
* https://developer.mozilla.org/en-US/docs/Web/API/Cache/delete

What should I consider as the main source of truth in these scenarios?

Thanks
