### ISSUE TITLE
Add compat data for CacheStorage

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#978]
MDN pages to migrate:

- [ ] [Web/API/CacheStorage](https://developer.mozilla.org/en-US/docs/Web/API/CacheStorage)
- [ ] [Web/API/CacheStorage/delete](https://developer.mozilla.org/en-US/docs/Web/API/CacheStorage/delete)
- [ ] [Web/API/CacheStorage/has](https://developer.mozilla.org/en-US/docs/Web/API/CacheStorage/has)
- [ ] [Web/API/CacheStorage/keys](https://developer.mozilla.org/en-US/docs/Web/API/CacheStorage/keys)
- [ ] [Web/API/CacheStorage/match](https://developer.mozilla.org/en-US/docs/Web/API/CacheStorage/match)
- [ ] [Web/API/CacheStorage/open](https://developer.mozilla.org/en-US/docs/Web/API/CacheStorage/open)

The data should be migrated into the file `api/CacheStorage.json`.

For more information on how to help with this work, see https://developer.mozilla.org/en-US/docs/MDN/Contribute/Structures/Compatibility_tables

**Comment by gsouquet** [comment]
I'll be working on this one
