### ISSUE TITLE
http.status.404 - <error in notes, unable to access>

### ISSUE THREAD

**Issue by clare-github-1** [mdn/browser-compat-data#9785]
I clicked on the notes link from the edx app, and error 404 came out in safari - can’t see the notes. I’m on an iPad air4 at IOS 14.4.2

<details>
<summary>MDN page report details</summary>

* Query: `http.status.404`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404
* Report started: 2021-04-06T10:58:16.897Z

</details>

**Comment by vinyldarkscratch** [comment]
Closing as I cannot determine the relevance to BCD.
