### ISSUE TITLE
api.RTCRtpReceiver.getCapabilities - doesn't work in FF

### ISSUE THREAD

**Issue by B-R-Bender** [mdn/browser-compat-data#9786]
FF 87.0 (64-bit) for Ubuntu

RTCRtpReceiver.getCapabilities doesn't work in FF
complaining with 

> TypeError: RTCRtpReceiver.getCapabilities is not a function

while it's stated 
![image](https://user-images.githubusercontent.com/16334107/113721086-e0f25b00-96f7-11eb-9b03-0af884df5d76.png)

To reproduce just open dev tools -> console -> `RTCRtpReceiver.getCapabilities("video");`

<details>
<summary>MDN page report details</summary>

* Query: `api.RTCRtpReceiver.getCapabilities`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/RTCRtpReceiver/getCapabilities
* Report started: 2021-04-06T12:09:56.987Z

</details>

**Comment by ddbeck** [comment]
Thanks for reporting this, @B-R-Bender. This is definitely not implemented in Firefox.

Source: https://github.com/mdn/browser-compat-data/blob/main/api/RTCRtpReceiver.json#L98-L146
Collector test (fails): https://mdn-bcd-collector.appspot.com/tests/api/RTCRtpReceiver/getCapabilities
Bug (open): https://bugzilla.mozilla.org/show_bug.cgi?id=1179084

I'd welcome a PR (from you or another contributor) setting the Firefox and Firefox for Android values `false` in [`RTCRtpReceiver.json`](https://github.com/mdn/browser-compat-data/blob/main/api/RTCRtpReceiver.json#L98-L146).

Thank you again!
