### ISSUE TITLE
api.Blob.text - Supported in Safari at least 14+

### ISSUE THREAD

**Issue by IceCreamYou** [mdn/browser-compat-data#9791]
OS: macOS 10.15.7
Browser: Safari 14.0.3

#### What information was incorrect, unhelpful, or incomplete?

I was looking at the browser compat section on the [MDN page for `Blob.text()`](https://developer.mozilla.org/en-US/docs/Web/API/Blob/text#browser_compatibility) and observed that it says Safari does not support that method. I thought that was unfortunate, so I tried it for myself to make sure. Turns out, at least the Safari version I tried does support `Blob.text()`:

![image](https://user-images.githubusercontent.com/203177/113830917-ec677580-973b-11eb-9301-53397755d907.png)

I also tried a much more complicated example involving `File` objects generated from an `<input type="file" multiple webkitdirectory />` and it worked there too.

#### What did you expect to see?

Browser compat information indicating that at least Safari 14+ supports `Blob.text()`.

#### Did you test this? If so, how?

Yes, see above.

<details>
<summary>MDN page report details</summary>

* Query: `api.Blob.text`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Blob/text
* Report started: 2021-04-07T07:38:42.073Z

</details>

**Comment by ddbeck** [comment]
Thanks for reporting this, @IceCreamYou. This was fixed a few weeks ago with https://github.com/mdn/browser-compat-data/pull/10129/.
