### ISSUE TITLE
javascript.builtins.WeakRef - works on Safari

### ISSUE THREAD

**Issue by TheSpyder** [mdn/browser-compat-data#9794]
#### What information was incorrect, unhelpful, or incomplete?

WeakRef states that Safari has no support. This is not true, it was merged in June 2019: https://bugs.webkit.org/show_bug.cgi?id=198710

It is likely Opera, which is also listed as no support, now has full support ([they're up to Chromium 89](https://blogs.opera.com/desktop/changelog-for-75/)).

#### What did you expect to see?

Full support listed under Safari as of version 14

#### Did you test this? If so, how?

At the console, running Safari 14.1 (16611.1.21.161.1):
> typeof WeakRef
< "function"
> typeof WeakRef.prototype.deref
< "function"

I have no way to test whether this was true in Safari 14 at release, but given it was merged in 2019 I am fairly confident it would be. It may even be true in Safari 13, as that was released 3 months after the merge in September 2019.

<details>
<summary>MDN page report details</summary>

* Query: `javascript.builtins.WeakRef`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakRef
* Report started: 2021-04-07T20:08:43.871Z

</details>

**Comment by jculver050** [comment]
Close

**Comment by jculver050** [comment]
Close

**Comment by vinyldarkscratch** [comment]
This has been resolved by #10129!
