### ISSUE TITLE
Cache control does not work in browser that taken from Android devices (not in list)

### ISSUE THREAD

**Issue by MrAlexanderWs** [mdn/browser-compat-data#9801]
I read the documentary about cache-control. However, not all Android browser support. (Browser is taken from Android itself, not any browser listed in documentary). My device is OPPO, and when I try to click back button on Android, after a student finishing a test, the answer can be manipulated by clicking back, the student are not using Google Chrome in Android

```
header("Cache-Control: no-store, no-cache, must-revalidate, max-age=0");
header("Cache-Control: post-check=0, pre-check=0", false);
header("Expires: 0 ");
header("Pragma: no-cache");
```

Note this code is used to disable back button. I tried in several browser platforms, this is worked. And I tried in my device using Google Chrome worked. However, some browser taken from Android devices won't work.

**Comment by vinyldarkscratch** [comment]
Can you specify which Android browsers aren't supporting this feature?

**Comment by MrAlexanderWs** [comment]
My device using OPPO Reno 3, and using browser from Android itself

**Comment by MrAlexanderWs** [comment]
I use this method, it works in PC web browsers. And even android browsers which listed in this link. The project is Codeigniter. It won't work on Android browsers which is taken from Android itself (not Google Chrome app). Even I using this, it won't work for back button for browsing in Android.

![malfunction](https://user-images.githubusercontent.com/46021397/114128674-17fa8380-9927-11eb-837c-5127ab94ad92.png)

**Comment by vinyldarkscratch** [comment]
When you say "taken from Android itself", are you talking about WebView?  Since around Android Jelly Bean, Android hasn't really had its "own browser", as even WebView is based upon Chrome (though with a number of APIs disabled).

Could you send your browser's useragent string, please?  That might help shed some light on what's going on.

**Comment by jculver050** [comment]
Close

**Comment by queengooborg** [comment]
I'm closing this issue because there hasn't been any response and there's not enough actionable information to proceed.  If this is still an issue, please feel free to reply to this thread and I'll be happy to reopen this!
