### ISSUE TITLE
api.Navigator.share - Edge + MacOS. It is not supported

### ISSUE THREAD

**Issue by rmaclean-ee** [mdn/browser-compat-data#9813]
#### What information was incorrect, unhelpful, or incomplete?

This API is listed as supported by Edge, but it is not supported on MacOS.

#### What did you expect to see?

Same as Chrome, a partial support with a link to the same bug

<details>
<summary>MDN page report details</summary>

* Query: `api.Navigator.share`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share
* Report started: 2021-04-09T14:22:24.245Z

</details>

**Comment by jculver050** [comment]
Close

**Comment by vinyldarkscratch** [comment]
Looks like this is a duplicate of #6817.
