### ISSUE TITLE
api.OffscreenCanvas - No information regarding WebGPU context

### ISSUE THREAD

**Issue by lwansbrough** [mdn/browser-compat-data#9815]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas

#### What information was incorrect, unhelpful, or incomplete?
No browser compatibility row is provided for `gpupresent` (offscreen webgpu capability)

#### Specific section or headline?
Browser compatibility

#### What did you expect to see?
`gpupresent context`

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/offscreencanvas`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/offscreencanvas/index.html
* Last commit: https://github.com/mdn/content/commit/f6f11d2a249520f01bad93d7c4a5e5cdf6ed914a
* Document last modified: 2021-02-19T19:33:30.000Z

</details>

**Comment by ddbeck** [comment]
Thanks for reporting this, @lwansbrough.

The feature data for this would probably go into this file, https://github.com/mdn/browser-compat-data/blob/main/api/OffscreenCanvas.json#L200-L504, as a subfeature of the `getContext` feature.

Unfortunately, I don't know much about this feature. It's unclear to me which browsers may have implemented this feature or what expectations to have about testing it.

As a next step, it would be helpful to get links to bugs related to the implementation of this feature, or a minimal test case which could confirm support in different browsers, or both. I'd welcome a follow up from you or another contributor with more information, so we can substantiate and fill out this data.

Thanks again!

**Comment by queengooborg** [comment]
It took me a bit to dig into this, but it appears that `gpupresent` was the former name of the `webgpu` context -- see https://github.com/gpuweb/gpuweb/issues/131 and https://github.com/gpuweb/gpuweb/pull/1930/files.  It looks like we don't have data for `webgpu` either, so we'll need to add that in.
