### ISSUE TITLE
javascript.builtins.String.at - <PUT TITLE HERE>

### ISSUE THREAD

**Issue by Mohammad-W-Momani** [mdn/browser-compat-data#9818]
#### What information was incorrect, unhelpful, or incomplete?
Uncaught TypeError: sentence.at is not a function
    at <anonymous>:1:10

#### What did you expect to see?
const sentence = 'The quick brown fox jumps over the lazy dog.';
sentence.at(index)  // "."
#### Did you test this? If so, how?
In google dev tool

<details>
<summary>MDN page report details</summary>

* Query: `javascript.builtins.String.at`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/at
* Report started: 2021-04-11T01:03:05.000Z

</details>

**Comment by vinyldarkscratch** [comment]
This is expected -- currently, our data states that no browser supports this function.
