### ISSUE TITLE
css.properties.backdrop-filter: Supported in Opera

### ISSUE THREAD

**Issue by jeremie-j** [mdn/browser-compat-data#9825]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/backdrop-filter

#### What information was incorrect, unhelpful, or incomplete?
The backdrop-filter is now available on opera

#### Specific section or headline?
Browser compatibility section

#### What did you expect to see?
/

#### Did you test this? If so, how?
I downloaded Opera to test the property

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/backdrop-filter`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/backdrop-filter
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/backdrop-filter/index.html
* Last commit: https://github.com/mdn/content/commit/f4fb4c2d90a134366c280eec6cb599825981ad5d
* Document last modified: 2021-03-15T17:55:56.000Z

</details>

**Comment by ddbeck** [comment]
Thanks for reporting this, @jeremie-j. I expect this will be resolved by https://github.com/mdn/browser-compat-data/pull/9812.

**Comment by foolip** [comment]
Fixed by https://github.com/mdn/browser-compat-data/pull/9812.
