### ISSUE TITLE
Remove xslt feature/directory from the repo (the data for which is mostly null)

### ISSUE THREAD

**Issue by sideshowbarker** [mdn/browser-compat-data#9826]
For reasons similar to #9589, the data (or lack of data…) in the `xslt` directory doesn’t seem to merit continuing to have its own top-level directory in BCD.

As with the `xpath` directory, there is only one actual standard XSLT feature for which we have data in that directory. The rest of the features in there are for non-standard EXSLT stuff.

And in both cases the bulk of the `xslt` data is `null` values, and nobody seems to care — certainly nobody cares enough to do the work of replacing it with actual data.

So if we are going to the trouble of removing the `xpath` directory, it would seem prudent to also remove the `xslt` directory.

**Comment by ddbeck** [comment]
I agree with this too, though there's a few more pages that would be impacted than with XPath. I think we should drop the data, but hold it until there are other breaking changes to make. See #9830 for details.
