### ISSUE TITLE
javascript.classes.private_class_fields - Rename and build out

### ISSUE THREAD

**Issue by meyerweb** [mdn/browser-compat-data#9833]
Currently, the only information about private class features (see https://github.com/tc39/proposal-private-methods#private-methods-and-fields) is a single row of data labeled `private_class_fields`.  I propose to replace it with `private_class_features` and give a row each to fields and methods, in both static and instance variants.  So the structure would be:

```
javascript
   classes
      private_class_features
         _compat
         instance_fields
         instance_methods
         static_fields
         static_methods
```

I would also handle converting any MDN documentation referencing `private_class_fields` to instead refer to `private_class_features`.  My current assumption is that the actual update process would be:

1. Add the above `private_class_features` structure to the BCD in a PR
1. Update MDN pages to point to it
1. Remove the `private_class_fields` structure from the BCD in a second PR

I’m opening this issue to invite discussion of the proposal, so any adjustments can be made ahead of submitting actual pull requests.

**Comment by jculver050** [comment]
Close

**Comment by hamishwillee** [comment]
Why? Is it because you expect private features to continue to be extended, and to deliver across many specs, an many different browser releases?

Note, #10854 is currently modifying this because the private features appear in FF90, so if we're going to, a good time to think about touching this.

**Comment by meyerweb** [comment]
Because different aspects of private class features have been added to browsers at different times (e.g. Chrome, which added private fields in 74 and private methods in 84).  The distinction between static and instance seems to be important 
to JS documentation and its readers, so I preserved it here.

I don’t know if there will be feature extensions or not.

**Comment by ddbeck** [comment]
Just saw this thanks to https://github.com/mdn/browser-compat-data/pull/10854. Since private class fields and methods were introduced separately in more than one browser, it definitely makes sense to have features for each. How to actually structure this is a bit tougher.

My inclination is to flatten everything:

```
javascript
   classes
      private_instance_fields
      private_instance_methods
      private_static_fields
      private_static_methods
```

or, with some more depth:

```
javascript
   classes
      private_fields*
        instance_fields
        static_fields
      private_methods*
        instance_methods
        static_methods
```

\* we'd have to do something tricky here, like `partial_implementation` for support for only one of the subfeatures being supported

The main thing I want to avoid here is the ambiguity created by the proposed `private_class_features`, which, given our schema, would only be able to mean "support for one or more of private class/instance fields/methods, but we won't tell you which one unless you actually read all of the subfeatures".

**Comment by meyerweb** [comment]
A question: which structure is better for MDN pages that need to pull in BCD data to construct compatibility tables for private class features?  There is currently one such page, with at least one more to come.  Is there a practical difference?

**Comment by hamishwillee** [comment]
> The distinction between static and instance seems to be important to JS documentation and its readers, so I preserved it here.

@ddbeck Note the comment ^^^. It is important for docs, but does this matter for BCD? (IMO only matters if it is not clear that the keys cover both static and instance). Devil's advocate, if it causes no harm, I don't mind either way.

**Comment by meyerweb** [comment]
Starting to wonder if it should be flattened like so:

```
javascript
   classes
      private_fields
      private_methods
```

My only concern is how to pull that information in for files that want to refer to both.  Then again, maybe the way to go is:

```
javascript
   classes
      fields
         public_fields
         public_methods
         private_fields
         private_methods
```

That way, any article about fields (public or private) can bring in everything, and if it has to get split up by static and instance variants later, there’s a single umbrella to hold everything.  What do you think?

**Comment by hamishwillee** [comment]
Hmm. Something else to throw in (as a question).  

For FF90 we add support to do an "ergonomic brand check for private class fields: (essentially allows you do use `in` operator to test for a private class field having a defined value, rather than having to wrap checks in `try`/`catch`. So this is a subfeature that applies to private fields (for info, see https://github.com/mdn/content/issues/5380). 

How do we add these to BCD? Right now I'd probably add as a peer
```
javascript
   classes
      private_class_features
      private_field_in
```
But this discussion allows other options. Thoughts?

**Comment by meyerweb** [comment]
Oh boy.

Does an ergonomic brand check apply only to property-like fields, or can it also apply to method-like fields?

**Comment by hamishwillee** [comment]
@meyerweb Stop asking questions which I don't know the answer with 100% certainty :-). The bug report specifically refers to properties though, and I think we have to assume for this discussion that these are separate and might be addressed separately.

**Comment by meyerweb** [comment]
See https://github.com/mdn/browser-compat-data/pull/11042.

**Comment by hamishwillee** [comment]
Thanks @meyerweb - that looks great. We'll have to see what Daniel says about the spec url. Possibly we just don't support that yet.

FYI only, yes the "in" test also works on methods.

**Comment by meyerweb** [comment]
> FYI only, yes the "in" test also works on methods.

Do you have a recommendation for a better description of it?  I thought about `private_class_in` or even just `in` but both felt like they didn’t conform to the rest of the labeling.

**Comment by meyerweb** [comment]
Pull request https://github.com/mdn/browser-compat-data/pull/11042 was merged this morning, so I think it’s safe to close this issue.  Thanks to everyone for input and assistance!

**Comment by hamishwillee** [comment]
@meyerweb Yes, this is good. Thanks very much. Re the description, a lot of these are a bit "opaque". I think "in" is much better than "ergonomic private class checks" :-)
