### ISSUE TITLE
http.headers.Referrer-Policy - Update Referrer-Policy conformity for Safari on iOS

### ISSUE THREAD

**Issue by matthiaswenz** [mdn/browser-compat-data#9846]
#### What information was incorrect, unhelpful, or incomplete?
Referrer-Policy support matrix lists Safari on iOS to not support `Referrer-Policy` header and its respective values.

#### What did you expect to see?
Actual results should be according to test protocol linked below:
- Safari on iOS (14.4.2 tested as latest release) understands and respects all specified `Referrer-Policy` header values according to the specification
- Safari on iOS does not default to `strict-origin-when-cross-origin` but rather `no-referrer-when-downgrade`

#### Did you test this? If so, how?
Tested using a local site and remote device Web Inspector, see details and test protocol here: https://gist.github.com/matthiaswenz/033f40b1b3c50029d2ba260f3ee43204

<details>
<summary>MDN page report details</summary>

* Query: `http.headers.Referrer-Policy`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy
* Report started: 2021-04-13T03:53:19.241Z

</details>

**Comment by queengooborg** [comment]
Looks like this was fixed by #15089!
