### ISSUE TITLE
api.Permissions - Firefox doesn't support "camera" permission

### ISSUE THREAD

**Issue by amitpanigrahi** [mdn/browser-compat-data#9855]
#### What information was incorrect, unhelpful, or incomplete?
`await navigator.permissions.query({ name: "camera" })`
`await navigator.permissions.query({ name: "microphone" })`

returning 
`Uncaught (in promise) TypeError: 'camera' (value of 'name' member of PermissionDescriptor) is not a valid value for enumeration PermissionName.`

on Firefox
Version 	88.0b9
Build ID 	20210408190318

#### What did you expect to see?
Should return a PermissionStatus object instance with below values.

```
{
    onchange: null
    state: "prompt/granted/denied"
}
```

#### Did you test this? If so, how?
`await navigator.permissions.query({ name: "camera" })`
`await navigator.permissions.query({ name: "microphone" })`
tested on google chrome console, and its working properly

<details>
<summary>MDN page report details</summary>

* Query: `api.Permissions.query`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Permissions/query
* Report started: 2021-04-14T10:26:48.657Z

</details>

**Comment by ddbeck** [comment]
Thanks for reporting this, @amitpanigrahi.

The data for the specific permission names supported by a browser, including `"camera"`, are listed in [`Permissions.json`](https://github.com/mdn/browser-compat-data/blob/ac3746fc06d39f888f5e7c7eae39d56d63d24d82/api/Permissions.json#L244-L291) ([as rendered on MDN](https://developer.mozilla.org/en-US/docs/Web/API/Permissions#browser_support)). Currently, the data reports no data for the camera permission in Firefox.

I'd welcome a PR from you (or another contributor) setting that value to `false` for Firefox and Firefox for Android.
