### ISSUE TITLE
html.elements.input.input-range - Safari desktop has tick mark support

### ISSUE THREAD

**Issue by edprats** [mdn/browser-compat-data#9867]
#### What information was incorrect, unhelpful, or incomplete?
The browser compatability chart currently shows Safari does not support tick marks, however tested on Safari 14.0.3, it currently does work.

#### What did you expect to see?
Expected no support (aka not to see tick marks), however the tick marks are displayed.

#### Did you test this? If so, how?
Used the sample html and opened it in the current latest Safari (14.0) and viewed it on my desktop.

<details>
<summary>MDN page report details</summary>

* Query: `html.elements.input.input-range`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range
* Report started: 2021-04-14T16:39:20.277Z

</details>

**Comment by NerdyDeedsLLC** [comment]
Clarification: Safari has PARTIAL tickmark support. Labels still are omitted, and Don't appear to transform with the corresponding `<input>` tag. 

...But @edprats is correct insofar as they DO show up now.

**Comment by mfranzke** [comment]
> Clarification: Safari has PARTIAL tickmark support. Labels still are omitted, and Don't appear to transform with the corresponding `<input>` tag.
> 
> ...But @edprats is correct insofar as they DO show up now.
> ![image](https://user-images.githubusercontent.com/43561032/117557574-d0583c00-b039-11eb-95a9-8205e47a3c4b.png)

Same for iOS 14 (tested with 14.7.1):
![A71DDC74-2002-49BC-9378-0BF1FF3999FD](https://user-images.githubusercontent.com/787658/127260675-ce8cd3fd-f5c1-4a5b-8d6c-6280f1e64388.png)
