### ISSUE TITLE
javascript.builtins.WebAssembly.compileStreaming - supported on Safari TP

### ISSUE THREAD

**Issue by typedrat** [mdn/browser-compat-data#9876]
#### What information was incorrect, unhelpful, or incomplete?

The page does not report that the compileStreaming API is supported in [the newest versions of Safari TP](https://developer.apple.com/safari/technology-preview/release-notes/) (TP 121 and newer).

This also effects the information for other recently added WASM features in TP, including `instantiateStreaming`.

#### What did you expect to see?

Correct information about the support for this API in Safari TP.

#### Did you test this? If so, how?

I have run code which requires the compileStreaming on the current Safari TP and it works correctly.

<details>
<summary>MDN page report details</summary>

* Query: `javascript.builtins.WebAssembly.compileStreaming`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/compileStreaming
* Report started: 2021-04-15T16:48:04.346Z

</details>

**Comment by jculver050** [comment]
Close

**Comment by queengooborg** [comment]
Looks like this was fixed in #10898!
