### ISSUE TITLE
http.headers.link - Not supported in Chrome (and missing table)

### ISSUE THREAD

**Issue by FrankyGolang** [mdn/browser-compat-data#9890]
Look this link ==> https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Link

I think this header no have support.

![image](https://user-images.githubusercontent.com/69035383/114906302-2f9ba580-9e1a-11eb-9fac-1c49ba4108ab.png)

**Comment by vinyldarkscratch** [comment]
It appears BCD isn't tracking data for this particular header, so we'll have to get it added in.

**Comment by Francisco-AM** [comment]
I've been doing a lot of testing in local development, it's a positive header, but still lacks implementation in browsers. I hope that preconect works correctly because I have not been able to test the dns.

**Comment by NiedziolkaMichal** [comment]
On firefox, this header works at least since version 85. I have tested it with `preload` type and that's the version preload was added to the link element too, so probably this header is older. On Link header with `preload` type works on version 11.1, while it doesn't work on 10.1.
