### ISSUE TITLE
OverconstrainedError event - is this the event?

### ISSUE THREAD

**Issue by hamishwillee** [mdn/browser-compat-data#9907]
MDN has docs for [OverconstrainedError](https://developer.mozilla.org/en-US/docs/Web/API/OverconstrainedError), with BCD: 
https://github.com/mdn/browser-compat-data/blob/main/api/OverconstrainedError.json - 

BCD further has [OverconstrainedErrorEvent](https://github.com/mdn/browser-compat-data/blob/main/api/OverconstrainedErrorEvent.json). However 
- this is all pretty much null
-  I can't find any docs for this in mdn
- it doesn't sound from the spec that this is a separate event.
- It is all a bit confusing because the MDN docs above read like OverconstrainedError is an event (not exception) and it is also listed in https://developer.mozilla.org/en-US/docs/Web/API/Event#introduction

My "guess" is that OverconstrainedErrorEvent was originally something proposed that never happened. If correct maybe delete the BCD entry and tidy the doc on MDN to make it clear this is an exception?

**Comment by ddbeck** [comment]
`OverconstrainedErrorEvent` is an interface exposed in Safari (I don't know about any others—stopped looking at this point). It looks like both exist, though the Event interface is non-standard.

https://bugs.webkit.org/show_bug.cgi?id=161199
https://trac.webkit.org/changeset/205024/webkit
