### ISSUE TITLE
Remove Web IDL typedefs

### ISSUE THREAD

**Issue by foolip** [mdn/browser-compat-data#9930]
BCD has some data for Web IDL [typedefs](https://heycam.github.io/webidl/#idl-typedefs), namely `ConstrainBoolean`, `ConstrainDOMString`, `ConstrainDouble`, `ConstrainULong` and `DOMHighResTimestamp`.

Typedefs in Web IDL are aliases of other types which are invisible to web developers. `DOMHighResTimestamp` when converted to JavaScript is a Number, but one that has a certain interpretation.

Because typedefs are aliases, they have no compat story of their own separately from the APIs that use the typedefs. In this way they are similar to dictionaries, but even more trivial.

This came up in https://github.com/mdn/browser-compat-data/pull/9892.

**Comment by foolip** [comment]
Also worth noting is that MDN documents [`ConstrainBoolean`](https://developer.mozilla.org/en-US/docs/Web/API/ConstrainBoolean) as a dictionary, but its [spec definition](https://w3c.github.io/mediacapture-main/#dom-constrainboolean) is:
```webidl
typedef (DOMString or
         sequence<DOMString> or
         ConstrainDOMStringParameters) ConstrainDOMString;
```

**Comment by saschanaz** [comment]
Also #6810.

**Comment by queengooborg** [comment]
We've now gotten rid of all the typedefs in BCD that we know of!  I'm going to close this issue -- let's track any future typedefs we may find in #6810.
