### ISSUE TITLE
::-webkit-scrollbar - iOS removed support in 14+

### ISSUE THREAD

**Issue by sarahbethfederman** [mdn/browser-compat-data#9967]
Apparently all support for custom scrollbars has been removed from iOS 14+? https://developer.apple.com/forums/thread/670065

<details>
<summary>MDN page report details</summary>

* Query: `css.selectors.-webkit-scrollbar-button`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar
* Report started: 2021-04-19T12:56:58.810Z

</details>

**Comment by GrimLink** [comment]
I can confirm that does not work anymore on iOS Safari 14+ anymore 😢
Made an PR to update this change.
