### ISSUE TITLE
api.Document.exitPointerLock - not supported on Safari for iOS

### ISSUE THREAD

**Issue by python273** [mdn/browser-compat-data#9994]
#### What information was incorrect, unhelpful, or incomplete?

doesn't look like `document.exitPointerLock` is supported on Safari for iOS

#### Did you test this? If so, how?

```js
> navigator.userAgent
< "Mozilla/5.0 (iPhone; CPU iPhone OS 14_4_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Mobile/15E148 Safari/604.1"
> document.exitPointerLock
< undefined
```

<details>
<summary>MDN page report details</summary>

* Query: `api.Document.exitPointerLock`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document/exitPointerLock
* Report started: 2021-04-21T03:08:38.494Z

</details>

**Comment by queengooborg** [comment]
This was fixed by #18545!
